### ISSUE TITLE
[CI] Verify Linked Issue Action bot is noisy

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning#10013]
## 🐛 Bug
![image](https://user-images.githubusercontent.com/20610905/137860780-15a1e557-eed2-4f28-a520-6a4ae31f3e98.png)

the bot (verifying if pr contains issue number) is noisy as observed in #10012.

### To Reproduce
Submit a PR w/o any issue number.

### Expected behavior
Bot comments only one time.

### Additional context
#9575 tried to fix this but it seems it didn't?

cc: @Borda

**Comment by tchaton** [comment]
Hey @akihironitta,

We will implement an improved version of the bot after v1.5. The spam is still a good thing to avoid un-tracked work.

Best,
T.C

**Comment by akihironitta** [comment]
Closed in #11338.
