### ISSUE TITLE
self.trainer.training/testing/validating/predicting all are False

### ISSUE THREAD

**Issue by qmpzzpmq** [PyTorchLightning/pytorch-lightning#10062]
During the checking phase before the first training step, the all self.trainer.training/testing/validating/predicting status in Datamodule are Fasle.

**Comment by qmpzzpmq** [comment]
@rohitgr7 on_after_batch_transfer

**Comment by rohitgr7** [comment]
must be happening during sanity_check. for that it's `self.trainer.sanity_checking`. you can disable it using `Trainer(num_sanity_val_steps=0)` if you want.
