### ISSUE TITLE
`get_model_size_mb` (`LightningModule.model_size`) shouldn't create temporary files in the current directory

### ISSUE THREAD

**Issue by RuRo** [PyTorchLightning/pytorch-lightning#10074]
Currently, the [`get_model_size_mb` function](https://github.com/PyTorchLightning/pytorch-lightning/blob/c3614f1c07caf2c1519fcbe37140f2aeef7a8308/pytorch_lightning/utilities/memory.py#L165) is implemented like this:
```python
def get_model_size_mb(model: Module) -> float:
    """Calculates the size of a Module in megabytes by saving the model to a temporary file and reading its size.
    The computation includes everything in the :meth:`~torch.nn.Module.state_dict`,
    i.e., by default the parameteters and buffers.
    Returns:
        Number of megabytes in the parameters of the input module.
    """
    # TODO: Implement a method without needing to download the model
    tmp_name = f"{uuid.uuid4().hex}.pt"
    torch.save(model.state_dict(), tmp_name)
    size_mb = os.path.getsize(tmp_name) / 1e6
    os.remove(tmp_name)
    return size_mb
```

This writes the model to disk and also introduces a race condition where the temporary file may be left behind if the user "Ctrl+C"s the program while the `torch.save` and `os.path.getsize` calls are running. I originally found this bug by investigating, what was creating the mysterious `cb0e0c0d62ee4c20986c67462c1105d3.pt` files in my project directory.

You can achieve the same result without touching the disk by doing
```python
import io

target = io.BytesIO()
torch.save(model.state_dict(), target)
size_mb = target.getbuffer().nbytes / 1e6
```

**Comment by awaelchli** [comment]
@RuRo Thanks, this seems totally reasonable to me. Would you be interested in contributing this change?
