### ISSUE TITLE
Lazy loading and multi-modal data

### ISSUE THREAD

**Issue by shubhamagarwal92** [PyTorchLightning/pytorch-lightning#1011]
#### What is your question?

Hi, 

Really nice repo. I was planning to port my code here. But I want to ask a question about lazy loading.

- It seems that dataloader already has pre-built lazy loading. The decorator [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/core/decorators.py) mentions this will use the lazy property. However, it is not clear to me where the logic of lazy loading resides. 

Also, how do I enable it? 

- If I am working with multi-modal data, what would be the best practice to use lazy data loading and how do I use pl module. 

Currently, I have a dataset similar to [this](https://github.com/batra-mlp-lab/visdial-challenge-starter-pytorch/blob/master/visdialch/data/dataset.py#L16) which is called as dataloader [here](https://github.com/batra-mlp-lab/visdial-challenge-starter-pytorch/blob/master/train.py#L136). However, this is a bit slow. Should I maintain a similar structure?

Thanks.

**Comment by williamFalcon** [comment]
on master you no longer need lazy loading. we fixed the issues that required it. your data won’t be called until it’s actually needed

**Comment by williamFalcon** [comment]
i can loon at the rest of this issue later today :)

**Comment by Borda** [comment]
@shubhamagarwal92 is it this still actual after new release?
