### ISSUE TITLE
Update examples doc

### ISSUE THREAD

**Issue by rohitgr7** [PyTorchLightning/pytorch-lightning#10124]
## 📚 Documentation

A lot of links are outdated here. Anyone willing to contribute a PR to fix them?
https://pytorch-lightning.readthedocs.io/en/latest/ecosystem/community_examples.html

Here is the file you need to edit: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/docs/source/ecosystem/community_examples.rst

Thanks!

**Comment by bibhabasumohapatra** [comment]
https://github.com/PyTorchLightning/pytorch-lightning/pull/10127#issue-1034981823

**Comment by kaushikb11** [comment]
Resolved with #10127

**Comment by kaushikb11** [comment]
Resolved with #10127
