### ISSUE TITLE
trainer.num_nodes not set when running elastic multi-node training 

### ISSUE THREAD

**Issue by jovan-absci** [PyTorchLightning/pytorch-lightning#10180]
## 🐛 Bug
I'm using the TorchElastic Kubernetes Controller to run ElasticJobs on my cluster. I'm using Lightning in my code and set the trainer like so:
`trainer = pl.Trainer(gpus=-1, accelerator='ddp')`

The job creates two pods, each using 4 gpus. The generated command for each pod looks like this:

   ```
/opt/conda/bin/python -m torch.distributed.run --rdzv_backend=etcd --rdzv_endpoint=etcd0.elastic-job:2379 --rdzv_id=some-job-id --nnodes=1:2 --nproc_per_node=4 train_lightning.py
```

[The docs](https://pytorch-lightning.readthedocs.io/en/latest/advanced/multi_gpu.html#torch-distributed-elastic) lead me to believe that I do not need to set the num_nodes on the trainer instance. My workers successfully rendezvous. I can verify that trainer.world_size matches WORLD_SIZE from the environment and in the worker logs I can see they each get the appropriate rank. However, my code crashes:
```
File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 172, in reload_evaluation_dataloaders
    self.trainer.reset_val_dataloader(model)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 441, in reset_val_dataloader
    self.num_val_batches, self.val_dataloaders = self._reset_eval_dataloader(model, "val")
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 386, in _reset_eval_dataloader
    self.auto_add_sampler(dl, shuffle=False, mode=self.state.stage) for dl in dataloaders if dl is not None
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 386, in <listcomp>
    self.auto_add_sampler(dl, shuffle=False, mode=self.state.stage) for dl in dataloaders if dl is not None
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 142, in auto_add_sampler
    sampler = self._get_distributed_sampler(dataloader, shuffle, mode=mode)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 241, in _get_distributed_sampler
    sampler = cls(dataloader.dataset, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/distributed.py", line 73, in __init__
    " [0, {}]".format(rank, num_replicas - 1))
ValueError: Invalid rank 4, rank should be in the interval [0, 3]
```
Upon further inspection, it seems that the DistributedSampler uses dist.get_world_size() to define the rank interval, which reports the wrong world_size. When I explicitly pass num_nodes into the Trainer constructor, dist.get_world_size() reports correctly and my training continues. This is a problem however, as I cannot know the number of nodes at an arbitrary time due to elasticity.
trainer.num_nodes is not set correctly (stays at 1), and while most of the ddp mechanism does not rely on this, for some reason, it seems that the get_world_size() method does.

Am I missing something?

### Expected behavior

The workers successfully rendezvous and training starts without explicitly passing num_nodes to the trainer.

### Environment

* CUDA:
        - GPU:
        - available:         False
        - version:           11.1
* Packages:
        - numpy:             1.21.2
        - pyTorch_debug:     False
        - pyTorch_version:   1.9.1+cu111
        - pytorch-lightning: 1.4.9
        - tqdm:              4.62.3
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - 
        - processor:         x86_64
        - python:            3.7.11
        - version:           91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021

cc @awaelchli @rohitgr7

**Comment by jovan-absci** [comment]
Hi @awaelchli 
The prints report correct information: 
<pytorch_lightning.plugins.environments.torchelastic_environment.TorchElasticEnvironment object at 0x7fa14f7d8c90>
8

**Comment by ananthsub** [comment]
You should specify `num_nodes` on the Trainer constructor.

Note that Lightning does not support distributed elastic training, meaning your torchelastic launch configuration should use the same min/max. 

Here's the related issue and discussion for distributed elastic support. 

https://github.com/PyTorchLightning/pytorch-lightning/issues/9063

**Comment by jovan-absci** [comment]
[This answer](https://github.com/PyTorchLightning/pytorch-lightning/issues/9063#issuecomment-904207515) from that discussion and [the official docs](https://pytorch-lightning.readthedocs.io/en/stable/advanced/multi_gpu.html#torch-distributed-elastic) lead me to believe that it should work.
I do pass num_nodes manually, as we decided against using elastic scaling in the end. Nonetheless, the docs should be updated if this is indeed an unsupported feature.

**Comment by martinbensonIU** [comment]
It would be great for elastic functionality to be supported by Lightning,and I agree with @jovan-absci that the docs imply that it IS supported. Hopefully a fix for this can be prioritised.
