### ISSUE TITLE
Disable UserWarning for DataLoaders with num_workers=0

### ISSUE THREAD

**Issue by marcm-ml** [PyTorchLightning/pytorch-lightning#10182]
## Proposed refactoring or deprecation

Disable dataloader UserWarning for **num_workers=0** since 0 disables multi-process loading (according to pytorch docs it loads in the main process whereas 1 would create a separate process)

### Motivation

I understand the motivation behind utilising more processes for data loading but the warning should not appear if the user specifically requested to use the main process (by setting num_workers=0)

### Pitch

Change

https://github.com/PyTorchLightning/pytorch-lightning/blob/c33df2639f19d49c5e7520294e3221efe402d684/pytorch_lightning/trainer/data_loading.py#L109-L115

to

    elif 0 < dataloader.num_workers <= 2 < num_cpus and not using_spawn:
        rank_zero_warn( 
            f"The dataloader, {name}, does not have many workers which may be a bottleneck." 
            " Consider increasing the value of the `num_workers` argument`" 
            f" (try {num_cpus} which is the number of cpus on this machine)" 
            " in the `DataLoader` init to improve performance." 
        )

**Comment by GF-Huang** [comment]
So? I get this warning if I never set `num_workers`. If I set it, I will stuck at `trainer.fit` because I use vscode jupyter.

**Comment by carmocca** [comment]
@awaelchli Do you think we should check if we are under an interactive environment before showing this warning as the comment above suggests?

**Comment by GF-Huang** [comment]
Is this fixed by the latest release version?

**Comment by awaelchli** [comment]
@carmocca I see no reason why at the moment. num_workers>0 should work in notebooks, if that's what you mean.
