### ISSUE TITLE
Support Habanas' Gaudi Accelerator

### ISSUE THREAD

**Issue by SeanNaren** [PyTorchLightning/pytorch-lightning#10214]
## 🚀 Feature

Recently Intel's Habana Labs announced [AWS nodes for their Gaudi Accelerator](https://venturebeat.com/2021/10/26/amazon-launches-aws-instances-powered-by-habanas-ai-accelerator-chip/). As described in the [reddit post](https://www.reddit.com/r/MachineLearning/comments/qh95on/n_amazon_launches_aws_instances_powered_by/) there seems to be a lot of potential for model parallel solution that require fast interconnect between processors.

Looking at the pytorch [migration guide](https://docs.habana.ai/en/latest/Migration_Guide/Migration_Guide.html#porting-a-simple-pytorch-model-to-gaudi) there is room for lightning to assist in making this process seamless, helping users to not have to worry about this details (especially around the KCRS -> RSCK format for convolutions).

I suggest we introduce a new accelerator type such that we can enable this in lightning through the accelerator flag, i.e:

```python
trainer = Trainer(accelerator='hpu')
```
HPU is what the accelerator seems to be called within the migration guide.

cc @borda

**Comment by Borda** [comment]
just for the record: #12258 and #12200
