### ISSUE TITLE
ImportError: cannot import name 'r2score' from 'torchmetrics.functional' 

### ISSUE THREAD

**Issue by fcqfcq** [PyTorchLightning/pytorch-lightning#10233]
## 🐛 Bug
```
ImportError: cannot import name 'r2score' from 'torchmetrics.functional' (/***/python3.7/site-packages/torchmetrics/functional/__init__.py)
-->
```

- PyTorch Lightning Version (e.g., 1.4.9,1.4.8):
- PyTorch Version (e.g., 1.8)
- Python version:3.7.10
- OS (e.g., Linux): Ubuntu
- CUDA/cuDNN version:11.1
- GPU models and configuration: 
- How you installed PyTorch (`conda`, `pip`, source):  pip
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:
-torchmetrics (0.6.0)

**Comment by tann9949** [comment]
Is this issue resolved? I still face this problem when importing `pytorch_lightning.metrics.functional`

**Comment by akihironitta** [comment]
@fcqfcq @tann9949 Please have a look at https://github.com/PyTorchLightning/pytorch-lightning/discussions/10253.

**Comment by Fang-git0** [comment]
I seen  10253. However, I have the same problem and  it doesn't work as I changed "from pytorch_lightning.metrics.functional import f1_score" to "from torchmetrics import f1_score‘’

Error:
ImportError: cannot import name 'r2score' from 'torchmetrics.functional'

My version：
python==3.7
torch 1.8.0+cu111
torchmetrics 0.6.0
torchtext 0.9.0
pytorch-lightning 1.4.9

change version to torchmetrics==0.5.1
errors：
ImportError: cannot import name 'Batch' from 'torchtext.data'

change version to pytorch-lightning==1.3.8
error：ImportError: cannot import name 'f1_score' from 'pytorch_lightning.metrics.functional'
