### ISSUE TITLE
Empty list for gpus throws MisconfigurationException instead of running on CPU

### ISSUE THREAD

**Issue by victorjoos** [PyTorchLightning/pytorch-lightning#10245]
## 🐛 Bug

When setting gpus to an empty list, it throws a MisconfigurationException instead of just not using a gpu, as I would expect.

### To Reproduce

Run any model with `Trainer(gpus=[])`

### Expected behavior

runs on CPU instead of crashing

### Environment
N/A

### Additional context
N/A

**Comment by awaelchli** [comment]
I would argue this not be treated as a bug as we had an explicit test for the empty list be unsupported. I think treating this as an enhancement would be more fitting :) Just a remark. Anyway, thanks for the PR
