### ISSUE TITLE
Update init_ddp_connection logging info message and update function name

### ISSUE THREAD

**Issue by four4fish** [PyTorchLightning/pytorch-lightning#10256]
## Proposed refactoring or deprecation

init_ddp_connection is not only used by DDP, but also used by FSDP and other plugins inherit DDP. The log info and rank_zero_info saying ""initializing ddp" or "DDP processes", which could be confusing for user

### Motivation

Debuggability and readability 

### Pitch

Update info message to be generic message
Update function name to initialize_distributed_connction as it's used by fsdp and sdp

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by tchaton** [comment]
Good idea, let's do this
