### ISSUE TITLE
Rapid prototyping templates are outdated

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#10268]
## 📚 Documentation

The Rapid [prototyping templates page](https://pytorch-lightning.readthedocs.io/en/latest/starter/rapid_prototyping_templates.html) is highly outdated. There are only two examples and both of them use API from < PL 1.2. For example `Trainer(automatic_optimization=False)`. They are hosted in Colab and therefore we can't update them automatically. 

- Does this section belong into the side menu? 
- How do we update the Colab notebook?

cc @borda @rohitgr7

**Comment by rohitgr7** [comment]
we can update and add them to pl_examples/templates and link it with colab/github?
