### ISSUE TITLE
Pytorch SequentialLR  cannot be used

### ISSUE THREAD

**Issue by blefaudeux** [PyTorchLightning/pytorch-lightning#10278]
## 🐛 Bug
Using Pytorch's [SequentialLR](https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.SequentialLR.html?highlight=sequentiallr#torch.optim.lr_scheduler.SequentialLR) with Lightning leads to `AttributeError: 'SequentialLR' object has no attribute 'optimizer'` in `_validate_scheduler_optimizer` ([pytorch_lightning/trainer/optimizers.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/optimizers.py#L231)), which makes sense since SequentialLR [does not have a self.optimizer attribute indeed](https://pytorch.org/docs/stable/_modules/torch/optim/lr_scheduler.html#SequentialLR) (though on the user side this should not be visible and things should work)

cc @SeanNaren @tchaton, this would be a nice way to repro MinGPTs schedule (warmup then exp down)

### To Reproduce
Instantiate `torch.optim.lr_scheduler.SequentialLR`as your scheduler in Lightning 

### Expected behavior
Works flawlessly

### Environment
Pytorch 1.10

**Comment by rohitgr7** [comment]
hey @blefaudeux thanks for raising this. seems like we need to support `SequentialLR` explictly :)

**Comment by rohitgr7** [comment]
ok seems like it's fixed on pytorch master here: https://github.com/pytorch/pytorch/pull/67406
for `ChainedScheduler` added an issue here: https://github.com/pytorch/pytorch/issues/67601
