### ISSUE TITLE
Decouple "Convert to Lightning" from the Lite page

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning#10277]
## 📚 Documentation
I'd like to suggest extracting "Convert to Lightning" from the Lite page. https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html

I'm having a look at the Lite doc page again, and I found it a bit confusing that the doc page has both of the following parts in a single page:
- Pure PyTorch to Lightning Lite ([convert-to-lightninglite](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html#convert-to-lightninglite))
- Lightning Lite to Lightning ([convert-to-lightning](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html#convert-to-lightning))

I think existing pure PyTorch users (who are interested in migrating their code to Lite) will get distracted by "Lightning Lite to Lightning" part because they visit the page to see what Lite is capable of and how to use Lite, but not to migrate their Lite code to Lightning. Putting both of the sections in a single page attracts some visibility for Lightning, but it can also be distracting.

What do you think? cc @borda @carmocca @justusschock @awaelchli @aribornstein

**Comment by aribornstein** [comment]
I agree with you 100% i think we should split it up as this page is quite overwhelming. Lets a have a simple example of how to organize the code and what it gets you and then a second page explaining how it works and how far you can take it.

**Comment by aribornstein** [comment]
@tchaton STEPPING STONE TO LIGHTNING is also a bad title we should make it clear exactly what lite does and why it's a stepping stone. This asumes you already know lightning in which case you probably aren't going to be reading about lite

**Comment by rohitgr7** [comment]
I think it was added to shine some light on `Distributed Training Pitfalls` and how `LightningModule and Trainer` mitigate those issues. If someone is converting their code to `Lite`, we should show them it's not the ultimate tool and has its limitations, in case they want something better in a long run.

**Comment by tchaton** [comment]
As @rohitgr7 shared, this was meant to indicate to the first glance that Lite is not the end of the journey and contains lot of limitations.

**Comment by akihironitta** [comment]
@rohitgr7 @tchaton I see your point, but I'm still in favor of moving the section to a different page. Lite is already very new to PyTorch users, and mixing another new thing (=Lightning) there can be confusing. I think only mentioning that there are limitations in Lite and linking to another page explaining "Lite to Lightning" would suffice in that case IMHO, but the decision is yours.

**Comment by tchaton** [comment]
@awaelchli @carmocca what are your thoughts ?

**Comment by carmocca** [comment]
I generally agree with Akihiro

**Comment by akihironitta** [comment]
As discussed with @kaushikb11 via Slack, let's keep the page as is for the reason we want to push not only Lite but also Lightning to pure PyTorch users.

Thanks @kaushikb11 for start discussing this :)
