### ISSUE TITLE
IterableDataset with wrong length causes validation loop to be skipped.

### ISSUE THREAD

**Issue by jopo666** [PyTorchLightning/pytorch-lightning#10290]
## 🐛 Bug

When `IterableDataset` has a wrong length defined, specifically a higher than the actual number of iterations, the validation epoch is skipped.

### To Reproduce

```
import os

import torch
from torch.utils.data import DataLoader, IterableDataset, get_worker_info

from pytorch_lightning import LightningModule, Trainer


class RandomDataset(IterableDataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def sample_queue(self, indices):
        for index in indices:
            yield self.data[index]

    def __len__(self):
        return self.len * 2

    def __iter__(self):
        indices = list(range(len(self.data)))
        # Get worker info.
        worker_info = get_worker_info()
        if worker_info is None:
            # Only a single process, so it gets all the data.
            return self.sample_queue(indices)
        else:
            # Divide indices to workers.
            worker_indices = indices[worker_info.id::worker_info.num_workers]
            return self.sample_queue(worker_indices)


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    test_data = DataLoader(RandomDataset(32, 64), batch_size=2)

    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        max_epochs=2,
    )
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
    trainer.test(model, dataloaders=test_data)


if __name__ == "__main__":
    run()
```

### Expected behavior

Run validations loops even with the wrong length.

### Environment
```
Versions

Collecting environment information...
PyTorch version: 1.10.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.33

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.11.0-38-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla V100-PCIE-16GB
Nvidia driver version: 470.63.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.3
[pip3] pytorch-lightning==1.4.9
[pip3] torch==1.10.0+cu113
[pip3] torchmetrics==0.6.0
[pip3] torchvision==0.11.1+cu113
```

**Comment by awaelchli** [comment]
@jopo666 
The IterableDataset should leave the len undefined unless you actually make it so that it returns the correct value. 
For this reason, Lightning prints a warning if you do define one:

> /Users/adrian/repositories/pytorch-lightning/pytorch_lightning/utilities/data.py:87: UserWarning: Your `IterableDataset` has `__len__` defined. In combination with multi-process data loading (when num_workers > 1), `__len__` could be inaccurate if each worker is not configured independently to avoid having duplicate data.

Here is how we determine the number of batches in a dataloader: 
https://github.com/PyTorchLightning/pytorch-lightning/blob/e4ee6df196dd0c6b17d8c695bea3f1d286114f4f/pytorch_lightning/trainer/data_loading.py#L349

If a length is defined, we take that as the truth. If not, we assume the dataloader can stop at any point. This variable `trainer.num_training_batches` is then later on used in the loops do determine if we have reached the last batch. [If the last batch is reached, we run validation](https://github.com/PyTorchLightning/pytorch-lightning/blob/e4ee6df196dd0c6b17d8c695bea3f1d286114f4f/pytorch_lightning/loops/epoch/training_epoch_loop.py#L243). That's where your example breaks, because these conditions are not satisfied.

**Comment by jopo666** [comment]
Yea I think it's could be implemented differently, so that `Trainer` does things in "the right way" even though the user makes a mistake. For example and `IterableDataset` with the wrong length wouldn't miss the validation step in the case below.

```python
for epoch in range(100):
    # Training loop.
    for batch in train_loader_with_wrong_length:
        training_step(batch)

    # Validation loop.
    for batch in val_loader:
        validation_step(batch)
```

To achieve the above case, `Trainer` should move on to the validation epoch if `IterableDataset` raises `StopIteration`, or based on the `val_check_interval` argument. Then the only case where the user's error in defining the `__len__`  would affect `Trainer` is if the user also passes a float to `val_check_interval` as then the`__len__` would affect how many batches the float value corresponds to. 

**A few questions/comments.**

- Where is the`IterableDataset` or more generally the `DataLoader.__len__` used?
- As training works fine without a specific length to the `DataLoader`, is there a specific reason that `Trainer` behaves differently (except for the `progress_bar` etc.) for `DataLoader`s with length.
- Is there some reason why the above warning is issued? The warning seems like something that could be raised by `torch`, not `pytorch-lightning`.
    - IMO, the warning should specifically say, where the `IterableDataset` length may cause an error **if** wrongly defined. Now it's just saying, "*hey you might have made a mistake!*" (which the user may also do with `Dataset` although not as easily).

**Comment by awaelchli** [comment]
@jopo666 I generally agree with your observations

> Where is theIterableDataset or more generally the DataLoader.__len__ used?

Essentially here, as the dataloader will call len() on the dataset if it has one defined: 

https://github.com/PyTorchLightning/pytorch-lightning/blob/e4ee6df196dd0c6b17d8c695bea3f1d286114f4f/pytorch_lightning/trainer/data_loading.py#L349

> As training works fine without a specific length to the DataLoader, is there a specific reason that Trainer behaves differently (except for the progress_bar etc.) for DataLoaders with length.

I think it is primarily for two features: 1) the progress bar will show the limits and a bar 2) the percentage based limits `Trainer(limit_train_baches=0.5)`

> Is there some reason why the above warning is issued? The warning seems like something that could be raised by torch, not pytorch-lightning.

I added the warning to Lightning because of this comment in the PyTorch source code: 
https://github.com/pytorch/pytorch/blob/2f68878a055d7f1064dded1afac05bb2cb11548f/torch/utils/data/dataloader.py#L379-L388
There is an explanation there why torch does not do anything. But we felt in Lightning we still wanted to show a useful message. Do you have any suggestions?

Related, some interesting pytorch issue: https://github.com/pytorch/pytorch/issues/40972

**Comment by libokj** [comment]
Can we revive this issue? Many have encountered the problem of validation loop being skipped when the actual (dynamically generated) number of batches available is smaller than the length of the batch sampler used. There should be a better way to initiate validation than just checking if the last batch is reached or using an infinite dataset.

https://github.com/Lightning-AI/lightning/blob/e7afe04ee86b64c76a5446088b3b75d9c275e5bf/src/lightning/pytorch/loops/training_epoch_loop.py#L406-L432

https://github.com/Lightning-AI/lightning/issues/2675
https://github.com/Lightning-AI/lightning/discussions/13006

**Comment by jjurm** [comment]
+1 having this problem. In my context, I dynamically filter out a few bad samples from the dataset, while this set of filtered samples depends on the training parameters and thus varies between runs. This makes me use `IterableDataset`. However, the true dataset length is still very close to the original one and so I'd like to benefit from the progress bar and its time estimate.

As a workaround, I wrote a simple callback that, in the first epoch, uses an approximate number of batches provided by a data module, then counts the real number of batches. It then overwrites `trainer.fit_loop.max_batches`.

This doesn't change the iteration behaviour in the training loop and so is more of a decorative workaround.

```python
from typing import Any

import lightning as pl


class BatchCounterCallback(pl.Callback):
    """
    This callback is used to set Trainer's max_batches for train, val and test loops, which fixes the progress bar when
    an IterableDataset without __len__ is used. The callback assumes that each iteration has the same number of batches
    and that only one dataloader is used for each set.

    In the first epoch it uses the datamodule's estimated number of batches for each set, which is expected to be
    an upper bound of the true number. In the following epochs it uses the number of batches counted previously.
    """

    def __init__(self):
        self.train_batch_counter = None
        self.train_true_batch_count = None
        self.val_batch_counter = None
        self.val_true_batch_count = None
        self.test_batch_counter = None
        self.test_true_batch_count = None

    def _train_set_guessed_num_batches(self, trainer: pl.Trainer):
        guessed_num_batches = self.train_true_batch_count or trainer.datamodule.get_approx_num_batches("train")
        trainer.fit_loop.max_batches = guessed_num_batches

    def _val_set_guessed_num_batches(self, trainer: pl.Trainer):
        guessed_num_batches = self.val_true_batch_count or trainer.datamodule.get_approx_num_batches("val")
        trainer.fit_loop.epoch_loop.val_loop._max_batches = [guessed_num_batches]

    def _test_set_guessed_num_batches(self, trainer: pl.Trainer):
        guessed_num_batches = self.test_true_batch_count or trainer.datamodule.get_approx_num_batches("test")
        trainer.test_loop._max_batches = [guessed_num_batches]

    def on_train_epoch_start(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule") -> None:
        self.train_batch_counter = 0
        self._train_set_guessed_num_batches(trainer)

    def on_validation_epoch_start(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule") -> None:
        if trainer.sanity_checking:
            return
        self.val_batch_counter = 0
        self._val_set_guessed_num_batches(trainer)

    def on_test_epoch_start(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule") -> None:
        self.test_batch_counter = 0
        self._test_set_guessed_num_batches(trainer)

    def on_train_batch_start(
            self, trainer: "pl.Trainer", pl_module: "pl.LightningModule", batch: Any, batch_idx: int
    ) -> None:
        self.train_batch_counter += 1

    def on_validation_batch_start(
            self,
            trainer: "pl.Trainer",
            pl_module: "pl.LightningModule",
            batch: Any,
            batch_idx: int,
            dataloader_idx: int = 0,
    ) -> None:
        if trainer.sanity_checking:
            return
        self.val_batch_counter += 1

    def on_test_batch_start(
            self,
            trainer: "pl.Trainer",
            pl_module: "pl.LightningModule",
            batch: Any,
            batch_idx: int,
            dataloader_idx: int = 0,
    ) -> None:
        self.test_batch_counter += 1

    def on_train_epoch_end(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule") -> None:
        self.train_true_batch_count = self.train_batch_counter

    def on_validation_epoch_end(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule") -> None:
        if trainer.sanity_checking:
            return
        self.val_true_batch_count = self.val_batch_counter

    def on_test_epoch_end(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule") -> None:
        self.test_true_batch_count = self.test_batch_counter
```
