### ISSUE TITLE
Some mis-alignment in video tutorial

### ISSUE THREAD

**Issue by puhuk** [PyTorchLightning/pytorch-lightning#10299]
## 📚 Documentation

In this video tutorial from (https://pytorch-lightning.readthedocs.io/en/stable/starter/new-project.html),
code indent looks different by each function.

I attach the captured image.

![lightinging](https://user-images.githubusercontent.com/2902772/139758549-db257c76-5c18-40a3-90b3-af931fd32a13.png)
 

cc @borda @rohitgr7

**Comment by Borda** [comment]
@puhuk mind sending a fix? :]

**Comment by puhuk** [comment]
@Borda, It is from the tutorial video. You mean sending a video? 
If you can send some requirements (like font size, color, editor, etc.) I think I can send in a few days :)

**Comment by akihironitta** [comment]
@puhuk Thanks for reporting the issue. I believe someone from our team should fix this (^^;)

**Comment by Borda** [comment]
@edenlightning @aribornstein @tchaton can we edit the video?

**Comment by tchaton** [comment]
Hey @Borda,

Yes, I believe we can. Sync with Eden.
