### ISSUE TITLE
Add `Loop.replace` to improve the customization UX

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#10309]
## 🚀 Feature

Implement a Loop method that allows easily replacing a Loop with not much customization.

### Motivation

There are 2 users of loops customization:
- (A): User that creates their own loop
- (B): User subclasses one of our loops but does not care about init args

Replacing the epoch loop is verbose for (B):

```python
trainer = Trainer(...)
# instantiate with existing values
epoch_loop = MyTrainingEpochLoop(trainer.fit_loop.epoch_loop.min_steps, trainer.fit_loop.epoch_loop.max_steps)
# connect children loops
epoch_loop.connect(trainer.fit_loop.epoch_loop.batch_loop, trainer.fit_loop.epoch_loop.val_loop)
# connect to parent loop
trainer.fit_loop.connect(epoch_loop)
```

This is tedious when the user made a simple modification, for example:

```python
class MyTrainingEpochLoop(TrainingEpochLoop):
    def _should_check_val_fx(self, *args, **kwargs):
        my_condition = self.trainer.optimizers[0].param_groups[0]["lr"] < 1e-3
        return my_condition and super()._should_check_val_fx(*args, **kwargs)
```

This proposal tries to make it easier for (B), but adds no benefits for (A)

### Pitch

Support:
```python
trainer.fit_loop.replace(MyTrainingEpochLoop)
```

where we find which `self` Loop attribute corresponds to this class, instantiates it with the correct arguments, connects the new loop to its subloops, and connects the new loop to the instance `replace` was called for. 

### Alternatives

Not do it, as it holds assumptions that will not work for any Loop implementation.

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @carmocca @justusschock @ananthsub @ninginthecloud

**Comment by tchaton** [comment]
Would the replace function takes any extra kwargs ?

**Comment by carmocca** [comment]
I don't think so.

This only works well when the customized loop `__init__` is kept equal, otherwise, everything could break if the parameter names are renamed or their positions are changed.

And if the `__init__` is equal, there shouldn't be a need for extra kwargs.
But if you have an example in mind where extra `**kwargs` would help, we can surely add it.

**Comment by carmocca** [comment]
After thinking a bit more, these would be the API options

(1): See original post
```python
trainer.fit_loop.replace(TestLoop)
```


(2): Two positional arguments
```python
trainer.fit_loop.replace("epoch_loop", TestLoop)
```

This has the advantages:
- No need to find the attribute name internally.
- Enables support for loops that have subloops of the same type (we don't have this in Lightning but maybe somebody does)

And disadvantages:
- Not as simple

(3): A dictionary
```python
trainer.fit_loop.replace({"epoch_loop": TestLoop})
```

This has the advantages:
- No need to find the attribute name internally.
- Can replace multiple loops at the same time.
- Enables support for loops that have subloops of the same type (we don't have this in Lightning but maybe somebody does)

And disadvantages:
- Not as simple
- Not possible to support `**kwargs` if we choose to.

(3b): Same as (3) but without the dictionary.

```python
trainer.fit_loop.replace(epoch_loop=TestLoop)
```

Let me know if you have any preference. I'm personally leaning towards (3b)

**Comment by carmocca** [comment]
@PyTorchLightning/core-contributors 👍 if you are fine with (3b), or comment if you have other ideas/thoughts.

**Comment by justusschock** [comment]
@carmocca what about an already initialized loop so that I could do 

```python
trainer.fit_loop.replace(epoch_loop=MyCustomLoop(some_arg, some_kwarg=some_arg))
```

And the replace function only takes care of connection? We could also support both with a simple check I think so that you can pass the class for an unchanged init and an instance for a changed init
