### ISSUE TITLE
Bug when calling LightningModule.__init__() directly

### ISSUE THREAD

**Issue by Big-Tree** [PyTorchLightning/pytorch-lightning#10317]
## 🐛 Bug
Colab link https://colab.research.google.com/drive/1ya337j6wM6sDNurgKTBumQNcqEPyGAJw?usp=sharing

The code crashes when you call `pl.LightningModule.__init__(self)` instead of `super().__init__()` when `self.save_hyperparameters()` is called.
### To Reproduce
This works:
```python
import pytorch_lightning as pl

class TestModel(pl.LightningModule):
    def __init__(self, hparams):
        #pl.LightningModule.__init__(self)
        super().__init__()
        self.save_hyperparameters(hparams, ignore='log')


hparams = {'x': 7}
model = TestModel(hparams)

```
This does not work:
```python
import pytorch_lightning as pl

class TestModel(pl.LightningModule):
    def __init__(self, hparams):
        pl.LightningModule.__init__(self)
        #super().__init__()
        self.save_hyperparameters(hparams, ignore='log')


hparams = {'x': 7}
model = TestModel(hparams)

```

### Expected behavior
It would be useful to not have to use `super()` as this gets complicated when there are multiple classes that the PL module inherits.

### Environment

* CUDA:
	- GPU:
		- Tesla K80
	- available:         True
	- version:           11.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.0+cu111
	- pytorch-lightning: 1.5.0
	- tqdm:              4.62.3
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.12
	- version:           #1 SMP Sat Jun 5 09:50:34 PDT 2021

**Comment by carmocca** [comment]
You can still use super to skip the parent's `__init__`, see this pure Python example:

```python
class A:
    def __init__(self):
        super().__init__()
        print('A.__init__')

class B(A):
    def __init__(self):
        super().__init__()
        print('B.__init__')

class C(B):
    def __init__(self):
        super().__init__()
        print('C.__init__')

C()

print("-" * 20)

class C2(B):
    def __init__(self):
        super(A, self).__init__()
        print('C.__init__')

C2()

print("-" * 20)

class C3(B):
    def __init__(self):
        super(B, self).__init__()
        print('C.__init__')

C3()
```
which prints:
```python
A.__init__
B.__init__
C.__init__
--------------------
C.__init__
--------------------
A.__init__
C.__init__
```

**Comment by Big-Tree** [comment]
Okay, thanks.  I'll use this.

**Comment by Big-Tree** [comment]
This does not quite solve my issue.  My class inherits from multiple other classes and pl.lightning isn't the first.  For example:

```python
class TestModel(A, pl.LightningModule, C):
    def __init__(self, hparams):
        super(A, self).__init__()
        self.save_hyperparameters(hparams, ignore='log')
```

This would not work if class `A` also inherited from a class.

**Comment by awaelchli** [comment]
@Big-Tree I looked at this. 

When we do this

```py
class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        # LightningModule.__init__(self)
        self.save_hyperparameters()
```
        
The `save_hyperparameters()` inspects the current frame and branches here in this line when `__class__` is in the local vars:

https://github.com/PyTorchLightning/pytorch-lightning/blob/ce3e63262a7247c1111375b28c90bdd83b42bf3f/pytorch_lightning/utilities/parsing.py#L177-L181

However, if we do

```py
class BoringModel(LightningModule):
    def __init__(self):
        # super().__init__()
        LightningModule.__init__(self)
        self.save_hyperparameters()
```
        
Then this condition will not be true. The variable `__class__` will not be set on the local frame.

I'm not sure how to overcome this issue. If I understand correctly, the check needs to be in place so that we don't go up to a frame where we land outside a class, since we don't want to collect local vars from outside the init frame(s).

**Comment by Big-Tree** [comment]
```python
import pytorch_lightning as pl

class A():
    def __init__(self):
        pass

class B():
    def __init__(self):
        pass

class BoringModel(A, pl.LightningModule, B):
    def __init__(self, hparams):
        pl.LightningModule.__init__(self)
        _ = super()  # Create __class__ variable   <---------------------------
        self.save_hyperparameters()

hparams = {'x': 7}
model = BoringModel(hparams)
```

Thanks for looking into the issue.  This seems to fix it but I'm not sure if it will have any side effects?

**Comment by awaelchli** [comment]
Ok, it seems to fix it for your use case. Just not sure what we can do in our `save_hyperparameters` method. It seems this call needs to happen outside and be done by the user. Because we want to prevent anyone from calling `model.save_hyperparameters()` outside class/init.

**Comment by awaelchli** [comment]
Closing now. Due to the requirements of how `save_hyperaparameters()` is supposed to be constrained, we need to check the variable `__class__`. This variable only gets properly set when `__init__` is called via `super()`. Injecting a `_ = super()` before the call as found by @Big-Tree seems to be the only solution right now.
