### ISSUE TITLE
Remove deprecated code after the 1.5 release

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#10312]
## Proposed refactoring or deprecation

Remove deprecated code after the 1.5 release

### Pitch

All the deprecated features we have are tested here

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/tests/deprecated_api/test_remove_1-6.py

If you are interested in taking care of one item, post a comment here asking to take it. This avoids multiple people working on the same thing.

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by puhuk** [comment]
Can I take this :)

**Comment by carmocca** [comment]
Seems like @daniellepintz took it already: https://github.com/PyTorchLightning/pytorch-lightning/pull/10322. Danielle, please write here any you plan to address so others can also participate.

@puhuk feel free to take any other.

**Comment by puhuk** [comment]
No problem!
Then let me take next one
test_v1_6_0_dataloader_renaming

**Comment by daniellepintz** [comment]
I will only do the trainer_model_hook_mixin, all the others are up for grabs!

**Comment by puhuk** [comment]
Let me also take with below.
test_v1_6_0_ddp_spawn_num_nodes()
test_v1_6_0_ddp_spawn_sync_batchnorm()

**Comment by rhjohnstone** [comment]
I'll do the tiny `early_stopping_monitor`.

**Comment by catalys1** [comment]
I'll tackle `test_v1_6_0_lightning_module_loaded_optimizer_states_dict`.

**Comment by puhuk** [comment]
Let me tackle below 2 items which are in same module (DDPPlugin)

test_v1_6_0_ddp_sync_batchnorm
test_v1_6_0_ddp_num_nodes

**Comment by mayeroa** [comment]
I would like to care of **test_v1_6_0_datamodule_lifecycle_properties** if nobody is working on that already.

**Comment by catalys1** [comment]
I can grab `every_n_val_epochs`.

**Comment by SauravMaheshkar** [comment]
I'll also grab `configure_slurm_dpp` next if that's okay with anyone else.

**Comment by puhuk** [comment]
Let me take `test_v1_6_0_master_params`

**Comment by puhuk** [comment]
Let me take `accelerator_pass_through_functions`

**Comment by shivammehta007** [comment]
Is `is_overridden` still available?  If yes I can take it!

**Comment by puhuk** [comment]
Will do with `test_v1_6_0_deprecated_hpc_load`
