### ISSUE TITLE
Trying to infer the `batch_size` from an ambiguous collection

### ISSUE THREAD

**Issue by BttMA** [PyTorchLightning/pytorch-lightning#10349]
## 🐛 Bug

Yesterday, I was working with my code and it is was perfect, running with no error. But toady, I keep getting this UserWarning saying that the model trying to infer the `batch_size` from an ambiguous collection. I am not sure where it come from. I did not do any changes on my code. The error keeps getting different batch size with the sale warning : 

```
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/data.py:57: UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 55. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
  "Trying to infer the `batch_size` from an ambiguous collection. The batch size we"
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/data.py:57: UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 1. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
  "Trying to infer the `batch_size` from an ambiguous collection. The batch size we"
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/data.py:57: UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 28. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
  "Trying to infer the `batch_size` from an ambiguous collection. The batch size we"
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/data.py:57: UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 51. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
  "Trying to infer the `batch_size` from an ambiguous collection. The batch size we"
```

### Expected behavior

Running epochs smoothly.

### Environment

- PyTorch Lightning Version: 1.5
- PyTorch Version: 1.9.0
- Python version: 3.7.12
- OS (e.g., Linux): Linux (Colab)
- CUDA/cuDNN version: 11.2
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source): pip
- If compiling from source, the output of `torch.__config__.show()`:
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

**Comment by awaelchli** [comment]
This warning was introduced in Lightning 1.5. You must have updated your packages. 
The warning was introduced here: #10247

What is the structure of your batch? Can you share a reproducible code?
Perhaps @rohitgr7 could take another look.

**Comment by BttMA** [comment]
thanks fr you replay.
I tried every possible update (torch, python...) but it keeps telling me me that i am already updated.
the last version pf pytorch Lit is 1.5. I dont know how can I get 1.7 version.

My code is a little bit long, so I couldn't make a reproducible version! sorry :(
but I can make a snippet of my dataloiader :  

```
...
# this is wrapped in a pl.LightningDataModule class

def train_dataloader(self):
  return DataLoader(self.train_dataset, # the data is a tensor torch Dataset
                      batch_size=self.batch_size,
                      shuffle=True,
                      num_workers=8) # same thing for the val_dataloader and test_dataloader

```
I can assure you that yesterday It was working fine and nothing wrong with it.

**Comment by rohitgr7** [comment]
If you can share the snippet of your dataset that would be great. All we need to know the structure of the batch you get inside your `training_step`.

**Comment by BttMA** [comment]
```
import torch
from torch.utils.data import Dataset

class XDataset(Dataset):

  def __init__(
    self, 
    data, 
    tokenizer, 
    max_token_len
  ):
    self.tokenizer = tokenizer
    self.data = data
    self.max_token_len = max_token_len
    
  def __len__(self):
    return len(self.data)

  def __getitem__(self, index: int):
    data_row = self.data.iloc[index]

    comment_text = data_row.com
    labels = data_row.lab

    encoding = self.tokenizer(
      comment_text,
      add_special_tokens=True,
      max_length=self.max_token_len,
      return_token_type_ids=False,
      padding="max_length",
      truncation=True,
      return_attention_mask=True,
      return_tensors='pt',
    )

    return dict(
      comment_text=comment_text,
      input_ids=encoding["input_ids"].flatten(),
      attention_mask=encoding["attention_mask"].flatten(),
      labels=torch.tensor(labels)
    )
```


```
import pytorch_lightning as pl
import torch
from torch.utils.data import TensorDataset, DataLoader

class XDataModule(pl.LightningDataModule):

  def __init__(self, train_df, val_df, test_df, tokenizer, batch_size, max_token_len):
    super().__init__()
    self.train_df = train_df
    self.val_df = val_df
    self.test_df = test_df
    self.batch_size = batch_size
    self.tokenizer = tokenizer
    self.max_token_len = max_token_len

  def setup(self, stage=None):
    self.train_dataset = XDataset(self.train_df,
                                              self.tokenizer,
                                              self.max_token_len)

    self.val_dataset = XDataset(self.val_df,
                                             self.tokenizer,
                                             self.max_token_len)
    
    self.test_dataset = XDataset(self.test_df,
                                             self.tokenizer,
                                             self.max_token_len)

  def train_dataloader(self):
    return DataLoader(self.train_dataset,
                      batch_size=self.batch_size,
                      shuffle=True,
                      num_workers=8)

  def val_dataloader(self):
    return DataLoader(self.val_dataset,
                      batch_size=self.batch_size,
                      num_workers=8)

  def test_dataloader(self):
    return DataLoader(self.test_dataset,
                      batch_size=self.batch_size,
                      num_workers=8)
```


```
N_EPOCHS = 3
BATCH_SIZE = 16

MAX_TOKEN_COUNT =100

data_module = XDataModule(
  train_df,
  test_df,
  val_df,
  tokenizer,
  batch_size=BATCH_SIZE,
  max_token_len=MAX_TOKEN_COUNT
)
```

**Comment by rohitgr7** [comment]
The issue might be with comment_text here. Can you print the shape for the all items of the batch passed in the training_step?

**Comment by BttMA** [comment]
When i do this :
````
test_dataset = XDataset(test_df, tokenizer)
sample_item = test_dataset[0]
sample_item.keys()
```
I got this : 

````
dict_keys(['comment_text', 'input_ids', 'attention_mask', 'labels'])
````

and the shape of my data is : `(torch.Size([8, 128]), torch.Size([8, 128]), torch.Size([8]))` (after I do this...) and `max_token_len = 128`

```
sample_batch = next(iter(DataLoader(test_dataset, batch_size=8, num_workers=2)))
sample_batch["input_ids"].shape, sample_batch["attention_mask"].shape, sample_batch["labels"].shape
```

Also When I do this `test_dataset.__getitem__(0)` I got this:

```
{'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]),
 'comment_text': '@MrBeast I can for that amount.. pls invite me.. ',
 'input_ids': tensor([  101,   137,  1828,  2064, 14517,  1204,   146,  1169,  1111,  1115,
          2971,   119,   119,   185,  3447, 13967,  1143,   119,   119,   102,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0]),
 'labels': tensor(7)}
```

**Comment by rohitgr7** [comment]
comment_text might also be coming within the batch of the training_step. I don't remember exactly how pytorch handles collating the string values, but if you are using automatic logging with on_step=true, we try to extract the batch_size from the batch itself by iterating over all its components. Now if there is any ambiguous batch for which we find more than 1 different batches, we log this warning along with the batch size to make sure that user is aware of batch_size being used to accumulate the logged values.

**Comment by BttMA** [comment]
Sorry I am not sur if I completely get your message. But Two days ago, the snippet that I showed you, they were working just fine! I am not sure this warning where it came from. 

as for the comment_text, you asked if it is coming in the batch or not, I can show you in my training_step method that It is not : 

```
  def training_step(self, batch, batch_nb):
    input_ids = batch["input_ids"]
    attention_mask = batch["attention_mask"]
    labels = batch["labels"]
    outputs = self(input_ids, attention_mask, labels)
    loss = outputs[0] # outputs["loss"]
    logits = outputs[1] # outputs["logits"]
    self.log("Train loss", loss, on_epoch=True, prog_bar=True, logger=True, sync_dist=True)
    tensorboard_logs = {'Train loss': loss}
    return {"loss": loss}
```

Also, as I mentioned in the issue ; in each refresh rate of the progress bar I got the same waring with new value for the batch size.

**Comment by rohitgr7** [comment]
These changes were added in recent 1.5 release. In your dataset above you are returning the comment text, but you are not using it inside training_srep. Can you try removing the comment text from the dictionary returned in your dataset and check if you still get this warning?

**Comment by BttMA** [comment]
Hi again :) NO problem! you are doing just fine.
I removed the comment text form the dict returned in the dataset and now it is working without any warning!
Thank you 😊

Now, It would be great if you can explain to me how this is happened in the first place? and why do I keep getting different  value of batch_size and what `self.log(..., batch_size=batch_size)` means? do I need to add the batch_size in each log in the methods train, val, and test?
Thanks again 😉

**Comment by rohitgr7** [comment]
Great! So basically what we do internally is iterate over the batch that is passed inside the training_step. Doesn't matter if any of its components are actually used to compute the loss/metric we use all its components to extract the batch size. In your example when you passed the other tensors including the comment_text which is string, even though it's not used to compute the loss/metric we will consider it to extract the batch size because we don't know how user is computing the loss/metric. Now depending upon the batch type which is a dict in your case we look for tensors to find out the batch_size of the dataset. Basically we look for the first dimension of each tensor and in case of string it's just the len of string. Now while iterating over this dict if we found multiple possible batch sizes we put this warning to make sure the accumulation of the logged metric happening internally must use the correct batch size. Now for your case when you are returning comment_text which is the first component of the dict, pytorch must not be collating it as you expected because string lengths are not constant and computing a batch I think is not possible over there. So that's why inside the training_step the comment_text component is variable most of the time and now since the first dim size is not matching with the first dim size of other tensors, this warning is being raised and we suggest to specify the batch size manually to make sure accumulation happens correctly.

**Comment by rohitgr7** [comment]
Here is the code if you want to check more where and how this warning is raised https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/utilities/data.py#L45

**Comment by BttMA** [comment]
Thank you for your help!
Wish you the best!!

**Comment by Nesqulck** [comment]
@rohitgr7 Can you elaborate why you consider strings to hold information about the batch size?

Maybe yielding None for types that are not tensors is less confusing, e.g. by changing else statement to yield None instead of 1 in:

https://github.com/PyTorchLightning/pytorch-lightning/blob/348fc4b49f0e74acb9785b5179abb8fd01beb45a/pytorch_lightning/utilities/data.py#L30-L42

and handling this None case in:

https://github.com/PyTorchLightning/pytorch-lightning/blob/348fc4b49f0e74acb9785b5179abb8fd01beb45a/pytorch_lightning/utilities/data.py#L45-L62

Also, if no batch_size was found (batch_size = None after loop), a similar warning can be logged

**Comment by XiaomoWu** [comment]
@rohitgr7 I totally get the motivation of batch_size sanity check, but what if I have such return type:

```python
def dataset(Dataset):
    def __getitem__(self, idx):
        # some process here

        # return results
        return {'input_1': {'token_ids': Tensor, 'attention_mask': Tensor},
                'input_2': {'token_ids': Tensor, 'attention_mask': Tensor}          
```

Then under current PL logic, the return size of each component will be 2, right?

The motivation of returning two dicts (`input_1` and `input_2` in my case) is that I usually need to test many different tokenization methods, raw data formats, etc. To keep the flexibility of code, I decide to return all of them and use a configuration to select a subset of them later (e.g., in `DataLoader` or `LightingModule`).

**Comment by Nesqulck** [comment]
I believe in this case the return type is still determined by the value of shape[0] of each tensor. Since your return type is just a nested dict of all tensors, thus the batch size is just determined recursively by _extract_batch_size.

However, there can be cases where there is a data type (e.g. list) of different types (string, int, Any, etc) where the length of this list is the actual batch size and not the length of the string for example. One could solve this by not doing this recursively but then we lose the ability to infer from nested sequences or mappings (dicts etc). Therefore, I suggested to ignore other types than tensors since usually people only work with tensors for all intents and purposes of self.log. And in cases where no batch size could be inferred due to a lack of tensors, the warning actually makes sense

**Comment by cgarchbold** [comment]
Hello, I am using a custom collate function in my code. This is part of a custom dataset I have written, one which may have a variable amount of labels per input image. This warning message comes up in my training constantly and attempting to resolve with self.log(..., batch_size=...) doesn't seem to make the warning go away. Can there be a way to mute this error message, when using a custom collate?

**Comment by Nesqulck** [comment]
The warning is not triggered by self.log but when loading a batch from the dataloaders. The trainer infers the batch size in every step which is needed for accumulated metrics when using self.log(on_epoch=True). It does so regardless if anything is logged at all, so using self.log(batch_size=...) does not suppress this warning. The warning is rather a reminder for the user to take care of this such that the accumulated metrics are correctly calculated.

I assume the reason you see this warning is similar to mine where there is a custom batch structure including special data types which are not necessarily needed for training or accumulating metrics, e.g. strings.

For now, a simple workaround would be to filter this warning manually by:

    import warnings
    
    warnings.filterwarnings(
        "ignore", ".*Trying to infer the `batch_size` from an ambiguous collection.*"
    )

**Comment by immanuelweber** [comment]
Hi there, I'm also carrying some lists of strings in my data where the length of the list is the batch size and the current implementation results in a warning in this situation. I would definitely prefer what @Nesqulck is suggesting.
I feel that the current implementation infers some applications but punishes others that are also valid.
I'm just commenting on this issue, since it has been closed, and I'm unsure if it is in focus anymore.
Cheers ✌️

**Comment by rohitgr7** [comment]
@cgarchbold your issue is being handled here: https://github.com/PyTorchLightning/pytorch-lightning/pull/10408

I agree with the above discussions. Opened an issue here: https://github.com/PyTorchLightning/pytorch-lightning/issues/10458

**Comment by yipliu** [comment]
I came across the warning in the following situation

```python
loss = self.loss_fn(logits, label, a_list)

self.log(f"{state}/loss", loss, on_step=False, on_epoch = True, prog_bar=False)
```
a_list: This is a list, len= batch_size
logits.shape = [B, x, xx]
lable.shape = [B,x]

When the self.log is executed, the warning occurs

**Comment by rohitgr7** [comment]
@yipliu 
since one of the components is a list that is not really a PyTorch tensor, it doesn't rely on it to determine the batch_size and thus gives a warning to ensure the user the batch_size used. If you want to disable the warning you can set 
```py
self.log(..., batch_size=...)
```

**Comment by talhaanwarch** [comment]
I set, but it still giving me warning with following code
```
def training_step(self,batch,batch_idx):
        out = self(batch["video"]).flatten()
        loss=self.criterion(out,batch["label"].float())
        mae=self.metric(out,batch["label"].float())
        return {'loss':loss,'mae':mae.detach()}

    def training_epoch_end(self, outputs):
        loss=torch.stack([x["loss"] for x in outputs]).mean().cpu().numpy().round(2)
        mae=torch.stack([x["mae"] for x in outputs]).mean().cpu().numpy().round(2)
        self.log('train_loss', loss,batch_size=self.batch_size)
        self.log('train_mae', mae,batch_size=self.batch_size)
        print('training loss ',self.current_epoch,loss,mae)
```

**Comment by rohitgr7** [comment]
hey @talhaanwarch
mind share a reproducible script with [BoringModel](https://colab.research.google.com/github/PyTorchLightning/pytorch-lightning/blob/example/bug_report/pl_examples/bug_report/bug_report_model.ipynb) to check more on this.

Also, while logging on training_epoch_end, I don't think there is a need to batch_size, but ideally, it should not even raise this warning.

**Comment by yipliu** [comment]
Hi @talhaanwarch 

I use the following code
```python
self.log(f"{stage}/loss", loss, on_step=False, ..., batch_size=self.config.batch_size
```

**Comment by je-santos** [comment]
If I'm accumulating gradients, should I use the batch size of the data loader or the batch size of the data loader times how many batches are accumulated ?

**Comment by adosar** [comment]
> Great! So

If the returned batch is a tuple of tensors `(x, y)` where `x.shape[0] != y.shape[0]` how Lightning handles this case? It uses only the first one, the second?

**Comment by adosar** [comment]
To check the inferred batch size from Lightning:
```python
from lightning.pytorch.utilities.data import extract_batch_size
extract_batch_size(batch)
# Output
```
