### ISSUE TITLE
Fault-tolerant training requires len to be available on all datasets

### ISSUE THREAD

**Issue by srdecny** [PyTorchLightning/pytorch-lightning#10358]
## 🐛 Bug

Fault-tolerant training assumes `len` is available on all datasets. [Pytorch's Dataset](https://pytorch.org/docs/1.7.0/_modules/torch/utils/data/dataset.html#Dataset) class does not require to actually implement `__len__`. Per the docs above: "Subclasses could also optionally overwrite :meth:`__len__`". Our dataset subclasses `Dataset`, and does not implement the `__len__` function, so with fault-tolerant training enabled, PL crashes right [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/93caa7cda9277f86f17b1eab0793019aee8d40c2/pytorch_lightning/trainer/data_loading.py#L288).

### To Reproduce
Public colab link: https://colab.research.google.com/drive/1-j9mjawAzbA8w5jTHfg-ILvl9D9Gy_u8?usp=sharing

### Expected behavior
The fault-tolerant training should work even if a dataset does not have a `len` function, as it is not required to.

### Environment

```
* CUDA:
	- GPU:
		- Tesla K80
	- available:         True
	- version:           11.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.0+cu111
	- pytorch-lightning: 1.5.0
	- tqdm:              4.62.3
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.12
	- version:           #1 SMP Sat Jun 5 09:50:34 PDT 2021
```
### Additional context
Thanks for your work on this cool project <3

cc @pzelasko

**Comment by tchaton** [comment]
Dear @srdecny,

When using pure PyTorch, if you define a dataset without a len, it would fail within the SequentialSampler. 

```py
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

    def __getitem__(self, index):
        return 1

dataloader = DataLoader(CustomDataset())
for batch in dataloader:
    print(batch)
```

```py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    for batch in dataloader:
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 560, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 512, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 229, in __iter__
    for idx in self.sampler:
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 66, in __iter__
    return iter(range(len(self.data_source)))
TypeError: object of type 'CustomDataset' has no len()
```

When the length is unknown, it is recommended to use an IterableDataset instead.

Would you mind giving more details about your use case?

Best,
T.C

**Comment by pzelasko** [comment]
Hi @tchaton,

Thanks for your interest in this! Let me just say that I'm working on multiple projects where PT Lightning is adopted and we find it immensely useful -- it's helping us a lot in prototyping and moving fast. Thank you for all the effort you put into it!!

Let me give you a bit of background. I'm building [Lhotse](https://github.com/lhotse-speech/lhotse), a library for speech data representation + PyTorch I/O. Basically the main idea is to bring a lot of speech datasets which have differing audio codecs, number of channels, metadata schemas, etc. into a common format and make it simple to work with from Python + PyTorch.

In Lhotse, we have a basic building block called `CutSet` which is a collection of utterances (or more precisely, light-weight meta-data dataclass for each utterance). We rely heavily on Sampler subclasses to implement things such as dynamic batch sizes, stratification, bucketing, etc. The sampler is actually a batch sampler, and instead of yielding indexes of examples, it yields mini-batch `CutSet` (a bunch of meta-data for utterances in a mini-batch). 

The twist is here: our Dataset classes are map-style datasets, but they don't actually own any data. Their `__getitem__` simply knows how to map a mini-batch of meta-data dataclasses/dicts into a mini-batch of tensors. It performs all the heavy lifting: I/O, feature extraction, transforms, augmentations, etc. along the way.

In this use-case, it doesn't make sense to define `__len__` for map-style dataset since it simply doesn't know the data ahead of time. Similarly, it doesn't make sense to define `__len__` for samplers, because they themselves might be reading the meta-data on-the-fly (e.g. line-by-line from an open file or connection). 

I know this is fairly deviant from the "standard" workflow with dataset + sampler, but we considered it carefully, and since PT doesn't require `__len__` on map-datasets to work, it seems legit ;) 

If you'd like to see an example of this workflow, we have a Colab that shows an end-to-end example of using Lhotse with ESPnet (E2E ASR training framework). See here: https://colab.research.google.com/drive/1HKSYPsWx_HoCdrnLpaPdYj5zwlPsM3NH

Let me know if you have any more questions. We would love it if we could use the fault-tolerant training feature of PL together with Lhotse I/O mechanisms!

**Comment by tchaton** [comment]
Hey @pzelasko,

Awesome work ! Really cool projects.
Let me try to run the notebook locally and see if I understand how I could add support for the length.

Best,
T.C

**Comment by tchaton** [comment]
Dear @pzelasko,

Here are my updates so far. There is tiny change to enable the code to work with Fault Tolerant Training. However, it seems the tokens aren't the same on restart.

The way your code is implemented is quite custom and a bit of a hack :) Not sure we can support it, but I will keep investigating it.

```py
import os

import chainer
import espnet
import lhotse
import numpy
from torch.utils.data import DataLoader
from lhotse.dataset import BucketingSampler
from lhotse.dataset.collation import TokenCollater
from lhotse.recipes import download_librispeech, prepare_librispeech
from lhotse import CutSet
from pytorch_lightning import LightningDataModule, LightningModule, Trainer, seed_everything
from lhotse.dataset.collation import TokenCollater
from espnet.bin.asr_train import get_parser
from espnet.nets.pytorch_backend.e2e_asr_conformer import E2E
import torch
from lhotse import Fbank, FbankConfig
from lhotse.dataset import OnTheFlyFeatures


parser = get_parser()
parser = E2E.add_arguments(parser)
args = parser.parse_args(
    ["--mtlalpha", "0.0", "--outdir", "out", "--dict", ""]  # weight for cross entropy and CTC loss
)  # TODO: allow no arg

class MinimalEspnetDataset(torch.utils.data.Dataset):
    def __init__(self, tokenizer: TokenCollater):
        self.extractor = OnTheFlyFeatures(Fbank(FbankConfig(num_mel_bins=80)))
        self.tokenizer = tokenizer

    def __getitem__(self, cuts: CutSet) -> dict:
        cuts = cuts.sort_by_duration()
        feats, feat_lens = self.extractor(cuts)
        tokens, token_lens = self.tokenizer(cuts)
        print(tokens)
        return {"xs_pad": feats, "ilens": feat_lens, "ys_pad": tokens}


class DataModule(LightningDataModule):

    def prepare_data(self,) -> None:
        download_librispeech(dataset_parts="mini_librispeech")

    def setup(self, stage = None):
        libri = prepare_librispeech(corpus_dir="LibriSpeech", output_dir="data/")
        self.cuts_train = CutSet.from_manifests(**libri["train-clean-5"])
        self.cuts_test = CutSet.from_manifests(**libri["dev-clean-2"])
        self.tokenizer = TokenCollater(self.cuts_train)
        self.tokenizer(self.cuts_test.subset(first=2))
        self.tokenizer.inverse(*self.tokenizer(self.cuts_test.subset(first=2)))

    def train_dataloader(self):
        train_sampler = BucketingSampler(self.cuts_train, max_duration=300, shuffle=True, bucket_method="equal_duration")
        return DataLoader(MinimalEspnetDataset(self.tokenizer), sampler=train_sampler, batch_size=None, num_workers=2)

    def test_dataloader(self):
        test_sampler = BucketingSampler(self.cuts_test, max_duration=400, shuffle=False, bucket_method="equal_duration")
        return DataLoader(MinimalEspnetDataset(self.tokenizer), sampler=test_sampler, batch_size=None, num_workers=2)

    @property
    def model_kwargs(self):
        return {
            "odim": len(self.tokenizer.idx2token),
        }


trainer = Trainer(strategy="ddp", gpus=2, logger=None, replace_sampler_ddp=False)
os.environ["PL_FAULT_TOLERANT_TRAINING"] = "1"

seed_everything(42)

class Model(LightningModule):
    def __init__(self, args):
        super().__init__()
        self.args = args

    def setup(self, stage = None) -> None:
        datamodule = self.trainer.datamodule
        setattr(self.args, "char_list", list(datamodule.tokenizer.idx2token))
        self.model = E2E(80, **datamodule.model_kwargs, args=self.args)

    def training_step(self, batch, batch_idx):
        return self.model(**batch)

    def configure_optimizers(self):
        return torch.optim.Adam(self.model.parameters())


dm = DataModule()
model = Model(args)

trainer.fit(model, dm)
```

**Comment by tchaton** [comment]
Dear @pzelasko

Would you mind implementing a Boring version of a Cuts Sampler to help me out to add investigate ? This would definitely save me some time.

Best,
T.C

**Comment by pzelasko** [comment]
Thanks! I appreciate the effort you put into this :)

Just to confirm -- I ran the snippet and got:

```
...
  File "/home/pzelasko/envtest/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 154, in prepare_dataloader
    dataloader = self._update_dataloader(dataloader, sampler, mode=mode)
  File "/home/pzelasko/envtest/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 299, in _update_dataloader
    dl_kwargs = TrainerDataLoadingMixin._get_dataloader_init_kwargs(dataloader, sampler, mode=mode)
  File "/home/pzelasko/envtest/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 288, in _get_dataloader_init_kwargs
    elif len(dl_kwargs["dataset"]):
TypeError: object of type 'MinimalEspnetDataset' has no len()
```

However, if I add a dummy len in the Dataset `def __len__(self): return 1` it seems to train OK. I wonder whether fault-tolerant mechanism in PL is relying on the existence of `__len__` for anything other than disambiguation between map and iterable datasets.

Re inconsistent tokens: thanks, you seem to be right. I'll take a deeper look into this.

**Comment by tchaton** [comment]
It doesn't rely on the len of the dataset. Can easily change the line too.

```py
            elif isinstance(dl_kwargs["dataset"], Dataset):

```

**Comment by pzelasko** [comment]
Does this help? https://colab.research.google.com/drive/1haJVDv_liEC7FqJPUE0v772Oeioszdwi?usp=sharing

**Comment by tchaton** [comment]
Hey @pzelasko,

Thanks, I will give it a try.

By the way, you might have some performance gain by using an IterableDataset instead. When using multiple workers, the Cuts are being passed to the workers via the data queue, and the process might add an overhead.

I believe it could be possible to optimise / clean this implementation :)

Best,
T.C

**Comment by pzelasko** [comment]
I guess that makes sense. I tried it at a much earlier stage but didn’t like how tightly the code was coupled with that approach. I am hoping adopting DataPipes at some stage later will clean this up nicely though.

**Comment by tchaton** [comment]
Dear @pzelasko,

After brainstorming with @awaelchli, we believe your use case is too complex to be fully automated by Lightning.
However, we are planning to add support for a manual fault tolerant on the data loading part.
So Lightning will collect the state_dict from the data loaders and re-inject them on loading. The user will be responsible to implement the logic and we will provide an advanced tutorial on how to do so.

I created this issue to track the progress: https://github.com/PyTorchLightning/pytorch-lightning/issues/10431

I would be quite interested to work with you to implement a manual collection of the state_dict and make sure the restoration is done properly.

Best,
T.C

**Comment by pzelasko** [comment]
That sounds interesting. Samplers in Lhotse already implement retrieving and storing state dicts so we could possibly try it out with little effort. See: https://github.com/lhotse-speech/lhotse/blob/ebf047280c2c409fd667c0901df8c1e545f43d2d/lhotse/dataset/sampling/single_cut.py#L106

The only caveat is that I accepted to lose num_workers * prefetch_factor batches; I’m not sure what is a clean way to work around the dataloader already having consumed a number of batches from the sampler, but not yielded them yet from training. With 0 workers dataloader it would work without losses.

**Comment by tchaton** [comment]
It should be fine. Lightning capture the state alongside the batch. So worth checking this out.

Are you on Lightning Slack, if yes, you would mind contacting me, I have the same username as on Github.

Best,
T.C

**Comment by tchaton** [comment]
Hey @pzelasko,

Lightning takes care of `prefetch_factor` by tracking the batch actually consumed by the model and retrieving the associated states.

Best,
T.C
