### ISSUE TITLE
minGPT examples with Deepspeed do not seem to be updated

### ISSUE THREAD

**Issue by stanleyshly** [PyTorchLightning/pytorch-lightning#10394]
Running the minGPT example on the advanced GPU training page seems to led to errors, given that the example is still using deepspeed through the plugin method, rather than the updated strategy input variable method.

**Comment by SeanNaren** [comment]
Thanks for taking a look @stanleyshly! I should take some time to redo this repo as it's strayed away from the min part of minGPT a bit :)

**Comment by SeanNaren** [comment]
I've updated the example here! https://github.com/SeanNaren/minGPT/tree/deepspeed should remedy the issue :)
