### ISSUE TITLE
make `get_nvidia_gpu_stats` public

### ISSUE THREAD

**Issue by rohitgr7** [PyTorchLightning/pytorch-lightning#10414]
### Motivation

https://github.com/PyTorchLightning/pytorch-lightning/blob/e61a98a3d0cbe28f1df41841b4766166dd9ea531/pytorch_lightning/accelerators/gpu.py#L76
This is currently a private function. I was trying lite so wanted something than can get me the memory usage and utilization. So I am suggesting to make it public.

Alternatively we have https://pytorch.org/docs/stable/generated/torch.cuda.memory_stats.html#torch.cuda.memory_stats
but this doesn't seem to return utilization.

Also there was some request over the slack (I'll add the link here once I find it) requesting to make both of them available but right now we disable the nvidia one if using torch >= 1.8
https://github.com/PyTorchLightning/pytorch-lightning/blob/e61a98a3d0cbe28f1df41841b4766166dd9ea531/pytorch_lightning/accelerators/gpu.py#L74-L76

If we make this public, it will be available to get the basic metrics related to GPU usage rather than the one available in torch which returns whole bunch of other things and will be available for public use and one can simply hack `GPUAccelerator` and use this one.

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

**Comment by ananthsub** [comment]
This could easily be a separate utility function. maybe `utilities/gpu.py` : https://github.com/PyTorchLightning/pytorch-lightning/blob/e61a98a3d0cbe28f1df41841b4766166dd9ea531/pytorch_lightning/accelerators/gpu.py#L88-L137

Which the accelerator could call.
