### ISSUE TITLE
[Main Issue] Accelerator and Plugin refactor

### ISSUE THREAD

**Issue by four4fish** [PyTorchLightning/pytorch-lightning#10416]
### Motivation
Accelerator is not stable API yet, we can improve the Accelerator related logic and move towards stable Accelerator version for 1.6

### Pitch
**Steps**
1. Collective refactor #7534
   - [x] deprecate accelerator collective directly call from TTP #9677
   - [ ] collective refactor #9414
2. Move Precision Plugin into TTP #7324 
3. Move Accelerator into Strategy #10648 
4. Simplify the Spawning logic #10059 
5. [RFC] Simplifying the Accelerator Connector logic and flags (can be done in parallel with aboves) #11449  11449
6. [RFC] Revisit the inheritance of TTP #11863
 
 
 

**More details in**: [Accelerator Refactor Proposal](https://docs.google.com/document/d/1E5t8auWf5DrNHzutvMmrJC_KqBqVyZuYX0thra69Ad8/edit#heading=h.nehmb825f40s)
[updating] 

### FAQ
1. Will this be a lot of breaking changes?
Not much user facing API changes from 1,2,3,4.(Unless we found out other existing bugs during refactor) The only breaking change will be for custom plugins
5 and 6 is still RFC stage, may have breaking changes which impact user facing APIs

2. How does this impact lightningLite?
Should be helpful for lightningLite too, there maybe function refactor/simplification could happen for lightningLite. (@awaelchli  any suggestion about this part?)

### Follow up TODOs:
- [ ] check if trainer.FITTING before setting up optimizers https://github.com/PyTorchLightning/pytorch-lightning/pull/10596#discussion_r753587321

- [ ] Send a PR to  https://github.com/ray-project/ray_lightning  to update their plugins

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @justusschock @awaelchli @akihironitta @tchaton @borda @kaushikb11 @ananthsub

**Comment by awaelchli** [comment]
Great summary! About 

> How does this impact lightningLite?

As best as I can see right now:
Step 1, 2 do not impact Lite. If there are changes in required in the Trainer, they will be mirrored directly by Lite. The Trainer as well as Lite do not make any strong assumptions on the internal composition of plugins.
Step 3: not sure
Step 4: Will impact Trainer more than Lite. Lite is sort of already setting an example here how it could/should look like in the Trainer.
Step 5, 6: should not impact Lite at all (accelerator connector is shared)

**Comment by tchaton** [comment]
Yes, definitely really excited about this. I am quite eager to finally see the accelerators marked as a stable API targetting v1.6.

**Comment by awaelchli** [comment]
@ananthsub 

https://github.com/PyTorchLightning/pytorch-lightning/pull/10570#pullrequestreview-807890492
> It'd be very good to list what APIs this lets us simplify or remove from the Accelerator/strategy/precision plugin. Those could be listed as immediate followups to this PR

Here are some that I found and also some are mentioned in the [doc](https://docs.google.com/document/d/1E5t8auWf5DrNHzutvMmrJC_KqBqVyZuYX0thra69Ad8/edit#heading=h.nehmb825f40s)

After 2)

Methods:
- Accelerator.optimizer_step (move)
- Accelerator.backward (move)
- Accelerator.*_dispatch (move + reduce)
- Accelerator.*_step (move)
- some miscellaneous ones

Property:
- Accelerator.amp_backend (move)
- Accelerator.precision (move)
- Accelerator.scaler (move)


After 3)

- TrainingTypePlugin.on_gpu/on_tpu
- TrainingTypePlugin.model_to_device

These will either make use of the accelerator or be moved to it.

**Comment by awaelchli** [comment]
Now that the precision plugin has moved, I will take a look at this TODO here:
https://github.com/PyTorchLightning/pytorch-lightning/blob/af0bb96f0ff645102680a7adc99dc131cfeb9c0b/pytorch_lightning/lite/lite.py#L433-L439

**Comment by awaelchli** [comment]
Here is another follow up we need to do IMO: #10686. This will unblock also #10657

**Comment by carmocca** [comment]
Closing this issue in favor of the smaller linked issues for the pending tasks.
