### ISSUE TITLE
[RFC] Support passing Precision Plugin instances to the `precision` flag

### ISSUE THREAD

**Issue by kaushikb11** [PyTorchLightning/pytorch-lightning#10413]
### Motivation

The motivation is to support passing `PrecisionPlugin` objects to the `precision` flag.

#### Current Approach

Right now, to pass the custom objects to the Trainer, users have to pass it to the `plugins` flag.

```python
trainer = Trainer(strategy="ddp", plugins=[CustomPrecisionPlugin()])
```

#### Proposed Solution

Support passing custom `PrecisionPlugin` objects directly to the `precision` flag. It would be similar to passing TrainingTypePlugin objects to the `strategy` flag and would match it. 

```python
trainer = Trainer(strategy="ddp", precision=CustomPrecisionPlugin())
```

Passing the precision plugin objects to the `plugins` flag  would be deprecated in v1.7 and will be removed in v2.0.

If you agree with this change, react with 🎉, if not then 🙅🏽 with comments.

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @carmocca @justusschock @awaelchli @akihironitta @rohitgr7 @kaushikb11 @tchaton

**Comment by tchaton** [comment]
Hey @kaushikb11, I agree with this proposal, 
However it seems there is lot of confusion right now as there is so many overlapping ways around device, strategy, etc...
Doing this right now would add in complexity and confusion.

**Comment by tchaton** [comment]
Hey @kaushikb11 @awaelchli Any updates on this ?

**Comment by ananthsub** [comment]
I don't fully get the motivation here. the precision plugin also takes into account the amp backend and the amp level. Does that mean the Trainer is now validating against this?

```py
Trainer(precision=32, amp_level="O2", amp_backend="native", plugins=[MyCustomPrecision(precision=16, amp_backend="foo", amp_level="bar")
```

what's the issue with passing precision plugin as an argument to plugins vs precision?

**Comment by justusschock** [comment]
I agree with @ananthsub that we should not allow that. IMO `precision=16` is only short for `plugins=NativeMixedPrecisionPlugin(precision=16)`

If we mix those it gets more confusing to the user.

**Comment by awaelchli** [comment]
At the moment, I don't see why there is a need for this.

**Comment by carmocca** [comment]
Let's close this then. Feel free to continue discussing here if you have further arguments either way
