### ISSUE TITLE
Broken links in the Example section of the README

### ISSUE THREAD

**Issue by ThomVett** [PyTorchLightning/pytorch-lightning#10427]
Hello all,

Was reading the README and realized that the links `Example` section of the [README](https://github.com/PyTorchLightning/pytorch-lightning#examples) are broken.

The fist MNIST hello world link works but the other links do not work.

Thanks,

Thomas

**Comment by justusschock** [comment]
Basically all links to examples from Bolts are not working.

The reason for this is, that they were moved to the deprecated section within bolts: https://lightning-bolts.readthedocs.io/en/latest/deprecated/models/reinforce_learn.html

Do we still want to list them although this is deprecated?
cc @Borda @ananyahjha93

**Comment by Borda** [comment]
I think that the issue is that we refer to the latest which may not be stable at all times...
Let's link to particular release/tags... @ThomVett mind sending a fix by replacing `latest` in links with a tag where we still had the examples at the expected paths?

**Comment by ThomVett** [comment]
@Borda here is a PR https://github.com/PyTorchLightning/pytorch-lightning/pull/10440
- keeping latest for pytorch-lightning links
- tagging to 0.4.0 for lightning-bolts links
