### ISSUE TITLE
Better name for parameter in RichProgressBarTheme

### ISSUE THREAD

**Issue by Raahul-Singh** [PyTorchLightning/pytorch-lightning#10435]
In the `RichProgressBarTheme`, there is a parameter `batch_process`
Would it be better to call it `batch_progress`

For reference, 
```python
@dataclass
class RichProgressBarTheme:
    """Styles to associate to different base components.
    https://rich.readthedocs.io/en/stable/style.html
    """

    text_color: str = "white"
    progress_bar_complete: Union[str, Style] = "#6206E0"
    progress_bar_finished: Union[str, Style] = "#6206E0"
    progress_bar_pulse: Union[str, Style] = "#6206E0"
    batch_process: str = "white"
    time: str = "grey54"
    processing_speed: str = "grey70"
```

**Comment by SeanNaren** [comment]
hey @Raahul-Singh!

names definitely need to be cleaned up for sure!

`batch_process` changes the colour of the text for the progress tracker (i.e `10/50` batches completed). Maybe we should just making it `batch_progress_text`? Would really help us if you could make a PR to change this name!

**Comment by kaushikb11** [comment]
I think `batch_progress` sounds good! We don't have `_text` suffix to other attributes
