### ISSUE TITLE
When auto-selecting GPUs, prioritize previously used GPUs

### ISSUE THREAD

**Issue by rharish101** [PyTorchLightning/pytorch-lightning#10456]
## Proposed refactoring or deprecation

When auto-selecting GPUs, Lightning iterates over available CUDA devices in sequence as follows:
https://github.com/PyTorchLightning/pytorch-lightning/blob/4755ae60b71a857a17f39dba1189c2c3245660f5/pytorch_lightning/tuner/auto_gpu_select.py#L48-L58

We should first check GPUs that have been previously used, and then check the unused ones.

### Motivation

Say we have processes A, B and C, and two GPUs configured in exclusive process mode. Consider the following situation:
* Process A is using GPU 0
* Process B, with Lightning, runs a `Trainer` that auto-selects GPU 1 (since A is using GPU 0).
* Process A exits, clearing up GPU 0.
* Process B finished using the `Trainer`, and thus 'frees' up GPU 1. However, B doesn't exit, and so there is still some small amount of memory reserved by PyTorch on GPU 1.
* Process B creates a new `Trainer`, that invokes the auto-selection again. It sees that GPU 0 is available, so it reserves it.
* Process C wants to get a GPU. However, since B is fully using GPU 0, and it's reserved GPU 1 (even though it's not using it), it doesn't get any GPU.

### Pitch

The GPU selection routine should be changed to:
```python
previously_used_gpus = []
unused_gpus = []
for i in range(torch.cuda.device_count()):
    if torch.cuda.memory_reserved(f"cuda:{i}") > 0:
        previously_used_gpus.append(i)
    else:
        unused_gpus.append(i)

# Prioritize previously used GPUs
for i in previously_used_gpus + unused_gpus:
    if i in exclude_gpus:
        continue
    # Try to allocate on device:
    device = torch.device(f"cuda:{i}")
    try:
        torch.ones(1).to(device)
    except RuntimeError:
        continue
    return i
raise RuntimeError("No GPUs available.")
```

I've made the changes here: https://github.com/rharish101/pytorch-lightning/tree/feature/10456-better_gpu_select

cc @justusschock @awaelchli @akihironitta

**Comment by tchaton** [comment]
@kaushikb11 Any thoughts ?

**Comment by rharish101** [comment]
I also noticed that `pick_single_gpu` is not used anywhere in the code. Maybe we can combine `pick_single_gpu` with `pick_multiple_gpus` to create a `pick_gpus` that can avoid traversing the loops multiple times, and maintaining an `exclude` list.

I've added this to my branch (https://github.com/rharish101/pytorch-lightning/tree/feature/10456-better_gpu_select) as follows:
https://github.com/rharish101/pytorch-lightning/blob/81ef04f1af2dbf8c327906cb59e37bd16a006f90/pytorch_lightning/tuner/auto_gpu_select.py#L21-L64

I can open a PR if you want.

**Comment by kaushikb11** [comment]
Hi @rharish101, the proposal sounds good.

I have a question, here you check if the GPU is being used before.
```python
if torch.cuda.memory_reserved(f"cuda:{i}") > 0:
	...
```
Let's consider GPU 0 has some PyTorch program running, it will return as True and crash if it is selected by Trainer, right? 

Wouldn't that be bad user experience? As there would be other GPUs available.

**Comment by rharish101** [comment]
Hi @kaushikb11, AFAIK `torch.cuda.memory_reserved` only shows memory reserved by the current process, not by any other PyTorch process. That way, we are actually making it safer.

**Comment by kaushikb11** [comment]
@rharish101 Sounds good! :)
You could go ahead with the PR. Thanks!

**Comment by rharish101** [comment]
Thanks for the approval! I've opened a PR (#10485) for the prioritization. I'll open another PR for the refactoring after this PR is merged (otherwise there would be a merge conflict with the PR merged later).

**Comment by carmocca** [comment]
I'm hesitant about this change for the reasons @kaushikb11 mentioned.

> only shows memory reserved by the current process, not by any other PyTorch process

Do you have any references for this? The docs don't say it:
https://pytorch.org/docs/stable/generated/torch.cuda.memory_reserved.html#torch.cuda.memory_reserve.

In the past, when I've had to share GPUs I preferred the opposite, prioritizing unused GPUs to minimize the impact of different scripts on memory and throughput.

**Comment by rharish101** [comment]
> Do you have any references for this?

Nope, I manually ran two scripts, each of which reserved memory by allocating a tensor, and printed `torch.cuda.memory_reserved`.

> In the past, when I've had to share GPUs I preferred the opposite, prioritizing unused GPUs to minimize the impact of different scripts on memory and throughput.

Do you mean that when you have multiple GPUs and multiple processes, you would prefer them to use separate GPUs? Because that is what my proposal does, as this tells each process to prioritise GPUs that it previously used, and not infringe on GPUs that could be used by other processes.

If you prefer the opposite, then it wouldn't work with the example mentioned in the issue (which would lead to unnecessary GPU sharing), especially when running in exclusive process mode.
