### ISSUE TITLE
I can't find callbacks on pl.Trainer()

### ISSUE THREAD

**Issue by varDiii** [PyTorchLightning/pytorch-lightning#1045]
I saw in Documentation that show ' argument', but when a run I got a error
The same for 'num_tpu_core's argument

```
TypeError                                 Traceback (most recent call last)
<ipython-input-23-62ad7a703918> in <module>()
      2 
      3 model = LightningBirdsClassifier(num_classes=200)
----> 4 trainer = pl.Trainer(gpus=-1, max_nb_epochs=120, callbacks=[ProgressBar()])
      5 
      6 trainer.fit(model)

TypeError: __init__() got an unexpected keyword argument 'callbacks'
```

**Comment by awaelchli** [comment]
Did you install from master? The new callbacks are only available on master and soon in the new release 0.7

**Comment by varDiii** [comment]
> Did you install from master? The new callbacks are only available on master and soon in the new release 0.7

how can i download from master? 
I used pip install pytorch-lightning

**Comment by awaelchli** [comment]
From the readme of this repository at the very bottom:

`pip install git+https://github.com/PytorchLightning/pytorch-lightning.git@master --upgrade`

**Comment by awaelchli** [comment]
Just keep in mind master is the development version and not stable

**Comment by varDiii** [comment]
> Just keep in mind master is the development version and not stable
OK, Thanks for you help
