### ISSUE TITLE
ModelCheckpoint doesn't save in default_root_dir hierarchy with Neptune logger

### ISSUE THREAD

**Issue by lucmos** [PyTorchLightning/pytorch-lightning#10475]
## 🐛 Bug

The `ModelCheckpoint` callback stores the checkpoint outside the `default_root_dir` if the Neptune logger is used. In particular they are stored in `cwd() / .neptune /  ...`

### To Reproduce

https://colab.research.google.com/drive/1NAYpHgXqWZEnJg_fehalpHwUNclx8UTi?usp=sharing

tl;dr: this is where the checkpoints get stored:

```
default_root_dir=/content/default_root_dir
Without neptune: /content/default_root_dir/lightning_logs/version_10/checkpoints/epoch=0-step=312.ckpt
With neptune in debug mode: /content/.neptune/Untitled/OFFLINE-1/checkpoints/epoch=0-step=312-v4.ckpt
With neptune in offline mode: /content/.neptune/offline-name/OFFLINE-1/checkpoints/epoch=0-step=312-v4.ckpt
With neptune in default mode: /content/.neptune/Untitled/TES-2/checkpoints/epoch=0-step=312.ckpt
```

### Expected behavior

The checkpoint should be stored in the `default_root_dir`, with some directories hierarchy, not in the current working directory. A common use case is to use different hard disks or file systems between the training and results/data storage.

Moreover, the Neptune `save_dir` is not currently configurable. See https://github.com/neptune-ai/neptune-client/issues/744
### Cause

The problem lies in the combination of this line that defaults to use the `logger.save_dir`:

https://github.com/PyTorchLightning/pytorch-lightning/blob/d2aaf6b4cc420a4ef2aa4d1db29a0e881cea9406/pytorch_lightning/callbacks/model_checkpoint.py#L583

And the Neptune logger, that defines the save dir as `cwd() / '.neptune'`:

https://github.com/PyTorchLightning/pytorch-lightning/blob/d2aaf6b4cc420a4ef2aa4d1db29a0e881cea9406/pytorch_lightning/loggers/neptune.py#L487-L494

### Environment

```bash
* CUDA:
	- GPU:
		- Tesla K80
	- available:         True
	- version:           11.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.0+cu111
	- pytorch-lightning: 1.5.1
	- tqdm:              4.62.3
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.12
	- version:           #1 SMP Sat Jun 5 09:50:34 PDT 2021
```

**Comment by rohitgr7** [comment]
well I think since neptune doesn't provide an option to specify the directory to save the logs, we rely on the default one that neptune uses internally. So the basic idea is to use the directory used by logger and if it's not there, use the `default_root_dir`.

**Comment by lucmos** [comment]
I see

Still, I think it is unexpected that the model checkpoints are not stored under the `default_root_dir` regardless of the logger used. 

Even more so since the `default_root_dir` can be a remote path (internally handled by `fsspec`)

**Comment by mrembalski** [comment]
Hi, 
I have recently encountered this issue. Can it be reopened?

**Comment by alessiamarcolini** [comment]
I also have the same issue.

Specifically, when using Neptune in debug mode, the `checkpoint_callback.best_model_path` is an empty string. This then makes a `load_from_checkpoint` call fail with `IsADirectoryError: [Errno 21] Is a directory:` because it's trying to read the checkpoint from a path which is the CWD

cc @TvdrBurgt
