### ISSUE TITLE
The difference between Module and Trainer load from checkpoint?

### ISSUE THREAD

**Issue by marsggbo** [PyTorchLightning/pytorch-lightning#1049]
`LightningModule` has a function `load_from_checkpoint`, while the trainer also has a variable, namely `resume_from_checkpoint`, what's the difference between them?

By the way, I want to print the best result of the checkpoint whenever I resume from the ckpt, how can I do this job? I override the `on_load_checkpoint` of `LightningModule`, but nothing happens...

**Comment by williamFalcon** [comment]
resume_from_checkpoint is private

**Comment by williamFalcon** [comment]
https://pytorch-lightning.readthedocs.io/en/latest/weights_loading.html
