### ISSUE TITLE
BoringModel notebook import outdated

### ISSUE THREAD

**Issue by jiwidi** [PyTorchLightning/pytorch-lightning#10490]
## 🐛 Bug

The model notebook at GColab you link when creating an issue is outdated. Tries to import metrics from pytorch lightning:  

```python
from pytorch_lightning.metrics.functional import accuracy
```

I believe this is because pytorch_lightning doesn't include torchmetrics anymore, and they are a completely separate library.

### To Reproduce

Go to the link and try to run it: 
https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing

### Expected behavior

To run smoothly!

### How to solve it

Replace the import with a torchmetrics import:
```python
from torchmetrics.functional import accuracy
```

I would open a PR myself but I couldnt find the notebook on the repo. It could be beneficial maybe to include it as part of the `pl_examples`? Then link the colab notebook to the version on master branch. That I could open a PR :) 

### Environment
Latest google colab

**Comment by rohitgr7** [comment]
I think we should keep a bug_report notebook inside pl_examples and link that one instead so that it can be updated whenever it's required to be.

https://colab.research.google.com/github/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.ipynb

**Comment by carmocca** [comment]
Yes, let's do that, we only need to update the issue template and add this ipynb
