### ISSUE TITLE
Multiple ModelCheckpoint callbacks format checkpoint name as {epoch}-{step}-v{version}.ckpt regardless of monitor

### ISSUE THREAD

**Issue by AAnoosheh** [PyTorchLightning/pytorch-lightning#10506]
## 🐛 Bug

Using more than one ModelCheckpoint is now supported as of Lightning 1.5, but if monitors are provided, the filenames of the stored checkpoints should auto-insert the metric name by default. 

Instead, they are simply the standard multiple-checkpoints-in-same-directory format using the version numbers as so, for example using three callbacks with different monitors each gives:
```
epoch=1-step=200.ckpt
epoch=1-step=200-v1.ckpt
epoch=1-step=200-v2.ckpt
```

### Expected behavior

The filenames should be named as so:
```
epoch=1-step=200-metric1=XX.ckpt
epoch=1-step=200-metric2=YY.ckpt
epoch=1-step=200-metric3=ZZ.ckpt
```

### Environment

- PyTorch Lightning Version: 1.5.0
- PyTorch Version: 1.10.0
- Python version: 3.8

**Comment by rohitgr7** [comment]
you can set you filename like this:
```py
ModelCheckpoint(filename='{epoch}-{step}-{metric1}', monitor='metric1'...)
ModelCheckpoint(filename='{epoch}-{step}-{metric2}', monitor='metric2', ...)
ModelCheckpoint(filename='{epoch}-{step}-{metric3}', monitor='metric3', ...)
```

**Comment by tchaton** [comment]
Hey @AAnoosheh,

I believe @rohitgr7 gave you the way forward. You can easily create multiple ModelCheckpoint with your metric keys and it should work as expected. Don't forget to pass them all when restoring your training from a checkpoint.

Closing this issue for now, feel free to re-open it if you have more questions.
