### ISSUE TITLE
Remove `pytest-random-order` from conda tests

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning#10515]
## 🚀 Tiny enhancement in CI
#10084 somehow fixed #10129 by randomise the order of the tests using `pytest-random-order`, but we should identify the source of the problem of conda CI runs getting killed.

### Pitch
- Identify the cause of #10129 
- Remove the change added in #10084
https://github.com/PyTorchLightning/pytorch-lightning/blob/fabb3644027a12c0df9acbdbc752d7ca7673396c/.github/workflows/ci_test-conda.yml#L33
https://github.com/PyTorchLightning/pytorch-lightning/blob/fabb3644027a12c0df9acbdbc752d7ca7673396c/.github/workflows/ci_test-conda.yml#L47

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

**Comment by tchaton** [comment]
Dear @akihironitta, did you look into removing it. Any ideas why the tests were failing ?

**Comment by akihironitta** [comment]
@tchaton I had a similar issue before in Bolts and it was due to OOM then, but I'm not sure yet if it applies to this issue as re-ordering the tests shouldn't impact the memory usage... I'll look into this in https://github.com/akihironitta/pytorch-lightning/pull/1.

**Comment by carmocca** [comment]
We can also try reverting #10084 entirely and running the CI a few times. Might have been resolved after all the recent CI updates
