### ISSUE TITLE
Step-by-step walk-through encounters some error when proceeding with Step-by-Step

### ISSUE THREAD

**Issue by os1ma** [PyTorchLightning/pytorch-lightning#10518]
## 📚 Documentation

I'm using pytorch-lightning (1.5.1).

When I tried to go through the Step-by-step walk-through of Get Started, From MNIST to AutoEncoders, The Research, to get started with PyTorch Lightning, I found some missing code and an error.

Relevant page: https://pytorch-lightning.readthedocs.io/en/latest/starter/introduction_guide.html#the-research

## 1. lack of print

Affected part: https://pytorch-lightning.readthedocs.io/en/latest/starter/introduction_guide.html#the-model

This is a very small problem, but `Size([1, 10])` requires the `print(out.shape)` statement.

## 2. Missing library

Affected part: https://pytorch-lightning.readthedocs.io/en/latest/starter/introduction_guide.html#data

When I run this, I get the following error.

```
ModuleNotFoundError: No module named 'torchvision'.
```

Solving this is easy, but it might be clear if the following installation command exists in the document.

```
pip install torchvision
```

## 3. lack of import and lack of configure_optimizers method

Affected part: https://pytorch-lightning.readthedocs.io/en/latest/starter/introduction_guide.html#pass-dataloaders-to-fit

### 3.1 Missing import

When I run this, I get the following error.

```
NameError: name 'Trainer' is not defined
```

This is a simple error, but it might be easier to specify import.

```
from pytorch_lightning import Trainer
```

### 3.2 Lack of configure_optimizers method

In addition, even with the above import, I still get the following error.

```
pytorch_lightning.utilities.exceptions.MisconfigurationException: No `configure_optimizers()` method defined. Lightning `Trainer` expects as minimum a `training_step()`, `train_dataloader()` and `configure_optimizers()` to be defined.
````

This is because the class LitMNIST defined above does not have a configure_optimizers method.

The configure_optimizers method is described in the [Optimizer](https://pytorch-lightning.readthedocs.io/en/latest/starter/introduction_guide.html#optimizer) section after here.

So it may be good that we swap the order with [Data](https://pytorch-lightning.readthedocs.io/en/latest/starter/introduction_guide.html#data) section and Optimizer section to solve the problem.

### 3.3 Where similar fixes may be needed

Related to this, it may be also good that we fix code in the beginning of [training](https://pytorch-lightning.readthedocs.io/en/latest/starter/introduction_guide.html#training).

`class LitMNIST(LightningModule)` also appears to need to add a configure_optimizers method.

## 4. Code that I don't know how to execute

Affected part: https://pytorch-lightning.readthedocs.io/en/latest/starter/introduction_guide.html#datamodules-recommended

Here class MyDataModule(LightningDataModule) is defined, but what is used after that is MNISTDatamodule and ImagenetDatamodule.

It may be desirable to include an example where you can try to run LightningDataModule.

## Fixes these

I don't know the proper solution for "4. Code that I don't know how to execute", but fixing 1, 2, and 3 is easy. So I will create a small pull request to fix 1, 2, and 3.

**Comment by tchaton** [comment]
Dear @os1ma,

Thanks for opening this issue and your PR :)

Best,
T.C
