### ISSUE TITLE
The EvaluationLoop() is an instance variable owned by an instance of the class TrainingEpochLoop?

### ISSUE THREAD

**Issue by yjqiang** [PyTorchLightning/pytorch-lightning#10524]
Recently, I read part of the code in pytorch-lightning. And I found [this pseudocode about when to run the validation code](https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_module.html).
```py
def fit_loop():
    on_epoch_start()
    on_train_epoch_start()

    for batch in train_dataloader():
        on_train_batch_start()

        on_before_batch_transfer()
        transfer_batch_to_device()
        on_after_batch_transfer()

        training_step()

        on_before_zero_grad()
        optimizer_zero_grad()

        on_before_backward()
        backward()
        on_after_backward()

        on_before_optimizer_step()
        configure_gradient_clipping()
        optimizer_step()

        on_train_batch_end()

        if should_check_val:
            val_loop()
    # end training epoch
    training_epoch_end()

    on_train_epoch_end()
    on_epoch_end()
```
We evaluate the model once on all validate datasets in `EvaluationLoop().run`, we evaluate the model once on one validate dataset in `EvaluationEpochLoop().run`, we train the model once on whole train dataset in `TrainingEpochLoop().run`.  
But I think it is strange that `epoch_loop:EvaluationEpochLoop` is an instance variable owned by an instance of the class `EvaluationLoop(DataLoaderLoop)`, and the `training_validation_loop: EvaluationLoop` is an instance variable owned by an instance of the class `TrainingEpochLoop`.   
In my opinion, the `trainer` is not just the trainer, and we can call it a "controller" because it controls the training, validating and others, which means **they should be at the same level**. And Maybe we should rewrite like this?
```py
class Trainer:  # Controller
    def __init__(self):
        self.validate_loop = EvaluationLoop(self)  # finish evaluating the model on all validate datasets
        self.train_loop = FitLoop(self) # finish training the model on whole train dataset for several epochs


class FitLoop:
    def __init__(self, controller: Trainer):
        self.controller = Trainer

    def advance(self):
        self.epoch_loop.run(data_fetcher)  # self.epoch_loop: TrainingEpochLoop


class TrainingEpochLoop:
    def __init__(self, controller: Trainer):
        self.controller = Trainer

    def advance(self):
        batch = next(train_dataloader):
        transfer_batch_to_device()

        training_step()
        optimizer_zero_grad()
        backward()

    def on_advance_end(self):
        if should_check_val:
            self.controller.validate_loop.run()
```
PS: I also found the [`self.validate_loop`](https://github.com/PyTorchLightning/pytorch-lightning/blob/fa0ed17f8a18e887ba272a057e7c35c61d7f04fa/pytorch_lightning/trainer/trainer.py#L469) and [`training_validation_loop`](https://github.com/PyTorchLightning/pytorch-lightning/blob/fa0ed17f8a18e887ba272a057e7c35c61d7f04fa/pytorch_lightning/trainer/trainer.py#L461). So can we just write them as one single validate_loop?

**Comment by tchaton** [comment]
@awaelchli

**Comment by carmocca** [comment]
We have two instances of the same `EvaluationLoop` (`trainer.validate_loop` and `trainer.fit_loop.epoch_loop.val_loop`) because even though their functionality is the same, the state needs to be kept separated.

> they should be at the same level. And Maybe we should rewrite like this?

This would mean that running `trainer.fit` -> `trainer.validate` -> `trainer.fit` would leave the validation progress of the fit loop in a bad state, as both procedures have updated the same progress tracking instances.

Additionally, even though the implementation matches for both the `trainer.validate` validation loop and the `trainer.fit` validation loop, this might not be true in the future.

> In my opinion, the trainer is not just the trainer, and we can call it a "controller" because it controls the training, validating and others

This is completely fine, we keep the `Trainer` name for backwards compatibility.

**Comment by yjqiang** [comment]
@carmocca But I'm still confused about, what is the difference between `ttrainer.validate_loop` validation loop and the `trainer.fit_loop.epoch_loop.val_loop` validation loop? Would you please give me some examples? I read [torch/ignite](https://github.com/pytorch/ignite) too, but it looks they just need one validation loop? https://gist.github.com/yjqiang/a25f59f976ac6bf284045ba069000b41#file-ignite-py-L74

**Comment by tchaton** [comment]
Hey @yjqiang,

Currently, `trainer.validate_loop` and  `trainer.fit_loop.epoch_loop.val_loop` are both instances of the same `EvaluationLoop`.
There is 2 instances of them as their states can be different due to their usage.

Best,
T.C

**Comment by yjqiang** [comment]
@tchaton So you mean that maybe user would write like this? So they have to keep their own state?
```py
trainer.fit(...)  # using trainer.fit_loop.epoch_loop.val_loop to select best model
trainer.validate(...)  #  using trainer.validate_loop to evalute 
```

**Comment by yjqiang** [comment]
Thank you so much.
