### ISSUE TITLE
Updating to 1.5.0 makes lightning ignore LightningDataModule.val_dataloader in some cases

### ISSUE THREAD

**Issue by danielgafni** [PyTorchLightning/pytorch-lightning#10527]
## 🐛 Bug

I have a training script that works fine with lightning 1.4.9. After upgrading to 1.5.0 (or 1.5.1) I get this error:

```
NotImplementedError: `val_dataloader` must be implemented to be used with the Lightning Trainer
```

Looks like other people are having this problem too: #10341

### To Reproduce
I can provide an example if it's necessary. 

### Environment
* CUDA:
        - GPU:
                - NVIDIA GeForce RTX 3090
                - NVIDIA GeForce RTX 3080
        - available:         True
        - version:           11.3
* Packages:
        - numpy:             1.21.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.10.0+cu113
        - pytorch-lightning: 1.5.0
        - tqdm:              4.62.3
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.9
        - version:           #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021

### Additional context

I'm using the new Loops API. I have a cross-validation FitLoop which runs `trainer.fit_loop` inside. Probably this is important, because otherwise such an obvious bug wouldn't get into the 1.5.0 release. I wrote my cross-validation loop with this [example](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/loop_examples/kfold.py) as reference.

The custom loop runs with lightning 1.4.9.

**Comment by rohitgr7** [comment]
yes, a simple reproducible example would be useful to resolve it :)

**Comment by jameschapman19** [comment]
```
import torch
import torchvision.transforms as T
from pl_examples.basic_examples.mnist_datamodule import MNIST
from pl_examples.basic_examples.mnist_examples.image_classifier_1_pytorch import Net
from pytorch_lightning import LightningModule
from torch.nn import functional as F
from torchmetrics import Accuracy
import pytorch_lightning as pl

class ImageClassifier(LightningModule):
    def __init__(self, model=None, lr=1.0, gamma=0.7, batch_size=32):
        super().__init__()
        self.save_hyperparameters()
        self.model = model or Net()
        self.test_acc = Accuracy()

    def forward(self, x):
        return self.model(x)

    def training_step(self, batch, batch_idx):
        x, y = batch
        logits = self.forward(x)
        loss = F.nll_loss(logits, y.long())
        return loss

    def test_step(self, batch, batch_idx):
        x, y = batch
        logits = self.forward(x)
        loss = F.nll_loss(logits, y.long())
        self.log("test_acc", self.test_acc(logits, y))
        return loss

    def configure_optimizers(self):
        optimizer = torch.optim.Adadelta(self.model.parameters(), lr=self.hparams.lr)
        return [optimizer], [torch.optim.lr_scheduler.StepLR(optimizer, step_size=1, gamma=self.hparams.gamma)]

    # Methods for the `LightningDataModule` conversion

    @property
    def transform(self):
        return T.Compose([T.ToTensor(), T.Normalize((0.1307,), (0.3081,))])

    def prepare_data(self) -> None:
        MNIST("./data", download=True)

    def train_dataloader(self):
        train_dataset = MNIST("./data", train=True, download=False, transform=self.transform)
        return torch.utils.data.DataLoader(train_dataset, batch_size=self.hparams.batch_size)

    def test_dataloader(self):
        test_dataset = MNIST("./data", train=False, download=False, transform=self.transform)
        return torch.utils.data.DataLoader(test_dataset, batch_size=self.hparams.batch_size)


def main():
    trainer=pl.Trainer()
    model=ImageClassifier()
    trainer.fit(model,model.train_dataloader(),model.val_dataloader())


if __name__ == "__main__":
    main()
```

**Comment by jameschapman19** [comment]
It's also a problem for accessing model.train_dataloader as well as model.val_dataloader if you modify (in my case) on_train_epoch_end and on_validation_epoch_end

```
def on_train_epoch_end(self, unused: Optional = None) -> None:
    score = self.score(
        self.train_dataloader, train=True
    ).sum()
    self.log('train corr', score)
```

**Comment by jameschapman19** [comment]
I can fix by hacking using `self.trainer.train_dataloader` and `self.trainer.val_dataloaders[0]`

**Comment by rohitgr7** [comment]
```py
you don't need to call `.some_dataloader()` explicitly. Just `trainer.fit(model)` is enough.
```

> I can fix by hacking using self.trainer.train_dataloader and self.trainer.val_dataloaders[0]

you should do this only because accessing the dataloader directly from the model will reinitialize them.

> NotImplementedError: `val_dataloader` must be implemented to be used with the Lightning Trainer

at what point are you getting this error exactly?

**Comment by jameschapman19** [comment]
OK have done an edit to my example

```
import torch
import torchvision
import torchvision.transforms as T
from pl_examples.basic_examples.mnist_examples.image_classifier_1_pytorch import Net
from pytorch_lightning import LightningModule
from torch.nn import functional as F
from torchmetrics import Accuracy
import pytorch_lightning as pl


class ImageClassifier(LightningModule):
    def __init__(self, model=None, lr=1.0, gamma=0.7, batch_size=32):
        super().__init__()
        self.save_hyperparameters()
        self.model = model or Net()
        self.test_acc = Accuracy()

    def forward(self, x):
        return self.model(x)

    def training_step(self, batch, batch_idx):
        x, y = batch
        logits = self.forward(x)
        loss = F.nll_loss(logits, y.long())
        return loss

    def validation_step(self, batch, batch_idx):
        x, y = batch
        logits = self.forward(x)
        loss = F.nll_loss(logits, y.long())
        self.log("test_acc", self.test_acc(logits, y))
        return loss

    def configure_optimizers(self):
        optimizer = torch.optim.Adadelta(self.model.parameters(), lr=self.hparams.lr)
        return [optimizer], [torch.optim.lr_scheduler.StepLR(optimizer, step_size=1, gamma=self.hparams.gamma)]

    # Methods for the `LightningDataModule` conversion

    def on_train_epoch_end(self):
        self.train_dataloader()
        pass

    def on_validation_epoch_end(self):
        self.val_dataloader()
        pass

transform = T.Compose([T.ToTensor(), T.Normalize((0.1307,), (0.3081,))])

mnistTrainSet = torchvision.datasets.MNIST(root='./data', train=True,
                                    download=True, transform=transform)
train_dataloader = torch.utils.data.DataLoader(mnistTrainSet, batch_size=16,
                                      shuffle=True, num_workers=2)

mnistTestSet = torchvision.datasets.MNIST(root='./data', train=False,
                                    download=True, transform=transform)
test_dataloader = torch.utils.data.DataLoader(mnistTrainSet, batch_size=16,
                                      shuffle=True, num_workers=2)

def main():
    trainer = pl.Trainer(max_epochs=3)
    model = ImageClassifier()
    trainer.fit(model, train_dataloader, test_dataloader)


if __name__ == "__main__":
    main()
```

I definitely introduce the error if I try to call `self.val_dataloader()` and `self.train_dataloader()` in `on_X_epoch_end`

**Comment by jameschapman19** [comment]
Note that I have pulled the train_dataloader methods out of the LightningModule class this time.

**Comment by rohitgr7** [comment]
> I definitely introduce the error if I try to call self.val_dataloader() and self.train_dataloader() in on_X_epoch_end

yes.. so I'd suggest using `self.trainer.{train/val}_dataloader` instead. Since train/val dataloader is not defined under `LightningModule`we made them agnostic to avoid patching inside 1.5. This will also avoid reinitiating the dataloaders and the trainer will contain the latest dataloader being used for the current method (.fit/validate/test). Can you try using `self.trainer.some_Dataloader?` (just FYI for the train you might need to use `self.trainer.train_dataloader.loader` I think)

**Comment by danielgafni** [comment]
I'm using trainer.fit_loop.run() and trainer.test_loop.run(), just like in the kfold example. Therefore I don't have control on the dataloader is using. Looks like there is a bug indeed?

**Comment by jameschapman19** [comment]
> > I definitely introduce the error if I try to call self.val_dataloader() and self.train_dataloader() in on_X_epoch_end
> 
> yes.. so I'd suggest using `self.trainer.{train/val}_dataloader` instead. Since train/val dataloader is not defined under `LightningModule`we made them agnostic to avoid patching inside 1.5. This will also avoid reinitiating the dataloaders and the trainer will contain the latest dataloader being used for the current method (.fit/validate/test). Can you try using `self.trainer.some_Dataloader?` (just FYI for the train you might need to use `self.trainer.train_dataloader.loader` I think)

So this fixes my specific issue (and is indeed the hack I referred to).

**Comment by danielgafni** [comment]
Ok, as I understand, my problem is with pytorch-forecasting, not pytorch-lightning. I can close the issue?

**Comment by rohitgr7** [comment]
we can keep it open.. its an issue with lightning.
