### ISSUE TITLE
Batch by maximum amount of tokens - NLP

### ISSUE THREAD

**Issue by yuvalkirstain** [PyTorchLightning/pytorch-lightning#10538]
## 🚀 Feature

Provide an option to batch examples by the maximum amount of tokens.

### Motivation

In NLP, the memory consumption of each example is determined by the number of tokens that it possesses. Some examples might be very long (and require a lot of memory), while others might be short (and require little memory). Thus, the batch size should be determined by the number of tokens rather than the number of examples (even if the implementation is somewhat trickier). Imagine an extreme case that there is a single example with 2k tokens, while the rest have 10 tokens. If the max memory consumption is 2k tokens, we will use a batch size of 1. Thus, each epoch will take x200 longer!

### Pitch

Let us train language models more efficiently!

### Additional context

Fairseq implements this feature but I like Pytorch-Lightning :)

**Comment by shabie** [comment]
Since I work with NLP too, this interests me too! :)

I am not sure where does pt-lightning does (or does not) do this more precisely in code?

**Comment by tchaton** [comment]
Hey @yuvalkirstain,

PyTorch Lightning provides the core block for you to build on top of and we try to avoid providing opinionated design.
There are several libraries you can use with PyTorch Lightning. I believe it is possible to use FairSeq with Lightning too.

Best,
T.C

**Comment by yuvalkirstain** [comment]
@tchaton Thanks for the quick reply. Yes, this is indeed mostly relevant to NLP. I'll upload this feature request to Lightning-transformers.
