### ISSUE TITLE
LightningLite not working with ModuleList and ModuleDict

### ISSUE THREAD

**Issue by justusschock** [PyTorchLightning/pytorch-lightning#10543]
### To Reproduce
```python
class MyClass(LightningLite):
    def run(self):
        model = torch.nn.ModuleList([torch.nn.Linear()])
        model, optimiser = self.setup(model, torch.optim.Adam(model.parameters()))
        for x in model:
            print(x) # Fails since _LiteModule is not Iterable
```
### Expected behavior

Model on correct device and still iterable

I see two possibilities here:
1.) we could apply the setup to each module within a `torch.nn.ModuleList`
2.) We could derive a class from `torch.nn.ModuleList` and `_LiteModule` to have methods and properties of both classes.

Whatever solution we choose, we probably need to do the same for `torch.nn.ModuleDict`

Opinions @awaelchli @carmocca ?

cc @carmocca @justusschock @awaelchli

**Comment by carmocca** [comment]
I don't quite understand what (2) proposes but (1) seems more natural

**Comment by justusschock** [comment]
you could do something like 
```
class _LiteModuleList(torch.nn.ModuleList, _LiteModule):
     pass
```

to ensure that the returned model still has all the attributes the `_LiteModule` has. This probably requires the least tweaking, since we possibly have to introduce multiple checks for accessing plugins etc when the returned module is no longer a `_LiteModule` but a ModuleList wrapping several `_LiteModules`. Also that way we have less references to the same plugins/attributes :)

**Comment by awaelchli** [comment]
Workaround is to change 

```python
for x in model:
```

to 

```python
for x in model.module:
```

1) seems ok to me and we would have to re-instantiate the list/dict module.
I'm not sure 2) is valid as there could be wrong decisions based on isinstance checks in the user code.
I think in general, no matter what we do, the user has to be aware that we are wrapping their module and that they have to access their attributes via `model.module.attribute`.

There is maybe an option 3) where we apply the same hack we do for the optimizer, by writing into ``self.__dict__`` but this probably leads to complications with module paths and parameters.

**Comment by awaelchli** [comment]
How would we do this when the plugin already requires the model to be wrapped in a special Module, like `DistributedDataParallel`? Can't really split it up like that, if we look at this section for example: 

https://github.com/PyTorchLightning/pytorch-lightning/blob/48cf1adfd3ad9c7e659083a4afc334dafb331f28/pytorch_lightning/lite/lite.py#L171-L179

`model = ModuleList(_LiteModule(m) for m in model) ` wouldn't work if model is a DistributedDataParallel already.
Neither approach 1 nor 2 seem to be straightforward.

**Comment by justusschock** [comment]
why not? wouldn't each part of the module list be its own DDP module then?

**Comment by awaelchli** [comment]
Maybe I'm not seeing it, but this does not check out with the requirement that optimizers need to be setup together with the model. This line here (see in last message above)

`model, optimizers = self._strategy._setup_model_and_optimizers(model, list(optimizers))
`
would wrap the model into DDP. But we can't iterate over the ModuleDict and call this method on each element. At least I think it wouldn't be correct in regards to the optimizers.

**Comment by justusschock** [comment]
I think that shouldn't matter since the assignment of the parameters to the optimiser(s) has already been done at that point.

**Comment by tchaton** [comment]
Yes, I would align with Adrian there, if you provide a single module, it should be wrapped entirely.

Otherwise, a user could pass a list of objects directly.

**Comment by justusschock** [comment]
@tchaton but this is essentially a list, just that it is wrapped to support device movements
