### ISSUE TITLE
[refactor] Clean up progress bar callback attribute on Trainer

### ISSUE THREAD

**Issue by ananthsub** [PyTorchLightning/pytorch-lightning#10546]
`progress_bar_callback` has a separate attribute on the Trainer like this: https://github.com/PyTorchLightning/pytorch-lightning/blob/01cf7a2ac5a6db588d53c70da1db8d0adcc7641c/pytorch_lightning/trainer/connectors/callback_connector.py#L97-L102

Should we define a property like this which is derived from the `callbacks` property? https://github.com/PyTorchLightning/pytorch-lightning/blob/40945a51765e72400dd3be8f1a84a52a69effa73/pytorch_lightning/trainer/trainer.py#L1841-L1846

_Originally posted by @ananthsub in https://github.com/PyTorchLightning/pytorch-lightning/pull/10520#r749502301_

cc @justusschock @awaelchli

**Comment by awaelchli** [comment]
Yes
