### ISSUE TITLE
Access dataloaders in LightningModule and Trainer

### ISSUE THREAD

**Issue by AndresAlgaba** [PyTorchLightning/pytorch-lightning#10558]
## 🐛 Bug

I have a training script based on the BERT example (see https://colab.research.google.com/github/PyTorchLightning/lightning-tutorials/blob/publication/.notebooks/lightning_examples/text-transformers.ipynb) in which the total number of steps for the learning rate scheduler is computed by the length of the train dataloader via the model.setup() method. 

With PL version 1.4.9 this works just fine, however from 1.5.0 onwards I get the following error:
```python
NotImplementedError: `train_dataloader` must be implemented to be used with the Lightning Trainer
```

This issue has already been raised recently in #10527 with the suggestion of using ```self.trainer.{train/val}_dataloader``` instead of ```self.{train/val}_dataloader```.  This removes the error. However, this returns a ```NoneType``` in my case. Computing the length thus results in the following error:
```python
TypeError: 'NoneType' object is not callable
```

An additional suggestion for the train dataloader is to use ```self.trainer.train_dataloader.loader```, but this, of course, results in the following error:
```python
AttributeError: 'NoneType' object has no attribute 'loader'
```

### To Reproduce

```python
import os

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer, LightningDataModule


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringDataModule(LightningDataModule):
    def __init__(self, train_data, val_data, test_data):
        super().__init__()
        self.save_hyperparameters()

    def train_dataloader(self):
        return self.hparams.train_data

    def val_dataloader(self):
        return self.hparams.val_data

    def test_dataloader(self):
        return self.hparams.test_data


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def setup(self, stage=None):
        train_loader = self.trainer.train_dataloader
        self.total_steps = len(train_loader)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    test_data = DataLoader(RandomDataset(32, 64), batch_size=2)

    dm = BoringDataModule(train_data, val_data, test_data)

    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        num_sanity_val_steps=0,
        max_epochs=1,
        enable_model_summary=False,
    )
    trainer.fit(model, dm)
    trainer.test(model, dm)


if __name__ == "__main__":
    run()
```

### Expected behavior

Following the BERT example, the expected behavior is that the train dataloader attribute can be accessed via self. However, as mentioned in #10527 "Since train/val dataloader is not defined under LightningModulewe made them agnostic to avoid patching inside 1.5. This will also avoid reinitiating the dataloaders and the trainer will contain the latest dataloader being used for the current method (.fit/validate/test)." So I am not sure whether this is still the case? Anyway, the BERT example will need to be modified to be compatible with the newest PL version.

### Environment
- PyTorch Lightning Version (e.g., 1.3.0): 1.5.0 (and 1.5.1 on colab, and tried 1.6.0dev locally)
- PyTorch Version (e.g., 1.8): 1.10.0
- Python version: 3.7
- OS (e.g., Linux): Windows (Linux on colab)
- CUDA/cuDNN version: 11.3 (and 11.2 on colab)
- GPU models and configuration: NVIDIA quadro t2000 (Tesla K80 on colab)
- How you installed PyTorch (`conda`, `pip`, source): pip
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context
Besides this potential bug there are still some other issues in the BERT example (see https://colab.research.google.com/github/PyTorchLightning/lightning-tutorials/blob/publication/.notebooks/lightning_examples/text-transformers.ipynb). Since it is a notebook, I am not sure how to update those, and whether I should create a separate issue for these? If allowed, I will create a PR (if possible) to update the BERT example.

If this issue turns out to be a bug, I would also be happy to create a PR to fix it :)

**Comment by rohitgr7** [comment]
two things here:
1. The example is not presenting the best practices. One should not request the dataloader inside `setup` because users sometimes setup their dataset there and initializing the dataloader there isn't recommended. If someones needs to calculate total training steps for the scheduler it should be done inside `configure_optimizers`.
2. Accessing the dataloaders inside `configure_optimizers` isn't possible yet. Tracking issue: https://github.com/PyTorchLightning/pytorch-lightning/issues/10430. Will be resolved soon.

**Comment by rohitgr7** [comment]
I am close to completing the fix. will attach the PR here. I'd suggest updating it since PR get's merged.
