### ISSUE TITLE
Move is_distributed from accelerator_connector to Strategy

### ISSUE THREAD

**Issue by four4fish** [PyTorchLightning/pytorch-lightning#10551]
## Proposed refactor

move is_distributed() to Strategies (Training_type_plugin) from accelerator_connect

### Motivation

Unblock #7324 
which is part of #10416 

Now in lite.py, we have reference to _accelerator_connector. After precision moved into strategy, the _accelerator_connector is only used for is_distirubted. 
https://github.com/PyTorchLightning/pytorch-lightning/blob/01cf7a2ac5a6db588d53c70da1db8d0adcc7641c/pytorch_lightning/lite/lite.py#L434-L446

### Pitch

Move is_distributed to every strategy
https://github.com/PyTorchLightning/pytorch-lightning/blob/01cf7a2ac5a6db588d53c70da1db8d0adcc7641c/pytorch_lightning/trainer/connectors/accelerator_connector.py#L542-L551

In Lite, we can call _strategy.is_distributed directly
https://github.com/PyTorchLightning/pytorch-lightning/blob/01cf7a2ac5a6db588d53c70da1db8d0adcc7641c/pytorch_lightning/lite/lite.py#L441-L446

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @awaelchli @justusschock @carmocca

**Comment by four4fish** [comment]
cc @awaelchli

**Comment by awaelchli** [comment]
> After precision moved into strategy, the _accelerator_connector is only used for is_distirubted.

You mean in the sense that this is the only property being used from outside the AcceleratorConnector. But surely the connector is heavily used for the parsing and validation of all inputs such as gpus, devices, accelerator choice etc. So I don't fully understand how this adds to the motivation.

> Move is_distributed to every strategy

That's probably doable. Does that mean it has to become an abstract property of the ParallelPlugin?

**Comment by awaelchli** [comment]
It's also not clear how this unblocks #7324. This seems to be quite strongly independent of #7324.

**Comment by four4fish** [comment]
> It's also not clear how this unblocks #7324. This seems to be quite strongly independent of #7324.

I misread the code. I thought lite reference _accelerator_connector is because of need access _accelerator.precision, if we move precision into strategy, we can access precision by strategy.precision. then we can remove the reference to accelerator_connector from lite. 

I don't think this is necessary anymore. Will close the issue
