### ISSUE TITLE
Add ability to pass logger to LightningCLI

### ISSUE THREAD

**Issue by scottire** [PyTorchLightning/pytorch-lightning#10574]
## 🚀 Feature

```
python trainer. py fit --trainer.logger=WandbLogger
```

### Motivation

If I use LightningCLI, I don't want to abandon my favourite logger, WandbLogger 😏. With the new way to reference class names, this would be very nice.

### Pitch

Allow users to pass their favourite logger via the command line (and in a config) using LightningCLI like 

```
python trainer. py fit --trainer.logger=WandbLogger
```

______________________________________________________________________

cc @borda @awaelchli @edward-io @ananthsub @rohitgr7 @kamil-kaczmarek @Raalsky @Blaizzy @carmocca @mauvilsa

**Comment by carmocca** [comment]
For the record, this is achievable right now:

If you don't want it to be configurable, as loggers generally don't change between runs
```python
LightningCLI(..., trainer_defaults={'logger': WandbLogger()})
```

And if you do:

```python
$ python script.py fit --trainer.logger.class_path=pytorch_lightning.loggers.WandbLogger
```
(or using a configuration file)

we just haven't implemented shorthand notation for them.

**Comment by F-Barto** [comment]
Hello, 

I may be wrong, but this seems to introduce a breaking change.
I configure my logger using a YAML config file and not via the command line:
```YAML
trainer:
    ...
    logger:
        class_path: pytorch_lightning.loggers.TensorBoardLogger
        init_args:
            save_dir: my/path/to/save/dir/
            name: default
            default_hp_metric: false
```

And it seems to not work anymore

```bash
Traceback (most recent call last):
  File "/home/clear/fbartocc/bev_project/lift-splat-shoot/lightning_train.py", line 255, in <module>
    BEVProjectCLI(BEVSemanticSegmentation, NuScenesDataModule, save_config_overwrite=True,
  File "/home/clear/fbartocc/miniconda3/envs/BEVProject/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 541, in __init__
    self.parse_arguments(self.parser)
  File "/home/clear/fbartocc/miniconda3/envs/BEVProject/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 681, in parse_arguments
    self.config = parser.parse_args()
  File "/home/clear/fbartocc/miniconda3/envs/BEVProject/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 252, in parse_args
    argv = self._convert_argv_issue_84(classes, k, argv)
  File "/home/clear/fbartocc/miniconda3/envs/BEVProject/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 312, in _convert_argv_issue_84
    class_path = passed_args[f"{argv_key}.class_path"]
KeyError: '--trainer.logger.class_path'
```

Same code and YAML config file work with PL 1.5.10

**Comment by carmocca** [comment]
@F-Barto It's working for me locally, this is the code:

```python
import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule
from pytorch_lightning.utilities.cli import LightningCLI


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)

    def train_dataloader(self):
        return DataLoader(RandomDataset(32, 64))


cli = LightningCLI(BoringModel)
```
```python
python bug_report_model.py fit --config=bug.yaml
```


What's your jsonargparse version? Try updating it with `pip install -U jsonargparse[signatures]`

**Comment by ylffan** [comment]
> For the record, this is achievable right now:
> 
> If you don't want it to be configurable, as loggers generally don't change between runs:
> 
> ```python
> LightningCLI(..., trainer_defaults={'logger': WandbLogger()})
> ```
> 
> Or, if you want to configure it:
> 
> ```python
> $ python script.py fit --trainer.logger.class_path=pytorch_lightning.loggers.WandbLogger --trainer.logger.init_args.name="foo"
> ```
> 
> (or using a configuration file)
> 
> we just haven't implemented shorthand notation for them:
> 
> ```python
> $ python script.py fit --trainer.logger=WandbLogger --trainer.logger.name="foo"
> ```

I am following this to set up my TensorBoardLogger but I found that when I set up using trainer_defaults, as the following

```python
trainer_defaults={'logger': TensorBoardLogger('.', version='myVersion')}
```
the saved config.yaml file will have a wrong logger configuration like
```python
logger: <lightning.pytorch.loggers.tensorboard.TensorBoardLogger object at 0x0000011EDBE85850>
```
which makes this configuration file not usable if I want to use it to resume training.

If I configure it in command line
```python
python train.py fit --trainer.logger TensorBoardLogger --trainer.logger.save_dir . --trainer.logger.version tempVersion
``` 
the config file is generated properly.

I wonder if there is anything I did it wrong here.

**Comment by mauvilsa** [comment]
@ylffan have a look at [lightning_cli_expert.html#class-type-defaults](https://lightning.ai/docs/pytorch/latest/cli/lightning_cli_expert.html#class-type-defaults). Don't use class instances as default because it is not possible for the CLI to know which parameters were used to create such instance. This is why in the config you have a reference to the instance. Also there should have been a warning saying about this.

**Comment by ylffan** [comment]
thanks for pointing this out, using the lazy_instance works now

**Comment by alfieroddan** [comment]
Just adding an example as I was confused on how a lazy_instance worked, may help someone in the future.

With one logger:

```python
# main.py
from lightning.pytorch.cli import LightningCLI
from lightning.pytorch.loggers import (  # noqa: F401
    TensorBoardLogger)

def cli_main():
    logger1 = {
        "class_path": "lightning.pytorch.loggers.TensorBoardLogger",
        "init_args": {
            "save_dir": "logs/"
        }
    }
  
    cli = LightningCLI(  # noqa: F841
        trainer_defaults={'logger': logger1}
    )


if __name__ == "__main__":
    cli_main()
```

With two loggers:

```python
# main.py
from lightning.pytorch.cli import LightningCLI
from lightning.pytorch.loggers import (  # noqa: F401
    TensorBoardLogger, CSVLogger)


def cli_main():
    logger1 = {
        "class_path": "lightning.pytorch.loggers.TensorBoardLogger",
        "init_args": {
            "save_dir": "logs/"
        }
    }
    logger2 = {
        "class_path": "lightning.pytorch.loggers.CSVLogger",
        "init_args": {
            "save_dir": "logs/"
        }
    }
    cli = LightningCLI(  # noqa: F841
        trainer_defaults={'logger': [logger1, logger2]}
    )


if __name__ == "__main__":
    cli_main()
```
