### ISSUE TITLE
Segmentation Fault While Import pytorch_lightning

### ISSUE THREAD

**Issue by BatYu** [PyTorchLightning/pytorch-lightning#10572]
Hi I confronted "Segmentation fault (core dumped)" when trying to import pytorch_lightning. The import line of code was:

`import pytorch_lightning.core.lightning as pl`

My environment is as follow:

- PyTorch Lightning Version 1.4.7
- PyTorch Version 1.9.0
- Python version: 3.7.10
- OS: Linux
- CUDA/cuDNN version: cuda11.1-cudnn8-runtime

I found a previous issue post a year ago whose answer is to suggest using cuda10 instead. Are there any new solutions now? Thank you!

**Comment by akihironitta** [comment]
@BatYu Could you check if `import torch` has the same issue? Also, which package manager did you use to install PyTorch (pip, conda, or from source)?

**Comment by akihironitta** [comment]
You might want to try installing it with conda as advised in https://github.com/pytorch/pytorch/issues/66782

> But in general, to avoid library incompatibility issues I would recommend installing Miniconda and then PyTorch in ones local folder

**Comment by BatYu** [comment]
@akihironitta Thank you for the suggestion! Finally solved it :)
