### ISSUE TITLE
Deprecate support for torchtext.legacy dependencies

### ISSUE THREAD

**Issue by ananthsub** [PyTorchLightning/pytorch-lightning#10597]
## Proposed refactor

Restrict checks & support for `torchtext.legacy` in Lightning

### Motivation

`torchtext` is retiring support for `torchtext.legacy` in upcoming versions: https://github.com/pytorch/text/issues/1422

Lightning uses the `Batch` from `torchtext.legacy` abstractions as part of this utility to move data to device:
https://github.com/PyTorchLightning/pytorch-lightning/blob/7f95fd04d77e3590c8073679e499eabb0c51f73c/pytorch_lightning/utilities/apply_func.py#L245-L255

### Pitch

Restrict the checks for `Batch` from torchtext based on the last torchtext version which supports them (torchtext <= 0.11).
Might be as simple as updating this line:
https://github.com/PyTorchLightning/pytorch-lightning/blob/7f95fd04d77e3590c8073679e499eabb0c51f73c/pytorch_lightning/utilities/apply_func.py#L29

to
```python
    if _compare_version("torchtext", operator.ge, "0.9.0") and _compare_version("torchtext", operator.le, "0.11"):
```
@parmeet @abhinavarora could you confirm?

Ultimately we could remove these checks as the torchtext team is not planning to support them. This would likely provide a performance boost on a critical path by removing a conditional check for torchtext when moving data to device.

### Additional context

cc @justusschock @awaelchli @akihironitta @tchaton @parmeet @abhinavarora 

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

**Comment by awaelchli** [comment]
Agree that we should eventually remove the legacy Batch logic. If users need the legacy version in a newer PL code base, they can always implement our hook to give special treatment to the legacy Batch object.
