### ISSUE TITLE
Neptune Logger assumes unix-style filepath for model checkpoint

### ISSUE THREAD

**Issue by seba-eng** [PyTorchLightning/pytorch-lightning#10602]
The Neptune Logger can automatically upload model checkpoints if the callback is used. It generates an "expected_model_path" for that. This path has hard-coded a '/' at the end (see [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/261ea90822e2bf1cfa5d56171ab1f95a81d5c571/pytorch_lightning/loggers/neptune.py#L547)), which can cause problems on Windows systems because the actual path has (or can have) a backslash at this position. A simple fix would be to use `os.path.sep` insteat of '/'.

cc @justusschock @awaelchli @akihironitta

**Comment by seba-eng** [comment]
never mind, there is already a pull request (#10500) for this problem

**Comment by awaelchli** [comment]
Let's use this issue then to link with the PR (which had no bug report attached). 
I interpret that you are reporting a bug.
