### ISSUE TITLE
pytorch Sequential device

### ISSUE THREAD

**Issue by kfarivar** [PyTorchLightning/pytorch-lightning#10624]
## 🐛 Bug

When wrapping a lighting module in a nn.Sequential module the lighting module doesn't move to the target device with `.to()`. 

### To Reproduce

```py
class model(LightningModule):
     def __init__(self, model):
             super().__init__()
             self.model = model
     def forward(self, x):
            return self.model(x)

a = torch.nn.Sequential(model( torch.nn.Linear(1,1)) )
a.to('cuda:0')
print(a[0].device)
```
this prints `device(type='cpu')` . 

### Expected behavior
For the model to move to the correct device. 

### Environment

 - PyTorch Version (e.g., 1.0):1.10.0
 - OS (e.g., Linux): Ubuntu
 - How you installed PyTorch (`conda`, `pip`, source): pytorch channel
 - Build command you used (if compiling from source):
 - Python version: 3.9.7
 - CUDA/cuDNN version: 11.3
 - GPU models and configuration:
 - Any other relevant information:

**Comment by awaelchli** [comment]
To my knowledge this is a fundamental limitation of nesting modules like this. When calling `.to` on a module, it does not recursively call `.to` on submodules. Instead, it calls [Module._apply](https://github.com/pytorch/pytorch/blob/a39060c001da5e8c91ff92ba776d7beae8fd0be7/torch/nn/modules/module.py#L907) which operates directly on the parameters. 


This effectively prevents us to intercept which device is requested. At the moment, we can only properly capture the device when the LightningModule is the root module.

**Comment by tchaton** [comment]
Hey @awaelchli,

We don't override the `_apply` function on the LightningModule, it should be possible  

```py
import torch
from pytorch_lightning import LightningModule
import inspect

def _find_device(current_frame):
    frame = current_frame.f_back.f_back

    device = None
    while device is None:
        values = inspect.getargvalues(frame)
        device = values.locals.get("device", None)
        frame = frame.f_back

    return device

class model(LightningModule):
    def __init__(self, model):
            super().__init__()
            self.model = model
    def forward(self, x):
        return self.model(x)
    
    def _apply(self, fn):
        self._device = torch.device(_find_device(inspect.currentframe()))
        for module in self.children():
            module._apply(fn)

a = torch.nn.Sequential(torch.nn.Sequential(model( torch.nn.Linear(1,1))))
a.to('cuda:0')
print(a[0][0].device)
```

But this feature would have to be improved if we want to properly support this.

**Comment by ZENGYIMING-EAMON** [comment]
still an issue for 1.6.1 if you define something like class SingleConv(nn.Sequential): and use it in lightning modules
