### ISSUE TITLE
Support passing `storage_options` in `trainer.save_checkpoint()` API

### ISSUE THREAD

**Issue by jjenniferdai** [PyTorchLightning/pytorch-lightning#10629]
### Motivation

Support specifying `storage_options` parameter in `trainer.save_checkpoint()` API.
For metadata that varies across different checkpoint instances, users can then specify `trainer.save_checkpoint(storage_options=...)` per individual checkpoint instance saved, that ultimately gets passed to CheckpointIOPlugin to inform how to best save that particular checkpoint instance.

### Pitch

Introduce new optional `storage_options` arg in `trainer.save_checkpoint()`:
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/trainer.py#L1864-L1865

Introduce and pass arg to `checkpoint_connector.save_checkpoint()`:
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L453

Introduce and pass arg to `TTP.save_checkpoint()`:
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/plugins/training_type/training_type_plugin.py#L294

Pass arg (arg already exists) to `CheckpointIOPlugin.save_checkpoint()`:
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/plugins/io/checkpoint_plugin.py#L36

### Alternatives

Having to specify through `trainer.training_type_plugin.checkpoint_io.save_checkpoint(storage_options=...)`

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @awaelchli @ananthsub @ninginthecloud @rohitgr7

**Comment by awaelchli** [comment]
To set the storage_option for model checkpointing, the user would implement a custom ModelCheckpoint, correct? Here, them main use case is mainly in calling trainer.save_checkpoint manually? What would be a common example for a storage option?

**Comment by jjenniferdai** [comment]
Right this is for calling `trainer.save_checkpoint` manually (or in your ModelCheckpoint callback). Examples could be any metadata/info _specific to different checkpoint instances_ (e.g. a common one could be different TTLs for different checkpoint instances)

**Comment by tchaton** [comment]
Hey @jjenniferdai. Would you mind sharing more on the use case? I am curious if this won't be more explicit if passed directly into the custom checkpoint_io on instantiation for the code readers.

**Comment by jjenniferdai** [comment]
> passed directly into the custom checkpoint_io on instantiation

This would not allow different `storage_options` per checkpoint instance saved (i.e. per `save_checkpoint` call) right?

**Comment by ananthsub** [comment]
> Hey @jjenniferdai. Would you mind sharing more on the use case? I am curious if this won't be more explicit if passed directly into the custom checkpoint_io on instantiation for the code readers.

A concrete use case is someone wanting use the exact same IO mechanisms, but different options per `save_checkpoint` call
```py
trainer.save_checkpoint(ttl_days=1)  # I want this checkpoint to be deleted after a day to save storage
trainer.save_checkpoint(ttl_days=90)  # I want this checkpoint to be saved longer
```
Users should not have to configure a separate IO plugin to do this
```py
# not nice API
trainer = Trainer(..., plugins=MyCheckpointIO(ttl_days=1))
trainer.save_checkpoint()
trainer.strategy.checkpoint_io = MyCheckpointIO(ttl_days=90)
trainer.save_checkpoint()
```
