### ISSUE TITLE
`trainer.validated/tested/predicted_ckpt_path`: mark private or deprecate

### ISSUE THREAD

**Issue by jjenniferdai** [PyTorchLightning/pytorch-lightning#10630]
## Proposed refactor / Motivation

As detailed in this comment: https://github.com/PyTorchLightning/pytorch-lightning/issues/10573#issuecomment-971622770:

- These properties are intended as read-only, they do not support any actual functionality (they do not and should not set the load path).

- The main reason to keep them is to track the exact ckpt_path used in the case of automatic "best" path resolution (https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/trainer.py#L1363). 

### Pitch

To clarify/emphasize this, we can either:

1. Set to private. Also just need one attribute (e.g. `trainer._ckpt_path` or `trainer._last_restored_ckpt_path`).

2. Can we deprecate these attributes entirely? checkpoint_connector gives us info on the exact path here: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L75 

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @justusschock @awaelchli @akihironitta @rohitgr7 @ananthsub @ninginthecloud @tchaton

**Comment by awaelchli** [comment]
At the most we would need only one of these attributes. It does not make sense to have one dedicated to each trainer method.

**Comment by jjenniferdai** [comment]
> At the most we would need only one of these attributes. It does not make sense to have one dedicated to each trainer method.

updated this in pitch option 1 !

**Comment by daniellepintz** [comment]
Hi, just curious what is that status of this issue?

**Comment by awaelchli** [comment]
Sine lately we changed the resume arguments to ckpt_path, I would say `trainer.ckpt_path` is most reasonable.

**Comment by carmocca** [comment]
I agree with ^

**Comment by awaelchli** [comment]
If I understand correctly, #11696 addressed this. Closing.
