### ISSUE TITLE
Remove optimizer for DeepSpeed inference

### ISSUE THREAD

**Issue by SeanNaren** [PyTorchLightning/pytorch-lightning#10640]
## Refactor/Feature

Recently in DeepSpeed it was merged to support making the optimizer optional for inference https://github.com/microsoft/DeepSpeed/pull/1514.

Currently in our plugin we pass in an optimizer always: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/plugins/training_type/deepspeed.py#L573. This is required to partition the parameters appropriately, however this shouldn't be needed now :)

We should wait till a release is made for DeepSpeed. Also we need to be cautious if the user uses a later version of deepspeed and does require an optimizer to be passed. @carmocca do you think we need a deprecation process for this?

### Motivation

Cleaner code, and probably less hacky.

cc @borda @justusschock @awaelchli @akihironitta @SeanNaren

**Comment by carmocca** [comment]
> @carmocca do you think we need a deprecation process for this?

In the past, we have updated our minimum required versions for 3rd party packages (jsonargpare, fairscale, ...) without deprecations for them. Unless you think there's enough difference between the 2 DeepSpeed versions so that it's worth supporting both, I would just update it.
