### ISSUE TITLE
URL to bug report is incorrect in Github issue template

### ISSUE THREAD

**Issue by Shreeyak** [PyTorchLightning/pytorch-lightning#10659]
## 📚 Documentation

When creating a new Github issue, the link to the BoringModel is incorrect and needs to be updated.

Existing (incorrect link):
```
<!--
Please reproduce using the BoringModel!
...
or this simple template:
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
```

Updated link:

```
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report/bug_report_model.py
```

Since this is an issue with the Github issue template, I don't think I can create a PR/fix for it.

cc @borda

**Comment by akihironitta** [comment]
@Shreeyak Thank you for reporting the issue. You can still submit a PR to fix the link. The file is here: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Would you be interested in creating a PR for it?

**Comment by akihironitta** [comment]
It seems like there is another place we need to fix the link:

```console
$ grep -rn pl_examples/bug_report .
docs/source/advanced/fault_tolerant_training.rst:137:On tiny models like the `BoringModel and RandomDataset <https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py>`_
.github/ISSUE_TEMPLATE/bug_report.md:23:https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
```
