### ISSUE TITLE
Invalid Bolts URL

### ISSUE THREAD

**Issue by Freed-Wu** [PyTorchLightning/pytorch-lightning#10654]
In <https://github.com/PyTorchLightning/pytorch-lightning/blob/master/docs/source/extensions/callbacks.rst?plain=1#L89>

```
`bolts library <https://lightning-bolts.readthedocs.io/en/latest/callbacks.html>`_.
```

This URL is `404 not found`.

cc @borda @rohitgr7

**Comment by Borda** [comment]
shall be fixed by #10440
