### ISSUE TITLE
Remove setup_optimizers_in_pre_dispatch logic (from #10596 comments)

### ISSUE THREAD

**Issue by four4fish** [PyTorchLightning/pytorch-lightning#10685]
## Proposed refactor

Commented in #10596, setup_optimizers_in_pre_dispatch logic is not needed anymore

### Pitch

To be added

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @awaelchli @justusschock @akihironitta

**Comment by awaelchli** [comment]
Yes, in a sense it is not needed anymore, but what is needed instead is that the fully sharded plugin will have to override the `setup()` and `pre_dispatch()` methods.
