### ISSUE TITLE
Support creating poptorch.DataLoader from within a LightningDataModule

### ISSUE THREAD

**Issue by hatemhelal** [PyTorchLightning/pytorch-lightning#10695]
## 🚀 Feature

Support creating `poptorch.DataLoader` from within a `LightningDataModule`

### Motivation

Related issue: #10694 

A user with knowledge of the IPU and the poptorch API cannot currently create a `poptorch.DataLoader` within their `LightningDataModule`.  This is limiting as there are a number of options that the `poptorch.DataLoader` provides that are not supported on the native PyTorch `DataLoader`.  Without support for this feature it is difficult for a user to manage advanced batching scenarios for the IPU.

### Pitch
Here is a minimized example showing a `BoringDataModule` that directly instantiates the `poptorch.DataLoader`

```python
class BoringDataModule(LightningDataModule):
    def get_options(self, training=False):
        plugin = self.trainer.accelerator.training_type_plugin

        if training:
            return plugin.training_opts

        return plugin.inference_opts

    def train_dataloader(self):
        opts = self.get_options(training=True)
        return poptorch.DataLoader(options=opts,
                                   dataset=RandomDataset(32, 64),
                                   batch_size=2)

    def val_dataloader(self):
        opts = self.get_options(training=False)
        return poptorch.DataLoader(options=opts,
                                   dataset=RandomDataset(32, 64),
                                   batch_size=2)

    def test_dataloader(self):
        opts = self.get_options(training=False)
        return poptorch.DataLoader(options=opts,
                                   dataset=RandomDataset(32, 64),
                                   batch_size=2)
```

### Alternatives

1. Don't use PyTorch Lightning with IPUs 😭 
2. Reimplement all advanced batching and data access options in Lightning from poptorch. This feels like obvious an anti-pattern.

cc @borda @SeanNaren

**Comment by hatemhelal** [comment]
Here is a tutorial on the `poptorch.DataLoader`:

https://github.com/graphcore/tutorials/tree/sdk-release-2.3/tutorials/pytorch/tut2_efficient_data_loading

**Comment by viethoang303** [comment]
@hatemhelal So we can't use pytorch-lightning and poptorch, right? And we should use pytorch and poptorch for training by ipu ????
