### ISSUE TITLE
Getting Errors on ddp, single node, 8 GPU only detecting device [0]

### ISSUE THREAD

**Issue by sarmientoj24** [PyTorchLightning/pytorch-lightning#10701]
I had this code and getting some errors.
```
    trainer = pl.Trainer(
        gpus=8, 
        max_epochs=500, 
        precision=16, 
        callbacks=[checkpoint_callback],
        logger=wandb_logger,
        log_every_n_steps=10,
        strategy='ddp'
    )
```

I am pretty sure that I have 8 devices online by checking device count and setting `CUDA_AVAILABLE_DEVICES`
```
import torch
torch.cuda.device_count()
>>> 8
```

I am getting this error
```
raceback (most recent call last):
  File "/home/user/yl/trainer.py", line 270, in <module>
    strategy='ddp'
  File "/home/user/anaconda3/envs/yl/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 38, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/user/anaconda3/envs/yl/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 426, in __init__
    gpu_ids, tpu_cores = self._parse_devices(gpus, auto_select_gpus, tpu_cores)
  File "/home/user/anaconda3/envs/yl/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1538, in _parse_devices
    gpu_ids = device_parser.parse_gpu_ids(gpus)
  File "/home/user/anaconda3/envs/yl/lib/python3.7/site-packages/pytorch_lightning/utilities/device_parser.py", line 89, in parse_gpu_ids
    return _sanitize_gpu_ids(gpus)
  File "/home/user/anaconda3/envs/yl/lib/python3.7/site-packages/pytorch_lightning/utilities/device_parser.py", line 152, in _sanitize_gpu_ids
    f"You requested GPUs: {gpus}\n But your machine only has: {all_available_gpus}"
pytorch_lightning.utilities.exceptions.MisconfigurationException: You requested GPUs: [0, 1, 2, 3, 4, 5, 6, 7]
 But your machine only has: [0]
Fusing layers... 
Model Summary: 290 layers, 21172173 parameters, 0 gradients
Traceback (most recent call last):
  File "/home/user/yl/trainer.py", line 270, in <module>
    strategy='ddp'
  File "/home/user/anaconda3/envs/yl/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 38, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/user/anaconda3/envs/yl/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 426, in __init__
    gpu_ids, tpu_cores = self._parse_devices(gpus, auto_select_gpus, tpu_cores)
  File "/home/user/anaconda3/envs/yl/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1538, in _parse_devices
    gpu_ids = device_parser.parse_gpu_ids(gpus)
  File "/home/user/anaconda3/envs/yl/lib/python3.7/site-packages/pytorch_lightning/utilities/device_parser.py", line 89, in parse_gpu_ids
    return _sanitize_gpu_ids(gpus)
  File "/home/user/anaconda3/envs/yl/lib/python3.7/site-packages/pytorch_lightning/utilities/device_parser.py", line 152, in _sanitize_gpu_ids
    f"You requested GPUs: {gpus}\n But your machine only has: {all_available_gpus}"
pytorch_lightning.utilities.exceptions.MisconfigurationException: You requested GPUs: [0, 1, 2, 3, 4, 5, 6, 7]
 But your machine only has: [0]
```

**Environment**  
`torch` is `1.10.0+cu102`  
`pytorch_lightning` is `1.5.2`

cc @justusschock @kaushikb11 @awaelchli @akihironitta @rohitgr7

**Comment by tchaton** [comment]
Hey @sarmientoj24,

Are you doing CUDA_AVAILABLE_DEVICES='0' python script.py. This would hide the others GPUs.

**Comment by sarmientoj24** [comment]
@tchaton No i did not. as a matter of fact, i run the function of getting the list of all GPUs using device count before Trainer fit and I can get `[0, 1, 2, 3, 4, 5, 6, 7]`

**Comment by tchaton** [comment]
Dear @sarmientoj24,

Would you mind using 1.5.2 and confirming you still get the error?
If you do, mind sharing a reproducible script?

**Comment by awaelchli** [comment]
> I am pretty sure that I have 8 devices online by checking device count and setting CUDA_AVAILABLE_DEVICES

Note, the correct variable would be **CUDA_VISIBLE_DEVICES**, not CUDA_AVAILABLE_DEVICES. 

Check in bash that the variable is not set. Even if you don't prefix your command with it, it could still be set globally on your system (for whatever reason): 

```bash
echo $CUDA_VISIBLE_DEVICES
```
should return nothing or a list of devices.

**Comment by sarmientoj24** [comment]
@tchaton should i also include `strategy='ddp'` in there?

**Comment by tchaton** [comment]
Hey @sarmientoj24, 

By default it would use `ddp_spawn`, but you can use ddp :)

**Comment by awaelchli** [comment]
@sarmientoj24 did you find anything new on your side?

**Comment by ZENGYIMING-EAMON** [comment]
Hi, this issue is annoying, and I wish I am reaching some clues here:
I print like this at main.py:
import os; print("===my0===",os.getenv('CUDA_VISIBLE_DEVICES'))
import pytorch_lightning as pl
print("===my1===",os.getenv('CUDA_VISIBLE_DEVICES'))

and I find that it give first 0,1,2,3,4,5,6,7 for two prints
and then give another two prints with only device 1 , (maybe somehow, the programme ran the main.py twice?)
the for the second running, the CUDA_VISIBLE_DEVICES is modified.
But I still can;t find out where it was changed.
Helpppp!

**Comment by ZENGYIMING-EAMON** [comment]
> 

further info:
at main.py:

import os; print("===my0===",os.getenv('CUDA_VISIBLE_DEVICES'))
if os.getenv('CUDA_VISIBLE_DEVICES')=='1':
    import ipdb;ipdb.set_trace()
import pytorch_lightning as pl

it shows first :
===my0=== 0,1,2,3,4,5,6,7
then:
===my0=== 1
> /home/zeng_19/A4-ptForcastPrivate/IDEA-NET-Jrn/LitModelWrapper.py(7)<module>()
      6     import ipdb;ipdb.set_trace()
----> 7 import pytorch_lightning as pl
      8 

ipdb>

**Comment by ZENGYIMING-EAMON** [comment]
Maybe it is because of something like "looping import"??

**Comment by awaelchli** [comment]
> maybe somehow, the programme ran the main.py twice

Yes, Lightning runs the script as many times as you selected devices in the Trainer. 
Lightning does not set the CUDA_VISIBLE_DEVICES env variable. Make sure it does not get modified inside of your script. Make sure your script runs properly on a single device first.

**Comment by ZENGYIMING-EAMON** [comment]
single device is fine, when I ran for devices>=2, this issue shows up

**Comment by ZENGYIMING-EAMON** [comment]
I tried to hack like this:

import os; 
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3,4,5,6,7" #manual modification!
print("===my0===",os.getenv('CUDA_VISIBLE_DEVICES'))
if os.getenv('CUDA_VISIBLE_DEVICES')=='1':
    import ipdb;ipdb.set_trace()
import pytorch_lightning as pl

it gives me new issue:

RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by ZENGYIMING-EAMON** [comment]
I think I have fixed it. It is (mainly) because of the multiprocessing issues. Add 

set trainer devices are [3,4,5]
set trainer strategy is DDP

add this at the top of the main.py:

import os;
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3,4,5,6,7" #manual modification! all you visible GPU!

add at the body of main.py

`if __name__=='__main__':` to wrap your pl.trainer / trainer.fit / trainer.test ...

**Comment by ZENGYIMING-EAMON** [comment]
> I think I have fixed it. It is (mainly) because of the multiprocessing issues. Add
> 
> set trainer devices are [3,4,5] set trainer strategy is DDP
> 
> add this at the top of the main.py:
> 
> import os; os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3,4,5,6,7" #manual modification! all you visible GPU!
> 
> add at the body of main.py
> 
> `if __name__=='__main__':` to wrap your pl.trainer / trainer.fit / trainer.test ...

I will appreciate it if anybody can tell me why
