### ISSUE TITLE
ModuleNotFoundError: No module named 'rich.progress_bar'

### ISSUE THREAD

**Issue by Vozf** [PyTorchLightning/pytorch-lightning#10702]
## 🐛 Bug

Updated pl from 1.4.9 to 1.5.2 and got this
```
Traceback (most recent call last):
File "train.py", line 9, in <module>
from pytorch_lightning import Trainer, seed_everything
File ".venv/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
from pytorch_lightning.callbacks import Callback  # noqa: E402
File ".venv/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py", line 25, in <module>
from pytorch_lightning.callbacks.progress import ProgressBar, ProgressBarBase, RichProgressBar, TQDMProgressBar
File ".venv/lib/python3.8/site-packages/pytorch_lightning/callbacks/progress/__init__.py", line 23, in <module>
from pytorch_lightning.callbacks.progress.rich_progress import RichProgressBar  # noqa: F401
File ".venv/lib/python3.8/site-packages/pytorch_lightning/callbacks/progress/rich_progress.py", line 26, in <module>
from rich.progress_bar import ProgressBar
ModuleNotFoundError: No module named 'rich.progress_bar'
```
P.s. import rich works, but rich.progress_bar - no

### Expected behavior

You can also fill out the list below manually.
-->

**Comment by kaushikb11** [comment]
@Vozf What version of rich are you using?

**Comment by Vozf** [comment]
I'm not using it at all
It seems like it was installed as pl subdependency 
8.0.0

**Comment by kaushikb11** [comment]
Could you use the latest version of rich and test it out?

**Comment by Vozf** [comment]
Works fine after update to 10.14, but still It should be handled in setup.py and not by manual user installation

**Comment by Runkli** [comment]
Would this be resolved just by adding 
`rich>=10.14` to the requirements.txt file? If yes, I can quickly add it

**Comment by Vozf** [comment]
I think so, but I can't be sure. I can test it on a branch or fork

**Comment by awaelchli** [comment]
Let's do that @Runkli

**Comment by kaushikb11** [comment]
@Runkli We have `rich>=10.2.2` in requirements/extras.txt.

We also check `_RICH_AVAILABLE = _module_available("rich") and _compare_version("rich", operator.ge, "10.2.2")` for the User before instantiating `RichProgressBar`

**Comment by Vozf** [comment]
Well, why is rich in extras, if importing anything from pl results in error without installed `rich`. Not sure what your check is supposed to do but as you can see it's not working in my case

**Comment by Runkli** [comment]
@awaelchli made a pull request

**Comment by kaushikb11** [comment]
@Runkli As I mentioned before the PR is not required. 

```python
if _RICH_AVAILABLE:
    from rich.console import Console, RenderableType
    from rich.progress import BarColumn, Progress, ProgressColumn, Task, TaskID, TextColumn
    from rich.progress_bar import ProgressBar
    from rich.style import Style
    from rich.text import Text
 ```
 
`Rich` is the optional requirement for Lightning. It doesn't need to be installed by default, if you have the right version of rich ie., `rich >= 10.2.2` , there won't be an `ModuleNotFoundError`.

**Comment by Vozf** [comment]
Rich is updated  for me with the installation from branch. Thanks. But imho it should be added in the next minor version instead of 1.6.0.

**Comment by Vozf** [comment]
Regarding the `not needed`  - how is the user with rich 8.0.0 subdependency from other package is supposed to know the cause of the error? If you want to check the rich in runtime go ahead and do it properly with checking the rich version and not only its presence

**Comment by kaushikb11** [comment]
```python
if _RICH_LESS_EQUAL_10_2_2:
	raise Exception("Install rich >= 10.2.2.......")
if not _RICH_AVAILABLE:
	raise Exception("Run pip install -u rich.......")
```
This would solve the usability issue :))

**Comment by Vozf** [comment]
It probably would, but raising an exception with asking to install an "optional" dependency doesn't sound like a good idea. Throwing a warning with setting `_RICH_AVAILABLE` to `False` sounds better

**Comment by kaushikb11** [comment]
`_RICH_AVAILABLE` should be `False` as 

```python
_RICH_AVAILABLE = _module_available("rich") and _compare_version("rich", operator.ge, "10.2.2")
```

And your rich version was less than 10.2.2. So, the import shouldn't have happened.

**Comment by Vozf** [comment]
Well I'm hereby to congratulate someone who wrote this piece of code. I've debugged it and it's not working. I have rich 8.0 and it always returns True after excepting on line 62
![image](https://user-images.githubusercontent.com/22998537/143465631-32fae8d5-089a-418b-a1fc-17e177be470b.png)

**Comment by awaelchli** [comment]
> Well I'm hereby to congratulate someone who wrote this piece of code.

@Vozf Please stay respectful in our public forum. The community contributes new code to the project every day. There are bugs and this is normal. We thoroughly review changes but we don't blame anybody for when bugs surface. As of right now, this ticket is still open, which means investigation will continue.

**Comment by Vozf** [comment]
Edited already, sry

**Comment by tchaton** [comment]
Dear @Vozf.

Adding to @awaelchli point. We encourage anyone to make contributions within Lightning and help contributors to thrive through reviews and mentorship. 
Furthermore, we will never blame anyone for bugs as it is a collective responsibility. This is how we build a trustful and collaborative community. Thanks for editing your message.

**Comment by kaushikb11** [comment]
@Vozf #10762 will fix the issue
