### ISSUE TITLE
Conda package should support something like [extra] in pip.

### ISSUE THREAD

**Issue by FeryET** [PyTorchLightning/pytorch-lightning#10729]
## 🚀 Feature

Pip installer comes with a `pytorch-lightning[extra]` variant. Conda installer should similarly support variants.

### Motivation

Currently the conda package only install the barebone `pytorch-lightning` package. There's no way to install `pytroch-lightning[extra]` on a conda environment without breaking things.

### Pitch

PyTorch apparently has a cpuonly tag for ts conda packages that directs the installer to install only the cpu version. Maybe something similar can be done for lightning?

### Alternatives

Bundling Lightning in 2 packages in conda? I'm out of ideas.

### Additional context

None.

cc @borda

**Comment by tchaton** [comment]
@Borda

**Comment by nils-werner** [comment]
Conda currently does not support extras: https://github.com/conda/conda/issues/7502

The only way to provide this is by providing meta-packages, i.e. `pytorch-lightning-extras`

**Comment by FeryET** [comment]
> Conda currently does not support extras: [conda/conda#7502](https://github.com/conda/conda/issues/7502)
> 
> The only way to provide this is by providing meta-packages, i.e. `pytorch-lightning-extras`

Yeah I found out eventually. Is providing a meta-package

**Comment by Borda** [comment]
yeah found something also here - https://stackoverflow.com/questions/43389520/installing-extras-using-conda

**Comment by FeryET** [comment]
I think there are 2 options:

1. Like torchmetrics, things like `LightningCLI` that introduce some dependencies of their own, should be encapsulated in another package, with their dependencies being clear and concise. Which while we're at the beta phase of CLI, I don't think there will be a strong push for this.
2. The meta-package that you've mentioned. 
3. What about the way PyTorch handles things? Is it not possible? Cpu only flag filters many of the dependencies of PyTorch package, albeit it is a bit breaking to do so because `mamba` cannot install PyTorch's cpuonly without some hacks.

**Comment by rohitgr7** [comment]
you can also do `pip install pytorch-lightning[extra]` inside conda env?

**Comment by FeryET** [comment]
> you can also do `pip install pytorch-lightning[extra]` inside conda env?

It installs a lot of dependencies, which is a big no in a conda environment, and the conda team has always stated that use `pip install` as little as possible in a conda environment.
