### ISSUE TITLE
Why is there no training_epoch_end?

### ISSUE THREAD

**Issue by dscarmo** [PyTorchLightning/pytorch-lightning#1076]
## 🚀 Feature
If i want to calculate and log average statistics for the training epoch, it seems like there is no option to define a "training_epoch_end" in the LightningModule, as there is validation_epoch_end and test_epoch_end.

### Motivation
Seems very intuitive to have this function. I know the on_epoch_end hook exists, but the "outputs" object with training history for that epoch is not available.

### Pitch

Same behavior of validation_epoch_end and test_epoch_end in training.

Sorry if there is something like this already, just started to use Pl. (the master version).

**Comment by williamFalcon** [comment]
didn't get around to it for this release. but feel free to PR it!
we do need it

**Comment by gerardrbentley** [comment]
Do you think more people would want a list of every full batch output (so the results of each training_step / training_step_end if implemented) or the accumulated batch outputs?

**Comment by dscarmo** [comment]
> Do you think more people would want a list of every full batch output (so the results of each training_step / training_step_end if implemented) or the accumulated batch outputs?

I think it could be in the same way the others work, in my understanding they return a list of dicts, with each dict corresponding to the return of an epoch (return of trainining_step or training_end if exists).

**Comment by ethanwharris** [comment]
The only gotcha that we need to watch out for is that all of the collected outputs need to be detached so they don't keep the gradient trees in memory. I would suggest writing a method that recursively traverses the output dictionary and creates a new one with the same elements but all detached, then we can apply this to each output before adding it to the dict. Will also need some good tests to make sure that there aren't any leaks :)

**Comment by isolet** [comment]
The message [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/training_loop.py#L693) suggest using `training_epoch_end`, however, it is not called...

**Comment by thegyro** [comment]
Is `training_epoch_end ` available on the latest release (0.7.2-dev)? The docs seem to suggest so. But I am not able to get it to work (tried logging by returning a 'log' dict).

**Comment by teristam** [comment]
> 
> 
> The message [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/training_loop.py#L693) suggest using `training_epoch_end`, however, it is not called...

Yes, this is quite confusing...

**Comment by awaelchli** [comment]
It is now here thanks to @jbschiratti ! #1357
