### ISSUE TITLE
Rewrite the `Getting Started` section in Lightning docs

### ISSUE THREAD

**Issue by kaushikb11** [PyTorchLightning/pytorch-lightning#10765]
## 📚 Documentation

Part of #7666 

Current content of the `Getting Started` section

```
Getting started

1. Lightning in 2 steps
2. How to organize PyTorch into Lightning
3. Rapid prototyping templates
4. LightningLite - Stepping Stone to Lightning

```

Proposed Structure

```
### Getting Started

1. Quick Start
    1. Intro 
    2. Prepare Data (Data Module) 
    3. Research Code (Lightning Module) 
    4. Abstract Boilerplate (Trainer) 
    5. Maximum Flexibility (Callbacks)
    6. Starter Templates
2. Installation
3.  From PyTorch to Lightning
4. LightningLite - Stepping Stone to Lightning
```

Also, Related #10632 
______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda

**Comment by rohitgr7** [comment]
shouldn't installation go first?

**Comment by rohitgr7** [comment]
hey @kaushikb11 !

this seems to be organized now. https://pytorch-lightning.readthedocs.io/en/latest/
can we close this?
