### ISSUE TITLE
Resolve training type plugin when passed with Accelerator

### ISSUE THREAD

**Issue by kaushikb11** [PyTorchLightning/pytorch-lightning#10775]
### To Reproduce

```python
trainer = Trainer(accelerator=GPUAccelerator(precision_plugin=PrecisionPlugin(), training_type_plugin=DDPPlugin()), gpus=4)
```

At the moment, when training type plugin is passed with Accelerators, attributes such as `parallel_devices`, `cluster_environment` and `sync_batchnorm` are not set to the training plugin and leads to errors.

### Expected behavior

```python
trainer = Trainer(accelerator=GPUAccelerator(precision_plugin=PrecisionPlugin(), training_type_plugin=DDPPlugin()), gpus=4)

# should be equivalent to

training_type_plugin.parallel_devices == [torch.device("cuda", i) for i in self.parallel_device_ids]
training_type_plugin.cluster_environment == LightningEnvironment()
training_type_plugin.sync_batchnorm == False
```

**Comment by awaelchli** [comment]
Thanks @kaushikb11 
This fix would only go into 1.5.x and partially apply to master, but #10416 would change the requirements slightly here as things get inverted.

**Comment by kaushikb11** [comment]
Yup @awaelchli, I did check https://github.com/PyTorchLightning/pytorch-lightning/issues/10648 out before going ahead with the PR.

**Comment by ananthsub** [comment]
@four4fish @kaushikb11 is this solved by the accelerator connector rewrite?

**Comment by four4fish** [comment]
@ananthsub yes it's solved by the rewrite and the follow ups
This is the last one https://github.com/PyTorchLightning/pytorch-lightning/pull/12105
