### ISSUE TITLE
🚀 Memory Sharing of Datasets Across Different Processes

### ISSUE THREAD

**Issue by rusty1s** [PyTorchLightning/pytorch-lightning#10806]
## 🚀 Memory Sharing of Datasets Across Different Processes

PL should be able to share datasets in `DataModule.setup` without requiring to create replicas for every process. In PyTorch, this can be usually achieved via `torch.multiprocessing.Queue`:

> All tensors sent through a `multiprocessing.Queue`, will have their data moved into shared memory and will only send a handle to another process.

https://pytorch.org/docs/stable/notes/multiprocessing.html

### Motivation

Currently, PL cannot handle in-memory datasets elegantly as data needs to be initialized and replicated in `DataModule.setup` for every process. While this may not be a problem for most toy datasets, it is still unnecessary and can become a huge problem once the user operates on a dataset in which only a single instance fits into memory.

### Pitch

I'm proposing to let `prepare_data` be able to pass its data to other processes. All data that is returned in `prepare_data` should be made available in `setup` through a simple `torch.multiprocessing.Queue`:

```python
class DataModule(LightningDataModule):
    def prepare_data(self):
        dataset = MNIST(...)
        return dataset

    def setup(self, stage, *args):
        # In case `prepare_data` returns something, its data will be passed to a queue and is made
        # available to all other ranks in `setup`. For PyTorch tensors, that means that their data will
        # be moved into shared memory and will only send a handle to other processes. 
        self.dataset = args[0]  # All PyTorch tensors in `dataset` are now in shared memory.

        # NOTE: There is no API change involved in this feature.
        # In case nothing is returned in `prepare_data`, `setup` will still be called
        # with a single argument, resembling the old behavior.
```

### Alternatives

* Waiting on `torchstore` (https://github.com/pytorch/pytorch/issues/64932). However, this might be overkill for such a simple mechanism.

**Comment by rusty1s** [comment]
I found a simple solution to my problem:
1. Skip the `setup` and `prepare_data` functions and initialize the data as part of `DataModule.__init__`.
2. Use `Trainer(strategy='ddp_spawn')` to automatically share any `Tensor` data across devices
```python
class DataModule(LightningDataModule):
    def __init__(self):
        self.dataset = MNIST(...)

...

trainer = Trainer(strategy='ddp_spawn', ...)
trainer.fit(model, data_module)
```
@tchaton It might be important to add this information to the doc (in particular, because a lot of GNN people struggle with this). Otherwise, please feel free to close this issue.

**Comment by tchaton** [comment]
Hey @rusty1s,

Would you mind making a PR with a documentation addition and linking this to an example within PyG?

Best,
T.C

**Comment by FarzanT** [comment]
Hi @tchaton, is this method only applicable for `ddp_spawn`? Is it possible to have something similar in other Plugins like DeepSpeed?
Replicating the data based on the number of GPUs drastically increases RAM requirements. A related issue is #8563, which you've already commented on. 
Is there any way to combine the memory-sharing benefits of `ddp_spawn` with the `DeepSpeedPlugin`?

**Comment by loretoparisi** [comment]
@tchaton any clue about the memory issues @FarzanT mentioned? I'm facing the same issue un AWS ec2 g4dn.12xlarge, with Nvidia T4 GPUs, getting on each of the 4 gpu a CUDA OOM
```
CUDA out of memory. Tried to allocate 2.37 GiB (GPU 3; 14.75 GiB total capacity; 14.21 GiB already allocated; 331.06 MiB free; 14.22 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
CUDA out of memory. Tried to allocate 2.37 GiB (GPU 1; 14.75 GiB total capacity; 14.21 GiB already allocated; 331.06 MiB free; 14.22 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
CUDA out of memory. Tried to allocate 2.37 GiB (GPU 0; 14.75 GiB total capacity; 14.21 GiB already allocated; 331.06 MiB free; 14.22 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
CUDA out of memory. Tried to allocate 2.37 GiB (GPU 2; 14.75 GiB total capacity; 14.21 GiB already allocated; 331.06 MiB free; 14.22 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
