### ISSUE TITLE
confusion about self.log() in test_step()

### ISSUE THREAD

**Issue by yc1999** [PyTorchLightning/pytorch-lightning#10814]
### Discussed in https://github.com/PyTorchLightning/pytorch-lightning/discussions/10801

<div type='discussions-op-text'>

<sup>Originally posted by **yc1999** November 29, 2021</sup>
Hi, I wrote following code in `test_step()` method:
```python
    def test_step(self, batch, batch_idx):
        ...
        self.log("test_loss", loss, on_epoch=True, prog_bar=True)
        self.log("test_acc", acc, on_epoch=True, prog_bar=True)
        ...
```
According to the official document, Pytorch Lightning will cache every `test_loss` and `test_acc` value produced in `test_step()` and then do a mean reduction at the end of the test epoch.

Now, I set my `number_of_test_batch=10000`, this means the code will run `test_step()` 10000 times, and there will be a `test_acc_lst` whose len is 10000, and  `test_loss_lst` whose len is 10000, and there will be `sum(test_acc_lst)/10000`  operation, is that right?

finally, when I check the tensorboard, I got following two pics:
![image](https://user-images.githubusercontent.com/37548571/143798676-35693d8d-773f-4395-8e9a-0bcfd7a744de.png)
![image](https://user-images.githubusercontent.com/37548571/143798701-3c82d2f1-1bd4-4cf5-950f-4b995e4bda74.png)

I am very confused why there is a `1500`(1.5K) step appeared in the picture, from the point of mine, it should be 10000 !!!
Can anyone solve this problem, thank you 😥</div>

cc @carmocca @edward-io @ananthsub @rohitgr7 @kamil-kaczmarek @Raalsky @Blaizzy @awaelchli

**Comment by rohitgr7** [comment]
hey @yc1999! 
mind share a reproducible example using [BoringModel](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report/bug_report_model.py) so we can have a better look at the issue?
