### ISSUE TITLE
Lower default progress_bar_refresh_rate

### ISSUE THREAD

**Issue by S-aiueo32** [PyTorchLightning/pytorch-lightning#1083]
## 🚀 Feature
From a conversation in Slack.
In v0.7.1, the default value of  `progress_bar_refresh_rate` is 50, which I think too high.
It is a measure to prevent notebook freezing, however, I believe most users run PL on CLI.
In addition, the high default value confuses the users in `fast_dev_run` because it has only 2 iterations.

So, I suggest the following:
- Set the default value as `1` or `2`. (I think `1` is better.)
- Add doc for notebook users like "you should raise `progress_bar_refresh_rate` to prevent freezing!"

for participants of the conversation: @williamFalcon @Borda @jeremyjordan

**Comment by jeremyjordan** [comment]
Thanks @S-aiueo32! Do you mind submitting a PR with the change?

**Comment by S-aiueo32** [comment]
@jeremyjordan yeah, just a moment 👍
