### ISSUE TITLE
Quickstart gif is larger than Github's allowable view

### ISSUE THREAD

**Issue by ematta** [PyTorchLightning/pytorch-lightning#10844]
## 📚 Documentation

The gif for PyTorch Lightning quickstart is larger than the set width of Github's view for in-repo images. See screenshot for cut off text.

Steps to reproduce:

1. Open the repo in Github Web UI
2. Click on quickstart gif (this will take you to [this](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/docs/source/_static/images/general/pl_quick_start_full_compressed.gif) url)
3. Let the gif play until step 6

![image](https://user-images.githubusercontent.com/220164/144073652-c8afe99e-a26d-4e99-9d13-bd20425a3d5b.png)
______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @rohitgr7

**Comment by carmocca** [comment]
cc @aribornstein

**Comment by tchaton** [comment]
@aribornstein

**Comment by aribornstein** [comment]
Yes its an issue with github changing the way they display image aspect ratios. I'm looking to see what the correct values should be will update when I find them so we can resize.

**Comment by aribornstein** [comment]
One thing to note is you can actually scroll left and right

https://www.loom.com/share/dd981be3765546c3bb8f91c2ce92282c
