### ISSUE TITLE
[CI] Explore GitHub action caching

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#10881]
## Proposed refactor

Use this shiny new thing

https://github.com/actions/setup-python/releases/tag/v2.3.0
https://github.com/actions/setup-python#caching-packages-dependencies

The action itself now can cache

### Motivation

We roll our own cache logic:

https://github.com/PyTorchLightning/pytorch-lightning/blob/619ef7a665244eab2c47c892f7d821360597da9e/.github/workflows/ci_test-full.yml#L41-L43

https://github.com/PyTorchLightning/pytorch-lightning/blob/619ef7a665244eab2c47c892f7d821360597da9e/.github/workflows/ci_test-full.yml#L68-L81

(see other test jobs too)

### Pitch

Remove our logic and use the action
______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @carmocca @akihironitta @borda @justusschock @awaelchli @rohitgr7

**Comment by awaelchli** [comment]
Do you already know some benefits in terms of speed, simplification, reliability etc., or is it just about switching systems?

**Comment by carmocca** [comment]
No idea other than simplification, that's why it's titled "Explore".

**Comment by tchaton** [comment]
Hey @carmocca Yes, this seems interesting. However, It doesn't seem to support weekly caching.

**Comment by Borda** [comment]
> Hey @carmocca Yes, this seems interesting. However, It doesn't seem to support weekly caching.

Yes, that is what I said earlier too, on the other hand all our ci uses caching but not all use weekly reset...

**Comment by akihironitta** [comment]
As mentioned above, the caching feature of `actions/setup-python` action itself cannot reset caches weekly. Closing this in favour of our custom action already added to torchmetrics (https://github.com/PyTorchLightning/metrics/blob/master/.github/actions/caching/action.yml) which will be added to this repo as part of #12545.
