### ISSUE TITLE
Remove precision_plugin pre_dispatch() method

### ISSUE THREAD

**Issue by four4fish** [PyTorchLightning/pytorch-lightning#10884]
## Proposed refactor

There is no logic in pre_dispatch() in any precision_plugins. We can remove the 

### Motivation

Simplify the logic
Eventually we should merge pre_dispatch and dispatch for strategies too. The first step is to remove 

### Pitch

Remove 
https://github.com/PyTorchLightning/pytorch-lightning/blob/038c151b6ee0754adb66714a62bf32b0a389511f/pytorch_lightning/plugins/precision/precision_plugin.py#L204-L205

And references
https://github.com/PyTorchLightning/pytorch-lightning/blob/1d2878523ac36703b851f0646b0ef17f14c582cc/pytorch_lightning/accelerators/accelerator.py#L82

### Additional context

part of #10648 
______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @justusschock @awaelchli @akihironitta @tchaton

**Comment by awaelchli** [comment]
This makes sense I agree, as it will become obsolete even more so after we do step 4 in #10059, because the concept of pre- and post-dispatch will no longer exist.
