### ISSUE TITLE
save_hyperparameters() violates fundamental programming principle

### ISSUE THREAD

**Issue by nils-werner** [PyTorchLightning/pytorch-lightning#10902]
## Proposed refactor

The handing of hyperparameters should be completely overhauled, as the use of [`LightningModule.save_hyperparameters()`](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/core/mixins/hparams_mixin.py#L33) creates a lot of issues with unexpected behaviour. And these issues will only get worse in the future as more features get added or changed.

### Motivation

The method `LightningModule.save_hyperparameters()` violates the most fundamental programming principle of modular programming: [local variables](https://en.wikipedia.org/wiki/Local_variable). The point of local variables is to contain variables and the effect they could have on the codebase, as to prevent unexpected side-effects. If methods start relying on or modifying each others internal state, or start modifying a common global state, the codebase comes more and more tightly coupled and the possibilities of unexpected side-effects grows larger and larger.

`save_hyperparamers()` essentially attempts to find all variables of the scope it was executed in, and get their values without these values haveing been passed to the method.

### Pitch

A different way of tracking hyperparameters should be found. I understand that tracking many variables is a headache, and that passing all of them explicitly is sometimes not an option.

However with new technologies like [Hydra](https://hydra.cc/), many of these manual an unclean steps like `save_hyperparameters()` may not be necessary anymore.

I don't have a more concrete refactoring plan, but I feel like this conversation needs to be started still.

cc @borda @tchaton @justusschock @awaelchli @akihironitta

**Comment by awaelchli** [comment]
Hi @nils-werner 

> as the use of LightningModule.save_hyperparameters() creates a lot of issues with unexpected behaviour. 

Could you list them?

**Comment by tchaton** [comment]
Hey @nils-werner,

A lot of users don't want to commit to a configuration-based system as it adds an overhead and misses language-based flexibility.

This functionality was introduced to provide a boilerplate-free manner to save hyperparameters for new users. 
As you stated above, this is a double edge sword if a user starts getting into more complex patterns for their LightningModule, DataModule, but the added value for new users definitely out-weighted this.

Best,
T.C

**Comment by carmocca** [comment]
Since there's no proposed alternative and using this method is fully optional, I'll go ahead and close this issue.

Note that using configuration-based tools such as Hydra (as you mentioned :P) and the LightningCLI is totally fine to replace this functionality, however, we aren't looking to deprecate `save_hyperparameters` at the moment.
