### ISSUE TITLE
Inconsistency with strategy when using num_processes=1 with ddp

### ISSUE THREAD

**Issue by rohitgr7** [PyTorchLightning/pytorch-lightning#10900]
### To Reproduce

```py
from pytorch_lightning import Trainer


if __name__ == '__main__':

    trainer = Trainer(
        num_processes=1,
        strategy='ddp_find_unused_parameters_false'
    )
    print(trainer.accelerator.training_type_plugin.__class__.__name__)
    
    trainer = Trainer(
        num_processes=1,
        strategy='ddp'
    )
    print(trainer.accelerator.training_type_plugin.__class__.__name__)
```

Prints
```console
DDPPlugin
SingleDevicePlugin
```

Same issue when using ddp_spawn

### Expected behavior
1. both should redirect to `SingleDevicePlugin`.
2. both should redirect to `DDPPlugin`.
3. Raise error

I'd prefer either 2 or 3.

### Environment

- PyTorch Lightning Version (e.g., 1.5.0): master
- PyTorch Version (e.g., 1.10):
- Python version (e.g., 3.9):
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

cc @justusschock @kaushikb11 @awaelchli @ninginthecloud

**Comment by awaelchli** [comment]
And same with
```
trainer = Trainer(num_processes=1, strategy=DDPPlugin())
print(trainer.accelerator.training_type_plugin.__class__.__name__)  # prints DDPPlugin
```

The reasoning there was: If user provides the plugin **instance** explicitly, we use it.

**Comment by justusschock** [comment]
Yes, this is some kind of preference we had to define. However, I think we should make this consistent. That means we either should use the DDPPlugin there (which should also work with 1 proc, it may just be some overhead, right @awaelchli?) or we should error out and ask the user to pass in more consistent arguments.

**Comment by kaushikb11** [comment]
Just checked. It has been resolved by the Accelerator Connector rewrite.

**Comment by four4fish** [comment]
Thanks @kaushikb11 :) i will close this then
