### ISSUE TITLE
Logger API is very inconsistent

### ISSUE THREAD

**Issue by nils-werner** [PyTorchLightning/pytorch-lightning#10901]
## Proposed refactor

Currently, the API across loggers is very inconsistent. They all attempt to implement an common interface pattern by inheriting from `LightningLoggerBase`, but all of them then turn around and violate the interface in one way or another.

I therefore propose to have a really long hard look at the logger APIs, and to figure out a common interface for them all. Internally, all of the loggers naturally work a bit differently and they all have their quirks, but the point of a common interface is to hide these idiosyncrasies from the user.

### Motivation

A common interface for loggers allows the user to quickly and easily replace one logger with another one, and to not worry about each individual type of logger.

### Pitch

 1. Investigate all loggers individually and together
 2. Identify functionality that should be provided by them all
 3. Implement a common interface for these loggers
 4. Implement each individual logger to follow the interface exactly

cc @tchaton @justusschock @awaelchli @borda @edward-io @ananthsub @rohitgr7 @kamil-kaczmarek @Raalsky @Blaizzy @akihironitta

**Comment by ananthsub** [comment]
@nils-werner do you have specific feedback for loggers? We started an investigation of logger APIs here: https://docs.google.com/document/d/1xHU7-iQSpp9KJTjI3As2EM0mfNHHr37WZYpDpwLkivA/edit#heading=h.g6ftsmnvn08y

You can add comments/thoughts here based on what you think is missing.

A difficulty is that the underlying implementations themselves are very different, across Tensorboard, Weights & Biases, MLFlow, CSV loggers, etc. Some support certain features while others don't, and this percolates up to the base Logger API

**Comment by nils-werner** [comment]
The idea of implementing a `LoggerBase` and deriving all specializations from it is to provide a common API for all of them. That way you can inject any logger you like, as long as its interface derives from `LoggerBase` (in compiled languages, this would even be checked at compile time).

However this principle is not being followed, and all loggers implement their own interface. You cannot simply replace one logger with another.
