### ISSUE TITLE
Loose check for batch_size cannot be inferred from current batch

### ISSUE THREAD

**Issue by four4fish** [PyTorchLightning/pytorch-lightning#10929]
## 🐛 Bug

Batch structure is hard to enforce. This PR https://github.com/PyTorchLightning/pytorch-lightning/pull/10541 removed custom batch support. We see a lot of tests failures because of this.

Suggested change:
from 
https://github.com/PyTorchLightning/pytorch-lightning/blob/dc57691f819f10a7c9c322acc863619223a227ea/pytorch_lightning/utilities/data.py#L77-L80

to 
```
    if batch_size is None:
        raise warning(msg)
        batch_size = -1

    return batch_size
```

### Environment

- PyTorch Lightning Version (e.g., 1.5.0):
- PyTorch Version (e.g., 1.10):
- Python version (e.g., 3.9):
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

cc @tchaton @carmocca @edward-io @ananthsub

**Comment by rohitgr7** [comment]
It never had correct custom batch support. It just silently used to use 1 all the time which would end up aggregating the logged values incorrectly. Now it has a strict rule too to only auto infer the batch_size when it needs to else for custom batches if user provides one with `self.log(..., batch_size=...)`, it doesn't auto infer it.

**Comment by four4fish** [comment]
> It never had correct custom batch support. It just silently used to use 1 all the time which would end up aggregating the logged values incorrectly. Now it has a strict rule too to only auto infer the batch_size when it needs to else for custom batches if user provides one with `self.log(..., batch_size=...)`, it doesn't auto infer it.

This is a breaking change caused a lot of failures which is hard to fix at once. Should it be backward compatible? 

Not every user use the logging and they can have their own implementation. Should we fail entire training for this? It's also very unclear from the doc, when the batch_size should be specified.
https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_module.html?highlight=log#log

**Comment by rohitgr7** [comment]
> This is a breaking change caused a lot of failures which is hard to fix at once. Should it be backward compatible?

couldn't find a way to make this backward compatible.

> Not every user use the logging and they can have their own implementation. Should we fail entire training for this? It's also very unclear from the doc, when the batch_size should be specified.

It doesn't compute the batch_size of no built-in logging is used. Docs can be updated.

**Comment by four4fish** [comment]
> couldn't find a way to make this backward compatible.
Could we raise warning for now and change to error in 1.7 to leave more time for user to migrate?

**Comment by rohitgr7** [comment]
> > couldn't find a way to make this backward compatible.
> 
> Could we raise warning for now and change to error in 1.7 to leave more time for user to migrate?

yeah, we can, but not a big fan of this. Might make lightning generate incorrect aggregations for users for another 5 months in case they ignore the warning. Because we usually raise warning for the cases where things work fine but not in an optimal way but here if we put a warning it will still end up generating incorrect metrics.

**Comment by four4fish** [comment]
Yeah make sense, correctness is more important than backward compatibility. Thank you @rohitgr7 !
