### ISSUE TITLE
Typehinting for LightningArgumentParser is broken.

### ISSUE THREAD

**Issue by FeryET** [PyTorchLightning/pytorch-lightning#10974]
## 🐛 Bug

I am using vscode, with a Pylance backend, and it cannot find the static type of `LightningArgumentParser` being linked to `jsonargparse.ArgumentParser`. 

### To Reproduce

Just create a `cli.py` and open it in vscode!

```
from pytorch_lightning.utilities.cli import LightningCLI, LightningArgumentParser


class MyCLI(LightningCLI):

    def add_default_arguments_to_parser(self, parser: LightningArgumentParser) -> None:
        return super().add_default_arguments_to_parser(parser)
```

### Expected behavior

Pretty obvious.

### Environment
```
* CUDA:
        - GPU:
        - available:         False
        - version:           None
* Packages:
        - numpy:             1.21.2
        - pyTorch_debug:     False
        - pyTorch_version:   1.10.0
        - pytorch-lightning: 1.5.4
        - tqdm:              4.62.3
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.9.7
        - version:           #45~20.04.1-Ubuntu SMP Wed Nov 10 10:20:10 UTC 2021
```

### Additional context

I can think this happens because of this portion in `pytorch_lightning/utilities/cli.py`
```
if _JSONARGPARSE_AVAILABLE:
    from jsonargparse import ActionConfigFile, ArgumentParser, class_from_function, set_config_read_mode
    from jsonargparse.actions import _ActionSubCommands
    from jsonargparse.optionals import import_docstring_parse

    set_config_read_mode(fsspec_enabled=True)
else:
    ArgumentParser = object
```

cc @carmocca @mauvilsa

**Comment by carmocca** [comment]
Hi, I followed your steps but I don't see any complaint by VSCode

<img width="1291" alt="Screenshot 2021-12-14 at 22 54 14" src="https://user-images.githubusercontent.com/11067892/146085475-ae6a8de8-e3af-4d16-abb6-8f9d36607d6e.png">

**Comment by carmocca** [comment]
Unfortunately, we must conditionally import it as `jsonargparse` is not a required dependency for the project. There's no solution as far as I know so I'll close this. If you know one, feel free to comment.

**Comment by mauvilsa** [comment]
A possible solution could be:

```python
if _JSONARGPARSE_AVAILABLE:
    ...
else:
    locals()['ArgumentParser'] = object
    locals()['Namespace'] = object
```
