### ISSUE TITLE
TPU - no op reports

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#1098]
If your TPU training is slower, please share the  link to the bug report here so the xla team can  take a look.

1. Use [this link](https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#using-debug_runpy-to-collect-debug-information) to generate the report.
2. upload to dropbox or gcloud or something.
3. post link here

**Comment by bkkaggle** [comment]
Adafactor on pytorch/xla is slow, it takes ~2 min for the first two iterations then ~5s/iteration for a full forward+backwards pass compared to SGD, which can do ~13 iterations/second.

Here's the colab notebook to reproduce this and create the debugging report:

https://colab.research.google.com/drive/1DF0pnIjsKiq9drUTskeg2dZL8jnFjolO

**Comment by Borda** [comment]
@bkkaggle any update back from XLA issue?

**Comment by bkkaggle** [comment]
Yes, with a few code changes to replace python math operations with xla operations it runs a lot faster, almost to the same speed as the TF version.

**Comment by Borda** [comment]
@bkkaggle sounds cool! Mind draft a PR?
