### ISSUE TITLE
PyTorchProfiler crashes without exception

### ISSUE THREAD

**Issue by twsl** [PyTorchLightning/pytorch-lightning#10983]
## 🐛 Bug

Program crashes after a few steps when I added PyTorchProfiler without any exception.

### To Reproduce

I couldn't reproduce the bug on Colab, or my Ubuntu machine, so I'd say it is eigher related to my hardware or GPU in docker on windows in general.

I used the boring model with the following trainer:
```python
from pytorch_lightning.profiler import PyTorchProfiler
from pytorch_lightning.loggers import TensorBoardLogger

log_dir = os.path.join(os.getcwd(), "logs")
model = BoringModel()
trainer = Trainer(
    accelerator="auto",
    devices="auto",
    limit_train_batches=1,
    limit_val_batches=1,
    limit_test_batches=1,
    num_sanity_val_steps=0,
    max_epochs=1,
    enable_model_summary=False,
    logger=[
        TensorBoardLogger(save_dir=log_dir, name="BoringModel", version="0.0.1", log_graph=False)
    ],
    profiler=PyTorchProfiler(dirpath=log_dir, filename="profiler"),
)
```

### Expected behavior

Work just fine without crash

### Environment

- PyTorch Lightning Version (e.g., 1.5.0): 1.5.5
- PyTorch Version (e.g., 1.10): 1.10
- Python version (e.g., 3.9): 3.8.12
- OS (e.g., Linux): Linux (Docker) on Windows
- CUDA/cuDNN version: 11.5/8
- GPU models and configuration: 1080
- How you installed PyTorch (`conda`, `pip`, source): pip
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

I know this is probably an edge case and nothing important, maybe even out of scope. Maybe someone can try to reproduce it on their machine? I'm just looking for pointers how to debug this and to alert the community.

cc @carmocca @kaushikb11 @ninginthecloud @rohitgr7

**Comment by carmocca** [comment]
Can you share the error stacktrace?

**Comment by twsl** [comment]
let me check a few things to see if i can create one.

**Comment by twsl** [comment]
I just noted a `Floating point exception` being printed to stdout. Any suggstion how I could get additional info?

**Comment by carmocca** [comment]
Sharing the complete error stacktrace would be a start :)

**Comment by twsl** [comment]
how do i recover the stack trace after it crashed? it doesnt stop in a debugger and doesnt print any additional info.

**Comment by carmocca** [comment]
So your program is normally running and you just get the message "Floating point exception", is that correct?

If that's the case, then this exception must be some sort of segfault coming from C++-land.

If you can consistently reproduce, I suggest trimming down code until you find the minimum script that reproduces the problem. Then you can share it here, but it's likely this is an issue that Lightning cannot fix.

**Comment by twsl** [comment]
Its just the code in the initial commit. I agree, that this is nothing Lightning can fix.
