### ISSUE TITLE
⚙️ Limit required versions

### ISSUE THREAD

**Issue by k4black** [PyTorchLightning/pytorch-lightning#10992]
## 🚀 Feature

Limit required versions according to [semantic versioning](https://semver.org/) (e.g `tqdm >=4.41.0, <5.0.0`)

### Motivation

Not fixed dependencies (like `tqdm >=4.41.0`) may lead to unexpected errors during major version upgrade (with pkg api change).

This errors __can not__ be caught in time (using ci tests), as it can occur between `pytorch-lightning` releases.

### Pitch

So, the majority (where it's possible to do) of the requirements should be limited with major version. 'Beta-stage' projects (`0.a.b`) may be limited with minor version. 

For example, here:
https://github.com/PyTorchLightning/pytorch-lightning/blob/01f5f99919e9828c088ba4a39e6d492f19f49c44/requirements.txt#L3-L7

Versions can be fixed as:
```
 numpy >=1.17.2, <2.0.0
 torch >=1.7.*, <2.0.* 
 future >=0.17.1, <1.18.0
 tqdm >=4.41.0, <5.0.0  
 PyYAML >=5.1, <7.0  # because 6.0 already in production and works well
```

#### Note

A similar error can occur with a minor update, if the package provider does not follow semantic versioning and break backward compatibility in minor update.   
But fixed versions significantly reduces the chances of its occurrence

### Alternatives

Versions can remain unfixed.  

#### Pros: 
* More flexibility, user and integrate this pkg with more versions  
* No additional efforts for checking version upgrade ([dependency bot](https://github.com/dependabot) can help)

#### Cons:
* Unexpected behaviour during major versions update 

### Additional context

cc @borda

**Comment by Borda** [comment]
well on other hand you restrict touse PL with any future version even it is fully compatible, so basically we would release PL 1.6 when PT 1.11 will be out, but ban using PT 1.12... is it what you suggest?

**Comment by k4black** [comment]
No, I should highlight that this limit Major version update.  

For example, Now we have no limit (`torch >=1.7.*`). In the case of PyTorch update to `2.0.*` highly likely it'll break backward compatibility. So users with uptodate version of PL will be allowed to install it (`2.0.*` is ok for current requirements) and will get an error.

I think, it's better to limit users (having `<2.0.*`) for some time from using PT2+PL and getting errors, till PL will get backward compatibility and set a new limit of `torch >=1.7.*,<3.0.*`.

P.S. In this case PyTorch is not the best examples, cause it's top-1 requirements here and major updates are expected. This error is more likely to occur with small utils libs such as `tqdm` or `PyYAML`
