### ISSUE TITLE
manual_optimization with ddp is slower than naive pytorch

### ISSUE THREAD

**Issue by azraelkuan** [PyTorchLightning/pytorch-lightning#11003]
### To Reproduce

when using manual_optimization with ddp, it will raise a warning `UserWarning: From PyTorch 1.7.0, Lightning ``manual_optimization`` needs to set ``find_unused_parameters=True`` to properly work with DDP.`, but ineed we do not need to set this to True, it will make trianing slower than False.
```
Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
```

### Expected behavior

do not force find_unused_parameters=True when using manual_optimization  with ddp
![image](https://user-images.githubusercontent.com/23380152/145324516-bae135d0-b112-4607-a0a8-bfa8226f15a1.png)

### Environment

- PyTorch Lightning Version (e.g., 1.5.0): 1.5.3
- PyTorch Version (e.g., 1.10): 1.8.0
- Python version (e.g., 3.9): 3.8
- OS (e.g., Linux): linux
- CUDA/cuDNN version: 10.2
- GPU models and configuration: 
- How you installed PyTorch (`conda`, `pip`, source): conda
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

**Comment by ananthsub** [comment]
If you want the default changed, here is the issue to discuss it. 

https://github.com/PyTorchLightning/pytorch-lightning/issues/7330

In the meantime you can specify `Trainer(strategy=DDPPlugin(find_unused_parameters=False)`

**Comment by azraelkuan** [comment]
for `Trainer(strategy=DDPPlugin(find_unused_parameters=False)`, u can see pl will force to set it True in core code.

**Comment by awaelchli** [comment]
Here also a [pointer to the docs](https://pytorch-lightning.readthedocs.io/en/latest/guides/speed.html#when-using-ddp-plugins-set-find-unused-parameters-false).

**Comment by tchaton** [comment]
Hey @azraelkuan,

You can try to override this file, set the value to False and see it works with latest PyTorch Version. 
I forced the value to be True in the past as it would break on the PyTorch side. Maybe they resolve it.

Best,
T.C

**Comment by carmocca** [comment]
We need to check again if this is still a problem

**Comment by azraelkuan** [comment]
I have tried to use naive pytorch to re-implement, with find_unused_parameters as False, it will speed up 10%.

**Comment by jule-c** [comment]
Hi, I think this is still an issue for manual optimisation, as pl forces me to set find_unused_parameters to True, although there aren't unused parameters (without DDP it's working fine).

**Comment by awaelchli** [comment]
> as pl forces me to set find_unused_parameters to True

How does pl force you to set this? 
It would help a lot if you could you please open an issue with description, repro code and version information.

**Comment by carmocca** [comment]
> pl forces me to set find_unused_parameters to True

@jule-c This was fixed in https://github.com/Lightning-AI/lightning/pull/12425 which was part of the 1.6 release
