### ISSUE TITLE
Remove trainer._device_type in favor of check Accelerator class

### ISSUE THREAD

**Issue by four4fish** [PyTorchLightning/pytorch-lightning#11002]
## Proposed refactor

Follow up for #11001: Generalize internal checks for precision plugin type, training type, accelerator type

### Motivation

Code simplification 

### Pitch

After #11001, _device_type is not needed anymore

```
    @property
    def _device_type(self) -> _AcceleratorType:
        return self._accelerator_connector.
```

Instead in tests and where we need check device type, use
```
isinstance(trainer.accelerator, XAccelerator)
```

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @justusschock @awaelchli @akihironitta

**Comment by awaelchli** [comment]
Hey @four4fish 
Thanks for looking at this.
This is not something we need to deprecate because it's already declared as internal, not exposed to user. 
It can simply be removed together with the last part of #11001

**Comment by four4fish** [comment]
Solved by https://github.com/PyTorchLightning/pytorch-lightning/pull/11992
