### ISSUE TITLE
enable progress bar = update freq 1

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#1102]
i think we can collapse two args. 
- remove enable progress bar arg. 
- disable the progress bar when update freq = 0

**Comment by gerardrbentley** [comment]
Was pretty straightforward to remove from Trainer args that the user has to remember, but I didn't remove the attribute so the Train / Eval loops can check it clearly (and avoid divide by zero error when checking to update)
