### ISSUE TITLE
Github 0.7.1 release

### ISSUE THREAD

**Issue by oplatek** [PyTorchLightning/pytorch-lightning#1103]
If I do install `pip install pytorch-lightning`  I get version `0.7.1` however, there is no official 0.7.1 release on Github. 

Is it intentional?

Note: that there is 0.7.1 git tag

**Comment by oplatek** [comment]
The tags 0.7.0 and 0.7.1 are hidden under `Two newer releases` in the Github release section

**Comment by Borda** [comment]
I do not see anything newer the `0.7.1` https://github.com/PyTorchLightning/pytorch-lightning/releases

**Comment by oplatek** [comment]
now it is ok/fixed/clear: 5 days ago there was a button Show two newer releases (at that time the two newer releases were 0.7.0 and 0.7.1 tags)
