### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by JamieSlome** [PyTorchLightning/pytorch-lightning#11045]
Hey there!

I belong to an open source security research community, and a member (@oivrip) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by justusschock** [comment]
Hi @JamieSlome , as you see @Borda already started to put together such a document. We are internally discussing which mail address to put there. For now the easiest way would probably be to talk to @tchaton @Borda or me on our slack directly.

**Comment by JamieSlome** [comment]
@justusschock - thanks for the swift response! ⚡ 

Our system will automatically send further details to the elected e-mail in your `SECURITY.md`, however, if you want to view the private report, you can view it here:

https://huntr.dev/bounties/31832f0c-e5bb-4552-a12c-542f81f111e6/

Only maintainers with write access will have permission to view the contents!

**Comment by carmocca** [comment]
Thank you @JamieSlome, I've validated the report. As the fix should be simple, feel free to open a PR with it.
