### ISSUE TITLE
Set `enable_progress_bar=False` in standalone tests

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#11083]
## Proposed refactor

The output produced by the standalone tests is unfiltered and produces 1000's of lines due to the progress bar being turned on. This is not needed for 99% - 100% of tests. For regular tests this is not an issue since the tests get batched and the output is not printed in verbose.

### Motivation

Easier to read and scroll the test output logs

### Pitch

Set

`Trainer(enable_progress_bar=False) 
`
for all tests that have

`@RunIf(standalone=True)`

as the marker.
Additionally, could also turn off the model summary.

### Additional context

Happy holidays

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.
``

cc @borda @justusschock @awaelchli @akihironitta

**Comment by ananthsub** [comment]
I'm assuming many tests could also disable these flags for faster runs and less verbose logs: Trainer(enable_checkpointing=False, logger=False, enable_model_summary=False)

**Comment by carmocca** [comment]
We could write an AST parser that looks for `Trainer` in our tests and adds these automatically, pre-commit will fix the formatting later. Or even a simple python script looking for `Trainer()` would work.

Then we remove the arguments for the failing tests that require different behavior.

**Comment by carmocca** [comment]
I opened #11113 with a potential implementation, but it's 4.5k additions

One filtering possibility would be to add these only to Trainer instances that set a `max_epochs=...` value.

**Comment by carmocca** [comment]
Comparing the runtime of the CPU Conda tests for #11113 and one of masters' commits, it doesn't seem like this provides any substantial speedup at all. We would need to compare N runs and take averages to properly see the magnitude.
