### ISSUE TITLE
Confusing code example for DeepSpeed activation checkpointing

### ISSUE THREAD

**Issue by lemairecarl** [PyTorchLightning/pytorch-lightning#11081]
## 📚 Documentation

In the section here:

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/docs/source/advanced/advanced_gpu.rst#deepspeed-activation-checkpointing

At line 557, a code comment says "Use the DeepSpeed checkpointing" while the code uses `torch.utils.checkpoint.checkpoint`, and below, it says the same thing, "Use the DeepSpeed checkpointing", but now it uses  `deepspeed.checkpointing.checkpoint`.

I am not sure what is the right correction here, since I don't have experience with those tools. Should we replace `torch.utils.checkpoint.checkpoint` with `deepspeed.checkpointing.checkpoint` at line 557 ?

Another issue is that the first part refers to `self.layer_h` which does not exist. I think it would make more sense to say `self.block_1`.

cc @borda @SeanNaren @awaelchli

**Comment by awaelchli** [comment]
Oh yes! Good catch. @SeanNaren  was cooking dinner for the Lightning team and a bit of sauce spilled onto the docs draft and this is how the typo came to be. 

It should be deepspeed.checkpointing.checkpoint I think.

Btw, a nicer version of the docs can also be accessed [here](https://pytorch-lightning.readthedocs.io/en/latest/advanced/advanced_gpu.html?).

Are you interested to send a pull request with the fix?

**Comment by lemairecarl** [comment]
Sean! Less cooky, more proofready!
lol

**Comment by awaelchli** [comment]
Thank you @lemairecarl for taking care of it!
