### ISSUE TITLE
Enable artifact logging for mlflow logger

### ISSUE THREAD

**Issue by HarshSharma12** [PyTorchLightning/pytorch-lightning#1113]
## 🚀 Feature
mlflow provides the ability to [log artifacts](https://www.mlflow.org/docs/latest/python_api/mlflow.html#mlflow.log_artifact) (a local file or directory). However, the MLFlowLogger class does not have the wrapper method for this functionality. 

### Motivation
I always use the log_artifacts method of mlflow to log things like the last weights file for the run, confusion matrix image for the last set of weights, etc. It would be great to have these features integrated with the lightning logger.

### Pitch
I'm currently using the mlflow logger and not the pytorch lightning's MLFlowLogger class but having this functionality would make the migration better.

### Additional context
1) https://www.mlflow.org/docs/latest/python_api/mlflow.html#mlflow.log_artifact
2) https://www.mlflow.org/docs/latest/python_api/mlflow.html#mlflow.log_artifacts
3) https://www.mlflow.org/docs/latest/concepts.html#referencing-artifacts

**Comment by williamFalcon** [comment]
can’t you just use the inner experiment object directly?

**Comment by HarshSharma12** [comment]
Yeah, I realized it later that that functionality exists. I'm using that now.

**Comment by skmatz** [comment]
@HarshSharma12 Hi! I am facing the same problem. Can you tell me exactly how you got the results in artifacts using the internal `experiment` object?

**Comment by HarshSharma12** [comment]
@skmatz I'm using `logger.experiment.log_artifact(logger.run_id, artifact_pth)`  to log the artifacts. 

You might also want to refer to this - https://github.com/mlflow/mlflow/issues/884

**Comment by skmatz** [comment]
@HarshSharma12 Got it, thanks!

**Comment by sachinruk** [comment]
For anyone coming from [the official docs about pytorch-lightning + mlflow](https://pytorch-lightning.readthedocs.io/en/0.6.0/pytorch_lightning.logging.mlflow.html) and was banging their heads on how to save the model. @HarshSharma12's last comment was the trick to get it working.

In my case, it was: 
```python
mlf_logger.experiment.log_artifact(mlf_logger.run_id, "./4/0d0f1c3c431548e9af1ac719f54d9088/checkpoints/epoch=6-step=2463.ckpt")
```

**Comment by artuntun** [comment]
this solution is not working for me. I have two loggers, mlflow and tensorboard so when I access `self.logger.experiment` I get a list. Accessing the first item returns me a `MlflowClient` object and not a `MLFlowLogger`. This means that I can't access the `run_id` property by `self.logger.experiment[0].run_id`

Any idea why is not returning a `MLFlowLogger` object. 
My Trainer looks like this

```python
AVAIL_GPUS = min(1, torch.cuda.device_count())
logger1 = TensorBoardLogger("./logs/tb_logs", name="my_model")
mlf_logger = MLFlowLogger(experiment_name="default", tracking_uri="./logs/mlruns")
trainer = Trainer.from_argparse_args(args, gpus=AVAIL_GPUS, progress_bar_refresh_rate=20,
                                     callbacks=callbacks, log_every_n_steps=5, logger=[mlf_logger, logger1])
trainer.fit(model, dm)
```

**Comment by felixsg** [comment]
@artuntun , something like this should work to get the right logger: https://github.com/ashleve/lightning-hydra-template/blob/390f42f7635eae6b93c082c177d40ae1cdd6e5f2/src/callbacks/wandb_callbacks.py#L16

**Comment by vilozio** [comment]
> For anyone coming from [the official docs about pytorch-lightning + mlflow](https://pytorch-lightning.readthedocs.io/en/0.6.0/pytorch_lightning.logging.mlflow.html) and was banging their heads on how to save the model. @HarshSharma12's last comment was the trick to get it working.
> 
> In my case, it was:
> 
> ```python
> mlf_logger.experiment.log_artifact(mlf_logger.run_id, "./4/0d0f1c3c431548e9af1ac719f54d9088/checkpoints/epoch=6-step=2463.ckpt")
> ```

Thank you for a hint. I've tried to do it in a more generic way

```python
mlf_logger = MLFlowLogger(...)
trainer = Trainer(..., logger=mlf_logger)
...
model_path = (
    trainer.checkpoint_callback.last_model_path
    or trainer.checkpoint_callback.best_model_path
)
mlf_logger.experiment.log_artifact(mlf_logger.run_id, model_path)
```
