### ISSUE TITLE
Improve the evaluation results verbose look

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#11139]
## 🚀 Feature

When evaluation `trainer.validate(verbose=True)` (or `test`) finishes, we print a dictionary with the results obtained

```python
--------------------------------------------------------------------------------
DATALOADER:0 TEST RESULTS
{'test_loss': -3.4134674072265625}
--------------------------------------------------------------------------------
```

https://github.com/PyTorchLightning/pytorch-lightning/blob/860959fb3fc9d54c3d65984d64bfa391f68bc51b/pytorch_lightning/loops/dataloader/evaluation_loop.py#L275-L288

### Pitch

Propose and implement a new and nicer format. For example, you can check if https://github.com/willmcgugan/rich is installed and then use it.

Please, comment in this issue first about what's your idea is before jumping on a PR.

### Motivation

The current output is very barebones, both ugly and not easy to parse.

### Alternatives

Don't do it
______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @awaelchli

**Comment by AndresAlgaba** [comment]
Here is a suggestion to create rich tables which present the metrics with the corresponding values:

```python
  def _print_results(self, results: List[_OUT_DICT], stage: RunningStage) -> None:
      try:
          from rich.console import Console
          from rich.table import Table

          console = Console()

          console.rule(f"[bold red]{stage.upper()} RESULTS")

          for i, metrics_dict in enumerate(results):

              table = Table(title=f"DATALOADER:{i} {stage.upper()} RESULTS", width=35)
              table.add_column("Metric", justify="center", style="cyan")
              table.add_column("Value", justify="center", style="magenta")

              for k, v in metrics_dict.items():
                  v = (v.item() if v.numel() == 1 else v.tolist()) if isinstance(v, torch.Tensor) else v
                  table.add_row(f"{k}", f"{v}")

              console.print(table)

              console.rule()
      except ModuleNotFoundError:
          from pprint import pprint

          print("-" * 80)
```

With the following result for example:
```python
───────────────────────────────────────────────────── TEST RESULTS ─────────────────────────────────────────────────────
     DATALOADER:0 TEST RESULTS
┏━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┓
┃  Metric   ┃        Value        ┃
┡━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━┩
│ test_loss │ -0.381743311882019… │
│ test_acc  │ 0.3817433118820198… │
└───────────┴─────────────────────┘
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by carmocca** [comment]
Hi @AndresAlgaba! Thanks for looking into this.

I would personally suggest getting rid of the separators above and below the table.

Also, do you think we could have the following in the case of multiple dataloaders?

```
┏━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┓
┃  Metric   ┃     DataLoader 0    ┃     DataLoader 1    ┃
┡━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━┩
│ test_loss │ -0.381743311882019… │ -0.381743311882019… │
│ test_acc  │ 0.3817433118820198… │ 0.3817433118820198… │
└───────────┴─────────────────────┴─────────────────────┘
```

which removes the need for the `DATALOADER:0 TEST RESULTS` row separation.

You can use the following import to check if `rich` is available

```python
from pytorch_lightning.utilities.imports import _RICH_AVAILABLE

if _RICH_AVAILABLE:
    ...
```

Also, a not-so-nice alternative implementation should be provided when rich is not available. You should also try thinking how you would implement it!

**Comment by AndresAlgaba** [comment]
Hi @carmocca, sure! Will look into this. Should I already create a PR, or keep iterating here?

**Comment by carmocca** [comment]
> Should I already create a PR

Yes, sure!
