### ISSUE TITLE
Move `TrainerCallbackHookMixin.on_save/load_checkpoint`  to `CheckpointConnector` and rename for clarity

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#11165]
_Originally posted by @ananthsub in https://github.com/PyTorchLightning/pytorch-lightning/pull/11148#discussion_r771886148_

## Proposed refactor
* Move `TrainerCallbackHookMixin.on_save/load_checkpoint` to `CheckpointConnector` as functions
* Rename them to something like `call_callbacks_on_save_checkpoint` and `call_callbacks_on_load_checkpoint`

### Motivation

* We are planning to deprecate `TrainerCallbackHookMixin` in #11148. However there are still two methods in there that we need to keep: `on_save_checkpoint` and `on_load_checkpoint`
* `CheckpointConnector` is a more logical place for these functions, since that is where all of the checkpointing code lives.
* Also, the current naming is confusing because it doesn't convey that we are calling the hook on all of the callbacks

### Pitch
* Move the functions to `CheckpointConnector` and rename them to `call_callbacks_on_save_checkpoint` and `call_callbacks_on_load_checkpoint`
* Deprecate the original methods in `TrainerCallbackHookMixin` as part of #11148

cc @justusschock @awaelchli @akihironitta @ananthsub @ninginthecloud @daniellepintz

**Comment by carmocca** [comment]
Based on your previous connector reviews, is the `CheckpointConnector` going to stay long-term?

If yes, then this makes sense to me.

**Comment by daniellepintz** [comment]
Based on previous connector reviews, the plan for the `CheckpointConnector` is to convert it to utility functions, so I think this aligns well.

**Comment by carmocca** [comment]
In that case, shouldn't we move it directly to the utility?

And wouldn't this utility function live in `trainer.py` then?

**Comment by daniellepintz** [comment]
sorry, I'm a bit confused by both questions.

> In that case, shouldn't we move it directly to the utility?

What do you mean by "to the utility"? Do you mean directly create a utility function from `on_save/load_checkpoint`? If so, yes I agree.

> And wouldn't this utility function live in trainer.py then?

Why would it live in trainer.py rather than a separate checkpointing utilities class?

**Comment by ananthsub** [comment]
@carmocca I think it makes sense to split this up into 2 stages:
1. Move the logic to save and load callback states from CallbackHookMixin to CheckpointConnector (this also makes the deprecations around #11148 easier, which is the immediate motivation). 

2. Figure out the refactoring of checkpoint connector separately

For 2), I don't the approach take for the other connectors of removing the trainer reference will work here because the connector needs to have access to all objects that could contribute to the checkpoint struct being saved. Only the trainer has that right now, and it would make sense to then move these methods to the trainer over time. But we should discuss the refactoring of the overall checkpoint connector in a dedicated issue

**Comment by carmocca** [comment]
> Do you mean directly create a utility function from `on_save/load_checkpoint`?

Yes

> Why would it live in trainer.py rather than a separate checkpointing utilities class?

Because we expect only the trainer to call it. Same reasoning as https://github.com/PyTorchLightning/pytorch-lightning/pull/11155/files/03969591d2ab2665c3e703eb6e41f0b6ad2d3db8#r771950283
Perhaps not directly in `trainer.py` but in file in the same directory.

> For 2), I don't the approach...

Sounds good.

**Comment by daniellepintz** [comment]
I agree we should split it up into the two stages @ananthsub described. And @carmocca I also agree it should live in the trainer, so we can avoid a hacky if statement like in https://github.com/PyTorchLightning/pytorch-lightning/blob/08e661ff7266f298a6e904fa04931698e20b2b89/pytorch_lightning/trainer/trainer.py#L1553-L1563

**Comment by daniellepintz** [comment]
If it's just a question of moving these two methods to the Trainer, that can easily be done as part of #11148

**Comment by daniellepintz** [comment]
I agree we should split this up into the two stages @ananthsub mentioned. And @carmocca I agree we should just put this directly into the trainer. I think I can just add it into #11148 as it fits logically.

**Comment by daniellepintz** [comment]
Sorry for all the thrash, I have created #11179 with what I envision, please lmk what you think @carmocca @ananthsub
