### ISSUE TITLE
Hyperparameter Search

### ISSUE THREAD

**Issue by ochipara** [PyTorchLightning/pytorch-lightning#1117]
Hi,
It looks like the hyperparameters search example is broken (https://github.com/optuna/optuna/blob/master/examples/pytorch_lightning_simple.py). Since this is such a common task, is there any example that documents how to properly integrate with a library like optuna or ray tune?

Thanks!

**Comment by Borda** [comment]
it seems that you are referring bug in another repository... Can you check with authors of `optuna` what version of Lightning are they using/require?

**Comment by festeh** [comment]
Attempted to fix the example [here](https://github.com/optuna/optuna/pull/1013/). Feel free to ask me if it wouldn't work for you.

**Comment by Borda** [comment]
cool, thx @festeh! feel free to reopen if you would need anything from Lightning side :]
