### ISSUE TITLE
Scalars generated by DeviceStatsMonitor should be grouped in tensorboard

### ISSUE THREAD

**Issue by semaphore-egg** [PyTorchLightning/pytorch-lightning#11176]
### Motivation

Currently, all scalars generated by DeviceStatsMonitor are directly listed in scalar pages of tensorboard.  Half of them start with prefix of "on_train_batch_start", others with "on_train_batch_end". All the keys are joined using dots. Something like:
```
on_train_batch_start.active.all.allocated
on_train_batch_start.active.all.current
on_train_batch_start.active.all.freed
```
In such format, tensorboard will show each scalar value in a seperate entry. This could pollute the scalars tab seriously since there are hundreds of items. 

### Advice
To group the scalars together, one solution could be simply replace the first dot with a slash. So the new names of scalars becomes:

```
on_train_batch_start/active.all.allocated
on_train_batch_start/active.all.current
on_train_batch_start/active.all.freed
```
This time, all scalars are organized into two groups and only two top entries (on_train_batch_start/on_train_batch_end) will be shown in scalars tab of tensorboard.

### Solution

Noticed that the prefix "on_train_batch_start" and "on_train_batch_end" are added by helper function prefix_metrics_keys.

https://github.com/PyTorchLightning/pytorch-lightning/blob/b1baf460d900a1e9982823b4428a3cd108a59d06/pytorch_lightning/callbacks/device_stats_monitor.py#L83

```
def prefix_metrics_keys(metrics_dict: Dict[str, float], prefix: str) -> Dict[str, float]:
    return {prefix + "." + k: v for k, v in metrics_dict.items()}
```
Maybe we can make a minor change like following:
```
def prefix_metrics_keys(metrics_dict: Dict[str, float], prefix: str) -> Dict[str, float]:
    return {prefix + "/" + k: v for k, v in metrics_dict.items()}   # "." -> "/"
```
In this way, minimum code changes are made.

I am not familiar with W&B or other loggers. This suggestion is only based on tensorboard.

#### Before refactor
![Screenshot from 2021-12-21 00-12-47](https://user-images.githubusercontent.com/56214204/146798104-2fc9c4fc-9c54-4a7f-a193-18764ce070e1.png)

#### After refactor
![Screenshot from 2021-12-21 00-09-34](https://user-images.githubusercontent.com/56214204/146797690-b1955172-9b44-4264-9d41-1361c56f17b8.png)

cc @justusschock @awaelchli @akihironitta @kaushikb11

**Comment by ananthsub** [comment]
Could this use the LightningLogger `group_separator` property: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/loggers/base.py#L348-L351

**Comment by semaphore-egg** [comment]
> Could this use the logger's `group_separator` property:
> 
> https://github.com/PyTorchLightning/pytorch-lightning/blob/08e661ff7266f298a6e904fa04931698e20b2b89/pytorch_lightning/loggers/base.py#L348-L351

Cool to see that we have a way to get the separator.

It seems replacing dot with group_separator ('/') shall be the default implementation for prefix_metrics_keys.

Currently I have to dynamically replace prefix_metrics_keys with my own implementation to get desired effect, which
is not elegant. 

Is there a better way to solve this problem.

**Comment by ananthsub** [comment]
@semaphore-egg the attached PR should resolve the issue without your needing to patch the callback

**Comment by semaphore-egg** [comment]
Waiting to see the pr in next weekly release.

> @semaphore-egg the attached PR should resolve the issue without your needing to patch the callback

Waiting to see the pr in following weekly release.
