### ISSUE TITLE
`cpu (macOS-10.15, 3.7, latest, stable)` gets cancelled due to timeout

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning#11216]
## 🐛 Bug
The CI run always (?) fails with the following message due to timeout (set to 40 min). Similarly to #11184, the actual tests seem to always pass, but the difference is that runs here get cancelled due to timeouts instead of segfaults.

```
=== 2247 passed, 499 skipped, 11 xfailed, 3618 warnings in 613.75s (0:10:13) ===
Error: The operation was canceled.
```

### To Reproduce
- https://github.com/PyTorchLightning/pytorch-lightning/runs/4601898496?check_suite_focus=true#step:16:2860
- https://github.com/PyTorchLightning/pytorch-lightning/runs/4601604324?check_suite_focus=true#step:16:2860
- https://github.com/PyTorchLightning/pytorch-lightning/runs/4601145564?check_suite_focus=true#step:16:2860

### Expected behavior
No timeout.

### Environment

- PyTorch Lightning Version (e.g., 1.5.0):
- PyTorch Version (e.g., 1.10):
- Python version (e.g., 3.9):
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context
Could be the same issue as #11184, but creating this issue for tracking just in case.

cc @carmocca @akihironitta @borda

**Comment by carmocca** [comment]
Looking at the time difference from the timestamps:

```console
Wed, 22 Dec 2021 04:31:25 GMT === 2239 passed, 509 skipped, 11 xfailed, 3589 warnings in 531.92s (0:08:51) ===
Wed, 22 Dec 2021 04:54:05 GMT Error: The operation was canceled.
```
Got stuck for 23 minutes after finishing the tests.
It's likely linked to #11184

**Comment by akihironitta** [comment]
Closing this since the issue's been resolved in master somehow.
