### ISSUE TITLE
Do not have combined train+val progress bar, keep bar output after epoch is finished

### ISSUE THREAD

**Issue by elistevens** [PyTorchLightning/pytorch-lightning#1121]
## 🚀 Feature
The progress bar labeled "Epoch" should be renamed to "Train" and the validation data should be displayed only in a separate bar.

Additionally, each epoch should leave the final training and validation bar on-screen for visual inspection.

### Motivation

It's confusing that training and validation are shown in a single bar, and it destroys the information about the iterations/sec from training. Since validation is faster, the value spikes up right at the end.

### Pitch

Have two separate bars, one for training, one for validation, and none combined.

After a bar fills up, move the cursor down a line to not overwrite it.

**Comment by danieltudosiu** [comment]
This can easily be done with tqdm. [Here](https://github.com/tqdm/tqdm#ipython-jupyter-integration) is their example.

We can have their "1st loop" as our experiment loop (which encompasses training+validation **epochs**) and then have one progress bar per training epoch and another one per validation epoch.

**Comment by awaelchli** [comment]
I would also like to see the two progress bars to be split completely, but I would still prefer it disappears after the epoch is done, otherwise it fills up the terminal unnecessarily. I prefer to inspect my metrics in the logger. (Just my opinion of course)

**Comment by awaelchli** [comment]
The progress bar is now a callback. Is there a desire for an alternative of a split progress bar? We could add this simply as an extra callback and the user can choose it.
This could also go to bolts.
