### ISSUE TITLE
Default `LightningDataModule.__init__` isn't called

### ISSUE THREAD

**Issue by rohitgr7** [PyTorchLightning/pytorch-lightning#11225]
### To Reproduce

Default LightningDataModule init call was added here #9039 but was removed here #10350. Not sure if it was by mistake or intentional but the following code isn't working on master but working fine on the latest patch release. If it was intentional then I'd suggest we should somehow enforce users to always call `super().__init__()` in their LightningDataModule init methods because the following error isn't user-friendly.

Code:
```py
import os

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer, LightningDataModule


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len

class BoringData(LightningDataModule):
    def __init__(self):
        # super().__init__()
        print('DataModule init')
#         
    def test_dataloader(self):
        return DataLoader(RandomDataset(32, 100), batch_size=16)
    

class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)
    
    def test_step(self, batch, batch_idx):
        logits = self.layer(batch)
    
model = BoringModel()
dm = BoringData()

trainer = Trainer(fast_dev_run=True)
trainer.test(model, datamodule=dm)
```

Error:
```console
AttributeError: 'BoringData' object has no attribute 'prepare_data_per_node'
```

### Environment

- PyTorch Lightning Version (e.g., 1.5.0): master
- PyTorch Version (e.g., 1.10): 1.10
- Python version (e.g., 3.9): 3.9
- OS (e.g., Linux): macos
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

cc @carmocca @awaelchli @borda @ananthsub @ninginthecloud @jjenniferdai

**Comment by carmocca** [comment]
Forgetting to call `super().__init__()` is a classic bug in all Python codebases of the world. I don't think it is our job to improve the UX of the language itself. If Python devs chose not to raise a warning or anything like that, it's probably for a reason.

Also, we don't do the same for the `LightningModule`

**Comment by rohitgr7** [comment]
but for the lightning module I guess `nn.Module` takes care of it by throwing the following error which actually makes sense.
```console
AttributeError: cannot assign module before Module.__init__() call
```

**Comment by awaelchli** [comment]
I agree with @carmocca 

@rohitgr7 When converting the module to a dataclass, one has to add:

```py
    def __post_init__(self):
        super().__init__() 
```

The Python docs for this: https://docs.python.org/3/library/dataclasses.html#post-init-processing

**Comment by rohitgr7** [comment]
yes, I understand that's the responsibility of the user. But my only request was to provide a meaningful error in such a case which I guess is not possible.
