### ISSUE TITLE
cannot access class attribute in setup which assign in prepare_data when using multi gpus

### ISSUE THREAD

**Issue by tshu-w** [PyTorchLightning/pytorch-lightning#11220]
## 🐛 Bug

I got AttributeError when tried to access Datamodule object attribute in setup which assign in prepare_data when using multi gpus with strategy ddp or ddp2.

### To Reproduce

1. clone https://github.com/tshu-w/deep-learning-project-template
2. install package in requirements
3. `run fit --data GLUE --model GLUETransformer --model.model_name_or_path=bert-base-uncased --trainer.gpus=0,1, --trainer.max_epochs=2 --model.max_length=128 --trainer.strategy=ddp`

### Environment

* CUDA:
	- GPU:
		- NVIDIA A100-PCIE-40GB
		- NVIDIA A100-PCIE-40GB
		- NVIDIA A100-PCIE-40GB
		- NVIDIA A100-PCIE-40GB
	- available:         True
	- version:           11.3
* Packages:
	- numpy:             1.21.4
	- pyTorch_debug:     False
	- pyTorch_version:   1.10.0+cu113
	- pytorch-lightning: 1.5.6
	- tqdm:              4.62.3
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.9.7
	- version:           #102~18.04.1-Ubuntu SMP Thu Nov 11 14:46:36 UTC 2021

cc @justusschock @awaelchli @ninginthecloud

**Comment by ananthsub** [comment]
This is called out in the docs: https://pytorch-lightning.readthedocs.io/en/stable/extensions/datamodules.html#prepare-data

Do not assign instance variables inside of `prepare_data` as it is only called on select ranks. Setting state here will almost certainly lead to inconsistencies in your program.

**Comment by tshu-w** [comment]
@ananthsub Sorry for nob question, but why I can see this attribute when I `print(dir(self))` in setup.

**Comment by ananthsub** [comment]
@tshu-w is this the code pointer you're referencing?

https://github.com/tshu-w/deep-learning-project-template/blob/828798b5d3eff9a42718f40fdf000afb6f72d210/src/datamodules/sample_datamodules.py#L23-L28

I don't see you assigning any instance variable in `prepare_data` . 
`setup` is called on every process, so it is safe to assign state here.

**Comment by tshu-w** [comment]
@ananthsub Sorry, I revert assigning commit and force push it. Last question, since hugging face datasets will generate cache file when `map,` Should we call `map` in `prepare_data` first for safe. This [example](https://colab.research.google.com/github/PyTorchLightning/lightning-tutorials/blob/publication/.notebooks/lightning_examples/text-transformers.ipynb#scrollTo=5a856234) doesn't do it.

**Comment by awaelchli** [comment]
Yes, to re-iterate and confirm here, prepare_data is meant for downloading data, writing files to disk etc. It will not run on every process, meaning when you assign attributes in that method, they will not be set for all processes. So please move all the code you have there to setup() except the part where you download the data (if any). 


> Last question, since hugging face datasets will generate cache file when map, Should we call map in prepare_data first and assign again in setup for safe. This example doesn't do it.

I don't know exactly how it works there, but the dataset holds a reference to the cache file internally, hence all processes need to know that. So you should call the map method on all processes. So the example you show seems to be doing the right thing. 

> @awaelchli @ninginthecloud now that spawning happens sooner in the trainer, calling prepare_data will happen under a distributed context. do you think it makes sense for the trainer to call prepare_data on every process?

No I don't think so, the whole point of prepare_data is that it runs the hook only on rank 0. It's not allowed/possible to call collectives there.

**Comment by tshu-w** [comment]
> Yes, to re-iterate and confirm here, prepare_data is meant for downloading data, writing files to disk etc. It will not run on every process, meaning when you assign attributes in that method, they will not be set for all processes (only the first). So please move all the code you have there to setup() except the part where you download the data (if any).

Yes, I thought I understand. 

> I don't know exactly how it works there, but the dataset holds a reference to the cache file internally, hence all processes need to know that. So you should call the map method on all processes. So the example you show seems to be doing the right thing.

My concern is that when the map is first executed to process the data, datasets will use pyarraw to cache the in-memory data to disk, which involves writing to disk, so as I understand it, it needs to be executed in prepare_data first. I don't think this is obvious to datasets users and it would be better to mention it in the documentation.


```python
def prepare_data(self):
    datasets = load_dataset("glue", self.task_name)
    datasets.map(...)

def setup(self):
    self.datasets = load_dataset("glue", self.task_name)
    self.datasets.map(...)
```

**Comment by awaelchli** [comment]
Yes, makes sense. Your first code snippet looks fine to me.

> Also I think it's a bit redundant and ugly to execute map twice in the code, and I'm wondering if there's a better solution. I'm not sure whether the following code are right.

Can you point me to some resource regarding the map and caching of that dataset? I don't understand why one wants a in-memory dataset and still cache data to the disk.

If done in pure pytorch, how would it be done? like this?

```py
if rank == 0:
    datasets = load_dataset("glue", self.task_name)
    datasets.map(...) # write to disk the first time 

self.datasets=datasets.map(...)
```

**Comment by tshu-w** [comment]
> Can you point me to some resource regarding the map and caching of that dataset? I don't understand why one wants a in-memory dataset and still cache data to the disk.

To be clear, the datasets I'm talking about are the [huggingface package](https://huggingface.co/docs/datasets/index.html), not the pytorch datasets. [Here](https://huggingface.co/docs/datasets/about_arrow.html#memory-mapping) is a brief introduction. Cache datasets allow large datasets to be used on machines with relatively small device memory, i.e. `datasets = load_dataset("glue", self.task_name)` does not load all the data into memory. For me it is the desire to cache some complex processing (rather than via collate_fn) to speed up training.

**Comment by awaelchli** [comment]
I'm struggling to find any mention of how to do this properly with multiprocessing. Perhaps it's not a common use case and not well known. But here is a forum post asking a similar question and see the last answer by user staas: https://discuss.huggingface.co/t/slow-processing-with-map-when-using-deepspeed-or-fairscale/7229/11

So basically what this user suggests is

```py
if rank > 0:
     torch.distributed.barrier()

dataset.map(...)

if rank == 0:
    torch.distributed.barrier()
```

and in Lightning this is equivalent to:

```py
def prepare_data(self):
    datasets.map(...) # write to disk the first time 

def setup(self):
    self.datasets = load_dataset("glue", self.task_name) # assign in setup, and datasets will read cache
    self.datasets.map(...)
```
(as you had above)

or if the separation and duplication of code in these two hooks is not desired:

```py
def setup(self):
    if self.trainer.local_rank > 0:
        self.barrier()
    
    self.datasets = load_dataset("glue", self.task_name) # assign in setup, and datasets will read cache
    self.datasets.map(...)

    if self.trainer.local_rank == 0:
        self.barrier()
```

The only inconvenience is that the trainer refernce and barrier are not accessible in the datamodule hooks. They are only accessible if you implement this in the LightningModule. So I think that the 2nd option is still the best for now, even though it will look like duplicated instructions.

**Comment by tshu-w** [comment]
@awaelchli Thanks to your reply, I understand better.
