### ISSUE TITLE
[RFC] Deprecate `LightningLoggerBase.experiment` requirement from Logger interface

### ISSUE THREAD

**Issue by ananthsub** [PyTorchLightning/pytorch-lightning#11234]
## Proposed refactor

Deprecate the `experiment` property required by the Logger interface

https://github.com/PyTorchLightning/pytorch-lightning/blob/dedfde6859a15270385e6e751567b29ab6488e87/pytorch_lightning/loggers/base.py#L104-L107

### Motivation

1. `experiment` carries no meaning as specified on the base logger. This is an object which can be anything. 

Currently, Lightning appears to promise users that `logger.experiment` will have a consistent interface across different logger implementations, which is not true!

If users are interacting with the `experiment` directly, then they must *already know* what Logger implementation they're using. 

A good rule of thumb is that the only required interfaces for the Logger are what the Trainer directly calls. Everything else can be pushed to various implementations.  Since the trainer does not interact with the `experiment` at all, it does not need to be required on the Logger API. 

What makes more sense is for the various logger implementations to directly offer public property on their interface. For example, the TensorBoard logger could expose the `SummaryWriter` as a property in its public interface for Tensorboard logger users to call in their own code. 

2. Authors of custom loggers need to define this seemingly random experiment property without knowing how/when it will be called.

### Pitch

1. Make the current `experiment` definitions in the logger implementations top-level properties in their respective classes.
2. Deprecate `experiment` off the base logger API

### Additional context

_Originally posted by @ananthsub in https://github.com/PyTorchLightning/pytorch-lightning/issues/11209#issuecomment-999393358_

Part of #7740

cc @justusschock @awaelchli @akihironitta @tchaton @borda @edward-io @ananthsub

**Comment by tchaton** [comment]
Hey @ananthsub,

I understand your arguments. IMO, I don't believe users are expecting a common API for the experiment object from experience as it is linked to the Logger Client, but I agree this would make sense to provide a cleaner API for the base.

**Comment by wilson100hong** [comment]
@ananthsub  SGTM!
