### ISSUE TITLE
Move protected static methods in `LightningLoggerBase` to utilities file

### ISSUE THREAD

**Issue by ananthsub** [PyTorchLightning/pytorch-lightning#11237]
## Proposed refactor

Move this code out of the base logger class to a utilities file: 
https://github.com/PyTorchLightning/pytorch-lightning/blob/dedfde6859a15270385e6e751567b29ab6488e87/pytorch_lightning/loggers/base.py#L181-L280
https://github.com/PyTorchLightning/pytorch-lightning/blob/dedfde6859a15270385e6e751567b29ab6488e87/pytorch_lightning/loggers/base.py#L363-L367

### Motivation

Streamline the `LightningLoggerBase` as the core interface required for implementations. 

These methods do not need to be part of the base class, since they're not required to be called or overridden. They can be moved out of the base class into a utils file in order to still be used in various logger implementations.

Moving these methods out makes the base class easier to read & follow.

There's no deprecation required since these methods are marked private already. 

### Pitch

Move these functions out, to either `pl/loggers/utilities.py` or `pl/utilities/logger.py` 

If agreed on, this could be a Good First Issue candidate

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @justusschock @awaelchli @akihironitta @rohitgr7 @edward-io @ananthsub @kamil-kaczmarek @Raalsky @Blaizzy

**Comment by wilson100hong** [comment]
@ananthsub  SGTM!
