### ISSUE TITLE
[RFC] Better support using multiple loggers simultaneously by deprecating `LoggerCollection`

### ISSUE THREAD

**Issue by ananthsub** [PyTorchLightning/pytorch-lightning#11232]
## Proposed refactor

Deprecate `LoggerCollection`:
https://github.com/PyTorchLightning/pytorch-lightning/blob/a6a28e08d22f59f2468ff1049c67507df7519e7c/pytorch_lightning/loggers/base.py#L370-L464

## Motivation

The logger collection implements the base logger interface and wraps a sequence of loggers. This way, the trainer always behaves as though a single logger is being used. Such a collection is somewhat handy for writing data, but is much less helpful when reading state from loggers, especially when individual loggers have different state/property values. For instance, It's not clear at all what `LoggerCollection.name` *should* be. The concatenation of all its instance loggers names? The first logger's name? This also came up here: https://github.com/PyTorchLightning/pytorch-lightning/issues/10954

This leads to inconsistencies across components. Namely, Lightning offers no such LoggerCollection-equivalent for Callbacks. The trainer treats them as a flat list, and when hooks need to be called, the Trainer iterates over this list, and calls the callbacks' hooks successively. Why do we not do the same for loggers? 

This leads to leaks in the user-facing API. If users pass a list of loggers to the `Trainer`'s `logger` flag, accessing `trainer.logger` returns a single instance of type `LoggerCollection`, which is different than what users specified, which means users have to learn about this abstraction and likely update their code to handle cases where a single logger is used vs multiple.

## Pitch

1. Introduce a `loggers` property on the Trainer which returns a list of the passed in Loggers objects, so users have an option to not use the LoggerCollection
```py
@property
def loggers(self) -> List[LightningLoggerBase]:
```
2. Deprecate `LoggerCollection` in favor of this `loggers` property. Wherever we call the Logger APIs from within the Trainer, iterate over the `loggers` list and call the hooks instead. 

Example:

Current
https://github.com/PyTorchLightning/pytorch-lightning/blob/a6a28e08d22f59f2468ff1049c67507df7519e7c/pytorch_lightning/trainer/trainer.py#L1444-L1445

New
```py
for logger in self.loggers:
    logger.finalize("success")
```

3. After `LoggerCollection` is removed, we could redefine `logger `on the Trainer to be something like this. Or we could deprecate `logger` entirely in favor of `loggers` to avoid any potential misuse/missed expectations around supporting multiple loggers. 

```py
@property
def logger(self) -> Optional[LightningLoggerBase]:
    loggers = self.loggers
    return loggers[0] if len(loggers) > 0 else None
```

_Originally posted by @ananthsub in https://github.com/PyTorchLightning/pytorch-lightning/issues/11209#issuecomment-999393358_
### Pitch

cc @justusschock @awaelchli @akihironitta @edward-io @borda @ananthsub @tchaton

**Comment by ananthsub** [comment]
See this issue as an area where we need to get the individual loggers group separators: https://github.com/PyTorchLightning/pytorch-lightning/pull/11254

There's no way to do this correctly without breaking the contract of the base logger API. 

It'd be much much easier to iterate over the 
```py
for logger in trainer.loggers:
    converted_metrics = _prefix_metrics(metrics_dict, prefix, logger.group_separator)
    logger.log_metrics(converted_metrics, trainer.global_step)
```
Than any other special handling for logger collections

**Comment by tchaton** [comment]
Hey @ananthsub,

Sounds like a good suggestion. This could lead to some breaking change.

**Comment by wilson100hong** [comment]
@ananthsub  this is better than `LoggerCollection`! I want to address a scenario that user might want to have a `dict` of Logger so they can choose the logger using key instead of index, which might be convenient in code management? WDYT?

**Comment by ananthsub** [comment]
Currently, the Trainer accepts an iterable of loggers, so passing a `dict` is "supported" as long as the _keys_ of the dict are the LightningLoggerBase objects, not the values, since the LoggerCollection today simply iterates over this to do the logging. Passing a Dict[str, LightningLoggerBase] would break in this case.

> so they can choose the logger using key instead of index, which might be convenient in code management?

Where would the user be accessing the logger from? `trainer.loggers` ? What would the type of `loggers` be based on this input? What specific `dict` type would the Trainer accept, to limit how much handling it'd need to do for iterating over the loggers to log values.

**Comment by carmocca** [comment]
> 3. After LoggerCollection is removed, we could redefine logger on the Trainer to be something like this

Do you plan to add a deprecation path for the setter?

Also, do you plan to rename `Trainer(logger=...)` to `Trainer(loggers=...)` after this issue is resolved?

**Comment by ananthsub** [comment]
@carmocca good questions. 
> Do you plan to add a deprecation path for the setter?

```
trainer.logger = ....
```

This update should also be mirrored in trainer.loggers to avoid staleness fyi @akashkw 

> Also, do you plan to rename Trainer(logger=...) to Trainer(loggers=...) after this issue is resolved?

One option is to go all in with `loggers` and do the following:
- Deprecate `trainer.logger` in favor of `trainer.loggers`
- Deprecate `LightningModule.logger` in favor of `LightningModule.loggers`: https://github.com/PyTorchLightning/pytorch-lightning/blob/86b177ebe5427725b35fde1a8808a7b59b8a277a/pytorch_lightning/core/lightning.py#L257-L260
- Change `Trainer(logger=...)` to `Trainer(loggers=...)`

from an API standpoint, this is the cleanest and most consistent. but it also introduces more breaking changes to the Trainer and LightningModule, which I understand users are sensitive to. Over time it reduces the risk of bugs though, like keeping the attributes in sync

**Comment by daniellepintz** [comment]
Do we have an estimate of what percentage of users use multiple loggers vs one logger?

**Comment by daniellepintz** [comment]
I vote for going all in with `loggers`. 

For the cases where users set `trainer.logger = ...` or `trainer.loggers = ...`, I think until we remove `trainer.logger` in v1.8 we will have to create setters for `logger` and `loggers` such that when one is set we update the other. 

If someone sets `trainer.loggers = ...` I'd say we set `trainer.logger` to a LoggerCollection of those loggers.

**Comment by akashkw** [comment]
I think the setters for `trainer.logger` and `trainer.loggers` belong in this PR https://github.com/PyTorchLightning/pytorch-lightning/pull/11683, so I'll go ahead and add them.

**Comment by awaelchli** [comment]
> For the cases where users set trainer.logger = ... or trainer.loggers = ..., I think until we remove

This is not allowed. We need to move away from this in the future anyway. The logger has to be owned by the logger connector and not be set on the Trainer indirectly. It is what we wanted to do for a while but never got to it.

**Comment by awaelchli** [comment]
The logger vs. loggers proposal here has some open questions which I believe we should address first before we set the api changes in motion. 

If we previously had

`trainer = Trainer(logger=Logger())`

and in my LightningModule:

`self.logger.log_image(...)`

Then now with the new change, if I change to `trainer = Trainer(logger=[Logger1(), Logger2()])` then that means I now also need to change the LightningModule code to a for loop iterating over loggers. This is not very well aligned with the design goals of Lightning (remember, we moved automatic_optimization to the LM because of this).

Furthermore, there is the question of whether to go "all in" with the loggers property. But what that means for the user is that they would have to write `self.loggers[0]` when 99% of time you just want to use a single logger which is silly imo. Having to write `self.loggers[0]` every time just screams after a `self.logger` property.

> Do we have an estimate of what percentage of users use multiple loggers vs one logger?

99% use one logger. 1% uses 2 loggers. nobody uses more than 2.

Motivation by @ananthsub:
> This leads to leaks in the user-facing API. If users pass a list of loggers to the Trainer's logger flag, accessing trainer.logger returns a single instance of type LoggerCollection, which is different than what users specified, which means users have to learn about this abstraction and likely update their code to handle cases where a single logger is used vs multiple.

To emphasize, the last part here "users have to [...] update their code to handle cases where a single logger is used vs multiple." is neither handled well by the current LoggerCollection nor does it get solved by the proposals here. 

Shouldn't we investigate a design that lets us switch out the loggers without being forced to change the LM code?

**Comment by ananthsub** [comment]
@awaelchli - one solution for that is to pick an arbitrary `logger` from the `loggers` list as a convenience. we do this with model checkpointing callbacks here: https://github.com/PyTorchLightning/pytorch-lightning/blob/1203094a201bd38f0b8b77d93bc39fc95f06d8ae/pytorch_lightning/trainer/trainer.py#L2199-L2205

What we could do is redefine `logger` in place, such that:
```py
if len(loggers) == 0:
    return None
if len(loggers) == 1:
    return loggers[0]
else:
    # emit warning of using logger when multiple loggers are configured, with this behavior changing in v1.8 to return the first logger in the list
    return LoggerCollection(loggers)
```

**Comment by akashkw** [comment]
@ananthsub I was in the middle of suggesting a similar solution right as you posted it.

I agree with @awaelchli that deprecating trainer.logger is going to be clunkier for most users, and I noticed while refactoring the codebase that having a for loop just didn't make sense in many places so I had to use trainer.loggers[0]. 

I think maintaining both trainer.logger and trainer.loggers is still much cleaner than having LoggerCollection. Users will still have to update their code when going from a single logger to multiple, but learning to use trainer.loggers is much simpler than learning to use LoggerCollection.

**Comment by ananthsub** [comment]
To summarize:
- the focus of this issue is deprecating LoggerCollection in favor of `loggers`
- We don't need to remove the fastpath option of `logger` because it's convenient for the overwhelmingly common case of using a single logger

Regarding the trainer API, I also don't see a strong need to do this migration: `Trainer(logger=...)` to `Trainer(loggers=...)` 
The documentation around this can clearly cite that multiple loggers are supported. But changing the argument incurs another migration.& breaking change eventually

**Comment by daniellepintz** [comment]
That sounds good. @awaelchli please confirm if this makes sense to you, so that @akashkw can finish his PR

**Comment by awaelchli** [comment]
**I am ok with that, we just need to be fully aware that if we remove the LoggerCollection abstraction, we won't be able to improve the situation where the user needs to change their code to make the LM compatible with the trainer settings, at least not with the current logger reference, and unless we recommend to always add that for loop.** 

In summary, the implications are:

Before:

```py
# agnostic to number of loggers in trainer (except 0)
self.logger.log_image(...)
```

After:
```
# have to change to:
for logger in self.loggers:
    logger.log_image(...)
```

This becomes the standard of accessing custom logging methods, the for loop will always be required to make it compatible with 0, 1, and multiple loggers. 

The only way I see to avoid the "boilerplate" for loop without a logger collection abstraction is to add the methods log_text, log_image, etc. to the LM itself, which internally would loop over the loggers.
