### ISSUE TITLE
Code in animation of LightningModule doc is wrong

### ISSUE THREAD

**Issue by Antoine101** [PyTorchLightning/pytorch-lightning#11241]
In **Docs > LightningModule** , code in first video animation at 0:40 is wrong, as per the screenshot below:
![image](https://user-images.githubusercontent.com/48209504/147225988-8be8004c-c18d-4a31-860a-97caee5db822.png)

First argument in **trainer.fit** should be **classifier** and not **model**.

To be confirmed.

cc @borda

**Comment by carmocca** [comment]
@aribornstein Do you have the source frames for the gif? are you able to fix this?

**Comment by aribornstein** [comment]
yes will fix

**Comment by rasbt** [comment]
Just a heads-up, as mentioned in the related issue #11661 there is also a `pl.Module` which should be `nn.Module` at 0:32
![Screen Shot 2022-01-29 at 4 51 41 PM](https://user-images.githubusercontent.com/5618407/151680122-b9f62826-7b11-4ddb-8064-2e0ec5b000ab.png)
