### ISSUE TITLE
Potential bug in DataConnector?

### ISSUE THREAD

**Issue by ZhaofengWu** [PyTorchLightning/pytorch-lightning#11266]
Is this supposed to be `getattr`? I don't think `setattr` returns anything.

https://github.com/PyTorchLightning/pytorch-lightning/blob/ca9b25db80f08a3b9a3c448048949ec1adb845ba/pytorch_lightning/trainer/connectors/data_connector.py#L117

cc @justusschock @awaelchli @ninginthecloud

**Comment by awaelchli** [comment]
Yes, it seems this should be `getattr`. Currently it will fall back to `_select_data_fetcher()` unconditinally.
