### ISSUE TITLE
Option to specify maximum batch size for `scale_batch_size`

### ISSUE THREAD

**Issue by cschell** [PyTorchLightning/pytorch-lightning#11295]
## 🚀 Feature

Option to specify maximum batch size for `scale_batch_size`

### Motivation

The `scale_batch_size` is a great feature for me to make sure that GPUs used by my (kubernetes) jobs are fully utilized. However, when my hyperparameter search proposes very small model sizes, `scale_batch_size` finds very large batch sizes. While these batches still fit onto the GPU, these batches get preloaded by the DataLoader workers and end up eating a lot of ram, which eventually crashes my jobs because of OOM issues.

### Pitch

To implement this feature [`scale_batch_size`](https://github.com/PyTorchLightning/pytorch-lightning/blob/5b153e507241c2b941783e94078ea5c49dd29adf/pytorch_lightning/tuner/batch_size_scaling.py#L33) needs an optional parameter (maybe called `max_batch_size`) that breaks the tuning loop if `new_size` reaches the provided value.

cc @borda @tchaton @rohitgr7 @akihironitta

**Comment by cschell** [comment]
I just stumbled over this bug report, might be related: #9625

**Comment by tchaton** [comment]
Hey @cschell,

Any chance you could provide a reproducible script with the BoringModel?

Furthermore, do you use multiple workers during the tuning phase too ?

cc: @rohitgr7 

Best,
T.C

**Comment by cschell** [comment]
> Any chance you could provide a reproducible script with the BoringModel?

I'm not able to test it right now since our cluster queue is currently very long, but I guess this would do it on a machine/container with less main memory than GPU memory, especially when dataloader workers are used:

```python

import os
import pytorch_lightning as pl

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        limit_test_batches=1,
        num_sanity_val_steps=0,
        gpus=[1],
        max_epochs=1,
        enable_model_summary=False,
        auto_scale_batch_size=True
    )

    class Datamodule(pl.LightningDataModule):
        def __init__(self):
            super().__init__()
            self.batch_size = 1

        def train_dataloader(self):
            return DataLoader(RandomDataset(32, 6_400_000), batch_size=self.batch_size)

    trainer.tune(model=BoringModel(), datamodule=Datamodule(), scale_batch_size_kwargs={"init_val": 200_000, "mode": "power"})


if __name__ == "__main__":
    run()
```

> Furthermore, do you use multiple workers during the tuning phase too ?

I guess so, since I provide it with the same datamodule I later use for training and validation (which I configured to use 4 workers).

**Comment by tchaton** [comment]
Dear @cschell,

Thanks for sharing this code. IMO, we shouldn't add a `max_batch_size`. Lightning should figure out the right value and not fail.

`max_batch_size` seems more like a hack to me.

**Comment by cschell** [comment]
I agree, it would be great if the algorithm could take main memory constraints into account as well. However, this still cannot account for other constraints that might appear further down the road and therefore might not leave enough spare memory for other parts of the training and validation routines. Therefore, `max_batch_size` looks to me like an easy way to avoid any such issues.

**Comment by rohitgr7** [comment]
you can limit the search using `max_trials` too to make sure it just doesn't go up too much in your use case.

**Comment by cschell** [comment]
yeah, that's what I'm currently doing, followed with the line `datamodule.batch_size = min(datamodule.batch_size,  100_000)`.

**Comment by carmocca** [comment]
The suggested solution makes sense to me. Closing

**Comment by RylanSchaeffer** [comment]
I have this exact same issue. I was a tad surprised to run into an OOM error after using Lightning's auto_scale_batch_size. Will try the suggested work-around, but would appreciate a general solution!
