### ISSUE TITLE
Render Changelog within the documentation

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#11343]
## 🚀 Feature

While investigating Streamlit, I found that their documentation render their [CHANGELOG](https://docs.streamlit.io/library/changelog) which means it is searchable and help find changes associated to components you are looking for.

This would help the discoverability of the new API.  

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda

**Comment by Borda** [comment]
we have it for a very long time already... https://pytorch-lightning.readthedocs.io/en/stable/generated/CHANGELOG.html

**Comment by akihironitta** [comment]
> This would help the discoverability of the new API.

Just an idea but we could move the changelog to a more discoverable place, e.g. in the "Getting started" section as streamlit does. It's extremely unlikely for users to reach the page because it's located at the very bottom and users have to click the "+" button:

<img width="224" alt="image" src="https://user-images.githubusercontent.com/20610905/148362928-d0678407-ced8-44bb-9f2f-2eb6c34bf1c9.png">

Could be handled as part of #7666.
cc @rohitgr7
