### ISSUE TITLE
Fault tolerant training with multiple dataloaders

### ISSUE THREAD

**Issue by ant0nsc** [PyTorchLightning/pytorch-lightning#11349]
## 🚀 Feature

We would love to see multiple dataloaders supported in fault tolerant training. The [present documentation](https://pytorch-lightning.readthedocs.io/en/latest/advanced/fault_tolerant_training.html#current-known-limitations) states this is not supported yet, and suggests to add a feature request if needed. Here's ours :-)

### Motivation

We are heavy users of self-supervised learning for large image datasets. Training times for our models are several days on multiple nodes, hence we are using low-cost interruptable compute nodes (low priority nodes on Azure). Fault tolerant training would be wonderful for us to have, to make best use of the compute capacity we have available. 

To train our models, we need an unlabelled dataset to train the actual encoder, and another dataset to evaluate the quality of the embeddings. For use, these datasets are usually different, hence we need to use multiple dataloaders.

### Pitch

Support for fault tolerant training when multiple data loaders are used.

cc @borda @justusschock @awaelchli @ninginthecloud @carmocca @tchaton

**Comment by tchaton** [comment]
Dear @ant0nsc,

Thanks for making this request.
Supporting automatic fault tolerant for multi dataloaders is very challenging and might not be possible in the short term.

However, this is achievable with Fault Tolerant Manual which isn't documented yet.

Find the associated [test](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/tests/utilities/test_auto_restart.py#L1523).

By implementing the `state_dict` and `load_state_dict` on your own sampler, dataset, Lightning will collect the states and restore them properly.

You would have to take care of the distribution and num_workers too.

Best regards,
T.C

**Comment by ant0nsc** [comment]
Dear @tchaton , if you could spare some time for a discussion to kickstart this work, that would be wonderful! I'll message you on Linkedin with my contact details..

**Comment by carmocca** [comment]
Closing this issue, tracking in #9130
