### ISSUE TITLE
Neptune logger runs are stopped late when using Hydra multirun and DDP

### ISSUE THREAD

**Issue by rivi** [PyTorchLightning/pytorch-lightning#11368]
## 🐛 Bug

When using Hydra's multirun feature and training a model using DDP with 2 GPUs all of the Neptune runs are finished (made "Inactive") when the entire multirun finishes. Until that moment, they stay in "Active" state.

I'm not familiar with internal workings of the DDP, but this behaviour also makes my worrying about other things that may leak after finishing each run in Hydra's multirun.

### To Reproduce

Let me know if you need a minimal example.

### Expected behavior

Neptune runs should be made "Inactive" as each run finishes. 

### Environment

* CUDA:
	- GPU:
		- NVIDIA GeForce RTX 3090
		- NVIDIA GeForce RTX 3090
	- available:         True
	- version:           11.3
* Packages:
	- numpy:             1.21.4
	- pyTorch_debug:     False
	- pyTorch_version:   1.10.1+cu113
	- pytorch-lightning: 1.5.7
	- tqdm:              4.62.3
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.9.7
	- version:           \# 1 SMP Wed Dec 22 13:25:12 UTC 2021

cc @justusschock @kaushikb11 @awaelchli @akihironitta @rohitgr7 @kamil-kaczmarek @Raalsky @Blaizzy

**Comment by Blaizzy** [comment]
Hi @rivi 

Prince Canuma here, a Data Scientist at Neptune.ai,

Neptune by default stops the thread automatically (calls `.stop()` method) when the script that initialized the connection finishes.

But you can alter this behaviour. In your case specifically, when performing multiple training jobs from one script one after the other, it is a good practice to use the `.stop()` method to manually make the finished tracked runs `Inactive` as every open run keeps an open connection with Neptune.

**Example**
```
for config in configs:
     run = neptune.init()
     [...] # Your training or monitoring code
     run.stop()
```
Docs: https://docs.neptune.ai/api-reference/run#.stop

**Comment by Blaizzy** [comment]
Let me know if this solves your problem! 😊

**Comment by rivi** [comment]
@Blaizzy yes - it seems to solve the problem. In case of the Lightning`s neptune logger I just needed to call:
```
logger.run.stop()
```

**Comment by Blaizzy** [comment]
That's amazing @rivi!!!  🥳 

Glad it worked for you!

Don't hesitate to reach out if you have any other issues or feature requests.

**Comment by bryant1410** [comment]
> @Blaizzy yes - it seems to solve the problem. In case of the Lightning`s neptune logger I just needed to call:
> 
> ```
> logger.run.stop()
> ```

Shouldn't PL do this automatically after some event (e.g., training end)?

**Comment by rivi** [comment]
@Blaizzy I'm running my code using a script that uses Hydra's multirun feature.

@bryant1410 As I understand it, it is somehow difficult to achieve, as you can still call `trainer.test()` after  `trainer.fit()` and the results should be logged to Neptune. There is no obvious point at which `logger.run.stop()` should be called automatically. One could think of applying context manager (`with` statement) here, but it would look rather strange.
