### ISSUE TITLE
Always use the latest testing packages

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning#11362]
## 🚀 Enhancement in CI
Currently, "oldest" testing uses the oldest versions of each testing packages. For example, `pytest==6.0.0` is used in "oldest" setting where its stable version is `pytest==6.2.5` as of now.

You can compare which versions are used in "oldest" and "latest" settings:
- `cpu (ubuntu-18.04, 3.7, oldest, stable) ` https://github.com/PyTorchLightning/pytorch-lightning/runs/4737256599?check_suite_focus=true
- `cpu (ubuntu-18.04, 3.7, latest, stable)` https://github.com/PyTorchLightning/pytorch-lightning/runs/4737256642?check_suite_focus=true

### Motivation
It'll become less likely to spend time debugging something unrelated to our side.

### Pitch
Remove:
https://github.com/PyTorchLightning/pytorch-lightning/blob/59a7ba760548baadf6dbb30864b54cb01c7225a3/.github/set-min-requirements.py#L5

### Alternatives
Use old versions of testing packages, e.g. pytest, (which are likely to have some bugs in testing packages

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

cc @carmocca @akihironitta @borda

**Comment by Borda** [comment]
if you set `pytest>6.0.0` the oldest replacement is not applied

**Comment by akihironitta** [comment]
@Borda I don't see a huge difference between:
- using `>` instead of `>=` in `requirements/test.txt` and
- removing the line above from `set-min-requirements.py`

but would you recommend I follow your suggestion for all testing packages?

**Comment by Borda** [comment]
> but would you recommend I follow your suggestion for all testing packages?

fair point, let's remove the line :]
