### ISSUE TITLE
Rename `pytorch_lightning/loggers/csv_logs.py` to `pytorch_lightning/loggers/csv.py`

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#11372]
## Proposed refactor

Rename `pytorch_lightning/loggers/csv_logs.py` to `pytorch_lightning/loggers/csv.py` 

### Motivation

None of the other Logger files have "logs" as a suffix in the filename, e.g. `comet.py`, `neptune.py`, `tensorboard.py`

cc @borda @justusschock @awaelchli @akihironitta @rohitgr7

**Comment by awaelchli** [comment]
The file was named like this because it otherwise clashes with the built-in csv module. I would advise no to rename it.

**Comment by daniellepintz** [comment]
@awaelchli I see, thanks! Why is this not a problem with mlflow?:
https://github.com/PyTorchLightning/pytorch-lightning/blob/86b177ebe5427725b35fde1a8808a7b59b8a277a/pytorch_lightning/loggers/mlflow.py#L32

or neptune?:
https://github.com/PyTorchLightning/pytorch-lightning/blob/86b177ebe5427725b35fde1a8808a7b59b8a277a/pytorch_lightning/loggers/neptune.py#L46

**Comment by rohitgr7** [comment]
because they are not built-in modules? [csv](https://docs.python.org/3/library/csv.html) module comes by default when you install python even with no dependencies.

**Comment by daniellepintz** [comment]
@rohitgr7 are you sure? I don't see csv listed here: https://docs.python.org/3/library/functions.html

**Comment by akihironitta** [comment]
@daniellepintz I think the list of standard modules are here https://github.com/python/cpython/tree/main/Lib, and csv is one of them.

**Comment by carmocca** [comment]
Yeah, conflicts with stdlib modules are very annoying and confusing to users. Let's not do this.
