### ISSUE TITLE
Simplification of how the gpus are given to the Trainer class

### ISSUE THREAD

**Issue by danieltudosiu** [PyTorchLightning/pytorch-lightning#1138]
## 🚀 Feature
Simplify how we specify what GPUs are to be used.

### Motivation
[As per the documentation](https://pytorch-lightning.slack.com/archives/CRBLFHY79/p1584064137115700), you can pass what GPUs to be used in one of the following manners:
    - None - which means train on CPU
    - Integer - which determines how many GPUs to use (can mean train on CPU if is 0, and all GPUs if -1)
    - List - which determines which GPUs to use
    - Comma-separated integers in a string - which determines which GPUs to use 
    - Single integer in a string - which determines which GPU to use, can be -1 to specify all

### Pitch
Change the behavior to a pure string-based method as follow:
    - "-1," or "-1" - means all GPUs
    - "0" or "0," - means GPU 0 by bus ordering
    - "0,1" - means GPUs 0 and 1 by bus ordering
    
It is true that we lose the ability to just say fetch x GPUs, but I believe that should not be used anyway since GPU usage can vary and you can wake up with clashing with other people's jobs in a shared environment. And if it is your workstation, realistically you will have max 4 GPUs which means little to none overhead for you to specify them.

### Alternatives
N/A

### Additional context
At the moment it is a bit confusing how to pass the GPUs and furthermore TensorBoard logger crashes if you pass it a list.

Past Slack discussion can be found here: https://pytorch-lightning.slack.com/archives/CRBLFHY79/p1584064137115700

**Comment by awaelchli** [comment]
The documentation is a bit hidden, but there is a list of possible values and types for the gpu argument [here](https://pytorch-lightning.readthedocs.io/en/latest/pytorch_lightning.trainer.distrib_parts.html#module-pytorch_lightning.trainer.distrib_parts).
The possibilities for string you propose already exist and behave like you describe. I don't see the point of simplifying everything to string. In fact, I would argue to even support more types. For example, why have list but not support tuple?

**Comment by danieltudosiu** [comment]
If you pass a list to the gpus parameters the TensorBoard Logger will error out with `ValueError: value should be one of int, float, str, bool, or torch.Tensor` which showcases that actually the list is not fully supported. 

Also, having a single way of passing the GPU list will simplify further Loggers that need to be added. Why have flexibility in passing a parameter that actually does not add any benefits at all? Furthermore, args are usually passed as strings, yes you can pass them as lists as well, but is non-trivial and again, does not add any benefit.

**Comment by yukw777** [comment]
It might be b/c I don't personally use `argparse` in my training script at all as I prefer a config driven approach using libraries like `hydra` that I actually prefer that we accept primitive types like int or list of ints. Another point of discussion.

**Comment by williamFalcon** [comment]
sounds like we just need to map whatever input is passed in to a single format (which i thought we did). then we make sure that format works well for things like tensorboard.

**Comment by awaelchli** [comment]
The issue with the hparams conversion for TB is discussed in #1095 (and a proposal to fix it was already submitted as PR).

**Comment by danieltudosiu** [comment]
My rationale is to reduce the amount of memory a human needs to spend to remember every possible variation in the framework while maintaining maximum flexibility. I find it similar to how a code formatter works, it makes it easier for your mind to read every piece of code by showing it in a well pre-defined format.

**Comment by sneiman** [comment]
I like having one way - and it is part of the declared design philosophy. An iterable makes more sense to me - list or tuple - because it is more useful and more pythonic.

The issue of how this integrates with loggers for me raises an issue that is lurking as more functionality is incorporated. Starting to be trickier to know exactly how to do things 'as a wrapper on pytorch' v. understanding exactly what Trainer/LightningModule are up to. I can think of a number of places where I have had to do some testing/code reading to really understand what is going on in the background and what an argument/function will do.

As an engineer, gpus is first and foremost an arg for Trainer(). So my bias is towards making it the simplest useful version of that possible. And pt  taking responsibility for converting it as needed to anything ptl is managing for the user- like hparams storage or logging.
