### ISSUE TITLE
While logging model in a multi gpu scenario, TypeError: can't pickle _thread.lock objects

### ISSUE THREAD

**Issue by jhoareau** [PyTorchLightning/pytorch-lightning#11398]
## 🐛 Bug

Duplicating https://github.com/PyTorchLightning/pytorch-lightning/issues/3444 since that issue was closed with no resolution and still happens in the latest versions.

### To Reproduce

- PyTorch Lightning Version (e.g., 1.5.0): 1.4.6
- PyTorch Version (e.g., 1.10): 1.9.1
- Python version (e.g., 3.9): 3.8.10
- OS (e.g., Linux): Linux
- How you installed PyTorch (`conda`, `pip`, source): pip

cc @justusschock @kaushikb11 @awaelchli @akihironitta @rohitgr7

**Comment by carmocca** [comment]
Can you reproduce it? In that case, can you share a reproducible script?
Do you experience it only when using the MLFlow callback?
Are you using `strategy="ddp_spawn"`? cc @awaelchli

> still happens in the latest versions.

Have you tried using master or `1.5.8` (latest right now)

We can fix this as long as we find the component that creates this object.

**Comment by jhoareau** [comment]
We are using the "ddp" strategy, not "ddp_spawn". I don't have any reproducible script right now but I'll work on that. Will try with 1.5.8 asap.

**Comment by jhoareau** [comment]
It seems to be working on the 1.5.8 actually, thanks for the tip. I will re-open with reproduction steps if it comes up again.
