### ISSUE TITLE
Outputs written to same URI if `default_root_dir` is s3 location and multiple training jobs launched simultaneously

### ISSUE THREAD

**Issue by JoshuaMeyers** [PyTorchLightning/pytorch-lightning#11418]
## 🐛 Bug

Outputs are written to same URI if `default_root_dir` is an s3 location and multiple training jobs are launched simultaneously.

### Expected behavior

If possible, it would be good to reduce the amount of time between determining the version number (`{default_root_dir}/version_X`) and writing the first output since in this gap it is possible for other training runs to determine the same version number and write to the same location. Is there an option to flush/write outputs _before_ the first epoch?

### Environment

- PyTorch Lightning Version==1.5.8
- PyTorch Version==1.8.0
- Python version==3.7
- OS==linux

Thanks in advance, awesome project! 🙌 

cc @justusschock @awaelchli @ninginthecloud @rohitgr7 @otaj @edward-io @borda @ananthsub @kamil-kaczmarek @Raalsky @Blaizzy

**Comment by kaushikb11** [comment]
> writing the first output since in this gap it is possible for other training runs to determine the same version number and write to the same location.

@JoshuaMeyers Have you faced this situation?

**Comment by JoshuaMeyers** [comment]
Yes I have. My solution was to write to a different directory with a timestamped name. That way lightning version is always `version_0` but the root directory is differentiated.

**Comment by awaelchli** [comment]
No matter how small we make the time between launching the script and determining the version number, the race condition will always exist. If these independent parallel jobs reference the same root folder and all of them assume they are the only ones looking at that folder, they will all updated the versions by looking at which versioned folders already exist. Note, it doesn't matter in which form we do the lookup: The same would be a problem if we were reading/writing from a file, a database, etc. 

I only see one way out of this: The user names their experiments. Set a name per parallel experiment so the logger can write to different folders.
