### ISSUE TITLE
Add `profile` method to `AbstractProfiler` class

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#11410]
## Proposed refactor

Add `profile` method to `AbstractProfiler` class. We can directly lift the implementation from the `BaseProfiler`:
https://github.com/PyTorchLightning/pytorch-lightning/blob/cec4f17df3cbdf2b585b723d518e03bd500a7c5b/pytorch_lightning/profiler/base.py#L69-L84

### Motivation

Set up for #11409

cc @justusschock @awaelchli @akihironitta @rohitgr7 @carmocca @kaushikb11 @ninginthecloud

**Comment by carmocca** [comment]
Should `profile_iterable` be lifted too?

**Comment by ananthsub** [comment]
> Should `profile_iterable` be lifted too?

`profile_iterable` doesn't seem to be used in the trainer anymore, i think after the data fetcher refactors? does that mean we could deprecate `profile_iterable` instead of lifting it up?

**Comment by daniellepintz** [comment]
@ananthsub Good point! I would vote for deprecation as well

**Comment by carmocca** [comment]
Mmm good catch. `git bisect` points to https://github.com/PyTorchLightning/pytorch-lightning/pull/9047/ as the PR that removed it, but it's unclear whether it was intentional. Can you comment @tchaton?

**Comment by tchaton** [comment]
Hey @ananthsub @daniellepintz. Good catch ! Yes, I think we could depreceate it and uplift the profile to the abstract profiler.
