### ISSUE TITLE
Unable to load pretrained weight into custom model in Pytorch Lightning

### ISSUE THREAD

**Issue by JohnDuke259** [PyTorchLightning/pytorch-lightning#11420]
Hello folks,

I want to retrain a custom model with my data. I can load the pretrained weights (.pth file) into the model in Pytorch and it runs but I want more functionality and refactored the code into Pytorch Lightning. I am having trouble loading the pretrained weight into the Pytorch Lightning model. The Pytorch Lightning code works but I have limited data and don’t have enough data to train from scratch.

Pytorch Model:

```
class BDRAR(nn.Module):
      def __init__(self):
          super(BDRAR, self).__init__()
          resnext = ResNeXt101()
          self.layer0 = resnext.layer0
          self.layer1 = resnext.layer1
          self.layer2 = resnext.layer2
          self.layer3 = resnext.layer3
          self.layer4 = resnext.layer4
```

My Lightning model looks like this:

```
 class liteBDRAR(pl.LightningModule):
         def __init__(self):
              super(liteBDRAR, self).__init__()
              self.model = BDRAR()
              print('Model Created!')

         def forward(self, x):
              return self.model(x)
```
My run:

```
KeyError: 'state_dict 
path = './ckpt/BDRAR/3000.pth'
bdrar = liteBDRAR.load_from_checkpoint(path,  strict=False)
trainer = pl.Trainer(fast_dev_run=True, gpus=1)
trainer.fit(bdrar)
```

I get the following error:

  `  "keys = model.load_state_dict(checkpoint["state_dict"], strict=strict) **KeyError: 'state_dict**'"`

I will appreciate any help. Thank you so much.

@williamFalcon </div> @rohitgr7

**Comment by rohitgr7** [comment]
hey @JohnDuke259,

checkpoints created outside Lightning, can't be loaded directly with `load_from_checkpoint`.

You can configure it like:
```py
class liteBDRAR(pl.LightningModule):
         def __init__(self, pt_ckpt_path=None):
              super(liteBDRAR, self).__init__()
              self.model = BDRAR()

              if pt_ckpt_path is not None:
                  ckpt_weights = torch.load(pt_ckpt_path)
                  self.model.load_state_dict(ckpt_weights)

              print('Model Created!')

         def forward(self, x):
              return self.model(x)
```
and run:
```py
path = './ckpt/BDRAR/3000.pth'
model = liteBDRAR(pt_ckpt_path=path)
trainer = pl.Trainer(fast_dev_run=True, gpus=1)
trainer.fit(bdrar)
```

**Comment by JohnDuke259** [comment]
Many thanks @rohitgr7! I got help from another forum and it worked without any runtime error.
