### ISSUE TITLE
Bug report colab notebook incorrectly imports `pytorch_lightning.metrics.functional`

### ISSUE THREAD

**Issue by EricWiener** [PyTorchLightning/pytorch-lightning#11424]
## 📚 Documentation
Bug report notebook pinned in slack ([this one](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing)) imports:
```
from pytorch_lightning.metrics.functional import accuracy
```

However, `metrics` was moved to a separate package so this either needs to be installed or not imported.

I can't make the change since I don't own the notebook.

cc @borda @rohitgr7

**Comment by rohitgr7** [comment]
bug report model was updated to: https://colab.research.google.com/github/PytorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report/bug_report_model.ipynb in the issue template.

is there any place you found the older one linked?

**Comment by EricWiener** [comment]
It was pinned in the #questions channel in slack @rohitgr7

**Comment by rohitgr7** [comment]
good catch! updated there :)

**Comment by EricWiener** [comment]
Thanks!
