### ISSUE TITLE
"Edit On Github" link is broken for notebooks

### ISSUE THREAD

**Issue by GaurangTandon** [PyTorchLightning/pytorch-lightning#11434]
## 📚 Documentation

On this [documentation page](https://pytorch-lightning.readthedocs.io/en/stable/notebooks/lightning_examples/text-transformers.html#Transformer-LightningModule), clicking "Edit on GitHub" redirects to a page which is 404 on GitHub.

I can't seem to find this notebook in `docs/source` on the latest branch either. Moreover, this link remains broken for the oldest listed version (1.4.0 in this case). This is the [link](https://github.com/PyTorchLightning/pytorch-lightning/blob/1.4.0/docs/source/notebooks/lightning_examples/text-transformers.ipynb) given in the docs and it does not work.

Kindly let me know where to find this on GitHub, as I intend to submit questions related to the code given in this documentation page. Thanks

cc @borda @rohitgr7

**Comment by Borda** [comment]
this could be hard as these notebooks are coming from git submodule and they are copied during generating the documentation... in contrast, the "Edit On Github" is sphinx wide (template-wise) future with relatively strictly defined behavior... so the only thing we can do is drop it for these pages and add custom download link inside each notebook...
or do you have any better idea, @ethanwharris ?
