### ISSUE TITLE
`use_amp` is broken in 0.7.0

### ISSUE THREAD

**Issue by rmrao** [PyTorchLightning/pytorch-lightning#1143]
I see that `use_amp` is deprecated but since the Trainer still accepts it as an argument, I believe this is still a bug. 

The issue is that the [hook that deals with this](https://github.com/PyTorchLightning/pytorch-lightning/blob/3c2fd560aa4d31b4f48ee225b83361deec53d9c7/pytorch_lightning/core/hooks.py#L136-L143) specifically checks if `trainer.precision == 16`. However, the Trainer does not set `precision = 16` if `use_amp = True`.

Proposed solution:

if `use_amp` is passed in, set precision = 16 and raise a deprecation warning.

**Comment by Borda** [comment]
that s a good catch, thx! could send a fix PR? :robot:

**Comment by rmrao** [comment]
Submitted!
