### ISSUE TITLE
ModelCheckpointCallback doesnt delete previous -last.ckpt while saving recent one

### ISSUE THREAD

**Issue by nithinraok** [PyTorchLightning/pytorch-lightning#11451]
## 🐛 Bug

ModelCheckpointCallback doesn't delete previous -last.ckpt while saving recent one. 
This is the snapshot of the checkpoints directory for (save_top_k=1 and save_last=True) 

> test_last_ckpt_issue--val_loss=1.8490-epoch=13.ckpt
> test_last_ckpt_issue--val_loss=1.8490-epoch=13-last.ckpt
> test_last_ckpt_issue--val_loss=6.0828-epoch=6-last.ckpt

As can be seen before saving epoch=7-last.ckpt it didnt delete *6-last.ckpt 

### To Reproduce

```py

import torch
from torch import nn
from torch.nn import functional as F
from torch.utils.data import DataLoader
from torch.utils.data import random_split
from torchvision.datasets import MNIST
from torchvision import transforms
import pytorch_lightning as pl
from pytorch_lightning.callbacks import ModelCheckpoint
# from pytorch_lightning.strategies import DDPStrategy

class LitAutoEncoder(pl.LightningModule):
	def __init__(self):
		super().__init__()
		self.encoder = nn.Sequential(
      nn.Linear(28 * 28, 64),
      nn.ReLU(),
      nn.Linear(64, 3))
		self.decoder = nn.Sequential(
      nn.Linear(3, 64),
      nn.ReLU(),
      nn.Linear(64, 28 * 28))

	def forward(self, x):
		embedding = self.encoder(x)
		return embedding

	def configure_optimizers(self):
		optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
		return optimizer

	def training_step(self, train_batch, batch_idx):
		x, y = train_batch
		x = x.view(x.size(0), -1)
		z = self.encoder(x)    
		x_hat = self.decoder(z)
		loss = F.mse_loss(x_hat, x)
		self.log('train_loss', loss)
		return loss

	def validation_step(self, val_batch, batch_idx):
		x, y = val_batch
		x = x.view(x.size(0), -1)
		z = self.encoder(x)
		x_hat = self.decoder(z)
		loss = F.mse_loss(x_hat, x)
		self.log('val_loss', loss)

def build_dataset():
	# data
	dataset = MNIST('', train=True, download=True, transform=transforms.ToTensor())
	mnist_train, mnist_val = random_split(dataset, [55000, 5000])
	train_loader = DataLoader(mnist_train, batch_size=32,num_workers=20)
	val_loader = DataLoader(mnist_val, batch_size=32,num_workers=20)

	return train_loader,val_loader

if __name__ == '__main__':

	train_loader, val_loader = build_dataset()
	# model
	model = LitAutoEncoder()

	#Callback
	checkpoint_callback = ModelCheckpoint(
	monitor='val_loss',
	dirpath='./test_last_ckpt',
	filename='test_last_ckpt-{val_loss:.2f}-{epoch}',
	save_last=True,
	save_top_k=4,
	)
	ModelCheckpoint.CHECKPOINT_NAME_LAST='test_last_ckpt-{val_loss:.2f}-{epoch}'+'-last'

	# training
	trainer = pl.Trainer(gpus=-1, num_nodes=1,max_epochs=5,max_steps=-1,
	strategy='ddp',
	logger=False,
	benchmark=True,
	callbacks=[checkpoint_callback]
	)
	
	trainer.fit(model, train_loader, val_loader)
```

### Expected behavior

Should only save one latest -last.ckpt while deleting all previous *-last.ckpt 

### Environment

* CUDA:
        - GPU:
                - Quadro GV100
        - available:         True
        - version:           10.2
* Packages:
        - numpy:             1.20.3
        - pyTorch_debug:     False
        - pyTorch_version:   1.10.1+cu102
        - pytorch-lightning: 1.5.8
        - tqdm:              4.62.3
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.9.7
        - version:           #45~20.04.1-Ubuntu SMP Wed Nov 10 10:20:10 UTC 2021

cc @tchaton @rohitgr7 @awaelchli @carmocca @ninginthecloud @jjenniferdai

**Comment by carmocca** [comment]
Hi!

Are you able to reproduce the issue with our bug report template? https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report/bug_report_model.py

Also, can you share the precise trainer and callback configuration used?

**Comment by nithinraok** [comment]
Hi, updated the issue please check again. 
This issue is not reproducible always (I am guessing due to versioning). Previously I observed the issue only on multi-node but I was able to get a system that I could reproduce the issue locally as well not just multi-node.

**Comment by carmocca** [comment]
I ran your code a number of times but could not reproduce it unfortunately.

Just to clarify, you can reproduce this by running that script just once even when the `test_last_ckpt` directory is empty before running, correct?

**Comment by nithinraok** [comment]
Ok I got it reproducible, I updated the reproducible code (Added `trainer.logger=False`) 
To Reproduce,
Run the full code and let it finish, and with watching the exp directory (`watch ls test_last_ckpt`), 
run the code again, now you would notice it starts to save epoch-0-last.ckpt checkpoint without cleaning epoch=4-last.ckpt

**Comment by nithinraok** [comment]
That's one. 
Another way: 
Clear the checkpoint directory.
Run the initial code up to say the end of 1 epoch and interrupt the training. 
Then add this piece of code to resume next run from epoch-1-last.ckpt as shown below
`trainer.checkpoint_connector.resume_from_checkpoint_fit_path='./test_last_ckpt/test_last_ckpt-val_loss=0.04-epoch=1-last.ckpt'` 
Rerun the code, now the training starts from epoch 2 - which is how it should be but, after finishing epoch 2 it doesnt delete the previous last checkpoint and creates another epoch-2-last.ckpt keeping the earlier one as is.

**Comment by nithinraok** [comment]
Created PR #https://github.com/PyTorchLightning/pytorch-lightning/pull/11481  to fix issue mentioned in https://github.com/PyTorchLightning/pytorch-lightning/issues/11451#issuecomment-1013518312 

But there is another issue:
Since I turned logger=False, it shouldn't create any version (like v1 v2 etc while saving checkpoints) and should overwrite the previous checkpoints if name matches to previous checkpoints right? But it doesn't. 

To Reproduce:
Run the full code and let it finish, and with watching the exp directory (`watch ls test_last_ckpt`),
run the code again, now you would notice it starts to save `*epoch=0-last.ckpt` checkpoint without cleaning `*epoch=4-last.ckpt` and also creates `*epoch=1-v1.ckpt` etc

**Comment by awaelchli** [comment]
When resuming from the checkpoint, it might be that the checkpoint callback does not reload its state. The deleting of the last checkpoint depends on the last_model_path variable being set, and if the states are not reloaded correctly, this could explain your behavior. So I would investigate that the  `ModelCheckpoint.on_load_checkpoint` gets called and that last_model_path is set when resuming.

**Comment by nithinraok** [comment]
I provided the fix [[#11481](https://github.com/PyTorchLightning/pytorch-lightning/pull/11481)]  to save the state correctly for last_model_path variable to store the latest model path correctly in case the training interrupts in between.  @carmocca @awaelchli could you review and suggest the fix accordingly? This is causing major issues while performing distributed training. Thanks.

**Comment by carmocca** [comment]
@nithinraok When you run your script for the second time, you are not passing an existing checkpoint to the trainer to resume: `.fit(..., ckpt_path="your_checkpoint.ckpt")`

This means that the `ModelCheckpoint` state does not get restored so the `last_model_path` from the previous run will not get deleted.

Considering that, training gets run again from the beginning and new checkpoints are generated:
- In the case of normal checkpoints, a version suffix gets appended (`*-v1.ckpt`).
- For last checkpoints, they get overwritten. The `epoch=4-last.ckpt` you see after the second run is the last checkpoint of the second run which overwrote the last checkpoint of the first run.

There's a feature request to add version suffix to "last" checkpoints #5030

So from my debugging, this is working as expected.

**Comment by carmocca** [comment]
If you don't actually want to resume from a checkpoint and you want to keep both "last" checkpoints from both runs, you have 3 options:

- Use an unique `ModelCheckpoint(dirpath=...)` per run.
- Use an unique `trainer.checkpoint_callback.CHECKPOINT_NAME_LAST=...` per run.
- Implement the feature #5030

**Comment by jjenniferdai** [comment]
> When you run your script for the second time, you are not passing an existing checkpoint to the trainer to resume: .fit(..., ckpt_path="your_checkpoint.ckpt")

+1, please use the supported `.fit(ckpt_path=)` API to resume from checkpoint (https://pytorch-lightning.readthedocs.io/en/latest/common/checkpointing.html#restoring-training-state)

> trainer.checkpoint_connector.resume_from_checkpoint_fit_path='./test_last_ckpt/test_last_ckpt-val_loss=0.04-epoch=1-last.ckpt'

this line that was being used is a lightning-internal only variable present only to continue supporting the deprecated `Trainer(resume_from_checkpoint=)` API until its removal in v2.0.

**Comment by nithinraok** [comment]
@carmocca what do you mean by ` you are not passing an existing checkpoint to the trainer to resume: .fit(..., ckpt_path="your_checkpoint.ckpt")` Are you referring to -last.ckpt or any .ckpt file? 

When resume from a saved checkpoint dir.. I expect to have only one -last.ckpt flle, deleting all previous ones if exist. 

changing to  `.fit(ckpt_path=)` doesnt help either in this case , I can still reproduce the issue.

**Comment by nithinraok** [comment]
Let me explain the issue and intended behavior again. 

Using the code mentioned in https://github.com/PyTorchLightning/pytorch-lightning/issues/11451#issue-1100736679 , I run the code for few epochs, lets say 1. [This means epoch 0 and epoch 1 have finished and I interupted the training after end of first epoch that is during 2nd epoch] 
At this point, checkpoint directory looks like this:

> test_last_ckpt-val_loss=0.04-epoch=0.ckpt
> test_last_ckpt-val_loss=0.04-epoch=1.ckpt
> test_last_ckpt-val_loss=0.04-epoch=1-last.ckpt

Now when I resume training with `trainer.fit(...,ckpt_path="test_last_ckpt-val_loss=0.04-epoch=1-last.ckpt")` I expect training to resume from 2nd epoch and after 2nd epoch gets finished, it should delete "test_last_ckpt-val_loss=0.04-epoch=1-last.ckpt" keeping only "test_last_ckpt-val_loss=0.04-epoch=2-last.ckpt" 

but this is how it looks:

> test_last_ckpt-val_loss=0.04-epoch=0.ckpt
> test_last_ckpt-val_loss=0.04-epoch=1.ckpt
> test_last_ckpt-val_loss=0.04-epoch=1-last.ckpt
> test_last_ckpt-val_loss=0.04-epoch=2.ckpt
> test_last_ckpt-val_loss=0.04-epoch=2-last.ckpt
> 

While I expect the directory should look like:

> test_last_ckpt-val_loss=0.04-epoch=0.ckpt
> test_last_ckpt-val_loss=0.04-epoch=1.ckpt
> test_last_ckpt-val_loss=0.04-epoch=2.ckpt
> test_last_ckpt-val_loss=0.04-epoch=2-last.ckpt
> 

Please let me know if that is not how it should behave, thanks much

**Comment by carmocca** [comment]
@nithinraok Would you mind adapting the following script to reproduce the behaviour? Both fit calls can be done in the same script to simplify the demostration

<details>

```python
import os
import shutil

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer
from pytorch_lightning.callbacks import ModelCheckpoint


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return loss

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    model = BoringModel()

    # remove data
    dir = f"{os.getcwd()}/debug"
    shutil.rmtree(dir, ignore_errors=True)

    # configure model checkpoint
    model_checkpoint = ModelCheckpoint(
        dirpath=dir, filename="{epoch}", monitor="valid_loss", save_last=True, save_top_k=-1
    )
    model_checkpoint.CHECKPOINT_NAME_LAST = "{epoch}-last"

    # first run
    trainer = Trainer(
        max_epochs=3, callbacks=model_checkpoint, enable_model_summary=False, enable_progress_bar=False, logger=False
    )
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)

    actual = set(os.listdir(dir))
    assert actual == {
        "epoch=1.ckpt",
        "epoch=0.ckpt",
        "epoch=2.ckpt",
        "epoch=2-last.ckpt",
    }

    # second run
    trainer = Trainer(
        max_epochs=6, callbacks=model_checkpoint, enable_model_summary=False, enable_progress_bar=False, logger=False
    )
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data, ckpt_path=f"{dir}/epoch=2-last.ckpt")

    actual = set(os.listdir(dir))
    assert actual == {
        "epoch=0.ckpt",
        "epoch=1.ckpt",
        "epoch=2.ckpt",
        "epoch=3.ckpt",
        "epoch=4.ckpt",
        "epoch=5.ckpt",
        "epoch=5-last.ckpt",
    }


if __name__ == "__main__":
    run()
```

</details>

The assertions currently pass

**Comment by nithinraok** [comment]
@carmocca I think the important thing to note here is the interruption of training and resuming from where we left. This scenario happens while we train on clusters, where after a certain time limit job gets killed and we would want our next job to safely restore states and resume running. 

The script you mentioned passes assertions at my end too.

**Comment by carmocca** [comment]
My point is that we need a (generally) reproducible snippet to fully understand the problem and write a test to avoid a regression. A repro recipe of running multiple scripts is hard to get right so I would like that we isolate the problem to its most minimal form.

You can take that script and start adapting it until you observe the behavior you see in the clusters. I just wanted to provide the starting piece.

**Comment by nithinraok** [comment]
@carmocca I wish I could provide you a script end to end to replicate the behavior that was shown above with appropriate trainer flags but I couldn't. I tried the `max_steps` option to stop training at 2nd epoch but checkpoint states have been safely stored as `epoch 2-last.ckpt` even though it doesn't finish the epoch fully. So I couldn't replicate the interruption behavior. 

But, I hope you understand that the issue arises only when script has been killed by SIGKILL. I can't think of any other way to reproduce the issue in a single script without SIGKILL at the moment.

**Comment by carmocca** [comment]
Wouldn't raising an exception manually reproduce it? Does it need to be a SIGKILL?

```python
class MyModel:
    def training_step():
        if self.global_step == ...:
            raise SystemExit(1)
        ...

trainer = Trainer(...)
try:
    trainer.fit(...)
except SystemExit:
    print("SystemExit caught", os.listdir(...))

trainer = Trainer(...)
trainer.fit(..., ckpt_path=...)
```

**Comment by nithinraok** [comment]
Thanks for the suggestion, here is the snippet to reproduce the error :) 


```python
import torch
from torch import nn
from torch.nn import functional as F
from torch.utils.data import DataLoader
from torch.utils.data import random_split
from torchvision.datasets import MNIST
from torchvision import transforms
import pytorch_lightning as pl
from pytorch_lightning.callbacks import ModelCheckpoint
import os
# from pytorch_lightning.strategies import DDPStrategy

class LitAutoEncoder(pl.LightningModule):
	
	def __init__(self):
		super().__init__()
		self.encoder = nn.Sequential(
      nn.Linear(28 * 28, 64),
      nn.ReLU(),
      nn.Linear(64, 3))
		self.decoder = nn.Sequential(
      nn.Linear(3, 64),
      nn.ReLU(),
      nn.Linear(64, 28 * 28))

	def forward(self, x):
		embedding = self.encoder(x)
		return embedding

	def configure_optimizers(self):
		optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
		return optimizer

	def training_step(self, train_batch, batch_idx):
		x, y = train_batch
		x = x.view(x.size(0), -1)
		z = self.encoder(x)    
		x_hat = self.decoder(z)
		loss = F.mse_loss(x_hat, x)
		self.log('train_loss', loss)
		return loss

	def validation_step(self, val_batch, batch_idx):
		x, y = val_batch
		x = x.view(x.size(0), -1)
		z = self.encoder(x)
		x_hat = self.decoder(z)
		loss = F.mse_loss(x_hat, x)
		self.log('val_loss', loss)

class ModifiedEncoder(LitAutoEncoder):
	def __init__(self):
		super().__init__()

	def training_step(self, train_batch, batch_idx):
		x, y = train_batch
		x = x.view(x.size(0), -1)
		z = self.encoder(x)    
		x_hat = self.decoder(z)
		loss = F.mse_loss(x_hat, x)
		self.log('train_loss', loss)

		if self.global_step == 4500:
			raise SystemExit(1)

		return loss

def build_dataset():
	# data
	dataset = MNIST('', train=True, download=True, transform=transforms.ToTensor())
	mnist_train, mnist_val = random_split(dataset, [55000, 5000])
	train_loader = DataLoader(mnist_train, batch_size=32,num_workers=20)
	val_loader = DataLoader(mnist_val, batch_size=32,num_workers=20)

	return train_loader,val_loader

if __name__ == '__main__':

	train_loader, val_loader = build_dataset()
	# model
	model = ModifiedEncoder()

	#Callback
	checkpoint_callback = ModelCheckpoint(
	monitor='val_loss',
	dirpath='./test_last_ckpt',
	filename='test_last_ckpt-{val_loss:.2f}-{epoch}',
	save_last=True,
	save_top_k=2,
	)
	ModelCheckpoint.CHECKPOINT_NAME_LAST='test_last_ckpt-{val_loss:.2f}-{epoch}'+'-last'

	# training
	trainer = pl.Trainer(gpus=-1, num_nodes=1,max_epochs=8,
	strategy='ddp',
	logger=False,
	benchmark=True,
	callbacks=[checkpoint_callback],
	)
	
	resume_from_checkpoint_fit_path=None
	try:
		trainer.fit(model, train_loader, val_loader, ckpt_path=resume_from_checkpoint_fit_path)
	except:
		print("System exit caught", os.listdir('./test_last_ckpt'))

	model = LitAutoEncoder()
	
	trainer = pl.Trainer(gpus=-1, num_nodes=1,max_epochs=8,max_steps=-1,
	strategy='ddp',
	logger=False,
	benchmark=True,
	callbacks=[checkpoint_callback],
	)
	resume_from_checkpoint_fit_path='test_last_ckpt/test_last_ckpt-val_loss=0.04-epoch=1-last.ckpt'
	
	trainer.fit(model, train_loader, val_loader, ckpt_path=resume_from_checkpoint_fit_path)
	print("After finishing 2nd run ",os.listdir('./test_last_ckpt'))

```

**Comment by nithinraok** [comment]
Adapting the script you provided:
<details>
<summary> Adapting the script you provided: </summary>
<br>

```python
import os
import shutil

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer
from pytorch_lightning.callbacks import ModelCheckpoint


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        return loss

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)

class ModifiedModel(BoringModel):
    def __init__(self):
        super().__init__()
    
    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        if self.global_step == 80:
            raise SystemExit(1)
        return loss 

def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    model = ModifiedModel()

    # remove data
    dir = f"{os.getcwd()}/debug"
    shutil.rmtree(dir, ignore_errors=True)

    # configure model checkpoint
    model_checkpoint = ModelCheckpoint(
        dirpath=dir, filename="{epoch}", monitor="valid_loss", save_last=True, save_top_k=2
    )
    model_checkpoint.CHECKPOINT_NAME_LAST = "{epoch}-last"

    # first run
    trainer = Trainer(
        max_epochs=6, callbacks=model_checkpoint, enable_model_summary=False, enable_progress_bar=False, logger=False
    )
    try:
        trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
    except:
        print("system exit caught",os.listdir(dir))

    actual = set(os.listdir(dir))
    assert actual == {
        "epoch=1.ckpt",
        "epoch=0.ckpt",
        "epoch=1-last.ckpt",
    }

    model = BoringModel()
    # second run
    trainer = Trainer(
        max_epochs=6, callbacks=model_checkpoint, enable_model_summary=False, enable_progress_bar=False, logger=False
    )

    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data, ckpt_path=f"{dir}/epoch=1-last.ckpt")

    actual = set(os.listdir(dir))
    assert actual == {
        "epoch=4.ckpt",
        "epoch=5.ckpt",
        "epoch=5-last.ckpt",
    }


if __name__ == "__main__":
    run()
```
</details>

This gets fixed with the PR I provided but it has a problem of a checkpoint being deleted in case the interruption happens at that movement. One way is, we could copy last_model_path to a temp variable and save first then delete prev checkpoint.

**Comment by carmocca** [comment]
Thanks! This was helpful. We can use the a temporary variable.

I updated your PR and added a test

**Comment by nithinraok** [comment]
Thank you @carmocca 💯
