### ISSUE TITLE
Pretty test result with pprint

### ISSUE THREAD

**Issue by S-aiueo32** [PyTorchLightning/pytorch-lightning#1146]
### Motivation
Test results are shown at the end of test loops since v0.7.0.
The content of the indication is `prog_bar_metrics`, which is basically inputted as a `dict`.
By default, this part uses built-in `print` function:
![image](https://user-images.githubusercontent.com/14917234/76911857-44df9100-68f5-11ea-8719-744acfc05855.jpeg)
This way cannot display the pretty results so I suggest using `pprint`:
![image](https://user-images.githubusercontent.com/14917234/76911882-5c1e7e80-68f5-11ea-81c5-54226c3262e8.jpeg)

### Pitch
- Substitute `print` at the end of the test loop with `pprint` .

### Alternatives
Modify [here ](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/evaluation_loop.py#L375)like:
```python
        if test_mode:
            if self.proc_rank == 0:
                from pprint import pprint

                print('-' * 100)
                print('TEST RESULTS')
                pprint(prog_bar_metrics)
                print('-' * 100)
```

**Comment by S-aiueo32** [comment]
PR is ready 64a2f602170df382befc18f4a4c2c06379269543

**Comment by Borda** [comment]
can you please also add output or illustration?
just feel a bit puzzled, the commit seems to be this repo, but I can't find it in master nor open PR
anyway I do agree that `pprint` gives better formatting also for `dict` it is ordered
