### ISSUE TITLE
Instantiating callbacks from CLI fails

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#11489]
### To Reproduce

On master:

```
python pl_examples/basic_examples/autoencoder.py  --trainer.callbacks=pytorch_lightning.callbacks.early_stopping.EarlyStopping --trainer.callbacks.patience=5
```

### Expected behavior

As described in the [docs](https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_cli.html#trainer-callbacks-and-arguments-with-class-type), we should be able to instantiate the callback from the CLI with the above syntax.

### Environment

You can also fill out the list below manually.
-->

- PyTorch Lightning Version (e.g., 1.5.0): master and 1.5.8
- PyTorch Version (e.g., 1.10): 1.10
- Python version (e.g., 3.9): 3.9
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information: jsonargparse-4.1.1

### Additional context

X

cc @carmocca @mauvilsa

**Comment by carmocca** [comment]
You don't need to specify the full classpath using the shorthand notation.

`python pl_examples/basic_examples/autoencoder.py  --trainer.callbacks=EarlyStopping --trainer.callbacks.patience=5`

You might have noticed already. Posting the answer in case somebody finds this issue.
