### ISSUE TITLE
[Bug] Progress bar displays wrong total iterations for train

### ISSUE THREAD

**Issue by versatran01** [PyTorchLightning/pytorch-lightning#1148]
#1018  🐛 Bug

for example, my training dataset has 448 samples, and I use a batch size of 4, then the loader should have length 448 / 4 = 112, but the progress bar is displaying N/171, which I have no idea how it computes that. The training then proceeds normally until it hits 112/171 and enters validation.

**Comment by isolet** [comment]
Have you figure out how the total iteration is computed?

**Comment by versatran01** [comment]
I think it is the sum of train and val iteration, which is confusing.

**Comment by ThierryDeruyttere** [comment]
Yes it is very confusing. I think this should be fixed though. It took me at least 1 hour to come to the same conclusion. I first thought I made a mistake in my dataloader but this wasn't the case.

**Comment by dtoniolo** [comment]
Agree, I find it counter-intuitive
