### ISSUE TITLE
Mark `CheckpointConnector` as protected

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#11482]
## Proposed refactor

Mark `CheckpointConnector` as protected:
https://github.com/PyTorchLightning/pytorch-lightning/blob/18bbb39eef77c8c3d19789b1067164e962640c93/pytorch_lightning/trainer/trainer.py#L464

### Motivation

Part of #9778

cc @borda @justusschock @awaelchli @akihironitta @rohitgr7 @kaushikb11 @ninginthecloud

**Comment by krishnakalyan3** [comment]
I would like to work on this!

**Comment by rohitgr7** [comment]
@krishnakalyan3 awsome!

please go ahead with a PR :)
