### ISSUE TITLE
PyTorch Profiler leaks memory

### ISSUE THREAD

**Issue by EricWiener** [PyTorchLightning/pytorch-lightning#11480]
## 🐛 Bug
When using `profiler="PyTorch"`, memory usage (as measured by vm_percent) will keep increasing until running out of memory.

### To Reproduce
No code yet, but will try to make an example. Just wanted to make this public info.

### Expected behavior
The profiler doesn't leak memory.

### Environment
- PyTorch Lightning Version (e.g., 1.5.0): 1.5.8
- PyTorch Version (e.g., 1.10): 1.10.1
- Python version (e.g., 3.9): 3.6
- OS (e.g., Linux): Linux
- CUDA/cuDNN version: 11.2
- GPU models and configuration: GeForce RTX 2080 Ti
- How you installed PyTorch (`conda`, `pip`, source): pip
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context
N/A

cc @carmocca @kaushikb11 @ninginthecloud @rohitgr7

**Comment by tchaton** [comment]
Hey @EricWiener, do you have a reproducible script ?

**Comment by EricWiener** [comment]
Hi @tchaton I wasn't able to immediately reproduce this in colab, but will hopefully be able to at some point. For reference, here are charts of Memory usage for the same job where one had the profiler and one didn't (blacked out some irrelevant info):
![CleanShot 2022-01-16 at 09 24 10@2x](https://user-images.githubusercontent.com/18071029/149664034-e10e7a5b-65b3-43cc-a6e6-f05792bc54ce.png)
![CleanShot 2022-01-16 at 09 26 03@2x](https://user-images.githubusercontent.com/18071029/149664035-c1d6b094-fb6e-4a19-8b6e-da0ab085d0c3.png)

**Comment by EricWiener** [comment]
Is there any chance any behavior of the profiler is tied to the end of an epoch (ex. clearing out the cache or summing up metrics)? I'm training with an infinite epoch, so was thinking this could be a source of the issue

**Comment by tchaton** [comment]
Hey @EricWiener. Are you overriding on_epoch_X hook. The output of your steps would be stored automatically for you. This could explain the memory leakage.

**Comment by EricWiener** [comment]
I'm not overriding `on_epoch_X` hook, but I am overriding `pl_module.log` with:

```
def log(  # type: ignore[override]
        self, name: str, value: _METRIC_COLLECTION, **kwargs: Any
    ) -> None:
        if self.trainer and self.trainer.state.stage == RunningStage.TRAINING:
            kwargs.update(on_step=True)
            kwargs.update(on_epoch=False)
        super().log(name, value, **kwargs)
```

with the intent to turn off all epoch behavior.

**Comment by tchaton** [comment]
Hey @EricWiener,

Thanks for sharing. If you manage to make a reproducible script, this would be quite good.

**Comment by carmocca** [comment]
We should log a warning when training is configure to run an infinite epoch and the LightningModule overrides `training_epoch_end`.

**Comment by tchaton** [comment]
@carmocca Mind creating an issue ?
