### ISSUE TITLE
Mark `SignalConnector` as protected:

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#11483]
## Proposed refactor

Mark `SignalConnector` as protected:
https://github.com/PyTorchLightning/pytorch-lightning/blob/18bbb39eef77c8c3d19789b1067164e962640c93/pytorch_lightning/trainer/trainer.py#L465

### Motivation

Part of #9778

cc @borda @justusschock @awaelchli @akihironitta @rohitgr7 @kaushikb11 @ninginthecloud

**Comment by rohitgr7** [comment]
@Cyber-Machine  awsome!

please go ahead with a PR :)
