### ISSUE TITLE
I have runned: `pip install pytorch-lightning`, but get error: No module named `pytorch_lightning`

### ISSUE THREAD

**Issue by muyuuuu** [PyTorchLightning/pytorch-lightning#11499]
### Discussed in https://github.com/PyTorchLightning/pytorch-lightning/discussions/11498

<div type='discussions-op-text'>

<sup>Originally posted by **muyuuuu** January 16, 2022</sup>
![image](https://user-images.githubusercontent.com/43681138/149628558-289611ed-244e-4ed7-95d0-c34d4e341520.png)

python: 3.8.8
pytorch: 1.7.0
pytorch-lightning: 1.5.8
windows 10 and anaconda 4.11.0</div>

**Comment by semaphore-egg** [comment]
This issue probably is not related to lightning.

Check if lightning is successfully installed in correct environments and activate the environment before running the code.
Following commands might help:
`which pip`
`pip list` 
`conda env list`
`conda activate env_name`

**Comment by akihironitta** [comment]
@muyuuuu Would you mind trying @semaphore-egg's suggestion? Or you could also try:

```
python -m pip install pytorch-lightning
```

**Comment by muyuuuu** [comment]
> 

1. /c/programData/Miniconda3/Scripts/pip
2. pip list shows pytorch-lightning: 1.5.8
3. I didn't create virtual environment

**Comment by estathop** [comment]
> @muyuuuu Would you mind trying @semaphore-egg's suggestion? Or you could also try:
> 
> ```
> python -m pip install pytorch-lightning
> ```

This solved the case for me in MACOSX and MacBook Air early 2015
