### ISSUE TITLE
Propose to save new model before deleting previous ones in ModelCheckpointing

### ISSUE THREAD

**Issue by Ir1d** [PyTorchLightning/pytorch-lightning#1150]
## 🚀 Feature

In an edge case, the trainer deleted previous model and then was killed because of system error before successfully saving new model. Thus all the models were lost.
I understand specifying save_top_k > 1 helps, and saving before deleting leads to larger disk consumption. But it might be good to provide an option for this?
### Pitch

in the worst case, you have two but never none...

**Comment by Borda** [comment]
That is good point, I like it... @PyTorchLightning/core-contributors ^^

**Comment by williamFalcon** [comment]
@Ir1d sounds great. submit a PR?

**Comment by Ir1d** [comment]
I can do it this friday
