### ISSUE TITLE
`import pytorch_lightning` fails with `ValueError: transformers.models.auto.__spec__ is None`

### ISSUE THREAD

**Issue by nonstopfor** [PyTorchLightning/pytorch-lightning#11524]
## 🐛 Bug

A ValueError occurs whenever PyTorch Lightning is imported after Huggingface's Transformer. Importing Transformer after PyTorch does not lead to any errors, however. 

### To Reproduce
Tested in local anaconda environment:
import this:
```
from transformers import T5ForConditionalGeneration, T5Tokenizer
import pytorch_lightning
```
It seems that this issue doesn't exist on Google Colab.

### Expected behavior
```
ValueError: transformers.models.auto.__spec__ is None
```

### Environment
* CUDA:
        - GPU:
                - TITAN X (Pascal)
                - TITAN X (Pascal)
                - TITAN X (Pascal)
                - TITAN X (Pascal)
        - available:         True
        - version:           10.1
* Packages:
        - numpy:             1.22.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.8.1+cu101
        - pytorch-lightning: 1.5.8
        - tqdm:              4.61.2
        - transformers: 4.15.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.9.5
        - version:           #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017

**Comment by akihironitta** [comment]
It seems to happen with `torchmetrics==0.7` which was released yesterday as reported in https://github.com/PyTorchLightning/metrics/issues/770.

**Comment by nonstopfor** [comment]
Thanks! It is solved now.

**Comment by akihironitta** [comment]
Let's keep this issue open until it gets fixed :)

**Comment by BenoitDalFerro** [comment]
exact same issue exact same diagnostic with install as of yesterday 22/01/2022 20h51 GMT+1
` torchmetrics  0.7.0 pyhd8ed1ab_0    conda-forge`
downgrading to torchmetric<0.7.0 as a quick fix did the trick
