### ISSUE TITLE
[bug] missing np.array handling in _get_dataloader_init_kwargs

### ISSUE THREAD

**Issue by yifeim** [PyTorchLightning/pytorch-lightning#11529]
https://github.com/PyTorchLightning/pytorch-lightning/blob/033dba1494a177954e8ca59bc74b1635e83b9efa/pytorch_lightning/utilities/data.py#L225

This line of code yields an error if I initialize `predict_dataset = torch.utils.data.DataLoader(np.array(5))`, because the comparison `<inspect._empty> != np.array(5)` will return a numpy array, which is unacceptable by true/false comparators. A possible fix is to skip the first argument in the check, where such inputs may show up.

**Comment by rohitgr7** [comment]
PyTorch, dataloaders doesn't accept NumPy arrays. It should be a Dataset.
https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader
