### ISSUE TITLE
inference_mode

### ISSUE THREAD

**Issue by ZhaofengWu** [PyTorchLightning/pytorch-lightning#11530]
PyTorch has an `inference_mode` (https://pytorch.org/docs/stable/generated/torch.inference_mode.html) that it recommends as a replacement for `no_grad`. But I don't think lightning is currently using it. Should it?

cc @borda @awaelchli @rohitgr7 @akihironitta

**Comment by shabie** [comment]
Pretty cool. When was this introduced in PyTorch? Seems very recent.

**Comment by ananthsub** [comment]
We actually added support for it: https://github.com/PyTorchLightning/pytorch-lightning/issues/8499
But needed to revert as inference mode wasn't supported across all process group backends, which led to errors with distributed. That being said, we could try landing this again and selectively disabling it depending on the underlying configuration (e.g. if gloo is used, don't use inference mode)

**Comment by ZhaofengWu** [comment]
I believe that's probably worth doing -- given how common inference is, even small improvements here would probably mean a lot.

**Comment by ZhaofengWu** [comment]
Commenting for activity

**Comment by ananthsub** [comment]
@ZhaofengWu in the meantime, you can do this:
```py
with torch.inference_mode():
    trainer.predict(...)
```
