### ISSUE TITLE
Ability to change the number of epochs after initiating the trainer.

### ISSUE THREAD

**Issue by BartekKrzepkowski** [PyTorchLightning/pytorch-lightning#11547]
## 🚀 Feature

Ability to change the number of epochs after initiating the trainer.

### Motivation

Imagine that you have defined a model and you are creating a trainer with the parameter max_epochs = n. After training the model, you are going to change something in the dataset and continue training with more epochs. It cannot be done (to my knowledge) without creating a new trainer. The problem in this situation is the lack of continuity in logger reporting. It creates a new rune or overwrites the old one.

### Pitch

Method to change the number of epochs, or set the number of epochs only during .fit()

cc @borda

**Comment by ananthsub** [comment]
Here's a related RFC that discussed this: https://github.com/PyTorchLightning/pytorch-lightning/issues/10444

**Comment by atif-hassan** [comment]
In my case, I had to train a model for a few iterations, before making some changes and then continue training the same model for 98 epochs. To achieve this using the same trainer, I used the following code:

`trainer.fit_loop.max_epochs=98`
`trainer.fit_loop.max_steps=-1`

**Comment by coffeecoding** [comment]
@atif-hassan That's the only solution that worked for me as well.
