### ISSUE TITLE
add ffcv data loader

### ISSUE THREAD

**Issue by paantya** [PyTorchLightning/pytorch-lightning#11553]
## 🚀 Feature

add:
Fast Forward Computer Vision: train models at a fraction of the cost with accelerated data loading!
https://github.com/libffcv/ffcv

### Motivation

speedup training

cc @borda

**Comment by Borda** [comment]
I think it is duplicate to #11538 :rabbit:

**Comment by paantya** [comment]
cool!
yes, tnx
