### ISSUE TITLE
[RFC] Deprecate `on_before_accelerator_backend_setup` hook

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#11559]
## Proposed refactor

Deprecate `on_before_accelerator_backend_setup` hook in v1.6 for removal in v1.8. Redirect users to the `setup` hook.
https://github.com/PyTorchLightning/pytorch-lightning/blob/5ad5ba54c0c477546d21daf75ac7b4748d7963a7/pytorch_lightning/callbacks/base.py#L63-L65

### Motivation

I only see two external uses of this hook and 3 internal uses in https://www.grep.app/search?q=on_before_accelerator_backend_setup 
Users can implement the `setup` hook instead.

### Additional context

This hook was originally added in #5377
Part of #7740

cc @justusschock @awaelchli @akihironitta @rohitgr7 @tchaton @carmocca @borda @ninginthecloud @daniellepintz

**Comment by ananthsub** [comment]
+1 - this hook is also confusing following the strategy refactor, since the Accelerator no longer directly controls the backend setup

**Comment by tchaton** [comment]
This hook was introduced to enable freezing model weights prior to creating the optimizers.

Now that accelerator has been refactored, I believe setup would be a better replacement and we could depreciate this and move the base fine-tuning callback to rely on setup.

**Comment by krishnakalyan3** [comment]
I would like to work on this!.

**Comment by krishnakalyan3** [comment]
@daniellepintz can you please point me to examples/steps on how to achieve this?.

**Comment by carmocca** [comment]
I agree with deprecating this, the hook is really specific. Using it doesn't paint a good picture design-wise so I think it'll be good to clean up, now that it's not necessary.

**Comment by daniellepintz** [comment]
Thanks @krishnakalyan3! Please see https://github.com/PyTorchLightning/pytorch-lightning/pull/10940 as an example. Lmk if you have any questions!

**Comment by awaelchli** [comment]
Strictly speaking, setup() is not a direct replacement/alternative for this deprecated hook. 
the sequence of hook calls is this:

```
        self._data_connector.prepare_data()
        self._call_callback_hooks("on_before_accelerator_backend_setup")
        self.strategy.setup_environment()
        self._call_setup_hook()
```
**Just saying.**
But nobody uses this hook specifically to run right before setup_environment.
