### ISSUE TITLE
[RFC] Deprecate `on_configure_sharded_model` callback hook

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#11560]
## Proposed refactor

Deprecate `on_configure_sharded_model` callback/LM hooks in v1.6 for removal in v1.8
https://github.com/PyTorchLightning/pytorch-lightning/blob/5ad5ba54c0c477546d21daf75ac7b4748d7963a7/pytorch_lightning/callbacks/base.py#L60-L61

### Motivation

I see no uses of this hook either externally or internally: https://www.grep.app/search?q=on_configure_sharded_model

### Additional context

This hook was originally added in #6679

cc @justusschock @awaelchli @akihironitta @rohitgr7 @tchaton @carmocca @borda @ninginthecloud @daniellepintz

**Comment by tchaton** [comment]
@SeanNaren I believe it has never been properly advertised. I think it would be fair to remove it as I don't really find a real use case for it.

**Comment by SeanNaren** [comment]
Sounds good! Should we also remove the additional code tied to it (exposing the context manager for larger models in deepspeed/FSDP etc?)

**Comment by carmocca** [comment]
I agree with removal, the hook is really specific. Using it doesn't paint a good picture design-wise so I think it'll be good to clean up, now that it's not necessary.

**Comment by daniellepintz** [comment]
> Should we also remove the additional code tied to it (exposing the context manager for larger models in deepspeed/FSDP etc?)

yes sounds good. can you link to the code we can remove so whoever does this issue remove it as well?

For anyone picking up this issue, you can also follow https://github.com/PyTorchLightning/pytorch-lightning/pull/10940 as an example

**Comment by Piyush-97** [comment]
I will try to do this.

**Comment by awaelchli** [comment]
Yes!

**Comment by Piyush-97** [comment]
I don't know how to write the test for this.

**Comment by rohitgr7** [comment]
hey @Piyush-97 
for the test you need to ensure that the deprecation warning is caught when someone uses this hook.
check [this](https://github.com/PyTorchLightning/pytorch-lightning/pull/11577/files#diff-e56cd65ba16a825908493410d047a0f7a52a9a6bd9b95ffa552ea8f5d18a19d7) for reference.

**Comment by Piyush-97** [comment]
def test_v1_8_0_on_configure_sharded_model(tmpdir):
    class TestCallback(Callback):
        def on_configure_sharded_model(self, trainer, model):
            print("Configuring sharded model")

    model = BoringModel()

    trainer = Trainer(
        callbacks=[TestCallback()],
        max_epochs=1,
        fast_dev_run=True,
        enable_progress_bar=False,
        logger=False,
        default_root_dir=tmpdir,
        strategy='ddp_sharded'
    )
    with pytest.deprecated_call(
        match="The `on_configure_sharded_model` callback hook was deprecated in v1.6 and will be removed in v1.8."
    ):
        trainer.fit(model)

I don't have GPU and I am not sure if this is right.

**Comment by ananthsub** [comment]
@Piyush-97 - you don't have to specify `strategy="ddp_sharded"` for the test. we should warn the user whenever the hook is overridden that it is deprecated. 


```py
def test_v1_8_0_on_configure_sharded_model(tmpdir):
    class TestCallback(Callback):
        def on_configure_sharded_model(self, trainer, model):
            print("Configuring sharded model")

    model = BoringModel()
    trainer = Trainer(
        callbacks=[TestCallback()],
        max_epochs=1,
        fast_dev_run=True,
        enable_progress_bar=False,
        logger=False,
        default_root_dir=tmpdir,
    )
    with pytest.deprecated_call(
        match="The `on_configure_sharded_model` callback hook was deprecated in v1.6 and will be removed in v1.8."
    ):
        trainer.fit(model)`
```

**Comment by Piyush-97** [comment]
I have written a test but it is failing with two more tests.

**Comment by daniellepintz** [comment]
Hi @Piyush-97 those failures are due to a known issue affecting multiple PRs, not just yours: #11633
