### ISSUE TITLE
`build-CUDA (3.7, 1.8)` fails with `ModuleNotFoundError: No module named 'apex'`

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning#11566]
## 🐛 Bug
See title and recent failures of the workflow:
https://github.com/PyTorchLightning/pytorch-lightning/actions/workflows/ci_dockers.yml

Seems like the workflow has been failing for quite a long time...

### Expected behavior
No failure.

### Environment

- PyTorch Lightning Version (e.g., 1.5.0):
- PyTorch Version (e.g., 1.10):
- Python version (e.g., 3.9):
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

cc @carmocca @akihironitta @borda @justusschock @awaelchli @rohitgr7

**Comment by Borda** [comment]
I guess that the `apex` is installed to another site-packages then default one
