### ISSUE TITLE
Progress bar metrics not displaying metrics logged in `on_train_epoch_end` hook

### ISSUE THREAD

**Issue by rohitgr7** [PyTorchLightning/pytorch-lightning#11586]
## 🐛 Bug

See title.

### To Reproduce

```py
import torch
import os
from pytorch_lightning import LightningModule
from pytorch_lightning import Trainer
from torch.utils.data import Dataset, DataLoader


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def training_step(self, batch, batch_idx):
        loss = self.layer(batch).sum()
        self.log('train_loss', loss, prog_bar=True)
        return loss
    
    def on_train_epoch_end(self, *args, **kwargs):
        self.log('prog_train', 7., prog_bar=True)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


class RandomDataset(Dataset):
    def __init__(self, size, num_samples):
        self.len = num_samples
        self.data = torch.randn(num_samples, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
trainer = Trainer(fast_dev_run=7)
model = BoringModel()
trainer.fit(model, train_dataloaders=train_data)
```

Output:
<img width="1573" alt="Screenshot 2022-01-23 at 8 28 05 PM" src="https://user-images.githubusercontent.com/30778939/150684644-8b83ae26-a0c7-4fad-9757-df02f102e1a0.png">

But `trainer.progress_bar_metrics` displays it correctly:
```py
{'train_loss': -5.339050769805908, 'prog_train': 7.0}
```

### Expected behavior

It should display the metrics since we allow logging metrics inside `on_train_epoch_end` hook.

### Reason for the issue:
Since the progress bar is just a callback, we execute its hooks before LM.
https://github.com/PyTorchLightning/pytorch-lightning/blob/623dc974f56505cfdb6a7c62ad75780229e101de/pytorch_lightning/loops/fit_loop.py#L278-L279

This behavior is common across all hook execution.

A similar issue can come up if someone is logging something in the `on_train_epoch_end` LM hook and using callbacks like `ModelCheckpoint` or `EarlyStopping` to monitor it since by that time the log won't be present and it will lead to an error.

### Solution
1. One solution is of course flipping the calls, i.e. call LM then Callback hook. but this might be a breaking change.
2. Disable logging in these hooks (not a good one IMO).
3. Use the `on_epoch_end` hook instead to log metrics in the progress bar, but this again is not a good sol because if someone uses `on_epoch_end` to log something then it's a problem again.
4. Open to discuss :)

### Environment

- PyTorch Lightning Version (e.g., 1.5.0): master
- PyTorch Version (e.g., 1.10): 1.10
- Python version (e.g., 3.9): 3.9
- OS (e.g., Linux): mac
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

Closely related to why https://github.com/PyTorchLightning/pytorch-lightning/issues/5285 got closed.

cc @carmocca @edward-io @ananthsub @rohitgr7 @kamil-kaczmarek @Raalsky @Blaizzy @awaelchli @borda @ninginthecloud @daniellepintz

**Comment by carmocca** [comment]
This is an unavoidable limitation of the Callback hook design.
The only simple solution is to invert the call order but that's a breaking change and then we'd have the opposite problem: "what if the LightningModule relies on something produced in the same hook of a callback"? (albeit this is rarer than the current limitation).

A lasting solution but much more complex would be to adopt a reactive design for these circumstances instead of using callbacks. Not saying we should pursue this at the moment.

For this specific case of the progress bar, this is generally not a problem because it will get updated right after in the next batch. Or, if training will not run anymore, we can make it also get updated in `on_train_end`.

**Comment by rohitgr7** [comment]
> For this specific case of the progress bar, this is generally not a problem because it will get updated right after in the next batch. Or, if training will not run anymore, we can make it also get updated in on_train_end.

the example is just to highlight the underlying problem. For a different kind of callback, it might fail completely. for eg. `ModelCheckpoint`.

> This is an unavoidable limitation of the Callback hook design.
The only simple solution is to invert the call order but that's a breaking change and then we'd have the opposite problem: "what if the LightningModule relies on something produced in the same hook of a callback"? (albeit this is rarer than the current limitation).

yes, inverting the calls might cover up more cases since callbacks are sort of like plug-in/out components so the opposite cases might be less comparatively.

for validation/test we have `on_validaiton_end/on_test_end` hooks where we can ensure that logging is completed and now we can be ensured that all will the logs will be present in this hook but for the training epoch, there isn't any yet.

**Comment by carmocca** [comment]
@rohitgr7 Since there's no actionable solution, I would suggest closing this issue
