### ISSUE TITLE
Inconsistency with loading dataloaders when `limit_batches=0`

### ISSUE THREAD

**Issue by rohitgr7** [PyTorchLightning/pytorch-lightning#11587]
## Proposed refactor

Whenever we set `limit_batches=0`, for training we don't even load the dataloader but for validation/testing/prediction we do but set `num_batches=0` and don't even iterate it.

<details><summary>CODE</summary>
<p>

```py
import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningDataModule, LightningModule


class RandomDataset(Dataset):
    def __init__(self, size: int, length: int):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def loss(self, batch, prediction):
        return torch.nn.functional.mse_loss(prediction, torch.ones_like(prediction))

    def training_step(self, batch, batch_idx):
        output = self(batch)
        loss = self.loss(batch, output)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        output = self(batch)
        loss = self.loss(batch, output)

    def test_step(self, batch, batch_idx):
        output = self(batch)
        loss = self.loss(batch, output)

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
        return optimizer

    def train_dataloader(self):
        return DataLoader(RandomDataset(32, 64))

    def val_dataloader(self):
        return DataLoader(RandomDataset(32, 64))

    def test_dataloader(self):
        return DataLoader(RandomDataset(32, 64))

    def predict_dataloader(self):
        return DataLoader(RandomDataset(32, 64))


model = BoringModel()
```
</p>
</details>

Case 1: no training/validation with `.fit`
```py
trainer = Trainer(max_epochs=1, limit_train_batches=0, limit_val_batches=0)
trainer.fit(model)
print(trainer.train_dataloader, trainer.num_training_batches, trainer.val_dataloaders, trainer.num_val_batches)
```
Output:
```console
None inf None []
```
Expected:
```console
None inf None []
```

Case 2: training with no validation with `.fit`
```py
trainer = Trainer(max_epochs=1, limit_train_batches=1, limit_val_batches=0)
trainer.fit(model)
print(trainer.train_dataloader, trainer.num_training_batches, trainer.val_dataloaders, trainer.num_val_batches)
```
Output:
```console
<pytorch_lightning.trainer.supporters.CombinedLoader object at 0x7fc208ec16a0> 1 [<torch.utils.data.dataloader.DataLoader object at 0x7fc1e8c298e0>] [0]
```
Expected
```console
<pytorch_lightning.trainer.supporters.CombinedLoader object at 0x7fc208ec16a0> 1 [] []
```

Case 3: no validation with validate (same applies for test/predict)
```py
trainer = Trainer(max_epochs=1, limit_val_batches=0)
trainer.validate(model)
print(trainer.val_dataloaders, trainer.num_val_batches)
```
Output:
```console
[<torch.utils.data.dataloader.DataLoader object at 0x7fc219b04040>] [0]
```
Expected:
```console
None []
```

### Motivation

This is a little inconsistent.

### Pitch

Don't load the dataloaders if limit is 0.

### Additional context

Is there any reason why it's done like that? Loading datalaoders and setting num_batches = 0 instead of not loading the dataloaders at all? any use-case?

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @justusschock @awaelchli @akihironitta @rohitgr7 @ninginthecloud

**Comment by carmocca** [comment]
I think this was like this for legacy reasons. The less work we do the better. CI will tell if anything relied on this behavior.

**Comment by rohitgr7** [comment]
I updated all the tests. Most of them were just checking the `num_eval_batches` contains 0s.
Apart from these only, 1 more test was there related to loops, but that too was irrelevant with no related assertions.
