### ISSUE TITLE
[Feature] Loosen `pydeprecate` version pin

### ISSUE THREAD

**Issue by alanhdu** [PyTorchLightning/pytorch-lightning#11600]
This is a minor nit, but right now PyTorch Lightning seems to pin a very specific version of [`pyDeprecate==0.3.1`](https://github.com/PyTorchLightning/pytorch-lightning/blob/fe34bf2a653ebd50e6a3a00be829e3611f820c3c/requirements.txt#L10). This is causing some dependency mismatches on our-end, since we have a separate dependency in our environment that relies on `pyDeprecate==0.3.2`.

Would there be some way of other updating the version pin, or (ideally) loosening it to support a couple different versions?

cc @borda

**Comment by Borda** [comment]
I think we are fine to use `pyDeprecate>=0.3.1, <0.4.0` mind sending a PR? :]
