### ISSUE TITLE
CSV Logger on_step logging bug

### ISSUE THREAD

**Issue by rasbt** [PyTorchLightning/pytorch-lightning#11605]
## 🐛 Bug

I am currently trying to make sense of the logging behavior and think there is a bug with the `on_step` logging in the `CSVLogger`. 

1. It seems it is skipping steps
2. Also, the steps order seems to be wrong.

### To Reproduce

I uploaded an example here: https://github.com/rasbt/bugreport/blob/master/pytorch-lightning/csvlogger-stepsbug/01.ipynb

There should be approx. 11 steps per epoch (718 training examples and batch size 64).
In `training_step`, I set

```python
self.log("train_loss", loss, on_step=True)
```

And in addition, I also set

```python
logger = CSVLogger(..., flush_logs_every_n_steps=1)
```

But still it is not logging every step for some reason. E.g., in the CSV file I see that it logs step 0 and 1 but then skips everything up to step 11. Then it logs steps 2 and 3 (which I find weird) and then step 23. I may be misunderstanding how steps are counted, or is my code missing something?

<img width="630" alt="Screen Shot 2022-01-24 at 10 08 52 PM" src="https://user-images.githubusercontent.com/5618407/150869308-2b73ceb2-e25a-49b6-acec-9d3316c5e652.png">

### Expected behavior

Instead of steps 0, 1, 11, the steps should be 0, 1, 2, 3, 4, 5 ... 11. 

Also, instead of steps 11, 2, 3, ... it should be 11, 12, 13

### Environment

```bash
* CUDA:
	- GPU:
	- available:         False
	- version:           None
* Packages:
	- numpy:             1.22.1
	- pyTorch_debug:     False
	- pyTorch_version:   1.10.1
	- pytorch-lightning: 1.5.9
	- tqdm:              4.62.3
* System:
	- OS:                Darwin
	- architecture:
		- 64bit
		- 
	- processor:         arm
	- python:            3.8.12
	- version:           Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101
```

**Comment by rohitgr7** [comment]
hey @rasbt! how is it going?

all the logs are logged based on global_step (overall optimization step) by default for training.

if you need to log in at every step, you can configure `Trainer(log_every_n_steps=1)`
https://pytorch-lightning.readthedocs.io/en/latest/extensions/logging.html#id2
by default, it is 50, as you can see `train_loss` being logged at 49, ...

a warning is also emitted in the notebook
```console
/Users/sebastian/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:432: UserWarning: The number of training samples (12) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
```

the reason for 0, 11, 23 with `valid_loss_epoch` and `valid_mae` is: train dataset has 718 samples with batch_size=32, so total batches = 12 (drop_last=False by default), and once this is reached, epoch level metrics are logged.

the reason for 0-1, 2-3, 4-5 with `valid_loss_step` is that it's being logged with total batches = 2 (validation dataset), so they are just logged at every validation step.

trust me CSVLogger isn't the best one to work with :smile: to interpret logs.

**Comment by rasbt** [comment]
Awesome, thanks so much, Rohit! Didn't know about the `log_every_n_steps` param and this makes so much more sense now. 

Also, the weird numbering order (11 to 2, 3) makes sense now, because like you said, one is counting the relative logging step (2, 3) where the other one is the absolute step number 11).

Now, I only have a tiny question, why are those not on the same line (haha, I bet there is also a good reason, i.e., `_epoch_end` for train and valid steps just have separate lines intentionally?)
<img width="561" alt="Screen Shot 2022-01-25 at 8 29 58 AM" src="https://user-images.githubusercontent.com/5618407/150931789-2951d515-3a8b-45c6-a841-17fd6aec593a.png">
:

**Comment by rohitgr7** [comment]
> (haha, I bet there is also a good reason, i.e., _epoch_end for train and valid steps just have separate lines intentionally?)

close,
they are logged separately, so csv logger just creates a new entry. but when you use a better logger like wandb, the graphs will be aligned based on the step, and I think you can export the metrics from there directly.

**Comment by rasbt** [comment]
Awesome, thanks! Right now I am using the CSVLogger to create more minimalistic, self-contained examples but I personally also favor WandB :)
