### ISSUE TITLE
load_from_checkpoint, raise "No pretrained weights exists for this model, using random initialization"

### ISSUE THREAD

**Issue by WangLibo1995** [PyTorchLightning/pytorch-lightning#11609]
I use the following code to train a model:

model = MiniFranceSSL()
trainer = pl.Trainer(gpus=1)
trainer.fit(model=model)
trainer.save_checkpoint("pretrain_weights/minifrance.ckpt")

when I load checkpoints for infernece using the following code:

pre_model = MiniFranceSSL.load_from_checkpoint(checkpoint_path="pretrain_weights/minifrance.ckpt")

 The bug happened, "No pretrained weights exists for this model, using random initialization"
I think the code is correct, what's wrong

**Comment by rohitgr7** [comment]
hey @WangLibo1995 !
doesn't seem to be coming from Lightning. Can you share the complete stack trace?

**Comment by WangLibo1995** [comment]
> hey @WangLibo1995 ! doesn't seem to be coming from Lightning. Can you share the complete stack trace?

when I use the following code to inference:

outputs = trainer.predict(model=model, dataloaders=predict_loader, ckpt_path="pretrain_weights/minifrance.ckpt")

It runs ok and can load the checkpoint, so confusing.

**Comment by WangLibo1995** [comment]
![image](https://user-images.githubusercontent.com/38718224/150971964-1c0a54a7-ddba-48b9-bd57-e19455f3bd39.png)

**Comment by WangLibo1995** [comment]
> is the implementation of `MiniFranceSSL` open-sourced?

No, it is designed by myself for competition, it runs ok. 
My environment is Ubuntu 20.04 and pytorch 1.8.0.
Is it need a ckpt path like "home/wlb/pretrained_weights/Minifrance.ckpt"?

**Comment by rohitgr7** [comment]
> No, it is designed by myself for competition, it runs ok.

just trying to check where the log is coming from since it's not from lightning. maybe the implementation is using a  pretrained backbone that is raising this?

**Comment by WangLibo1995** [comment]
> > No, it is designed by myself for competition, it runs ok.
> 
> just trying to check where the log is coming from since it's not from lightning. maybe the implementation is using a pretrained backbone that is raising this?
Yes, I used a pretrained backbone. Many thanks you for your help.
