### ISSUE TITLE
[Feature Request] Simple method to display image batch

### ISSUE THREAD

**Issue by austinmw** [PyTorchLightning/pytorch-lightning#11625]
## 🚀 Feature

basically a show_batch feature.

### Motivation

I'd like to be able to very quickly visualize how batches of data + annotations look to debug my dataloading pipeline before training.  A lot of problems can be quickly solved just by having the capability to see an augmented batch of training data.

### Pitch

I'd like a model or data module objects to have this method.

### Alternatives

Maybe an option in the trainer to show part of a training and val batch before validation sanity check? 
Adding more boilerplate to get tensorboard image logging for classification/detection/segmentation could be another alternative.

cc @borda

**Comment by carmocca** [comment]
I believe this is available in [Flash](https://github.com/PyTorchLightning/lightning-flash).

cc @ethanwharris

**Comment by deepseek-eoghan** [comment]
I use https://marketplace.visualstudio.com/items?itemName=elazarcoh.simply-view-image-for-python-debugging with VS code debugger and breakpoints at the batch assignment stage in the model code to achieve this functionality.

Agree it would be nice to have this included in the code-base.

**Comment by rohitgr7** [comment]
I think lightning doesn't integrate domain-specific extensions, although they can be easily used with available hooks or 3d-party packages or flash if it's there.
