### ISSUE TITLE
CombinedLoader for training data does not work in DDP

### ISSUE THREAD

**Issue by ant0nsc** [PyTorchLightning/pytorch-lightning#11632]
## 🐛 Bug

When using a `CombinedLoader` for the training data in conjunction with DDP, all GPUs get to see the full data.
This is pretty much the same problem as reported previously in #10373, just this time for the training data.

@tchaton FYI

### To Reproduce

https://gist.github.com/ant0nsc/ad44d277eaca209d4e387b8ba7717dcb

### Expected behavior

In the above script, CombinedLoader(..., mode="min_size") should give 6 batches. When split across 2 GPUs, each GPU should see 3 batches. However, we are seeing all 6 batches per GPU. The same problem applies when using "max_size_cycle"

### Environment
* CUDA:
        - GPU:
                - Tesla K80
                - Tesla K80
        - available:         True
        - version:           11.1
* Packages:
        - numpy:             1.19.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.8.0
        - pytorch-lightning: 1.5.5
        - tqdm:              4.62.3
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - 
        - processor:         x86_64
        - python:            3.7.3
        - version:           #58~18.04.1-Ubuntu SMP Wed Jul 28 23:14:18 UTC 2021

cc @tchaton @rohitgr7 @akihironitta

**Comment by tchaton** [comment]
Hey @ant0nsc,

Would you be interesting into submitting a bug fix for this one as you have already the example from the previous fix ?

Best,
T.C

**Comment by rohitgr7** [comment]
hey @ant0nsc !

I think the example might be incorrect.
`train_dataloader` shouldn't return `CombinedLoader`, rather it should return only the dictionary of dataloaders, since the object returned is wrapped around CombinedLoader internally here:

https://github.com/PyTorchLightning/pytorch-lightning/blob/fe34bf2a653ebd50e6a3a00be829e3611f820c3c/pytorch_lightning/trainer/trainer.py#L1759-L1791

the mode should be set inside
```py
Trainer(..., multiple_trainloader_mode='max_size_cycle')`  or 'min_size'
```
can you try that?

**Comment by ant0nsc** [comment]
Hi @rohitgr7 , yes, this works. There are two reasons why I'm not particularly happy with that solution:
* The datamodule in our case is choosing the cycling mode based on the length of the datasets. With the workaround you are suggesting, the cylce mode now needs to be communicated to the trainer. It is, in my view, breaking the separation of concerns.
* It creates an odd asymmetry that validation data can be a `CombinedLoader`, but training data cannot. 

If this asymmetry is by design, please let me know. Otherwise, I'll try to do a PR as suggested by @tchaton

**Comment by rohitgr7** [comment]
thanks for confirming @ant0nsc !

yes! that is a little annoying.

we have a similar request [here](https://github.com/PyTorchLightning/pytorch-lightning/issues/11475) and possibly a better proposal [here](https://github.com/PyTorchLightning/pytorch-lightning/issues/9046) (I haven't looked at this in depth yet).

But at least, if it works in that way, can we say that CombinedLoader works with DDP?
if it does, all we need is to provide more flexibility for users to customize the behavior in case an instance of CombinedLoader is returned.

**Comment by tchaton** [comment]
Hey @ant0nsc,

You are right.

Internally, we would wrap the `train_dataloader` into a CombinedLoader, but I believe we could skip the super-wrapping causing the issue.

Here is the associated line: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/trainer.py#L1791.

Would you be interested into trying to fix this up ? I won't have much bandwidth to do so.
