### ISSUE TITLE
every_n_train_steps + every_n_epochs for ModelCheckpoint

### ISSUE THREAD

**Issue by ZhaofengWu** [PyTorchLightning/pytorch-lightning#11645]
Currently these two options are mutually exclusive -- why? Sometimes it's useful to save checkpoints during training, but also keep the checkpoint at the end of every epoch. Is there currently a way to achieve this?

cc @borda @carmocca @awaelchli @ninginthecloud @jjenniferdai @rohitgr7

**Comment by ananthsub** [comment]
You can configure 2 different checkpointing callbacks to achieve this. The reason to keep them mutually exclusive was that the other metadata the checkpoint callback tracks (the monitor metric, topK, models, checkpoint name) might be different across training & validation

**Comment by ZhaofengWu** [comment]
Ah, got it. Thanks for the quick help!
