### ISSUE TITLE
Setuptools pinned to version 59.5.0

### ISSUE THREAD

**Issue by jzazo** [PyTorchLightning/pytorch-lightning#11660]
## 🐛 Bug

I am installing pytorch lightning in an environment using poetry, and setuptools is pinned to version 59.5.0.  Why and where is it pinned and can it be unpinned? This is giving me package conflict versions.

A pin is present in [lightning-flash](https://github.com/PyTorchLightning/lightning-flash/blob/54d641db382cd4f65839bb6ebcbf05abc10f509d/requirements.txt), but I could not find it in this repo.

There might be a connection with this [bug](https://github.com/pytorch/pytorch/pull/69904), but after installing torch from master I still see setuptools pinned to version 59.5.0. And the dependency tree lists that lightning pins the package.

This is the list of direct dependencies that I get from pytorch-lightning:
```
├── pytorch-lightning *
│   ├── fsspec >=2021.05.0,<2021.06.0 || >2021.06.0 
│   │   ├── aiohttp * 
│   │   │   ├── aiosignal >=1.1.2 
│   │   │   │   └── frozenlist >=1.1.0 
│   │   │   ├── async-timeout >=4.0.0a3,<5.0 
│   │   │   ├── attrs >=17.3.0 
│   │   │   ├── charset-normalizer >=2.0,<3.0 
│   │   │   ├── frozenlist >=1.1.1 (circular dependency aborted here)
│   │   │   ├── multidict >=4.5,<7.0 
│   │   │   └── yarl >=1.0,<2.0 
│   │   │       ├── idna >=2.0 
│   │   │       └── multidict >=4.0 (circular dependency aborted here)
│   │   └── requests * 
│   │       ├── certifi >=2017.4.17 
│   │       ├── charset-normalizer >=2.0.0,<2.1.0 (circular dependency aborted here)
│   │       ├── idna >=2.5,<4 (circular dependency aborted here)
│   │       ├── pysocks >=1.5.6,<1.5.7 || >1.5.7 
│   │       └── urllib3 >=1.21.1,<1.27 
│   ├── future >=0.17.1 
│   ├── numpy >=1.17.2 
│   ├── packaging >=17.0 
│   │   └── pyparsing >=2.0.2,<3.0.5 || >3.0.5 
│   ├── pydeprecate 0.3.1 
│   ├── pyyaml >=5.1 
│   ├── setuptools 59.5.0 
│   ├── tensorboard >=2.2.0 
│   │   ├── absl-py >=0.4 
│   │   │   └── six * 
│   │   ├── google-auth >=1.6.3,<3 
│   │   │   ├── cachetools >=2.0.0,<6.0 
│   │   │   ├── pyasn1-modules >=0.2.1 
│   │   │   │   └── pyasn1 >=0.4.6,<0.5.0 
│   │   │   ├── rsa >=3.1.4,<5 
│   │   │   │   └── pyasn1 >=0.1.3 (circular dependency aborted here)
│   │   │   └── six >=1.9.0 (circular dependency aborted here)
│   │   ├── google-auth-oauthlib >=0.4.1,<0.5 
│   │   │   ├── google-auth >=1.0.0 (circular dependency aborted here)
│   │   │   └── requests-oauthlib >=0.7.0 
│   │   │       ├── oauthlib >=3.0.0 
│   │   │       └── requests >=2.0.0 (circular dependency aborted here)
│   │   ├── grpcio >=1.24.3 
│   │   │   └── six >=1.5.2 (circular dependency aborted here)
│   │   ├── markdown >=2.6.8 
│   │   │   └── importlib-metadata >=4.4 
│   │   │       └── zipp >=0.5 
│   │   ├── numpy >=1.12.0 (circular dependency aborted here)
│   │   ├── protobuf >=3.6.0 
│   │   ├── requests >=2.21.0,<3 (circular dependency aborted here)
│   │   ├── setuptools >=41.0.0 (circular dependency aborted here)
│   │   ├── tensorboard-data-server >=0.6.0,<0.7.0 
│   │   ├── tensorboard-plugin-wit >=1.6.0 
│   │   ├── werkzeug >=0.11.15 
│   │   └── wheel >=0.26 
│   ├── torchmetrics >=0.4.1 
│   │   ├── numpy >=1.17.2 (circular dependency aborted here)
│   │   ├── packaging * (circular dependency aborted here)
│   │   ├── pydeprecate >=0.3.0,<0.4.0 (circular dependency aborted here)
│   │   └── torch >=1.3.1 
│   │       └── typing-extensions * 
│   ├── tqdm >=4.41.0 
│   │   └── colorama * 
│   └── typing-extensions * (circular dependency aborted here)
```

### Expected behavior

Setuptools is not pinned to any version.

### Environment

- PyTorch Lightning Version: 1.5.9
- PyTorch Version (e.g., 1.10): 1.10.2 and master on Jan 28, 2022
- Python version (e.g., 3.9): 3.8.10
- OS (e.g., Linux): Ubuntu 20.04

cc @carmocca @akihironitta @borda

**Comment by akihironitta** [comment]
I don't think it's pinned from our side. @Borda Is it?

**Comment by jzazo** [comment]
Is there any dependency of pytorch-lightning to ligthning-flash or from lite, etc.? Because lightning-flash is clearly pinned to that exact version.

**Comment by jzazo** [comment]
I tried to reproduce this error in an empty environment:
```
$ poetry init
$ poetry add pytorch-lightning
$ poetry add pipdeptree
$ pipdeptree -p setuptools
```
And this is the result:
```
$ pipdeptree -p setuptools
Warning!!! Possibly conflicting dependencies found:
* pytorch-lightning==1.5.9
 - setuptools [required: ==59.5.0, installed: 60.2.0]
------------------------------------------------------------------------
setuptools==60.2.0
```
It seems that pytorch lightning is pinning setuptools to version 59.5.0.

I did the same procedure in an environment only with torch:
```
$ poetry init
$ poetry add torch
$ poetry add pipdeptree
$ pipdeptree -p setuptools
setuptools==60.2.0
```
without any warning.

This is a very easy to reproduce setup. What is pinning setuptools?

**Comment by carmocca** [comment]
I am able to reproduce this in Colab. Any idea @Borda?

**Comment by jzazo** [comment]
Ok, found the issue. Searching `requirements.txt` in the tagged version 1.5.9 lists `setuptools==59.5.0 # required for https://github.com/pytorch/pytorch/pull/69904`.

In master this pin does not exist and the search functionality of github only works over master, that's why I couldn't find it.

Thanks.
