### ISSUE TITLE
No such file or directory: '../_notebooks/.actions/requirements.txt'

### ISSUE THREAD

**Issue by bhadreshpsavani** [PyTorchLightning/pytorch-lightning#11673]
## 🐛 Bug

While running docs.txt from the requirements folder I am getting the below error
```
No such file or directory: '../_notebooks/.actions/requirements.txt'
```
Please let me know if i am missing anything or it seems valid issue

**Comment by ananthsub** [comment]
Did you run `git submodule update --init --recursive` ? https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md#documentation

**Comment by bhadreshpsavani** [comment]
Nope!
I need to run it I think!
