### ISSUE TITLE
DeepSpeed model checkpoint saves all the checkpoints even when ModelCheckpoint.save_top_k=1

### ISSUE THREAD

**Issue by tridao** [PyTorchLightning/pytorch-lightning#11687]
## 🐛 Bug

When using DeepSpeed with ModelCheckpoint, even when I set save_top_k to 1, the checkpoint directory named `last.ckpt` contains all the checkpoints, instead of just the top 1. This causes the checkpoints to take way more disk space.

This behavior is due to the [DeepSpeed strategy](https://github.com/PyTorchLightning/pytorch-lightning/blob/86b177ebe5427725b35fde1a8808a7b59b8a277a/pytorch_lightning/strategies/deepspeed.py#L749) saving each checkpoint in `last.ckpt` with a distinct the tag containing `global_step` (default for DeepSpeed). These are never deleted.
For example, if I save a checkpoint every 1000 steps and train for 400k steps, the directory `last.ckpt` will contain: `global_step_999`, `global_step_1999`, ..., `global_step_399999`, which takes way too much disk space.

### Expected behavior

When saving checkpoints with DeepSpeed, `last.ckpt` should only contain the last global step instead of all the global steps if save_last_k is set to 1.

### Environment

- PyTorch Lightning Version (e.g., 1.5.0): 1.5.9
- PyTorch Version (e.g., 1.10): 1.10.1
- Python version (e.g., 3.9): 3.8
- OS (e.g., Linux): Ubuntu 20.04
- Any other relevant information: deepspeed 0.5.10

cc @awaelchli @ananthsub @ninginthecloud @rohitgr7 @SeanNaren @carmocca @jjenniferdai

### [Edit] To reproduce:
```
import os

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer
from pytorch_lightning.callbacks import ModelCheckpoint


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    test_data = DataLoader(RandomDataset(32, 64), batch_size=2)

    model = BoringModel()
    trainer = Trainer(
        strategy='deepspeed_stage_1',
        accelerator='gpu',
        devices=1,
        callbacks=[ModelCheckpoint(save_top_k=1, save_last=True)],
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        limit_test_batches=1,
        num_sanity_val_steps=0,
        max_epochs=10,
        enable_model_summary=False,
    )
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
    trainer.test(model, dataloaders=test_data)


if __name__ == "__main__":
    run()


# last.ckpt contains ALL the checkpoints even though we limit the number of checkpoints to 1.
# This can take up way too much disk space.

# ls lightning_logs/version_0/checkpoints/last.ckpt
# global_step1  global_step2  global_step3  global_step4  global_step5  global_step6  global_step7  global_step8  global_step9  global_step10  latest  zero_to_fp32.py
```

**Comment by rohitgr7** [comment]
hey @tridao 

mind share a reproducible script to reproduce this behavior using [BoringModel](https://colab.research.google.com/github/PyTorchLightning/pytorch-lightning/blob/example/bug_report/pl_examples/bug_report/bug_report_model.ipynb)? It might not work on colab, but you can prepare one locally and upload it there or share the notebook directly.

ideally, all the checkpoints along with file paths are managed by ModelCheckpoint so old ones should be deleted once they are not required based on the configuration. `DeepspeedStrategy.save_checkpoint` call is managed by ModelCheckpoint indirectly.

**Comment by tridao** [comment]
I've updated the bug report above to include the code to reproduce the issue.
Thanks for your help!
