### ISSUE TITLE
Centralize DDP optimizations in docs

### ISSUE THREAD

**Issue by ananthsub** [PyTorchLightning/pytorch-lightning#11698]
## 📚 Documentation

DDP optimizations for `find_unused_parameters` and tuning NCCL parameters are listed here: https://pytorch-lightning.readthedocs.io/en/latest/guides/speed.html#when-using-ddp-plugins-set-find-unused-parameters-false

However, there's another section on the doc which explicitly talks about DDP optimizations here: https://pytorch-lightning.readthedocs.io/en/latest/advanced/advanced_gpu.html#ddp-optimizations

The pieces from the speed guide should be moved to the DDP optimizations section, and then the speed guide can simply refer to the advanced GPU training section for pointers. This way users have one consistent way to get specifics on how to tune DDP settings for speedups.

And the speedup doc can be a higher-level index of what users can do to explore faster training across dataloading/accelerators/strategies and general guidance for writing efficient pytorch programs

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @rohitgr7 @justusschock @kaushikb11 @awaelchli @akihironitta

**Comment by shabie** [comment]
I'd like to do it if it is up for grabs.

**Comment by ananthsub** [comment]
> I'd like to do it if it is up for grabs.

awesome, I've assigned the issue to you @shabie

**Comment by shabie** [comment]
OK so I've spent enough time reading about DDP in detail and will get working on the docs from tomorrow. I know that I am suppoosed to move them around but does it also make sense to suggest some improvements in the text itself in the same PR?

**Comment by ananthsub** [comment]
@shabie sure, let's discuss on the PR
