### ISSUE TITLE
Using the step argument raises an error for WandbLogger's log_image

### ISSUE THREAD

**Issue by NathanGodey** [PyTorchLightning/pytorch-lightning#11703]
## 🐛 Bug

When using the WandbLogger log_image method, adding the step argument raises an error:
```
  File "/home/nathan/work/these/engine/venv/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py", line 417, in log_image
    if len(v) != n:
TypeError: object of type 'int' has no len()
```

### To Reproduce
```

from pytorch_lightning.loggers import WandbLogger
import torch
logger=WandbLogger()
fake_img = torch.randn((50,50))
logger.log_image(key='fake', images=[fake_img], step=0)
```

### Expected behavior

The image is logged with appropriate step in Wandb.

### Environment

- PyTorch Lightning Version (e.g., 1.5.0): stable

### Additional context

Can be easily fixed by swapping a few lines in the method.

cc @awaelchli @morganmcg1 @AyushExel @borisdayma @scottire @manangoel99

**Comment by rohitgr7** [comment]
hey @NathanGodey 

good catch! mind send a PR?
