### ISSUE TITLE
Distributed Pytorch-Lightning is not working with Dask workers/cluster

### ISSUE THREAD

**Issue by jcfaracco** [PyTorchLightning/pytorch-lightning#11729]
## 🐛 Bug

I'm using a [Dask](https://dask.org/) environment (with GPU and without GPU. I tested using both) to run a multi node training.
It can be done using two different ways: programing your own methods to distribute the code or using `dask_pytorch_ddp` module.
The last one can reduce the number of lines and the need of setup your own Cluster Environment.
To avoid a huge code, I'm gonna use the `dask_pytorch_ddp` example, but both returns the same error.

### To Reproduce

```python
import os
import torch
from torch import nn
import torch.nn.functional as F
from torchvision.datasets import MNIST
from torch.utils.data import DataLoader, random_split
from torchvision import transforms

from typing import List, Dict

import pytorch_lightning as pl
from pytorch_lightning.plugins.environments import ClusterEnvironment

from distributed import Client
from distributed.client import wait, FIRST_COMPLETED
from distributed.utils import TimeoutError as DistributedTimeoutError
import torch.distributed as dist


class LitAutoEncoder(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.encoder = nn.Sequential(nn.Linear(28 * 28, 128), nn.ReLU(), nn.Linear(128, 3))
        self.decoder = nn.Sequential(nn.Linear(3, 128), nn.ReLU(), nn.Linear(128, 28 * 28))

    def forward(self, x):
        # in lightning, forward defines the prediction/inference actions
        embedding = self.encoder(x)
        return embedding

    def training_step(self, batch, batch_idx):
        # training_step defines the train loop. It is independent of forward
        x, y = batch
        x = x.view(x.size(0), -1)
        z = self.encoder(x)
        x_hat = self.decoder(z)
        loss = F.mse_loss(x_hat, x)
        self.log("train_loss", loss)
        return loss

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
        return optimizer


def _get_worker_info(client: Client) -> List[Dict]:
    """
    returns a list of workers (sorted), and the DNS name for the master host
    The master is the 0th worker's host
    """
    workers = client.scheduler_info()["workers"]
    worker_keys = sorted(workers.keys())
    workers_by_host: Dict[str, List[str]] = {}
    for key in worker_keys:
        worker = workers[key]
        host = worker["host"]
        workers_by_host.setdefault(host, []).append(key)
    host = workers[worker_keys[0]]["host"]
    all_workers = []
    global_rank = 0
    hosts = sorted(workers_by_host.keys())
    for host in hosts:
        local_rank = 0
        for worker in workers_by_host[host]:
            all_workers.append(
                dict(
                    master=hosts[0],
                    worker=worker,
                    local_rank=0,
                    global_rank=global_rank,
                    host=host,
                    world_size=len(workers_by_host[host]),
                )
            )
            local_rank += 1
            global_rank += 1
    return all_workers


dataset = MNIST(os.getcwd(), download=True, transform=transforms.ToTensor())
train, val = random_split(dataset, [55000, 5000])

client = Client("<dask-scheduler-host:8786")

autoencoder = LitAutoEncoder()

all_workers = _get_worker_info(client)

def train_test(metadata, model, train, val=None, test=None):
    class MyClusterEnvironment(ClusterEnvironment):
        def __init__(self, metadata) -> None:
            super().__init__()
            self.metadata = metadata
            self._master_port = 23456

        @staticmethod
        def detect() -> bool:
            if "master" not in self.metadata:
                return False
            if "world_size" not in self.metadata:
                return False
            if "global_rank" not in self.metadata:
                return False

            return True

        @property
        def creates_processes_externally(self) -> bool:
            """Return True if the cluster is managed (you don't launch processes yourself)"""
            return True

        def creates_children(self) -> bool:
            return False

        def world_size(self) -> int:
            return int(self.metadata["world_size"])

        def global_rank(self) -> int:
            return int(self.metadata["global_rank"])

        def local_rank(self) -> int:
            if "local_rank" in self.metadata:
                return int(self.metadata["local_rank"])
            else:
                return 0

        def node_rank(self) -> int:
            return int(self.metadata["global_rank"])

        def master_address(self) -> str:
            return self.metadata["master"]

        def master_port(self) -> int:
            return self._master_port

        def set_world_size(self, size: int) -> None:
            pass

        def set_global_rank(self, rank: int) -> None:
            pass

    trainer = pl.Trainer(max_epochs=1, accelerator="cpu", strategy="ddp", plugins=[MyClusterEnvironment(metadata)])

    trainer.fit(model, DataLoader(train), DataLoader(val))

for worker in all_workers:
    futures = client.submit(train_test, worker, autoencoder, train, val)

while True:
    if not futures:
        break

    try:
        result = wait(futures, 0.1, FIRST_COMPLETED)
    except DistributedTimeoutError:
        continue

    for fut in result.done:
        try:
            fut.result()
        except Exception as e:  # pylint: disable=broad-except
            print(str(e))
            raise
    futures = result.not_done
```

Notice this model uses CPU and `gloo` backend with 1 *epoch*.

Once the processes are started, the workers show the proper message saying (i.e.):

    initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/8

But right after, it shows:

    Invalid rank 1, rank should be in the interval [0, 0]')

And then, everything freezes.
I would bet that `DistributedSampler` is not using the default `world_size` to batch the samplers, but it is only some hypotheses.

### Expected behavior

The training should be balanced across the workers.

### Environment

- PyTorch Lightning Version: 1.5.9
- PyTorch Version:  1.10.1
- Python version: 3.8.12
- Dask_pytorch_ddp: 0.2.2
- Dask: 21.12.0
- Distributed: 2021.11.1
- OS: Ubuntu 20.04.3 LTS
- CUDA/cuDNN version: 11.2
- GPU models and configuration: GTX1080 mainly
- How you installed PyTorch (`conda`, `pip`, source): pip3.

### Additional context

No additional comments.

cc @justusschock @kaushikb11 @awaelchli @akihironitta @rohitgr7

**Comment by awaelchli** [comment]
Hello

I have an idea what could be the problem:
In the trainer, you need to set the number of devices and number of nodes to the same value as the environment, i.e., if you launch dask processes with 2 nodes with 4 devices each, the trainer needs to set `Trainer(devices=4, num_nodes=2, ...)`.

Could you try this? Thanks <3

**Comment by jcfaracco** [comment]
Thanks @awaelchli 

It seems to work. Now I see the `GLOBAL_RANK` and `MEMBERS` set properly in each node.
The data is also balanced between workers (I'm using 2 workers with one GPU each to test `Trainer(devices=1, num_nodes=2, accelerator="gpu", strategy="ddp", ...)`). 
There is only one issue that I'm still seeing. The output of one work shows only:

```
initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
[W reducer.cpp:1303] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
```

**Comment by jcfaracco** [comment]
Apparently, it is working. It is suppressing the training output on other works. If I force with a simple `print()`, it seems to work fine. Unless someone has any objection or any extra suggestion, I guess we can close this bug report.

**Comment by rohitgr7** [comment]
possibly because the progress bar is shown only on rank 0 but total batches here will be correct due to distributed sampling. If we show it for all ranks, will be become uneasy to track.

**Comment by awaelchli** [comment]
Yes exactly, as @rohitgr7 said we don't let each process print a progress bar to avoid an unpleasant experience when the terminal gets spammed with outputs. However, we could potentially restrict this to `local_rank==0` instead of `global_rank==0`, then at least for multi-node training you will see the bar in each terminal of a different node. This could be a slight improvement we want to consider. 

Fyi, you are not the first to run into this misconfiguration problem and we have ideas to give better feedback to the user and choose better default behavior. See for example #10150, #10107

**Comment by jcfaracco** [comment]
Thanks, guys. I assume this is closed. I appreciate your feedback and support 😃

**Comment by YUHUINI1995** [comment]
@jcfaracco I am learning Dask recently. I wonder if you are able to make it work for multiple node multiple gpus?  
Is it possible to run `Trainer(devices=2, num_nodes=2)` for example, each node has two gpus?
