### ISSUE TITLE
Adding log_params function to MLFlowLogger class

### ISSUE THREAD

**Issue by xamm** [PyTorchLightning/pytorch-lightning#11736]
## 🚀 Feature

*mlflow* provides a `log_params()` function ([link to docs](https://www.mlflow.org/docs/latest/python_api/mlflow.html#mlflow.log_params)).
This provides the ability to pass a `dictionary` of parameters and log them all at once.
At the moment the `MLFlowLogger` does not offer this function.

The added function should simply take a dictionary as input and log all parameters contained in the dictionary to the same run.

Basically, this workaround could be turned into a function of the class `MLFlowLogger`.
```
def log_params(ml_logger, param):
    for key, value in param.items():
        ml_logger.experiment.log_param(ml_logger.run_id, key, value)
```

### Motivation

I think it would be good to have this function also in `MLFlowLogger` to match the available functions of *mlflow*, and because it makes logging a lot of parameters more convenient.

### Pitch

I would like to see the above workaround implemented as a function in the `MLFlowLogger` class.

### Alternatives

As a workaround, the parameters can be logged separately at this time.

cc @borda

**Comment by xamm** [comment]
If there is interest in this new feature I would be happy to implement this.

**Comment by rohitgr7** [comment]
hey @xamm !

I think log_hyperparams does the same:
https://github.com/PyTorchLightning/pytorch-lightning/blob/32e7d32956e1685d36f2ab0ca3770baa2f76ce10/pytorch_lightning/loggers/mlflow.py#L195

**Comment by xamm** [comment]
Yes, thank you! 

I was looking for `log_params` because the method for logging individual parameters is called `log_param`, so I completely overlooked this function.

**Comment by happen2me** [comment]
I think the l`og_hyperparameters` should be renamed to conform with the original function name `log_params` in MLFlow. This will cause less confusion.
