### ISSUE TITLE
Bug report: This line causes error when using MADGRAD optimizer & resume training

### ISSUE THREAD

**Issue by circlecrystal** [PyTorchLightning/pytorch-lightning#11741]
https://github.com/PyTorchLightning/pytorch-lightning/blob/8c07d8bf905e395bbd2142b5df7b185b8e936c41/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L284

The reported error is:
`  File "/home/tiger/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 283, in restore_optimizers
    for k, v in state.items():
AttributeError: 'Tensor' object has no attribute 'items'`

For MADGRAD, optimizer.state["k"] is tensor-type instead of mapping type. Therefore, we need to fix this problem for making Pytorch Lightning compatible with such kind of optimizers.

The correct way of fixing this issue is changing it to:
![Screen Shot 2022-02-05 at 4 57 59 AM](https://user-images.githubusercontent.com/5665980/152602560-90f2dc23-6d6c-4f83-965c-1904ed49ef06.jpg)

cc @awaelchli @ananthsub @ninginthecloud @rohitgr7

**Comment by awaelchli** [comment]
Hello @circlecrystal 
Thanks for bringing this up.
I don't see anything immediately wrong with your suggestion. Since you found the fix already, would you be interested in sending a fix in a PR? We would then need to extend one of our tests to check against this type of optimizer. 

cheers

**Comment by circlecrystal** [comment]
> Hello @circlecrystal Thanks for bringing this up. I don't see anything immediately wrong with your suggestion. Since you found the fix already, would you be interested in sending a fix in a PR? We would then need to extend one of our tests to check against this type of optimizer.
> 
> cheers

I have finally finished a PR for fixing this bug. Please take a look at here:
https://github.com/PyTorchLightning/pytorch-lightning/pull/11757

**Comment by awaelchli** [comment]
Re-opening. We would need to add a test to complete the bugfix.
