### ISSUE TITLE
`apply_to_collections` fails on dataclass inputs

### ISSUE THREAD

**Issue by TidalPaladin** [PyTorchLightning/pytorch-lightning#11759]
## 🐛 Bug

If `apply_to_collections` is called on two dataclasses, the passed `function` will be called on only one of the input dataclasses. 

Dataclass inputs for `apply_to_collection` are handled by a conditional:

https://github.com/PyTorchLightning/pytorch-lightning/blob/8ddf9f996d4a98e7be5fc591b7734b6f78313771/pytorch_lightning/utilities/apply_func.py#L128

`apply_to_collections` does not appear to have such a conditional.

### To Reproduce
Code

```python
import torch
from torch import Tensor
from dataclasses import dataclass
from pytorch_lightning.utilities.apply_func import apply_to_collections

@dataclass
class Dataclass:
    x: Tensor = torch.rand(10)

dc1 = Dataclass()
dc2 = Dataclass()
apply_to_collections(dc1, dc2, Tensor, torch.allclose)
```

Fails with

```
Traceback (most recent call last):
  File "/home/tidal/Documents/dl-template/combustion/dc.py", line 18, in <module>
    apply_to_collections(dc1, dc2, Tensor, torch.allclose)
  File "/home/tidal/Documents/dl-template/combustion/venv/lib/python3.9/site-packages/pytorch_lightning/utilities/apply_func.py", line 215, in apply_to_collections
    return apply_to_collection(data1, dtype, function, *args, wrong_dtype=wrong_dtype, **kwargs)
  File "/home/tidal/Documents/dl-template/combustion/venv/lib/python3.9/site-packages/pytorch_lightning/utilities/apply_func.py", line 138, in apply_to_collection
    v = apply_to_collection(
  File "/home/tidal/Documents/dl-template/combustion/venv/lib/python3.9/site-packages/pytorch_lightning/utilities/apply_func.py", line 95, in apply_to_collection
    return function(data, *args, **kwargs)
TypeError: allclose() missing 1 required positional arguments: "other"
```

### Expected behavior

No exception should be raised, or it should be indicated that `apply_to_collections` does not support dataclasses.

### Environment

```
* CUDA:
        - GPU:
                - NVIDIA GeForce RTX 3090
                - NVIDIA GeForce RTX 3090
        - available:         True
        - version:           11.3
* Packages:
        - numpy:             1.22.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.10.2+cu113
        - pytorch-lightning: 1.5.9
        - tqdm:              4.62.3
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:
        - python:            3.9.9
        - version:           #1 SMP PREEMPT Thu, 27 Jan 2022 18:27:00 +0000
```

cc @borda

**Comment by awaelchli** [comment]
Hello

Yes this is happening because `apply_to_collections` does not support dataclasses. However, we recently added support for dataclasses in `apply_to_collection` (singular) and we could investigate how to support that also for the zip version.

**Comment by awaelchli** [comment]
Hello! That would be very much appreciated. Glad you found the blog post and live stream useful. I see you already started. Feel free to leave the docs for last and focus on the problem solving first. For the test, you could easily take @TidalPaladin's code and turn it into a test case. 

> about the docs, I'm a little confused that where exactly should I update?

Directly in the docstring of that function would be the best.
