### ISSUE TITLE
[RFC] Deprecate `weights_save_path` from the Trainer constructor

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#11768]
## Proposed refactor

Deprecate `weights_save_path` from the Trainer constructor:
https://github.com/PyTorchLightning/pytorch-lightning/blob/9d8faecdb2b873b52b95f2772f4bf48068a0af9a/pytorch_lightning/trainer/trainer.py#L175

### Motivation

We currently have multiple ways to set the checkpoint save path in Lightning:
* the`weights_save_path` Trainer argument
* the `dirpath` argument and instance variable of `ModelCheckpoint`
* the generic `default_root_dir` Trainer argument

We have all this complicated logic here to determine how to set the checkpoint save path based on the above variables:
https://github.com/PyTorchLightning/pytorch-lightning/blob/9d8faecdb2b873b52b95f2772f4bf48068a0af9a/pytorch_lightning/callbacks/model_checkpoint.py#L567-L601

Having multiple ways of doing the same thing can create confusion and overly complex code. Also, we don't have any save_path for the profiler in the Trainer constructor, so why should we for checkpointing?

### Additional context

Discussed in https://github.com/PyTorchLightning/pytorch-lightning/discussions/10547

This argument was first added in https://github.com/PyTorchLightning/pytorch-lightning/pull/211

cc @awaelchli @ananthsub @ninginthecloud @rohitgr7 @tchaton @akihironitta @justusschock @kaushikb11 @borda

**Comment by ananthsub** [comment]
This argument is used for automatic fault-tolerance here: https://github.com/PyTorchLightning/pytorch-lightning/blob/0cb64fb8baf954db2de234a69b483209fb19de9a/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L55-L68

What would be used instead? 
What happens if multiple model checkpoints are configured? It doesn't make sense to save multiple checkpoints used for resuming?

**Comment by daniellepintz** [comment]
I see. Can we use `default_root_dir` here?

**Comment by jjenniferdai** [comment]
I like deprecating `weights_save_path` usage in `ModelCheckpoint` - don't see a reason for it when `ModelCheckpoint` has `dirpath`. Some things we lose by deprecating `weights_save_path` Trainer arg:

1. the ability for fault tolerance to specify a path different from `default_root_dir`. potential solutions:

-  trying to check `ModelCheckpoint` `dirpath`s to use. This is messy/won't work well though as mentioned above, e.g. multiple `ModelCheckpoint(dirpath)` callbacks, or no `ModelCheckpoint` callbacks at all.

- keep `weights_save_path` arg, just repurpose and rename it as e.g. `fault_tolerance_path` (remove functionality for `weights_save_path` being used in `ModelCheckpoint`)

2. (sharing `weights_save_path` across multiple `ModelCheckpoint` callbacks. Nbd, I think explicitly giving `dirpath` to each `ModelCheckpoint` is much better)

**Comment by daniellepintz** [comment]
Interesting, yeah it seems like the only viable option is repurposing it as `fault_tolerance_path`

**Comment by daniellepintz** [comment]
any thoughts @tchaton @awaelchli?

**Comment by carmocca** [comment]
I think that fault-tolerance using `weights_save_path` is a bug considering the fault-tolerance is set to save in `default_root_dir`. (the same argument can be done the other way around).

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/trainer.py#L1761

I would not introduce a `Trainer` argument for the ft path as it's still experimental and supposed to be invisible to the users.

This logic will get cleaned up with #11862. The callback added can be extended in the future.

**Comment by daniellepintz** [comment]
Makes sense, thanks. So after https://github.com/PyTorchLightning/pytorch-lightning/pull/11862 lands, do you think we can make the changes initially proposed in this issue?

**Comment by awaelchli** [comment]
That's fine, we can introduce an environment variable for the path for the special fault-tolerance checkpoints and default to the root dir.

**Comment by carmocca** [comment]
> do you think we can make the changes initially proposed in this issue?

I believe so, looking at the PR that introduced this variable: https://github.com/PyTorchLightning/pytorch-lightning/pull/211

The argument was allowing saving customization without `ModelCheckpoint`, however, we are moving away from cluster-specific saving logic.
