### ISSUE TITLE
Multi-GPU Tensor Initialization Question

### ISSUE THREAD

**Issue by MRGLabs** [PyTorchLightning/pytorch-lightning#11775]
### Discussed in https://github.com/PyTorchLightning/pytorch-lightning/discussions/11774

<div type='discussions-op-text'>

<sup>Originally posted by **MRGLabs** February  6, 2022</sup>
The documentation advises the usage of '_type_as_' when initializing new tensors in multi-gpu settings:

> [https://pytorch-lightning.readthedocs.io/en/stable/advanced/multi_gpu.html#init-tensors-using-type-as-and-register-buffer](url)
When you need to create a new tensor, use type_as. This will make your code scale to any arbitrary number of GPUs or TPUs with Lightning.

The example shows a case where a new tensor is initialized inside a LightningModule forward function:

> def forward(self, x):
         z = torch.Tensor(2, 3)
         z = z.type_as(x)

Presumably _x_ is a tensor that has already been initialized on the target gpu.

My question is what to do in the case where we want to initialize a new tensor on the target gpu, and we **do not** have access to a tensor that has already been initialized on the target gpu? 

For example, how does one properly initialize a new tensor when it is created inside a Dataset constructor that is instantiated during LightningDataModule _setup()_?

> class SomeDataModule(LightningDataModule):
...
    def setup(self, stage: Optional[str] = None):
        if stage in (None, "fit"):
            dataset = SomeDataset()
...

where:

> class SomeDataset(Dataset):
    def __init__(self):
        self.some_tensor = torch.Tensor(2,3)

Will using _type_as_ on the new tensor initialize the data on the target gpu?

> self.some_tensor = self.some_tensor.type_as(self.some_tensor)

Or is a different approach necessary? (e.g. [register_buffer()](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.register_buffer))

</div>

**Comment by akihironitta** [comment]
See #11774.
