### ISSUE TITLE
Load checkpoint with updated `Trainer` arguments

### ISSUE THREAD

**Issue by OverLordGoldDragon** [PyTorchLightning/pytorch-lightning#11791]
Just like the model, from [docs](https://pytorch-lightning.readthedocs.io/en/latest/common/checkpointing.html#checkpoint-loading):
```python
# uses in_dim=32, out_dim=10
model = LitModel.load_from_checkpoint(PATH)

# uses in_dim=128, out_dim=10
model = LitModel.load_from_checkpoint(PATH, in_dim=128, out_dim=10)
```
I'd like to do e.g.
```
trainer.fit(model, ckpt_path..., detect_anomaly=False)
```
Is there a workaround in the meantime?

cc @borda

**Comment by rohitgr7** [comment]
hey @OverLordGoldDragon !

why not do just
```py
trainer = Trainer(..., detect_anomaly=False)
trainer.fit(model, ckpt_path=...)
```

**Comment by OverLordGoldDragon** [comment]
Overridden by the checkpoint

**Comment by rohitgr7** [comment]
checkpoint doesn't save any trainer arguments.

**Comment by OverLordGoldDragon** [comment]
Strange, I saw `trainer._detect_anomaly == True` despite passing `False`, but now can't make an MRE. I'll reopen if I can confirm more definitively, thanks
