### ISSUE TITLE
[Tracker] Remaining tasks for Strategy stable version

### ISSUE THREAD

**Issue by four4fish** [PyTorchLightning/pytorch-lightning#11812]
## 🚀 Feature

Lightning Strategy stable version

### Motivation

After the refactoring issue is done, the main code structure will be stable. But there are other correctness and stability related issues that need to be addressed, some API simplification should be done, and some P0 features should be supported.

### Pitch
**Remaining tasks**
1. [Finish refactor, we have two remaining steps for accelerator refactor](https://github.com/PyTorchLightning/pytorch-lightning/issues/10416)
    - [Accelerator_connector rewrite](https://github.com/PyTorchLightning/pytorch-lightning/pull/11448) (in review)
         * follow ups: strategy selection and fallback logic, [device/accelerator default](https://github.com/PyTorchLightning/pytorch-lightning/issues/10606), misconfig handling
    - Flatten the strategies inheritance (not started)
2. Correctness and stability related issues
    - Revisit and unification of device related logic #11427 and 
    - Stable lazy initialization in Strategies #7650
    - Generalize internal checks for precision plugin type, training type, accelerator type #10821
    - Fix horovod bugs
    - (Other bug fixes)
3. API simplifications and improvement
    - Deprecations : unused properties in accl_conn, [enums](https://github.com/PyTorchLightning/pytorch-lightning/blob/8c07d8bf905e395bbd2142b5df7b185b8e936c41/pytorch_lightning/utilities/enums.py#L228-L283), [trainer.X](https://github.com/PyTorchLightning/pytorch-lightning/blob/32e7d32956e1685d36f2ab0ca3770baa2f76ce10/pytorch_lightning/trainer/trainer.py#L1971-L2009)_method
    - Align DDP/DDPSpawn process creation #10985
    - Precision API revisit, better support amp, move misconfig/availability checks from accl_conn to precision._init__
    - Strategies API revisit, add is_distributed(), and move misconfig/availability checks to strategy._init_
    - Accelerator API revisit, add teardown(), and add devices availability check (in review)
    - [Finish collective refactor](https://github.com/PyTorchLightning/pytorch-lightning/pull/9414)
4. Feature support
    - no-op Strategy and Accelerator, support open source project TorchRec
    - [Support Fairring, support init PG outside lightning](https://github.com/PyTorchLightning/pytorch-lightning/issues/11725) 
5. Better engineering tasks
   - Improve typing
   - Improve unit tests
   - docs and docstrings

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @justusschock @kaushikb11 @awaelchli @ninginthecloud @akihironitta @rohitgr7 @carmocca @tchaton @ananthsub

**Comment by carmocca** [comment]
This kind of issue is more of a "Tracker" than an "RFC" so renaming it a such if you don't mind :)
