### ISSUE TITLE
update all docs to reflect new syntax for accelerators

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#11833]
All the docs still say:
```python
Trainer(gpus=...)
```

But we now support a different syntax:
```python
Trainer(devices=4, accelerator='gpu')
```

Although we have backward support, all the docs (including readme) needs to reflect the new way of doing it

cc @borda @rohitgr7 @akihironitta @ananthsub @carmocca @Borda

**Comment by divyanshugit** [comment]
If it's available, then I would love to work on it.
