### ISSUE TITLE
[RFC] Remove `log_text` and `log_image` from `LightningLoggerBase` API

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#11837]
## Proposed refactor

Remove these methods from the `LightningLoggerBase` API:
https://github.com/PyTorchLightning/pytorch-lightning/blob/8d23f6287adf1e1040948802e6649c4ae2b3eda1/pytorch_lightning/loggers/base.py#L193-L205

### Motivation
`log_text` and `log_image` are both only overridden on 2 loggers: `WandbLogger` and `NeptuneLogger`.

For the rest of the loggers, since these methods are on the Base API it seems to imply that you can call them, but if you do for most loggers you will get a `NotImplementedError`. This is not a good user experience and it would be better to just keep these methods specific to `WandbLogger` and `NeptuneLogger` so it is clear that they can only be called for those loggers.

Similar motivation to https://github.com/PyTorchLightning/pytorch-lightning/issues/11234

From https://github.com/PyTorchLightning/pytorch-lightning/issues/11234: "A good rule of thumb is that the only required interfaces for the Logger are what the Trainer directly calls. Everything else can be pushed to various implementations". Since the trainer does not call `log_text` or `log_image` these do not need to be required on the Logger API.

### Additional Context
These were added in https://github.com/PyTorchLightning/pytorch-lightning/pull/9545

cc @justusschock @awaelchli @rohitgr7 @tchaton @borda @edward-io @ananthsub @kamil-kaczmarek @Raalsky @Blaizzy @akihironitta

**Comment by ananthsub** [comment]
The Trainer explicitly calls `log_graph` here: https://github.com/PyTorchLightning/pytorch-lightning/blob/789fae828dd3c3196b09bb5451e568c776dc99a6/pytorch_lightning/trainer/trainer.py#L1243

This means it's required to be on the logger API

**Comment by daniellepintz** [comment]
Updated the issue to not include `log_graph`, and will update it shortly with more information overall.

**Comment by ananthsub** [comment]
Based on #9545, I agree with them motivations:
-  `WandbLogger.log_image` and `WandbLogger.log_text` still exist, so the primary use case is unaffected by this
- WandbLogger does not require these interfaces on the base class
- The arguments to these functions are completely left open. This means all argument validation is left to logger subclasses, and users don't get the benefit of typehints, which can easily lead to errors.
- Only log_image and log_text were added to the base class, but log_table wasn't, despite being added in #9545. The inconsistency here demonstrates that these methods don't need to be on the base class

**Comment by daniellepintz** [comment]
Yeah, good points, especially about `log_table`!
