### ISSUE TITLE
rework docs to encourage the best practice of having a separate nn.Module

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#11834]
A while back we shifted to recommending:
```python
encoder = ...
decoder = nn.Module(...)

class Autoencoder(LightningModule):
    def __init__(self, encoder, decoder):
        self.encoder = encoder
        self.decoder = decoder
```

instead of:
```python
class Autoencoder(LightningModule):
    def __init__(self):
        self.encoder = nn.Module(...)
        self.decoder = nn.Module(...)
```

we need to update all the docs including readme. This DOES NOT mean we don't support the first one, but the recommended thing is to keep your nn.Modules outside of LightningModule so that you don't HAVE to couple it with PL when you go do inference.

However, some people might still want to do:
```python
class Model(LightningModule):
    def __init__(self):
       self.l1 = nn.Module(...)
       self.l2 = nn.Module(...)
```
and that's STILL OK and likely to be the pattern for researchers

Related to https://github.com/PyTorchLightning/pytorch-lightning/issues/10270

cc @borda @rohitgr7

**Comment by rohitgr7** [comment]
one issue, with the first one, is that while saving the hparams, the `nn.Modules` will be saved too in the hyperparameters while calling `self.save_hyperparameters()` unless the user explicitly calls it with `self.save_hyperparameters(ignore=['encoder', 'decoder'])`.

maybe we can improve the `save_hyperparameters()` to not save any `nn.Module`s by default?

**Comment by awaelchli** [comment]
It's true that keeping the model definitions outside helps in production. And we've seen people adopt this pattern very often. However, we should also keep in mind that you can't simply load the nn Module weights from a lightning checkpoint. For example, in the auto encoder example above the parameter names will still include the "encoder." and "decoder." prefixes for all parameter names. 

So simply calling `load_state_dict` in your production code won't be enough, you have to iterate over the state dict and remove the prefix from all keys.

That's why I have recommended this pattern in the past as well

```py
# your lightning module for training
class MyLightningModule(LightningModule):
    def __init__(self):
       self.model = Model()
       
 
# a simple wrapper, instead of LightningModule it inherits from nn.Module
# use this in production
class ProductionModelWrapper(nn.Module):
    def __init__(self):
       self.model = Model()
```

You can now load the trained weights from the checkpoint and directly call
```py
production_model_wrapper = ProductionModelWrapper()
production_model_wrapper.load_state_dict(...)
```

**Comment by timothylimyl** [comment]
Hi all, currently I am on the same boat with @awaelchli, my production code uses a dummy lightning module to wrap the PyTorch model to load it. 

Another way around it will be to change the `state_dict()` manually. For example:

pytorch model state dict is `conv1.weights` whereas lightning will be `model.conv1.weights`.  Now we cannot do:
```
trained_weights = torch.load('xxx.ckpt')["state_dict"]
model.load_state_dict(trained_weights)
```

Convert the dictionaries accordingly:
```
from collections import OrderedDict

def lightning_to_torch_dicts(model_dict):

    new_dict = OrderedDict()

    for k, v in model_dict.items():
        if "model." in k:
            k = k.replace("model.", "")
        new_dict[k] = v
    return new_dict
```
Now we can run this with no problem.
```
trained_weights = torch.load('xxx.ckpt')["state_dict"]
trained_weights = lightning_to_torch_dicts(trained_weights)
model.load_state_dict(trained_weights)
```


 If it is always 'model.' in front, I believe the lightning team can just add a flag that allows users to convert lightning state dict to PyTorch model state dict as such.

Happy to contribute accordingly, please let me know how I can help, hoping to contribute back to lightning but I am not a very experienced open-source contributor.
