### ISSUE TITLE
Reproducibility issue vs vanilla pytorch on multiple training runs

### ISSUE THREAD

**Issue by amin-nejad** [PyTorchLightning/pytorch-lightning#11840]
## 🐛 Bug

**Pytorch Lightning (PL):**

The first run of a model in PL gives one set of results. Subsequent runs (new model instance, same data) all give the _same results_ **but** _different to that of the first run_. There is no reseeding in between these runs. If I reseed, then I am able to reproduce the original results.

**Vanilla pytorch (PT):**

With the same model and data reproduced in PT, on the first run I'm able to get the same results as the first run of the PL model. So I know the models are doing the same thing. However on subsequent runs without reseeding in between, I get a _different set of results_ that are **different every time** both with respect to each other and with respect to the results in PL. Again, if I reseed, then I am able to reproduce the original results.

On the basis of these results, I think we can tease out a few distinct (but obviously related) issues:

1. It appears something in that first run in PL is modifying the RNG state unexpectedly which is _not happening on subsequent runs_
2. This modification is different to whatever is done in vanilla PT which appears to modify the RNG state every time we fit the model and in a different way too because the second set of results in PL are different to the second set of results in PT
3. Why is there a difference in behaviour between subsequent runs in lightning vs subsequent runs in pytorch? Specifically why do we always get the same results in pytorch lightning but not in vanilla pytorch
4. I don't think we should need to reseed between runs. If we do, should this be documented?

I'm not sure what is going on here e.g. is this is a bug in PT, PL, my code or just a documentation issue, but my inclination is that PL should follow PT and we should always get the same results as each other.

### To Reproduce

Please see the colab notebook below with the issue reproduced with the Boring model.

https://colab.research.google.com/drive/1rhR6k7bN5cKwiJLHz7szVR2T14Wyxe3B?usp=sharing

### Expected behavior

We should get _exactly_ the same results in PT as we do in PL. If it turns out I'm doing something wrong (which may well be the case!) then this should probably become a documentation ticket rather than a bug in order to more openly highlight the issue to users.

### Environment

* CUDA:
	- GPU:
	- available:         False
	- version:           11.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.10.0+cu111
	- pytorch-lightning: 1.5.10
	- tqdm:              4.62.3
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.12
	- version:           # 1 SMP Tue Dec 7 09:58:10 PST 2021

### Additional context

For PL, I followed the guidance in the documentation [here](https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#reproducibility).

For PT, I followed the guidance in the documentation [here](https://pytorch.org/docs/stable/notes/randomness.html).

cc @awaelchli @akihironitta

**Comment by awaelchli** [comment]
When you ran the PL script, did you have sanity check turned on? Could be caused by this line:

The reset_seed() method is feeding off of an environment variable PL_GLOBAL_SEED which persists between your multiple runs. With every fit, you will rerun sanity check and I guess re-trigger the reset. 

You should be able to suppress this behavior by setting num_sanity_val_steps=0 in the Trainer.

I have an idea how we could improve this reset logic. Instead of seeding with the initial global_seed, we 

1. capture the random state before we run the sanity check, save it
2. run the sanity check
3. restore the random state to what it was before the sanity check.

**Comment by awaelchli** [comment]
Update. I tried my fix with your notebook (thanks a lot for providing it) to verify it. Feel free to do the same, you can replace the pip install with

```py
pip install git+https://github.com/PyTorchLightning/pytorch-lightning.git@bugfix/reset-seed
```

**Comment by amin-nejad** [comment]
Hi @awaelchli, sorry for the late reply, I think that's good solution! I tested it and it seems like it does the job. 💪🏽  

The vanilla and lightning versions now behave much more similarly in that the results change every time now. One thing I'm still not clear on though is why the results aren't exactly the same as each other after the first run. It seems like the random state is still being modified differently somehow. I have set `num_sanity_val_steps=0` on the PL trainer but the issue is still there. Do you have an idea of what might be going on here?

**Comment by crazyn2** [comment]
same issue
```
os.environ['PYTHONHASHSEED'] = str(args.seed)
    pl.seed_everything(args.seed, workers=True)
    random.seed(args.seed)
    torch.cuda.manual_seed_all(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    torch.cuda.manual_seed_all(args.seed)
```
those codes couldn't run the same result
