### ISSUE TITLE
_LightningModuleWrapperBase doesn't pass attribute _ddp_params_and_buffers_to_ignore correctly

### ISSUE THREAD

**Issue by Honzys** [PyTorchLightning/pytorch-lightning#11844]
## 🐛 Bug

I guess, there's a problem when passing `_ddp_params_and_buffers_to_ignore` attribute to the wrapper. There's the corresponding section - https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/overrides/base.py#L75 .

I think it should be prefixed with the name of attribute where it is saved.

```diff
class _LightningModuleWrapperBase(DeviceDtypeModuleMixin, torch.nn.Module):
    def __init__(self, pl_module: Union["pl.LightningModule", _LightningPrecisionModuleWrapperBase]):
        """
        Wraps the user's LightningModule and redirects the forward call to the appropriate
        method, either ``training_step``, ``validation_step`` or ``test_step``.
        If the LightningModule is in none of the states `training`, `testing` or `validation`,
        the inputs will be redirected to the
        :meth:`~pytorch_lightning.core.lightning.LightningModule.predict` method.
        Inheriting classes may also modify the inputs or outputs of forward.

        Args:
            pl_module: the model to wrap
        """
        super().__init__()
        self.module = pl_module

        # set the parameters_to_ignore from LightningModule.
-        self._ddp_params_and_buffers_to_ignore = getattr(pl_module, "_ddp_params_and_buffers_to_ignore", [])
+        self._ddp_params_and_buffers_to_ignore = list(map(lamba x: f"module.{x}", getattr(pl_module, "_ddp_params_and_buffers_to_ignore", [])))
```
### To Reproduce

You can set anything to `self._ddp_params_and_buffers_to_ignore` in `LightningModule` and then print the values in here - https://github.com/PyTorchLightning/pytorch-lightning/blob/9ebdc52ec631df92ca7cfc1ba852801dd36d3864/pytorch_lightning/plugins/training_type/ddp.py#L188 .
It will not have the prefixes of `module` caused by the wrapping, leading to situation where the params to ignore are not correctly passed to the `DistributedDataParallel`, which then can cause errors.

### Expected behavior

Parameter names should be prefixed with the modules while wrapping. This will fix later errors when parameters are not ignored properly.

### Environment

* CUDA:
        - GPU:
        - available:         False
        - version:           11.1
* Packages:
        - numpy:             1.22.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.10.0+cu111
        - pytorch-lightning: 1.5.8
        - tqdm:              4.62.3
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - 
        - processor:         x86_64
        - python:            3.8.0
        - version:           #1 SMP Fri Sep 10 13:19:36 EDT 2021

### Additional context

cc @tchaton @rohitgr7 @akihironitta @carmocca @justusschock @awaelchli @borda @ananthsub @ninginthecloud @jjenniferdai @kaushikb11

**Comment by awaelchli** [comment]
Hello
Thanks for this report. I think your assessment is correct. Would you be able to send a PR with this proposed fix?

**Comment by Honzys** [comment]
Hello,
yes, I can try to create the PR :) .
