### ISSUE TITLE
"Edit on GitHub" font looks off

### ISSUE THREAD

**Issue by rasbt** [PyTorchLightning/pytorch-lightning#11882]
## 📚 Documentation

I think there might be an incorrect style/class attribute set for the "Edit on GitHub" text on the documentation page. It's a serif font, and every time I look at it, it throws me off a little. It's maybe one of these things that you can't unsee once you've seen it:

![Screen Shot 2022-02-11 at 8 28 18 AM](https://user-images.githubusercontent.com/5618407/153609889-da1c5c72-819d-4e86-a85c-37fdc57c5e8f.png)

I suggest trying to see if you can use the same style attribute as for the other text (e.g., Shortcuts next to it) so that it uses the same font.

cc @borda @rohitgr7

**Comment by Borda** [comment]
this coming from the plugin we are using, I would be rather considered disabling it for any notebooks and including the specific link in the notebook itself...

**Comment by rasbt** [comment]
I see! Actually, it also looks fine on Safari. It only looks weird on Chrome for some reason.
![Screen Shot 2022-02-11 at 3 20 50 PM](https://user-images.githubusercontent.com/5618407/153671909-c2369dd7-f8f4-40e3-ae83-03a20e625ff8.png)
