### ISSUE TITLE
Confusing setting of validation frequency

### ISSUE THREAD

**Issue by cmpute** [PyTorchLightning/pytorch-lightning#1189]
## 🚀 Feature

Currently the validation frequency is set by `check_val_every_n_epoch` and `val_check_interval` of Trainer. The former one and latter one have an overlap in terms of frequency control actually. I propose use `check_val_every_n_epoch` and `check_val_every_n_batches` as the parameter:

`check_val_every_n_epoch=10` is equivalent to `check_val_every_n_epoch=10` previously
`check_val_every_n_epoch=0.1` is equivalent to `val_check_interval=0.1` previously
`check_val_every_n_batches=10` is equivalent to `val_check_interval=10`.

And furthermore, these two options should be mutually exclusive. If one sets `check_val_every_n_batches` then shouldn't set `check_val_every_n_batches`.

### Motivation

I propose this because I get confused when I try to tweak the validation frequency and find two options for setting it...

**Comment by Borda** [comment]
@cmpute do you have a specific suggestion? :]

**Comment by cmpute** [comment]
Yeah just as I said, change the option `val_check_interval` to `check_val_every_n_batches` and change their meanings to correspondant one

**Comment by Borda** [comment]
@PyTorchLightning/core-contributors do you see this API change as needed?

**Comment by jeremyjordan** [comment]
i agree it would be more clear

**Comment by cmpute** [comment]
bump

**Comment by williamFalcon** [comment]
agree that this is a good rename. can you think of something shorter?

**Comment by cmpute** [comment]
Maybe just remove the "check_" prefix?

**Comment by williamFalcon** [comment]
how about
`validate_frequency` or similar

**Comment by qiuhuaqi** [comment]
Why not merge the two flags together? 
e.g. keep only `val_check_interval`, use `int` to specify the number of batches, use `float` to specify in terms of epochs

`val_check_interval=3.0` => validation every 3 epochs, 
`val_check_interval=10` => validation every 10 batches within an epoch

in the unlikely case of `val_check_interval=3.5` => validation every 3.5 epochs, (triggering `validation_epoch_end` at the end of epoch 4?)

Or would this complicate other things too much?

**Comment by williamFalcon** [comment]
yeah... this seems pretty complicated. if you need to read the docs and not derive it from the syntax, it's too complicated

**Comment by qiuhuaqi** [comment]
Fair enough. Renaming would be great though. Took me a while to find both flags. 
How about:
`check_val_every_n_epoch` -> `val_every_n_epoch`,
`val_check_interval` -> `val_freq_in_epoch`

**Comment by cmpute** [comment]
bump

**Comment by williamFalcon** [comment]
cc @edenafek
