### ISSUE TITLE
train and validation hooks

### ISSUE THREAD

**Issue by thistlillo** [PyTorchLightning/pytorch-lightning#11903]
please consider the `fit_loop` in this page:
[https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_module.html](https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_module.html)

it ends with:
```
    # end training epoch
    training_epoch_end()
    on_train_epoch_end()
```

Now consider the `val_loop`. An epoch ends with:
```
    validation_epoch_end(val_outs)
    on_validation_epoch_end()
```
In the `val_loop` it is clear there is difference between the two hooks, the first receives an input.

In the `fit_loop`:
- is there an error in the documentation?
- if not, what's the purpose of the two hooks?

cc @borda @rohitgr7

**Comment by rohitgr7** [comment]
yes, `training_epoch_end` receives the outputs., just like the validation counterpart.
