### ISSUE TITLE
parameters devices and gpus in Trainer

### ISSUE THREAD

**Issue by thistlillo** [PyTorchLightning/pytorch-lightning#11902]
### 📚 The doc issue

In this page:
https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html

it is not clear the difference between `devices` and `gpus`. It seems they are equivalent, but then when I read this page:

https://pytorch-lightning.readthedocs.io/en/stable/advanced/multi_gpu.html

Only the `gpus` argument is discussed, so it is not clear what happens when `devices` is used in place of `gpus`.

### Suggest a potential alternative/fix

Please discuss the differences between the parameters `devices` and `gpus` (and the other types of device), if any.

Please specify what happens when both `devices` and `gpus` are used, especially when their values are different, e.g. `devices=2, gpus=[0,1,3]` or `devices=2, gpus=3`.

cc @borda @rohitgr7

**Comment by rohitgr7** [comment]
gpus = `devices + accelerator`

```py
Trainer(gpus=4) -> Trainer(devices=4, accelerator='gpu')
```

```py
Trainer(gpus=[1,2,3]) -> Trainer(devices=[1,2,3], accelerator='gpu')
```

`devices` is common for all the accelerators (TPU, IPU, ...), but `accelerator` defined the kind of accelerator to use. We will anyways deprecate and remove `gpus` in the future, so I'd suggest using `devices` and `accelerator` instead.

**Comment by awaelchli** [comment]
We are slowly moving away from the gpus, ipus, tpus, ... syntax in favor of accelerator + devices as @rohitgr7 explains. For 1.6, we updated all docs to this new syntax and will continue to do so in all ecosystem libraries. So there is no need anymore to point out differences. Closing this issue. If you have any questions, let us know :)
