### ISSUE TITLE
DDP GPU memory imbalanced

### ISSUE THREAD

**Issue by lukasfolle** [PyTorchLightning/pytorch-lightning#11923]
## 🐛 Bug
Creating an issue for the problem described in https://github.com/PyTorchLightning/pytorch-lightning/discussions/6568.
When using DDP on a single node with 8 GPUs the memory usage is highly imbalanced with one using 98% of the memory while the remaining GPUs just use around 70%.

A solution to this might be https://discuss.pytorch.org/t/extra-10gb-memory-on-gpu-0-in-ddp-tutorial/118113.

cc @justusschock @kaushikb11 @awaelchli @akihironitta @rohitgr7

**Comment by justusschock** [comment]
Hi @lukasfolle Can you provide a reproducible script for that?

The solution you mentioned is already implemented in https://github.com/PyTorchLightning/pytorch-lightning/blob/f79d75d4b5e50eb3e37073606eba5ca10d48c99a/pytorch_lightning/strategies/ddp.py#L119 and https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/accelerators/gpu.py#L45

**Comment by lukasfolle** [comment]
Did this change recently?

The script I am running is this (with 8 GPUs on one node): https://github.com/facebookresearch/fastMRI/blob/main/fastmri_examples/varnet/train_varnet_demo.py

**Comment by justusschock** [comment]
@lukasfolle Is there any chance that you could provide a minimal reproducible script or a dummy dataset providing similar outputs?

I would prefer not to download tons of data for trying this.

> Did this change recently? 
No, this should be quite "old" actually.

**Comment by lukasfolle** [comment]
> The solution you mentioned is already implemented in 

I don't see the empty_cache call, but I don't have the deepest understanding of the topic, so it might not be necessary here.

With this code you should be able to reproduce it:
``` python
import os
import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    dataset_train = RandomDataset(32, 64)
    dataset_val = RandomDataset(32, 64)
    sampler_train = torch.utils.data.DistributedSampler(dataset_train)
    sampler_val = torch.utils.data.DistributedSampler(dataset_val)
    train_data = DataLoader(dataset_train , batch_size=2, sampler=sampler_train, num_workers=64) 
    val_data = DataLoader(dataset_val , batch_size=2, sampler=sampler_val, num_workers=64)

    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        gpus=8,
        accelerator='ddp',
        replace_sampler_ddp=False,
    )
    trainer.fit(model, train_data, val_data)

if __name__ == "__main__":
    run()
```

**Comment by justusschock** [comment]
Hi @lukasfolle , I unfortunately cannot reproduce this. 

I have only 2 GPUs, but with your script I trained for 1000 epochs and the output is as follows:

<img width="637" alt="image" src="https://user-images.githubusercontent.com/12886177/154089415-1e45c470-ba41-44f5-972f-1ff0f678b761.png">


So substracting the two x-server processes, the gpus are at both at 2103 MB (i.e. perfectly on par).

Which lightning version are you using?

**Comment by lukasfolle** [comment]
Thank you for checking this. I will try to dig deeper into the issue and update here if I notice anything further.
I freshly installed pl.

**Comment by WYHbxer** [comment]
> Thank you for checking this. I will try to dig deeper into the issue and update here if I notice anything further. I freshly installed pl.

Hello，I am also suffering from this problem. Is there any solution now

**Comment by tkella47** [comment]
I also am interested in the solution here

**Comment by Boltzmachine** [comment]
Look at mine :(
![85a8c23eff8d195d92f4cd9d8fbb3a8](https://github.com/user-attachments/assets/33d11681-0562-485f-a3a7-68d3a221fe2b)
