### ISSUE TITLE
ModelCheckpoint called before validation

### ISSUE THREAD

**Issue by ZhaofengWu** [PyTorchLightning/pytorch-lightning#11930]
When I set both model checkpoint and validation to happen mid-epoch (at the same interval), it seems that checkpoint is done before validation. Looks like checkpoint happens in the `advance` function of `TraininingEpochLoop`
https://github.com/PyTorchLightning/pytorch-lightning/blob/f79d75d4b5e50eb3e37073606eba5ca10d48c99a/pytorch_lightning/loops/epoch/training_epoch_loop.py#L221

whereas validation happens in `on_advance_end`
https://github.com/PyTorchLightning/pytorch-lightning/blob/f79d75d4b5e50eb3e37073606eba5ca10d48c99a/pytorch_lightning/loops/epoch/training_epoch_loop.py#L245

Is this expected? Is there a way to specify the same time interval but do validation first, so that the checkpoint (at least its file name) reports the correct metrics?

**Comment by awaelchli** [comment]
Hello

See the argument `save_on_train_epoch_end` in the [model checkpoint docs](https://pytorch-lightning.readthedocs.io/en/1.5.10/extensions/generated/pytorch_lightning.callbacks.ModelCheckpoint.html#modelcheckpoint). Try to set it to false, `save_on_train_epoch_end=False`.

**Comment by ZhaofengWu** [comment]
I did. I have two `ModelCheckpoint` callbacks, one for end-of-epoch checkpoints (with `save_on_train_epoch_end=True`), and one for mid-epoch checkpoints (with `save_on_train_epoch_end=False` and `every_n_train_steps` set to the validation interval). The checkpoint in question is the second one, which seems to be called before mid-epoch validation.

**Comment by rohitgr7** [comment]
hey @ZhaofengWu for the second one you don't need to set the `every_n_train_steps` because by default checkpoint callback is called after each validation loop, so setting `save_on_train_epoch_end=False` would do the job.

**Comment by ZhaofengWu** [comment]
Thanks! This seems to work for me. And actually I lied -- I didn't set `save_on_train_epoch_end` for the second checkpoint callback. I thought it defaults to `False` but apparently it defaults to `None`. Anyway, I guess the original behavior that I described is slightly unintuitive, but it's good enough for me that there is a configuration of flags that works.
