### ISSUE TITLE
Investigate environment variable "MASTER_PORT"  in spawn plugin 

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#11965]
## Proposed refactor

Investigate if setting the MASTER_PORT environment variable is needed here:
https://github.com/PyTorchLightning/pytorch-lightning/blob/4397f2d7481aad5d8a476e201d6a28daea5c4aa5/pytorch_lightning/strategies/launchers/spawn.py#L67

From [comment](https://github.com/PyTorchLightning/pytorch-lightning/pull/11643#discussion_r809252728) by @carmocca 
### Motivation

We would like to rely on the cluster environment completely if possible, and not leak logic for specific variables. 

### Pitch

Remove and see if tests fail.

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @justusschock @awaelchli @rohitgr7

**Comment by carmocca** [comment]
Can you add that as a comment in the PR? Thanks!
