### ISSUE TITLE
Wrong documentations for `on_fit_*` of `TrainerCallbackHookMixin`

### ISSUE THREAD

**Issue by function2-llx** [PyTorchLightning/pytorch-lightning#11961]
Hello PyTorch Lightning team,

it seems that documentations for `on_fit_*` methods of `TrainerCallbackHookMixin` class are wrong (seems to misplace doc for `on_init_start` here).

https://github.com/PyTorchLightning/pytorch-lightning/blob/4dba492fb55e2862bb20f304e6bef43f1f151fc7/pytorch_lightning/trainer/callback_hook.py#L115-L139

cc @borda @rohitgr7 @carmocca @awaelchli @ninginthecloud @daniellepintz

**Comment by ananthsub** [comment]
> What is the problem exactly?

The docs reference this line:
>          Called when the trainer initialization begins, model has not yet been set. 

Which is not true for `on_fit_start`

**Comment by awaelchli** [comment]
This used to be true but not anymore. It has changed roughly around the work we did on #10896 and such a doc update got easily missed. A PR for correcting this would be very welcomed ❤️
