### ISSUE TITLE
ModelCheckpoint class attempts to save a model file on every batch run - when only training_step configured in Trainer class

### ISSUE THREAD

**Issue by kwanUm** [PyTorchLightning/pytorch-lightning#1197]
## 🐛 Bug

ModelCheckpoint class attempts to save a model file on every batch run.

### Additional context

I've created a simple trainer with a checkpoint, passing save_best_k=-1. My trainer only has a training step configured. 

The model checkpoint class is being called at the end of each batch run here - https://github.com/PyTorchLightning/pytorch-lightning/blob/732eaee4d735dafd1c90728e5583341d75ff72b5/pytorch_lightning/trainer/training_loop.py#L741

This seems to be because train_step_only flag is active in my case, and the relevant code that triggers the model save is here - https://github.com/PyTorchLightning/pytorch-lightning/blob/732eaee4d735dafd1c90728e5583341d75ff72b5/pytorch_lightning/trainer/training_loop.py#L457

**Comment by awaelchli** [comment]
I tested it on the latest master branch and cannot reproduce what you described. It looks like this was fixed (the `train_step_only` variable is not there anymore). Can you confirm this?

**Comment by edenlightning** [comment]
@kwanUm is this still relevant?

**Comment by kwanUm** [comment]
Seems to be fixed. Thank you!
