### ISSUE TITLE
Rename `loops/base.py` to `loops/loop.py`

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#11974]
## Proposed refactor

Rename `loops/base.py` to `loops/loop.py`

### Motivation
For consistency, let's conform to the standard of our other main files, like `accelerators/accelerator.py` and `strategies/strategy.py`.

Part of https://github.com/PyTorchLightning/pytorch-lightning/issues/11908

cc @borda @justusschock @awaelchli @rohitgr7 @carmocca @ananthsub @ninginthecloud @daniellepintz

**Comment by kingjuno** [comment]
@valanm22 Can I start working on this issue if you are not working on this now?

**Comment by valanm22** [comment]
Yes @kingjuno you can.
