### ISSUE TITLE
Rename `callbacks/base.py` to `callbacks/callback.py`

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#11973]
## Proposed refactor

Rename `callbacks/base.py` to `callbacks/callback.py`

### Motivation
For consistency, let's conform to the standard of our other main files, like `accelerators/accelerator.py` and `strategies/strategy.py`.

Part of https://github.com/PyTorchLightning/pytorch-lightning/issues/11908

cc @borda @justusschock @awaelchli @rohitgr7 @ananthsub @daniellepintz

**Comment by daniellepintz** [comment]
Yes! Assigning you :)

**Comment by akihironitta** [comment]
Hi @PushanAgrawal! Thank you for working on this in #11996! Would you like to continue the linked PR or let another contributor work on this issue instead?

Hi @shantam-8! Thanks for your interest in contributing!  Let's wait maybe for a few days to hear if @PushanAgrawal still wishes to continue to work on it :] In the meantime, you could pick one of the issues labeled "good first issue" or "help wanted"! (#12521 has a lot of TODO items and definitely needs help from the community!)

**Comment by akihironitta** [comment]
@shantam-8 Would you be interested in submitting a PR?
