### ISSUE TITLE
Rename `LightningLoggerBase` to `Logger`

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#11971]
## Proposed refactor
* Create a new file `loggers/logger.py`
* In that file, create a new `Logger` class by copying the code in `LightningLoggerBase`
* Make `LightningLoggerBase` subclass `Logger`, and create a dummy constructor to emit a deprecation warning like in this example:
https://github.com/PyTorchLightning/pytorch-lightning/blob/d61371922bf89a2b810711e67eee47f224be60cc/pytorch_lightning/plugins/training_type/ddp.py#L18-L24

### Motivation

We want all of our main class names to follow the same standard. `Logger` should match `Callback`, `Strategy`, `Accelerator`, etc. Also, we want our files names to conform to standard of `accelerators/accelerator.py`, `strategies/strategy.py`, etc.

Part of #11908

cc @justusschock @awaelchli @rohitgr7 @edward-io @borda @ananthsub @kamil-kaczmarek @Raalsky @Blaizzy

**Comment by MohammedAlkhrashi** [comment]
Hi, if no one has been assigned yet, can I work on this issue?
