### ISSUE TITLE
Add tutorial how to convert to PL (+ colab notebooks)

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#1198]
## 📚 Documentation

To keep track of a suggestion made by @Borda: 
- Add a tutorial to docs that shows how to convert regular PyTorch to PyTorch Lightning
- Colab notebooks could be directly included into the docs

**Comment by marylicious** [comment]
Hey @Borda , can you give me more info on this? What ideas do you have in mind? I'm starting a study group and probably will do some tutorials so it's like killing two birds with one gun

**Comment by Borda** [comment]
generate a documentation page with notebook is simple with `nbconvert`
for launching in colab see e.g. [Running Jupyter Notebook on Colab](https://medium.com/@margaretmz/running-jupyter-notebook-with-colab-f4a29a9c7156)

**Comment by asvskartheek** [comment]
Hi! I'm interested in working on this issue.

**Comment by Borda** [comment]
cool, @asvskartheek mind sync with @nateraw :]
