### ISSUE TITLE
Deprecate `Trainer.root_gpu`

### ISSUE THREAD

**Issue by ananthsub** [PyTorchLightning/pytorch-lightning#11994]
## Proposed refactor

Deprecate this property: 
https://github.com/PyTorchLightning/pytorch-lightning/blob/cf64f3443474a93d23b5afb0417e4a60298006e6/pytorch_lightning/trainer/trainer.py#L1982-L1984

### Motivation

This property is redundant with the Strategy's `root_device` property, which generalizes this check. 
Following https://github.com/PyTorchLightning/pytorch-lightning/pull/11758, this property is not used anywhere else in the framework. This is only used in tests, which can be updated to use `trainer.strategy.root_device` instead

### Pitch

Deprecate this property, and recommend using `trainer.strategy.root_device` instead
Regarding how to deprecate the property, this issue provides an example: https://github.com/PyTorchLightning/pytorch-lightning/issues/10615

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @justusschock @awaelchli @rohitgr7 @tchaton @akihironitta @kaushikb11 @ananthsub @ninginthecloud @jjenniferdai

**Comment by vpavankalyan** [comment]
I would like to work on this issue

**Comment by rohitgr7** [comment]
hey @vpavankalyan!
I have assigned this issue to you. Feel free to send a PR :)
