### ISSUE TITLE
Small issue in documentation for BaseFinetuning callback

### ISSUE THREAD

**Issue by dennisbappert** [PyTorchLightning/pytorch-lightning#12005]
## 🐛 Bug

It seems that there is a small error in the sample and the documentation (https://pytorch-lightning.readthedocs.io/en/stable/extensions/generated/pytorch_lightning.callbacks.BaseFinetuning.html?highlight=finetuning):

![image](https://user-images.githubusercontent.com/7000188/154798971-6fb4b65d-dbab-47cb-a0d9-27da806c6da5.png)

```python
# The parameter list should look like this:
filter(lambda p: p.requires_grad, self.parameters())
```

cc @borda @rohitgr7

**Comment by dennisbappert** [comment]
![image](https://user-images.githubusercontent.com/7000188/154799134-f41b7fe6-5480-41d8-872d-726ec5ae2bd5.png)

The parent class constructor call is also missing in the documentation.

**Comment by akihironitta** [comment]
Hi @dennisbappert, thank you for reporting the issue. It should be the following as you point out:
```diff
-        return Adam(filter(lambda p: p.requires_grad, self.parameters))
+        return Adam(filter(lambda p: p.requires_grad, self.parameters()))
```

Would it be possible for you to submit a PR with the proposed fix?
