### ISSUE TITLE
Cannot pass callable as `model_class` to `LightningCLI`

### ISSUE THREAD

**Issue by yangky11** [PyTorchLightning/pytorch-lightning#12013]
## 🐛 Bug

I get the following error when trying to pass a function that returns a `LightningModule` as the `model_class` argument to when constructing `LightningCLI`.

```
pytorch_lightning.utilities.exceptions.MisconfigurationException: Cannot add arguments from: <class 'jsonargparse.signatures.class_from_function.<locals>.ClassFromFunction'>. You should provide either a callable or a subclass of: Trainer, LightningModule, LightningDataModule, or Callback.
```

It looks like the potential problem is here:

https://github.com/PyTorchLightning/pytorch-lightning/blob/0374fe65dba85ff6b169524289921254357f0e7d/pytorch_lightning/utilities/cli.py#L169-L189

Even if `callable(lightning_class) and not isinstance(lightning_class, type)` is `True`, the `MisconfigurationException` at the end will still be raised. Is that intended? 

cc @carmocca @mauvilsa

**Comment by mauvilsa** [comment]
This is working as intended, though the error message could be improved. When `callable(lightning_class) and not isinstance(lightning_class, type)` is `True` the value of `lightning_class` changes and the subsequent `if` must evaluate to `True`. @yangky11 your problem probably is that you are giving a callable that doesn't have a return type annotation or it is wrong. It must be a subclass of one of the lightning classes `(Trainer, LightningModule, LightningDataModule, Callback)`.

**Comment by yangky11** [comment]
I see. Thanks!

**Comment by wconnell** [comment]
for others, 

I ran into this issue because I was importing 

    import pytorch_lightining as pl

this was fixed when I switched to 

    import lightning.pytorch as pl

**Comment by klieret** [comment]
I ran into this issue when I used

```
# fails
from lightning import LightningModule
```

instead of

```
# runs
from pytorch_lightning import LightningModule
```

**Comment by apple2373** [comment]
I had a similar issue that i got "You should provide either a callable or a subclass of: Trainer, LightningModule, LightningDataModule, or Callback." But I am sure it was subclass of one of them. 

Then I changed the import sentence 
from `from pytorch_lightning.callbacks import Callback` to `from lightning.pytorch.callbacks import Callback`, which solved the problem. Maybe `pytorch_lightning` or `lightning.pytorch` matters.
