### ISSUE TITLE
Several issues with `WandbLogger` output directory structure in offline mode

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#12036]
## Proposed refactor

Change the default `name` to "lightning_logs" and the default `save_dir` to "wandb".
https://github.com/PyTorchLightning/pytorch-lightning/blob/60fe1520fd8ac8fa9006237f31045465200c9803/pytorch_lightning/loggers/wandb.py#L252-L253

### Motivation

Currently the `name` and `save_dir` properties on the `WandbLogger` default to `None`, and the version can be `None` as well.  This causes several issues in the directory structure as shown in the image below:

<img width="525" alt="wandb currentl" src="https://user-images.githubusercontent.com/38207072/155041288-27bd1396-dcad-401e-bbb6-740bb024e1be.png">

1. The main logging directory is named `None` which is an odd name for a directory to store logs
2. Wandb already automatically creates a directory called `wandb` which contains metadata. It is weird to have two separate logging directories for Wandb - let's instead default to storing everything in one. Plus, the doc literally says the save_dir is `wandb` by default, which is not true at the moment:
https://github.com/PyTorchLightning/pytorch-lightning/blob/60fe1520fd8ac8fa9006237f31045465200c9803/pytorch_lightning/loggers/wandb.py#L221
3. The profiler output is unable to save to a path since the logger's save_dir is `None`, and we get the error `The PyTorchProfiler failed to export trace as dirpath is None`
4. A fourth issue, but one that is not addressed by this proposed change, is that the subdirectory is named "version_None" which is also an odd name for a directory.

How the directory structure will look after this change:
<img width="537" alt="wandb after" src="https://user-images.githubusercontent.com/38207072/155042932-bf6a0f71-5719-4f80-b9ec-01db53b97400.png">

cc @awaelchli @morganmcg1 @AyushExel @borisdayma @scottire @manangoel99

**Comment by borisdayma** [comment]
> 2. Wandb already automatically creates a directory called `wandb` which contains metadata. It is weird to have two separate logging directories for Wandb - let's instead default to storing everything in one. Plus, the doc literally says the save_dir is `wandb` by default, which is not true at the moment:
>    https://github.com/PyTorchLightning/pytorch-lightning/blob/60fe1520fd8ac8fa9006237f31045465200c9803/pytorch_lightning/loggers/wandb.py#L221

It's typically a bad idea to put files within the `wandb` folder as it is used to upload logs and files internally.
You could have a risk of having wandb process trying to log them (even if model checkpoints are already logged separately through artifacts).

`wandb` folder is mainly used for offline use (and later sync), for uploading files/media/objects and for debugging.

**Comment by daniellepintz** [comment]
@borisdayma thanks for the info! good to know. so we will not put it in the wandb folder then. But I still think we should give it a default name other than None

**Comment by manangoel99** [comment]
I tried recreating this issue with the latest versions of wandb and pytorch-lightning and it got fixed. I think we can close this.
