### ISSUE TITLE
DDP training with Lite

### ISSUE THREAD

**Issue by 834799106** [PyTorchLightning/pytorch-lightning#12040]
For DDP training with Lite, I tried to evaluate in the main process. To ensure synchronization, I set sell.barrier () before the start of the next epoch, but I don't know if it took me too long to evaluate (17min), I couldn't train after the evaluation, maybe other processes had hung up. (Note: The same code will not have a problem when the evaluation time is about 2 minutes)

cc @carmocca @justusschock @awaelchli @kaushikb11 @akihironitta @rohitgr7

**Comment by awaelchli** [comment]
Hey @834799106
Is there a specific reason you need to do validation in a single process? It should be ok to just use all processes. After all, by default the dataloader gets a distributed sampler when using DDP, keep that in mind (it can also be turned off). It will also be faster.

**Comment by 834799106** [comment]
Hi @awaelchli ,
As a matter of fact, I am using MONAI framework for medical image segmentation. His evaluation module actually contains the code that sends the results to the buffer during multi-process evaluation and then collects them in the main process once. However, with the training process of Lite, I will have the following situation:
https://github.com/Project-MONAI/tutorials/issues/564
So I had to manually write a simple list on the main process to collect the evaluation results and then do the average code. And that works in most cases, except this one.

**Comment by awaelchli** [comment]
Hey @834799106 

> Its evaluation module actually contains the code that sends the results to the buffer during multi-process evaluation and then collects them in the main process once.

Could you point us to that code? What Lite settings are you using? Is the strategy ddp or ddp_spawn? Do you want to evaluate once after the training finishes or every epoch?

**Comment by 834799106** [comment]
Hi @awaelchli 
that codes are on https://github.com/Project-MONAI/MONAI/blob/816f413a1e101e317f865533ae9212b2f2bb0b71/monai/metrics/meandice.py#L23
My Lite settings are 
`lite = trainer(strategy='ddp', accelerator="gpu", devices=args.gpu_num,precision=16)`
`lite.run(args)`
and I want to evaluate every epoch.
