### ISSUE TITLE
Tests should only run if module available; Skip if not

### ISSUE THREAD

**Issue by krshrimali** [PyTorchLightning/pytorch-lightning#12058]
## Proposed refactor

Currently, the tests attempt to run even if specific modules are not available. Though they give a `None object is not callable` error, it can still be noise for the developer. IMO, these tests should instead be skipped. (only for external modules like `scikit-learn`)

I could only find a single example of this, but to prevent this in the future - it will be nice to use `@RunIf(_SKLEARN_AVAILABLE)` or `unittest.skipIf(not _SKLEARN_AVAILABLE, "scikit-learn required")` like usage. (please see `Motivation` section for example)

### Motivation

If `scikit-learn` is not available/installed, `make_classification` is set to `None`:

https://github.com/PyTorchLightning/pytorch-lightning/blob/550d3a640d1bfeb731a16b2996d3160f0f7eb071/tests/helpers/datamodules.py#L23-L30

Which when called here will raise an error:

https://github.com/PyTorchLightning/pytorch-lightning/blob/550d3a640d1bfeb731a16b2996d3160f0f7eb071/tests/helpers/datamodules.py#L103-L108

### Pitch

The methods/functions can be wrapped with `unittest.skipIf` decorator, PyTorch does it like this:

https://github.com/pytorch/pytorch/blob/299b40de50d2ab3325b6bd77db6eacb9874813b1/test/test_unary_ufuncs.py#L586

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @justusschock @awaelchli @rohitgr7 @borda @akihironitta @carmocca @kaushikb11

**Comment by rohitgr7** [comment]
good observation.
we already have scikit-learn under `test.txt` as a requirement, so maybe we could do the opposite and remove the check and always assume that scikit-learn is there if someone's running the test suite? just a suggestion though.

**Comment by carmocca** [comment]
I agree with @krshrimali. We will always install sklearn in our CI, but skipping the tests if it's not available would be a better experience for new contributors.

The solution is very simple, we just need to add

```python
    def __init__(self, ...):
        if not _SKLEARN_AVAILABLE:
            pytest.skip("`sklearn` is not available.")
```

to the `__init__`s of `SklearnDataModule`, `ClassifDataModule`, and `RegressDataModule`
