### ISSUE TITLE
Datamodule's hparams should be saved inside checkpoint

### ISSUE THREAD

**Issue by rohitgr7** [PyTorchLightning/pytorch-lightning#12062]
## 🚀 Feature

LDM supports `save_hyperparameters` method just like LM.
https://github.com/PyTorchLightning/pytorch-lightning/blob/1ef34c5ffd20a42c687682798eb7db9b1dbcdb05/pytorch_lightning/core/datamodule.py#L26

but during checkpointing, only `model.hparams` are saved.
https://github.com/PyTorchLightning/pytorch-lightning/blob/1ef34c5ffd20a42c687682798eb7db9b1dbcdb05/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L365-L374

### Motivation

A user can have data specific hparams, like batch_size, image_size for transforms etc...
There can be cases where these hparams are required again, for eg in case of transfer learning/fine-tuning and user might be able to reload the hparams used while pre-training, without remembering what hparams were used during init, if they are saved inside the checkpoint.

Moreover, if we support this, we can possibly introduce `LDM.load_from_checkpoint` method just like we have in LM.

### Pitch

2 possible ways we can save LDM hparams:
1. Inject the LDM hparams inside model hparams, just like we do with `logger.log_hyperparams`
https://github.com/PyTorchLightning/pytorch-lightning/blob/1ef34c5ffd20a42c687682798eb7db9b1dbcdb05/pytorch_lightning/trainer/trainer.py#L1273
2. Create separate keys for each i.e. change `hyper_parameters` to `model_hyper_parameters` and add another `datamodule_hyper_parameters`.

### Alternatives

One can use `on_save_checkpoint/on_load_checkpoint` to reload the hparams, but this is slightly inconsistent with what we have within LM.

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @carmocca @awaelchli @ananthsub @ninginthecloud @jjenniferdai @rohitgr7

**Comment by carmocca** [comment]
Another alternative: use the `LightningCLI` and forget about hparams in your classes! 🎉
