### ISSUE TITLE
`TypeError`: __init__() got an unexpected keyword argument `'distributed_backend'`

### ISSUE THREAD

**Issue by hassiahk** [PyTorchLightning/pytorch-lightning#12070]
## 🐛 Bug

When initializing a `Trainer` object, I am getting a similar error but at different places with different pytorch-lightning versions.

**`pytorch-lightning = 1.5.10`**, installed using `pip install pytorch-lightning`:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 38, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'distributed_backend'
```

**`pytorch-lightning = 1.6.0dev`**, installed using `pip install git+https://github.com/PyTorchLightning/pytorch-lightning`:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/argparse.py", line 338, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'distributed_backend'
```

### Expected behavior
As I understood that `distributed_backend` had been removed in 1.5.0, this error should not have popped up.

### Environment

- PyTorch Lightning Version (e.g., 1.5.0): 1.5.10, 1.6.0dev
- PyTorch Version (e.g., 1.10): 1.10.0+cu111
- Python version (e.g., 3.9): 3.7
- OS (e.g., Linux): Linux
- CUDA/cuDNN version: 11.2

### Additional context

I am running the above mentioned commands and my script in Google Colab.

My `Trainer` object:
```
trainer = pytorch_lightning.Trainer(
	num_sanity_val_steps=2,
	gradient_clip_val=hparams.max_grad_norm,
	callbacks=[RunValidationOnStart()],
	checkpoint_callback=ModelCheckpoint(
		save_top_k=3,
		save_last=True,
		mode="min" if "acc" not in hparams.metric_to_track else "max",
		monitor=hparams.metric_to_track,
		dirpath=model.hparams.hparams_dir,
		filename="{epoch}",
		verbose=True,
	),
	logger=logger,
	max_epochs=hparams.max_epochs,
	gpus=hparams.gpus,
	distributed_backend="dp",
	limit_val_batches=hparams.limit_val_batches,
	limit_train_batches=hparams.limit_train_batches,
	limit_test_batches=hparams.limit_test_batches,
	check_val_every_n_epoch=hparams.check_val_every_n_epoch,
	profiler=SimpleProfiler(),
	accumulate_grad_batches=hparams.accumulate_grad_batches,
	reload_dataloaders_every_epoch=True,
	resume_from_checkpoint=hparams.resume_from_checkpoint,
)
```

**Comment by rohitgr7** [comment]
the deprecation cycle which is around 6 months is followed for each deprecated argument. So this must have been deprecated in v1.3 and was removed in v1.6.

you can instead use `strategy='dp'`.

**Comment by hassiahk** [comment]
Ah, my bad. I was trying to run someone else's code and overlooked that `distributed_backend` was defined in `Trainer` object. Thanks!

I am closing the issue now.
