### ISSUE TITLE
How to save checkpoints within lightning_logs?

### ISSUE THREAD

**Issue by polars05** [PyTorchLightning/pytorch-lightning#1207]
I'm currently doing checkpointing as follows:
```
checkpoint_callback = pl.callbacks.ModelCheckpoint(
          filepath=os.path.join(os.getcwd(), 'checkpoints/{epoch}-{val_loss:.2f}'),
          verbose=True,
          monitor='val_loss', 
          mode='min', 
          save_top_k=-1,
          period=1
      )

 
  trainer = pl.Trainer(
      default_save_path=os.path.join(os.getcwd(), 'log_files_are_stored_here'),
      gpus=1,
      max_epochs=2
      checkpoint_callback=checkpoint_callback
  )  
```
This creates the following folder structure:
```
├── checkpoints # all the .pth files are saved here
└── log_files_are_stored_here
    └── lightning_logs 
       ├── version_0
       ├── version_1
       ├── version_2
```
How can I get the .pth files for each version to be saved in the respective version folders like so?:
```
└── log_files_are_stored_here
    └── lightning_logs 
       ├── version_0
            └── checkpoints #  save the .pth files here
       ├── version_1
            └── checkpoints #  save the .pth files here
       ├── version_2
            └── checkpoints #  save the .pth files here
```

**Comment by chris-clem** [comment]
Hi,

this is how I do it:

```python
tt_logger = TestTubeLogger(save_dir=str(log_dir / "tt_logs"), name=run_name)

checkpoint_dir = (
    Path(tt_logger.save_dir)
    / tt_logger.experiment.name
    / f"version_{tt_logger.experiment.version}"
    / "checkpoints"
)
filepath = checkpoint_dir / "{epoch}-{val_loss:.4f}"
checkpoint_cb = ModelCheckpoint(filepath=str(filepath))

trainer = pl.Trainer(
        logger=tt_logger,
        checkpoint_callback=checkpoint_cb,
        ...
    )
```

**Comment by oplatek** [comment]
Hi, the TensorBoard version inspired by @chris-clem snippet.

Any idea how to get rid of the "HACK"?

```
tb_logger = TensorBoardLogger(save_dir='logs/tb/')

# HACK: tb_logger crashes in self._get_next_version() if I access tb_logger.log_dir
os.makedirs(f'logs/tb/default', exist_ok=True) 

mcp =  ModelCheckpoint(filepath=f'{tb_logger.log_dir}/' + '{epoch}_vl_{val_loss:.2f}')
trainer = Trainer(logger=tb_logger, checkpoint_callback=mcp) 
...
```

**Comment by vedal** [comment]
@Borda Could we re-open this?
I still cannot find any method of storing checkpoints along with logs when logs are versioned with "version_i". It would be really handy to have the structure @polars05 proposed as default. 

Maybe a solution is to enable passing the parameter TensorboardLogger.name through the trainer along with ?

**Comment by vedal** [comment]
@Borda Thank you
Another auto-closed issue which seems to access the exact log dir (including version:
https://github.com/Lightning-AI/lightning/issues/2409

**Comment by vedal** [comment]
My bad, there seems to already be a way to do this:
if using `ModelCheckpoint` and `TensorboardLogger`, then setting the `TensorboardLogger.save_dir` does what @polars05 suggested. 

For reference, this is how to set this in a .yaml for LightningCLI
```yaml
directory: my/output/dir
trainer:
    #default_root_dir: 
    callbacks:
    - class_path: ModelCheckpoint # short-hand notation
      init_args:
        #dirpath: checkpoints
    logger:
        class_path: pytorch_lightning.loggers.TensorBoardLogger
        init_args:
            save_dir: ${directory}
            name: some_experiment_name

```

That is: 
1. leave `Trainer.default_root_dir` as default
2. leave `ModelCheckpoint.dir_path` as default
3. set `TensorBoardLogger.save_dir` to the desired 

I suggest that this should be specified in the documentation for `Trainer.default_root_dir.`

We can close this issue now, and I'll report it in https://github.com/Lightning-AI/lightning/issues/14188
