### ISSUE TITLE
Remove deprecated `AcceleratorConnector.parallel_devices`

### ISSUE THREAD

**Issue by DuYicong515** [PyTorchLightning/pytorch-lightning#12074]
## Proposed refactor

Remove the unused property `AcceleratorConnector.parallel_devices` 

https://github.com/PyTorchLightning/pytorch-lightning/blob/550d3a640d1bfeb731a16b2996d3160f0f7eb071/pytorch_lightning/trainer/connectors/accelerator_connector.py#L762-L764

### Alternative
```
parallel_devices = getattr(Trainer.strategy, "parallel_devices", [Trainer.strategy.root_device])
```

### Motivation

Remove unused [accelerator_connector properties](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/connectors/accelerator_connector.py#L758-L870) 

`AcceleratorConnector.parallel_devices` was not used within PytorchLightning anymore and this property were not meant to be public. `Trainer.strategy.parallel_devices` is preferred compared to `Trainer.accelerator_connector.parallel_devices`

### Pitch

Remove the property `AcceleratorConnector.parallel_devices`

### Additional context

No other usage, should be a safe remove

cc @justusschock @awaelchli @rohitgr7 @four4fish

**Comment by kaushikb11** [comment]
@DuYicong515 Could you elaborate why we should remove it? It is used at multiple places in AcceleratorConnector.

**Comment by DuYicong515** [comment]
Hi @kaushikb11, there was no `AcceleratorConnector.parallel_devices` used in existing code base. 

Within accelerator_connector.py it's using a private variable `_parallel_devices` instead. Externally I think it's preferred to access`Train.strategy.parallel_devices` to access `parallel_devices` when using `ParallelStrategy`

The issue was intended to stop it being a public property, `AcceleratorConnector._parallel_devices` should be kept within accelrator_connector.py, while `Trainer.strategy.parallel_devices` is preferred compared to `Trainer.accelerator_connector.parallel_devices`
