### ISSUE TITLE
Remove deprecated `AcceleratorConnector.device_type`

### ISSUE THREAD

**Issue by DuYicong515** [PyTorchLightning/pytorch-lightning#12077]
## Proposed refactor

Remove the property `AcceleratorConnector.device_type` and migrate its usage
https://github.com/PyTorchLightning/pytorch-lightning/blob/550d3a640d1bfeb731a16b2996d3160f0f7eb071/pytorch_lightning/trainer/connectors/accelerator_connector.py#L766-L775

### Motivation

Remove deprecated [accelerator_connector properties](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/connectors/accelerator_connector.py#L758-L870) and deprecate [Trainer properties](https://github.com/PyTorchLightning/pytorch-lightning/blob/8c07d8bf905e395bbd2142b5df7b185b8e936c41/pytorch_lightning/trainer/trainer.py#L1935-L1998) accordingly.

Remove the property `AcceleratorConnector.device_type`, which is not used

### Additional context

No other usage, should be a safe remove

cc @justusschock @awaelchli @rohitgr7 @four4fish

**Comment by carmocca** [comment]
In the linked PR, I see the property was not deprecated previously but just removed.

Was this discussed somewhere? Is the assumption that we don't deprecate connector properties? Or some other reasoning?

**Comment by four4fish** [comment]
> In the linked PR, I see the property was not deprecated previously but just removed.
> 
> Was this discussed somewhere? Is the assumption that we don't deprecate connector properties? Or some other reasoning?

@carmocca this is one of the follow ups in #11449, all these properties are not used anymore and can be removed. I think you already removed the trainer.device_type?

**Comment by carmocca** [comment]
> I think you already removed the trainer.device_type?

I did, but that was prefixed by `_`: #11992

Personally, I'm okay with removing this. Properties and attributes inside the connectors were never meant to be public. I just wanted to raise awareness about this.

**Comment by krshrimali** [comment]
Just did a quick google search, to see if anywhere in a blog/docs, anyone has used `device_type`, and found no relevant results. So looks like removal is safe, but just putting this question for someone who comes to this issue for context: What is the suggested alternate (if any)? If a user wants to know the device type of the `AcceleratorConnector` object, how should they do it now? (except `isinstance(obj, [CPU/GPU/TPU/IPU]Accelerator)`)

**Comment by DuYicong515** [comment]
@krshrimali Thanks for the suggestion! I feel getting the device_type string are not recommended now. (The _AcceleratorType is an internal enum instead). 

The best alternative is to check `isinstance(Trainer.acclerator, [CPU/GPU/TPU/IPU]Accelerator)` whenever they want to know the accelerator type they are using? I've added this alternative to the issue descriptions. 

Any other alternatives we should consider?

**Comment by krshrimali** [comment]
> @krshrimali Thanks for the suggestion! I feel getting the device_type string are not recommended now. (The _AcceleratorType is an internal enum instead).
> 
> The best alternative is to check `isinstance(Trainer.acclerator, [CPU/GPU/TPU/IPU]Accelerator)` whenever they want to know the accelerator type they are using? I've added this alternative to the issue descriptions.
> 
> Any other alternatives we should consider?

Thanks for the response, I guess this is okay then. I didn't see any usage of `device_type` as such, so this is fine. Thank you!

**Comment by four4fish** [comment]
> > I think you already removed the trainer.device_type?
> 
> I did, but that was prefixed by `_`: #11992
> 
> Personally, I'm okay with removing this. Properties and attributes inside the connectors were never meant to be public. I just wanted to raise awareness about this.

Thanks for the hands up, we have a bunch of properties in accl_conn can be removed like this. The trainer._accelerator_connector is already private, I think it's safe to remove properties in it directly?
