### ISSUE TITLE
Remove `AcceleratorConnector.num_nodes`

### ISSUE THREAD

**Issue by DuYicong515** [PyTorchLightning/pytorch-lightning#12082]
## Proposed refactor
Remove the property `AcceleratorConnector.num_nodes` and migrate its usage
https://github.com/PyTorchLightning/pytorch-lightning/blob/a8ee5cacb7b31064c8b73372ca944d43f7caadc6/pytorch_lightning/trainer/connectors/accelerator_connector.py#L777-L779

### Motivation

`AcceleratorConnector.num_nodes` was only used on `Trainer.num_nodes` and this property were not meant to be public. 
`Trainer.num_nodes` is preferred to return the property from its strategy using `getattr(Trainer.strategy, "num_nodes", 1)` compared to access its accelerator_connector. 
 
After the property removal `Trainer.num_nodes` is the alternative of accessing `num_nodes`

### Pitch
https://github.com/PyTorchLightning/pytorch-lightning/blob/a8ee5cacb7b31064c8b73372ca944d43f7caadc6/pytorch_lightning/trainer/trainer.py#L2015-L2017

```
@property
def num_nodes(self) -> int:
    getattr(self.strategy, "num_nodes", 1):
```

cc @justusschock @awaelchli @rohitgr7 @four4fish

**Comment by ananthsub** [comment]
do we need to deprecate `num_nodes` off the trainer? given it's a constructor argument to the Trainer, this is very convenient for users.

fully agreed with removing the duplicated property from the accelerator connector though

**Comment by four4fish** [comment]
Yeah, my bad, I think let's keep this as well.
I think for trainer, let's have device_ids and num_nodes, num_devices(optional) and deprecate the rest

**Comment by DuYicong515** [comment]
Thanks for the comments! Make sense. I updated the title and descriptions -- will remove `Accelerator.num_nodes` only and migrate its usage on `Trainer.num_nodes`

**Comment by DuYicong515** [comment]
How about `Trainer.num_processes`, it's also a constructor argument to the Trainer, do we want to keep that as well in addition to `device_ids `, `num_nodes`?
cc @four4fish @ananthsub

**Comment by four4fish** [comment]
> How about `Trainer.num_processes`, it's also a constructor argument to the Trainer, do we want to keep that as well in addition to `device_ids `, `num_nodes`? cc @four4fish @ananthsub

No, num_processes should be deprecated.

**Comment by DuYicong515** [comment]
Good to know! Thanks @four4fish!
