### ISSUE TITLE
BUG: You requested GPUs: [0] But your machine only has: []

### ISSUE THREAD

**Issue by djahdkjqbwfkb1213** [PyTorchLightning/pytorch-lightning#12087]
## 🐛 Bug

I have the problem as follows:
```
pytorch_lightning.utilities.exceptions.MisconfigurationException: You requested GPUs: [0] But your machine only has: []
python3.7
```
![image](https://user-images.githubusercontent.com/46812006/155485567-0491fd7b-d992-4528-8814-54847d579b31.png)

```
print(torch.cuda.device_count()) 0
torch.cuda.is_available() False
```
Thank u for your help!

**Comment by kaushikb11** [comment]
> print(torch.cuda.device_count()) 0
torch.cuda.is_available() False

@djahdkjqbwfkb1213 As you pointed out, GPUs doesn't seem to be available on your system.

**Comment by djahdkjqbwfkb1213** [comment]
> > print(torch.cuda.device_count()) 0
> > torch.cuda.is_available() False
> 
> @djahdkjqbwfkb1213 As you pointed out, GPUs doesn't seem to be available on your system.

yes, and I want to find how to fix it up.
I'm trying to change the environment to py3.8 cuda11.3

**Comment by djahdkjqbwfkb1213** [comment]
> > print(torch.cuda.device_count()) 0
> > torch.cuda.is_available() False
> 
> @djahdkjqbwfkb1213 As you pointed out, GPUs doesn't seem to be available on your system.

it is still wrong (py3.8 cuda11.3)

**Comment by semaphore-egg** [comment]
Search for pytorch beginner's guide and setup a valid dl environment for `pytorch`.

Your problem has nothing to do with `pytorch-lightning`.

Make sure that `nvidia-smi` prints correct gpu information before trying anything related to `pytorch` or `pytorch-lightning`.
