### ISSUE TITLE
update docs to recommend __call__ for forward passes

### ISSUE THREAD

**Issue by jeremyjordan** [PyTorchLightning/pytorch-lightning#1209]
## 📚 Documentation

We should update the docs to recommend usage of `self(x)` for calculating the forward pass rather than `self.forward(x)`. Calling `forward()` directly can cause issues when you're using PyTorch model hooks (eg. see the additional logic in [`nn.Module.__call__`](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L540)).

Although most people don't play around with hooks and using `self.forward()` will work fine for them, we should probably follow the best practice (as I understand) of using `__call__` for calculating forward passes.

Related issues: #632

**Comment by awaelchli** [comment]
Very good idea! Then the examples should also be updated I guess?

**Comment by jeremyjordan** [comment]
yes! we should update:

- [ ] docs pages
- [ ] lightning examples
- [ ] colab notebooks

i'm happy to tackle the first two, i think @williamFalcon  is planning to do the third. will link to a WIP PR soon.

**Comment by williamFalcon** [comment]
@jeremyjordan i'll do colabs!
