### ISSUE TITLE
Add multiple dataloaders documentation to "common use cases"

### ISSUE THREAD

**Issue by lext** [PyTorchLightning/pytorch-lightning#1210]
## 🚀 Feature

Currently, only one train/val loader is supported by pytorch lightning. I would like to help with this and I could implement this feature.

### Motivation
Many methods for semi-supervised learning need several dataloaders. E.g. you want to sample one batch of labeled data and 2 batches of unlabeled data. 

### Pitch
I think that the following API modification of the will be ok:

1. `pl.LightningModule.train_dataloader` should return either one loader, or a dict of loaders
2. `pl.LightningModule` needs to support a sampling config and a data sampling hook
3. `pl.LightningModule.train_step` API will be unchanged for 1 loader, but in case if there is a dict of loaders, it will receive a dict of batches, where a key would correspond to the dataset name.

Example:
```
class MyModule(pl.LightningModule):
    def __init__(self):
        ... 
    def sample_batches(self):
        return {'labeled_data': 2, 'unlabeled_data':1}

    def train_dataloader(self):
        ...
        return {'labeled_data': labeled_loader, 'unlabeled_data': unlabeled_loader}

    def train_step(self, batch, batch_idx):
        labeled = batch['labeled_data'] # has two batches of data!
        unlabeled = batch['unlabeled_data']
        loss_val = 0
        for batch_l in labeled:
            out = self.model(batch_l['images'])
            loss_val += self.loss(out, batch_l['targets'])
        ...
```

### Alternatives
Can't think of any alternative with a clean code.

**Comment by lext** [comment]
I will also note that with my team we have previously tried such design and seems to be very convenient: https://github.com/MIPT-Oulu/Collagen/blob/master/collagen/data/_dataprovider.py

**Comment by Borda** [comment]
We already had a similar discussion here #1089

**Comment by lext** [comment]
@Borda thanks for pointing out!

**Comment by williamFalcon** [comment]
@Borda can you make add a "multiple dataloaders" section to the docs under the "common use cases" ?

**Comment by Borda** [comment]
done in #1416
