### ISSUE TITLE
Will pytorch lightning intruduce a significant performance effect?

### ISSUE THREAD

**Issue by shenmishajing** [PyTorchLightning/pytorch-lightning#12115]
## 🐛 Bug

I try to run mmdet models with pytorch lightning, and I use an adapter like [icevision](https://github.com/airctic/icevision/blob/4f68a87baa6651766f406b7cc9bf8d377dc98d20/icevision/models/mmdet/lightning/model_adapter.py) to run mmdet detectors in pytorch lightning. You can find all my code from [here](https://github.com/shenmishajing/pytorch_lightning_performence_issue).

I find the pytorch lightning version mmdet is more slow and will occupy more momery than the raw version, or rather about two times.

On a single 3090, a faster rcnn run on coco dataset with batch size = 4. The pytorch lightning version will occupy almost all momery of 3090, while the raw version only use about 10G momery, as follow.

- 1 is pytorch lightning version and 3 is raw version, typically, the gpu utilization ratio of pytorch lightning version is lower than raw version
<img width="859" alt="截屏2022-02-25 19 58 40" src="https://user-images.githubusercontent.com/32559715/155714785-0f5ded73-1aa1-4d15-9147-70ecd854e256.png">
Meanwhile, the pytorch lightning version will have about 1.4 it/s, and the raw version is 2.55 it/s, as follow.

- pytorch lightning version
<img width="1439" alt="截屏2022-02-25 19 55 51" src="https://user-images.githubusercontent.com/32559715/155714662-8aa2dc8b-fc17-44ee-8fef-c885de2599b5.png">

- raw version
<img width="1441" alt="截屏2022-02-25 19 58 32" src="https://user-images.githubusercontent.com/32559715/155714682-b0baa67c-6c59-48e2-94c3-a19f437bdee6.png">

When I set batch size to 8 of raw version(pytorch lightning version will oom with bs=8), it will have a speed as 1.28 it/s, and use momery as pytorch lightning version.

<img width="1438" alt="截屏2022-02-25 19 55 43" src="https://user-images.githubusercontent.com/32559715/155715127-6b0afb06-141e-4281-b39c-3f7ed589fe27.png">

- 1 is pytorch lightning version and 3 is raw version.  The gpu utilization ratio of pytorch lightning version never reach 100%, but raw version often.

<img width="891" alt="截屏2022-02-25 19 56 04" src="https://user-images.githubusercontent.com/32559715/155716167-142e0027-bc4f-4581-b8e5-3b42e2a78591.png">

In my adapter, I just accpet a mmdet detector inited by pytorch lightning cli.

https://github.com/shenmishajing/pytorch_lightning_performence_issue/blob/e65b6b7be7d1c500c02a4f2a2f5282609ef46cc9/models/mmdet_adapter.py#L22-L33

In training_step, I just give the batch to self.modal.train_step.

https://github.com/shenmishajing/pytorch_lightning_performence_issue/blob/e65b6b7be7d1c500c02a4f2a2f5282609ef46cc9/models/mmdet_adapter.py#L50-L53

All other thing like logs already have been removed, but the pytorch lightning version still is suffered from such a huge performence effect. Is it caused by pytorch lightning? Any idea about the huge difference between this two version?

### To Reproduce

You can get all code from this [repo](https://github.com/shenmishajing/pytorch_lightning_performence_issue)

### Environment
* CUDA:
        - GPU:
                - GeForce RTX 3090
                - GeForce RTX 3090
                - GeForce RTX 2080 Ti
                - GeForce RTX 3090
                - GeForce RTX 2080 Ti
                - GeForce RTX 3090
                - GeForce RTX 3090
        - available:         True
        - version:           11.1
* Packages:
        - numpy:             1.22.2
        - pyTorch_debug:     False
        - pyTorch_version:   1.9.0+cu111
        - pytorch-lightning: 1.5.10
        - tqdm:              4.62.3
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.9.7
        - version:           #202001120738 SMP Sun Jan 12 12:40:39 UTC 2020
### Additional context
If you want to compare the speed of mmdet and the pytorch lightning version, you may need the rich progress bar run in mmdet. You can get the file from [here](https://github.com/shenmishajing/pytorch_lightning_performence_issue/blob/main/utils/rich_progress_bar_hook.py), add this hook in log config in mmdet and remove the default text log. The code will look like
```python
log_config = dict(
    interval = 50,
    hooks = [dict(type = 'RichProgressBarHook')])
```

cc @borda @akihironitta

**Comment by shenmishajing** [comment]
I use the profilers prodived by pytorch lightning to debug this, but I do not find any bottle neck like data load etc. You can get the profiling result from [here](https://github.com/shenmishajing/pytorch_lightning_performence_issue/tree/main/results/profiling) now.

For convenience, I put the simple profiling result below.
![截屏2022-02-28 11 18 07](https://user-images.githubusercontent.com/32559715/155918462-4ea21640-c137-412b-9f7a-69f7d3cc1fad.png)
The train forward and backward take almost 75% time, loading data only takes 2%. But, the modal of two version is same, I don't know why there is such a significant performance difference. Did pytorch lightning do something in model.forward()?

**Comment by rohitgr7** [comment]
hey @shenmishajing !

A few questions here:
1. how many GPUs are you running your training on? in both cases?
2. are you using DDP in the raw version too? if yes, can you share that code snippet/link?

**Comment by shenmishajing** [comment]
> hey @shenmishajing !
> 
> A few questions here:
> 
> 1. how many GPUs are you running your training on? in both cases?
> 2. are you using DDP in the raw version too? if yes, can you share that code snippet/link?

1. just one gpu for both case
2. no, I just use the offical script to train modal, like `python tools/train.py path/to/config.py`.  I forget this, and sorry for that.

So, it is the ddp which introduce such a significant performance effect? If yes, how can I avoid this in pytorch lightning? just remove the `strategy: ddp_find_unused_parameters_false` config will get it?

Thanks for your reply very much, I will try to rerun this experiment without strategy config.

**Comment by shenmishajing** [comment]
@rohitgr7 hi, I have tried set the `strategy` to null in config file and rerun this experiment, but it do not fix this.

I only a very midly speed increment indeed, it's still about 1.45it/s. I think it's just some fluctuation.
![截屏2022-03-01 13 35 47](https://user-images.githubusercontent.com/32559715/156111235-f613142c-c5ce-4f76-a7e7-870d45277804.png)

**Comment by shenmishajing** [comment]
During the training of pytorch lightning version, the gpu utilization ratio change ups and downs, from 0~3% up to about 75% and down to 0~3% again. I think there is some bottle neck causing this, but I can't find it. Any one want to give a help?

**Comment by shenmishajing** [comment]
> I saw you selected gpus=-1 in your config, so in that case, I think lightning enables either ddp or ddp_spawn.

OK, I will try to set `strategy` to `null` and set `gpus=0` and rerun this experiment.

> possibly data loading might be a bottleneck here.

But, in my profiling result like [here](https://github.com/shenmishajing/pytorch_lightning_performence_issue/blob/main/results/profiling/simple/fit-epoch_3_batch_100.txt), loading data only take about 1% time. I do no think the bottle neck is loading data.

**Comment by shenmishajing** [comment]
> well, if both are running on a single device and data loading is not a bottleneck, it's really hard to tell here what could be the issue here. But ideally, they should run with similar it/s.

@rohitgr7 yes...It has confused me servel days, but I still can not figure out why there is such a huge difference.

Have you tried to reproduced this experiment? or Can you spend some time reproducing this experiment? I want to check whether there is some drive version or some hardware related bug causing this. Thanks for your help again.

**Comment by rohitgr7** [comment]
I can try it next week.

**Comment by shenmishajing** [comment]
Thanks for your help, and I'm glad to wait for good news from you. I will try to figure this out, too.

**Comment by rohitgr7** [comment]
just for a sanity check, can you ensure `DataLoader(num_workers=?)` is the same in both cases?

**Comment by shenmishajing** [comment]
yes, I set batch_size=num_workers=4 in both cases.
You can get pytorch lightning version config here
https://github.com/shenmishajing/pytorch_lightning_performence_issue/blob/b976a7e8bcb68a5b6e5f28ae48f27236632eeab8/configs/faster_rcnn.yaml#L197-L201
https://github.com/shenmishajing/pytorch_lightning_performence_issue/blob/b976a7e8bcb68a5b6e5f28ae48f27236632eeab8/datasets/mmdataset_adapter.py#L40-L41
and mmdet version
<img width="695" alt="截屏2022-03-02 19 09 05" src="https://user-images.githubusercontent.com/32559715/156350549-655c24f4-4737-4c61-a917-b20b5489b3fb.png">

**Comment by shenmishajing** [comment]
I will add a script to reproduce the mmdet version to [repo](https://github.com/shenmishajing/pytorch_lightning_performence_issue) later.

**Comment by shenmishajing** [comment]
Hi everyone, I have add the mmdet version script in [repo](https://github.com/shenmishajing/pytorch_lightning_performence_issue). We can reproduce the both case, now.

But be careful with the rich progress bar running in mmdet. Unlike pytorch lightning, the hook of mmdet can not be call at teardown or ctrl-c, so the rich progress bar will not be stopped when we use ctrl-c to kill the runnning process.

Please follow the known issue section if you get in trouble. Also, I'm glad if someone want to fix this issue.

**Comment by shenmishajing** [comment]
@rohitgr7 Hi, do you find something related to this issue? Can we solve this?

**Comment by rohitgr7** [comment]
sorry, totally slipped my mind.
will try it this week

**Comment by rohitgr7** [comment]
hey, @shenmishajing!
are you on slack? if not you can join it using: https://join.slack.com/t/pytorch-lightning/shared_invite/zt-12iz3cds1-uyyyBYJLiaL2bqVmMN7n~A

we can discuss it there. I am facing issues while installing dependencies and reproducing it.

**Comment by shenmishajing** [comment]
Hi, I have join it now. But I do not find your message or problem issue, can you give me a link?

**Comment by rohitgr7** [comment]
> @rohitgr7 Hi, I have join it now. But I do not find your message or problem issue, can you give me a link?

hey @shenmishajing what's your username on slack? mine is just `Rohit`. Can you ping me? I'll share the issues.

**Comment by shenmishajing** [comment]
@rohitgr7 Hi, my name on slack in 神秘鲨鲸. I have find someone named `Rohit` on slack and send a message to him. Is that you?

**Comment by rohitgr7** [comment]
after some investigation:

native pytorch 1 epoch: 25 min
Pytorch lightning 1 epoch: ~26-27 min


Updates that I made:
1. Turn off `detect_anomaly` in [faster_rcnn_pytorch_lightning.yaml](https://github.com/shenmishajing/pytorch_lightning_performence_issue/blob/8236aaa26a1278d1ccead8ec716ef5be60a0791e/configs/faster_rcnn_pytorch_lightning.yaml#L29).
2. Replace the [collate_fn](https://github.com/shenmishajing/pytorch_lightning_performence_issue/blob/8236aaa26a1278d1ccead8ec716ef5be60a0791e/datasets/mmdataset_adapter.py#L54) with `mmcv.parallel.collate` with `samples_per_gpu=batch_size`, just like it is done in original implementation.
3. Used `mmcv.parallel.MMDataParallel` to handle the `DataContainer` inputs produced by the above collate.

Observations:
1. Point 1 gave a huge boost [as expected](https://pytorch-lightning.readthedocs.io/en/latest/common/debugging.html#detect-anomaly).
2. Points 2 and 3 didn't help much, as expected.
3. Don't trust the `it/s` displayed in the tqdm of original implementation since that accounts only for how much time does it take for batch to pass through the model and not for how much time is spent while preparing the batch (which is significant), which is not the case with Lightning since it accounts everything that happened on that batch including batch preparation.

**Comment by shenmishajing** [comment]
Thanks for your help very much, I have got a huge boost and almost speed of mmdet version by disable `detect_anomaly`.

But, can you explain more detailly about the `it/s` displayed in mmdet? the progress bar has been updated every iter as
https://github.com/open-mmlab/mmcv/blob/25602c68441d18430d649711a4f3bec576ce327e/mmcv/runner/epoch_based_runner.py#L47-L52
So, i think it is same as tqdm in pytorch lightning. Why they are  different with batch preparation?

**Comment by rohitgr7** [comment]
> But, can you explain more detailly about the it/s displayed in mmdet?

can't say for sure, but when I turned off the model step, it stopped updating the tqdm progress bar altogether, even though I was iterating over the dataloader. But that might be happening due to something else, not sure, but at least the real issue is resolved here.

from next time, I'll surely check the trainer configuration first before going further, haha.... spent quite some time here to find the issue.

**Comment by shenmishajing** [comment]
Ok, I also think that might be happening due to something else. Thanks so much for your work and help, again.
