### ISSUE TITLE
No memory being freed up when using torch.cuda.empty_cache()

### ISSUE THREAD

**Issue by NilsLusch** [PyTorchLightning/pytorch-lightning#12117]
## 🐛 Bug

When training multiple models after one another and deleting models no longer used. torch.cuda.empty_cache(), doesn't seem to free up any memory

### To Reproduce
train an arbitrary model on the GPU
del model
torch.cuda.empty_cache()

### Expected behavior

When the model is deleted and torch.cuda.empty_cache() is called, all memory currently taken up by the model and objects associated with it should be removed from memory

**Comment by semaphore-egg** [comment]
Probably not an issue related to lightning.

Consider:
1. The memory strategy might be very different in the non-interactive (scripts) and interactive (ipython, jupyter) mode. The interactive mode is likely to keep memory for longer time even after delete. 
2.  `nvidia-smi` can only shows the total amount of memory allocated for processes but can not tell the amount of used/reserved by a specific process. 

Following discussion 
[1 about interactive mode](https://stackoverflow.com/questions/63787404/why-the-cuda-memory-is-not-release-with-torch-cuda-empty-cache/66812053#66812053)
[2 about used/reserved/allocated](https://stackoverflow.com/questions/58216000/get-total-amount-of-free-gpu-memory-and-available-using-pytorch)
 might help you.
