### ISSUE TITLE
Add support for loading flattened meta_tags.csv

### ISSUE THREAD

**Issue by S-aiueo32** [PyTorchLightning/pytorch-lightning#1212]
### Motivation
PL+TensorBoard can log hierarchical dict after #1152, however, `meta_tags.csv` has been disabled by the change.

### Pitch
- Make `meta_tags.csv` back to a hierarchical dict based on their delimiter.

### Alternatives
62de7948634b1cd8c7e494f4cd9a02625cd3f602

### Additional context
1. We can consider the deprecation of `meta_tags.csv`, then adopt `config.yaml`.
1. We can interpret primitive-type parameters through the files, so it is needed to rethink parameter sanitization or update docs.

**Comment by williamFalcon** [comment]
can you elaborate on what the .yaml would look like? i kind of like the idea.
@luiscape

**Comment by S-aiueo32** [comment]
@williamFalcon thank you for replying.

Roughly, I plan to make the following change for tags_csv replacement with yaml: 
1. Replace [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/3be81cb54ebf2b5425cae09327e852bea0e7c492/pytorch_lightning/loggers/tensorboard.py#L143) with `yaml.dump()`. 
    ```python
    import yaml

    with open("config.yaml", "w") as wf:
        yaml.dump(self.tags, wf)
    ```
1. Create `load_hparams_from_yaml` like [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/3be81cb54ebf2b5425cae09327e852bea0e7c492/pytorch_lightning/core/saving.py#L39)
    ```python
    import yaml

    def load_hparams_from_yaml(config_yaml: str) -> Dict[str, Any]:
        if not os.path.isfile(config_yaml):
            log.warning(f'Missing Tags: {config_yaml}.')
            return {}

        with open(config_yaml) as f:
           tags = yaml.load(f, Loader=yaml.SafeLoader)

        return tags
    ```

**Comment by Borda** [comment]
I very much support replacing CSV by YAML it is much easier to read and handle (also comment)
