### ISSUE TITLE
Automatic Checkpointing not working

### ISSUE THREAD

**Issue by scrunguss** [PyTorchLightning/pytorch-lightning#12128]
## 🐛 Bug

checkpoints aren't created

### To Reproduce

clone https://github.com/scrunguss/DQNAgent then run:
`sudo docker build --tag learn`
`sudo docker run -it --rm -v $(pwd)/log:/log learn`
### Expected behavior
checkpoints should be created under `/log/default/version_x/checkpoints/`

### Environment
/home/scrungus/.local/lib/python3.9/site-packages/torchvision/io/image.py:11: UserWarning: Failed to load image Python extension: /home/scrungus/.local/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZNK3c106IValue23reportToTensorTypeErrorEv
  warn(f"Failed to load image Python extension: {e}")
* CUDA:
        - GPU:
        - available:         False
        - version:           10.2
* Packages:
        - numpy:             1.21.3
        - pyTorch_debug:     False
        - pyTorch_version:   1.8.1+cu102
        - pytorch-lightning: 1.5.10
        - tqdm:              4.62.3
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.9.5
        - version:           #55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022

- PyTorch Lightning Version (e.g., 1.5.0): 1.5.10
- PyTorch Version (e.g., 1.10):  1.8.1
- Python version (e.g., 3.9): 3.9.5
- OS (e.g., Linux): Ubuntu 
- CUDA/cuDNN version: NA
- GPU models and configuration: NA
- How you installed PyTorch (`conda`, `pip`, source): pip
- If compiling from source, the output of `torch.__config__.show()`:NA

cc @awaelchli @ananthsub @ninginthecloud @rohitgr7

**Comment by carmocca** [comment]
Hi! Can you describe the issue you are seeing with more detail?

Can you adapt this script https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report/bug_report_model.py to reproduce the issue?
