### ISSUE TITLE
Provide the reason associated with `should_stop` being True.

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#12139]
## 🚀 Feature

Currently, `should_stop` is False or True.

As a user, I would like to track why my training stopped and not have to parse my logs.

The Trainer should expose the reason and make it easily accessible.

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @carmocca @justusschock @ananthsub @ninginthecloud @rohitgr7

**Comment by carmocca** [comment]
Instead of exposing the reason through the `Trainer`, I think any time `should_stop` becomes True we should generate a log event with the reason.
