### ISSUE TITLE
can't get mnist tpu colab notebook to work with tpu

### ISSUE THREAD

**Issue by level14taken** [PyTorchLightning/pytorch-lightning#1214]
I ended up with following error when trying to run [mnist_colab](https://colab.research.google.com/drive/1-_LKx4HwAxl5M6xPJmqAAu444LTDQoa3) with tpu, 
```
Exception in device=TPU:4: [Errno 2] No such file or directory: '/content/lightning_logs/version_0/checkpoints/epoch=0.ckpt' Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 119, in _start_fn fn(gindex, *args)
```
I've restarted the session after lightning import
I've set the `num_tpu_cores=8`
any ideas on what should be done?

**Comment by level14taken** [comment]
@williamFalcon hey can you check this please

**Comment by jwallat** [comment]
Try adding a CheckpointCallback that actually saves checkpoints (save_top_k-parameter): 

`checkpoint_callback = ModelCheckpoint(
    filepath=args.decoder_model_dir,
    save_top_k=1,
    verbose=True,
    monitor='val_loss',
    mode='min',
    prefix=''
)`

and add it to your trainer: 
`Trainer(..., checkpoint_callback=checkpoint_callback)`

It did work for me this way. 
Also you might need to set precision to 32 bit as this seems to be broken right now (or at least has been last week ;) )

**Comment by Borda** [comment]
@jwallat good points, mind draft a PR with forcing 32 precision for TPU and stop trying to import missing checkpoint is there was not requested (no CheckPointing)?

**Comment by Borda** [comment]
Trying to get info about float16 support for pytorch TPU? @williamFalcon
for the record - https://discuss.pytorch.org/t/pytorch-tpu-support/25504/10

**Comment by williamFalcon** [comment]
lightning already supports tpu 16 bit @Borda

**Comment by Borda** [comment]
Feel free to reopen if the issue stays :robot:
