### ISSUE TITLE
Drop PyTorch 1.7 support

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#12161]
## Proposed refactor

With the release of PL 1.6, we will support PyTorch 1.8 to 1.11 (4 version window)

### Pitch

Do this in 2 steps:

1. Drop testing from CI (important before release)
2. Remove code for its support. (optional before release)
______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @carmocca @akihironitta @borda

**Comment by krshrimali** [comment]
Re-opening this since we are yet to drop PyTorch 1.7 from the code-base.

**Comment by carmocca** [comment]
Removing the milestone as this does not need to strictly happen before the release.
