### ISSUE TITLE
Model checkpoint loading compatibility with PyTorch Geometric lazy modules

### ISSUE THREAD

**Issue by rhjohnstone** [PyTorchLightning/pytorch-lightning#12173]
## 🚀 Feature

Update the `load_from_checkpoint` method to work with PyTorch Geometric's lazily-initialised modules, e.g. [Linear](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.dense.Linear).

### Motivation

The `load_from_checkpoint` method does not work with lazily-initialized modules, because the trained/initialized model now has definite weights, so the shapes don't match. See [this gist](https://gist.github.com/rhjohnstone/1b6c607f47241f25849778b4b35f83db) for an example.

### Pitch

I don't know enough about how `load_from_checkpoint` works, but if it could somehow check if it's trying to load a lazily-initialized module before trying to load it. I know PL can't be expected to create special tools for every library, but PyTorch Geometric is pretty much the standard for graph learning, and is continuing to gain popularity.

### Alternatives

As shown in the gist above, a checkpoint can still be loaded by creating a new instance, initializing, and then loading the weights, but it would be nice to be able to use the intentioned method.

cc @awaelchli @ananthsub @ninginthecloud @rohitgr7

**Comment by awaelchli** [comment]
@rhjohnstone Thanks for the feature request.
How would you expect Lightning to replicate this part of your code snippet:

```py
# 1)
loaded_model = LitModel()

# 2)
with torch.no_grad():
    out = loaded_model(init_batch.x)

# 3)
loaded_model.load_state_dict(state_dict)
```

The `load_from_checkpoint` function does 1) and 3). If I understand correctly, you are requesting that we do 2). Could we do this:

```py
with torch.no_grad():
    loaded_model(loaded_model.example_input_array)
```
if [example_input_array](https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.core.LightningModule.html#pytorch_lightning.core.LightningModule.example_input_array) is defined?
