### ISSUE TITLE
ModelCheckpoint deletes old checkpoints

### ISSUE THREAD

**Issue by gahdritz** [PyTorchLightning/pytorch-lightning#12170]
## 🐛 Bug

I'm using the ModelCheckpoint callback to save checkpoints every epoch. Every time it writes a new checkpoint, it appears to delete the previous one. The result at the end of training is one checkpoint with a name unique to the final checkpoint ("epoch=35-step=35999.ckpt").

### To Reproduce

I'm not doing anything fancy. I initialize the model checkpointing callback as follows:

```python
mc = ModelCheckpoint(
    every_n_epochs=1,
)
callbacks.append(mc)
```

And then pass it to the trainer:

```python
trainer = pl.Trainer.from_argparse_args(
    args,
    default_root_dir=args.output_dir,
    strategy=strategy,
    callbacks=callbacks,
    logger=loggers,
)
```

### Expected behavior

I expect one checkpoint to be saved (and not overridden) every epoch.

### Environment

* CUDA:
        - GPU:
                - NVIDIA A100-SXM4-40GB
        - available:         True
        - version:           11.3
* Packages:
        - numpy:             1.21.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.10.1+cu113
        - pytorch-lightning: 1.5.9
        - tqdm:              4.62.2
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                -
        - processor:         x86_64
        - python:            3.7.0
        - version:           #1 SMP Wed Dec 1 05:10:33 EST 2021

cc @borda @rohitgr7 @carmocca @awaelchli @ninginthecloud @jjenniferdai

**Comment by tshu-w** [comment]
You should change `save_top_k` to `-1`, see https://pytorch-lightning.readthedocs.io/en/stable/extensions/generated/pytorch_lightning.callbacks.ModelCheckpoint.html#pytorch_lightning.callbacks.ModelCheckpoint: 
```python
mc = ModelCheckpoint(
    every_n_epochs=1, save_top_k = -1
)
```

**Comment by tshu-w** [comment]
Sorry, I forgot it. But according to the doc if you don't not set a monitor, it saves a checkpoint only for the last epoch.

**Comment by ananthsub** [comment]
> I expect one checkpoint to be saved (and not overridden) every epoch.

I don't understand. After training is finished, do you want only one checkpoint overall, or one checkpoint per epoch?

**Comment by awaelchli** [comment]
You can also think of it this way: If no monitor is set, any checkpoint is considered the best one, and `every_n_epochs=x` means we check whether we have a better one every n epochs. 
So in that sense, save_top_k=1 as the default saving the latest one is a a reasonable choice. Also, we don't want to fill the disk with checkpoints by default.
