### ISSUE TITLE
Fix inconsistent function signatures in log_image 

### ISSUE THREAD

**Issue by chris-boson** [PyTorchLightning/pytorch-lightning#12183]
## 🚀 Feature
Make function signature of `log_image` self consistent.

### Motivation

WandB and Neptune loggers have inconsistent function signatures which means that it's not useful to call
`self.logger.log_image(...)` when both loggers are initialized, as it leads to unexpected arguments.
https://github.com/PyTorchLightning/pytorch-lightning/blob/5da065e287b44e2c1fe4f7951003813ed45365c9/pytorch_lightning/loggers/base.py#L272-L274

https://github.com/PyTorchLightning/pytorch-lightning/blob/5da065e287b44e2c1fe4f7951003813ed45365c9/pytorch_lightning/loggers/wandb.py#L417-L431

https://github.com/PyTorchLightning/pytorch-lightning/blob/5da065e287b44e2c1fe4f7951003813ed45365c9/pytorch_lightning/loggers/neptune.py#L655-L662

### Pitch

There should be a unique interface to `self.logger.log_image(...)` that handles any number of loggers.

### Alternatives

More general refactor of how images, histograms, plotly plots, html etc are logged.
See also discussion in https://github.com/PyTorchLightning/pytorch-lightning/issues/6720 https://github.com/PyTorchLightning/pytorch-lightning/issues/11232

### Additional context

cc @justusschock @awaelchli @rohitgr7 @edward-io @borda @ananthsub @kamil-kaczmarek @Raalsky @Blaizzy

**Comment by justusschock** [comment]
This already has been discussed in https://github.com/PyTorchLightning/pytorch-lightning/pull/9545#pullrequestreview-756058618 (and following comments) and there we found that the APIs were too different and the possibilities too different, to really unify them under one API.

**Comment by ananthsub** [comment]
See also https://github.com/PyTorchLightning/pytorch-lightning/issues/11837
These APIs have been removed from the base logger to avoid any such confusion

**Comment by chris-boson** [comment]
> This already has been discussed in [#9545 (review)](https://github.com/PyTorchLightning/pytorch-lightning/pull/9545#pullrequestreview-756058618) (and following comments) and there we found that the APIs were too different and the possibilities too different, to really unify them under one API.

I think there is a case to be made to at least unify the basic functionality of logging a single image or plotly plot with a specific key and step. I don't think it needs to generalize advanced logging functionality as mentioned in https://github.com/PyTorchLightning/pytorch-lightning/issues/6720#issuecomment-811562472.

**Comment by daniellepintz** [comment]
@chris-boson most loggers in Lightning don't offer a `log_image` method so what would you propose we do for those?

Also fyi the first code snippet in your issue has been deprecated along with all of LoggerCollection in https://github.com/PyTorchLightning/pytorch-lightning/issues/11232

**Comment by twsl** [comment]
Actually it seems, that almost all loggers support a way to log images.
This extends to other functions as well.

https://www.mlflow.org/docs/latest/_modules/mlflow/tracking/client.html#MlflowClient.log_image
https://www.comet.ml/docs/python-sdk/Experiment/#experimentlog_image
https://docs.wandb.ai/guides/track/log/media
https://docs.neptune.ai/you-should-know/what-can-you-log-and-display#images
https://www.tensorflow.org/tensorboard/image_summaries

I propose the following method definition:
```
def log_image(self, key: str, image: torch.Tensor, step: Optional[int] = None,  *args, **kwargs):
```

**Comment by chris-boson** [comment]
> I propose the following method definition:
> 
> ```
> def log_image(self, key: str, image: torch.Tensor, step: Optional[int] = None,  *args, **kwargs):
> ```
> 
> Also I'd like to use this opportunity to say that I'm not a fan of the deprecation of loggercollection as it allows an easy option to support multiple loggers at the same time without struggle

I would suggest to also allow other image formats such as
- a file-like object containing an image
- a numpy matrix
- a PIL Image
- a matplotlib Figure

**Comment by carmocca** [comment]
Considering the deprecation of `LoggerCollection` (#11232), standardizing the interface is not as relevant because users are meant to differentiate between logger instance types if multiple different logger classes are used.

We should try to keep the implementations of these as consistent as possible, but a unifying interface is a limiting requirement for the logger implementations.

Closing for these reasons. If there are specific suggestions or inconsistencies to address, you can continue the discussion here.

**Comment by twsl** [comment]
As already pointed out, im not a fan of the deprecation of the LoggerCollection and I think the advantages of a unified logging api outweight the extra work that has to be put into it. Please reopen the issue

**Comment by tshu-w** [comment]
@carmocca  I support @twsl, please consider reopen it.

**Comment by twsl** [comment]
> Any viewpoints that we might have missed are appreciated but discussions about that should go into that issue.

I can appreciate the changes introduced by that PR but think that the deprecation is unnecessary. I just want an easy way to log to multiple loggers and having a wrapper using the logger interface is an easy way to prevent writing additional boilerplate over and over for each logging call. That's an additional life of code for every logging call right now. There would be no harm in keeping it.

> Most logger implementations live in-tree but this is not a requirement. Users could have custom loggers that we don't know of.

There is nothing that prevents other users from having their own implementations, they could simply make a required method a fall-through and add their own methods to call. If there is no standardized interface, a user would have to know how to call it anyway.

> Unifying all of them is a huge constraint on the design and we don't have full visibility of what users might be defining as loggers. Additionally, PRs around these unifications were often blocked by nuances of each implementation. Having to update multiple classes when you want to add a feature for a specific logger became slow and limiting for authors.

This is definitely no easy task.
I believe, the initial logger interface was created based on available capabilities but these have been extended across loggers.
I dont get why you would stop at providing an interface, such calls could then easily be added to the `Trainer` as well.
If you don't unify the interface of a logger, you could simply use exposed raw client directly.
