### ISSUE TITLE
Add OmegaConf DictConfig support for Trainer args

### ISSUE THREAD

**Issue by Anjum48** [PyTorchLightning/pytorch-lightning#12201]
## 🚀 Feature

Certain Trainer args can be passed as a Python dict (e.g. `accumulate_grad_batches`). This fails if a `DictConfig` object is passed if the user is using Hydra or OmegaConf

### Motivation

If you are using Hydra or OmegaConf and passing training args using config objects like this:
```
trainer = pl.Trainer(**cfg.trainer)
```
An error will be thrown since the `isinstance(accumulate_grad_batches, dict)` check will fail

### Pitch

Change to `isinstance(accumulate_grad_batches, (dict, DictConfig))` in `callback_connector.py`. (There may be other args with a similar check)

### Alternatives

The above solution might fail if parts of the config are dynamic & not resolved. Maybe an additional internal function is needed to QC OmegaConf inputs are safe for PL?

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @justusschock @kaushikb11 @awaelchli @borda @rohitgr7

**Comment by ananthsub** [comment]
I don't think Lightning should specialize for a particular config system, in this case Omegaconf/Hydra. 
I think Hydra relies on MutableMapping for its DictConfig, so maybe it makes sense to change the isinstance check to rely on that instead of a Dict, given its a python primitive which doesn't add dependencies or significantly complicate the code structure. Would you be interested in trying this out and seeing if it works for you?

**Comment by Anjum48** [comment]
I think that's a great idea. Will test and get back to you
