### ISSUE TITLE
WandbLogger does not log test results

### ISSUE THREAD

**Issue by chris-clem** [PyTorchLightning/pytorch-lightning#1220]
## 🐛 Bug

The WandbLogger does not log test results when testing happens right after training.

### To Reproduce

When running the MNIST example with the WandbLogger like in the following snippet, the test results do not get logged to wandb because it syncs before testing starts:

#### Code sample
```python
    ...
    trainer = pl.Trainer(logger=WandbLogger(...))
    trainer.fit(model)
    trainer.test()
```

### Expected behavior

WandbLogger should also log the test results by default like TensorBoardLogger or TestTubeLogger to be a real alternative for the other loggers.

### Environment
```shell_script
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[conda] pytorch-lightning         0.7.1                    pypi_0    pypi
[conda] torch                     1.4.0                    pypi_0    pypi
[conda] torchvision               0.5.0                    pypi_0    pypi

```

**Comment by Borda** [comment]
@borisdayma @colehurwitz @calclavia pls ^^

**Comment by borisdayma** [comment]
@Borda I think it's due to the finalize method closing the run with wandb.join.

I'm not completely familiar with the typical use case but a possible solution would be to remove it from the callback.

**Comment by borisdayma** [comment]
@chris-clem can you confirm that [this proposed fix](https://github.com/PyTorchLightning/pytorch-lightning/issues/1116#issuecomment-599244414) solves the issue?

If so then related PR should fix it.

**Comment by Borda** [comment]
also discussed in #1116 and a fix in #1193
@borisdayma @chris-clem could you pls review it

**Comment by borisdayma** [comment]
The PR looks good to me!

**Comment by chris-clem** [comment]
The fix works, thanks!
