### ISSUE TITLE
Colab weird behaviour and error when passing values from collate_fn to validation_step

### ISSUE THREAD

**Issue by dumitrescustefan** [PyTorchLightning/pytorch-lightning#1221]
The same code that runs perfectly on my local machine (MacOS with Python3.7 and tested on an Ubuntu docker 18.04 with Python3.6.9) fails to run on colab.

It performs weirdly, calling the Dataset init() multiple times. However, it fails when the collate function that (correctly) returns (printed out the results) the following:
```
return x_tensor, x_lengths, y_tensor
```
get passed in the sanity check right at start in the ``validation_step``:
```
def validation_step(self, batch: tuple, batch_nb: int, *args, **kwargs) -> dict:
        x_tensor, x_lengths, y_tensor = batch <-- here it fails
        .. forward(x_tensor,x _lengths) .. etc.
```
with the error:
```
line 234, in validation_step
    x_tensor, x_lengths, y_tensor = batch
ValueError: too many values to unpack (expected 3)
```
it actually just return the first value (x_tensor). I tried packing them in a dict from the collate function, but in the validation step ``batch`` comes to me just as the first key (as string!) from the dict created in collate_fn.

The environment is the same except the Python version (latest torch and lightning versions) across local runtime, docker ubuntu and colab. To ensure the same code is running on all machines, I'm doing just git clone, pip3 install -r requirements and python3 train.py. Am I missing something with Colab that's just not working? I can provide full code if needed.

**Comment by williamFalcon** [comment]
Try running master?

**Comment by dumitrescustefan** [comment]
@williamFalcon 

Confirm that running on colab with version ``pytorch-lightning==0.7.2.dev0`` (from master directly) fixes the problem above. 

Thanks a lot!
