### ISSUE TITLE
Prefix log_metrics keys with class name in callbacks

### ISSUE THREAD

**Issue by pbsds** [PyTorchLightning/pytorch-lightning#12231]
**Problem:** `callbacks.DeviceStatsMonitor` spams tensorboard with 107 metrics under the very non-descript group labels "on_train_batch_end" and "on_train_batch_start". 

This convention composes very poorly with other callbacks. For this reason i propose moving to the the naming convention `CallbackClassName.hook_name` instead of just `hook_name`.

Basically, RFC on #12228, please.

cc @tchaton @justusschock @awaelchli @borda @ananthsub @daniellepintz @rohitgr7 @kaushikb11

**Comment by daniellepintz** [comment]
Makes sense to me!

**Comment by pbsds** [comment]
bleep bloop no stale
