### ISSUE TITLE
Strategy API is not exposed

### ISSUE THREAD

**Issue by robogast** [PyTorchLightning/pytorch-lightning#12270]
## 🐛 Bug

The strategies [docs](https://pytorch-lightning.readthedocs.io/en/latest/extensions/strategy.html#training-strategies-with-various-configs) imply using a Strategy object directly is valid syntax: `trainer = Trainer(strategy=DDPStrategy(...), accelerator="gpu", devices=4)` 

However, `strategies` is not part of the pytorch_lightning api:
```python
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytorch_lightning as pl
>>> pl.__version__
'1.5.10'
>>> dir(pl)
['Callback', 'LightningDataModule', 'LightningModule', 'Trainer', '_PACKAGE_ROOT', '_PROJECT_ROOT', '__about__', '__all__', '__author__', '__author_email__', '__builtins__', '__cached__', '__copyright__', '__doc__', '__docs__', '__file__', '__homepage__', '__license__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_logger', '_root_logger', 'accelerators', 'callbacks', 'core', 'loggers', 'logging', 'loops', 'os', 'overrides', 'plugins', 'profiler', 'seed_everything', 'trainer', 'tuner', 'utilities']
```

### To Reproduce
```python
>>> from pytorch_lightning import strategies
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'strategies' from 'pytorch_lightning' 
```

### Expected behavior
```python
>>> from pytorch_lightning import Trainer, strategies
>>> strategy = strategies.DDPStrategy(...)
>>> trainer = Trainer(strategy=strategy)
```
### Environment
- PyTorch Lightning Version (e.g., 1.5.0): 1.5.10
- PyTorch Version (e.g., 1.10): 1.10
- Python version (e.g., 3.9): 3.9
- OS (e.g., Linux): Linux
- CUDA/cuDNN version: 11.3.1/8.2.1.32
- GPU models and configuration: N/A
- How you installed PyTorch (`conda`, `pip`, source): conda

**Comment by akihironitta** [comment]
Yes, the Strategy API is only available in master, and it will be included in the v1.6 release.
