### ISSUE TITLE
Ability to Automatically Relaunch Jobs in LSF Environment

### ISSUE THREAD

**Issue by amorehead** [PyTorchLightning/pytorch-lightning#12279]
### Discussed in https://github.com/PyTorchLightning/pytorch-lightning/discussions/12278

<div type='discussions-op-text'>

<sup>Originally posted by **amorehead** March  9, 2022</sup>
Hello. I was reading through Lightning's documentation on the Slurm cluster environment, and I saw that it currently supports the ability to automatically requeue a running job after its time expires (e.g., SBATCH --signal=SIGUSR1@90). I was wondering if such a feature is also possible/available through the LSF cluster environment that Lightning currently supports.</div>

**Comment by zihaozou** [comment]
Hi, do you find a solution to relaunch the jobs on LSF?

**Comment by amorehead** [comment]
Hi, @zihaozou. Sadly, I have not yet. However, I will most likely be looking back into this in the near future, as I have a current project that could make use of such functionality within PyTorch Lightning.

**Comment by ShihengDuan** [comment]
The auto_requeue in SLURM environment is convenient. Would like to see if this is doable with LSF.
