### ISSUE TITLE
Log artifacts to an existing run ID in MLflow 

### ISSUE THREAD

**Issue by pedrety** [PyTorchLightning/pytorch-lightning#12287]
## 🚀 Feature

Right now you can't log artifact to an existing run in MLflow because you can only specify the experiment name and the desired run name you want to log artifacts to. This creates an issue where a new run is created instead of logging the data into an existing one. Also if you use ```mlflow.pytorch.autolog()``` and you want to log extra items into the current run it will create a new one because the ```MLflowLogger``` ([MLflowLogger.\_\_init\_\_](https://github.com/PyTorchLightning/pytorch-lightning/blob/d31126c3310af62d76ffb87368ae1e4cc5bbac93/pytorch_lightning/loggers/mlflow.py#L111)) can't be created specifying a run id.

### Motivation

I'm trying to log extra items into an existing run during the training and it will create a new MLflow run instead of logging them into an existing run (1). 

### Pitch

I just want to log new items into my existing run by specifying the current run id without creating new runs and having the information divided into 2 runs. 

### Additional context

(1) As you can see in this image 
![mlflow_pytorch](https://user-images.githubusercontent.com/17024367/157626165-60ce2c4b-254e-4764-83ed-2467eeb15cd1.png)

cc @borda

**Comment by awaelchli** [comment]
Hey @Kr4is @pedrety 

Great contribution. Just a heads up: Lightning 1.6 will soon get released. It's possible #12290 won't land in time. Thanks for the patience <3
