### ISSUE TITLE
deepspeed some config raise exception

### ISSUE THREAD

**Issue by GGGGGGXY** [PyTorchLightning/pytorch-lightning#12299]
I am pretty enjoy using Lightning. It's so convenient.

But also I meet somewhere inconvenient.

![image](https://user-images.githubusercontent.com/15215819/157861232-184cc988-8a57-4dad-a1fd-f8d57a637477.png)

when using Deepspeed autotuning feature, it will auto generate ds_config.json for the user.  The config contains gradient_accumulation_steps and also, this will pass through args.

And the code in lightning strategies/deepspeed.py:616

This will raise a exception.

I think this maybe could be a warning and the training can go on.

______________________________________________________________________

cc @SeanNaren @awaelchli @rohitgr7

**Comment by GGGGGGXY** [comment]
And maybe it can check. if the 'gradient_accumulation_steps' in config.json is not equal to args.accumulate_grad_batches. Then raise the exception

**Comment by rohitgr7** [comment]
in that case, does it tune the `gradient_accumulation_steps`? if so, will both of them be equal i.e the value inside the config and the one passed to the trainer?

**Comment by SeanNaren** [comment]
I don't think this can be a warning unfortunately, as Lightning relies heavily on knowing what this value is. As @rohitgr7 suggested, what would be the best approach is if you could pass this intro the trainer, i.e

```python
pl.Trainer(accumulate_grad_batches=x)
del ds_config['grad_accumulation_steps']
```

**Comment by GGGGGGXY** [comment]
> in that case, does it tune the `gradient_accumulation_steps`? if so, will both of them be equal i.e the value inside the config and the one passed to the trainer?

yes, the value inside the config and the one passed to the trainer, and they are equal

**Comment by GGGGGGXY** [comment]
> I don't think this can be a warning unfortunately, as Lightning relies heavily on knowing what this value is. As @rohitgr7 suggested, what would be the best approach is if you could pass this intro the trainer, i.e
> 
> ```python
> pl.Trainer(accumulate_grad_batches=x)
> del ds_config['grad_accumulation_steps']
> ```

This worked. Thank you
