### ISSUE TITLE
Document DistributedDataParallel Static Graph support

### ISSUE THREAD

**Issue by ananthsub** [PyTorchLightning/pytorch-lightning#12296]
## 📚 Documentation

PyTorch 1.11 makes static graph a stable feature for DDP. https://pytorch.org/blog/pytorch-1.11-released/#distributed-training

There are no code changes needed to support this from the Lightning framework POV: all kwargs to the DDPStrategy are forwarded to the DistributedDataParallel constructor here: https://github.com/PyTorchLightning/pytorch-lightning/blob/3b4061f39a8af47a77e9dfa58256e818784b21ca/pytorch_lightning/strategies/ddp.py#L159

Users can enable this with the following
```py
trainer = Trainer(strategy=DDPStrategy(static_graph=True))
```

This should be added to the DDP optimization sections in the docs here: https://pytorch-lightning.readthedocs.io/en/latest/advanced/advanced_gpu.html#ddp-optimizations
______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @rohitgr7 @justusschock @kaushikb11 @awaelchli @akihironitta

**Comment by tchaton** [comment]
@ananthsub let s get this for 1.6, seems quite simple to get in.
