### ISSUE TITLE
Deprecate `Trainer.use_amp`

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#12307]
## Proposed refactor

Deprecate `use_amp` from the Trainer:
https://github.com/PyTorchLightning/pytorch-lightning/blob/90a9da5abb99bdd8df1fce405024f503f9a69088/pytorch_lightning/trainer/trainer.py#L2143-L2145

### Motivation

* `Trainer.use_amp` is not used anywhere in our codebase
* The current implementation is wrong because it does't consider precision=="mixed" or "bf16"
* I don't see any usages in https://www.grep.app/search?q=trainer.use_amp
* The Trainer has the properties `amp_backend` and `precision` which can be used instead.

### Additional context
This was originally added in https://github.com/PyTorchLightning/pytorch-lightning/pull/3412

cc @tchaton @rohitgr7 @carmocca @justusschock @awaelchli @akihironitta

**Comment by daniellepintz** [comment]
Should we also deprecate `LightningModule.use_amp`?
https://github.com/PyTorchLightning/pytorch-lightning/blob/7ee690758ccad7f702460d056f6369c1d4371a46/pytorch_lightning/core/lightning.py#L100

It doesn't seem to be used anywhere and just gets its value from `Trainer.amp_backend`:
https://github.com/PyTorchLightning/pytorch-lightning/blob/ac735db0a052b0cdad45ac8efb7941c2a186d670/pytorch_lightning/trainer/connectors/data_connector.py#L167

**Comment by carmocca** [comment]
Yes!
