### ISSUE TITLE
Facilitate configuration file loading outside training script

### ISSUE THREAD

**Issue by cifkao** [PyTorchLightning/pytorch-lightning#12309]
## 🚀 Feature

I'd like to request a feature that would allow to use the `LightningCLI` configuration more easily in Jupyter notebooks, or in general, outside the main training script (e.g. for serving). This could be done by implementing a mode for `LightningCLI` that exposes the correctly configured parser without actually trying to parse any arguments.

### Motivation

After training a model on the command line, I often want to load it in a Jupyter notebook, e.g. to run it on some toy examples. Often I need to create not just the model itself, but also the data module and maybe even the trainer, optimizers etc. Sometimes I even want to modify the configuration (e.g. the maximum sequence length in a Transformer) before creating the model.

With `LightningCLI`, this is not currently straightforward (see #10363, #12302).

### Pitch

Probably the most flexible solution would be to implement a mode for `LightningCLI` that sets up and exposes the parser without actually trying to parse anything (e.g. `parse=False`). Then one could, for example, feed custom configuration (modified on the fly) via `parser.parse_object()`. Then one could call `instantiate_classes()`, ideally with the possibility to choose which top-level objects (model, data module, trainer) to instantiate.

cc @borda @carmocca @mauvilsa

**Comment by carmocca** [comment]
Hi!

The `LightningCLI` exposes several hooks that you can subclass to introduce your own parsing logic. See it's API reference: https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.utilities.cli.html#pytorch_lightning.utilities.cli.LightningCLI

**Comment by mauvilsa** [comment]
> @carmocca I guess I could subclass the parser in my notebook and override `parse_arguments()` and `instantiate_classes()` to prevent them from actually doing anything. Then I could access the `parser` and use it to do whatever I want (e.g. parse custom configuration using `parser.parse_object()` then call `parser.instantiate_classes()`). Would that work?

I think it will fail because it will try to access the config, but it will not be there because the parsing hasn't been done. Specifically these two lines https://github.com/PyTorchLightning/pytorch-lightning/blob/7ee690758ccad7f702460d056f6369c1d4371a46/pytorch_lightning/utilities/cli.py#L554-L556.

**Comment by cifkao** [comment]
@mauvilsa I see... It's probably possible to work around this, but in any case, it would be easier to have an option to skip all the parsing.

**Comment by mauvilsa** [comment]
> @mauvilsa I see... It's probably possible to work around this, but in any case, it would be easier to have an option to skip all the parsing.

A workaround would not be advisable. I have thought a bit about this and right now I am not sure about a change in LightningCLI. I know of one more use case in which there is a need to get the parser of a CLI. Thus, it might make sense to add a feature to jsonargparse for this. Basically a way to capture the parser from a CLI without any need to modify the CLI.

**Comment by mauvilsa** [comment]
@cifkao in the current version of jsonargparse in master there is now a way to capture the parser from a cli function. You can see the documentation for this feature at https://jsonargparse.readthedocs.io/en/latest/#capturing-parsers.
