### ISSUE TITLE
AttributeError: module 'horovod.torch' has no attribute 'nccl_built'

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#12314]
The `PL.pytorch-lightning (GPUs)` CI job is failing with `AttributeError: module 'horovod.torch' has no attribute 'nccl_built'`

https://dev.azure.com/PytorchLightning/pytorch-lightning/_build/results?buildId=61024&view=logs&j=3afc50db-e620-5b81-6016-870a6976ad29&t=059bb337-5de1-5e6a-4c56-42f55a328c0e

cc @tchaton @rohitgr7 @akihironitta @carmocca @borda

**Comment by awaelchli** [comment]
There is this message:

> Extension horovod.torch has not been built: /usr/local/lib/python3.7/dist-packages/horovod/torch/mpi_lib/_mpi_lib.cpython-37m-x86_64-linux-gnu.so not found
> If this is not expected, reinstall Horovod with HOROVOD_WITH_PYTORCH=1 to debug the build error.
> Warning! MPI libs are missing, but python applications are still available.

There seems to be a missing MPI package. 
The GPU uses the docker container from [this file](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/dockers/base-cuda/Dockerfile).
We can try to add it there. Horrible

**Comment by akihironitta** [comment]
@awaelchli @Borda I'll try to fix this in the next hour(s). If you're already finishing up your fix, let me now here or in the chat :)

**Comment by awaelchli** [comment]
@akihironitta any ideas and help are very welcome. Feel free to give it a try.

**Comment by akihironitta** [comment]
As the hotfix #12368 has unblocked all ongoing PRs, relabelling this issue to P1.
