### ISSUE TITLE
Add typing to the Trainer object within LightningModules

### ISSUE THREAD

**Issue by jlhbaseball15** [PyTorchLightning/pytorch-lightning#12337]
## Proposed refactor

I want to add typing for the `trainer` pointer within the `LightningModule`. 

### Motivation

This would improve autocompletion for IDEs.

### Pitch
I would like to make the following addition:

(`LightningModule`)[https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/core/lightning.py#L97]
```python
class LightningModule(...):
    ...
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
        self.trainer = None
```

changed to 
```python
class LightningModule(...):
    ...
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
        self.trainer: Optional[Trainer] = None
```

### Additional context

See changes [here](https://github.com/jlhbaseball15/pytorch-lightning/commit/ee3b2428e90e8c194d63da3813413d9c8147cc04)

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda

**Comment by akihironitta** [comment]
Hi @jlhbaseball15, thanks for your suggestion! We're trying to add annotations to the whole codebase in #7073. Would you be interested in submitting a PR?
