### ISSUE TITLE
Restoring training session docs

### ISSUE THREAD

**Issue by rzepinskip** [PyTorchLightning/pytorch-lightning#1233]
## 📚 Documentation

["Restoring training session"](https://pytorch-lightning.readthedocs.io/en/latest/pytorch_lightning.trainer.training_io.html#restoring-training-session) documentation shows example, which does not work correctly - [Google Colab](https://colab.research.google.com/drive/14C4G2kKcCS6CvEHv6b1ikQoymsiDwjlA).

Furthermore, when I was looking how to resume sessions I was confused by `load_from_checkpoint`  (Model) and `resume_from_checkpoint` (Trainer) descriptions. I suppose clarifying that the former does only load model state (weights etc.) and the latter load model and training state would be helpful.

The most user-friendly solution would be the one currently stated in docs - passing version id to any logger would cause `fit()` to try to load the latest checkpoint from the version's folder. I think that would require every logger to implement `version` and `get_last_checkpoint` methods, which constitutes a source code change PR.

**Comment by Borda** [comment]
Thx, mind sending a PR? :robot:
