### ISSUE TITLE
[Feature request] Load checkpoints inplace

### ISSUE THREAD

**Issue by louismartin** [PyTorchLightning/pytorch-lightning#12336]
I have seen multiple use cases where people create their lightning module first and then load weights from a previous checkpoint using `module.load_state_dict(...)`.

However it seems that [`ModelIO.load_from_checkpoint(...)`](https://github.com/PyTorchLightning/pytorch-lightning/blob/7ee690758ccad7f702460d056f6369c1d4371a46/pytorch_lightning/core/saving.py#L56) is more complete but it only works when you instantiate a new module object.

Would it make sense to have another method `ModelIO.load_from_checkpoint_inplace(...)` that would be similar to `load_from_checkpoin(...)` but work for already instantiated Lightning Modules ?

**Comment by rohitgr7** [comment]
`load_from_checkpoint` internally instantiate the model first and then load the checkpoint state dict. Since LightningModules are inherited from `nn.Module` state dict, you can simple use the PyTorch API for it too
```py
model = LitModel(...)
ckpt = torch.load(...)
model = model.load_state_dict(ckpt['state_dict'])
```

**Comment by louismartin** [comment]
Yes thanks for the answer, that's indeed what I'm doing know but that sadly does not call the callbacks and other additional logic in `load_from_checkpoint(...)`

**Comment by rohitgr7** [comment]
`load_fom_checkpoint`doesn't do anything related to callbacks. The additional logic is used to initialize the model with new params if there are any and use the hparams from the checkpoint, but since in your case, the model is already initialized that logic is anyways nullified.

**Comment by louismartin** [comment]
Ok good point, I thought that maybe it could make sense to overwrite those hparams using the stored hparams but I'm not sure it's always a good thing. 
I'll stick with that for now.
