### ISSUE TITLE
Support for latest PyTorch profiler

### ISSUE THREAD

**Issue by scottgigante-immunai** [PyTorchLightning/pytorch-lightning#12358]
## 🚀 Feature

Support for the ["new" PyTorch profiler](https://pytorch.org/blog/introducing-pytorch-profiler-the-new-and-improved-performance-tool/). 

### Motivation

Per the [PyTorch docs](https://pytorch.org/docs/stable/profiler.html), the torch.autograd profiler used in Lightning is legacy code and will be deprecated. The `torch.profiler` is much nicer and has been supported for over a year.

### Pitch

Rename PyTorchProfiler to PyTorchAutogradProfiler and implement PyTorchProfiler as the new default profiler.

### Alternatives

Keep PyTorchProfiler as the legacy profiler and implement PyTorchProfiler2 (or something) as an alternative profiler.

### Additional context

N/A

cc @carmocca @kaushikb11 @ninginthecloud @rohitgr7

**Comment by ananthsub** [comment]
The integration with the latest pytorch profiler is already available here: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/profiler/pytorch.py

Specifically:
https://github.com/PyTorchLightning/pytorch-lightning/blob/bc812077c41896c93205fe6e9e3d18485d83a2e5/pytorch_lightning/profiler/pytorch.py#L477-L479

@kaushikb11 the profiling docs should be updated to reflect this:
https://pytorch-lightning.readthedocs.io/en/latest/advanced/profiler.html#pytorch-profiler

**Comment by scottgigante-immunai** [comment]
Thanks!

**Comment by scottgigante-immunai** [comment]
@carmocca just a flag that the tips on how to run the PyTorch profiler are also only relevant for the legacy profiler: see https://pytorch-lightning.readthedocs.io/en/stable/advanced/profiler.html#pytorch-profiler vs instructions with `torch_tb_profiler` [here](https://pytorch.org/blog/introducing-pytorch-profiler-the-new-and-improved-performance-tool/)

**Comment by carmocca** [comment]
@scottgigante-immunai Would you be interested in opening a PR to the docs mentioning that package and linking to it? https://github.com/pytorch/kineto/tree/main/tb_plugin

cc @guotuofeng

**Comment by carmocca** [comment]
Sure!
