### ISSUE TITLE
Send notifications if nightly CI fails

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning#12367]
## 🚀 Feature
Create issues from nightly CI failures.

### Motivation
Nightly CI jobs can silently fail as we've seen #12365 and #12366. If there was a bot creating issues from nightly CI failures, we could've avoided those situations.

### Pitch
(I haven't looked for available tools in the wild yet. To be filled.)

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @carmocca @akihironitta

**Comment by Borda** [comment]
I would probably start with slack notification, as nightly fails may generate too many new issues/noise
see for example what we have in EcoCI:
https://github.com/PyTorchLightning/ecosystem-ci/blob/3217aca9f6368ae70c142c87e017356f6e2f6b50/.github/workflows/ci_testing.yml#L124-L134

**Comment by akihironitta** [comment]
@Borda Forgot about the Slack notifier! Let's utilize that.

**Comment by akihironitta** [comment]
On second thought, I believe we should enable it for all CI jobs running in master rather than enabling it only for scheduled ones.

**Comment by Borda** [comment]
implemented in #12675
