### ISSUE TITLE
use Trainer to train model without validation loop

### ISSUE THREAD

**Issue by dingyic1** [PyTorchLightning/pytorch-lightning#12374]
Dear Developer, 

Since I have to train the model without validation loops. Is there any parameter that can make the trainer training without the validation loop? 

trainer = pl.Trainer(strategy="dp", accelerator="gpu", devices="auto", max_epochs=1, limit_val_batches=0,
                         num_sanity_val_steps=0, val_check_interval=0)
I tried to set those parameters, but it does not work

**Comment by rohitgr7** [comment]
```py
limit_val_batches=0,
num_sanity_val_steps=0
```
just these 2 should work. Is it running the validation loop? does it show the validation progress bar?
