### ISSUE TITLE
The process of deadlock

### ISSUE THREAD

**Issue by 834799106** [PyTorchLightning/pytorch-lightning#12385]
``## 🐛 Bug
Recently, I tried DDP training of single machine with multiple cards. I have four V100 cards, which are usually used in pairs to run the same different hyperparameter code, but I often encountered the phenomenon that 100% of the training of the first epoch was stuck. I checked the checkpoint after each epoch and found that it was saved normally. I tried to update the latest PyTorch lighting and sometimes this worked, but I got stuck at about half of the training total.

```python
pytorch_lightning.utilities.seed.seed_everything(seed=args.seed, workers=True)
best_checkpoint_callback = ModelCheckpoint(
        save_top_k=1,
        monitor="val mean dice",
        mode="max",
        dirpath="./checkpoint/",
        filename=f"{args.model_name}-best_metric_model",
    )
current_checkpoint_callback = ModelCheckpoint(dirpath="./checkpoint/",
                filename=f"{args.model_name}-last_model",
                        save_on_train_epoch_end =True)
model = LightningModel(args)
trainer = Trainer(max_epochs=args.num_epochs,
                          devices=args.gpu_num,
                          gpus=args.gpu_num,
                          accelerator="gpu",
                          strategy='ddp_find_unused_parameters_false',
                          callbacks=[best_checkpoint_callback,current_checkpoint_callback],
                          logger=wandb_logger,
                          check_val_every_n_epoch=args.val_interval,
                          precision=16,
                         sync_batchnorm=True,

                         )
```

cc @justusschock @kaushikb11 @awaelchli @akihironitta @rohitgr7

**Comment by 834799106** [comment]
<img width="678" alt="1647834605(1)" src="https://user-images.githubusercontent.com/78247190/159202995-4686b8a1-d73a-47f8-b64c-664b0b33f4d3.png">
such like this

**Comment by carmocca** [comment]
Can you share a script that reproduces the issue?
Or can you step through with a debugger to find the call that hangs?

**Comment by 834799106** [comment]
> Or can you step through with a debugger to find the call that hangs?

I've been trying to find a way to find the call that hangs in lightning. Could you tell me how to do that？

**Comment by 834799106** [comment]
> 您是否遇到数据不均衡的情况，其中某些进程处理的批次比其他进程多？这将导致在 epoch 结束时挂起

HI, I do have a similar situation, but I just tried and setting limit_train_batch to int doesn't work for me.
https://github.com/PyTorchLightning/pytorch-lightning/issues/11910

**Comment by 834799106** [comment]
It is worth noting that most of the problems occur when the second program freezes after running the same code successively.

**Comment by 834799106** [comment]
I just did a test. First, I started train.py using DDP in a single-machine multi-card environment and it worked normally (sometimes not). Starting train.py with DDP in the same environment with different hyperparameters would get stuck when the first epoch was completed, then I tried to update the latest PyTorch-Lightning version and started train.py in the same way and it worked fine. However, when the two programs are trained and run in the same way, they still fail. The only solution seems to be that the two programs are running different versions of PyTorch-Lightning.
Note: If limit_TRAIN_Batch is set to 7 and val is set to 5, the version without update works normally. However, if the value is larger than 250, the version still does not work. Because of the experimental data and the specificity of the code, I may not be able to provide boring code.

**Comment by PiotrDabkowski** [comment]
I also have the same issue when the batch size is variable!

**Comment by arlofaria** [comment]
> I just did a test. First, I started train.py using DDP in a single-machine multi-card environment and it worked normally 
> ...
> Note: If limit_TRAIN_Batch is set to 7 and val is set to 5, the version without update works normally.

If setting `limit_train_batch` resolves the problem, this might suggest that there's a bug in your dataloader -- are you using a custom batch sampler?  That was the situation for a similar bug report in #10947 ... hope this pointer might help!
