### ISSUE TITLE
Benchmark tests are flaky

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning#12404]
## 🐛 Bug
I have seen the benchmark testing failing due to the following error quite a number of times:

```
>       assert np.mean(diffs) < max_diff, f"Lightning diff {diffs} was worse than vanilla PT (threshold {max_diff})"
E       AssertionError: Lightning diff [1.30557255e+00 3.60853071e-07] was worse than vanilla PT (threshold 0.0002)
E       assert 0.6527864532870287 < 0.0002
E        +  where 0.6527864532870287 = <function mean at 0x7fcd121d6320>(array([1.30557255e+00, 3.60853071e-07]))
E        +    where <function mean at 0x7fcd121d6320> = np.mean

tests/benchmarks/test_basic_parity.py:38: AssertionError
```
https://dev.azure.com/PytorchLightning/pytorch-lightning/_build/results?buildId=62256&view=logs&j=46f8844e-d2e7-54ff-5b07-42679d5a20a0&t=d0c9a9e3-f716-53b7-5c53-27dd0366278d

which is configured at:

https://github.com/PyTorchLightning/pytorch-lightning/blob/bc1c8b926c5072f58f42ad4b7413a8ef5c904c85/.azure-pipelines/gpu-tests.yml#L121-L123
https://github.com/PyTorchLightning/pytorch-lightning/blob/bc1c8b926c5072f58f42ad4b7413a8ef5c904c85/.azure-pipelines/gpu-benchmark.yml#L39

### Expected behavior
No error raised so we can always keep our CI green 🟢

### Additional context

cc @carmocca @akihironitta @borda

**Comment by Borda** [comment]
hmm seems that some process takes longer than it should...?

**Comment by akihironitta** [comment]
> hmm seems that some process takes longer than it should...?

It seems the issue is about memory but not about speed. 

---

Only one of the benchmarks have been failing frequently in particular with the following parameter:
```python
pytest.param(ParityModuleCIFAR, 4.0, 0.0002, 2, 2, marks=_MARK_SHORT_BM), 
```
https://github.com/PyTorchLightning/pytorch-lightning/blob/51575dcf60f1fdf59a1850fbcafa78ad10947321/tests/benchmarks/test_basic_parity.py#L59-L76

**Comment by akihironitta** [comment]
After running some of our existing benchmark scripts `tests/benchmarks/` on previous commits, we see that https://github.com/PyTorchLightning/pytorch-lightning/commit/00211c1d (where ) increases the memory usage while it decreases execution time, which looks like normal behaviour. ref:  [Set Torch.backends.cudnn.benchmark = True consumes huge amount of memory](https://discuss.pytorch.org/t/set-torch-backends-cudnn-benchmark-true-consumes-huge-amount-of-memory/131010)

Quick screenshot of the result:

<img width="607" alt="Screen Shot 2022-05-23 at 16 05 19" src="https://user-images.githubusercontent.com/20610905/169762650-349e8558-a736-4f1c-8e0d-b96430268cae.png">

---

TODO:
- add env details for benchmarking.
- check `Trainer(benchmark=False)` will make the same memory usage as before 00211c1d.
- add possible causes if found.

**Comment by carmocca** [comment]
Thanks @akihironitta! That's interesting to know.

Doesn't the pure torch benchmark that we check against also set `benchmark=True`?

**Comment by akihironitta** [comment]
I ran the benchmark with `tests.helpers.advanced_models.ParityModuleCIFAR` again (but this time with `Trainer(benchmark=False)` explicitly specified) and confirmed that there's no difference in the memory usage before and after the commit 00211c1.

I'll conclude this issue by adding `Trainer(benchmark=False)` to the existing benchmarks.
