### ISSUE TITLE
`cpu (ubuntu-20.04, 3.7, oldest, stable)` fails due to SHA mismatch

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning#12402]
## 🐛 Bug
The CI job is failing in master.
```
Collecting numpy>=1.14.6
  Using cached numpy-1.21.5-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    numpy>=1.14.6 from https://files.pythonhosted.org/packages/50/46/292cff79f5b30151b027400efdb3f740ea03271b600751b6696cf550c10d/numpy-1.21.5-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl#sha256=3d893b0871322eaa2f8c7072cdb552d8e2b27645b7875a70833c31e9274d4611 (from scikit-learn>0.22.1->-r requirements/test.txt (line 12)):
        Expected sha256 3d893b0871322eaa2f8c7072cdb552d8e2b27645b7875a70833c31e9274d4611
             Got        447418515[384](https://github.com/PyTorchLightning/pytorch-lightning/runs/5629082072?check_suite_focus=true#step:12:384)153cd6d31e522f98ac6fd9eb4727c1d2dc8b5113f44b24b1ed0a
```
https://github.com/PyTorchLightning/pytorch-lightning/runs/5629082072?check_suite_focus=true

### Environment

- PyTorch Lightning Version (e.g., 1.5.0):
- PyTorch Version (e.g., 1.10):
- Python version (e.g., 3.9):
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

cc @carmocca @akihironitta @borda

**Comment by Borda** [comment]
we can try to change the cache hash, or just lower the time reset to 2 days instead of one week?
