### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch_lightning.callbacks.pt_callbacks'

### ISSUE THREAD

**Issue by jinfagang** [PyTorchLightning/pytorch-lightning#12412]
<img width="851" alt="image" src="https://user-images.githubusercontent.com/21303438/159489468-f3a4112f-2d5d-4b75-9032-d988366fe96b.png">

can it update these new feature to pypi on time?
otherwise users maybe very confused about these new imports.

**Comment by carmocca** [comment]
Hi!

1.6.0 has not been released yet so it's not available in PyPI.

If you want to try master, you can do so with:

```bash
pip install https://github.com/PyTorchLightning/pytorch-lightning/archive/master.zip
```

Can you share the full error stacktrace if you are getting an import error?

**Comment by rohitgr7** [comment]
> ModuleNotFoundError: No module named 'pytorch_lightning.callbacks.pt_callbacks'

also, you might need to do this:
```py
import pytorch_lightning.callbacks as pt_callbacks
```
