### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch_lightning.strategies'

### ISSUE THREAD

**Issue by weiyigong** [PyTorchLightning/pytorch-lightning#12414]
## 🐛 Bug

I was trying to import using
```python
from pytorch_lightning.strategies.ddp import DDPStrategy
```
but got the following error message:
> ModuleNotFoundError: No module named 'pytorch_lightning.strategies'

### Environment

- PyTorch Lightning Version (e.g., 1.5.0): 1.5.10
- Python version (e.g., 3.9): 3.8
- OS (e.g., Linux): Ubuntu 20.04
- How you installed PyTorch (`conda`, `pip`, source): pip install pytorch-lightning

**Comment by rohitgr7** [comment]
hey @weiyigong !

this is currently available on master and will be available in the next v1.6 release (end of March).
