### ISSUE TITLE
Allow callbacks to access internal variables of training loop

### ISSUE THREAD

**Issue by amoudgl** [PyTorchLightning/pytorch-lightning#1243]
## 🚀 Feature
Internal variables (batch, predictions, etc) of the training loop (training + validation step) should be made transparent to callbacks. Right now, there is no way to access these internal variables of the training loop through callbacks without making them as attributes of lightning module. This doesn't sound optimal as it pollutes the lightning module with non-essential code.

### Motivation

Use case: Visualize images and predictions from a training batch. Right now, there are two ways: 
1. Add a `log` method in pl module and call this from `training_step` method of pl module. By doing this, we are essentially polluting pl module with non-essential code.

2. Write a visualization callback. As of now, callback has access to pl module and trainer but still, it can’t access the variables (images, predictions, etc) in the training step. We can make these variables as attributes of pl module but then updating these attributes in every training step (so that callback can access it) would also count as “non-essential code” which would defeat the point of the callback. It also spoils the neat separation between callbacks and pl module as we'll be caching/updating attributes in pl module even if we switch off the callback.

**Comment by Borda** [comment]
each callback method has accessible trainer and model... 
what PL version are using? because we made these changes quite recently... :]
cc: @ethanwharris

**Comment by amoudgl** [comment]
Hi @Borda, I am using pl version 0.7.1. In this version, callbacks do have access to trainer and pl module as you said. However, I wanted to point out that I can't access the interval variables of pl module `training step` method from a callback. Example: 


Let's say we have the following module class from pl examples:

```python
class LitModel(pl.LightningModule):

    def __init__(self):
        super().__init__()
        self.l1 = torch.nn.Linear(28 * 28, 10)

    def forward(self, x):
        return torch.relu(self.l1(x.view(x.size(0), -1)))

    def training_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self(x)
        return {'loss': F.cross_entropy(y_hat, y)}
```

I'd try to write the visualization callback as follows to visualize images from training batch: 

```python
class VizCallback(pl.Callback):

    def on_batch_end(self, trainer, pl_module):
        # here I wish to have access to images `x` from training_step
        grid_img = torchvision.utils.make_grid(x)
        self.logger.experiment.log_image(grid_img)
```

The issue is I can't access training samples `x` in the example above from a callback without linking it to pl module. As the code gets more complicated, I wish to have access to several variables of `training_step` which could be model predictions, attention maps and so on from a callback. In order to access these variables from a callback, I'd have to make them as attributes of pl module and update them in every training step which I think is non-ideal. See what I mean?

**Comment by czotti** [comment]
I have figured a way to retrieve these informations in a callback. Use `hiddens`, not sure if it's the right way to do it but at least it works with little modifications in your model, here is my `training_step()` function
```python
def training_step(self, batch, batch_idx):
    inputs, targets = batch
    preds = self(inputs)
    loss = #whatever 
    hiddens = {"inputs": inputs, "predictions": preds, "targets": targets}
    return {"loss": loss, "hiddens": hiddens}
```

with this you will get everything in your callback

```python
class VizCallback(pl.Callback):
    def on_batch_end(self, trainer, pl_module):
        # here I wish to have access to images `x` from training_step
        if trainer.hiddens:
            inputs = trainer.hiddens["inputs"]
            preds = trainer.hiddens["predictions"]
            targets = trainer.hiddens["targets"]
            grid_img = torchvision.utils.make_grid(inputs)
            self.logger.experiment.log_image(grid_img)
```

But there is nothing for the validation loop as far as I see there is no `on_batch_end` for the validation am I wrong?

**Comment by williamFalcon** [comment]
@czotti good hack haha but we need an actual way of doing this.
@PyTorchLightning/core-contributors ?

**Comment by jeremyjordan** [comment]
iirc, you can return any arbitrary key and it will be added to `trainer.callback_metrics` - you don't need to override the `hiddens` key

**Comment by amoudgl** [comment]
I think any key returning based idea (like overriding `hiddens` key/returning dictionary relevant for callback) would spoil the neat separation between callbacks and pl module because user would have to remember to cache/return variables in pl module which are relevant for callback and when user wishes to switch off the callback, they would have to delete the corresponding cache/return code in pl module. Thus, I suggested all the internal variables of training and validation to be exposed to callbacks by default so that they don't have to remember cache relevant stuff for callback in pl module. Please let me know if I wasn't clear. :)

**Comment by isvoboda** [comment]
> iirc, you can return any arbitrary key and it will be added to `trainer.callback_metrics` - you don't need to override the `hiddens` key

Unfortunately, in the case of [on_batch_end](https://github.com/PyTorchLightning/pytorch-lightning/blob/8544b334e4af9caa060a280146e7d3bb10648332/pytorch_lightning/trainer/training_loop.py#L653) callback the Trainer's `self.callback_metrics` is not yet [populated](https://github.com/PyTorchLightning/pytorch-lightning/blob/8544b334e4af9caa060a280146e7d3bb10648332/pytorch_lightning/trainer/training_loop.py#L667).

**Comment by justusschock** [comment]
@williamFalcon I think the way to go here is to have more of the looping variables as trainer attributes. However, we need to be careful with this as we don't want our trainer to be bloated.

**Comment by Borda** [comment]
we can offer some read-only properties...

**Comment by amoudgl** [comment]
I haven't gone through this in detail but it seems relevant to the discussion here: 

Repo: https://github.com/pberkes/persistent_locals
Blog post: http://code.activestate.com/recipes/577283-decorator-to-expose-local-variables-of-a-function-/

**Quick summary from the README of above repo:**

The proposed solution consists of a decorator that makes the local variables accessible from a read-only property of the function, 'locals'. For example:
```
@persistent_locals
def is_sum_lt_prod(a,b,c):
    sum = a+b+c
    prod = a*b*c
    return sum<prod
```

after calling the function, e.g. `is_sum_lt_prod(2,1,2)`, we can analyze
the intermediate results as

```
is_sum_lt_prod.locals
```
which returns

```
{'a': 2, 'b': 1, 'c': 2, 'prod': 4, 'sum': 5}
```

**Comment by amoudgl** [comment]
Please ignore my above comment, I don't think the solution is neat and maintainable...

**Comment by festeh** [comment]
Yes, this would be useful. Currently there's no proper way to pass batch computation result to `on_test_batch_end` for a custom `Callback` (`hiddens` and `callback_metrics` won't work either). As a hacky workaround I'm just attaching the results of `test_step` to `self` lol.

**Comment by AAnoosheh** [comment]
I needed to do this in my code as well (log the results of inference as they occur), and I was thinking of setting model class attributes i.e. `self.current_test_output = ...` and then accessing it in the callback.

But then I thought maybe this would cause issues during multiprocessing, since I'm not exactly sure how the model is split/synced during DP/DDP.

**Comment by JohnnyRisk** [comment]
Has this been resolved? I am trying to implement a callback for visualization and currently facing the same issue.

**Comment by ophiry** [comment]
Are there any solutions \ workarounds for this?
having a similar issue of complex reporting of predictions that I want to separate from the main module

**Comment by YannDubs** [comment]
I'm using czotti's hack with `self.hiddens` (see above) but I agree that it poluted the pl module.

**Comment by ayulockin** [comment]
I don't know if this is relevant here but I was able to build a custom callback that was able to log images along with the predictions to the Weights and Biases dashboard. 

```
class ImagePredictionLogger(Callback):
    def __init__(self, val_samples, num_samples=32):
        super().__init__()
        self.num_samples = num_samples
        self.val_imgs, self.val_labels = val_samples
        
    def on_validation_epoch_end(self, trainer, pl_module):
        val_imgs = self.val_imgs.to(device=pl_module.device)
        val_labels = self.val_labels.to(device=pl_module.device)
       
        logits = pl_module(val_imgs)
        preds = torch.argmax(logits, -1)
        
        trainer.logger.experiment.log({
            "examples":[wandb.Image(x, caption=f"Pred:{pred}, Label:{y}") 
                           for x, pred, y in zip(val_imgs[:self.num_samples], 
                                                 preds[:self.num_samples], 
                                                 val_labels[:self.num_samples])]
            })
```

This is the associated [colab notebook](https://colab.research.google.com/drive/12oNQ8XGeJFMiSBGsQ8uth8TaghVBC9H3?usp=sharing). Associated W&B's [run page](https://wandb.ai/wandb/wandb-lightning/runs/2272kyy6).

**Comment by festeh** [comment]
Your code indeed separates logic of lightning module from callback, but it does some additional work. I noticed that Callback now also has `on_validation_batch_end` so czozzi's method can be applied at validation time too (same for test). Also `on_*_batch_end` now provides an actual batch, so use case from https://github.com/PyTorchLightning/pytorch-lightning/issues/1243#issuecomment-605536194 is supported.

**Comment by Parskatt** [comment]
@festeh The problem of outputs remain though. For me I think the ideal solution would be inplace modification of a batch dictionary which is propagated by pytorch-lightning. Right now no inplace modifications are propagated, so the batch may only contain the original data which makes it rather useless. Until then I guess I will record the batch to the module.

**Comment by festeh** [comment]
I'm not sure how modifying a batch would help to solve original problem - coupling essential and non-essential code. For me it's either full decoupling and clean code (but you'll have to do additional computations in callback) or less nicer code that just returns everything in outputs.

**Comment by Shreeyak** [comment]
For logging images or other media, I'm returning the values from the train/val/test step and using those outputs in my visualization callback. This does increase the memory overhead, but cleans up the code:

```
class MyModel(pl.LightningModule):
    def __init__(self):
        ...

    def training_step(self, batch, batch_idx):
        ...
        outputs = {
            "loss": total_loss,
            "rgb_imgs": batch["rgb"].detach(),
        }
```

Callback:
```
class LogMedia(Callback):
    def __init__(...):
        ...
    
    @rank_zero_only
    def on_train_batch_end(self, trainer, pl_module, outputs, batch, batch_idx):
        if self.every_n_steps_train > 0 and trainer.global_step % self.every_n_steps_train == 0:
            # 2D outputs - Shape: [b, ips, c, h, w], ips=imgs/scene
            rgb_imgs = outputs.get("rgb_imgs", None)
            if rgb_imgs is not None:
                viz_rgb = []
                rgb_imgs = rgb_imgs[:, : self.limit_samples_2d, ...]
                for idx, batch_rgb in enumerate(rgb_imgs):
                    rgb_imgs = torchvision.utils.make_grid(batch_rgb.detach(), nrow=4)  # create_grid
                    rgb_imgs = rgb_imgs.cpu().numpy().transpose((1, 2, 0))
                    rgb_imgs = (rgb_imgs * 255).astype(np.uint8)
                    rgb_imgs = Image.fromarray(rgb_imgs)
                    viz_rgb.append(wandb.Image(rgb_imgs))  # wandb uses PIL Image
    
                    if self.save_to_disk:
                        batch_num = 0 if self.overwrite_prev_files else batch_idx
                        rgb_imgs.save(self.exp_dir / f"batch-{batch_num}.{idx}.rgb.jpg")
                trainer.logger.experiment.log({f"{stage.value}/rgb": viz_rgb}, commit=False)
```

**Comment by Parskatt** [comment]
@Shreeyak Does your method not store every image of the epoch? IIRC the outputs of the training step are all stored for the at_epoch_end step in the model. For large datasets I think this would cause the memory to explode.

**Comment by Shreeyak** [comment]
@Parskatt No, I actually don't. The above was a simplified snippet of code that uploads the images every batch. In my actual code, I log the latest N batches every M steps.
I keep a circular queue (`collections.deque` object) in the `LogMedia` callback that holds the latest N batches. 

Here's a sample code:

```python
from collections import deque
from pytorch_lightning.utilities import rank_zero_only

def flush_deque(deque_obj: deque) -> List:
    """Return all of the data in a que, in order oldest->newest in list"""
    data_r = []
    while len(deque_obj) > 0:
        data_r.append(deque_obj.popleft())
    return data_r

class LogMedia(Callback):
  def __init__(self, max_samples: int = 3, every_n_steps_train: int = 50, ...):
        self.deque_train = deque(maxlen=self.max_samples)
        self.every_n_steps_train = every_n_steps_train
        self.max_samples = max_samples

    @rank_zero_only
    def on_train_batch_end(self, trainer, pl_module, outputs, batch, batch_idx):
        self.deque_train.append(outputs)
        if self.every_n_steps_train > 0 and trainer.global_step % self.every_n_steps_train == 0:
            self._log_results(trainer, self.deque_train, Stage.TRAIN, batch_idx)

    def _log_results(self, trainer, deque_obj: deque, stage: Stage, batch_idx: Optional[int] = None):
        """Process and upload the media files to logger"""
        outputs_list = flush_deque(deque_obj)
        for outputs in outputs_list:
            self.visualize_scene_outputs(trainer, outputs, stage, batch_idx)
```

**Comment by Shreeyak** [comment]
> IIRC the outputs of the training step are all stored for the at_epoch_end step in the model.

I didn't realize that. I didn't see much memory increase in my project (5000 imgs only). In this case, the code can be modified so that the LightningModule holds the latest N batches, which it passes to the callback in the `train_epoch_end()` method.
