### ISSUE TITLE
Horovod doesn't support  setting num_nodes/ num_gpus explicitly.Use'

### ISSUE THREAD

**Issue by lunasdejavu** [PyTorchLightning/pytorch-lightning#12459]
## 🐛 Bug

```
Traceback (most recent call last):
File'"/PyTorch_CIFAR10-master/train.py", line 93, in ‹modules
main(args)
File "/PyTorch_CIFAR10-master_2/train.py", line 44, in main
accelerator="horovod"
File"/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py"
line 41, in overwrite_by _env_vars
return fn(self, **kwargs)
File"/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 357, in
init
deterministic,
File"/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator_connector.py",line
113, in on_trainer_init
self.set_distributed_mode()
File"/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator_connector.py"
line340, in set _distributed_mode
self. set horovod_backend()
File"/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator_connector.py"
" 
line357, in_set horovod_ backend
self.check horovod()
File"/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator_connector.py"
line376, in check horovod
*Horovod does not support setting num_nodes / num gpus explicitly. Use
pytorch_lightning.utilities.exceptions.MisconfigurationException: Horovod does not support setting num_nodes
Fira stackerpust tevent-cahiprausdrun/ mpirwn to confieure the number of processes.
File"/PyTorch_CIFAR10-master/train.py", line 93, in ‹module>
main(args)
File"/PyTorch_CIFAR10-master/train.py", line 44, in main
*Horovod does not support setting num_nodes / num gpus explicitly. Use
pytorch_lightning.utilities.exceptions.MisconfigurationException: Horovod does not support setting num_nodes
num _gpus explicitly. Use horovodrun / mpirun to configure the number of processes.
Process. 1 exit with status code 1.
Terminating remaining workers after failure of Process 1
Procesach fris, "ittentetoi, (pls ):
File"/opt/conda/bin/horovodrun"; line 8, in «modules
sys.exit(run_commandline())
File"/opt/conda/lib/python3.7/site-packages/horovod/runner/launch.py", line 770, in run_commandline
run(args)
File"/opt/conda/lib/python3.7/site-packages/horovod/runner/launch.py",line760,inrun
return
run static(args)
File"/opt/conda/lib/python3.7/site-packages/horovod/runner/launch.py",line 617, in _run static
launch_job(args, settings, nics, command)
File"/opt/conda/lib/python3.7/site-packages/horovod/runner/launch.py"
, line 733, in _launch_job
args.verbose)
File"/opt/conda/lib/python3.7/site-packages/horovod/runner/launch.py"
, line 706, in un_controller
gloo_run()
File"/opt/conda/lib/python3.7/site-packages/horovod/runner/launch.py"
, line 722, in gloo run fn
gloo_run (settings, nics, env, driver_ip, command)
file"/opt/conda/lib/python3.7/site-packages/horovod/runner/gloo_run.py",line298,ingloo_run
launch_gloo(command, exec_command, settings, nics, env, server ip)
File "/opt/conda/lib/python3.7/site-packages/horovod/runner/gloo_run.py", line 285, in launch gloo
• format (name=name, code=exit_code))
RuntimeError: Horovod detected that one or more processes exited with non-zero status, thus causing the job to
be terminated. The first process to do so was:
Process name:1
Exit code:1
```

### To Reproduce
https://github.com/huckiyang/PyTorch-CIFAR10 I just use this repository and follow the lightning document
I only added to use `trainer(accelerator = horovod)` to do single worker multi-GPUs training
and run the script
```
export NCCL_SHH_DISABLE=1
export NCCL_SOCKET _IFNAME=eth0
export NCCL_IB_DISABLE=1
export NCCL_P2P_DISABLE=1
CUDA_VISIBLE_DEVICES="0,1"
horovodrun -np2 python train.py -- classifier res18
```

https://github.com/huckiyang/PyTorch-CIFAR10 I use the code from here
### Expected behavior
horovod training on single workers for multi gpus

### Environment

- PyTorch Lightning Version (e.g., 1.5.0):1.1.0
- PyTorch Version (e.g., 1.10):1.7.0
- Python version (e.g., 3.9):3.7
- OS (e.g., Linux):ubuntu 18
- CUDA/cuDNN version:CUDA 10.2 7605
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source): pip
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:
horovod 0.23
### Additional context
Or can anyone just tell me the environment setting  that I can use horovod by lightning, the code on the document doesn't work

cc @awaelchli @akihironitta

**Comment by rohitgr7** [comment]
possibly related to the example here: https://pytorch-lightning.readthedocs.io/en/latest/accelerators/gpu.html#horovod

**Comment by lunasdejavu** [comment]
> possibly related to the example here: https://pytorch-lightning.readthedocs.io/en/latest/accelerators/gpu.html#horovod
It can't find strategy
For pytorch_lightning 1.5.10
I tried 

trainer = Trainer(strategy="horovod", accelerator="gpu", devices=1)
It showed

File
11 estderr»:
"/PyTorch_ CIFAR1e-naster /train.py*, line 95, in «modules
main(ares)
1]«stderry: File
®/home/notebook/code/personal/PyTorch_CIEAR10-master/train.py
", line 46, in main
11<stderr):
devices=2
1] «stderry: File
*/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/env_vars_connecto
write by env_vars
1 ‹stderr):
return fn(self, **kwargs)
11<stderr> :TypeError:
init
_() got an unexpected keyword argument 'strategy
@] «stderr» :Traceback (most recent call last):
(0] «stderr>:
File
0<stderr>:
*/home/notebook/code/personal/PyTorch_ CIFAR10-master 2/train.py", line 95, in «modules
main(args)
[e]«stderr>: File "/home/notebook/code/personal/PyTorch_CIFAR10-master_2/train.py"
, line 46, in main
[0] «stderr>:
devices=2
[o]«stderr>: File
"/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector
write by_ env_ vars
[0] «stderr»:
return fn(self, **kwargs)
[0] «stderr» :TypeError:
init
_() got an unexpected keyword argument
° strategy

**Comment by lunasdejavu** [comment]
@gianscarpe can you tell me all the library settings for horovod, PyTorch and pytorch_lightning? I tried this for days I really how to let the horovod works for my task as soon as possible 😭

**Comment by awaelchli** [comment]
Here are the [docs for Horovod with Lightning](https://pytorch-lightning.readthedocs.io/en/stable/advanced/multi_gpu.html?highlight=horovod#horovod). 

```
pytorch_lightning.utilities.exceptions.MisconfigurationException: Horovod does not support setting num_nodes
num _gpus explicitly. Use horovodrun / mpirun to configure the number of processes.
```

This error message is raised when you set `Trainer(num_nodes>1)` or `Trainer(gpus>1)` which is not allowed. 
@lunasdejavu Try `Trainer(accelerator="horovod", gpus=1)` (setting explicitly). 

It's possible that there is a bug with devices=auto in combination with horovod, in which case devices gets set to higher than  1 which is not suitable.

**Comment by lunasdejavu** [comment]
@awaelchli I tried, and there is another error showed up
pytorch_lightning/trainer/connectors/callback_connector.pay line 40 in insert_env_defaults
pytorch_lightning.utilities.exceptions.MisconfigurationException:Invalid type provided for checkpoints_callback instances to the 'callbacks' argument in the Trainer constructor instead

**Comment by awaelchli** [comment]
@lunasdejavu I just noticed that you reported this issue for Lightning version 1.1.0. This is ancient and I probably can't help you much there. The horovod strategy and accelerators have seen substantial internal changes and improvements. Have you tried upgrading?

**Comment by lunasdejavu** [comment]
@awaelchli I tried with pytorch_lightning 1.15 in the beginning so I downgraded to 1.1
Do you have any recommendations of the pytorch_lightning version and horovod version?I  think it might be the horovod problem but I don't know which one could fit pytorch_lightning 1.15

**Comment by gianscarpe** [comment]
Hi @lunasdejavu, in the end I noticed that the problem is with the pytorch version that horovod requires. It's mandatory to use the exact version for horovod and adat the other depencies (e.g., lightning, vision, ...) accordingly. For achieving this, try to install horovod first and next install the other dependencies while checking that pytorch is kept the same!
