### ISSUE TITLE
[CLI] Cannot pass init_args to override config file

### ISSUE THREAD

**Issue by tshu-w** [PyTorchLightning/pytorch-lightning#12464]
## 🐛 Bug

Suppose I have a CLI configuration file, but I have no way to modify the Datamodule or Model init_args in it via command line arguments.

### To Reproduce
I thought the traceback is clear enough, so I don't reproduce with a BoringModel. If you really need it, please let me know. 

Here is the **reproduce steps**:

1. `git clone https://github.com/tshu-w/lightning-template.git`
2. `conda create -n env python=3.9 && conda activate env && pip install -r requirements.txt`
3. make sure `run fit --config configs/mrpc.yaml --print_config=skip_null` works fine.
4. `run fit --config configs/mrpc.yaml --data.batch_size=64 --print_config=skip_null` raise error.

#### Traceback
```
Traceback (most recent call last):
  File "/home1/wangtianshu/lightning-template/run", line 33, in <module>
    main()
  File "/home1/wangtianshu/lightning-template/run", line 20, in main
    cli = LitCLI(
  File "/home1/wangtianshu/.local/share/conda/envs/template/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 516, in __init__
    self.parse_arguments(self.parser)
  File "/home1/wangtianshu/.local/share/conda/envs/template/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 655, in parse_arguments
    self.config = parser.parse_args()
  File "/home1/wangtianshu/.local/share/conda/envs/template/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 230, in parse_args
    argv = self._convert_argv_issue_84(classes, k, argv)
  File "/home1/wangtianshu/.local/share/conda/envs/template/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 290, in _convert_argv_issue_84
    class_path = passed_args[f"{argv_key}.class_path"]
KeyError: '--data.class_path'
```

### Expected behavior

`run fit --config configs/mrpc.yaml --data.batch_size=64 --print_config=skip_null` works correctly.

### Environment

* Packages:
	- numpy:             1.22.2
	- pyTorch_debug:     False
	- pyTorch_version:   1.11.0+cu113
	- pytorch-lightning: 1.5.10
	- tqdm:              4.63.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.9.7
	- version:           #219-Ubuntu SMP Tue Aug 11 12:26:50 UTC 2020

cc @borda @carmocca @mauvilsa

**Comment by tshu-w** [comment]
@carmocca Hi, I'm a little busy now, and I will read the original issue to check if is it the same feature as what I am talking about.

**Comment by carmocca** [comment]
It is. Shorthand notation is implemented as a "hack" in Lightning by modifying `sys.argv` so it doesn't support mixing with what's provided in a configuration file.

We could try and add support but at some point it's better to stop developing this "hack" and contribute the feature to jsonargparse

**Comment by tshu-w** [comment]
In fact, I think this issue is more relevant to https://github.com/omni-us/jsonargparse/issues/113 https://github.com/omni-us/jsonargparse/issues/89. I do agree that this needs to be supported upstream though.

**Comment by quancs** [comment]
Hello, I meet this problem when I use `parser.set_defaults`.
run `python boring.py fit --print_config` will report an error `KeyError: 'No action for destination key "model.arch.init_args.input_size" to set its default.'`. 
Though, the commented lines before `"model.arch.init_args.input_size": 32,` works, but it's long and indirect.
Also, [Variable Interpolation](https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_cli.html#variable-interpolation) could not be set using `parser.set_defaults` (see the commented line after).

```python
from typing import List

import torch
from pytorch_lightning import LightningDataModule, LightningModule
from pytorch_lightning.utilities.cli import (LightningArgumentParser, LightningCLI)
from torch.utils.data import DataLoader, Dataset
from jsonargparse import lazy_instance


class Arch(torch.nn.Module):

    def __init__(self, input_size: int, output_size: int = 2) -> None:
        super().__init__()
        self.linear = torch.nn.Linear(input_size, output_size)


class RandomDataset(Dataset):

    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class MyDataModule(LightningDataModule):

    def __init__(self, input_size: int, train_transforms=None, val_transforms=None, test_transforms=None, dims=None):
        super().__init__(train_transforms=train_transforms, val_transforms=val_transforms, test_transforms=test_transforms, dims=dims)
        self.input_size = input_size

    def train_dataloader(self) -> DataLoader:
        return DataLoader(RandomDataset(self.input_size, 64), batch_size=2)

    def val_dataloader(self) -> DataLoader:
        return DataLoader(RandomDataset(self.input_size, 64), batch_size=2)

    def test_dataloader(self) -> DataLoader:
        return DataLoader(RandomDataset(self.input_size, 64), batch_size=2)


class BoringModel(LightningModule):

    def __init__(self, arch: Arch = lazy_instance(Arch), channels: List[int] = [0, 1]):
        super().__init__()
        self.arch = arch

    def forward(self, x):
        return self.arch(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


class MyCLI(LightningCLI):

    def add_arguments_to_parser(self, parser: LightningArgumentParser) -> None:
        parser.set_defaults({
            # "model.arch": {
            #     "class_path": "__main__.Arch",
            #     "init_args": {
            #         "input_size": 32,
            #     },
            # },
            "model.arch.init_args.input_size": 32,
            # "data.input_size": "${model.arch.init_args.input_size}",
        })
        return super().add_arguments_to_parser(parser)


if __name__ == '__main__':
    cli = MyCLI(BoringModel, MyDataModule, seed_everything_default=None, save_config_overwrite=True, parser_kwargs={"parser_mode": "omegaconf"})

```

**Comment by carmocca** [comment]
Opened that report in a separate issue @quancs

**Comment by quancs** [comment]
> Opened that report in a separate issue @quancs

I thought my problem is relavant to this one (both related with init_args, and may have the same solution), so I posted it in this issue. Anyway, thank you for moving it. ^^
