### ISSUE TITLE
Building Docker images is failing in master

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning#12489]
## 🐛 Bug
These CI jobs building docker images started to fail 4 hrs ago as seen at the dashboard: https://hud2.pytorch.org/ci/PyTorchLightning/pytorch-lightning/master/

- Docker / build-Conda (3.8, 1.10, 11.1)
- Docker / build-Conda (3.8, 1.8, 11.1)
- Docker / build-Conda (3.8, 1.9, 11.1)
- Docker / build-Conda (3.9, 1.11, 11.3.1)

### Environment

- PyTorch Lightning Version (e.g., 1.5.0):
- PyTorch Version (e.g., 1.10):
- Python version (e.g., 3.9):
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

cc @tchaton @rohitgr7 @akihironitta @carmocca @borda

**Comment by Borda** [comment]
Seem the creation of Conda env is broken since Friday:
```
ERROR   Could not write out repodata file '/root/miniconda3/pkgs/cache/d7a9c3aa.json': No such file or directory
```

**Comment by akihironitta** [comment]
Seems we no longer experience this issue in master, so closing this.
https://hud2.pytorch.org/ci/PyTorchLightning/pytorch-lightning/master/
