### ISSUE TITLE
Wrong usage of `DeepSpeedPlugin` in doc

### ISSUE THREAD

**Issue by ShaneTian** [PyTorchLightning/pytorch-lightning#12492]
## 📚 Documentation

You need to use key word argument `config` in `DeepSpeedPlugin`, otherwise PL use default config.
```py
DeepSpeedPlugin(config=deepspeed_config_dict_or_path)
```
wrong doc:
https://pytorch-lightning.readthedocs.io/en/1.5.10/advanced/advanced_gpu.html#custom-deepspeed-config

related code:
https://github.com/PyTorchLightning/pytorch-lightning/blob/9ebdc52ec631df92ca7cfc1ba852801dd36d3864/pytorch_lightning/plugins/training_type/deepspeed.py#L117

cc @borda @rohitgr7

**Comment by rohitgr7** [comment]
yes! feel free to send a PR to fix it :)
