### ISSUE TITLE
Make positional arguments required in the argument parser

### ISSUE THREAD

**Issue by fschlatt** [PyTorchLightning/pytorch-lightning#12503]
## 🚀 Feature

Make positional arguments required for classes passed into the `add_argparse_args` function.

### Motivation

I use the `add_argparse_args` function not only for the Trainer but also for additional classes required for my training script (e.g. the DataModule). Some arguments of the additional classes are positional and do not have suitable default values. In the current implementation, positional arguments receive a default value of `inspect._empty`, which usually leads to unforeseen errors somewhere further down the line.

### Pitch

In the ptl argument parser utilities, modify the parser such that positional arguments of a class given to the `add_argparse_args` are marked as required in the resulting ArgumentParser.

cc @borda

**Comment by carmocca** [comment]
Thanks for the suggestion!

Let me also shamelessly plug the [`LightningCLI`](https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_cli.html) which already takes care of this :purple_heart:
