### ISSUE TITLE
Trainer `strategy` argument is case sensitive

### ISSUE THREAD

**Issue by ethanwharris** [PyTorchLightning/pytorch-lightning#12526]
## 🐛 Bug

The `strategy` argument is case sensistive so `ddp` works but `DDP` doesn't.

### To Reproduce

`strategy="DDP"` gives an error that it's not in the registry...

### Additional context

This probably applies to all things using the registry, may make sense to make it case-insensitive.

**Comment by kaushikb11** [comment]
Yup, we could make it case-insensitive.
