### ISSUE TITLE
Improve error when a sequence of strings is passed to `gpus` arg in `Trainer`

### ISSUE THREAD

**Issue by krshrimali** [PyTorchLightning/pytorch-lightning#12520]
## Proposed refactor

Consider a machine where there is a single GPU, and the user passes the GPU ID as a string.

- Before refactor, doesn't tell you _clearly_ that the type was wrong and not the device availability.
- The error is also raised in the [`_sanitize_gpu_ids`](https://github.com/PyTorchLightning/pytorch-lightning/blob/6109b0b49cc1c94164bf2f40a46511096e5f655c/pytorch_lightning/utilities/device_parser.py#L170) function instead of the [`_check_data_type`](https://github.com/PyTorchLightning/pytorch-lightning/blob/6109b0b49cc1c94164bf2f40a46511096e5f655c/pytorch_lightning/utilities/device_parser.py#L229) function in the file: [`device_parser.py`](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/utilities/device_parser.py).
<table>
<tr>
<th>
Before Refactor
</th>
<th>
After Refactor
</th>
</tr>

<tr>

<td>
<pre>

```python
>>> Trainer(gpus=['0'])
... stack trace ...
MisconfigurationException: You requested gpu: ['0']
 But your machine only has: [0]
```
</pre>
</td>

<td>
<pre>

```python
>>> Trainer(gpus=['0'])
... stack trace ...
MisconfigurationException: Device ID's (GPU/TPU)
 must be int, string, or sequence of ints or None,
 but you passed a sequence of string(s)
```
</pre>
</td>

</tr>
</table>

Note that, we do get a clear error for non-iterator types, example:

```python
>>> Trainer(gpus=True)
MisconfigurationException: Device ID's (GPU/TPU) must be int, string or sequence of ints or None.
```

### Motivation

While scrolling through the codebase :)

### Pitch

Let's revise the [`_check_data_type`](https://github.com/PyTorchLightning/pytorch-lightning/blob/6109b0b49cc1c94164bf2f40a46511096e5f655c/pytorch_lightning/utilities/device_parser.py#L229) function which iterates over an iterator (if provided), and shows the error message as proposed in the above table.

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc: @carmocca

cc @justusschock @awaelchli @rohitgr7 @kaushikb11 @akihironitta @borda

**Comment by kaushikb11** [comment]
Sounds good!
