### ISSUE TITLE
Support for passing dataloader to trainer.test()

### ISSUE THREAD

**Issue by shijianjian** [PyTorchLightning/pytorch-lightning#1255]
## 🚀 Feature
```python
dl = DataLoader(...)
trainer = Trainer(...)
trainer.test(model, dl)
```

### Motivation

In most cases of mine, I got a fixed training/validation dataset but other collaborators would send me different datasets to evaluate my model. In which case, I hope not to modify the code inside the ```CoolSystem```.  I prefer to build different dataloaders for different collaborators in an ```evaluation.py```, which sounds more reasonable than putting unseen test data into the training process.

I found there are similar features in ```trainer.fit()```. I am wondering if it is possible to have this feature for ```trainer.test()```. 

### Current Solution
My current solution follows a complex way but wish to have a feature to simplify it.
```python
class MyCoolSystem(pl.lightning_module):
    ...
class CoolSystemForDataA(MyCoolSystem):
    def test_dataloader():
          # Overriden dataloaders.
```

**Comment by Borda** [comment]
Thx for your comment we are aware of this feature request, pls see #1195

**Comment by awaelchli** [comment]
This was recently added. See 
https://pytorch-lightning.readthedocs.io/en/stable/pytorch_lightning.trainer.html?highlight=test#pytorch_lightning.trainer.Trainer.test
Feel free to reopen if issues remain.

**Comment by Borda** [comment]
I think that there may be still issue as the passed dataloader is not used být `val_dataloader` instead

**Comment by awaelchli** [comment]
I cannot reproduce it. When I pass a custom test dataset, it runs on that. 
But I do think #1195 should be high priority because it could indeed cause some side effects.
