### ISSUE TITLE
Using autograd.grad twice with 16bit mixed-precision always returns NaN values.

### ISSUE THREAD

**Issue by joshua840** [PyTorchLightning/pytorch-lightning#12600]
## 🐛 Bug

Using `autograd.grad` twice with 16bit mixed-precision returns NaN values, while the same calculation with 32bit mixed-precision doesn't. This phenomenon can easily be reproduced. 

- 16bit mixed-precision: (`pl.Trainer.from_argparse_args(args, precision=16)`)
  - `tensor([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], device='cuda:0')` 
- 32bit mixed-precision:  (`pl.Trainer.from_argparse_args(args, precision=32)`)
  - `tensor([ 3.6491e-07, -2.1480e-07,  6.6031e-07,  1.9925e-06,  2.2461e-06, -4.7170e-07, -8.1581e-07,  3.6208e-06, -1.4615e-06,  6.3490e-07], device='cuda:0')`.

``` python
    def training_step(self, batch, batch_idx):
        x, y = batch
        x.requires_grad = True

        logit = self(x)
        loss = F.cross_entropy(logit, y, reduction="mean")

        grad1 = torch.autograd.grad(loss, x, retain_graph=True, create_graph=True)[0]
        v = torch.randn_like(x)
        grad2 = torch.autograd.grad(torch.einsum("nchw,nchw->n", grad1, v).sum(), x, retain_graph=True)[0]

        print(grad2.flatten()[:10])

        return loss
```

### To Reproduce
The whole reproducible code is given here. The following code is a standard ImageNet training code, and I added the second derivation calculation in the training step.

- Running code (You need a Imagenet dataset to run this code)
``` bash
python3 main.py --gpu 1 --data_dir 'path/to/ImageNet/dir'
```

- main.py
``` python
from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter

import pytorch_lightning as pl

from pl_classifier import LitClassifier
from data_module import ImageNetDataModule


def cli_main():
    # ------------ args -------------
    parser = ArgumentParser(add_help=True, formatter_class=ArgumentDefaultsHelpFormatter)
    parser.add_argument("--data_dir", default="/Data/ImageNet", type=str, help="directory of imagenet dataset")
    parser = pl.Trainer.add_argparse_args(parser)
    args = parser.parse_args()

    pl.seed_everything(1234)

    # ------------ data -------------
    data_module = ImageNetDataModule(data_dir=args.data_dir,)

    # ------------ trainer -------------
    trainer = pl.Trainer.from_argparse_args(args, precision=16, gradient_clip_val=2.0,)
    # trainer = pl.Trainer.from_argparse_args(args, precision=32, gradient_clip_val=2.0,)

    # ------------ model -------------
    model = LitClassifier(**vars(args))

    # ------------ run -------------
    trainer.fit(model, datamodule=data_module)
    trainer.test(model, dataloaders=data_module)


if __name__ == "__main__":
    cli_main()

```

- data_module.py
``` python
import os
import pytorch_lightning as pl
from torchvision import transforms
from torch.utils.data import DataLoader
from torchvision.datasets import ImageFolder


class ImageNetDataModule(pl.LightningDataModule):
    def __init__(self, data_dir: str = "/Data/ImageNet"):
        super().__init__()
        self.save_hyperparameters()
        self.data_dir = data_dir

    def prepare_data(self):
        pass

    def setup(self, stage=None):
        train_dir = os.path.join(self.data_dir, "train")
        val_dir = os.path.join(self.data_dir, "val")

        normalize = transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))

        train_transform = transforms.Compose(
            [transforms.RandomResizedCrop(224), transforms.RandomHorizontalFlip(), transforms.ToTensor(), normalize]
        )

        val_transform = transforms.Compose(
            [transforms.Resize(256), transforms.CenterCrop(224), transforms.ToTensor(), normalize]
        )

        self.train_dataset = ImageFolder(train_dir, transform=train_transform)
        self.test_dataset = ImageFolder(val_dir, transform=val_transform)

    def train_dataloader(self):
        return DataLoader(dataset=self.train_dataset, batch_size=128, shuffle=True, num_workers=4, pin_memory=True,)

    def val_dataloader(self):
        return DataLoader(dataset=self.test_dataset, batch_size=100, shuffle=False, num_workers=4, pin_memory=True,)

    def test_dataloader(self):
        return self.val_dataloader()

    def predict_dataloader(self):
        return self.val_dataloader()

```
- pl_classifier.py
``` python
import torch
import torch.nn.functional as F
import pytorch_lightning as pl

from torchvision.models import resnet18


class LitClassifier(pl.LightningModule):
    def __init__(self, **kwargs):
        super().__init__()
        self.save_hyperparameters()

        self.model = resnet18()

    def forward(self, x):
        x = self.model(x)
        return x

    def training_step(self, batch, batch_idx):
        x, y = batch
        x.requires_grad = True

        logit = self(x)

        loss = F.cross_entropy(logit, y, reduction="mean")

        grad1 = torch.autograd.grad(loss, x, retain_graph=True, create_graph=True)[0]
        v = torch.randn_like(x)
        grad2 = torch.autograd.grad(torch.einsum("nchw,nchw->n", grad1, v).sum(), x, retain_graph=True)[0]

        print(grad2.flatten()[:10])

        return loss

    def validation_step(self, batch, batch_idx):
        pass

    def test_step(self, batch, batch_idx):
        pass

    def configure_optimizers(self):
        optim = torch.optim.AdamW(self.parameters(), lr=1e-3, weight_decay=1e-2)

        return [optim], []

```

### Expected behavior
NaN is not printed when 16bit mixed-precision is used.

### Environment

* CUDA:
        - GPU:
                - NVIDIA TITAN Xp
                - NVIDIA TITAN Xp
                - NVIDIA TITAN Xp
                - NVIDIA TITAN Xp
        - available:         True
        - version:           11.1
* Packages:
        - numpy:             1.20.3
        - pyTorch_debug:     False
        - pyTorch_version:   1.9.1
        - pytorch-lightning: 1.5.10
        - tqdm:              4.62.3
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.11
        - version:           #101~18.04.1-Ubuntu SMP Fri Oct 22 09:25:04 UTC 2021

The same phenomena occurs in the following envs.

* CUDA:
        - GPU:
                - RTX A5000
                - RTX A5000
                - RTX A5000
                - RTX A5000
        - available:         True
        - version:           11.1
* Packages:
        - numpy:             1.20.3
        - pyTorch_debug:     False
        - pyTorch_version:   1.9.1
        - pytorch-lightning: 1.5.10
        - tqdm:              4.62.3
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.11
        - version:           #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021

Also, the same for the following env.

* CUDA:
        - GPU:
                - NVIDIA TITAN Xp
                - NVIDIA TITAN Xp
                - NVIDIA TITAN Xp
                - NVIDIA TITAN Xp
        - available:         True
        - version:           10.2
* Packages:
        - numpy:             1.21.2
        - pyTorch_debug:     False
        - pyTorch_version:   1.11.0
        - pytorch-lightning: 1.6.0
        - tqdm:              4.63.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.13
        - version:           #101~18.04.1-Ubuntu SMP Fri Oct 22 09:25:04 UTC 2021

cc @carmocca @justusschock @awaelchli @akihironitta @rohitgr7

**Comment by akihironitta** [comment]
Hi @joshua840! AFAIK, using fp16 can be very unstable during training due to its small range compared to fp32. Instead, I'd use bfloat16 which has the same number of exponential bits as fp32 (https://pytorch.org/docs/stable/tensors.html#id5).

```python
Trainer(..., precision="bf16")
```

**Comment by joshua840** [comment]
Hi @akihironitta! Thank you for your very helpful reply. I think you are right and I will try bfloat16 instead of float16. I will close this issue now.
