### ISSUE TITLE
WandbLogger name return the project name rather than the run/exp name

### ISSUE THREAD

**Issue by tshu-w** [PyTorchLightning/pytorch-lightning#12603]
## 🐛 Bug

`self._experiment.project_name()` is not the `self._name` but `self._project`

https://github.com/PyTorchLightning/pytorch-lightning/blob/7d1075d2116f8ceda9f7bf12cc083fbc1eb0f32e/pytorch_lightning/loggers/wandb.py#L450

### To Reproduce

```ipython
In [1]: import wandb
   ...:
   ...: run = wandb.init(project="lightning-template", entity="wangtianshu", name="run-name")
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Currently logged in as: wangtianshu (use `wandb login --relogin` to force relogin)
wandb: Tracking run with wandb version 0.12.11
wandb: Run data is saved locally in /home1/wangtianshu/lightning-template/wandb/run-20220404_171224-1z8az7jn
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run run-name
wandb: ⭐️ View project at https://wandb.ai/wangtianshu/lightning-template
wandb: 🚀 View run at https://wandb.ai/wangtianshu/lightning-template/runs/1z8az7jn

In [2]: run.project_name()
Out[2]: 'lightning-template'

In [3]: run.name
Out[3]: 'run-name'
```

### Expected behavior

`wandb_logger.name` return then correct name rather than project name.

### Environment

* Packages:
	- numpy:             1.22.2
	- pyTorch_debug:     False
	- pyTorch_version:   1.11.0+cu113
	- pytorch-lightning: 1.6.0
	- tqdm:              4.63.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.9.7
	- version:           #177-Ubuntu SMP Thu Feb 3 10:50:38 UTC 2022

cc @awaelchli @morganmcg1 @AyushExel @borisdayma @scottire @manangoel99

**Comment by akihironitta** [comment]
Closing this in favour of #12157.

**Comment by tshu-w** [comment]
@manangoel99 Hi, I have made a PR for it. Can you take a look at it?
