### ISSUE TITLE
PyTorch Lightning 1.6 + Rich 12.2 leads to version conflict in Colab

### ISSUE THREAD

**Issue by adamgayoso** [PyTorchLightning/pytorch-lightning#12626]
## 🐛 Bug

```
!pip install pytorch-lightning
!pip install rich
```

leads to

```
ContextualVersionConflict: (typing-extensions 3.10.0.2 (/usr/local/lib/python3.7/dist-packages), Requirement.parse('typing-extensions<5.0,>=4.0.0; python_version < "3.9"'), {'rich'})
```

in Colab. Notebook [here](https://colab.research.google.com/drive/1eDZr3xEVRq8tUf3OywrewvRLxAm-B9l1?usp=sharing)

### To Reproduce

See notebook above

### Expected behavior

No error :)

### Environment

Colab

- PyTorch Lightning Version (e.g., 1.5.0): 1.6.0
- PyTorch Version (e.g., 1.10): 1.10
- Python version (e.g., 3.9):
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context
<img width="1991" alt="Screen Shot 2022-04-05 at 5 11 21 PM" src="https://user-images.githubusercontent.com/10859440/161871072-54d52f7b-78fa-4bb8-9567-92bd184ff21a.png">

cc @kaushikb11 @rohitgr7

**Comment by akihironitta** [comment]
Hi @adamgayoso! Thanks for reporting this!

In short, would you mind trying resetting the kernel after installation?

---

By default, Google Colab has an old version of `typing-extensions` which *seems* incompatible with rich installed as the error suggests:
```
ContextualVersionConflict: (typing-extensions 3.10.0.2 (/usr/local/lib/python3.7/dist-packages), Requirement.parse('typing-extensions<5.0,>=4.0.0; python_version < "3.9"'), {'rich'})
```

After installing rich, you'll find a new version of `typing-extensions` installed in the env:
```
!pip list|grep typing-extensions
typing-extensions             4.1.1
```

And then, in Colab, users need to reset the kernel once they installed something on their own to use the installed version of packages.

**Comment by akihironitta** [comment]
@adamgayoso Please let us know if the issue's resolved and feel free to reopen this issue :]

**Comment by adamgayoso** [comment]
Thanks!
