### ISSUE TITLE
model summarize can not log to stdout

### ISSUE THREAD

**Issue by vincentzlt** [PyTorchLightning/pytorch-lightning#1263]
https://github.com/PyTorchLightning/pytorch-lightning/blob/ac6692d3e48084bc563e0e9001062edf168668c5/pytorch_lightning/core/lightning.py#L1446

during training, the default model summarize function can not log the model summary information to stdout. I guess is because of the logger is not referring to the actual logger.

**Comment by jeremyjordan** [comment]
if you look at the imports, you'll see
https://github.com/PyTorchLightning/pytorch-lightning/blob/ac6692d3e48084bc563e0e9001062edf168668c5/pytorch_lightning/core/lightning.py#L17

which you can trace back to here
https://github.com/PyTorchLightning/pytorch-lightning/blob/ac6692d3e48084bc563e0e9001062edf168668c5/pytorch_lightning/__init__.py#L15

did you configure logging in your project?

a simple check: (add this to your root `__init__.py`)
```
import logging
logging.basicConfig(level=logging.INFO)
```

**Comment by vincentzlt** [comment]
Thanks. It works when I added the codes to `__init__.py`.

But it was still strange why it can not log under default settings.. If nobody else have the same issue, please close this issue.

**Comment by jeremyjordan** [comment]
this was addressed in #1267, closing issue. thanks :)
