### ISSUE TITLE
Warning of ambiguous batch size when using torchmetrics

### ISSUE THREAD

**Issue by Qcactus** [PyTorchLightning/pytorch-lightning#12640]
## 🐛 Bug

When I use torchmetrics with some "ambiguous batch size" data, the batch size for each update step can be handled by using torchmetrics API, so pytorch lightning does not need to know the batch size. But lightning always gives me warnings like "UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 1. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`."

Sorry I don't much time to provide codes for this. I think this might be a bug and hope that you can fix it.

cc @carmocca @edward-io @ananthsub @rohitgr7 @kamil-kaczmarek @Raalsky @Blaizzy

**Comment by rohitgr7** [comment]
hey @Qcactus !

can you share the code snippet for the log call?

**Comment by Qcactus** [comment]
This is an example using torch_geometric dataset and dataloader. The batch size of input data is not explicit, but it can be obtained from `batch.num_graphs`. I pass it into the update method of MeanMetric.

```python
import os
import torch
from pytorch_lightning import LightningModule, Trainer
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader
from torchmetrics import MeanMetric


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(1, 1)
        self.train_loss_metric = MeanMetric()

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch.x).sum()
        self.train_loss_metric(
            loss, batch.num_graphs
        )  # batch size (batch.num_graphs) specified when updating the metric
        self.log("train_loss", loss)
        return {"loss": loss}

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        limit_test_batches=1,
        num_sanity_val_steps=0,
        max_epochs=1,
        enable_model_summary=False,
    )
    trainer.fit(
        model,
        train_dataloaders=(
            DataLoader(
                dataset=[
                    Data(x=torch.Tensor([[1], [2]])),
                    Data(x=torch.Tensor([[1], [2]])),
                    Data(x=torch.Tensor([[1], [2]])),
                ],
                batch_size=2,
            )
        ),
    )


if __name__ == "__main__":
    run()
```

Output:
```
UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 1. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`
```

**Comment by carmocca** [comment]
@Qcactus Try `self.log("train_loss", self.train_loss_metric, batch_size=batch.num_graphs)`

**Comment by rohitgr7** [comment]
the above code-snippet is not throwing any warning on v1.6. Must have been fixed. Closing the issue. Feel free to reopen if it comes up again :)
