### ISSUE TITLE
Sample sequentially from multiple `DataLoaders` in `LightningDataModule`

### ISSUE THREAD

**Issue by jlehrer1** [PyTorchLightning/pytorch-lightning#12650]
## 🚀 Feature

Currently, the `LightningDataModule` handles multiple `DataLoaders` but returns either a list of batch samples, or a dictionary of batch samples. What I would like is a new functionality, in which we can sample sequentially from multiple `DataLoaders` instead of the default of sampling in combination.

### Motivation
Although we most commonly applying transforms directly to the data in our `Dataset` class, there are cases where the transform is much faster to apply batch-wise. This can easily be done by writing a custom collate function, but in the case where the transform is dependent on an underlying attribute of the `Dataset`, we can't use a `ConcatDataset` and then create the `DataLoader`. 

### Pitch
Either we should modify `train_dataloader, val_dataloader, test_dataloader` methods of `LightningDataModule` such that we can choose sequential/combined batch sampling, or create a new class that works with `LightningDataModule` and handles sequential sampling from multiple dataloaders. 

### Additional context

I've seen [#1089](https://github.com/PyTorchLightning/pytorch-lightning/issues/1089), the AlternateIterator from [here](https://gist.github.com/Dref360/2524e524244569ed47428f19c487f264) and [#2457](https://github.com/PyTorchLightning/pytorch-lightning/issues/2457), but none of these address sequential sampling from >2 dataloaders. 

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

**Comment by tshu-w** [comment]
Currently, the following works fine for me: (maybe related to https://github.com/PyTorchLightning/pytorch-lightning/issues/10696.)
```python
from torch.utils.data import DataLoader


class SequentialLoader:
    def __init__(self, *dataloaders: DataLoader):
        self.dataloaders = dataloaders

    def __len__(self):
        return sum(len(d) for d in self.dataloaders)

    def __iter__(self):
        for dataloader in self.dataloaders:
            yield from dataloader
```

```python
    def train_dataloader(self) -> TRAIN_DATALOADERS:
        dataloaders = (
            DataLoader(
                dataset=dataset,
                batch_size=self.hparams.batch_size,
                num_workers=self.hparams.num_workers,
                pin_memory=self.hparams.pin_memory,
                collate_fn=self.collate_fn,
                persistent_workers=self.hparams.num_workers > 0,
                shuffle=True,
            )
            for dataset in self.datasets
        )
        return SequentialLoader(*dataloaders)
```

**Comment by jlehrer1** [comment]
Thanks! Soon after opening this issue I actually figured it out, lol. An alternative `__iter__` method is 
```
    def __iter__(self):
        yield from functools.chain(*self.dataloaders)
```

**Comment by marcmk6** [comment]
I don't understand why this functionality of chaining `DataLoader`s is not implemented in neither Pytorch nor lightning. It's not technically hard and pretty useful in certain cases.
It really took me a while to reach the solution and it turns out the only part I missed is `__len__` for mimicking a `DataLoader`.
