### ISSUE TITLE
Lightning swallows errors

### ISSUE THREAD

**Issue by alok** [PyTorchLightning/pytorch-lightning#12674]
## 🐛 Bug

During training, if there's some logic error (say a KeyError loading some data), then lightning will end the run but not bubble up the original error.

I end up having to run in a debugger and step through manually, which is a pain.

**Comment by ananthsub** [comment]
Are you sending a keyboard interrupt when using lightning interactively? If not, all exceptions are re-raised here: https://github.com/PyTorchLightning/pytorch-lightning/blob/f3e7e91f64ce003f933d266f73c81c9d6a8f7f9b/pytorch_lightning/trainer/trainer.py#L650-L682

**Comment by alok** [comment]
turned out to be an issue deeper in the guts of the application, not lightning
