### ISSUE TITLE
Lightning CLI not working with WandbLogger

### ISSUE THREAD

**Issue by cifkao** [PyTorchLightning/pytorch-lightning#12714]
## 🐛 Bug

Using Lightning CLI with `--trainer.logger=WandbLogger` results in the following error:

```
ValueError: Value "Namespace(class_path='pytorch_lightning.loggers.WandbLogger', init_args=Namespace(agg_default_func=None, agg_key_funcs=None, anonymous=None, experiment=None, id=None, log_model=False, name=None, offline=False, prefix='', project=None, save_dir='/tmp/save_dir', version=None))" does not validate against any of the types in typing.Union[pytorch_lightning.loggers.base.LightningLoggerBase, typing.Iterable[pytorch_lightning.loggers.base.LightningLoggerBase], bool]:
  - init() got an unexpected keyword argument 'agg_key_funcs'
  - Expected a List but got "Namespace(class_path='pytorch_lightning.loggers.WandbLogger', init_args=Namespace(agg_default_func=None, agg_key_funcs=None, anonymous=None, experiment=None, id=None, log_model=False, name=None, offline=False, prefix='', project=None, save_dir='/tmp/save_dir', version=None))"
  - Expected a <class 'bool'> but got "Namespace(class_path='pytorch_lightning.loggers.WandbLogger', init_args=Namespace(agg_default_func=None, agg_key_funcs=None, anonymous=None, experiment=None, id=None, log_model=False, name=None, offline=False, prefix='', project=None, save_dir='/tmp/save_dir', version=None))"
```

### To Reproduce

https://colab.research.google.com/gist/cifkao/eb6b18cf2b30f9b617b5cdc3146a1cb1/bug_report_model.ipynb

### Environment

* CUDA:
	- GPU:
		- Tesla K80
	- available:         True
	- version:           11.1
* Packages:
	- numpy:             1.21.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.10.0+cu111
	- pytorch-lightning: 1.6.0
	- tqdm:              4.63.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.13
	- version:           # 1 SMP Tue Dec 7 09:58:10 PST 2021

cc @awaelchli @morganmcg1 @AyushExel @borisdayma @scottire @manangoel99 @carmocca @mauvilsa

**Comment by tshu-w** [comment]
@cifkao Hi, this is the same as https://github.com/PyTorchLightning/pytorch-lightning/issues/12529

**Comment by cifkao** [comment]
Is there any workaround?

**Comment by tshu-w** [comment]
You can discard redundant parameters introduced by `jsonargparse` in `before_instantiate_classes` of `CLI`, see: 
https://github.com/tshu-w/universal-blocker/blob/7c14c498f1926a51ee5192edbd333dbca1f10f16/src/utils/lit_cli.py#L50-L52

**Comment by cifkao** [comment]
@tshu-w Thanks, but your repo seems to be private.

**Comment by cifkao** [comment]
Workaround:
```python
def before_instantiate_classes(self):
    config = self.config[self.subcommand]
    logger = config.trainer.logger
    del logger.init_args.agg_key_funcs, logger.init_args.agg_default_func
```
