### ISSUE TITLE
bug(tqdm): creating multiple rows after 70%

### ISSUE THREAD

**Issue by AmitMY** [PyTorchLightning/pytorch-lightning#1273]
## 🐛 Bug

When I run a training loop, every epoch it would do `tqdm` well until roughly 70%, and then create more rows until finished:
![image](https://user-images.githubusercontent.com/5757359/77832032-08f1ca80-7144-11ea-8bdd-f81308da24c2.png)

### Expected behavior

No new `tqdm` rows

### Environment

```
cuda:
	GPU:
		GeForce GTX 1080 Ti
	available:           True
	version:             10.1
packages:
	numpy:               1.18.1
	pyTorch_debug:       False
	pyTorch_version:     1.4.0
	pytorch-lightning:   0.7.1
	tensorboard:         2.1.0
	tqdm:                4.43.0
system:
	OS:                  Linux
	architecture:
		64bit
		
	processor:           x86_64
	python:              3.7.6
	version:             #1 SMP Fri Dec 6 15:49:49 UTC 2019
```

### Additional context

Running this using PyCharm, not directly on the terminal.

This seems to happen directly in the terminal as well, in tmux

**Comment by Borda** [comment]
@AmitMY can you please share example code or is it happening also on our examples?

**Comment by awaelchli** [comment]
Hi, I would like to know if this is still an issue for you. I am running the latest version of PyCharm and it works fine. I also observed this issue before and what helped was going to "Run Configurations" -> "Emulate terminal in output console".

**Comment by AmitMY** [comment]
Thanks, @awaelchli 

In run configuration under execution, If I have this setup:
![image](https://user-images.githubusercontent.com/5757359/80952175-eec1a100-8e01-11ea-8eac-36e2a40a427c.png)

I get:
![image](https://user-images.githubusercontent.com/5757359/80952558-832c0380-8e02-11ea-8a89-7945d306934b.png)

Meaning, I now don't have many rows after 70%, but rather 3 rows instead of 1 for each epoch.

I upgraded PyCharm to 2020.01, I got the same result.

**Comment by awaelchli** [comment]
Turn on "emulate terminal in output console".

**Comment by AmitMY** [comment]
My apology, but I actually can't find that option anywhere. Tried looking online, it doesn't show. Where did you set that up? 
![image](https://user-images.githubusercontent.com/5757359/80979454-0879dd00-8e30-11ea-9daf-3935e581fcd1.png)

**Comment by awaelchli** [comment]
I have it right there under "Execution", but it seems it is only showing up if configured with local interpreter. You have setup a remote interpreter. 
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360007040860-No-Emulate-terminal-in-output-console-option-in-PyCharm-for-Windows

**Comment by awaelchli** [comment]
Can you confirm the repeated progress bar is just limited to PyCharm? If you run it in the console, it works fine?

**Comment by AmitMY** [comment]
While the repeating lines after 70% did occur in the terminal, now my last "issue" indeed just has 1 line directly in the terminal - which epoch, and what evaluation metrics
