### ISSUE TITLE
[RFC] Is `fast_dev_run` still needed?

### ISSUE THREAD

**Issue by ananthsub** [PyTorchLightning/pytorch-lightning#12738]
### Motivation

This was feedback from a user:

> Hi, we found an unexpected error when training a model with fast_dev_run=True. The training finishes with single train and val steps, but writing a further outputs to the checkpoint directory fails. 

> How is fast_dev_run mode different from just setting to 1 epoch and 1 batch per epoch? My understanding is that fast_dev_run is almost equivalent to `limit_train_batches=1` and `limit_val_batches=1` (or something like that), but when I set these params instead of fast_dev_run there were no issues at all.

The issue was that within the checkpoint callback, we do not create a checkpoint directory if `fast_dev_run` is used. It is not obvious at all to users what this flag does based on the documentation. I had to grep through the Lightning codebase to see where all `fast_dev_run` takes effect. The ambiguity makes it hard to reason about. The framework is also inconsistent with this flag: should the model summary be printed? Should early stopping take effect? What about loggers or profilers? Why some but not others?

We already have Trainer flags for `max_steps`, `limit_train_batches`, `enable_checkpointing`, etc. Do we still need `fast_dev_run` on top of this?

### Pitch

Deprecate `fast_dev_run` in favor of the specific flags already offered on the Trainer?

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @justusschock @kaushikb11 @awaelchli @rohitgr7

**Comment by rohitgr7** [comment]
personally, I like this flag and won't consider removing it, but agree that it doesn't enable complete unit-testing. With checkpoint disabled, it just doesn't disable checkpoint callback, but checkpointIO, custom loggers, etc.

but still, these are some specific cases, fast_dev_run is still handy flag.

**Comment by carmocca** [comment]
IMO this is entirely a docs issue. https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html#fast-dev-run should describe all the things it enables or disables

**Comment by rohitgr7** [comment]
I think it does in the `note`.

**Comment by justusschock** [comment]
I agree that we shouldn't remove it, but maybe reconsider what is triggered and what not based on the description @ananthsub gave

**Comment by williamFalcon** [comment]
yeah, i want to keep this.
if we need to expand the functionality then we should do that.

but yes, non expert users aren't going to know to turn these 2-5 things on to get this effect. 

this is like a "shortcut" more than anything else.

so, maybe the action item is to make sure we add these other things to fast_dev_run

**Comment by carmocca** [comment]
> Why some but not others?

We skip those that would create undesired effects in future runs. You don't want the `fast_dev_run` run to pollute the logger or checkpoint directories.

**Comment by awaelchli** [comment]
I agree with the doc improvements on this one and the PR that @carmocca has put together. If we look at the list there, it becomes clear that a shorthand flag like this is needed, as manually flipping the switches on all these arguments is an inconvenience. 

Another perspective: Callbacks that produce artifacts or provide unit-test functionality can check for the trainer.fast_dev_run to be set and behave accordingly. Having a single flag makes the implementation much easier and we explicitly know the intention of the user is "testing".
