### ISSUE TITLE
Improve `LightningEnum` and its deprecation

### ISSUE THREAD

**Issue by ethanfurman** [PyTorchLightning/pytorch-lightning#12749]
## Proposed refactor

- Use the built-in `Enum` capabilities to make `LightningEnum` simpler.
- Modify and rename the `_OnAccessEnumMeta` type to only call a `deprecate()` method (it's not used for anything else.
- Create a `DeprecatedEnum` base class and use that instead of constantly setting `metaclass=...` on deprecated enums.
- Correct attribution for `_OnAccessEnumMeta` (current attribution is to a website and article that falsely claims authorship of `Enum`).

### Motivation

Fixing the attribution (which came to my attention due to [an `aenum` issue](https://github.com/ethanfurman/aenum/issues/18), and efficient use of `Enum`.

cc @justusschock @awaelchli @rohitgr7 @tchaton

**Comment by awaelchli** [comment]
@ethanfurman Is this fixing a recursion error you mention? 
Would it be better to mark this as a bugfix and include it in 1.6.x?
cc @carmocca
