### ISSUE TITLE
Utility function `_compare_version` does not compare Python version correctly

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#12752]
### To Reproduce

Open a Python environment with Python >= 3.8
Run the following code:

```
adrian@quantumgrid ~/r/pytorch-lightning (feature/callback-entry-points)> python --version                                                         (lightning) 
Python 3.8.11

adrian@quantumgrid ~/r/pytorch-lightning (feature/callback-entry-points)> python                                                                   (lightning) 
Python 3.8.11 (default, Aug  6 2021, 08:56:27) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pytorch_lightning.utilities.imports import _compare_version
>>> import operator
>>> _PYTHON_GREATER_EQUAL_3_8_0 = _compare_version("python", operator.ge, "3.8.0")
>>> _PYTHON_GREATER_EQUAL_3_8_0 
False


```

### Expected behavior

The above code should return True.

### Environment
* CUDA:
        - GPU:
        - available:         False
        - version:           None
* Packages:
        - numpy:             1.22.3
        - pyTorch_debug:     False
        - pyTorch_version:   1.11.0
        - pytorch-lightning: 1.7.0dev
        - tqdm:              4.64.0
* System:
        - OS:                Darwin
        - architecture:
                - 64bit
                - 
        - processor:         i386
        - python:            3.8.11
        - version:           Darwin Kernel Version 19.6.0: Thu Jan 13 01:26:33 PST 2022; root:xnu-6153.141.51~3/RELEASE_X86_64

### Additional context

cc @borda @akihironitta

**Comment by Borda** [comment]
It is kind of expected, and so badly communicated t user/dev this version compare applies only to python packages not python as interpreter itself... this would need to e added to the func scope

**Comment by awaelchli** [comment]
This is caused by #12753

@Borda I can reproduce the same outside the Python interpreter, in a regular script invoked via python.

**Comment by awaelchli** [comment]
`_PYTHON_GREATER_EQUAL_3_8_0` is used only internally in our tests, so it doesn't affect users. Not a priority just wanted to point this out as I saw a need for this recently when wanting to write a test.

**Comment by HeyQXX** [comment]
Hi! Is there any solution to this bug now? Except for waiting for version 1.6.2

**Comment by Borda** [comment]
> Except for waiting for version 1.6.2

yes :)
