### ISSUE TITLE
Implementation of Efficient-Net and Efficient-Det in Pytorch Lightning

### ISSUE THREAD

**Issue by bilel-bj** [PyTorchLightning/pytorch-lightning#1276]
## 🚀 Feature
Implementation of Efficient-Net and Efficient-Det in Pytorch Lightning

### Motivation

These two algorithms are the state of the art in Image classification and Object detection. Providing an implementation in Pytorch LIghtning will attract many data scientist to adopt this promising framework

### Alternatives

https://paperswithcode.com/paper/efficientdet-scalable-and-efficient-object

**Comment by rohitgr7** [comment]
I think they are working on it. https://twitter.com/PyTorchLightnin/status/1242774793126100992

**Comment by bilel-bj** [comment]
> I think they are working on it. https://twitter.com/PyTorchLightnin/status/1242774793126100992

Do you know when it is estimated to be delivered?

**Comment by rohitgr7** [comment]
> > I think they are working on it. https://twitter.com/PyTorchLightnin/status/1242774793126100992
> 
> Do you know when it is estimated to be delivered?

No idea.
