### ISSUE TITLE
pytorch_lightning.trainer.trainer.Trainer.validate() -- redundant trainer.trainer reference?

### ISSUE THREAD

**Issue by rasbt** [PyTorchLightning/pytorch-lightning#12767]
Is the double `trainer.trainer` intentional [here](https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.trainer.trainer.Trainer.html#pytorch_lightning.trainer.trainer.Trainer.validate), or is it a Sphinx import artifact? 

![Screen Shot 2022-04-14 at 7 16 53 PM](https://user-images.githubusercontent.com/5618407/163496373-54dee8c9-5b74-4cec-92c0-0e95ae1afde8.png)

cc @borda @rohitgr7

**Comment by awaelchli** [comment]
Thanks for spotting this formatting issue. Prefixing this with a tilde (~) will properly hide the long path and only link the method.
