### ISSUE TITLE
Trainer.status set after call to Strategy.launch

### ISSUE THREAD

**Issue by jgbos** [PyTorchLightning/pytorch-lightning#12779]
I was looking at making a custom DDP launcher and noticed that `Trainer.status` is no longer set so that I know whether we are fitting or testing in `_call_children_scripts`.  Could we get the trainer status set before this call?

cc @borda @justusschock @awaelchli @ninginthecloud @rohitgr7

**Comment by awaelchli** [comment]
Hey @jgbos 

I believe your request is totally reasonable, however I think it doesn't fit our current design very well. What if you checked the function that gets passed into the launcher? A lookup like this should work:

def launch(self, function, *args, **kwargs):
    if function.__name__ == "_fit_impl":
        # do something when fit is called
    if function.__name__ == "_validate_impl":
        # do something when validate is called
    # etc.

Although granted, reyling on the protected name is not the most robust solution.
Let me know what you think.

**Comment by jgbos** [comment]
Thanks @awaelchli, that is very helpful and appears to be working.
