### ISSUE TITLE
Incorrect progress rate (steps/iter) in TQDM Progress bar

### ISSUE THREAD

**Issue by ductai199x** [PyTorchLightning/pytorch-lightning#12787]
## 🐛 Bug

The new TQDM Progress Bar update (from 1.5.0 to 1.6.1) seemed to have broken the progress rate (steps/iter) - shown below

![pytorch-lightning bug](https://user-images.githubusercontent.com/29772899/163727275-5eba0781-0303-490c-a079-ee4e74552993.gif)

### To Reproduce

Run training (`trainer.fit(model, train_dl, val_dl)`) on any model for a long time

### Expected behavior

You can see that the tick rate (step) is much quicker than 6s. I took another look and it seems to take the total amount of time then divide by the "it" number. But this is misleading since:

1. The "it" number is ONLY for ONE epoch while the total time is for all epochs up to the current one
2. The training process also includes running validation batches - which is not included in the "it" number.

_I think we should reverse this change in TQDM Progress Bar behavior because it does not add any information to the researcher while introducing confusion._

### Environment

- PyTorch Lightning Version (e.g., 1.5.0): 1.6.1
- PyTorch Version (e.g., 1.10): 1.11.0+cu113
- Python version (e.g., 3.9): 3.9.10
- OS (e.g., Linux): Ubuntu 20.04
- CUDA/cuDNN version: 11.6 CUDA, 8.4.3 CuDNN
- How you installed PyTorch (`conda`, `pip`, source): pip

cc @tchaton @rohitgr7 @awaelchli

**Comment by ductai199x** [comment]
Here's where it shows negative rate:
![pytorch-lightning bug2](https://user-images.githubusercontent.com/29772899/164067928-67d9159f-ad7c-40a7-9d5b-1b180e37baaa.gif)

**Comment by KimbingNg** [comment]
The `total` property is modified directly instead of calling ` self.main_progress_bar.reset`, which makes the `last_print_t` attribute of `main_progress_bar` is not updated correctly and causes this issue.   https://github.com/PyTorchLightning/pytorch-lightning/blob/1233554e73303f4f3d30f9a9219e2aa8c3f6a467/pytorch_lightning/callbacks/progress/tqdm_progress.py#L262

cc @carmocca

**Comment by ductai199x** [comment]
@carmocca @awaelchli Could anyone in the team take a quick look at this bug? I know it's does not make PL 100% unusable but this is preventing users from using new features in PL 1.6. Thank you very much in advance!

**Comment by rohitgr7** [comment]
hey @ductai199x !

would you mind trying out #12889 and checking if it fixes your issue?
