### ISSUE TITLE
Fitting only works the first time

### ISSUE THREAD

**Issue by thomasahle** [PyTorchLightning/pytorch-lightning#12789]
## 🐛 Bug

Reusing a Trainer on different model instances only fits the first model.

I'm unsure exactly what state a Trainer object keeps. It feels like an immutable class that shouldn't behave differently depending on whether I already used it to fit something else.

### To Reproduce

https://colab.research.google.com/drive/1Md3lyREm0biHaq9hn5uh4I9EmpE2DZM_?usp=sharing

I just added this:

    model = BoringModel()
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
    trainer.test(model, dataloaders=test_data)
    model2 = BoringModel()
    trainer.fit(model2, train_dataloaders=train_data, val_dataloaders=val_data)
    trainer.test(model2, dataloaders=test_data)

### Expected behavior

I would expect both model to train and report about the same error.
Instead it only fits the first model, so the second one goes completely untrained.

I couldn't find any documentation of this behaviour, so I consider it a bug.
Even if it is intended, it opens questions such as "what happens if I test the same model twice?"

### Environment

* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           11.1
* Packages:
	- numpy:             1.21.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.10.0+cu111
	- pytorch-lightning: 1.6.1
	- tqdm:              4.64.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.13
	- version:           #1 SMP Tue Dec 7 09:58:10 PST 2021

cc @justusschock @kaushikb11 @awaelchli @borda @ananthsub @ninginthecloud @jjenniferdai @rohitgr7 @akihironitta

**Comment by ZENGYIMING-EAMON** [comment]
Just a thought. Is there anything like trainer end/reset or just create a new trainer will solve this?

**Comment by thomasahle** [comment]
Creating a new trainer fixes this.

In my application I train a bunch of models, then run a bunch of tests on all of them.

It's not even clear to me if I need to keep all the trainers around for testing? Or if I just need to use different trainers for each fit, but then can reuse the last one for all the testing?

**Comment by carmocca** [comment]
>  It feels like an immutable class that shouldn't behave differently depending on whether I already used it to fit something else.

This is far from the case. The trainer is VERY stateful.

You should only reuse the same instance if the same model is passed and you want to continue the previous run or checkpoint.

For example, you to re-run for 2 extra epochs, you need to modify the state

```python
model = ....
trainer = Trainer(max_epochs=2)
trainer.fit(model)
# if you don't do this, the next fit call will not run
# any training because the 2 max epochs have already happened
trainer.fit_loop.max_epochs = 4
trainer.fit(model)
```

**Comment by thomasahle** [comment]
@carmocca What about running `trainer.test`, should I also make a new trainer every time I do that? Should it be the same trainer as was used to fit the model?
Sorry for all the questions. If you can refer me to a place with information about this, I'll happily read it.

**Comment by carmocca** [comment]
> should I also make a new trainer every time I do that?

You don't need to, as the concept of `max_epochs` only applies to `fit`.

> Should it be the same trainer as was used to fit the model?

Only if you want `trainer.test(ckpt_path="best")` to work, otherwise it's not necessary.

Closing, feel free to ask any further questions
