### ISSUE TITLE
Rich progress bar doesn't play nicely with other prints

### ISSUE THREAD

**Issue by RuRo** [PyTorchLightning/pytorch-lightning#12824]
## 🐛 Bug

Some internal printing mechanisms don't play nicely with RichProgressBar.
This can result in the progress bar getting interleaved into the printed data.

For example, this affects the pretty table of metrics that is printed after `Trainer.test`ing your model:
```
Testing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s  ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_loss         │    -4.4067792892456055    │
└───────────────────────────┴───────────────────────────┘
```

A similar issue can also come up, when using `RichModelSummary.summarize`.

### To Reproduce

Take the `BoringModel` sample code and add 
```
callbacks=[pl.callbacks.RichProgressBar()]
```
to the `Trainer`.

### Expected behavior

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_loss         │    -4.4067792892456055    │
└───────────────────────────┴───────────────────────────┘
Testing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s
```

### Environment

```
* CUDA:
	- GPU:
		- NVIDIA GeForce GTX 1050
	- available:         True
	- version:           11.3
* Packages:
	- numpy:             1.22.3
	- pyTorch_debug:     False
	- pyTorch_version:   1.11.0+cu113
	- pytorch-lightning: 1.6.0
	- tqdm:              4.63.2
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         
	- python:            3.10.4
	- version:           #1 SMP PREEMPT Mon Mar 28 09:16:36 UTC 2022
```

## Fix

Instead of creating a new `Console` and printing to it, `RichModelSummary.summarize` and `EvaluationLoop._print_results` should <s>check if `trainer` has a `progress_bar_callback` of type `RichProgressBar` and if so, it should use `trainer.progress_bar_callback.progress.console`.</s>

Edit: Actually a better solution might be using `rich.get_console()` instead of creating new instances of `rich.console.Console()` everywhere and if you need to change the `kwargs` (because user passed `console_kwargs` in `RichProgressBar`) use `rich.reconfigure(**console_kwargs)`.

cc @kaushikb11 @rohitgr7

**Comment by RuRo** [comment]
Also, you might want to initialize the `logging` using the Rich handler, if it is available, otherwise all the warnings and `pl.utilities.rank_zero.rank_zero_*` print functions also break the progress bars.

**Comment by carmocca** [comment]
These are both great suggestions. Would you like to work on the fixes yourself?

You can open 2 PRs. One for each of your comments

**Comment by RuRo** [comment]
Sorry, I am kind of busy right now. I am trying to submit issues as I run into them, but I don't currently have the time to properly fix them. If this issue is still not fixed in a couple of weeks, I might revisit it and submit the PRs, but for now I'll have to pass.

**Comment by carmocca** [comment]
@RuRo Can you share what rich version you have installed? `pip freeze | grep rich`

**Comment by RuRo** [comment]
@carmocca `rich==12.2.0`
