### ISSUE TITLE
Printing evaluation results gives unicode decode error

### ISSUE THREAD

**Issue by alvitawa** [PyTorchLightning/pytorch-lightning#12823]
## 🐛 Bug

![image](https://user-images.githubusercontent.com/10909323/164244696-c2614841-9c25-45c5-adbd-9d67acd3f553.png)

Certain terminals only support latin-1 but the character used for pretty printing the results table is outside this range.

This line is the culprit: https://github.com/PyTorchLightning/pytorch-lightning/blob/4930561556418cf4c44dae74a436ca43417e4ec6/pytorch_lightning/loops/dataloader/evaluation_loop.py#L387

It should be changed to a normal dash "-"

cc @awaelchli @rohitgr7

**Comment by carmocca** [comment]
Hi! This character was chosen on purpose because it leaves no spaces when used consecutively:
`----` vs `────`

But we can check if the terminal does not support it, and then fall back to the normal dash.

Are you interested in working on a fix?

**Comment by alvitawa** [comment]
I did a quick swoop of the codebase for non-ascii characters and with
`find | while read in; do LC_ALL=C grep '[^ -~]' $in;  "$in"; done`
And this seems to be the only place where this issue can be a problem.

How about just:
```
               bar_character = "-"
                try:
                    unicode_dash = "─"
                    unicode_dash.encode(sys.stdout.encoding)
                    bar_character = unicode_dash
                except UnicodeEncodeError:
                    pass
                bar = bar_character * term_size
```

Seems like it should be foolproof

**Comment by alvitawa** [comment]
Here is a pull request https://github.com/PyTorchLightning/pytorch-lightning/pull/12828

The method works for my non-unicode terminal

**Comment by jgbos** [comment]
Thank you @alvitawa for finding this! I was getting this error on SLURM but only on the rank zero node with no helpful traceback.
