### ISSUE TITLE
Raise a error [ZeroDivisionError: float division by zero] at trainer/connectors/data_connector.py

### ISSUE THREAD

**Issue by Ryyyc** [PyTorchLightning/pytorch-lightning#12830]
### To Reproduce

Use a data loader with no data, i.e., `len(dataloader) == 0`.

### Expected behavior

Raise error `ZeroDivisionError: float division by zero`.

### Environment

- PyTorch Lightning Version (e.g., 1.5.0):  1.6.1
- PyTorch Version (e.g., 1.10): 1.10.2
- Python version (e.g., 3.9): 3.9.12
- OS (e.g., Linux): Windows
- CUDA/cuDNN version: CUDA 11.3
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source): conda
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

Hey guys, PyTorchLightning has helped me simplify a lot of my model training work, and it's really great!

Today I ran into an error which `ZeroDivisionError: float division by zero`, after troubleshooting, I found was caused by this line of code:

https://github.com/PyTorchLightning/pytorch-lightning/blob/1233554e73303f4f3d30f9a9219e2aa8c3f6a467/pytorch_lightning/trainer/connectors/data_connector.py#L402

The path to my validation dataset was pointing to the wrong place, so `len(val_dataloader)` was 0.

So I'd like to add a check here to alert the user in a friendly way that its data loader has no data!

Thanks for all the efforts!

cc @borda @justusschock @awaelchli @ninginthecloud @rohitgr7

**Comment by rohitgr7** [comment]
good catch!
mind send a PR with the fix?

**Comment by Ryyyc** [comment]
Sorry, at the moment I'm just new to pytorch-lightning and I'm not sure where to check, throw warnings, throw exceptions from a design point of view. You guys will do a better job than me.
