### ISSUE TITLE
User Warning is missed in `pl.{}_end` function in 0.7.0

### ISSUE THREAD

**Issue by davinnovation** [PyTorchLightning/pytorch-lightning#1286]
### To Reproduce

Using `train_end` `validation_end` `test_end` above 0.7.0
mentioned in [code](https://github.com/PyTorchLightning/pytorch-lightning/blob/31b71483c47fa4aa688912b432726cdac0025a9b/pytorch_lightning/core/lightning.py#L232) as comment but not return user warning

### Expected behavior

log UserWarning as `data_loader` decorator
Example : 
`UserWarning: validation_end decorator deprecated in 0.7.0. use validation_step_end instead`

**Comment by williamFalcon** [comment]
fixed on master @Borda can you add the PR links here?
