### ISSUE TITLE
enum.Enum in hparams causes an error if used with TPU

### ISSUE THREAD

**Issue by tsuga** [PyTorchLightning/pytorch-lightning#12908]
## 🐛 Bug

My team is using python `enum.Enum` to manage hyper parameters primarily for getting better IDE support and conciseness.
It works fine with GPU training, but it causes an error with TPU training.

### To Reproduce
The essential codes are:

```
import enum
class DummyHparam(enum.Enum):
  MODEL1 = 1
  MODEL2 = 2

class LitModel(LightningModule):
    def __init__(self, channels, width, height, num_classes, hidden_size=64, learning_rate=2e-4, dummy_param=DummyHparam.MODEL1):
        super().__init__()
        self.save_hyperparameters()
```

```
[/usr/local/lib/python3.7/dist-packages/torch_xla/utils/utils.py](https://localhost:8080/#) in _for_each_instance_rewrite(value, select_fn, fn, rwmap)
    204     for k in result.__dict__.keys():
    205       v = _for_each_instance_rewrite(result.__dict__[k], select_fn, fn, rwmap)
--> 206       result.__dict__[k] = v
    207   else:
    208     rwmap[id(value)] = result

TypeError: 'mappingproxy' object does not support item assignment
```
For the complete reproducible notebook is here:
https://colab.research.google.com/drive/14uOqslWVPvteF5kVZ4WngHQ2PzNKT3_g?usp=sharing

### Expected behavior

It should not cause error as like working with GPU

### Environment

* CUDA:
        - GPU:
        - available:         False
        - version:           11.3
* Packages:
        - numpy:             1.21.6
        - pyTorch_debug:     False
        - pyTorch_version:   1.11.0+cu113
        - pytorch-lightning: 1.6.1
        - tqdm:              4.64.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - 
        - processor:         x86_64
        - python:            3.7.13
        - version:           #1 SMP Tue Dec 7 09:58:10 PST 2021

### Additional context

I'm not sure this is a bug in pytorch-lightning or torch/xla. 

cc @kaushikb11 @rohitgr7

**Comment by carmocca** [comment]
This is unsupported by XLA and mentioned in our [troubleshooting guide](https://pytorch-lightning.readthedocs.io/en/stable/accelerators/tpu.html#troubleshooting)

AFAIK there's no solution or workaround. cc @kaushikb11

**Comment by tsuga** [comment]
Thank you for your explanation.

Is it also the case for `[enum.IntEnum](https://github.com/python/cpython/blob/3.10/Lib/enum.py#L807-L808)` ?

**Comment by kaushikb11** [comment]
Yup @tsuga. I believe so. This is a blocker from XLA's end.
