### ISSUE TITLE
BasePredictionWriter: where the input predictions come from?

### ISSUE THREAD

**Issue by 2533245542** [PyTorchLightning/pytorch-lightning#12933]
Hi,

Just a quick question. I was looking into the BasePredictionWriter callback and I wonder how would the predictions passed to the callback? Is there a way to pass more parameters like the inputs, to the call back to write as well?

<img width="849" alt="image" src="https://user-images.githubusercontent.com/28517073/165993964-6704fd24-6e24-4108-a88d-0ad546ce2662.png">

https://github.com/PyTorchLightning/pytorch-lightning/blob/46c59d04db4156ae98e184e1d9321932f7e2ebf7/pytorch_lightning/callbacks/prediction_writer.py#L42

cc @rohitgr7

**Comment by rohitgr7** [comment]
predictions are passed to one of the callback hooks internally which passed them to this method.
https://github.com/PyTorchLightning/pytorch-lightning/blob/46c59d04db4156ae98e184e1d9321932f7e2ebf7/pytorch_lightning/callbacks/prediction_writer.py#L99-L119

by inputs if you mean the current batch, then the `batch` argument inside `write_on_batch_end` is what you are looking for.

**Comment by 2533245542** [comment]
Thanks Rohit! Is there a way to call on_predict_batch_end only at trainer.test()?

**Comment by rohitgr7** [comment]
for testing, there is a separate hook called `on_test_batch_end`. If follows a similar pattern. If you return the outputs from `test_step`, they will be available there.
https://github.com/PyTorchLightning/pytorch-lightning/blob/46c59d04db4156ae98e184e1d9321932f7e2ebf7/pytorch_lightning/callbacks/base.py#L217-L226

**Comment by 2533245542** [comment]
Thanks again!
