### ISSUE TITLE
After using datamodule, the consuming time of epoch in the progress bar is accumulating.

### ISSUE THREAD

**Issue by Iywie** [PyTorchLightning/pytorch-lightning#12939]
## 🐛 Bug
The problem happens after I applied datamodule.
In the progress bar, the consuming time of epoch should be reset to zero in every epoch while it is accumulating.
Thus, the estimated time turns to be wrong too.

`Epoch 37:  20%|▏| 9/45 [20:01<1:20:06, 133.50s/it, v_num=8, loss/loss=0.111, lr=0.00791]`
`Epoch 37:  36%|▋ | 16/45 [20:05<36:24, 75.34s/it, v_num=8, loss/loss=0.0933, lr=0.00789]`
`Epoch 37:  56%|█ | 25/45 [20:10<16:08, 48.41s/it, v_num=8, loss/loss=0.0831, lr=0.00786]`
`Epoch 37:  76%|██▎| 34/45 [20:14<06:33, 35.73s/it, v_num=8, loss/loss=0.102, lr=0.00783]`
`Epoch 37:  91%|██▋| 41/45 [20:18<01:58, 29.72s/it, v_num=8, loss/loss=0.110, lr=0.00781]`

### To Reproduce

`trainer.fit(model, datamodule=data)`

### Environment

- PyTorch Lightning Version 1.6.2:
- PyTorch Version 1.10:
- Python version 3.8:
- OS both windows11 and linux:
- CUDA/cuDNN version: 11.3
- GPU models and configuration: TiTanX
- How you installed PyTorch pip

**Comment by rohitgr7** [comment]
duplicate: https://github.com/PyTorchLightning/pytorch-lightning/issues/12875
