### ISSUE TITLE
Metrics: Accuracy, Precision, Recall, F1, ROC

### ISSUE THREAD

**Issue by justusschock** [PyTorchLightning/pytorch-lightning#1295]
## 🚀 Feature
Implement the following metrics (grouped since highly similar):
- [ ] Accuracy
- [ ] Precision
- [ ] Recall
- [ ] F1
- [ ] ROC

**Comment by xssChauhan** [comment]
@Borda @williamFalcon I can take this up if no one is working on it currently.

**Comment by justusschock** [comment]
there is also @cuent working on this and there is an early version in #1488
