### ISSUE TITLE
Metrics: AUC

### ISSUE THREAD

**Issue by justusschock** [PyTorchLightning/pytorch-lightning#1296]
## 🚀 Feature
Implement general AUC (to be combined with other metrics like ROC)

**Comment by NickYi1990** [comment]
just use `from sklearn.metrics import roc_auc_score`, I don't think there's any need to write this function from scratch

**Comment by justusschock** [comment]
Actually there is. Using the sklearn function involves the necessity to convert from `torch.Tensor` to `numpy.ndarray` before converting. While this is totally fine on cpu (no memory copy made here), this really causes a slow-down for gpu tensors, since it involves a GPU-sync. 
For now #1327 already implements a sklearn version, but it shall be replaced with a native torch one.
