### ISSUE TITLE
Compatability issues with PL 1.5.2 and torch

### ISSUE THREAD

**Issue by kunal-savvy** [PyTorchLightning/pytorch-lightning#12963]
## 🐛 Bug

Our team has created  lot of code using Pytorch Lightning version 1.5.2 which had inbuilt compatibility for torch 1.10. However now underlying torch is getting updated to new version automatically and gives a compatibility error. The easy fix for this is to remove PL version while doing pip install BUT that is not feasible. A lot of code is ready to be deployed & retesting it all to new version is not an option. How can we fix the PL to 1.5.2 and torch to 1.10 in our env? The env used is Google Collab

### To Reproduce

do a pip install

!pip install torchtext==0.8.0 torch==1.10.0 pytorch-lightning==1.5.2 --quiet

Gives this

torchvision 0.12.0+cu113 requires torch==1.11.0, but you have torch 1.10.0 which is incompatible.
torchaudio 0.11.0+cu113 requires torch==1.11.0, but you have torch 1.10.0 which is incompatible.

when trying to import

import pytorch_lightning as pl

gets this

SError: /usr/local/lib/python3.7/dist-packages/torchtext/_torchtext.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtESt10shared_ptrIS0_EPSo

### Expected behavior

Was working fine earlier

### Environment

You can also fill out the list below manually.
-->

- PyTorch Lightning Version (e.g., 1.5.2):
- PyTorch Version (e.g., 1.10):
- torch 1.10
- Python version (e.g., 3.9): 
- OS (e.g., Linux): Google Collab
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):pip
- If compiling from source, the output of `torch.__config__.show()`: 
- Any other relevant information:

### Additional context

Earlier it could work without specifying torch text version but now it does not work . And given a specific version of torch text ; PL is not getting imported

**Comment by ductai199x** [comment]
You can see that `torchvision` is on `0.12.0+cu113` and `torchaudio` is on `0.11.0+cu113`. Maybe some package is overriding your `torchvision` and `torchaudio`? Just as a safe precaution, I always install torch first, then PL, using commands from https://pytorch.org/get-started/locally/ or https://pytorch.org/get-started/previous-versions/ 

Your case would likely be: `pip install torch==1.10.0+cu102 torchvision==0.11.0+cu102 torchaudio==0.10.0 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by akihironitta** [comment]
Hi @kunal-savvy! You need to have compatible versions of torch-related packages installed.

Please refer to their readme for the version that is compatible with `torch==1.10.0` and check if the correct version is installed in your environment:
https://github.com/pytorch/vision#installation
https://github.com/pytorch/text#installation
