### ISSUE TITLE
[Metrics] Bleu

### ISSUE THREAD

**Issue by justusschock** [PyTorchLightning/pytorch-lightning#1301]
## 🚀 Feature
Implement BLEU

**Comment by ydcjeff** [comment]
I would like to take this if there is no one doing it right now.

**Comment by justusschock** [comment]
@ydcjeff This would be great. When you have questions or a working implementation just ping me (either on GitHub or in our slack)

**Comment by ydcjeff** [comment]
@justusschock hello,

I now have [a working implementation of bleu](https://github.com/ydcjeff/pytorch-lightning/blob/metrics/add-bleu/pytorch_lightning/metrics/bleu.py) and [testing](https://github.com/ydcjeff/pytorch-lightning/blob/metrics/add-bleu/tests/metrics/test_bleu.py). Please take a look.

**Comment by ydcjeff** [comment]
hello, any update on this?

**Comment by justusschock** [comment]
Hey @ydcjeff sorry I must have missed the notification. Can you maybe open a PR with your changes and ping me there? Then we can discuss the code line by line :) 
But as I could see so far, this already looks good :)
