### ISSUE TITLE
wrong PossibleUserWarning when using `from_argparse_args(args)`

### ISSUE THREAD

**Issue by wangherr** [PyTorchLightning/pytorch-lightning#13036]
## 🐛 Bug

when I use `pl.Trainer().from_argparse_args(args)`, even I set `max_epochs` in args, there is still a warning `PossibleUserWarning: `max_epochs` was not set. Setting it to 1000 epochs. To train without an epoch limit, set `max_epochs=-1`.`

### To Reproduce
~~~
    parser = ArgumentParser()
    parser.add_argument('--max_epochs', type=int, default=3)
    args = parser.parse_args()

    ...

    trainer = pl.Trainer().from_argparse_args(args)
    trainer.fit(model=model, datamodule=dm)
~~~

### Expected behavior

remove the wrong warning

### Environment

- PyTorch Lightning Version (e.g., 1.6.3):
- PyTorch Version (e.g., 1.10):
- Python version (e.g., 3.9):

### Additional context

The wrong is because of the `from_argparse_args()` is called after the `Trainer().__init()__`

cc @otaj

**Comment by carmocca** [comment]
Hi!

`from_argparse_args` is a [classmethod](https://www.geeksforgeeks.org/classmethod-in-python/), so it should be called on the class type, not the instance.

```diff
from argparse import ArgumentParser

from pytorch_lightning import Trainer
from pytorch_lightning.demos.boring_classes import BoringModel

parser = ArgumentParser()
parser.add_argument('--max_epochs', type=int, default=3)
args = parser.parse_args()


model = BoringModel()
-trainer = Trainer().from_argparse_args(args)
+trainer = Trainer.from_argparse_args(args)
trainer.fit(model)
```

Closing this issue! If you read this misuse in our docs, feel free to open a PR fixing it!
