### ISSUE TITLE
Impossible to check whether a current process was launched using the torchelastic command on MacOS

### ISSUE THREAD

**Issue by aynetdia** [PyTorchLightning/pytorch-lightning#13118]
## 🐛 Bug

When checking whether a current process was launched using the torchelastic command on a system running MacOS, it results in an error stating that `module 'torch.distributed' has no attribute 'is_torchelastic_launched'`. This is due to the `torch.distributed` not being available by default on MacOS, which leads to other APIs in the `distributed` package being hidden, as per the PyTorch [documentation](https://pytorch.org/docs/stable/distributed.html).

### To Reproduce

Any call of the `detect()` method from the `TorchElasticEnvironment` class.

### Expected behavior

The `detect()`method should return `False` when `torch.distributed` is not available.

### Environment

- PyTorch Lightning Version (e.g., 1.5.0): 1.6.3
- PyTorch Version (e.g., 1.10): 1.11.0
- Python version (e.g., 3.9): 3.8.13
- OS (e.g., Linux): MacOS
- CUDA/cuDNN version: -
- GPU models and configuration: M1 Chip
- How you installed PyTorch (`conda`, `pip`, source): conda
- If compiling from source, the output of `torch.__config__.show()`: - 
- Any other relevant information:

### Additional context

I discovered this bug when using the [Lightning-Hydra-Template](https://github.com/ashleve/lightning-hydra-template), which calls that method by default to check for availability of distributed job scheduling.

**Comment by aynetdia** [comment]
I've fixed this bug by simply incorporating an additional if-statement in the said method. Thus I am willing to submit a PR.

**Comment by martinb-bb** [comment]
Can confirm I am seeing same error with running:
pytorch 0.11.1

```bash 
`File ~/miniforge3/envs/gst/lib/python3.8/site-packages/pytorch_lightning/plugins/environments/torchelastic_environment.py:65, in TorchElasticEnvironment.detect()
63 """Returns True if the current process was launched using the torchelastic command."""
64 if _TORCH_GREATER_EQUAL_1_9_1:
---> 65 return torch.distributed.is_torchelastic_launched()
66 required_env_vars = {"RANK", "GROUP_RANK", "LOCAL_RANK", "LOCAL_WORLD_SIZE"}
67 return required_env_vars.issubset(os.environ.keys())

AttributeError: module 'torch.distributed' has no attribute 'is_torchelastic_launched'`

```

**Comment by akihironitta** [comment]
@aynetdia Thanks for reporting the issue. I think the patch will be something similar to #12794. Feel free to ping me anytime if you have any trouble submitting a PR :]

**Comment by akihironitta** [comment]
> pytorch 0.11.1

@martinb-bb Do you mean PyTorch 1.11.0?

**Comment by martinb-bb** [comment]
@akihironitta  hi, sorry! yes 1.11.0 👍

**Comment by martinb-bb** [comment]
Hi @akihironitta  Can you tell me when this fix will be pushed to PyPI package? thanks 😄

**Comment by akihironitta** [comment]
@martinb-bb We finalised the next patch release in #13019, so it should be available very soon (today I believe).
