### ISSUE TITLE
Usage of `tests.helpers.datasets` in "Lightning in 15 minutes" tutorial

### ISSUE THREAD

**Issue by thatlittleboy** [PyTorchLightning/pytorch-lightning#13125]
## 📚 Documentation

I'm following the ["Lightning in 15 minutes" tutorial](https://pytorch-lightning.readthedocs.io/en/latest/starter/introduction.html#define-a-lightningmodule), and in the code snippet of the second section, there is a reference to a MNIST dataset from the `tests/` directory.

![image](https://user-images.githubusercontent.com/30731072/169685554-7da2d549-09a5-4506-b99e-c6804dd57a83.png)

This `tests` module is presumably just for CI/CD testing.
Where should a new user to the library get this dataset from? `torchvision`?

Thanks.

cc @borda @rohitgr7

**Comment by awaelchli** [comment]
Hello @thatlittleboy
Yes it's a typo, the import should be

```py
from torchvision.datasets import MNIST
```

Would you like to take this opportunity and become a contributor? By sending a PR with the update?

**Comment by jiny419** [comment]
@thatlittleboy If you don't mind, could I resolve the issue?

**Comment by thatlittleboy** [comment]
@jiny419 sure, go ahead
