### ISSUE TITLE
Extra train_loader in auto_scale_batch_size docs?

### ISSUE THREAD

**Issue by rasbt** [PyTorchLightning/pytorch-lightning#13140]
## 📚 Documentation

Hey, in the docs here (https://pytorch-lightning.readthedocs.io/en/latest/advanced/training_tricks.html) we have 

```python
# using LightningModule
class LitModel(LightningModule):
    def __init__(self, batch_size):
        super().__init__()
        self.save_hyperparameters()
        # or
        self.batch_size = batch_size

    def train_dataloader(self):
        return DataLoader(train_dataset, batch_size=self.batch_size | self.hparams.batch_size)


trainer = Trainer(...)
model = LitModel(batch_size=32)
trainer.tune(model)

# using LightningDataModule
class LitDataModule(LightningDataModule):
    def __init__(self, batch_size):
        super().__init__()
        self.save_hyperparameters()
        # or
        self.batch_size = batch_size

    def train_dataloader(self):
        return DataLoader(train_dataset, batch_size=self.batch_size | self.hparams.batch_size)


trainer = Trainer(...)
model = MyModel()
datamodule = LitDataModule(batch_size=32)
trainer.tune(model, datamodule=datamodule)
```

Is it necessary to also have the `train_loader` as a `LightningModule` method, or is it sufficient to have it as the data module method? If it is necessary, we need to clarify that. It doesn't say anything about that in the text currently.

cc @borda @rohitgr7

**Comment by carmocca** [comment]
Either work! That snippet is trying to show that both are possible. If both are present, the datamodule takes precedence.

If you have specific ideas of how to improve this example, don't hesitate to open a PR!
