### ISSUE TITLE
Can't load lightning on Azure Ml compute.

### ISSUE THREAD

**Issue by MalcolmMielle** [PyTorchLightning/pytorch-lightning#13145]
## 🐛 Bug

Can't use lightning on Azure ML compute. I am hit with this error 

`ModuleNotFoundError                       Traceback (most recent call last)
Input In [1], in <module>
----> 2 import pytorch_lightning as pl

ModuleNotFoundError: No module named 'pytorch_lightning'`

When I try to import lightning in my Jupiter notebook, even though lightning is installed. This is very weird and I'm wondering if anyone in this community would have an idea why? The compute is on python3.8 and torch works fine, only lightning crashes the Jupiter kernel\has that module not found error.

If it's not the right place to ask, apologies and feel free to close it.

**Comment by akihironitta** [comment]
@MalcolmMielle I believe you're using a different Python interpreter. Inside your notebook, could you check again if it's installed?
```
! pip list | grep lightning
```

If not installed, you can install it from the notebook with:
```
! pip install pytorch-lightning
```

Please note that you might need to restart the kernel after installation.

**Comment by MalcolmMielle** [comment]
I'll double-check but I have tried both directly on the Azure compute and on my machine. I have also tried reinstalling with `pip reinstall pytorch-lightning` but the error stayed the same. I'll edit my message with the grep output later today.

**Comment by MalcolmMielle** [comment]
I found the solution! It's to reinstall lightning using `%conda` magic instead of `! conda` magic... so that it is visible to the kernel. I still don't know why the kernel couldn't see it before but at least it's solved.
