### ISSUE TITLE
Automatic environment check

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#1315]
## 🚀 Feature

Lightning could automatically detect a requirements.txt or environment.yml file and check if the packages in the current environment meet the specified versions. If these are not met, it could warn the user.

### Motivation

Lightning facilitates and encourages reproducibility of research code. A feature like this could further improve this part and make a user's life easier. 

### Pitch

- Check if there is a requirements.txt (pip, pipenv) or environment.yml (conda) file in the same path as the main script.
- If there is, check the versions and warn the user if dependencies are not met.
- Optional: Automatically upgrade/downgrade packages via pip / conda call (not sure if this is smart)

### Alternatives

Keep as is. The users have to take care of this themselves.

### Additional context

I have already implemented this for myself to keep track when working on multiple machines and code repositories.

**Comment by Borda** [comment]
do you have something else than #1234?
