### ISSUE TITLE
can not use WandbLogger when use multi-gpu training (ddp)    

### ISSUE THREAD

**Issue by pengzhangzhi** [PyTorchLightning/pytorch-lightning#13166]
## 🐛 Bug
I use wandb in my code. it works well in single-gpu. But when I use two gpus (with ddp),
an error appears.
 Here is my code:
```python
from pytorch_lightning.loggers import WandbLogger
        wandb_logger = WandbLogger(project="ZFold_Single_Seq", name=hparams.get('exp_name'),save_dir=exp_dir,reinit=True)
        wandb_logger.experiment.config.update(hparams)
```
Here is the error
```bash
    exec(compile(contents + "\n", file, 'exec'), glob, loc)
  File "/user/pengzhangzhi/SS_protein/zfold_origin/lightning/train.py", line 72, in <module>
    train(args, hprams)
  File "/user/pengzhangzhi/SS_protein/zfold_origin/lightning/train.py", line 32, in train
    wandb_logger = get_wandb_logger(args, hparams, exp_dir)
  File "/user/pengzhangzhi/SS_protein/zfold_origin/lightning/utils.py", line 28, in get_wandb_logger
    wandb_logger.experiment.config.update(hparams)
AttributeError: 'function' object has no attribute 'update'
```

### Environment

- PyTorch Lightning Version (e.g., 1.5.0):
- PyTorch Version (e.g., 1.10):
- Python version (e.g., 3.9):
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

cc @awaelchli @morganmcg1 @AyushExel @borisdayma @scottire @manangoel99 @justusschock @kaushikb11 @akihironitta @rohitgr7

**Comment by manangoel99** [comment]
Hi @pengzhangzhi ! Engineer from W&B here. In case of DDP, the WandbLogger goes only to the rank 0 process and all other processes get a dummy logger object. Hence, if you add a check before updating the config that the process is rank 0, it should work.

**Comment by pengzhangzhi** [comment]
Thanks! Here is the thing. If I delete the line that causes the error: `wandb_logger.experiment.config.update(hparams)`, it will work. But I want to keep it. 
My PL version is :
```bash
pytorch-lightning             1.6.3
```

**Comment by manangoel99** [comment]
Cool! The reason for that is [this](https://github.com/PyTorchLightning/pytorch-lightning/blob/9ac5cca8427f87f97afb08d5187966ccd401c9ae/pytorch_lightning/loggers/logger.py#L32) snippet.
On the rank 0 process in DDP you get the actual W&B logger but on other processes you get the `DummyExperiment` object so on all other processes except rank 0, `wandb_logger.experiment.config.update(hparams)` would throw an error. 

Hence, you should put this line inside an if block which checks the rank of the process.

**Comment by pengzhangzhi** [comment]
Thanks man. Would you like to provide the if block? I don't know how to check the rank of the process.

**Comment by awaelchli** [comment]
@pengzhangzhi 

```py
wandb_logger = WandbLogger(...)
trainer = Trainer(logger=wandb_logger, ...)
if trainer.global_rank == 0:
    wandb_logger.experiment.config.update(hparams)
...
```

**Comment by pengzhangzhi** [comment]
thanks~

**Comment by Anner-deJong** [comment]
## Potential useful note for future readers:
If like me you run into this before you have the trainer, the following simple snippets works:
```
from pytorch_lightning.utilities import rank_zero_only
...
if rank_zero_only.rank == 0:
    wandb_logger.experiment.config.update(my_config)
```

## nit @manangoel99 / wandb-on-pytorch-lightning engineers: for the current issue:
Shouldnt/couldnt the rank_zero_only filtering be abstracted by the wandb_logger / dummy logger themselves? Or the dymmy logger just being able to accept all calls that can be made to wandb_logger (as no-ops)?
