### ISSUE TITLE
Inference without Lightning dependencies

### ISSUE THREAD

**Issue by dpaleka** [PyTorchLightning/pytorch-lightning#13160]
The suggested way to run inference without a Lightning dependency is the following:

https://github.com/PyTorchLightning/pytorch-lightning/blob/dd475183227644a8d22dca3deb18c99fb0a9b2c4/docs/source/deploy/production_intermediate.rst?plain=1#L11-L19

However, this just throws an error because `model` is a dict:
```
AttributeError: 'dict' object has no attribute 'eval'
```

In fact, I am not sure whether [what is implied in the documentation](https://pytorch-lightning.readthedocs.io/en/latest/deploy/production_intermediate.html#use-pytorch-as-normal) is even possible given only the data saved in the checkpoint. 
Is there another way to do this?

cc @borda @rohitgr7

**Comment by carmocca** [comment]
Yes, this piece of docs is wrong. We save the `state_dict` of the model and not the instance itself (and inside a dictionary!) so it has to be pulled out of the dictionary and the weights loaded

**Comment by ekagra-ranjan** [comment]
Hi, I have the following suggestions for updating the doc.

1. The first code snippet in the doc should be changed from
```
import torch

model = torch.load("path/to/lightning/checkpoint.ckpt")
model.eval()
```

to 
```
import torch

class MyModel(nn.Module):
   . . .

model = MyModel()
checkpoint = torch.load("path/to/lightning/checkpoint.ckpt")
model.load_state_dict(checkpoint["state_dict"])
model.eval()
```

2. We can remove the second code snippet. I think the motivation of this snippet was to show that one can load a part of the model directly from the checkpoint which isn't the case. The user can just use `model.encoder`  to get a part of the model once the complete model's weights have been restored.

3. This [line](https://github.com/PyTorchLightning/pytorch-lightning/blob/a6e9bc2943bf2c82036e31a4948bd8caa54957ee/docs/source/deploy/production_intermediate.rst?plain=1#L88) should be changed from ```state_dict = checkpoint["state_dict"] ``` to ``` model_weights = checkpoint["state_dict"] ```

Please let me know your thoughts.

**Comment by carmocca** [comment]
All your suggestions look good to me :)
