### ISSUE TITLE
Support Aim as Logger

### ISSUE THREAD

**Issue by tshu-w** [PyTorchLightning/pytorch-lightning#13176]
## 🚀 Feature

[Aim](https://github.com/aimhubio/aim/) is an easy-to-use and performant open-source ML experiment tracker. It would be nice if pl support to use aim with logger by default. I would like to help to make this realize.

cc @borda @awaelchli @edward-io @ananthsub @rohitgr7 @kamil-kaczmarek @Raalsky @Blaizzy

**Comment by awaelchli** [comment]
Hi
This is a duplicate of #3985.
The aim package already has an integration with PyTorch Lightning, see an example usage [here](https://github.com/aimhubio/aim#integrations). We do not plan adding more third-party logger integrations directly into the PL package at the moment.

**Comment by tshu-w** [comment]
Sorry, I miss them.
