### ISSUE TITLE
Save the best epoch in `ModelCheckpoint`

### ISSUE THREAD

**Issue by GPla** [PyTorchLightning/pytorch-lightning#13269]
## 🚀 Feature

Add `best_model_epoch` (`best_model_step`) to the `ModelCheckpoint` callback.  

### Motivation

After training, it would be good to know during which epoch/step a model reached its min/max in the `monitor` metric. 
Right now, it can be figured out by from the `best_model_path` by using a regex, which is rather inconvenient.

```python
ckpt = ModelCheckpoint(...)
best_epoch = int(re.search(r'(?<=epoch\=)(\d+)(?=.ckpt)', ckpt.best_model_path).group(0))
```

### Pitch

Add two additional attributes `best_model_epoch` and `best_model_step`  which are updated in `_update_best_and_save` alongside the existing `best_xxx` attributes.

### Additional context

cc @carmocca @awaelchli @ninginthecloud @jjenniferdai @rohitgr7

**Comment by carmocca** [comment]
Our suggestion here is that you load the checkpoint and extract the epoch value

```python
ckpt = torch.load("my_model_checkpoint.ckpt")
epoch = ckpt["epoch"]
```
