### ISSUE TITLE
DDP runs main script multiple times (unnecessary duplication)

### ISSUE THREAD

**Issue by timothylimyl** [PyTorchLightning/pytorch-lightning#13276]
Reference Issue: ![8563](https://github.com/PyTorchLightning/pytorch-lightning/issues/8563)

The use case is to set up an optimiser search under DDP mode in the beginning to look for suitable optimisers and then only proceed to continue to train in DDP mode.

Pseudocode:
```
for optimisers in available_optimisers:
   train(opt_select=optimisers)

opt = get_best_opt(...)
train(opt_select=opt)
```

The issue is that DDP will cause the script to run 4 times (4 GPU), whereas we want it to just run once per loop search. How do we get DDP to run like a single GPU training process where it terminates after `trainer.fit` and can run another `trainer.fit` without any issues?

cc @justusschock @kaushikb11 @awaelchli @akihironitta @rohitgr7

**Comment by carmocca** [comment]
This is a limitation by the design of DDP and cannot be accomplished.

I suggest each `train()` call saves results to disk and then in a separate script call, you load them, choose the best one, and train again

**Comment by justusschock** [comment]
Setting up a bash script to individually call the same python script won't help as we call the script again when choosing DDP as strategy.

You really should separate these two trainings.

Note: You could also use ddp_spawn as training strategy which does not call the script multiple times but does have some other limitations
