### ISSUE TITLE
Adapting SWA for pytorch lightning.

### ISSUE THREAD

**Issue by RafailFridman** [PyTorchLightning/pytorch-lightning#1329]
Hello!
I'm currently trying to add SWA support to my lightning module, following this post https://pytorch.org/blog/stochastic-weight-averaging-in-pytorch/
And I have problems with loading averaged weights after I finish training. 
I do it like this:
```python
def on_train_end(self): #hook for SWA weights swapping
        if self.swa_enabled:
            print("Swapping model weights to SWA averages.")
            self.trainer.optimizers[0].swap_swa_sgd()
            print("Saving model with SWA weights to another checkpoint")
            self.save_checkpoint(os.path.join(self.trainer.checkpoint_callback.dirpath,f"swa_model_epoch={self.current_checkpoint}.ckpt"))
```
And bump into following problems:
1) It returns error message `'MyCoolModel' object has no attribute 'save_checkpoint' `  on the line `self.save_checkpoint.....`, instead of saving the model as stated in https://pytorch-lightning.readthedocs.io/en/latest/weights_loading.html 
2)Even if I succeed with the 1st issue, I'm still required to update BN instances. As I believe, the best way to do this is to just run forward pass over the whole training data. So, my question is: is there a simple way to run 1 epoch though training data without writing my own loops?
Thanks in advance

**Comment by williamFalcon** [comment]
Thanks for the Q! @PyTorchLightning/core-contributors.

Good question, I think you could probably use ```run_training_epoch```.
But ideally we add a call to run a single epoch (```fit_epoch```) or something.

I don't have time to look at the weights thing today, but can look next week

**Comment by jeremyjordan** [comment]
> It returns error message 'MyCoolModel' object has no attribute 'save_checkpoint' on the line self.save_checkpoint.....

i believe the documentation is wrong, `save_checkpoint` is a method for the `Trainer` class and not the `LightningModule` class. 

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/training_io.py#L247

**Comment by RafailFridman** [comment]
@jeremyjordan thanks for the reply. Is there a way to manually save the lightning module, but not the Trainer?

**Comment by jeremyjordan** [comment]
it's a bit misleading but the trainer saves a model checkpoint

```
trainer.save_checkpoint("example.ckpt")
model = MyModel.load_from_checkpoint(checkpoint_path="example.ckpt")
```

we should update the docs accordingly

**Comment by jeremyjordan** [comment]
@RafailFridman feel free to reopen this issue if you're still having problems
