### ISSUE TITLE
How to log (TestTubes metrics.csv) per epoch 

### ISSUE THREAD

**Issue by Dunrar** [PyTorchLightning/pytorch-lightning#1341]
#### What is your question?
I use the TestTube logger as well as Neptune.ai and want to keep the local TestTube .csv logs as small and as clean as possible. For that reason I locally only log per epoch. I am not returning a log in training_step, but the metrics.csv still logs `created_at` for every (10th?) timestep:

#### Code
```
def on_epoch_end(self):
    # Logging loss per epoch
    train_loss_mean = np.mean(self.training_losses)
    self.logger[0].experiment.log_metric('epoch/mean_absolute_loss', y=train_loss_mean, x=self.current_epoch)
    self.logger[1].experiment.log({'epoch/mean_absolute_loss': train_loss_mean, 'epoch': self.current_epoch}, global_step=self.current_epoch)
    self.training_losses = []  # reset for next epoch
```
```
trainer = pl.Trainer(
    checkpoint_callback=False,
    logger=[neptune_logger, testtube_logger],
    gpus=hparams.cuda,
    val_percent_check=0,
    early_stop_callback=early_stopping,
    default_save_path=src.settings.LOG_DIR,
    max_epochs=hparams.epochs,
    row_log_interval=hparams.n_datasamples,
    log_save_interval=hparams.n_datasamples
)
```

#### What have you tried?
As you can see, I tried changing the `log_save_interval` and `row_log_interval` parameters, to make logging cheaper and the log files smaler. That works, but not perfectly. My metrics.csv file now looks like this: 
```
created_at,epoch/mean_absolute_loss,epoch
2020-04-02 10:34:58.104557,,
2020-04-02 10:35:02.600094,0.1986402783766389,0.0
2020-04-02 10:35:02.606550,,
2020-04-02 10:35:06.822270,0.11120840712822974,1.0
2020-04-02 10:35:06.827882,,
2020-04-02 10:35:11.068734,0.07875163345225156,2.0
```
Before, there were many more "empy" lines, but I still have one line with only datetime/created_at for every line with actual data. Is there any way to change that?

**Comment by Borda** [comment]
I think that with this extra logging in `on_epoch_end` and the call in trainer they interfere
https://github.com/PyTorchLightning/pytorch-lightning/blob/e6b34ef90d5f3eac70154b305b476614a64f1981/pytorch_lightning/trainer/logging.py#L73
 would say that logging interval shall be a feature of the particular logger rather then Trainer attribute

**Comment by Dunrar** [comment]
Okay, so for the TestTube logger, is there a way to get it to log only per epoch?

**Comment by scarecrow1123** [comment]
The same happens with the recently added `CSVLogger`. Is this an issue to be fixed or is this due to a mis-configuration?
