### ISSUE TITLE
Trainer.add_argparse_args not recognizing type

### ISSUE THREAD

**Issue by kunshouout** [PyTorchLightning/pytorch-lightning#1343]
## 🐛 Bug
Following the guide, I added trainer args into the parser:
```
  parser = Trainer.add_argparse_args(parser)
   trainer = Trainer.from_argparse_args(args)

$ python main.py --gpus 1 --max_epochs 64 --arbitrary_trainer_arg some_value

```
Then I got error:
TypeError: 'str' object cannot be interpreted as an integer

It's because max_epochs is "str" rather than "int". I think an easy fix would be adding type-info in parser.add_argument in Trainer.add_argparse_args.

**Comment by alexeykarnachev** [comment]
Hi!. I think, It's solved here
https://github.com/PyTorchLightning/pytorch-lightning/issues/1139
