### ISSUE TITLE
Running multiGPU test(): one GPU overflows

### ISSUE THREAD

**Issue by zetyquickly** [PyTorchLightning/pytorch-lightning#1344]
## ❓ Questions and Help

Hi, everyone
Thank you all for your contribution to such great project!

#### What is your question?

During my experiments I've faced an issue that I cannot overcome and find any information on this.

I've trained some net and for now I would like to perform a test of this model. I've defined `test_step`, `test_end` and run my test on multiGPU. 
What I see is that on of three devices overflows with values and if I use `preds.cpu()` I get an error.

```
  File "/root/anaconda2/envs/pytorch-gpu/lib/python3.7/site-packages/torch/nn/parallel/_functions.py", line 54, in forward
    assert all(map(lambda i: i.is_cuda, inputs))
AssertionError
```

I would like to know how to preserve GPU memory from accumulating values from previous batches, or how to flush it to RAM after `test_step`

#### Code

```
class Net(pl.LightningModule):
    def __init__(self, hparams):
        super(Net, self).__init__()
        self.hparams = hparams
        self.submodule = pretrainedmodels.se_resnet50(
            num_classes=1000, pretrained='imagenet'
        )
        self.submodule.last_linear = nn.Linear(
            self.submodule.last_linear.in_features, self.hparams.num_categories
        )

    def forward(self, x):
        return self.submodule(x)
    
    def test_step(self, test_batch, batch_idx):
        x = test_batch['image']
        logits = self.forward(x)
        preds = torch.log_softmax(logits, dim=1)
       
        return {'batch_preds': preds.cpu()}

    def test_epoch_end(self, outputs):
        return {'all_preds': outputs}

model = Net.load_from_checkpoint(PATH)
    model.freeze()

    trainer = pl.Trainer(
        gpus=[0,1,3], 
    )

    # print(model.data_test[0])
    trainer.test(model)
```

**Comment by zetyquickly** [comment]
So, the solution is to flush tensors to RAM in `test_step_end` when whole batch is gathered. 
```
def test_step(self, test_batch, batch_idx):
        x, ids = test_batch['image'], test_batch['id']
        logits = self.inference(x)
        preds = F.softmax(logits, dim=1)
        return {'batch_preds': preds, 'batch_ids': ids}

    def test_step_end(self, outputs):
        preds = outputs['batch_preds'].cpu()
        ids = outputs['batch_ids'].cpu()
        return {'batch_preds': preds, 'batch_ids': ids}

    def test_epoch_end(self, outputs):
        all_preds = torch.cat([x['batch_preds'] for x in outputs], axis=0)
        all_ids = torch.cat([x['batch_ids'] for x in outputs], axis=0)
        self.preds = [all_preds, all_ids]
        return {}
```
But here is the question: `test_step_end` is now deprecated and will be removed in version `1.0`, how do we expected to achieve same functionallity only with `test_step` and `test_epoch_end`?

**Comment by williamFalcon** [comment]
@zetyquickly mind submitting a PR? @Borda mind helping complete?

```test_step_end``` is the same as ```test_epoch_end```

**Comment by zetyquickly** [comment]
My bad. There is no issue 

`test_end` is deprecated. `test_step_end` still exists and hasn't deprecated. 
And documentation on `test_step_end` says "Use this when testing with dp or ddp2 because test_step will operate on only part of the batch" which is precisely my case

What kind of changes in PR do you expect here?
