### ISSUE TITLE
Long time between calls to training_step when there are multiple optimizers

### ISSUE THREAD

**Issue by karlinjf** [PyTorchLightning/pytorch-lightning#1354]
I have a GAN model with two optimizers that is running 30-40% slower in lightning than without. I've discovered that the lost time comes between the end of training_step for optimizer_idx 0 and the start of the call for optimizer_idx 1. There is 120ms of time (cpu, not wall) spent there. 30ms of that time is the backwards step. The other 90ms is unaccounted for. Note that after optimizer_idx 1 is run, there is only 20ms cpu time before optimizer_idx 0 is called again for the next batch.

So why might there be extra time between the optimizers?

This is happening in both the latest release as well as master.

Thanks!

**Comment by karlinjf** [comment]
I think this might actually be more of a bug than a question. I can reproduce this on the sample gan.py as well. Each forward step takes 130ms, and there are 270ms between forward steps, of which only 180ms is used for the backwards step. Again, leaving 90ms of processing overhead, which is simply too much for real use.

**Comment by williamFalcon** [comment]
ummm thanks for highlightning the potential speed issues. @Borda @jeremyjordan mind looking into this?

**Comment by Borda** [comment]
well all mentioned func contains look with converting from Tensor to native types aka `v.item()`

**Comment by Borda** [comment]
@karlinjf talking about GAN are you using the PL example or your own GAN?

**Comment by Borda** [comment]
![Screenshot at 2020-04-08 10-17-28](https://user-images.githubusercontent.com/6035284/78761051-58c16480-7982-11ea-8c82-4b2904c5cb97.png)

**Comment by karlinjf** [comment]
Both the PL example and my own GAN had the 90ms of overhead between iterations.

**Comment by karlinjf** [comment]
Ah, it's not quite the same. in the PL example GAN most of that type is going to the step function. I don't see any problem with that. It appears to be just my GAN then, and I've sprinkled some timing functions around and it appears to be taking a long time in the type_as() method in TensorRunningMean.append. I'll look closer.

**Comment by karlinjf** [comment]
Ah, perhaps:

```
        if self.memory.type() != x.type():
             self.memory.type_as(x)
```

Is supposed to be:
```
        if self.memory.type() != x.type():
            self.memory = self.memory.type_as(x)
```

**Comment by karlinjf** [comment]
That's already fixed by b8ff9bc1d242a18f5e7147f34d63f43fcdd0e50. Hmm, but I'm still much slower. Will investigate more, you can ignore this issue for now while I track it down.

**Comment by karlinjf** [comment]
Here is what happens with generative_adversarial_network.py on tip-of-tree 3f1e4b953f84ecdac7dada0c6b57d908efc9c3d3:

master: 14.3 it/s
Comment out `self.detect_nan_tensors(loss)`: 16.4 it/s
Change TensorRunningAccum.append's  x = x.to(self.memory) to self.memory = self.memory.to(x): 16.65 it/s

And on my own GAN on lightning:
master: 6.78 it/s
Comment out `self.detect_nan_tensors(loss)`:8.08 it/s

So it seems like detect_nan_tensors should either be optimized or dropped, as it's very expensive.

That change fixes half of the gap between my own setup and my setup with lightning. Will continue digging.

**Comment by awaelchli** [comment]
Sorry about the nan detection perf issue, but it is now disabled by default. 
Were you able to further close the performance gap?

**Comment by karlinjf** [comment]
No worries. There is still a good ways to go. #1576 was another big chunk. I believe the rest comes from .item() calls in the likes of add_tqdm_metrics and the like.

**Comment by awaelchli** [comment]
I think there is no way around calling .item(). However, we could update the progress bar metrics with the refresh rate, and then it would be possible to set the refresh rate and only get calls to .item() when the bar is actually getting updated. It would require some refactoring though, because the progress bar is now a callback.
