### ISSUE TITLE
auto enable TPU checkpoint save and checkpoint load using the proper wrappers

### ISSUE THREAD

**Issue by patil-suraj** [PyTorchLightning/pytorch-lightning#1363]
I trained a model on TPU with google colab. When trying to load the checkpoint on GPU it gives following error

`RuntimeError: Could not run 'aten::empty.memory_format' with arguments from the 'XLATensorId' backend. 'aten::empty.memory_format' is only available for these backends: [CUDATensorId, SparseCPUTensorId, VariableTensorId, CPUTensorId, MkldnnCPUTensorId, SparseCUDATensorId].`

How to load the checkpoint saved on TPU with cpu/gpu ?

**Comment by williamFalcon** [comment]
ummm great point.  @dlibenzi any docs on this?

**Comment by dlibenzi** [comment]
The recommended way to save checkpoint is to use the `xm.save()` API.
This is a thin wrapper around `torch.save()` that makes sure there is a symmetric graph execution on all cores:

https://github.com/pytorch/xla/blob/3518650335dba07820df8d5f6a33d1a969f78265/torch_xla/core/xla_model.py#L521

Saved tensors are PyTorch CPU tensor.
The load happen using vanilla `torch.load()` which sucks in PyTorch CPU tensor, then create your normal model, set the state dictionary, and then `model.to(xla_device)`.

**Comment by williamFalcon** [comment]
i thought we had automated this. 
this should be embedded in the auto checkpoint feature and load from checkpoint. 

let’s turn this PR into those feature requests

**Comment by Borda** [comment]
will be fixed in #2726
