### ISSUE TITLE
Permission denied when trying to restore model from checkpoint

### ISSUE THREAD

**Issue by LucFrachon** [PyTorchLightning/pytorch-lightning#1367]
Hi
I trained a pretrained DenseNet model by freezing its features and creating a new classifier.
I am now trying to restore the trainer from a checkpoint and unfreeze the features to fine-tune them, but am getting the following error:

```
~\Miniconda3\envs\pl\lib\site-packages\torch\serialization.py in __init__(self, name, mode)
    191 class _open_file(_opener):
    192     def __init__(self, name, mode):
--> 193         super(_open_file, self).__init__(open(name, mode))
    194 
    195     def __exit__(self, *args):

PermissionError: [Errno 13] Permission denied: 'H:/kaggle_plants/chkpts'
```
Some more detail. Here's my model's init:
```
    def __init__(self, hparam):
        super().__init__()
        self.hp = Namespace(**hparam) if isinstance(hparam, dict) else hparam
        self.features = densenet121(pretrained=self.hp.pretrained, progress=False).features
        self.classifier = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
            nn.Linear(in_features=1024, out_features=4, bias=True),
            nn.Dropout(self.hp.drop_rate),
        )
        if self.hp.freeze_features:
            freeze(self.features)
        else:
            unfreeze(self.features)
```
The hyper-parameters are like this:
```
hparams = dict(chkpt_path = 'H:/kaggle_plants/chkpts',
               log_path = 'H:/kaggle_plants/lightning_logs',
               version = 1,
               pretrained = True, 
               freeze_features = True,
               n_epochs = 8,
(etc.)
)
```
Logger and checkpoint:
```
model = PlantsDenseNet(hparams)
hp = Namespace(**hparams)
logger = TensorBoardLogger(save_dir=hp.log_path, version=hp.version)
chkpt = ModelCheckpoint(filepath=hp.chkpt_path, 
                        save_top_k=1, verbose=True, monitor='val_loss')
```
First round of training (frozen features):
```
trainer = pl.Trainer(checkpoint_callback=chkpt, gpus=-1, max_epochs=hp.n_epochs, 
                     use_amp=hp.use_16bit, logger=logger)
trainer.fit(model)
```
Second round of training (unfreeze features and fine-tune them for a further 8 epochs):
```
hp.freeze_features = False
hp.n_epochs = 16
model = PlantsDenseNet(hparams)
trainer = pl.Trainer(resume_from_checkpoint=hp.chkpt_path, 
                     max_epochs=hp.n_epochs)
trainer.fit(model)
```
That's when I get the error. I tried running the notebook with Admin rights, and have full access rights so I suspect that a process is not releasing the checkpoint file.
I must say I am still slightly confused by the way Pl manages checkpoint and logging paths so I might be doing something wrong but I would appreciate some assistance.
Thanks!

**Comment by williamFalcon** [comment]
chmod your weights. you likely created your weights from a different account or something. If this is on a cluster, make sure to both train, activate conda env and save weights from same account.

happy to reopen if this is still an issue

**Comment by LucFrachon** [comment]
The original weights are the pretrained ones from Pytorch. They go through a first round of training and the resulting weights are immediately (i.e. within the same session) recalled for fine-tuning, after unfreezing the features layers. So there is no notion of different accounts etc.

PS : I forgot to mention it, but I am running on Windows.
