### ISSUE TITLE
Epoch progress bar only showing training steps

### ISSUE THREAD

**Issue by VitorGuizilini** [PyTorchLightning/pytorch-lightning#1386]
Maybe I am missing something obvious, but my epoch progress bar also includes validation steps. This means that, when one of my training epochs is over the progress bar is still around half-way through the number of steps, and then a validation progress bar starts and both increase at the same time. 

It makes sense that an epoch should end when training and validation are over, but is there a way to decouple these two, so there is a bar only for training (the epoch progress bar) and another only for validation?

**Comment by Borda** [comment]
@PyTorchLightning/core-contributors any strong opinion about the need to split train/valid progress bars? we may have it as an option for a user to chose...?

**Comment by williamFalcon** [comment]
@vguizilini we originally had it this way, but we chose to make it the way you see with the two progress bars. What about the other way do you prefer?

Maybe we can just make a callback for the progress bar that lets users configure their own options for it?

@Borda or @awaelchli do you want to do this?

**Comment by Borda** [comment]
I this that moving progress bar to a callback was discussed already https://github.com/PyTorchLightning/pytorch-lightning/issues/765#issuecomment-593703168

**Comment by awaelchli** [comment]
I like the idea of having it as callback. I could look into it this weekend and try to do what @hadim suggested. But I suspect I won't be able to finish it in time for next release I'm afraid.

**Comment by Borda** [comment]
there is release these days, so I think we are very fine with having it in next 0.7.3

**Comment by vguizilini** [comment]
@Borda I am fine with implementing the progress bar as a callback, thanks!

**Comment by awaelchli** [comment]
We introduced a callback for the progress bar #1450 . It can be customized and extended by the user. See https://pytorch-lightning.readthedocs.io/en/latest/callbacks.html#progress-bars

**Comment by awaelchli** [comment]
do we need to do anything more? or can it be closed?
