### ISSUE TITLE
How to publicize blog post 😉

### ISSUE THREAD

**Issue by Crissman** [PyTorchLightning/pytorch-lightning#1390]
Hi!

I wrote a [blog post on how to use Optuna with PyTorch Lightning](https://medium.com/optuna/using-optuna-to-optimize-pytorch-lightning-hyperparameters-d9e04a481585). If you could [retweet](https://twitter.com/OptunaAutoML/status/1247048549734309888), or post somewhere, that would be appreciated!

Thanks!

**Comment by Borda** [comment]
We can push it via our Twitter or co-publish with @williamFalcon on medium...
moreover, if you already have block-post, share it here and we add it to our/local wiki

**Comment by Borda** [comment]
anyway this one is already retweeted and added to [Tutorials](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Tutorials)
