### ISSUE TITLE
Add an option to disable Trainer.detect_nan_tensors

### ISSUE THREAD

**Issue by quinor** [PyTorchLightning/pytorch-lightning#1392]
## 🚀 Feature

Add an option to disable `Trainer.detect_nan_tensors`

### Motivation

This function tends to be pretty slow when your network has got a lot of parameters, especially in small tensors. For example in my case it took ~0.5s per training iteration.

### Pitch

Add an option to the `Trainer` class that disables calling `detect_nan_tensors` every epoch.

### Alternatives

Remove it all together. Bad idea.

**Comment by quinor** [comment]
I'm currently using a workaround:

`trainer.detect_nan_tensors = lambda x: 0`

**Comment by ethanwharris** [comment]
This proposal sounds good :) would maybe go as far as to say that it should be disabled by default, certainly if this speeds up testing :). We should also add `detect_nan_tensors` to the profiler so that users can see how long it is taking

**Comment by Borda** [comment]
See profiler results here https://github.com/PyTorchLightning/pytorch-lightning/issues/1354#issuecomment-610821017

**Comment by williamFalcon** [comment]
agreed! let's do this
