### ISSUE TITLE
Progress bar in Jupyter adds newlines for each validation step

### ISSUE THREAD

**Issue by tcwalther** [PyTorchLightning/pytorch-lightning#1399]
## 🐛 Bug

Pytorch lightning prints newlines when showing the validation progress bar. See attached screenshot.

This may be a bug with nested progress bars in tqdm. I'm using the recent tqdm 4.45.0; I also had the issue with tqdm 4.43.0.

<img width="1192" alt="Screenshot 2020-04-07 at 12 31 30" src="https://user-images.githubusercontent.com/2840901/78659548-045bad80-78cc-11ea-9feb-76aaf328ed78.png">

### To Reproduce

In a Jupyter notebook, run `trainer.fit(model)` on any model that has a validation step.

### Expected behavior

No newlines should be added.

### Environment

```
cuda:
        GPU:
                Tesla K80
        available:           True
        version:             10.1
packages:
        numpy:               1.17.4
        pyTorch_debug:       False
        pyTorch_version:     1.4.0
        pytorch-lightning:   0.7.1
        tensorboard:         2.2.0
        tqdm:                4.45.0
system:
        OS:                  Linux
        architecture:
                64bit

        processor:           
        python:              3.7.3
        version:             #1 SMP Debian 4.9.168-1+deb9u4 (2019-07-19)
```

**Comment by williamFalcon** [comment]
upgrade to master. i think it’s fixed there

**Comment by williamFalcon** [comment]
happy to reopen if it isn’t

**Comment by tcwalther** [comment]
Thanks for your swift reply. I'm afraid it's still an issue after upgrading.

<img width="1205" alt="Screenshot 2020-04-07 at 13 05 41" src="https://user-images.githubusercontent.com/2840901/78662360-88179900-78d0-11ea-9642-1da552f4436f.png">

**Comment by tcwalther** [comment]
What happens in Jupyter is that there's a bunch of empty divs left over. I expanded one for illustration, too.

<img width="391" alt="Screenshot 2020-04-07 at 13 08 27" src="https://user-images.githubusercontent.com/2840901/78662571-f2c8d480-78d0-11ea-89be-e486e9b365bb.png">

**Comment by williamFalcon** [comment]
maybe submit a PR?
https://github.com/tqdm/tqdm/issues/375

**Comment by tcwalther** [comment]
Turns out this is a bug in tqdm. I will file an issue there.
Easiest way to reproduce:

```
from tqdm.auto import tqdm
from time import sleep

for _ in tqdm(range(5)):
    for _ in tqdm(range(5), leave=False):
        sleep(0.01)
```

**Comment by tcwalther** [comment]
I had a look at that issue, but it didn't seem fully relevant. I've filed a new issue:

tqdm/tqdm#935

**Comment by tcwalther** [comment]
Looks like this has been an issue between jupyterlab and ipywidgets for quite some time (https://github.com/jupyter-widgets/ipywidgets/issues/1845), and seems to be a main motivator why the fastai people wrote their own progress bar library:

https://github.com/fastai/fastprogress/issues/6

Would you consider switching to fastprogress, too? I understand the library is a lot less common than tqdm, but it may be more suitable for this project.

**Comment by Borda** [comment]
let's open a new issue with a discussion about `fastprogress`,
 see https://github.com/fastai/fastprogress

**Comment by tcwalther** [comment]
@Borda will do so now.
