### ISSUE TITLE
Implement Asynchronous GPU transfer and Training with Multithreading

### ISSUE THREAD

**Issue by HenryJia** [PyTorchLightning/pytorch-lightning#1404]
## 🚀 Feature
Asynchronous GPU transfer can be achieved by utilizing pinned memory with multithreading
Minimal example code
https://github.com/HenryJia/Lighter/blob/master/lighter/train/loaders.py

### Motivation

Parallelrising GPU transfer and training will cut down time GPU is stuck waiting for data from CPU
https://devblogs.nvidia.com/how-overlap-data-transfers-cuda-cc/

### Pitch

Everyone likes faster training and maximal GPU utilisation

### Alternatives

Not Applicable

### Additional context

None

**Comment by williamFalcon** [comment]
@PyTorchLightning/core-contributors do we want to bring this in?

**Comment by sebastienwood** [comment]
Is it the same as using the arg `non_blocking=True` in the `.to(device)` method ?

E.g.:
``` 
for batch_idx, (inputs, targets) in enumerate(trainloader):
   inputs, targets = inputs.to(device, non_blocking=True), targets.to(device, non_blocking=True)
```

**Comment by HenryJia** [comment]
If you set non_blocking=True and pin_memory=True it allows asynchronous GPU transfer but will block if you need it immediately, that's why you still need queue and Threading

**Comment by justusschock** [comment]
I'm not sure we want this tbh. This may introduce some race conditions. And if GPU is busy, outsourcing to another cuda stream will also not speed things up (and usually it's the case, that cpu waits for gpu. Also I remember the advice from PyTorch guys to avoid using cuda streams manually when it's not essential.

Can you maybe provide a small benchmark script so that we can see the potential benefit?

A sidenote from reading your code: does a threading Queue also involve pickling? If it does, you might want to switch to torch.muktiprocessings queue since it bypasses that via shared memory. On the other hand, I really want to avoid extra queues as they usually slow things down.

**Comment by Borda** [comment]
this is on a similar note as [DALI](https://developer.nvidia.com/DALI) right?
https://towardsdatascience.com/nvidia-dali-speeding-up-pytorch-876c80182440
we had the initiative to add it already #791 #789 #513 #1316

**Comment by HenryJia** [comment]
@justusschock 
No it doesn't introduce any race conditions I think you misunderstood what the code does.
With PyTorch's bog standard dataloader you always have to wait on the CPU as you end up with 
.to() -> train(...) -> .to() -> train(...) ->...
My code simply sticks the .to() in a separate thread and stream so that the GPU isn't waiting for data
There's 2 threads now, one which just does
to() -> queue.put() -> to() -> queue.put() ->...
and the main training thread which does
queue.get() -> train -> queue.get() -> train

The only possible case which the main thread would be bottlenecked by the loading thread is if the batches are so large we're bottlenecked by the normal dataloader or the PCIE bus anyway. The queue put and get takes no time since only a handle referencing the batch (which now already lives on the GPU) is stored in the queue.

Threading queue does not involve pickling. It's simply a threadsafe version of deque. It uses deque to actually store everything. We're using threads so there's no need to pickle and pass objects around. They all live in the same shared memory space anyway on the CPU

On small datasets (size wise not sample wise) like MNIST, it's slightly faster. My Asynchronous loader takes 151 seconds for 100 epochs of training and validation, vs PyTorch's bog standard dataloader which takes 158 seconds. Code: https://gist.github.com/HenryJia/930916775c11bc5c6debb87c046965e5

On larger datasets there's more of an effect. This code which generates 256MB batches of random numbers to load and multiply takes 17.8s on my machine to complete with the AsynchronousLoader and 22.1s to complete without it: https://gist.github.com/HenryJia/17e3a647cc2da1dd0ceeb6365bdfeaac

**Comment by HenryJia** [comment]
I am aware of DALI, and I believe it does similar stuff and has a bit more functionality, although I personally think it's a little bit bulky. I wrote mine to be as minimalistic as I could and work exactly like a PyTorch dataloader in terms of interfacing

**Comment by HenryJia** [comment]
Closing this issue because I've already added to bolts. Sorry I forgot about it for a bit

**Comment by amogkam** [comment]
@HenryJia this is a fantastic feature!

one quick question- is there any concern about cuda oom? If the batches are very large such that the main thread is using up pretty much all the GRAM is it possible for the loading thread to cuda oom when moving the next batch to GPU? 

or is cuda smart enough to block the transfer if it will lead to oom

**Comment by max0x7ba** [comment]
> Closing this issue because I've already added to bolts. Sorry I forgot about it for a bit

lightning-bolts-0.7.0 in pip is incompatible with pytorch-lightning-2.x versions, unfortunately.
