### ISSUE TITLE
Parallel and distributed training on preemptible instances

### ISSUE THREAD

**Issue by renat-abbyazov** [PyTorchLightning/pytorch-lightning#1414]
## 🚀 Feature

Ray announced RaySGD
https://medium.com/distributed-computing-with-ray/faster-and-cheaper-pytorch-with-raysgd-a5a44d4fd220

It would be great to have an opportunity to use preemptible instances in order to cut prices on training.

See also #1325.

**Comment by Borda** [comment]
@luiscape @PyTorchLightning/core-contributors ^^

**Comment by williamFalcon** [comment]
awesome. thanks for mentioning! i need to look at what it takes to integrate this. will keep you posted! maybe shoot for 0.8.0 on this

**Comment by jeremyjordan** [comment]
also see https://github.com/pytorch/elastic for a similar effort, RaySGD looks pretty sweet!

**Comment by williamFalcon** [comment]
will reopen closer to tackling this issue in a few months
