### ISSUE TITLE
Gym missing from requirements.txt?

### ISSUE THREAD

**Issue by TylerYep** [PyTorchLightning/pytorch-lightning#1420]
## 🐛 Bug

When running `bash .run_local_tests.sh`, I get an error that `import gym` failed. I solved this using pip install gym, but this package might need to be added to the requirements?

Wasn't sure exactly where this would belong (seems test specific), but would be a quick PR.

**Comment by philip30** [comment]
I think ```gym``` is a very specific to the test and is not a part of the framework. We might want to separate what is essential for the package and testing.

**Comment by williamFalcon** [comment]
gym is part of the test requirements not the framework requirements.
@Borda mind adding to test requirements?

**Comment by Borda** [comment]
we have it in experiment requirements.txt
https://github.com/PyTorchLightning/pytorch-lightning/blob/b5c6d0e39398f31e2959a3fc8dcd053f0110d790/pl_examples/requirements.txt#L2
