### ISSUE TITLE
run_training_batch breaks on None batch or -1 response from on_batch_start (in new 0.7.2 release)

### ISSUE THREAD

**Issue by david-alexander-white** [PyTorchLightning/pytorch-lightning#1421]
## 🐛 Bug

run_training_batch now is supposed to return a 4-tuple in 0.7.2 

however, there are two places where it still returns a 3-tuple, which will cause the program to crash, saying "ValueError: not enough values to unpack (expected 4, got 3)"

(training_loop.py:533)
```
if batch is None:
    return 0, grad_norm_dic, {}
``` 

(training_loop.py:543)
```
if response == -1:
    return -1, grad_norm_dic, {}
```

vs. the standard return
`return 0, grad_norm_dic, all_log_metrics, batch_output`

### To reproduce
just return -1 from on_batch_start

**Comment by williamFalcon** [comment]
good catch. mind submitting a PR?

**Comment by ddd-bbb** [comment]
nice, beat me to it

**Comment by david-alexander-white** [comment]
Nice, beat me to it
