### ISSUE TITLE
How to find the current epoch number inside the training loop?

### ISSUE THREAD

**Issue by Deepayan137** [PyTorchLightning/pytorch-lightning#1424]
#### How to find the current epoch number inside the training loop?
I am training a Conv autoencoder on MNIST images and want to save the reconstructed images after every 10 epochs. 
#### Code
```
class AutoEncoder(pl.LightningModule):
    def __init__(self):
        pass
    def forward(self, x):
        pass
    def training_step(self, batch, batch_idx):
         images = batch
         out  = self.forward(images)
         loss = self.loss(out, images)
         if epoch % 10:
            save(images)
  ````       
I am looking for something like this where the output images are saved every 10 epoch.

#### What have you tried?
I haven't tried anything since I am unable to find any documentation on current epoch no.
#### What's your environment?
I am using pytorch 1.4 and Lightning version 0.7
 - OS: [e.g. iOS, Linux, Win]
 - Packaging [e.g. pip, conda]
 - Version [e.g. 0.5.2.1]

**Comment by philip30** [comment]
```self.current_epoch``` would do. (self is a lightning module). Though it starts with 0.

**Comment by Deepayan137** [comment]
Thanks @philip30 :)

**Comment by jovenwayfarer** [comment]
@philip30 tqdm starts from epoch 1 but actually it is epoch 0?

**Comment by LC117** [comment]
How about total epochs?

**Comment by pme0** [comment]
In case the iteration/step is required, there is also `self.global.step`.
