### ISSUE TITLE
Test metrics is not being reported to TensorBoard since 0.7.2

### ISSUE THREAD

**Issue by yukw777** [PyTorchLightning/pytorch-lightning#1435]
### To Reproduce

https://colab.research.google.com/drive/1fM6xL140u9pU0vcmJf6qKzHwczjcMpcF

#### Code sample

Please see the colab above.

### Expected behavior

The test metrics should be reported.

### Environment

The Colab environment:
```
cuda:
	GPU:
	available:           False
	version:             10.1
packages:
	numpy:               1.18.2
	pyTorch_debug:       False
	pyTorch_version:     1.4.0
	pytorch-lightning:   0.7.2
	tensorboard:         2.2.0
	tqdm:                4.38.0
system:
	OS:                  Linux
	architecture:
		64bit
		
	processor:           x86_64
	python:              3.6.9
	version:             #1 SMP Wed Feb 19 05:26:34 PST 2020
```

### Additional context
Regression from 0.7.1

**Comment by Borda** [comment]
@williamFalcon ^^ 0.7.3?

**Comment by yukw777** [comment]
@williamFalcon, #1441 didn't fix the issue with Tensorboard (the issue with the console output has been fixed). I've updated the colab to test the same code with 0.7.3 (https://colab.research.google.com/drive/1fM6xL140u9pU0vcmJf6qKzHwczjcMpcF), and you'd notice that the `test_loss` metrics is not rendered in Tensorboard.

**Comment by yukw777** [comment]
it seems like this issue is now being tracked here: https://github.com/PyTorchLightning/pytorch-lightning/issues/1447
