### ISSUE TITLE
Run WandbLogger with no internet.

### ISSUE THREAD

**Issue by rohitgr7** [PyTorchLightning/pytorch-lightning#1439]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
Is there any way to run wandb logger offline without the internet? I was trying to use it for a competition with the rule of no internet access. Or any other online logger that can do the same without the internet? I am using it in Kaggle kernels. So if there is any trick or a hacky way to do that with no internet access, please share.:grin:

#### What have you tried?
I tried the offline parameter but still needs wandb authentication using the wandb key.

#### What's your environment?

 - Linux: [e.g. iOS, Linux, Win]
 - Pip [e.g. pip, conda]
 - Version [e.g. 0.5.2.1]

**Comment by awaelchli** [comment]
WandB can be installed and used locally as a docker: https://docs.wandb.com/self-hosted
Other loggers that I know (can) run locally are TensorBoard and MLFlow.

**Comment by rohitgr7** [comment]
Resolved: https://github.com/wandb/client/issues/960#issuecomment-612149459
