### ISSUE TITLE
More granular callbacks

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#1440]
### Motivation

I am currently implementing #765 (make progress bar into a callback) and I need additional callback methods to do this.

### Pitch

introduce these new callback methods:

- `on_train_batch_start` (currently named `on_batch_start`)
- `on_train_batch_end` (currently named `on_batch_end`)
- `on_val_batch_start`
- `on_val_batch_end`
- `on_test_batch_start`
- `on_test_batch_end`

and make `on_batch_start` run on any of the above `*_start` (same for `on_batch_end`)

Further suggestions:
- introduce `on_train_epoch_start`, `on_val_epoch_start`, `on_test_epoch_start` and corresponding `*_end` methods.

### Alternatives

Keep as is, but I don't know how to implement the  progress bar callback otherwise for validation/test updates.

**Comment by awaelchli** [comment]
For the record, #1450 introduced callbacks for validation_start/end, test_start/end, and sanity_check_start/end. 

The question remains whether we should rename `on_batch_*` to `on_training_batch_*` for consistency with the naming of the others.

**Comment by Borda** [comment]
> The question remains whether we should rename `on_batch_*` to `on_training_batch_*` for consistency with the naming of the others.

that it shall be for all batch train/valid...
