### ISSUE TITLE
Also update progress_bar in training_epoch_end

### ISSUE THREAD

**Issue by Deanamic** [PyTorchLightning/pytorch-lightning#1448]
## 🚀 Feature
[PR 1357](https://github.com/PyTorchLightning/pytorch-lightning/pull/1357) implements training_epoch_end to log metrics. The comments in the issue suggest that it should behave like validation_epoch_end, but the PR only replicates the callbacks and metric logging. This feature would add updates to the progress bar as well.

### Motivation
Motivation is for the same usecase as having a progress bar. 
While tensorboard or any other logger is a great resource to have. It is painful to set up in environments like slurm where you can only submit jobs and possibly cannot forward ports or set up the logging.
### Pitch

The changes should only entail adding an update to tqdm [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/b2707c9b2ebeac03f19a3939df9432ac8859d894/pytorch_lightning/trainer/training_loop.py#L503)

**Comment by awaelchli** [comment]
I will look into this after #1450 is done :)
