### ISSUE TITLE
add support for prefetch_generator

### ISSUE THREAD

**Issue by Ir1d** [PyTorchLightning/pytorch-lightning#1454]
## 🚀 Feature

https://github.com/justheuristic/prefetch_generator

it can be used to speed up the dataloader.

Perhaps related to #1316 , but prefetch_generator is quite different from DALI

**Comment by HenryJia** [comment]
PyTorch dataloader already uses queues and prefetching 

https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L672

https://github.com/pytorch/pytorch/blob/master/torch/utils/data/_utils/worker.py#L107
