### ISSUE TITLE
ddp causes an error when my model class has a lambda function

### ISSUE THREAD

**Issue by thnkim** [PyTorchLightning/pytorch-lightning#1457]
### To Reproduce

1. Add ```self.fn_error = lambda x: x``` to the model (e.g., your_model).
2. Run the trainer with ddp backend.
4. It causes an error like 'AttributeError: Can't pickle local object 'your_model.__init__.<locals>.<lambda>'.

### Expected behavior
When I use dp backend, everything is ok.

### Environment
```
cuda:
	GPU:
		TITAN RTX
		TITAN RTX
	available:           True
	version:             10.2
packages:
	numpy:               1.17.2
	pyTorch_debug:       False
	pyTorch_version:     1.6.0a0+b55dee9
	pytorch-lightning:   0.7.4-dev
	tensorboard:         2.2.0
	tqdm:                4.45.0
system:
	OS:                  Linux
	architecture:
		64bit
		
	processor:           x86_64
	python:              3.7.4
	version:             #86~16.04.1-Ubuntu SMP Mon Jan 20 11:02:50 UTC 2020
```

**Comment by thnkim** [comment]
It seems to be an issue on PyTorch (torch.multiprocessing).

**Comment by williamFalcon** [comment]
this is a pytorch limitation

**Comment by Borda** [comment]
can we crap the lambda with a `functools.partial`?
