### ISSUE TITLE
Test metrics are no longer pushed to Comet.ML (and perhaps others)

### ISSUE THREAD

**Issue by alsrgv** [PyTorchLightning/pytorch-lightning#1460]
## 🐛 Bug

PyTorch Lightning 0.7.2 used to publish test metrics to Comet.ML.  Commit https://github.com/PyTorchLightning/pytorch-lightning/commit/ddbf7de6dc97924de07331f1575ee0b37cb7f7aa has broken this functionality.

### To Reproduce

Run fast-run of training and observe test metrics not being submitted to Comet.ML (and possibly other logging destinations).

### Environment

```
cuda:
        GPU:
                Tesla T4
        available:           True
        version:             10.1
packages:
        numpy:               1.17.2
        pyTorch_debug:       False
        pyTorch_version:     1.4.0
        pytorch-lightning:   0.7.4-dev
        tensorboard:         2.2.0
        tqdm:                4.45.0
system:
        OS:                  Linux
        architecture:
                64bit

        processor:           x86_64
        python:              3.6.8
        version:             #69-Ubuntu SMP Thu Mar 26 02:17:29 UTC 2020
```

cc @alexeykarnachev

**Comment by williamFalcon** [comment]
@PyTorchLightning/core-contributors or @alsrgv mind submitting a PR? good catch!

**Comment by alsrgv** [comment]
Happy to, but I could use some pointers into what may be broken.  Does logging use aggregation with flush in the end, and that flush is somehow not called for the test pass?  @alexeykarnachev, any ideas?

**Comment by Borda** [comment]
Shall be fixed in #1459

**Comment by alexeykarnachev** [comment]
Sorry, guys, totally missed the messages.
@Borda , is anything required from my end?

**Comment by Borda** [comment]
I think it is fine, just if you have an idea why the Github Actions fails/hangs...
https://github.com/PyTorchLightning/pytorch-lightning/pull/1459/checks?check_run_id=584135478
