### ISSUE TITLE
Leaked semaphores with DDP training

### ISSUE THREAD

**Issue by VitorGuizilini** [PyTorchLightning/pytorch-lightning#1461]
I constantly get this warning when training on an AWS instance (8 GPUs, using DDP). It does not crash, but the training hangs for a few seconds before continuing.

```
/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 3 leaked semaphores to clean up at shutdown
```

I can share my docker container if necessary, as it might be an issue with library versions.

**Comment by vguizilini** [comment]
FYI this behaviour only shows up in the latest master (8544b334e4af9caa060a280146e7d3bb10648332), if I install 0.7.3 it disappears.

**Comment by tullie** [comment]
@vguizilini  I haven't been able to reproduce this on latest master while running with 8 GPUS using DDP. Are you still getting the warning?
