### ISSUE TITLE
Model checkpoint upload with TRAINS logger is broken

### ISSUE THREAD

**Issue by iakremnev** [PyTorchLightning/pytorch-lightning#1466]
## 🐛 Bug

When using TRAINS logger, asynchronous model checkpoint upload fails due to renaming of the checkpoint file.
Specifically, [this](https://github.com/PyTorchLightning/pytorch-lightning/blob/3f1e4b953f84ecdac7dada0c6b57d908efc9c3d3/pytorch_lightning/trainer/training_io.py#L244) portion of code is incoherent with TRAINS logic. `torch.save` is patched by TRAINS, and so [its definition](https://github.com/allegroai/trains/blob/d4358af1e804374629667f21a98aa6d20b612db2/trains/binding/frameworks/pytorch_bind.py#L45) is called, starting an asynchronous upload of `.part` checkpoint file to specified `output_uri`.

### To Reproduce

1. Compose minimal training example.
2. Pass `logger=TrainsLogger(..., output_uri=<some_real_uri>)` to `Trainer` instance.
3. Launch training.
4. Behold messages like "Trains upload started, file = "model_epoch=0.ckpt.part" and then "Train upload failed".

### Expected behavior

Model checkpoint is uploaded only after the atomic save or the file is renamed only after upload completes.

### Environment

cuda:
        GPU:
                GeForce RTX 2060
        available:           True
        version:             10.1
packages:
        numpy:               1.16.4
        pyTorch_debug:       False
        pyTorch_version:     1.4.0
        pytorch-lightning:   0.7.3
        tensorboard:         2.2.0
        tqdm:                4.45.0
system:
        OS:                  Linux
        architecture:
                64bit
                ELF
        processor:           x86_64
        python:              3.6.8
        version:             #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020

### PS

I could add code sample later if needed.

**Comment by bmartinn** [comment]
@iakremnev thank you for catching this buggy behavior.
Seems like a bug in *Trains* which the *pytorch-lightning* exposes.
Basically renaming or deleting a model file before the async upload is completed will cause this error.

Let's continue the discussion on the Trains repository.
For the time being, please close the issue here.
