### ISSUE TITLE
transfering of data to gpu with custom data type

### ISSUE THREAD

**Issue by JonathanSchmidt1** [PyTorchLightning/pytorch-lightning#1467]
#### What is your question?
The batch, that should be passed to the train/val step consists of a list of https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html torch_geometric Data objects. The batch is not passed to the corresponding gpus. I assumed that this would happen in the pytorch_lightning/trainer/distrib_parts.py transfer methods, however the code never arrives in these methods. Where do I have to change the code of lightning to allow for custom data types ?
#### What have you tried?
If I change the batch to a list of tensors, they are correctly transfered, so I assume the rest of my code works fine. Transfering the data by adding the corresponding to device calls in the train step also works.
#### What's your environment?

 - Ubuntu 18.04
 - pip
 - Version '0.7.1'
- dgx2 cluster, no slurm

**Comment by nghorbani** [comment]
This issue remains and pytorch lighting seems to be working with pytorch geometric data types upto pl version 0.9.0.
The loaded batch is wrong is size (i.e. not divided by the number of gpus) and the batch is not on the correct device.
