### ISSUE TITLE
Load model from checkpoint when model is not instantiated in __init__

### ISSUE THREAD

**Issue by jpvcaetano** [PyTorchLightning/pytorch-lightning#1472]
## 🚀 Feature
Be able to load a model from a checkpoint path when the model is not instantiated in __init__

### Motivation

Imagine I can only instantiate the model after looking at the train dataset. Ex: for the creation of emb layers you need the number of categories in categorical features.

### Pitch

I would like an option where when loading a model from a checkpoint I could tell it I need to run prepare data first so I can instantiate the model for instance.

### Alternatives

There are probably better alternatives to this to the option presented in pitch.

**Comment by arroqc** [comment]
Why not initiate based on some params that you derive from the data and then pass to the module ?

**Comment by jpvcaetano** [comment]
Could do that. But would need to do the preprocessing of the datasets outside of lightning. Was wondering if it could be done inside.

**Comment by Borda** [comment]
@jpvcaetano @arroqc have you come to a solution? :rabbit:

**Comment by raynardj** [comment]
@jpvcaetano any thoughts?
