### ISSUE TITLE
Customizing hparams after loading checkpoint

### ISSUE THREAD

**Issue by tullie** [PyTorchLightning/pytorch-lightning#1474]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
I'm wondering what the best practice for loading a model with different hparams than what is stored in the checkpoint?

I realize I could just load the model and set them afterwards e.g.: 
```
model = model.load_from_checkpoint(args.checkpoint_file) # Load model

# Set hparams etc..
model.hparams.arg1 = 0.0
model.hparams.arg2 = 1.0
 
```
But the problem is that my  model __init__ function depends on the hparams arg1 and arg2 so they're set too late.

I could also do 
```
checkpoint = torch.load(args.checkpoint_file)
checkpoint['hparams']['arg1'] = 0.0
checkpoint['hparams']['arg2'] = 1.0
model = model._load_state_dict(checkpoint)
```

The problem here is that i'm using the protected function _load_state_dict. Is there another way of solving this that i've missed? Or could we consider making _load_state_dict public?

**Comment by williamFalcon** [comment]
@tullie good question, maybe we can have a flag for disabling hparam use?
```python
load_from_checkpoint(PATH, auto_hparam=False, arg1=my_arg, arg2=my_arg2, hparam={...})
```

load_from_checkpoint currently allows passing in the args directly as shown above
```python
load_from_checkpoint(PATH, auto_hparam=False, arg1=my_arg, arg2=my_arg2)
```
so, in this case an arg (hparam) would be a regular arg which you could then construct to be whatever you want.

Alternative 2:
We add a ```hparam_updates``` arg which sets those updates in the hparams

```python
load_from_checkpoint(PATH, hparam_updates={'arg1': 0.0, 'arg2': 0.0})
```
