### ISSUE TITLE
on_before_zero_grad hook

### ISSUE THREAD

**Issue by sebastienwood** [PyTorchLightning/pytorch-lightning#1481]
## 📚 Documentation

The documentation report the method `on_before_zero_grad`. Strangely, this method is not shown in the lifecycle for hooks documentation. Moreover, when it is defined in a lightning module it is not called.

Hence the question : is it a discontinued hook ? If so we could erase its mention in the docs.

Thanks.

**Comment by awaelchli** [comment]
Hi
I added it in #1483 . Do you see any other hooks missing from the lifecycle?

**Comment by sebastienwood** [comment]
@awaelchli not that I know ! 
It seems however that this particular hook is not called. Tried a few experiments and never reached it. [The codebase](https://github.com/PyTorchLightning/pytorch-lightning/blob/8544b334e4af9caa060a280146e7d3bb10648332/pytorch_lightning/trainer/training_loop.py#L636) doesn't seem to call it either.
