### ISSUE TITLE
ImportError: cannot import name 'WandbLogger' from 'pytorch_lightning.loggers'

### ISSUE THREAD

**Issue by braindotai** [PyTorchLightning/pytorch-lightning#1487]
## 🐛 Bug

I tried importing wandb logger from pytorch_lightning.loggers and got import error.

#### Code sample
```python
from pytorch_lightning.loggers import WandbLogger
```
### Environment

 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.7.7
 - CUDA/cuDNN version: Cuda compilation tools, release 10.1, V10.1.105
 - GPU models and configuration: 1050ti

**Comment by olineumann** [comment]
What is the exact error message?

**Comment by awaelchli** [comment]
`from pytorch_lightning.loggers.wandb import WandbLogger` also doesn't work?

**Comment by lezwon** [comment]
You need to install wandb package first. 
`pip install  wandb`

**Comment by Borda** [comment]
You may also install all extra libs `pip install -r requirements-extra.txt`
@braindotai feel free to re-open if needed :rabbit:

**Comment by lezwon** [comment]
Guess it would be helpful if there was a error displayed suggesting to install the logger package while importing. I had this same issue while using comet logger and wasn't sure what was wrong.

**Comment by braindotai** [comment]
The issue is solved. Thanks to everyone for the quick response.
