### ISSUE TITLE
ImageNet example shows contradictions

### ISSUE THREAD

**Issue by sebastienwood** [PyTorchLightning/pytorch-lightning#1491]
## 📚 Documentation

Hi ! :)

There is a puzzling fact for newcomer found at the dataloader definitions of the ImageNet example script [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/f293c9b5f4b4f9fabb2eec0c369f08a66c57ef14/pl_examples/domain_templates/imagenet.py#L138)

There is a sampler that is manually defined.

The documentation mentions that `With Lightning, you don’t need to do this because it takes care of adding the correct samplers when [needed.`([source](https://pytorch-lightning.readthedocs.io/en/stable/multi_gpu.html#remove-samplers))

What is the correct stance for the sane Lightning beginner ?

**Comment by miriaford** [comment]
Yes I'm also very confused by this, please explain, thanks!

**Comment by miriaford** [comment]
@sebastienwood I tried to just remove the manual sampler, and the code seems to work fine. It's supposed to automatically replace the sampler anyway. Could you please verify?
