### ISSUE TITLE
Switch from tqdm to fastprogress for jupyter-lab friendly progress bars

### ISSUE THREAD

**Issue by tcwalther** [PyTorchLightning/pytorch-lightning#1500]
## 🚀 Feature
Use https://github.com/fastai/fastprogress instead of tqdm for displaying progress bars.

### Motivation

tqdm doesn't work well with Jupyter Lab. This creates issues with pytorch-lightning's progress bars, where each validation bar creates a newline in the cell output: #1399. This is a well-known issue in jupyter-widgets: https://github.com/jupyter-widgets/ipywidgets/issues/1845

The Fast.ai people developed [fastprogress](https://github.com/fastai/fastprogress) as a replacement for exactly this reason.

### Pitch

Replace tqdm with fastprogress.

### Alternatives

The alternative is to wait for jupyter-widgets to fix the issue on their side. Given that this issue has been around since November 2017, I'm not too hopeful that it will happen, though. It looks like this would require major design changes in ipywidgets and/or jupyter-lab.

### Additional context

Motivated by #1399.

**Comment by awaelchli** [comment]
Could be done as a follow up to the progress bar callback PR ❤️

**Comment by williamFalcon** [comment]
@tcwalther sorry, we don't want to  add more dependencies to lightning.
If this is needed, then it should be added as a callback with a fresh implementation, but no dependencies :)

**Comment by ethanwharris** [comment]
Perhaps a fast progress callback could be a good lightning bolt (https://github.com/PyTorchLightning/lightning-bolts)???

**Comment by Borda** [comment]
so open an issue there?

**Comment by ethanwharris** [comment]
https://github.com/PyTorchLightning/lightning-bolts/issues/2
