### ISSUE TITLE
change method signature for better pycharm auto complete

### ISSUE THREAD

**Issue by liyiwei979621500** [PyTorchLightning/pytorch-lightning#1525]
## 🚀 Feature
imporve pycharm auto complete experience

### Motivation
The auto complete result when typing def training_step
```
def training_step(self, *args, **kwargs):
```
### I want it to be
```
def training_step(self, batch, batch_idx):
```

**Comment by aiyolo** [comment]
so anyone could explain what causes it?

**Comment by liyiwei979621500** [comment]
@aiyolo 

https://github.com/PyTorchLightning/pytorch-lightning/blob/a22a8142ac65668781a6e6f76d3c4e55ea7c249a/pytorch_lightning/core/lightning.py#L144
