### ISSUE TITLE
add_argparse_args --gpus 1 error

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#1531]
When using 
```python
parser = Trainer.add_argparse_args(parser)
args = parser.parse_args()

# 
Trainer.from_argparse_args(args)
```
```bash
python main.py --gpus 1
```

This fails because it thinks we requested GPU at index 1

**Comment by Borda** [comment]
is this still valid? :rabbit:

**Comment by awaelchli** [comment]
nope, this is fixed on master. 
I just tested it on my single gpu machine and it runs as expected on gpu 0.
