### ISSUE TITLE
Allow keeping default save_dir in ModelCheckpointer

### ISSUE THREAD

**Issue by ematvey** [PyTorchLightning/pytorch-lightning#1535]
##  Feature
Make `filepath` argument of `ModelCheckpointer` optional.

### Motivation
I'm pretty happy with all defaults of `ModelCheckpointer` except `save_top_k`. In case I want to override that parameter I have to write some awkward code related to figuring out the checkpointing path, which is normally only known at runtime:

```python
DEFROOT = Path('/data/models/lightning')
logger = WandbLogger(name=net.hparams.run_name, project=net.hparams.project, save_dir=str(DEFROOT))
logger.watch(net)
_ = logger.experiment  # create an experiment to determine version
cp_template = str(DEFROOT / net.hparams.project / ('version_'+logger.version) / 'checkpoints' / '{epoch:04d}-{val_loss:.2f}-{other_metric:.2f}.pt')

checkpointer = ModelCheckpoint(
    filepath=cp_template,
    save_top_k=10,
    verbose=True,
    monitor='val_loss',
    mode='min',
)

trainer = Trainer(
    gpus=1,
    logger=logger,
    default_root_dir=DEFROOT,
    checkpoint_callback=checkpointer,
    **extra,
)
trainer.fit(net)
```

It would be nice to have an option to allow Lightning to determine runtime-valued save location instead. Additionally, it would be nice to have an option to override checkpoint filename without overriding the whole save path.

**Comment by yukw777** [comment]
The fix to this issue introduced a bug.. if you don’t pass in `filepath` and use the default `None`, this check will fail b/c you can’t run `os.path.isdir()` on `None`

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/callbacks/model_checkpoint.py#L89

cc @PyTorchLightning/core-contributors
