### ISSUE TITLE
LightningTemplateModel is broken

### ISSUE THREAD

**Issue by festeh** [PyTorchLightning/pytorch-lightning#1546]
## 🐛 Bug

`LightningTemplateModel` has no implemented `validation_step_end` method. See [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/8035c10f379dd0c00dcf00bd3fdee3f66fb074a2/pl_examples/models/lightning_template.py#L245)
### To Reproduce
Just try to run test evaluation on MNIST example

### Expected behavoir
It should not crash

**Comment by Borda** [comment]
@festeh mind draft a PR to fix it? :rabbit:

**Comment by festeh** [comment]
@Borda yes, will make it soon
