### ISSUE TITLE
How can I log (to tensorboard for example) at process 0 only?

### ISSUE THREAD

**Issue by thnkim** [PyTorchLightning/pytorch-lightning#1601]
#### What is your question?
I'm using two GPU's. It seems training_step with batch_idx = 0 is called twice.
I want to log something when the current process is 0.

**Comment by williamFalcon** [comment]
we already automatically log only from gpu 0. 

to print anything from only gpu zero use self.print()

**Comment by thnkim** [comment]
Thank you. But I wanted to call add_image (like self.logger.experiment.add_image()).
I've just found that I can refer self.trainer.proc_rank :)

If I can easily log image also, please let me know.
Thank you.

**Comment by williamFalcon** [comment]
https://pytorch-lightning.readthedocs.io/en/latest/loggers.html#using-loggers

**Comment by wuyxiquanquan** [comment]
> https://pytorch-lightning.readthedocs.io/en/latest/loggers.html#using-loggers

Sorry sir, I can't find anything on this website.
<img width="1276" alt="Screen Shot 2020-05-05 at 5 51 45 PM" src="https://user-images.githubusercontent.com/40594739/81054321-2a8b6200-8ef9-11ea-977d-ceb309b9fe5c.png">

**Comment by Borda** [comment]
@wuyxiquanquan it is fixed now
