### ISSUE TITLE
Early stopping + checkpoint key

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#1618]
Consider updating how we condition early stopping or checkpoint

```python
return {'early_stop_on': mse_loss, 'checkpoint_on': other_metric}
```

Instead of:
```python
# only if val_loss is present
return {'val_loss': val_loss}
```

**Comment by jeremyjordan** [comment]
in my opinion all of the configuration for early stopping or model checkpointing should occur in the initialization of the callback object. if we condition based on a special key in the step return, users have to change their model to modify the behavior of a callback.

**Comment by williamFalcon** [comment]
as a shortcut, can the trainer flags already support the key?

early_stop_callback=‘val_loss’ 

for example
