### ISSUE TITLE
How can I write the validation and training losses from the progress bar to disk?

### ISSUE THREAD

**Issue by zeeshansayyed** [PyTorchLightning/pytorch-lightning#1626]
Is there a way to output the results of the progress bar to file? Or will I have to write my own simple logger for the same? I want to use this as a quick sanity check before resorting to other more complex loggers.

**Comment by awaelchli** [comment]
Hi
Anywhere in your LightningModule you can access the progress_bar_dict like so:

self.trainer.progress_bar_dict

Then you can format it the way you like and print it to a file, for example in one of the hooks. I wouldn't do it in training loop though, as it could slow things down. If you do it there, maybe only print every 100 iterations or so.

**Comment by awaelchli** [comment]
The loggers though are very easy to use. 
Note that the progress_bar values are smoothed over the epoch.
