### ISSUE TITLE
add Trainer states

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#1633]
## 🚀 Feature

Add trainer states so in each time user get info what is happening

### Motivation

simplify the return values and clean up the interface

### Pitch

The state will be implemented as enum and updated according to Trainer phase:
- INITIALIZE
- RUNNING
- FINISHED
- TEARING_DOWN
- TERMINATED
- ...

**Comment by zerogerc** [comment]
As I understood it right, the change is to add enum with phases, add corresponding updates, and logging of the current phase. @Borda I can take it as my first issue.

**Comment by Borda** [comment]
@zerogerc cool, that it adds an enum (with possible texts) and change the states according to the training phase...

**Comment by awaelchli** [comment]
Don't we want to control these states with decorators? I think having the code for these state changes mixed with the core training logic is a bit distracting and fragile, don't you think?

**Comment by Borda** [comment]
> Don't we want to control these states with decorators? I think having the code for these state changes mixed with the core training logic is a bit distracting and fragile, don't you think?

well, decorators would be nicer :] @awaelchli mind comment/suggest on the open PR?
