### ISSUE TITLE
Using default path in ModelCheckpoint does not work 

### ISSUE THREAD

**Issue by benob** [PyTorchLightning/pytorch-lightning#1660]
According to the implementation, passing None as model path uses the default path for checkpoints. However, the following test prevents this feature to be used when save_top_k > 0:
https://github.com/PyTorchLightning/pytorch-lightning/blob/3e8f2d99a9951bfb5fc67a98614128317913be1d/pytorch_lightning/callbacks/model_checkpoint.py#L89

It results in the following error:
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

Also, as a side issue, the example for model checkpointing from the documentation suggests using os.getcwd() as path and save_top_k=True, which results in the warning being displayed and potentially all files of current directory being removed. New users have to be very careful if they don't wand their source code deleted.

**Comment by olineumann** [comment]
Just checked it. Got the same issue. Could be fixed by adding 'filepath is not None'. See:

https://github.com/olineumann/pytorch-lightning/tree/issue/checkpoint_filepath_none

For quick fix:
```
pip install git+https://github.com/olineumann/pytorch-lightning.git@issue/checkpoint_filepath_none
```

**Comment by olineumann** [comment]
Duplicate PR because of #1654
