### ISSUE TITLE
batch_sampler in dataloader cant work properly in ddp mode

### ISSUE THREAD

**Issue by stas6626** [PyTorchLightning/pytorch-lightning#1661]
## 🐛 Bug

when we are setting batch_sampler, we cannot set sampler [proof](https://github.com/pytorch/pytorch/blob/1b525f88ce150fdc816856d23b8e840a32cd3eae/torch/utils/data/dataloader.py#L194)
but in ddp mode lightning falls [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/79196246cfcc73391de1be71bfb27d4366daf75a/pytorch_lightning/trainer/training_loop.py#L328) with error like `self.train_dataloader.sampler.set_epoch(epoch)
AttributeError: 'SequentialSampler' object has no attribute 'set_epoch'`

also, lightning check existence of sampler, but dataloader always have sampler [proof](https://github.com/pytorch/pytorch/blob/1b525f88ce150fdc816856d23b8e840a32cd3eae/torch/utils/data/dataloader.py#L207)

### To Reproduce

1. set batch_sampler
2. disable auto distributed batch sampler setter
3. use ddp

### Environment

i tried on 0.7.4 and 0.7.5

**Comment by stas6626** [comment]
probably we need just replace `self.use_ddp or self.use_horovod and hasattr(self.train_dataloader.sampler, 'set_epoch')` to `(self.use_ddp or self.use_horovod) and hasattr(self.train_dataloader.sampler, 'set_epoch') `

**Comment by stas6626** [comment]
Lol, i tried it locally and it fixed my problem. shall i submit PR @williamFalcon ?

**Comment by Borda** [comment]
@stas6626 just pls check recent PRs on Horovod by @tgaddair

**Comment by edenlightning** [comment]
Closing this. @stas6626 please reopen if still needed.

**Comment by jdcla** [comment]
I am currently having the same problem. It does not seem possible to use SequentialSampler or RandomSampler with ddp, as pytorch-lightning returns the error:
> AttributeError: 'SequentialSampler' object has no attribute 'batch_size'

**Comment by samaritanhu** [comment]
I have the same problem as well...

> AttributeError: 'SequentialSampler' object has no attribute 'set_epoch'
