### ISSUE TITLE
Trainer add args doesn't add default root dir

### ISSUE THREAD

**Issue by tshrjn** [PyTorchLightning/pytorch-lightning#1665]
## 🐛 Bug
1. When using `parser = Trainer.add_argparse_args(parser)`, it's supposed to put all Trainer's arguments in the argparse with default values. Though currently it doesn't add `default_root_dir` and you get the error:

```
'Namespace' object has no attribute 'default_root_dir'
```
It does add `default_save_path` which is deprecated.

#### Code Sample
```python
import argparse
from pytorch_lightning import Trainer

parser = argparse.ArgumentParser(description='demo')
parser = Trainer.add_argparse_args(parser)
args = parser.parse_args()

print(args.default_root_dir)
```

A similar unit test could also be made, if not there already.

### Environment

```
* CUDA:
        - GPU:
                - GeForce RTX 2080 Ti
                - GeForce RTX 2080 Ti
                - GeForce RTX 2080 Ti
                - GeForce RTX 2080 Ti
                - GeForce RTX 2080 Ti
                - GeForce RTX 2080 Ti
                - GeForce RTX 2080 Ti
                - GeForce RTX 2080 Ti
        - available:         True
        - version:           10.1
* Packages:
        - numpy:             1.18.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.4.0
        - pytorch-lightning: 0.7.3
        - tensorboard:       2.2.0
        - tqdm:              4.45.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                -
        - processor:         x86_64
        - python:            3.6.7
        - version:           #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019
```

**Comment by olineumann** [comment]
Did you tried to update to 0.7.5. Maybe it is already solved.

**Comment by tshrjn** [comment]
Hi @olineumann, yes updating did resolve this. However, the `profiler` arg is now broken. The same demo code above with `profiler` gives the same error `'Namespace' object has no attribute 'profiler'`.

**Comment by olineumann** [comment]
What do you mean 'with profiler'? Do you mean Trainer(..., profiler=True)? But you don't initialize a Trainer.

Running your code or this below won't crash with any error on my machine.
```python
import argparse
from pytorch_lightning import Trainer

parser = argparse.ArgumentParser(description='demo')
trainer = Trainer(profiler=True)
parser = trainer.add_argparse_args(parser)
args = parser.parse_args()

print(args.default_root_dir)
```

**Comment by tshrjn** [comment]
`add_argparse_args ` is supposed to add the args from trainer to parser. But it doesn't do that for a few args. In this case `profiler`, previously the issue was for `default_root_dir`.

Try the following code by running:
`python demo.py --profiler True` or  other possibly accepted way `python demo.py --profiler`  with the following code:

```
import argparse
from pytorch_lightning import Trainer

trainer = Trainer()
parser = argparse.ArgumentParser(description='demo')
parser = trainer.add_argparse_args(parser)
args = parser.parse_args()

print(args.profiler)

```

**Comment by tshrjn** [comment]
Any update?

**Comment by olineumann** [comment]
I just created a PR. After looking at the code I found out that add_argparse_args is checking the argument types and is only adding attributes of type str, float, int or bool. The profiler attribute could be of type bool so it should be a bug.

I saw that get_init_arguments_and_types() is returning profiler as argument but only of type BaseProfiler. After updating typing annotation of profiler argument it worked. Should be available in the next version.

See PR #1794

**Comment by tshrjn** [comment]
A similar issue is with the pickling of the profiler when it's a `Profile` object & the trainer tries to save the `hparams`.

```python
TypeError: can't pickle Profile objects
```


Example code:

```python
import argparse
from pytorch_lightning import Trainer
from pytorch_lightning import profiler
from pl_bolts.models.gans import BasicGAN

trainer = Trainer()
parser = argparse.ArgumentParser(description='demo')
parser = trainer.add_argparse_args(parser)
args = parser.parse_args()
model = BasicGAN()

trainer = Trainer.from_argparse_args(
        args, profiler=profiler.AdvancedProfiler())
trainer.fit(model)

```

**Comment by olineumann** [comment]
Can't reproduce your issue on pl version 0.7.6rc1. On my machine it runs with profiler on and saves checkpoints without crashing. Also this wouldn't belong to the topic of this issue imo. This would be a bug in saving routine.
