### ISSUE TITLE
ModelCheckpoint/Callback checkpointing issue with huggingface/tokenizers object

### ISSUE THREAD

**Issue by devjeetr** [PyTorchLightning/pytorch-lightning#1677]
#### What is your question?
I have a model that stores as an attribute a `huggingface/tokenizers` object. This is not stored as a part of the model's `hparams`, but as an instance attribute. When I simply use `Trainer` without `ModelCheckPoint` or custom callbacks to save the model, checkpoints are properly stored by lightning. However, as soon as I use either `ModelCheckpoint` or callbacks, I get an exception saying that tokenizer objects cannot be pickled. 

I have tried using `save_weights_only=True`, and in my custom callbacks, I take care to only store the model's `state_dict`. I have also checked all child modules used by my model to ensure that I'm not accidentally storing the vocabulary somewhere. The only reference to the `tokenizer` is in my model class.

Am I missing something here?
 

#### What's your environment?

 - OS: Ubuntu 19
 - Packaging conda
 - Version 0.7.5

Edit: Seems like `save_weights_only` does not work. I can confirm this for `0.7.5`. I also found that there is an issue opened about this #427. I'm going to investigate more to see what is going on with this.

**Comment by yukw777** [comment]
This isn't really a PL issue. HuggingFace's tokenizer is written in Rust with a python binding, so you can't really pickle it as it's not a native python object. You'd have to write custom code to load it after PL loads all the appropriate PyTorch weights for you. Take a look at this hook: https://pytorch-lightning.readthedocs.io/en/stable/pytorch_lightning.core.lightning.html#pytorch_lightning.core.lightning.LightningModule.on_load_checkpoint, which is a good place to take care of this type of things.

**Comment by yukw777** [comment]
Oops sorry it seems like I misunderstood your question! I'll leave my answer up for posterity though haha

**Comment by williamFalcon** [comment]
@srush

**Comment by devjeetr** [comment]
> Oops sorry it seems like I misunderstood your question! I'll leave my answer up for posterity though haha

I think asking my real question in the "What you have tried" section was confusing. Edited!
