### ISSUE TITLE
Folder names inconsistent if version is string and using `TensorBoardLogger`

### ISSUE THREAD

**Issue by hjalmarlucius** [PyTorchLightning/pytorch-lightning#1681]
A) According to `TensorBoardLogger`, if `version` is a string then it is used as the run-specific subdirectory name, otherwise ``'version_${version}'`` is used.
B) However,  in the callback ``'version_${version}'`` is always used.

LINKS:
A) https://github.com/PyTorchLightning/pytorch-lightning/blob/8b82ce09039e75f3fcb77a987c964249e38def3b/pytorch_lightning/loggers/tensorboard.py#L40
B) https://github.com/PyTorchLightning/pytorch-lightning/blob/3e8f2d99a9951bfb5fc67a98614128317913be1d/pytorch_lightning/trainer/callback_config.py#L55

Edit: This issue comes up as I generally use git commit IDs as version numbers.

**Comment by CarloLucibello** [comment]
this has been recently fixed in #1748
