### ISSUE TITLE
How to disable progress bar and printing model structure?

### ISSUE THREAD

**Issue by liyiwei979621500** [PyTorchLightning/pytorch-lightning#1686]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What's your environment?

 - OS: [e.g. iOS, Linux, Win]
 - Packaging [e.g. pip, conda]
 - Version [e.g. 0.5.2.1]

**Comment by SkafteNicki** [comment]
Progress bar can be disabled by setting the `progress_bar_refresh_rate` argument in trainer:
```
# don't show progress bar
trainer = Trainer(progress_bar_refresh_rate=0)
```

To disable model structure printing you can set the `weights_summary` argument in trainer:
```
# don't print a summary
trainer = Trainer(weights_summary=None)
```

please see the documentation on [trainer flags](https://pytorch-lightning.readthedocs.io/en/latest/trainer.html#trainer-flags) for more info.

**Comment by liyiwei979621500** [comment]
thanks @SkafteNicki

**Comment by fredericosantos** [comment]
`weights_summary` has been deprecated.

From the source code:
weights_summary: Prints a summary of the weights when training begins.
                .. deprecated:: v1.5
                    ``weights_summary`` has been deprecated in v1.5 and will be removed in v1.7.
                    To disable the summary, pass ``enable_model_summary = False`` to the Trainer.
                    To customize the summary, pass :class:`~pytorch_lightning.callbacks.model_summary.ModelSummary`
                    directly to the Trainer's ``callbacks`` argument.

progress_bar_refresh_rate: How often to refresh progress bar (in steps). Value ``0`` disables progress bar.
                Ignored when a custom progress bar is passed to :paramref:`~Trainer.callbacks`. Default: None, means
                a suitable value will be chosen based on the environment (terminal, Google COLAB, etc.).
                .. deprecated:: v1.5
                    ``progress_bar_refresh_rate`` has been deprecated in v1.5 and will be removed in v1.7.
                    Please pass :class:`~pytorch_lightning.callbacks.progress.TQDMProgressBar` with ``refresh_rate``
                    directly to the Trainer's ``callbacks`` argument instead. To disable the progress bar,
                    pass ``enable_progress_bar = False`` to the Trainer.

**Comment by pasinit** [comment]
when the progressbar is disabled, is it possible to still log the progress with every n steps automatically? Manually i guess one can just add prints on training_step and validation_step functions

**Comment by easz** [comment]
> when the progressbar is disabled, is it possible to still log the progress with every n steps automatically? Manually i guess one can just add prints on training_step and validation_step functions

how about [logging](https://pytorch-lightning.readthedocs.io/en/stable/extensions/logging.html)?
