### ISSUE TITLE
[Examples] The UNet model has some bugs

### ISSUE THREAD

**Issue by MrinalJain17** [PyTorchLightning/pytorch-lightning#1697]
## 🐛 Bug

The UNet model definition has some bugs pertaining to bilinear interpolation.

#### Code sample

1. 
https://github.com/PyTorchLightning/pytorch-lightning/blob/2950f669834506f8e5845b318b0f25d52d19e331/pl_examples/models/unet.py#L35-L37

In the code above, there seems to be a typo. The `bilinear` flag should be passed to the function `Up()`. It has instead been passed to the `.append()` method of the list.

2. 
https://github.com/PyTorchLightning/pytorch-lightning/blob/2950f669834506f8e5845b318b0f25d52d19e331/pl_examples/models/unet.py#L101-L104

The number of channels once the input passes through either one of these layers is different. For "bilinear", the number of channels remains the same, whereas they decrease to half if a `ConvTranspose2d` is used. This gives an error in the network's `.forward()` method.

I wanted to directly use the model for some other application, but not sure how issue 2 should be solved. Maybe use a 1x1 convolution to reduce the channels to half?

**Comment by Borda** [comment]
@MrinalJain17 mind draft a PR?
