### ISSUE TITLE
Enable Deepsource checks in CI/CD

### ISSUE THREAD

**Issue by ternaus** [PyTorchLightning/pytorch-lightning#1701]
In addition to flake8, mypy and other checks, I use https://deepsource.io/ for my projects.

It is free and from time to time it finds non-trivial bugs.

When I use it for projects with Pytorch-lightning and several validation loaders it throws me an error in python style and syntax. To overcome this I need to add things like:

`# skipcq: PYL-W0201` to my code. I would prefer to avoid it.

Is it possible that Deepsource checks would be allowed in Pytorch Lightning repo? I believe it will lead to better code quality.

**Comment by Borda** [comment]
we were using [Codefactor](https://www.codefactor.io/repository/github/pytorchlightning/pytorch-lightning) but it seems inactive now...

**Comment by ternaus** [comment]
I believe they look at the code with different angles, hence both could be enabled? :)

**Comment by thebpc** [comment]
Hi, have you tried https://www.deepcode.ai/, maybe yet another different/deeper angle, it requires no set-up. Here is what it currently finds in this repo: https://www.deepcode.ai/app/gh/PyTorchLightning/pytorch-lightning/e6b34ef90d5f3eac70154b305b476614a64f1981/_/dashboard

**Comment by Borda** [comment]
well there are several, and trying all would take too much time... I had a quite good experience with Codacy.io :] Not much happy about adding extra config needed by Deepsource

**Comment by Borda** [comment]
these are view to my forked:
- https://deepsource.io/gh/Borda/pytorch-lightning
- https://app.codacy.com/manual/Borda/pytorch-lightning/dashboard
- https://www.codefactor.io/repository/github/borda/pytorch-lightning
- https://www.deepcode.ai/app/gh/Borda/pytorch-lightning/cc6153c08b0f5292bfa60d93c913605ecfc7da3d/_/dashboard

**Comment by thebpc** [comment]
> these are view to my forked:
> 
> * https://deepsource.io/gh/Borda/pytorch-lightning
> * https://app.codacy.com/manual/Borda/pytorch-lightning/dashboard
> * https://www.codefactor.io/repository/github/borda/pytorch-lightning
> * https://www.deepcode.ai/app/gh/Borda/pytorch-lightning/cc6153c08b0f5292bfa60d93c913605ecfc7da3d/_/dashboard

@Borda  thanks for the links, very helpful, I looked at them, and as far as I can see only DeepCode.ai is reporting potential bugs. All the other tools are reporting https://www.pylint.org/ issues. I asked the DeepCode team responsible for why they are disabled as they are listed as supported there as well.

**Comment by Borda** [comment]
> I looked at them, and as far as I can see only DeepCode.ai is reporting potential bugs.

I am quite suspicious that there are only 4 potential bugs

> All the other tools are reporting https://www.pylint.org/ issues. I asked the DeepCode team responsible for why they are disabled as they are listed as supported there as well.

yes, check the other issues as pylint does would be helpful as we do not want to maintain too many tools/plaform
