### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by xinfangliu** [PyTorchLightning/pytorch-lightning#1702]
I set Cuda to 5 
INFO:lightning:CUDA_VISIBLE_DEVICES: [5]

however, there always a small part of the memory in gpu 0, when gpu 0 has not enough memory, error is produced.

![image](https://user-images.githubusercontent.com/35248527/80856418-6c5ba480-8c7c-11ea-97fd-1ded85ee0e5b.png)

in the img you can see that two processes is running on gpu5,6 and 2 * 577M is running gpu0.
I want the processes to only use what GPU I set.

**Comment by xinfangliu** [comment]
m24.py
![image](https://user-images.githubusercontent.com/35248527/80868176-6214c700-8ccb-11ea-982b-ed3b6c584e9f.png)

**Comment by jiahuei** [comment]
I have this same issue as well, it happens regardless of memory pinning

**Comment by jiahuei** [comment]
I am using this as a temporary fix
```
if __name__ == "__main__":
    args = parse_arguments()
    os.environ['CUDA_DEVICE_ORDER'] = 'PCI_BUS_ID'
    os.environ['CUDA_VISIBLE_DEVICES'] = ','.join(map(str, args.gpus))
    args.gpus = list(range(len(args.gpus)))
    ...
    trainer = pl.Trainer(gpus=args.gpus)
```

**Comment by Borda** [comment]
you shall user batch side finder

**Comment by williamFalcon** [comment]
can you try running on master? and also decrease your batch size?

**Comment by xinfangliu** [comment]
> can you try running on master? and also decrease your batch size?

It has no matter with the batch size, I  solved the problem with torch.cuda.set_device(6)
