### ISSUE TITLE
Model checkpoint and restore via GCS on Ai platform

### ISSUE THREAD

**Issue by dkajtoch** [PyTorchLightning/pytorch-lightning#1706]
#### What is your question?
I am training models on Google's ai platform and every checkpointing or restoration is done via Google Cloud Storage (not using pytorch-lightning for that yet). I noticed that pytorch-lightning uses `torch.save`, `torch.load` and `io` operations to work with saving and loading, which do not handle GCS by default (although I could pass file-like object to torch.save/load). Is it possible to extend the library so that is works with GCS without forking and modifying the code directly? The most important component for me is checkpoint save and restore on GCS. Is it a matter of Trainer class, Callbacks or model hooks?

**Comment by dkajtoch** [comment]
For the future release, my idea is that of all the necessary classes inherit from a basic `UniversalIO` class that implements atomic operations such as open, save, isdir, isfile, makedir etc. then it would be easy to define own storage backend.

**Comment by kaushikb11** [comment]
Tests has been added for GCS filesystem in #7946. Closing this issue!
