### ISSUE TITLE
example of doing simple inference with lightning

### ISSUE THREAD

**Issue by pamparana34** [PyTorchLightning/pytorch-lightning#1708]
I have an existing model where I load some pre-trained weights and then do inference (one image at a time) in pytorch. I am trying to basically convert it to a pytorch lightning module and am confused about a few things.

So currently, my `__init__` method for the model looks like this:

    self._load_config_file(cfg_file)
    # just creates the pytorch network
    self.create_network()  
    
    self.load_weights(weights_file)
    
    self.cuda(device=0)  # assumes GPU and uses one. This is probably suboptimal
    self.eval()  # inference mode

What I can gather from the lightning docs, I can pretty much do the same, except not to do the `cuda()` call. So something like:

    self.create_network()
    
    self.load_weights(weights_file)
    self.freeze()  # inference mode
    
So, my first question is whether this is the correct way to use lightning? How would lightning know if it needs to use the GPU? I am guessing this needs to be specified somewhere.

Now, for the inference, I have the following setup:

    def infer(frame):
        img = transform(frame)  # apply some transformation to the input
        img = torch.from_numpy(img).float().unsqueeze(0).cuda(device=0)
        with torch.no_grad():
            output = self.__call__(Variable(img)).data.cpu().numpy()
        return output

This is the bit that has me confused. Which functions do I need to override to make a lightning compatible inference?

Also, at the moment, the input comes as a numpy array. Is that something that would be possible from the lightning module or do things always have to use some sort of a dataloader? 

At some point, I want to extend this model implementation to do training as well, so want to make sure I do it right but while most examples focus on training models, a simple example of just doing inference at production time on a single image/data point might be useful. 

I am using 0.7.5 with pytorch 1.4.0 on GPU with cuda 10.1

Thank you for your work and patience with this newbie questions.

**Comment by hminle** [comment]
Hi @pamparana34 , do you find a way to do simple inference with lightning?
