### ISSUE TITLE
Can lightning auto-find unused GPUs

### ISSUE THREAD

**Issue by liyiwei979621500** [PyTorchLightning/pytorch-lightning#1712]
I have 2 gpus in a machine
Pl always find the same gpu to use.
Can it automaticly find this unused gpu and run on it ?

**Comment by festeh** [comment]
It would be great if Lightning had this functionality, yet even now it's simple to do in a local machine with some other library like [this](https://github.com/anderskm/gputil#examples) one.

**Comment by williamFalcon** [comment]
```python
Trainer(auto_select_gpus=True)
```

**Comment by xinfangliu** [comment]
it seems the Trainer(auto_select_gpus=True) can not choose the GPU has the largest memory

**Comment by lr1100** [comment]
I have a server with 8 P100s. When I use auto_select_gpus in my trainer, it still picks gpu 0 everytime. I am wanting to use 1 GPU  on the server, but would like it choose one that is not already being used.

I have tried:
`trainer = pl.Trainer(
        gpus=1,
        max_epochs=epochs,
        callbacks=callbacks,
        auto_select_gpus=True
    )`

and 
trainer = pl.Trainer(
        auto_select_gpus=True,
        max_epochs=epochs,
        callbacks=callbacks
    )

Here is  my  nvidia-smi:
![image](https://user-images.githubusercontent.com/2781468/108759005-05f48b00-7509-11eb-8147-f9bb0878c354.png)

Can someone look into this?  This is a neat feature that I would love to use.
Using pytorch-lightning  1.1.5

**Comment by ozanozyegen** [comment]
I would love to see this feature. The default behavior of `auto_select_gpus` can be updated to select the gpu with the lowest memory use.
