### ISSUE TITLE
Get Caffe2 Error when import the pytorch-lightning.

### ISSUE THREAD

**Issue by limberc** [PyTorchLightning/pytorch-lightning#1713]
## 🐛 Bug

Get Caffe2 Error when import the pytorch-lightning.

### To Reproduce

`import pytorch_lightning`
```
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: /opt/caffe2/build/lib/libcaffe2.so: undefined symbol: dnnLRNCreateForward_F32
CRITICAL:root:Cannot load caffe2.python. Error: /opt/caffe2/build/caffe2/python/caffe2_pybind11_state.so: undefined symbol: _Py_ZeroStruct
```
### Environment

* CUDA:
	- GPU:
		- Tesla P100-PCIE-16GB
	- available:         True
	- version:           10.0.130
* Packages:
	- numpy:             1.18.1
	- pytorch_lightning   0.7.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.2.0
	- tensorboard:       2.2.1
	- tqdm:              4.45.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
	- processor:         x86_64
	- python:            3.7.6
	- version:           #76-Ubuntu SMP Wed Feb 12 03:02:44 UTC 2020

**Comment by Borda** [comment]
well I do no think it is lightning issue as we rely on pytorch... @williamFalcon?

**Comment by awaelchli** [comment]
how do you activate the environment before you do the import? It must be trying to load caffe somewhere but definitely not in lightning.

**Comment by awaelchli** [comment]
Does it happen in the interactive python shell too?

**Comment by limberc** [comment]
> Does it happen in the interactive python shell too?

Yes it does!

![image](https://user-images.githubusercontent.com/18211333/80949209-28a49e80-8e26-11ea-83cb-bd2614bc65f1.png)

**Comment by Borda** [comment]
can you try `import pytorch`?

**Comment by limberc** [comment]
> can you try `import torch`?

PyTorch is ok.

![image](https://user-images.githubusercontent.com/18211333/80951535-ae2a4d80-8e2a-11ea-8d73-31a24430784c.png)

**Comment by limberc** [comment]
It seems that there is some conflict in Caffe2 and PyTorch Lightning in Azure DLVM setup.

When I delete the Caffe2, it works fine now.
