### ISSUE TITLE
Uncenssary information of apex always pop up

### ISSUE THREAD

**Issue by NickYi1990** [PyTorchLightning/pytorch-lightning#1730]
### To Reproduce
```
import pytorch_lightning as pl
trainer = pl.Trainer(
    gpus=2,
    progress_bar_refresh_rate=0,
    precision=16,
    num_sanity_val_steps=0,
    profiler=True,
    gradient_clip_val=hparams.gradient_clip_val,
)

output:
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
```

Try manually set _amp_state=0 the to disable this print and did not work
```
import apex
apex.amp._amp_state = 0
```

### Expected behavior

Give a parameter the set control this print behavior in apex

### Environment
CUDA:
- GPU:
- GeForce RTX 2080 Ti
- GeForce RTX 2080 Ti
- GeForce RTX 2080 Ti
- GeForce RTX 2080 Ti
- available: True
- version: 10.1
Packages:
- numpy: 1.18.1
- pyTorch_debug: False
- pyTorch_version: 1.4.0
- pytorch-lightning: 0.7.5
- tensorboard: 2.2.1
- tqdm: 4.42.1
System:
- OS: Linux
- architecture:
- 64bit
-
- processor: x86_64
- python: 3.7.6
- version: #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020

**Comment by williamFalcon** [comment]
@NickYi1990 fixed on master
