### ISSUE TITLE
IterableDataset does not work in validation

### ISSUE THREAD

**Issue by cmpatino** [PyTorchLightning/pytorch-lightning#1731]
## 🐛 Bug

**Colab to Reproduce**: https://colab.research.google.com/drive/1YEdFCv0_VkdOG9FVibPzGAOv3tH-vpki

Validation datasets cannot use IterableDatsets because Lightning still needs the `__len__` method of the validation dataset. I tracked the `__len__` call to the line I reference below.

https://github.com/PyTorchLightning/pytorch-lightning/blob/48e808c20e55fae47fc58b3e2c4e2056883b88b4/pytorch_lightning/trainer/data_loading.py#L222

Particularly, the `if dl` statement implicitly calls the `__len__` function of the dataset.

**Comment by awaelchli** [comment]
A fix is in the works in PR #1560
