### ISSUE TITLE
loading hparams as tags_csv results in Dict not Namepsace being passed to __init__

### ISSUE THREAD

**Issue by jfelectron** [PyTorchLightning/pytorch-lightning#1737]
## 🐛 Bug

Doctrstring indicates: 

"""                However, if your checkpoint weights don't have the hyperparameters saved,
                use this method to pass in a .csv file with the hparams you'd like to use.
                These will be converted into a :class:`~argparse.Namespace` and passed into your
                :class:`LightningModule` for use.
"""

This does not appear to be true. 

""" class PurchaseEventsClassifier(pl.LightningModule):
    def __init__(self, hparams: Namespace):
        import pdb; pdb.set_trace()
        embed_params = json.loads(hparams.embed_params) """

hparams is a a dict here not a Namespace as expected. 

### To Reproduce

2. Run '....'

### Expected behavior

hparams loaded from tags_csv should be a Namespace 

### Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by awaelchli** [comment]
I will put a note here to see if we need to address it after #1271 . 
csv file for hparams will be deprecated in the future.
