### ISSUE TITLE
How to persist a pytorch lightning module that depends on external data?

### ISSUE THREAD

**Issue by Apsod** [PyTorchLightning/pytorch-lightning#1755]
#### What is your question?

Hi! We're using pytorch lightning to train language models and transformers from scratch. This includes training tokenizers and applying them text data, resulting in binarized data. 
The way we've structured the process is to train a tokenizer, apply it to text data (coupling the binarized data and the tokenizer), and apply a language model on the binarized data. 

Since the language model depends on the tokenizer (number of tokens, special tokens, et.c.) the pytorch lightning model needs a tokenizer/vocabulary as part of its hparams. This does not play very nicely with the way hparams and loading works: If we transfer the model from one computer to another, we would need to move a tokenizer to the exact same path on the other computer. 

Generally i guess the problem boils down to this: If the inner pytorch modules of the pytorch lightning module depends on some kind of external data (e.g. a vocabulary, or a random sparsity graph), and you then wish to share the pytorch lightning module, we can't find an easy way of doing this.

on_load/save_checkpoint does not work, since they take effect **after** the model has been initialized, whereas we would like to persist data to the initialization logic in itself. 

Is there an elegant way to do this in pytorch lightning?

**Comment by williamFalcon** [comment]
good points. been thinking about this as well. 

can you share pseudocode so we can come up with the changes to the API?

**Comment by Apsod** [comment]
FWIW, we did find a workaround that makes the module self-contained, but it's not very pretty. It is built on the kwarg workaround, adding a separate hparams only classmethod `make` responsible for tokenizer initialization and a separate classmethod `load` responsible for loading from checkpoint.

```python
class Transformer(LightningModule):
  def __init__(self, hparams, tokenizer=None):
    ...
    # set the tokenizer (tokenizer loading logic outside of Transformer)
    self.tokenizer = tokenizer

    # Initialize the pytorch model (dependent on tokenizer)
    self.transformer = torch.nn.Transformer(
      dimension = hparams.dimension,
      num_embeddings = self.tokenizer.vocab_size,
      padding_index = self.tokenizer.padding_index,
      ...)
    def on_save_checkpoint(self, checkpoint):
        checkpoint['tokenizer'] = self.tokenizer

    @classmethod
    def make(cls, hparams):
        # Essentially a wrapper around init responsible for tokenizer loading
        tokenizer = get_tokenizer(hparams)
        return cls(hparams, tokenizer=tokenizer)

    @classmethod
    def load(
            cls,
            checkpoint_path,
            map_location = None
            ):
        # Copied from load_from_checkpoint, but we extract tokenizer (saved during on_save) and make it a kwarg.

        if map_location is not None:
            checkpoint = torch.load(checkpoint_path, map_location=map_location)
        else:
            checkpoint = torch.load(checkpoint_path, map_location=lambda storage, loc: storage)
        
        args = []
        tokenizer = checkpoint['tokenizer']   # extract the tokenizer
        kwargs = {'tokenizer': tokenizer}      # Make it a kwarg to _load_model_state

        model = cls._load_model_state(checkpoint, *args, **kwargs)
        return model
```

This is obviously particular to our use case, but I think it is possible to polish it a bit by, for example, making it possible use a saved kwargs-dictionary in load_from_checkpoint.

**Comment by mateuszpieniak** [comment]
> If we transfer the model from one computer to another, we would need to move a tokenizer to the exact same path on the other computer.

It's a completely valid requirement. That's why people wrap up their training experiments into Dockerfiles. A different example is that Polyaxon supports this with [YAML scripts](https://docs.polyaxon.com/references/polyaxonfile-yaml-specification/environment/) that help you define running environment.
