### ISSUE TITLE
Add the following example to Community Examples

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#1762]
### Motivation

Dear people of Pytorch-Lightning,

Would it be possible for you to add this example on how to integrate torch-points3d with pytorch-lightning under Community Examples ?

Here is framework
https://github.com/nicolas-chaulet/torch-points3d

Best regards,
Thomas Chaton

Here is the example integrating torch-points3d with pytorch-lightning
https://github.com/tchaton/torch-points3d-templates/blob/master/examples/pytorch-lightning/main.py

### Pitch

It shows how to train a point cloud classifier with several backbones PointNet2, KPConv, RSConv on ModelNet dataset under 100 lines of code. The integration was really smooth compared to fastAI, I think it is worth noting :)

**Comment by edenlightning** [comment]
Hey! This looks great! Want to pend us a PR adding your example?
