### ISSUE TITLE
csvlogger: version number doen't increase in the save directory

### ISSUE THREAD

**Issue by zhong-yy** [PyTorchLightning/pytorch-lightning#17656]
### Bug description

In pytorch-lightning 2.0.2 No matter how many times I run training, the results are always saved in `save_dir/name/version0`. However, in previous pytorch-lightning versions, the version number should increase by 1 automatically.

When I run the training again, I get the following warning:
```
lightning_fabric/loggers/csv_logs.py:188: UserWarning: Experiment logs directory weights/xx/version_0 exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!

```
and
```
pytorch_lightning/callbacks/model_checkpoint.py:612: UserWarning: Checkpoint directory weights/alaskalp_lpclass/version_0/checkpoints exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
```

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

```python
csv_logger = CSVLogger("weights", "xx")
trainer.fit(model, train_loader, dev_loader)
```

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
Thanks for reporting @zhong-yy 

This was recently fixed in https://github.com/Lightning-AI/lightning/commit/a36af3f9f855a4735fdc97c5e08bebb8a7467bf3. The fix is not yet released in a bugfix release, but will be soon.
If you want to confirm this, you could install the development version via

```
pip install -U https://github.com/Lightning-AI/lightning.git
```
