### ISSUE TITLE
How can I retrieve metrics from training and testing

### ISSUE THREAD

**Issue by Uroc327** [PyTorchLightning/pytorch-lightning#1768]
## ❓ Questions and Help
How can I extract the metrics returned from `training_step`, `training_epoch_end`, `validation_step`, `validation_epoch_end`, `test_step`, `test_epoch_end` after a `train()` or a `test()` run?

I'd like to return some dictionary (e.g. `{'loss': ..., 'log': ..., 'param a: 'a', 'param b': 'b', 'param c': {...}}`) from e.g. `test_epoch_end` and retrieve this after calling `trainer.test(net)`. It seems like the data is available some where, as the Weights and Biases logger prints at least the training metrics before uploading. Where can I find those metrics from training and testing?

**Comment by appleparan** [comment]
It seems it's a duplicate. See #1694 .
BTW, If you need just postprocessing, I hacked this problem by putting everything (including plotting, I/O, etc.) in `test_epoch_end` . I think it's not best practice but I also couldn't find any method to get the test result. 

I just write the file that records what I need. After then, I write another script to process the file. I wish this helps you.
