### ISSUE TITLE
Checkpoint: OverflowError: cannot serialize a string larger than 4GiB

### ISSUE THREAD

**Issue by chnsh** [PyTorchLightning/pytorch-lightning#1769]
## 🐛 Bug

Model checkpointing fails with the error: OverflowError: cannot serialize a string larger than 4GiB and halts training

 - PyTorch Version (e.g., 1.0): 1.5
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: GTX 2080Ti
 - Any other relevant information:

### Additional context

This is a known Python issue https://github.com/pytorch/pytorch/issues/12085

Possible fix, set the protocol correctly

**Comment by Borda** [comment]
I guess there is some pickle limitation or the file system you are using...
can you specify your devel environment?
