### ISSUE TITLE
Allow not to freeze other optimizers' parameters

### ISSUE THREAD

**Issue by carefree0910** [PyTorchLightning/pytorch-lightning#1770]
## 🚀 Feature

When using multiple optimizers, provide a flag which can control whether we should freeze other parameters or not (which is a 'FIX' in [here](https://github.com/PyTorchLightning/pytorch-lightning/pull/603))

### Motivation

When implementing BicycleGAN with lightning, I'm having great trouble because it requires something like this:

```python
opt_e.zero_grad()
opt_g.zero_grad()
loss_eg.backward(retain_graph=True)
opt_e.step()
opt_g.step()

opt_g.zero_grad()
loss_g.backward()
opt_g.step()
```

which means optimize two optimizers in one `optimizer_step` in lightning. However currently it is not possible because only one optimizer's parameters are not frozen

### Pitch

Let's say we have a flag called `freeze_other_parameters`, then:

```python
for opt_idx, optimizer in enumerate(self.optimizers):
    if freeze_other_parameters:
        # make sure only the gradients of the current optimizer's paramaters are calculated 
        # in the training step to prevent dangling gradients in multiple-optimizer setup.
        for param in self.get_model().parameters():
            param.requires_grad = False
        for group in optimizer.param_groups:
            for param in group['params']:
                param.requires_grad = True
```

### Alternatives

A more elegant way might be supporting multiple optimizers optimize at one same `optimizer_step`, but that would break backward compatibility

### Additional context

[This](https://github.com/junyanz/BicycleGAN/blob/master/models/bicycle_gan_model.py#L191) is the original repo where I port from.

**Comment by carefree0910** [comment]
Hi, would you please give me a response so I can make sure this is the design of pytorch-lightning, and how could I resolve the pitch?

**Comment by carefree0910** [comment]
So maybe pytorch-lightning now wants us to handle this specific condition by ourselves? Because it seems that the latest release supports us to re-design the training step completely 😕

**Comment by 0560405608** [comment]
****

**Comment by awaelchli** [comment]
I think for this GAN example it would be best to use the manual optimization mode. 
https://pytorch-lightning.readthedocs.io/en/stable/optimizers.html#manual-optimization
Then you have the most control over the optimizers.

**Comment by tchaton** [comment]
Any update on this issue ?

**Comment by carefree0910** [comment]
I think it will be fine to close this issue now 😆
