### ISSUE TITLE
Backward on tensors inside training_step

### ISSUE THREAD

**Issue by agadetsky** [PyTorchLightning/pytorch-lightning#1771]
#### What is your question?

Is it safe to call .backward() on tensors inside .training_step? It is the case for example if loss depends on the gradients.

**Comment by williamFalcon** [comment]
Might need to use retain_graph if you do. But otherwise no problem. 
If you don't need lightning's .backward, override the method.

**Comment by agadetsky** [comment]
@williamFalcon thank you for your answer. I wanted to override .backward, I think it is more proper way to do what I want, but I need to access some tensors from the training_step, but .backward accepts only loss from training_step. Is there a proper way to get access? To save somehow what I need and then pass it to lightning's .backward?
