### ISSUE TITLE
it would be better to introduce the update for each release

### ISSUE THREAD

**Issue by marsggbo** [PyTorchLightning/pytorch-lightning#1775]
The newest version is 0.7.5, but it is not clear for us what's the update for this version. Hence, I think it would be better to introduce the updated details for each new release.

**Comment by yukw777** [comment]
PL keeps a very detailed changelog: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md

**Comment by marsggbo** [comment]
thanks a lot!

**Comment by Borda** [comment]
you can also check release notes - https://github.com/PyTorchLightning/pytorch-lightning/releases
