### ISSUE TITLE
Need a grammar check in README.md file. 

### ISSUE THREAD

**Issue by Deeksha2501** [PyTorchLightning/pytorch-lightning#1796]
There are some grammar issues in README.md file. Can I work on this issue?

**Comment by williamFalcon** [comment]
yes! please submit a PR :)

**Comment by Deeksha2501** [comment]
Thank you, I will make PR today

**Comment by Deeksha2501** [comment]
I have submitted PR, please review

**Comment by Borda** [comment]
finished with #1798, Thank you :]
