### ISSUE TITLE
Use .comet.config file for CometLogger

### ISSUE THREAD

**Issue by neighthan** [PyTorchLightning/pytorch-lightning#1810]
## 🚀 Feature

When creating a CometML experiment normally, the API key will be read from the file `~/.comet.config` or from an environment variable if it isn't passed in directly. It would be nice if the `CometLogger` supported these uses as well.

### Motivation

Putting the API key in code is certainly a bad practice, and it's a pain to have to export it as an environment variable and then get its value in Python or else read it from the file manually. Adding this feature makes things more seamless compared to how people use CometML when not using PyTorch Lightning.

### Additional context

I have a [patch] written for this already; it only changes a few lines of code. From the template message when I went to create a PR, though, it seemed I should create an issue first. Let me know if you have thoughts about this.

(somewhat related - the REST API key is also [deprecated]; the normal API key should be used instead now. I didn't change that code, though, because I'm not sure if older versions of Comet would have any issues with that change.)

[patch]: https://github.com/PyTorchLightning/pytorch-lightning/compare/master...neighthan:master
[deprecated]: https://www.comet.ml/docs/python-sdk/advanced/#python-configuration

**Comment by rohitgr7** [comment]
@Borda Can this be fixed?? This makes easy to work with CometLogger.

**Comment by Borda** [comment]
@neighthan cool mind send the PR?
