### ISSUE TITLE
How to add customized DistributedSampler?

### ISSUE THREAD

**Issue by jonbakerfish** [PyTorchLightning/pytorch-lightning#1816]
When training in [multi-gpu mode](https://pytorch-lightning.readthedocs.io/en/stable/multi_gpu.html#remove-samplers), we can disable the auto replacing of sampler with `Trainer(replace_sampler_ddp=False)`. However, how can we add our customized DistributedSampler for train/val dataloader and reset them after each epoch?

**Comment by jjkindergarten** [comment]
hey, did you successfully add  a customized distributed sampler? i try to, but come with error like this:
'''
AssertionError: Default process group is not initialized
'''
