### ISSUE TITLE
Automatic batch_size finder does not work with 16 bit and in ddp

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#1827]
The recursive .fit() call in this module means it can't be used with ddp interactive.

It also cannot be used with 16-bit since the scaler is not enabled and saving checkpoint fails.

**Comment by williamFalcon** [comment]
@SkafteNicki

**Comment by SkafteNicki** [comment]
I have trouble reproducing your error. If I run `pl_examples/basic_examples/gpu_template.py` with `--use_16bit --distributed_backend ddp` and have set `auto_scale_batch_size='power` in trainer construction I do not get an error.

**Comment by williamFalcon** [comment]
add —gpus 2

**Comment by edenlightning** [comment]
@williamFalcon is this still relevant?

**Comment by edenlightning** [comment]
@SkafteNicki could you reproduce the error?
