### ISSUE TITLE
Allow boolean flags to work without passing True

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#1829]
We tried to fix this but it's still broken

This fails when adding args to argparse automatically...
```
--auto_lr_find
```

Instead we have to do:
```
--auto_lr_find True
```

which is not great

**Comment by SkafteNicki** [comment]
This only seems to be a problem with the `auto_lr_find` flag, since it is the only argument that is a union between the 4 allowed types `(str, float, int, bool)` in the `add_argparse_args`. So either this needs to be handled as a special case in the argparser or remove one of its allowed value (`str` or `bool`).

**Comment by williamFalcon** [comment]
it's a problem for many flags haha. The pattern is bool or the callback or string.

So, early stopping, checkpoint, etc... all have this problem. 
And for the batch size and lr finder stuff we have a few options

```python
auto_lr_find=True
auto_lr_find='some.path'
```
But True is getting parsed as a string which breaks everything.

**Comment by williamFalcon** [comment]
I think we need to solve this before 0.7.6 release as this is causing a lot of unexpected behaviors @Borda.

Basically i think we need to:
1. allow the flag to be passed in with set_true ```--my_flag```.
2. but if there is something else, then treat that thing as a string ```--my_flag this_is_a_string```

**Comment by Borda** [comment]
I think that the complication comes with `auto_lr_find: Union[bool, str]`  so you cannot in argparse define to be `store_true`  and optional string at the same time

**Comment by Borda** [comment]
well this is the minimal solution
```python
import argparse
p = argparse.ArgumentParser()
p.add_argument("--a", type=str, default=False, nargs="?")
v = vars(p.parse_args())
v = {k: True if v is None else v for k, v in v.items()}
print(v)
```
gives:
- `python sample.py --a`  >> `{'a': True}`
- `python sample.py`  >> `{'a': False}`
- `python sample.py --a park`  >> `{'a': 'park'}`

**Comment by williamFalcon** [comment]
let's merge this asap for 0.7.6

**Comment by Borda** [comment]
> let's merge this asap for 0.7.6

ready to review... ^^ @williamFalcon
