### ISSUE TITLE
Better visualization of the model using torchsummaryX

### ISSUE THREAD

**Issue by IncubatorShokuhou** [PyTorchLightning/pytorch-lightning#1833]
## 🚀 Feature
Better visualization of params,size et.al. using torchsummaryX

### Motivation

Now in pytorch-lightning, visualization of the model is generated according to the layers listed in `__build_model` function. However, the layers in the function is not necessarily used, and not necessarily used for only one time, which may make the visualization of the model incorrcet.

### Pitch

In my point of view, [torchsummaryX](https://github.com/nmhkahn/torchsummaryX) could be intergrated into pytorch-lightning. 
Torchsummary X is an improved visualization tool of [torchsummary](https://github.com/sksq96/pytorch-summary). It visualizes kernel size, output shape, params, and Mult-Adds. It genreates information of the model by actually runnning the `forward` function, which make the information of the model more accurent. Also, it has a little bit more information than the `ModelSummary` function now using in pytorch-lightning.

**Comment by Borda** [comment]
cc: @PyTorchLightning/core-contributors

**Comment by awaelchli** [comment]
I have a PR in the works #1773 that does input/output shapes properly (probably very similar to torchsummary) . With the layer summary class I added, it should be easy to extend it further to display weight shapes etc. without us needing to add a dependency on a library torchsummaryX. I suggest to go this path. 
See also #1556

**Comment by Borda** [comment]
@awaelchli so is this done? :]

**Comment by awaelchli** [comment]
Depends how far we want to go. Currently our model summary shows num params, layer type, input- and output shapes. 
@IncubatorShokuhou mentions that torchsummaryX also shows 
- parameter tensor shapes
- mult-adds
If we don't want these, we can close the issue.

**Comment by dav-ell** [comment]
Was there not enough interest in this to continue? I'm interested in this being implemented.

**Comment by Borda** [comment]
@dav-ell sure, do you want to take it over?

**Comment by awaelchli** [comment]
@dav-ell sure go ahead. Please add me as reviewer when you send the PR. cheers!

**Comment by george-gca** [comment]
Adding as a reminder for myself (or anyone who tackles this issue first): this should be made [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/72f19768c828b734d8565ffef7b78fb9a57ba847/pytorch_lightning/core/memory.py#L272). Probably doing the total values calculation before calling the function [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/72f19768c828b734d8565ffef7b78fb9a57ba847/pytorch_lightning/core/memory.py#L255), adding a new parameter to the function. The num of parameters for each layer is already stored in `self.param_nums`, but a `num_trainable_parameters` property would be useful in [LayerSummary](https://github.com/PyTorchLightning/pytorch-lightning/blob/72f19768c828b734d8565ffef7b78fb9a57ba847/pytorch_lightning/core/memory.py#L32) class. This could be achieved doing the same as `num_parameters`, but also checking if `p.requires_grad` is `True`. I couldn't find a test for this feature though. Maybe I missed something?
