### ISSUE TITLE
Enable pytorch lightning with non-trainable models?

### ISSUE THREAD

**Issue by tdvginz** [PyTorchLightning/pytorch-lightning#1840]
I'm trying to use pl infrastructure with a non-deep learning model.
As I'm validating multiple models, and some are "classic" but all use the same trainers, preprocessing, GPUs, etc, it would really benefit me to use the same code for all models:)

If I simply run a model with no weights I get the following error:
`RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn`

As `pl` doesn't allow to not pass the `configure_optimizers` function,
I tried overriding `optimizer_step` as well
```
def optimizer_step(self, current_epoch, batch_nb, optimizer, optimizer_i, second_order_closure=None):
        pass
```

But got the same error.
Overriding `backward` did not help either.

If someone has a solution, even a hacky one, I'll be happy to hear.

**Comment by williamFalcon** [comment]
how would you expect this to work?

can you give me pseudocode of what you want to do? is this for something like an svm?

**Comment by ethanwharris** [comment]
It should be possible to just return `None` from `configure_optimizers` (https://pytorch-lightning.readthedocs.io/en/stable/lightning-module.html#lightningmodule-class). Does that solve the grad error?

**Comment by festeh** [comment]
Another hacky solution: add dummy `Linear` layer to your module (so `model.parameters()` won't be empty) and in the `forward()` just return `torch.tensor(0.0, requires_grad=True)`

**Comment by dvirginz** [comment]
@ethanwharris  - returning `None` from `configure_optimizers ` does not help as `loss.backward` is still called

@williamFalcon - svm but not just, for example fitting a gmm after using a pretrained pipeline with fixed weights from earlier training, 
In this scenario, for example, I would set the max_epochs to be 1, fit on the training data, and test of the validation.
As 99% of the infra stays the same, including the loaders, etc. using the same code for that would be preferable for me, even if pl is not natively for that purpose:)

@festeh Liked the idea, currently getting 
`assert all(map(lambda i: i.is_cuda, inputs))` when doing so, I'll continue to investigate why. Probably a shape thing..

**Comment by dvirginz** [comment]
Probably the award-winning hack of the year:
I'm setting 
`accumulate_grad_batches=~Any number bigger than the true size of the batch-size`
and inside the model
```
    def optimizer_step(self, current_epoch, batch_nb, optimizer, optimizer_i, second_order_closure=None):
        pass
    def backward(self, use_amp, loss, optimizer,another):
        pass
```

**Comment by ethanwharris** [comment]
@dvirginz love the hack haha. What would be a good way for lightning to support this by default? We could add support for losses to be None? Would be nice if this use case was better supported :)

**Comment by williamFalcon** [comment]
maybe add a flag 
differentiate = False?

**Comment by williamFalcon** [comment]
Ok, i think this is super interesting. My suggestion is to add a flag:
```
differentiable=False
```
which should be used for non differentiable models.
Then we turn off all the gradient stuff

**Comment by kpoeppel** [comment]
I would still be interested in this feature. Any suggestions on where to start for a PR?
This issue is also related to #2208
