### ISSUE TITLE
Named constructor parameters?

### ISSUE THREAD

**Issue by drozzy** [PyTorchLightning/pytorch-lightning#1852]
Is it possible to define a Lightning Module to take named parameters instead of argparse "hparam"?

I don't user argparse and when I am running a hyperparam search I want to supply my own arguments.

Any tips? Thanks.

**Comment by williamFalcon** [comment]
could you put a simple script of how you run a training without argparse?
or a simple GH repo you can share?

**Comment by drozzy** [comment]
Currently I use pydantic and wandb.

Here is some pseudocode.
Basically I want wandb to overwrite the params in the dictionary:

```
from pydantic import BaseModel as Config


class Params(Config):
  NUM_LAYERS = 4 


class Model(nn.Module):
    def __init__(self, num_layers):
      super().__init__()
      self.num_layers = num_layers

# This allows wandb to inject hyperparams:
params = Params()
wandb.init(project='my_project', config=params.dict())

train(epochs=params.NUM_LAYERS)
```

**Comment by williamFalcon** [comment]
where is train defined? how do num_layers get passed in? maybe put together a colab or a simple repo. Easier to make a decision and change based on a more holistic evaluation

**Comment by drozzy** [comment]
Ok, I'll work on a simple example.

But to answer one of your questions, the arguments get passed in via wandb agent:
https://docs.wandb.com/sweeps/quickstart#4-launch-agent-s

`train` is just my function that does the main training loop.

**Comment by borisdayma** [comment]
@drozzy it seems like you're trying to do a hyperparameter search using wandb sweeps.
It should already be supported with no issue.

You can see an example here: https://github.com/borisdayma/lightning-kitti

**Comment by drozzy** [comment]
Thanks, I'll give it a go!

**Comment by drozzy** [comment]
@borisdayma It seems like doing `wandb.init` creates one run, and then `wandb_logger = WandbLogger()` creates another run.
Did you encouter that issue?

**Comment by borisdayma** [comment]
Are you in a jupyter environment or is it a script?

**Comment by drozzy** [comment]
Jupyter.

**Comment by borisdayma** [comment]
There's a current issue for this case in jupyter notebooks, though it works in scripts.
There is an issue filed in wandb: https://github.com/wandb/client/issues/1059
