### ISSUE TITLE
Implicitly setting a random seed?

### ISSUE THREAD

**Issue by miriaford** [PyTorchLightning/pytorch-lightning#1868]
### To Reproduce

```
import pytorch_lightning
import random
print(random.randint(0, 100000))
```

If you run this script repeatedly, you will get the same 'random' integer. PyTorch-lightning seems to be setting a random seed behind the hood. This is very dangerous because I want to show the variance of my algorithm, and PTL actually makes (part of) it deterministic. 

### Expected behavior

PTL shouldn't set the seed without the user's permission.

**Comment by williamFalcon** [comment]
pl doesn’t set the seed anywhere. we have a function you can use to do it. search the codebase for the word seed

**Comment by williamFalcon** [comment]
https://github.com/PyTorchLightning/pytorch-lightning/search?q=seed&type=

**Comment by miriaford** [comment]
Yes, but why do I get deterministic random int every time I run the script? I didn't set any seed explicitly. It's only 3 lines, you can try it yourself.

**Comment by miriaford** [comment]
Also if I simply remove the first line `import pytorch_lightning`, the script prints a different int every time (which is the expected behavior)

**Comment by williamFalcon** [comment]
```
(env) ➜  Desktop python a.py
319
(env) ➜  Desktop python a.py
350
(env) ➜  Desktop python a.py
548
(env) ➜  Desktop cat a.py
import pytorch_lightning
import random
print(random.randint(0, 1000))
```

**Comment by miriaford** [comment]
I don't know why I'm getting the deterministic behavior - I'm on PL 0.7.5, both OS X and Ubuntu 16.04 give me the same issue

**Comment by williamFalcon** [comment]
Not sure... we're very aware of correct research practices. Double check your environment or how you're running this...

Here's a discussion showing how hard we thought about adding the seed_everything function... we don't new feature decisions lightly.

https://github.com/PyTorchLightning/pytorch-lightning/pull/1572

**Comment by miriaford** [comment]
thanks!
