### ISSUE TITLE
load_from_checkpoint(): hparam_overrides only works with hparams_file

### ISSUE THREAD

**Issue by rightaditya** [PyTorchLightning/pytorch-lightning#1870]
## 🐛 Bug

Using the `hparam_overrides` argument for `load_from_checkpoint()` without the `hparams_file` argument gives an `UnboundLocalError`.

#### Code sample
Do:
```python3
MyLightningModule.load_from_checkpoint(ckpt_path, hparam_overrides={'param': 0})
```
and the result will be `UnboundLocalError: local variable 'hparams' referenced before assignment`, but the following works:
```python3
MyLightningModule.load_from_checkpoint(ckpt_path, hparams_file=hp_path, hparam_overrides={'param': 0})
```

### Expected behavior

Overriding should be possible even if the hparams are loaded from the checkpoint file rather than the separate hparams file.

### Environment

 - PyTorch Version (e.g., 1.0): 1.5.0
 - OS (e.g., Linux): Ubuntu 16.04 and 18.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.8.2
 - CUDA/cuDNN version: 10.1.243/7.6.5.32
 - GPU models and configuration: GTX1070

### Additional context

This is a super simple fix---I thought about just submitting a PR directly but figured I should check that this behaviour is indeed erroneous first.

**Comment by rightaditya** [comment]
Shall I just submit a PR for this?

**Comment by williamFalcon** [comment]
@rightaditya try from master?

**Comment by williamFalcon** [comment]
```
MyLightningModule.load_from_checkpoint(ckpt_path, arg_to_override=x)
```
