### ISSUE TITLE
Lightning cant find visible gpu when using pytorch 1.5.0

### ISSUE THREAD

**Issue by leslyarun** [PyTorchLightning/pytorch-lightning#1872]
## 🐛 Bug

When using the latest pytorch version 1.5.0 with multi-gpu's (backend ddp), lightning says there are no visible gpu's.

The same code runs without issues when using pytorch 1.4.0

```
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 464, in __init__
    self.data_parallel_device_ids = parse_gpu_ids(self.gpus)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 730, in parse_gpu_ids
    gpus = sanitize_gpu_ids(gpus)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 696, in sanitize_gpu_ids
    """)
pytorch_lightning.utilities.exceptions.MisconfigurationException: 
                You requested GPUs: [0, 1, 2, 3, 4, 5, 6, 7]
                But your machine only has: []
```

 - PyTorch Version (e.g., 1.0): 1.5.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: Nvidia - V100 - 8 gpu's
 - Lightning - 0.7.6

**Comment by williamFalcon** [comment]
mind posting a script to recreate?

**Comment by williamFalcon** [comment]
also make sure you have the gpu version of pytorch

**Comment by yukw777** [comment]
i'm kind of sensing that you stopped your aws instance and resumed it. I encountered this exact same "bug" when I did that. For some unknown reasons, when you stop a gpu instance on aws and resume it, the nvidia driver goes away.. Try `nvidia-smi` to see if you still see your GPUs.

**Comment by leslyarun** [comment]
I was using cuda 10.1 and upgraded pytorch (which by default expects cuda 10.2). Installed pytorch 1.5.0 in the right way and it fixed the issue

**Comment by SaoYear** [comment]
torch==1.8.0 solved my same problem.

**Comment by SaoYear** [comment]
This code saved my life.
```
conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=10.2 -c pytorch
```
