### ISSUE TITLE
Training time estimation when max_epochs is given

### ISSUE THREAD

**Issue by HansBambel** [PyTorchLightning/pytorch-lightning#1875]
## 🚀 Feature
Time estimation of training until `max_epochs` are reached.

### Motivation

Right now I don't see how long I am training for already and how long it is going to take to train e.g. 500 epochs.
I usually have a tqdm progress bar for number of epochs to get an estimate how long my training will run maximally.

### Pitch

If `max_epochs` is given, create a tqdm progress bar (probably with `leave=True`).

### Alternatives

Keep it like it is and make rough estimations per hand.

**Comment by williamFalcon** [comment]
? we already have a tqdm bar. in case you need a custom one you can also implement one using a callback @awaelchli

**Comment by HansBambel** [comment]
I know, but it only shows the time for the current epoch, but not how long the overall training will take.

**Comment by williamFalcon** [comment]
don't you just multiply times the num of epochs?

**Comment by HansBambel** [comment]
Then I would not have a time for how long I am training already and I would need to manually check how long one epoch takes and do the calculation manually.

Such a feature was mentioned in #765 as well.

**Comment by awaelchli** [comment]
Maybe we could provide such a global progress bar as part of bolts.
