### ISSUE TITLE
Load batches as float16?

### ISSUE THREAD

**Issue by tbachlechner** [PyTorchLightning/pytorch-lightning#1876]
#### Can I use lightning to load training examples as `dtype = float16` to the GPU?

In order to train imagenet with larger batches I'd like to store the batches with fp16 on the GPU memory, rather than fp32. In basic examples I've tried this does not happen, and using `precision = 16` barely uses less GPU memory than `precision = 32`. Is it possible to convince lightning to load the batches as  `dtype = float16` and thus to increase the batch size?

#### Code

Here is a simple example that reveals the `dtype` of the batches and the output within the `forward()` loop.

```
import torch
from torch import nn
import pytorch_lightning as pl
from torch.nn import functional as F
from torch.utils.data import DataLoader
from torchvision.datasets import MNIST
from torchvision import datasets, transforms
import os 
import pytorch_lightning as pl

class LitModel(pl.LightningModule):

    def __init__(self):
        super().__init__()
        self.l1 = torch.nn.Linear(28 * 28, 10)

    def forward(self, x):
        print('forward() input dtype: ', x.dtype)
        out = torch.relu(self.l1(x.view(x.size(0), -1)))
        print('forward() output dtype: ', out.dtype)
        return out

    def training_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self(x)
        return {'loss': F.cross_entropy(y_hat, y)}

    def train_dataloader(self):
        return DataLoader(MNIST(os.getcwd(), train=True, download=True,
                                 transform=transforms.ToTensor()), batch_size=32,num_workers = 8)
    def configure_optimizers(self):
         return torch.optim.Adam(self.parameters(), lr=0.02)

trainer = pl.Trainer(gpus = 1,amp_level='O1', precision=16,max_steps=10)
model = LitModel()

trainer.fit(model)
```

The output I get seems to indicate that the batches are stored as fp32 on the GPU, consistent with high memory usage:
```
forward() input dtype:  torch.float32
forward() output dtype:  torch.float16
```

#### What have you tried?

I'm wondering if the behavior I observe is a bug or a feature.

#### What's your environment?

 - OS: Linux
 - CUDA 10.1, torch 1.4, lightning 0.7.5

**Comment by williamFalcon** [comment]
try torch 1.6? much more stable for fp16.
then we can look into loading fp16 directly.

**Comment by tbachlechner** [comment]
> try torch 1.6? much more stable for fp16.
> then we can look into loading fp16 directly.

Thanks for your quick response!

Done, my code produces the same output with torch 1.6, the batches are still float32 on the GPU.
