### ISSUE TITLE
Support OmegaConf dicts in hparams

### ISSUE THREAD

**Issue by Darktex** [PyTorchLightning/pytorch-lightning#1880]
## 🚀 Feature
Lightning hparams were recently changed to support only dicts and ArgParse namespaces. This diff (re)introduces compatibility with OmegaConf DictConfig, which is the type of config that Hydra uses.

### Motivation

Using Hydra + Lightning

**Comment by calclavia** [comment]
Running into the same issue when trying to use things like auto_lr_find 
`pytorch_lightning.utilities.exceptions.MisconfigurationException: When auto_lr_find is set to True, expects that hparams either has field `lr` or `learning_rate` that can overridden`
