### ISSUE TITLE
Accumulate Metrics for K Batches

### ISSUE THREAD

**Issue by n2cholas** [PyTorchLightning/pytorch-lightning#1881]
#### What is your question?

I would like to aggregate metrics for k minibatches before logging to Tensorboard. How can I accomplish this? 

For example, I would like to average my loss and accuracy for 10 minibatches and report that value to TensorBoard, not just report the statistics on the 10th minibatch.

#### What have you tried?

I noticed there's a `log_save_interval` argument for the trainer, but, this only logs the metrics computed per one batch. This is not that useful for me because my batch size is very small, so I need to average my statistics across multiple minibatches. 

There is a `train_epoch_end` method I can override, but only gives me my outputs at the end of an epoch. I am looking for something like this where I have access to all my outputs from the previous k minibatches so I can aggregate them.

**Comment by williamFalcon** [comment]
in validation_step log directly:

self.logger.experiment is a summarywriter

**Comment by n2cholas** [comment]
Thanks for the quick reply @williamFalcon! I wanted to do this without running my validation every k steps, so instead, I created a callback that does this reporting every k iterations using the `self.logger.experiment` SummaryWriter.

**Comment by hughperkins** [comment]
Hi @n2cholas , dont suppose... could you provide more details on how you did this please?

**Comment by tchaton** [comment]
Hey @hughperkins,

You do something like this:

```py
class Model(LightningModule):

    ...

    def training_step(..., batch_idx):

        self.metric(...) # accumulate state
        if batch_idx % 10 == 0:
            self.log("my_metric", self.metric.compute()) # perform a compute every 10 batches
            self.metric.reset() # reset the metric to restart accumulating
```
