### ISSUE TITLE
Custom Text Logger example

### ISSUE THREAD

**Issue by ternaus** [PyTorchLightning/pytorch-lightning#1882]
I am using Neptune.ML for logging, but I would like to keep the data for analysis locally.

Trying to write a simple logger that dumps info to the CSV files.

`train.csv` like:

```
step, loss1, loss2
1, 0.5, 0.4
2, 0.4, 0.12
....
```

`val.csv` should look like:

```
epoch, loss1, loss2
1, 0.6, 0.23
2, 0.13245, 0.2134
....
```

I am looking at the docs at https://pytorch-lightning.readthedocs.io/en/latest/loggers.html

and at the examples in https://github.com/PyTorchLightning/pytorch-lightning/tree/master/pytorch_lightning/loggers

and cannot figure out how to do this.

It would be nice if you extend the documentation with a more detailed example.

**Comment by festeh** [comment]
All you need to to is to implement `log_metrics` and provide some dummy defaults for other abstract methods. In  `log_metrics` you can inspect the input and write it to corresponding file. Check the [example](https://colab.research.google.com/drive/1_DyMnvvPOTIDSYHNoA7eacBuwGyk8qXy?usp=sharing)

**Comment by ternaus** [comment]
@festeh somehow the example works for me only if 

`checkpoint_callback=False`

When I try to use `checkpoint_callback=ModelCheckpoint(filepath="2020-05-19")`

I get an error:

```
~/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/callback_config.py in configure_checkpoint_callback(self)
     56                     self.logger.name,
     57                     version,
---> 58                     "checkpoints"
     59                 )
     60             else:

~/anaconda3/lib/python3.7/posixpath.py in join(a, *p)
     92                 path += sep + b
     93     except (TypeError, AttributeError, BytesWarning):
---> 94         genericpath._check_arg_types('join', a, *p)
     95         raise
     96     return path

~/anaconda3/lib/python3.7/genericpath.py in _check_arg_types(funcname, *args)
    147         else:
    148             raise TypeError('%s() argument must be str or bytes, not %r' %
--> 149                             (funcname, s.__class__.__name__)) from None
    150     if hasstr and hasbytes:
    151         raise TypeError("Can't mix strings and bytes in path components") from None

TypeError: join() argument must be str or bytes, not 'NoneType'
```

**Comment by Erlemar** [comment]
To fix this error with checkpoint, you need to define `name` property in the logger. For example:

```python
    @property
    def name(self):
        return 'run_name'
```

**Comment by festeh** [comment]
@ternaus Updated the example with two options to solve it. It seems that you only need to return some name for the logger in the second one. Note that default checkpoint path in the first option may be a bit ugly so you may prefer to create `ModelCheckpoint` with a custom path.

**Comment by ternaus** [comment]
Thanks! Works!
