### ISSUE TITLE
lightning_mnist_tpu crashes

### ISSUE THREAD

**Issue by satyajitghana** [PyTorchLightning/pytorch-lightning#1885]
## 🐛 Bug

![image](https://user-images.githubusercontent.com/8092481/82298839-523af980-99d2-11ea-8e4c-ec0b7ddaeb2e.png)

### To Reproduce

Run https://colab.research.google.com/drive/1-_LKx4HwAxl5M6xPJmqAAu444LTDQoa3 with `VERSION = "1.5"`

There were other error when trying to run with other versions from `["1.5" , "20200325", "nightly"]` neither of them seem to work properly, there's always some sort of bug that pops up.
at this one moment when i had finally got it to run the model, the second time i ran the cell, it crashed, could be that i had to free up mem. but i dont see why it shouldn't have been done automatically.

**Comment by lezwon** [comment]
@satyajitghana It worked fine for me with nightly. Could you try it again with nightly? Do let me know if there's any bug that pops up with it.

**Comment by edenlightning** [comment]
@satyajitghana any update on this? Otherwise bug will be closed.

**Comment by satyajitghana** [comment]
it works on latest nightly !
close issue

**Comment by edenlightning** [comment]
Thanks!
