### ISSUE TITLE
hparam_overrides not working

### ISSUE THREAD

**Issue by artidoro** [PyTorchLightning/pytorch-lightning#1886]
## 🐛 Bug

Error when using `hparam_overrides` which was recently introduced by: #1797. This is the log:
```
Traceback (most recent call last):
  File "main.py", line 211, in <module>
    model = RelationEmbeddingModelLit.load_from_checkpoint(
  File "/home/ubuntu/anaconda3/envs/py38/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1601, in load_from_checkpoint
    update_hparams(hparams, hparam_overrides)
UnboundLocalError: local variable 'hparams' referenced before assignment
```

### To Reproduce

1. Load a checkpoint using the `hparam_overrides` argument:
```
MyPLModel.load_from_checkpoint(checkpoint_path, hparam_overrides={key: new_val})
```
### Expected behavior

No bug.

### Environment

* CUDA:
	- GPU:
		- Tesla V100-SXM2-16GB
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.1
	- pyTorch_debug:     False
	- pyTorch_version:   1.4.0
	- pytorch-lightning: 0.7.7-dev
	- tensorboard:       2.2.1
	- tqdm:              4.43.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.8.1
	- version:           #117-Ubuntu SMP Wed Apr 8 09:52:02 UTC 2020

**Comment by williamFalcon** [comment]
@artidoro try from master?

**Comment by artidoro** [comment]
Now it works! You might need to clean up the docs for `hparam_overrides` in the `load_from_checkpoint` method @williamFalcon.
