### ISSUE TITLE
`num_training_batches` can be 0 if `train_percent_check` is too small

### ISSUE THREAD

**Issue by annemariet** [PyTorchLightning/pytorch-lightning#1903]
## 🐛 Bug

if train_percent_check is set to a tiny value, then `num_training_batches` can be 0. Then no training happens, and no validation either, but no warning is raised and epochs are normally iterated over.

### To Reproduce

Train on any dataset using limit sufficiently small (eg 0.01).

#### Code sample
I think there is a simple fix, in `data_loading.py`, adding a line after l. 171

```
            (l.171) self.num_training_batches = int(self.num_training_batches * self.train_percent_check)
            self.num_training_batches = max(1, self.num_training_batches)
```

### Expected behavior

Training at least on 1 batch to have a quick check.

### Environment
* CUDA:
        - GPU:
        - available:         False
        - version:           None
* Packages:
        - numpy:             1.18.4
        - pyTorch_debug:     False
        - pyTorch_version:   1.5.0
        - pytorch-lightning: 0.7.6rc3
        - tensorboard:       2.2.1
        - tqdm:              4.46.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.2
        - version:           #864-Microsoft Thu Nov 07 15:22:00 PST 2019

**Comment by awaelchli** [comment]
sounds reasonable. 
btw there is also a Trainer arg "fast_dev_run" if you want to do a quick check with one batch per training/validation dataloader.

**Comment by annemariet** [comment]
Okay, thanks for the tip, indeed that would fit my needs here!
