### ISSUE TITLE
How to disable model summary?

### ISSUE THREAD

**Issue by sshleifer** [PyTorchLightning/pytorch-lightning#1909]
Mine is very long and makes it tough to see warnings/errors

For reference, I mean this thing:
![image](https://user-images.githubusercontent.com/6045025/82500732-f94a8e80-9ac1-11ea-8257-e5ff96b86cf6.png)

Thanks!

**Comment by rohitgr7** [comment]
In `Trainer` specify `weights_summary=None`.

**Comment by sshleifer** [comment]
Thx!
