### ISSUE TITLE
options for run only sanity check without training in 'run_pretrain_routine'

### ISSUE THREAD

**Issue by davinnovation** [PyTorchLightning/pytorch-lightning#1911]
### Motivation

for pytest pytorch-lightning based project, the training phase is not essential in some cases (like testing only inference). So adding an argument for running sanity-check without the training phase could be reasonable.

### Pitch

`run_pretrain_routine(self, model)` => `run_pretrain_routine(self, model, run_train=True)`

**Comment by awaelchli** [comment]
I don't understand this. Please elaborate more. 
In some tests training a couple of steps or even an epoch is needed to test certain calls or events.
