### ISSUE TITLE
Custom experiment name

### ISSUE THREAD

**Issue by ImMrMa** [PyTorchLightning/pytorch-lightning#1915]
## 🚀 Feature
now the experiment name is like:
./lightning_logs/version_0/**
Can I customize the name of my experiment？like:
./lightning_logs/object_detection_**/**
I think just add a default key like experiment_name=**.

### Motivation
So I can clearly know what each experiment has done

**Comment by rohitgr7** [comment]
It uses `TensorBoardLogger` [by default](https://github.com/PyTorchLightning/pytorch-lightning/blob/98f7842970fd593c21bebfdba5da8aa311d50730/pytorch_lightning/trainer/logging.py#L30-L35). So I think you can pass a `TensorBoardLogger` with `version` parameter as `"object_detection_"`.
