### ISSUE TITLE
Allow passing dict object as batch

### ISSUE THREAD

**Issue by GuillaumeRochette** [PyTorchLightning/pytorch-lightning#1918]
## 🚀 Feature
Allow the **batch** variable to be a (nested) _dict_ object (in _training_step()_, etc.)

### Motivation
I was porting my code from my own implementation of a Trainer to Pytorch Lightning, as I believe this is an asset for reproducibility and clarity.
However I stumbled across a problem, it is not possible for the variable **batch** to be a (nested) _dict_ object and it can only be a _Tensor_, _tuple_ or _list_.

### Pitch
The dataset structure that I am using is the following:
```py
import torch
from torch.utils.data import Dataset


class MyDataset(Dataset):
    def __init__(
        self, n: int
    ):
        self.n = n

    def __len__(self):
        return self.n

    def __getitem__(self, item):
        frame = {
            "index": item,
            "A": {
                "image": torch.randn(3, 128, 128),
                "R": torch.randn(3, 3),
                "t": torch.randn(3, 1),
                "K": torch.randn(3, 3),
            },
            "B": {
                "image": torch.randn(3, 128, 128),
                "R": torch.randn(3, 3),
                "t": torch.randn(3, 1),
                "K": torch.randn(3, 3),
            },
        }
        return frame

```
The PyTorch Dataloader is able to make a **batch** of frames with the default _collate_fn_.
To move things onto the GPU, I am currently doing:
```py
def move(self, d: dict, device) -> dict:
    for k in d:
        if isinstance(d[k], dict):
            d[k] = self.move(d[k])
        elif isinstance(d[k], (Tensor)):
            d[k] = d[k].to(device=device, non_blocking=True)
    return d
```
There is probably a nicer way to do it, but it does the job.

Could you please add this feature, as passing a _tuple_ is very impractical when the amount of variables is high?

Thanks in advance,

Guillaume

**Comment by awaelchli** [comment]
Hi 
this  is already possible. dicts, tuples, lists etc are moved automatically to the correct device, and nesting is also supported. just try it :)

We also have a PR #1756 that allows one to define the transfer of custom batches in a hook.

**Comment by awaelchli** [comment]
In Lightning you don't have to move any data yourself.

**Comment by cifkao** [comment]
@awaelchli The docs say that `batch` is "A tensor, tuple or list." I had to google this issue to make sure I can use a dict as well. So the docs should probably be updated (you write about "dicts, tuples, lists etc", so I'm wondering what else is included).
