### ISSUE TITLE
Images not being logged after using auto_lr_find

### ISSUE THREAD

**Issue by SubodhDahal** [PyTorchLightning/pytorch-lightning#1919]
## 🐛 Bug

When I use the auto LR finder, the images that I logged are no longer being displayed in Tensorboard. The logging works normally when setting it to `False` or when not specifying it.

### To Reproduce

1. Set  `auto_lr_find = True` for the trainer
2. Log image during test/validation step as `self.logger.experiment.add_image(title, image, step)`
3. Load the Tensorboard WebUI and see that the image is not being logged

### Expected behavior

The image that I logged should be visible in Tensorboard, even when using auto LR finder.

### Environment

```
* CUDA:
        - GPU:
                - GeForce GTX 1050 Ti with Max-Q Design
        - available:         True
        - version:           10.2
* Packages:
        - numpy:             1.18.3
        - pyTorch_debug:     False
        - pyTorch_version:   1.5.0
        - pytorch-lightning: 0.7.6
        - tensorboard:       2.2.1
        - tqdm:              4.46.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.2
        - version:           #41~1586790036~18.04~600aeb5-Ubuntu SMP Mon Apr 13 17:47:15 UTC
```
 - How you installed PyTorch (`conda`, `pip`, source): `pip`

### Additional context

Not sure if relevant, but I couldn't figure out how to pass the params to the `Trainer` as I'm using `from_argparse_args(hparams)`, where `hparams` contains the keys and values obtained from command-line `ArgumentParser`. So I set `hparams.auto_lr_finder = True` before instantiating the `Trainer`. The LR finder work's, so I assume there's no issue with that.

**Comment by danielhomola** [comment]
I can second this. Same goes for the graph of the net.. Spent almost a full day trying to figure out what am I doing wrong, but once auto_lr_find=False, everything works fine..

**Comment by SkafteNicki** [comment]
@SubodhDahal and @danielhomola could one of you try out the fix that is on master now, and report back if it worked. If so please close the issue :)
