### ISSUE TITLE
Trainer max_steps does not work when reloaded from checkpoint (if value is already exceeded)

### ISSUE THREAD

**Issue by jeremyjordan** [PyTorchLightning/pytorch-lightning#1922]
## 🐛 Bug 

The trainer flag for `max_steps` is not respected when you reload the Trainer from a checkpoint.

### To Reproduce

This works:
```
import tests.base.utils as tutils
from pytorch_lightning import Trainer, LightningModule
from pytorch_lightning.callbacks import EarlyStopping, LearningRateLogger, ModelCheckpoint
from tests.base import EvalModelTemplate

def test_trainer_max_steps():
    model = EvalModelTemplate()
    trainer = Trainer(max_steps=1)
    trainer.fit(model)
    assert trainer.global_step == 1
```

This breaks:
```
def test_trainer_exceed_max_steps_from_checkpoint():
    model = EvalModelTemplate()
    checkpoint_callback = ModelCheckpoint(save_top_k=1)
    trainer = Trainer(checkpoint_callback=checkpoint_callback, max_epochs=4)
    trainer.fit(model)
    step_count = trainer.global_step

    checkpoint_filepath = checkpoint_callback.kth_best_model
    trainer = Trainer(max_steps=1,
                    resume_from_checkpoint=checkpoint_filepath)
    trainer.fit(model)
    # current step exceeds max_steps, training should stop immediately
    assert trainer.global_step == step_count
```

### Expected behavior

Both of the above tests that I've written should pass.

We should also probably warn the user when they pass in a `max_steps` or `max_epochs` which exceeds the current state when reloading from a checkpoint.

### Environment

* CUDA:
        - GPU:
        - available:         False
        - version:           None
* Packages:
        - numpy:             1.18.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.4.0
        - pytorch-lightning: 0.7.7-dev
        - tensorboard:       2.1.0
        - tqdm:              4.42.0
* System:
        - OS:                Darwin
        - architecture:
                - 64bit
                - 
        - processor:         i386
        - python:            3.7.6
        - version:           Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64

**Comment by edenlightning** [comment]
Hey! Can you verify this is still the case?

**Comment by Borda** [comment]
yeah, just change this condition from `==` to `>=`
https://github.com/PyTorchLightning/pytorch-lightning/blob/3f28a8ef321774dffeba2f412cec7a1038b5c342/pytorch_lightning/trainer/training_loop.py#L498
@edenlightning mind send a PR?

**Comment by edenlightning** [comment]
fixed in force crash when max_epochs < epochs in a checkpoint #3580
