### ISSUE TITLE
More Details about Distributed Data Parallel Random Seed

### ISSUE THREAD

**Issue by woolpeeker** [PyTorchLightning/pytorch-lightning#1924]
## ❓ Questions and Help

https://pytorch-lightning.readthedocs.io/en/stable/multi_gpu.html#distributed-data-parallel

The document says: during Distributed-Data-Parallel
"Make sure to set the random seed so that each model inits with the same weights"
Is there any more detailed information? Where should I add the code to fix random seed.
I searched for the PyTorch document and found nothing.
Any help would be very appreciated.

**Comment by DKandrew** [comment]
@woolpeeker You raise a good question! It is so sad that nobody is answering this. I believe the seed should be set after the calling of Trainer, which calls the [`init_process_group`](https://pytorch.org/docs/stable/distributed.html#torch.distributed.init_process_group). I raise the same question here #3460
