### ISSUE TITLE
"test_loss" in test step

### ISSUE THREAD

**Issue by hminle** [PyTorchLightning/pytorch-lightning#1936]
Hi PL team,

## 🚀 Feature

![image](https://user-images.githubusercontent.com/16201681/82765900-b56cc780-9de8-11ea-8d53-00b52f6e3060.png)
I see in the test step, we should return "test_loss" instead of "val_loss". 
It will become clearer.

Thanks

**Comment by awaelchli** [comment]
could you point us to the link you found this?

**Comment by hminle** [comment]
> could you point us to the link you found this?

Hi @awaelchli ,
Here you are: https://pytorch-lightning.readthedocs.io/en/stable/introduction_guide.html#testing

**Comment by awaelchli** [comment]
ok, this will probably anyway be overwritten by the docs in part 3 of #2615 structured results.

**Comment by Borda** [comment]
@hminle mind send a PR?

**Comment by romesc-CMU** [comment]
This docs fix was overwritten in `latest` which now recommends returning an `EvalResult` object: https://pytorch-lightning.readthedocs.io/en/latest/introduction_guide.html#testing

The relevant info is now in:

I made a PR to clarify that the validation loop paragraph is also applicable to the test_loop.
#2827

**Comment by awaelchli** [comment]
nice thank you!

**Comment by hminle** [comment]
Thank guys
