### ISSUE TITLE
ModelCheckpoint epoch and progress bar epoch mismatch

### ISSUE THREAD

**Issue by versatran01** [PyTorchLightning/pytorch-lightning#1946]
## 🐛 Bug

Progress bar epoch starts at 1, but in ModelCheckpoint it starts at 0.

### To Reproduce

https://github.com/PyTorchLightning/pytorch-lightning/blob/8ca8336ce52ee7379f4d399520636143eb31018b/pytorch_lightning/callbacks/progress.py#L320

https://github.com/PyTorchLightning/pytorch-lightning/blob/8ca8336ce52ee7379f4d399520636143eb31018b/pytorch_lightning/callbacks/model_checkpoint.py#L212

### Expected behavior

Shouldn't they be consistent?

**Comment by williamFalcon** [comment]
@Borda FYI.
in 0.8.0 we are setting all indexing to be from 0

**Comment by versatran01** [comment]
what is the epoch number of the val sanity check? I don't want to write the results of sanity check to my logs, is there a way to check if validation is currently in sanity check?

**Comment by versatran01** [comment]
This does not seem to be true in 0.8.0. Epoch still starts from 1.

**Comment by williamFalcon** [comment]
yes just noticed that too... they should start from 0 @Borda

**Comment by Borda** [comment]
> yes just noticed that too... they should start from 0 @Borda

ohhh that was my misunderstanding, I thought it shall start from 1 and because of the confusion I was asking about the diff indexing in steps and epochs https://github.com/PyTorchLightning/pytorch-lightning/pull/2206#issuecomment-644568854

Ok, reverting and moving epoch indexing starting from 0
