### ISSUE TITLE
Images take a lot of GPU space

### ISSUE THREAD

**Issue by RafailFridman** [PyTorchLightning/pytorch-lightning#1957]
Right now my dataset is about 15 gigs of png images, with each image taking about 0.15Mb. I'm working on a V100 GPU with 32G of memory. My model takes only about 1G on a GPU, however, I'm not able to use big batches and the maximum that I can use is 32 images per batch. Is this a normal situation? Or there is a possibility that I have a memory leak?

**Comment by HansBambel** [comment]
This very much depends on your network that you implemented. Here is a nice explanation of someone having a similar issue (keras or pytorch does not make a difference): https://stackoverflow.com/questions/53170149/memory-usage-of-neural-network-keras

**Comment by RafailFridman** [comment]
Thank you very much! I surely must have taken that into account.
