### ISSUE TITLE
Validation Loop shall pass the hidden state

### ISSUE THREAD

**Issue by igormq** [PyTorchLightning/pytorch-lightning#1965]
## 🚀 Feature

`validation_step` function only receives the `batch` and `batch_idx`, while the `training_step` also receives the `hiddens` when working with sequences. But, when we are evaluating our recurrent LMs, we pass the hidden state through the validation steps and the pytorch-lightning do not permit this.

**Comment by HansBambel** [comment]
`training_step` also only gets `batch` and `batch_idx`. Do you mean the amount of values that your dataset gives back? 
Similar to #1888 ?

**Comment by igormq** [comment]
Hi @HansBambel, this is not actually true when you are working with sequences, as you can see in         [pytorch_lightning/trainer/__init__.py#L953](https://github.com/PyTorchLightning/pytorch-lightning/blob/7c7e50ca4702a5b35bc1b80d44bca7606552093a/pytorch_lightning/trainer/__init__.py#L953)

**Comment by HansBambel** [comment]
Oh, you're right. Haven't used LSTMs in pytorch lightning yet. Sorry for the confusion!

**Comment by igormq** [comment]
Don't worry! I am having some issues when using recurrent networks. Actually, I think would be better if we were able to pass between the lifecycle any object we wan't haha.

**Comment by williamFalcon** [comment]
you can just assign the objects you want to self

self.thing_i_need = ...

**Comment by igormq** [comment]
Yes, of course I can, but it is brittle, don't you think?

Both training_step and validation_step should have at least the same api regarding the hidden state

**Comment by Borda** [comment]
@igormq what API do you propose?

**Comment by petrgeiger-incieve** [comment]
+1

**Comment by ggdupont** [comment]
+1

**Comment by timlod** [comment]
+1

**Comment by davzaman** [comment]
Does anyone have a fix for this?
