### ISSUE TITLE
ModelCheckpointCallback.on_validation_end does not listen to val_check_interval?

### ISSUE THREAD

**Issue by sshleifer** [PyTorchLightning/pytorch-lightning#1966]
Evidence: I have a unit test where I train for 2 epochs with `val_check_interval=0.5` and I only get two model checkpoints. Set breakpoints and indeed it is only hit twice. Would expect 4 times.

**Comment by HansBambel** [comment]
In the `ModelCheckpoint` class is a parameter `period` that tells the callback after how many epochs a model is saved. Since this value is supposed to be an int I think it is only possible to save the model after whole epochs.

**Comment by sshleifer** [comment]
Is there any plan to change that or a way to make a checkpointing callback to run on_validation_end?

**Comment by williamFalcon** [comment]
yes, checkpoint and that API is being reworked atm #1989.
