### ISSUE TITLE
What the NeptuneLogger records as params or properties

### ISSUE THREAD

**Issue by hirune924** [PyTorchLightning/pytorch-lightning#1977]
#### What is your question?
Currently, NeptuneLogger seems to be logging property what is passed as a hparams.

https://github.com/PyTorchLightning/pytorch-lightning/blob/c3cf33d1de7de3444e3a4a7d45bc613d8e01a7c0/pytorch_lightning/loggers/neptune.py#L233
```
    @rank_zero_only
    def log_hyperparams(self, params: Union[Dict[str, Any], Namespace]) -> None:
        params = self._convert_params(params)
        params = self._flatten_dict(params)
        for key, val in params.items():
            self.experiment.set_property(f'param__{key}', val)
```
But neptune-client has already logged the hparams that were passed to it when it did the project.create_experiment. So the current implementation is trying to log hparams twice, in different ways.

Now I am trying to log a large number of hparams using hydra.
And it doesn't take much time to log the hparams during project.create_experiment, but it takes a long time to repeat the set_property in log_hyperparams loop.

So I am rewriting and running as follows, but there is no inconvenience
Is there a problem with changing it in this way? Also, is there any chance that this will be the default?
```
    @rank_zero_only
    def log_hyperparams(self, params: Union[Dict[str, Any], Namespace]) -> None:
        pass
```

#### What's your environment?

 - OS: [Linux]
 - Packaging [pip]
 - Version [0.7.6]

**Comment by Borda** [comment]
@jakubczakon @pitercl mind have a look pls ^^

**Comment by pitercl** [comment]
Hi @hirune924, the underlying problem is that currently Neptune doesn't allow overwriting parameters after experiment creation. We'll be changing that within the next month. This will fix both the problem with doubling the parameters and the problem with inefficient implementation of `log_hyperparameters`.

I think that for now, your workaround is a good idea.

**Comment by tdvginz** [comment]
Hi, this is still the case with Neptune.
I.e, while logging with comet/TB takes 0.1 sec to log hyperparameters, it takes 100 seconds with Neptune (250 hyper parameters)
