### ISSUE TITLE
Best practice: How to convert a tensor created in __init__() to the same device as the model

### ISSUE THREAD

**Issue by DKandrew** [PyTorchLightning/pytorch-lightning#1978]
#### Question
Say I create a tensor in the `__init__()` of a module, what is the best practice for me to convert it to the same device as the module so that it works for cpu/gpu/distributed training environment?

#### Things that I tried
I tried to put this type check into the `prepare_data()` function, and run the module in GPU, but it seems like the module type is still in CPU when this function is called. 

I then tried to put in my `forward()` function, because this is eventually where the train/validation/test will end up with, but this looks ugly because we need to do this check at every step, but essentially we only need to call do it once. Is there a better solution?

**Comment by awaelchli** [comment]
This is a PyTorch question. Register it as a buffer.
See pytorch docs for register_buffer.

**Comment by DKandrew** [comment]
WOWW this is awesome!! Thank you!!!
