### ISSUE TITLE
Dynamically change optimizer frequency

### ISSUE THREAD

**Issue by lucadiliello** [PyTorchLightning/pytorch-lightning#1979]
#### What is your question?
I have a WGAN and the ratio between iterations on the discriminator and on the generator is fixed at 5:1. I accomplished this by passing the frequency parameter in the `configure_optimizers` method
```
res_1 = {
            'optimizer': optimizer_d,
            'frequency': 5,
            'lr_scheduler': scheduler_d
        }
```
same for generator
```
res_2 = {
            'optimizer': optimizer_g,
            'frequency': 1, 
            'lr_scheduler': scheduler_g
        }
```

How can I dynamically change the `frequency` parameter, such that for the first `n` iterations I have a frequency `x` and after I have a frequency `y`.

#### Code

Don't know how to do it.

#### What's your environment?

 - OS: OS independent
 - Packaging: pip
 - Version: 0.7.6

**Comment by SkafteNicki** [comment]
There is no official way of doing this. However, this can be achieved using a `Callback` to change the `Trainer` attribute `optimizer_frequencies`. So if you define callback like this:
```
class DynamicOptimizerFrequency(Callback):
    def on_epoch_end(self, trainer, model):
           if trainer.current_epoch >10:
               trainer.optimizer_frequency = [3,1]
           if trainer.current_epoch > 20:
               trainer.optimizer_frequency = [2,1]
```
where you change the code to however dynamically you want to change the frequencies.

**Comment by lucadiliello** [comment]
Oh fantastic. I will try then to create a `Callback` and maybe create a pull request to let others use it. You pointed me to the right way.
