### ISSUE TITLE
Project structure drawing typo (Quick Start diagram)

### ISSUE THREAD

**Issue by nikitajz** [PyTorchLightning/pytorch-lightning#1985]
## 📚 Documentation

I've noticed there is a tiny mistake in Quick Start diagram:
https://pytorch-lightning.readthedocs.io/en/stable/_images/pt_to_pl.jpg
`optimizer.zero_grad()` should be part of the `Trainer`

I'm afraid this requires the original image to fix it, so I've added details of what should be fixed:
https://i.imgur.com/eNMAPhF.jpg
It would be also great to make it clickable to enlarge.

**Comment by Borda** [comment]
@williamFalcon mind share the drawable image?
@nikitajz nice, mind draft a PR?

**Comment by ydcjeff** [comment]
@Borda I think this is fixed on latest docs with the awesome GIF.
