### ISSUE TITLE
Stopping the code along with a graceful shutdown.

### ISSUE THREAD

**Issue by nsidn98** [PyTorchLightning/pytorch-lightning#1988]
##
Is there a way to stop the training in the model when some criteria are satisfied. Something along the lines:
```
class myCallback(Callback):
    def __init__(self):
        ...
    def on_epoch_end(self, trainer, pl_module):
        if criteria:
            model.stop_training = True # stops the training; need help here
```
Note that I also want to have the early stopping feature where the 'val_loss' is monitored but want to stop running the code if some other criteria is satisfied. Also, is my method of having this feature in the callback module correct or should I inherit the early stopping criteria?

**Comment by awaelchli** [comment]
You could raise KeyboardInterrupt, this will lead to a graceful shutdown. There is some work in progress in this PR:
#1631

**Comment by nsidn98** [comment]
Got it by using `raise KeyboardInterrupt` in the code.
Closing the issue
