### ISSUE TITLE
TestTube version attribute does not perform as documented

### ISSUE THREAD

**Issue by jeremyjordan** [PyTorchLightning/pytorch-lightning#1997]
###  🐛 Bug

The docs for TestTube logger state:
> If version is not specified the logger inspects the save for existing versions, then automatically assigns the next available version.

However, this does not happen.

### To Reproduce

```
>>> from pytorch_lightning.loggers import TestTubeLogger
>>> logger = TestTubeLogger('tb_logs', name='my_model')
>>> logger.version
>>> assert logger.version is None
```

### Expected behavior

I would expect the TestTube logger performs something similar to:
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/loggers/tensorboard.py#L177

**Comment by rohitgr7** [comment]
Since the experiment is not initialized in the constructor no version is assigned. Either the docs needs to be updated or the experiment should be initialized within the constructor.

**Comment by Borda** [comment]
@rohitgr7 mind update docs?

**Comment by jeremyjordan** [comment]
I would push for an implementation similar to the Tensorboard logger rather than simply updating the docs. The reason is that the ModelCheckpoint checks the logger version when the Trainer is initialized (https://github.com/PyTorchLightning/pytorch-lightning/pull/1504/files#diff-78066f556babcb77bb4490eca66c7ec1L50 - I created this issue based on observing the problem in that PR) and right now (in my PR) it is saving checkpoints to `version_None` which is less than ideal.

**Comment by rohitgr7** [comment]
I checked with master only and it's working fine there. I see that in your PR you fixed the WandbLogger version issue.
