### ISSUE TITLE
log_save_interval doesn't have the intended effect

### ISSUE THREAD

**Issue by gsellers-tulco** [PyTorchLightning/pytorch-lightning#2003]
## 🐛 Bug

I'm using the `MLFlowLogger` class for logging, and initially, I noticed my training loop slowed down immensely when changing the tracking URI from my local file system to a remote mlflow server (which makes sense). To fix this, I saw in the pytorch lightning docs that `log_save_interval` can be used to change the frequency at which logs are written and `row_log_interval` can be used to change the frequency at which rows are added to the logs. However, I found that `log_save_interval` has no effect on speeding up the training loop, and only `row_log_interval` speeds up the training loop.

### To Reproduce

1. Take any training loop and log metrics to a remote server (in this case for mlflow)
2. Manipulate log_save_interval and row_log_interval to see the effect

#### Code sample

The behavior makes sense when looking at sections of the pytorch lightning codebase.
In `pytorch_lightning/trainer/training_loop.py`:
```
            # when logs should be saved
            should_save_log = (batch_idx + 1) % self.log_save_interval == 0 or early_stop_epoch
            if should_save_log or self.fast_dev_run:
                if self.proc_rank == 0 and self.logger is not None:
                    self.logger.save()

            # when metrics should be logged
            should_log_metrics = batch_idx % self.row_log_interval == 0 or early_stop_epoch
            if should_log_metrics or self.fast_dev_run:
                # logs user requested information to logger
                self.log_metrics(batch_step_metrics, grad_norm_dic)
```
From the above, it can be seen that `log_save_interval` is not used to control when metrics are logged. From what I can tell `self.log_metrics` leads to a call to:
```
self.logger.agg_and_log_metrics(scalar_metrics, step=step)
```
in `pytorch_lightning/trainer/logging.py` which for mlflow causes a write to the remote server.

### Expected behavior

I expected `log_save_interval` to reduce the amount of remote writes, but it does not.

### Environment

```
* CUDA:
        - GPU:
        - available:         False
        - version:           None
* Packages:
        - numpy:             1.18.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.4.0
        - pytorch-lightning: 0.7.5
        - tensorboard:       2.2.1
        - tqdm:              4.46.0
* System:
        - OS:                Darwin
        - architecture:
                - 64bit
                - 
        - processor:         i386
        - python:            3.8.2
        - version:           Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
```

### Additional context

I'm aware my pytorch lightning version is behind the latest (due to an issue with 0.7.6 which seems to have been fixed in master), but my code samples are from the latest code.

**Comment by awaelchli** [comment]
Had a quick look and it seems that this trainer flag does not apply to all loggers. AFAIK In MLFlow, there is no distinction between adding rows and saving the logs. It probably only applies to the TensorBoard logger. 
We could think about documenting this fact or pulling it out of the Trainer and make it an argument of the TensorBoardLogger.
