### ISSUE TITLE
Error using TrainsLogger with Trainer in 'ddp'

### ISSUE THREAD

**Issue by itsikad** [PyTorchLightning/pytorch-lightning#2018]
## 🐛 Bug

Got the following error when using TrainsLogger with 'ddp' backend during run_pretrain_routine.
1. Doesn't happen with 'dp' backend
2. The attribute self._metrics_to_agg still exists up to the point where spawn._wrap is called

>  -- Process 0 terminated with the following error:
> Traceback (most recent call last):
>   File "/home/access/projects/depth_completion/venv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
>     fn(i, *args)
>   File "/home/access/projects/depth_completion/venv/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_data_parallel.py", line 389, in ddp_train
>     self.run_pretrain_routine(model)
>   File "/home/access/projects/depth_completion/venv/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 943, in run_pretrain_routine
>     self.logger.save()
>   File "/home/access/projects/depth_completion/venv/lib/python3.6/site-packages/pytorch_lightning/loggers/base.py", line 225, in save
>     self._finalize_agg_metrics()
>   File "/home/access/projects/depth_completion/venv/lib/python3.6/site-packages/pytorch_lightning/loggers/base.py", line 110, in _finalize_agg_metrics
>     agg_step, metrics_to_log = self._reduce_agg_metrics()
>   File "/home/access/projects/depth_completion/venv/lib/python3.6/site-packages/pytorch_lightning/loggers/base.py", line 100, in _reduce_agg_metrics
>     if not self._metrics_to_agg:
> AttributeError: 'TrainsLogger' object has no attribute '_metrics_to_agg'
>   File "/home/access/projects/depth_completion/src/issue_reproduce.py", line 62, in main
>     trainer.fit(experiment)
>   File "/home/access/projects/depth_completion/src/issue_reproduce.py", line 65, in <module>
>     main()

### To Reproduce
See code below

#### Code sample
```
The following code will reproduce the issue:
import torch.nn as nn
import os
from torch.optim import Adam
import pytorch_lightning as pl
from pytorch_lightning import Trainer
from pytorch_lightning.loggers import TrainsLogger
from torchvision import transforms
from torchvision.datasets import MNIST
from torch.utils.data import DataLoader, random_split

class Exp(pl.LightningModule):
    def __init__(self):
        super(Exp, self).__init__()
        self.layer_1 = nn.Linear(in_features=28**2, out_features=1)
        self.loss = nn.MSELoss(reduction='mean')

    def forward(self, img):
        return self.layer_1(img.view([-1,1,28**2])).squeeze()
        
    def training_step(self, batch, batch_idx):
        x, y = batch
        pred = self.forward(x)
        loss = self.loss(pred, y)
        return {'loss' : loss}

    def validation_step(self, batch, batch_idx):
        x, y = batch
        pred = self.forward(x)
        loss = self.loss(pred, y)
        return {'val_loss' : loss}

    def train_dataloader(self):
        transform=transforms.Compose([transforms.ToTensor(),
                                      transforms.Normalize((0.1307,), (0.3081,))])
        mnist_train = MNIST(os.getcwd(), train=True, download=False,
                            transform=transform)
        return DataLoader(mnist_train, batch_size=64)
        
    def val_dataloader(self):
        transform=transforms.Compose([transforms.ToTensor(),
                                      transforms.Normalize((0.1307,), (0.3081,))])
        mnist_train = MNIST(os.getcwd(), train=True, download=True,
                            transform=transform)
        _, mnist_val = random_split(mnist_train, [55000, 5000])
        mnist_val = DataLoader(mnist_val, batch_size=64)
        return mnist_val

    def configure_optimizers(self):
        return Adam(self.parameters(), lr=1e-3)  # TODO: scheduler

def main():
    trains_logger = TrainsLogger(project_name='Reproduce Issue',
                                task_name='reproduction',
                                output_uri='.')

    trainer = Trainer(logger=trains_logger,
                    #   distributed_backend='dp',
                      num_nodes=1,
                      gpus=2)

    experiment = Exp()
    trainer.fit(experiment)

if __name__ == '__main__':
    main()
```

### Expected behavior

Should run smoothly (this is almost a copy-paste from pytorch-lightning introduction tutorial and TrainsLogger example)

### Environment

python: 3.6.9 (pip 20.1.1)
torch : 1.5 
trains: 0.14.3 
pytorch-lightning: 0.7.6
OS: Ubuntu 18.04
gpus: 2x RTX 2080 Ti
CUDA: 10.1

**Comment by itsikad** [comment]
@allegroai I believe this maybe of interest for you.
This issued pushed me to use another logger instead.

**Comment by bmartinn** [comment]
Thanks @itsikad I'll take a look.

> AttributeError: 'TrainsLogger' object has no attribute '_metrics_to_agg'

Seems like the TrainsLogger is internal attribute, "_metrics_to_agg" , which is odd I'm not aware this is an abstract attribute that needs implementation...
