### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by DKandrew** [PyTorchLightning/pytorch-lightning#2022]
In the documentation [logger](https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.loggers.html#using-loggers) where it says "Read more in the [Experiment Logging use case](https://pytorch-lightning.readthedocs.io/en/latest/api/experiment_logging.html)", the link is broken.

**Comment by Borda** [comment]
@DKandrew mind send a PR? :rabbit:

**Comment by DKandrew** [comment]
Sure! Should I just route the link to this [website](https://pytorch-lightning.readthedocs.io/en/latest/experiment_reporting.html#)?

**Comment by Borda** [comment]
> Update: I think I can see where the problem comes from, but I don't know how to modify it.

mind check this link generation
https://github.com/PyTorchLightning/pytorch-lightning/blob/0914873bc2f588ae592c896460c0c9e6577324cf/docs/source/conf.py#L348-L382

**Comment by Borda** [comment]
@DKandrew how is it going, did the link generation helped?

**Comment by DKandrew** [comment]
@Borda Hi Borda, Sorry I did not look into it because this week is my final week. Could I fix this issue during the weekend?

**Comment by Borda** [comment]
Sure, and thanks for your help

**Comment by DKandrew** [comment]
Hi @Borda 

After looking into this issue in the afternoon. I don't think I can come up with a perfect solution. 

The only working solution that I have, is to change the link to the online linkage. 
```
# Change from 
Read more in the `Experiment Logging use case <./experiment_logging.html>`_.
# To 
Read more in the `Experiment Logging use case <https://pytorch-lightning.readthedocs.io/en/latest/experiment_logging.html>`_.
```

----

The challenge is that the reference link is encoded in the docstring, not in a pure `.rst` file, so the Custom Anchor solution listed [here](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html) does not work. The function `linkcode_resolve` does not help because it seems that it is generating a link to the main body of a Python function/variable, not an unnamed string put on top of the Python file.   

Similar reference issue is also discovered in this link
https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.trainer.html
Again, because of the `../api/..` in the path of HTML, if you try to click 

* Multi-GPU training guide
* Multi-node (SLURM) guide
* Any link that does not belong to `api` folder

You will get the same 404 result. 


------

The downside of my solution is that developers have to have a network connection when they test this link, and the link will not direct to their local file (which they may be also developing). 

Any Suggestions?

**Comment by Kshitij09** [comment]
> "Read more in the Experiment Logging use case"

 I didn't see this line on logger [documentation](https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.loggers.html#using-loggers).  Is it removed?

**Comment by Borda** [comment]
@DKandrew as it is a while, I am wondering if this is still valid, mind update?

**Comment by DKandrew** [comment]
Hello @Borda,  it seems like the documentation in the original [page](https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.loggers.html#using-loggers) is gone, as @Kshitij09 points out. So this case may not be valid anymore.
