### ISSUE TITLE
Support DictConfig

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#2027]
We need to add DictConfig support for Omegaconf @Borda to the auto hparam save

**Comment by DKandrew** [comment]
Yes, I agree. Users should have other options besides argument parser to set up their configuration. Personally speaking, I don't like typing too much on the command line b/c that is error-prone. A dictionary-like configuration system would be great. One example would be Ross's [yacs](https://github.com/rbgirshick/yacs) which works pretty well.

**Comment by Darktex** [comment]
OmegaConf is along the same lines as Yacs, but with more features (might as well support YACS too, but just saying).

**Comment by Borda** [comment]
@DKandrew @Darktex you would keep passing one eg `OmegaConf` argument which is used internally? Kind of pseudocode...
1. ```
    conf = OmegaConf(...)
    model = MyModel(conf)
    ```
2. ```
    conf = OmegaConf(...)
    model = MyModel(**vars(conf))
    ```
assuming that the conf can be also loaded from a file...

**Comment by DKandrew** [comment]
Hi @Borda 
I am not sure if I understand your question correctly, are you asking which approach you listed above is better?

**Comment by Borda** [comment]
> I am not sure if I understand your question correctly, are you asking which approach you listed above is better?

I am trying to understand your use-case, mind draw your use case?

**Comment by williamFalcon** [comment]
let’s do this:

## case 1
User explicitly says what they want to save.

```python
class LitModel(...):

    def __init__(self, conf):
        self.save_hyperparameters(conf)
```

## Case 2:
User wants to save all the init stuff

```python
```python
class LitModel(...):

    def __init__(self, arg1, arg2, arg3):
        self.save_hyperparameters(arg_name=arg1, arg_name=arg2, arg_name=arg3)
        
        # equivalent
        self.save_hyperparameters()
```


```

**Comment by DKandrew** [comment]
> let’s do this:
Sounds good to me. Looking forward to it!

**Comment by Borda** [comment]
> ## case 1
> User explicitly says what they want to save.
> 
> ```python
> class LitModel(...):
> 
>     def __init__(self, conf):
>         self.save_hyperparameters(conf)
> ```

is very tricky as we would need to do some pairing from init frame and hope none of the `conf1, conf2, ...` has the same value so I would skip this case...

> ## Special cases:
> * namespace
> * dict
> 
> ```python
>     def __init__(self, conf):
>         # manually
>         self.save_hyperparameters(conf)
> ```

here you want to unroll all elements?
 assume you have `some_dict=dict(a=1, b=3)` then you would in fact do something similar like `self.save_hyperparameters(**some_dict)`

if fact 
```
def save_hyperparameters(**kwargs):
    ...
    for elms in kwargs:
        if isisntance(conf, (dict, OmegaConf)):
            self.save_hyperparameters(**conf)
        if isisntance(conf, Namespace):
            self.save_hyperparameters(**vars(conf))
       ...
```
