### ISSUE TITLE
Docs are missing the anchor links

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#2034]
## 📚 Documentation

As pointed out by @oplatek the docs suddenly miss the anchor button that allows one to generate a link that points to a particular resource within a page.

This was working before, but now there is a 404 when accessing some assets (js, css, ...)

EDIT: seems not related to the 404 seen in the JS console.

**Comment by awaelchli** [comment]
I noticed the following:
1. The anchor links for title sections are there
2. The anchor links are only missing for the class/method/function definitions in the docs composed in .rst files. 
3. If you search for the class/function in the search box and click on the result, you get to a page where all the anchor links are there. For example, compare [this](https://pytorch-lightning.readthedocs.io/en/latest/callbacks.html) vs. [this](https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.callbacks.base.html?highlight=callback).

So it seems the theme is only inserting the anchor links in autogenerated docs, but not the handwritten .rst files. 

No idea how to fix it still...

**Comment by awaelchli** [comment]
I think this is the issue:
https://github.com/sphinx-doc/sphinx/issues/7052
All docs that have :noindex: in the automodule/autoclass don't get the permalink

**Comment by Borda** [comment]
so there is nothing we can do about it... @awaelchli, right?

**Comment by awaelchli** [comment]
@Borda We will be when they release the new sphinx version. We can replace the `:noindex:` with `:noindexentry:` and it should show the links.

**Comment by ydcjeff** [comment]
Is this still an issue? I would like to take it.

**Comment by ydcjeff** [comment]
Btw, what is the issue tho?

**Comment by awaelchli** [comment]
have not made progress. so I'm happy if you can take it. as mentioned on slack, I believe the links are missing because we have two types of docs and we can't index both, and one has the :noindex: label, which causes links to disappear.

**Comment by ydcjeff** [comment]
I think could it be fixed with autosummary?
