### ISSUE TITLE
Ctrl + C does not kill the process

### ISSUE THREAD

**Issue by pvnieo** [PyTorchLightning/pytorch-lightning#2035]
## 🐛 Bug

Hi there,
I'm using the last dev version available on Master. I have noticed that when I updated the package today, that Ctrl + C does not stop the training anymore, and I verified this by noticing that the model checkpoints continue to be made. I tested this on my laptop and on google colab.

### Expected behavior 
Normal behavior after a KeyboardInterrupt is detected:
```Detected KeyboardInterrupt, attempting graceful shutdown...```

### To Reproduce

You can reproduce this using the [live demo](https://colab.research.google.com/drive/1F_RNcHzTfFuQf-LeKvSlud6x7jXYkG31#scrollTo=HOk9c4_35FKg) provided in the original documentation, by changing the line of pip installing pytorch-lightning by:
```
!pip install --upgrade git+https://github.com/PyTorchLightning/pytorch-lightning.git
```
and launch the training of MNIST model and interrupt the excution by clicking on the stop button.

### Environment

 - PyTorch Version : 1.5
 - OS (e.g., Linux): linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): pip install --upgrade git+https://github.com/PyTorchLightning/pytorch-lightning.git
 - Python version: 3.8
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: GeoForce GTX 1060

**Comment by pvnieo** [comment]
Also, I got this error at the end of training:
```
Error in atexit._run_exitfuncs:
TypeError: run_training_teardown() missing 1 required positional argument: 'self'
```

**Comment by williamFalcon** [comment]
fixed on master
