### ISSUE TITLE
Support omniconf in hparams

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#2040]
We need to get hydra dict config to work.

Proposed solution:
    1. save all primitives to the state of the checkpoint.
    2. create function save_arguments()
        1. if no args passed- save everything in scope, even if it's not primitives.
        2. if kargs specified- save key value pairs.

Make sure to explicitly test the omniconf (saving and loading).

**Comment by Borda** [comment]
are you sure about the name `omniconf` I found this but it is not probably it https://pypi.org/project/omniconf

**Comment by edenlightning** [comment]
Yes, i guess it is.

**Comment by omry** [comment]
definitely not omniconf.

https://github.com/omry/omegaconf

**Comment by edenlightning** [comment]
Apologize for the confusion, fixed now! Thanks!
