### ISSUE TITLE
speed-up too long tests

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#2041]
We should make sure our tests run in a reasonable time.
Check the speed of all tests and set an upper bound for testing time. Also check if we can enforce that in GH (except parity tests).
Find hanging tests that are taking the longest- and ping last author to fix.

**Comment by awaelchli** [comment]
> Find hanging tests that are taking the longest- and ping last author to fix.

Haha this is good :)

**Comment by Borda** [comment]
After deploying the new docker image we lower GPU runtime from 14min to 9min #3658 
some more speed gain shall come from using a simpler model for testing #3827
