### ISSUE TITLE
Checkpoint customized format

### ISSUE THREAD

**Issue by pvnieo** [PyTorchLightning/pytorch-lightning#2042]
## 🚀 Feature
Hi all,

Is it possible to add a parameter to ModelCheckpoint that represent the format for the `filename`. Indeed, filename is by default `{epoch}`, and it would be cool if we can see the validation metrics in the name of the model, for example: `{epoch}-{val_loss:.2f}`.

Currently, the `filename` format is set in `configure_checkpoint_callback()` during `run_pretrain_routine`, and it is impossible to access the attribute `trainer.checkpoint_callback.filename` after lunching the train loop `trainer.fit(model)`.

### Motivation

The main motivation is that I want to keep the structure of versions used by default by pytorch-lightning
```
- lightning_logs
    - version_0
        - checkpoints
    - version_1
    - version_2
```

, but also, I want to see my validation metrics in the model filename.

**Comment by rohitgr7** [comment]
You can specify the [filepath parameter](https://github.com/PyTorchLightning/pytorch-lightning/blob/0914873bc2f588ae592c896460c0c9e6577324cf/pytorch_lightning/callbacks/model_checkpoint.py#L84).

**Comment by pvnieo** [comment]
@rohitgr7 Thank you for your response. 
Yes, but if I do so, I will lose the default versioning structure of  pytorch-lightning and I need to do it manually.

**Comment by andrewjong** [comment]
Please reopen. Can we get this, please?

**Comment by rohitgr7** [comment]
The only way I can think of is:
```python
mc_cb = ModelCheckpoint(filepath='{val_loss}', save_top_k=-1, verbose=True, monitor='val_loss', mode='min')
mc_cb.dirpath = None
```

**Comment by andrewjong** [comment]
Okay, I found a way to create a custom filename using Callbacks.

```python
class CheckpointCustomFilename(pl.Callback):
    def __init__(self, filename_fmt="{epoch}_{global_step}_{val_loss:.2f}"):
        """
        Formats just the filename of the Trainer checkpoints, such that the path
        organization is preserved and only the filename format is modified.

        Args:
            filename_fmt: see formats here, excluding the preceeding path https://pytorch-lightning.readthedocs.io/en/latest/callbacks.html#model-checkpointing .
              (default: "{epoch}_{global_step}_{val_loss:.2f}")
        """
        self.filename_fmt = filename_fmt

    def on_validation_end(self, trainer: pl.Trainer, pl_module):
        """
        ModelCheckpoint hardcodes self.filename = '{epoch}' in its on_train_start().
        But custom callbacks are called _before_ ModelCheckpoint, meaning setting it
        in our on_train_start() would just get overwritten. Therefore, we set it here in
        on_validation_end(), as checkpointing in Lightning is currently tied to
        Validation performance.
        """
        trainer.checkpoint_callback.filename = self.filename_fmt


Trainer(callbacks=[CheckpointCustomFilename("your_custom_filename_format_here")])
```

Note anything used in the format string must be returned in the result of one of your LightningModule's methods. For me, in my LightningModule adds `{"global_step": self.global_step()}` to the `validation_epoch_end()` return value.

Even though this workaround succeeds, I still think it'd be better to add a "filename" argument to ModelCheckpoint's init.
