### ISSUE TITLE
Installation of packages in requirements-extra.txt fails due to horovod when openmpi isn't installed

### ISSUE THREAD

**Issue by uditarora** [PyTorchLightning/pytorch-lightning#2049]
## 🐛 Bug

Installation of packages in requirements-extra.txt fails due to horovod when openmpi isn't installed on the system.

### To Reproduce

On a system where openmpi isn't installed -

1. Go to `pytorch-lightning`
2. Run `pip install -r tests/requirements-devel.txt`

```
File "/private/var/folders/r8/n9z0w1_x6mxby66vv4tkmsg40000gn/T/pip-install-9qlwgs9u/horovod/setup.py", line 635, in get_common_options
      raise RuntimeError('One of Gloo or MPI are required for Horovod to run. Check the logs above for more info.')
  RuntimeError: One of Gloo or MPI are required for Horovod to run. Check the logs above for more info.
  ----------------------------------------
  ERROR: Failed building wheel for horovod
```

### Expected behavior

The openmpi dependency can potentially be called out separately in the test README.md file, or it can be installed automatically if needed.

**Comment by Borda** [comment]
@uditarora mind send a PR with the suggested update in Readme?
also, you can use already prepared docker images https://hub.docker.com/r/pytorchlightning/pytorch_lightning/tags

**Comment by uditarora** [comment]
Sure, let me send a PR with updated Readme.

And thanks for sharing the docker links.
