### ISSUE TITLE
Keyboard Interrupt lunches test but wandblogger kills the process

### ISSUE THREAD

**Issue by Brechard** [PyTorchLightning/pytorch-lightning#2059]
## 🐛 Bug
I am using WandBLogger and when I have a run that I want to stop manually with a keyboard interrupt, the model correctly stops training and starts executing the Test function. The problem is that at the same time WandBLogger starts uploading the data and when it is done it kills the process, therefore the test function is not finished and that data is not uploaded to the logger ofc.

### To Reproduce

1. Execute a run with wandblogger that has (trainer.fit(model); trainer.test())
2. Ctrl + C

### Expected behavior
Execute train -> Ctrl+C -> stop the training -> lunch the test -> upload everything to the logger

**Comment by Borda** [comment]
@Brechard mind specify your env and Pl version?
@justusschock @jeremyjordan ^^

**Comment by williamFalcon** [comment]
try again using master

**Comment by Brechard** [comment]
I just tryed in master and it has the same problem.

I am runing on an EC2 p3.2xlarge with pytorch 1.5 installed

**Comment by Borda** [comment]
@borisdayma mind have a look? 🐰

**Comment by borisdayma** [comment]
@Borda I never personally use "Ctrl + C". I thought it was mainly to release properly resources.
Would it be expected to keep the logger alive or would there be any kind of risks of incorrect data sent to loggers?
