### ISSUE TITLE
0.8.0-dev can't load model with hparams, KeyError: 'module_arguments'

### ISSUE THREAD

**Issue by xiadingZ** [PyTorchLightning/pytorch-lightning#2067]
## 🐛 Bug
In pt 0.8.0-dev, I  initialize my model with hparams as old version, but it can't be load using `load_from_checkpoint`

```
Traceback (most recent call last):
  File "main.py", line 123, in <module>
    main(hparams)
  File "main.py", line 61, in main
    checkpoint_path=checkpoint,
  File "/mnt/lustre/maxiao1/anaconda3/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1563, in load_from_checkpoint
    checkpoint[CHECKPOINT_KEY_MODULE_ARGS].update(kwargs)
KeyError: 'module_arguments'
```

**Comment by versatran01** [comment]
You can just have your own function that load from the checkpoint, which avoid the mess with moudle_arguments.
something like this hopefully works
```
@classmethod
def load_checkpoint(cls, checkpoint_path):
    checkpoint = th.load(checkpoint_path)
    system = cls(hparams)
    system.load_state_dict(checkpoint['state_dict'])
    return system
```

**Comment by williamFalcon** [comment]
the PR fix is almost ready. I would just wait @Borda. 

this is why generally it’s recommended to use releases instead of master since it’s always in active development and we can’t guarantee that it won’t be broken some times. 
m

**Comment by Borda** [comment]
@xiadingZ mind check #2160
