### ISSUE TITLE
Adding histogram through TensorBoardLogger object not working  

### ISSUE THREAD

**Issue by clmartinez151** [PyTorchLightning/pytorch-lightning#2077]
I tried adding a histogram of the weights in my model to the TensorBoardLogger object, but got the following error:

`<ipython-input-50-72d4a2369ba5> in training_epoch_end(self, outputs)
     24     def training_epoch_end(self, outputs):
     25         for name, param in self.named_parameters():
---> 26             self.logger.experiment.add_histogram(name, param, self.current_epoch)
     27 

/net/10.57.1.2/vol/homes/martinezniev1/complexcode/env/lib64/python3.6/site-packages/torch/utils/tensorboard/writer.py in add_histogram(self, tag, values, global_step, bins, walltime, max_bins)
    408             bins = self.default_bins
    409         self._get_file_writer().add_summary(
--> 410             histogram(tag, values, bins, max_bins=max_bins), global_step, walltime)
    411 
    412     def add_histogram_raw(self, tag, min, max, num, sum, sum_squares,

/net/10.57.1.2/vol/homes/martinezniev1/complexcode/env/lib64/python3.6/site-packages/torch/utils/tensorboard/summary.py in histogram(name, values, bins, max_bins)
    248     name = _clean_tag(name)
    249     values = make_np(values)
--> 250     hist = make_histogram(values.astype(float), bins, max_bins)
    251     return Summary(value=[Summary.Value(tag=name, histo=hist)])
    252 

/net/10.57.1.2/vol/homes/martinezniev1/complexcode/env/lib64/python3.6/site-packages/torch/utils/tensorboard/summary.py in make_histogram(values, bins, max_bins)
    286 
    287     if counts.size == 0 or limits.size == 0:
--> 288         raise ValueError('The histogram is empty, please file a bug report.')
    289 
    290     sum_sq = values.dot(values)

ValueError: The histogram is empty, please file a bug report.`

I'm not sure what to make of this, since I thought that calling self.logger.experiment gave me access to the SummaryWriter object. Anyone know how to get around this?

**Comment by nsarang** [comment]
In my experience, I didn't have any problem with `self.logger.experiment.add_histogram()`. It would be great if you could provide code to reproduce the problem.

**Comment by feiwofeifeixiaowo** [comment]
Hi @nsarang , 
how to write gradient to tensorboard **asynchronously**? when i use ``` self.logger.experiment.add_histogram() ```Python in ``` on_before_zero_grad ``` function,  i can feel the main thread stuck a few milliseconds.

**Comment by nsarang** [comment]
@feiwofeifeixiaowo
How often do you log histograms? It's a slow operation because it needs to write them to disk. I used to log the summaries only every 10 batches.
[on_after_backward](https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.core.hooks.html#pytorch_lightning.core.hooks.ModelHooks.on_after_backward) is where you'd want to do it.

**Comment by feiwofeifeixiaowo** [comment]
@nsarang thanks for your quick reply, i write log every 500 steps because the stuck.
i will try put log operation into ```on_after_backward``` function.
