### ISSUE TITLE
Handle KeyboardInterrupt during training

### ISSUE THREAD

**Issue by moi90** [PyTorchLightning/pytorch-lightning#2079]
## 🚀 Feature

It should be possible to examine the stack  if the training is interrupted manually.

### Motivation

In my case, the program hangs at some point and I have to cancel it manually. Because Lightning catches KeyboardInterrupt, I don't get to know where the program was hanging.

### Alternatives

1. **Re-raise KeyboardInterrupt.** This would break the current behavior. This could be made configurable.
2. **Save result of `sys.exc_info()` for later examination.** This could introduce memory issues like memory leaks or circular references.
3. **Call a handler.** The users could then call `sys.exc_info()` in the handler. This would make memory issues less likely.

I will prepare a pull request for the third option.

**Comment by moi90** [comment]
The least invasive change would be to save the result of sys.exc_info() for later examination.

**Comment by Borda** [comment]
> The least invasive change would be to save the result of sys.exc_info() for later examination.

where would you save it, to logs? mind sending a PR?

**Comment by moi90** [comment]
I already did, see above ;) As I said, using a callback narrows the possibility of memory issues.

**Comment by SurajDonthi** [comment]
Is this feature up in the latest release - 0.9.0?

I'm looking to perform actions on Keyboard Interrupt but haven't been successful!

**Comment by moi90** [comment]
```sh
git tag --contains fd1693e
0.8.0
0.8.1
0.8.2
0.8.3
0.8.4
0.8.5
0.9.0
0.9.1rc1
```

So: Yes.
