### ISSUE TITLE
[test] Add memory parity tests

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#2080]
Preferably add memory parity assertions to existing tests, to avoid extra run time.

Memory parity tests are important to avoid memory leaks.

**Comment by Borda** [comment]
Fron Will in core....
`torch.cuda.memory_snapshot()`
I think we could use this to generate a memory profiler
```
(Pdb) torch.cuda.memory_allocated(device=None)
9580032
(Pdb) torch.cuda.memory_allocated(device=‘cuda:0’)
0
(Pdb) torch.cuda.memory_allocated(device=‘cuda:1’)
0
```
