### ISSUE TITLE
Add multi GPU tests for torchelastic nightly

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#2088]
Add a test to CircleCI that spawns to torchelastic and verify that raining works and that the training model returned is correct.

**Comment by Borda** [comment]
is this done with `ddp_spawn` #2115 @williamFalcon ?

**Comment by Borda** [comment]
@edenlightning I have a hard time finding how the `torchelastic` is installed...
so basically we just want to test it on the nightly version, or something else?

**Comment by edenlightning** [comment]
blocked by https://github.com/PyTorchLightning/pytorch-lightning/issues/2089

**Comment by edenlightning** [comment]
@Borda still blocked?

**Comment by edenlightning** [comment]
@Borda ?
