### ISSUE TITLE
[test] Add tests against PT nightly using GPUs

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#2090]
Testing against nightly build.

**Comment by ydcjeff** [comment]
@Borda I would like to take this

**Comment by Borda** [comment]
@ydcjeff cool, I guess that for that we would need to redo the image to be based on CUDA directly not on PyTorch image as this way would allow us to unify the exiting and pre-release PTs

**Comment by ydcjeff** [comment]
so, test with github actions?

**Comment by Borda** [comment]
well, I see two ways:
- update the docker image and use it for Drone (but this we need to extend Drone capacity to run stable and develop PT)
- add extra GH Action to test just pre-release (the reason for extra config is to have a separate badge for both)

**Comment by ydcjeff** [comment]
I will go for GH action

**Comment by ydcjeff** [comment]
@Borda I have updated the docker image to be based on CUDA for stable and nightly PyTorch.

https://github.com/ydcjeff/nightly
Please let me know if the CUDA image is the right one.

For testing with GPUs, should we run tests in parallel for stable and dev PyTorch version? OR
should we run one after another?

**Comment by ydcjeff** [comment]
@Borda

**Comment by Borda** [comment]
Have you open a PR to check the update?
Sorry for late reply, I am out of office these days
