### ISSUE TITLE
Save checkpoint on Ctrl+C

### ISSUE THREAD

**Issue by nkyriazis** [PyTorchLightning/pytorch-lightning#2095]
I understand that pl handles cli ctrl+c with graceful degradation. I also see the ability to save checkpoints which is triggered by metrics queries. Is there is an idiomatic way to have pl save a checkpoint when I ctrl+c?

**Comment by williamFalcon** [comment]
we should add a callback, on_ctrl_c or something

**Comment by Borda** [comment]
@nkyriazis mind send a PR with saving in `on_interupr`

**Comment by kaushal-py** [comment]
Hi I am a new contributor. I would like to work on this issue if no one else is working on it. Where could I find the `on_interupr` utility?

**Comment by kaushal-py** [comment]
Hi I am a new contributor. I would like to work on this issue if no one else is working on it. I could not locate the `on_interupr` utility on the master branch. Am I missing something?

**Comment by williamFalcon** [comment]
go for it!

why not just support ctrl+s?  isn’t this a more user friendly approach haha?

or do you also mean save a checkpoint on interrupt?

**Comment by kaushal-py** [comment]
Saving a checkpoint on ctrl+s is also not a bad idea.
Terminate program without saving checkpoint : ctrl+c
Terminate program and save latest checkpoint : ctrl+s
Does this sound good?

**Comment by williamFalcon** [comment]
i was thinking more like ctrl+s saves a checkpoint at that time. 

then separately if you want to finish training ctrl+c

**Comment by kaushal-py** [comment]
Wouldn't this be an issue if the program is in middle of a training epoch. Generally we save checkpoints at the end of an epoch right?

**Comment by justusschock** [comment]
@williamFalcon I'm not sure this is possible

actually I don't think so, because python does not raise an Exception on ctrl+s. So there's nothing we can actually hook into, since all inputs, that are not caught by pythons io or raise an exception are postponed until the program is finished afaik

**Comment by chenzhekl** [comment]
This feature seems to be no longer available in the latest release. Is it expected?

**Comment by noctildon** [comment]
This should be what you are looking for
https://lightning.ai/docs/pytorch/latest/api/lightning.pytorch.callbacks.OnExceptionCheckpoint.html
