### ISSUE TITLE
CI: run doctests only on GPU machine

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#2098]
Currently the doctests run on CPU and GPU but we can't include any GPU related doctests, otherwise they would fail on CPU-only machines. 

I propose to turn off CI doctests for CPU-only machines and only let them run on machines with GPU (i.e. drone). 

This would allow us to write doctests also for GPU related stuff.

@Borda

**Comment by Borda** [comment]
I would rather have doctest that would work on both CPU and GPU as it allows anyone to run all test suite locally and move GPU test in docstring to code samples (or find a way to run then under conditions of GPU)

**Comment by awaelchli** [comment]
I understand, but it will block us of writing doctests for many things. For example here: 1905 I would like a doctest as an example how it works, but it is impossible if the CI fails when no gpus are found.

**Comment by awaelchli** [comment]
> or find a way to run then under conditions of GPU

I have not found a way. It seem impossible with pytest to skip conditionally

**Comment by Borda** [comment]
> I understand, but it will block us of writing doctests for many things. For example here: #1905 I would like a doctest as an example how it works, but it is impossible if the CI fails when no gpus are found.

I understand, but unfortunately, I do not see any other solution for now as doctests supports only `+SKIP` not `skipif`, see the docs https://docs.python.org/3/library/doctest.html#option-flags

**Comment by awaelchli** [comment]
😢 that's a bummer. I wonder how PyTorch does it?
not sure, but probably this is an unsolvable problem if we want to keep it everywhere in CI. So shall I close the issue then?

**Comment by Borda** [comment]
Actually they may not run it and ignore some files in pytest without GPU...
