### ISSUE TITLE
check_model_configuration throws error for no val_dataloader even if val_check_percent == 0

### ISSUE THREAD

**Issue by filipeabperes** [PyTorchLightning/pytorch-lightning#2100]
The `check_model_configuration` method raises an error when `val_dataloader` is `None` even if `val_check_percent` is 0, due to the line below.

https://github.com/PyTorchLightning/pytorch-lightning/blob/c09317e68f7b108ba4efac44726090812005e9f2/pytorch_lightning/trainer/trainer.py#L1145

This ends up being a bit annoying, since a common use case is to have a `LightningModule` set up that has a `validation_step`, but for some part of development temporarily pass in no validation dataset. The current implementation already has a way for disabling validation, which is to set `val_check_percent` to 0. However, in this case this does not avoid the error in the line above. 

Fix should be simple, simply changing the condition to

```
if self.is_overridden('validation_step', model) and self.val_percent_check != 0:
```

Or it might also make sense to simply accept the case where no `val_dataloader` is passed and skip the `validation_step`, showing a warning to the user. There seems to already be a related warning that says `UserWarning: One of given dataloaders is None and it will be skipped.`.

**Comment by bharathc346** [comment]
Second this. Is there any plan to do this
