### ISSUE TITLE
Unable to run tests locally due to missing dependencies

### ISSUE THREAD

**Issue by uditarora** [PyTorchLightning/pytorch-lightning#2120]
## 🐛 Bug

Unable to run tests locally due to missing dependencies on torchvision and gym packages.

### To Reproduce

1. Follow the instructions to run tests locally in the contributing guide.

#### Error message

```bash
_______________________________________________________ ERROR collecting pl_examples/__init__.py ________________________________________________________
pl_examples/__init__.py:143: in <module>
    from pl_examples.models.lightning_template import LightningTemplateModel
pl_examples/models/lightning_template.py:10: in <module>
    import torchvision.transforms as transforms
E   ModuleNotFoundError: No module named 'torchvision'

...

_________________________________________ ERROR collecting pl_examples/domain_templates/reinforce_learn_Qnet.py _________________________________________
pl_examples/domain_templates/reinforce_learn_Qnet.py:26: in <module>
    import gym
E   ModuleNotFoundError: No module named 'gym'
```

### Expected behavior

The packages should be added in tests/requirements.txt

**Comment by williamFalcon** [comment]
@Borda

**Comment by Borda** [comment]
@williamFalcon already resolved in the related PR, the info was missing in contrib notes but it is in [pl_examples/requirements.txt](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/requirements.txt)
