### ISSUE TITLE
Error in Bert example in Lightning demo notebook

### ISSUE THREAD

**Issue by fotisj** [PyTorchLightning/pytorch-lightning#2123]
## 📚 Documentation

the notebook which contains examples of MNIST, GAN, etc. has also an example how to finetune Bert which is broken. This is the error message:

> `---------------------------------------------------------------------------
> 
> TypeError                                 Traceback (most recent call last)
> 
> <ipython-input-8-28b627c75784> in <module>()
> ----> 1 bert_mnli_train_dataloader, bert_mnli_val_dataloader, bert_mnli_test_dataloader = generate_mnli_bert_dataloaders()
> 
> <ipython-input-7-e2c277301a17> in generate_mnli_bert_dataloaders()
>      11                                           pad_on_left=False,
>      12                                           pad_token=tokenizer.pad_token_id,
> ---> 13                                           pad_token_segment_id=0)
>      14   train_dataset = TensorDataset(torch.tensor([f.input_ids for f in features], dtype=torch.long), 
>      15                                 torch.tensor([f.attention_mask for f in features], dtype=torch.long),
> 
> TypeError: glue_convert_examples_to_features() got an unexpected keyword argument 'pad_on_left'
> 
> `
> 

the function generate_mnli_bert_dataloaders() calls the method glue_convert_examples_to_features() which - according to the [documentation ](https://huggingface.co/transformers/main_classes/processors.html)- is not handling the padding.

Fixed the error and hit the next one: 

> MisconfigurationException: Your val_dataloader has shuffle=True, it is best practice to turn this off for validation and test dataloaders.

I guess this is the result of using RandomSampler above.

**Comment by fotisj** [comment]
@Borda I am sorry, if I gave you the impression, that I finished debugging the example. I didn't. I just got past the first bug, but I never found out, whether my fix (removing all lines relating to padding) is really working. Just wanted to let you know that one of the basic examples -- basically one of the first things you see after reading the website -- seems to be broken.

**Comment by Borda** [comment]
we shall move these examples to the repo so we can simply fix it... 
cc: @nateraw

**Comment by nateraw** [comment]
I believe this can be closed now after #3591 . @fotisj go ahead, if you agree.
