### ISSUE TITLE
Setting gpus with hydra

### ISSUE THREAD

**Issue by BartekRoszak** [PyTorchLightning/pytorch-lightning#2137]
When setting a list of gpus with hydra, the list object is `omegaconf.listconfig.ListConfig` so it breaks the code here:

https://github.com/PyTorchLightning/pytorch-lightning/blob/8211256c46430e43e0c27e4f078c72085bb4ea34/pytorch_lightning/trainer/distrib_parts.py#L323

Should PL support setting gpus with `ListConfig`?

**Comment by pvnieo** [comment]
try use the latest version of pytorch-lightning:
```
pip install pytorch-lightning==0.8.0rc1
```

**Comment by BartekRoszak** [comment]
Nothings change. It breaks if you set a list of GPU idx.

**Comment by pvnieo** [comment]
What is the error?

**Comment by BartekRoszak** [comment]
```
pytorch_lightning.utilities.exceptions.MisconfigurationException: GPUs must be int, string or list of ints or None.
```

**Comment by pquadri** [comment]
I use this function to convert it correctly to list (or handle it if it's just an int): 
`def omegalist_to_list(omegalist):
    if type(omegalist)==int:
        return omegalist
    l = []
    for i in range(len(omegalist)):
        l.append(omegalist[i])
    return l`

**Comment by omry** [comment]
OmegaConf can be converted to list or dict with OmegaConf.to_container(cfg).

This does sounds like an issues that should be resolved in PL now that it's trying to support OmegaConf configs though.

**Comment by pquadri** [comment]
I literally looked it up and couldn’t find it 😂 thank you

**Comment by omry** [comment]
> I literally looked it up and couldn’t find it  thank you

It's in the [OmegaConf docs](https://omegaconf.readthedocs.io/en/1.4_branch/).
