### ISSUE TITLE
How to use metrics classes of 0.8.0

### ISSUE THREAD

**Issue by xiadingZ** [PyTorchLightning/pytorch-lightning#2142]
## ❓ Questions and Help

0.8.0 has new Metric class which can auto_reduce in ddp. But no examples of them.  Can you give some examples about how to use it?

**Comment by Borda** [comment]
@justusschock pls ^^

**Comment by MrinalJain17** [comment]
For sure, examples on how to use `TensorMetric` and `NumpyMetric` would be extremely helpful.

**Comment by justusschock** [comment]
Hi, these examples are currently added in #2184

**Comment by Borda** [comment]
done in #2184 and #2209
