### ISSUE TITLE
Very slow training on colab with TPU

### ISSUE THREAD

**Issue by ipyffor** [PyTorchLightning/pytorch-lightning#2148]
https://colab.research.google.com/drive/1OxoEcbNVCF5aj_9o0axTnKAh8p5I4Ikw?usp=sharing

**Comment by Borda** [comment]
@ipyffor mind share your PL version and sample notebook?

**Comment by ipyffor** [comment]
![image](https://user-images.githubusercontent.com/47955238/84398309-5ef9e880-ac32-11ea-9f35-7080f4bd325d.png)
After running the progress has not changed

**Comment by lezwon** [comment]
@ipyffor I cant access the colab file anymore. are you still facing the issue?

**Comment by rahulvigneswaran** [comment]
@ipyffor Not just on TPU. Even on GPU, it makes the entire browser unresponsive. It doesn't look like, it is code specific.

**Comment by iliemihai** [comment]
I am facing the same issue. Even if I run the code on 8 core TPU one iteration takes 35s, the same as running on 1 core TPU.

**Comment by Borda** [comment]
@iliemihai @rahulvigneswaran we had a bug there so multicore was not running in fact... shall be fixed now #2632 mind try actual master? also, mind send a PR with some parity speed testing?
