### ISSUE TITLE
The docker image tagged with Pytorch 1.5 and Python 3.8, has Pytorch 1.4 installed and is running Python 3.7

### ISSUE THREAD

**Issue by Shreeyak** [PyTorchLightning/pytorch-lightning#2167]
## 🐛 Bug

The docker image [tagged](https://hub.docker.com/layers/pytorchlightning/pytorch_lightning/0.8.0rc1-py3.8-torch1.5/images/sha256-9f34736c8ebc3ee3f07eea1079d7bd02b066773b208ae3feb3c4ed7752119c12?context=explore) with Pytorch 1.5, eg `0.8.0rc1-py3.8-torch1.5`, has torch 1.4 installed in it, as seen via pip list. Also, it is running Python 3.7 instead of Python 3.8, as the tag indicates.

### To Reproduce

1. Pull docker image: `docker pull pytorchlightning/pytorch_lightning:0.8.0rc1-py3.8-torch1.5`
2. Run the container: `docker run --rm -it --init pytorchlightning/pytorch_lightning:0.8.0rc1-py3.8-torch1.5`
3. Check version of python and pytorch:

```bash
containeruser@c5c87a61b71c:~$ python --version
Python 3.7.7

containeruser@71d3c9f95de7:~$ pip list | grep torch
pytorch-lightning         0.8.0rc1           
torch                     1.4.0
```

### Expected behavior

Since the tag of the docker image is `0.8.0rc1-py3.8-torch1.5`, I expect to see it running Python 3.8 and Pytorch 1.5.

### Environment

N/A

**Comment by fabrizzioalco** [comment]
Which OS are you running the project?

**Comment by Borda** [comment]
seems like this args are not executed correctly
https://github.com/PyTorchLightning/pytorch-lightning/blob/7c0a3f47455f6ff3c53fcbd9276f12ade9fc97ae/.github/workflows/docker-builds.yml#L30

**Comment by Borda** [comment]
it seems we had a typo and the image was build always with the default args, see 2374
