### ISSUE TITLE
Save the whole model object

### ISSUE THREAD

**Issue by p-christ** [PyTorchLightning/pytorch-lightning#2170]
Is there anyway of saving a whole model object with PyTorch lightning? 

e.g. I want something like this:

```
model = load("mypath")
prediction = model.predict(x) 

```

without needing access to the original Model class.  

I know how to load things from a checkpoint, but that requires having access to the model class. 

Is this possible? Any help would be much appreciated

**Comment by sambaths** [comment]
I think this is similar to #2145

**Comment by awaelchli** [comment]
@p-christ have a look at the linked issue. I think the answer to your question is there. Let us know.
