### ISSUE TITLE
torch.no_grad() during validation step

### ISSUE THREAD

**Issue by p-christ** [PyTorchLightning/pytorch-lightning#2171]
Does PyTorch lightning call torch.no_grad() under the hood during a validation step? 

The documentation here implies it does NOT but I think it definitely should... can someone confirm? 

https://pytorch-lightning.readthedocs.io/en/stable/new-project.html

![image](https://user-images.githubusercontent.com/26346243/84566735-67097380-ad6b-11ea-9234-9d9faf803be4.png)

**Comment by rohitgr7** [comment]
Yep it calls
https://github.com/PyTorchLightning/pytorch-lightning/blob/10c643f162318b7fe2b4a041a1f2975468492a92/pytorch_lightning/trainer/evaluation_loop.py#L246

**Comment by awaelchli** [comment]
@p-christ @rohitgr7 would you like to send a PR adding this to the code sample above?
