### ISSUE TITLE
How does the training step work with multiple optimizers?

### ISSUE THREAD

**Issue by nsidn98** [PyTorchLightning/pytorch-lightning#2172]
#### What is your question?
How does the training_step work exactly when there are multiple optimizers? I suppose that the optimizers update the corresponding networks one after another by converting the network associated with the other optimizer to eval mode and keeping the network associated with the current optimizer in training mode. Is this correct? If yes, how do we train networks where the loss function for each optimizer depends on both the network outputs.

How do I get this to work in PyTorch-Lightning:
```
for batch in dataloader:
    x,y = batch
    output1 = self.net1(x,self.net2(x))
    output2 = self.net2(x,self.net1(x))

    loss_net1 = some_loss_function(output1)
    loss_net2 = other_loss_function(output2)

    optimizer1.zero_grad()
    # want the loss to backprop through even net2
    loss_net1.backward(retain_graph=True) 
    optimizer1.step()

    optimizer2.zero_grad()
    loss_net2.backward()
    optimizer2.step()
```

**Comment by sambaths** [comment]
@nsidn98 Did you try this from PL examples?

https://colab.research.google.com/drive/1F_RNcHzTfFuQf-LeKvSlud6x7jXYkG31#scrollTo=TyYOdg8g77P0

This is for a GAN, but as you need it used 2 optimizers.

**Comment by nsidn98** [comment]
Yes, I used that example as a model for my code. But I think that net2() doesn't work in training mode when optimizer1 is getting updated and hence I am getting an error of `RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn` for the output obtained from net2().

**Comment by sambaths** [comment]
Can you share the code ?

**Comment by nsidn98** [comment]
You can find the code [here](https://gist.github.com/nsidn98/7f23200b316c0e71f0357cdfb21a2a78). Pardon me for putting all the code in one file. This was supposed to be a part of a bigger code base with imports from different files. This code runs independently. The main intention is to run RL algorithms and hence I am trying the different functionalities of Lightning on RL algorithms.

**Comment by sambaths** [comment]
@nsidn98 I haven't worked that much with RL algorithms, but nevertheless, I tried something.

I changed [Line 392](https://gist.github.com/nsidn98/7f23200b316c0e71f0357cdfb21a2a78#file-test-py-L392) and the code ran.

I changed this:
```python
self.value_loss = nn.MSELoss()(value, expected_value.detach())
```
to
```python
self.value_loss = nn.MSELoss()(value.requires_grad_(True), expected_value.detach())
```

Let me know if this is working like it is supposed to.

**Comment by nsidn98** [comment]
The code does seem to work now but the algorithm is not converging. I think there is a problem in some other part of the code. Closing the issue.
