### ISSUE TITLE
[hparams] support haparms and params in the init

### ISSUE THREAD

**Issue by ArthDh** [PyTorchLightning/pytorch-lightning#2204]
## 🐛 Bug

Gives TypeError while running on Google Colab TPU

### To Reproduce

https://colab.research.google.com/drive/1K5i4kXzZCvbq3jc8IHPD_bd_EdUSjFml?usp=sharing
running trainer.fit(model) on TPU

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-65-0e7bbefb5da4> in <module>()
     21                       )
     22 
---> 23   trainer.fit(model)

3 frames
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloader, val_dataloaders)
    872 
    873             # load weights if not interrupted
--> 874             self.load_spawn_weights(model)
    875             self.model = model
    876 

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_data_parallel.py in load_spawn_weights(self, original_model)
    415             # load weights saved in ddp
    416             path = os.path.join(self.default_root_dir, '__temp_weight_ddp_end.ckpt')
--> 417             loaded_model = original_model.__class__.load_from_checkpoint(path)
    418 
    419             # copy loaded weights to old model

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/lightning.py in load_from_checkpoint(cls, checkpoint_path, map_location, hparams_file, tags_csv, hparam_overrides, *args, **kwargs)
   1596             update_hparams(hparams, hparam_overrides)
   1597 
-> 1598         model = cls._load_model_state(checkpoint, *args, **kwargs)
   1599         return model
   1600 

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/lightning.py in _load_model_state(cls, checkpoint, *args, **kwargs)
   1630         if cls_takes_hparams:
   1631             kwargs.update(hparams=hparams)
-> 1632         model = cls(*args, **kwargs)
   1633         model.load_state_dict(checkpoint['state_dict'])
   1634 

TypeError: __init__() missing 3 required positional arguments: 'df_train', 'df_test', and 'fold'

### Expected behavior
I am trying implement 5-fold CV and expected it to proceed to the next fold normally.

### Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

* CUDA:
	- GPU:
	- available:         False
	- version:           None
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0a0+541814f
	- pytorch-lightning: 0.7.6
	- tensorboard:       2.2.2
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Wed Feb 19 05:26:34 PST 2020
### Additional context
Running on Google Colab TPU

**Comment by awaelchli** [comment]
PL saves hyperparameters to the checkpoint so that you can load it later, but that only works if you save them into self.hparams (in 0.7.6), and in your colab I can see the "fold" parameter is an argument but you don't save it into hparams. 

Two ways to solve this problem:
1. Update to master branch (or 0.8.0 in a few days) and then use the `save_hyperparameters` method in your init (this is the new way of dealing with hparams)
2. If you have to stay with 0.7.6, save the fold parameter into your hparams dict/Namespace and make that the only argument to your model.

**Comment by ArthDh** [comment]
I see, just out of curiosity would it be possible to pass in hparams and parameters together so something like this:

```
class LitMNIST(LightningModule):

    def __init__(self, hparams ,layer_1_dim=128, learning_rate=1e-2):
        super().__init__()
        # call this to save (layer_1_dim=128, learning_rate=1e-4) to the checkpoint
        self.hparams = hparams
        self.save_hyperparameters()

        # equivalent
        self.save_hyperparameters(['layer_1_dim', 'learning_rate'])

        # this now works
        self.hparams.layer_1_dim
```

Would this cause any sort of conflict since hparams will be saved by default and another explicit save is called on the hyperparameters?

**Comment by awaelchli** [comment]
> Would this cause any sort of conflict since hparams will be saved by default and another explicit save is called on the hyperparameters?

not sure, now that you mention it it looks weird. did you already  test it in the meantime?

**Comment by ArthDh** [comment]
Sorry, I haven't. I'll look into it later. 
However, the same syntax `model = LightModel(train_df, test_df, fold, hparams, emb_dims)` works on a GPU without any errors.

**Comment by williamFalcon** [comment]
0.8.0 you can pass in whatever you want. hparams + keyword args, objects etc :)
