### ISSUE TITLE
module 'pytorch_lightning' has no attribute 'metrics'

### ISSUE THREAD

**Issue by Nilanshrajput** [PyTorchLightning/pytorch-lightning#2207]
module 'pytorch_lightning' has no attribute 'metrics'. 

### To Reproduce

I am using master branch installation 
pip install git+https://github.com/PytorchLightning/pytorch-lightning.git@master --upgrade
pl.metrics.AUROC() throws error.

### Expected behavior

As I see metrics are present on master branch but they are not in init.

**Comment by justusschock** [comment]
Hi @Nilanshrajput , I verified your issue. I am not entirely sure why this happens, but as a workaround `from pytorch_lightning.metrics import AUROC` worked for me.

**Comment by Nilanshrajput** [comment]
Yeah I checked just now it's working i am baffled!

**Comment by szywise** [comment]
It is solved in #2506, where they imported metrics in \_\_init\_\_.py of pytorch_lightning.

**Comment by samadmoslehi** [comment]
I have a error in call module. please help me.......

AttributeError                            Traceback (most recent call last)
C:\Users\S28C7~1.MOS\AppData\Local\Temp\8/ipykernel_17348/3129809395.py in <module>
     10 from sklearn.metrics import roc_auc_score
     11 import copy
---> 12 engines = [Engine(config, copy.deepcopy(NAM_model)) for _ in range(config.n_models)]

C:\Users\S28C7~1.MOS\AppData\Local\Temp\8/ipykernel_17348/3129809395.py in <listcomp>(.0)
     10 from sklearn.metrics import roc_auc_score
     11 import copy
---> 12 engines = [Engine(config, copy.deepcopy(NAM_model)) for _ in range(config.n_models)]

C:\Program Files\Python39\lib\nam\engine\engine.py in __init__(self, config, model)
     22 
     23     self.metrics = pl.metrics.MeanAbsoluteError() if config.regression \
---> 24                     else pl.metrics.Accuracy()
     25 
     26     self.save_hyperparameters(vars(self.config))

AttributeError: module 'pytorch_lightning' has no attribute 'metrics'

**Comment by ananthsub** [comment]
@samadmoslehi Lightning metrics have been moved to torchmetrics: https://torchmetrics.readthedocs.io/

**Comment by telltao** [comment]
改为以下代码
import torchmetrics
metrics = torchmetrics.Accuracy()
