### ISSUE TITLE
[metrics] AUROC Metric cant handle batch with single class samples

### ISSUE THREAD

**Issue by Nilanshrajput** [PyTorchLightning/pytorch-lightning#2210]
## 🐛 Bug
During calculation of AUROC for a batch, if all samples of particular batch are of same class, it raises following error
```
`/usr/local/lib/python3.6/dist-packages/pytorch_lightning/metrics/functional/classification.py in roc(pred, target, sample_weight, pos_label)
    548 
    549     if fps[-1] <= 0:
--> 550         raise ValueError("No negative samples in targets, false positive value should be meaningless")
    551 
    552     fpr = fps / fps[-1]

ValueError: No negative samples in targets, false positive value should be meaningless`
```

This is tensor for labels : `tensor([1., 1., 1., 1., 1., 1.])` for this batch all samples were of same class,
 

The metric being used : pytorch_lightning.metrics.classification.AUROC

### Expected behavior

I don't know much about the calculation of auroc but it possible to batch have a single class only, and the metric should somehow handle this

**Comment by Borda** [comment]
In such case it shall be 1
@justusschock @SkafteNicki

**Comment by justusschock** [comment]
Well this is to be consistent with sklearn: 

```
>>> roc_auc_score([1, 1, 1, 1, 1], [0.9, 0.8, 0.5, 0.7])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/justusschock/Workspace/conda/envs/leg/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/Users/justusschock/Workspace/conda/envs/leg/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 393, in roc_auc_score
    sample_weight=sample_weight)
  File "/Users/justusschock/Workspace/conda/envs/leg/lib/python3.7/site-packages/sklearn/metrics/_base.py", line 77, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "/Users/justusschock/Workspace/conda/envs/leg/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 223, in _binary_roc_auc_score
    raise ValueError("Only one class present in y_true. ROC AUC score "
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
```

And I also think it should be handled that way

**Comment by Nilanshrajput** [comment]
@justusschock we calculate metrics after each validation step, and we cannot insure them to be of a single class, this way training would never complete due to possible error in every step. I think sklearn metric is designed keeping in mind to calculate auroc over a complete dataset not a batch.

**Comment by justusschock** [comment]
Yes, and we basically do the same. 

This implementation just provides the implementation. In the next version, we will provide an automated evaluation plan that caches multiple batches. In the meantime you can return them and aggregate them in `at_epoch_end` for metric computation.

I designed it that way on purpose, since an AUROC (or a ROC in general) is not descriptive in a single batch

**Comment by Nilanshrajput** [comment]
Oh, that sounds right, currently, i just increased the validation batch size very much to decrease such probability of such cases:D, but I will add it to val epoch end, Thanks @justusschock

**Comment by shijianjian** [comment]
What I am doing now is using the following code for aggregation:
```python
class Metrics(nn.Module):
    def __init__(self, num_classes):
        super().__init__()
        self.trues = []
        self.preds = []
        self.metrics = [
            M.Precision(num_classes),
            M.Recall(num_classes),
            M.AUROC(),
            M.Accuracy(),
            # M.AveragePrecision(pos_label=0),
            # M.AveragePrecision(pos_label=1),
        ]

    def forward(self, y_pred, y_true, prefix='train'):
        self.trues.append(y_true.cpu())
        self.preds.append(y_pred.detach().cpu())

        trues = torch.cat(self.trues, dim=0)
        preds = torch.cat(self.preds, dim=0)

        results = {}
        if len(trues.unique()) != 1:
            preds = nn.functional.softmax(preds, dim=-1)
            for metric in self.metrics:
                results.update({f"{prefix}_{metric.name}": metric(preds.cpu(), trues.cpu())})
        return results

    def reset(self):
        self.trues = []
        self.preds = []
```

**Comment by BeyondTheProof** [comment]
Can you think of a good workaround for the multiclass scenario? I'm running into an issue where there are classes that are very rare. 

In the case of 0 observations, I feel the `average='weighted'` should work, since the contribution to the final AUROC should be 0 regardless. One can think of other scenarios where there are a very high number of classes, some of which will happen to not be seen in some dataset.

**Comment by Troublem1** [comment]
Hi, please has this been fixed?
run into the same error while working with a binary classification problem
_No positive samples in targets, true positive value should be meaningless_

**Comment by SkafteNicki** [comment]
@Troublem1 if you do not have any positive samples then the score is meaningless. Are you trying to evaluate this per batch?

**Comment by Troublem1** [comment]
Yes i was.. should i calculate it per epoch instead?

**Comment by sachinruk** [comment]
For anyone else looking this up, here's how I did it inside a `LightningModule`:

```python
def __init__(self, ...):
        self.valid_auc = torchmetrics.AUROC(pos_label=1)

def validation_step(self, batch: Tuple[torch.FloatTensor, torch.LongTensor], *args) -> None:
        self.valid_auc.update(logits.cpu().detach(), y.cpu().detach())
        self.log("validation_auc", self.valid_auc, on_step=False, on_epoch=True, prog_bar=True)
```

**Comment by Borda** [comment]
a solution I used in 3D medical is to compute the metric over epoch instead of single batch
https://github.com/Borda/kaggle_brain-tumor-3D/blob/58185ed24f58f06c2675728a7743a46dacce5af2/kaggle_brain3d/models.py#L52

**Comment by Troublem1** [comment]
@Borda thanks.. i am current using PL lightning for that competition.. i got a bit scared when my model starting reaching nans.. seeing as yours did as well.. its a bit surprising..

thanks for sharing the AUROC solutions...

**Comment by hunhoon21** [comment]
@Borda thanks for sharing the AUROC solution!

I'm little concerned about using `try / except` statement.
how about this one?
```python
def __init__(self, ...):
    ...
    self.auroc = torchmetrics.AUROC(..., compute_on_step)
...

def validation_step(self, batch, _):
    ...
    self.auroc(y_hat, y)
    self.log("val_auroc", self.auroc.compute(), on_step=False, on_epoch=True)
```

please tell me if there is something wrong
