### ISSUE TITLE
ModelSummary fails on the "generative_adversarial_net" example

### ISSUE THREAD

**Issue by johngull** [PyTorchLightning/pytorch-lightning#2211]
## 🐛 Bug

When you run this example: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/domain_templates/generative_adversarial_net.py
you got error: `RuntimeError: size mismatch, m1: [56 x 28], m2: [100 x 128]`

My understanding by quick viewing of callstack:
Seems that problem in ModelSummary, which unfold 2 presented nn.Module to the same list of mods. And then it tries to push result of one module to the input of another layer, but this layers are not part of the same models.

### To Reproduce

Just run example https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/domain_templates/generative_adversarial_net.py

### Environment

Python 3.7
PyTorch 1.3.1
pytorch-lightning 0.7.6

**Comment by awaelchli** [comment]
I fixed this recently, see #1773. Try the master branch (or the 0.8.0 release in a few days).

**Comment by awaelchli** [comment]
I'll close this unless you find another issue.
