### ISSUE TITLE
Best practices when Module __init__ contains Dataset?

### ISSUE THREAD

**Issue by turian** [PyTorchLightning/pytorch-lightning#2232]
#### What is your question?

What are best practices when the Module __init__ contains the Dataset? This is useful when the input and output sizes are derived from the data set, and not hparams.

However, `Module.load_from_checkpoint(...)` fails with the following error:

```
TypeError: __init__() missing 1 required positional argument: 'patchDistanceDataset'
```

#### What have you tried?

There could be a module method to load the dataset. However, this will not help __init__ to build the network because it will be unaware of the input and output sizes.

#### What's your environment?

 - OS: OSX
 - Packaging pip3
 - Version 0.7.6

**Comment by williamFalcon** [comment]
```
Module.load_from_checkpoint(PATH, your_dataset=Dataset)
```
