### ISSUE TITLE
How to programmatically determine the checkpoint directory?

### ISSUE THREAD

**Issue by turian** [PyTorchLightning/pytorch-lightning#2233]
#### What is your question?

How do you programmatically determine the checkpoint directory?

pytorch lighting has automatic support for checkpoints and those checkpoints are stored in `lightning_logs/VERSION/checkpoints/epoch=BEST.ckpt`. However, I don't know how to programmatically determine what the VERSION or directory is, to copy the checkpoint to save it for later in another directory.

Another reason I would like to do this is to store auxiliary training data (e.g. Dataset) with the checkpoint, and I don't know how to do this based upon the docs.

#### What have you tried?

I have tried manually finding the directory in lightning_logs.

#### What's your environment?

 - OS: OSX
 - Packaging pip3
 - Version 0.7.6

**Comment by turian** [comment]
I see `trainer.ckpt_path` and `trainer.weights_save_path`, which is preferred to use?

**Comment by williamFalcon** [comment]
https://pytorch-lightning.readthedocs.io/en/stable/trainer.html#checkpoint-callback

**Comment by Wheest** [comment]
I had a similar issue, and was not able to find a solution looking at the docs.

I can see that each time I run training, my model checkpoint is saved in a new directory, called `version_{i}`.

E.g.:

```
$ ls lighting_logs
version_0/  version_1/  version_2/
```

The original question is how to programatically get this version number.

Looking at [this post](https://forums.pytorchlightning.ai/t/how-to-get-the-checkpoint-path/327/7) on the PyTorch Lighting forums gives more insights.

You can programmatically get the version number in this way: `trainer.logger.version`
