### ISSUE TITLE
Model.load_from_checkpoint tries to open file path as URL and fail

### ISSUE THREAD

**Issue by Molaire** [PyTorchLightning/pytorch-lightning#2243]
## 🐛 Bug
 load_from_checkpoint tries to classify if the input is a file path or an URL and detects the hard drive letter as a scheme and then classify wrongly the input because of this.
urllib.error.URLError: \<urlopen error unknown url type: d\>

My input:
D:\Prog\Projects\AceriNet\research_seed\checkpoints\acerinet\bnacerinet0_target=OVA_OK_penalized=None_loss_fn=ce_normalized=True_balanced=FalseFalse_seed=42_val_loss=0.374_val_auroc=0.9041_v0.ckpt

### To Reproduce

Use any path with a hard drive letter at the start (windows formatting) for pl.LightningModule().load_from_checkpoint(path)

**Comment by yukw777** [comment]
Ah I didn’t think about Windows when I implemented this. I’ll take a look if there’s a better.

**Comment by Molaire** [comment]
We could try to detect if the file exists with if os.path.isfile() or Path(path_of_chkpt).is_file() instead of checking for scheme

**Comment by awaelchli** [comment]
Also came across this when I was running tests on windows. I wonder why it was not showing up in CI.

**Comment by Molaire** [comment]
The only reason I see is that tmpdir is a relative path without prefix at the start, dodging the problem. It should be fixed by my PR, I hope.

**Comment by awaelchli** [comment]
Thanks @Molaire. I can verify the tests now pass locally on windows.

**Comment by airium** [comment]
I am afraid the PR #2244 introduced a new bug, as now `Path(path_or_url).is_file()` will block every URL by raising `OSError`. I will submit a new PR to better fix it.
