### ISSUE TITLE
Full batch training

### ISSUE THREAD

**Issue by turian** [PyTorchLightning/pytorch-lightning#2263]
## ❓ Questions and Help

For smaller datasets, it makes sense to do full batch training, not minibatch. How do you implement fullbatch training in pytorch lightning, given that train and validation might be different sizes?

**Comment by williamFalcon** [comment]
what do you mean by full batch training?

This is not lightning specific though... this is pytorch

```
Dataloader(..., batch_size=1)
Dataloader(..., batch_size=32)
Dataloader(..., batch_size=len(dataset))
```

**Comment by turian** [comment]
Thank you, that is perfect.
