### ISSUE TITLE
Improve Exception Handling

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#2266]
## 🚀 Code Quality Improvement

I came across this a few times already:
```python
try:
   # something
except Exception:
   # something
```
It is the worst possible way to handle Exceptions. It is better to catch the specific exception or at least log a message. 

### Alternatives

None. Sooner or later someone has to deal with this anyway :)

**Comment by Borda** [comment]
@awaelchli so what do you propose to have more exact Exceptions like `ImportError`?

**Comment by awaelchli** [comment]
Yes exactly, the specific exception we try to catch. 
Also, sometimes we don't need exception handling at all:
```python
try: 
    x = myobject.attribute
except Exception
    x = 0
```
can be replaced with
`x = getattr(myobject, "attribute", 0)`

**Comment by awaelchli** [comment]
Another code smell we frequently see (in many places in the code):

```python
try:
    from some_package import some_module
except ImportError:
    SOMEPACKAGE_AVAILABLE = False
else:
    SOMEPACKAGE_AVAILABLE = True
```

Better:
```python
import importlib
SOMEPACKAGE_AVAILABLE = importlib.util.find_spec("some_package") is not None
```

**Comment by Borda** [comment]
About the import error, I remember that thare is something twisted about python version and avalanche exceptions, I guess that py3.6 doesn't have the one suggest (need to check)

Also is there a simple way how to import jist a function from a package that you are not sure if it is installed?

**Comment by awaelchli** [comment]
I think the simplest is this:
```python
if importlib.util.find_spec("some_package") is not None:
    from some_package import my_function

```
because when we import the function in Python it always has to import the whole package anyway.
