### ISSUE TITLE
Exception when trainer.gpus are passed as a list through hydra (omegaconf)

### ISSUE THREAD

**Issue by sudarshan85** [PyTorchLightning/pytorch-lightning#2270]
## 🐛 Bug
When we pass the `gpus` flag for `Trainer` using `hydra` (which in turn uses `Omegaconf`) it is passed as `omegaconf.listconfig.ListConfig`. However, internally `Trainer` only checks for `int`, `str`, `list`. This throws an exception. 

#### Code sample
```
#!/usr/bin/env python

import warnings
warnings.filterwarnings("ignore")

import os

import torch
from torch import nn
from torch.utils.data import DataLoader, random_split
from torchvision.datasets import MNIST
from torchvision import datasets, transforms
from torch.nn import functional as F
from torch import optim

from pytorch_lightning.core.lightning import LightningModule
from pytorch_lightning import Trainer
from omegaconf import OmegaConf

class LitMNIST(LightningModule):
  def __init__(self):
      super().__init__()
      self.layer_1 = torch.nn.Linear(28 * 28, 128)
      self.layer_2 = torch.nn.Linear(128, 256)
      self.layer_3 = torch.nn.Linear(256, 10)  
      
  def prepare_data(self):
    transform=transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))])
    # transform
    mnist_train = MNIST(os.getcwd(), train=True, download=False, transform=transforms.ToTensor())
    
    # train/val split
    mnist_train, mnist_val = random_split(mnist_train, [55000, 5000])

    # assign to use in dataloaders
    self.train_dataset = mnist_train
    self.val_dataset = mnist_val
    
  def forward(self, x):
      batch_size, channels, width, height = x.size()
      x = x.view(batch_size, -1)
      x = self.layer_1(x)
      x = torch.relu(x)
      x = self.layer_2(x)
      x = torch.relu(x)
      x = self.layer_3(x)
      x = torch.log_softmax(x, dim=1)
      return x    
    
  def training_step(self, batch, batch_idx):
      x, y = batch
      logits = self(x)
      loss = F.nll_loss(logits, y)

      # add logging
      logs = {'loss': loss}
      return {'loss': loss, 'log': logs}    
    
  def validation_step(self, batch, batch_idx):
    x, y = batch
    logits = self(x)
    loss = F.nll_loss(logits, y)
    return {'val_loss': loss}    

  def train_dataloader(self):
    return DataLoader(self.train_dataset, batch_size=64)
  
  def val_dataloader(self):
    return DataLoader(self.val_dataset, batch_size=64) 
  
  def configure_optimizers(self):
    return optim.Adam(self.parameters(), lr=1e-3)    

if __name__=='__main__':
#   trainer_params = OmegaConf.create({'max_epochs': 1, 'overfit_pct': 0.01, 'gpus': 1}) # this works
#   trainer_params = OmegaConf.create({'max_epochs': 1, 'overfit_pct': 0.01, 'gpus': [1]}) # this throws an exception about gpus not being int, str, or list(int)
  model = LitMNIST()
  trainer = Trainer(**trainer_params)
  trainer.fit(model)
```

**Comment by Borda** [comment]
well it is OmegaConf issue
```
trainer_params = OmegaConf.create({'max_epochs': 1, 'overfit_pct': 0.01, 'gpus': [1]})
type(trainer_params.gpus)
Out[1]: omegaconf.listconfig.ListConfig
isinstance(trainer_params.gpus, list)
Out[2]: False
```

**Comment by Borda** [comment]
in fact, the solution shall be that `ListConfig` is inherited from `list`, so no change needed for PL
@omry ^^ @williamFalcon 
cc: @PyTorchLightning/core-contributors

**Comment by omry** [comment]
@Borda : 

Inheriting from primitive containers is not recommended.
Python is making a ton of assumptions about list and dict that would break if the objects are not actually what it expects.
Here is a [post](https://treyhunner.com/2019/04/why-you-shouldnt-inherit-from-list-and-dict-in-python/) by someone talking about some of the problems.

As of OmegaConf 2.0 ListConfig is [implementing MutableSequence](https://github.com/omry/omegaconf/blob/master/omegaconf/listconfig.py#L38). and DictConfig is [implementing MutableMapping](https://github.com/omry/omegaconf/blob/master/omegaconf/dictconfig.py#L47) to make it easier to identify them in a way that works for lists and dicts as well.

Additionally:
OmegaConf is very low level, making such changes there is a huge deal. This kind of change will require a major version. (in ot happening in the next 6 months, and probably not happening at all for the reasons I outlined above).

**Comment by omry** [comment]
```python
In [1]: from omegaconf import OmegaConf
In [2]: trainer_params = OmegaConf.create({'max_epochs': 1, 'overfit_pct': 0.01, 'gpus': [1]})
In [3]: isinstance(trainer_params.gpus, list)
Out[3]: False
In [4]: from typing import MutableSequence
In [5]: isinstance(trainer_params.gpus, MutableSequence)
Out[5]: True
In [6]: isinstance([1,2,3], MutableSequence)
Out[6]: True
```

Please note that this is only working with OmegaConf 2.0, which means this is only working with Hydra 1.0.0rc1 or newer (which is still a release candidate, most Hydra users are still using the stable version).
However, it looks like the PL support for Hydra is already assuming 1.0 so we might as well continue to assume it.

**Comment by Borda** [comment]
```
In[9]: isinstance(trainer_params.gpus, List)
Out[9]: False
```

**Comment by williamFalcon** [comment]
@omry we want to support this but this is now scattering a lot of code everywhere for special cases.

Unfortunately, I think this is as much effort as we can put into this at this time. Please support Lists in Omegaconf and i would also suggest to supprot --args

in the meantime @sudarshan85, i'm sorry but it looks like this is incompatible with lightning at the moment. Please use a regular argparse or maybe pass in a string for the GPUs instead of list.

**Comment by omry** [comment]
I looked at implementing typing,List at some point while working on OmegaConf 2.0 and decided against it.
I just tested again and it's causing issues around copy and deepcopy , and around pickling.
I can revisit it for the next major version but I can't guarantee that I will change it.
Even if I do end up making this change - it may be as long as 6 months before it's available to Hydra users.

**Comment by sudarshan85** [comment]
@williamFalcon @omry 
No worries. The only problem is if I pass in an `int` enclosed quotes to force a string such as '1' on the command line using Hydra, it automatically converts it to an int and does not read it as a string.  Is there way to force hydra to get a string out of it?

**Comment by omry** [comment]
@sudarshan85 
Join the Hydra chat if you have questions about Hydra.

**Comment by Borda** [comment]
@omry @sudarshan85 I have changed the checking `list` to `MutableSequence` in #2273 which shall resolve this issue, pls have look...

**Comment by dreaquil** [comment]
For Hydra, using a parameter conversion strategy resolved my issue.

https://hydra.cc/docs/next/advanced/instantiate_objects/overview/#parameter-conversion-strategies
