### ISSUE TITLE
optimizer got an empty parameter list

### ISSUE THREAD

**Issue by soulhi-vz** [PyTorchLightning/pytorch-lightning#2282]
Hi,
Got the following error:
ValueError: optimizer got an empty parameter list with both options below:

def configure_optimizers(self):
        # option1 optimizer = torch.optim.Adam(self.parameters(), lr=self.hparams.lr)
        # option 2
        optimizer = torch.optim.Adam(params = list(self.parameters()), lr=self.hparams.lr)
        return optimizer

class Autoencoder(pl.LightningModule):
    
    def __init__(self, hparams: argparse.Namespace):
        super(Autoencoder,self).__init__() 
        self.hparams = hparams
           
        self_layer_e_1 = nn.Conv1d(hparams.in_channels, hparams.out_channels, hparams.kernel_size)
        self_layer_e_2 = nn.Conv1d(hparams.out_channels,hparams.in_channels,hparams.kernel_size)
        self_layer_d_1 = nn.ConvTranspose1d(hparams.in_channels,hparams.out_channels,hparams.kernel_size)
        self_layer_d_2 = nn.ConvTranspose1d(hparams.out_channels,hparams.in_channels,hparams.kernel_size)
        
    
    def forward(self,x):
        x = self_layer_e_1(x)
        x = nn.ReLu(x)
        x = self_layer_e_2(x)
        encoded = nn.ReLU(x)
        x = self_layer_d_1(encoded)
        x = nn.ReLU(x)
        decoded = self_layer_d_2(x)
        decoded = self.decoder(encoded)
        return self.decoded, self.encoded
    
    
    def training_step(self, batch, batch_idx):
        x, _ = batch
        decoded, encoded = self.forward(x)
        loss = MSE(x, decoded)
        return loss
    
    def validation_step(self, batch, batch_idx):
        return self._shared_eval(batch, batch_idx, 'val')

    def test_step(self, batch, batch_idx):
        return self._shared_eval(batch, batch_idx, 'test')
        
    def _shared_eval(self, batch, batch_idx, prefix):
        x, y = batch
        decoded, encoded = self.forward(x)
        loss = F.nll_loss(x, decoded)
        return {f'{prefix}_loss': loss}
    
    def train_dataloader(self):
        return DataLoader(self.CarrierDataset, batch_size=self.hparams.batch_size)

    def val_dataloader(self):
        return DataLoader(self.CarrierDataset, batch_size=hparams.batch_size)

    def test_dataloader(self):
        return DataLoader(self,CarrierDataset, batch_size=hparams.batch_size)

    def configure_optimizers(self):
        #optimizer = torch.optim.Adam(self.parameters(), lr=self.hparams.lr)
        optimizer = torch.optim.Adam(params = list(self.parameters()), lr=self.hparams.lr)
        return optimizer

**Comment by versatran01** [comment]
You need to use self.xxx instead of self_xxx for nn.Module to register them as parameters

**Comment by soulhi-vz** [comment]
It works now. Thanks for the catch !!!!
