### ISSUE TITLE
example_input_array dtype

### ISSUE THREAD

**Issue by hjalmarlucius** [PyTorchLightning/pytorch-lightning#2286]
Currently assumed that example_input_array dtype to be equal to model dtype. This is not necessarily correct - e.g. if input is a vector of INT.

https://github.com/PyTorchLightning/pytorch-lightning/blob/7dc58bd286b1e81ca4d293f05bddff5e93361020/pytorch_lightning/core/memory.py#L192

**Comment by awaelchli** [comment]
Hi, I don't understand. Does it throw an error or does it display nothing?
I don't think we can very accurately define the "input shape" for anything other than tensors. 
For this reason we exclude things like dicts from the overview, because it is not very practical to visualize this in a table.

**Comment by hjalmarlucius** [comment]
Hi, currently the model is run with `input_` as an input. If the model expects a tensor of INTs then it will crash if floats come. I encountered this issue when pretraining an ALBERT-like model. This receives word embeddings as inputs, which have to be integers as they're going into a `nn.Embedding`

**Comment by awaelchli** [comment]
okay I see, so we should not change the dtype as given by example_input_array. 
I can't recall why I added this conversion, maybe  it was because of amp and the half conversions. I'll have a closer look, thanks for bringing it up.

**Comment by awaelchli** [comment]
as a workaround until it is fixed, cast your input to int before feeding to the embedding layer, or don't use the example_input_array.
