### ISSUE TITLE
Validation turns on midway during training instead of epoch end - Progress Bar 

### ISSUE THREAD

**Issue by sid-sundrani** [PyTorchLightning/pytorch-lightning#2291]
Validation is starting before epoch end. Validation starts during the first training epoch. 
I've attached a snippet of the command prompt
![image](https://user-images.githubusercontent.com/19412334/85184392-8c532180-b244-11ea-8ac4-24d52bc4cce1.png)

EDIT: Epoch progress bar includes validation progress. Please close the issue

**Comment by awaelchli** [comment]
Exactly, the first bar contains both the count of training and validation data.
