### ISSUE TITLE
Support HTCondor in addition to SLURM

### ISSUE THREAD

**Issue by djordjemiladinovic** [PyTorchLightning/pytorch-lightning#2302]
## 🐛 Bug

New DDP implementation is still not working for me. I am in the situation where I need to send a single job i.e. run a single executable due to the batch system we have on our university GPU cluster. Therefore, rather than calling the training script multiple times with different env variables as suggested in the documentation, my solution is to create a super script (see below) which will then call the main training script multiple times each time forking a new subprocess. However, the training never seem to commence in the end.

### Code sample

1. My super script looks as follows

```
import sys
import subprocess
import time
import os
import random

def main():

    # fetch arguments
    args = sys.argv[1:]

    # Extract the number of gpus from argument list
    gpus = 0
    for idx in range(len(args)):
        if args[idx] == "--gpus":
            gpus = int(args[idx+1])

    # random master port 0
    master_port_0 = random.randint(10000, 19000)

    # create a subprocess for each gpu
    for gpu in range(gpus):
        my_env = os.environ.copy()
        my_env["MASTER_ADDR"] = "localhost"
        my_env["MASTER_PORT"] = str(master_port_0+gpu)
        my_env["WORLD_SIZE"] = str(gpus)
        my_env["NODE_RANK"] = str(gpu)
        my_env["LOCAL_RANK"] = "0"
        subprocess.Popen(["/usr/bin/python3", "train.py"] + args, env=my_env)
        print("Sleep for 10 seconds")
        time.sleep(10)

    print("Sleep for another 60 seconds")
    time.sleep(60)
```

2. The output that I get when I run for 2 GPUs is:

Allocating cuda
Model signature
Creating trainer
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
Allocating cuda
Model signature
Creating trainer
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/2

### Expected behavior

I would expect some output: "All DDP processes registered.." but I get nothing, it seems that my subprocesses get stuck somewhere.

### Environment

 - PyTorch Version (e.g., 1.0): 1.5.1+cu101
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip3
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1

**Comment by williamFalcon** [comment]
ummm...not sure if our ddp will work with this... 
if your cluster is managed by SLURM, you should submit your script that way.
Lightning supports this out of the box
https://pytorch-lightning.readthedocs.io/en/stable/slurm.html

**Comment by djordjemiladinovic** [comment]
Unfortunately, this one is managed by [https://research.cs.wisc.edu/htcondor/](htcondor) Do you think it would be easy to re-design interface so you can call one script only as described above? I could have a look at this myself.

**Comment by williamFalcon** [comment]
just set the environment flags and call the script without popen and set ddp backend.  ddp does something very similar, so you are just duplicating work

**Comment by williamFalcon** [comment]
if you want, you can submit a PR to support condor. just need to figure out what the matching flags are vs SLURM

**Comment by djordjemiladinovic** [comment]
So regarding the approach above: I was expecting something similar was implemented in the library already, that is why I am surprised my code wouldn't work. Isn't Popen more appropriate than call since it's non-blocking ? ..that is, you want to run several threads in parallel. The "backend" is set to "ddp" in the main script.

Yes, I could submit PR for condor, but it still feels like there could be a more general and simpler solution, other collaborator unis use other clusters e.g. IBMs. It would be a pity not to enable people to use this amazing library on large clusters of big institutes and unis.
