### ISSUE TITLE
Loading a model checkpoint that is trained on TPU using a GPU

### ISSUE THREAD

**Issue by ArthDh** [PyTorchLightning/pytorch-lightning#2303]
#### What is your question?
Is it possible to load a model that is trained on a TPU saved using ModelCheckpoint on a GPU for inference?

#### Code

```
        model = LightModel(hparams)
        trainer = pl.Trainer(resume_from_checkpoint=str(ckpt), gpus=1)
        trainer.test(model)
```

#### What have you tried?## ❓ Questions and Help

Tried to normally load the weights as with a GPU but throws an error.

#### What's your environment?
Kaggle GPU
torchvision==0.6.0a0+82fd1c8
torch==1.5.0
pytorch-lightning-0.8.1

**Comment by Laksh1997** [comment]
Have you tried to load on CPU?

**Comment by Geeks-Sid** [comment]
Can you put the error?

**Comment by ArthDh** [comment]
`RuntimeError: Could not run 'aten::empty_strided' with arguments from the 'XLATensorId' backend. 'aten::empty_strided' is only available for these backends: [CPUTensorId, CUDATensorId, BackendSelect, VariableTensorId].`

**Comment by ArthDh** [comment]
@Laksh1997 I tried, it still gives the RuntimeError

**Comment by Geeks-Sid** [comment]
This looks like a PyTorch Issue and [this](https://github.com/pytorch/pytorch/issues/33152) looks something similar. Your code looks fine, someone senior should take a look I guess. @Borda
