### ISSUE TITLE
Using s3 backed for Mlflow logger fails

### ISSUE THREAD

**Issue by kreid415** [PyTorchLightning/pytorch-lightning#2318]
## 🐛 Bug
MLflow logger support for s3 URI's. It is already supported by MLflow 1.9.0, https://www.mlflow.org/docs/latest/tracking.html#amazon-s3, but passing an s3 URI to the logger's tracking_uri parameter fails.

### To Reproduce

1. init a lighting_module and a trainer.
2. init a mlflow_logger with an s3 URI set for 'tracking_uri'.
3. run the trainer

`mlflow.tracking.registry.UnsupportedModelRegistryStoreURIException:  Model registry functionality is unavailable; got unsupported URI 's3://somebucket/' for model registry data storage. Supported URI schemes are: ['', 'file', 'databricks', 'http', 'https', 'postgresql', 'mysql', 'sqlite', 'mssql']. See https://www.mlflow.org/docs/latest/tracking.html#storage for how to run an MLflow server against one of the supported backend storage locations.`

#### Code sample
`
model = somedummymodel() 
mlflow_logger = MLFlowLogger(
        experiment_name='some_name',
        tracking_uri="s3://somebucket/"
    )
trainer = LT(logger=mlflow_logger)
trainer.fit(model, somedata, somedata_val)
`
### Expected behavior

It should post logs into the bucket using the mlfow tracking server feature.

### Environment

* CUDA:
        - GPU:
                - GeForce RTX 2080 Ti
                - GeForce RTX 2080 Ti
        - available:         True
        - version:           10.0.130
* Packages:
        - numpy:             1.17.0
        - pyTorch_debug:     False
        - pyTorch_version:   1.3.1
        - pytorch-lightning: 0.8.1
        - tensorboard:       2.2.2
        - tqdm:              4.46.1
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - 
        - processor:         x86_64
        - python:            3.7.6
        - version:           #53~18.04.1-Ubuntu SMP Thu Jun 4 14:58:26 UTC 2020

**Comment by Borda** [comment]
@RudrakshTuwani thanks for your help
@kreid415 feel free to reopen if needed :]
