### ISSUE TITLE
Community Examples : Pytorch lightning + MS NNI

### ISSUE THREAD

**Issue by davinnovation** [PyTorchLightning/pytorch-lightning#2329]
### Motivation

Hi. Pytorch lightning team! I really loving to use PL in my recent projects, and I wrote some example for using omegaconf + Pytorch lightning + Microsoft NNI 

https://github.com/davinnovation/pytorch-boilerplate

I would appreciate if it could be added as part of community examples.

### Pitch

This Repo guides to use Pytorch lightning project under docker container.

**Comment by Borda** [comment]
Nice, mind send a PR? :rabbit: 
cc: @edenlightning

**Comment by davinnovation** [comment]
Sure!

**Comment by davinnovation** [comment]
merged. closing this issue
