### ISSUE TITLE
How to suppress messages from Trainer class?

### ISSUE THREAD

**Issue by teboozas** [PyTorchLightning/pytorch-lightning#2332]
Hi,

How can I suppress messages from Trainer class
alarming GPU and TPU resources? like

![image](https://user-images.githubusercontent.com/40536602/85429353-931dc380-b5b9-11ea-8ffc-2c8c460b4141.png)

**Comment by awaelchli** [comment]
You could increase the logging level from INFO to WARNING or ERROR, for example like this. 

```python
import logging
logging.getLogger("lightning").setLevel(logging.ERROR)
```
Put this somewhere at the beginning of your script or in `__init__.py`.

**Comment by williamFalcon** [comment]
@awaelchli can we add this to docs?

**Comment by mykappa** [comment]
Neither 

```Python
import logging
logging.getLogger("lightning").setLevel(logging.ERROR)
```

nor 

```Python
import logging

# configure logging at the root level of Lightning
logging.getLogger("lightning.pytorch").setLevel(logging.ERROR)
```
as suggested in the [documentation ](https://lightning.ai/docs/pytorch/stable/common/console_logs.html) does suppress theses outputs for me in v.2.0.2

**Comment by mykappa** [comment]
Based on the stackoverflow answer https://stackoverflow.com/a/75592068/11603726, the following seems to work:

Either assign the following loggers to the `logging.NullHandler()`:
```Python
import logging
logging.getLogger("pytorch_lightning.utilities.rank_zero").addHandler(logging.NullHandler())
logging.getLogger("pytorch_lightning.accelerators.cuda").addHandler(logging.NullHandler())
```

or set their log level to `WARNING`:

```Python
import logging
logging.getLogger("pytorch_lightning.utilities.rank_zero").setLevel(logging.WARNING)
logging.getLogger("pytorch_lightning.accelerators.cuda").setLevel(logging.WARNING)
```
