### ISSUE TITLE
max_steps does not work if resume_from_checkpoint is specified

### ISSUE THREAD

**Issue by desmondchchan** [PyTorchLightning/pytorch-lightning#2344]
## 🐛 Bug

max_steps does not work if resume_from_checkpoint is specified

### To Reproduce

1. Specify max_steps
2. Specify resume_from_checkpoint

#### Code sample

```python
import os

import torch
from torch.nn import functional as F
from torch.utils.data import DataLoader
from torchvision.datasets import MNIST
from torchvision import transforms
import pytorch_lightning as pl

class MNISTModel(pl.LightningModule):

    def __init__(self):
        super(MNISTModel, self).__init__()
        self.l1 = torch.nn.Linear(28 * 28, 10)

    def forward(self, x):
        return torch.relu(self.l1(x.view(x.size(0), -1)))

    def training_step(self, batch, batch_nb):
        x, y = batch
        loss = F.cross_entropy(self(x), y)
        tensorboard_logs = {'train_loss': loss}
        return {'loss': loss, 'log': tensorboard_logs}

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=0.02)

train_loader = DataLoader(MNIST(os.getcwd(), train=True, download=True, transform=transforms.ToTensor()), batch_size=32)

mnist_model = MNISTModel()
trainer = pl.Trainer(gpus=1, max_steps=123, resume_from_checkpoint="./lightning_logs/version_0/checkpoints/epoch=2.ckpt")    
trainer.fit(mnist_model, train_loader)  
```

### Expected behavior
Training stops at max_steps

### Environment
* CUDA:
        - GPU:
                - Tesla T4
        - available:         True
        - version:           10.2
* Packages:
        - numpy:             1.18.5
        - pyTorch_debug:     False
        - pyTorch_version:   1.6.0.dev20200622
        - pytorch-lightning: 0.8.0
        - tensorboard:       1.15.0
        - tqdm:              4.46.1
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                -
        - processor:         x86_64
        - python:            3.7.7
        - version:           #28~18.04.1-Ubuntu SMP Sat Jun 6 00:0

**Comment by desmondchchan** [comment]
I think the global_step is restored from the checkpoint. The max_steps flag only works when max_steps > global_step of the model. If max_steps < global_step, the training will go on until max_epoch.

Also, is there an option to train the model for a specified number of steps?

**Comment by williamFalcon** [comment]
yeah this is correct. You'd now have to set max_step to something much higher since it's max_GLOBAL_step
