### ISSUE TITLE
save_hyperparameters incorrect documentation

### ISSUE THREAD

**Issue by david-waterworth** [PyTorchLightning/pytorch-lightning#2345]
## 📚 Documentation

The documentation has examples 

`self.save_hyperparameters(['layer_1_dim', 'learning_rate'])`

This fails as due to type list not being supported as a hyperparameter. However, looking at the source for `save_hyperparameters` it appears that the correct usage is

`self.save_hyperparameters('layer_1_dim', 'learning_rate')`

As an aside I also do have a list as a hyperparameter for one model - it's a time convolutional network with stacked temporal convolutions, I was originally passing in the number of filters per layer as a list.

**Comment by Borda** [comment]
true, @david-waterworth mind send a PR?

**Comment by awaelchli** [comment]
isn't it supposed to be passed as keyword arguments?
`self.save_hyperparameters(layer_1_dim=layer_1_dim, learning_rate=learning_rate)`

**Comment by Borda** [comment]
> isn't it supposed to be passed as keyword arguments?
> `self.save_hyperparameters(layer_1_dim=layer_1_dim, learning_rate=learning_rate)`

that was not implemented as it was quite dangerous...

**Comment by awaelchli** [comment]
dangerous in what sense? this is just passing in variables with named args, it happens all the time in Python :)

**Comment by Borda** [comment]
I think that the point was with creating new instance from checkpoint as with the new mapping your new parameters do not match names in the class init... we do not want to do any deep/recursive frame investigation and moreover when you update any of there parameters/arguments before you call `save_hyperparameters` there is no simple way to do init argument-hparams mapping
```
class MyModule(...):
  def __init__(self, arg1, arg2):
    param2 += 1
    self.save_hyperparameters(param1=arg1, param2=arg2)
```

**Comment by awaelchli** [comment]
It looks like these docs were fixed . thanks @david-waterworth
