### ISSUE TITLE
Error when loading with LitModel.load_from_checkpoint(path)?

### ISSUE THREAD

**Issue by MicPie** [PyTorchLightning/pytorch-lightning#2364]
### Before asking:   
1. search the issues.   Done
2. search the docs.    Done

#### What is your question?

When I'm loading a Lightning model with LitModel.load_from_checkpoint(path) I always get this error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-5cfc485836df> in <module>
      1 # OPTION 2:
      2 # test after loading weights
----> 3 model = LitModel.load_from_checkpoint("lightning_logs/version_0/checkpoints/epoch=2.ckpt")

~/anaconda3/envs/pytorch-lightning/lib/python3.7/site-packages/pytorch_lightning/core/saving.py in load_from_checkpoint(cls, checkpoint_path, map_location, hparams_file, tags_csv, *args, **kwargs)
    169         checkpoint[cls.CHECKPOINT_HYPER_PARAMS_KEY].update(kwargs)
    170 
--> 171         model = cls._load_model_state(checkpoint, *args, **kwargs)
    172         return model
    173 

~/anaconda3/envs/pytorch-lightning/lib/python3.7/site-packages/pytorch_lightning/core/saving.py in _load_model_state(cls, checkpoint, *args, **kwargs)
    195 
    196         # load the state_dict on the model automatically
--> 197         model = cls(*args, **kwargs)
    198         model.load_state_dict(checkpoint['state_dict'])
    199 

TypeError: __init__() takes 1 positional argument but 2 were given
```

#### Code

Simple example is from https://pytorch-lightning.readthedocs.io/en/latest/new-project.html.
Custom LightModul is very similar but I am using other data, sets, and loaders and a torchvision ResNet.

#### What have you tried?

I tried different checkpoints as well as relative and absolute paths.
Checkpoints are loaded from `lightning_logs/version_0/checkpoints/` which where saved automatically after stopping training.

Setup and training itself works without problems.

I also get the same error with the more complex setup.

Maybe I don't see something super obvious?

Thank you very much & kind regards

#### What's your environment?

 - OS: Ubuntu 18.04
 - Packaging: Conda
 - Version:
pytorch_select 0.2
pytorch 1.3.1
pytorch-lightning 0.8.0

**Comment by dscarmo** [comment]
Might be related to #2334 
If you put an hparams argument in your LitModel does it work? What about using 0.8.1?

**Comment by MicPie** [comment]
Thank you for your reply!

This code snippet gives me the same error:
```
model = LitModel.load_from_checkpoint(checkpoint_path="lightning_logs/version_0/checkpoints/epoch=2.ckpt",
                                      hparams_file="lightning_logs/version_0/hparams.yaml")
```
Via conda I get no update and also tried upgrade with pip but still 0.8.
Do I need for 0.8.1 an editable install via the GitHub repo?

**Comment by dscarmo** [comment]
Sorry, I meant changing the __init__ to (self, hparams).

To me it looks the load_from_checkpoint is trying to force hparams (2 arguments given)
But this might have been fixed in 0.8.1.

Try to `pip uninstall pytorch_lightning` and `pip install pytorch_lightning --upgrade`

**Comment by MicPie** [comment]
Thank you, I was able to install the 0.8.1 version with this trick.

When I add `hparams` to the `def __init__(self, hparams)` to my lightning module I have to supply it during object creation too?

When I load the checkpoint with `torch.load` everything seems to be there.

I suspect the `args` are the reason this happens (`kwargs` are empty), will check later in detail.

**Comment by Borda** [comment]
> I suspect the `args` supplied to `cls._load_model_state(checkpoint, *args, **kwargs)` are the reason this happens (`kwargs` are empty), will check later in detail.

yes, you need to allow your class to pass arguments to the parent class, otherwise, it seems duplicate to #2386
