### ISSUE TITLE
trainer.test() should return the test score

### ISSUE THREAD

**Issue by turian** [PyTorchLightning/pytorch-lightning#2365]
## 🐛 Bug

trainer.test() has no return value. However, after testing one might like to have the test score returned, and saved.

#### Code sample

```
test_score = trainer.test()
```

### Expected behavior

trainer.test() should return the final test score.

### Environment

```
* CUDA:
	- GPU:
	- available:         False
	- version:           None
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.5.0
	- pytorch-lightning: 0.7.6
	- tensorboard:       2.2.2
	- tqdm:              4.46.1
* System:
	- OS:                Darwin
	- architecture:
		- 64bit
		-
	- processor:         i386
	- python:            3.7.7
	- version:           Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64
```

### Additional context

Althought in some settings, `test` is only done immediately before publication and thus should not be used for model selection, there are other settings where validation is used for early stopping and `test` is used for final held-out evaluation. In these settings, being able to save the test score is important.

**Comment by ZhaofengWu** [comment]
In addition to scores, it could also be predictions when we don't have the test set label (e.g. GLUE). Ideally we can get access to the return value of `test_epoch_end`.

**Comment by awaelchli** [comment]
This now works in 0.8.5. Trainer.test() returns whatever you return in `test_epoch_end`.
