### ISSUE TITLE
Access the logging directory through LightningModule or Trainer

### ISSUE THREAD

**Issue by DavidRuhe** [PyTorchLightning/pytorch-lightning#2370]
Is there a way to access the current logging directory (e.g., lightning_logs/version_x)? I've searched the documentation and the source code but haven't found a solution yet.

I want to save some intermediate raw tensors to that directory.

Thanks,
David

**Comment by rohitgr7** [comment]
For tensorboard I think you can use `self.logger.log_dir`, not sure about others. I think this property should be present for all the available loggers if possible.

**Comment by DavidRuhe** [comment]
Thanks!
