### ISSUE TITLE
hparams are not logged in tensorboard

### ISSUE THREAD

**Issue by pvnieo** [PyTorchLightning/pytorch-lightning#2371]
## 🐛 Bug

I'm using the latest version of PL. My problem is when I launch an experiment, everything is logged correctly to tensorboard, except the hparams:
![image](https://user-images.githubusercontent.com/22404728/85848735-f2422a80-b7a9-11ea-80f6-96ab9d6a4a61.png)

I tried to launch the cpu_template on a fresh virtual environement, but it didn't work. However, when I launch the pytorch example of logging hparams to tensorboard (https://pytorch.org/docs/stable/tensorboard.html#torch.utils.tensorboard.writer.SummaryWriter.add_hparams), it worked!

### To Reproduce
I succeeded to reproduce this using the official MNIST collab (https://colab.research.google.com/drive/1F_RNcHzTfFuQf-LeKvSlud6x7jXYkG31#scrollTo=HOk9c4_35FKg), by skipping the "Simplest example" and excuting directly '1. LightningModule' 

### Environment

 - PyTorch Version (e.g., 1.0): 1.5
 - OS (e.g., Linux): ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8 / 3.6
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: GeForce GTX 1060
 - Any other relevant information:

**Comment by david-waterworth** [comment]
Not sure if it's related - I'm getting hparams but not metrics https://github.com/PyTorchLightning/pytorch-lightning/issues/2406

**Comment by pvnieo** [comment]
UPDATE: I used the same code, with the same version in new folder (just copy past the code), and now I have the hparams, but no metrics!

**Comment by awaelchli** [comment]
putting a reminder here that we saw this problem popping up recently in one of the tests. 
See here, https://github.com/PyTorchLightning/pytorch-lightning/pull/2512#discussion_r451011814
need to look at the test there to debug the problem.

**Comment by edenlightning** [comment]
Closing issue. @pvnieo please let us know if you have any issues!
