### ISSUE TITLE
Incorrect docs in metrics

### ISSUE THREAD

**Issue by rohitgr7** [PyTorchLightning/pytorch-lightning#2377]
## 📚 Documentation
Here
https://github.com/PyTorchLightning/pytorch-lightning/blob/a5f45787eabddfec4559983f8e6ba1c8317f62f1/pytorch_lightning/metrics/functional/classification.py#L137
the argument is `num_classes` but in docs it is `class_index`
https://github.com/PyTorchLightning/pytorch-lightning/blob/a5f45787eabddfec4559983f8e6ba1c8317f62f1/pytorch_lightning/metrics/functional/classification.py#L148

Also, it returns 5 values but only 4 are mentioned.
https://github.com/PyTorchLightning/pytorch-lightning/blob/a5f45787eabddfec4559983f8e6ba1c8317f62f1/pytorch_lightning/metrics/functional/classification.py#L152-L153

**Also, some more typos and docs needed to be fixed in the metrics module.**

**Comment by awaelchli** [comment]
interested in sending a PR @rohitgr7 ?
