### ISSUE TITLE
Pause and resume support

### ISSUE THREAD

**Issue by Geeks-Sid** [PyTorchLightning/pytorch-lightning#2381]
## 🚀 Feature
It would be really helpful if we could have a pause and resume support for training networks. I am not talking about restarting from checkpoint training, but more in the lines of stopping in between randomly, the saving the optimizer state_dicts, and if resumed, then starting from the same place where it left off during training which would be a slightly more complicated and precise version of checkpointing.

### Motivation
During one of my recent experiments, I am currently running very very long epochs, epochs usually last for 12 hours over 10000 samples and a batch size of 1 is causing constraints to train. 

I sometimes want to add new images to the data loader without losing the state_dict and it was possible in Pytorch with some hacky methods, but I wanted to know if we already/could support this feature. 

From my experience, stopping with a keyboard interrupts usually calls a graceful shutdown as mentioned [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/e085e93dd303e80af2e9a5fe4aa392055c831114/pytorch_lightning/trainer/__init__.py#L71) which does save optimizer state_dicts, etc and call an on_train_end, but is it possible to resume from the same point of the data loader?

Also, It would be great to know if all interrupts are supported with this feature which feels a little unclear reading [this](https://github.com/PyTorchLightning/pytorch-lightning/blob/94463907799bde33fa3af9f1e2a1c7a2521bcf48/tests/trainer/test_trainer.py#L704)

Could you shed some light on this @williamFalcon if possible?

**Comment by justusschock** [comment]
Hi @Geeks-Sid , I'm afraid this is not possible in general, since we don't control the DataLoader and it is also not that easy to extract a state out of it with it's multiple workers. I think for this to become possible, you'd have to write your own DataLoader. Or do you have any other proposals on this?
