### ISSUE TITLE
CometLogger improvements

### ISSUE THREAD

**Issue by neighthan** [PyTorchLightning/pytorch-lightning#2393]
## 🚀 Features

1. Save the offline experiment data in the same directory as the model's checkpoint directory
2. Use the experiment name in the directory name for the experiment
3. Fix the `name` property on the logger (this part is a bug more than a feature request)

## Motivation / Pitch

Suppose I set up my logger and trainer like this:

```python
import pytorch_lightning as pl

logger = pl.loggers.CometLogger(
    save_dir="/home/user/models",
    project_name="my_project",
    experiment_name="my_exp",
)
trainer = pl.Trainer(logger)
model = ...
trainer.fit(model)
```

1. If the id of my experiment was `123` then I'd have the offline experiment file at `/home/users/models/123.zip`. The rest of the data from that training run would be at `/home/users/models/my_project/123/ `. I think it would be nicer if the `123.zip` file was at `/home/users/models/my_project/123/123.zip`.
2. For easier discoverability, it would be nice to have the experiment name as part of the name of the directory. So instead of `/home/users/models/my_project/123/`, the directory could be `/home/users/models/my_project/my_exp/` or perhaps `/home/users/models/my_project/my_exp_123/`. Then one could find experiments by name.
3. If I check `logger.name`, I'll get `"my_project"` instead of `"my_exp"`. The getter should be return str(self.experiment.get_name()) instead of the current `return str(self.experiment.project_name)`.

## Cons

* Having all of the offline experiment zip files in the same directory probably makes it easier to upload them to the Comet website. I don't think this would be very hard with the zip files in each experiment's own directory, but it might take a slightly more complicated bash command.
* I don't think we can implement 1. unless we remove the experiment ID from the directory name; we have to pass the save directory when creating the offline experiment, but at that point no ID has been assigned yet. If 2. is also done and we just use the experiment name, without the id, then 1. would be easy to implement. If we want things to be robust to multiple experiments with the same name, we could add `_{i}` to the name where `i` is 0 by default and takes on the smallest unused integer value if there are already directories with the same experiment name (this has the added benefit of making it easy to tell what order I ran the experiments in, so I could, e.g., find the most recent run of an experiment with a certain name).

## Implementation

I'm happy to implement these features if a PR would be accepted.

**Comment by neighthan** [comment]
Or is there an easy way to do 1. and 2. using callbacks without changing the code?

**Comment by neighthan** [comment]
While 3. does still seem to be a bug (because the name getter uses the project name but the name setter changes the experiment name), changing this would also break backwards-compatibility because the logger's name is used to determine the checkpoint directory ([here](https://github.com/PyTorchLightning/pytorch-lightning/blob/90f641af0d509645ecd679d00f1213f68d4a44ad/pytorch_lightning/trainer/callback_config.py#L56)).

**Comment by neighthan** [comment]
4. It would also be nice if there was a flag (off by default for backwards-compatibility / to save space) to have the logger automatically upload the checkpoint file as an asset to Comet at the end of training. The issue here is, the logger doesn't necessarily know the directory where the checkpoints are saved, does it? While it would be nicer if this could be automatic, if that's not possible, I think it would still be quite useful if the logger had a method for this which required just the `Trainer` as input (since that will know the checkpoint directory). So then you'd have to do something like

```python
logger = CometLogger()
model = MyModel()
trainer = Trainer(logger=logger)
trainer.fit(model)
logger.upload_model(trainer)
```

**Comment by neighthan** [comment]
3. If the logger has `save_dir`, the checkpoints are saved at `logger.save_dir/logger.name/logger.version/checkpoints`. Thus instead of changing `name` to get / set the experiment name, I think it's nicer to have this get the project name (and not provide a setter; I don't think the project of an existing experiment can be changed) and have the version return the experiment name if there is one (otherwise the id). Then the weights are saved in `save_dir/project_name/experiment_name/checkpoints`. (As mentioned in the first post, I currently do `{experiment_name}_{i}` for `i` incrementing from 0 so that there aren't issues if multiple experiments have the same name, and it's easy to distinguish between multiple of them)

**Comment by justusschock** [comment]
cc @Borda @williamFalcon

**Comment by Borda** [comment]
@neighthan how is it going here?
