### ISSUE TITLE
cannot unpack non-iterable NoneType object when predicting with test function/dataloader

### ISSUE THREAD

**Issue by soulhi-vz** [PyTorchLightning/pytorch-lightning#2394]
Hi,
When trying to evaluate the autoencoder with test dataset, we got the error:
cannot unpack non-iterable NoneType object  

def training_step(self, train_batch, batch_idx):
        x, _ = train_batch
        decoded, encoded = self.forward(x)
        loss = self.mse(decoded,x)
        tensorboard_logs = {'train_loss': loss}
        return {'loss': loss, 'log': tensorboard_logs}
def test_step(self,test_batch, batch_idx):
        x, _ = test_batch
        decoded, encoded = self.forward(x)
        return decoded, encoded
def test_dataloader(self):
        return DataLoader(dataset=Train_x_t_e, batch_size=self.hparams.batch_size)

# save model
me = Autoencoder.load_from_checkpoint(checkpoint_path="testmodel.ckpt")
# predict autoencoder result
trainer = pl.Trainer()
y_hat, z = trainer.test(me)

Got this error:

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py:23: RuntimeWarning: You passed  in a `test_dataloader` and have defined a `test_step()`, you may also want to define `test_epoch_end()` for accumulating stats.
  warnings.warn(*args, **kwargs)
/opt/conda/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py:23: UserWarning: The dataloader, test dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)
HBox(children=(FloatProgress(value=1.0, bar_style='info', description='Testing', layout=Layout(flex='2'), max=…
--------------------------------------------------------------------------------
TEST RESULTS
{}
--------------------------------------------------------------------------------

TypeErrorTraceback (most recent call last)
<ipython-input-111-f27519f8b5a7> in <module>
----> 1 y_hat, z = trainer.test(me)

TypeError: cannot unpack non-iterable NoneType object

**Comment by rohitgr7** [comment]
The reason is `trainer.test()` returns nothing. It just evaluates your test_dataloader. If you want to get those values you can save them in a file in `test_end` for each batch or save all the test accumulated outputs in `test_epoch_end`.

**Comment by awaelchli** [comment]
related/the same as #1694 #2365

**Comment by soulhi-vz** [comment]
Thanks Rohit for the feedback

How to get encoded, decoded into the test_epoch_end since these variables are local to test_step and can not be returned

def test_step(self,test_batch, batch_idx):
        x, _ = test_batch
        decoded, encoded = self.forward(x)
        return {'y_hat':decoded, 'z':encoded}
    
    def test_epoch_end(self, outputs):
        outputs = ??
        return outputs

**Comment by rohitgr7** [comment]
`outputs` in `test_epoch_end` is a list which stores the value returned from `test_step`. Since you are returning a dict in `test_step` the `outputs` will be `[dict, dict, ...]` for each test_batch in `test_dataloader`. Check this:
https://github.com/PyTorchLightning/pytorch-lightning/blob/66ffbaddf5abf3e3fca5789ba2427be55b27d1af/pytorch_lightning/core/lightning.py#L644-L649

**Comment by soulhi-vz** [comment]
Thanks Rohit
