### ISSUE TITLE
Are auto-resubmited slurm jobs completely the same as if it weren't interrupted?

### ISSUE THREAD

**Issue by ZhaofengWu** [PyTorchLightning/pytorch-lightning#2397]
In other words, does `trainer.hpc_save` persist _all_ necessary information (e.g. how many batches are processed in the current epoch) such that, when restored, it behaves completely the same (random states aside) as if it weren't interrupted?

And a related question: if my cluster handles auto-resubmission, which means I only need the `hpc_save` part of `pytorch-lightning`'s `SIGUSR1` handling logic, is there a way I can disable to resubmission logic?

**Comment by williamFalcon** [comment]
1. yes it's all handled. However the epoch will start again (but everything else is saved).
2. To disable it don't pass SIGUSR1 to your slurm script

**Comment by ZhaofengWu** [comment]
If the epoch starts over while the model state doesn't get reset to before the epoch, wouldn't this be equivalent to training with more data for that specific epoch? That might be undesirable when we want very rigorous comparisons across different models/settings/etc. Is there a way to achieve this? I guess a simple way is to save a checkpoint at the end of every epoch and use that, but that creates a lot of unnecessary checkpoints, as mentioned in #2141.
