### ISSUE TITLE
Trainer.restore_weights takes a model, but never uses it

### ISSUE THREAD

**Issue by scnerd** [PyTorchLightning/pytorch-lightning#240]
In line with the discussion on #169 , while digging through the code trying to figure out how to load a model when I don't have a meta_tags.csv (I'm hitting exp.save(), but that file never shows up, just a "meta.experiment" file), I discovered the [``Trainer.restore_weights(self, model)``](https://github.com/williamFalcon/pytorch-lightning/blob/87708157bc1c8f69ccfe5401b75d227348f56dfe/pytorch_lightning/trainer/trainer_io.py#L24) function. It crashed when I tried to use it, though, because the ``model`` argument never gets used, and instead it just calls ``Trainer.restore``, which gets the model from [``Trainer.__get_model``](https://github.com/williamFalcon/pytorch-lightning/blob/87708157bc1c8f69ccfe5401b75d227348f56dfe/pytorch_lightning/trainer/trainer_io.py#L132). It seems like either the model shouldn't be asked for, or it ought to be used, not sure which is better in this case.

**Comment by scnerd** [comment]
I'm actually running into this while trying to figure out how to use ``.test()`` because, again, there's no ``meta_tags.csv`` file and thus I can't use the ``load_from_metrics`` function. It's frustrating because I can call ``.fit(model)`` and the model loads from the latest checkpoint, everything resets to where it was, and we're good, but ``.test()`` doesn't do any of that (and probably shouldn't), but figuring out how to load the model from a checkpoint without a ``meta_tags.csv`` file is tricky.

**Comment by williamFalcon** [comment]
good points. i think we have an issue already for cleaning up the load function. if you want to take a crack at it, we’d love the PR! 

Otherwise I can look into it after next week
