### ISSUE TITLE
Will load_from_checkpoint load Huggingface models as well? 

### ISSUE THREAD

**Issue by vibhavagarwal5** [PyTorchLightning/pytorch-lightning#2404]
#### What is your question?

Just wanted to know will using the `load_from_checkpoint` for a `LightningModule` load the state_dict for the **HuggingFace** models as well?

Eg: for the given example in the docs, will state_dict be loaded for `BertModel.from_pretrained` thing as well? 
Ideally, `load_from_checkpoint` should load state_dict for Bert as well like `BertModel.from_pretrained(same_checkpoint)` would do.

#### Code
```
class BertMNLIFinetuner(LightningModule):

    def __init__(self):
        super().__init__()

        self.bert = BertModel.from_pretrained('bert-base-cased', output_attentions=True)
        self.W = nn.Linear(bert.config.hidden_size, 3)
        self.num_classes = 3


    def forward(self, input_ids, attention_mask, token_type_ids):

        h, _, attn = self.bert(input_ids=input_ids,
                         attention_mask=attention_mask,
                         token_type_ids=token_type_ids)

        h_cls = h[:, 0]
        logits = self.W(h_cls)
        return logits, attn
```

**Comment by dscarmo** [comment]
When working with the Hugging Face library i just store the string (in this case best-base-cased) as an hparam.

**Comment by vibhavagarwal5** [comment]
Sure, that is fine. I think you misunderstood my question. Will the state_dict from the checkpoint (using `load_from_checkpoint`) load the bert model as well or not? Or will I have to load it explicitly using `model.from_pretrained(checkpoint_path)` ?

**Comment by awaelchli** [comment]
I don't know this Bert stuff , but if it helps:
`Model.load_from_checkpoint()` will init your model with the args and kwargs from the checkpoint and then call `model.load_state_dict` to load the model weights as you would do in pure PyTorch.
So, if your` self.bert` is a `nn.Module` , then that will have the parameters loaded as well.

**Comment by dscarmo** [comment]
Oh now i understand. The updated weights of your whole lightning module (if you didnt freeze bert) will be loaded. I am just wondering if the init `from_pretrained`  you overwrite your trained weights? 

I hope PL will only load the trained weights after init runs.

**Comment by awaelchli** [comment]
yes, so the from_pretrained will run first and load your pretrained weights (since it's in the init). and then the load_state dict will overwrite them again with the weights from the checkpoint. 

I encourage you to make a sanity check and not blindly believe me :), for example, you could load your checkpoint manually and replace all weights with ones and then save it again. Then load the checkpoint again using pytorch lightning and print the weights of the loaded model.

**Comment by vibhavagarwal5** [comment]
My guess is the same that after from_pretrained weights are loaded, checkpoints weights override them.

**Comment by vibhavagarwal5** [comment]
Another doubt, do the checkpoints save all sorts of callbacks as well? Coz I don't see it in the dict keys when I do torch.load(chckpoint).

**Comment by awaelchli** [comment]
we do that for early stopping and model checkpoint (see v0.8.2), but not for your custom callbacks. We recently discussed how to do that, here is an open discussion #2401 .

**Comment by vibhavagarwal5** [comment]
v.0.8.2 is not released yet right?
