### ISSUE TITLE
save the model/training source code to model checkpoint or logs directory

### ISSUE THREAD

**Issue by ares89** [PyTorchLightning/pytorch-lightning#2409]
## 🚀 Feature

Save the model/training source code to model checkpoint or logs directory

### Motivation

Now, the hparams has been saved in yaml file.  Sometimes, we not only change the hparams but also the network arch, the pre-process flow, so if we save the relate source code to model, we will get all the information to restore the model, because the source code is with the model hparams and all other things.

### Pitch

add Trainer args parse params, or Checkpoint callback params,  one for wether to save source code, and one for which codes to save

**Comment by dscarmo** [comment]
I achieve this through saving the commit hash (assuming your code is in a git repo). 
Some loggers will catch this automatically, or you can have a function to add this to your parameters automatically.

Would be nice as a feature anyway.

**Comment by versatran01** [comment]
I think sacred can do this.
