### ISSUE TITLE
Imagenet example use num_workers 0

### ISSUE THREAD

**Issue by ruotianluo** [PyTorchLightning/pytorch-lightning#2422]
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/domain_templates/imagenet.py#L160

Is there a specific reason for that?

**Comment by dscarmo** [comment]
I think there is no reason, however this wil raise a warning in current version that low num workers can be a bottleneck.

**Comment by williamFalcon** [comment]
no reason. feel free to change it!
