### ISSUE TITLE
Train in run_pretrain_routine?

### ISSUE THREAD

**Issue by ruotianluo** [PyTorchLightning/pytorch-lightning#2431]
I see the train() is run in run_pretrain_routine, doesn't it look wierd? At least violating the function name.

https://github.com/PyTorchLightning/pytorch-lightning/blob/d4a02e3bd8471946c606fef7512ce44d42f07d3a/pytorch_lightning/trainer/trainer.py#L1003

**Comment by awaelchli** [comment]
We are aware of that it will be refactored in the future. Here is already a discussion: #1195

**Comment by ruotianluo** [comment]
Thanks
