### ISSUE TITLE
Using single GPU when training on object detection

### ISSUE THREAD

**Issue by anguoyang** [PyTorchLightning/pytorch-lightning#2439]
## 🐛 Bug
Lightning using only one GPU training, it happens only on object detection applications, it seems lightning does not support target to be a tuple of tensors in the data loader.
1.if we use pytorch with object detection, it is fine
2.if we use pytorch-lightning with classification tasks, e.g. face recognition, it is also fine
3.if we use pytorch-lightning with object detection, it uses only 1 GPU even if we set 4 GPUs for it

### To Reproduce

there is an example on pytorch-lightning with object detection:
https://github.com/Erlemar/wheat
you could reproduce the problem by modify the ngpu=4 or any value>1 then see the GPU usage with nvidia-smi.

### Expected behavior

Using all GPUs when training

### Environment
1.conda python3.7 virtual envs
2.Ubuntu 18.04
3.Cuda version: 10.1
4.pytorch version: 1.5.1
5.lightning version:  we tried  on several versions, from version 0.7.6 ~  the master version on June.24

**Comment by awaelchli** [comment]
I see a config file in wheat/conf/trainer/default_trainer.yaml
which has gpus=1
Try to change that?

**Comment by anguoyang** [comment]
@awaelchli yes

**Comment by VinhLoiIT** [comment]
AFAIK, the param `gpus` of `pl.Trainer` could be one of `int`, `List[int]` or `str`. You set your param `gpus=1` so it will only use one GPU. Try to change to `gpus=-1` to use all available GPUs as described [here](https://pytorch-lightning.readthedocs.io/en/latest/multi_gpu.html#select-gpu-devices)

**Comment by edenlightning** [comment]
Closing this issue. @anguoyang feel free to reopen if you run into any issues!
