### ISSUE TITLE
Live Demo lightning_mnist_tpu.ipynb on colab hanging

### ISSUE THREAD

**Issue by foobar8675** [PyTorchLightning/pytorch-lightning#2440]
## 🐛 Bug

1. Run lightning_mnist_tpu.ipynb on colab

### To Reproduce

1. Go to lightning_mnist_tpu.ipynb from https://pytorch-lightning.readthedocs.io/en/latest/tpu.html
2. Run
3. See screen gets stuck here

<img width="1188" alt="Screen Shot 2020-06-30 at 11 19 34 PM" src="https://user-images.githubusercontent.com/1685700/86199510-2487bb00-bb0f-11ea-8e27-e9050742b323.png">

### Environment

Colab pro

**Comment by williamFalcon** [comment]
Duplicate of #2419
