### ISSUE TITLE
multi-gpu training triggers CUDA out of memory error

### ISSUE THREAD

**Issue by griff4692** [PyTorchLightning/pytorch-lightning#2456]
Hi - 

I am running into issues when going from single to multi-gpu training.  Specifically, if I switch the line

`pl.Trainer(gpus=1, precision=16, distributed_backend='ddp')`

to

`pl.Trainer(gpus=4, precision=16, distributed_backend='ddp')`

I get the dreaded CUDA out of memory error.  Is there any reason why the parallelism causes the GPU to receive more data?

**Comment by justusschock** [comment]
Hi, what are your outputs of the validation_step? If there are any large tensors, it's likely they get synced back to root GPU by https://github.com/PyTorchLightning/pytorch-lightning/pull/2434 . We're working on that.

**Comment by griff4692** [comment]
Hi - I actually haven't implemented the validation step yet.  this just occurs on the training side

**Comment by justusschock** [comment]
what is your gpu consumption on a single gpu (used/available)?

**Comment by griff4692** [comment]
On single gpu, I am using 5/11 GB.  The problem seems to be that when I switch over to multiple GPUs, there is an explosion of processes created on the first GPU.  Any ideas what could be causing this?

<img width="611" alt="Screen Shot 2020-07-02 at 9 32 21 AM" src="https://user-images.githubusercontent.com/12277915/86365204-32405c00-bc47-11ea-9211-0e6ccfb57f8d.png">

**Comment by griff4692** [comment]
**Fixed it!**.  I was calling `.to('cuda')` on my input tensors in my Dataset __get__item function which caused all the data to be uploaded to the first GPU.  Removed that and solved the problem.

**Comment by williamFalcon** [comment]
@justusschock does that mean we should add back the all reduce for val?

**Comment by justusschock** [comment]
No, there were other issues with that as well :D Let's just keep it out for now.

**Comment by MuhammadWaleedUsman** [comment]
I have the same issue but couldnt solve it by removing .to('cuda'). when i do this i get error:
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

**Comment by MuhammadWaleedUsman** [comment]
> **Fixed it!**. I was calling `.to('cuda')` on my input tensors in my Dataset __get__item function which caused all the data to be uploaded to the first GPU. Removed that and solved the problem.

I have the same issue but couldnt solve it by removing .to('cuda'). when i do this i get error:
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
