### ISSUE TITLE
Wandb Flatten Dict

### ISSUE THREAD

**Issue by anthonytec2** [PyTorchLightning/pytorch-lightning#2458]
Wandb logger should flatten the dictionary of parameters before logging. Every other logger has the bellow pattern of code:
```
 params = self._convert_params(params)
 params = self._flatten_dict(params)
```

## 🐛 Bug

Wandb logger does not flatten parameters resulting in dictionaries being logged to Wandb, which are not searchable causing for some loss of features in wandb. 
### To Reproduce

Run the cpu_template with wandb logger, and log a nested dictionary. 

### Expected behavior

Solution, just call  ` params = self._flatten_dict(params)` this in the wandb logger. 
### Environment
* CUDA:
	- GPU:
	- available:         False
	- version:           None
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.5.0
	- pytorch-lightning: 0.8.4
	- tensorboard:       2.2.2
	- tqdm:              4.46.1
* System:
	- OS:                Darwin
	- architecture:
		- 64bit
		-
	- processor:         i386
	- python:            3.7.7
	- version:           Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64

**Comment by awaelchli** [comment]
![image](https://user-images.githubusercontent.com/5495193/86573252-659b2780-bf74-11ea-90d5-30041764941c.png)

Is this what you mean? 
I agree, it would be nice if we could flatten that out.

**Comment by anthonytec2** [comment]
Exactly, this commit will make hparams look like:

<img width="566" alt="Screen Shot 2020-07-06 at 7 08 59 AM" src="https://user-images.githubusercontent.com/11021542/86587431-93be3e80-bf57-11ea-85da-c420b613e26f.png">

**Comment by awaelchli** [comment]
perfect!
