### ISSUE TITLE
Trainer auto_lr_find flag cannot be set to boolean through argparse

### ISSUE THREAD

**Issue by qiaoruiyt** [PyTorchLightning/pytorch-lightning#2461]
## 🐛 Bug

It seems that the Trainer `auto_lr_find` flag can only be set to `str` type via argparse. If it is not a boolean, Trainer will seek the finder with variable name defined via `--auto_lr_find` instead of using the default lr_finder. It's not a big issue as we can work around this by some processing after parsing the arguments. However, I hope the `auto_lr_find` flag can be set in a better way as it may cause trouble for people who don't know about this. Thanks!

### To Reproduce
This works:
```bash
python train.py
```
```python
trainer = pl.Trainer(gpus=args.gpus, 
                            auto_lr_find=True)
```

This will have error because of the string type:
```bash
python train.py --auto_lr_find True
```
```python
parser = pl.Trainer.add_argparse_args(parser)
args = parser.parse_args()
trainer = pl.Trainer.from_argparse_args(args)
```

### Environment
0.8.4

**Comment by awaelchli** [comment]
on flags like this or for example fast_dev_run we should set the action="store_true" in the argparser. 
Then we can just do
```
python train.py --auto_lr_find 
```
but 
```
python train.py --auto_lr_find True
```
is definitely not the desired way, but you can currently use "1" instead of "True"

**Comment by qiaoruiyt** [comment]
Thanks for the help! It sounds okay if "1" would work for the case.

**Comment by williamFalcon** [comment]
fixed!
