### ISSUE TITLE
DDP breaks when `python` does not refer to the correct interpreter

### ISSUE THREAD

**Issue by kl0211** [PyTorchLightning/pytorch-lightning#2472]
## 🐛 Bug

If using the DDP distributed_backend, the program breaks if `python` refers to `python2` or does not exist.

### To Reproduce

1. Make sure the `python` command does not link to `python3`, such as on Ubuntu 18.04.
2. Run Trainer().fit with distributed_backed='ddp'

### Additional context

The problem lies at https://github.com/PyTorchLightning/pytorch-lightning/blob/0697dd306d578f0cd3c4d23b768da0106e54a095/pytorch_lightning/trainer/distrib_data_parallel.py#L422 The `python` command is hardcoded here. On many systems, `python` is a symlink to `python2`, or does not exist.

**Comment by RitchieAlpha** [comment]
Same question!!!!!

**Comment by Borda** [comment]
it is based on your default python 
https://github.com/PyTorchLightning/pytorch-lightning/blob/25ee51bc570503f331dceecc610d0eb355e22327/pytorch_lightning/trainer/distrib_data_parallel.py#L422
mind send a Pr which updating the actual python interpreter?
cc: @williamFalcon

**Comment by kl0211** [comment]
@Borda I just saw #2482. Using `sys.executable` is exactly what I was going to suggest. According to https://www.python.org/dev/peps/pep-0394/#for-python-script-publishers, this should ensure the same interpreter is used to spawn the child processes.

Thanks for the quick change!
