### ISSUE TITLE
PSNR metric in metrics

### ISSUE THREAD

**Issue by rohitgr7** [PyTorchLightning/pytorch-lightning#2474]
## 🚀 Feature
Can we have [PSNR](https://en.wikipedia.org/wiki/Peak_signal-to-noise_ratio) metric in the metrics module?

### Motivation
This metric is used in Image generative models eg. super-resolution.

**Comment by InCogNiTo124** [comment]
I believe I could implement it.

**Comment by InCogNiTo124** [comment]
Actually I think I have implemented it somewhere

**Comment by rohitgr7** [comment]
Couldn't find it in lightning.

**Comment by InCogNiTo124** [comment]
> Couldn't find it in lightning.

No, sorry, I meant I've implemented it for my needs, and I'm about to open a PR where I add it

**Comment by rohitgr7** [comment]
Oh! I have worked with it too. It's just `log inverse mse`. Thought it would be a good addition to lightning metrics.

**Comment by InCogNiTo124** [comment]
Oh, okay.

I've added a stub [here in my fork](https://github.com/InCogNiTo124/pytorch-lightning/blob/psnr-metric/pytorch_lightning/metrics/regression.py#L191)

**Comment by Borda** [comment]
@InCogNiTo124 mind send a PR adding it to lightning?
