### ISSUE TITLE
Model and Input not on same GPU when training with native AMP and DP

### ISSUE THREAD

**Issue by aeryen** [PyTorchLightning/pytorch-lightning#2476]
## 🐛 Bug

Training with `distributed_backend='dp'` and `precision=16` result in the error that some input/output of the model is not on the same GPU.

### To Reproduce

```
from pytorch_lightning import Trainer, seed_everything
from pl_examples.models.lightning_template import LightningTemplateModel
seed_everything(234)

def main():
    # model = LightningTemplateModel(**vars(args))
    model = LightningTemplateModel()

    trainer = Trainer(
        gpus=2,
        num_nodes=1,
        distributed_backend='dp',
        precision=16
        )

    trainer.fit(model)

if __name__ == '__main__':
    main()
```

Run the above example code will result in following error:

```
Traceback (most recent call last):
  File "./_debug_pytorch_lightning_16gpu.py", line 28, in <module>
    main()
  File "./_debug_pytorch_lightning_16gpu.py", line 24, in main
    trainer.fit(model)
  File "/home/ubuntu/anaconda3/envs/trfm/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 973, in fit
    self.dp_train(model)
  File "/home/ubuntu/anaconda3/envs/trfm/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 267, in dp_train
    self.run_pretrain_routine(model)
  File "/home/ubuntu/anaconda3/envs/trfm/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1139, in run_pretrain_routine
    False)
  File "/home/ubuntu/anaconda3/envs/trfm/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 291, in _evaluate
    output = self.evaluation_forward(model, batch, batch_idx, dataloader_idx, test_mode)
  File "/home/ubuntu/anaconda3/envs/trfm/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 441, in evaluation_forward
    output = model(*args)
  File "/home/ubuntu/anaconda3/envs/trfm/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/trfm/lib/python3.7/site-packages/pytorch_lightning/overrides/data_parallel.py", line 65, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ubuntu/anaconda3/envs/trfm/lib/python3.7/site-packages/pytorch_lightning/overrides/data_parallel.py", line 69, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ubuntu/anaconda3/envs/trfm/lib/python3.7/site-packages/pytorch_lightning/overrides/data_parallel.py", line 209, in parallel_apply
    raise output
  File "/home/ubuntu/anaconda3/envs/trfm/lib/python3.7/site-packages/pytorch_lightning/overrides/data_parallel.py", line 172, in _worker
    output = module.validation_step(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/trfm/lib/python3.7/site-packages/pl_examples/models/lightning_template.py", line 102, in validation_step
    val_loss = F.cross_entropy(y_hat, y)
  File "/home/ubuntu/anaconda3/envs/trfm/lib/python3.7/site-packages/torch/nn/functional.py", line 2422, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/ubuntu/anaconda3/envs/trfm/lib/python3.7/site-packages/torch/nn/functional.py", line 2218, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Assertion `THCTensor_(checkGPU)(state, 4, input, target, output, total_weight)' failed. Some of weight/gradient/input tensors are located on different GPUs. Please move them to a single one. at /opt/conda/conda-bld/pytorch_1593673617738/work/aten/src/THCUNN/generic/ClassNLLCriterion.cu:31
```

### Expected behavior

The model should train successfully on 2 GPUs with native PyTorch AMP.

### Environment

* CUDA:
        - GPU:
                - Tesla V100-SXM2-16GB
                - Tesla V100-SXM2-16GB
                - Tesla V100-SXM2-16GB
                - Tesla V100-SXM2-16GB
        - available:         True
        - version:           10.2
* Packages:
        - numpy:             1.18.5
        - pyTorch_debug:     False
        - pyTorch_version:   1.7.0.dev20200702
        - pytorch-lightning: 0.8.5-dev
        - tensorboard:       2.2.2
        - tqdm:              4.47.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - 
        - processor:         x86_64
        - python:            3.7.7
        - version:           #30~18.04.1-Ubuntu SMP Mon Jun 22 15:48:21 UTC 2020

### Additional context

This only seems to be an issue with native AMP, not Apex AMP.

**Comment by aeryen** [comment]
I just realized that without precision=16 the script would still fail with a different error
`TypeError: zip argument #1 must support iteration`
Am I doing something wrong? This seems like a separate bug.

**Comment by s-rog** [comment]
I'm not using native amp yet but apex only works on ddp, and I suspect the native implementation might be as well.

**Comment by aeryen** [comment]
I see, so it's not supported yet. Thanks for the information. Unfortunately, I have to stick with DP, because PyTorch does not allow gradient checkpointing with DDP. Let me see if I can get this to work.

**Comment by aeryen** [comment]
@s-rog regarding the issue that DP also doesn't work even without precision=16, can you kindly help me confirm that? should I open a separate issue?

**Comment by s-rog** [comment]
I've never really used dp so I really can't tell you

**Comment by williamFalcon** [comment]
yes that's correct... for some reason, dp and apex do not mix well.
Maybe @mcarilli might know why when forward is called with dp the casting isn't automated?

**Comment by aeryen** [comment]
@williamFalcon Hi, sorry, the issue is actually with native amp, not apex. Also, honestly, currently the DP is completely broken, not just when using precision=16. It does feel like people have mostly abandoned DP and moved to DDP in general?

**Comment by williamFalcon** [comment]
yeah, dp should not really be used but we can’t remove since some people’s research depends on it.

**Comment by aeryen** [comment]
So here is my question (apologies if this is not a good place to discuss this): Isn't the PyTorch gradient checkpointing currently can only work with DP? My current conundrum, I'm trying to work with HuggingFace longformer, and without gradient checkpointing, I can only fit batch size 1 in a single GPU with 16g vram. So the best combo for me right now is Native AMP + DP + gradient checkpointing.
I guess maybe the long term direction is either just move to TPU and not bother or wait to see if PyTorch can manage to get DDP to work with gradient checkpointing.

**Comment by mcarilli** [comment]
torch.cuda.amp should support DP, and torch.cuda.amp + DP is tested in pytorch CI, so the error is unexpected.  Do you have a minimal repro that uses raw Pytorch (not lighting)?  This would help us narrow down if the problem lies with DP, torch.cuda.amp, or how lightning combines them.  Also, can you post the complete backtrace?

**Comment by aeryen** [comment]
@mcarilli My feeling is the issue is within lightning, I've done a rough test with raw Pytorch and haven't been able to recreate the bug (but could be because I'm bad at this). I've added the trace to the top.

**Comment by edenlightning** [comment]
@mcarilli can you take a look?

**Comment by mcarilli** [comment]
I can look into this but probably not in the next few days, reping if I don't respond by then.  Did you ever get a repro with raw pytorch (not lightning)?

**Comment by edenlightning** [comment]
@aeryen

**Comment by aeryen** [comment]
No I still don't have repro for raw pytorch. So I still think it's within lighting.
I tried to debug it, I even tried manually move the model to each GPU according to the location of the data within my outer forward(). The issue still occur. Looks to me the model's device jump to something else as soon as my sub modules' forward() are being called. I had the impression that threads are not using the model that belongs to them. I'm probably not explaining this as clear as I should...

**Comment by binshengliu** [comment]
Sorry I’m a bit hectic and not up for making a PR.
