### ISSUE TITLE
init_slurm_connection causing hostname errors

### ISSUE THREAD

**Issue by jgbos** [PyTorchLightning/pytorch-lightning#2479]
# Problem

Can you update this function to support checking if `MASTER_ADDR` and `MASTER_PORT` are already in `os.environ`?  Running into some weird errors where this code adds host to `MASTER_ADDR` and crashes the code.

https://github.com/PyTorchLightning/pytorch-lightning/blob/0697dd306d578f0cd3c4d23b768da0106e54a095/pytorch_lightning/core/lightning.py#L903

# Solution

Do you prefer a pull request?  Here's the check I put it

```python
def _init_slurm_connection(self) -> None:
        """
        Sets up environment variables necessary for pytorch distributed communications
        based on slurm environment.
        """

        if 'MASTER_PORT' not in os.environ:
            # use slurm job id for the port number
            # guarantees unique ports across jobs from same grid search
            try:
                # use the last 4 numbers in the job id as the id
                default_port = os.environ['SLURM_JOB_ID']
                default_port = default_port[-4:]

                # all ports should be in the 10k+ range
                default_port = int(default_port) + 15000

            except Exception:
                default_port = 12910

            # if user gave a port number, use that one instead
            try:
                default_port = os.environ['MASTER_PORT']
            except Exception:
                os.environ['MASTER_PORT'] = str(default_port)

        # figure out the root node addr
        if 'MASTER_ADDR' not in os.environ:
            try:
                root_node = os.environ['SLURM_NODELIST'].split(' ')[0]
            except Exception:
                root_node = '127.0.0.1'

            root_node = self.trainer.resolve_root_node_address(root_node)
            os.environ['MASTER_ADDR'] = root_node
```

**Comment by jgbos** [comment]
Ok, back on this and tracked down the bug.  The problem is in this line:

```python
  root_node = os.environ['SLURM_NODELIST'].split(' ')[0]
```

On my system, `SLURM_NODELIST` is a comma delineated list, so `split(',')` instead of `split(' ')`.

**Comment by jgbos** [comment]
Additionally, our system will use this for two systems:

```bash
 d-10-11-[1-2]
```

**Comment by Borda** [comment]
@williamFalcon is this fixed?

**Comment by jgbos** [comment]
fyi, this is not fixed in general.  I think the problem is fixed for the example above

```bash
SLURM_NODE_LIST=d-10-11-[1-2]
```

but not the case for 

```bash
SLURM_NODE_LIST=d-10-11-1,d-11-12-1
```

My current hack for PL to run on slurm is to set `MASTER_ADDR` in the sbatch script and then do the following:

```python
    # fix slurm node list
    if 'MASTER_ADDR' in os.environ and 'SLURM_NODELIST' in os.environ:
        slurm_node_list = os.environ['SLURM_NODELIST'].split(',')
        master_addr = os.environ['MASTER_ADDR']
        os.environ['SLURM_NODELIST'] = ' '.join([master_addr] + slurm_node_list)
```

**Comment by edenlightning** [comment]
@jgbos mind sending a PR for this fix?

**Comment by jgbos** [comment]
@edenlightning I currently do this before I run lightning so I  feel my solution is just a *hack* and that there's probably a better solution.  It currently requires the user to set `MASTER_ADDR` first.  If I find some time I'll take a look at the code, maybe come upon a real solution once I see how lightning works here.

**Comment by williamFalcon** [comment]
this is fixed now! no longer needed to hack anything. You can pass your own ClusterEnvironment and do whatever logic you need.

https://pytorch-lightning.readthedocs.io/en/latest/trainer.html#cluster-environment
