### ISSUE TITLE
Integration with Hyperopt

### ISSUE THREAD

**Issue by Ir1d** [PyTorchLightning/pytorch-lightning#248]
**Is your feature request related to a problem? Please describe.**
Hyperopt: Distributed Asynchronous Hyper-parameter Optimization
https://github.com/hyperopt/hyperopt

**Comment by williamFalcon** [comment]
looks cool! but also looks super confusing to use... 
i'd suggest just using test-tube for this.

However, if you feel strongly about adding support for this, then propose a minimal example how this should work at the API level first. Once we agree on a good API, you can make whatever changes to Lightning to support it!

**Comment by Ir1d** [comment]
I was thinking that we might dont want to.integret this. bydefault.
Perhaps we could add an example to docs and show it to those who are interested 🤔

**Comment by williamFalcon** [comment]
agreed. doc example would be good! go for it!

**Comment by williamFalcon** [comment]
@Ir1d want to still do this? if so, we'll reopen

**Comment by Ir1d** [comment]
@williamFalcon I'll do this when I find a proper way :joy:

**Comment by williamFalcon** [comment]
It's likely just a tutorial  #718
