### ISSUE TITLE
CI: proper Conda caching

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#2491]
## 🚀 Feature

Fix the Github action test fro Conda, it seems that the environment is always made from search which takes about 8min even according action readme we shall cache the environment...

### Motivation

Significantly speed-up CI tests using Conda

https://github.com/goanpeca/setup-miniconda#caching

**Comment by Joel-hanson** [comment]
@Borda shall I take this up?

**Comment by Borda** [comment]
@Joel-hanson sure, I have started some work, mind check #2491 first?

**Comment by Joel-hanson** [comment]
@Borda I had gone through the PR and seems like you have covered all the parts which required this change. Is there anything pending or did I miss to check anywhere else?

**Comment by Borda** [comment]
not sure, lets try this one and if it does not help we ll make followup...

**Comment by Joel-hanson** [comment]
Sure thanks 🙂
