### ISSUE TITLE
TPU hangs when using only a train loop (ie: no val loop)

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#2498]
I think it's somehow related to checkpointing.

Easiest way to debug is to get on colab.

**Comment by awaelchli** [comment]
@williamFalcon I struggle to reproduce this. PL does not even recognize the TPUs in the runtime, XLA_AVAILABLE gets set to false (mnist tpu colab). Tried different pytorch and xla versions, all the same. 
Could you share the colab in which you observed the hangs?

**Comment by awaelchli** [comment]
@williamFalcon checked again and now I am able to run the mnist colab without validation and it does not hang anymore (latest master). Not sure what fixed it.
