### ISSUE TITLE
How do I checkpoint depending on the epoch number?

### ISSUE THREAD

**Issue by nervecenter** [PyTorchLightning/pytorch-lightning#2503]
Just to preface, Lightning has been a joy thus far. Everything is concise, well-automated where appropriate, and I converted a Keras model to PyTorch in just a few hours, with no previous PyTorch experience.

To the point, how might I set up a `ModelCheckpoint` to save conditioned on a given arbitrary condition, such as an epoch number? It seems to only be set up to automatically saved based on metrics. It also seems that manually saving is a bit difficult since only the `Trainer` has the proper function to save; given that `LightningModule` features the ability to load from checkpoint, it seems intuitively odd that these are separated between the two classes. Thus, it's difficult to consider the sheer volume of cyclical reference hacking it'd take to pass a trainer to the `LightningModule` to have it save in `on_epoch_end()`.

So yes, without loading the question by presenting my own code attempts, what is the canonical way to save conditioned on an epoch number, or an arbitrary condition?

**Comment by rohitgr7** [comment]
If you want to save on last k epochs or something you can set `monitor=`epoch`` and `mode='max'` in `ModelCheckpoint` callback. Or do you want something like this?
```
if epoch > 4: # epoch number:
    save_checkpoint()
```

**Comment by nervecenter** [comment]
Nonono, I want to save on specific epoch numbers, regardless of condition. For example, 5, 10, 15, 20, 25, etc.

**Comment by rohitgr7** [comment]
You can specify `save_top_k = -1` and `period = 5` in `ModelCheckpoint`.

**Comment by nervecenter** [comment]
Very good. Is there any way to possibly pass in a list of epoch numbers? Then one could do:
```
ModelCheckpoint(
    "...",
    save_top_k=-1,
    period=list(range(1, 51, 5))
)
```

**Comment by nervecenter** [comment]
Yeah, `save_top_k = -1` and `period = 5` don't quite meet my needs. I need to specify a specific starting epoch for the period, or a specific list of epochs to save.

**Comment by rohitgr7** [comment]
I don't think you can do that with ModelCheckpoint yet. But you can override some of the methods of ModelCheckpoint and make it work the way you want by tweaking it a little. Let me know if you need any help overriding these functions, I'll try.
