### ISSUE TITLE
Training with DataParallel (DP) is broken

### ISSUE THREAD

**Issue by aeryen** [PyTorchLightning/pytorch-lightning#2507]
## 🐛 Bug

Currently, the distributed training backend DataParallel (DP) seems to be broken. Using DP will result in error 
`TypeError: zip argument #1 must support iteration`. Below is the last few lines of the call stack:
```
  File "/home/ubuntu/anaconda3/envs/trfm/lib/python3.7/site-packages/pytorch_lightning/overrides/data_parallel.py", line 66, in forward
    return self.gather(outputs, self.output_device)
  File "/home/ubuntu/anaconda3/envs/trfm/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 168, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/ubuntu/anaconda3/envs/trfm/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "/home/ubuntu/anaconda3/envs/trfm/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 62, in gather_map
    for k in out))
  File "/home/ubuntu/anaconda3/envs/trfm/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 62, in <genexpr>
    for k in out))
  File "/home/ubuntu/anaconda3/envs/trfm/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
TypeError: zip argument #1 must support iteration
```

### To Reproduce

Run the following code will always result in this issue.

```
from pytorch_lightning import Trainer, seed_everything
from pl_examples.models.lightning_template import LightningTemplateModel

seed_everything(234)

def main():
    # model = LightningTemplateModel(**vars(args))
    model = LightningTemplateModel()

    trainer = Trainer(
        gpus=2,
        num_nodes=1,
        distributed_backend='dp',
        )

    trainer.fit(model)


if __name__ == '__main__':
    main()
```

### Expected behavior

The trainer should initialize correctly and start training.

### Environment

* CUDA:
        - GPU:
                - Tesla V100-SXM2-16GB
                - Tesla V100-SXM2-16GB
                - Tesla V100-SXM2-16GB
                - Tesla V100-SXM2-16GB
        - available:         True
        - version:           10.2
* Packages:
        - numpy:             1.18.5
        - pyTorch_debug:     False
        - pyTorch_version:   1.7.0.dev20200702
        - pytorch-lightning: 0.8.5-dev
        - tensorboard:       2.2.2
        - tqdm:              4.47.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - 
        - processor:         x86_64
        - python:            3.7.7
        - version:           #30~18.04.1-Ubuntu SMP Mon Jun 22 15:48:21 UTC 2020

**Comment by aeryen** [comment]
From what I can tell, this issue seems to be caused by LightningDataParallel calling **gather** on outputs from **validation_step**. Gather expects a list of tensors but received a list of dicts.

**Comment by nsarang** [comment]
This might be related to #1935

**Comment by aeryen** [comment]
@nsarang oh you are totally right, sorry didn't these before. I'm closing this issue as it's a duplicate of https://github.com/PyTorchLightning/pytorch-lightning/issues/1904
