### ISSUE TITLE
page unresponsive running Lighhtning-demo.ipynb

### ISSUE THREAD

**Issue by foobar8675** [PyTorchLightning/pytorch-lightning#2517]
## 🐛 Bug
I'm getting this when running the demo:

<img width="865" alt="colab" src="https://user-images.githubusercontent.com/1685700/86543397-e30e5b80-bed2-11ea-9d9f-630c4d59a8d3.png">

### To Reproduce

1. click MNIST hello world on https://github.com/PyTorchLightning/pytorch-lightning
2. run in colab

**Comment by foobar8675** [comment]
I feel if it's unresponsive because of tqdm, then a print statements wit the status would a reasonable way to go.

**Comment by williamFalcon** [comment]
Yes, tqdm creashed colab when updated too fast.
set Trainer(progress_bar_refresh_rate=20) or something high

**Comment by foobar8675** [comment]
even at 20, unfortunately, I still get thhe same issue. :(
