### ISSUE TITLE
format_checkpoint_name takes global step

### ISSUE THREAD

**Issue by ruotianluo** [PyTorchLightning/pytorch-lightning#2533]
## 🚀 Feature
Since there is val_check_interval, the model checkpointer could also be enhanced to save in the form of, for example `checkpoint_iter2000.ckpt`, by defining
```checkpoint_callback = ModelCheckpoint(filepath='checkpoint_iter{global_step}')```

https://github.com/PyTorchLightning/PyTorch-Lightning/blob/master/pytorch_lightning/callbacks/model_checkpoint.py#L191

**Comment by rohitgr7** [comment]
If you return `global_step` in `validation_epoch_end` in the log you can save in this form too. But the format will be a little different, something like `checkpoint_iterglobal_step=19.ckpt`.

**Comment by ruotianluo** [comment]
I found that.
My workaround now is:
```
class ModelCheckpoint(pl.callbacks.ModelCheckpoint):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.filename = 'checkpoint_{global_step}'

    def on_validation_end(self, trainer, pl_module):
        trainer.callback_metrics.update({'global_step': trainer.global_step})
        super().on_validation_end(trainer, pl_module)

    def format_checkpoint_name(self, *args, **kwargs):
        return super().format_checkpoint_name(*args, **kwargs).replace('global_step=', '')
```
