### ISSUE TITLE
TPU fp16 requires apex installed

### ISSUE THREAD

**Issue by YuxianMeng** [PyTorchLightning/pytorch-lightning#2539]
When I tried to use precision=16 on TPU, pytorch-lightning is trying to find amp, which is unnecessary.
The backtrace is 
```
GPU available: False, used: False
TPU available: True, using: 8 TPU cores
Traceback (most recent call last):
  File "bert_ner/light/fp16_debug.py", line 16, in <module>
    trainer = pl.Trainer(tpu_cores=8, precision=16)
  File "/anaconda3/envs/torch-xla-1.5/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 607, in __init__
    self.init_amp()
  File "/anaconda3/envs/torch-xla-1.5/lib/python3.6/site-packages/pytorch_lightning/trainer/auto_mix_precision.py", line 27, in init_amp
    "You set `use_amp=True` but do not have apex installed."
ModuleNotFoundError: You set `use_amp=True` but do not have apex installed.Install apex first using this guide and rerun with use_amp=True:https://github.com/NVIDIA/apex#linux his run will NOT use 16 bit precision
```
### To Reproduce

build a whatever Trainer in TPU and use fp16 

#### Code sample

```
import pytorch_lightning as pl

trainer = pl.Trainer(tpu_cores=8, precision=16)
```

### Expected behavior

Should have nothing error.

### Environment

 - PyTorch Version (e.g., 1.5.0):
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information: actually I directly use pytorch-xla-1.5 docker on Google Cloud

**Comment by SkafteNicki** [comment]
If you want to do 16 bit precision training, you either need to have the nightly version of pytorch install or have apex installed. Based on the traceback I guess that you do not have any of them.
I could get this working using nightly version of pytorch:
```
pl.Trainer(precision=16, tpu_cores=8)
>>>GPU available: False, used: False
>>>TPU available: True, using: 8 TPU cores
>>>Using native 16bit precision.
```

**Comment by YuxianMeng** [comment]
> If you want to do 16 bit precision training, you either need to have the nightly version of pytorch install or have apex installed. Based on the traceback I guess that you do not have any of them.
> I could get this working using nightly version of pytorch:
> 
> ```
> pl.Trainer(precision=16, tpu_cores=8)
> >>>GPU available: False, used: False
> >>>TPU available: True, using: 8 TPU cores
> >>>Using native 16bit precision.
> ```

Thanks for the quick reply. But [the document](https://pytorch-lightning.readthedocs.io/en/latest/apex.html) does not point out that I must have nightly version of pytorch installed or have apex installed when training on TPU with fp16. Maybe it's better to revise that part of document?

**Comment by SkafteNicki** [comment]
Yes, I agree that from the documentation it would look like it is only a requirement for gpu training. I guess that the specific requirement for TPU is to have pytorch version 1.6 or higher.
