### ISSUE TITLE
apex amp state dict

### ISSUE THREAD

**Issue by ruotianluo** [PyTorchLightning/pytorch-lightning#2555]
## 🐛 Bug

https://github.com/PyTorchLightning/pytorch-lightning/blob/25ee51bc570503f331dceecc610d0eb355e22327/pytorch_lightning/trainer/training_io.py#L310

It seems for native amp support, the scalar state dict is saved. But for non native amp, the amp state dict is not saved?

**Comment by ruotianluo** [comment]
anyone think it should be fixed?

**Comment by Borda** [comment]
@ruotianluo mind send a PR? 🐰
