### ISSUE TITLE
Simultaneously run multiple optimizers

### ISSUE THREAD

**Issue by ruotianluo** [PyTorchLightning/pytorch-lightning#2559]
Current optimizers are run sequentially.

However, there are cases that two optimizers are used optimized different parts of the network, for example, a CNN+LSTM. one would want CNN to be updated SGD and LSTM to be updated Adam.

**Comment by bradezard131** [comment]
+1, would also be useful for certain types of adversarial cases where the steps are not alternating (e.g. Concrete DropBlock from https://arxiv.org/abs/2004.04725)
