### ISSUE TITLE
Model loaded from checkpoint file has low test score

### ISSUE THREAD

**Issue by JanRuettinger** [PyTorchLightning/pytorch-lightning#2591]
I have trained a model and now I want to load it again from a checkpoint file and test it. Unfortunately, the test scores are really low (not random though). It takes a while to create a minimal viable example (project is quite complex) that's why I am posting these code snippets here. Perhaps you can already spot a mistake I made.

## TransferLearningModel.py
```
class TransferLearningModel(LightningModule):
    
    def __init__(self, config):
        super().__init__()
        
        self.config = config
        # save config dict when saving model
        self.save_hyperparameters(config)
       ....
        self.hparams.learning_rate = self.config["optimizer_initial_lr"]

        ......
```

## training_testing.py
```
config = {
    "model_name": "resnext101_32x8d", 
    "amp_optimization_level": "O1", 
    ...
}

model = TransferLearningModel(config)

trainer = Trainer(...)
trainer.fit(model)

# testing
trainer.test(ckpt_path = filepath)

```

Any idea what I might be doing wrong?

**Comment by awaelchli** [comment]
The only thing I see is you pass the amp optimization level to the model, what's that for?
If you use the training set for testing, do you get the performance matching the training?

**Comment by JanRuettinger** [comment]
I use one config dict to configure the model as well as the trainer. `amp_optimization_level` is used as a parameter for the trainer to specify the apex optimization level.
