### ISSUE TITLE
Unable to run one of the domain_templates

### ISSUE THREAD

**Issue by TheBigTicket02** [PyTorchLightning/pytorch-lightning#2599]
## 🐛 Bug

``
Hi. 
I've tried to run computer_vision_fine_tuning.py from domain_templates on Kaggle.
After first epoch(5) in the second stage, there was an error.

#### Error

`/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/callback_hook.py in on_epoch_start(self)`
`     55         """Called when the epoch begins."""`
`     56         for callback in self.callbacks:`
`---> 57             callback.on_epoch_start(self, self.get_model())`
`     58 `
`     59     def on_epoch_end(self):`

`/opt/conda/lib/python3.7/site-packages/pytorch_lightning/callbacks/lr_logger.py in on_epoch_start(self, trainer, pl_module)`
 `  71 `
  `   72     def on_epoch_start(self, trainer, pl_module):`
`---> 73         latest_stat = self._extract_lr(trainer, 'epoch')`
 `    74         if trainer.logger and latest_stat:`
 `    75             trainer.logger.log_metrics(latest_stat, step=trainer.global_step)`

`/opt/conda/lib/python3.7/site-packages/pytorch_lightning/callbacks/lr_logger.py in _extract_lr(self, trainer, interval)`
`     85                     for i, pg in enumerate(param_groups):`
`     86                         lr, key = pg['lr'], f'{name}/pg{i + 1}'`
`---> 87                         self.lrs[key].append(lr)`
`     88                         latest_stat[key] = lr`
`     89                 else:`

`KeyError: 'learning_rate/pg1'`

 - PyTorch Version torch-1.7.0.dev20200701+cu101 torchvision-0.8.0.dev20200701+cu101:
 - Pytorch-Lightning 0.8.5

**Comment by rohitgr7** [comment]
Tried just now. Not getting any error. Can you share the kaggle notebook??

**Comment by TheBigTicket02** [comment]
Thanks. It was actually my mistake(
