### ISSUE TITLE
torch.save(model) in dump_checkpoint

### ISSUE THREAD

**Issue by davinnovation** [PyTorchLightning/pytorch-lightning#2616]
## 🚀 Feature
Current PL save the only weight of network, but param searched network change their architecture flexibly while training.

`Trainer.(..., save_entier_model=True)` could be option

### Motivation

 After training 'param searched network' with pl and closed session, recognized I cannot load weight! :(

Saving the only state_dict is reasonable in most cases, but give the option to users for saving the whole network will be nice in some cases. 

### Alternatives

Manually save by users

### Additional context

Always thx for cool dev project!

**Comment by rohitgr7** [comment]
Can you share the model code and error?

**Comment by awaelchli** [comment]
The description is not very clear, but think @davinnovation wants to do architecture search (correct me if I'm wrong), where they train several model architectures and they want to save the full architecture to the checkpoint to easily load and remember the model architecture.
@davinnovation can you confirm that this is what you mean?

in this case I would recommend onnx, jit, and all these other model serializers.
