### ISSUE TITLE
resume_from_checkpoint got RuntimeError: Error(s) in loading state_dict for EfficientNet: 	Unexpected key(s) in state_dict: "criterion.pos_weight".

### ISSUE THREAD

**Issue by feiwofeifeixiaowo** [PyTorchLightning/pytorch-lightning#2617]
### To Reproduce

1. train efficient net with pos_weight
```
    def get_criterion(self):
        if not hasattr(self, 'criterion'):
            pos_weight = 3.2
            self.criterion = torch.nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight))
        return self.criterion
```

2. save weight with pl chpt callback

`checkpoint_callback = pl.callbacks.ModelCheckpoint(filepath='../chkpt/-{epoch:02d}-{avg_val_auc:.4f}', prefix=hparams.model_name)`

3. call load_from_checkpoint got error 
`model.load_from_checkpoint('path')`

4. error msg
```
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for EfficientNet:
	Unexpected key(s) in state_dict: "criterion.pos_weight". 

```

### Environment

* CUDA:
	- GPU:
		- GeForce GTX 1080 Ti
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.1
	- pyTorch_debug:     False
	- pyTorch_version:   1.7.0.dev20200701+cu101
	- pytorch-lightning: 0.8.5
	- tensorboard:       2.2.2
	- tqdm:              4.42.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.6
	- version:           #56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020

**Comment by dlrac** [comment]
This happens when you build model differently, `criterion` is not instantiated at all or weights are not instantiated when you are trying to load from checkpoint. In model `__init__` make sure you always have `pos_weight` tensor (e.g. you can use `torch.tensor(1, dtype=torch.float)` for the case when you don't care). 

To be fair, there is a `strict` argument for `torch.load()` which solves this when `strict=False` but I haven't seen Lightning supporting that argument i.e. no way to affect `torch.load()` used inside Lightning implementation of model loading.

**Comment by feiwofeifeixiaowo** [comment]
Thanks @dlrac , i will try this.

> In model __init__ make sure you always have pos_weight tensor (e.g. you can use torch.tensor(1, dtype=torch.float) for the case when you don't care).

**Comment by dlrac** [comment]
@feiwofeifeixiaowo Let me know if it works (it is how I solved it in my case).

**Comment by feiwofeifeixiaowo** [comment]
hi @dlrac ,  it doesn't work in my case. Through your insight, I initialize the criterion in the init function, then fix this.
thanks .

**Comment by entangledloops** [comment]
I had this same problem even inside my model `__init__`. The issue is that the `pos_weight` is stored in the checkpoint, but torch doesn't know how to load it. Lightning `load_from_checkpoint` now supports `strict=False`, which resolved it for me.
