### ISSUE TITLE
Expose load_state_dict strict=False

### ISSUE THREAD

**Issue by shijianjian** [PyTorchLightning/pytorch-lightning#2629]
## 🚀 Feature
In contrastive learning, we normally train a representation learning backbone then adding the classifier. Sometimes, I wish to play with different classifiers. It would be best to have ```strict=False``` exposed to make the model still load with a user's permission.
```python
model = TransferLearningModel.load_from_checkpoint(ckpt_path, strict=False)
```

The implementation is intuitive but an extremely useful feature in my case. Thank you!

**Comment by hbredin** [comment]
This feature would also be very useful for `LightningModule` instances that add a bunch of layers at `setup` time (as `load_from_checkpoint` does not seem to call `setup`).

See [related conversation](https://pytorch-lightning.slack.com/archives/CQXV8BRH9/p1595167276419600) in PytorchLightning Slack.

I'd be happy to try and contribute this (easy, I guess) change if this seems like a good idea.

**Comment by s-rog** [comment]
yeah seems pretty straight forward. Add a `strict` arg with default True to `load_from_checkpoint` that gets passed into `_load_model_state` and into `model.load_state_dict` [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/ed581eb64f105a39c1516527cd733a93f033edcb/pytorch_lightning/core/saving.py#L207)

unless there are other concerns?

**Comment by hbredin** [comment]
I don't foresee any other concern but would like to hear from maintainers before spending some time on such a PR.
