### ISSUE TITLE
multi-node multi-gpu with time constraint and model checkpointing

### ISSUE THREAD

**Issue by vr25** [PyTorchLightning/pytorch-lightning#2634]
Hi,

I am using a multi-node multi-gpu cluster which has a scheduled time limit of 6 hours for the SLURM jobs. 

Is there any quick sample code to understand how to use multi-node and multi-gpu and checkpoint and resume after 6 hours automatically?

Any suggestions would be helpful.

Thanks!

**Comment by awaelchli** [comment]
This should help:
https://pytorch-lightning.readthedocs.io/en/latest/slurm.html
in particular the section about auto-resubmit.

**Comment by vr25** [comment]
@awaelchli Thank you for the link. A follow-up question: How to make sure that it starts from where it left off, checkpointing should help, right?

**Comment by awaelchli** [comment]
Yes, it's supposed to restart from checkpoint. I have never tried it myself, but we're looking into adding multi-node testing so we can guarantee this works smoothly in all cases.

**Comment by vr25** [comment]
I see, thanks for your reply, and yes, built-in multi-node support would be great.
