### ISSUE TITLE
Integer limit_val_batches does not work with infinite DataLoader.

### ISSUE THREAD

**Issue by discharged-spider** [PyTorchLightning/pytorch-lightning#2649]
## 🐛 Bug

Documentation states that you can use limit_val_batches=100 (with integer value) to limit number of batches. However, when using IterableDataset I get the following error:
pytorch_lightning.utilities.exceptions.MisconfigurationException: When using an infinite DataLoader (e.g. with an IterableDataset or when DataLoader does not implement `__len__`) for `limit_val_batches`, `Trainer(limit_val_batches)` must be `0.0` or `1.0`.

### To Reproduce
Just use:
pl.Trainer(val_check_interval=10, limit_val_batches=100)

with infinite DataLoader.

### Expected behavior

Do only N (100 in this case) validation steps.

### Environment

* CUDA:
        - GPU:
                - GeForce GTX 1080 Ti
        - available:         True
        - version:           10.0.130
* Packages:
        - numpy:             1.17.4
        - pyTorch_debug:     False
        - pyTorch_version:   1.3.1
        - pytorch-lightning: 0.8.5
        - tensorboard:       2.2.2
        - tqdm:              4.46.1
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - 
        - processor:         x86_64
        - python:            3.7.4
        - version:           #1 SMP Wed Mar 7 19:03:37 UTC 2018

**Comment by rohitgr7** [comment]
The bug is here:
https://github.com/PyTorchLightning/pytorch-lightning/blob/6d10ac2ac84bc01f78eed381fd6152c869040b64/pytorch_lightning/trainer/data_loading.py#L309-L316
