### ISSUE TITLE
Make use of package extras in setup.py

### ISSUE THREAD

**Issue by nateraw** [PyTorchLightning/pytorch-lightning#2654]
## 🚀 Feature

Right now, to install testing dependencies, you must follow the steps in [Contributing.md](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md):

```
python -m pip install -r requirements/devel.txt
python -m pip install -r requirements/examples.txt
python -m pip install pre-commit
```

 If we make use of the `extras_require` kwarg of `setup()` in setup.py, we can install these extras like this:

```
pip install -e ".[testing]"
# or
pip install -e ".[dev]"
``` 

### Motivation

I would rather run one command to setup my dev/testing environment than having to run multiple.

### Pitch

All we have to do is construct a dictionary in `setup.py` that collects arguments for different 'extra' options.

```python
extras = dict()
extras['dev'] = ['numpy>=1.16.4', 'torch>=1.3', 'tensorboard>=1.14', ...]
extras['test'] = extras['dev'] + ['codecov>=2.1', 'pytest>=3.0.5', ...]
...

setup(
    ...
    extras_require=extras,
)
```

### Alternatives

- We could get rid of `requirements/` folder entirely and let `setup.py` explicitly define the extra requirements
- We could probably populate the `extras` dict from the `requirements/` folder's files if we wanted to, but I think this makes things a touch more confusing (and I'm not sure if you'd have to include the requirements folder when you build the artifact to avoid setup.py from breaking on missing files).

### Additional context

I can submit PR for this if we're interested in doing it. 😄

**Comment by Borda** [comment]
we shall use the requirements listed in folder `requirements` as we do with the base requirements anyway
the question is if we want to have extras as default option? @PyTorchLightning/core-contributors

**Comment by justusschock** [comment]
@Borda I have done something like this before and I really think we should not use it as a default, but instead document what is installed when and really make sure to keep those up to date.

**Comment by williamFalcon** [comment]
no defaults... this is not a common thing people know/do (i have never used it actually). 

We are not re-inventing how installs are done today with PL. We need to keep it simple as it is right now. 

If users want a package they can install it separately

**Comment by Borda** [comment]
> Borda I have done something like this before and I really think we should not use it as a default, but instead document what is installed when and really make sure to keep those up to date.

just check the docs and it is very simple, just add this one dict, which would be loaded from our existing requirements

**Comment by awaelchli** [comment]
is it for development only or for all users?

**Comment by justusschock** [comment]
This would be available for all users then
