### ISSUE TITLE
How to reload partial weights from the trained checkpoint?

### ISSUE THREAD

**Issue by guvcolie** [PyTorchLightning/pytorch-lightning#2656]
#### What is your question?
Now I want to reload partial weights from trained checkpoint and let the remaining parameters trained from scratch. But I didn't find the api that allows me to reload partial parameters.

#### Code
my code is like this, I find pl only support resume_from_checkpoint path to reload all weights from checkpoint.
```
trainer = pl.Trainer(gpus=1, early_stop_callback=None, resume_from_checkpoint=resume_checkpoint, val_check_interval=1000)

trainer.fit(model) 
```

What should I do to reload partial parameters?   Thank you!

**Comment by awaelchli** [comment]
It's all PyTorch! The checkpoints we save are fully compatible with torch.load, so you do your fancy reloading before fit and then give whatever weights you want trained to your optimizers :)

**Comment by guvcolie** [comment]
@awaelchli  got it! thank you!
