### ISSUE TITLE
Validation epoch skipped

### ISSUE THREAD

**Issue by IgorDavidyuk** [PyTorchLightning/pytorch-lightning#2675]
Well, for some reason sometimes validation loop is skipped. I would like to give more details, but python spits out no message.
The progress bar just jumps forward and the print function that I placed in the beginning of validation_step is not being triggered.
I get this behaviour for some datasets. I use several dataloaders and for some the validation happens, but if others appear in dataloaders list the validation is kinda avoided without any message.

So my question is can I enable verbose mode or something?

#### Environment

 - OS: Ubuntu 18.04
 - Packaging: pip
 - Version: last
I use torch 1.5.1 but tried nightly build - the same issue

Thanks for your work.

**Comment by IgorDavidyuk** [comment]
The problem was in dataloaders that I use, obviously.
Somehow length of some dataloaders is greater than number of batches they actually spit out, so the last did not trigger validation epoch start.

**Comment by SamPusegaonkar** [comment]
Hi @IgorDavidyuk 

> The problem was in dataloaders that I use, obviously. Somehow length of some dataloaders is greater than number of batches they actually spit out, so the last batch did not trigger validation epoch start.

Hi Can you expand on this a little? Are you saying that your last batch in your dataloader was not equal to the batch size you set?
