### ISSUE TITLE
Does pytorch-lightning support mixed-precision training?

### ISSUE THREAD

**Issue by zhenhuahu** [PyTorchLightning/pytorch-lightning#2677]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### I know lightning support FP32 and FP16. Does it also support mixed-precision training? I read the source code of trainer.py and found that it supports Apex, but it seems that it only supports all 16-bit or 32-bit training. Am I correct?

Thanks.

#### What's your environment?

 - OS: [e.g. iOS, Linux, Win]: Linux
 - Packaging [e.g. pip, conda]: pip
 - Version [e.g. 0.5.2.1]

**Comment by rohitgr7** [comment]
With `precision=16` you can set `amp_level='O1' or 'O2'`. I think they [are different implementations of mixed precision](https://nvidia.github.io/apex/amp.html?highlight=opt_level#o1-mixed-precision-recommended-for-typical-use).

**Comment by zhenhuahu** [comment]
> With `precision=16` you can set `amp_level='O1' or 'O2'`. I think they [are different implementations of mixed precision](https://nvidia.github.io/apex/amp.html?highlight=opt_level#o1-mixed-precision-recommended-for-typical-use).

Thanks. I may have a misunderstanding here. I thought _precision=16_ denotes only FP16 training. Thank you very much!
