### ISSUE TITLE
training_epoch_end seems to fail when returning nothing

### ISSUE THREAD

**Issue by andrewredd** [PyTorchLightning/pytorch-lightning#2678]
I'm trying to log weight histograms to tensorboard at the end of each training epoch. I have the following code:

```
    def training_epoch_end(self, outputs):
        self.log_hists()
```

This is in line with the documentation. "If you don't need to display anything, Don't return anything"

However when this function runs I get the following error:

```
...
File "/venv/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 499, in run_training_epoch
│    self.run_training_epoch_end(epoch_output)
│  File "/venv/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 533, in run_training_epoch_end
│    _processed_outputs = self.process_output(epoch_output)
│  File "/venv/lib/python3.6/site-packages/pytorch_lightning/trainer/logging.py", line 106, in process_output
│    for k, v in output.items():
│AttributeError: 'NoneType' object has no attribute 'items'
│Exception ignored in: <object repr() failed>
│Traceback (most recent call last):
│  File "/venv/lib/python3.6/site-packages/tqdm/std.py", line 1086, in __del__
│  File "/venv/lib/python3.6/site-packages/tqdm/std.py", line 1293, in close
│  File "/venv/lib/python3.6/site-packages/tqdm/std.py", line 1471, in display
│  File "/venv/lib/python3.6/site-packages/tqdm/std.py", line 1089, in __repr__
│  File "/venv/lib/python3.6/site-packages/tqdm/std.py", line 1433, in format_dict
│TypeError: 'NoneType' object is not iterable```

The fix that I've found is to return a dictionary according to the expected typed return, as follows:

```
    def training_epoch_end(self, outputs):
        self.log_hists()
        return {'dummy': torch.Tensor()}
```

This seems like a bandaid rather than a true fix since I don't need to return anything.

1) Is there a better way to log the histograms to tensorboard?
2) Should I be doing something different in this function?

**Comment by ydcjeff** [comment]
`training_epoch_end` by default doesn't log histogram.
If you want to plot histogram on tensorboard, try `self.logger.experiment.add_histogram()`.

It's [the docs](https://pytorch-lightning.readthedocs.io/en/latest/experiment_logging.html#tensorboard).
PL supports every method of `SummaryWriter` class with `self.logger.experiment.summary_writer_methods`.

**Comment by andrewredd** [comment]
Thanks Jeff!

The log_hists function that I have in the example is logging the entire the
model weights, the biases and the gradients and it does use the referenced
method.  Is the fact that if I don't return something from the function a
bug or user error?

**Comment by ydcjeff** [comment]
@andrewredd sorry for the delayed reply, currently we need to return empty dict in `training_epoch_end` to make it work. But, Lightning will be supporting `return None` in the future.

**Comment by snie2012** [comment]
Running into the same issue

**Comment by edenlightning** [comment]
@williamFalcon are we going to support return None?
