### ISSUE TITLE
Checkpoint saving order

### ISSUE THREAD

**Issue by shtoshni92** [PyTorchLightning/pytorch-lightning#2680]
The last model save action, [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/1369012bc71f257dcf7423ec65146d055ddc1cc7/pytorch_lightning/callbacks/model_checkpoint.py#L295), should be after saving the top k model because the best model and best score could have changed. Swapping the order allows resuming the training from the last checkpoint, with the last checkpoint having the latest information about the best model path/score.

**Comment by awaelchli** [comment]
@shtoshni92 Thanks for the bug report. I fixed this in the linked PR and added a test.
