### ISSUE TITLE
ZeRO for Memory Optimizations

### ISSUE THREAD

**Issue by vchiley** [PyTorchLightning/pytorch-lightning#2695]
## 🚀 Feature
Incorporate the [Zero Redundancy Optimizer (ZeRO)](https://arxiv.org/abs/1910.02054) for distributed training strategies.

### Motivation

Distributed training carries with it a lot of synchronization overheads. Incorporating ZeRO will help alleviate those overheads.

### Pitch

ZeRO will allow users to train distributed models with greater resource utilization.

### Alternatives

Incorporate all the tricks needed for full fp16 training (as done by OpenAI in GPT3) instead of MixedPrecision training (ZeRO does MP training). But MP is more trusted and I don't know how stable the full fp16 training used in GPT3 really is.

**Comment by Borda** [comment]
@vchiley would you be willing to implement it?
cc: @PyTorchLightning/core-contributors

**Comment by vchiley** [comment]
Duplicate of #2695

**Comment by michele-arrival** [comment]
the issue closed because duplicate of itself?

**Comment by erhoo82** [comment]
Seems like no further discussion after the close. Is there a plan to implement this?

**Comment by ananthsub** [comment]
This is already supported. See here for more information: https://pytorch-lightning.readthedocs.io/en/latest/advanced/advanced_gpu.html
