### ISSUE TITLE
Change the default checkpoint filename output to remove the = as in 'epoch=6.ckpt'

### ISSUE THREAD

**Issue by jloveric** [PyTorchLightning/pytorch-lightning#2696]
The default checkpoint name output 'epoch=6.ckpt' has an equal sign in it which does not always play well.  In this case I'm having problems with the latest version of hydra on the command line.  The output could instead be changed to 'epoch.6.ckpt' which would look less like an injection attack!

**Comment by omry** [comment]
Please file a an issue against Hydra. the grammar is new and I went with a more restrictive initial approach. = It's likely that = can be added as a supported character there.
for now you can quote the string for Hydra (not for the shell!).
```
model.checkpoint="/.../checkpoint/epoch=6.ckpt"
```
In the shell you will need to either quote again or escape the `"`.
```
'model.checkpoint="/.../checkpoint/epoch=6.ckpt"'
```
or
```
model.checkpoint=\"/.../checkpoint/epoch=6.ckpt\"
```

**Comment by omry** [comment]
for reference about the new grammar, please check [this](https://hydra.cc/docs/next/advanced/command_line_syntax). It describe quoting and the and shell issues as well.
