### ISSUE TITLE
How to use DataModule and StructResult?

### ISSUE THREAD

**Issue by xiadingZ** [PyTorchLightning/pytorch-lightning#2702]
## ❓ Questions and Help
I see newest has these two  features, and it seems very good.  Bug I can't find docs about how to use them. Can you give some examples? thanks.

**Comment by Borda** [comment]
the docs is coming soon... :rabbit: 
cc: @nateraw @williamFalcon

**Comment by williamFalcon** [comment]
Ok, v1 of the docs are live :)

The quick guide:
https://pytorch-lightning.readthedocs.io/en/latest/new-project.html#step-1-build-lightningmodule
https://pytorch-lightning.readthedocs.io/en/latest/new-project.html#data

The detailed docs for datamodule:
https://pytorch-lightning.readthedocs.io/en/latest/datamodules.html
