### ISSUE TITLE
When I call Trainer.test it calls both "test" and "fit" stages of setup - should it just be "test"

### ISSUE THREAD

**Issue by jloveric** [PyTorchLightning/pytorch-lightning#2715]
## 🐛 Bug
When I call Trainer.test it calls both "test" and "fit" stages of "setup" function.  Shouldn't it just call test?

### To Reproduce

You can actually look through the code to see that this will happen since self.fit() is called.  Follow trainer.test() then choose the function self.__test_given_model(model, test_dataloaders) and then self.fit(model) is called.  Also, you can just print out "stage" in the setup function and you will see both "fit" and "test" are called when trainer.test(model=model, test_dataloaders=dataloaders) is called.  I'm using the "fit" value for training, should I be using something else?

**Comment by rohitgr7** [comment]
Can you check on master? It's fixed #2624.

**Comment by Borda** [comment]
@yukw777 mind have look? :]

**Comment by rohitgr7** [comment]
@Borda it's already fixed on master.
