### ISSUE TITLE
Live long and prosper

### ISSUE THREAD

**Issue by Ceceu** [PyTorchLightning/pytorch-lightning#2716]
This issue is just to thank the PyTorch Lightning team. 

Even though my beginner knowledge over Pytorch and other Deep Learning frameworks, I was able to easily implement a quite complex model that is clearly written and completely reproducible.  

I hope to contribute in some way in the near future.

**Comment by edenlightning** [comment]
Happy to hear that :) Have you checked out our ["good first issue" label](https://github.com/PyTorchLightning/pytorch-lightning/labels/good%20first%20issue)? It has many ideas. Also you can [join our slack channel](https://join.slack.com/t/pytorch-lightning/shared_invite/zt-f6bl2l0l-JYMK3tbAgAmGRrlNr00f1A) to talk some more!
