### ISSUE TITLE
TensorBoard logging in validation_step and test_step

### ISSUE THREAD

**Issue by Ceceu** [PyTorchLightning/pytorch-lightning#2717]
Even defining the log in all steps of the PL model:

```python
    def training_step(self, batch, batch_idx):
        ...
        # TensorBoard logging
        log = {"train_loss": train_loss, "train_mrr": train_mrr}
        return {'loss': train_loss, "log":log}

    def test_step(self, batch, batch_idx):
        ...
        # TensorBoard logging
        log = {"test_loss": test_loss, "test_mrr": test_mrr}
        return {'test_loss': test_loss, 'log': log}

    def validation_step(self, batch, batch_idx):
        ...
        # TensorBoard logging
        log = {"val_loss": val_loss, "val_mrr": val_mrr}
        return {'val_loss': val_loss, 'log': log}
```

I could visualize only the `train_loss` and `train_mrr` on TensorBoard. I mean, `test_loss` and `test_mrr` do not appear in TesorBoard. Similar behavior happens with `val_loss` and `val_mrr`.

**Comment by rohitgr7** [comment]
Usually in pl as of now, logging is done at the `epoch_end` for each train/val/test except for train where it is done at step level too. You can still use `self.logger.experiment.log_metrics()` in step function of val/test to log them at step level.

**Comment by Borda** [comment]
The `test_step` is called only in the test loop, for that you need to call `Trainer.test(...)`

**Comment by ydcjeff** [comment]
Lightning uses `global_step` for plotting in `training_step`, but the reason not logging in `validation_step` and `test_step` is [here](https://pytorch-lightning.slack.com/archives/CRBLFHY79/p1595242017365000?thread_ts=1595180618.360300&cid=CRBLFHY79)

**Comment by Ceceu** [comment]
> Lightning uses `global_step` for plotting in `training_step`, but you probably don't want logging in `validation_step` and `test_step`. [A good explanation by awaelchli](https://pytorch-lightning.slack.com/archives/CRBLFHY79/p1595242017365000?thread_ts=1595180618.360300&cid=CRBLFHY79)

I was unable to access the Slack channel that you had shared.

**Comment by Borda** [comment]
> I was unable to access the Slack channel that you had shared. 

try https://join.slack.com/t/pytorch-lightning/shared_invite/zt-f6bl2l0l-JYMK3tbAgAmGRrlNr00f1A

**Comment by SiddhantRanade** [comment]
How about renaming `global_step` to `global_train_step` (number of training steps) and introducing the variables `global_eval_step` and `global_test_step`?

Similarly, for epoch, we can have additional epoch_val, epoch_test variables. Here, epoch_val indicates the number of times a full eval run has occurred, which may be different from the train_epoch (which is the number of full passes over the training set).

This is most general IMO.
