### ISSUE TITLE
datamodule how to load checkpoint

### ISSUE THREAD

**Issue by xiadingZ** [PyTorchLightning/pytorch-lightning#2718]
## ❓ Questions and Help
Trainer will automatically save a checkpoint. Is this checkpoint shared by model and datamodule, datamodule can load this checkpoint as model `load_from_checkpoint`

**Comment by nateraw** [comment]
The model checkpoint is not shared by the datamodule. I'm not entirely sure what something like this would look like. Do you have any idea of what you'd like to see @xiadingZ ? Would love to hear your thoughts 😄 

As for right now, you save/load your model checkpoint and you can pass any datamodule through that model that is compatible with it. I have a glimpse of an idea where we log a snapshot of the datamodule's code for some reproducibility/traceability reasons....but again, I don't know what this would look like/if it would just make things more confusing.

**Comment by nateraw** [comment]
moving discussion to #3544 as it lays out plans to implement the feature this question is inquiring about.
