### ISSUE TITLE
How to access wandb logging directory from lightning?

### ISSUE THREAD

**Issue by topshik** [PyTorchLightning/pytorch-lightning#2725]
## I want to solve simple task: store .yaml config file in the same folder where checkpoints are saved

I'm using following tools:
1. lightning
2. hydra for reading configs
3. lightning wandb logging interface

I see following options:
1. save everything with hydra to it's `outputs` directory. 
  Pros: directory is easily accessible with `os.getcwd()`, so everything can be managed manually if needed
  Cons: wandb logs are in the separate folder; default checkpoints directory is another (third already) directory, automatically created by lightning
2. save logs, config.yaml and checkpoints to local wandb run directory
  Pros: everything you need is in one place and can be easily analysed or accessed, not spawning to much separate logging directories
  Cons: directory with wandb logs is not accessible from runtime (or, better say, hidden very well), so I can't save anything there. Despite it is possible to set wandb directory manually, I don't want to do it, because it will force me to recreate it for every model launch.

I've tried to google hardly, searching for the best solution, which works with checkpointing callback and wandb logger, but I ended up with saving both checkpoints and .yaml file to hydra directory, which is created for current run.

My current solution is bad, because it stores different logging entities in different places. Moreover, DDP spawns two hydra folders for a run, but that's for another issue, I suppose.

#### Code
```
@hydra.main(config_path="train-config.yaml", strict=False)
def train(config: DictConfig) -> None:
    config.hydra_base_dir = os.getcwd()
    original_wd = hydra.utils.get_original_cwd()
    os.chdir(original_wd)

    checkpoint_callback = ModelCheckpoint(
        filepath=config.hydra_base_dir,
        save_top_k=3,
        verbose=True,
        monitor="val_loss",
        mode="min",
    )
    shutil.copy2("train-config.yaml", os.path.join(config.hydra_base_dir, "train-config.yaml"))

    wandb_logger = WandbLogger(
        offline=False,
    )

    model = MyModel(config)

    trainer = pl.Trainer(
        max_epochs=config.train.max_epochs,
        gpus=config.train.n_gpu,
        auto_select_gpus=True,
        distributed_backend="ddp",
        checkpoint_callback=checkpoint_callback,
        logger=wandb_logger,
    )

    trainer.fit(model)

```

### P.S.
1. I know that wandb saves configs locally to it's folder, but it is still separate from checkpoints. Moreover, it stores config in the format, which should be processed to acquire the structre of original config file.
2. I also know that lightning checkpoint contains model parameters in `hparams` field, but the goal is to store run config in the separate file. 

#### Environment?

 - OS: Ubuntu 18.04
 - Conda, Python 3.7.7
 - hydra-core==0.11.3
- pytorch-lightning==0.8.5
- wandb==0.9.3

**Comment by Borda** [comment]
@borisdayma mind have look? 🐰

**Comment by borisdayma** [comment]
Hi, what do you think about putting the files directly in wandb folder. You can access it with ’wandb.run.dir‘

**Comment by topshik** [comment]
@borisdayma wandb.run.dir cannot be accessed after pytorch_lightning.loggers.WandbLogger object is inited. That is the point of the issue. This happens, because I'm initing logger not from wandb interface but pytorch lightning one. Thus, wandb.run object doesn't exist.

**Comment by borisdayma** [comment]
If the training has not started yet then you can use "WandbLogger.experiment.dir"

**Comment by Junyoungpark** [comment]
Is this problem fixed? I encounter kinda same issue what @topshik experienced.
For me, it was not able to find the path for the specific wandb run.

```
wandb_logger = WandbLogger(entity='sentinel', project='aa')
ckpt_dir = join(wandb_logger.experiment.dir, 'ckpt')
os.mkdir(ckpt_dir)
checkpoint_cb = ModelCheckpoint(monitor='multi_step_loss', 
                                dirpath=ckpt_dir,
                                filename='{epoch:02d}-{multi_step_loss:.2f}',
                                save_top_k=3,
                                mode='min')
```

And the traceback is as follows:
```
Traceback (most recent call last):
  File "/home/silab9/dev/WONIK/GraphPreCO_lighting.py", line 179, in <module>
    main(config)
  File "/home/silab9/dev/WONIK/GraphPreCO_lighting.py", line 156, in main
    config.to_yaml(join(wandb_logger.experiment.dir, "model_config.yaml"))
  File "/home/silab9/anaconda3/envs/gpu_torch/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not method
```

As @borisdayma suggested, I also tried `wandb_logger.experiment.dir` before I setup the `Trainer`.
but I ended up with the  same error. I guess it is because the `WandbLogger` doesn't instantiate the `run` object of wandb before actually training start.

oh btw I used `accelerator='ddp', plugins='ddp_sharded'` for the `Trainer`.

**Comment by Junyoungpark** [comment]
I found a okay solution for this
1) instantiate the wandb `run` results by calling `wandb.init()`
2) Pass the wandb `run` object ot the `WandbLogger` as specifying `experiment=run`

Later calling `run.dir` to get the running directory of the wandb run.

disadvantage of this solution is spawning `n` independent wandb run when using `ddp`. Here, `n` is the
number of gpus.

**Comment by borisdayma** [comment]
I think the main issue is that when you call `wandb_logger.experiment`, it tries to create a run with the config from `Trainer` (as it's typically how it's created).

The 2 options would be:
* Option 1: access the run from the `Trainer` with `trainer.logger.experiment.dir`
* Option 2: create your custom run with `wandb.init()` as you did -> the intended behavior is that the logger does not new runs. Can you confirm you use latest versions of wandb and pytorch-lightning?

**Comment by Junyoungpark** [comment]
@borisdayma Thanks for the comment.

The first option would be hard not enough for my purpose. Maybe one of the typical usages of `wandb` is to log the experiments, including the checkpoints, and save those logs to the wandb cloud such that we can retrieve any logs from the cloud later.

In `pytorch-lightening,` logging the checkpoints are typically done with `ModelCheckpoint` callback, which is required to be instantiated before the trainer object is instantiated. It was not straightforward that altering the saving path of checkpoints to the inside wandb logging directory, which will be generated after calling `trainer.fit()` method. That was the reason I decided to use kind-of the second option.  Is that possible (or more pytorch-lightning way) to implement the codes as I wish above?

I used pytorch-lightning 1.1.0 and wandb 0.10.12

**Comment by borisdayma** [comment]
You should not have to change the saving directory.
Actually `WandbLogger(log_model=True)` should automatically log your model (and checkpoints if you have any).

**Comment by Junyoungpark** [comment]
Oh, that sounds great! 

Can I get a code snippet or documentation about your suggestion? What should I pass `dirtpath` and `filename` for the `ModelCheckPoint` to save all checkpoints to the `wandb.run.dir`? And also can I save any extra files, such as metadata for the experiments, to the `wandb.run.dir` before calling `trainer.fit()` method?

**Comment by borisdayma** [comment]
You should be able to use any value (just keep the default).
At the moment it logs only model checkpoints but we should get more flexibility later with #4903 
You could also manually use W&B artifacts but I hope to make it easy with this integration.

**Comment by Junyoungpark** [comment]
Thanks I will look around the other issue also 👍
