### ISSUE TITLE
AttributeError: module 'pytorch_lightning' has no attribute 'LightningDataModule'

### ISSUE THREAD

**Issue by odats** [PyTorchLightning/pytorch-lightning#2733]
Name: pytorch-lightning
Version: 0.8.5

<img width="670" alt="Screenshot 2020-07-28 at 11 13 38" src="https://user-images.githubusercontent.com/944379/88638111-b6112b00-d0c3-11ea-88dd-f07947d21986.png">

following latest doc: https://pytorch-lightning.readthedocs.io/_/downloads/en/latest/pdf/

**Comment by ydcjeff** [comment]
To use `LightningDataModule`, you have to use latest master or RC release.
You can install RC release with `pip install pytorch-lightning==0.9.0rc2`

**Comment by nateraw** [comment]
Closing, as this is a version issue.

**Comment by aiyolo** [comment]
I suggest adding version description at [datamodules](https://pytorch-lightning.readthedocs.io/en/latest/datamodules.html) page

**Comment by samiede** [comment]
Is this version also available on conda somehow?

**Comment by paul-tqh-nguyen** [comment]
@samiede, I'm not sure if this 100% meets your needs (and I apologize if this is something you already know), but I was able to use `conda` to work around (but not truly solve) the problem of using `conda` to install `pytorch-lightning` by [using `pip` inside my `conda` environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#pip-in-env).

In particular, I ran `conda env create` in a directory with an `environment.yml` that looked like this:
```
name: myenv
dependencies:
  - python=3.7
  - more-itertools
  - conda-forge::typing_extensions
  - pandas
  - matplotlib
  - pytorch==1.4.0
  - pip
  - pip:
    - transformers
    - pandarallel
    - pytorch-lightning==0.9.0rc2
```

**Comment by rnjv** [comment]
Still facing this issue. 

import pytorch_lightning as pl
pl.__version__
1.7.1

**Comment by nateraw** [comment]
@rnjv I just now ran this in Google Colab and it works fine. Also works fine on latest version. There must be an issue with your environment.

<img width="671" alt="Screen Shot 2022-10-18 at 5 46 00 PM" src="https://user-images.githubusercontent.com/32437151/196550953-86a50b29-1ba2-464f-8333-ae2d795ef7f9.png">

**Comment by Nouman-Hasan** [comment]
Getting the same error. Any solution ?

**Comment by ranch-hands** [comment]
> pip install pytorch-lightning==0.9.0rc2

``` [
ERROR: Could not find a version that satisfies the requirement pytorch-lightning==0.9.0rc2 (from versions: 0.0.2, 0.2, 0.2.2, 0.2.3, 0.2.4, 0.2.4.1, 0.2.5, 0.2.5.1, 0.2.5.2, 0.2.6, 0.3, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.4.1, 0.3.5, 0.3.6, 0.3.6.1, 0.3.6.3, 0.3.6.4, 0.3.6.5, 0.3.6.6, 0.3.6.7, 0.3.6.8, 0.3.6.9, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.5.0, 0.5.1, 0.5.1.2, 0.5.1.3, 0.5.2, 0.5.2.1, 0.5.3, 0.5.3.1, 0.5.3.2, 0.5.3.3, 0.6.0, 0.7.1, 0.7.3, 0.7.5, 0.7.6, 0.8.1, 0.8.3, 0.8.4, 0.8.5, 0.9.0, 0.10.0, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.2.9, 1.2.10, 1.3.0rc1, 1.3.0rc2, 1.3.0rc3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.7.post0, 1.3.8, 1.4.0rc0, 1.4.0rc1, 1.4.0rc2, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.8.0rc0, 1.8.0rc1, 1.8.0rc2, 1.8.0, 1.8.0.post1, 1.8.1, 1.8.2, 1.8.3, 1.8.3.post0, 1.8.3.post1, 1.8.3.post2, 1.8.4, 1.8.4.post0, 1.8.5, 1.8.5.post0, 1.8.6, 1.9.0rc0, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 2.0.0rc0, 2.0.0, 2.0.1, 2.0.1.post0, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.9.post0, 2.1.0rc0, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2)
ERROR: No matching distribution found for pytorch-lightning==0.9.0rc2
```
