### ISSUE TITLE
how to resume in the same folder

### ISSUE THREAD

**Issue by etienne87** [PyTorchLightning/pytorch-lightning#2735]
when i launch the pytorch lightning trainer fit(), to resume it seems you can pass one old checkpoint, but i am not sure if it is possible (or perhaps it is chosen not to) to simply resume the current training in the same "version" sub-folder?

**Comment by AAnoosheh** [comment]
I can't get mine to ever create a new "version" folder, no matter what. We seem to have opposite problems.

**Comment by etienne87** [comment]
i launch my training like this:
trainer = pl.Trainer(
            default_root_dir=params.log_dir,
            gpus=1,
            precision=16,
            progress_bar_refresh_rate=20,
            max_epochs=20,
            check_val_every_n_epoch=4,
            resume_from_checkpoint=ckpt,
        )

**Comment by nimral** [comment]
I have the same question. When trying to resume training with 
`python3 main.py fit --config /default_root_dir/lightning_logs/version_34/config.yaml --ckpt_path /default_root_dir/lightning_logs/version_34/checkpoints/last.ckpt`, the new checkpoints and events get saved to `/default_root_dir/lightning_logs/version_35/` and not to `/default_root_dir/lightning_logs/version_34/`

**Comment by Jerrypiglet** [comment]
Same issue. Any workarounds?
