### ISSUE TITLE
How to configure steps of multiple optimizers for GANs

### ISSUE THREAD

**Issue by sergevkim** [PyTorchLightning/pytorch-lightning#2737]
## 🚀 Feature
Custom number of steps in generator and discriminator

### Motivation
I've spent a lot of time looking for some example of using different number of steps for G and D, but I didn't find anything.
However, GANs are very capricious. Is it possible to append this feature?

Maybe I missed it. Can you give me an example of how to use it?

**Comment by nateraw** [comment]
I believe what you're looking for is already built in 😄 ...although it may take a little digging in docs to figure out what to do for your exact intentions/use case.

**These two things might help:**
  1. Refer to documentation on how to [step optimizers differently](https://pytorch-lightning.readthedocs.io/en/latest/optimizers.html#step-optimizers-at-arbitrary-intervals)

```python
# Alternating schedule for optimizer steps (ie: GANs)
def optimizer_step(self, current_epoch, batch_nb, optimizer, optimizer_i, second_order_closure, on_tpu, using_native_amp, using_lbfgs):
    # update generator opt every 2 steps
    if optimizer_i == 0:
        if batch_nb % 2 == 0 :
            optimizer.step()
            optimizer.zero_grad()

    # update discriminator opt every 4 steps
    if optimizer_i == 1:
        if batch_nb % 4 == 0 :
            optimizer.step()
            optimizer.zero_grad()
```

  2. Explicitly define what happens for each optimizer (guidance in docs [can be found here](https://pytorch-lightning.readthedocs.io/en/0.7.1/pl_examples.domain_templates.gan.html#pl_examples.domain_templates.gan.GAN.training_step))

```python
# Multiple optimizers (ie: GANs)
def training_step(self, batch, batch_idx, optimizer_idx):
    if optimizer_idx == 0:
        # do training_step with encoder
    if optimizer_idx == 1:
        # do training_step with decoder
```

Please let me know if this helps, @sergevkim!

**Comment by nateraw** [comment]
I'm fairly sure this and other information in the documentation answers your question, so I'm going to close this. Feel free to reopen if I'm wrong.

**Comment by krenerd** [comment]
New [link](https://pytorch-lightning.readthedocs.io/en/stable/common/optimizers.html#step-optimizers-at-arbitrary-intervals) to documentation for `optimizer_step`
