### ISSUE TITLE
[DataModule] Datamodule setup in docs shows non-existent stage arg

### ISSUE THREAD

**Issue by ydcjeff** [PyTorchLightning/pytorch-lightning#2751]
### To Reproduce

[Colab Minimal code](https://colab.research.google.com/drive/1nzVh8xeEGLOJvSZ0Ih7WccNHgI1gDzaD?usp=sharing)

### Expected behavior

DataModule should call `prepare_data` and `setup`

### Environment

- Colab

### Additional context

PL Version: 0.9.0rc3

**Comment by Borda** [comment]
I guess it was changed recently, @nateraw mind update docs? 🐰 
or @ydcjeff mind sending a PR with update according to actuals code...

**Comment by ydcjeff** [comment]
I think @nateraw has updated the docs along in #2755
