### ISSUE TITLE
How to suppress GPU/TPU device information warnings

### ISSUE THREAD

**Issue by import-antigravity** [PyTorchLightning/pytorch-lightning#2757]
#### What is your question?
I'm training lots of modules in succession in a Jupyter notebook and I set `weights_summary=None` in the trainer in order to stop having the model summary print over and over again, but the following GPU/TPU information is printing:

<img width="1040" alt="Screen Shot 2020-07-29 at 4 46 04 PM" src="https://user-images.githubusercontent.com/24441495/88856936-00290800-d1bb-11ea-9efb-7850bc0a674c.png">

#### What have you tried?

I've tried using the `warnings` package to suppress warnings, I've tried the `%%capture output` magic, neither have worked.

#### What's your environment?

 - OS: iOS
 - Packaging conda
 - Version 0.8.5

**Comment by awaelchli** [comment]
Hi
Does this work?
```python
import warnings
warnings.filterwarnings('ignore')
```

**Comment by Borda** [comment]
it is level `logging.INFO` so setting something above like `logging.WARNING`
see docs: https://docs.python.org/3/library/logging.html#logging-levels

**Comment by import-antigravity** [comment]
I can try ‘logging’. Like I said in my original post I already tried ‘warnings’
