### ISSUE TITLE
Enable option to use Apex when PyTorch 1.6 is installed

### ISSUE THREAD

**Issue by Anjum48** [PyTorchLightning/pytorch-lightning#2788]
## 🚀 Feature

Currently, if PyTorch 1.6 is installed, PyTorch Lightning will use native AMP by default. It would be useful to have an option to force PL to use Apex if needed, which is not currently possible

### Motivation

Native AMP is great but under certain conditions may perform differently to Apex. For debugging purposes and backwards compatibility, having the option to still use Apex might be useful.

In my particular problem, I needed to roll back to PT 1.5 since I was seeing different behaviour between the two. Having the option to switch between the two AMP methods would make it easier to diagnose my issue.

### Pitch

Have a flag to force the Trainer to use Apex over native AMP

**Comment by calclavia** [comment]
Same here. I notice some results could no longer be replicated now that I upgraded to PT 1.6 and lightning 0.8.5 (which may be related to FP16).
