### ISSUE TITLE
how to run m validation batches after running every n training batches?

### ISSUE THREAD

**Issue by benwu232** [PyTorchLightning/pytorch-lightning#2799]
## 🚀 Feature

For example, I'm runing a model on a big dataset. After every 10000 training batches, I'd like to run 1000 validation batches to  check the avg_traning_loss and avg_val_loss. 

I tried val_check_interval but it just run all validation dataset, which is too big and time consuming. How to validate only part of the validation data?

This is similar to #2534 with something different. 

Thanks a lot!
Ben

**Comment by ydcjeff** [comment]
I think `Trainer(limit_val_batches=1000, val_check_interval=10000)` will do that.

**Comment by benwu232** [comment]
@ydcjeff  Working like a charm! Thank you very much! How do you find these magic parameters? :)

**Comment by ydcjeff** [comment]
@benwu232 from https://pytorch-lightning.readthedocs.io/en/latest/trainer.html#limit-val-batches

**Comment by nateraw** [comment]
Looks like this is sorted out, so I'm closing it. Thank you @ydcjeff 😄

**Comment by benwu232** [comment]
@ydcjeff Thanks again!  :)
