### ISSUE TITLE
AttributeError on lr_find with half precision

### ISSUE THREAD

**Issue by SimonNarendorf** [PyTorchLightning/pytorch-lightning#2804]
## 🐛 lr_find crash with mixed precision

initial run of lr_find raise AttributeError when run with 16Bit precison

### To Reproduce

1. Init module and trainer with precision=16
2. Run trainer.lr_find(module)

`AttributeError: 'NoneType' object has no attribute 'state_dict'`

Stacktrace:

```
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_io.py in dump_checkpoint(self, weights_only)
    360             # save native amp scaling
    361             if self.use_amp and NATIVE_AMP_AVALAIBLE and not self.use_tpu:
--> 362                 checkpoint['native_amp_scaling_state'] = self.scaler.state_dict()
    363 
```

#### Code sample
```
module = new LightningModule(...)
trainer = Trainer(max_epochs=10, precision=16)
trainer.lr_find(module, min_lr=1e-06, max_lr=1e-01, early_stop_threshold=None)
```

### Environment

You can get the script and run it with Torch 1.6.0+cu101, Torchvision 0.7.0+cu101, CUDA 10.1, Lightning 0.8.5

**Comment by awaelchli** [comment]
Could this be because we don't restore the scaler attribute after the lr_find has finished @SkafteNicki?

**Comment by SkafteNicki** [comment]
This happens because the `scaler` is setup during the `run_pretrain_routine` but a checkpoint is tried to save beforehand in the learning rate finder, since we need to restore to this after running the search.

**Comment by edenlightning** [comment]
@SkafteNicki whats the fix here?

**Comment by rohitgr7** [comment]
why not just make lr_find, and scaling batch_size work in a way that it logs the optimized learning_rate / batch_size and add a log for the user to adjust the learning_rate / batch_size manually and reinitialize model / datamodule and call `trainer.fit`.

**Comment by edenlightning** [comment]
@Borda any idea what the fix here is?

**Comment by edenlightning** [comment]
@SimonNarendorf can you upgrade to the latest version to see if issue persists?
