### ISSUE TITLE
WandbLogger(log_model=True) seems to have no effect

### ISSUE THREAD

**Issue by sooheon** [PyTorchLightning/pytorch-lightning#2805]
## 🐛 Bug

When initializing WandbLogger with log_model=True, user expects the logger to save the best k checkpoints to wandb on train end. 

### To Reproduce

1. Initialize `wandb_logger = WandbLogger(log_model=True)`
2. Initialize `trainer = pl.Trainer(logger=wandb_logger, early_stop_callback=True)`
3. `trainer.train(model, tdl, vdl)`
4. When training finishes, check the wandb dashboard -- there are no associated files or artifacts with the run.

#### Code sample

Be logged into wandb

```python
import numpy as np
import pytorch_lightning as pl
import torch
import torch.nn.functional as F
import wandb
from pytorch_lightning.callbacks import ModelCheckpoint
from pytorch_lightning.loggers import WandbLogger
from sklearn.datasets import make_classification
from torch.utils.data import DataLoader


class LitModel(pl.LightningModule):

    def __init__(self):
        super().__init__()
        self.l1 = torch.nn.Linear(20, 2)

    def forward(self, x):
        return torch.relu(self.l1(x))

    def training_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self(x)
        loss = F.cross_entropy(y_hat, y)
        return {'loss': loss}

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=0.0005)

    def validation_step(self, batch, batch_idx):
        return self.training_step(batch, batch_idx)

    def validation_epoch_end(self, outputs):
        losses = []
        for m in outputs:
            losses.append(m['loss'])
        return {'log': {'val_loss': torch.stack(losses).mean()}}


X, y = make_classification(n_samples=1000)
X = X.astype(np.float32)
y = y.astype(np.long)
dataset = list(zip(X, y))

dl = DataLoader(dataset[:800])
vdl = DataLoader(dataset[800:])

wandb_logger = WandbLogger(log_model=True)
checkpointer = ModelCheckpoint(save_top_k=3)
trainer = pl.Trainer(logger=wandb_logger,
                     checkpoint_callback=checkpointer,
                     max_epochs=10)

model = LitModel()

trainer.fit(model, dl, vdl)

```

### Expected behavior

WandbLogger utilizes the checkpoint callback, and saves the best model weights to wandb, using [artifacts](https://www.wandb.com/artifacts)

### Environment

```
* CUDA:
	- GPU:
		- Tesla V100-SXM2-16GB
		- Tesla V100-SXM2-16GB
		- Tesla V100-SXM2-16GB
		- Tesla V100-SXM2-16GB
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0
	- pytorch-lightning: 0.8.5
	- tensorboard:       1.15.0
	- tqdm:              4.48.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		-
	- processor:
	- python:            3.7.7
	- version:           #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07)
```

### Additional context

In general, it's a little unclear how `trainer.default_root_dir`, `ModelCheckpoint.filepath` and `WandbLogger.save_dir` interact. I can create a separate ModelCheckpoint callback, and after the training ends upload to wandb:

```python
wandb_logger = WandbLogger(log_model=True)
checkpointer = ModelCheckpoint(save_top_k=3)
trainer = pl.Trainer(logger=wandb_logger,
                     checkpoint_callback=checkpointer,
                     max_epochs=10)

model = LitModel()

trainer.fit(model, dl, vdl)
artifact = wandb.Artifact(f'{wandb_logger.experiment.name}_model', type='model')
for path, val_loss in checkpointer.best_k_models.items():
    artifact.add_file(path)
wandb_logger.experiment.log_artifact(artifact)
```

However, this is now "experiment code" outside of the trainer abstraction. Ideally this should be handled by the wandblogger and checkpointer in conjunction, and gracefully handle early sigint and so on.

**Comment by Borda** [comment]
@borisdayma mind have look? 🐰

**Comment by borisdayma** [comment]
@sooheon If you go to the file menu on wandb dashboard do you see your model?

![image](https://user-images.githubusercontent.com/715491/89157836-c3e70600-d532-11ea-9580-95de9771c279.png)

**Comment by sooheon** [comment]
@borisdayma I do not. Just some config files.
<img width="394" alt="Screen Shot 2020-08-03 at 4 44 09 PM" src="https://user-images.githubusercontent.com/302945/89158096-8fae2c80-d5a8-11ea-82ff-04d9ed407c57.png">

**Comment by awaelchli** [comment]
It's because the save dir is just the root dir of the logger. The ModelCheckpoint callback actually determines the final checkpoint dir. By default it will create a path of the form save_dir / logger name / logger version. But the trainer could also specify weights_save_dir, or the model checkpoint callback can be configured to save it elsewhere. The logger does not know where the checkpoints will be saved. 
The current log_model argument we have here is wrong. It cannot work like that. We need a creative solution :)

**Comment by sooheon** [comment]
If I were to try to add this Artifact creation and upload code to some pl.Trainer or pl.LightningModule method(s), what is the right place for it?

```
artifact = wandb.Artifact(f'{wandb_logger.experiment.name}_model', type='model')
for path, val_loss in checkpointer.best_k_models.items():
    artifact.add_file(path)
wandb_logger.experiment.log_artifact(artifact)
```

**Comment by awaelchli** [comment]
if you want it in your LightningModule, then the `on_train_end` hook, or make a callback class and add these lines in the `on_train_end` callback method.

Hooks:
https://pytorch-lightning.readthedocs.io/en/latest/hooks.html#general-hooks
Callback:
https://pytorch-lightning.readthedocs.io/en/latest/callbacks.html#callback-base

**Comment by sooheon** [comment]
Thanks, with the following I'm getting artifacts uploaded properly if training ends as normal (i.e. hitting max_epochs). However, if I interrupt training with Ctrl-C, the files are added to the artifact but fail to upload to wandb. I have also tried the same code in `on_keyboard_interrupt`, but the result is the same.

```python
class WandbArtifactCallback(pl.Callback):
    def on_train_end(self, trainer, pl_module):
        run = trainer.logger.experiment
        print(f'Ending run: {run.id}')
        artifact = wandb.Artifact(f'{run.id}_model', type='model')
        for path, val_loss in trainer.checkpoint_callback.best_k_models.items():
            print(f'Adding artifact: {path}')
            artifact.add_file(path)
        run.log_artifact(artifact)
```

**Comment by borisdayma** [comment]
This is probably related to #2059

**Comment by borisdayma** [comment]
I checked and all checkpoints seem to be saved correctly.
See [this colab](https://colab.research.google.com/drive/1AUPRCyeSN7miViMMU5bfmbpyLvgHadKu?usp=sharing)

As for interrupting training with Ctrl + C, this seems to be already filed as #2059 so if there are no more comments related to checkpoints I would suggest to close this issue.
