### ISSUE TITLE
Metric on all test data

### ISSUE THREAD

**Issue by Ceceu** [PyTorchLightning/pytorch-lightning#2809]
Is there an approach to handle scenarios in which the metric calculated during test_step depends on the entire test set and not just the existing data in the batch?

**Comment by awaelchli** [comment]
Hi, do you mean you want to have all outputs from your model in test_epoch_end, and then compute a metric over all of them? You can do that by returning your predictions in the output dict of the test_step method and in test_epoch_end you will get a list of all of them. Would that work in your usecase?

**Comment by Ceceu** [comment]
I am currently working on an information retrieval model that encodes both `query` and the `document` into dense vectors of size equal to `768`.
Then, in `test_step` I would like to calculate metrics like `MRR` (Mean Reciprocal Rank) to the entire test set.

Save test_step `outputs` will work. However, as my model outputs embedding the best practice maybe is to save the model and use it in another test environment.

**Comment by SkafteNicki** [comment]
@Ceceu Class based metrics have been revamped!
Your case is very similar to `ExplainedVariance` metric (https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/metrics/regression/explained_variance.py), as this metric also requires access to all predictions and targets to compute the metric values in the end. Please, check this out to see if this could solve your problem.

**Comment by Ceceu** [comment]
> @Ceceu Class based metrics have been revamped!
> Your case is very similar to `ExplainedVariance` metric (https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/metrics/regression/explained_variance.py), as this metric also requires access to all predictions and targets to compute the metric values in the end. Please, check this out to see if this could solve your problem.

Thanks @SkafteNicki, 

I'll check it. Currently, I'm saving the predictions into a file (using EvalResult) and the metric is computed after the train step.

**Comment by Ceceu** [comment]
> @Ceceu Class based metrics have been revamped!
> Your case is very similar to `ExplainedVariance` metric (https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/metrics/regression/explained_variance.py), as this metric also requires access to all predictions and targets to compute the metric values in the end. Please, check this out to see if this could solve your problem.

@SkafteNicki,

Where is stored the [state variable](https://github.com/PyTorchLightning/pytorch-lightning/blob/89e8796e2a14429541f923b2ecf8fd7079c32a65/pytorch_lightning/metrics/regression/explained_variance.py#L92)? Can't that lead to an overflow of memory?

**Comment by SkafteNicki** [comment]
It is stored on the same device as your model. You are completely right that this can lead to out of memory errors, however to my understanding it is impossible to compute such metrics without having access to all predictions and targets. This is the very reason for this warning:
https://github.com/PyTorchLightning/pytorch-lightning/blob/89e8796e2a14429541f923b2ecf8fd7079c32a65/pytorch_lightning/metrics/regression/explained_variance.py#L94-L98

**Comment by sick78** [comment]
Canada

**Comment by sick78** [comment]
things are purchased within app to certify

**Comment by sick78** [comment]
i send u a quick vid n u see

**Comment by sick78** [comment]
gimme a sec

**Comment by Ceceu** [comment]
> It is stored on the same device as your model. You are completely right that this can lead to out of memory errors, however to my understanding it is impossible to compute such metrics without having access to all predictions and targets. 

Would it be possible to calculate a metric from predictions saved in disk using one of the methods below?

https://github.com/PyTorchLightning/pytorch-lightning/blob/471ca375babad9093abf60683a8d0647ac33d4a8/pytorch_lightning/core/lightning.py#L347-L352

If so, someone could use `test_step` to save `predictions_dict` and in `test_epoch_end` to calculates the metric. 
What do you think about it?

**Comment by SkafteNicki** [comment]
I definitely think that would work. It would probably be a good enhancement in the future to allow metrics a generic way of saving to disk, and automatically loading during the `.compute()` step.

**Comment by sick78** [comment]
http://www.passiveprofitpages.com/index1.html?hop=puisong&vendor=passivepag


Sent from my iPhone

**Comment by sick78** [comment]
https://www.financialfreedom-forever.co/video31538819/?p1=1853&p2=02fecffc7cc749ac9abb89a391cc1a1d


Sent from my iPhone

**Comment by sick78** [comment]
https://coinmarketcap.com/alexandria/glossary


Sent from my iPhone

**Comment by sick78** [comment]
https://coinmarketcap.com/guides/blockexplorer#more-market-data


Sent from my iPhone

**Comment by sick78** [comment]
https://assets.website-files.com/5d0125b82bca931b917653b8/5d01402a01d01eaac8ebf45d_Screen%20Shot%202019-06-12%20at%202.09.04%20PM.png


Sent from my iPhone

**Comment by sick78** [comment]
i know what i’m talking bout


Sent from my iPhone

**Comment by sick78** [comment]
https://ssl.clickbank.net/order/c/clickw/img/cws%20banner-min.png


Sent from my iPhone

**Comment by sick78** [comment]
call to order this https://github.com/30-seconds/30-seconds-of-code

Sent from my iPhone

**Comment by sick78** [comment]
my commisions cycle commissions still locked please fix  asap 

Sent from my iPhone
