### ISSUE TITLE
Shouldn't LightningDataModule inherit abc.ABC to have @abstractmethod decorator works properly ?

### ISSUE THREAD

**Issue by roytseng-tw** [PyTorchLightning/pytorch-lightning#2815]
https://github.com/PyTorchLightning/pytorch-lightning/blob/a55c481d5d27028bd34024705d79cbea66c48d32/pytorch_lightning/core/datamodule.py#L89

To ensure all abstract methods are overridden, one should inherit `abc.ABC` or set `metaclass=abc.ABCMeta`.
Like below,
```python
class _DataModuleWrapperABCMeta(_DataModuleWrapper, ABCMeta):
    pass


class LightningDataModule(metaclass=_DataModuleWrapperABCMeta):  # pragma: no cover
```
However, this way will require user to explicitly define all three (train/val/test) dataloaders, even if some are not actually needed.

**Comment by nateraw** [comment]
@roytseng-tw I ran into some issue when I tried to inherit from abc.ABC while doing initial implementation. Sounds like what you suggested would work, though.

Mind submitting a quick PR? I can assign you to this.

**Comment by nateraw** [comment]
> However, this way will require user to explicitly define all three (train/val/test) dataloaders, even if some are not actually needed.

I think that this is not what we want. the point is that you don't have to define them. Perhaps better not to go this route then. If you have any other suggestions, let me know. otherwise, maybe we close this?

**Comment by roytseng-tw** [comment]
If that is not what we want, then maybe we shouldn't mark those methods using `@abc.abstractmethod`. Otherwise, false positive pylint warning will complain about abstractmethod not overridden.
Instead, we can `raise NotImplementedError` in dataloader methods.

**Comment by nateraw** [comment]
I think having `raise NotImplementedError` is also not what we want, because all hooks in a DataModule are optional. You might have a test dataset or you might not. You may have a dm setup, or potentially you take care of that within LightningModule setup. Because of that, I'm going to close this for now

**Comment by indigoviolet** [comment]
@nateraw: mypy also has an annoying false positive warning because of these @abstractmethod decorators -- we should just remove them if we intend for them to be optional. I think this is not the intended purpose of @abstractmethod
