### ISSUE TITLE
Generalize i/o to other storage systems

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#2825]
### Motivation

Support checkpointing from storage systems, facebook is using this -> https://github.com/facebookresearch/fvcore/blob/master/fvcore/common/file_io.py

Solution should be similar to what is[ proposed here](https://github.com/PyTorchLightning/pytorch-lightning/pull/2175).

**Comment by f4hy** [comment]
I believe #2164 resolved this.
