### ISSUE TITLE
Support Slash Seperator for TrainResult / EvalResult for TensorBoard

### ISSUE THREAD

**Issue by wxc-kumar** [PyTorchLightning/pytorch-lightning#2843]
## 🚀 Feature
TensorBoard [supports and recommends grouping tags prefixed with slashes](https://github.com/tensorflow/tensorboard#tags-giving-names-to-data). Tags are group under the same drop down with other tags that share the prefix. For example:
```
step
step/train_loss
step/val_loss

epoch
epoch/train_loss
epoch/val_loss
```

Currently, both [TrainResult and EvalResult prefix the results with an underscore](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/core/step_result.py#L104) (i.e. `step_` and `epoch_`). For compatibility with TensorBoard, please support the slash separator or provide user configurable argument to set the separator.

**Comment by justusschock** [comment]
cc @williamFalcon

**Comment by awaelchli** [comment]
The user-configureable way is to simply do this with the current API (there are no more Results objects):
```python
self.log("step/metric", metric, on_step=True, on_epoch=False)
self.log("epoch/metric", metric, on_step=False, on_epoch=True)
```
