### ISSUE TITLE
This is really a bad idea. what if someone really don't want to sample/shuffle their data during training.

### ISSUE THREAD

**Issue by chu-NMSU** [PyTorchLightning/pytorch-lightning#2857]
https://github.com/PyTorchLightning/pytorch-lightning/blob/633cf76c686357c88f2d6397fa316ed710004184/pytorch_lightning/trainer/data_loading.py#L146

**Comment by awaelchli** [comment]
Most users want that. But if you don't, then you can turn it off by setting the flag in the Trainer and provide your own sampler. 
https://pytorch-lightning.readthedocs.io/en/latest/trainer.html#replace-sampler-ddp
Feel free to reopen if that doesn't solve your problem.

**Comment by chu-NMSU** [comment]
> Most users want that. But if you don't, then you can turn it off by setting the flag in the Trainer and provide your own sampler.
> https://pytorch-lightning.readthedocs.io/en/latest/trainer.html#replace-sampler-ddp
> Feel free to reopen if that doesn't solve your problem.

Thank you awaelchli. This solves my problem!
