### ISSUE TITLE
Metrics error due to inplace operation, "computation has been modified by an inplace operation". 

### ISSUE THREAD

**Issue by sykrn** [PyTorchLightning/pytorch-lightning#2862]
Hey, @williamFalcon, I got a new error since I upgraded the library today.
I used the accuracy metric, but got an error.

### Code sample:
```
# in lightning module
def training_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self(x)
        loss = F.cross_entropy(y_hat, y)
        acc = accuracy(y_hat, y)      # from the functional metric classification
        tensorboard_logs = {'train_loss': loss}
        return {'loss': loss, 'log': tensorboard_logs}
```

### Error msg:
```
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.LongTensor [32]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

### Can be *solved* using `.clone()` method.
However, when I clone the `y` before feeding to the accuracy function, no error was shown.
```
acc = accuracy(y_hat, y.clone())
````
But, it's inconvenience if user has to do it manually, isn't it? 
Actually, I can use the code above without `clone` before I upgrade to the latest. So, it might due to the latest update/rebase causing this error.

> The same error shown for `f1_score` metric.

**Comment by williamFalcon** [comment]
cc @justusschock

**Comment by justusschock** [comment]
cc @Diuven , I think you introduced in-place ops for speed-up, right?

**Comment by Diuven** [comment]
> cc @Diuven , I think you introduced in-place ops for speed-up, right?
> Does the speedup only come from inplace methods or can we simply replace them by out-of-place methods ?

Yeah, you're right. I think this is because of the `clamp_max_` I used in `stat_scores_mulitple_classes`. [This](https://github.com/Diuven/pytorch-lightning/blob/7195b1dff618eb23d8341eb83fe84fb9167c93b9/pytorch_lightning/metrics/functional/classification.py#L184) is the part.

[This](https://github.com/PyTorchLightning/pytorch-lightning/pull/2878) is a quick PR fixing this issue. If you may, please check the code still gives the issue.

Sorry for the inconvenience!

**Comment by sykrn** [comment]
Great, It runs without any error, now. Thanks for the hotfix. 👍
