### ISSUE TITLE
Throw warning for changing val_loss

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#2868]
Add warning to user that when changing val_loss to another keyword it will break checkpointing, early stopping, and other features relying on it.

**Comment by shivin7** [comment]
Hi @edenlightning, newcomer here. Is it okay if I work on this?

**Comment by shivin7** [comment]
Hi @Borda, newcomer here. Can I work on this?

**Comment by Borda** [comment]
@shivin7 perfect, go ahead! 🎉
