### ISSUE TITLE
Throw warning for using monitor in trainer

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#2869]
In the init method for monitor checkpoint, we should throw a warning for calling monitor key inside the trainer.

**Comment by edenlightning** [comment]
@teddykoker mind tackling this one? should be simple

**Comment by teddykoker** [comment]
@edenafek can you elaborate on this one? Not sure what you mean here ...

**Comment by awaelchli** [comment]
https://github.com/PyTorchLightning/pytorch-lightning/blob/7b64472ced732c6762978f2a3a844f6ef5261157/pytorch_lightning/callbacks/model_checkpoint.py#L310

**Comment by Borda** [comment]
> https://github.com/PyTorchLightning/pytorch-lightning/blob/7b64472ced732c6762978f2a3a844f6ef5261157/pytorch_lightning/callbacks/model_checkpoint.py#L310

heh, I dont like this `m="""..."""` formatting :D
