### ISSUE TITLE
is it better to return num_classes in get_num_classes()?

### ISSUE THREAD

**Issue by aiyolo** [PyTorchLightning/pytorch-lightning#2886]
if `num_classes != num_all_classes`, I think it is better to return `num_classes` rather than raise an error

https://github.com/PyTorchLightning/pytorch-lightning/blob/f798cffd02a0b6cbdc3033c981501c1a0c4677bd/pytorch_lightning/metrics/functional/classification.py#L67-L92

**Comment by rohitgr7** [comment]
It's not raising an error, just a warning, will still return `num_classes`.
