### ISSUE TITLE
unexpected keyword argument 'amp_type' in trainer __init__() 

### ISSUE THREAD

**Issue by JanRuettinger** [PyTorchLightning/pytorch-lightning#2896]
## 🐛 Bug

Versions used: 
- Pytorch: 1.6.0
- Pytorch Lightning: 0.9.12rc.

```
trainer = Trainer(amp_type='apex', ...)
```
Error message: `__init__() got an unexpected keyword argument 'amp_type'`

### To Reproduce
Init trainer as shown above.

**Comment by awaelchli** [comment]
The init of which class? could you paste the full stacktrace? Can't reproduce sorry.

**Comment by JanRuettinger** [comment]
Thanks for you help! When I try to run this line from the documentation I get the error mentioned above.
<img width="867" alt="Screenshot 2020-08-09 at 23 29 53" src="https://user-images.githubusercontent.com/8582703/89742212-3e1a0c00-da98-11ea-854a-186f15372ccc.png">

**Comment by awaelchli** [comment]
Cannot reproduce on r12. Could you paste the error message please?

**Comment by williamFalcon** [comment]
this arg was renamed a few days later
