### ISSUE TITLE
Unable to train with 8 cores TPU

### ISSUE THREAD

**Issue by krisho007** [PyTorchLightning/pytorch-lightning#2914]
## 🐛 Bug

Unable to train with TPU cores = 8. It trained one full fold, and it failed during the next fold.
I have a validation loop and it still fails. I am trying on kaggle.

### To Reproduce

Fork edit this notebook and run on TPU
 
https://www.kaggle.com/krisho007/fork-of-melanoma-with-pylightning

### Additional context
* CUDA:
	- GPU:
	- available:         False
	- version:           10.2
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.5.0
	- pytorch-lightning: 0.8.5
	- tensorboard:       2.2.2
	- tqdm:              4.45.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.6
	- version:           #1 SMP Thu Aug 6 20:22:07 PDT 2020

**Comment by ArmanMazdaee** [comment]
I have encountered the same issue and I am suspected that the source of the bug is in the `ModelCheckpoint`.
If the `checkpoint_callback` parameter of the Trainer set to `False` the training could continue with out any problem.

**Comment by rohitgr7** [comment]
`New entrants are currently not allowed. You will be able to accept the rules and submit late predictions after the competition completes.` In the meantime try it with master??

**Comment by krisho007** [comment]
Not sure what I am doing wrong. I get below error when I try to instal the mater on Kaggle notebook. 
`ERROR: Command errored out with exit status 1: /opt/conda/bin/python3.7 /opt/conda/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-5a_ig8hg/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel Check the logs for full command output.`

**Comment by rohitgr7** [comment]
`pip install git+https://github.com/PytorchLightning/pytorch-lightning.git@master --upgrade`
Not working??

**Comment by rohitgr7** [comment]
Try:
```bash
!pip uninstall -q typing --yes
!pip install -U git+https://github.com/PytorchLightning/pytorch-lightning.git@master
```

**Comment by Borda** [comment]
@krisho007 feel to reopen if needed 🐰
