### ISSUE TITLE
add graph to Tensorboard logger

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#2915]
## 🚀 Feature

adding a graph to TB logger as it is shown here
https://www.learnopencv.com/tensorboard-with-pytorch-lightning/
maybe also add histograms...

### Motivation

![image](https://user-images.githubusercontent.com/6035284/89909431-581a3280-dbef-11ea-9969-1d5ff15107ac.png)

**Comment by Fan-Luo** [comment]
Hi,

I am trying to add the computational graph to tensorboard with
      ` self.logger.experiment.add_graph(TriviaQA(self.args), sampleInput)`

but got the error message
 
>  File "./.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 742, in _check_trace
>     raise TracingCheckError(*diag_info)
> torch.jit.TracingCheckError: Tracing failed sanity checks!
> ERROR: Graphs differed across invocations!
 
(~30000 lines after `Graph diff`)

> 
> First diverging operator:
> 	Node diff:
> 		- %9 : __torch__.torch.nn.modules.linear.___torch_mangle_226.Linear = prim::GetAttr[name="linear_sp_sent"](%self.1)
> 		?                                                        ^^^
> 		+ %9 : __torch__.torch.nn.modules.linear.___torch_mangle_470.Linear = prim::GetAttr[name="linear_sp_sent"](%self.1)
> 		?                                                        ^^^
> 
> 

I tried one solution in the similar issue (https://github.com/pytorch/pytorch/issues/23993) by not declare `sampleInput` as a variable, but does not work.
The other solution mentioned is to set `check_trace` to False. But I do not call `torch.jit.trace` directly.

Another issue (https://github.com/PyTorchLightning/pytorch-lightning/pull/3003) mentioned one requirement: user has defined the `model.example_input_array` attribute, but I assume it is only for automatically logging the computational graph, right?

Any other solution I can try?

Thank you

**Comment by JakobHavtorn** [comment]
It would be nice to be able to pipe arguments for `torch.jit.trace` through `.add_graph()` as `kwargs` such that we can disable the trace checking for stochastic models.
