### ISSUE TITLE
ModelCheckpoint with custom filepath don't support training on multiple nodes

### ISSUE THREAD

**Issue by angshine** [PyTorchLightning/pytorch-lightning#2916]
## 🐛 Bug
When training on multiple nodes using `ModelCheckpoint` with custom `filepath`, it will raise `FileExistsError` caused by the following line of code: [model_checkpoint.py#L127](https://github.com/PyTorchLightning/pytorch-lightning/blob/97e6f35b34437c89d422bd440dca4a8d2c4d5a9f/pytorch_lightning/callbacks/model_checkpoint.py#L127). 

Maybe a try-except block is needed?

**Comment by awaelchli** [comment]
No I think we just need to pass in exists=True :)

**Comment by awaelchli** [comment]
@f4hy your PR added this line. Do you know a good way to fix it?

**Comment by f4hy** [comment]
Ah sorry. I think I know what's up. I'll get a patch out this evening. Sorry!

**Comment by f4hy** [comment]
@angshine I found a few issues with the model checkpoint path stuff. Not 100% sure I found the particular bug you were seeing but I think this should fix it. Can you give my branch in the above PR a test? Sorry to have introduced this bug for you.

**Comment by angshine** [comment]
Sorry for the late reply, but it seems that this bug has not been fully fixed. [This line](https://github.com/PyTorchLightning/pytorch-lightning/blob/ee72271d205beb2c012e34425cb16e189cc56c7d/pytorch_lightning/utilities/cloud_io.py#L88) still raises an exception:  `tensorboard.compat.tensorflow_stub.errors.AlreadyExistsError: Directory already exists` when training with DDP. I still need to manually add a `try-except` to ignore the exception.

**Comment by f4hy** [comment]
@angshine That line has been completely replaced now on master. Can you give it another try. I hope #3320  has finally resolved this.
