### ISSUE TITLE
How can I get the unused parameters from `find_unused_parameters`?

### ISSUE THREAD

**Issue by cinjon** [PyTorchLightning/pytorch-lightning#2919]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?

I searched both of the above and it seems like `find_unused_parameters` is on by default (https://github.com/PyTorchLightning/pytorch-lightning/blob/b7d72706c3696afafb2519e3ff3715d2bf295606/pytorch_lightning/overrides/data_parallel.py#L180), however I am getting an associated error when I try to use >1 gpu:

```
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
```

How do I get the report back as to what are the unused output tensors?

#### What's your environment?

 - OS: [e.g. iOS, Linux, Win]: Linux
 - Packaging [e.g. pip, conda]: Conda
 - Version [e.g. 0.5.2.1]: pytorch 1.6.0 / pl 0.8.5

**Comment by gusdnd852** [comment]
Did you solve this problem?

**Comment by SapirWeissbuch** [comment]
Is there a solution to this?

**Comment by lucadiliello** [comment]
I found [here](https://discuss.pytorch.org/t/how-to-find-the-unused-parameters-in-network/63948/4) that you can print all the parameters which gradient is `None`.

```python
for name, param in model.named_parameters():
    if param.grad is None:
        print(name)
```
