### ISSUE TITLE
ddp_backend in 0.9.0rc12 fails if no CUDA_VISIBLE_DEVICES found

### ISSUE THREAD

**Issue by ananthsub** [PyTorchLightning/pytorch-lightning#2942]
## 🐛 Bug
In ddp_backend, training immediately fails if the environment variable CUDA_VISIBLE_DEVICES isn't set. This line should handle the None case gracefully: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/accelerators/ddp_backend.py#L90

### To Reproduce
Start a run using ddp on CPU. This was discovered using torchelastic to launch

### Expected behavior
This shouldn't crash if the environment variable isn't set. We could default to `num_gpus = 0` in this case. 
Replacing the line above with something like this could work:

`num_gpus = os.environ.get('CUDA_VISIBLE_DEVICES', []).split(',').__len__()
`

**Comment by ananthsub** [comment]
This is a bug in our usage of distributed backend, not an issue with lightning

**Comment by Borda** [comment]
@ananthsub good catch, mind send a PR?

**Comment by ananthsub** [comment]
@Borda reading more about the accelerator changes, I am confused about the split between ddp and ddp_cpu backends. For example, if the user wants to launch training with torchelastic or a non-slurm launcher, then we use the ddp backend. This will fail if the training is on CPUs. The docs aren't updated with the latest changes either: https://pytorch-lightning.readthedocs.io/en/latest/multi_gpu.html#distributed-modes

**Comment by Borda** [comment]
the `ddp` is GPU based compare to `ddp_cpu` is CPU only...

**Comment by ananthsub** [comment]
@Borda in our test case, we launch with these trainer parameters: 
`{'max_epochs': 25, 'gpus': 0, 'num_nodes': 1, 'distributed_backend': 'ddp', 'default_root_dir': '/tmp/'}
`
and this is the stacktrace we run into:
```
    trainer.fit(self)
  File "pytorch_lightning/trainer/states.py", line 34, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File "pytorch_lightning/trainer/trainer.py", line 1030, in fit
    results = self.accelerator_backend.spawn_ddp_children(model)
  File "pytorch_lightning/accelerators/ddp_backend.py", line 90, in spawn_ddp_children
    num_gpus = os.environ['CUDA_VISIBLE_DEVICES'].split(',').__len__()
  File "/usr/lib/python3.7/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'CUDA_VISIBLE_DEVICES'
```
In such cases, should we default the `distributed_backend` to None and let lightning figure out the backend for us, based on gpus and nodes? https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/distrib_data_parallel.py#L251-L266
