### ISSUE TITLE
Issue with pl.Trainer.from_argparse_args(...)

### ISSUE THREAD

**Issue by amitness** [PyTorchLightning/pytorch-lightning#2943]
### To Reproduce

1. Use `parser = pl.Trainer.add_argparse_args(parser)`
2. Run `python main.py --overfit_batches 1` 
3. The training runs over the whole dataset instead of running on a single batch

![Screenshot from 2020-08-13 13-45-55](https://user-images.githubusercontent.com/8587189/90109358-6ab97680-dd6b-11ea-92d9-f1d47aea8435.png)

### Expected behavior
Only one batch should have run.

### Environment

* CUDA:
	- GPU:
		- Tesla P100-PCIE-16GB
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0+cu101
	- pytorch-lightning: 0.8.5
	- tensorboard:       2.3.0
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

**Comment by williamFalcon** [comment]
thanks. looking at it
