### ISSUE TITLE
Global Step Graph looks incorrect?

### ISSUE THREAD

**Issue by shreyaskamathkm** [PyTorchLightning/pytorch-lightning#2952]
## 🐛 Bug

The graph should be a straight line and should not drop as seen in the figure below:

### To Reproduce

Just including wandb logger in the trainer.

![image](https://user-images.githubusercontent.com/16343884/90157446-bebc5f00-dd5b-11ea-95bb-6a911452dbda.png)

**Comment by williamFalcon** [comment]
the gaps are the validation calls. global step is for training loop. 

run it again without the validation loop (or turn it off)
