### ISSUE TITLE
Make it easy to disable logging/checkpoints

### ISSUE THREAD

**Issue by import-antigravity** [PyTorchLightning/pytorch-lightning#2958]
## 🚀 Feature

Introduce an easy way to disable logging and checkpoints for `Trainer` instances.

### Motivation

Sometimes when training a model you don't want to keep any logs or checkpoints, and there doesn't appear to be an obvious way to do that.

### Pitch

The most obvious way to implement this would be to make it so when `log_save_interval=0` the logger never writes to the disk.

### Alternatives

As I understand it the current way to do this would be to make some sort of dummy class which inherits `LightningLoggerBase` but doesn't actually do anything. This strikes me as unnecessarily involved.

**Comment by rohitgr7** [comment]
set `checkpoint_callback=False` and `logger=False`.

**Comment by import-antigravity** [comment]
Okay, awesome. Thanks!
