### ISSUE TITLE
TensorBoardLogger not saving hparams without metrics

### ISSUE THREAD

**Issue by s-rog** [PyTorchLightning/pytorch-lightning#2971]
## 🐛 Bug

`log_hyperparams` for `TensorBoardLogger` saves no data with default `metrics=None`, only hparam entries/names show up in sidebar

### To Reproduce

```
import pytorch_lightning as pl
logger = pl.loggers.TensorBoardLogger("./test_logs")
test_dict = {"test":0}
logger.log_hyperparams(test_dict)                      ## no data saved
logger.log_hyperparams(test_dict, test_dict)           ## works
logger.log_metrics(test_dict)                          ## works
logger.experiment.add_hparams(test_dict, test_dict)    ## works but saves in a different events file
```

### Expected behavior
hparams data is saved and viewable via tensorboard with default args

### Proposed solution
For default hparams logging without metrics, add a placeholder metric? I can do a PR if this is appropriate.

**Comment by s-rog** [comment]
```
logger.log_hyperparams({"hp_1":1,"hp_2":2}, {"test_m":0})
### training
logger.log_hyperparams({"hp_1":10,"hp_2":20}, {"test_m":1})
```

by calling log_hyperparams again at the end of training with the same metric name, the value can be updated... however it does mess up the graph for said metric... so there would have to be a dedicated metric for hparams

**Comment by justusschock** [comment]
This is duplicate of #2406 . The issue we have there, is that usually you log these params at the end, but we cannot guarantee them to be logged for crashes then.

**Comment by s-rog** [comment]
My bad, will move discussions over there
