### ISSUE TITLE
Would it be possible to have a boiler template codebase for Pytorch-lighthing / Sagemaker training, serving ?

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#2977]
### Motivation

In production env, Pytorch Lightning seems like a great option. I was wondering if you could provide a boiler template for serving / training with Sagemaker integration.

**Comment by justusschock** [comment]
Hi @tchaton , we're not yet at the point, where we consider production, but we're thinking about that as well. I am not sure, if our first version will include a pagemaker example, but definitely we will provide some interface for deployment in the future (probably after our first stable release).

**Comment by tchaton** [comment]
Dear @justusschock,

Thanks for answering me !
I am going to give a try with my team.
 If we come up something nice enough, I would share it with you guys.

Best regards,
T.C

**Comment by tchaton** [comment]
I have found this example which can adapted to be a template: https://github.com/awslabs/amazon-sagemaker-examples/blob/master/aws_marketplace/creating_marketplace_products/Bring_Your_Own-Creating_Algorithm_and_Model_Package.ipynb

And this amazing repo too: https://github.com/SeanNaren/deepspeech.pytorch

**Comment by tchaton** [comment]
Hey @justusschock,

I have started to work on it: https://github.com/tchaton/sagemaker-torch-template

Best regards,
Thomas Chaton.

**Comment by justusschock** [comment]
Thanks, @tchaton , could you ping me, if you got a running version?

**Comment by tchaton** [comment]
Hey @justusschock,

Do you have a Slack where it would be more convenient to talk ? I have some questions about Pytorch Lightning. I want to make sure it will be compatible with my template.

Best regards,
Thomas Chaton.

**Comment by justusschock** [comment]
Sure, there's a slack link in our readme

**Comment by tchaton** [comment]
Hey @justusschock,

Thanks. Training is working fine 👍 
Tqdm to teak and some trouble with hydra new structured config, but It should be solve quickly.

<img width="1610" alt="Screenshot 2020-08-16 at 15 43 46" src="https://user-images.githubusercontent.com/12861981/90337003-64c7cd80-dfd7-11ea-8bc9-7c14dbb0f501.png">

Best regards,
T.C

**Comment by austinmw** [comment]
@tchaton hey, any updates on this?
