### ISSUE TITLE
"limit_train_batches" not receiving float value

### ISSUE THREAD

**Issue by asrafulashiq** [PyTorchLightning/pytorch-lightning#2989]
## 🐛 Bug

error: argument --limit_train_batches: invalid int value: '0.3'

### To Reproduce
 Just put any float value after '--limit_train_batches' or '--val_check_interval'

I am using the latest master branch. 0.9.rc14

I think this issue is related to the fix of #2943

**Comment by williamFalcon** [comment]
@Borda i think you have to do that thing again to enable both floats and ints from add_argparse_args
