### ISSUE TITLE
Calling pl.TrainResult causes an exception

### ISSUE THREAD

**Issue by xhlulu** [PyTorchLightning/pytorch-lightning#2991]
[The docs](https://pytorch-lightning.readthedocs.io/en/latest/loggers.html) shows the following code snippet:
```
def training_step(self, batch, batch_idx):
    loss = ...

    result = pl.TrainResult(minimize=loss)
    result.log('train_loss', loss)
    return result
```

However, calling `pl.TrainResult` in v0.8.5 causes an exception:
```
AttributeError: module 'pytorch_lightning' has no attribute 'TrainResult'
```

This happened with:
* Torch: 1.5.1
* Environment: Kaggle kernels

**Comment by rohitgr7** [comment]
try latest `0.9.0rc14` `pip install pytorch-lightning==0.9.0rc14`

**Comment by awaelchli** [comment]
I can confirm, on 0.8.5 import fails, but it is working on the latest release.
