### ISSUE TITLE
Add TPU support

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#300]
Although still experimental, we should add the according support for it. Likely as a distributed backend flag?

I'm not familiar with the TPU APIs but I assume there is a DP and DDP version? So, something like
```python
Trainer(distributed_backend='tpu_dp')
Trainer(distributed_backend='tpu_ddp')
```

**Comment by Borda** [comment]
shall we catch this one in 0.6.1 or next 0.6.2 as you mentioned we already have nice features...
