### ISSUE TITLE
valdation_epoch_end won't log if no logging is done in validation_step

### ISSUE THREAD

**Issue by rohitgr7** [PyTorchLightning/pytorch-lightning#3000]
## 🐛 Bug
@edenlightning looks like setting both logger=False and prog_bar=False won't do anything. If this is intended, maybe we should add a warning or something.

Also saw another issue, if I don't log anything in validation_step then logged values in validation_epoch_end won't be logged too even if we set logger=True. Updated the notebook attatched above for the same to verify.

#### Code sample
https://colab.research.google.com/drive/1Os9oSPK_rwwutcFdZTDsBaMc2IrqkSrP#scrollTo=3BJmPqHwX6WA

### Environment
pl: master
env: colab

**Comment by rohitgr7** [comment]
@edenlightning looks like setting both `logger=False` and `prog_bar=False` won't do anything. If this is intended, maybe we should add a warning or something.

Also saw another issue, if I don't log anything in `validation_step` then logged values in `validation_epoch_end` won't be logged too even if we set `logger=True`. Updated the notebook attatched above for the same to verify.

**Comment by edenlightning** [comment]
Edited the original bug with the current issue.

**Comment by rohitgr7** [comment]
@edenlightning it's resolved in a recent PR. Forgot to close it. Will close now.
