### ISSUE TITLE
ModelCheckpoint does not create full path

### ISSUE THREAD

**Issue by ydcjeff** [PyTorchLightning/pytorch-lightning#3001]
### To Reproduce

Run `checkpoint_callback = ModelCheckpoint('my/path/')`
Only `my` folder is created.

I think [this line](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/callbacks/model_checkpoint.py#L126) discard the last trailing slash. So the directories are not created as intended when the paths are getting split.

### Expected behavior

Path should be fully created.

**Comment by awaelchli** [comment]
I do not think that the trailing slash is the root problem. We also want that "my/path" should be interpreted as a path to a folder. 
I think a reasonable fix is to force the user to provide the extension when they want a file. This way, we can easily differentiate between folders and files.

**Comment by rohitgr7** [comment]
how about two parameters, `dirpath and filename`? `dirpath` should be required and `filename` can be optional?

**Comment by awaelchli** [comment]
I don't think we can make it required, because we have `default_root_dir` in Trainer, which should work as expected.

**Comment by ydcjeff** [comment]
@awaelchli I mean trailing slash isn't the problem, discarding the last trailing slash is the problem.

**Comment by rohitgr7** [comment]
yeah it can be optional, no problem

**Comment by rohitgr7** [comment]
but @ydcjeff it should work with both 'my/path/' and 'my/path'.

**Comment by awaelchli** [comment]
I think what jeff want's to say is that 

`path, filename = os.path.split("a/b/c")
`

vs.

`path, filename = os.path.split("a/b/c/")`

in the former, filename = "c", and in the latter filename = ""

**Comment by ydcjeff** [comment]
yes, it's that.

**Comment by rohitgr7** [comment]
I think separate parameters `dirpath and filename` would be more flexible for the user.

**Comment by edenlightning** [comment]
Anyone can send a PR?

**Comment by rohitgr7** [comment]
let's discuss it on #3583. The approach suggested there will solve this issue.
