### ISSUE TITLE
Checkpoint files location when WandbLogger 

### ISSUE THREAD

**Issue by ksasi** [PyTorchLightning/pytorch-lightning#3002]
I am trying to look for checkpoint files when using WandbLogger. However checkpoint files doesn't seem to be exist in wandb folder as well. This is despite the fact that log_model=True is setup in WandbLogger. Please help me on this, I am not sure if I am missing something on this.

OS is macOS Mojave. However I noticed the issue on Colab, didn't run on my local machine though.

**Comment by awaelchli** [comment]
Hi, can you post 
1. the arguments you pass into your wandblogger
2. the output messages in the terminal from wandb
I just tested it running 2 epochs with the cpu_example, and for me it uploads at the end of the training.

**Comment by ksasi** [comment]
Hi,

Below are the configuration details :

from pytorch_lightning.loggers import WandbLogger
wandb_logger = WandbLogger(name='SSCNN-Run-streamlit',project='limited_vocabulary_speech_recognition', log_model=True)

trainer = Trainer(max_epochs=2, gpus=1, logger = wandb_logger, progress_bar_refresh_rate = 20)

Output messages : 

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
CUDA_VISIBLE_DEVICES: [0]
Logging results to Weights & Biases (Documentation).
Project page: https://app.wandb.ai/ksasi/limited_vocabulary_speech_recognition
Run page: https://app.wandb.ai/ksasi/limited_vocabulary_speech_recognition/runs/3pq6wolw
and the progress bar.

**Comment by timothybrooks** [comment]
Any update on why the WandbLogger doesn't save checkpoints when `log_model=True` is set? Is there a workaround to log checkpoints to the correct wandb location easily?

**Comment by borisdayma** [comment]
Hi, I tested it and the last model is saved for me. See [colab](https://colab.research.google.com/drive/16d1uctGaw2y9KhGBlINNTsWpmlXdJwRW?usp=sharing#scrollTo=CxXtBfFrKYgA)

**Comment by awaelchli** [comment]
Ok, looked at it again. We are missing the `wandb.finish` call. I spotted that thanks to @borisdayma's notebook which makes the call at the end. Let me send a PR and you guys test it out?
