### ISSUE TITLE
`type_as` bug in the doc of LightningModule

### ISSUE THREAD

**Issue by szywise** [PyTorchLightning/pytorch-lightning#3005]
## 🐛 Bug

When I run [this line of code](https://github.com/PyTorchLightning/pytorch-lightning/blame/master/docs/source/lightning-module.rst#L54) in the doc, it complains that `type_as` shouldn't be given a `str`.

#### Code sample

The last line of the following code
```python
x = torch.zeros(2, device='cpu')
new_x = torch.zeros(3, device='cuda:0')
new_x = new_x.type_as(x.type())
```
gives this error:
```plain
TypeError: type_as(): argument 'other' (position 1) must be Tensor, not str
```

### Expected behavior

Cast `new_x` to the same type as `x`.

A potential fix:
```python
new_x = new_x.type_as(x)
```

### Environment

```plain
* CUDA:
        - GPU:
                - GeForce RTX 2080
                - GeForce RTX 2080
        - available:         True
        - version:           10.2
* Packages:
        - numpy:             1.18.5
        - pyTorch_debug:     False
        - pyTorch_version:   1.5.1
        - pytorch-lightning: 0.9.0rc5
        - tensorboard:       2.2.2
        - tqdm:              4.47.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.3
        - version:           #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020
```

**Comment by awaelchli** [comment]
In the example you linked, it creates a new tensor. 
This way
`new_x = x.new_empty(2, 3)`
the tensor will have the same device and dtype and does not need to be copied to the new device.

We should prevent this from getting into the docs by replacing the code block by
`.. testcode:: `
which will run the code and reveal such errors immediately.
