### ISSUE TITLE
Auto-scaling batch-size not compatible with half precision training

### ISSUE THREAD

**Issue by iantimmis** [PyTorchLightning/pytorch-lightning#3025]
Using `precision=16` and `auto_scale_batch_size=True` yields `'NoneType' object has no attribute 'state_dict'` error

### Expected behavior

Largest batch size should be found when using 16 bit precision

### Environment
- PyTorch Version (e.g., 1.0): 1.6
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.8
 - CUDA/cuDNN version: 10/7
 - GPU models and configuration: 2080ti

**Comment by Borda** [comment]
it seems that loading has some issue
@iantimmis are interested in sending a PR?
