### ISSUE TITLE
Loading model and self.conf

### ISSUE THREAD

**Issue by hmdolatabadi** [PyTorchLightning/pytorch-lightning#3031]
I'm using pl to train a model. I read my config and turn it into an object using:

```
class obj(object):
def __init__(self, d):
        for a, b in d.items():
            if isinstance(b, (list, tuple)):
               setattr(self, a, [obj(x) if isinstance(x, dict) else x for x in b])
            else:
               setattr(self, a, obj(b) if isinstance(b, dict) else b)
```

Then, I pass this config to my model and set its variables.
I trained my model without any bugs.
Now, when I want to load the ckpt, I use the exact same code and config, but it gives me this error:

```
 ...self.model = UNet(self.conf.model.in_channel,
AttributeError: 'dict' object has no attribute 'model'
```

And this is my model definition:

```
class my_model(pl.LightningModule):
    def __init__(self, conf):
        super().__init__()
        self.conf  = conf
        self.model = UNet(self.conf.model.in_channel,
                                      self.conf.model.channel)
```

Could you tell me what is going on? Because I didn't have any issue in training my model, and this is happening only when I'm using the .load_from_checkpoint. 

Thanks.

**Comment by hmdolatabadi** [comment]
Isn't there an answer?

**Comment by SkafteNicki** [comment]
Could you provide a full traceback or preferably a colab notebook where we can reproduce your error

**Comment by hmdolatabadi** [comment]
```
Traceback (most recent call last):
  File "train.py", line 237, in <module>
    model = denoising_model.load_from_checkpoint('./model_1.ckpt')
  File "/home/user/.conda/envs/idf/lib/python3.7/site-packages/pytorch_lightning/core/saving.py", line 169, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, *args, **kwargs)
  File "/home/user/.conda/envs/idf/lib/python3.7/site-packages/pytorch_lightning/core/saving.py", line 205, in _load_model_state
    model = cls(*cls_args, **cls_kwargs)
  File "train.py", line 127, in __init__
    self.model = UNet(self.conf.model.in_channel,
AttributeError: 'dict' object has no attribute 'model'
```

**Comment by hmdolatabadi** [comment]
I'm (almost) sure that when I read to load ckpt the model gets defined twice, once when I do it (in which self.conf is correctly an object) and another time where the self.conf is a dict, while it isn't...

**Comment by SkafteNicki** [comment]
I guess that could be the problem. Hard to say. If you can put together a simple colab notebook I can investigate this further.

**Comment by AustinT** [comment]
I'm having a similar issue. I believe that if you initialize your model with a Namespace object (e.g. `def __init__(self, hparams: argparse.Namespace)`), this gets converted to a dict upon loading from a checkpoint. Unlike a `Namespace`, the keys of the dict cannot be accessed as attributes, and so you get an error.

The relevant lines would be here: https://github.com/PyTorchLightning/pytorch-lightning/blob/cc205f6a652c20259339113802cb633f7811f4b6/pytorch_lightning/core/saving.py#L162-L167

I've managed to solve it by converting to a `Bunch` object (see https://github.com/dsc/bunch). However this is a hack. Not sure how to best solve this.

**Comment by awaelchli** [comment]
Don't you need to call `self.save_hyperparameters()`?

**Comment by hmdolatabadi** [comment]
It seems that there's a problem with saving such hyperparameters.
I tried your suggestion, and called the `self.save_hyperparameters()` but it gave me the following error:

`
Traceback (most recent call last):
  File "train.py", line 240, in <module>
    denoising_diffusion_model = my_model(conf).cuda()
  File "train.py", line 127, in __init__
    self.save_hyperparameters(conf)
  File "/home/user/.conda/envs/idf/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1704, in save_hyperparameters
    self._set_hparams(hp)
  File "/home/user/.conda/envs/idf/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1714, in _set_hparams
    raise ValueError(f'Unsupported config type of {type(hp)}.')
ValueError: Unsupported config type of <class '__main__.obj'>.
`

**Comment by edenlightning** [comment]
@hmdolatabadi were you able to find a workaround?

**Comment by hmdolatabadi** [comment]
No, I just load the model directly instead of using the .load_from_checkpoint to avoid this issue.

**Comment by Borda** [comment]
otherwise, could you share a full code sample, this is almost impossible to reproduce...

**Comment by hmdolatabadi** [comment]
> otherwise, could you share a full code sample, this is almost impossible to reproduce...

Here's my entire repository where I encountered the problem. I believe it's reproducible.
