### ISSUE TITLE
Epoch counting is one-off in multiple instances

### ISSUE THREAD

**Issue by AAnoosheh** [PyTorchLightning/pytorch-lightning#3032]
🐛 Bug

Two issues occur:

1. The final epoch does not save a checkpoint during training.
2. Resuming from a checkpoint N will start the epochs at N+2.

### Expected behavior

1. Final checkpoint should save a .ckpt file, as usual.
2. Should resume from epoch N+1.

### Environment

```
* CUDA:
	- GPU:
		- Tesla V100-DGXS-16GB
		- Tesla V100-DGXS-16GB
		- Tesla V100-DGXS-16GB
		- Tesla V100-DGXS-16GB
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.1
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0
	- pytorch-lightning: 0.9.0rc12
	- tensorboard:       2.2.1
	- tqdm:              4.46.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		-
	- processor:         x86_64
	- python:            3.7.7
	- version:           #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020
```

**Comment by awaelchli** [comment]
@AAnoosheh Honestly I do not understand how the PR you linked relates to the bug your report. Did you mean to link another issue? 

> The final epoch does not save a checkpoint during training.

I don't experience this. The epoch number is 0-indexed, and by default it only saves best checkpoints. Could one of these reasons be why you may think this is a bug?

How can I reproduce the second issue?

**Comment by AAnoosheh** [comment]
Sorry I should have clarified I use the following to save every epoch:

`pl.callbacks.ModelCheckpoint(save_top_k=-1, verbose=True)`

The second is done via `Trainer(resume_from_checkpoint=some_ckpt_file)`

I assume some change was made to move epochs to 0-index, when previously they were 1-indexed, and there's a mismatch now.

**Comment by ananyahjha93** [comment]
@AAnoosheh so when you run ```pl.callbacks.ModelCheckpoint(save_top_k=-1, verbose=True)``` all the checkpoints are saved, however we do not save the last one as 'last.ckpt'. Also, the checkpoints are numbered from 0, so if you run for 4 epochs, the last checkpoint saved will be 'epoch=3.ckpt' and when you resume, it resumes from the expected 5th epoch.
