### ISSUE TITLE
0.9.0 rc16  tensorboard 2.3.0 can't find hparams data

### ISSUE THREAD

**Issue by xiadingZ** [PyTorchLightning/pytorch-lightning#3033]
tensorboard version: 2.3.0
pytorch-lightning version: 0.9.0 rc16

my code:
```
class Video_Base(pl.LightningModule):
    def __init__(self, hparams, *args, **kwargs):
        self.hparams = hparams
```
tensorbord 2.2.0 is ok, 2.3.0 can't show hparams, says no hparams data found

**Comment by ananyahjha93** [comment]
@xiadingZ instead of setting self.hparams, can you try using ```self.save_hyperparameters()``` to save anything into self.hparams passed to the LightningModule?

**Comment by Borda** [comment]
lets freeze TB==2.2.0 for now and reopen this after 0.9 is out...

**Comment by teddykoker** [comment]
Freezing TB, #3039, will reopen after 0.9
