### ISSUE TITLE
Using multiple trainers vs. single trainer if `max_epochs` needs to change.

### ISSUE THREAD

**Issue by MarioIshac** [PyTorchLightning/pytorch-lightning#3037]
### Before asking:   
I've looked at [Issue with running multiple models in PyTorch Lightning](https://github.com/PyTorchLightning/pytorch-lightning/issues/2807) which talks about using multiple trainers for multiple models.

#### What is your question?
I want to clarify when I should be using multiple trainers vs. one trainer if I'm trying to train a bunch of models (all of `BaseModel`, a custom subclass of `pytorch_lightning.LightningModule`) which only differ among their hyperparameters (and there hyperparameters are provided as `hparams` in the instantiation of `BaseModel`). The catch is that the max epochs is a hyperparameter in my case.

#### Code

Given that `train_model` is being called for each `model` I want to train, do I go this route:

```
def train_model(model: BaseModel):
    trainer = pytorch_lightning.Trainer(..., max_epochs=model.hparams.max_epochs)
    trainer.fit(model)
```

or this route:

```
trainer = pytorch_lightning.Trainer(...)

def train_model(model: BaseModel):
    trainer.max_epochs = model.hparam.max_epochs
    trainer.fit(model)
```

Everything else about the trainer remains unchanged after initialization (such as `gpus`, `logger`, `early_stop_callback`, etc, this is all part of the `...`). Only `max_epochs` needs to change.

#### What's your environment?

 - OS: Ubuntu 20.04
 - Packaging: pip
 - Version: 0.8.5

**Comment by awaelchli** [comment]
I would choose the first option, because the Trainer saves some state (e.g. in the loggers) that you probably don't want to reuse in the following model that will train. 
Besides, I don't recommend setting attributes on the Trainer directly (like trainer.max_epochs = ...). These attributes are not meant to be modified from outside.

**Comment by drozzy** [comment]
I wish there was a bit more clarification on this in the docs, as I had to google for this.

**Comment by awaelchli** [comment]
I'm sorry that you had to google it. Where did you find your answer? Here in github?
Any idea where would be a good place to mention this?

**Comment by drozzy** [comment]
Yeah here: https://pytorch-lightning.readthedocs.io/en/stable/trainer.html#
Something like "don't use the same trainer multiple times" etc.
