### ISSUE TITLE
ModelCheckpoint instance to JSON

### ISSUE THREAD

**Issue by mpariente** [PyTorchLightning/pytorch-lightning#3047]
## 🚀 Feature

Have a `to_json(path)` function that writes the `best_k_models` to a json file in `path`.

### Motivation

Why having a JSON is good? 
Then you don't need to load the checkpoints to know the metrics and things like a posteriori stochastic weight averaging gets  easier. 

It used to be easier in 0.6, but loss values are now tensors, so it's not directly serializable.
This is currently needed: 
```python
best_k = {k: v.item() for k, v in checkpoint.best_k_models.items()}
with open(json_path, "w") as f:
    json.dump(best_k, f, indent=0)
```

Instead, we could have 
```python
checkpoint.to_json(json_path)
```

I'm ready to make a PR for it. Just tell me if this would be useful for you.

**Comment by awaelchli** [comment]
should this file be saved with every checkpoint, or one file that gets updated/overwritten?

**Comment by mpariente** [comment]
I just thought about a single function that can be called by the user at the end of training. 
But actually, updating/overwritting at every checkpoint also would be cool, at least the user never has to call it. 
Link to the PR #3048
