### ISSUE TITLE
metrics.sklearns don't work with DDP: Tensors must be CUDA and dense

### ISSUE THREAD

**Issue by Erlemar** [PyTorchLightning/pytorch-lightning#3069]
## 🐛 Bug

Using sklearn-like metrics (from metrics.sklearns) works fine in DP mode, but results in the following error in DDP mode: `Tensors must be CUDA and dense`

### To Reproduce

This colab notebook has a full example: https://colab.research.google.com/drive/1uxihs4pztF_qTN-gkO1QOaX0npzE_uSZ?usp=sharing

Mentioning @justusschock

**Comment by Borda** [comment]
@SkafteNicki @justusschock mind have look? 🐰

**Comment by SkafteNicki** [comment]
@borda PR https://github.com/PyTorchLightning/pytorch-lightning/pull/2528 seems to solve it (tried out the colab notebook with that branch and error was gone). Could you please review so we can get it merged?
