### ISSUE TITLE
Support a to_torchscript function on the LightningModule

### ISSUE THREAD

**Issue by ananthsub** [PyTorchLightning/pytorch-lightning#3080]
## 🚀 Feature
Support a conversion function to [PyTorch JIT](https://pytorch.org/docs/stable/jit.html) similar to what's available for [ONNX](https://pytorch-lightning.readthedocs.io/en/latest/lightning-module.html#to-onnx).
 
### Motivation
TorchScript is a way to create serializable and optimizable models from PyTorch code. Any TorchScript program can be saved from a Python process and loaded in a process where there is no Python dependency. TorchScript is a method by which users can serve PyTorch models efficiently. 

### Pitch
By default, we can use TorchScript to script the LightningModule. Users can override this in their own lightning modules to use tracing, or to script specific nn.Modules inside their LightningModule. This can then be extended to other Lightning utilities like model checkpointing, so we can save TorchScript or ONNX converted models alongside the best model checkpoints to make going to serving even easier to do

```
    def to_torchscript(self):
        """Saves the model as a JIT module. 
            This can be overridden to support custom TorchScript module export
        Example:
            >>> class SimpleModel(LightningModule):
            ...     def __init__(self):
            ...         super().__init__()
            ...         self.l1 = torch.nn.Linear(in_features=64, out_features=4)
            ...
            ...     def forward(self, x):
            ...         return torch.relu(self.l1(x.view(x.size(0), -1)))
            >>> with tempfile.NamedTemporaryFile(suffix='.onnx', delete=False) as tmpfile:
            ...     model = SimpleModel()
            ...     torch.jit.save(model.to_torchscript(), tmpfile.name)
            ...     os.path.isfile(tmpfile.name)
            True
        """
       return torch.jit.script(self.eval())
```

**Comment by Borda** [comment]
I like this proposal and it shall be quite straight forward, mind send a PR? 🐰 
cc: @PyTorchLightning/core-contributors

**Comment by ananthsub** [comment]
@Borda regarding the API, what if someone wanted to expose multiple torchscript modules from their lightning module. E.g. their lightning module does GAN training, and they want to export both the generator and discriminator separately. Should the interface allow for multiple scripted modules to be returned?

**Comment by awaelchli** [comment]
I think that would be super useful in these cases! How about something like
```python
model.to_torchscript()  # exports whole module
model.to_torchscript(children=["discriminator", "generator"])  # returns the list of script modules
```

**Comment by williamFalcon** [comment]
> I think that would be super useful in these cases! How about something like
> 
> ```python
> model.to_torchscript()  # exports whole module
> model.to_torchscript(children=["discriminator", "generator"])  # returns the list of script modules
> ```
> 
> or should that just be part of the override the user can do, without any argument passed to the method?

so, the PL module would need attrs with discriminator and generator no? i think this makes sense as long as we specify that.

**Comment by Borda** [comment]
Yeah, the children paraneter is good =)

**Comment by ananthsub** [comment]
> @ananthsub what about transforms? or a data pipeline the user might also need when exporting to torchscript/onnx. how are you thinking about that?

Yes, combining with transforms is a big need. In order to serve models, we will extract the transforms from the data module and "glue" them into the forward function (assuming the transforms are also TorchScriptable)

I think an API like this would be extensible. We recently added a Lightning callback that does this today and which people can extend

```

    def to_torchscript(self) -> Dict[str, nn.Module]:
        # By default, scripts the whole lightning module and wraps this in a dictionary from name to scripted model
        # if you would like to customize the modules that are scripted
        # or you want to use tracing you should override this method
        with pl_module.eval() and torch.no_grad():
            scripted_model = torch.jit.script(pl_module)
        return {DEFAULT_MODEL_FILENAME: scripted_model}
```

**Comment by snisarg** [comment]
Note that to_onnx() takes file_path, though I would prefer not to take that route as it'll get trickier with multiple torchscript exports. 

Users are free to add arguments to their version of to_torchscript(), (like children=[], as an example) because torchscripting can get fancy based on user requirements. So they could potentially add a save path if they deem necessary?

**Comment by snisarg** [comment]
For consistency's sake, pointing out that to_onnx() takes a file path, though I would much rather prefer the proposed solution.

**Comment by hudeven** [comment]
> Yes, combining with transforms is an important need. In order to serve models, we will also extract the transforms from the data module and "glue" them into the forward function (assuming the transforms are also TorchScriptable)
there are train_transforms, val_transforms and test_transforms in data module. Could we assume test_transforms always be the one to torchscript with model? Sometimes, the transform used in training/testing might be different than in inference, we might need additional logic to patch the transform during export.

How about add "to_torchscript()" to data module? such that model doesn't need to know the members in data module and any special patching for transform happens inside of data module.

**Comment by Borda** [comment]
@hudeven I think that datamodule shall not be part of the exported model as we move to data-agnostic models...
thoughts @nateraw @williamFalcon

**Comment by ananthsub** [comment]
> @hudeven I think that datamodule shall not be part of the exported model as we move to data-agnostic models...
thoughts @nateraw @williamFalcon

That makes sense. I think we can go with the simplest approach. It'd be great if we could also bake in bundled inputs into the torchscript export, as this would be broadly useful: https://github.com/pytorch/pytorch/blob/master/torch/utils/bundled_inputs.py#L17

**Comment by awaelchli** [comment]
@ananthsub we also have the option to use torch.jit.trace. Should we support both in the same function, or better not?
I was thinking `to_torchscript(trace=False)`?

**Comment by Borda** [comment]
> @ananthsub we also have the option to use torch.jit.trace. Should we support both in the same function, or better not?
> I was thinking `to_torchscript(trace=False)`?

I would prefer the parameter way...

**Comment by ananthsub** [comment]
Tracing also requires the user to provide an example input. So the API would become `to_torchscript(trace=False, example_input=None)` ? 

The PyTorch JIT team encourages users to use scripting over tracing because tracing has a number of limitations, which is why I didn't want to add a new dependency here. Given that this is new, maybe we could start without tracing and then add it as a feature request if many lightning users are interested. What do you think?

**Comment by awaelchli** [comment]
yes, perfect. was wondering the same, but script seems to be very versatile.

**Comment by Borda** [comment]
> Tracing also requires the user to provide an example input. So the API would become `to_torchscript(trace=False, example_input=None)` ?

let's follow the same parameter order as we already have for ONNX export
https://github.com/PyTorchLightning/pytorch-lightning/blob/d9ea25590e95ca9e70401123a0f1f59de711e2ff/pytorch_lightning/core/lightning.py#L1689
co to have the params diff from onnx to place as last...

**Comment by awaelchli** [comment]
I've implemented now the basic version as proposed by @ananthsub. 

@Borda example input is not required for scripting module, but we can make it have the file_path=None and if provided, save to file directly. 

Also, do we want the option to export submodules, for example with the syntax I proposed https://github.com/PyTorchLightning/pytorch-lightning/issues/3080#issuecomment-680965563
but then how is that going to work if we decide to have the file_path as parameter?

**Comment by ananthsub** [comment]
> @ananthsub what is the benefit of returning a dict instead of the script module directly? Do you plan to call this on submodules and collect them into a single dict, or let user return multiple entries by overriding?

I initially proposed this to keep the output parsing simpler. But I agree the most common case would be returning the script module directly. Maybe the type signature could be `-> Union[ScriptModule, Dict[str, ScriptModule]]`. 

I suppose I'm jumping ahead with bundled inputs then
