### ISSUE TITLE
When auto_sceale_batch_size and auto_lr_find are both enabled, lr find is called with every batch search

### ISSUE THREAD

**Issue by LeeJZh** [PyTorchLightning/pytorch-lightning#3088]
is this a bug or feature? I think lr find should be called after batch size search is done.

**Comment by Borda** [comment]
@SkafteNicki mind have look? 🐰

**Comment by SkafteNicki** [comment]
@Borda this is definitely a bug, it should be added to the list of attributes that are stored and altered before the search and then restored after the search:
https://github.com/PyTorchLightning/pytorch-lightning/blob/ccc923cbb01af7776f2472056b264758a6745871/pytorch_lightning/trainer/training_tricks.py#L213-L249
I will send a bugfix.

**Comment by Borda** [comment]
or @LeeJZh are interested in sending fix? 🦝

**Comment by LeeJZh** [comment]
> or @LeeJZh are interested in sending fix? 🦝

a pull request has been made.
