### ISSUE TITLE
Result docs doesnt specify logger and checkpointing methods

### ISSUE THREAD

**Issue by Vichoko** [PyTorchLightning/pytorch-lightning#3093]
[On the docs of this new feature ](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/docs/source/results.rst#result) it doesn't specify the default logging and checkpointing classes used.

In my case, I have a legacy pytorch-lightning implementation with explicit TubeLogger for TensorBoard and an early-stopper with a custom tolerance for my training scheme, that are given to my Trainer instance.

The thing is, using this new feature I don't know which logger it is using, and if it isn't TensorBoard compatible, I wouldn't know how to change it either. In the other hand, I don't know how to customize the Early-Stopping parameters, more specifically the tolerance, in this new scheme.

Lastly, reading the tutorial that involves the use of the Trainer class, I noticed that I can't figure what happens with the Result ```early_stop_on``` and ```checkpoint_on``` parameters, if I give explicitly the early stopper and logger classes to the Trainer class. The Early-Stop and Logger objects given to the Trainer instance have their own parameters, for example, the metric they are watching. So I don't know what happens if I use the Result parameters ```checkpoint_on``` and ```early_stop_on``` while using Trainer and Result early stop and checkpoint specifications at the same time.

**Comment by Borda** [comment]
Mind send a PR with updated docs and we can assist you... 🐰

**Comment by Vichoko** [comment]
I still don't know what would happen in the cases i explained, but i'll keep informed as soon as i figure out.

**Comment by Lucas-Steinmann** [comment]
They always get averaged, if you create the results in ``training_step`` or ``validation_step``. I was confused as well.
I added documentation in #3193.

**Comment by edenlightning** [comment]
Hey! We simplified the API and now simply use self.log() for logging, and simple dicts for data flow between LightningModule hooks.

Please refer to [latest version of docs](https://pytorch-lightning.readthedocs.io/en/latest/), and see if that helps your understanding!
You can choose any metric you want to monitor for checkpointing or early stopping, as long as you log it using self.log().

**Comment by Vichoko** [comment]
After I updated to the 1.0.0+ version my issue was solved with the new logging and checkpointing scheme.
