### ISSUE TITLE
How automaticly load best model checkpoint on Trainer instance with TestTubeLogger

### ISSUE THREAD

**Issue by Vichoko** [PyTorchLightning/pytorch-lightning#3107]
The only way I've found to resume the training of a model from the best checkpoint is to explicitly instance Trainer with following structure:

```python
best_epoch = 250  ## ?? (Actually i dont know)
self.trainer = ptl.Trainer(
    logger=TestTubeLogger(
        save_dir=self.save_dir,
        version=0  # fixed 
      ),        
    resume_from_checkpoint=str(self.save_dir / 'default' / 'version_0' / 'checkpoints' / 'epoch={}.ckpt'.format(best_epoch)),
    default_root_dir=self.save_dir,                                                                                                                                                                 )
```
The problem is that is not natural to know the exact epoch which has the better model.

I think loading the best model is a pretty natural operation for most of the cases:
Training: You want to continue training from the best model.
Test: You want to test the best model.

I think a method to find the "best checkpoint" is the kind of boilerplate code this library tries to avoid.

**Comment by Vichoko** [comment]
I'm pretty sure the TubeTestLogger did the best model loading before i updated. The feature stopped working after updating PyTorch-lightning from 0.3 to 0.9.
About loading the best model Trainer instance I thought about picking the checkpoint with the higher epoch from the checkpoint folder and use `resume_from_checkpoint` Trainer param to load it. I thought there'd be an easier way but I guess not.

**Comment by Borda** [comment]
I would recommend using Tensorboard logger instead TestTube logger, anyway as mentioned above the "best" is part of checkpointing, not logger :]

**Comment by Vichoko** [comment]
@Borda Can you explain why would you prefer Tensorboard logger? I thought Test Tube logger use was encouraged as was used so much on the tutorial.

**Comment by Borda** [comment]
@williamFalcon ^^

**Comment by Vichoko** [comment]
This is the workaround Trainer and Logger scheme i made for the purpose of this issue based on what i had.
```python
# Logger Specification
# We use TubeLogger for nicer structure
version = 1
logger = TestTubeLogger(
    save_dir=save_dir,
    version=version  # fixed to one to ensure checkpoint load
)
ckpt_folder = save_dir / 'default' / 'version_{}'.format(version) / 'checkpoints'
best_epoch = find_best_epoch(ckpt_folder)
# trainer with some optimizations
self.trainer = ptl.Trainer(
    logger=logger,
    resume_from_checkpoint=str(ckpt_folder / 'epoch={}.ckpt'.format(best_epoch)),
)
```

And the ```find_best_epoch``` i defined was:
```python
def find_best_epoch(ckpt_folder):
    """
    Find the highest epoch in the Test Tube file structure.
    Assumes 'epoch={int}.ckpt' format on files.
    :param ckpt_folder: dir where the checpoints are being saved.
    :return: Integer of the best_epoch
    """
    # Best Model Checkpoint
    ckpt_files = listdir(ckpt_folder)  # list of strings
    best_epoch = None
    for filename in ckpt_files:
        best_epoch = 0 if not best_epoch else best_epoch
        current_epoch = int(filename[6:-5])  # based on current format: 'epoch={int}.ckpt'
        best_epoch = current_epoch if current_epoch > best_epoch else best_epoch
    return best_epoch
```

**Comment by loretoparisi** [comment]
@Vichoko I think it could be useful also a `find_best_loss` function assumed you have same epoch, different losses
