### ISSUE TITLE
Metatags are saved over and over in TensorBoardLogger when logging metrics

### ISSUE THREAD

**Issue by bryant1410** [PyTorchLightning/pytorch-lightning#3114]
Is it okay that the metatags are saved every time metrics are logged in `TensorBoardLogger`? I find that it slows down training a bit.

[I found a related discussion.](https://github.com/PyTorchLightning/pytorch-lightning/pull/687/files#r367010524)

This is the part I'm talking about:

https://github.com/PyTorchLightning/pytorch-lightning/blob/83ab3eadb6bd32a761fd2e710a7a28778efa0360/pytorch_lightning/loggers/tensorboard.py#L201-L211

which is called by:

https://github.com/PyTorchLightning/pytorch-lightning/blob/83ab3eadb6bd32a761fd2e710a7a28778efa0360/pytorch_lightning/trainer/logging.py#L88-L91

which is in turn called by:

https://github.com/PyTorchLightning/pytorch-lightning/blob/83ab3eadb6bd32a761fd2e710a7a28778efa0360/pytorch_lightning/trainer/training_loop.py#L749-L757

**Comment by Borda** [comment]
mind send a fix PR? 🐰

**Comment by ksasi** [comment]
@Borda, I am trying to look into this as part of Hacktoberfest. If we stop saving "metatags" every time metrics are logged, don't we lose "metatags"? Please advise

**Comment by Borda** [comment]
@bryant1410 could you quantify what the bit slowdown is?
@ksasi we could just check it such a file already exists, assuming that the parameters do not change over a training...
cc: @PyTorchLightning/core-contributors

**Comment by bryant1410** [comment]
> mind send a fix PR?

Sorry for the delay. Don't have bandwidth right now unfortunately. Will pin it and revisit it later.

> @bryant1410 could you quantify what the bit slowdown is?

Not working right now on the project with which I found it. However, my understanding is that the slowdown depends on the underlying system and hardware, but that it's small generally.

**Comment by ksasi** [comment]
@Borda, thanks for your thoughts. I am interested in sending a PR for this. Let me know if this is fine.

**Comment by Borda** [comment]
@ksasi sure, go ahead...
