### ISSUE TITLE
Retrieve exact number of training steps in `configure_optimizers`

### ISSUE THREAD

**Issue by lucadiliello** [PyTorchLightning/pytorch-lightning#3115]
#### What is your question?
Some schedulers may require the total number of training steps. How can I retrieve it?

#### Code
```python
def configure_optimizers(self) -> (torch.optim.Optimizer, torch.optim.lr_scheduler.LambdaLR):
    steps = self.trainer.total_training_steps
```

#### What have you tried?
I tried computing them from the dataset length and the training parameters. But I don't think this is correct in a multi-gpu, multi-node setting.
```python
def get_total_number_of_steps_for_schedulers(hparams, trainer):
    if trainer.max_steps is not None:
        return trainer.max_steps
    else:
        training_batches_per_epoch = math.ceil(trainer.num_training_batches / (hparams.batch_size * trainer.world_size))
        steps = (hparams.max_epochs * training_batches_per_epoch) // hparams.accumulate_grad_batches
        return steps
```

#### What's your environment?

OS Independent
`pytorch_lightning`: 0.9.0

**Comment by rohitgr7** [comment]
In `setup` you can set:
```python
class MyModule(LightningModule):
    def setup(self, stage):
        if stage == 'fit':
            total_batch_size = self.hparams.batch_size * self.hparams.n_gpus * self.hparams.n_nodes
            train_batches = self.train_dataloader() // (total_batch_size)
            self.train_steps = (self.hparams.epochs * train_batches) // self.hparams.accumulate_grad_batches

    def configure_optimizers(self):
        total_train_steps = self.train_steps
```

**Comment by lucadiliello** [comment]
This makes sense. I was wrong not counting the network size and dividing again the number of training batches by the batch size.
I would add the comparison with `max_steps` since lot of people define the number of steps and not the number of epochs. Anyway, thank you a lot.

**Comment by kazhang** [comment]
Hi @rohitgr7 , thanks for the example! What if I use a data module, how do I retrieve the length of train dataloader in LightningModule? `train_dataloader()` is not implemented in this case

**Comment by rohitgr7** [comment]
hey @kazhang !
trying to add it here: https://github.com/PyTorchLightning/pytorch-lightning/pull/11599
