### ISSUE TITLE
AttributeDict vs Namespace?

### ISSUE THREAD

**Issue by MarioIshac** [PyTorchLightning/pytorch-lightning#3116]
## ❓ Questions and Help

I've looked at other issues that bring up using `AttributeDict` or `Namespace`, but have not seen any clarifying why pytorch lightning did not go with `Namespace` instead of `AttributeDict`. 

#### What is your question?

What is the difference `argparse.Namespace` and `pytorch_lightning.utilities.AttributeDict`? What did `Namespace` lack that an `AttributeDict` was made to accomplish?

**Comment by Borda** [comment]
`AttributeDict` has mixed features between `Dict` and `Namespace` as in past we have used dict for some places and namespace elsewhere, so do not break code and compatibility we came with this kind of hybrid 🐰 
To your question, I would recommend using `AttributeDict`

feel free to reopen if needed :]
