### ISSUE TITLE
Distributed Training not starting

### ISSUE THREAD

**Issue by bluesky314** [PyTorchLightning/pytorch-lightning#3117]
My code works and training starts with the progress bar with 1 gpu. However when I switch to 2, either using ddp or ddp_spawn the process gets stuck at:

<img width="877" alt="image" src="https://user-images.githubusercontent.com/35393972/91033116-800e8a80-e620-11ea-92df-521730301f60.png">

Nothing happens but around 1.5 gb is taken on each gpu(the process takes around 8 on a single gpu)

Here is my code:
```
class LightningModel(pl.LightningModule):

    def __init__(self):
        super(LightningModel, self).__init__()
        # not the best model...
        self.model = U2NET(3, 1)

    def forward(self, x):
        # called with self(x)
        return self.model(x)

    def training_step(self, batch, batch_nb):
        # REQUIRED
        x = batch['image'].float() 
        labels_v=batch['label'].double() 
        
        d0, d1, d2, d3, d4, d5, d6 = self(x)
        d0, d1, d2, d3, d4, d5, d6,loss2, loss = muti_bce_loss_fusion(d0, d1, d2, d3, d4, d5, d6, labels_v)
        
        tensorboard_logs = {'train_loss': loss}
        return {'loss': loss, 'log': tensorboard_logs}


    def configure_optimizers(self):

        opt=torch.optim.Adam(self.model.parameters(), lr=lr, betas=(0.9, 0.999), eps=1e-08, weight_decay=0) 
#         scheduler=CombineCos(opt,0.2,lr,lr,5e-4,len(self.train_dataloader()),100)
        return opt

    def train_dataloader(self):
        loaders=get_loader([size,size])
        return loaders['train']

def main():
    train_loader = get_loader([size,size])['train']
    model = LightningModel()

    trainer = pl.Trainer(gpus=2,distributed_backend='ddp_spawn')
    trainer.fit(model, train_loader)
  
if __name__ ==  '__main__':
    main()
    

```

System

    Python 3.6 
    Pytorch 1.6
    Linux
    pip installed lightning
    CUDA Version: 10.1
    Nvidia-V100

**Comment by Borda** [comment]
the example seems fine to me, mind share complete example even with dummy data, eg colab notebook?

**Comment by bluesky314** [comment]
Colab does not allow ddp I read in the docs. How can I give you a workable example then?

**Comment by Borda** [comment]
true, so jut share script so we can run it...

**Comment by awaelchli** [comment]
@bluesky314  yes please, if you can share the script. I will try to run it and help debug. 
how do you launch your script? do you have cuda_visible_devices environment variable set?
