### ISSUE TITLE
Model checkpoint naming consistency

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#3125]
## 🚀 Feature
1. Modify [`str_ver` inside `format_checkpoin_name()`](https://github.com/PyTorchLightning/pytorch-lightning/blob/18160b81b5c39806b09b3bbdee8b71c316471a43/pytorch_lightning/callbacks/model_checkpoint.py#L267)
2. Let [`ModelCheckpoint.CHECKPOINT_NAME_LAST`](https://github.com/PyTorchLightning/pytorch-lightning/blob/18160b81b5c39806b09b3bbdee8b71c316471a43/pytorch_lightning/callbacks/model_checkpoint.py#L114) contain templates.

### Motivation

1. Going by `format_checkpoint_name`'s [docstring example](https://github.com/PyTorchLightning/pytorch-lightning/blob/18160b81b5c39806b09b3bbdee8b71c316471a43/pytorch_lightning/callbacks/model_checkpoint.py#L245). It is standard to use `-` to split metrics and `_` to split metric names. This makes `str_ver`'s [format](https://github.com/PyTorchLightning/pytorch-lightning/blob/18160b81b5c39806b09b3bbdee8b71c316471a43/pytorch_lightning/callbacks/model_checkpoint.py#L267) inconsistent by using `-`.
2. It would be helpful to be able to set `ModelCheckpoint.CHECKPOINT_NAME_LAST='last-{epoch}-{acc.3f}.ckpt'` with the same parsing behaviour as regular checkpoints.

### Pitch

1. Replace `f"_v{ver}"` for `f"-v{ver}"` or `f".{ver}"`
2. Parse `ModelCheckpoint.CHECKPOINT_NAME_LAST` with `format_checkpoint_name()`

**Comment by Borda** [comment]
that sounds good to me, mind link some reference for this "standard way"? also sending a PR is very welcome 🐰 
cc: @PyTorchLightning/core-contributors

**Comment by carmocca** [comment]
I couldn't find any good reference other than Python's use of underscore in variable names (see [PEP8](https://www.python.org/dev/peps/pep-0008/)). I will make "-" (default field splitter) a modifiable variable.
