### ISSUE TITLE
Add logger for Azure Machine Learning

### ISSUE THREAD

**Issue by dkmiller** [PyTorchLightning/pytorch-lightning#3128]
## 🚀 Feature

We already have PyTorch Lightning loggers for Comet, MLFlow, and Neptune. It would be great if we also had one for [Azure Machine Learning](https://docs.microsoft.com/en-us/azure/machine-learning/) (AML).

### Motivation

A data scientist hoping to use PyTorch Lightning in AML currently has to build their own "logger adapter" to get logs from their training runs to show up in the AML "metrics" UI like this:

![image](https://user-images.githubusercontent.com/5003801/91076946-1927ac00-e5f5-11ea-9093-bb90f9f69969.png)

It would be great if a user could just "drop in" an AML logger and get those kinds of metrics for free.

### Pitch

The AML logging API is very similar to PyTorch Lightning's, with the small caveat that AML uses the terms "experiment" and "run" slightly differently than PyTorch Lightning does. I've even coded up a preliminary implementation with unit tests here: [dkmiller/pytorch-lightning](https://github.com/PyTorchLightning/pytorch-lightning/compare/master...dkmiller:master).

### Alternatives

The only alternative I can think of is for individual users to build their own AML :: PyTorch Lightning loggers.

### Additional context

Full disclosure: I'm a data scientist in the Azure Machine Learning team.

**Comment by Borda** [comment]
wow it sounds good, just the case now is we have feature freeze til 1.0 also we would consider as a better practice to have implemented this kind of nowel features in Bolts and if we found it stable we would move it to main PL repo
so my suggestion would be adding it In Bolts now because of feature freeze in PL for next few months... :]
cc: @PyTorchLightning/core-contributors

**Comment by dkmiller** [comment]
Thanks @Borda , this is good to know. For now, I'll contribute the logger to Bolts.

**Comment by dkmiller** [comment]
Moved: https://github.com/PyTorchLightning/pytorch-lightning-bolts/issues/180 .
