### ISSUE TITLE
Data DistributedSampler Error  when using Multi-GPU setting (with ddp).

### ISSUE THREAD

**Issue by ShomyLiu** [PyTorchLightning/pytorch-lightning#3149]
## 🐛 Bug

Hi, 
I have converted my pure PyTorch code into pytorch-lightning code, however,  the pl code would be crashed when using multi-gpus settings, while the code **runs successfully** when I set gpus=1.

My task is a binary classification task, and the error happens in AUC-ROC-score computing using **sklearn**:
```
File "/usr/local/lib/python3.6/dist-packages/sklearn/metrics/ranking.py", line 256, in _binary_roc_auc_score                                                    raise ValueError("Only one class present in y_true. ROC AUC score "
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
```

## Code sample
the trainer:
```
trainer = pl.Trainer(gpus=opt.gpu_num, distributed_backend='ddp')
```
the core part in `model.py`: Note that I need to collect the outputs of all validation-steps first, and then to compute the metric in the `validation_epoch_end`.
```
    def training_step(self, batch, batch_idx):
        label_list = batch[0]
        data = batch[1:]
        score = self(data)
        loss = F.cross_entropy(score, label_list.max(1)[1])
        result = pl.TrainResult(loss)
        result.log('train_loss', loss, sync_dist=True)
        return result

    def validation_step(self, batch, batch_idx):
        label_list = batch[0]
        data = batch[1:]
        score = self(data)
        loss = F.cross_entropy(score, label_list.max(1)[1])
        result = pl.EvalResult(loss)
        result.label_list = label_list.squeeze(1).tolist()
        result.pred_list = score.squeeze(1).tolist()
        return result

    def validation_epoch_end(self, val_outputs):

        labels = [i for k in val_outputs.label_list for i in k]
        preds = [i for k in val_outputs.pred_list for i in k]
    
        res = cal_metric(all_labels, all_preds)
        result = pl.EvalResult(checkpoint_on=torch.tensor(res['group_auc']))
        result.log_dict(res, prog_bar=True, sync_dist=True)
        return result

```

### Environment

* CUDA:
        - GPU:
                - GeForce GTX 1080 Ti
                - GeForce GTX 1080 Ti
        - available:         True
        - version:           10.2
* Packages:
        - numpy:             1.17.4
        - pyTorch_debug:     False
        - pyTorch_version:   1.6.0
        - pytorch-lightning: 0.9.0
        - tensorboard:       2.0.2
        - tqdm:              4.48.2
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.6.9
        - version:           #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020

So  what might be the reason that leads to the error in `validation_epoch_end` in multi-gpus setting. (it goes well in gpus=1).

Thanks.

**Comment by ShomyLiu** [comment]
Updated

-----------
I have checked that the batch_data (i.e., the `label` and `data`),  and found out that the batch data is unexpected and disturbed, which would lead to there are all zeros in some `y_true` and cause the error.  (In fact, there should be at least one `1` in the label.

Hence the reason might be the `sampler` in `ddp`. #1567.  Following is my data-loader:
```
def collate_fn(batch):
    '''
    label_list, candidate_news_indexs, click_news_indexes, user_indexes
    '''
    data = zip(*batch)
    data = [torch.LongTensor(d) for d in data]
    return data
train_dataloader = DataLoader(train_data,
                                  opt.batch_size,
                                  shuffle=True,
                                  collate_fn=collate_fn)
test_dataloader = DataLoader(test_data,
                                 opt.batch_size,
                                 shuffle=False,
                                 collate_fn=collate_fn)
```

So, should I define the distributedsampler?

**Comment by Borda** [comment]
@SkafteNicki @justusschock mind have look? 🐰

**Comment by ShomyLiu** [comment]
Updated2: (BTW, I'm new to DDP)
-----------
when I disabled the auto-sampler in pl using `replace_sampler_ddp=False`, the code can run without errors, however, if there is no distributed sampler, the data in different GPUs is the same.

**Comment by justusschock** [comment]
@ShomyLiu yes without the ddp sampler data on different GPUs is same. What you'd need is some kind of stratified splitting across GPUs (or a larger batchsize). 

While we cannot do anything on the stratification side, we will provide custom aggregation cross different batches for several metrics, once #2528 is done. 

But this is not an error on our side, this only caused to your data scenario.

**Comment by ShomyLiu** [comment]
Hi, thanks for your reply.  But it seems that I could not catch your point. I think that there is no aggregation cross different batches in my scenario.



As shown in my `collate_fn`:
```
def collate_fn(batch):
    data = zip(*batch)
    data = [torch.LongTensor(d) for d in data]
    return data
```
Each returned `batch data` is a list containing some tensors (the first dimension of all the tensors are the batch_size), and these tensors are used in the model `forward`.  This is a very common data format with PyTorch. 

When using the default sampler in pl (i.e.,  auto_add_sampler) with multi-gpus, the batch data will be disordered.
So the problem is caused by the sampler or my collate function? 
Or, in this data scenario, how to use ddp?

Thanks very much.

**Comment by rohitgr7** [comment]
you can try out some kind of stratified DistributedSampler. If you search if online you'll find one. Then just add that sampler and set `replace_ddp_sampler=False`.

**Comment by ShomyLiu** [comment]
Thanks for your suggestions. 
The `DistributedSampler` can only be used after initializing the DDP environment using  `torch.distributed.init_process_group`,  However, pytorch-lightning has taken over the multi-gpus settings of pytorch, the distributed env could not be initilized repeatedly.

So could you please show some examples to customize the distributed sampler in pytorch-lightning?

PS:  When I change the code into pure pytorch DDP, it can run well and the batch data is correct, the core part:
```
torch.distributed.init_process_group(backend="nccl" ....) 
def collate_fn(batch):
    data = zip(*batch)
    data = [torch.LongTensor(d) for d in data]
    return data
train_data = Data("Train")
test_data = Data("Test")

train_sampler = DistributedSampler(train_data, shuffle=True)
test_sampler = DistributedSampler(test_data, shuffle=False)

train_dataloader = DataLoader(train_data, opt.batch_size, shuffle=True,  collate_fn=collate_fn, sampler=train_sampler)
test_dataloader = DataLoader(test_data, opt.batch_size, shuffle=False, collate_fn=collate_fn, sampler=test_sampler)
....
....
```

And when I change into lightning, the auto-sampler would lead to wrong batch data.

**Comment by vincentzlt** [comment]
I had similar problems. I think the type of `batch` argument the `collate_fn` function receives changed from a list of examples to examples in my case. I do not know why this bug exists, but it seems only with Pytorch Lightning (after googling)..
