### ISSUE TITLE
Validation Step for Epoch Clarified

### ISSUE THREAD

**Issue by dulayjm** [PyTorchLightning/pytorch-lightning#3164]
## 🚀 Feature

This simple change would add the `num_validation_sanity_steps` flag to also include `fullEpoch` in addition to the synonymous `-1` flag, to add clarity to the end-user. 

### Motivation
I grew frustrated with trying to find a way to easily run an entire validation epoch before using training loops in pytorch-lightning. After finding this parameter (https://github.com/PyTorchLightning/pytorch-lightning/pull/2246), I still did not like how the `-1` flag works. This also confused a colleague of mine, so I decided to submit this change as a means to add clarity to the end-user.

### Pitch
Allow `-1` and `fullEpoch` flags to run the validation sanity step on an entire batch prior to training

### Pull Request
https://github.com/PyTorchLightning/pytorch-lightning/pull/3166

**Comment by Borda** [comment]
Thx for your PR 👍
