### ISSUE TITLE
Max line length mismatch

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#3168]
## 🐛 Bug

[.pep8speaks.yml](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.pep8speaks.yml) has `max-line-length` set to 119 whereas it is 120 in [pyproject.toml](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pyproject.toml)

### Expected behavior

line-length should be consistent

**Comment by Borda** [comment]
mind send a fix PR? :]

**Comment by carmocca** [comment]
Sure!
