### ISSUE TITLE
Warn when you forget to call super().__init__() in datamodule subclass

### ISSUE THREAD

**Issue by nateraw** [PyTorchLightning/pytorch-lightning#3175]
## 🚀 Feature

If you forget to call `super().__init__()` in datamodule subclass, you end up getting confusing errors down the line. We should let the user know they've forgotten to do so and give them a warning.

**Comment by rbracco** [comment]
Exact error message is: AttributeError: 'YourDataModule' object has no attribute '_has_prepared_data'. Adding this to make the error searchable here.

**Comment by t-vi** [comment]
I think this is pretty bad, it used to work not too long ago, so people will see this on upgrades.

**Comment by nfsergiu** [comment]
This is still not fixed in v1.4.8. I was lucky to find this thanks to @rbracco's comment above.
