### ISSUE TITLE
How to wrap progress bar?

### ISSUE THREAD

**Issue by LeeJZh** [PyTorchLightning/pytorch-lightning#3177]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
When there are a lot things to log, the progess bar becomes to long to fit in a single line; therefore some informations are missing. Can we warp the progress bar so that it dispalys in multiple lines?
#### What's your environment?

 - OS: [Linux]
 - Packaging [pip]
 - Version [0.9]

**Comment by ananyahjha93** [comment]
@rohitgr7 do you have anything for this?

**Comment by rohitgr7** [comment]
![Screenshot from 2020-08-27 03-43-41](https://user-images.githubusercontent.com/30778939/91362191-96cb0200-e817-11ea-96f1-fa3da9090826.png)

@LeeJZh I tried to log random tensors here and it goes to the next line. Can you share an ss of your progress bar logs? Although I would suggest to use logger if you have a lot of thing to log.

**Comment by LeeJZh** [comment]
> ![Screenshot from 2020-08-27 03-43-41](https://user-images.githubusercontent.com/30778939/91362191-96cb0200-e817-11ea-96f1-fa3da9090826.png)
> 
> @LeeJZh I tried to log random tensors here and it goes to the next line. Can you share an ss of your progress bar logs? Although I would suggest to use logger if you have a lot of thing to log.

![image](https://user-images.githubusercontent.com/42196021/91375749-1247a600-e84e-11ea-9207-f8f9c6c9cf80.png)

Thanks! And I am also using the default Tensorboard logger; however it feels better if i can get most information from CLI.

**Comment by LeeJZh** [comment]
> ![Screenshot from 2020-08-27 03-43-41](https://user-images.githubusercontent.com/30778939/91362191-96cb0200-e817-11ea-96f1-fa3da9090826.png)
> 
> @LeeJZh I tried to log random tensors here and it goes to the next line. Can you share an ss of your progress bar logs? Although I would suggest to use logger if you have a lot of thing to log.

sorry, it seems to be caused by vscode and windows.

**Comment by souravraha** [comment]
> > ![Screenshot from 2020-08-27 03-43-41](https://user-images.githubusercontent.com/30778939/91362191-96cb0200-e817-11ea-96f1-fa3da9090826.png)
> > @LeeJZh I tried to log random tensors here and it goes to the next line. Can you share an ss of your progress bar logs? Although I would suggest to use logger if you have a lot of thing to log.
> 
> sorry, it seems to be caused by vscode and windows.

@LeeJZh 
Hi I am facing the same issue in vscode. Do you have a way of bypassing it?
