### ISSUE TITLE
Make PyTorch Lightning PEP 561 Compliant

### ISSUE THREAD

**Issue by MarioIshac** [PyTorchLightning/pytorch-lightning#3186]
## Motivation
Make `pytorch_lightning` [PEP 561](https://www.python.org/dev/peps/pep-0561) compliant such that its code can be type checked when it is added as a dependency.
## Description
Currently `pytorch_lightning` has inline type hints such that running `mypy` on `pytorch_lightning` itself reports success. However, when `pytorch_lightning` is imported by another project, and `mypy` is run there, I'm met with the following error:
```
error: Skipping analyzing 'pytorch_lightning': found module but no type hints or library stubs
```
This is because `pytorch_lightning` is not declared as PEP 561-compliant package. To quote from PEP 561:
> Package maintainers who wish to support type checking of their code MUST add a marker file named py.typed to their package supporting typing.

To reproduce:

1. Create a new Python project with a `virtualenv`
2. Create file `sample.py` with contents:
```
import pytorch_lightning
```
3. `pip install mypy`.
4. `pip install -e git+https://github.com/PyTorchLightning/pytorch-lightning#egg=pytorch-lightning`
5. Observe that `mypy sample.py` results in
```
error: Skipping analyzing 'pytorch_lightning': found module but no type hints or library stubs
note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
```
6. `pip install -e git+https://github.com/MarioIshac/pytorch-lightning@pep-561-compliance#egg=pytorch-lightning` (wiping the previous git clone)
7. Observe that `mypy sample.py` results in:
```
Success: no issues found in 1 source file
```

**Comment by Borda** [comment]
so is it just about adding the one empty file?

**Comment by MarioIshac** [comment]
> so is it just about adding the one empty file?

yeah basically, but also changing `setup.py` to distribute this empty file as part of `package_data`.

**Comment by Borda** [comment]
> > so is it just about adding the one empty file?
> 
> yeah basically, but also changing `setup.py` to distribute this empty file as part of `package_data`.

then add it rather to MANIFEST.in
