### ISSUE TITLE
Broken [Source] links in docs

### ISSUE THREAD

**Issue by dedeswim** [PyTorchLightning/pytorch-lightning#3189]
## 📚 Documentation

Hello, I was browsing the docs, and out of curiosity, I wanted to check the source for `LightningModule`, and so I clicked on the [Source] link of the `forward` method. The link, however, sends to https://github.com/PyTorchLightning/PyTorch-Lightning/blob/pytorch_lightning/core/lightning/LightningModule.py, which is not right, as the repo name is "pytorch-lightning".

I am not familiar with Sphinx, but I checked the docs and the conf file, and I think that the reason can be found here:

https://github.com/PyTorchLightning/pytorch-lightning/blob/ee4eae884b137054e10f21a44f0d1d427405e310/docs/source/conf.py#L59-L71

Since `github-repo` is set to `project`, which is, indeed, `PyTorch-Lightning`, as in the broken link.

If someone more familiar with Sphinx can confirm this, I'd be glad to submit a PR to fix this.

**Comment by Borda** [comment]
@awaelchli mind have look? 🐰

**Comment by ananyahjha93** [comment]
@dedeswim so the reason you pointed out is not exactly why a wrong link is being generated for LightningModule. 

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/docs/source/conf.py#L347

The function ```linkcode_resolve``` generates the 'source' links in the doc and that is giving out the wrong link for LightningModule. If you see the link generated for say TrainResult class, it links to the master branch and the exact line number for the methods, which is not the case here.

**Comment by Borda** [comment]
btw, need to keep compatibility with tagged releases as well as with master...

**Comment by dedeswim** [comment]
Hi, thank you @ananyahjha93 for the explanation!

I indeed realized that the link should go to "pytorch_lightning/core/lightning.py", instead of "pytorch_lightning/core/lightning/LightningModule.py".

Interestingly, the 0.8.5 version of the docs redirects to the right link (the one above), whereas the "0.9.0", "latest" and "stable" versions (which are the same version, right?) don't work.

**Comment by Borda** [comment]
ok, then we may have the wrong path in docs, is it only this case or all docs have wrong links?

**Comment by dedeswim** [comment]
I tried with all the other classes under the "Python API" section of the bar on the right in the docs and it looks like this is the only one broken

**Comment by Borda** [comment]
ok, then it is nothing with `linkcode_resolve` but just wrong link in docs, mind send a PR fix
https://github.com/PyTorchLightning/pytorch-lightning/blob/4d98419bb84e06c06aaee0a86530e322e24f6d11/pytorch_lightning/core/lightning.py#L136

**Comment by dedeswim** [comment]
I'd be happy to, but I am not sure about how to fix this. Where is the path to the source defined? Isn't it generated by `linkcode_resolve`?

**Comment by ananyahjha93** [comment]
@Borda others are correct, LightningModule is the only one that seems broken.

**Comment by awaelchli** [comment]
it looks like this is because in the .rst docs we refer to the methods with autofunction instead of automethod. it seems to solve the link issue, but breaks formatting of docs, need to figure out how to  properly use it.

**Comment by ydcjeff** [comment]
@Borda or @awaelchli is there a specific reason using `linkcode` extension?
if not, shall we use this extension https://www.sphinx-doc.org/en/master/usage/extensions/viewcode.html?
this creates `_modules` folder for source code and link to that folder. PyTorch is using this also.

It also solves this issue using `automethod`, `autofunction` won't work just like @awaelchli comment.
I discovered that PyTorch docs doesn't refer to source code for `methods`, so we need to add some css to the forked theme.

Here's the tried output:
It doesn't show `self` which is pretty normal I think, just like methods of other classes.

![Screen Shot 2020-09-14 at 22 57 57](https://user-images.githubusercontent.com/32727188/93113155-d7af8b80-f6de-11ea-9840-7026948f0250.png)

**Comment by awaelchli** [comment]
@ydcjeff nice, could you make a draft PR so we can try it out?

**Comment by ydcjeff** [comment]
@awaelchli with `viewcode` extension?

**Comment by awaelchli** [comment]
so you say it's a two step fix. 
1. viewcode, which solves the problem with linked source code, but we lose methods source code
2. add the custom css to the theme

if it can consistently link all classes, methods and functions, I think this is what we want.

**Comment by ydcjeff** [comment]
Yes, pytorch sphinx theme doesn't include css for directly linking methods.
So, we need to add it. I think `viewcode` works with all modules, classes, methods and functions.

But i will try with all to make sure it works and i will draft a PR

**Comment by Borda** [comment]
just testing and sure if it is a better way as before it linked to GitHub source and you simply create a perm link...
