### ISSUE TITLE
Can EvalResult show a max metric value in progress bar?

### ISSUE THREAD

**Issue by xiadingZ** [PyTorchLightning/pytorch-lightning#3218]
## 🚀 Feature
now EvalResult can only show current epoch's metric value in progress bar, can you add a flag to make it show max/min value of some metric, such as max accuracy up to current epoch?

**Comment by awaelchli** [comment]
I think this feature is a bit too specific to add a flag for it. What do @PyTorchLightning/core-contributors think?
For what you want to do, I have this solution overriding `get_progress_bar_dict` in LightningModule:

```python
def get_progress_bar_dict(self):
    bar_dict = super().get_progress_bar_dict()
    bar_dict["max"] = max(self.epoch_losses)  # save your epoch metrics in this list
    return bar_dict
```

**Comment by xiadingZ** [comment]
`EvalResult`'s `checkpoint_on`  is to get the best metric model, I think is convenient to print this best metric on the progress bar to show the best case. Now I have to open tensorboard of each log_dir to see the best metric I get.

**Comment by rohitgr7** [comment]
One can maintain the best metric state in module itself and log it everytime with prog_bar=True

**Comment by williamFalcon** [comment]
or change the reduce_fx to torch.max

**Comment by rohitgr7** [comment]
> result = ...
result.log('x', x, reduce_fx=torch.max)

@williamFalcon  `reduce_fx` is used to aggregate step metrics right? Will this work when we need to track the best epoch_metric from all previous epochs?
