### ISSUE TITLE
val_dataloader gets reloaded twice when num_sanity_val_steps > 0

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#3220]
## 🐛 Bug

val_dataloader gets called during sanity check and then again in the actual validation later on. 

### Expected behavior

gets only instantiated once (unless reload dataloaders every epoch = True)

### Additional context

From report on slack

**Comment by williamFalcon** [comment]
Fixed by #3221

**Comment by awaelchli** [comment]
@williamFalcon could you ping me next time so we don't work on the same thing in parallel please?

**Comment by williamFalcon** [comment]
oh sorry! missed that. i was just in that part of the code with refactors, so it was a quick fix and also didn't want to have merge conflicts

**Comment by awaelchli** [comment]
all good, thanks for taking care of it
