### ISSUE TITLE
How to calculate metric over entire validation set when training with DDP?

### ISSUE THREAD

**Issue by i-pan** [PyTorchLightning/pytorch-lightning#3225]
I started refactoring my code into Lightning yesterday. When I perform validation, I save all the predictions over the entire validation set and then calculate the validation metrics on all validation data at once. This is especially important for metrics like AUROC. 

I am training a model with DDP on 4 GPUs. I have a `validation_epoch_end` method to calculate a metric over the entire validation set:

```
def validation_epoch_end(self, outputs):
    auc_score = sklearn.metrics.roc_auc_score(outputs.target.cpu().numpy(), outputs.output[:,1].cpu().numpy())
    result = pl.EvalResult(checkpoint_on=torch.tensor(auc_score))
    result.log('auc', auc_score)
    return result
```

Here is a script that illustrates what the problem I'm encountering: 
[snippet.zip](https://github.com/PyTorchLightning/pytorch-lightning/files/5136973/snippet.zip)

However, when using DDP, this method gets called separately in each process, so I end up calculating the metric 4 times on 1/4 of the overall validation set. When I look at the values of each of the 4 AUROCs and the value that gets saved to `checkpoint_on`, the saved value is just 1 of the 4 (I'm assuming the one calculated by the process with rank 0?). 

I tried using the built-in pytorch_lightning metrics, but those give me a RuntimeError: Tensors must be CUDA and dense. This is using the most current branch (0.9.1.dev). 

There may be a simple solution to this, but I spent the last few hours combing through the docs and existing issues without any luck. 

Thanks in advance to anyone who can help.

**Comment by i-pan** [comment]
I found a workaround where we only use the `DistributedSampler` for training and not for validation. This was done by editing the `auto_add_sampler` method of class `TrainerDataLoadingMixin` in`trainer/data_loading.py`:

Line 166:
`dataloader = self.replace_sampler(dataloader, sampler)`
to
`if train: dataloader = self.replace_sampler(dataloader, sampler)`

Now all processes run inference on the entire validation set, which seems inefficient (probably the same speed as single GPU validation), so they all return the same metrics. 

In [MMDetection](https://github.com/open-mmlab/mmdetection/blob/4b6ff75b86dd76d46b8733dc667ee3f28683b036/mmdet/core/evaluation/eval_hooks.py), there is a class `DistEvalHook` that first performs multi-GPU inference and then runs evaluation on 1 process:

```
results = multi_gpu_test(
  runner.model,
  self.dataloader,
  tmpdir=tmpdir,
  gpu_collect=self.gpu_collect)
if runner.rank == 0:
  print('\n')
  self.evaluate(runner, results)
```

I'll take a look at the source code to see if something like this could be integrated into Lightning.

**Comment by awaelchli** [comment]
https://pytorch-lightning.readthedocs.io/en/latest/metrics.html#auroc
can reduce in ddp, maybe you can use that in validation_epoch_end instead of the sklearn metric, then you also don't have to move the tensors to cpu.

**Comment by s-rog** [comment]
```
    def reduce_mean(self, x):
        group = torch.distributed.group.WORLD
        torch.distributed.barrier(group)
        torch.distributed.reduce(x, 0)
        if self.global_rank == 0:
            x /= torch.distributed.get_world_size(group)
        return x
```

I run this on my metrics in `validation_epoch_end` but result objects can be synced via:

```
result = pl.EvalResult()
result.log('x', x, dist_sync=True)
```

though you might have to cast your tensor to cuda (self.device) first

**Comment by psinger** [comment]
How can I calculate a custom metric over the entire set?

**Comment by s-rog** [comment]
> How can I calculate a custom metric over the entire set?

Interested in this as well, so far I only know how to calculate on each gpu then reduce

**Comment by psinger** [comment]
I am currentkly trying something similar as you attempted @s-rog - the idea is to pickle the results for each rank and then collect them afterwards on rank=0.

**Comment by junwen-austin** [comment]
Please see #3159 for a temp solution. I have it tested to work on my code.

**Comment by s-rog** [comment]
@psinger looking into the torch distributed docs I think we need to:
1. gather (pred and target) on rank 0
2. stack or cat as appropriate
3. calculate metrics

or

1. calculate unreduced metric on all ranks
2. gather on rank 0
3. stack or cat as appropriate
4. reduce

I'm assuming this is only for logging purposes as backprop would probably cause issues. Also this is just from looking at the docs, haven't tried it out yet.

**Comment by sooheon** [comment]
@awaelchli The pl metric AUROC does not have reduce_group or reduce_op defined, can it still reduce across DDP?

**Comment by awaelchli** [comment]
@sooheon hmm, I don't think you can define a meaningful reduction operation for that metric. The best is to gather all pairs and then compute the roc once for all data.

**Comment by sooheon** [comment]
> The best is to gather all pairs and then compute the roc once for all data. 

Currently if I use AUROC in val_epoch_end, does this happen?

**Comment by SkafteNicki** [comment]
Note that we are working on implementing aggregation for metrics (this PR https://github.com/PyTorchLightning/pytorch-lightning/pull/3321 has started the process) such that each metric gets an `aggregated` property which will calculate the metric over all data seen so far.

**Comment by SkafteNicki** [comment]
Class based metrics have been revamped!
Please check out the documentation for the new interface, and see if the new interface solves your problem (less metrics are available at the moment as we are in the process of converting them to the new api).
