### ISSUE TITLE
Switching to using LightningDataModule see "has no attribute 'save_hyperparameters'"

### ISSUE THREAD

**Issue by jloveric** [PyTorchLightning/pytorch-lightning#3232]
I'm trying to use the LightningDataModule and so I just copied the data members in my existing LightningModule to a LightningDataModule.  The LightningModule takes a config as input and then I call self.save_hyperparameters(cfg).  Obviously that same function doesn't work in the LightningDataModule (nor does it make sense).  Is there another function in LightningDataModule to save data the parameters (or configuration)?

**Comment by awaelchli** [comment]
@nateraw is working on this as far as I know.

**Comment by edenlightning** [comment]
@nateraw any update?

**Comment by nateraw** [comment]
Moving discussion to #3544 as it lays out plans to implement the feature mentioned here.
