### ISSUE TITLE
Error using Custom DistributedSampler

### ISSUE THREAD

**Issue by dalmia** [PyTorchLightning/pytorch-lightning#3238]
## 🐛 Bug

When using a custom `DistributedSampler`, I get the following error while requesting the train dataloader:

```python
File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/accelerators/tpu_backend.py", line 81, in train
    self.tpu_train_in_process(self.trainer.tpu_id, model, self.trainer, self.mp_queue)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/accelerators/tpu_backend.py", line 112, in tpu_train_in_process
    results = trainer.run_pretrain_routine(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1239, in run_pretrain_routine
    self.train()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 355, in train
    self.reset_train_dataloader(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/data_loading.py", line 205, in reset_train_dataloader
    self.train_dataloader = self.request_dataloader(model.train_dataloader)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/data_loading.py", line 360, in request_dataloader
    dataloader = dataloader_fx()
  File "/content/lib/coreml/coreml/data/data_module.py", line 41, in train_dataloader
    drop_last=False)
  File "/content/lib/coreml/coreml/data/dataloader.py", line 127, in get_dataloader
    'rank': xm.get_ordinal()
  File "/content/lib/coreml/coreml/data/sampler.py", line 139, in __init__
    sampler.dataset, num_replicas, rank, shuffle)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/distributed.py", line 58, in __init__
    rank = dist.get_rank()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 598, in get_rank
    _check_default_pg()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 210, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized
```
When no custom sampler is used, the code works fine. The `DistributedSampler` object is created as a wrapper over my actual sampler - the definition can be found [here](https://github.com/dalmia/coreml/blob/lightning/coreml/data/sampler.py#L132) and the object creation happens [here](https://github.com/dalmia/coreml/blob/lightning/coreml/data/dataloader.py#L116). 

A quick Google search led me to [this](https://github.com/dalmia/coreml) PyTorch issue where [this](https://github.com/pytorch/pytorch/issues/38300#issuecomment-629446169) comment highlighted that the call to `torch.distributed.init_process_group` might be missing. 

### To Reproduce
Use [this](https://colab.research.google.com/drive/155-MwCKwM-vFFn7rTF7S7aTJSg0bfA8j?usp=sharing) colab notebook.

**Comment by jjkindergarten** [comment]
come with same issue

**Comment by dalmia** [comment]
@williamFalcon I do not intend to spam, but is there any fix for this? I found other open issues regarding Custom Distributed Sampler as well and so, figured that this is still relevant. Please have a look!

**Comment by sshleifer** [comment]
I got this `DistributedSortishSampler` working
https://github.com/huggingface/transformers/blob/master/examples/seq2seq/utils.py#L225

It required passing `-replace_sampler_ddp=False`.

**Comment by dalmia** [comment]
Hi @sshleifer. I did set `replace_sampler_ddp=False` but still got this error. Thanks for pointing me to this example from HuggingFace. I'll try following their example to see if I can get this working!

**Comment by awaelchli** [comment]
@dalmia Could you share the code for your custom distributed sampler, or even better, a minimal example that reproduces the error?

**Comment by awaelchli** [comment]
@dalmia 
The trainer will call the dataloader before dist.get_rank() is initialized. Therefore the rank is not yet known. 
But when creating the sampler, you don't have to provide the rank and num_replicas, you can leave it at the default values and when distributed get's initialized, they will be known.

Furthermore, your distributed sampler also has the following typo:  `self.sampler = Sampler` (should be sampler)
Here is what worked for me (ddp and ddp_spawn):

```python
class DistributedSamplerWrapper(DistributedSampler):
    def __init__(
            self, sampler,
            num_replicas: Optional[int] = None,
            rank: Optional[int] = None,
            shuffle: bool = True):
        super(DistributedSamplerWrapper, self).__init__(
            sampler.dataset, num_replicas, rank, shuffle)
        # typo:
        # self.sampler = Sampler
        self.sampler = sampler

    def __iter__(self):
        indices = list(self.sampler)
        indices = indices[self.rank:self.total_size:self.num_replicas]
        return iter(indices)

    def __len__(self):
        return len(self.sampler)

```
and then in dataloader:
```python
sampler = DistributedSamplerWrapper(RandomSampler())  # leave other values default
dataloader = DataLoader(dataset, sampler=sampler, ...)
```

Hope this helps you.

**Comment by dalmia** [comment]
@awaelchli thank you for your answer. I feel so silly for missing the `Sampler` bug.
However, upon changing it and leaving rank and num_replicas as its default, I still get the same issue as when I am creating the sampler, the `DistributedSampler` within torch (https://github.com/pytorch/pytorch/blob/master/torch/utils/data/distributed.py#L62) calls `dist.get_rank()` if `rank` is None. So, I'm back to the same issue. Shouldn't the sampler be created after distributed gets initialized?

**Comment by dalmia** [comment]
It's working now. It was an issue with the way I was passing parameters to my DistributedSampler

**Comment by pgmikhael** [comment]
> It's working now. It was an issue with the way I was passing parameters to my DistributedSampler

Hi, I'm running into this problem and am not clear how you were able to resolve it. Specifically, I'm still hitting the call mentioned above (https://github.com/pytorch/pytorch/blob/master/torch/utils/data/distributed.py#L62).

**Comment by YuxianMeng** [comment]
> @awaelchli thank you for your answer. I feel so silly for missing the `Sampler` bug.
> However, upon changing it and leaving rank and num_replicas as its default, I still get the same issue as when I am creating the sampler, the `DistributedSampler` within torch (https://github.com/pytorch/pytorch/blob/master/torch/utils/data/distributed.py#L62) calls `dist.get_rank()` if `rank` is None. So, I'm back to the same issue. Shouldn't the sampler be created after distributed gets initialized?

Hi, I met the same issue here, could you please provide the way that you pass parameters to your DistributedSampler?

**Comment by awaelchli** [comment]
If I recall correctly they just get passed through the init and then the super call.
