### ISSUE TITLE
Number of training steps

### ISSUE THREAD

**Issue by fperazzi** [PyTorchLightning/pytorch-lightning#3246]
Is it possible to know within the `LighthingModule` the total number of training steps? I.e , what's going to be the value of `self.trainer.global_step` at the end of the training? I would need this info to set `T_max` in `CosineAnnealingLR`.

**Comment by romesco** [comment]
One possibility is setting the [`max_steps`](https://pytorch-lightning.readthedocs.io/en/latest/trainer.html#max-steps) parameter in `Trainer`.

Just make sure the number of steps will be greater than `max_epochs`, otherwise,  it will complete early!

**Comment by fperazzi** [comment]
Got it. So `max_steps` should be computed based on the number of epochs, the batch size and the number GPUs, somewhere before instantiating the `Trainer`.

**Comment by madaan** [comment]
Looks like this is the same issue as: https://github.com/PyTorchLightning/pytorch-lightning/issues/3115.
