### ISSUE TITLE
Incorrect aggregation when logging predictions into EvalResult with distributed_backend DP

### ISSUE THREAD

**Issue by Erlemar** [PyTorchLightning/pytorch-lightning#3264]
## 🐛 Bug

It it possible to log some data in EvalResult like this:
```
result = pl.EvalResult(checkpoint_on=val_loss)
result.y_hat = y_hat.float()
```
Suppose I log some value with dimensions (32, 10) - batch size 32 and 10 classes. And I have N samples in total.
If distributed_backend is None, in validation_epoch_end `outputs.y_hat.shape` is (N, 10)
If distributed_backend is ddp, in validation_epoch_end `outputs.y_hat.shape` is (N, 10)
But if distributed_backend is dp, in validation_epoch_end `outputs.y_hat.shape` is (N) - the values are averaged over samples.

#### Code sample
https://colab.research.google.com/drive/16NQaMTho5gI0URzgh3CNsZvXmHHyynvh?usp=sharing

**Comment by williamFalcon** [comment]
Sorry about the delay! was wrapping up all the refactors :) 

no, you have to log directly with the .log call...

```python
result = pl.EvalResult(checkpoint_on=val_loss)
result.log('my_metric_name', y_hat)
```
