### ISSUE TITLE
 'dict' object has no attribute 'callback_metrics'

### ISSUE THREAD

**Issue by sheljoy** [PyTorchLightning/pytorch-lightning#3269]
raise the error
`
File "/opt/software/envs/dl/lib/python3.6/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 421, in __update_callback_metrics
    self.callback_metrics = eval_result.callback_metrics
AttributeError: 'dict' object has no attribute 'callback_metrics'
`
where using the follow

```{python3}

from pytorch_lightning import LightningModule as LitModule
class myLitMoudel(LitModule):

     def validation_step(self,batch,batch_idx):
         loss = self.batch_loss(batch["sent"])
         result = EvalResult()
         result.log("val_loss", loss)
         return result

     def validation_epoch_end(self,outputs):
         val_loss = torch.mean(outputs["val_loss"]).mean()
         print(val_loss)
         return {"val_loss":val_loss}
```

with early stopping configure

`es = EarlyStopping(monitor="val_loss",min_delta=0.001,patience=30,verbose=True,mode="min")
`

pytorch 1.6.0
pytorch-lightning  0.9.0

**Comment by phongnhhn92** [comment]
I am also receiving this error. Please help !

**Comment by sheljoy** [comment]
I had solved it,just since example docs is out-of-date. the API has been cleared to use.

**Comment by tarokiritani** [comment]
@sheljoy Could you share your solution please?

**Comment by sheljoy** [comment]
@phongnhhn92 
```{python}
    def validation_step(self,batch,batch_idx):
        loss = self.batch_loss(batch["sent"])
        result = EvalResult(checkpoint_on=loss)
        result.log_dict({"val_loss":loss},prog_bar=False,on_epoch=True)
        return result

```

You can conference the API docs 'https://pytorch-lightning.readthedocs.io/en/latest/lightning-module.html#validation-loop'.

the isssue raised when the `validation_step` return dict-typed variance.  The returned TrainResult/EvalResult  is recomanded instead of the dict-typed  log.
