### ISSUE TITLE
on_fit_start not triggering (master)

### ISSUE THREAD

**Issue by s-rog** [PyTorchLightning/pytorch-lightning#3278]
## 🐛 Bug
on_fit_start is not being triggered on master as of f46318ebfeb785a659c49091a6871584ccde3ee1

### To Reproduce

1. Install master
2. Run template with on_fit_start added (included below)
(identical behavior for single gpu, ddp_spawn and ddp)

#### Code sample
```
"""
Runs a model on a single node across multiple gpus.
"""
import os
from argparse import ArgumentParser

from pl_examples.models.lightning_template import LightningTemplateModel
from pytorch_lightning import Trainer, seed_everything

seed_everything(234)

class custom_template(LightningTemplateModel):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    
    def on_epoch_start(self):
        print("on_epoch_start")

    def on_fit_start(self):
        print("on_fit_start")

def main(args):
    """ Main training routine specific for this project. """
    # ------------------------
    # 1 INIT LIGHTNING MODEL
    # ------------------------
    model = custom_template(**vars(args))

    # ------------------------
    # 2 INIT TRAINER
    # ------------------------
    trainer = Trainer.from_argparse_args(args)

    # ------------------------
    # 3 START TRAINING
    # ------------------------
    trainer.fit(model)


def run_cli():
    # ------------------------
    # TRAINING ARGUMENTS
    # ------------------------
    # these are project-wide arguments
    root_dir = os.path.dirname(os.path.realpath(__file__))
    parent_parser = ArgumentParser(add_help=False)

    # each LightningModule defines arguments relevant to it
    parser = LightningTemplateModel.add_model_specific_args(parent_parser, root_dir)
    parser = Trainer.add_argparse_args(parser)
    parser.set_defaults(gpus=2, distributed_backend='ddp')
    args = parser.parse_args()

    # ---------------------
    # RUN TRAINING
    # ---------------------
    main(args)


if __name__ == '__main__':
    run_cli()
```

### Expected behavior
"on_fit_start" should be printed along with "on_epoch_start" but only "on_epoch_start" is printed

**Comment by rohitgr7** [comment]
because at this point neither `model` nor `accelerator_backend` is assigned to the `trainer`.
https://github.com/PyTorchLightning/pytorch-lightning/blob/caf7893f27c73db227883ad00531d0ff550cbb23/pytorch_lightning/trainer/trainer.py#L984
Should be called after
https://github.com/PyTorchLightning/pytorch-lightning/blob/caf7893f27c73db227883ad00531d0ff550cbb23/pytorch_lightning/trainer/trainer.py#L1008

**Comment by s-rog** [comment]
I'll move the hook and test it out, if it works I'll do a PR

**Comment by s-rog** [comment]
@rohitgr7 moving the hook can work but causes another peculiar issue
```
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1029, in fit
    self.call_hook('on_fit_start', model)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1384, in call_hook
    output = hook_fx(*args, **kwargs)
TypeError: on_fit_start() takes 1 positional argument but 2 were given
```
more specifically `on_fit_start()` is called with 2 modules, still locating the source of this extra arg/module

**Comment by rohitgr7** [comment]
let's just wait for refactors and keep this issue open. After exploring a bit more I saw a few more bugs :sweat_smile: .

**Comment by s-rog** [comment]
@rohitgr7 I implemented the following changes and now on_fit_start is working as expected:

- move hook
- change on_fit_start signature (like on_fit_end)
- change callback.on_fit_start args (like on_fit_end)

> After exploring a bit more I saw a few more bugs 😅
What else did you find? I'll take a look before I submit a PR

**Comment by edenlightning** [comment]
@s-rog want to send the PR out?
