### ISSUE TITLE
Error in transfer_batch_to_device when None type is in the batch

### ISSUE THREAD

**Issue by hyukyu** [PyTorchLightning/pytorch-lightning#3280]
### To Reproduce

1. There should be no `torchtext` pre-installed
2. Run the sample code

#### Code sample
```import torch
from torch.utils.data import DataLoader
import pytorch_lightning as pl


def collate_fn(batch):
    return batch


class MyDataModule(pl.LightningDataModule):
    def __init__(self):
        super().__init__()

    def prepare_data(self):
        pass

    def setup(self, stage):
        self.train = [{"input": torch.randn(1,2), "output": None}]

    def train_dataloader(self):
        return DataLoader(self.train, batch_size=1, collate_fn=collate_fn)


class MyModel(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(2, 1)

    def forward(self, x):
        return self.linear(x)

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters())

    def training_step(self, batch, batch_idx):
        x = batch[0]["input"]
        y = batch[0]["output"]
        loss = self(x)
        result = pl.TrainResult(loss)
        result.log('train_loss', loss, on_epoch=True)
        return result


def main():
    # Dataset
    data_module = MyDataModule()

    # Model
    model = MyModel()

    # Train
    trainer = pl.Trainer(max_steps=1)
    trainer.fit(model, datamodule=data_module)


if __name__ == "__main__":
    main()
```

### Expected behavior
The above code runs fine if the package `torchtext` is installed. However, the code raises following error if `torchtext` is not available and I believe this inconsistency is a bug.

```
 File "python3.6/site-packages/pytorch_lightning/utilities/apply_func.py", line 122, in batch_to
    return data.to(device, **kwargs)
AttributeError: 'NoneType' object has no attribute 'to'
python-BaseException
```

I think this line of the [code](https://github.com/PyTorchLightning/pytorch-lightning/blob/f46318ebfeb785a659c49091a6871584ccde3ee1/pytorch_lightning/utilities/apply_func.py#L24) is the cause of the problem 

### Environment
* CUDA:
	- GPU:
		- TITAN Xp
		- TITAN Xp
		- TITAN Xp
		- TITAN Xp
		- TITAN Xp
		- TITAN Xp
		- TITAN Xp
		- TITAN Xp
	- available:         True
	- version:           10.2
* Packages:
	- numpy:             1.18.4
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0
	- pytorch-lightning: 0.9.0
	- tensorboard:       2.2.1
	- tqdm:              4.46.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.6.8
	- version:           #81~16.04.1-Ubuntu SMP Tue Nov 26 16:34:21 UTC 2019

**Comment by edenlightning** [comment]
Thanks! Mind sending us a PR with the fix?

**Comment by edenlightning** [comment]
@awaelchli mind taking a look?

**Comment by awaelchli** [comment]
I submitted a fix. 
@hyukyu Be aware, torchtext will remove/deprecate this Batch object soon. So in the future you should switch to their new dataloading pipeline that integrates better with PyTorch and Lightning.
