### ISSUE TITLE
TrainResult erroring with deepcopy on epoch end

### ISSUE THREAD

**Issue by tfrizza** [PyTorchLightning/pytorch-lightning#3283]
When detaching the Result object from the graph the code first calls deepcopy.copy() which throws an error
`*** RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.`
as the Result object still contains the graphs. It seems like it needs to perform some sort of recursive detach (like the dict implementation in the lines below), since calling `detach()` on its own will modify `training_step_output_for_epoch_end` and `training_step_output` in place.

https://github.com/PyTorchLightning/pytorch-lightning/blob/f3c63f774632ad10699e84bb330dfc2332b120d5/pytorch_lightning/trainer/training_loop.py#L1038

N.B. This was run on TPU

**Comment by harpone** [comment]
I'm facing the same issue on TPUs. I'm doing `result = pl.TrainResult(minimize=loss)`, and I get that error for the `loss`. I guess calling `.item()` or `.detach()` would solve the logging issue, but of course that wouldn't quite work in general... :/

So I guess `Result` is just not usable with TPUs ATM and I need to resort to (more) manual logging?

**Comment by tfrizza** [comment]
@harpone The workaround for me was to use the dictionary approach for logging metrics, i.e. returning `{'loss':loss, 'log':{}}`. Still not super happy with this since I was hoping to use the Result object to aggregate metrics across TPU cores.

**Comment by harpone** [comment]
yeah I'm actually now using the trainer's logger, so basically `self.logger.log_metrics(loss_dct, step=self.global_step) if batch_idx % 50 == 0 else None`, which is actually fine... 

I guess using `Result` in validation should work now that #3252 is fixed... need to try that out

**Comment by Borda** [comment]
@lezwon mind have a look?

**Comment by lezwon** [comment]
This issue should be fixed in master. @tfrizza @harpone mind retrying with master?

**Comment by Borda** [comment]
feel free to re-open if needed 🐰

**Comment by harpone** [comment]
OK works now on master, both for train and eval (on TPU v3-8). But now I'm getting a total hangup when using gradient clipping... need to check into it further.

**Comment by tfrizza** [comment]
Yep seems to be working now, thanks!
