### ISSUE TITLE
Trainer.profiler should allow str

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#3330]
## 🚀 Feature

Currently, the `profile` argument of the Trainer is `bool`. It should be `Union[bool, str]`.

### Motivation

It would avoid having to set the profiler manually by creating and passing the object to the Trainer.
It is also the way `auto_scale_batch_size` and `auto_lr_find` work.

### Pitch

```
# equivalent to --profiler true
trainer = Trainer(profiler=True)

# equivalent to --profiler simple
trainer = Trainer(profiler=SimpleProfiler())

# equivalent to --profiler advanced
trainer = Trainer(profiler=AdvancedProfiler())
```

**Comment by Borda** [comment]
@jeremyjordan any thoughts?

**Comment by jeremyjordan** [comment]
Sounds good to me, want to submit a PR @carmocca?

>It should be Union[bool, str].

Technically, it should be `Union[bool, str, BaseProfiler]`.

**Comment by carmocca** [comment]
> Sounds good to me, want to submit a PR @carmocca?

Bit busy right now, maybe at a later point.

@Borda Tag it "good first issue" in the meantime?

**Comment by ddrevicky** [comment]
@Borda Assign this to me please :).

**Comment by ananthsub** [comment]
if you're using Hydra, this instantiation via config becomes a lot easier. This has parallels to the distributed_backend / plugin interfaces too, which are increasingly supporting explicit instantiations passed to the trainer @williamFalcon
