### ISSUE TITLE
Remove warnings usage

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#3332]
## 🚀 Feature

`warnings.warn` should be replaced by `logging.warning`

### Motivation

In my project, I get the lightning logger (`logging.getLogger('lightning')`) and override its handlers and format to fit my use case. This allows me to save everything into a log file.

However, there is no way to control warnings behaviour. Its messages cannot be saved to a file and they break any ongoing tqdm bars. We should always use the lightning logger.

### Pitch

~`warnings.warn(*args, **kwargs)`~
`log.warning(*args, **kwargs)`

#### Also, a bug:

https://github.com/PyTorchLightning/pytorch-lightning/blob/ee72271d205beb2c012e34425cb16e189cc56c7d/pytorch_lightning/utilities/distributed.py#L44-L45

This should be `log.debug`

**Comment by Borda** [comment]
you can filter warnings, see for example https://docs.python.org/3.0/library/warnings.html

**Comment by carmocca** [comment]
But I don't want to filter them, I want to log them and to have them play nicely with my tqdm bars.

**Comment by awaelchli** [comment]
@carmocca when we use logging instead of warnings, does it still only show the warning once? There are cases where warning is issued multiple times, and we want to only show it once, that's what the warnings module does by default.

**Comment by carmocca** [comment]
It does not show only once. However, a [filter](https://stackoverflow.com/questions/31953272/python-logging-print-message-only-once) could be used:

**Comment by carmocca** [comment]
Found out I can do what I want with https://docs.python.org/3/library/logging.html#integration-with-the-warnings-module.

Closing. Thanks!
