### ISSUE TITLE
log_gpu_memory should use a GPUStatsMonitor

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#3333]
## 🐛 Bug

`Trainer.log_gpu_memory` should use a `GPUStatsMonitor` callback

The only extra feature of `log_gpu_memory` is the ability to print the min and max memory used. We could add that to `GPUStatsMemory` if deemed necessary.

cc @rohitgr7 
https://github.com/PyTorchLightning/pytorch-lightning/pull/2932#issuecomment-672895220

**Comment by Borda** [comment]
@carmocca mind draft a PR? 🐰

**Comment by carmocca** [comment]
Should I wait until refactors are over?
