### ISSUE TITLE
Support FLOPS in profiling

### ISSUE THREAD

**Issue by ananthsub** [PyTorchLightning/pytorch-lightning#3337]
## 🚀 Feature
When the weights summary is run for the LightningModule, Lightning should also calculate the FLOPs for each module, in addition to the parameter size and in/out sizes. This could be conditional based on the torch module class and input/output shapes.

### Motivation
This would be useful for performance benchmarking and knowing how many FLOPs are computed in the LightningModule

### Pitch
We could extend the LayerSummary object here to also include a method for returning `flops`: in addition to num_parameters
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/core/memory.py

**Comment by ananyahjha93** [comment]
@ananthsub would you want to contribute this feature? Create a PR for it?

**Comment by ananthsub** [comment]
@ananyahjha93 here is my approach: 
- Add `flops` as an attribute to `LayerSummary`
- Calculate FLOPS in the hook here for a given module + input: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/core/memory.py#L84-L89
- Include it in the model summary table
Rough prototyping: https://gist.github.com/ananthsub/b9e23f480cd993945d2f3fc35f0520f9

What do you think of this approach?

**Comment by karthi0804** [comment]
Hi is it implemented?

**Comment by yuys0602** [comment]
> Hi is it implemented?
 I also want to know

**Comment by karthi0804** [comment]
> > Hi is it implemented?
> > I also want to know

@yuys0602  This is what I am using now. You can try [DeepSpeed](https://deepspeed.readthedocs.io/en/latest/flops-profiler.html)

**Comment by yuys0602** [comment]
> > > Hi is it implemented?
> > > I also want to know
> 
> @yuys0602 This is what I am using now. You can try [DeepSpeed](https://deepspeed.readthedocs.io/en/latest/flops-profiler.html)


thanks, it will be better if deepspeed Flops Profiler could be embedded into lightning.
