### ISSUE TITLE
Trainer was signaled to stop but required minimum epochs (100) or minimum steps (None) has not been met. Training will continue... 

### ISSUE THREAD

**Issue by david-waterworth** [PyTorchLightning/pytorch-lightning#3378]
When I initialise the trainer as follows:

`trainer = pl.Trainer.from_argparse_args(args, early_stop_callback=True, min_epochs=100, logger=mlflow, gpus=[0])`

I cannot halt training early with Ctrl-C, I get the message

`Trainer was signaled to stop but required minimum epochs (100) or minimum steps (None) has not been met. Training will continue... `

It seems to me that this message makes sense if the early stopping callback tries to stop before 100 epochs but Ctrl-C should really stop training unconditionally in my opinion.

**Comment by s-rog** [comment]
I looked into it and this does not seem like intended behavior. Which version of lightning are you on?

**Comment by david-waterworth** [comment]
@s-rog pytorch-lightning==0.9.0

**Comment by s-rog** [comment]
I am unable to replicate the issue on my end. Can you try the examples under `pl_examples`?

**Comment by david-waterworth** [comment]
I'm not getting the error message but running gpu_template.py for example I get the behaviour below - Ctrl-C doesn't work, the progress bar gets copied down a line and continues  (ie. each line represents a point where I hit Ctrl-C).

I'm using vscode on ubuntu 20.04 with a bash terminal

![image](https://user-images.githubusercontent.com/5028974/92689180-ebc35800-f381-11ea-91aa-af2917840c43.png)

**Comment by s-rog** [comment]
Are you using the trainer from pl_examples as well (with min_epochs added)?

**Comment by david-waterworth** [comment]
I added that but it didn’t make any difference, in either case Ctrl-C didn’t halt training but I couldn’t reproduce the original message

**Comment by s-rog** [comment]
At this point it's probably not caused by lightning but instead something in your env. I would first try running it outside vscode (in a native bash terminal) as there might be something wonky with signal propogation there.
