### ISSUE TITLE
TypeError: 'generator' object is not callable

### ISSUE THREAD

**Issue by david-waterworth** [PyTorchLightning/pytorch-lightning#3379]
I'm getting the exception TypeError: 'generator' object is not callable when I train with multiple GPU's

I'm not sure where it's coming from, my datasets are subclasses of torchtext.data.Dataset and the data loaders are torchtext.data.BucketIterator. 

What's the easiest way of identifying what's causing the exception?  

```
    # create trainer
    mlflow = loggers.MLFlowLogger("Transformer")
    trainer = pl.Trainer.from_argparse_args(args, early_stop_callback=True, min_epochs=10, logger=mlflow, gpus=[0,1])

    # prepare data
    train_dataset, val_dataset = load_datasets(path=args.path, files=args.files)
    train_loader, val_loader = create_dataloaders(train_dataset, val_dataset, batch_size=args.batch_size)

    # init the model
    hparams = vars(args)
    transformer = Transformer(src_vocab=train_dataset.vocab, tgt_vocab=val_dataset.vocab, **hparams)

    # train
    trainer.fit(transformer, train_loader, val_dataloaders=val_loader)
    transformer.freeze()


```

**Comment by awaelchli** [comment]
The first step is to look at the error message, the full stack trace and read what it is saying. Can you post that please? Plus the PL version you are using. If this is a bug in Lightning that we need to fix, it would be good to have a minimal code example.

**Comment by david-waterworth** [comment]
@awaelchli  here's the stack trace. I'll try and put together a minimal example tomorrow

pytorch-lightning==0.9.0

> Traceback (most recent call last):
>   File "/home/david/.pyenv/versions/3.8.4/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/home/david/.pyenv/versions/3.8.4/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/david/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
>     cli.main()
>   File "/home/david/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 430, in main
>     run()
>   File "/home/david/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 267, in run_file
>     runpy.run_path(options.target, run_name=compat.force_str("__main__"))
>   File "/home/david/.pyenv/versions/3.8.4/lib/python3.8/runpy.py", line 265, in run_path
>     return _run_module_code(code, init_globals, run_name,
>   File "/home/david/.pyenv/versions/3.8.4/lib/python3.8/runpy.py", line 97, in _run_module_code
>     _run_code(code, mod_globals, init_globals,
>   File "/home/david/.pyenv/versions/3.8.4/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/david/dev/machine-learning-research/src/annotation/src/transformer.py", line 161, in <module>
>     trainer.fit(transformer, train_loader, val_dataloaders=val_loader)
>   File "/home/david/.pyenv/versions/transformer/lib/python3.8/site-packages/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn
>     result = fn(self, *args, **kwargs)
>   File "/home/david/.pyenv/versions/transformer/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1052, in fit
>     self.accelerator_backend.train(model, nprocs=self.num_processes)
>   File "/home/david/.pyenv/versions/transformer/lib/python3.8/site-packages/pytorch_lightning/accelerators/ddp_spawn_backend.py", line 43, in train
>     mp.spawn(self.ddp_train, nprocs=nprocs, args=(self.mp_queue, model,))
>   File "/home/david/.pyenv/versions/transformer/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
>     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
>   File "/home/david/.pyenv/versions/transformer/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 149, in start_processes
>     process.start()
>   File "/home/david/.pyenv/versions/3.8.4/lib/python3.8/multiprocessing/process.py", line 121, in start
>     self._popen = self._Popen(self)
>   File "/home/david/.pyenv/versions/3.8.4/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
>     return Popen(process_obj)
>   File "/home/david/.pyenv/versions/3.8.4/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
>     super().__init__(process_obj)
>   File "/home/david/.pyenv/versions/3.8.4/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
>     self._launch(process_obj)
>   File "/home/david/.pyenv/versions/3.8.4/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
>     reduction.dump(process_obj, fp)
>   File "/home/david/.pyenv/versions/3.8.4/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
>     ForkingPickler(file, protocol).dump(obj)
> TypeError: 'generator' object is not callable

**Comment by david-waterworth** [comment]
@awaelchli 

The script below generates the same stack trace. I suspect it's related to the torchtext objects as I've just stubbed out all the pl callbacks and it still throws the exception. Not torchtext are deprecating these classes in the next release (although they will live in a legacy module for a while) 

Also sorry this downloads a lot of data (one time)! You can probably switch to a smaller dataset but I just copied the first example I found from torchtext and adapted to a DataModule.

```
> pip freeze
torch==1.6.0
torchtext==0.7.0
pytorch-lightning==0.9.0
mlflow==1.11.0
...
```

```
from torchtext import data, datasets
from torchtext.vocab import GloVe
import pytorch_lightning as pl

import torch
import torch.nn as nn
import torch.nn.functional as F
from pytorch_lightning import loggers


class DataModule(pl.LightningDataModule):
    def __init__(self, batch_size=4):
        super().__init__()
        self.batch_size = batch_size

    def setup(self, stage=None):
        # set up fields
        TEXT = data.Field(lower=True, include_lengths=True, batch_first=True)
        LABEL = data.Field(sequential=False)

        # make splits for data
        self.train, self.test = datasets.IMDB.splits(TEXT, LABEL)

        # build the vocabulary
        TEXT.build_vocab(self.train, vectors=GloVe(name='6B', dim=300))
        LABEL.build_vocab(self.train)

        self.src_vocab = TEXT.vocab
        self.tgt_vocab = LABEL.vocab

    def train_dataloader(self):
        train_iter, _ = datasets.IMDB.iters(self.batch_size)
        return train_iter
    
    def val_dataloader(self):
        _, val_iter = datasets.IMDB.iters(self.batch_size)
        return val_iter


class Transformer(pl.LightningModule):
    def __init__(self, **kwargs):
        super().__init__()

    @staticmethod
    def add_model_specific_args(parent_parser):
        parser = ArgumentParser(parents=[parent_parser], add_help=False)
        parser.add_argument('--d_model', default=512, type=int)
        parser.add_argument('--batch_size', default=256, type=int)  
        parser.add_argument('--learning_rate', default=1e-5) 
        return parser

    def loss_function(self, outputs, targets):
        return F.cross_entropy(outputs, targets, ignore_index=self.tgt_vocab.stoi['<pad>'])

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=self.hparams.learning_rate)

    def forward(self, src, tgt):
        pass

    def training_step(self, batch, batch_idx):
        pass

    def validation_step(self, batch, batch_idx):
        pass


if __name__ == '__main__':
    # to avoid relative import errors ensure "env": { "PYTHONPATH": "${workspaceFolder}/src" } is set in launch.json
    from argparse import ArgumentParser

    parser = ArgumentParser()
    # program args
    # model args
    parser = Transformer.add_model_specific_args(parser)  
    # trainer args
    parser = pl.Trainer.add_argparse_args(parser)
    # obtain args
    args = parser.parse_args()

    # create trainer
    mlflow = loggers.MLFlowLogger("Transformer")
    trainer = pl.Trainer.from_argparse_args(args, gpus=[0,1], early_stop_callback=True, logger=mlflow, row_log_interval=25)

    # prepare data
    dm = DataModule(batch_size=args.batch_size)
    dm.prepare_data()
    dm.setup()

    # init the model
    hparams = vars(args)
    transformer = Transformer(src_vocab=dm.src_vocab, tgt_vocab=dm.tgt_vocab, **hparams)

    # train
    trainer.fit(transformer, datamodule=dm)
    transformer.freeze()
```

**Comment by edenlightning** [comment]
@awaelchli mind taking a look?

**Comment by awaelchli** [comment]
@mateuszpieniak has used Lightning with torchtext before, maybe he has some tips.

**Comment by david-waterworth** [comment]
@awaelchli thanks for looking. I need to refactor this anyway since as I mentioned `torchtext` has started to deprecate their DataLoader / Dataset in place of the `torch` equivalents. I've been putting it off since they've not yet provided a migration path for custom datasets (frustratingly they seem to be focusing on migrating the built-in datasets using private pipeline methods - I feel they should have created a migration pathway first and then used it to migrate their datasets). 

@mateuszpieniak any pointers would be useful - I need to add '<sos>' and '<eos>' tokens to each example and then pad each batch. Ideally, by using high-performance code someone has already thoroughly tested
