### ISSUE TITLE
Using distributed_backend='dp' causes result.write to fail

### ISSUE THREAD

**Issue by willprice** [PyTorchLightning/pytorch-lightning#3384]
## 🐛 Bug

Saving results with `result.write` is broken up DP distributed training.

### To Reproduce

Perform something like this
```python
result.write('blah', ['one', 'two', 'three']
````
in a `test_step` and run with `distributed_backend='dp'`, PTL will then call into `Result.dp_reduce` and try to run
`self[k] = value.mean(dim=-1)` where `value` is the `predictions` dictionary which will subsequently fail.

**Comment by edenlightning** [comment]
Hey @willprice which version of lightning are you using?

**Comment by willprice** [comment]
0.9.0, sorry, should have put that in the original issue.

**Comment by edenlightning** [comment]
hey @willprice! We updated our API to use self.write instead of results objects, that should simplify things.

Can you try upgrading to 1.0.2 to see if issue presists?

**Comment by edenlightning** [comment]
Feel free to reopen if needed!
