### ISSUE TITLE
NeptuneLogger doesn't support fetching active experiment.

### ISSUE THREAD

**Issue by blatr** [PyTorchLightning/pytorch-lightning#3389]
Hi!
### 🚀 Feature
Currently NeptuneLogger doesn't support reconnecting to active experiment. Each initialization always creates a new one and there is no option to pass existing experiment id. 
However, this feature is already supported by Neptune library and actually implemented in _create_or_get_experiment() method inside NeptuneLogger class. 

### Proposal
Make it possible to pass optional argument **experiment_id** to class initialization. 
With this replacement _create_or_get_experiment() function will be able to fetch existing experiment during class initialization.

If you don't mind i can make a PR with this small enhancement.

**Comment by Borda** [comment]
@jakubczakon mind have look? 🐰

**Comment by pitercl** [comment]
Hi @blatr, I thinks it's a nice idea!
Please be aware, that there's already a PR in progress  (#3256) that'll probably come in a superficial conflict with yours, but I don't see any actual problems with this idea.
