### ISSUE TITLE
specifying one example input per network

### ISSUE THREAD

**Issue by sumanthratna** [PyTorchLightning/pytorch-lightning#3390]
#### What is your question?

I have a GAN, implemented with `pl.LightningModule`. right now, I can set `self.example_input_array = torch.rand(1, 3, 256, 256, device=self.device)`. However, that will output this:
```

  | Name         | Type                | Params | In sizes         | Out sizes       
-------------------------------------------------------------------------------------------
0 | net_G        | UnetGenerator       | 54 M   | [1, 3, 256, 256] | [1, 1, 256, 256]
1 | net_D        | NLayerDiscriminator | 2 M    | ?                | ?               
2 | criterionGAN | GANLoss             | 0      | ?                | ?               
3 | criterionL1  | L1Loss              | 0      | ?                | ?  
```

the input and output shapes for net_G are correct, but I'm unsure how to tell Lightning what the input shape for net_D is. 

right now, I don't really mind the `criterionGAN` and `criterionL1` shapes but ideally, I should be able to specify input shapes for those too. 

#### Code

I'm expecting something like this:
```python
self.example_input_array = {
    'net_G': torch.rand(1, 3, 256, 256, device=self.device),
    'net_D': torch.rand(1, 4, 256, 256, device=self.device),
}
```

I'm labeling this as a question because I feel like I simply missed this is in the docs and source; sorry in advance if this is really a feature request.

related code in lightning (I think):
https://github.com/PyTorchLightning/pytorch-lightning/blob/306d55c7f8dbe27567010ed7f6501683591e32bf/pytorch_lightning/core/lightning.py#L92-L98

#### What have you tried?

n/a

#### What's your environment?

 - OS: docker
    - host: macOS 10.16 Beta 6
    - container: 3.8-slim-buster (debian buster)
 - Packaging: pip (python3.8)
 - Version: 0.9.0

**Comment by awaelchli** [comment]
@sumanthratna the summary can only record what you pass through the forward of LightningModule. I assume you only have the generator there. 

Your suggestion of using a dict is unfortunately not going work. We interpret example_input_array the following way:
- Tensor: direct input to forward
- tuple: gets unpacked as *args to forward
- dict: gets unpacked as **kwargs to forward

If you want the table to show the discriminator, you need to include it in the forward pass. The input of the discriminator is determined by the output of the generator, I assume in your case.

Hope this helps

**Comment by sumanthratna** [comment]
@awaelchli Thanks for your reply! I think adding this to the documentation would be useful (I can only find `example_input_array` in the 0.4.9 docs). 

> If you want the table to show the discriminator, you need to include it in the forward pass. 

Hmm...I see why this might have been implemented as such, but in my case, I don't want to include it in the forward pass. For inference, for example, the output of the discriminator isn't really of use to me. 

That said, I'm still a little confused as to how calling `net_D` in `forward` will work. This is what I *want* to see:
```

  | Name         | Type                | Params | In sizes         | Out sizes       
-------------------------------------------------------------------------------------------
0 | net_G        | UnetGenerator       | 54 M   | [1, 3, 256, 256] | [1, 1, 256, 256]
1 | net_D        | NLayerDiscriminator | 2 M    | [1, 4, 256, 256] | [1, 1]
2 | criterionGAN | GANLoss             | 0      | ?                | ?               
3 | criterionL1  | L1Loss              | 0      | ?                | ?  
```
As you can see, the `net_D` input isn't the same as the output of the `net_G`. The `net_D` input is constructed by concatenating the generated output with the input along dimension 1, which results in 4 channels for `net_D`'s input. 

Based on what you described, I don't think there's any way to tell Lightning about this. I guess you can consider this a feature request now, assuming I'm not misunderstanding anything :)

**Comment by YannDubs** [comment]
@awaelchli I'm having a similar issue. A simple way to let the users change that if needed would be to have a method `forward_example_input` in the pl.module which by default simply calls `forward` but can be modified if needed just for computing the sizes. That would be a nice feature
