### ISSUE TITLE
How to specify 'mode' when using checkpoint_on in the new Result types.

### ISSUE THREAD

**Issue by Rob-Fletcher** [PyTorchLightning/pytorch-lightning#3401]
#### What is your question?
I have been using PL for a while now and am just getting around to switching all of my code over to a newer version (0.9.0 from 0.6.0). I would like to switch over to using the newer TrainResult and EvalResult types instead of plain dictionaries. In the past I used a ModelCheckpoint() that I passed into the trainer with the monitor and mode options set. Now using the EvalResult type and passing it a 'checkpoint_on' option, I dont know how to specify a mode (min or max). Is this possible? Looking through the code it seems like maybe you can still pass a 'mode' through the ModelCheckpoint() but this seems a bit strange since it splits up what you are monitoring and whether its a min or max into two different places that you have to specify (one in my model and another in the ModelCheckpoint() ). Is this right? If so would it make sense to add the ability to pass a mode in with the {Train/Eval}Result as well?

**Comment by Rob-Fletcher** [comment]
If there currently isnt a way to do this and you guys think its needed I can make a PR.

**Comment by carmocca** [comment]
`mode` is currently passed to `ModelCheckpoint`. I am with you in that it is confusing having the metric and the mode in different places. We have a discussion over at #3286 about how we should fix it.
