### ISSUE TITLE
Specify mlflow<1.11

### ISSUE THREAD

**Issue by tmcclintock** [PyTorchLightning/pytorch-lightning#3402]
## 🚀 Feature
Specify `mlflow<1.11` in the [`environment.yml`](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/environment.yml) file.

### Motivation

As I pointed out in [this issue](https://github.com/mlflow/mlflow/issues/3400) in the mlflow repo, the most recent version of that package creates an `mlruns` directory at the location of any script that imports it. Importing PL also results in this directory being created. This is problematic since it pollutes development environments, and especially test suites.

### Pitch

Specify a maximum mlflow version.

### Alternatives

Add `mlruns` to the `gitignore`.

**Comment by Borda** [comment]
I would add it to gitignore or adjust the MLFlowLogger accordingly, mind send a PR?

**Comment by tmcclintock** [comment]
Well, it isn't the MLFlowLogger that is the issue. It is the package itself. Just doing `import mlflow` results in the directory being created when on mlflow>=1.11.0.

I'll gladly PR a line in the gitignore for PL, but projects that use PL will still have this issue that is pretty difficult to track down.

**Comment by awaelchli** [comment]
@tmcclintock If it is a bug, it has to be fixed by the mlflow team, and then we should add `mlflow >= X` where X is the version it is fixed in. since mlflow is in the extras, you can control which version you want to install. you can downgrade the library yourself as a temporary fix, until it is resolved on their end. Please correct me if I'm wrong.

**Comment by tmcclintock** [comment]
@awaelchli of course. I offered on the mlflow issue I made to work on the topic, but they haven't gotten back to me yet. I figured that, for now, while this undesirable behavior is the default that PL should avoid it.

**Comment by tmcclintock** [comment]
Update - I am working with an mlflow dev to fix this. I will issue a PR here that follows @awaelchli's suggestion when it is solved in mlflow.

**Comment by tmcclintock** [comment]
The mlflow devs fixed this issue on master as [seen here](https://github.com/mlflow/mlflow/pull/3410). I don't know when this will make it into a version. I'll loop back around here when it does.

**Comment by tmcclintock** [comment]
This was fixed in mlflow's recent release, so I'm closing. This issue will only exist for specific minor versions of 1.11 (e.g. 1.11.0)

**Comment by awaelchli** [comment]
Awesome! thanks for taking care of this.

**Comment by Borda** [comment]
yeah, but probably we need to skip the [articular version `mlflow != 1.11` right?

**Comment by tmcclintock** [comment]
@Borda it turns out the update happened without updating the version, so I think taking no action is fine.
