### ISSUE TITLE
Models defined by data

### ISSUE THREAD

**Issue by david-waterworth** [PyTorchLightning/pytorch-lightning#3406]
Is this correct (https://pytorch-lightning.readthedocs.io/_/downloads/en/latest/pdf/ pg17)

The first code example shows `prepare_data()` and `setup()` being called on the dataloader, but then it is not passed to `fit()`?

The second box has no explanation - I assume it's an alternative to the first code example?

![image](https://user-images.githubusercontent.com/5028974/92544980-89d7f500-f292-11ea-88d2-26cec7870eda.png)

**Comment by rohitgr7** [comment]
yeah, should be passed to `.fit` in the example. Mind send a PR for doc-fix?
