### ISSUE TITLE
progress bar summing both train and val steps 

### ISSUE THREAD

**Issue by yairkit** [PyTorchLightning/pytorch-lightning#3415]
for example, for **70** train samples and **20** validation samples:
progress-bar is:
Epoch 0:   0%|          | 0/**90**

is that a normal behavior for pl?

Thanks

**Comment by ydcjeff** [comment]
yes if you have defined train + val dataloaders

**Comment by yairkit** [comment]
@ydcjeff Thanks for the quick answer,

I did define both train and val dataloaders.
Isn't pl supports separate pbars for training, val?

**Comment by ydcjeff** [comment]
That is a main pbar that shows train + val samples if you have defined them
that main bar acts as a train pbar in training and
another pbar shows up at validation.

**Comment by BYJRK** [comment]
@yairkit Actually that did confuse me in the very beginning when I just could not find out why the total iteration number within a single epoch should be like that. I actually don't think it's necessary adding the validation iters to the main pbar as there is another pbar running. Why not just freeze the main pbar for a little while?
