### ISSUE TITLE
Issue with trainer.test in "ddp" distributed mode

### ISSUE THREAD

**Issue by griff4692** [PyTorchLightning/pytorch-lightning#3430]
Hi -

I have the following pseudo code workflow:

> trainer = Trainer(distributed_backend='ddp', ...)
model = new custom LightningModule
trainer.fit(model, ...)
model.freeze()
train.test(model, ...)

The error that I get is this:

`AssertionError: DistributedDataParallel is not needed when a module doesn't have any parameter that requires a gradient.`

What is the best way to address this?

Thanks very much,
Griffin

**Comment by rohitgr7** [comment]
That is a PyTorch `AssertionError`. Try it without calling `model.freeze()`?

**Comment by griff4692** [comment]
Thanks! this worked
