### ISSUE TITLE
How to disable printings about GPU/TPU

### ISSUE THREAD

**Issue by 7rick03ligh7** [PyTorchLightning/pytorch-lightning#3431]
How to disable this printings?

![image](https://user-images.githubusercontent.com/15386257/92659283-0c17f600-f333-11ea-90e4-a9655c35ff8d.png)

**Comment by SkafteNicki** [comment]
It is currently not possible to disable printing of that. For reference it is printed by these lines:
https://github.com/PyTorchLightning/pytorch-lightning/blob/8f6b115511166e404c1419000a3bfa15865a9885/pytorch_lightning/trainer/distrib_data_parallel.py#L296-L298
and this line:
https://github.com/PyTorchLightning/pytorch-lightning/blob/8f6b115511166e404c1419000a3bfa15865a9885/pytorch_lightning/trainer/distrib_data_parallel.py#L377

**Comment by rohitgr7** [comment]
Check #2757.

**Comment by 7rick03ligh7** [comment]
@rohitgr7 
Thanks

These two lines helped me
```
import logging
logging.getLogger('lightning').setLevel(0)
```

**Comment by goldmyu** [comment]
This is still an issue today, especially when working with multiple GPUs and num_of_workers>0...

**Comment by LingxiaoShawn** [comment]
This is still an issue. This actually can be fixed easily hope someone can do this.

**Comment by max0x7ba** [comment]
Another way to disable these messages:

```
pytorch_lightning.utilities.distributed.log.setLevel(logging.ERROR)
```

**Comment by angelolovatto** [comment]
It seems that the base logger for lightning has changed since @7rick03ligh7's last comment. The following does the job now
```python
logging.getLogger("pytorch_lightning").setLevel(logging.WARNING)
```

**Comment by Hockey86** [comment]
As of lightning v1.9.4,

`logging.getLogger("lightning.pytorch.utilities.rank_zero").setLevel(logging.WARNING)` disables the following output:
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

`logging.getLogger("lightning.pytorch.accelerators.cuda").setLevel(logging.WARNING)` disables the following output:
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

**Comment by pfk-beta** [comment]
> @rohitgr7 Thanks
> 
> These two lines helped me
> 
> ```
> import logging
> logging.getLogger('lightning').setLevel(0)
> ```

Let's remove all warnings, and let's use some meaningless value 0.

**Comment by youurayy** [comment]
as of PL 2.2.4:
```python
logger = logging.getLogger('pytorch_lightning.utilities.rank_zero')
logger.setLevel(logging.ERROR)
... your code here ...
logger.setLevel(logging.INFO)
```
or
```python
logger = logging.getLogger('pytorch_lightning.utilities.rank_zero')
class IgnorePLFilter(logging.Filter):
    def filter(self, record):
        return 'available:' not in record.getMessage()
logger.addFilter(IgnorePLFilter())
```

**Comment by carusyte** [comment]
As of today, I'm using 2.4.0 and seems I need to maneuver log level for `lightning.fabric.utilities.rank_zero`.
```python
logger = logging.getLogger('lightning.fabric.utilities.rank_zero')
logger.setLevel(logging.FATAL)
... your code here ...
logger.setLevel(logging.INFO)
```

**Comment by Gingko4ever** [comment]
Customize the keywords according to your needs.
```
import logging
class IgnorePLFilter(logging.Filter):
    def filter(self, record):
        keywords = ['available:', 'CUDA', 'LOCAL_RANK:']
        return not any(keyword in record.getMessage() for keyword in keywords)
    
logging.getLogger('pytorch_lightning.utilities.rank_zero').addFilter(IgnorePLFilter())
logging.getLogger('pytorch_lightning.accelerators.cuda').addFilter(IgnorePLFilter())
```

**Comment by JackCaster** [comment]
With lightning `2.5.0` I had to do:

```python
def device_info_filter(record):
    return "PU available: " not in record.getMessage()

logging.getLogger("lightning.pytorch.utilities.rank_zero").addFilter(device_info_filter)
```

modified from https://github.com/Lightning-AI/pytorch-lightning/issues/13378#issuecomment-1170258489
