### ISSUE TITLE
Cometml Logger epoch is not set.

### ISSUE THREAD

**Issue by Vozf** [PyTorchLightning/pytorch-lightning#3437]
## 🐛 Bug

While logging using comet ml there is an argument to set epoch https://www.comet.ml/docs/python-sdk/Experiment/#experimentlog_metrics
The info is available in metrics dict, but instead of passing it as an arg, it is passed as metrics value. I will suply a PR in a moment

**Comment by awaelchli** [comment]
looks like it's not a mandatory argument. is it ok if I remove the bug label?

**Comment by Vozf** [comment]
Sure
