### ISSUE TITLE
Conda pytorch-lightning breaks torchvision

### ISSUE THREAD

**Issue by matthaeusheer** [PyTorchLightning/pytorch-lightning#3443]
## 🐛 Bug

I have to use conda on our SLURM cluster. First I installed pytorch and torchvision within a conda environment which works fine. As soon as I additionally install pytorch-lightning, torchvision breaks

### To Reproduce

1. ```conda create --name pytorch_test_env pytorch torchvision cudatoolkit --channel pytorch```
2. ```conda activate pytorch_test_env```
1. ```python``` and ```import torch``` and ```import torchvision``` -> works fine
2. exit and run ```conda install -c conda-forge pytorch-lightning```
  Problem(?): reports that pytorch will be updated: ```pytorch::pytorch-1.1.0-py3.7_cuda9.0.~ --> pkgs/main::pytorch-1.3.1-cpu_py37h62f834f_0```
3. again, inside a python shell do ```import torchvision```
4. The error is
```
Import Error: <"path_to">/lib/python3.7/site-packages/torchvision/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1011CPUTensorIdEv
```

### Expected behavior

Lightning will be installed and work side-by-side with my current pytorch version.

### Environment

```
* CUDA:
	- GPU:
	- available:         False
	- version:           None
* Packages:
	- numpy:             1.19.1
	- pyTorch_debug:     False
	- pyTorch_version:   1.3.1
	- pytorch-lightning: 0.9.0
	- tensorboard:       2.2.0
	- tqdm:              4.48.2
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         
	- python:            3.7.9
	- version:           #1 SMP Debian 4.9.228-1 (2020-07-05)
```

### Additional context

Note that this machine does not have a GPU (see above). The GPU machine will be the one I submit a job to via SLURM.

**Comment by ydcjeff** [comment]
Could you try reinstalling pytorch, torchvision, pytorch-lightning with the version you will use?

**Comment by Borda** [comment]
yes, it seems your base PT version is 1.1 and PL requires >= 1.3 so you need to reinstall torchvision...
