### ISSUE TITLE
Not able to train lightning with tpu

### ISSUE THREAD

**Issue by soumochatterjee** [PyTorchLightning/pytorch-lightning#3445]
![image](https://user-images.githubusercontent.com/42636586/92727897-79f10b80-f38d-11ea-8c6c-c06a4436b274.png)
  
### To Reproduce
[Link ](https://www.kaggle.com/soumochatterjee/landmark-detection)
 Go to the link and click edit to run the cells for reproducing the error .

**Comment by Borda** [comment]
@lezwon mind have look? 🐰

**Comment by lezwon** [comment]
This looks to be more like a kaggle memory issue. @sumanthratna try reducing the batch size? Also, to make the notebook public :)

**Comment by soumochatterjee** [comment]
@lezwon are u asking me ?

**Comment by soumochatterjee** [comment]
Tried batch_size  of 512 but still its same ... i also tried to train this 98 GB dataset on Kaggle Gpu but getting cuda device-side assert error . Made  the notebook public

**Comment by lezwon** [comment]
The batch size of 1024 or 512 should be the problem. I tried with a batch size of 32. Seemed to work fine.

**Comment by soumochatterjee** [comment]
I cann't see any changes after changes..  only this thing is appearing
![image](https://user-images.githubusercontent.com/42636586/92761044-e3354680-f3ae-11ea-93fd-2153c6cda7cd.png)

@lezwon  Can u please post ur changes with the progress bar ...

**Comment by lezwon** [comment]
Try this one: https://www.kaggle.com/lezwon/landmark-detection

**Comment by soumochatterjee** [comment]
Thanks @lezwon Seems like it is training n
I saw you added these lines

!pip uninstall typing -y
!pip install -qU git+https://github.com/PyTorchLightning/pytorch-lightning.git

and changed the batchsize to 16 for the model to start training  on tpu ????????

Also getting the **RuntimeError: CUDA error: device-side assert triggered**  while running 
[this notebook](https://www.kaggle.com/soumochatterjee/landmark-detection-gpu-pytorchlightning) on gpu

![image](https://user-images.githubusercontent.com/42636586/92785865-6497d380-f3c5-11ea-9a58-666c8b7c9cb4.png)

**Comment by lezwon** [comment]
I installed PyTorch lightning from master itself as the TPU support is more stable there. As for batch size, I faced an out of memory issue after a while when choosing 32. Hence 16.

**Comment by lezwon** [comment]
@rohitgr7 any idea about the cuda error?

**Comment by Borda** [comment]
there shall not be anything about CUDA in TPU ran... mind trace it to the source?

**Comment by lezwon** [comment]
I think it occurs when he runs it on gpu.

**Comment by rohitgr7** [comment]
@soumochatterjee just `LabelEncode` `landmark_id`, it will work.

Also, you need to fix this:
```python
self.aug = albumentations.Compose([
                albumentations.Resize(img_height , img_width, always_apply = True) ,
                albumentations.Normalize(mean , std , always_apply = True),
                Cutout(),
                albumentations.ShiftScaleRotate(shift_limit = 0.0625,
                                                scale_limit = 0.1 ,
                                                rotate_limit = 5,
                                                p = 0.9)
            ])
```
since `Cutout` is not in `albumentations`, you will get an error later on. You can use `albumetations.Cutout()`.

**Comment by lezwon** [comment]
@soumochatterjee is your issue resolved?

**Comment by soumochatterjee** [comment]
Yes @lezwon thanks for all the help .

**Comment by feiwofeifeixiaowo** [comment]
@lezwon  meet same issue here, can't start training when using tpu with pl(code run success with kaggle gpu).
i try smaller batch size, augument all use from albumentations, install from master branch, still got no luck.


Go to the link and click edit to run the cells for reproducing the error .
[kaggle notebook](https://www.kaggle.com/feiwofeifeixiaowo/cassava-tpu-training)

**Comment by rohitgr7** [comment]
@feiwofeifeixiaowo the notebook link is not accessible.

**Comment by feiwofeifeixiaowo** [comment]
@lezwon @rohitgr7   Do you have any ideas for troubleshooting? Thanks

**Comment by lezwon** [comment]
@feiwofeifeixiaowo I tried running the notebook with one tpu core. The training seems to start but it's extremely slow. My assumption is that there is some bottleneck when loading your data. I'm still debugging it.

**Comment by feiwofeifeixiaowo** [comment]
> @feiwofeifeixiaowo I tried running the notebook with one tpu core. The training seems to start but it's extremely slow. My assumption is that there is some bottleneck when loading your data. I'm still debugging it.

yesterday i change read image backend from cv2 to PLI ，still got no luck .

**Comment by feiwofeifeixiaowo** [comment]
hi @lezwon , after set gradient_clip_val to zero everything goes well. 
in xla troubleshooting guide [link](https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#known-performance-caveats), 
it seems that ori gradient_clip_val action will cause this slow thing.
> 

Use torch.where to substitute control flow when applicable. E.g. The control flow with item() used in clip_grad_norm_ is problematic and impacts performance, so we have patched clip_grad_norm_ by calling torch.where instead, which gives us a dramatic performance improvement.
```Python
...
else:
  device = parameters[0].device
  total_norm = torch.zeros([], device=device if parameters else None)
  for p in parameters:
    param_norm = p.grad.data.norm(norm_type) ** norm_type
    total_norm.add_(param_norm)
  total_norm = (total_norm ** (1. / norm_type))
clip_coef = torch.tensor(max_norm, device=device) / (total_norm + 1e-6)
for p in parameters:
  p.grad.data.mul_(torch.where(clip_coef < 1, clip_coef, torch.tensor(1., device=device)))
```

thanks for your help again.

**Comment by lezwon** [comment]
@feiwofeifeixiaowo ah yes.. calling .item() makes xla to forcibly execute the graph which slows it down. Sorry I didn't catch this earlier and glad you figured it out. Will keep a note of this issue in the docs 😊👍

**Comment by feiwofeifeixiaowo** [comment]
@lezwon , with albumentations augment blew, Idle Time very high. is there any trick/tips to speed up ?
```Python
train_transform = Compose(
        [
            Resize(height=image_size[0], width=image_size[1]),
            OneOf([RandomBrightness(limit=0.1, p=1), RandomContrast(limit=0.1, p=1)]),
            OneOf([MotionBlur(blur_limit=3), MedianBlur(blur_limit=3), GaussianBlur(blur_limit=3)], p=0.5),
            VerticalFlip(p=0.5),
            HorizontalFlip(p=0.5),
            ShiftScaleRotate(
                shift_limit=0.2,
                scale_limit=0.2,
                rotate_limit=20,
                interpolation=cv2.INTER_LINEAR,
                border_mode=cv2.BORDER_REFLECT_101,
                p=1,
            ),
            Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225), max_pixel_value=255.0, p=1.0),
        ]
    )
```
![image](https://user-images.githubusercontent.com/4606937/104806064-a58a7380-580f-11eb-95f5-9883dcd76cb5.png)

**Comment by lezwon** [comment]
@rohitgr7 any idea about this?

**Comment by feiwofeifeixiaowo** [comment]
> @rohitgr7 any idea about this?

i add prefetch dataloader, but seems not help yet.
[prefetch_generator](https://github.com/justheuristic/prefetch_generator)

**Comment by rohitgr7** [comment]
not sure about this. Is it faster when using albumentations in the case of GPUs? try increasing the batch_size (a multiple of 2 maybe) since 8 core TPU training requires a high batch_size to work effectively.

Also, you check some performance tips here:
https://github.com/PyTorchLightning/pytorch-lightning/blob/release/1.2-dev/docs/source/tpu.rst#performance-considerations

FYI, there is a prefetch option in native DataLoader too.
https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader

**Comment by feiwofeifeixiaowo** [comment]
> not sure about this. Is it faster when using albumentations in the case of GPUs? try increasing the batch_size (a multiple of 2 maybe) since 8 core TPU training requires a high batch_size to work effectively.
> 
> Also, you check some performance tips here:
> https://github.com/PyTorchLightning/pytorch-lightning/blob/release/1.2-dev/docs/source/tpu.rst#performance-considerations
> 
> FYI, there is a prefetch option in native DataLoader too.
> https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader

i will try this, thanks~
