### ISSUE TITLE
Very slow training on SLURM cluster

### ISSUE THREAD

**Issue by matthaeusheer** [PyTorchLightning/pytorch-lightning#3451]
## 🐛 Bug

When switching from my local machine (old and slow 960m laptop GPU) to a SLURM cluster with Titan X GPU's, I see a significant drop in performance from 4.71it/s to 7s/it (!) - so basically training becomes unusably slow.

### To Reproduce
1. Take a model and submit it as a SLURM job. Happy to provide further details if requested, not sure what is relevant here.

```
2020-09-10 22:11:58,979 : lightning    : INFO       GPU available: True, used: True
2020-09-10 22:11:58,979 : lightning    : INFO       TPU available: False, using: 0 TPU cores
2020-09-10 22:11:58,979 : lightning    : INFO       CUDA_VISIBLE_DEVICES: [0,1]
2020-09-10 22:12:01,698 : lightning    : INFO       Set SLURM handle signals.
Epoch 1:  40%|███▉      | 150/377 [19:11<29:02,  7.68s/it, loss=2.401, v_num=19]
```

#### Code sample
The is setup as follows
```python
logger = TensorBoardLogger(str(DATA_DIR_PATH / 'lightning_logs'), name=Path(__file__).stem)
trainer_kwargs = {'logger': logger,
                  'default_root_dir': str(DATA_DIR_PATH / 'lightning_logs'),
                  'val_check_interval': 0.2,  # check (1 / value) * times per train epoch
                  'gpus': 1,
                  # 'distributed_backend': 'ddp',  # checked with ddp enabled, 2 GPUs, multiple workers etc., same slow behaviour
                  'fast_dev_run': False}
trainer = pl.Trainer(**trainer_kwargs)
```

### Environment
* Packages:
	- numpy:                 1.18.1
	- pyTorch_debug:   False
	- pyTorch_version: 1.4.0
	- pytorch-lightning: 0.8.5
	- tensorboard:        1.15.0
	- tqdm:                   4.43.0

 - PyTorch Version (e.g., 1.0): 
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.7.9
 - CUDA/cuDNN version: cudatoolkit 10.0
 - GPU models and configuration: TitanX (on SLURM cluster)

**Comment by bartonp2** [comment]
I have the same problem on a cluster with LSF. Basic profiling shows most time is spent in the forwards and backwards pass, as well as the optimisation step. Furthermore, checking GPU utilisation appears to be 0% even though pytorch lightning found the gpu device and said it was using it.

**Comment by bartonp2** [comment]
For me the problem turned out to the setting of the  'distributed_backend' option in the trainer. I had set this to 'None' for testing purposes through the command line. Removing this command line option or changing it back to 'ddp' solved the issue. GPU utilisation is now back up.

**Comment by edenlightning** [comment]
@matthaeusheer were you able to solve the issue?

**Comment by williamFalcon** [comment]
this looks like user error
