### ISSUE TITLE
Model summarize displayed twice before training starts

### ISSUE THREAD

**Issue by ananthsub** [PyTorchLightning/pytorch-lightning#3458]
## 🐛 Bug

Model summarize is called in two spots, which results in duplication in the logs:
- It's called once in the training loop: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/training_loop.py#L160

And I'm unsure how it's called again

![119083522_2815247905426328_3914141584028152470_n](https://user-images.githubusercontent.com/2382532/92856189-04deff80-f3a8-11ea-824c-35bd2aef2258.png)

The first time is with the logger.info(...) since it's formatted. The second time it appears to be logged with `print(...)` since the table formatting doesn't handle newlines

### To Reproduce
Run any training with `weights_summary` set on the trainer

### Expected behavior
We only call summarize once

**Comment by rohitgr7** [comment]
Tried on master. Working fine. Is it happening with ddp backend only?

**Comment by ananthsub** [comment]
Yes this happens with DDP backend

**Comment by awaelchli** [comment]
on my windows machine, single gpu, happens too. but the others stuff is also logged twice, including all warnings.

```
TPU available: False, using: 0 TPU cores
TPU available: False, using: 0 TPU cores
CUDA_VISIBLE_DEVICES: [0]
CUDA_VISIBLE_DEVICES: [0]
```
¨
which means it is logging related, not model summary. 
I will investigate

**Comment by JVGD** [comment]
Just started migration of our codebase to Lightning and the first trainer I write have this issue... Could this be something related with duplicated handlers in logger? It might be that the logger.getLogger() which is a singleton is called twice, so it might be that 2 handlers are initialized, the root handler and another stream handler

**Comment by awaelchli** [comment]
yes, I think that's the case. does my PR not resolve the problem for you?

**Comment by JVGD** [comment]
Hi, I am on Linux in Ubuntu 18.04 distro.

I tried your PR but unfortunately it does not solve my issue, maybe I am doing something wrong?
![image](https://user-images.githubusercontent.com/6736158/93877394-af282280-fcd8-11ea-89f8-e5a34f220253.png)

**Comment by JVGD** [comment]
I am using Ubuntu 18.04.

I tried you PR but unfortunately it does not solve the issue. Maybe I am doing something wrong?
![image](https://user-images.githubusercontent.com/6736158/93877650-04fcca80-fcd9-11ea-8193-eef3156949a4.png)

**Comment by JVGD** [comment]
I am using Ubuntu 18.04.

I tried you PR but unfortunately it does not solve the issue. Maybe I am doing something wrong?
![image](https://user-images.githubusercontent.com/6736158/93877718-29f13d80-fcd9-11ea-8adb-d1690a69f064.png)

**Comment by awaelchli** [comment]
@JVGD could you try again with my updated branch. sorry, I don't have much experience with this python logging, for me the duplicate messages are resolved locally.

**Comment by JVGD** [comment]
Unfortunately is still showing duplicated logs. I am going to do further testing, but as far as I know I think the pytroch_lightning logger adds an extra StreamHandler to the base root logger. Maybe that is why there are duplicates

**Comment by awaelchli** [comment]
indeed, if we remove the streamhandler, this also solves the problem (for me). can you confirm?
https://github.com/PyTorchLightning/pytorch-lightning/pull/3514/files

**Comment by JVGD** [comment]
Amazing! it was just deleting that line and now it works like a charm. By the way, I did it in the pytorch-lightning==0.9.0 version, I was in my development environment. So I haven't been able to test it on your branch. But tomorrow I will!

Thank you for the support. Now it looks great:
![image](https://user-images.githubusercontent.com/6736158/93907924-4784ce00-fcfe-11ea-9f27-832315cebc9d.png)

**Comment by awaelchli** [comment]
@JVGD this is all really strange. I checked again with a different machine (also ubuntu 18) and now It's not printing the model summary, while on my notebook it did. 
I need to go through the python versions and see if there is a difference. ugh :(

**Comment by JVGD** [comment]
Mmm really strange man, you almost got it. I got an hypothesis: maybe you don't see any logs because the root logger does not have any handlers. This means, pytorch_lightning did not add any handlers (because we removed it), and app you are running does not add any other handlers.

I think it works in my case because my app already adds a StreamHandler at the beginning. So there is at least one StreamHandler.

If it helps, in my python project I check explicitly that there is only one StreamHandler in the root base logger. Maybe doing something like this could help. The idea is to add a StreamHandler only if there is none, but if it is at least one, then use that one (instead of adding another that will print duplicated logs).

```python
        # Checking if there is already a stream
        # handler for avoinding log repetition
        console_hanlder_configured = any(
            [isinstance(handler, logging.StreamHandler)
             for handler in root_logger.handlers])

        # If console handler not configured, then add it
        if not console_hanlder_configured:
            # Handler for logging to stdout
            console_handler = logging.StreamHandler()
            console_handler.setFormatter(formatter)
            console_handler.setLevel(level)

            # Adding handler to logger
            root_logger.addHandler(console_handler)
```

**Comment by williamFalcon** [comment]
are we good on this? i also made a bunch of stability fixes to ddp including duplicate logging and so on

**Comment by JVGD** [comment]
Last time I checked it wasn't but I am happy to check it out. The branch to test is still _bugfix/duplicated-logging_ right?

**Comment by JVGD** [comment]
Tested, I am good on my side
![image](https://user-images.githubusercontent.com/6736158/94782957-4aea1a80-03cc-11eb-8687-96ef362e408f.png)

**Comment by kielnino** [comment]
I'm using pytorch-lightning 1.0.7 and still get all the logging and summary twice:
```
GPU available: True, used: True
[2020-11-19 08:03:30,215][lightning][INFO] - GPU available: True, used: True
TPU available: False, using: 0 TPU cores
[2020-11-19 08:03:30,215][lightning][INFO] - TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
[2020-11-19 08:03:30,215][lightning][INFO] - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Using native 16bit precision.
[2020-11-19 08:03:30,216][lightning][INFO] - Using native 16bit precision.

  | Name                            | Type                  | Params
--------------------------------------------------------------------------
0 | discriminative_loss             | DiscriminativeLoss    | 0     
1 | val_discriminative_metric       | PanopticQualityMetric | 0     
2 | test_discriminative_metric      | PanopticQualityMetric | 0     
3 | base                            | Unet                  | 24 M  
4 | binary_segmentation             | SegmentationHead      | 145   
5 | binary_segmentation_loss        | BCEWithLogitsLoss     | 0     
6 | val_binary_segmentation_metric  | Accuracy              | 0     
7 | test_binary_segmentation_metric | Accuracy              | 0     
[2020-11-19 08:03:32,536][lightning][INFO] - 
  | Name                            | Type                  | Params
--------------------------------------------------------------------------
0 | discriminative_loss             | DiscriminativeLoss    | 0     
1 | val_discriminative_metric       | PanopticQualityMetric | 0     
2 | test_discriminative_metric      | PanopticQualityMetric | 0     
3 | base                            | Unet                  | 24 M  
4 | binary_segmentation             | SegmentationHead      | 145   
5 | binary_segmentation_loss        | BCEWithLogitsLoss     | 0     
6 | val_binary_segmentation_metric  | Accuracy              | 0     
7 | test_binary_segmentation_metric | Accuracy              | 0 
```
I'm using a vanilla LightningModule without any specific logger. I just do `self.log()` in the training loop.

**Comment by ianlini** [comment]
I still have the duplicate log issue like this:
```
GPU available: True, used: True
[2021-01-22 07:43:17,623][INFO] lightning: GPU available: True, used: True
TPU available: None, using: 0 TPU cores
[2021-01-22 07:43:17,623][INFO] lightning: TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
[2021-01-22 07:43:17,623][INFO] lightning: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
```
I'm using pytorch-lightning version 1.1.1, and I configured the root log using `logging.dictConfig` with `"disable_existing_loggers": False`. The configuring are done after importing pytorch-lightning. I think it's a common approach.

I think these lines in `__init__.py` should be removed
```
_logger.addHandler(python_logging.StreamHandler())	
_logger.setLevel(python_logging.INFO)
```
This is the only library having this issue in my hundreds of dependencies.
related issue: #1503

**Comment by awaelchli** [comment]
@ianlini see #4621 and #5509 for progress on this issue

**Comment by fingoldo** [comment]
Just observed this doubled logging in the recent version of Lightning. It happens in summarize method of the ModelSummary class.
Execution of  this single line log.info("\n" + summary_table) produces doubled log entry. I have my custom logger configured. I suppose either my logger or the logger of Lightning are not configured correctly.
