### ISSUE TITLE
Links between Lightning docs are not linked properly

### ISSUE THREAD

**Issue by ydcjeff** [PyTorchLightning/pytorch-lightning#3479]
## 📚 Documentation

https://pytorch-lightning.readthedocs.io/en/latest/trainer.html#profiler

The link to profiler.html is not properly linked.
These links are happening too (found out so far).
- link to multi gpu docs
- link to slurm docs
- link to lr_finder docs
- link to logger docs

This is not happening on the stable 0.9.0 docs.
I couldn't find what PR caused this or something caused this.

Currently, they are linked like 
```py
`Title <title.rst>`_
```
Using `:ref:` fixed this for now. But, I'm not sure this is a proper way to fix.

**Comment by awaelchli** [comment]
@ydcjeff yes using ref on the anchor is correct. could you try to fix it?

**Comment by ydcjeff** [comment]
@awaelchli okay, I will try it
