### ISSUE TITLE
Load not only last_chechpoint but early_stop_callback history

### ISSUE THREAD

**Issue by xujiaze13** [PyTorchLightning/pytorch-lightning#3488]
When I resume the training process.

> model = MyModel()
> trainer = Trainer(early_stop_callback=pl.callbacks.EarlyStopping(), resume_from_checkpoint='last.ckpt')
> trainer.fit(model)

I find that the early_stop history is not considered.

For example, the best epoch is 7, early_stop patience is 3.
So after epoch 10, the training procedure ends, and the best epoch is 7.

However, if I stop training after epoch 7, and then resume training.
The best epoch would not be 7. It will be 8 or 9 or 10.

How could I get the best epoch when (stop and resume) occurs?

**Comment by awaelchli** [comment]
which version of Lightning are you using? we recently added persistence to the callbacks. #2501

**Comment by xujiaze13** [comment]
> which version of Lightning are you using? we recently added persistence to the callbacks. #2501

0.9.0

**Comment by rohitgr7** [comment]
try `master` or `0.9.1rc3`. It should work.

**Comment by xujiaze13** [comment]
I tried `0.9.1rc3` by
`a=torch.load('./lightning_logs/version_1/checkpoints/last.ckpt')`
and
`a['callbacks'][pl.callbacks.ModelCheckpoint]['best_model_path']`
results as
`"./lightning_logs/version_1/checkpoints/epoch=9.ckpt"`

However, the best model path should be 
`"./lightning_logs/version_0/checkpoints/epoch=6.ckpt"`

Is there some templates for reference? Thanks

**Comment by xujiaze13** [comment]
Maybe I should manually load the early stop from checkpoint?

https://github.com/PyTorchLightning/pytorch-lightning/blob/c60c4c4be04cf0c9d635ac8828cb73579808ba68/tests/callbacks/test_early_stopping.py#L50-L64

**Comment by rohitgr7** [comment]
> results as
"./lightning_logs/version_1/checkpoints/epoch=9.ckpt"
However, the best model path should be
"./lightning_logs/version_0/checkpoints/epoch=6.ckpt"

can you recheck? versions are different here.

**Comment by xujiaze13** [comment]
Yes. I resume from checkpoint in version_0.
And version_1 appears

**Comment by awaelchli** [comment]
> Yes. I resume from checkpoint in version_0.
> And version_1 appears

This is expected, since it is a new run, it will create a new version. But I would expect the path be correctly saved into the checkpoint. Does the same happen if you load epoch 9 checkpoint instead of last?

Maybe the epoch counting is incorrect when resuming from checkpoint

**Comment by xujiaze13** [comment]
> > Yes. I resume from checkpoint in version_0.
> > And version_1 appears
> 
> This is expected, since it is a new run, it will create a new version. But I would expect the path be correctly saved into the checkpoint. Does the same happen if you load epoch 9 checkpoint instead of last?
> 
> Maybe the epoch counting is incorrect when resuming from checkpoint

Yes. Same problem happens.
When it loads the checkpoint and continues to run, it only considers new epochs and ignore the val_loss in old checkpoint.

**Comment by rohitgr7** [comment]
@xujiaze13 still facing this issue on master? can you put up a colab notebook for this issue?
