### ISSUE TITLE
training_step should allow returning None

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#3491]
## 🐛 Bug

In my dataset, some of the samples are too small and cannot produce valid losses. If all of the samples of a batch are invalid, I need to return None because I do not have a valid loss. Lightning does not seem to allow it.

### To Reproduce

```python
def training_step(self, *args, **kwargs):
    return None
```
In 0.9.0:
```
  File "python3.8/site-packages/pytorch_lightning/trainer/logging.py", line 140, in process_output
    for k, v in output.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

### Expected behavior

Training should not stop and should move on to the next iteration.

**Comment by teddykoker** [comment]
Thanks for the report! I just verified, and you should be able to return `None` in your validation step (you will get a `RuntimeWarning` but everything should still work.

You are correct that we do not support `None` values for the training step. Typically if I want to do some sort of data validation I do that in my Dataset:
```python
class MyDataset(torch.utils.data.Dataset):
    def __getitem__(self, index):
        if not valid(index):
            return None
        return self.data[index]
```

Then you can write a collate_fn to skip these `None`s:
```python
def collate_fn(batch):
    batch = [d for d in batch if d is not None]

dataset = MyDataset()
dataloader = torch.utils.data.DataLoader(dataset, collate_fn=collate_fn)
```

Hope this helps! If you still need `train_step` to support `None` values, please open a feature request.

**Comment by carmocca** [comment]
Thanks for your suggestion!

Your proposal is a valid workaround, however, in my case, whether a sample is valid or not depends on the loss function so it is a bit ugly to check this inside the dataset/dataloader.

Assuming this is not very hard to support, I think we should do it.

**Comment by teddykoker** [comment]
I see. I'll see if there is a work around you can use in the meantime. I'll mark this as a feature request.

**Comment by carmocca** [comment]
I just realized your proposal does not actually solve the issue because if all of the samples in the `collate_fn` batch are `None`, it just returns an empty list and we still have to skip that training iteration.

**Comment by williamFalcon** [comment]
yeah this is fine. if you return none it should skip to the next batch. @teddykoker

**Comment by ananthsub** [comment]
Should this be handled at the dataloader level instead? the dataloader should fetch enough examples to fill a full batch

**Comment by carmocca** [comment]
> Should this be handled at the dataloader level instead?

Ideally yes, but lightning should still allow returning None in case it is not possible.

**Comment by ananthsub** [comment]
This almost seems like wrapping the train step in a try/catch, and if there's an exception, return none and continue to the next batch. An argument against this is that it could obscure real issues in your training pipeline For instance, if there's a bug in your dataloader that causes it to always return empty batches? Lightning would blindly iterate through the whole dataset issue instead of failing fast. So it almost seems like this is about how to handle exceptional cases in the train step, and pushing this responsibility to the dataloader makes the contract for train_step much clearer
