### ISSUE TITLE
Add missing callback hook for optimizer dicts

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#3496]
Need a callback hook to consolidate the state of optimizer dicts before saving the final state_dict during model checkpointing.

**Comment by ananthsub** [comment]
this is blocked on #3545 
For more context, I want to use https://github.com/facebookresearch/fairscale/blob/master/fairscale/optim/oss.py with Lightning. I have a callback that defines `on_save_checkpoint` to call the optimizer's [`consolidate_state_dict` ](https://github.com/facebookresearch/fairscale/blob/master/fairscale/optim/oss.py#L168)

however, this requires the callback to run in all workers to do the comms before we can save the optimizer state
