### ISSUE TITLE
Difference in support for IterableDataset in Trainer.fit and Trainer.test

### ISSUE THREAD

**Issue by wongjoel** [PyTorchLightning/pytorch-lightning#3500]
#### What is your question?
When using WebDataset (which implements IterableDataset), Trainer.fit works without warnings, but Trainer.test will fail unless a nominal length is specified. Is this intended behaviour?

#### What have you tried?
When running Trainer.test without specifiying nominal length:
```
Traceback (most recent call last):
  File "sunset.py", line 222, in <module>
    main(parser.parse_args())
  File "sunset.py", line 126, in main
    main_test(args)
  File "sunset.py", line 210, in main_test
    trainer.test(model, test_dataloaders=test_loader, verbose=True)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1346, in test
    if test_dataloaders and datamodule:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 325, in __len__
    length = self._IterableDataset_len_called = len(self.dataset)
TypeError: 'NoneType' object cannot be interpreted as an integer
```

When running Trainer.test after specifying nominal length (and having multiple workers):
```
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:37: UserWarning: Your `IterableDataset` has `__len__` defined. In combination with multi-processing data loading (e.g. batch size > 1), this can lead to unintended side effects since the samples will be duplicated.
  warnings.warn(*args, **kwargs)
```

#### What's your environment?

 - OS: Ubuntu 18.04 (inside Docker Container)
 - Packaging: pip
 - Version: 0.9.0 on Python 3.6.9

**Comment by Borda** [comment]
I would say that the case is that for training you shall define nb steps per epoch so then you just sample from dataloader as much to finish your epoch, but for testing, you shall run all and if you don't know how many we cannot provide any progress has or other estimates... So maybe we can change it just to warning and drop the progress bar in such a case... What do you think?

**Comment by wongjoel** [comment]
I think that would be helpful - I would rather run without a progress bar than have a hard error preventing testing. (Sorry about the late reply, I ended up doing testing outside the framework, so I forgot about this).

**Comment by hey0** [comment]
Are there any news on this issue?

**Comment by antonkhmv** [comment]
> nb steps per epoch

Hi! How do you define nb steps per epoch? I'm using just a regular DataLoader with IterableDataset. I've tried searching for it, I couldn't find anything. I tried overriding __len__ for the data loader itself, not IterableDataset, since it seems that's how the number of batches in an epoch is calculated in code, but it still shows me a warning. It seems to work but I'm not sure if that's going to cause any side-effects too and I would like to specify nb steps per epoch directly. 

I guess you just need to set self.num_training_batches, but isn't there a better way to do this?
