### ISSUE TITLE
Tensorboard display nothing

### ISSUE THREAD

**Issue by NickYi1990** [PyTorchLightning/pytorch-lightning#3506]
### To Reproduce

I run the code below successfuly, and when i open my tensorboard, scalar display in board, but there's not value on the plot, vert confusing~

#### Code sample

```python
class DNNClassifer(pl.LightningModule):
    def __init__(self):
        super().__init__()

        # network
       
        # others
        self.criterion = MSELoss()
        self.logger_kun = init_logger("dnn", notebook=True)
        

    def forward(self, x):
        x = self.model.forward(x)
        return x
    
    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters())
    
    def training_step(self, batch, batch_idx):
        x, y, data_load_times = batch
        y_pred = self(x)
        
        loss = self.criterion(y_pred.squeeze(), y)
        self.logger.experiment.add_scalar('loss', loss, self.global_step)
        result = pl.TrainResult(minimize=loss)
        result.log("train_loss", loss, on_epoch=True)
        return result
        
    def validation_step(self, batch, batch_idx):
        x, y, data_load_times = batch
        y_pred = self(x)
        loss = self.criterion(y_pred.squeeze(), y)
        
        result = pl.EvalResult(checkpoint_on=loss)
        result.log("valid_loss", loss)
        return result
```
![image](https://user-images.githubusercontent.com/13381684/93210396-1baf9880-f792-11ea-9415-a1ea4ae4d48d.png)

### Expected behavior

Display value on tensorboard

### Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

* CUDA:
	- GPU:
	- available:         False
	- version:           10.2
* Packages:
	- numpy:             1.18.1
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0
	- pytorch-lightning: 0.9.0
	- tensorboard:       2.2.0
	- tqdm:              4.42.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.6
	- version:           #47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020

**Comment by awaelchli** [comment]
how many batches are in one epoch?
try a lower value for row_log_interval

**Comment by ozen** [comment]
Trainer's row_log_interval parameter is set to 50 by default. If the number of batches is less than row_log_interval, train metrics are never logged.

**Comment by awaelchli** [comment]
fyi, there is already an issue here #3466 which requests to base row_log_interval onto global step. It would solve the issue described here.

**Comment by NickYi1990** [comment]
> batches

em... I think give a warning when row_log_interval < 50 will be a better user experience
