### ISSUE TITLE
ImportError: cannot import name 'trim_batch'

### ISSUE THREAD

**Issue by gauravcanon** [PyTorchLightning/pytorch-lightning#3508]
🐛 Bug

### To Reproduce

1. Go to 'https://colab.research.google.com/drive/1em4d2iTwF1x4yZ10J5g5LtLcXBwgiyTA?usp=sharing'
2. Run 
3. Scroll down to 'LN 26'

### Environment

Please copy and paste the output from our
* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0+cu101
	- pytorch-lightning: 0.9.0
	- tensorboard:       2.2.0
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

**Comment by Borda** [comment]
@gauravcanon it is a private collab, pls rather share a minimal example here, or better make it is a test case...

**Comment by gauravcanon** [comment]
Updated link my bad

**Comment by gauravcanon** [comment]
I think this problem is not related to PyTorch-lighting. This is transformer update https://github.com/huggingface/transformers/pull/4510#issue-421650163
Sorry can close
