### ISSUE TITLE
RPC support

### ISSUE THREAD

**Issue by ruotianluo** [PyTorchLightning/pytorch-lightning#3513]
## 🚀 Feature
Pytorch 1.6 adds rpc. When will that be added to pytorch-lightning?

**Comment by Borda** [comment]
@ruotianluo mind add a link, some more motivation?

**Comment by ruotianluo** [comment]
https://pytorch.org/docs/stable/rpc.html. It seems to me is used to do model parallelism. I guess it's not a high-frequency use case, but just curious if you have looked at it and have any plan.
