### ISSUE TITLE
Allow auto-reduce of Result even if _epoch_end is implemented

### ISSUE THREAD

**Issue by ozen** [PyTorchLightning/pytorch-lightning#3515]
## 🚀 Feature

Currently, if Result is used and *_epoch_end is implemented, auto-reduce of result object is skipped.

The code for the validation loop is linked below. The same logic applies to the train and test loops.

https://github.com/PyTorchLightning/pytorch-lightning/blob/3281586ab4dc3811362a11259831b9d116fc0507/pytorch_lightning/trainer/evaluation_loop.py#L202-L210

So "[doing something special with the outputs](https://pytorch-lightning.readthedocs.io/en/latest/results.html#validation-test-loop-example)" together with auto-reduce is not possible. Reduce of all metrics must be done manually by the user in _epoch_end. I think a mechanism to use auto-reduce while adding something special on top of that would be beneficial.

**Comment by gerardsn** [comment]
similar to #3215

**Comment by edenlightning** [comment]
Closing this, keeping #3215.
