### ISSUE TITLE
in `child_modules` the forward pass example should use the encoder subnet

### ISSUE THREAD

**Issue by miccio-dk** [PyTorchLightning/pytorch-lightning#3524]
## 📚 Documentation

In my understanding, the forward pass of the example autoencoder should return the latent representation extracted by the encoder.
If my assumption is correct, then the `forward`, `training_step`, and `_shared_eval` functions should be corrected to reflect that. In this case, I'd be happy to create and submit a PR.
Otherwise, I am deeply confused and could use an explanation 😅

Thanks for the amazing library!

**Comment by rohitgr7** [comment]
I think yes, it should be the encoder, or maybe it can do both by passing a flag? It's an AutoEncoder, can run both ways.

**Comment by miccio-dk** [comment]
Good point! However, the article says that "we now want to train an Autoencoder to use as a feature extractor for MNIST images" ;)

**Comment by rohitgr7** [comment]
@miccio-dk This is an issue on lightning-bolts, can you open an issue there or maybe just make a pull request there itself. Closing this one.

**Comment by miccio-dk** [comment]
How is this related to Bolts? Please note that the issue I'm reporting is specific about the code/psudocode in https://pytorch-lightning.readthedocs.io/en/latest/child_modules.html and not about the AE model in lightning-bolts.

**Comment by rohitgr7** [comment]
I thought you were talking about the actual implementation in bolts, which is now fixed in one of the OR recently. Also looks like it's encoder now in docs, so I guess all ok now?

**Comment by miccio-dk** [comment]
all okay! :)
