### ISSUE TITLE
add support for 1.7 nightly

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#3531]
## 🚀 Feature
 
@ydcjeff created a CI with Conda to have tested with nighly 1.7 but in #3074 some tests were failing for 1.7 some let's move it as separate work

### Motivation

be continuously compatible even with new PT versions when they come

### ToDo

- [ ] uncomment CI and enable 1.7 testing
- [ ] fix test so 1.7 passes

**Comment by ydcjeff** [comment]
@Borda Let me take this one
