### ISSUE TITLE
Support automatic torchscript checkpointing.

### ISSUE THREAD

**Issue by kandluis** [PyTorchLightning/pytorch-lightning#3532]
## 🚀 Feature

Support exporting to TorchScript natively in the ModelCheckpoint callback. This would be a natural follow-up to #3080. 

### Motivation

It's common for users to rely on checkpoints (eg, usually last, but sometimes other intermediate models especially if using model ensembles or picking the best model the last k models). Frequently these models need to be served in a non-Python environment, meaning users have to convert their checkpoints to TorchScript.

With the implementation of #3080 it seems natural to add more support for TorchScript throughout the Lightning framework. In particular, we should allow users to export TorchScript models easily in checkpoints.

### Pitch

We can rely on the `to_torchscript` method in LightningModule's to access a TorchScript version of the model when checkpointing. We would then provide an parameter in the ModelCheckpoint callback 

```python
class ModelCheckpoint(Callback):
    r"""
    Save the model after every epoch if it improves.

    After training finishes, use :attr:`best_model_path` to retrieve the path to the
    best checkpoint file and :attr:`best_model_score` to retrieve its score.

    Args:
      ...
      save_torchscript: When set, each exported model includes a Torchscript
            version. Default: ``False``.
      ...
    """       
```

### Additional context

See #3080.

**Comment by Borda** [comment]
@kandluis do you have any estimate about time delay with exporting the model also to TorchScript?
just thinking that in such case you are probably fine just with exporting the best one or k-best, right?

**Comment by ananthsub** [comment]
This would happen whenever we call save_model. That means we'd honor the checkpoint callback's args for save_top_k for torchscript as well. There'd be a 1:1 mapping between checkpoints and models exported to torchscript saved. That also means we'll delete saved torchsrcipt models if they're no longer the top-K

**Comment by keunwoochoi** [comment]
+1 for this!

**Comment by rusmux** [comment]
@Borda I think it would be nice to implement this feature. This would spare developers from writing their own callbacks. Currently, to convert a checkpoint to another format, such as ONNX, one would need to create an exact instance of the model used for training, with the same initial arguments. And after that, load the checkpoint weights into it. With checkpoints in the TorchScript format, there is no need for that.

**Comment by pfeatherstone** [comment]
I would also love this feature. I'm currently using the following:
```
class JitCheckpoint(Checkpoint):
    def __init__(self):
        self.lastLoss = 100000

    def on_validation_end(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule"):
        if trainer.is_global_zero:
            assert "loss/val" in trainer.callback_metrics, "monitor not in callback_metrics"
            assert "acc/val" in trainer.callback_metrics, "monitor not in callback_metrics"
            loss        = trainer.callback_metrics["loss/val"].item()
            acc         = trainer.callback_metrics["acc/val"].item()
            if loss < self.lastLoss:
                print("Saving checkpoint last loss {} new loss {}".format(self.lastLoss, loss))
                self.lastLoss = loss
                ckpdir      = trainer.log_dir + "/checkpoints/"
                filePath    = ckpdir + "epoch={}_loss={:.4f}_acc={:.2f}".format(trainer.current_epoch, loss, acc)
                jitPath     = filePath + '.pt'
                onnxPath    = filePath + '.onnx'
                os.makedirs(ckpdir, exist_ok=True)

                input = torch.randn(2, 20*1024, 2)
                pl_module.to_torchscript(file_path=jitPath, method='trace', example_inputs=[input])
                pl_module.to_onnx(file_path=onnxPath, input_sample=input)
        trainer.strategy.barrier()
```

However my code hangs while all my GPUS are throttling at 100% doing nothing.
I tried adding ``` trainer.strategy.barrier()``` but that had no effect.
