### ISSUE TITLE
Re-initializing weights before each batch

### ISSUE THREAD

**Issue by mortonjt** [PyTorchLightning/pytorch-lightning#3539]
This question was initially posted on the pytorch forums [here](https://discuss.pytorch.org/t/initializing-weights-before-an-sgd-update/96079).

After further investigation, I'm noticing some interesting behavior within the `optimizer_step` function -- my parameters of interest get updated accordingly, then get _reverted_ back to the original state in the next iteration.

I'm narrowing down the suspects to issues with [inplace operations](https://pytorch.org/docs/stable/notes/autograd.html#in-place-operations-with-autograd) (hence the pytorch-forum post) and the mysterious `second_order_closure` function.

I've tried to track down where the `second_order_closure` function for LBFGS is defined without much luck.
Obtaining the appropriate references for this function would be greatly appreciated (in addition to any possible insights behind this interesting behavior).

**Comment by mortonjt** [comment]
Ok, I _think_ that this problem has been resolved by defining the `on_train_batch_start` callback.  But I'm still going to leave this open, because the `second_order_closure` function could benefit from more documentation.

**Comment by Borda** [comment]
I would keep this question in the forum...

**Comment by mortonjt** [comment]
@Borda that's fine ...
But are you open for a PR to update the documentation?  This was not trivial to debug ...

**Comment by Borda** [comment]
Sure doc update is very welcome :]

**Comment by SkafteNicki** [comment]
Closed by #3551.
