### ISSUE TITLE
GPUs requested but none are available

### ISSUE THREAD

**Issue by shanhaidexiamo** [PyTorchLightning/pytorch-lightning#3542]
my server has 8 GPUs, but when I use the **trainer** class and set gpus = -1, it gets the run error **GPUs requested but none are available**, use torch to check the gpus , get the number of gpu is 8, and cuda.is_available is true. Does any one can tell me what's wrong ?

**Comment by Borda** [comment]
Mind check if you have installed CUDA version of your PT as `torch.cuda.is_available()`

**Comment by awaelchli** [comment]
@shanhaidexiamo what does
`torch.cuda.device_count()`
return?
`cuda.is_available` alone does not tell us if the gpus are visible to torch.

**Comment by kyoungrok0517** [comment]
> > cuda.is_available is true
> 
> @shanhaidexiamo what does
> `torch.cuda.device_count()`
> return?
> `cuda.is_available` alone does not tell us if the gpus are visible to torch.

Sorry to interrupt but I'm experiencing the same issue. the device_count() returns `2` in my case, and I'm running on GCP instance with 2 `V100`. I had no problem with my own server so it's strange. `pytorch-lightning==0.9.0`

**Comment by Borda** [comment]
@kyoungrok0517 mind sharing this output, just to check that you have properly installed PT and drivers...
`python -c "import torch ; print(torch.cuda.device_count())"`

**Comment by kyoungrok0517** [comment]
That returns `2` as expected. What I found just now is that if I use `-1` for `gpus` argument the lightning doesn't work as I described. But if I give the exact number of gpus (`2` in my case) it works fine. I'm using `ddp` as the backend.

**Comment by Borda** [comment]
@kyoungrok0517  good catch, mind sending PR?

**Comment by awaelchli** [comment]
@williamFalcon is working on the parsing of gpus for DDP. The error is most likely because they are not correctly passed to or parsed in the child process.

**Comment by kyoungrok0517** [comment]
> @kyoungrok0517 good catch, mind sending PR?

Hmm... so am I late to PR? I never did this before so it'll be grateful if you guide me how it works. I make pull request even though I don't know how to fix it?? Please tell me. I'd like to help.

**Comment by fishbotics** [comment]
Hi all,

I am now having the same issue. I'm running my job on a server with 8 GPUs. When I run `python -c "import torch ; print(torch.cuda.device_count())"` I get `8`, but when I run with `gpus=1` and `auto_select_gpus=True`, I get an error saying that there are no GPUs available.

@Borda , @awaelchli : do you know if this was ever fixed?

Thanks!

**Comment by awaelchli** [comment]
@fishbotics  What else is running on the gpus?

The original issue reported here was fixed by https://github.com/PyTorchLightning/pytorch-lightning/pull/4209, I believe.
adding gpus=1 and auto_select_gpus=True works for me with the pl_examples
