### ISSUE TITLE
on_save_checkpoint callbacks runs in rank zero only

### ISSUE THREAD

**Issue by ananthsub** [PyTorchLightning/pytorch-lightning#3545]
## 🐛 Bug

If any callback implements `on_save_checkpoint`, then that function runs only in the rank zero worker. I think this is suboptimal as you might want to do some communication across workers before saving state.

The lineage of calls here is:

- [model checkpoint callback's on_validation_end is decorated with rank_zero_only](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/callbacks/model_checkpoint.py#L316)
- [this calls the checkpoint callback's _save_model](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/callbacks/model_checkpoint.py#L385)
- [which calls it's save_function](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/callbacks/model_checkpoint.py#L198-L200)
- [the save_function is trainer.save_checkpoint](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/connectors/callback_connector.py#L66-L67)
- [save_checkpoint in checkpoint_connector calls dump_checkpoint](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L335-L348)
- [dump_checkpoint calls trainer.on_save_checkpoint()](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L249)
- [trainer on_save_checkpoint() calls any callback implementing on_save_checkpoint ](https://github.com/PyTorchLightning/pytorch-lightning/blob/a9c0ed920a5a6d0c2bb92f2c61046aeb5070db4f/pytorch_lightning/trainer/callback_hook.py#L194-L202)

I think this could be avoided with more judicious usage of `rank_zero_only`. the main benefit of `rank_zero_only` in the model checkpoint callback to avoid redundant file I/O. For saving the checkpoint, that is taken care of by [this check.](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L338)

Other file I/O in the model checkpoint callback could be similarly guarded, and we should remove the decorator from `on_validation_end`

**Comment by ananthsub** [comment]
with this thread i wanted to raise awareness of a limitation in the callback API here and a proposed workaround. if the code complexity isn't palatable, then we should document the limitations of the API.
making the implementation in `on_validation_epoch_end` have some more checks for `trainer.is_global_zero` rather than relying on the catch all decorator isn't so bad.  we're still able to apply the `rank_zero_only` decorator to smaller functions like `_del_model`

removing the decorator from `on_validation_epoch_end` also means we should remove the decorator from `on_pretrain_routine_start` because there is state set in `on_pretrain_routine_start` that is later read in `on_validation_epoch_end`. if `on_pretrain_routine_start` runs on rank zero only, then there are uninitialized fields when `on_validation_epoch_end` runs in non-zero ranks.

it's also unclear what we need to do for the model checkpoint's own definitions of `on_save_checkpoint`.

do all callbacks implementing `on_save_checkpoint` now need to check for `trainer.is_global_zero`? is that a dealbreaker?

**Comment by edenlightning** [comment]
@williamFalcon PTAL

**Comment by ananthsub** [comment]
#3688 finished this
