### ISSUE TITLE
Confusing Documentation about TrainResult and EvalResult

### ISSUE THREAD

**Issue by magic282** [PyTorchLightning/pytorch-lightning#3548]
## 📚 Documentation
Hi,

I am trying to migrate from pl 0.7.6 to latest 0.9.0. The TrainResult and EvalResult seems to be new a new wrapper.

I am confused by the documentation of them.

The `log` function of TrainResult says:
```
on_step: if True logs the output of validation_step or test_step
```
How is TrainResult during training related to the validation or test steps? What does this `on_step` really mean?

---
Another issue is about the `sync_dist: if True, reduces the metric across GPUs/TPUs`. Is this mandatory or not if I use ddp or any other backends for multi-gpu training?

Thanks!

**Comment by Borda** [comment]
btw, The dict is still supported...
the `on_step` is for logging to TB or what ever you use
`sync_dist` depend if you are running DDP or not..
