### ISSUE TITLE
LightningModule and Pytorch Models should really be decoupled.

### ISSUE THREAD

**Issue by ayberkydn** [PyTorchLightning/pytorch-lightning#3577]
Not a feature per se, but a design suggestion for the LightningModule to discuss.

I think a lot of people already using PL the way so that they build the model in other classes. For example filling a Generator and Discriminator class and only initialize them within the LightningModule init method. The motivation is to have a modular design and more plug and play nature.

I am actually wondering if a specific feature obligates this coupling (like DDP support or some logging) or it was one of initial simple paths that is now difficult to refactor since the project got larger. By the way, I was thinking similar about usage of datasets and DataModule update just really solved my (hypothetical) problem about it. I appreciate the update and wonder; can a similar thing done with "nn.Module"s?

**Comment by ananthsub** [comment]
The design now allows for someone to write their nn.Module inside the lightning module, or for users to instantiate a model through some other class inside the lightning module. this already is modular design and plug and play to me. what would your proposal be to decouple the lightning module from nn.Module?

**Comment by ayberkydn** [comment]
> The design now allows for someone to write their nn.Module inside the lightning module

I think this is the exact opposite of being modular. Of course you can write any piece of code into the __init__ method of LightningModule. But this makes them coupled in a way that your piece of code would be **in** the module, right?

To me, the right way to do this (in the most general case) to pass a dictionary of models to init or use some 'Module'  just like DataModule.

**Comment by ananthsub** [comment]
> I think this is the exact opposite of being modular
You're not forced to do this. You're free to instantiate your models however you want to. the `Module` you're describing sounds exactly like `nn.Module`

**Comment by ayberkydn** [comment]
Unless you need to test your saved models somewhere else. I remember people having difficulties with loading model weights and testing with models not initialized in LightningModule.

A LightningModule is far from being a tensor transformation module. It includes a few, but you need to be able plug & play without changing the code inside the init method. You should check 'Open Closed Principle'

**Comment by s-rog** [comment]
> I remember people having difficulties with loading model weights and testing with models not initialized in LightningModule.

I've fixed the loading issues, though the changes have not made it into release yet

**Comment by williamFalcon** [comment]
Great suggestion! 

a few steps ahead of you ;)

Please check out two of our demos that explicitly don't do this.
In addition, our new docs reflect that:

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/basic_examples/autoencoder.py#L34-L42

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/basic_examples/image_classifier.py#L42-L46

https://pytorch-lightning.readthedocs.io/en/latest/new-project.html#step-1-define-lightningmodule

**Comment by ayberkydn** [comment]
So I see that we can initiate the lightning model with any kind of arguments, including pytorch nn modules. With this setting, is there any point inheriting torch.nn.Module and overriding the inherited .forward() method? If it is only for inference logic, shouldn't it be renamed as something like .inference() ? Also, I am wondering if this setting works when I need to train the model in one .py file and test with arbitrary datasets in another (test.py) file rather than trainer.fit(); trainer.test() in same code file. 

The reason I am asking this is, I think it's a better approach to decouple training and test phases of a machine learning pipeline to make experiments with arbitrary datasets, which is generally needed if you are not working de facto datasets like ImageNet or MNIST. But I always find doing this in lightning very confusing, and a little buggy, occasionly.

**Comment by aligholami** [comment]
I gotta agree with @ayberkydn 
The forward() function in pl.LightningModule is quite confusing.
