### ISSUE TITLE
Split ModelCheckpoint filepath into dirpath and filename

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#3583]
## 🚀 Feature

Previous discussions:

https://github.com/PyTorchLightning/pytorch-lightning/pull/3163#issuecomment-683539565
https://github.com/PyTorchLightning/pytorch-lightning/pull/3163#issuecomment-695854769
https://github.com/PyTorchLightning/pytorch-lightning/issues/3001

## Idea:

Keep backwards compatibility by having `filepath` (old parameter) and `dirpath`, `filename` (new parameters)
    - if `filepath` is set: old logic, show deprecated warning.
    - if `dirpath` and `filename` are set: new logic.
    - if `filepath`, `dirpath`, and `filename` are set: raise `MisconfigurationException`

---

cc @Borda @awaelchli @ananthsub @rohitgr7 @ydcjeff

**Comment by rohitgr7** [comment]
I have been suggesting this for a long time. 😅

**Comment by carmocca** [comment]
I know, @Borda just [asked me](https://github.com/PyTorchLightning/pytorch-lightning/pull/3163#issuecomment-695955673) to create a new issue to discuss.

**Comment by Borda** [comment]
> I have been suggesting this for a long time. 😅

but it was not properly resolved, right? do you remember the issue/PR?

**Comment by awaelchli** [comment]
I like it, I vote for this :) We have plenty of tests for the filepath arg (I think thanks to @carmocca?), so the guarantee for back compatibility is there.

**Comment by awaelchli** [comment]
> but it was not properly resolved, right? do you remember the issue/PR?

There was this PR #2584 but was slightly different

**Comment by rohitgr7** [comment]
Should we have these parameters now in `ModelCheckpoint` since 1.x is released?

**Comment by awaelchli** [comment]
Yes, I think it would be useful.
