### ISSUE TITLE
LightningDataModule seems to do some dataloader operations on CPU, which was not the case with LightningModule loader methods

### ISSUE THREAD

**Issue by navrudh** [PyTorchLightning/pytorch-lightning#3607]
## 🐛 Bug

While using LightningDataModule as `lit_model(datamodule=datamodule)` the models waits for some time using 1 CPU core before beginging training, and periodically stops training (every 50 train steps) GPU util goes 0% and 1 CPU core is in use. This behaviour continues till training finishes.

### To Reproduce

1. Create a lightning model which takes a datamodule as input. `__init__` contains`this.datamodule=datamodule`
2. In the LightningDataModule I'm using PyTorch's UCF101 dataset

#### Code sample
```python3
class UCF101DataModule(LightningDataModule):
    def setup(self, stage=None):
        if stage == "fit" or stage is None:
            self.train_dataset = datasets.UCF101(
                UCF101_ROOT_PATH,
                UCF101_ANNO_PATH,
                frames_per_clip=5,
                step_between_clips=30,
                num_workers=UCF101_WORKERS,
                train=True,
                fold=self.fold,
            )

    def train_dataloader(self):
        print("Train Dataloader Called")
        return DataLoader(
            self.train_dataset,
            batch_size=self.batch_size,
            num_workers=DATALOADER_WORKERS,
            collate_fn=custom_collate,
            shuffle=True,
        )

class LitModel(LightningModule):
    def __init__(datamodule):
        self.datamodule = datamodule
```

### Expected behavior

Training loop should start immediately

### Environment

* CUDA:
	- GPU:
		- GeForce RTX 2080 Ti
	- available:         True
	- version:           10.2
* Packages:
	- numpy:             1.18.1
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0
	- pytorch-lightning: 0.9.0
	- tqdm:              4.46.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.8.3
	- version:          113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020

**Comment by edenlightning** [comment]
@nateraw

**Comment by awaelchli** [comment]
> (every 50 train steps)

@navrudh That sounds suspiciouly like the `row_log_interval`. Can you confirm you are not doing any expensive custom logging?

**Comment by navrudh** [comment]
Tried `Trainer(row_log_interval=1, ...)` and am still observing the same behaviour

**Comment by awaelchli** [comment]
How many workers are you using? If the training stops and gpu usage goes to 0, it means your dataloading can't keep up. Increase the number of workers. Make sure the cpu is not the bottleneck.

**Comment by navrudh** [comment]
I'm using number of workers = 12.

Also, if I instead move the code to the `val_loader`, `train_loader` methods of `LightningModule` training starts straightaway without this delay.

**Comment by awaelchli** [comment]
@navrudh I don't fully understand how to reproduce this. Can you provide your training script and LightningModule?
https://colab.research.google.com/drive/1JPqcv8hexwdByACFN5S8UyPi5G4Ielxq?usp=sharing

**Comment by navrudh** [comment]
I've updated the code. I took a model from the internet since I can't share the model that I'm currently using.

**Comment by awaelchli** [comment]
> I've updated the code.

thanks. where can I find it?

**Comment by navrudh** [comment]
Sorry, here's the link https://colab.research.google.com/drive/1e69KUDeZbNA-eEE76EK0MaiVhOGJsxmY

But I'm not getting the same issue on colab.
