### ISSUE TITLE
Support all_gather usecase for sync_ddp 

### ISSUE THREAD

**Issue by oyj0594** [PyTorchLightning/pytorch-lightning#3624]
## 🚀 Feature

all_gather function support for EvalResult sync_dist option.

### Motivation
Current sync_dist implementation is for manipulating output tensors from each validation loop of several GPUs. ('mean', 'sum')
There are use cases which need all_gather function rather than all_reduce function.

**Comment by oyj0594** [comment]
@SkafteNicki

**Comment by SkafteNicki** [comment]
@oyj0594 do you have time for submitting a PR yourself?

**Comment by oyj0594** [comment]
@SkafteNicki Okay let me work on this. If there is problem with my schedule, I will contact you.
