### ISSUE TITLE
automatically copy state-dict when using ddp

### ISSUE THREAD

**Issue by AljoSt** [PyTorchLightning/pytorch-lightning#3628]
## 🚀 Feature
Copy model state-dict from rank 0 process to other processes when using ddp

### Motivation
This would mean that the user does not need to worry about initializing models with the same weights

### Alternatives
Alternatively lightning could at least check if the weights are the same and if not warn the user / thrown an exception

Not sure if this is possible and how easy it can be accomplished, but I could imagine that this could be a source for errors.

**Comment by AljoSt** [comment]
hm I suppose just setting the seed would be enough? Or can there be situations where it's not the case?

**Comment by awaelchli** [comment]
Yes exactly, in ddp we always need to set the seed. 
Although what @AljoSt suggests may make sense on first thought, I do not believe that simply copying the model state dict is enough. Why only that? The assumption here is that the only non deterministic state is the model, but that is simply not true in general. We may have random state in dataset, imported libraries, and other external influences.

**Comment by AljoSt** [comment]
yes, good point. I'll close this then!
