### ISSUE TITLE
wandbLogger log Image does not seem to work. 

### ISSUE THREAD

**Issue by joshclancy** [PyTorchLightning/pytorch-lightning#3635]
## 🐛 Bug

in normal pytorch I would log an Image in wandb like this:
`wandb.log({"Reconstruction":[wandb.Image(recon, caption="recon")]})`

in lightning documentation it says:
      self.logger.experiment.some_wandb_function()

I have used this to successfully log other metrics, but if I do this with Images:    
`self.logger.experiment.log({"val_input_image":[self.logger.experiment.Image(val_batch[0][0].cpu(), caption="val_input_image")]})`

I get this error:

<ipython-input-29-de79f9ca10a6> in validation_step(self, val_batch, batch_idx)
     44           print("val_batch", val_batch[0][0].shape)
     45           # wandb.log({"pred_image":[wandb.Image(mask, caption="pred")], "epoch":outputDict["epochNum"]})
---> 46           self.logger.experiment.log({"val_input_image":[self.logger.experiment.Image(val_batch[0][0].cpu(), caption="val_input_image")]})
     47         return {'val_loss': val_loss, "val_acc" : acc, "log" : val_logs}
     48 

AttributeError: 'Run' object has no attribute 'Image'

Any ideas how to get around this??

cc @borda @rohitgr7 @awaelchli @morganmcg1 @AyushExel @borisdayma @scottire

**Comment by awaelchli** [comment]
Do this:
```python
self.logger.experiment.log({"val_input_image":[wandb.Image(val_batch[0][0].cpu(), caption="val_input_image")]})
```
With a bit of luck, I have not introduced a typo.

**Comment by phisad** [comment]
Just wasted an hour on this using `pytorch-lightning            1.5.8` :(

This worked:
```
self.logger.experiment.log({"image": [wandb.Image(image)]})
```

while this did not worked, but is in the documentation:
```
self.log({"image": [wandb.Image(image)]})
```

https://pytorch-lightning.readthedocs.io/en/latest/common/loggers.html#weights-and-biases

**Comment by awaelchli** [comment]
Yes, sorry the docs would need to be updated. Recently we also introduced `self.logger.log_image`: https://pytorch-lightning.readthedocs.io/en/latest/extensions/generated/pytorch_lightning.loggers.WandbLogger.html#pytorch_lightning.loggers.WandbLogger.log_image, this should make your life easier too.

**Comment by morganmcg1** [comment]
Hey all, I'm at Weights & Biases, we'll get this fixed :)

**Comment by lqrhy3** [comment]
> Yes, sorry the docs would need to be updated. Recently we also introduced `self.logger.log_image`: https://pytorch-lightning.readthedocs.io/en/latest/extensions/generated/pytorch_lightning.loggers.WandbLogger.html#pytorch_lightning.loggers.WandbLogger.log_image, this should make your life easier too.

Hi! Why do I have `404 page not found` error visiting your link?

**Comment by awaelchli** [comment]
Hey @lqrhy3 
Because I posted this link more than 1 year ago and it wasn't a "permanent" link. I hope you understand. 
This is the link to the latest docs: https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.loggers.wandb.html
There is a section for logging media, including images, with example code.
