### ISSUE TITLE
Loading written predictions

### ISSUE THREAD

**Issue by baradl** [PyTorchLightning/pytorch-lightning#3638]
One can write predictions (or metrics, etc.) to disk with a result object using the method `write` which pickles them in `on_test_end`. I'm interested in loading them afterwards with following lines
```
with open(preds_path, "rb") as pred_file:
    preds = pickle.load(pred_file)
```
and I'm receiving the following error

`UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.`

I can't find the line where predictions are pickled and where such a function might be specified. Any help would be appreciated!

**Comment by awaelchli** [comment]
I think @nateraw worked on this predictions feature and may know the answer :)

**Comment by nateraw** [comment]
The predictions are written with `torch.save` so you should use `torch.load('your_predictions.pt')`. Let me know if this helps!
