### ISSUE TITLE
gan.py on 'dp' mode will get a bug!

### ISSUE THREAD

**Issue by GuHongyang** [PyTorchLightning/pytorch-lightning#364]
<img width="1280" alt="屏幕快照 2019-10-13 下午9 06 51" src="https://user-images.githubusercontent.com/20881636/66716277-4b298880-edfe-11e9-8005-08103206615b.png">

**Comment by williamFalcon** [comment]
yeah, good catch. it's because it isn't tracking your updated image state between batches. Need to figure out how to support this, but in the meantime use DDP because DP is not really meant to be used anymore unless you really need it
