### ISSUE TITLE
How to use a custom Callback with Trainer.from_argparse_args

### ISSUE THREAD

**Issue by KirillShmilovich** [PyTorchLightning/pytorch-lightning#3648]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?

I'd like specify a custom Callback while passing argparse paramaters using `Trainer.from_argparse_args`

#### Code

For example, I've tried something like this with no success:

`trainer = Trainer(callbacks=[CustomCallback()]).from_argparse_args(args)`

which doesn't seem to properly apply the callback.

What is the proper way to define a custom callback within a trainer when using `from_argparse_args`?

#### What have you tried?

However, this DOES work as expected when calling from checkpoint:

``` 
trainer = Trainer(
        resume_from_checkpoint=ckpt_fname,
        callbacks=[CustomCallback()])
```

#### What's your environment?

 - OS: Linux
 - Packaging: conda
 - Version: 0.9.0

**Comment by carmocca** [comment]
You can do the following:

```python
import pytorch_lightning as pl
import argparse

args = argparse.Namespace(max_epochs=3)  # fake args
trainer = pl.Trainer.from_argparse_args(args)
trainer.callbacks.append(CustomCallback())
```

**Comment by awaelchli** [comment]
I do this
```python 
trainer = Trainer.from_argparse_args(args, callbacks=[CustomCallback()])
```
from_argparse_args accepts kwargs that can override the args in the namespace.

**Comment by awaelchli** [comment]
Pretty confident this or @carmocca's comment will answer it for you, so closing this already. Let us now if it worked!
