### ISSUE TITLE
Add on_after_backwards callback option

### ISSUE THREAD

**Issue by rbracco** [PyTorchLightning/pytorch-lightning#3657]
## 🚀 Feature
Add an on_after_backward callback option.

### Motivation
Currently there are no callbacks for after the backwards step so non-essential code like logging gradients clutters the LightningModule. 

### Pitch

Expand the callback options to include a hook for `on_after_backward()` to execute callbacks immediately after the backwards pass

### Alternatives

Sticking my non-essential gradient logging code in my LightningModule

**Comment by awaelchli** [comment]
useful!

**Comment by FelixLorenz** [comment]
I need nearly the same feature: `on_before_backward` as an abstract method in the `Callback` base class would be awesome!

**Comment by rohitgr7** [comment]
maybe we should add all the optimizer-related hooks to callbacks too if it makes sense?? What do you think @awaelchli?

**Comment by awaelchli** [comment]
@rohitgr7 which hooks do you have in mind?

**Comment by rohitgr7** [comment]
@awaelchli all of them? `on_after_backward`, `on_before_backward`, `on_before_zero_grad`.

**Comment by awaelchli** [comment]
I think that would be nice to have.

**Comment by rohitgr7** [comment]
okay, will add them in few hours.
