### ISSUE TITLE
Allow .write and .write_dict with TrainResult.

### ISSUE THREAD

**Issue by rohitgr7** [PyTorchLightning/pytorch-lightning#3670]
## 🚀 Feature
Allow `.write` and `.write_dict` with `TrainResult`.

### Motivation
- Can be used to check the results generated by GAN (generator) over the course of an epoch to visualize and check the learning process of the generator.

### Pitch
Similar to that with `EvalResult`.

Let me know what you guys think. :)

**Comment by kyoungrok0517** [comment]
It'll be even better if batched writing is allowed. It seems like the actual writing happens after all the inference is finished, which can blow GPU memory when the output is huge (e.g. embeddings)

**Comment by rohitgr7** [comment]
is it good to add this feature now?
