### ISSUE TITLE
remove value field from Result objects 'meta' key

### ISSUE THREAD

**Issue by gerardsn** [PyTorchLightning/pytorch-lightning#3677]
## 🚀 Feature

remove value field from Result objects 'meta' key

### Motivation

The value field in the Result obj's  meta data is
- a duplicate of the raw data in the Result obj, 
- not being used,
- not updated in the gathered results presented to the user in [training,validation,test]_epoch_end.

Especially this last point can lead to confusion.

### Pitch

The value field should no longer be written to the meta data in the Result obj.

I can submit a PR if this change is approved.

**Comment by teddykoker** [comment]
Hey @gerardsn thanks for the issue! We are currently making some changes with regards to result, so I'll check back in a couple days to see if this is still relevant :)
