### ISSUE TITLE
Fix exception chaining

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning#3679]
I recently went over [PyTorch](https://github.com/pytorch/pytorch/pull/43836) and [Detectron2](https://github.com/facebookresearch/detectron2/pull/1945), suggesting a fix in the way that Python 3's exception chaining is used.

As described in detail in [this article](https://blog.ram.rachum.com/post/621791438475296768/improving-python-exception-chaining-with), exception chaining ([PEP 3134](https://www.python.org/dev/peps/pep-3134/)) can be used to make exceptions more user-friendly, and in that case, the syntax `raise new_exception from old_exception` needs to be used.

When `raise .. from ..` is used, there will be a line saying `The above exception was the direct cause of the following exception` between tracebacks. However, when implicitly chaining exceptions (meaning when `raise .. from ..` is not used), the message will be `During handling of the above exception, another exception occurred` which can confuse users.

Specifically, the following should be used in order to chain exceptions:
```python
try:
    something_which_raises_OldError
except OldError as e:
    raise NewError("A more user-friendly exception message.") from e 
```
instead of:
```python
try:
    something_which_raises_OldError
except OldError:
    raise NewError("A more user-friendly exception message.")
```

One example which needs to be fixed is:
https://github.com/PyTorchLightning/pytorch-lightning/blob/3d76f604bdb97d66dd1248540ea088fb18c06a03/pytorch_lightning/utilities/parsing.py#L159-L162

If this suggestion sounds good and reasonable, I'd be happy to create a PR! Let me know your thoughts on this!

**Comment by awaelchli** [comment]
oh! I just learned something new about Python exceptions. Awesome!
So if I understand correctly, this change will make the exceptions more user friendly, pointing to where it originated from. 
Do we keep the bugfix label? It sounds more like an enhancement

Related: #2266

**Comment by akihironitta** [comment]
Thanks @edenlightning for relabelling the issue! I didn't know Hacktoberfest at all!

@awaelchli Thank you for your quick response!
Yes, you're right. Since this issue is not critical, can I work on this in October as a PR for Hacktoberfest?

**Comment by rohitgr7** [comment]
@akihironitta assigned you to this issue. Yeah, you can do this in October.

**Comment by akihironitta** [comment]
@awaelchli @rohitgr7 I just made #3750 ready for review! Can you have a look at the changes?
