### ISSUE TITLE
How to set default EarlyStopping patience?

### ISSUE THREAD

**Issue by chrismaliszewski** [PyTorchLightning/pytorch-lightning#3696]
Is it possible to set the default EarlyStopping patience without creating a custom early stopping callback? 

Instead of writing:
```
trainer = pl.Trainer(early_stop_callback=EarlyStopping(patience=XXX))
```

I'd like to overwrite the default patience directly and then use EvalResult(early_stop_on=...).

**Comment by rohitgr7** [comment]
No. Any problem with using a custom callback??

**Comment by chrismaliszewski** [comment]
No, just wondering. I just would like to keep the early stopping things in one place, EvalResult, instead of jumping elsewhere to change settings. 

Thanks. Closing.
