### ISSUE TITLE
UserWarning: "When using EvalResult(early_stop_on=X) or ..." triggers always. 

### ISSUE THREAD

**Issue by vegovs** [PyTorchLightning/pytorch-lightning#3710]
## 🐛 Bug
The UserWarning: 
                    "When using EvalResult(early_stop_on=X) or TrainResult(early_stop_on=X) the
                    'monitor' key of EarlyStopping has no effect.
                    Remove EarlyStopping(monitor='val_early_stop_on) to fix')"

triggers without the `EarlyStopping(monitor='val_early_stop_on)`.
### To Reproduce

Run as normal with EarlyStopping callback, and no `early_stopping_on` on either TrainResult or EvalResult: 

Example:
```python
Epoch 0:  50%|█████     | 1/2 [00:00<00:00,  1.53it/s, loss=0.750, v_num=20]
Validating: 0it [00:00, ?it/s]
Epoch 0: 100%|██████████| 2/2 [00:02<00:00,  1.39s/it, loss=0.750, v_num=20]/home/vegovs/venvs/seg/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py:37: UserWarning: 
                    When using EvalResult(early_stop_on=X) or TrainResult(early_stop_on=X) the
                    'monitor' key of EarlyStopping has no effect.
                    Remove EarlyStopping(monitor='val_early_stop_on) to fix')
                
  warnings.warn(*args, **kwargs)
Epoch 0: 100%|██████████| 2/2 [00:03<00:00,  1.58s/it, loss=0.750, v_num=20]
Epoch 0: 100%|██████████| 2/2 [00:03<00:00,  1.66s/it, loss=0.750, v_num=20]
Saving latest checkpoint..
INFO:lightning:Saving latest checkpoint..

Process finished with exit code 0
```

Callback:
#### Code sample
```python
    early_stopping = EarlyStopping(
        patience=5 if not os.getenv("EARLY_STOP") else int(os.getenv("EARLY_STOP")),
        verbose=True,
    )
```
EvalResult:
```python
        result = pl.EvalResult(loss, checkpoint_on=loss)
        result.log("val_loss", loss, sync_dist=True)
        if batch_idx == 0:
            rand_idx = randint(0, self.hparams.batch_size - 1)
```

TrainResult:
```python
        loss = self.loss_funciton(masks_pred, masks)
        result = pl.TrainResult(minimize=loss)
        result.log("train_loss", loss, sync_dist=True)
```
### Expected behavior

Expect no user warning when no monitor value is given to EarlyStopping callback.. 

### Environment

* CUDA:
        - GPU:
                - GeForce RTX 2070 SUPER
        - available:         True
        - version:           10.2
* Packages:
        - numpy:             1.19.2
        - pyTorch_debug:     False
        - pyTorch_version:   1.6.0
        - pytorch-lightning: 0.9.0
        - tqdm:              4.49.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.6.9
        - version:           #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020

**Comment by edenlightning** [comment]
Hey! We created a new simpler API for early stopping, simply passing a callback. Please have a look at [latest docs](https://pytorch-lightning.readthedocs.io/en/latest/early_stopping.html) and try our master to see if this fixes the problem!

**Comment by williamFalcon** [comment]
yes, please use the new API!
