### ISSUE TITLE
Change the tensorboard run-names to 

### ISSUE THREAD

**Issue by vegovs** [PyTorchLightning/pytorch-lightning#3711]
### What is your question?
What is the easiest and most pythonic way to change the Tensorboard runs names from "version_{n}" to something like "{hostname}_{time}_{lr}_{batch_size}" etc? Do i have to manually create a tensorboard logger and send it to the trainer? What happens with the checkpoint folder and stuff? 

#### What's your environment?

CUDA:
- GPU:
- GeForce RTX 2070 SUPER
- available: True
- version: 10.2
Packages:
- numpy: 1.19.2
- pyTorch_debug: False
- pyTorch_version: 1.6.0
- pytorch-lightning: 0.9.0
- tqdm: 4.49.0
System:
- OS: Linux
- architecture:
- 64bit
- ELF
- processor: x86_64
- python: 3.6.9
- version: #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020

**Comment by rohitgr7** [comment]
Is this what you need??
https://github.com/PyTorchLightning/pytorch-lightning/blob/3dcf7130c554f4511c756ccbb4e3a417103d595d/pytorch_lightning/loggers/tensorboard.py#L110-L119

**Comment by vegovs** [comment]
Gees, thanks! :D
