### ISSUE TITLE
Incorrect example in Learning Rate Finder documentation

### ISSUE THREAD

**Issue by mtszkw** [PyTorchLightning/pytorch-lightning#3717]
## 📚 Documentation

In [lr_finder](https://pytorch-lightning.readthedocs.io/en/latest/lr_finder.html) docs there's an example code showing how to use Learning Rate finder:

```
model = MyModelClass(hparams)
trainer = Trainer()

# Run learning rate finder
lr_finder = trainer.tuner.lr_find(model)

# Results can be found in
lr_finder.results

...
```

This example raises an error when I run it:

> AttributeError: 'Trainer' object has no attribute 'tuner'

however this line seems to work:

```
lr_finder = trainer.lr_find(model, dataset)
```

Here is my Colab notebook with both working and non-working code visible:  
https://colab.research.google.com/drive/1RvcsMRhQqJusFAkquIiHbmh4Fpm7vhSf?usp=sharing

That's the case both in Colab and my local machine, so I assume there's a mistake in docs. Is that right?

**Comment by ananyahjha93** [comment]
I think this is a bug in the lightning release on pip right now, 

did a 'pip install git+https://github.com/PytorchLightning/pytorch-lightning.git@master --upgrade' and it works, so I guess the docs don't need to be updated since the latest release will fix it.
