### ISSUE TITLE
PyTorch/XLA GA support in pytorch-lightning

### ISSUE THREAD

**Issue by minimaxir** [PyTorchLightning/pytorch-lightning#3725]
## 🚀 Feature
The PyTorch team just released [native TPU support](https://medium.com/pytorch/pytorch-xla-is-now-generally-available-on-google-cloud-tpus-f9267f437832) as GA for TPUs.

From the demos, it _might_ be plug-and-play with the current pytorch-lightning implementation of xla, but more work may need to be done (since native support should result in a massive speedup), and documentation at minimum may need to be adjusted. (e.g. no more setup scripts in Colab!)

**Comment by minimaxir** [comment]
Even though it does use XLA, it may need a QA pass since it may not be guaranteed to work.

Additionally, a few of the TPU docs have the setup scripts in Colab; if those are no longer necessary as a part of a QA pass, they can be simplified.

**Comment by Borda** [comment]
we have t tested for Colab also Kaggle now...
PL is running on all TOU as well as TPU, the point of Pl is to be agnostic to a used backend, so all examples we have can run on TPU 🐰
