### ISSUE TITLE
Explicitly add num_classes parameter to confusion_matrix

### ISSUE THREAD

**Issue by LucaButera** [PyTorchLightning/pytorch-lightning#3743]
## 🚀 Feature

It would be nice to be able to specify explicitly the number of classes expected for the confusion matrix metric. A similar behavior is allowed in the accuracy metric for instance.

### Motivation

It may happen that you want to incrementally compute the confusion matrix over different steps of testing and, in the end, aggregate those matrices into the final confusion matrix.

Sometimes, particularly with small batches, it happens that a random batch doesn't have samples for each class. With inferred number of classes, this leads to a confusion matrix with a different dimension than expected, thus making it a pain to match shapes afterwards.

Explicit number of classes declaration solves the problem easily for cases in which you know how many classes to expect in advance.

### Pitch

Change signature of

```pytorch_lightning.metrics.ConfusionMatrix(normalize: bool = False, reduce_group: Any = None, reduce_op: Any = None)```

to 

```pytorch_lightning.metrics.ConfusionMatrix(normalize: bool = False, num_classes: Optional[int] = None, reduce_group: Any = None, reduce_op: Any = None)```

make a matching change for

```pytorch_lightning.metrics.functional.confusion_matrix(pred: torch.Tensor, target: torch.Tensor, normalize: bool = False)```

to become

```pytorch_lightning.metrics.functional.confusion_matrix(pred: torch.Tensor, target: torch.Tensor, normalize: bool = False, num_classes: Optional[int] = None)```

inside the latter method use the given ```num_classes```, instead of ```None```, as input for ```get_num_classes```

### Alternatives

I don't have any that come to my mind.

### Additional context

No additional context needed

**Comment by SkafteNicki** [comment]
Please update to master as it is already implemented there:
https://github.com/PyTorchLightning/pytorch-lightning/blob/d3ae26fcfc322b8d64f67b90722931e363769844/pytorch_lightning/metrics/classification.py#L90-L112
Closing this issue.
