### ISSUE TITLE
Tensorboard, what does epoch chart show?

### ISSUE THREAD

**Issue by chrismaliszewski** [PyTorchLightning/pytorch-lightning#3759]
Fast question. 

Image from Tensorboard:
![image](https://user-images.githubusercontent.com/7532602/94738555-10807d80-03cc-11eb-85e1-2a7ce3ef824b.png)

I don't add this log. It's done automatically by lightning. What does this chart present?

**Comment by ydcjeff** [comment]
If you are on Lightning 0.9.0, the x-axis represents `global_step` and y-axis is showing `epoch`

**Comment by chrismaliszewski** [comment]
Thank you, @ydcjeff. Is there any information in the doc? Can't find it. Since it's a default chart, it'd be good to have the info somewhere.

**Comment by ydcjeff** [comment]
Hi @chrismaliszewski , I guess there is no info about plotted charts in the docs.
Would you like to send a PR with the necessary information you have in mind?
