### ISSUE TITLE
auto_scale_batch_size doesnt use 'binsearch'

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#3780]
I tried to following and it's still using power:

```
#####################
# 1. Init Model
##################### 

model = LitAutoEncoder()

#####################
# 2. Init Trainer
##################### 
trainer = pl.Trainer(auto_scale_batch_size='binsearch')

#####################
# 3. Tune
#####################
trainer.fit(model)
```

Did we remove support? or is that a bug?

**Comment by edenlightning** [comment]
@Borda any idea?

**Comment by SkafteNicki** [comment]
@edenlightning it seems that this was changed during one of the refactors.
No matter what the `auto_scale_batch_size` argument is set to, the tuning will not run as part of `fit` anymore.
Instead user should call `trainer.tune()`.

**Comment by Borda** [comment]
@SkafteNicki mind fix it?
@edenlightning where is this example so we shall edit it also there and make it as a tested example...

**Comment by SkafteNicki** [comment]
@Borda i am not sure if there is anything to fix, as I think the intention with the refactors was that the user should call `trainer.tune()`.
cc: @williamFalcon

**Comment by Borda** [comment]
I see, then just update the docs... :]

**Comment by SkafteNicki** [comment]
It actually is described correctly in the [docs](https://pytorch-lightning.readthedocs.io/en/latest/training_tricks.html#auto-scaling-of-batch-size)
@edenlightning is it an old example you have the code from?

**Comment by edenlightning** [comment]
sorry, wrong screenshot.

![Screenshot - 2020-10-04T121904.655.png](https://images.zenhubusercontent.com/5ed62005fdb9223ab9f9c818/9a1ec5fe-71bc-475a-9adf-64e879b8908c)

its just using power instead of binsearch

**Comment by SkafteNicki** [comment]
I don't see anything wrong here.

Seems like you are running on mnist. Mnist has 60000 samples, and it seems like you can fit it all in gpu memory. The batch size finder never go higher than the len of the train dataloader.

In this case there will be no difference between modes (power and binsearch), as the binary search will first kick in after the power scaling fails the first time.

**Comment by edenlightning** [comment]
ok so i guess this is just a matter of documentation. Can you help clarify this behaviour in the docs?

**Comment by SkafteNicki** [comment]
Yes, will send i PR :]
