### ISSUE TITLE
Trainer.tune() doesn't work

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#3781]
![Screenshot - 2020-10-01T213349 970](https://user-images.githubusercontent.com/66261195/94879292-cf20ba00-042d-11eb-8e66-4b40031c6051.png)

Should we just remove it from the docs?

**Comment by Borda** [comment]
it is there, mind share your PL version as it was refactored I gues in 0.9.1rc3
https://github.com/PyTorchLightning/pytorch-lightning/blob/ac2b0f0f066967b5896a73591ce7aa25dfb75306/pytorch_lightning/trainer/trainer.py#L364

**Comment by edenlightning** [comment]
Thanks!
