### ISSUE TITLE
Incorrect batch size tracking in training and validation steps

### ISSUE THREAD

**Issue by itsikad** [PyTorchLightning/pytorch-lightning#3840]
## 🐛 Bug
Batch sizes are tracked both in training and evaluation loops to reduce the Train/Eval results on epoch end.
In both cases `len(batch)` is used to find the current batch_size which is incorrect, for example MNIST loader will return 2 since `batch = batch_data, batch_target`.

**Training loop:**
https://github.com/PyTorchLightning/pytorch-lightning/blob/b40de5464a953ff5866a255f4670d318bd8fd65a/pytorch_lightning/trainer/training_loop.py#L1026

**Evaluation loop:**
https://github.com/PyTorchLightning/pytorch-lightning/blob/b40de5464a953ff5866a255f4670d318bd8fd65a/pytorch_lightning/trainer/evaluation_loop.py#L339

### Expected behavior

Match the actual batch_size

**Comment by rohitgr7** [comment]
duplicate https://github.com/PyTorchLightning/pytorch-lightning/issues/3668??

**Comment by itsikad** [comment]
Thanks @rohitgr7! I absolutely missed this one when I searched. Closing the issue.
