### ISSUE TITLE
Consider making the docs default to the latest stable version instead of the latest

### ISSUE THREAD

**Issue by jdepoix** [PyTorchLightning/pytorch-lightning#3867]
## 📚 Documentation

Hi,

I just started using PyTorch Lightning and got a bit confused by the fact that pytorch-lightning.readthedocs.io defaults to the latest version (including release candidates), while running `pip install pytorch-lightning` (without specifying a version) will (correctly) default to the latest stable version.

This is quite confusing for a new user trying to go through a [tutorial like this one](https://pytorch-lightning.readthedocs.io/en/latest/new-project.html) as it instructs him to just run `pip install pytorch-lightning` and follow along. However, this will (currently) download v0.9.0, while the tutorial uses features which only work in newer RC versions, like using `self.log(...)`.

I guess this could easily be solved by defaulting pytorch-lightning.readthedocs.io to the latest stable version, or changing all pip install instructions to `pip install pytorch-lightning==x.x.x`.

**Comment by ndrplz** [comment]
+1, I also stumbled upon this

**Comment by williamFalcon** [comment]
which docs links did you click?
they should all be the stable version

**Comment by williamFalcon** [comment]
This one is stable:

![image](https://user-images.githubusercontent.com/3640001/95096924-e0521b00-06fa-11eb-9454-9c19def8d8b1.png)

This one is stable:
![image](https://user-images.githubusercontent.com/3640001/95096952-e9db8300-06fa-11eb-89a8-07ad9d47b163.png)

What link are you using???

**Comment by jdepoix** [comment]
@williamFalcon Oh, yeah. Those actually forward to the docs I would have expected to end up on.
I got to the link mention by googling for PyTorch Lightning docs. By just opening `https://pytorch-lightning.readthedocs.io` it will forward you to `.../latest` instead of `.../stable`, so that's probably why google brought me there. I guess `.../stable` would be the better default forward.

**Comment by williamFalcon** [comment]
fixed! didn't know about that :)
