### ISSUE TITLE
Understanding Processed_Paths

### ISSUE THREAD

**Issue by zachschmitz** [PyTorchLightning/pytorch-lightning#3880]
I'm a beginner with Pytorch Geometric. I'm trying to understand what **self.processed_paths** is in initializing a Pytorch Geometric dataset, like an InMemoryDataset. 

The Pytorch Geometric guide outlines a dataset like: 
<img width="584" alt="Screen Shot 2020-10-05 at 12 20 20 PM" src="https://user-images.githubusercontent.com/63166138/95111920-d255c780-0705-11eb-8749-ff0a01c710ed.png">

**Torch.load()** takes in a string from **self.processed_paths[0]**. However, we never define **processed_paths**. Where does **processed_paths** come from? 

I've looked through the main Pytorch Geometric guides, example datasets, and documentation for saving and loading with torch. My idea is that **self.processed_paths** is somehow defined from **processsed_file_names(self)**; for instance, if we look at the coma dataset, they initialize the dataset as the following: 
![image](https://user-images.githubusercontent.com/63166138/95112127-2bbdf680-0706-11eb-87ef-6137f4851f7f.png)

We see that coma defines a path from **self.processed_paths** depending on whether they're training or not. This makes me think that **self.processed_paths** is somehow implicitly defined from **processed_file_names(self)**. Do you know how this is possible? 

Thank you for your help.

**Comment by pbmstrk** [comment]
Your question is probably better suited as an issue in the [pytorch_geometric](https://github.com/rusty1s/pytorch_geometric) repository - they will probably be able to help you better over there. 

I can perhaps help in answering your question, though. The object `MyOwnDataset` inherits from `InMemoryDataset` which in turn inherits from `Dataset`. The implementation of `Dataset` defines the property `processed_paths`, which is implemented as follows:

```
@property
def processed_paths(self):
    r"""The filepaths to find in the :obj:`self.processed_dir`
    folder in order to skip the processing."""
    files = to_list(self.processed_file_names)
    return [osp.join(self.processed_dir, f) for f in files]
```

Thus, you are right there is a connection between `self.processed_paths` and `processed_file_names` but this is explicit. 

Looking at the implementations of [InMemoryDataset](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/data/in_memory_dataset.py) and [Dataset](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/data/dataset.py) may clear this up.
