### ISSUE TITLE
Lightning Module's to_disk should use fsspec to write reusults

### ISSUE THREAD

**Issue by ananthsub** [PyTorchLightning/pytorch-lightning#3890]
## 🚀 Feature
use fsspec here to support more storage backends besides local disk:
https://github.com/PyTorchLightning/pytorch-lightning/blob/cea5f1f53876399dfaa0d37accdc527af7ca39af/pytorch_lightning/trainer/supporters.py#L138-L165

cc @nateraw

**Comment by surajit-techie** [comment]
I would like to take a look into this, and submit a PR.
