### ISSUE TITLE
Accessing logger's data at the end of a training

### ISSUE THREAD

**Issue by chrismaliszewski** [PyTorchLightning/pytorch-lightning#3893]
I'd know if it is possible to access all logs that were created during the training process at its end? I'd like to do something with the data. How do I access logger's data? 

Is it even possible with the code that exists or should I create a new data structure in my class to store it along with the logger's actions? 

I'm using 0.9.1rc4.

**Comment by SkafteNicki** [comment]
In addition to whatever logger you are currently using, you can use lightnings `CSVLogger` (https://pytorch-lightning.readthedocs.io/en/stable/loggers.html#csvlogger). This logger writes everything to .csv file which should be easy to process after end training.

**Comment by chrismaliszewski** [comment]
Great. Good to know! Haven't thought about this. I'll have a look. I'm closing this short issue. 

Thank you, @SkafteNicki!
