### ISSUE TITLE
copy badges to release package

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#3905]
## 🚀 Feature

Parse the Readme and replace generated badges by downloaded ones

0. process in setup.py
1. parse all badges from online CI and save them as png (svg is problematic, does not work for all plaforms)
2 replace badges in Readme with the downloaded ones

### Motivation

pipy page does not work well with generated badges and also projecting the master state to a given release does not make sense.. also no need to keep link to CI :]

**Comment by Abelarm** [comment]
HI,

I would like to take care of this, if it's ok with you.
Any more information I can have to solve this problem.

Thanks

**Comment by Abelarm** [comment]
HI @Borda,

I am working on it, I was able to download the png file for some of the badge and save it, but sadly not all the badges have the .png version buy only the svg. How do you think I should proceed?
I just save the svg files and load it?

Other questions: 
- I was planning to save the badges in `docs/source/_images/badges` is it fine for you?

**Comment by Borda** [comment]
> HI @Borda,
> 
> I am working on it, I was able to download the png file for some of the badge and save it, but sadly not all the badges have the .png version buy only the svg. How do you think I should proceed?
> I just save the svg files and load it?

I think that my version now with locally saved badges is fine now, not sure, maybe SVG will work too and the issue was just the online version... later we can try something else :]

> * I was planning to save the badges in `docs/source/_images/badges` is it fine for you?

yes, sounds good to me :] just add also this location to MANIFEST.in
