### ISSUE TITLE
UserWarning for testing_epoch_end in 0.9.1rc4

### ISSUE THREAD

**Issue by chrismaliszewski** [PyTorchLightning/pytorch-lightning#3922]
Just informing about the user warning I was displayed:

```YYY\anaconda3\envs\pt_cpu\lib\site-packages\pytorch_lightning\utilities\distributed.py:37: UserWarning: The testing_epoch_end should not return anything as of 9.1.to log, use self.log(...) or self.write(...) directly in the LightningModule warnings.warn(*args, **kwargs)```

although I don't have the ```testing_epoch_end``` method in my class. **UPDATE:** The warning does not appear when I implement it. 

I'm using 0.9.1rc4.

If it's being resolved elsewhere and I missed that, feel free to close the issue.

**Comment by Borda** [comment]
@chrismaliszewski it seems as there is a missing check if the method is overwritten, mind sends a PR?

**Comment by chrismaliszewski** [comment]
It's fine now. Closing.
