### ISSUE TITLE
Plotting multiple metrics in a single graph

### ISSUE THREAD

**Issue by abhinavg97** [PyTorchLightning/pytorch-lightning#3932]
## 🚀 Feature

Can we have multiple metrics plotted on the same graph in Tensorboard logging done by lightning?
That is plotting the dictionary values returned in log_dict in the same graph.

**Comment by SkafteNicki** [comment]
You can already do this in lightning, by calling the tensorboard logger yourself, using the `add_scalars` method.
If you insert this into your code (artificial example)
```
        self.logger.experiment.add_scalars('main_tag', 
                                           {'metric1': loss, 
                                            'metric2': loss+1}, 
                                           global_step=self.global_step)
```
it will produce this in tensorboard
![Screenshot from 2020-10-07 12-03-25](https://user-images.githubusercontent.com/24896311/95317761-e29cac80-0895-11eb-8245-975730d06787.png)
where the metrics are shown in the same plot.

**Comment by abhinavg97** [comment]
Thank you so much!
