### ISSUE TITLE
define PL dev debugger for all tests

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#3934]
## 🚀 Feature

define `os.environ['PL_DEV_DEBUG'] = '1'`` at init of each test or each test file so we do not thing twice how to get more information from testing, so it will be by default...

### Motivation

have all dev info always for all tests

**Comment by biswaroop1547** [comment]
I'd like to do this, we just have to add ```os.environ['PL_DEV_DEBUG'] = '1' ``` at the top of every test file or their init file only, right?

**Comment by carmocca** [comment]
What about doing it with a pytest fixture with `autouse=True`? https://docs.pytest.org/en/stable/fixture.html#autouse-fixtures-xunit-setup-on-steroids

**Comment by awaelchli** [comment]
why does it need to be added to each test?
does pytest "unset" env variables on each test?

**Comment by williamFalcon** [comment]
i'm sorry, this was not something we were actually looking to do :(

**Comment by Borda** [comment]
> does pytest "unset" env variables on each test?

that is a good point, I think it does not... so it is there since the first usage...
