### ISSUE TITLE
limit builds for Docs

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#3942]
## 🚀 Feature

limit build for PR with are strictly related to docs, so skip:
- Conda & Dockers & Full testing [GH actions]
- TPU testing [CircleCI]
- GPU testing [Drone CI]

### Motivation

lower the resources requirements

### Additional context

Btw, if you need skip GPU testing use magic work in commit or PR name [CI SKIP]
https://docs.drone.io/pipeline/skipping/

**Comment by ydcjeff** [comment]
@Borda [CI SKIP] in commit doesn't work in Drone, has to be in PR name
Maybe we should mention in the contributing guide too

**Comment by edenlightning** [comment]
@Borda anything left here todo?

**Comment by Borda** [comment]
as all required to run all test for merge and also update all PRs to master, this does not make sense anymore...
