### ISSUE TITLE
`fit` hangs with a custom port on 2+ GPUs

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#3957]
## 🐛 Bug

The following seems to indefinitely hang:

### To Reproduce

file: hangs.py
```python
import os, random
from tests.base.boring_model import BoringModel
from pytorch_lightning import Trainer

def test(tmpdir):
    port = str(random.randint(1200, 1900))
    os.environ['MASTER_PORT'] = port

    trainer = Trainer(
        default_root_dir=tmpdir,
        progress_bar_refresh_rate=0,
        logger=False,
        max_epochs=2,
        limit_train_batches=10,
        limit_val_batches=10,
        gpus=2,
        distributed_backend='ddp'
    )
    trainer.fit(BoringModel())
```

`pytest hangs.py`

### Expected behavior

Test runs

### Environment

Current master

**Comment by williamFalcon** [comment]
you can't test ddp like this :)  
This is a limitation of pytest

ddp needs to be called from a separate file...

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/tests/backends/test_ddp.py#L40-L57

**Comment by carmocca** [comment]
But why does it only happen when the port is modified?

**Comment by carmocca** [comment]
Actually, it also gets stuck without pytest:

```python
def test(tmpdir):
    # same code
    ...

# call manually
test('/tmp/kk')
```

`python hangs.py`

**Comment by awaelchli** [comment]
yep, this is expected given your code sample :) 

ddp calls your script N times. 
in each subprocess, you will get a different master port, because you select it randomly in your code.

Set your master port **before** you launch the script. I think this should also work:
`MASTER_PORT=123 python hangs.py`
