### ISSUE TITLE
Update the package on conda-forge

### ISSUE THREAD

**Issue by tmcclintock** [PyTorchLightning/pytorch-lightning#3960]
## 🚀 Feature

Update the version of PL on [conda-forge](https://anaconda.org/conda-forge/pytorch-lightning) to the recent tagged release. Conda-forge has 0.9.0

### Motivation

Keep the package up to date on important channels. Conda-forge is the default channel so it qualifies.

### Pitch

When making a new environment and conda install-ing PL, you want the most recently tagged version.

### Alternatives

Not keep conda-forge up to date and requiring users to clone this repo to get the most recently tagged version.

**Comment by Borda** [comment]
on its way :] https://github.com/conda-forge/pytorch-lightning-feedstock/pull/11

**Comment by tmcclintock** [comment]
This is done.

**Comment by tmcclintock** [comment]
Thanks!
