### ISSUE TITLE
Does self.log do ddp sync automatically?

### ISSUE THREAD

**Issue by xiadingZ** [PyTorchLightning/pytorch-lightning#3972]
Does `self.log` do ddp sync automatically? mean or sum?
Or I have to do ddp sync manually in `training_step_end` then log it, instead of directly log it in `training_step`?

--------update---------
I see ddp sync options in code, but it doesn't show in docs. I still have a question, what's the difference of `reduce_fx ` and `sync_dist_op `?

**Comment by ananyahjha93** [comment]
The LightningModule.log within LightningModule docs provides docs for this: https://pytorch-lightning.readthedocs.io/en/latest/lightning_module.html

I'll send in a PR to avoid this confusion, ```reduce_fx``` is end of epoch reduction and ```sync_dist_op``` is op for sync across GPUs.
