### ISSUE TITLE
The use of save_hyperparameters() is currently confusing (due to name and docs)

### ISSUE THREAD

**Issue by NumesSanguis** [PyTorchLightning/pytorch-lightning#3981]
## 📚 Documentation & function name change
The following documentation page is relevant here: https://pytorch-lightning.readthedocs.io/en/stable/weights_loading.html

The use of `self.save_hyperparameters()` is currently confusing for the following 3 reasons:

1. The role of this function is unclear. In the documentation this function is not mentioned once under the header "Checkpoint saving". Also, all arguments given to a LightningModule will be saved when calling `trainer.save_checkpoint()`, whether `save_hyperparameters()` has been used or not.
  a. **Edit**: For example, are there any benefits of calling `self.save_hyperparameters('arg1', 'arg3')` over just assigning directly to self.hparams? E.g. like: `self.hparams['arg1'] = arg1`
2. The name `save` would indicate it is used to store the hyper parameters somewhere (e.g. disk). You would also expect that this function is not necessary when loading a .ckpt file (I don't want to change the self.hparams, and therefore do not want to save anything).
3. The documentation only mention this function under:
  > But if you don’t want to use the values saved in the checkpoint, pass in your own here

```python
class LitModel(LightningModule):

    def __init__(self, in_dim, out_dim):
        super().__init__()
        self.save_hyperparameters()
        self.l1 = nn.Linear(self.hparams.in_dim, self.hparams.out_dim)
```

So my understanding of `save_hyperparameters()` was only to be used when you load a checkpoint AND want to overwrite the hyper parameters found in that checkpoint.

This resulted me being stuck in a "hparams not restored when loading ckpt" issue (https://forums.pytorchlightning.ai/t/hparams-not-restored-when-using-load-from-checkpoint-default-argument-values-are-the-problem/237) for longer than I would like to admit.

## Possible solutions
1. Clarify why would like to use `save_hyperparameters()` over just not calling the function. Why was this function created? E.g. indicate that this moves arguments to `self.hparams`, which are used for automatic logging by e.g. Allegro TRAINS.
2. Change the name to something like `init_hyperparameters()` or `arguments_to_hyperparameters()`.
3. Mention in documentation under Loading that this function is necessary to restore .ckpt hyperparameters.

## End word
What are your thoughts about this?

## Tagging
@Borda

**Comment by yukw777** [comment]
I think you still have some confusion on what `save_hyperparameters()` is for. For example,

> So my understanding of `save_hyperparameters()` was only to be used when you load a checkpoint AND want to overwrite the hyper parameters found in that checkpoint.

This is not exactly correct. `save_hyperparameters()` is used to specify which init arguments should be saved in the checkpoint file to be used to instantiate the model from the checkpoint later. If you don't call `save_hyperparameters()` in `__init__()`, no arguments (or hyperparameters) will be saved in the checkpoint, hence the error you got. If you want to overwrite the hyperparameters found in that checkpoint, you'd actually do this (this is the example in the doc):
```python
class LitModel(LightningModule):

    def __init__(self, in_dim, out_dim):
        super().__init__()
        self.save_hyperparameters()
        self.l1 = nn.Linear(self.hparams.in_dim, self.hparams.out_dim)

...
# if you train and save the model like this it will use these values when loading
# the weights. But you can overwrite this
LitModel(in_dim=32, out_dim=10)

# uses in_dim=32, out_dim=10
model = LitModel.load_from_checkpoint(PATH)

# uses in_dim=128, out_dim=10
model = LitModel.load_from_checkpoint(PATH, in_dim=128, out_dim=10)
```

Detailed explanations on hyperparameter handling (and `save_hyperparameters()` by extension) can be found here: https://pytorch-lightning.readthedocs.io/en/stable/hyperparameters.html#lightningmodule-hyperparameters

Please let us know if you still have questions!

**Comment by NumesSanguis** [comment]
> > So my understanding of `save_hyperparameters()` **was** only to be used when you load a checkpoint AND want to overwrite the hyper parameters found in that checkpoint.
> 
> This is not exactly correct. `save_hyperparameters()` is used to specify which init arguments should be saved in the checkpoint file to be used to instantiate the model from the checkpoint later.

Yes, that was my point. From the ["Saving and loading weights" doc page](https://pytorch-lightning.readthedocs.io/en/stable/weights_loading.html) that was my initial understanding. Only when getting loading errors I realized this understanding was wrong. Therefore, renaming the function to `init_hyperparameters()` would better match what you described.

> If you don't call `save_hyperparameters()` in `__init__()`, no arguments (or hyperparameters) will be saved in the checkpoint, hence the error you got.

The [documentation](https://pytorch-lightning.readthedocs.io/en/stable/weights_loading.html#automatic-saving) disagrees with you on this:

> The Lightning checkpoint also saves the arguments passed into the LightningModule init under the module_arguments key in the checkpoint.

```python
class MyLightningModule(LightningModule):

   def __init__(self, learning_rate, *args, **kwargs):
        super().__init__()

# all init args were saved to the checkpoint
checkpoint = torch.load(CKPT_PATH)
print(checkpoint['module_arguments'])
# {'learning_rate': the_value}
```

> Detailed explanations on hyperparameter handling (and `save_hyperparameters()` by extension) can be found here: https://pytorch-lightning.readthedocs.io/en/stable/hyperparameters.html#lightningmodule-hyperparameters

Thank you! I missed that page. Would be great if this page could be linked from the "Saving and loading weights" page.

So both [**given arguments**](https://pytorch-lightning.readthedocs.io/en/stable/weights_loading.html#automatic-saving)

> The Lightning checkpoint also saves the arguments passed into the LightningModule init under the module_arguments key in the checkpoint.

AND [everything in `self.hparams`](https://pytorch-lightning.readthedocs.io/en/stable/hyperparameters.html#lightningmodule-hyperparameters)

> 3. Assign to self.hparams. Anything assigned to self.hparams will also be saved automatically

will be stored in the checkpoint file, whether you have called `save_parameters()` or not. So to me `save_parameters()` is only about transferring all/specific arguments to `self.hparams`.

**Comment by awaelchli** [comment]
The 3rd point there is old, the approach with self.hparams =... still works but is not recommended. 
In #4417 I added the missing self.hyperparameters in the docs and we will either remove point 3 from docs or put a warning that it is deprecated.

**Comment by NumesSanguis** [comment]
@awaelchli I have raised some questions and concerns about not supposing to use `self.hparams` to assign values, here: https://github.com/PyTorchLightning/pytorch-lightning/pull/4417#discussion_r514754403

**Comment by awaelchli** [comment]
@NumesSanguis is there still confusion on your side of what `save_hyperparameters` is or what it does?

> Also, all arguments given to a LightningModule will be saved when calling trainer.save_checkpoint(), whether save_hyperparameters() has been used or not.

This is not true. You are probably using the old setter for hparams. That's why.

> The name save would indicate it is used to store the hyper parameters somewhere (e.g. disk). You would also expect that this function is not necessary when loading a .ckpt file (I don't want to change the self.hparams, and therefore do not want to save anything).

It is not necessary when loading the checkpoint file. But most of the time it will be there because loading and saving models in pytorch requires the code to be mostly identical otherwise stuff breaks, we can't do anything about that. 
`LightningModule.load_from_checkpoint` allows to override hyperprameters if necessary. 

We can try to improve docs and mention it in places where loading and saving is explained
