### ISSUE TITLE
AttributeError when using multiple dataloaders

### ISSUE THREAD

**Issue by florisdf** [PyTorchLightning/pytorch-lightning#3994]
## 🐛 Bug

When training with multiple datasets and using `self.log()` for logging, I get following `AttributeError`:

`AttributeError: 'dict' object has no attribute 'get_epoch_log_metrics'`

### Proposed fix

After some code digging, I suppose [this line](https://github.com/PyTorchLightning/pytorch-lightning/blob/53e056612c1d27deb45916351222522efabfaf35/pytorch_lightning/trainer/connectors/logger_connector.py#L208) is the culprit. I'm guessing it should be replaced with:

```python
result = Result()
result.update({
    f'{k}/dataloader_idx_{dataloader_idx}': v
    for k, v in metrics.items()
})
```

or something similar.

**Comment by imh** [comment]
I did some digging, and I think I found the culprit. In `LoggerConnector._log_on_evaluation_epoch_end_metrics`, [there's a step](https://github.com/PyTorchLightning/pytorch-lightning/blob/0474464c454a000e4cacfe188c86a0b8317288d5/pytorch_lightning/trainer/connectors/logger_connector.py#L180) that [renames results keys by data loader index](https://github.com/PyTorchLightning/pytorch-lightning/blob/0474464c454a000e4cacfe188c86a0b8317288d5/pytorch_lightning/trainer/connectors/logger_connector.py#L204) if there are multiple data loaders. It takes a `Result`, but if there are multiple data loaders, it returns a plain old `dict`. When this dict comes back, it tries to call `.get_epoch_log_metrics()` and `.get_epoch_pbar_metrics()`, which are `Results ` methods.

**Comment by imh** [comment]
I took a crack at it in that PR, but I'm still extremely new to the codebase, so I have very little confidence in it.

**Comment by Vozf** [comment]
This is a major bug and a strange behavior overall. Why pl is even renaming my metrics when I explicitly set them when I'm logging
