### ISSUE TITLE
Broken link in Documentation

### ISSUE THREAD

**Issue by pbmstrk** [PyTorchLightning/pytorch-lightning#4011]
## 📚 Documentation

The Module Index link at the bottom of the main page of the Lightning documentation is broken. This seems to be because the `make html` command does not create a `py-modindex.html` file (not sure why).

If the Module Index page is not required a solution is to remove `* :ref: modindex` from the index.rst file.

Additionally, below the Module Index link there is a link to a search page, that is currently empty. Seeing as searching is possible in the sidebar, not sure if the page is required, so could remove `* :ref: search` as well.

Not super familiar with Sphinx but think this wouldn't break anything.

**Comment by Borda** [comment]
@pbmstrk not sure what you mean, mind share some screenshot?
or better send a PR with fix... ? 🐰

**Comment by pbmstrk** [comment]
It's a very minor issue, but seeing as the link is broken thought it was worthwhile raising.

Below is the screenshot (can be found by scrolling to the bottom of https://pytorch-lightning.readthedocs.io/en/latest/),

<img width="698" alt="Bildschirmfoto 2020-10-09 um 13 31 45" src="https://user-images.githubusercontent.com/41694868/95583318-d8b0b000-0a33-11eb-852b-6c0e00327a69.png">

The Module Index link is broken and the Search Page link leads to an empty page. I believe Sphinx automatically adds links to Index, Module Index, and Search Page to index.rst when first creating the docs (see [here](https://github.com/PyTorchLightning/pytorch-lightning/blame/master/docs/source/index.rst#L132-L134)). I can send a PR to remove them if you think the links are not necessary.

**Comment by Borda** [comment]
ok, @pbmstrk mind send a PR with remooving this term from index?
