### ISSUE TITLE
Patent implications and coverage

### ISSUE THREAD

**Issue by mejran** [PyTorchLightning/pytorch-lightning#4028]
In a now removed by the mods hacker news comment @williamFalcon claimed that the Lightning patent prevents the use of the Lightning  API by other projects (even those under an Apache license). As this seems to go against the patent indemnification clause of the Apache license I'd like a clarification on the Pytorch Lightning stance regarding projects that use or extend the code or APIs.

**Comment by williamFalcon** [comment]
Nope!

Lightning can be used in any project you want.

The patent only covers literally copying the lightning API and the general dress/look and feel (ie: you can't make a clone of lightning...) but you can build something like Nemo or Hugginface, etc...
