### ISSUE TITLE
clean-up metric testing

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#4059]
## 🚀 Feature

apply comments in #4043 which were ignored and make the tests easier too understand

### Motivation

now the testing so black-boxing, and confusing with the same function SK names in different files

**Comment by awaelchli** [comment]
and also very important, we need to speed it up. The ddp initialization and forking processes causes tests to run several minutes.

**Comment by Borda** [comment]
cleaning in #4152
