### ISSUE TITLE
Why does the example not use the prepare data hook?

### ISSUE THREAD

**Issue by aribornstein** [PyTorchLightning/pytorch-lightning#4075]
I would expect the out of the box example to use the proper [prepare_data hook](https://pytorch-lightning.readthedocs.io/en/latest/hooks.html) to enable multi node training. Is there a reason that the mnist data is downloaded in main rather than in the style of the [sample from the blog post](https://gist.github.com/williamFalcon/2168a349492a9480f41f9da39ea755cd#file-pl-py-L85)?

![image](https://user-images.githubusercontent.com/3045407/95678932-5ad9d980-0bd8-11eb-9631-164c58384cb8.png)

If relevant I'd be happy to contribute a patch.

https://github.com/PyTorchLightning/pytorch-lightning/blob/86c70622fbae611dd45ccb104830e7e28639fe44/pl_examples/basic_examples/mnist.py#L86

**Comment by ydcjeff** [comment]
The argument `download` is set to `True` in `prepare_data` hook, so downloading the data is done at that method.

But that argument is set to `False` in dataloaders method, so dataset will not be downloading again.

**Comment by aribornstein** [comment]
I understand but the basic examples aren't using the prepare_data hook.

**Comment by awaelchli** [comment]
@aribornstein makes sense

**Comment by williamFalcon** [comment]
we've moved away from defining data in the lightning modules (it's still supported) but for these kinds of things we prefer to use a DataModule (literally the same hooks but in a different class).

We'll update the tutorial
