### ISSUE TITLE
Weird warning popping out. Unable to understand

### ISSUE THREAD

**Issue by saahiluppal** [PyTorchLightning/pytorch-lightning#4124]
I'm getting this warning only after first epoch
```bash
/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:200: UserWarning: Please also save or load the state of the optimizer when saving or loading the scheduler.
warnings.warn(SAVE_STATE_WARNING, UserWarning)
```
I'm unable to understand this.

**Comment by ndrplz** [comment]
Could you provide a bit of context about your setting / a minimal snippet to reproduce your issue?

Also, that warning come from the pytorch package (not from lightning). If you google it, there are a bunch of discussions related to that

**Comment by ZhaofengWu** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/46813
