### ISSUE TITLE
Speedup imports

### ISSUE THREAD

**Issue by jankrepl** [PyTorchLightning/pytorch-lightning#4126]
## 🚀 Feature
Increase the speed of importing from `pytorch_lightning`
### Motivation
```
time python -c "from pytorch_lightning import LightningModule"

real    0m3.193s
user    0m1.920s
sys     0m0.557s
```
vs
```
time python -c "from torch.nn import Module"

real    0m1.022s
user    0m0.603s
sys     0m0.185s
```

Note that this difference becomes quite visible when running the following sequence of steps quite often:
* load a model (subclass of `pl.LighteningModule`)
* forward pass 
* close Python interpreter 

### Pitch
The import speed might be very important for one-off inference usecases.

### Alternatives
It is worth mentioning, that I tried to pinpoint a specific module where `LighteningModule` is implemented and import it from there. However, it did not really change much.
```
time python -c "from pytorch_lightning.core.lightning import LightningModule"

real    0m3.398s
user    0m2.071s
sys     0m0.597s
```

I guess I can just get around this issue by clever subclassing and never importing from PL at inference time. 

### Additional context
Please let me know what your opinions are and whether there is an existing solution that could help me. Thank you in advance

**Comment by Borda** [comment]
@jankrepl do you have some concrete solution/proposal in mind? 🐰

**Comment by jankrepl** [comment]
> @jankrepl do you have some concrete solution/proposal in mind? 🐰

Actually yes, I did some digging (see https://stackoverflow.com/a/51300944/6632199):
```
python -X importtime -c "from pytorch_lightning import LightningModule" 2> imports.log
tuna imports.log
```
The problem is that the following module `pytorch_lightning/loggers/mlflow.py` gets imported as well.
And half of the time is spent on importing `mlflow`. Uninstalling `mlflow` actually led to an expected speedup. Anyway, I am using `mlflow` as a logger at training time so I guess for my purposes I will just try to mock it out at inference time.

I was slightly overwhelmed by the source code and I am not sure if I will have time to submit a good PR.

**Comment by williamFalcon** [comment]
ok... so it sounds like the slow import is mlflow which you are using. but since we don't need it to actually load, it looks like this is not really a PTL issue no?
