### ISSUE TITLE
The conda installation still imposes a fixed version of tensorboard

### ISSUE THREAD

**Issue by MrinalJain17** [PyTorchLightning/pytorch-lightning#4129]
## 🐛 Bug

Not sure if this is done for a reason, but the conda installation of pytorch-lightning still requires `tensorboard==2.2.0`, evident from the recipe:

https://github.com/conda-forge/pytorch-lightning-feedstock/blob/master/recipe/meta.yaml#L27

Given that this issue has been fixed in v1.0.0, updating the conda feedstock would probably be a good idea.

And it's not like I need the latest version of tensorboard. But just to have consistency across different installation methods.

**Comment by Borda** [comment]
@MrinalJain17 good catch, just send fix in https://github.com/conda-forge/pytorch-lightning-feedstock/pull/13
