### ISSUE TITLE
Clean CSVLogger saved csv

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#4143]
## 🚀 Feature

<img width="1018" alt="Screenshot 2020-10-14 at 12 07 52" src="https://user-images.githubusercontent.com/12861981/95983345-5d774180-0e19-11eb-90f1-e80e9df2b43e.png">

Proposition:

- Re-order by order, step, metrics (Easier to follow)
- Aggregate valid_loss_step/epoch-{} to valid_loss_epoch (When num_epochs large, it will generate a very sparse .csv)
- There is a flickering line 53 for validation where step goes to 0 (seems to happen at all epoch)

### Motivation

Simplify logs parsing / reading for people using CSVLogger.

**Comment by rohitgr7** [comment]
> Aggregate valid_loss_step/epoch-{} to valid_loss_epoch (When num_epochs large, it will generate a very sparse .csv)

this issue is there with every logger.

**Comment by lixinyuu** [comment]
I met the same problem. The logger csv file is unreadable at all.
