### ISSUE TITLE
Trainer: min_steps arguments overwrites early_stopping functionality

### ISSUE THREAD

**Issue by ludwigwinkler** [PyTorchLightning/pytorch-lightning#4154]
Hi,

I observed the following behaviour:
If I set min_steps to a large number (guaranteeing that the early stopping callback gets activated), the trainer will continue training even after reaching the min_steps. This error does not occur with min_epochs.

It will print "Trainer was signaled to stop but required minimum epochs (1) or minimum steps (1000) has not been met. Training will continue..." and continue training until the max_epoch flag.

## Please reproduce using [the BoringModel and post here]
https://colab.research.google.com/drive/1MCmXCwiPpuDYPkKhmxcI431Jk4U2PoZl#scrollTo=4Dk6Ykv8lI7X

### Expected behavior

My understanding is that if early stopping is triggered, the trainer should proceed until the number of minimum epochs is finished or minimum steps is reached and *then* trigger the early stopping. 

### Environment

It's all in the colab above.

**Comment by williamFalcon** [comment]
good find. yes, the training should go until at least the min steps or min epoch and then trigger early stop

**Comment by tchaton** [comment]
Hey @ludwigwinkler,

Thanks for using Pytorch Lightning !

Would you mind making your colab public. I can't access it 👍 Trying to replicate this bug locally

Best regards,
Thomas Chaton

**Comment by ludwigwinkler** [comment]
Here's a link to a freely editable colab notebook:
https://colab.research.google.com/drive/1MCmXCwiPpuDYPkKhmxcI431Jk4U2PoZl?usp=sharing

The description of the excepted behaviour is correct.

**Comment by tchaton** [comment]
Hey @ludwigwinkler,

I couldn't reproduce your bug. Would you mind creating a test with Boring Model ?

Best regards,
T.C

**Comment by ludwigwinkler** [comment]
Mh, I can't reproduce it either.
I set the trainer to train for two epochs which corresponds to 4000 training steps and the early stopping triggers after the second epoch. The min_steps flag is set to 4100. 
https://colab.research.google.com/drive/1MCmXCwiPpuDYPkKhmxcI431Jk4U2PoZl?usp=sharing#scrollTo=Flyi--SpvsJN

What's weird though is, that every validation epoch adds a single increment to the global step?

**Comment by edenlightning** [comment]
Feel free to reopen if needed!
