### ISSUE TITLE
Incorrect `get_optimizers` in gif animation

### ISSUE THREAD

**Issue by S-aiueo32** [PyTorchLightning/pytorch-lightning#4160]
## 📚 Documentation
There is an incorrect `get_optimizers` method in the gif animation in README and it should be `configure_optimizers`.

**Comment by williamFalcon** [comment]
cc @edenafek

**Comment by carmocca** [comment]
Duplicate of https://github.com/PyTorchLightning/pytorch-lightning/issues/4227
