### ISSUE TITLE
Circulation training increases memory

### ISSUE THREAD

**Issue by clearlovewl** [PyTorchLightning/pytorch-lightning#4161]
## I reproduce using [the BoringModel and post here] https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing
This is my BoringModel colab link here.
 https://colab.research.google.com/drive/1PGgSuL3Rm-pWQgBNS75LYE5PQBODueWd?usp=sharing#scrollTo=4Dk6Ykv8lI7X  

### Expected behavior
code：
`for i in range(0,50):
  test_x(tmpdir)
  print(torch.cuda.max_memory_allocated()/ 1024**2,'\n','\n','\n','\n')`

The torch.cuda.max_memory_allocated() is increasing. 
I  ran out of memory in the second loop in real situation

### Environment

* CUDA:
	- GPU:
		- Tesla P4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0+cu101
	- pytorch-lightning: 1.0.1
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

### Additional context

Wait online for a solution.

**Comment by williamFalcon** [comment]
please enable access on the colab :)

**Comment by clearlovewl** [comment]
https://colab.research.google.com/drive/1PGgSuL3Rm-pWQgBNS75LYE5PQBODueWd?usp=sharing
this is  the enable access link

**Comment by williamFalcon** [comment]
1. you need a seed.
2. i added clear mem at the loop start.

it looks pretty constant over time...

https://colab.research.google.com/drive/1QTEzsQ32RZ12S2YfARVzlBI8Z9CMyvbH?usp=sharing

**Comment by clearlovewl** [comment]
Thank you for your kind answer, but I still have problems with my project.
Because of the needs of my project, I need to run the program over and over again to measure the performance of the model. So Each time I give the model a different SEED. This can also lead to memory leaks. This makes me wonder why giving different seedings would cause this problem.
based on your code ，I change seed. colab link :
https://colab.research.google.com/drive/1KUz-IFZ8RMK9O2Gd4XSaYbRe8iFFSD09?usp=sharing
