### ISSUE TITLE
Hparams are not automatically saved to WandB logger in 1.0.2

### ISSUE THREAD

**Issue by huyvnphan** [PyTorchLightning/pytorch-lightning#4179]
## 🐛 Bug

When I update to 1.0.2, when I assign `self.hparams = args` in Lightning module, the hparams are not logged in WandB anymore. This bug is not present in 1.0.0 however. Snippets of my code.

```python
...
parser.add_argument("--description", type=str, default="Trainig")
...
args = parser.parse_args()
main(args)

# Inside main
logger = WandbLogger(name=args.description, project="myProject")
model = MyModule(args)

# Inside LightningModule
class MyModule(pl.LightningModule):
    def __init__(self, args):
        super().__init__()
        self.hparams = args
        ...
```

**Comment by nateraw** [comment]
If you aren't doing anything fancy w/ your args, its usually easier to explicitly type them. That's my quick answer, but it doesn't solve your problem. I've never used Wandb, but I'm giving it a go right now 😄 . will let ya know

**Comment by Borda** [comment]
well we are saving the initial arguments, so you should be calling `self.save_hyperparameters()`
this is not just the case of WandB, it is for all loggers since #4163

**Comment by nateraw** [comment]
Yeah your issue is solved if you just switch to using `**kwargs`. Also, make sure you're calling `self.save_hyperparameters()`.

```python
class YourModel(pl.LightningModule):
    def __init__(self, **kwargs):
        super().__init__()
        self.save_hyperparameters()

# ...
```

This made it work fine for me. seeing the correct hparams on WandB

**Comment by Borda** [comment]
Feel free to reopen if needed :]

**Comment by nateraw** [comment]
> well we are saving the initial arguments, so you should be calling `self.save_hyperparameters()`
> this is not just the case of WandB, it is for all loggers since #4163
> 
> EDIT: the reccomended flow is:
> 
> ```python
> class MyModule(pl.LightningModule):
>     def __init__(self, arg1, arg2):
>         super().__init__()
>         self.save_hyperparameters()
>         ...
> ```

I also recommend writing the args explicitly. code just reads better that way (imo).
