### ISSUE TITLE
Resume training from a finished-training model will results in a new incorrect checkpoint

### ISSUE THREAD

**Issue by ruotianluo** [PyTorchLightning/pytorch-lightning#4184]
To verify a model if a model has finished training. I ran the training script again.

However, when I try to evaluate with the model, I got error that:
```
pytorch_lightning.utilities.exceptions.MisconfigurationException:
            you restored a checkpoint with current_epoch=11
            but the Trainer(max_epochs=10)
```

After digging a little bit, it seems that since the model has finished training, it will directly go to on_train_end, and save the model checkpoint with `currect_epoch+1`.

I am wondering if the design of saving checkpoints with "next epoch" is reasonable? Why not add the epoch number after resuming?

**Comment by ruotianluo** [comment]
I moved +1 from https://github.com/PyTorchLightning/pytorch-lightning/blob/dec31b3e761115b0a938caf35649acd814f557c9/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L254 to https://github.com/PyTorchLightning/pytorch-lightning/blob/dec31b3e761115b0a938caf35649acd814f557c9/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L150

**Comment by ruotianluo** [comment]
A simpler solution is adding an if before https://github.com/PyTorchLightning/pytorch-lightning/blob/b45b57cc587a11c3049fb5c605cf2d4b0689de2c/pytorch_lightning/trainer/trainer.py#L510

**Comment by ruotianluo** [comment]
I add an if before https://github.com/PyTorchLightning/pytorch-lightning/blob/72f19768c828b734d8565ffef7b78fb9a57ba847/pytorch_lightning/trainer/training_loop.py#L178
```
         if self.trainer.current_epoch < self.trainer.max_epochs and not self.interrupted:
             self.check_checkpoint_callback(should_save=True, is_last=True)
```

**Comment by rohitgr7** [comment]
duplicate https://github.com/PyTorchLightning/pytorch-lightning/issues/4176 ?
I think a simple solution would be to not do anything anything if `current_epoch >= max_epoch`

**Comment by ruotianluo** [comment]
@rohitgr7 yes. It's the same.
