### ISSUE TITLE
1.0.2 doesn't log hyper parameters

### ISSUE THREAD

**Issue by xiadingZ** [PyTorchLightning/pytorch-lightning#4186]
In pt 1.0.2, tensorboard can't log hyperparameters, it only show `hp_metrics`. and `hparams.yaml` is empty

this is my code aboud hparams:
```
class Video_Base(pl.LightningModule):
    def __init__(self, hparams, *args, **kwargs):
        super().__init__()
        self.hparams = hparams

```

**Comment by ndrplz** [comment]
I think you should replace 
```
self.hparams = hparams
```
with
```
self.save_hyperparameters()
```
(see [here](https://github.com/PyTorchLightning/pytorch-lightning/issues/4179#issuecomment-709537764))

related: #4179

**Comment by Borda** [comment]
well we are saving the initial arguments, so you should be calling `self.save_hyperparameters()`
this is not just the case of TB, it is for all loggers since #4163 

the reccomended flow is:
```python
class MyModule(pl.LightningModule):
    def __init__(self, arg1, arg2):
        super().__init__()
        self.save_hyperparameters()
        ...
```

**Comment by Borda** [comment]
eventually, we may permit this action if `self.hparams = hparams` is inside `__init__` or just for the fist time is called...
