### ISSUE TITLE
How to use Truncated Backpropagation Through Time 

### ISSUE THREAD

**Issue by arthurpiazzi** [PyTorchLightning/pytorch-lightning#4194]
Hi all,

I am trying to use Truncated Backpropagation Through Time to train a multivariate time series dataset. 

But I found the documentation insufficient. 

Could anyone provide an example?

Thanks in advance

**Comment by awaelchli** [comment]
If anyone in the community is interested in providing an example here, feel free to send a PR. Or even a tutorial in form of a Juypter Notebook / Google Colab!
