### ISSUE TITLE
ModelCheckpoint(monitor='val_loss') crashes when with self.log("val_loss")

### ISSUE THREAD

**Issue by blisc** [PyTorchLightning/pytorch-lightning#4198]
## 🐛 Bug

ModelCheckpoint is crashing with MisconfigurationException when using monitor and using self.log inside the validation_epoch_end function.

## Please reproduce using [the BoringModel and post here](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing)

https://colab.research.google.com/drive/1vqVx1l2tp9adKAeTUS8Q-zUUBQnZtbTY

### To Reproduce
N/A

### Expected behavior

ModelCheckpoint to work and monitor my val_loss

### Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0+cu101
	- pytorch-lightning: 1.0.2
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

### Additional context

N/A

**Comment by ydcjeff** [comment]
Hi @blisc I noticed you are not calling `self.log` in validation_epoch_end
```py
    def validation_epoch_end(self, outputs):
        avg_loss = torch.stack([x['val_loss'] for x in outputs]).mean()
        # self.log('val_loss', avg_loss)
```

**Comment by blisc** [comment]
Good catch, thanks @ydcjeff. Let me know into it again and reopen if needed
