### ISSUE TITLE
Metric is different in logger and progress bar

### ISSUE THREAD

**Issue by MohammedAljahdali** [PyTorchLightning/pytorch-lightning#4199]
Hey
I am recording a metric called Character Error Rate, I was monitoring it through tensorboard logger, I also record some outputs with their CER every 100 batch, and I noticed that the CER is low  on the recorded outputs, compared to the epoch CER I saw on tensorboard and I said this might be a lucky batches. Then when I looked on the epoch CER on my progress bar it was so different from the on in tensorboard, and the CER I saw on the examples started to make sense. I don't know how to re-produce this because it's happening during a very long experiment.

Progress bar val_cer_epoch =  0.291:
 
![progress bar](https://user-images.githubusercontent.com/24215630/96321334-b8798600-101d-11eb-9dd8-04ae96c5eea3.PNG)

Tensorboard val_cer_epoch = 0.687:
![tensorboard](https://user-images.githubusercontent.com/24215630/96321400-eeb70580-101d-11eb-941e-02b7619b723d.PNG)

note:
Opening an issue on a project is new for me, so excuse me if I am doing it wrong.

**Comment by awaelchli** [comment]
which version of Lightning are you using here? 
maybe the same problem as  #4141, which was fixed in the latest version. If you are not on the latest version, try to install 1.0.2

**Comment by MohammedAljahdali** [comment]
My version is 1.0.0 . The issue you mentioned is the same as mine, I will try to install 1.0.2, if this did not work I will post here to inform you. Thanks you.

**Comment by MohammedAljahdali** [comment]
The issue is fixed with 1.0.2, I will close this issue
