### ISSUE TITLE
Viewing validation statistics by epoch (on x-axis) broken in Wandb

### ISSUE THREAD

**Issue by tadejsv** [PyTorchLightning/pytorch-lightning#4203]
## 🐛 Bug

Here's the [boring model](https://colab.research.google.com/drive/1h8KbopeAidzcLc8w7uxiOGftaoztJdMV?usp=sharing).

If you want to view the charts in Weights and Biases with epoch on the X-axis, you get a message that there is "no data availible". Viewing with the step/global step on the X-axis still works. See the two images below:

*With epoch on x-axis*
![Screenshot from 2020-10-17 15-46-05](https://user-images.githubusercontent.com/11489772/96338781-a8e75500-1090-11eb-8aef-ca72102a7e80.png)

*With global_step on x-axis*
![Screenshot from 2020-10-17 15-45-37](https://user-images.githubusercontent.com/11489772/96338782-a8e75500-1090-11eb-8f7f-52cbca131293.png)

I suspect this is related to the values that PL sends with the logs, for example this is what the CSVLogger produces:
![Screenshot from 2020-10-17 15-47-59](https://user-images.githubusercontent.com/11489772/96338780-a84ebe80-1090-11eb-9fe5-7723e40c3f54.png)

For some strange reason, there is no epoch value for validation data - the place that should definitely have it...

This bug is extremely annoying if you are, for example, experimenting with different batch sizes - then just comparing steps is meaningless...

### Environment

```
* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0+cu101
	- pytorch-lightning: 1.0.2
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020
```

P.S.: Default PL in boring model should be changed to 1.0.2.

**Comment by rohitgr7** [comment]
I think this might fix the issue https://github.com/PyTorchLightning/pytorch-lightning/pull/4130

**Comment by tadejsv** [comment]
I tried, and it does!

**Comment by awaelchli** [comment]
Thanks for reporting and reproducing. I need this too!
