### ISSUE TITLE
[Feature] Add on_after_backward in Callback. Enable ModelGradTrackerCallback

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#4212]
### Motivation

The call_hook `on_after_backward ` is already implemented, but not added in Callback class.
It boils down to add it within Callback Class

### Pitch

Adding this new hook within callback could be used to implement something like`ModelGradTrackerCallback`.

**Comment by rohitgr7** [comment]
#3657 already requested :)

**Comment by Borda** [comment]
pls, update the existing one if needed :]
