### ISSUE TITLE
Add favicon to docs

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning#4220]
TODO: Add a favicon file and set its path like: https://github.com/optuna/optuna/commit/c314894492de4bceef827f0ea188e99a8d7d6b7a.

**Comment by ydcjeff** [comment]
Shall we have a favicon for new logo?
cc: @edenlightning

**Comment by akihironitta** [comment]
@ydcjeff The new logo you mean is ![](https://assets.website-files.com/5f76c986da6f6011315a6c45/5f7b485594e5335f56984a3c_Lightning_FavIcon.png)? (favicon taken from https://pytorchlightning.ai)

**Comment by ydcjeff** [comment]
@akihironitta yes

**Comment by akihironitta** [comment]
Link https://github.com/PyTorchLightning/pytorch-lightning/issues/4286 when updating the logo images.
