### ISSUE TITLE
segmentation fault when import pytorch_lightning

### ISSUE THREAD

**Issue by zye1996** [PyTorchLightning/pytorch-lightning#4224]
I am trying the very minimum code which imports torch and pytorch_lightning, with the following code:
```import torch
import pytorch_lightning as pl
```
The import of pytorch_lightning fails immediately with the error: 29144 segmentation fault (core dumped)  python
I am using pytorch-dev 1.7.0 as it is required for cuda11 with new GPUs, and I installed pytorch-lightning from source. 

 - OS: Linux
 - Packaging: pip
 - Version 1.0.2

**Comment by ydcjeff** [comment]
Hi @zye1996 thank you for reporting.
While we have nightly support for PyTorch 1.7, we have only tested in cpu environment. Also we currently only support CUDA 10.1 and 10.2 just like pytorch did. So this issue may come from CUDA 11 + PyTorch 1.7-dev as the binaries are not built for CUDA 11 yet.

https://discuss.pytorch.org/t/pytorch-with-cuda-11-compatibility/89254/4

If you don't have a specific requirment to use cuda 11, it'd probably better to use pytorch 1.6/1.7-dev and cuda 10.1 or 10.2.

**Comment by jxmorris12** [comment]
I ran into this same issue, and fixed it by updating torch under the hood:
```bash
conda install pytorch torchvision torchaudio -c pytorch
```
