### ISSUE TITLE
Batch size finder is not working if batch_size is specified in LightningDataModule

### ISSUE THREAD

**Issue by maxjeblick** [PyTorchLightning/pytorch-lightning#4226]
## 🐛 Bug

The batch size finder won't work if the batch size is specified in the LightningDataModule, only (it is natural to define it there). 

An instance of a LightningModule always has the attribute [hparams](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/core/lightning.py#L1603); the batch_size finder raises a `MisconfigurationException` if `batch_size` isn't found [there](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/tuner/batch_size_scaling.py#L70).

## Please reproduce using [the BoringModel and post here](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing)

https://colab.research.google.com/drive/1gruW3UwitVijzkhcUYIzHlIpoIB1shzt?usp=sharing

### Expected behavior
Batch size finder works.

### Environment

* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0+cu101
	- pytorch-lightning: 0.10.0
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

**Comment by SkafteNicki** [comment]
That is strange, we have a test for that specific case:
https://github.com/PyTorchLightning/pytorch-lightning/blob/7c4f80a1afe3d7b0f1e9ee834aacaf8439195cdf/tests/trainer/test_trainer_tricks.py#L233-L270
It must be the logic in `lightning_hasattr`, that is broken, because it should explicit check if dataloader has a field called `batch_size`:
https://github.com/PyTorchLightning/pytorch-lightning/blob/7c4f80a1afe3d7b0f1e9ee834aacaf8439195cdf/pytorch_lightning/utilities/parsing.py#L177-L197

**Comment by maxjeblick** [comment]
In the test mentioned above, the `batch_size` is also specified inside the `LightningModule`. Both attributes `batch_size` (inside the module and inside the datamodule) are updated correctly.
The batch size finder fails if `batch_size` is specified in the datamodule, only.

**Comment by edenlightning** [comment]
@maxjeblick would you like to try and submit a PR to fix?

**Comment by maxjeblick** [comment]
@edenlightning Yes I can have a look.
