### ISSUE TITLE
Add contributors section

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#423]
Would be great to have a nice display of the contributors in the README.md.

Here's an example:
https://github.com/tqdm/tqdm#contributions

![image](https://user-images.githubusercontent.com/3640001/67475036-6b89ec00-f623-11e9-8a24-c762f7496e7c.png)

**Comment by Joel-hanson** [comment]
Shall I do this @williamFalcon

**Comment by Borda** [comment]
@williamFalcon still going to add it or are we fine with the list as it is now?
@Joel-hanson are still interested in sending this PR?
