### ISSUE TITLE
[AttributeError] Multiple validation dataloaders

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#4245]
## Please reproduce using [the BoringModel and post here](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing)

```
        for dl_idx, dl_metrics in enumerate(step_metrics):
            if len(dl_metrics) == 0:
                continue
            reduced_epoch_metrics = dl_metrics[0].__class__.reduce_on_epoch_end(dl_metrics)
            # make the keys 'k/dl'
            reduced_epoch_metrics = self.__rename_keys_by_dataloader_idx(reduced_epoch_metrics, dl_idx, num_loaders)
            # track the metrics
            logger_metrics = reduced_epoch_metrics.get_epoch_log_metrics()
```

with `__rename_keys_by_dataloader_idx`

```
AttributeError 'dict' object has no attribute 'get_epoch_log_metrics'
```

### Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by edenlightning** [comment]
@tchaton update on this issue?

**Comment by edenlightning** [comment]
This should be fixed in master, by the logging refactor.
