### ISSUE TITLE
Documentation page load speed

### ISSUE THREAD

**Issue by jonashaag** [PyTorchLightning/pytorch-lightning#4248]
## 🐛 Bug

Documentation loads slowly due to lots of assets. For example, in Firefox, this page https://pytorch-lightning.readthedocs.io/en/stable/trainer.html takes 12 s to load and downloads 18 MiB. In Chrome (vanilla configuration) it takes 34 s and loads 36 MiB.

In Firefox most of the time is spent making request (> 100 requests), and most data comes from large video preview files. In Chrome most time is spent downloading the first few seconds of each of the videos.

**Comment by edenlightning** [comment]
Thanks for the issue! If you have any ideas to speed up, would be great :)

**Comment by jonashaag** [comment]
Why are you considering this a won’t fix?
