### ISSUE TITLE
GAN example doesn't work

### ISSUE THREAD

**Issue by vobecant** [PyTorchLightning/pytorch-lightning#4249]
## 🐛 Bug

The GAN example for MNIST doesn't work as advised in the script basic_gan_module.py

## Please reproduce using [the BoringModel and post here](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing)

To reproduce the issue just run:
`basic_gan_module.py --gpus 1`

### Expected behavior
Train the GAN network well for MNIST dataset with the default setting.

### Environment
* CUDA:
	- GPU:
		- GeForce GTX 1080 Ti
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.19.1
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0
	- pytorch-lightning: 1.0.2
	- tqdm:              4.50.2
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.8.5
	- version:           #1 SMP Tue Aug 25 17:23:54 UTC 2020

**Comment by tchaton** [comment]
Dear @vobecant, 

Are you referring to Bolt examples (https://github.com/PyTorchLightning/pytorch-lightning-bolts) ?
If yes, could you open an issue there ?

Best,
T.C

**Comment by vobecant** [comment]
Dear @tchaton , yes, I am. I will open the issue there.
