### ISSUE TITLE
Error in logging of Regression Metrics

### ISSUE THREAD

**Issue by pbmstrk** [PyTorchLightning/pytorch-lightning#4266]
## 🐛 Bug

When attempting to log a regression metric object as described [here](https://pytorch-lightning.readthedocs.io/en/stable/metrics.html#) when training for more than one epoch, the following error occurs,

```
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment
```

Interestingly, this error only occurs when using regression metrics. For example, `Accuracy()` works without any problems. 

### Boring Model Link

[Link](https://colab.research.google.com/drive/1dVJAq-jrgaFfdsSmjTBbrCVRnQ2ywNNC?usp=sharing)

### Expected behavior

Logging should work for all metrics.

When comparing to metrics that work it seems that in the case of the regression metrics some of the variables (e.g. `sum_squared_error`) are still attached to the computational graph - which seems to be the cause of the problem. If I add the line,

```
preds = preds.detach()
```

to the `update()` method everything seems to work.

### Environment

see colab.

**Comment by edenlightning** [comment]
@SkafteNicki or @teddykoker

**Comment by ananyahjha93** [comment]
@pbmstrk mind sending in a PR with .detach fix?

**Comment by ananyahjha93** [comment]
@pbmstrk actually there are other issues with detaching or keeping attached metrics which are discussed here, so maybe wait for @SkafteNicki to send in a PR for the base class and see if that resolves the issue itself.

Discussion here: #4098.

**Comment by pbmstrk** [comment]
@ananyahjha93 Ah okay, no worries!

**Comment by SkafteNicki** [comment]
@pbmstrk just pushed a commit to PR #4313 that solves the bug (confirmed by running colab model) :]
Basically had to call detach within the `self.log` code (only `Metric` objects did not automatically get detached, which is rectified now in the PR)
