### ISSUE TITLE
EarlyStopping mode auto is unknown, fallback to auto mode.

### ISSUE THREAD

**Issue by david-waterworth** [PyTorchLightning/pytorch-lightning#4268]
In the process of refactoring as I upgraded lighting and it looks like there's been a slight change to the callback interface.

This code:

`early_stop_callback = pl.callbacks.EarlyStopping(verbose=True)`

Results in the message:

> EarlyStopping mode auto is unknown, fallback to auto mode.
> EarlyStopping mode set to min for monitoring early_stop_on.

The default for `mode` is 'auto' so the first message doesn't make sense

**Comment by tchaton** [comment]
Hey @david-waterworth,

Thanks for using Pytorch Lightning and finding this bug !

I think it should be this way.

```
EarlyStopping mode not provided, fallback to auto mode.
...
EarlyStopping mode set to min for monitoring early_stop_on.
```

Best regards,
Thomas Chaton.
