### ISSUE TITLE
training is very slow 

### ISSUE THREAD

**Issue by morestart** [PyTorchLightning/pytorch-lightning#4269]
#### when I use gpu (rtx2080 8G) to train a simple net, it give me a cuda out of memory error,dataset is cat and dog. so I use cpu to train my net, it's to slow for me, my cpu is i9-9900K

Epoch 0:  37%|███▋      | 9300/25000 [14:30:04<24:28:50,  5.61s/it, loss=0.706, v_num=4, train loss_step=0.675]
it will use 24h??.. oh

#### Code
this is my code
https://colab.research.google.com/drive/18dJM0iyhhiJnahkz9lnKfa4UKyDhJx08?usp=sharing

#### What's your environment?

 - OS: [ Win]
 - Packaging [ pip]
 - Version 1.0.2

**Comment by rohitgr7** [comment]
dataset link?

**Comment by ananyahjha93** [comment]
@rohitgr7 I think it is the kaggle dataset: https://www.kaggle.com/c/dogs-vs-cats

**Comment by ananyahjha93** [comment]
@morestart You are not reducing spatial dimension of feature maps using Conv layers and you first linear layer weights themselves are > 2GB in size. The linear layer should not be 14 * 224 * 224.

**Comment by morestart** [comment]
> @morestart You are not reducing spatial dimension of feature maps using Conv layers and you first linear layer weights themselves are > 2GB in size. The linear layer should not be nn.Linear(14 * 224 * 224, 1024).
> 
> That itself is exceeding the GPU memory with a batch size of 1. Closing this issue for now.

thanks!
