### ISSUE TITLE
ModelCheckpoint.save_function documentation

### ISSUE THREAD

**Issue by david-waterworth** [PyTorchLightning/pytorch-lightning#4271]
I might be looking in the wrong place but I couldn't find any documentation on `ModelCheckpoint.save_function`. I found after upgrading to the latest release I have to specify after constructing a `ModelCheckpoint` or an exception is thrown (maybe it should be a non-optional constructor kwarg since without setting it, the callback isn't really properly constructed?)

I did the following, is this what you expect (transformer is my model instance).

    checkpoint_callback = pl.callbacks.ModelCheckpoint(verbose=True, mode='min', monitor='val_loss')
    def save_function(filepath, *args):
        torch.save(transformer.state_dict(), filepath)
    checkpoint_callback.save_function = save_function

**Comment by ydcjeff** [comment]
@david-waterworth here's it.

https://pytorch-lightning.readthedocs.io/en/stable/generated/pytorch_lightning.callbacks.ModelCheckpoint.html#pytorch_lightning.callbacks.ModelCheckpoint.save_checkpoint

**Comment by david-waterworth** [comment]
@ydcjeff I don't think that's the same thing. The ModelCheckpoint expects a callback with signature `save_function(filepath, save_weights_only)` - https://github.com/PyTorchLightning/pytorch-lightning/blob/09c2020a9325850bc159d2053b30c0bb627e5bbb/pytorch_lightning/callbacks/model_checkpoint.py#L295

The `save_checkpoint` function https://github.com/PyTorchLightning/pytorch-lightning/blob/09c2020a9325850bc159d2053b30c0bb627e5bbb/pytorch_lightning/callbacks/model_checkpoint.py#L179 says "it is the responsibility of `self.save_function` to handle correct behaviour in distributed training" but doesn't really go into details

**Comment by ydcjeff** [comment]
@david-waterworth so your question is you need to specify `save_function` for ModelCheckpoint to work properly?
or you want to use your custom `save_function`?

**Comment by david-waterworth** [comment]
Yes it appears that you have to supply your own function - I thought perhaps if you didn't it might have a default but that's not what I've observed.

**Comment by david-waterworth** [comment]
Looks like I'm running into bug #4275

**Comment by ydcjeff** [comment]
@david-waterworth you need to pass ModelCheckpoint to `checkpoint_callback` to work properly
See: https://colab.research.google.com/drive/1mkB5sshFDZMFZnrCWhjW561El5Kmlp13?usp=sharing

passing `ModelCheckpoint` to `callbacks` flag is still WIP

**Comment by ydcjeff** [comment]
Closing it as it's resolved
