### ISSUE TITLE
Update logo images

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning#4286]
## 🚀 Feature
There are currently old logo images here as well as in bolts. Would be fantastic to see new ones.
- pytorch-lightning: https://github.com/PyTorchLightning/pytorch-lightning/tree/8a20d6af51d13adec37593c1356ce08ef380e828/docs/source/_images/logos/
- pytorch-lightning-bolts: https://github.com/PyTorchLightning/pytorch-lightning-bolts/tree/2f3f58045a44ffb32103a3644c2ee2be920a508b/docs/source/_images/logos/

**Comment by ananyahjha93** [comment]
@edenlightning can you send in quick PR for this?
