### ISSUE TITLE
k-fold cross validation using DataModule

### ISSUE THREAD

**Issue by celsofranssa** [PyTorchLightning/pytorch-lightning#4287]
DataModule is great! 
I'm wondering how it can be applied to handle with k-fold cross-validation.

**Comment by rohitgr7** [comment]
all k models and datamodules will be independent so create seperate datamodules and models for each.

**Comment by ananyahjha93** [comment]
I think there is a discussion of having a cross validation feature in Lightning in #839.

**Comment by ananyahjha93** [comment]
@SkafteNicki @Borda @justusschock tagging you guys here as well.

**Comment by Svito-zar** [comment]
Has this feature been implemented yet?
I could not find it in the documentation ...

**Comment by SkafteNicki** [comment]
@Svito-zar not implemented, closed due to being a duplicate of #839

**Comment by macabdul9** [comment]
Any update on this?
