### ISSUE TITLE
Using `terminate_on_nan=True` on TPU leads to huge slowdowns

### ISSUE THREAD

**Issue by harpone** [PyTorchLightning/pytorch-lightning#4302]
## 🐛 Bug

Using `trainer = Trainer(terminate_on_nan=True, ...)` leads to calling `TrainerTrainingTricksMixin().detect_nan_tensors()`, which is very slow on TPU. About 5x slower forward passes for resnet50 scale nets.

Should maybe raise a warning if using TPUs and `terminate_on_nan`.

**Comment by awaelchli** [comment]
yes terminate on nan always leads to a slow down, also for GPU and CPU not just TPU. I don't see a way to speed it up, and it's not clear to me why it is a bug?
It should only be used for debugging.

**Comment by harpone** [comment]
Seemed pretty fast on GPU, but OK. No need to speed it up but a warning would be nice.
