### ISSUE TITLE
Checkpoint hparams.yaml does not save current self.hparms, but only at self.save_hyperparameters

### ISSUE THREAD

**Issue by NumesSanguis** [PyTorchLightning/pytorch-lightning#4316]
## 🐛 Bug

I expect that `lightning_logs/version_0/hparams.yaml` matches `self.hparams` when Checkpoint is called, or at least matches `self.hparams` when calling `trainer.fit(model)`.
Instead `hparams.yaml` only contains the arguments given to `self.save_hyperparameters()` (empty is all arguments).

## Please reproduce using [the BoringModel and post here](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing)

https://colab.research.google.com/drive/1dmZjS_3SETwF3hAAeCq0xdrd0NQGs9nt?usp=sharing

### To Reproduce

```
def __init__(self, output_neurons):
    super().__init__()
    # !!!!! CHANGED !!!!!
    self.save_hyperparameters()
    self.hparams["output_neurons"] = 3
    self.layer = torch.nn.Linear(32, self.hparams["output_neurons"])
...
model = BoringModel(output_neurons=2)
```

### Expected behavior

Inside `hparams.yaml` the following line:
```yaml
output_neurons: 3
```

### Actual behavior
Inside `hparams.yaml` the following line:
```yaml
output_neurons: 2
```

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

* `IDE`: Please, use our python [bug_report_model.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
) template.

* `Colab Notebook`: Please copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py) (or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```
Colab

* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0+cu101
	- pytorch-lightning: 1.0.3
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020
 - Any other relevant information:

### Additional context

I listed this as a bug, as it would go against (my) intuition. If this is intended behavior, this should be made clear in the documentation.

#### How I came across this issue
I trained and model and saved it with `to_torchscript()`. I wanted to share with my teams the hparams of this new model.pt, but found out that `hparams.yaml` did not contain the hparam values I used to train the model with. I'm also adding additional information to self.hparams later in the `pl.LightningModule`, but this was also not included.

Imagine doing transfer learning. You set `self.hparams["output_neurons"] = 10` to match the output size when loading the weights of a pre-trained model. Then you change `self.hparams["output_neurons"] = 5` and do a `self.output_layer = torch.nn.Linear(32, self.hparams["output_neurons"])` to train on your new task.
You would expect `hparams.yaml` to contain this new output size, but in the current PL version it does not.

**Comment by NumesSanguis** [comment]
For the people who need hparams.yaml to be complete (setting self.hparam values after creating an instance), here is a workaround:

```python
from pytorch_lightning.callbacks import Callback
from pytorch_lightning.core.saving import save_hparams_to_yaml

class OnCheckpointHparams(Callback):
    def on_save_checkpoint(self, trainer, pl_module):
        # only do this 1 time
        if trainer.current_epoch == 0:
            file_path = f"{trainer.logger.log_dir}/hparams.yaml"
            print(f"Saving hparams to file_path: {file_path}")
            save_hparams_to_yaml(config_yaml=file_path, hparams=pl_module.hparams)

trainer = Trainer(callbacks=[OnCheckpointHparams()])
```

This calls the save hparams to yaml function only on the first epoch (epoch==0), so you'll have the self.hparams at time of training start.

**Comment by edenlightning** [comment]
@awaelchli is this a bug?

**Comment by awaelchli** [comment]
It depends what we want the meaning of `hparams.yaml` to be. We could say 

a) it is the hyperparameters passed into the LightningModule (current behaviour) or 
b) it is the latest state of hyperparameters (can be updated after init). 

The current behavior in my view is the correct one. See this artificial example:

```python 
def __init__(self, output_neurons):
    super().__init__()
    self.save_hyperparameters()
    if output_neurons == 1:
        self.hparams["output_neurons"] = 3
    else:
        self.hparams["output_neurons"] = 5
    
    self.layer = torch.nn.Linear(32, self.hparams["output_neurons"])
...
model = BoringModel(output_neurons=1)  # saves output_neurons=3
```

With current behavior (a) we save `output_neurons=1` to the file. With (b) we would save `output_neurons=3`. 
Now I ask you: **What is the parameter I need to pass into the model to reproduce results?**
The answer is `output_neurons=1`, not 3.

Therefore, for the sake of reproducibility I recommend to keep the current behavior.

**Comment by NumesSanguis** [comment]
@awaelchli I saw `hparams.yaml` as a "These are the values the model has been trained with." (your b).
Do I correctly understand that `hparams.yaml` is NOT used when loading a model, but instead it's just for the user?
Because the question:

> What is the parameter I need to pass into the model to reproduce results?

Is not in relation to `hparams.yaml`, but to what's inside `some_model.pt` right?

I can understand if you want `hparams.yaml` to stand for a). If that's the case, this issue can be closed and I just use my callback to get my intended use of `hparams.yaml`.
However, if `hparams.yaml` is to show to any user (not just the person who trained it) what hparams are in the model, then b) makes more sense. A 3rd party does not know how `self.hparams` has been modified if he/she only gets the `.ckpt` or `.pt` and `hparams.yaml` files (which is enough for a TorchScript model).

-----

Somewhat relevant issue about `save_hyperparameters()`: https://github.com/PyTorchLightning/pytorch-lightning/issues/3981

**Comment by awaelchli** [comment]
You make good point with torchscript. We have now arguments for and against both ways. It seems that the whole discussion just comes to the simple question:

**Should the hparams.yaml file be kept in sync with the contents of the checkpoint?**

I do not know how important it is to be able to tell with what parameters a torchscript model was trained (not much experience). I do however know from own experience that it is very important to know how a model was initialized, i.e. in the case the parameters change then the only way to reproduce the results is to know the _initial_ parameters.
