### ISSUE TITLE
Lightning/Transformers tutorial contribution?

### ISSUE THREAD

**Issue by dataframing** [PyTorchLightning/pytorch-lightning#435]
First off, thank you for your hard work on this package! It's proven to be _very_ helpful for fully leveraging multi-GPU training of large-scale language models.

---

**Is your feature request related to a problem? Please describe.**
I'm using the (also incredible) [transformers](https://github.com/huggingface/transformers) package by the folks at HuggingFace to do a number of tasks, including text classification. I realized that training these models can be quite computationally expensive, even on decently-sized single-GPU instances. I found out about this repo and was (with relative ease) able to train the same model over 4 GPUs and 16-bit precision much, _much_ more easily than training with vanilla PyTorch. 

I was wondering if there was any interest in a contributed tutorial that specifically goes through the process of integrating pytorch-lightning with `transformers`, which seems to have quite a bit of staying power and success within the realm of applied NLP. Regardless, thanks again!

**Describe the solution you'd like**
N/A?

**Describe alternatives you've considered**
N/A?

**Additional context**
N/A?

**Comment by williamFalcon** [comment]
yes! that would be amazing. would welcome a PR!

**Comment by dataframing** [comment]
Neat! I noticed that the current domain template (for GANs [here](https://github.com/williamFalcon/pytorch-lightning/blob/master/pl_examples/domain_templates/gan.py)) is a Python script — is that preferred over a full notebook?

**Comment by Borda** [comment]
I would suggest creating a tutorial folder with notebooks. Later we can automatically generate documentation from these notebooks, see [example from readthedocs](https://birl.readthedocs.io/en/latest/notebooks/ANHIR_submissions-stat.html)

**Comment by williamFalcon** [comment]
@dataframing go ahead and make a notebook!

**Comment by dataframing** [comment]
Sounds good! Apologies for the delay here; had a busy week. Should be able to get something out soon 👍

**Comment by williamFalcon** [comment]
@dataframing any updates? in the meantime, we can  use the tutorial i put together on medium and the COLAB in the readme
