### ISSUE TITLE
Add best_model_monitor to ModelCheckpoint

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#4368]
### Motivation

If I have a directory with many checkpoints, possibly belonging to runs with different monitors, I don't know which metric was tracked by each checkpoint.

### Pitch

```python
ckpt = torch.load("saved_model.ckpt")
assert hasattr(ckpt, "checkpoint_callback_best_model_monitor"
```

### Alternatives

Guess If I included the monitor in the checkpoint name, I could parse it to know. But seems much more convenient to add the property.

**Comment by rohitgr7** [comment]
another alternative: you can also add that to checkpoint itself in `on_save_checkpoint`.

**Comment by carmocca** [comment]
Do you mean by overriding it in my `LightningModule`?

It is an ugly solution because it does not know about any ModelCheckpoints used. Only the trainer knows about them.

So I would need to instantiate my LightningModule with an added `checkpoint_callback_monitor` parameter in order to do:

```python
def on_save_checkpoint(self, checkpoint):
    checkpoint["checkpoint_callback_best_model_monitor"] = self.checkpoint_callback_monitor
```

**Comment by ananthsub** [comment]
@carmocca [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/6abc254ae6830bcf2688f780cd12ef68e57531ce/pytorch_lightning/callbacks/model_checkpoint.py#L188-L192)

**Comment by carmocca** [comment]
If you guys agree with this issue, I can work on the PR

**Comment by ananthsub** [comment]
I think it makes sense to add `monitor` especially since `best_model_score` is already included. Lightning should track what that score actually represents 😃

**Comment by rohitgr7** [comment]
> Do you mean by overriding it in my LightningModule?

na.. not the LightningModule but ModelCheckpoint, I know it's ugly haha..
IMO I think it's good to have the monitor as well. But need to check whether it is required to load it back or not in `on_load_checkpoint`.
