### ISSUE TITLE
Make profiling possible on validation steps.

### ISSUE THREAD

**Issue by pafi-code** [PyTorchLightning/pytorch-lightning#4370]
## 🚀 Make profiling possible on validation steps.
It would be really nice, if we could also profile function calls at validation and/or test stage.

### Motivation
In my case the implementation and functionality of the validation step is really different than the one from the training step so it would be nice to also profile this one. Different metrics are getting calculated and some other stuff is going on.

**Comment by ydcjeff** [comment]
@pafi-code are you interested in implementing this feature?
