### ISSUE TITLE
Please support drop_last in DistributedSampler when you update to PyTorch 1.7.0

### ISSUE THREAD

**Issue by blisc** [PyTorchLightning/pytorch-lightning#4377]
## 🚀 Feature
Please support drop_last in DistributedSampler when you update to PyTorch 1.7.0

### Motivation

DistributedSampler is currently bugged in PyTorch 1.6.0, but it is fixed in master
PyTorch PR that fixed this bug: https://github.com/pytorch/pytorch/pull/41171

### Pitch

Pass through (train/val/test)_dataloader's drop_last parameter to DistributedSampler

**Comment by carmocca** [comment]
This is tricky because Lightning supports torch<1.7.0 so if we added it as an option to the Trainer, it would only have an effect for torch>=1.7.0

You could always set the DistributedSampler yourself without Lightning having an explicit option for it.
