### ISSUE TITLE
Add sacred logger

### ISSUE THREAD

**Issue by expectopatronum** [PyTorchLightning/pytorch-lightning#438]
**Is your feature request related to a problem? Please describe.**
For most of our projects we are using [sacred](https://github.com/IDSIA/sacred) for logging the parameters, metrics, ... to a MongoDB database.  For the last project I used pytorch-lightning with the default logger, but I'd prefer sacred.

**Describe the solution you'd like**
I'd like a `SacredLogger` for logging with `sacred` similar to `MLFlowLogger` for `mlflow`.

At some point I'll implement this myself but I thought maybe someone else is interested as well.

**Comment by neggert** [comment]
Could you tackle this yourself? It should be pretty straightforward. You can use the other loggers in https://github.com/williamFalcon/pytorch-lightning/tree/master/pytorch_lightning/logging as examples.

**Comment by expectopatronum** [comment]
Yes, I can and I will, just like I said in the description of my issue. But since this is an open source project I thought maybe someone else might be interested as well, or already attempted it or might be interested in having it implemented. If no one else is interested (because no one is using sacred except me) I don't need to take the effort and create a pull request (which is a lot more work than just implementing a custom logger for myself).
I am sorry if this is not how issues should be used in this project but I saw [this](https://github.com/williamFalcon/pytorch-lightning/issues/265) and thought this should be fine.

**Comment by neggert** [comment]
Sorry, I was unclear. Thanks for opening an issue. That's the correct way to start a discussion on a new feature. I'm not aware of anyone else working on this, but I believe Sacred is fairly widely used, so we'd encourage you to submit a PR  adding this functionality.

Feel free to follow up here if you run into any questions or issues while implementing it.

**Comment by williamFalcon** [comment]
@expectopatronum still interested in submitting a PR for this? :)

**Comment by expectopatronum** [comment]
Yes, I am working on it now! :)

**Comment by williamFalcon** [comment]
@expectopatronum want to rebase master so we can merge? great  job!

**Comment by Borda** [comment]
there is still an issue with testing, tests shall not be tolerant of the missing package...

**Comment by williamFalcon** [comment]
what do you mean?

**Comment by Borda** [comment]
> what do you mean?

is the package is not loaded then it is not tested.. https://github.com/PyTorchLightning/pytorch-lightning/pull/656#discussion_r369521641

**Comment by Borda** [comment]
if there is an interest in this logger we may add it to upcoming `lightning-bolts` :robot:

**Comment by williamFalcon** [comment]
@Borda we haven't decided on whether to move loggers or not.

**Comment by Borda** [comment]
sure, but with @expectopatronum not having time to add it https://github.com/PyTorchLightning/pytorch-lightning/pull/656#issuecomment-581504898, there is noone to do it now... or do you prefer to keep this open?

**Comment by diff7** [comment]
Hi, any plans to sacred logger?

**Comment by Borda** [comment]
@diff7 mind open an issue for it in Bolts as suggested in https://github.com/PyTorchLightning/pytorch-lightning/issues/438#issuecomment-604446913
