### ISSUE TITLE
LightningModule.load_from_checkpoint with module_arguments is broken

### ISSUE THREAD

**Issue by lagph** [PyTorchLightning/pytorch-lightning#4390]
## 🐛 Bug
Saving a `LightningModule` whose constructor takes arguments and attempting to load using `load_from_checkpoint` errors with

```
TypeError: __init__() missing 1 required positional argument: 'some_param'
```

## Please reproduce using [the BoringModel and post here](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing)

https://colab.research.google.com/drive/1fbzDt4mEjRQuy4L_DYkkZqBRhQCxZ6kP?usp=sharing

### Expected behavior
```python

class BoringModel(LightningModule):

    def __init__(self, some_param):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)
        self.some_param = some_param



model = BoringModel(some_param=10)

# Initialize a trainer
trainer = pl.Trainer(
    max_epochs=1, 
    progress_bar_refresh_rate=20
)

# Train the model ⚡
trainer.fit(model, train, val)
trainer.save_checkpoint("example.ckpt")

model = BoringModel.load_from_checkpoint("example.ckpt")
assert model.some_param == 10
```
### Environment

* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0+cu101
	- pytorch-lightning: 1.0.0
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

### Additional context

Part of the problem seems to stem from `checkpoint_connector.py`:
```python
        # add the module_arguments and state_dict from the model
        model = self.trainer.get_model()

        checkpoint["state_dict"] = model.state_dict()

        if model.hparams:
            if hasattr(model, "_hparams_name"):
                checkpoint[
                    LightningModule.CHECKPOINT_HYPER_PARAMS_NAME
                ] = model._hparams_name
            # add arguments to the checkpoint
            if OMEGACONF_AVAILABLE:
                checkpoint[LightningModule.CHECKPOINT_HYPER_PARAMS_KEY] = model.hparams
                if isinstance(model.hparams, Container):
                    checkpoint[LightningModule.CHECKPOINT_HYPER_PARAMS_TYPE] = type(
                        model.hparams
                    )
            else:
                checkpoint[LightningModule.CHECKPOINT_HYPER_PARAMS_KEY] = dict(
                    model.hparams
                )

        # give the model a chance to add a few things
        model.on_save_checkpoint(checkpoint)
        if self.trainer.datamodule is not None:
            self.trainer.datamodule.on_save_checkpoint(checkpoint)

        return checkpoint

```
It says "add the module_arguments and state_dict from the model" but I don't see `module_arguments` being added anywhere. Also, there seems to be confusion between `model.hparams` and `module_arguments`: for instance here
```python
            try:
                atomic_save(checkpoint, filepath)
            except AttributeError as err:
                if LightningModule.CHECKPOINT_HYPER_PARAMS_KEY in checkpoint:
                    del checkpoint[LightningModule.CHECKPOINT_HYPER_PARAMS_KEY]
                rank_zero_warn(
                    "Warning, `module_arguments` dropped from checkpoint."
                    f" An attribute is not picklable {err}"
                )
                atomic_save(checkpoint, filepath)

```
it warns about `module_arguments` but is actually checking `hyper_parameters`.

**Comment by rohitgr7** [comment]
It just saves model state_dict (model weights) and all other parameters are saved as hyperparameters.
For that you need to use:
```python
def __init__(self, some_param):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)
        self.save_hyperparameters()
```

if you don't want to save them as hyperparameters then while loading you need to pass them in `load_from_checkpoint` explicitly as kwargs.

**Comment by lagph** [comment]
Ok, thanks! Looks like the docs are out of date though, see the end of this section: https://pytorch-lightning.readthedocs.io/en/stable/weights_loading.html#automatic-saving. Also there are a bunch of references to `module_arguments` in the comments in the code.

**Comment by rohitgr7** [comment]
Haven't seen `module_arguments` before. Looks like these are available for backward compatibitly in order to support checkpoints trained before v0.7.6. Should docs be updated?? @Borda

**Comment by awaelchli** [comment]
yes, I'm pretty sure module_arguments should not be mentioned anywhere, that's old.

**Comment by rsokl** [comment]
> yes, I'm pretty sure module_arguments should not be mentioned anywhere, that's old.

oh... yes, the [checkpoint loading](https://pytorch-lightning.readthedocs.io/en/stable/weights_loading.html#checkpoint-loading) docs should be revised then. 

I was just about to open a bug report because the [docs tell me](https://pytorch-lightning.readthedocs.io/en/stable/weights_loading.html#checkpoint-loading):

> To load a model along with its weights, biases and module_arguments use the following method

and it makes no mention of `save_hyperparameters()`, and tells me to look for `module_arguments` in my checkpoint

**Comment by awaelchli** [comment]
@rsokl I removed the old references to module_arguments here: #4417
Do these changes look good to you? 

> and it makes no mention of save_hyperparameters(), and tells me to look for module_arguments in my checkpoint

Yeah, it makes no mention, but we have a different docs section just for [hyperparameters](https://pytorch-lightning.readthedocs.io/en/stable/hyperparameters.html#lightningmodule-hyperparameters). The docs you are looking at is currently just about loading and saving checkpoint. Maybe we need to add a link.

**Comment by rsokl** [comment]
@awaelchli this looks good! But as @rohitgr7  mentioned there needs to be a class to `self.save_hyperparameters()` to make the code snippet correct

**Comment by m13uz** [comment]
None of the links works :(

**Comment by rohitgr7** [comment]
@m13uz here is the link which contains everything related to checkpointing: https://pytorch-lightning.readthedocs.io/en/stable/common/checkpointing.html

let me know if you are looking for something specific. You can also search for it in the search bar.
