### ISSUE TITLE
Improve documentation for trainer.test()

### ISSUE THREAD

**Issue by pbmstrk** [PyTorchLightning/pytorch-lightning#4392]
## 📚 Documentation

I noticed a couple of things when working with the `trainer.test()` method:

1. I think that it should be highlighted that the `ckpt_path` and `model` arguments of `trainer.test()` are mutually exclusive. That is, if you pass a model the checkpoint path is ignored. I noticed this as I tried to use,
```
trainer.test(model, ckpt_path=checkpoint_callback.best_model_path)
```
believing that this would test the given model using the weights in the checkpoint, however after looking at the code
https://github.com/PyTorchLightning/pytorch-lightning/blob/6878f3bf4e2df94eed430cb9db4b47e419948af9/pytorch_lightning/trainer/trainer.py#L709-L712
this simply evaluates the given model ignoring the checkpoint path. Perhaps raising a warning if passing both a `model` and `ckpt_path` would help resolve the confusion.

Another option would be to override the weights of a model, if both `model` and `ckpt_path` are provided. This would allow for testing and loading models with different `state_dicts` without having to redefine a new instance of trainer. As currently, I believe it is not possible to train a model, and then test a different model from a checkpoint without having to create a new instance of trainer. 

2. Using `trainer.test` with `ckpt_path` silently changes the weights of the model to that of the checkpoint (not sure if this is desired behaviour). That is,

```
model = LitModel()
results_before = trainer.test(model, ...)
results_checkpoint = trainer.test(ckpt_path = "/path/to/model", ...)
results_after = trainer.test(model, ...)

# causes the following
results_before != results_after
results_checkpoint == results_after
```

Would it not be safer to create a copy of the model before copying the weights?

**Comment by rohitgr7** [comment]
IMO it should load the `ckpt_path` regardless if the model is passed or not.

**Comment by pbmstrk** [comment]
@rohitgr7 I'm not sure I understand what you mean. The way I see it the `trainer.test()` can currently be used for two scenarios.
1. Test using a model with existing weights (e.g. test model after training) -> can simply use `trainer.test(model, ...)`
2. Test using a checkpoint of the model -> can use `trainer.test(ckpt_path="best", ...)`

For example, if the ModelCheckpoint callback is not used, there is not `ckpt_path` to load from. So there is a use-case for passing `model` and not loading weights from `ckpt_path`. My confusion arose as I thought that when passing a model and checkpoint path, `test()` would copy the weights from the checkpoint to the model and evaluate. Thought it might be useful to raise a warning if a user passes both a model and checkpoint path to highlight that the checkpoint path will be ignored. 

Alternatively, if both `model` and `ckpt_path` are passed, `test()` could load the checkpoint weights into the model. This would allow to test models structurally different from `trainer.get_model()`. This would be useful if I wanted to test many different models whose `state_dict` don't match - currently I would have to load the checkpoints manually and then pass the model to `test()`. I guess an argument against enabling this behaviour is that testing different models than were trained, pollutes things such as `callback_metrics` and makes things harder to follow and keep track of.

**Comment by rohitgr7** [comment]
> Alternatively, if both model and ckpt_path are passed, test() could load the checkpoint weights into the model. This would allow to test models structurally different from trainer.get_model(). This would be useful if I wanted to test many different models whose state_dict don't match - currently I would have to load the checkpoints manually and then pass the model to test().

@pbmstrk this is what I meant. If `ckpt_path != None` and model is passed, it should load the ckpt_path weights into the model. Yes, it can be done by explictly by loading the weights from ckpt_path manually but I suggest this should be changed. If ckpt_path is passed it should load regardless of the fact whether a model is passed or not.
