### ISSUE TITLE
on_epoch logging in validation_step appears to miss the data for the 1st epoch: Lightning 1.0.3

### ISSUE THREAD

**Issue by junwen-austin** [PyTorchLightning/pytorch-lightning#4398]
## 🐛 Bug

On_epoch logging in validation_step appears to miss the data for the 1st epoch. My epoch has 313 steps and therefore I expect the first on_epoch logging in validation_step should at step 312 (0-indexed), but I saw it was at step 625, the end of the 2nd epochs.

### To Reproduce

I have 4 GPUs and used DDP and the following validation_step:
```
def validation_step(batch, batch_idx):
    loss = self.forward(batch)
    self.log('loss/valid', loss, on_epoch=True, on_step=False, sync_dist=True, sync_dist__op='mean'
```
### Expected behavior
The first on_epoch logging should occur at the end of the first epoch, not the second.

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

* `IDE`: Please, use our python [bug_report_model.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
) template.

* `Colab Notebook`: Please copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py) (or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

 - PyTorch Version (e.g., 1.0):  1.4
 - OS (e.g., Linux):  Linux
 - How you installed PyTorch (`conda`, `pip`, source):   pip
 - Build command you used (if compiling from source):   
 - Python version:  3.7
 - CUDA/cuDNN version:   10.1
 - GPU models and configuration:
 - Any other relevant information:   PyTorch Lightning 1.0.3, 4 GPUs with DDP

**Comment by tchaton** [comment]
Hey @junwen-austin,

Would you mind trying again from master. I should be solved, but just in case.

Best regards,
T.C

**Comment by junwen-austin** [comment]
@tchaton Thanks I will try again and report back shortly.

**Comment by junwen-austin** [comment]
@tchaton  @Borda Yes I confirm that in the latest 1.0.7 release this has been fixed. Thanks.
