### ISSUE TITLE
Init model directly on GPU

### ISSUE THREAD

**Issue by chrismaliszewski** [PyTorchLightning/pytorch-lightning#4403]
Is it possible to initialize a model or move an initialized model to GPU without running a training? Can't find this information anywhere.

I'm using this code https://drive.google.com/file/d/1fOH-70fA2Yk4tVPh7-NTyxN9htMs1fYh/view?usp=sharing which is based on https://github.com/sksq96/pytorch-summary/blob/master/torchsummary/torchsummary.py with small changes I made to get model's summary. 

In the code, I check if GPU is available and set appropriate data type (cuda.Float or Float) for the data that is forwarded thought the model's structure. 

It looks a LightningModule model is initialized on CPU even if GPU is available which causes the problem:
```
Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
```
It isn't a big issue since I can set the appropriate device/data type on my own, but I'd like to be sure if it's possible to init model on a specific device.

**Comment by SkafteNicki** [comment]
`LightningModule` is just a `nn.Module` with extra functionality. To my understanding `nn.Module` is always initialized on cpu, and then the user can move to gpu using `.cuda()` method, which is also how you can move a `LightningModule` to gpu.

**Comment by chrismaliszewski** [comment]
Yeah, I think you're right. So there are two questions, I haven't tried them yet: 
a. how will ```LightningModule``` model behave if it's moved to GPU and, then, training runs? 
b. is it possible to determine on which device the model exists at the moment?
It's 12 PM my time; I'll try it tomorrow or, if you're interested yourself, could you check it?

**Comment by SkafteNicki** [comment]
a. If you move to gpu and then afterwards train on gpu then everything is fine. You will get a error if you have moved your model to gpu and try to train on cpu.
b. The device of a `LightningModule` can be access through `module.device`

**Comment by chrismaliszewski** [comment]
Great, thank you, @SkafteNicki! I think your comments answer the question.
