### ISSUE TITLE
Enable trainer val_check_interval to be greater than number of the training batches

### ISSUE THREAD

**Issue by Vozf** [PyTorchLightning/pytorch-lightning#4406]
Currently I can't set val_check_interval greater than number of the training batches
Error occurs
```
/site-packages/pytorch_lightning/trainer/data_loading.py", line 203, in reset_train_dataloader
    raise ValueError(
ValueError: `val_check_interval` (1000000) must be less than or equal to the number of the training batches (5). If you want to disable validation set `limit_val_batches` to 0.0 instead.
```
But it is a useful feature when validation takes considerate time. I want to do validation after multiple train epochs(but fixed number of steps, so I can't use `check_val_every_n_epoch`)

cc @borda @tchaton @justusschock @awaelchli

**Comment by justusschock** [comment]
This would probably require #4086 first, right?

**Comment by Vozf** [comment]
Yeah, seems like so

**Comment by gamerDecathlete** [comment]
Has this issue been resolved? I'm using the latest version of pylightning and I seem to get this error when my number of training batches are less than my val_check_interval
