### ISSUE TITLE
Metrics inside a dictionary are not properly moved to GPU

### ISSUE THREAD

**Issue by NumesSanguis** [PyTorchLightning/pytorch-lightning#4408]
## 🐛 Bug

The following code WORKS:
```
self.accuracy = Accuracy()
```
The following code DOES NOT WORK (throws CPU error):
```
self.metrics['accuracy'] = Accuracy()
```

## Please reproduce using [the BoringModel and post here](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing)

https://colab.research.google.com/drive/1oLE2Ts4AkQwd2oLSaz8qNvFdiygyvgrZ?usp=sharing

### Expected behavior

Move metric to proper device (GPU) whether assigned to `self.some_metrics` or `self.all_metrics['some_metric']`

### Actual behavior
```python
--> 113         self.correct += torch.sum(preds == target)

RuntimeError: Trying to pass too many CPU scalars to CUDA kernel!
```

### Environment
COLLAB
* CUDA:
	- GPU:
		- Tesla P100-PCIE-16GB
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0+cu101
	- pytorch-lightning: 1.0.4
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

### Additional context

I put the Metrics in a dict, so I can use the following code:
```python
for metric_name, metric in self.metrics.items():
    self.log(f"{metric_name}/{phase}_step", metric(predictions, targets))
```

**Comment by awaelchli** [comment]
You should use `torch.nn.ModuleList `or `torch.nn.ModuleDict`
This is not a PL issue. Torch does not detect submodules in lists and dicts.

**Comment by NumesSanguis** [comment]
Thanks, that was indeed the issue!
