### ISSUE TITLE
Remove check_val_every_n_epoch

### ISSUE THREAD

**Issue by tadejsv** [PyTorchLightning/pytorch-lightning#4409]
## 🚀 Feature

I think `check_val_every_n_epoch` trainer flag should be removed: `val_check_interval` already contains* all of its functionality.

\* The only thing needed would be to interpret `val_check_interval=2.0` as check every two epochs. This is just a straightforward extension of the current functionality

**Comment by rohitgr7** [comment]
Nice!
Somewhat connected to https://github.com/PyTorchLightning/pytorch-lightning/issues/4406

maybe when we can have 1.1, 1.2, ... all possible int/float values.

**Comment by turian** [comment]
Related to this discussion: https://github.com/PyTorchLightning/pytorch-lightning/discussions/6253
