### ISSUE TITLE
Batch size finder fails in DDP mode

### ISSUE THREAD

**Issue by maxjeblick** [PyTorchLightning/pytorch-lightning#4424]
## 🐛 Bug

The batch size finder fails in DDP mode, as `os.remove` is [called](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/tuner/batch_size_scaling.py#L113) from each process trying to load and delete the same model checkpoint.
The batch size finder works if the `os.remove` line is commented out (leaving the temporary checkpoint).

### To Reproduce

Run` trainer.tune()` in DDP mode.

### Environment

* CUDA:
	- GPU:
		- Tesla V100-SXM2-16GB
		- Tesla V100-SXM2-16GB
		- Tesla V100-SXM2-16GB
		- Tesla V100-SXM2-16GB
	- available:         True
	- version:           10.2
* Packages:
	- numpy:             1.19.3
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0
	- pytorch-lightning: 1.0.4
	- tqdm:              4.51.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.6.9
	- version:           #25~18.04.1-Ubuntu SMP Fri Jun 5 15:18:30 UTC 2020

**Comment by SkafteNicki** [comment]
Maybe we could add the `rank_zero_only` decorator to the call?
https://github.com/PyTorchLightning/pytorch-lightning/blob/f76bc5254e4ca5591a240aa19c8e3c5180d247df/pytorch_lightning/utilities/distributed.py#L30-L41

**Comment by ClaartjeBarkhof** [comment]
I get the same error:
```
    os.remove(save_path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cbarkhof/code-thesis/NewsVAE/temp_model.ckpt'
```

**Comment by rohitgr7** [comment]
isn't running batch size finder on DDP a bit weird. I mean it just tells you the batch size to use and one can get that while running on a single gpu too and with ddp it's just using the same batch_size on all the devices.

or am I missing something here?

**Comment by maxjeblick** [comment]
Yes, it's ideally running on a single GPU, only. Currently, I run `trainer.tune` on a single GPU, and then run `trainer.fit ` afterwards with the batch size obtained.

**Comment by ananthsub** [comment]
a separate bug here is that the tuner should use `fsspec` to work with remote file paths

**Comment by edenlightning** [comment]
Maybe we can add a warning here, to move to one GPU? thoughts?

**Comment by maxjeblick** [comment]
Fixed by https://github.com/PyTorchLightning/pytorch-lightning/pull/4458
