### ISSUE TITLE
In 1.0.4, training_step is never called when optimizer_step is overriden

### ISSUE THREAD

**Issue by catalys1** [PyTorchLightning/pytorch-lightning#4447]
## 🐛 Bug

Something changed from `1.0.3` to `1.0.4`: in `1.0.3` I was able to override `optimizer_step` in my LightningModule and everything worked fine. But in `1.0.4`, when I override `optimizer_step` it causes `training_step` to be skipped.

## Please reproduce using [the BoringModel and post here](https://colab.research.google.com/drive/19BSV_Hesf2x2c4yHVI9n8WUlIRl9F7w2?usp=sharing)

[BoringModel replication](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing)

### Expected behavior

Defining `optimizer_step` should not cause `training_step` to be skipped over. This is definitely a problem.

**Comment by jwspaeth** [comment]
Also ran into this bug. Fixed in my case by passing optimizer.step the optimizer_closure, as they do in LightningModule [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/9cfd29946a308526cee088c176a2285e6752453c/pytorch_lightning/core/lightning.py#L1216).

**Comment by catalys1** [comment]
Thanks, that seems to be working. If this is going to be the required way of handling it (unlike in previous releases) then I think it needs to be clearly pointed out in the documentation. Otherwise, hopefully it can be fixed before the next maintenance update.

**Comment by ananyahjha93** [comment]
yes, I think the docs are a bit old, I am updating them in the fix. Apart from that just making sure that passing optimizer_closure is the only issue here.

**Comment by edenlightning** [comment]
@SeanNaren please update what is left TODO here

**Comment by SeanNaren** [comment]
This should be closed, the docs have been cleared up in #4455, ensuring that users know to pass the optimizer_closure to the optimizer.
