### ISSUE TITLE
Training_step outputs not propagated

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#4452]
cc @ananthsub @awaelchli @justusschock
Hi, after updating to version 1.0.4,  i think  below approach seems to be not working as desired

```
def training_step(...):
    return {'loss': loss, 'random_thing': [1, 'a', Tensor(), ...]}

def training_epoch_end(self, training_step_outputs):
    for d in training_step_outputs:
        random_thing = d['random_thing']
```
    
`training_step_outputs` is always empty. On further debugging i find that `training_step` is never getting called, instead this function `training_step_and_backward` is called within `run_training_batch`

Any help appreciated and also apologies if i am making any mistake

_Originally posted by @nazim1021 in https://github.com/PyTorchLightning/pytorch-lightning/pull/3681#issuecomment-719849781_

**Comment by nazim1021** [comment]
Hi @edenlightning , so  I tried to replicate the issue on cifar10 dataset in this cpcv2 based training,  here is boring model - https://colab.research.google.com/drive/1a0svxoAVuPAJTk0QcxHKwzC25DDSjID4?usp=sharing

However, currently, it seems to working fine. Don't see any error.

On my task,  I have exact same model, only the dataset differs, and am running it through command line,  but it always seems to give this error -   
```
File "classifier.py", line 166, in training_epoch_end
    train_loss_mean = torch.stack([output['loss']
RuntimeError: stack expects a non-empty TensorList
```
as a result, on debugging this further, i came to the doubt of training step outputs not being propagated. Apologies for the mistake.

I am still not sure why the behaviour is different, I have also observed difference in training speed, (I had kept same number of samples and trainer configs in boring setup as that in my personal dataset task).

**Comment by ananyahjha93** [comment]
@edenlightning @nazim1021 I have the error replicated, related to #4447. With a custom optimizer_step override, if you pass optimizer.step() instead of optimizer.step(optimizer_closure), then the training_step_outputs are empty.

**Comment by nazim1021** [comment]
@ananyahjha93  oh i see, but i think i am not using any custom optimizer_step, Maybe i need to debug little further

**Comment by nazim1021** [comment]
Hi @ananyahjha93  i think your point helped me figured out the bug, i had custom optimizer, like instead of inbuilt Adam, i had an implementation of Ranger optimizer, so on this i think the optimizer_closure may not be getting applied.

**Comment by ananyahjha93** [comment]
@nazim1021 if you are inheriting Optimizer class now, the step has to take in a closure param.

https://pytorch.org/docs/stable/_modules/torch/optim/optimizer.html#Optimizer

**Comment by nazim1021** [comment]
oh i see, i ll need to double check the ranger implementation, but i i guess,  i ll need to override optimizer_step as well

**Comment by justusschock** [comment]
to accept a closure while retaining the current behaviour, the easiest way is to just call the closure beforehand like this:

```python
def step(closure: Callable):
    _ = closure()
    ... # whatever your step does here
```
