### ISSUE TITLE
Is there a way to supress all printing and warnings in the Trainer?

### ISSUE THREAD

**Issue by erap129** [PyTorchLightning/pytorch-lightning#4462]
Hello,  
I am aware of the `progress_bar_refresh_rate` and `weight_summary` parameters, but even when I disable them I get these GPU warning-like messages:  
![image](https://user-images.githubusercontent.com/30405025/97796547-d947fb00-1c1b-11eb-903b-194a8cffcbad.png)
I would like to disable all warnings and printings from the Trainer, is this possible?  
Why? because I want to perform several training operations in a loop and monitor them with tqdm, so intermediate printing will ruin the tqdm progress bar.

**Comment by ydcjeff** [comment]
@erap129 See: https://pytorch-lightning.readthedocs.io/en/0.9.0/experiment_reporting.html#configure-console-logging

**Comment by amin-nejad** [comment]
New stable link: https://pytorch-lightning.readthedocs.io/en/stable/extensions/logging.html#configure-console-logging

**Comment by daniilino** [comment]
Both snippets from above links are not working :(

**Comment by jarun-title** [comment]
```
import logging
logging.getLogger("pytorch_lightning").setLevel(logging.WARNING)
```

This snippet should work.

**Comment by turbotimon** [comment]
To make it short for everyone looking for the answer:

For the *old* lightning:

```python
import pytorch_lightning
import logging
logging.getLogger("pytorch_lightning").setLevel(logging.ERROR)
```

For the *new* lightning
```python
import lightning
import logging
logging.getLogger("lightning.pytorch").setLevel(logging.ERROR)
```
