### ISSUE TITLE
refactor: Remove unused `tmpdir` in tests

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning#4463]
## 🚀 Feature (Refactoring)
`tmpdir` fixture provided by [pytest](https://docs.pytest.org/en/stable/tmpdir.html#the-tmpdir-fixture) is used at some places in the tests. However, not all `tmpdir` references are not actually used.

### Example
Below is one example of unnecessary `tmpdir`.
https://github.com/PyTorchLightning/pytorch-lightning/blob/839813eb7be1fbc614859db5086d6ed0d7fd3340/tests/core/test_datamodules.py#L104-L107

I'd be happy to submit a PR once you find it reasonable!

**Comment by rohitgr7** [comment]
I think we should keep it as it is. Sometimes we update tests and need this. It doesn't affect the tests right?

**Comment by akihironitta** [comment]
@rohitgr7 Sure. It does not affect the tests at all!
