### ISSUE TITLE
SIGSEGV when training on TPU

### ISSUE THREAD

**Issue by FabianBell** [PyTorchLightning/pytorch-lightning#4464]
### Before asking: 
1. Try to find answers to your questions in [the Lightning Forum!](https://forums.pytorchlightning.ai/)
2. Search for similar [issues](https://github.com/PyTorchLightning/pytorch-lightning/issues).   
3. Search the [docs](https://pytorch-lightning.readthedocs.io/en/latest/).    

#### What is your question?

I tried to apply the reformer model on a sentiment analysis task and train it on a tpu. I get a 
```
ProcessExitedException: process X terminated with signal SIGSEGV
```
What did I do wrong?

#### Code

   
You can find my code in a colab notebook [here](https://colab.research.google.com/drive/1k9ep7EhZPj3ihBuGEB02Ec2h_osMtopp?usp=sharing).

#### What have you tried?

I tried to stick to [notebook 1](https://colab.research.google.com/drive/1qnWIoIcO41sne48XGjb75uuuGRTtnxC1?usp=sharing#scrollTo=2Iz8dSUloqCy) for the general setup and [notebook 2](https://colab.research.google.com/drive/1-_LKx4HwAxl5M6xPJmqAAu444LTDQoa3) for the tpu setup. I saw #1956 and #2124 however it does not work with the latest version (1.0.4).

#### What's your environment?

 - OS: [e.g. iOS, Linux, Win] Linux
 - Packaging [e.g. pip, conda] pip
 - Version [e.g. 0.5.2.1] 1.0.4

**Comment by rohitgr7** [comment]
cc @lezwon

**Comment by lezwon** [comment]
This seems to be an XLA issue and is tracked here https://github.com/pytorch/xla/issues/1775

@FabianBell Mind adding the following at the beginning of your notebook and trying?
```python
import os
os.environ['XLA_USE_32BIT_LONG'] = '1'
os.environ['TRIM_GRAPH_SIZE'] = '1000000'
```

**Comment by FabianBell** [comment]
@lezwon thank you for your help.

I changed the notebook but I still get the same error.

**Comment by lezwon** [comment]
I get a different error: [Notebook](https://colab.research.google.com/drive/16rcPEyF-1Ok5zKIFyXmjtf35NekSyco1?usp=sharing)

`RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got XLAIntType instead (while checking arguments for embedding)`

Will look into this.

**Comment by lezwon** [comment]
@FabianBell I'm not able to figure out the root cause of the error mentioned above. I think it might be similar to this one: https://github.com/huggingface/transformers/issues/2952

**Comment by FabianBell** [comment]
@lezwon thank you for your help. I followed [notebook](https://colab.research.google.com/github/pytorch/xla/blob/master/contrib/colab/multi-core-alexnet-fashion-mnist.ipynb) and I ended up with the same error. I do not think that it is a pytorch lightning problem. I will therefore close this issue here.
