### ISSUE TITLE
How to save the latest and best checkpoint?

### ISSUE THREAD

**Issue by xiadingZ** [PyTorchLightning/pytorch-lightning#4465]
I can set a checkpoing callback to save best model, but I also want it save the latest model, so that i can `resume_from_checkpoint` from latest checkpoint. how to do this?

**Comment by ydcjeff** [comment]
@xiadingZ  There is `save_last` parameter in ModelCheckpoint that saves the last epoch

**Comment by xiadingZ** [comment]
Thanks
