### ISSUE TITLE
ModelCheckpoint filenames and metric names containing / (slash)

### ISSUE THREAD

**Issue by EliaCereda** [PyTorchLightning/pytorch-lightning#4468]
## 🐛 Bug
The current behaviour of `ModelCheckpoint` is problematic when the checkpoint's name includes a metric whose name contains a slash character.

Since the implementation always includes the name of the metric along with its value, a format specifier like `{some/name}` results in the checkpoint being stored in a subdirectory. Everything appears to work correctly apart from the inconvenience of having a subdirectory which is not deleted when deleting old checkpoints. 

## Reproducer
https://colab.research.google.com/drive/1E4EKc2Ndt4XluRjpGC83hyohyF0BQESU?usp=sharing

The two lines marked as `# STEP 1: ...` and `# STEP 2: ...` are sufficient to reproduce the issue, the checkpoints are stored in `lightning_logs/version_0/checkpoints`.

### Expected behavior

I haven't found a way to avoid this problem, because the substitution from `{metric}` to `metric=value` is hardcoded in PyTorch Lightning code.

I don't particularly care about the specific name of my checkpoints, so I'd propose for PL to automatically escape the slashes to some other character. Alternatively, PL should provide a way to manually specify a different name for the metric in the filename or a way to suppress the name altoghether.

### Environment

* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0+cu101
	- pytorch-lightning: 1.0.4
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

### Additional context

Supporting metrics with a slash in the name is desirable for me because `wandb` then automatically groups them in the dashboard.

**Comment by rohitgr7** [comment]
duplicate #4012??

**Comment by EliaCereda** [comment]
Yes, it is. Don't know how I could not find it in my search, sorry for the duplicate.

**Comment by rohitgr7** [comment]
@EliaCereda btw do you have any suggestions here on how to handle this?

**Comment by EliaCereda** [comment]
I left a comment in the original issue ;)
