### ISSUE TITLE
Multiple GPU/TPU support?

### ISSUE THREAD

**Issue by jhuang265** [PyTorchLightning/pytorch-lightning#4470]
I'm working on a project where we want to try using pytorch-lightning to run rerankers on multiple GPU/TPUs. I can't seem to find any direct information if this is possible, as [this link](https://pytorch-lightning.readthedocs.io/en/stable/tpu.html) seems to only indicate that it can run on TPUs but without any information as to whether it is possible to run on multiple ones.

#### Environment

 - OS: Linux
 - Packaging: pip
 - Version: 9.03

**Comment by ydcjeff** [comment]
Lightning supports multiple GPUs/TPUs.
Just change `gpus` or `tpu_cores` to the amount you want to use

**Comment by tchaton** [comment]
Hey @jhuang265,

`tpu_cores: How many TPU cores to train on (1 or 8) / Single TPU to train on [1]`

I am updating the doc to make it more clear :)

Best,
T.C
