### ISSUE TITLE
import pytorch_lightning as pl:  Segmentation fault (core dump)

### ISSUE THREAD

**Issue by SCRIER-org** [PyTorchLightning/pytorch-lightning#4472]
Pytorch_lightning immediately segfaults upon loading at the first executable line in the file:
`import pytorch_lightning as pl`
apparently it's doing this upon attempting to load `/opt/anaconda3/lib/python3.8/site-packages/torchtext/_torchtext.so`, which exists and is not protected, after _not_ crashing when it loaded `/opt/anaconda3/lib/python3.8/site-packages/torchvision/_C.so`.  It seems to be crashing at file:line `/opt/anaconda3/lib/python3.8/ctypes/__init__.py:373`  which is 

`        if handle is None:
            self._handle = _dlopen(self._name, mode)
`
inside the __init__ function of class object CDLL(), called from _Ops.load_library(  ) at file:line `/opt/anaconda3/lib/python3.8/site-packages/torch/_ops.py:105` with 
`        with dl_open_guard():
            # Import the shared library into the process, thus running its
            # static (global) initialization code in order to register custom
            # operators with the JIT.
            ctypes.CDLL(path)
`

I have no idea what's going on here.

sys.platform is "linux"
machine is running Lubuntu 20.04 with an AMD Ryzen 7 processor and single GeForce GTX 1660-Ti GPU
Python 3.8.3
nvcc: Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
NVIDIA Driver Version: 450.80.02

lightning had this issue both times when using the **standard pip** version:
`pip install pytorch-lightning
Downloading pytorch_lightning-1.0.4-py3-none-any.whl (554 kB)`
[double-check: `pip install pytorch-lightning
Requirement already satisfied: pytorch-lightning in /opt/anaconda3/lib/python3.8/site-packages (1.0.4)` ]

 and the **development** version:
`pip install git+https://github.com/PytorchLightning/pytorch-lightning.git@master --upgrade
Building wheels for collected packages: pytorch-lightning
  Building wheel for pytorch-lightning (PEP 517) ... done
  Created wheel for pytorch-lightning: filename=pytorch_lightning-1.0.4-py3-none-any.whl size=563410 
Successfully built pytorch-lightning
Installing collected packages: pytorch-lightning
  Attempting uninstall: pytorch-lightning
    Found existing installation: pytorch-lightning 1.0.4
    Uninstalling pytorch-lightning-1.0.4:
      Successfully uninstalled pytorch-lightning-1.0.4
Successfully installed pytorch-lightning-1.0.4
`
best tentative guess is machine has perhaps somehow been locked down with some kind of tight security such as systemctl / ufw, and maybe it's not letting a forked python process access the disk?  But this really wouldn't make much sense, as everything's on /opt.  Second best guess is torchtext.so needs some kind of fixing... 

this is a showstopper on NeMo.

**Comment by s-rog** [comment]
This is an env issue with the underlying torch libraries and not lightning.

torch, torchvision, torchtext all have to installed correctly with versions compatible with each other as well as your system driver and cuda version.

If you do find that it is a lightning specific issue, feel free to re-open!

For more help checkout our forums: https://forums.pytorchlightning.ai/

**Comment by RemonComputer** [comment]
I had the same issue, and it was solved after I installed torchtext package
```
conda install -c pytorch torchtext
```

**Comment by jxmorris12** [comment]
I ran into this same issue, and fixed it by updating torch under the hood:
```bash
conda install pytorch torchvision torchaudio -c pytorch
```

**Comment by bstee615** [comment]
> I ran into this same issue, and fixed it by updating torch under the hood:
> 
> ```shell
> conda install pytorch torchvision torchaudio -c pytorch
> ```

Run this even if you think you have the correct version. I had accidentally installed the CPU version of torchvision and this fixed it.

From the output of `conda install`:
```shell
The following packages will be SUPERSEDED by a higher-priority channel:

  torchvision        conda-forge::torchvision-0.12.0-cpu_p~ --> pytorch::torchvision-0.12.0-py39_cu102
```

**Comment by hoangthangta** [comment]
In my case, I fix the error by using these commands:

```
python3 -m pip install pytorch 
python3 -m pip install torchvision 
python3 -m pip install torchaudio 
```

**Comment by sonsus** [comment]
Shouldn't it be warned before just spitting core dump?

**Comment by ochen1** [comment]
In case anyone else is having this issue nearly two years later, you can also try updating the `protobuf` library. This was suggested [here](https://discuss.pytorch.org/t/seg-fault-with-pytorch-lightning/140973) and worked for me.
