### ISSUE TITLE
Allow Trainer to accept dictionary as input?

### ISSUE THREAD

**Issue by cheulyop** [PyTorchLightning/pytorch-lightning#4473]
I searched issues and the forum but couldn't find anyone who mentioned this, so here I'm asking: can we allow Trainer to accept dictionaries as an input argument?

This came up as I'm writing a script to run experiments under various configurations. For each experiment, I'm passing a configuration file (in JSON) into an experiment runner which builds callbacks, Trainer, and models internally. At the moment, I'm doing something that looks like:

```
trainer = pl.Trainer(
                gpus                = config.trainer.gpus,
                auto_select_gpus    = config.trainer.auto_select_gpus,
                precision           = config.trainer.precision,
                deterministic       = config.trainer.deterministic,
                max_epochs          = config.trainer.max_epochs,
                auto_lr_find        = config.trainer.auto_lr_find,
                gradient_clip_val   = config.trainer.gradient_clip_val,
                logger              = logger,
                callbacks           = callbacks,
            )
```
However, I would like to be able to do:

```
trainer = pl.Trainer(config.trainer)
```
I think running experiments would be so much more flexible this way unless there is a technical reason that prevents this from happening.

**Comment by s-rog** [comment]
trainer currently supports namespace/argparse, check out:
https://pytorch-lightning.readthedocs.io/en/stable/trainer.html#trainer-in-python-scripts

**Comment by cheulyop** [comment]
Sure, I can certainly convert dict to argparse namespace like this:
```
trainer_params = {
        # some params
    }

    parser = Trainer.add_argparse_args(argparse.ArgumentParser())
    args = parser.parse_args()
    vars(args).update(trainer_params)
    Trainer.from_argparse_args(args)
```
But this looks unnecessarily complicated. There should be an easier/cleaner way to do this? I just can't find one upfront.

**Comment by ydcjeff** [comment]
@cheulyop is config.trainer a dict type?

**Comment by cheulyop** [comment]
@ydcjeff when I opened this issue, I thought it should be. But thinking of it now, it doesn't have to be? 

Actually, in my code, `config` is a dict of dicts, such as `experiment, data, early_stop, trainer`, and `hparams`. I store config as json and load it with a hook converting dicts and their values into an object, i.e., namespace.

If it is namespace, I suppose the whole thing can be as simple as `Trainer.from_argparse_args(config.trainer)`.

I don't think the documentation is very clear about this, neither the name `from_argparse_args` :/

**Comment by ydcjeff** [comment]
If config.trainer is a dict, you could use double asterisk, right?

**Comment by cheulyop** [comment]
@ydcjeff yes you can do `Namespace(**config.trainer)`

**Comment by ydcjeff** [comment]
How about in this? `pl.Trainer(**config.trainer)` that can be used too?

**Comment by cheulyop** [comment]
Yes that works as well 👍

**Comment by ydcjeff** [comment]
Thank you for confirming!

Closing it as it is resolved, feel free to reopen if needed
