### ISSUE TITLE
Validation step is skipped when on_train_batch_start returns -1

### ISSUE THREAD

**Issue by nicola-decao** [PyTorchLightning/pytorch-lightning#4481]
## 🐛 Bug

It seems that when `on_train_batch_start` returns `-1` the validation step is skipped.

### Expected behavior

The trainer should skip the training epoch and start the evaluation.

```
 - pytorch-lightning version 1.0.4
 - PyTorch Version (e.g., 1.0): 1.7
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.7
```

**Comment by ydcjeff** [comment]
Yes, this is the correct behavior as described in the docs: `If you return -1 here, you will skip training for the rest of the current epoch.` one epoch includes training + validation, so it will skip validation step as well

**Comment by nicola-decao** [comment]
> Yes, this is the correct behavior as described in the docs: `If you return -1 here, you will skip training for the rest of the current epoch.` one epoch includes training + validation, so it will skip validation step as well

I understand `.. you will skip training for the rest of the current epoch.` as is written in documentation as only training is skipped. Yes, I want to only skip training. I think either the expected behavior of this `-1` is wrong or the documentation is wrong. Is there any way to only skip training?

**Comment by ydcjeff** [comment]
I see! yep, docs can be improved!
you can now return `None` in training_step to skip the training_step
See Returns Section in https://pytorch-lightning.readthedocs.io/en/latest/lightning_module.html#training-step

**Comment by nicola-decao** [comment]
> I see! yep, docs can be improved!
> you can now return `None` in training_step to skip the training_step
> See Returns Section in https://pytorch-lightning.readthedocs.io/en/latest/lightning_module.html#training-step

Right! But I have a stop criterion that is satisfied, I need to save it in a variable and the trainer will still loop over all batches that will be skipped. It seems more natural to do have a mechanism to skip the training entirely from a hook. Otherwise, the loop will be quite a waste of time/computation.

**Comment by ydcjeff** [comment]
Thank you for your feedback @nicola-decao 
noted the feature to implement when applicable
```
UserWarning: training_step returned None if it was on purpose, ignore this warning...
```
Most of us normally don't skip the training batch, so it's just notifying that user is skipping on purpose.

**Comment by zrqiao** [comment]
Hi developers! I wonder if there is a feature implemented to skip the training epoch only?
