### ISSUE TITLE
Videos in the documentation quality change for lower speed connections

### ISSUE THREAD

**Issue by asalimih** [PyTorchLightning/pytorch-lightning#4519]
## 🚀 Feature
adding the option to change the quality of the tutorial videos in the documentation page.

### Motivation
the videos inside the documentation seem very useful however every time I try to watch them I can't because they have a high quality and my internet access can't load it in the proper time.

### Alternatives
Simply upload them on Youtube

**Comment by kaushikb11** [comment]
The videos have been compressed and updated! Closing the issue.
