### ISSUE TITLE
Metrics ConfusionMatrix is not under this path: pytorch_lightning.metrics.classification.ConfusionMatrix

### ISSUE THREAD

**Issue by lzrpotato** [PyTorchLightning/pytorch-lightning#4520]
#### What is your question?
Metrics ConfusionMatrix is not under this path: pytorch_lightning.metrics.classification.ConfusionMatrix
Is the ConfusionMatrix removed from pytorch_lightning?
Refer to the following link in docs:
https://pytorch-lightning.readthedocs.io/en/latest/metrics.html#confusionmatrix

#### Code
```python
from pytorch_lightning.metrics import ConfusionMatrix
from pytorch_lightning.metrics.classification import ConfusionMatrix
```

The above code cannot import ConfusionMatrix.

#### What's your environment?

 - OS: Linux
 - Packaging: pip
 - Version: 1.0.5

**Comment by lzrpotato** [comment]
https://github.com/PyTorchLightning/pytorch-lightning/blob/e0b856c105d3c35df8d53f737762f88ae68ee1e3/pytorch_lightning/metrics/classification/confusion_matrix.py

The confusion_matrix.py file is on the repository, but it seems that this file hasn't been merged to version 1.0.5.

**Comment by SeanNaren** [comment]
Hey @lzrpotato you are correct, seems like it didn't make its way into 1.0.5 (here is the PR with the updated changelog: https://github.com/PyTorchLightning/pytorch-lightning/blob/137524402ebbe32a18e579d09f4845630b198880/CHANGELOG.md) I'll double check internally whether this is going to be in a point release or major.

**Comment by SeanNaren** [comment]
Can confirm, will be in 1.1. Apologies! was mis-classified, will close this for now but let me know if you run into any issues :)
