### ISSUE TITLE
save_hyperparameters() doesn't work with decorated __init__()

### ISSUE THREAD

**Issue by kittipatv** [PyTorchLightning/pytorch-lightning#4525]
## 🐛 Bug

save_hyperparameters() breaks when __init__() is decorated

https://colab.research.google.com/drive/1njXP32G3FSg4nWvwo7kuhVr6iqH3eabQ?usp=sharing

### Expected behavior

hyperparameters should be saved

### Environment

```
* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0+cu101
	- pytorch-lightning: 1.0.0
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020
```

### Additional context

I think the right way to detect parameters is using `inspect.signature(cls.__init__).parameters` instead of `inspect.getfullargspec(Reinforce.__init__)`. `signature()` does cooperate with `functools.wraps()`. You can use `kind` attribute on Parameter object to detect the variable positional & keyword arguments.

**Comment by Borda** [comment]
@kittipatv just curious what is the use-case you want to apply a decorator to model?
