### ISSUE TITLE
self.log with Metric in ddp

### ISSUE THREAD

**Issue by Maybewuss** [PyTorchLightning/pytorch-lightning#4529]
```python
def validation_epoch_end(self, outputs):
    self.log('metric', self.metric.compute()) # rank = 0

def validation_epoch_end(self, outputs):
    out = self.metric.compute()
    self.log('metric', out) # rank =0

def validation_epoch_end(self, outputs):
    if self.global_rank == 0:
        out = self.metric.compute()
        self.log('metric', out) # rank =0
    dist.barrier()
```

> global_rank
The global_rank of this LightningModule. Lightning saves logs, weights etc only from global_rank = 0. You normally do not need to use this property
Global rank refers to the index of that GPU across ALL GPUs. For example, if using 10 machines, each with 4 GPUs, the 4th GPU on the 10th machine has global_rank = 39
>
As the doc says, self.log will be call when global_rank = 0, but metric.compute will auto call self.reset().
So which example will work correctly?

**Comment by Maybewuss** [comment]
>
The global_rank of this LightningModule. Lightning saves logs, weights etc only from global_rank = 0. You normally do not need to use this property
>
Besides, I want to know Lightning whether use dist.barrier() when saving log or checkpoint etc from global_rank = 0?

**Comment by Maybewuss** [comment]
```python
def rank_zero_only(fn):

    @wraps(fn)
    def wrapped_fn(*args, **kwargs):
        if rank_zero_only.rank == 0:
            return fn(*args, **kwargs)

    return wrapped_fn
```
The decorator does not use dist.barrier()

**Comment by SkafteNicki** [comment]
If you are asking which of the three methods correctly logs the metric value, I see no problem with any of them (case 1 and 2 are identical). The recommended way is to just call `self.log("metric", self.metric, on_epoch=True)`.
I don't think we have a explicit barrier before saving log or checkpoints, but `dist.barrier()` is called every time `metric.compute()` is explicitly called.

**Comment by Maybewuss** [comment]
> If you are asking which of the three methods correctly logs the metric value, I see no problem with any of them (case 1 and 2 are identical). The recommended way is to just call `self.log("metric", self.metric, on_epoch=True)`.
> 
> I don't think we have a explicit barrier before saving log or checkpoints, but `dist.barrier()` is called every time `metric.compute()` is explicitly called.  

I think case2 may cause bug in ddp because metric.compute will reset the metric and it will be call in all processes.

**Comment by SkafteNicki** [comment]
> I think case2 may cause bug in ddp because metric.compute will reset the metric and it will be call in all processes.

I don't follow why that should give a bug.
Do you have code to reproduce?

**Comment by Maybewuss** [comment]
> > I think case2 may cause bug in ddp because metric.compute will reset the metric and it will be call in all processes.
> 
> I don't follow why that should give a bug.
> Do you have code to reproduce?

Because self.log will be used only in one process(global_rank=0), but validation_epoch_end will be executed in all process. 
And Metric.compute() will reset metric.
So if i have 4 process, if process 1 execute validation_epoch_end earlier than process 0, values in metric will be reset, when process 0 execute self.log, it will return wrong results. Is there a problem with what i think?

**Comment by SkafteNicki** [comment]
I don't think so. As I described earlier, when `metric.compute()` is called the different processes will sync, such that we get the correct result. Additionally, this computed value is stored in a internal cache which means that no matter how many times compute is called after the first compute (but before any update is called) the process will return the already computed result.
```
val = self.metric().compute() # states are reset, but computed value is cashed
val2 = self.metric() # return computed cashed value
print(val==val2) # True
self.metric.update(...) # update states, computed cashed value will be set to None
```

**Comment by Maybewuss** [comment]
> I don't think so. As I described earlier, when `metric.compute()` is called the different processes will sync, such that we get the correct result. Additionally, this computed value is stored in a internal cache which means that no matter how many times compute is called after the first compute (but before any update is called) the process will return the already computed result.
> 
> ```
> val = self.metric().compute() # states are reset, but computed value is cashed
> val2 = self.metric() # return computed cashed value
> print(val==val2) # True
> self.metric.update(...) # update states, computed cashed value will be set to None
> ```

Cool design! Is there such a situation that process 1 execute metric.compute() first and execute metric.update() in validation_step before process 0 execute metric.compute....

**Comment by SkafteNicki** [comment]
Each process have individual metric states and are only synced on `compute()`. This means, that even if process 1 executes `metric.update` before process 0 is done logging the result from `metric.compute()`, the `update` method will only influence the state of the metric at process 1, thus process 0 should still log the correct result.

**Comment by Maybewuss** [comment]
> This means, that even if process 1 executes metric.update before process 0 is done logging the result from metric.compute(),  the update method will only influence the state of the metric at process 1, thus process 0 should still log the correct result.

Why process 0 should log the correct result? As you say metric.compute will sync and correctly the state of metric at process1 had been changed.
