### ISSUE TITLE
undefined symbol when importing PyTorch Lightning after installing XLA

### ISSUE THREAD

**Issue by clementpoiret** [PyTorchLightning/pytorch-lightning#4533]
## 🐛 Bug

Following the doc, in order to use TPU on colab pro, I can't import PyTorch Lightning after installing XLA:
`ImportError: /usr/local/lib/python3.6/dist-packages/_XLAC.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at13nanmedian_outERNS_6TensorES1_RKS0_lb`

### To Reproduce
[https://colab.research.google.com/drive/1dv21HCCIMdv2r9iSqSRpeOmOJ7Hh8TXF?usp=sharing](https://colab.research.google.com/drive/1dv21HCCIMdv2r9iSqSRpeOmOJ7Hh8TXF?usp=sharing)

### Expected behavior

Well, I should be able to import pytorch_lightning I guess :)
It worked few days ago.
Installing pytorch_lightning before XLA leads to an error telling that XLA isn't installed when calling `trainer.fit`.

### Environment

 - PyTorch Version (e.g., 1.0): 1.7.0 & 1.8.0
 - OS (e.g., Linux): Linux (colab)
 - How you installed PyTorch (`conda`, `pip`, source): Already installed (colab)
 - Build command you used (if compiling from source): N/A
 - Python version: 3.6
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: TPU
 - Any other relevant information:

**Comment by clementpoiret** [comment]
Seems just a nightly issue, working well with torch XLA 1.7... Is there a specific purpose of using nightly builds as stated in PL's doc?

**Comment by Borda** [comment]
we want to get nightly back, just have not done yet after PT 1.7 release
cc: @zcain117

**Comment by diegovalenzuelaiturra** [comment]
A [specific version](https://github.com/pytorch/xla/blob/58ccf11c361e4ba2fd9d3829ca907c2d037657a1/contrib/scripts/env-setup.py#L3) can be specified like this :

```python3
VERSION = "1.7"

!curl "https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py" -o "pytorch-xla-env-setup.py"

%run pytorch-xla-env-setup.py  --version=$VERSION --apt-packages libomp5 libopenblas-dev
```

**Comment by kaushikb11** [comment]
```python
----> 9 import pytorch_lightning as pl
     10 from pytorch_lightning.metrics.functional import accuracy
     11 tmpdir = os.getcwd()

12 frames
/usr/local/lib/python3.7/dist-packages/torchtext/experimental/transforms.py in <module>()
      2 import torch.nn as nn
      3 from typing import List
----> 4 from torchtext._torchtext import RegexTokenizer as RegexTokenizerPybind
      5 from torch import Tensor
      6 from torchtext._torchtext import SentencePiece as SentencePiecePybind

ImportError: /usr/local/lib/python3.7/dist-packages/torchtext/_torchtext.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtERKSt10shared_ptrIS0_EPSo
```
Reopening the Issue. Following the instructions in the docs is throwing the above Error. Looking into it.

**Comment by tchaton** [comment]
Hey @kaushikb11,

It means torchtext wasn't compiled with the current torch version. If you uninstall and re-install it, everything should be fine.

Best,
T.C

**Comment by kaushikb11** [comment]
Noted!
Another way of installing Xla library, if anyone comes across this issue
```
!pip install cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.8-cp37-cp37m-linux_x86_64.whl
```
Closing the issue!

**Comment by peterukk** [comment]
I'm still getting the error (new Colab session, connected to TPU):

```
!pip install cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.8-cp37-cp37m-linux_x86_64.whl
!pip install pytorch-lightning
import pytorch_lightning as pl

```

```
WARNING:root:Waiting for TPU to be start up with version pytorch-1.8...
WARNING:root:Waiting for TPU to be start up with version pytorch-1.8...
WARNING:root:Waiting for TPU to be start up with version pytorch-1.8...
WARNING:root:TPU has started up successfully with version pytorch-1.8

---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)

<ipython-input-3-efd8697dde72> in <module>()
----> 1 import pytorch_lightning as pl

9 frames

/usr/local/lib/python3.7/dist-packages/torch_xla/__init__.py in <module>()
    126 import torch
    127 from ._patched_functions import _apply_patches
--> 128 import _XLAC
    129 
    130 

ImportError: /usr/local/lib/python3.7/dist-packages/_XLAC.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at11result_typeERKNS_6TensorEN3c106ScalarE
```

**Comment by brando90** [comment]
https://stackoverflow.com/questions/69229397/why-cant-torchtext-find-a-symbol/69229398#69229398
