### ISSUE TITLE
TypeError: unsupported format string passed to Tensor.__format__ during printing at validation stage

### ISSUE THREAD

**Issue by songwanguw** [PyTorchLightning/pytorch-lightning#4538]
## 🐛 Bug

I get error "TypeError: unsupported format string passed to Tensor.__format__". I suspect the code here need to be changed.

https://github.com/PyTorchLightning/pytorch-lightning/blob/51cc7a89ee9f1c0ad35c147ce37a5825ec6d77e5/pytorch_lightning/callbacks/model_checkpoint.py#L585

## Please reproduce using [the BoringModel and post here]

```
>>> import torch
>>> x = torch.Tensor([0])
>>> x
tensor([0.])
>>> type(x)
<class 'torch.Tensor'>
>>> y = torch.Tensor([1])
>>> f" {x:0.5f} (best {y:0.5f}),"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sonwang/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 419, in __format__
    return object.__format__(self, format_spec)
TypeError: unsupported format string passed to Tensor.__format__
>>> f" {x.item():0.5f} (best {y.item():0.5f}),"
' 0.00000 (best 1.00000),'
```

current, best_model_score in the code cited are both tensors, it will throw the same errors When I used the original code. 

Suggestd changes:

 rank_zero_info(
                f"Epoch {epoch:d}, global step {step:d}: {self.monitor} reached {current.item():0.5f}"
                f' (best {self.best_model_score.item():0.5f}), saving model to "{filepath}" as top {k}'
            )

**Comment by songwanguw** [comment]
https://github.com/songwanguw/pytorch-lightning/commit/1130bc44a763d8fe8f41f3416430acfb99e86d4c

**Comment by SeanNaren** [comment]
Are you able to reproduce the bug with this?

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py

This will help get a fix into master :)

**Comment by songwanguw** [comment]
@SeanNaren Thanks for pointing me to the script.  I was not able to reproduce the errors. I found there is no bug here. 

"current" is a torch.Tensor and scaler (`shape == torch.Size([]`) 

It is my mistake by confusing torch.Tensor() and torch.tensor().

```
>>>import torch
>>> x = torch.Tensor(1)
>>> print(f"{x:0.5f}")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sonwang/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 419, in __format__
    return object.__format__(self, format_spec)
TypeError: unsupported format string passed to Tensor.__format__
>>> x = torch.tensor(1)
>>> print(f"{x:0.5f}")
1.00000
>>> x.shape
torch.Size([])
```
