### ISSUE TITLE
Existing logger conflict with lr_finder

### ISSUE THREAD

**Issue by zippeurfou** [PyTorchLightning/pytorch-lightning#4540]
## 🐛 Bug

If you call specific logger function (ie. `add_histogram` on a tensorboard one). The tuner will fails because it overwrite it with a DummyLogger (https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/tuner/lr_finder.py#L150).
I would expect to not have to check if the logger I initiated in my trainer is being overwritten or not.
Additionally, on a minor minor note. I wouldn't expect `progress_bar_refresh_rate` to be overwritten as it is [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/tuner/lr_finder.py#L147). 

### Expected behavior

Have a smooth way to ignore it. 

### Environment

```
* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0+cu101
	- pytorch-lightning: 0.10.0
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020
```

 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux): colab
 - How you installed PyTorch (`conda`, `pip`, source): pip

### Additional context

I am putting this as a bug because it is a behavior that required me to check into the source code to figure out where this DummyLogger came from. If the solution is non-trivial, a resolution could just be some warnings in the doc.

**Comment by SkafteNicki** [comment]
We had this problem before (this issue https://github.com/PyTorchLightning/pytorch-lightning/issues/1919) and it was solved, but after refactors it seems to only be correct if `trainer.tune()` is called.
The solution is to rebind the logger after running the a tuner algorithm like here:
https://github.com/PyTorchLightning/pytorch-lightning/blob/f3dfb984442c1c4b79f95cfb1d83742aa76cc98b/pytorch_lightning/tuner/tuning.py#L58
@zippeurfou would you be up for sending a PR? basically the rebind statement just need to be more from `trainer.tune` to `trainer.tuner.lr_find` and `trainer.tuner.scale_batch_size`.

**Comment by zippeurfou** [comment]
Thanks @SkafteNicki  I think the issue might be more tricky.
`trainer.tune()` also fails. Here is an [example](https://colab.research.google.com/drive/13RrnVaPJtoPy5nHaSPbJu7SedkPbpeud?usp=sharing)
I will read the issue and resolution to see if I can do something along the lines.

**Comment by SkafteNicki** [comment]
@zippeurfou what I think is a better solution is for both `DummyLogger` and `DummyExperiment` to support indexing. It would simply be adding this class method to both:
```python
    def __getitem__(self, idx):
        return self
```
After adding this, if I run the line that gives problem in your example:
```
self.logger.experiment[0].add_histogram(f'grad/{name}', param.grad.data, self.global_step)
```
i get no error :]
Would you be up for sending a PR?
