### ISSUE TITLE
Replace AttributeDict in with dict in checkpoint

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#4542]
## 🚀 Feature

When we save hyperparameters to the checkpoint, we save them in a Lightning datastructure called AttributeDict. 
We should replace this with a regular dict when saving the checkpoint.

### Motivation

Allows loading checkpoints with `torch.load` in environments where Lightning is not installed.

### Pitch

Convert AttributeDict to dict when saving, convert dict to AttributeDict when loading.

cc @Borda

**Comment by rohitgr7** [comment]
wasn't this resolved here: https://github.com/PyTorchLightning/pytorch-lightning/issues/2653
maybe someone changed it again.

**Comment by awaelchli** [comment]
thanks for pointing to the linked pr. A week ago I inspected the checkpoint and the type was AttributeDict. 
I will check again

**Comment by s-rog** [comment]
Yeah this is odd, last I tested it was loading fine (without pl) as well... though there has been quite a bit of refactoring...

**Comment by awaelchli** [comment]
aha, but that means the logic there with omegaconf is making it break. because even when omegaconf is  installed but not used, we have the attribute dict in the checkpoint.

**Comment by s-rog** [comment]
oh I did not realize `OMEGACONF_AVAILABLE` is only checking if it's installed...
