### ISSUE TITLE
PR template requires label addition to non-permitted author

### ISSUE THREAD

**Issue by tarepan** [PyTorchLightning/pytorch-lightning#4544]
## 🐛 Bug
New PR template requires `Add labels and milestones`, but it is impossible because **non-maintainer author do not have labelling permission**.  

### To Reproduce
Try to follow below PR template instruction as non-maintainer.  

```
 - [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified; _Bugfixes should be including in bug-fix release milestones (m.f.X) and features should be included in (m.X.b) releases._
```

non-maintainer author do not have permission, so can do nothing (no label setup icon, like below image).  

![image](https://user-images.githubusercontent.com/19833110/98325468-3e438c80-2032-11eb-8e80-5ed721ea0593.png)

### Expected behavior
Have labelling permission, so PR author can label the PR.  

### Environment
master latest (5e09fd31e9850902fc0a79e92aaba7b80dae1944)

### Additional context
This template description is introduced in #4523

**Comment by rohitgr7** [comment]
cc @Borda

**Comment by tchaton** [comment]
Hey @tarepan,

Don't worry, we added this line to make sure Pytorch Ligthning Core Team add labels on every PRs.

Best regards,
Thomas Chaton.

**Comment by Borda** [comment]
@tchaton this is in the section for reviewers so do not worry... :]
but maybe we should write it there that the before submit is for author and PR review is for reviewers only
