### ISSUE TITLE
Clarify ModelCheckpoint behavior when self.monitor == None

### ISSUE THREAD

**Issue by miccio-dk** [PyTorchLightning/pytorch-lightning#4553]
## 📚 Documentation

In ModelCheckpoint, setting `self.monitor` to `None` (as for the built-in checkpoint callback in the Trainer) causes it to default to either `val_loss` or `checkpoint_on`, as per [L459](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/callbacks/model_checkpoint.py#L459). This, in turn, overrides the behavior described in the docs, which is caused by [L500](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/callbacks/model_checkpoint.py#L500).

Incriminated docs at [L53](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/callbacks/model_checkpoint.py#L53):
> monitor: quantity to monitor. By default it is ``None`` which saves a checkpoint only for the last epoch.

I think that this should be clarified to reflect the (pretty complex and a bit tricky, IMHO) behavior of ModelCheckpoint, perhaps by adding this to the doc entry:
> monitor: quantity to monitor. By default it is ``None`` which saves a checkpoint only for the last epoch; **if the user logs either ``val_loss`` or ``checkpoint_on``, it will instead monitor their quantity**.

I will happily submit a pull request once I hear from a maintainer! :)

**Comment by carmocca** [comment]
> if the user logs either val_loss or checkpoint_on, it will instead monitor their quantity.

This was kept for backwards compatibility. Before, you would monitor a quantity by setting it to those keys during training. Now, it is done via ModelCheckpoint's monitor. I guess we never deprecated it properly.

It is fine to update the docs with that piece of information. But it should also be properly deprecated and explicitly stated.

**Comment by miccio-dk** [comment]
thanks for the clarification! Indeed, I saw a comment about it in the code. 
This makes me wonder, however, about what's the desired future behavior once this functionality will be abandoned. 
Will the built-in checkpoint store only the last weights, so that users must instantiate a separate checkpoint monitoring a custom variable (e.g. `val_loss`)? in this case, users can skip saving the latest weights by setting `checkpoint_callback` to `False`. I think this would be a sensible behavior, but I don't know what your future plans are :)

**Comment by carmocca** [comment]
Yes, that is correct

**Comment by miccio-dk** [comment]
alright, i'll prepare a PR with the chance mentioned earlier. Please let me know if it should contain more than that, and I'll be happy to help :)
