### ISSUE TITLE
progress bar refresh_rate prevents old bars being cleared

### ISSUE THREAD

**Issue by simonm3** [PyTorchLightning/pytorch-lightning#4565]
If you set refresh_rate=100 then the sanity check and validation bars continue being displayed forever even though leave=False. Also the validation bars only show part complete.

I note also that the mininterval parameter for tqdm bars is ignored.

**Comment by awaelchli** [comment]
In which terminal emulator / environment did you observe this behavior? 

Can you verify it with our bug report model?

**Comment by simonm3** [comment]
In a jupyter notebook but likely will be same in any environment. If possible would be simpler to use tqdm for all the progress bar code rather than having a bespoke "refresh" mechanism. It gets to the progress point that should be the end of the bar but does not update it any more.

**Comment by simonm3** [comment]
works fine as long as the refresh is every iteration so bug is probably in the lightning refresh mechanism.

**Comment by edenlightning** [comment]
@awaelchli friednly ping :)

**Comment by awaelchli** [comment]
The PR is finished, it's ready for review
