### ISSUE TITLE
validation progress bar does not update correctly

### ISSUE THREAD

**Issue by simonm3** [PyTorchLightning/pytorch-lightning#4567]
Does not show progress. Reason is line 359 in progress.py:

`self.val_progress_bar.total = convert_inf(self.total_val_batches)`

should be:

`self.val_progress_bar.reset(self.total_val_batches)`

Same applies to other places where progress bar total set.

**Comment by awaelchli** [comment]
we would still have to convert the inf value, right?

`self.val_progress_bar.reset(convert_inf(self.total_val_batches))`

Would you be interested sending a PR with the fix?

**Comment by simonm3** [comment]
I am not clear why the value would ever be infinite.

**Comment by awaelchli** [comment]
A dataset (e.g. IterableDataset) can have infinite/undefined length.

**Comment by simonm3** [comment]
then yes still needs the convert_inf.

**Comment by awaelchli** [comment]
@simonm3 If I replace the `self.val_progress_bar.total` with `self.val_progress_bar.reset`, I don't see a difference. 
Can you post the examle code that gives the wrong progressbar?

**Comment by simonm3** [comment]
You can't see the difference on the validation bar until it is running for
a few seconds

Easiest is look at main progress bar by changing line 342 to self
.main_progress_bar.total = convert_inf(total_batches)

For example see attached.

**Comment by awaelchli** [comment]
thanks, for the main progress bar I can see what happens, just not for the validation and test bars but I submitted a PR. Just need to figure out how to write a test for it.

**Comment by edenlightning** [comment]
@awaelchli please update

**Comment by awaelchli** [comment]
sorry for the delay. @simonm3 see the changes in #4579 this should fix it.
