### ISSUE TITLE
Segmentation fault on import with RTX 3090

### ISSUE THREAD

**Issue by david-waterworth** [PyTorchLightning/pytorch-lightning#4587]
I've just installed an RTX 3090 in my DL machine. I have the following dependencies installed

Driver Version: 455.32
Cuda Version: 11.0
Python Version: 3.8.6
Pytorch Version: 1.7.0+cu11  (`pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`)

After initially having issues (installed cuda-11-1 rather than cuda-11-0) torch appears to work. I ran a  CIFAR10 example on GPU, I verified with nvidia-smi that it was indeed running on the GPU.

I installed the latest pytorch-lightning, i.e. `pip install git+https://github.com/PytorchLightning/pytorch-lightning.git@master --upgrade` but I cannot import, i.e.

```
>>> import pytorch_lightning as pl
Segmentation fault (core dumped)
```

Should this work? If so is there anything I've done wrong? If not, is there anything I can do to assist in tracking down the issue. Ironically I've just discovered that the CRF decoder is quicker on CPU (at least cf my older 1080Ti) so I don't need the GPU backend but atm I crashing on import is problematic ;)

**Comment by ydcjeff** [comment]
Hi @david-waterworth so Lighting imports failed on both CUDA 11 and 11.1?

**Comment by Borda** [comment]
@david-waterworth could you please confirm that the very same import works with `import torch`?

**Comment by david-waterworth** [comment]
@ydcjeff it may have but at that stage I was still getting the dependencies correct - there's no pre-built torch binary for 11.1 (afaik).

@Borda yes `torch` imports fine and I can run a pure torch training loop on my 3090. I'm going to clone `pytorch-lightning` and see where it's crashing. There's a chance I have an env variable or something pointing to the wrong place, although I would have thought that would impact `torch` as well as `pl`

**Comment by david-waterworth** [comment]
I deleted my virtual environment and reinstalled. It now no longer crashes. Instead I'm getting 'CUDA error: no kernel image is available for execution on the device' which is the error I saw earlier using `torch` when I had the wrong version of pytorch / cuda. Not sure why at this stage but pl is finding the wrong cuda by the looks of things - I'll dig further - it's probably an issue with my installation.

**Comment by david-waterworth** [comment]
I ended up installing the nightly version of pytorch via `pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html` which installed `torch-1.8.0.dev20201106+cu110` (based on https://github.com/pytorch/pytorch/issues/45028). 

It's working, despite the messages:

torchvision 0.8.1 requires torch==1.7.0, but you'll have torch 1.8.0.dev20201106+cu110 which is incompatible.
pytorch-lightning 1.0.5 requires torch<1.8,>=1.3, but you'll have torch 1.8.0.dev20201106+cu110 which is incompatible.

looks like there are still some torch issues to iron out - and cuda 11.1 is needed to unlock the full potential of the card.

**Comment by Borda** [comment]
@david-waterworth I am sorry for such complication, but it seems that it was not Pl problem in the end, away the HW specific issue would be quite hard to debug/reproduce locally as these kinds of cards are not available on cloud hosting...
From my experience, actual Torch binaries on PyPI are building with CUDA 10.1 and 10.2 so you may consider building your one package from the source...
So I assume this one as resolved as it is not PL issue, feel free to re-open if needed 🐰

**Comment by david-waterworth** [comment]
@Borda yes I agree, I'm not sure what the best approach at the moment is. I'll try building torch 1.7 against CUDA 11.1 from source. Although if I need torch 1.8 I'll have to wait for downstream packages to update their dependencies - both PL, AllenNLP and others require torch <= 1.7 at the moment

**Comment by Borda** [comment]
We are working on adding support for nightly (1.8) as soon as possible unless it will require some significant changes on the PL side...
cc: @edenlightning

**Comment by david-waterworth** [comment]
Thanks, it's now working with `pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`

I think some packages with `requires` in their dependencies replace 1.7.0+cu110 with 1.7.0 or even 1.6.0 so I've found I need to install this last.
