### ISSUE TITLE
Mergify never merge PullRequest

### ISSUE THREAD

**Issue by tarepan** [PyTorchLightning/pytorch-lightning#4588]
## 🐛 Bug
`.mergify.yml` requires over 54 tests pass, but CI `All checks have passed` results in  `53 successful checks`.  
Automatic merge never triggered.  

### To Reproduce
Make pull request which pass all test.  

![image](https://user-images.githubusercontent.com/19833110/98516644-18c3b680-22b0-11eb-8c7e-76fb2202c0c5.png)

Mergify unexpectedly do not merge this PR.  

### Expected behavior
Mergify automatically merge the PR.  

### Environment
master latest (ee35907170977bf9cba43c2c921520a2cb8a7901)  
Example non-merged PR: #4526

### Additional context
Current mergify config:  

https://github.com/PyTorchLightning/pytorch-lightning/blob/ee35907170977bf9cba43c2c921520a2cb8a7901/.mergify.yml#L26-L27

CI `All checks have passed` results in  `53 successful checks` (example: above image).  
But config requires over 54.  
It seems to be the cause of this bug (It could be nonsense because I am totally newbie of Mergify.)

**Comment by ydcjeff** [comment]
Hi @tarepan 
We temporarily disable mergify service because we config in the way that mergify request the core contributors to review the PRs even if they have already reviewed them. So, mergify notifications are taking up everywhere in the github noti so we temporarily disable it, not a bug
