### ISSUE TITLE
How to deal with "almost equal partitions" when implementing dataset partitioning for DDP?

### ISSUE THREAD

**Issue by arcticriki** [PyTorchLightning/pytorch-lightning#4599]
## What is your question?

I need to implement some simple Data Partitioning logic in order to explicitly split my big dataset among processes used in DDP. The logic will be the following:

assuming that each data_partition will be identified by a `data_partition_id` and `global_rank` of each machine will increase monotonically, I will be loading data in the target process only if `data_partion_id % global_rank == 0`.

Data loading is indeed working as expected. However, DDP training doesn't even start, since data_splits are "almost" equal in terms of the number of examples. 

My guess is that in pytorch-lightining we implicitly always have "training_epochs" outer loop and "training_steps"  inner loop. If examples needed to complete one full pass over the data (i.e epoch) differ, there won't be an "agreement" between DDP parts. The solution should be to completely disable the "epochs" logic and being able to specify only steps to train on, for each different process.

#### What have you tried?

I've tried to use only `max_steps` argument, but the problem still persists.

Do you have any idea how I could overcome such a problem? Otherwise, how to implement simple data partitioning for DDP in pytorch-lightning?

#### What's your environment?

 - OS: Linux
 - Packaging: pip
 - Version: pytorch-lightning==1.0.1, torch==1.5.0

**Comment by SeanNaren** [comment]
Hey @arcticriki are you implementing DDP data partitioning logic into your dataloader? For some further information we do an automatic sampler swap if using DDP such that any standard data-loader that is meant to be used sequentially is automatically partitioned correctly for DDP:

https://pytorch-lightning.readthedocs.io/en/stable/multi_gpu.html#remove-samplers

Currently the sampler circles additional samples to the end to ensure that there are equal batches split across all processes. 

This logic can be turned off in the trainer using `replace_sampler_ddp=False` if you'd like to specify your own sampler. Let me know if this helps!

**Comment by arcticriki** [comment]
@SeanNaren thanks for your answer. I'll tell you exactly I'm doing it, maybe you will have some more ideas.

* I'm using `pl.LightningDataModule` to abstract my `Dataset`, say we have:
```
class MyDataModule(pl.LightningDataModule)
 ...
```
* In the `setup` method of `MyDataModule` I'm "building" my dataset in this way:
```
def setup(self, stage: str = None):

  dataset = []
  data_chunks = list_filepaths(data_dir, filename_extension='.json')
  # sort to preserve order among processes
  data_chunks.sort()

  process_global_rank = torch.distributed.get_rank()
  num_processes = torch.distributed.get_world_size()

  local_data_chunks = data_chunks[process_global_rank::num_processes]

  for data_chunk in local_data_chunks:
    dataset.extend(load_json(data_chunk, logger))

  return dataset
```

* then, this list (`dataset`) is passed to the dataloader:

```
    def train_dataloader(self, dataset) -> DataLoader:
        return DataLoader(
            dataset,
            batch_size=self.hparams.batch_size,
            num_workers=self.hparams.num_workers,
            shuffle=True,
            pin_memory=True,
        )
```

This code is packed into my "train.py" script, that is launched in every machine. In the logs I see that indeed every machine is reading its portion of data. Everything will work fine until, for each process, we will have exactly the same number of examples (i.e each partition is composed of an equal number of examples).

However, when the number of examples differs, the training doesn't even start.

As you can see, I'm not passing any `sampler` to my dataloader, so pytorch-lightning should automatically set the `DistributedDataSampler`. I tried to disable it, as you suggested, but the problem persists.

Given this experiment setup, what would you suggest to do? 
Or maybe, can you suggest a completely different way of partitioning my data?
