### ISSUE TITLE
load_from_checkpoint: TypeErrror: __init__() missing 1 required positional argument

### ISSUE THREAD

**Issue by EQlearning** [PyTorchLightning/pytorch-lightning#4600]
```
def load_checkpoint(path):
    model = resnet50().load_from_checkpoint(path)
    print(model)
    model.eval()
    logit = model._modules.get('fc')
    return model, logit
```

When i call this function, i got this error. 
**TypeError: __init__() missing 1 required positional argument: 'layers'**

My model resnet50 is public code in torchvision.

What is wrong in my code?

**Comment by EQlearning** [comment]
In my model ResNet def __init__() i added this line self.save_hyperparameters().

It works :)

**Comment by keunwoochoi** [comment]
Thanks!
