### ISSUE TITLE
How to save gradient every step?

### ISSUE THREAD

**Issue by Limtle** [PyTorchLightning/pytorch-lightning#4601]
#### What is your question?
Because my model have some gradient disappear , I need to save gradient every step to debug. 
I found this issue #49. But the document does not have its information. How to save gradient every step?

**Comment by SeanNaren** [comment]
Hey @Limtle, do you mean saving your gradients from the loss or within the parameters?

**Comment by rohitgr7** [comment]
you can override `on_after_backward` or `on_before_zero_grad` hook and save the save gradient as you wish. You can acces them both within a callback or the LightningModule itself.

with a callback:
```python
def on_after_backward(self, trainer, pl_module):
    ... save the gradients
```
