### ISSUE TITLE
How to load to from a checkpoint to same device when pretrained encoder was used

### ISSUE THREAD

**Issue by hakanyi** [PyTorchLightning/pytorch-lightning#4604]
## ❓ Questions and Help 

I implemented a `ClassificationNet` (see below) that's using a pretrained encoder. After training, I'm trying to load it to CPU using `ClassificationNet.load_from_checkpoint(pth, map_location=torch.device("cpu")`, but since `map_location` in `get_encoder` is `None`, the encoder tries to load to GPU. How can I inform `get_encoder` to load to the same `map_location`? 
Since I just started using Lightning, I guess there's a much smarter way to circumvent this situation altogether -- I look forward to your suggestions :) Thanks!

#### Code
``` python
class ClassificationNet(LightningModule):
    ...
    self.encoder = get_encoder(pretrained=True)

get_encoder(pretrained=False, map_location=None):
    model = FancyModel()
    if pretrained:
        ckpt_data = torch.utils.model_zoo.load_url(url, map_location=map_location)
    ....
```

 - OS: Manjaro Linux
 - Version 1.0.5

**Comment by rohitgr7** [comment]
one solution can be having an additional argument for it.
```python
class ClassificationNet(LightningModule):
    def __init__(self, encoder_map_location, ...):
        self.encoder = get_encoder(pretrained=True, map_location=encoder_map_location)
```
```python
ClassificationNet.load_from_checkpoint(pth, map_location=torch.device("cpu"), encoder_map_location=torch.device("cpu"))
```

or maybe without an additional argument. Not sure about this one though. But should work.
```python
class ClassificationNet(LightningModule):
    def __init__(self, ...):
        ....
    
    def setup(self, stage):
        self.encoder = get_encoder(pretrained=True, map_location=self.device)
```
```python
ClassificationNet.load_from_checkpoint(pth, map_location=torch.device("cpu"))
```

**Comment by hakanyi** [comment]
Thanks @rohitgr7! The second solution works indeed and does the job just perfectly :)
