### ISSUE TITLE
EarlyStopping BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by aktersnurra** [PyTorchLightning/pytorch-lightning#4605]
## 🐛 Bug
EarlyStopping together with num_workers > 0 yields the following error message for me:

```
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.8.2/lib/python3.8/multiprocessing/queues.py", line 245, in _feed
    send_bytes(obj)
  File "/home/user/.pyenv/versions/3.8.2/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/user/.pyenv/versions/3.8.2/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/home/user/.pyenv/versions/3.8.2/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

I strongly believe this is the case, as setting `num_workers=0` or **not** using the `EarlyStopping` callbacks removes this error message from showing up.

### To Reproduce
This is probably coupled with reading data from a hdf5 file, with an implementation similar to this one:

https://discuss.pytorch.org/t/dataloader-when-num-worker-0-there-is-bug/25643/16

(It seems like h5 does not have good support multiprocessing handling.)

### Environment

 - PyTorch Version (e.g., 1.0): 1.7.0
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, source): poetry
 - Python version: 3.8.2
 - CUDA/cuDNN version: nvidia-cuda-toolkit
 - GPU models and configuration: 2080 ti

**Comment by SeanNaren** [comment]
Hey @aktersnurra this seems hdf5 specific, would it be possible to get the fullstack trace or reproduce using this?

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py

**Comment by aktersnurra** [comment]
Hi @SeanNaren, 

I ran the `bug_report_model.py`, it is as you thought, a hdf5 bug. I suspect it has something to do with the threads reading from the h5 file and early stopping trying to terminate the training that causes the issue. I'll go dig for a solution in the h5 corner.

Thanks for the fast response,

Cheers,

Gustaf

**Comment by Shreeyak** [comment]
@aktersnurra Hey, I'm getting the same error message. Where did you add this line to solve the issue?

**Comment by aktersnurra** [comment]
@Shreeyak are you using any type of multiprocessing/threading when loading the files?

**Comment by Shreeyak** [comment]
Not that I'm aware of! I'm just reading in png images in my dataloader (unique image each time) as normal.

I am using DDP though. I'll check if maybe 2 processes are trying to create the same directory or something. Thanks for the tip!

**Comment by karthi0804** [comment]
Hi, 
This happens to me when training using DDP inside a docker container. But native training has no prob. Any thoughts?
