### ISSUE TITLE
lr_tuner fails if called after tuning batch_size

### ISSUE THREAD

**Issue by Palzer** [PyTorchLightning/pytorch-lightning#4616]
https://github.com/PyTorchLightning/pytorch-lightning/blob/514cb22bd719e6ca056cacce730c8de875c9dbf6/pytorch_lightning/tuner/lr_finder.py#L411

The line above sets current_step to 2 if the batch_size tuner has already run.

https://github.com/PyTorchLightning/pytorch-lightning/blob/514cb22bd719e6ca056cacce730c8de875c9dbf6/pytorch_lightning/tuner/lr_finder.py#L419-L420

This causes best_loss to be zero and compare against the smoothed loss. This will cause the tuner to terminate and fail.

Also, just looks like this was already supposed to be changed.

**Comment by edenlightning** [comment]
@SkafteNicki mind taking a look?

**Comment by SkafteNicki** [comment]
It seems the solution is to remove the `+1` from `current_step` (as the todo note also states)
@Palzer would you be up for sending a PR with the fix?

**Comment by Palzer** [comment]
Done. First pr on github so be gentle :P

**Comment by SkafteNicki** [comment]
@Palzer I can probably find some time tomorrow to look over your work. Thanks for wanting to contribute :]
