### ISSUE TITLE
Add log_gpu_utilization

### ISSUE THREAD

**Issue by elgalu** [PyTorchLightning/pytorch-lightning#4628]
## 🚀 Feature
There is `log_gpu_memory` , what about `log_gpu_utilization` ? for instance 4.0 (400 %) would mean 4 GPU(s) are currently being efficiently utilized.

**Comment by rohitgr7** [comment]
try [GPUStatsMonitor](https://pytorch-lightning.readthedocs.io/en/latest/generated/pytorch_lightning.callbacks.GPUStatsMonitor.html#gpustatsmonitor) callback.
