### ISSUE TITLE
TensorBoardLogger saves hyperparams generated by opt_range as strings

### ISSUE THREAD

**Issue by vladimirbelyaev** [PyTorchLightning/pytorch-lightning#4631]
## Please reproduce using [the BoringModel and post here]
https://colab.research.google.com/drive/1UAvfpDsvnIG3EHMIul4OR68GunMMmRgE?usp=sharing

### To Reproduce
I used HyperOptArgumentParser to generate opt_range and pass it to model.
Then i passed these hyperparams to tensorboard logger as
`self.save_hyperparameters(params)`
Then I see that opt_range hyperparams are sorted in alphabetical order(like strings) and aren't usable for filtering trials.

### Expected behavior
Float hyperparameters are still float in TensorBoard (e.g. they can be sorted and can be used as filtering value for hyperparameter table)

### Environment

* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0+cu101
	- pytorch-lightning: 1.0.0
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

### Additional context

I suppose problem is in `_sanitize_params` function of LightningLoggerBase which converts np.float64 values to strings.
Currently there's a simple workaround for this problem:
```
def pre_sanitize_args(kwargs: Dict) -> Dict:  
    return {k: float(v) if type(v) == np.float64 else v for k, v in kwargs.items()}
```

**Comment by s-rog** [comment]
```
my_float_hopt_param <class 'numpy.float64'>
my_float_param <class 'float'>
```
I'm guessing there are issues casting np floats
