### ISSUE TITLE
is it able to save stdout to file ?

### ISSUE THREAD

**Issue by aiyolo** [PyTorchLightning/pytorch-lightning#4644]
currently, the terminal output won’t be saved, i think it will be more convenient to print some metrics in the terminal and then save them in a file

**Comment by Borda** [comment]
Hi, you can use Linux standard redirection to a file as
```
python Script-train-my-model.py >> ./some-file-for-logs.txt
```
as an alternative you can explore saving logs with different level - at this moment we show INFO logs in the terminal but you can print DEBUG level to a file, check sample code here:
https://github.com/Borda/BIRL/blob/087e6771236ebffc4d293e37076815438d88e6c2/birl/utilities/experiments.py#L276-L298
