### ISSUE TITLE
Loading samples to RAM with DDP.

### ISSUE THREAD

**Issue by jopo666** [PyTorchLightning/pytorch-lightning#4646]
#### What is your question?

I'm facing an IO bottleneck that can be fixed with a custom `torch.utils.data.Dataset` that loads each sample to RAM. Then training goes fast as I don't need to read my samples (images) from disk (slow). Everything works well with when I'm using 1 GPU, but I'm a bit lost when I switch to multiple GPUs with DDP.

DDP divides the samples to each GPU and I'm wondering when/where I should load my samples to RAM so that each process only loads its own partition of the samples?

#### Code

```
class RAMDataset(data.Dataset):
    def __init__(self, paths,labels,transform):
        """Dataset that loads all samples to RAM."""
        self.paths = paths
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.samples)

    def load_to_RAM(self):
        self.images = []
        for path in self.paths:
            with open(path, "rb") as f:
                str_encode = f.read()
                nparr = np.frombuffer(str_encode, np.uint8)
                self.images.append(cv2.imdecode(nparr, cv2.IMREAD_COLOR))

    def __getitem__(self, index):
        # Run self.load_to_RAM() first!
        image = self.transform(self.images[index])
        label = self.labels[index]
        return image, label
```

#### What have you tried?

With 1 GPU `self.load_to_RAM()` can be excecuted as soon as the Dataset has been created.

```
dataset = RAMDataset(paths,labels)
dataset.load_to_RAM()
loader = DataLoader(dataset,...)
trainer.fit(model,loader)
```

But obviously this would load the samples `num_gpus` times to the RAM of the node.

I quickly tried to call `self.train_dataloader.dataset.load_to_RAM()`on the hook `setup()` but got the following error...
```
AttributeError: '_PatchDataLoader' object has no attribute 'dataset'
```
..and I'm 99% this solution would also load all of the samples to RAM.

#### Possible solution?

1. Find out which process (which GPU and which node) is currently running.
2. Get the allocated slice of the samples for this process.
3. Load only that slice of the `self.paths` to RAM.

Tried to go through the source code but couldn't find out how I could implement this.

**Comment by s-rog** [comment]
The OS should automatically cache the dataset after the first epoch (assuming you have enough ram) so you shouldn't need to do this.

I'm actually not sure if distributed sampler shards the same data/item on the same GPU through different epochs... but that's more of a pytorch question than a lightning one.

**Comment by lucadiliello** [comment]
Lightning uses a random `Sampler` to extract data from the `Dataset`. No easy way to know in advance the indices that will be used on each machine. However, you can create a `Dataset` where only the right portion of the data is loaded into RAM before training on each GPU/node. You can use `torch.distributed.get_world_size()` and `torch.distributed.get_rank()` to know which data should be loaded on each parallel process.

Example (I did not test it):

```
class MyDataset():
    def __init__(self, data):
        start = (len(data) // torch.distributed.get_world_size()) * torch.distributed.get_rank()
        end = (len(data) // torch.distributed.get_world_size()) * (torch.distributed.get_rank() + 1)
        self.data = load_ram(data[start:end])

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        # checks on index ...
        return self.data[idx]
```

**Comment by jopo666** [comment]
I do have enough RAM if I manage to divide my data to multiple nodes. If the `BasicDataset()` below is cached after the first epoch wouldn't that mean only the labels and paths are cached? What I would want is that the loaded images are cached. I'll look into PyTorch and see if the same data/items are kept for each epoch.

```
class BasicDataset(data.Dataset):
    def __init__(self, paths,labels,transform):
        self.paths = paths
        self.labels = labels

    def __getitem__(self, index):
        image = load(self.paths[index]) # This is my bottleneck.
        label = self.labels[index]
        return image, label
```

**Comment by s-rog** [comment]
Ah you're doing cross node DDP, I was referring to single node above... I'm afraid I don't have much experience with multi node DDP.

But if each node gets the same subset of data every epoch, the OS should cache the files all the same (without needing `load_to_RAM`) after the first epoch since you have enough RAM.

**Comment by jopo666** [comment]
Would the actual loaded images be cached even though they are loaded inside `__getitem__()` and not just the whole `Dataset` object with only the `paths` to these files?

**Comment by s-rog** [comment]
Yes, this is not stored in your program/script memory but instead it's simply file caching at the system level.

I use Ubuntu but this should be the same for other linux ditros unless some memory/caching settings have been changed/limited. You can look at the cache part of your ram usage in htop as your data is loaded into memory during the first epoch.

**Comment by jopo666** [comment]
Perfect! Kept running tests that ran only for one epoch so I never noticed the seed-up on the second epoch... 😄 Well you learn something new everyday.
