### ISSUE TITLE
Modification to the default logging frequency

### ISSUE THREAD

**Issue by MrinalJain17** [PyTorchLightning/pytorch-lightning#4649]
## 🚀 Feature

As described [here in the documentation](https://pytorch-lightning.readthedocs.io/en/stable/logging.html#control-logging-frequency), lightning logs once every 50 training steps. It'd be helpful if the default were instead a function of the total number of batches in the dataset instead of a hard-coded value.

### Motivation

I'm working on a medical image segmentation problem. A common issue in the medical domain is that the data is often very limited. In my case, I have about 1300 images, which amounts to around 20 training steps per epoch with a batch size of 64. Due to the hard-coded value of `log_every_n_steps=50`, the lightning module only logs the losses/metrics once in every 2 epochs (if I log every step - `on_step=True`).

However, this doesn't seem right. I understand that logging every step is not feasible, and could slow down the training process. But I'd still like to get my logs flushed atleast once every epoch.

### Pitch

I think one approach to automate this with lightning could be something along the lines of:

```python
num_batches = ...
log_every_n_steps = min(50, num_batches - 1)
```

This should hopefully not break any existing code, but will in effect make the `log_every_n_steps` more generalized and relevant for small datasets.

### Alternatives

I could just set `log_every_n_steps` manually, but maybe a better solution would be if lightning handles this internally (because otherwise this value could be different for different batch sizes). For example, let's say that I set `log_every_n_steps=20` given that I have 30 training steps in an epoch. If however, I double my batch size - the training steps will be down to 15 (and we're back to square one).

**Comment by stwerner97** [comment]
Although the issue has been stale for a while, I think it would be great to implement the proposed changes.

I am currently working on an approach based on curriculum learning. The prediction horizon starts off small but steadily increases with the number of epochs. Therefore, the number of batches decreases over time and no predefined `log_every_n_steps` parameter will work well.
