### ISSUE TITLE
[Trainer] flush_logs_every_n_steps not working

### ISSUE THREAD

**Issue by emilemathieu** [PyTorchLightning/pytorch-lightning#4664]
## 🐛 Bug

HI all ! thanks a lot for this great module :)

`Trainer` has this neat argument `flush_logs_every_n_steps`, and does indeed take it into account before calling `logger.save()` [in training_loop.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/baa8558cc0e6d2a3e24f2669e6a59ffdb8138737/pytorch_lightning/trainer/training_loop.py#L878).
Yet, the `LoggerConnector` flushes at each `log_metrics` call by calling [self.trainer.logger.save()](https://github.com/PyTorchLightning/pytorch-lightning/blob/baa8558cc0e6d2a3e24f2669e6a59ffdb8138737/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py#L214).

Is that the expected behaviour of `flush_logs_every_n_steps`?
Shouldn't it be something like 
```python
if self.trainer.logger is not None:
    if self.trainer.is_global_zero:
        self.trainer.logger.agg_and_log_metrics(scalar_metrics, step=step)
        if self.should_flush_logs:
            self.trainer.logger.save()
```
in [logger_connector.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/baa8558cc0e6d2a3e24f2669e6a59ffdb8138737/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py#L211) ?

### To Reproduce
Print when `Logger.save` is called.

### Expected behavior

Only call `logger.save()` every n steps.

### Environment

I've tried to reproduce the bug in Colab but I get an error as `test_tube` is not installed even though I did `pip install test_tube `.

* CUDA:
	- GPU:
	- available:         False
	- version:           10.2
* Packages:
	- numpy:             1.19.4
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0
	- pytorch-lightning: 1.0.6
	- tqdm:              4.51.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		-
	- processor:         x86_64
	- python:            3.7.9
	- version:           #1 SMP Tue Aug 11 16:36:14 UTC 2020

Cheers,
Emile

**Comment by Borda** [comment]
@emilemathieu mind share some small example for illustration what you mean? 🐰

**Comment by emilemathieu** [comment]
Hi @Borda, I understood that  `log_every_n_steps` was the "time discretisation" (i.e. having a point every n step/batch) in the tensorboard logs, and that `flush_logs_every_n_steps` was the period (measured in steps) for actually flushing/saving these logs into a file. 

In [this colab](https://colab.research.google.com/drive/1Cm7JaB78Sbq5dcspSDsDFMUq8n8f6uK7?usp=sharing), I'm setting `log_every_n_steps=1, flush_logs_every_n_steps=50`, yet the logger is flushed (i.e logger.save()) at every step even though it should be only every 50 steps.

**Comment by edenlightning** [comment]
@teddykoker mind taking a look?

**Comment by emilemathieu** [comment]
Would there be any news about this issue?
I believe the solution is extremely simple:
```python
if self.should_flush_logs:
    self.trainer.logger.save()
```

**Comment by MJHutchinson** [comment]
@Borda @tchaton @emilemathieu 

Bump on this issue - it's very annoying as it causes excessive logging. @emilemathieu 's fix works perfectly.

**Comment by emilemathieu** [comment]
@Borda @tchaton @teddykoker @edenlightning Please would there be any news regarding this? It's really an issue to avoid flushing to often hence blowing up I/O. The fix is also extremely simple.

**Comment by kaushikb11** [comment]
@emilemathieu Will look into it soon :) Thanks!

**Comment by emilemathieu** [comment]
Here is the fix: https://github.com/emilemathieu/pytorch-lightning/commit/043496d68ec3c45defff73dbb1253c8d19fcd13c

**Comment by kaushikb11** [comment]
@emilemathieu I had tried that. It's working but it's failing a couple of tests. [Test1](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/tests/loggers/test_all.py#L145) and [Test2](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/tests/loggers/test_base.py#L169).

**Comment by emilemathieu** [comment]
@kaushikb11 Indeed, I had a proper look at it but it's honestly it's quite complex, made me loose faith a bit in pl.

For one, what is [`logger.history`](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/tests/loggers/test_all.py#L144)? I could not find anything on that. Also [`logger.agg_and_log_metrics`](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py#L243) is not necessarily calling `logger.log_metrics`. What is it supposed to do then? as opposed to `logger.save`? 

I don't think I'll push more on this, but there is still definitely an issue.

**Comment by kaushikb11** [comment]
@emilemathieu `logger.history` is an attribute of a Custom Logger to test the calls to the `log_metrics` method. It's just for the test.
https://github.com/PyTorchLightning/pytorch-lightning/blob/baa8558cc0/tests/loggers/test_all.py#L77

Yeah, I understand why it could be confusing. `logger.agg_and_log_metrics` and `logger.save`, both are calling `logger.log_metrics`. `logger.agg_and_log_metrics` is calling it if it has metrics to log. Also, we would need to regard for `validation` and `test` modes.

I think it would be better to do a mini refactor than trying to fit a fix in the current flow.

**Comment by emilemathieu** [comment]
I see. And when are the logs actually flushed? as in written in the file system? Is it when `logger.experiment.flush()` is called? or every time `logger.log_metrics` is called?

**Comment by inzouzouwetrust** [comment]
Bump! My write I/O is through the roof and it significantly slows down my training when all my logs point to the same disk (which is my case). It's becoming a major bottleneck.
Anything I could do to help/fix it?

**Comment by kaushikb11** [comment]
@inzouzouwetrust I will look into it again later this week. You could look into it as well, feel free to ask any questions.

**Comment by emilemathieu** [comment]
It seems that each logger is handling this differently. The fixed I proposed works for the `CSVLogger`, the `TensorboardLogger` as a `max_queue` parameter that can be set at init, `wandb` seems to be handling this in an async manner (cf https://github.com/wandb/client/issues/1904#issuecomment-786813853)

**Comment by inzouzouwetrust** [comment]
From my experience the `max_queue` in `TensorboardLogger` does not do the job, unfortunately. I'm currently debugging but so far my results are unconclusive.
