### ISSUE TITLE
What is the difference of the two function, train_epoch_end and on_train_epoch_end

### ISSUE THREAD

**Issue by 7zhanghao** [PyTorchLightning/pytorch-lightning#4671]
It seems that don't  have some difference. Hope someone can explain this for me. Thanks a lot.

**Comment by ydcjeff** [comment]
There is no `train_epoch_end` function, only `on_train_epoch_end` and `on_epoch_end`

**Comment by 7zhanghao** [comment]
> There is no `train_epoch_end` function, only `on_train_epoch_end` and `on_epoch_end`
![捕获](https://user-images.githubusercontent.com/46468492/99147039-5f525000-26b8-11eb-9bcb-3d10262dabf8.PNG)
But i really find this function. And what the difference between on_train_epoch_end and on_epoch_end ?

**Comment by ydcjeff** [comment]
They all are called at the end of an epoch of your training.
The order is
- [training_epoch_end](https://github.com/PyTorchLightning/pytorch-lightning/blob/e1955e3c89cdfef2c6db3ccf6e0be3990cb50438/pytorch_lightning/trainer/training_loop.py#L907) gets called [here](on_train_batch_end)
- [on_epoch_end](https://github.com/PyTorchLightning/pytorch-lightning/blob/e1955e3c89cdfef2c6db3ccf6e0be3990cb50438/pytorch_lightning/trainer/training_loop.py#L817)
- [on_train_epoch_end](https://github.com/PyTorchLightning/pytorch-lightning/blob/e1955e3c89cdfef2c6db3ccf6e0be3990cb50438/pytorch_lightning/trainer/training_loop.py#L818)

**Comment by 7zhanghao** [comment]
> They all are called at the end of an epoch of your training.
> The order is
> 
> * [training_epoch_end](https://github.com/PyTorchLightning/pytorch-lightning/blob/e1955e3c89cdfef2c6db3ccf6e0be3990cb50438/pytorch_lightning/trainer/training_loop.py#L907) gets called [here](on_train_batch_end)
> * [on_epoch_end](https://github.com/PyTorchLightning/pytorch-lightning/blob/e1955e3c89cdfef2c6db3ccf6e0be3990cb50438/pytorch_lightning/trainer/training_loop.py#L817)
> * [on_train_epoch_end](https://github.com/PyTorchLightning/pytorch-lightning/blob/e1955e3c89cdfef2c6db3ccf6e0be3990cb50438/pytorch_lightning/trainer/training_loop.py#L818)

So it means that they all carried out  at the end of an epoch. But they have different execution order and need different input. Otherwise, they have no other difference ?

**Comment by ydcjeff** [comment]
Yep, `on_epoch_end` and `on_train_epoch_end` are the same, both are callback methods, we don't currently have better naming so keeping the two for now.
`training_epoch_end` which is the method of `LightningModule` gives you `self.log()` to log the results of the `training_step`.

**Comment by 7zhanghao** [comment]
> Yep, `on_epoch_end` and `on_train_epoch_end` are the same, both are callback methods, we don't currently have better naming so keeping the two for now.
> `training_epoch_end` which is the method of `LightningModule` gives you `self.log()` to log the results of the `training_step`.

Thanks a lot for your answer, it helps me a lot. I undersand it.
