### ISSUE TITLE
self.log on validation_step is broken on pre 1.1 [nightly]

### ISSUE THREAD

**Issue by annikabrundyn** [PyTorchLightning/pytorch-lightning#4681]
https://colab.research.google.com/drive/1tSphAIaCdy3tC9Lzhe1GEK_fH_0a6oYj?usp=sharing

**Comment by Borda** [comment]
@annikabrundyn mind write here a bit more description as it will be useful for others who have the same problem in the future as the linked colab won't be available always... pls copy-paste the model and TB PrintScreen 🐰

**Comment by Borda** [comment]
just tested and it appears only on master, the latest 1.0.7rc0 is fine...

**Comment by annikabrundyn** [comment]
@Borda thank you for looking at this so quickly! will remember to paste context in addition to colab link next time 😊
