### ISSUE TITLE
fix failing examples

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#4694]
## 🐛 Bug

We have uncommented PL examples in #4551 but two of them turned to be failing and shall be fixed:
```
FAILED pl_examples/test_examples.py::test_examples_dp_image_classifier[\n--max_epochs 1 --batch_size 32 --limit_train_batches 2 --limit_val_batches 2 --gpus 2 --distributed_backend dp --precision 16 ]
FAILED pl_examples/test_examples.py::test_examples_dp_autoencoder[\n--max_epochs 1 --batch_size 32 --limit_train_batches 2 --limit_val_batches 2 --gpus 2 --distributed_backend dp --precision 16 ]
```

### To Reproduce

uncomment two remaining examples with TODO comment

### Environment

Drone Multi-GPU testing

### Additional context

get back full example testing...

**Comment by edenlightning** [comment]
TODO: add doctest so we can verify that the API is up tp date

**Comment by Borda** [comment]
> TODO: add doctest so we can verify that the API is up tp date

adding doctests in #5079 #5083 #5085

**Comment by Borda** [comment]
Atm considering adding ddp examples only for master as they take quite some time to run, see #4995 (which shall be the last one from fixing sequence)
