### ISSUE TITLE
Validation step with multiple dataloaders

### ISSUE THREAD

**Issue by williford** [PyTorchLightning/pytorch-lightning#4696]
## 🐛 Bug

I tried to follow the directions for using multiple validation loaders from here:
https://pytorch-lightning.readthedocs.io/en/0.4.9/LightningModule/RequiredTrainerInterface/#validation_step

When I do so, I get the following error:
```
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/connectors/logger_connector.py in _log_on_evaluation_epoch_end_metrics(self, epoch_logs)
    184 
    185             # track the metrics
--> 186             logger_metrics = reduced_epoch_metrics.get_epoch_log_metrics()
    187             pbar_metrics = reduced_epoch_metrics.get_epoch_pbar_metrics()
    188             self.logged_metrics.update(logger_metrics)

AttributeError: 'dict' object has no attribute 'get_epoch_log_metrics'
```

I'm guessing I'm missing something that I need to do, but if so, it would be great for the documentation to be expanded. Also, is there a complete example using multiple validation data loaders?

### BoringModel reproduction

(Edited: updated to correct link ~ with stable pip version of pytorch-lightning)
https://colab.research.google.com/drive/1K1BHSWkS2xT0hahopSeZ0r81QMG4X1ti?usp=sharing

### To Reproduce

In addition to the BoringModel, you can also reproduce in image_classifier example easily:
can  add "dataloader_idx" to validation_step and then make a list of val_loaders (for example, [val_loader, val_loader]) when calling fit.

### Expected behavior

Run validation on each dataloader, logging result for each one.

### Environment

* CUDA:
	- GPU:
		- Tesla P100-PCIE-16GB
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0+cu101
	- pytorch-lightning: 1.0.6
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

**Comment by rohitgr7** [comment]
was fixed here: https://github.com/PyTorchLightning/pytorch-lightning/pull/4480
can you try master?

**Comment by williford** [comment]
It looks like it works after updating to master: https://colab.research.google.com/drive/1xjRGw9tVcCB587UpZsQ2Y2fSf8k_lxxV?usp=sharing

Thanks!
