### ISSUE TITLE
Move dev debugger directly in logging

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#4701]
@edenlightning commented on [Mon Nov 16 2020](https://github.com/PyTorchLightning/staff-private/issues/26)

**Comment by edenlightning** [comment]
This came from postmortem on logging bug.
Move the dev debugger within the logging, to avoid overriding the values expected in tests.

**Comment by edenlightning** [comment]
@tchaton

**Comment by edenlightning** [comment]
@tchaton did we end up doing this?

**Comment by tchaton** [comment]
Hey @edenlightning,

Partially, we removed dependence in the test using the debugging tool at some extend.

**Comment by edenlightning** [comment]
@tchaton what is left TODO?
