### ISSUE TITLE
Where are the parameters passed to?

### ISSUE THREAD

**Issue by FrankXinqi** [PyTorchLightning/pytorch-lightning#4710]
#### What is your question?

I am curious about where are the parameters passed to? In the official implementation of SimCLR, I cannot find any operations use the initialized parameters:
                 batch_size: int,
                 num_samples: int,
                 warmup_epochs: int = 10,
                 lr: float = 1e-4,
                 opt_weight_decay: float = 1e-6,
                 loss_temperature: float = 0.5,
                 **kwargs):

The reason to know that is, when I copy the function and mimic it to write my own function. I cannot find where are these parameters passed to... 

#### Code

https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/b746be06a7ef59c52fb7911b985a1a73821d1a74/pl_bolts/models/self_supervised/simclr/simclr_module.py#L56

**Comment by SkafteNicki** [comment]
The call to `self.save_hyperparameters()` makes all the arguments in `init` available as attributes of `self.hparams`.
You can read more about it here:
https://pytorch-lightning.readthedocs.io/en/stable/hyperparameters.html
