### ISSUE TITLE
How to monitor more than one quantity?

### ISSUE THREAD

**Issue by 7zhanghao** [PyTorchLightning/pytorch-lightning#4711]
What i do if i want to monitor more than one quantity?

**Comment by carmocca** [comment]
You can pass multiple `ModelCheckpoint` callbacks to the trainer callback list

```python
Trainer(callbacks=[ModelCheckpoint(monitor="a"), ModelCheckpoint(monitor="b")])
```

however, this is not fully supported and the saved checkpoints will contain the state for only one of the `ModelCheckpoint`s

Duplicate of #2908

**Comment by 7zhanghao** [comment]
Thanks a lot.
