### ISSUE TITLE
GAN Domain Template: Typo in the description of Adam's beta 2

### ISSUE THREAD

**Issue by ludgerpaehler** [PyTorchLightning/pytorch-lightning#4714]
Hi,

I think Adam's beta 2 parameter was mistakenly referred to as the first order momentum of the gradient, whereas I think it should be the second order momentum?

In the current domain template:
`parser.add_argument("--b2", type=float, default=0.999, help="Adam: decay of first order momentum of gradient")`

Whereas it should be:
`parser.add_argument("--b2", type=float, default=0.999, help="Adam: decay of second order momentum of gradient")`

This has no effect on the correct working of the example however.

All the best,
Ludger

**Comment by justusschock** [comment]
Hi,
Great catch! Do you want to send a pr to fix that?

**Comment by ludgerpaehler** [comment]
@justusschock I'm terribly sorry, but I forgot to link my PR to this issue. The PR has been approved and merged by now :)
