### ISSUE TITLE
Tensorboard save_dir overrides default_root_dir

### ISSUE THREAD

**Issue by MartFire** [PyTorchLightning/pytorch-lightning#4736]
I am using PytorchLighting with Tensorboard and if I specify the argument `save_dir` in `TensorBoardLogger` then my checkpoints will be saved in this directory and not in the `default_root_dir` provided to the `Trainer`. Is this a normal behavior ?

```
tb_logger = pl_loggers.TensorBoardLogger(save_dir=config.TRAINING.log_path)  
began = BEGAN(config)  # My model
trainer = Trainer(logger=tb_logger, default_root_dir=config.TRAINING.ckpt_path)  
trainer.fit(model=began, datamodule=CIFAR10DataModule())  
# checkpoints are saved in config.TRAINING.log_path, not in config.TRAINING.ckpt_path
```

**Comment by SeanNaren** [comment]
This is the default behaviour of `default_root_dir`: https://pytorch-lightning.readthedocs.io/en/latest/trainer.html#default-root-dir

Could you try passing in a `ModelCheckpoint` object to the `callbacks` trainer list and see if this works for you?

```python
tb_logger = pl_loggers.TensorBoardLogger(save_dir=config.TRAINING.log_path)  
began = BEGAN(config)  # My model
trainer = Trainer(logger=tb_logger, callbacks=[ModelCheckpoint(config.TRAINING.ckpt_path)])  
trainer.fit(model=began, datamodule=CIFAR10DataModule())  
# checkpoints are saved in config.TRAINING.log_path, not in config.TRAINING.ckpt_path
```

**Comment by MartFire** [comment]
It's working, thank you !
