### ISSUE TITLE
seed_everything() runs _select_seed_randomly() even if PL_GLOBAL_SEED is set

### ISSUE THREAD

**Issue by bprus** [PyTorchLightning/pytorch-lightning#4741]
## 🐛 Bug

There is a bug in `pl.utilities.seed.seed_everything()`. 

The problem is here:
https://github.com/PyTorchLightning/pytorch-lightning/blob/1.0.5/pytorch_lightning/utilities/seed.py#L44

If `None` is passed as a seed:
`seed = os.environ.get("PL_GLOBAL_SEED", _select_seed_randomly(min_seed_value, max_seed_value))`
is run. And `_select_seed_randomly` is run even if `PL_GLOBAL_SEED` is present in `os.environ`.

The seed is set properly, but there is a warning displayed that suggests a different seed had been set. This introduces some confusion, especially during training with ddp.

### To Reproduce

```
import pytorch_lightning as pl
import os

pl.utilities.seed.seed_everything()
seed = os.environ.get('PL_GLOBAL_SEED')
print(seed)

pl.utilities.seed.seed_everything()
seed = os.environ.get('PL_GLOBAL_SEED')
print(seed)
```

### Expected behavior

The code above produces the following output:
```
No correct seed found, seed set to 3315818503
3315818503
No correct seed found, seed set to 1668269197
3315818503
```

`_select_seed_randomly(min_seed_value, max_seed_value)` should only be run when there is no `PL_GLOBAL_SEED` set.

### Environment

 - PyTorch Lightning Version (e.g., 1.0): 1.0.5

**Comment by SeanNaren** [comment]
Thanks for the issue! Could you verify #4743 fixes this?

**Comment by bprus** [comment]
It seems that this fixes my problem. But it introduces another one, as any seed is now incorrect because of:
`if not (seed < min_seed_value <= seed <= max_seed_value):`
(someone already pointed it in PR comments)

**Comment by bprus** [comment]
Still waiting for a fix.
