### ISSUE TITLE
Getting an error when trying to use torch.load on model trained using DDP

### ISSUE THREAD

**Issue by gsellers-tulco** [PyTorchLightning/pytorch-lightning#4761]
#### What is your question?
I'm trying to save my model with torch.save() with the trainer and logger detached and then load it with `torch.load()`. If I train the model using DDP on 2 P4 gpus, I get the following error when I try to load it:
```
RuntimeError: [enforce fail at inline_container.cc:222] . file not found: archive/data/94881266361728
```
Reverting back to pytorch-lightning version 0.7.5 (big version gap.. I know) seems to fix the issue as does training on a single GPU. I'm wondering if there's something that got attached to the model somewhere in the version gap that I need to detach before pickling.

#### Code
I can't share code unfotunately.
   

#### What have you tried?
I've tried running on a single GPU or reverting lightning versions.

#### What's your environment?

 - OS: [e.g. iOS, Linux, Win] Ubuntu 20.04
 - Packaging [e.g. pip, conda] conda
 - Version [e.g. 0.5.2.1] 1.0.7 (w/ pytorch 1.7 and cuda 11)

**Comment by Borda** [comment]
@gsellers-tulco mind share some more info, the full error message you are getting?
We shall be back-compatible with even the 0.6 version but it seems as your saved model is corrupted... Are you able to load the model even with the very same version of PL which you used for saving?

**Comment by gsellers-tulco** [comment]
I don't think I can share more of the message without exposing code unfortunately. If I use PL 0.7.5, both saving and loading works fine with that version. It's only when I switched to the latest version that there were issues. I totally understand if that isn't enough info to figure out the issue. I might have time next week to play around with things more and get your more information about the problem. Thanks.

**Comment by jensam** [comment]
@gsellers-tulco did you resolve this issue? @Borda I am also seeing the same. 
I am leveraging distributed training using NCCL backend in kubernetes 1.17 (specifically kubeflow 1.1) with 1 master and multiple workers. I have downloaded the checkpoint file to my local machine '/checkpoints/epoch=0.ckpt' to do some testing. I am using pl.loggers.CSVLogger

```
Traceback (most recent call last):
  File "test.py", line 59, in <module>
    checkpoint = torch.load(PATH,map_location=torch.device('cpu'))
  File "/venv/lib/python3.8/site-packages/torch/serialization.py", line 584, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/venv/lib/python3.8/site-packages/torch/serialization.py", line 842, in _load
    result = unpickler.load()
  File "/venv/lib/python3.8/site-packages/torch/serialization.py", line 834, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/venv/lib/python3.8/site-packages/torch/serialization.py", line 822, in load_tensor
    storage = zip_file.get_storage_from_record(name, size, dtype).storage()
RuntimeError: [enforce fail at inline_container.cc:209] . file not found: archive/data/94728604392496
```

**Comment by awaelchli** [comment]
> I'm trying to save my model with torch.save() 

How do you do that? It is not advised to save like this on multi gpus. Make sure you only save on rank 0. 
If you can't share all the code can you at least share this line where you attempt to manually do saving?
Is the `ModelCheckpoint` not working for you?

> with the trainer and logger detached

what does that mean?

**Comment by awaelchli** [comment]
Are your checkpoint files corrupted?
https://stackoverflow.com/questions/64206070/pytorch-runtimeerror-enforce-fail-at-inline-container-cc209-file-not-fou
re-download again, check the file size

**Comment by jensam** [comment]
@awaelchli thanks! I must have been a little hasty getting the file last night. Sorry about that. Working fine now both with my script and your peek.py. I think this can be closed now. Thanks again :)

**Comment by awaelchli** [comment]
ok, that's great. I'll wait for a response from @gsellers-tulco the author of this issue before we close.

**Comment by gsellers-tulco** [comment]
@awaelchli I figured out the issue thanks to your comments. I wasn't making sure I was on rank 0 before saving, so that's what was corrupting the save file. I'm not sure why it was working with 0.7.5, but oh well. I might have missed it, but it might be helpful to include a note in the docs about checking rank 0 for DDP if you're using alternative saving methods. I'm using torch.save to bundle preprocessing with my model into 1 file. Thanks for help.

**Comment by awaelchli** [comment]
@gsellers-tulco You are right. @SeanNaren is taking care of this docs update already here #4660, good timing haha :)

**Comment by gsellers-tulco** [comment]
Awesome. Glad to hear it. Keep up the great work.
