### ISSUE TITLE
Close issues where author did not respond

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#4766]
Can we automate with GH actions?

https://github.com/probot/no-response
@Borda what do you think about this?

**Comment by Borda** [comment]
so you mean something else then stale?
stale gives warning after N days inactive and closes after another D days >> issue/PR is closed after N+D days
Do you want if an issue is marked as wait on author close it after D days or another custom delay?

**Comment by edenlightning** [comment]
Yes, exactly.

**Comment by tchaton** [comment]
Hey, any updates there ?
