### ISSUE TITLE
Average checkpoint

### ISSUE THREAD

**Issue by 7zhanghao** [PyTorchLightning/pytorch-lightning#4780]
How to average n checkpoints? Is it must be done by myself ?

**Comment by tchaton** [comment]
Hey @7zhanghao,

Thanks for using Pytorch Lightning. We currently don't  support n checkpoints average, but feel free to make a PR.
It don't think it should be too hard to implement.

Best regards,
Thomas Chaton.

**Comment by 7zhanghao** [comment]
Thanks a lot. I have a try.
