### ISSUE TITLE
Loading model

### ISSUE THREAD

**Issue by kargarisaac** [PyTorchLightning/pytorch-lightning#4789]
## 🐛 Bug

For loading the model, when I use the following command it seems it doesn't update the weights in the model:
```
model = LitModel()
model.load_from_checkpoint(checkpoint_path=<path to ckpt>)    
```
I need to use:
```
model = LitModel()
model = model.load_from_checkpoint(checkpoint_path=<path to ckpt>)
```

### Expected behavior
It should use the new weight for the model but it seems it doesn't work. In PyTorch when we use `model.load_state_dict()', it updates the model weights.

 - PyTorch Version : 1.7.0
 - OS: Ubuntu 20
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.8.5
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: RTX 2080Ti

**Comment by Borda** [comment]
@kargarisaac this `self.test_transforms` is a class constructor, the same as `pandas.read_csv` so the proper usage should be 
```python
model = LitModel.load_from_checkpoint(checkpoint_path=<path to ckpt>)
```
eventually, we can think about adding `inplace` argument but it may be even more confusing...
