### ISSUE TITLE
a read-from-here folder or file

### ISSUE THREAD

**Issue by Devansh-Walia** [PyTorchLightning/pytorch-lightning#4790]
## 🚀 Feature
I was trying to read the project I found it hectic to continue in a normal fashion, It would have been a great help if there was a file that directed me to start reading from this folder then that one &c.

### Motivation

This simple file could help and encourage others to read the project and also be less time consuming when doing so.
Correct me if I'm wrong and please help me see what my mistake was.

**Comment by Borda** [comment]
@Devansh-Walia I am not sure if I follow your suggestion, are you talking about some PL component or any other project using PL?

**Comment by Devansh-Walia** [comment]
actually no. let me try and explain. 
what I wanted to say was: A there should be a file that could direct people who are interested in reading the code of the project that highlights the workflow of the project. ( which module comes first which second)
