### ISSUE TITLE
checkpoint cannot be loaded without source code

### ISSUE THREAD

**Issue by Sushobhan04** [PyTorchLightning/pytorch-lightning#4792]
## 🐛 Bug

I saved a model using ModelCheckpoint callback. Later I tried to load it in a machine without the source code and it gave me an error saying it could not find the right model. I copy-pasted the source code in the new machine, it loads perfectly. I am using `save_weights_only=True`. I think this is a bug related to #2653, #4542

```
checkpoint_callback = ModelCheckpoint(
                        monitor="val_loss",
                        dirpath=os.path.join(model_dir, model_name),
                        filename="chkpt-{epoch:02d}",
                        save_top_k=1,
                        mode='min',
                        save_weights_only=True)

args.callbacks = [checkpoint_callback]
args.set other_attributes = attribute

trainer = pl.Trainer.from_argparse_args(args)
model = BaseModel(args)
trainer.fit(model, train_loader, val_loader)

Once the checkpoint is saved, I load it using this command:

checkpoint = torch.load("/home/some_dir/test0/chkpt-epoch=85.ckpt")
```
which gives me the following error:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-7-ab43e3d8ea3c> in <module>
----> 2 checkpoint = torch.load("/home/some_dir/test0/chkpt-epoch=85.ckpt")
      3 print(checkpoint.keys())

~/anaconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    583                     return torch.jit.load(opened_file)
    584                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
--> 585         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
    586 
    587 

~/anaconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    763     unpickler = pickle_module.Unpickler(f, **pickle_load_args)
    764     unpickler.persistent_load = persistent_load
--> 765     result = unpickler.load()
    766 
    767     deserialized_storage_keys = pickle_module.load(f, **pickle_load_args)

AttributeError: Can't get attribute 'BaseModel' on <module 'project_name' from '/home/some_dir/project_name/models.py'>
```

I have only been using Pytorch Lightning for about a week. But my experience with Pytorch was that `torch.save(model)` had similar issues, but not with `torch.save(model.state_dict())` which is what I expected with `save_weights_only` flag. Is there a different philosophy for the `save_weights_only` flag?

**Comment by Borda** [comment]
@Sushobhan04 I think that the problem is that you are sawing only weight any information about the model... it is like saving air for your wheel (for a car) without keeping info about the tear...
cc: @SeanNaren mind correct me... :]

**Comment by Sushobhan04** [comment]
@Borda Thanks for the response. But isn't it the philosophy behind saving only weights (torch.save(model.state_dict())) that it can be loaded in any machine without the knowledge of the model which generated it ? 

I want to train models in training environment and then deploy the model in a different environment. How to achieve that in pyotrch lightning ?

**Comment by Borda** [comment]
> @Borda Thanks for the response. But isn't it the philosophy behind saving only weights `torch.save(model.state_dict())` that it can be loaded in any machine without the knowledge of the model which generated it?

that is the example with air which can be cold/warn abut not shape, and wheel...

> I want to train models in a training environment and then deploy the model in a different environment. How to achieve that in pyotrch lightning ?

I see your point and what you want is exporting your model to torchscript or ONNX, pls see docs on [inference and production](https://pytorch-lightning.readthedocs.io/en/latest/production_inference.html)

**Comment by Sushobhan04** [comment]
@Borda While exporting to torchscript or ONNX is one solution, but it feels like a roundabout way as both my training and deployment is in pyotorch. 

I also found out that the default model checkpoint does not have this behavior. I could load the model saved by default (Trainer(checkpoint_callback=True) instead of explicit ModelCheckpoint callback), which makes me think its a bug rather than a design principle.

If it is indeed the desired behavior, can you tell me how should I modify my callback to achieve the default behavior ? Currently I am using:

checkpoint_callback = ModelCheckpoint(
                        monitor="val_loss",
                        dirpath=os.path.join(model_dir, model_name),
                        filename="chkpt-{epoch:02d}",
                        save_top_k=1,
                        mode='min',
                        save_weights_only=True)

args.callbacks = [checkpoint_callback]
args.set other_attributes = attribute

trainer = pl.Trainer.from_argparse_args(args)
model = BaseModel(args)
trainer.fit(model, train_loader, val_loader)

Also, the dictionary keys in the checkpoint does not have anything that explicitly require source code for loading. I have printed the keys here:

dict_keys(['epoch', 'global_step', 'pytorch-lightning_version', 'state_dict', 'hparams_name', 'hyper_parameters'])

However, current checkpoint loading requires source code and classes to match (to the exact path), which is a rather stringent requirement for data that does not depend on it. I still think its because the way the files are pickled which is forcing it to look for exact path.


I found pytorch-lightning very convenient for training pytorch models, especially in experimentation mode. However, its reproducibility in different environment is proving to be challenging.

**Comment by marios1861** [comment]
This is still an issue. I can not use my pytorch lightning models in deployment when saved with the callback.

**Comment by dscarmo** [comment]
> This is still an issue. I can not use my pytorch lightning models in deployment when saved with the callback.

Currently you can load with torch with: 

`torch.load(ckpt_path, map_location=torch.device('cpu'))["state_dict"]`

Use that as a state_dict for torch's load_state_dict

You can even access hyperparameters with the "hyper_parameters" key.

**Comment by thewh1teagle** [comment]
I'm facing the same issue in https://github.com/mush42/optispeech/issues/2#issuecomment-2339133370
