### ISSUE TITLE
Lower parity tests

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#4796]
## 🐛 Bug

We have observed that the trainer reached the initial threshold for parity
Note that we are still almost the same fast, but we may find some weeks spots

## Please reproduce using 

see GPU tests in the benchmark folder

### Additional context

actual version 1.0.7 has avg diff 0.84s

**Comment by edenlightning** [comment]
@Borda can you explain what is needed TODO here?

**Comment by Borda** [comment]
> @Borda can you explain what is needed TODO here?

this is @tchaton's task but I guess he already sent one fix...

**Comment by tchaton** [comment]
Closing this issue @Borda as we managed to improve parity tests.
