### ISSUE TITLE
add pytorch 1.7 network profiler to pytorch-lightning profiler

### ISSUE THREAD

**Issue by davinnovation** [PyTorchLightning/pytorch-lightning#4798]
## 🚀 Feature
Add profiling of network memory/time consumption ( above 1.7 pytorch ) - https://pytorch.org/tutorials/recipes/recipes/profiler.html

### Motivation

At 1.7 pytorch, they add pytorch profiler for measure consumption of network. What about binding this feature to pytorch-lightning?

### Pitch
Just an example...
```python
trainer = Trainer(..., network_profiler=True)
```

```text
# -------------------------  --------------  ----------  ------------  ---------
# Name                       Self CPU total   CPU total  CPU time avg  # Calls
# -------------------------  --------------  ----------  ------------  ---------
# model_inference            3.541ms         69.571ms    69.571ms      1
# conv2d                     69.122us        40.556ms    2.028ms       20
# convolution                79.100us        40.487ms    2.024ms       20
# _convolution               349.533us       40.408ms    2.020ms       20
# mkldnn_convolution         39.822ms        39.988ms    1.999ms       20
# batch_norm                 105.559us       15.523ms    776.134us     20
# _batch_norm_impl_index     103.697us       15.417ms    770.856us     20
# native_batch_norm          9.387ms         15.249ms    762.471us     20
# max_pool2d                 29.400us        7.200ms     7.200ms       1
# max_pool2d_with_indices    7.154ms         7.170ms     7.170ms       1
# -------------------------  --------------  ----------  ------------  ---------
```

### Alternatives

User add use pytorch 1.7's profilier manually in lightning module __init__ function

**Comment by awaelchli** [comment]
A new Trainer flag is probably too expensive here. We already have several profilers, so I suggest that this be implemented using the BaseProfiler class and then you pass it in 

```python
trainer = Trainer(..., profiler=profiler)
```
Would that work?

**Comment by awaelchli** [comment]
https://pytorch-lightning.readthedocs.io/en/stable/profiler.html

**Comment by davinnovation** [comment]
Thx for doc :) Maybe adding network profiler option for `AdvancedProfiler` could be better.

**Comment by davinnovation** [comment]
If no one is working on, may I assigned on this ticket

**Comment by edenlightning** [comment]
This was added in #5481
