### ISSUE TITLE
Adding a visualize method in LightningDataModule.

### ISSUE THREAD

**Issue by kartik4949** [PyTorchLightning/pytorch-lightning#4802]
## 🚀 Feature
So this feature will visualize your train/val/test data during training or you can explicitly call this method to visualize

It will visualize image data with transformations or without , it can help check the transformation sanity check for the problem statement you are solving.

Initialize it will visualize classification labels, later will add bbox ,keypoints , etc support.
### Motivation

Almost all framework lack this feature as default.
### Alternatives
can add the function method in utils or visualize module.
and just use it inside visualize method of lightingdatamodule.
### Additional context
Example Usage

```
 parser = ArgumentParser()
 parser = MNISTDataModule.add_argparse_args(parser)
 dm = MNISTDataModule.from_argparse_args(args)
 # visualize
 dm.visualize(data='train', samples=10, index = 'random', save='visualize_train/', transforms=True)
 # saves 10 random images in the passed path with transformations.
```

**Comment by rohitgr7** [comment]
I believe this is specific to classification or image-data related tasks only, not a general one. You can still add your own methods and use them in LightningDataModule. If it's required I believe it's better suited for the bolts library.

**Comment by kartik4949** [comment]
> I believe this is specific to classification or image-data related tasks only, not a general one. You can still add your own methods and use them in LightningDataModule. If it's required I believe it's better suited for the bolts library.

Yeah didn't knew about bolt, will move this to bolt!, thanks
