### ISSUE TITLE
transform module with explicit transformations coupled with torch.transforms

### ISSUE THREAD

**Issue by kartik4949** [PyTorchLightning/pytorch-lightning#4804]
## 🚀 Feature
Thinking to file a pr for transform module which consist inhouse transformations which are not present torch.transforms.
### Motivation
Gridmask, mosaic, mixup, cutmix, etc
above augmentations are missing in most of the frameworks and they are de facto for kaggle, general computer vision solutions, etc

### Reference
my library which consist all of this module -> github.com/kartik4949/TensorPipe

**Comment by ydcjeff** [comment]
@kartik4949 this would be more suited with bolts.

**Comment by kartik4949** [comment]
@ydcjeff makes sense, will look what bolts is,
thanks
