### ISSUE TITLE
Apply import formatter `isort`

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning#4805]
## 🚀 Refactoring
As `isort` has been added to ci in #4242, we now need to apply the formatter step by step i.e. a submodule per PR (recommended in https://github.com/PyTorchLightning/pytorch-lightning/pull/4242#issuecomment-724323170 by @Borda)

<details>
<summary>Steps</summary>

For each PR:
1. choose one submodule from below list and apply `isort` to it
2. remove the corresponding line in `pyproject.toml`
3. make sure `isort --check` passes

</details>

<details>
<summary>Progress</summary>
The rest of the submodules should be done by @arnaudgelas.

The followings are PL submodules.
- [x] `pytorch_lightning/*.py` >> #4717
- [ ] `pytorch_lightning/accelerators/`
- [ ] `pytorch_lightning/callbacks/`
- [ ] `pytorch_lightning/cluster_environments/`
- [ ] `pytorch_lightning/core/`
- [ ] `pytorch_lightning/distributed/`
- [ ] `pytorch_lightning/loggers/`
- [ ] `pytorch_lightning/metrics/`
- [ ] `pytorch_lightning/overrides/`
- [ ] `pytorch_lightning/plugins/`
- [ ] `pytorch_lightning/profiler/`
- [ ] `pytorch_lightning/trainer/`
- [ ] `pytorch_lightning/tuner/`
- [ ] `pytorch_lightning/utilities/`

The followings are tests.
- [x] `tests/*.py` >> #4717
- [ ] `tests/backends/` >> #5430
- [ ] `tests/base/` >> #5429
- [ ] `tests/callbacks/` >> #5428
- [x] `tests/checkpointing/` >> #5427
- [x] `tests/core/` >> #5426
- [ ] `tests/loggers/` >> #5425
- [ ] `tests/plugins/` >> #5422
- [ ] `tests/metrics/` >> #5424
- [ ] `tests/models/` >> #5423
- [ ] `tests/trainer/` >> #5421
- [ ] `tests/tuner/`
- [x] `tests/utilities/` >> #5420

The followings are other python files.
- [x] `*.py` (#4242)
- [x] `docs/` (#4242)
- [x] `pl_examples/` (#5291)

<details>

**Comment by akihironitta** [comment]
Would you consider adding the following labels to this issue so that new contributors can work on this issue...?
good first issue
Refactors and code health
Priority P2
tests / CI

**Comment by rohitgr7** [comment]
it's a pre-commit hook right? wouldn't it be done automatically when someone makes changes to a file in a PR just before it gets merged??

otherwise, I would suggest doing it all at once in a single PR just before the next release (v1.1, I suppose).

**Comment by akihironitta** [comment]
@rohitgr7 Yes, #4242 added `isort` to pre-commit as well as to CI testing, but I guess that not everyone is using pre-commit...

Also, #4242 actually tried to apply isort to all files at once, but I think we agreed to split the PR to avoid unexpected errors as @Borda mentioned in the PR:
> we just need to make it in smaller steps, like per PL/subpackage...
> having one huge change can overlook some minor issues and in general, it is a recommended strategy by williamFalcon to have PRs easier to check and maintain, also it breaks all waiting PRs...

**Comment by rohitgr7** [comment]
> but I guess that not everyone is using pre-commit

oh okay, I thought pre-commit hook runs before a PR get's merged. Is there something like pre-merge hook or something which always runs on the changed files before a PR get's merged. If there is one I feel it will be useful to avoid any import formatting issues in the future.

**Comment by Borda** [comment]
> Is there something like a pre-merge hook which always runs on the changed files before a PR get's merged. If there is one I feel it will be useful to avoid any import formatting issues in the future.

yes, that is the CI as @akihironitta mentioned, but at this moment we have almost all files ignored so when a file is fixed we remove it from the ignore lost and since that time it shall be checked with each PR before merge...

**Comment by rohitgr7** [comment]
Oh, got it

**Comment by hassiahk** [comment]
Happy to help with this, if more helping hands are needed.

**Comment by rohitgr7** [comment]
sure go ahead. @hassiahk

**Comment by hassiahk** [comment]
@rohitgr7, I will start from the bottom `utilities` so that I don't clash with @akihironitta, since I think @akihironitta is working on the top sections.

**Comment by akihironitta** [comment]
@hassiahk As the isort config may change in #4960, would you mind waiting for #4960 to be closed?

**Comment by hassiahk** [comment]
@akihironitta sure, definitely.

**Comment by akihironitta** [comment]
As #4960 is closed, we all can start to work on this issue :) cc: @hassiahk

**Comment by arnaudgelas** [comment]
I have all commits ready to fix isort (~20). Should I create 20 PRs for that?
Here is the first one: https://github.com/PyTorchLightning/pytorch-lightning/pull/5398

**Comment by Borda** [comment]
> I have all commits ready to fix isort (~20). Should I create 20 PRs for that?
> Here is the first one: #5398

Great!, yes by me, just be aware they shall go `release/1.2-dev` not master
cc: @akihironitta

**Comment by arnaudgelas** [comment]
Actually, we first need to merge #5408 to make `pre-commit` and `isort` works properly for anyone.

**Comment by awaelchli** [comment]
I noticed that isort and black change import formatting differently, which leads to unnecessary file changes. Maybe consider this configuration: https://black.readthedocs.io/en/stable/compatible_configs.html#isort

**Comment by akihironitta** [comment]
We are actually introducing `yapf` instead of `black` in Bolts since `yapf` is highly configurable as discussed with @Borda in https://github.com/PyTorchLightning/pytorch-lightning-bolts/issues/482. We plan to first try `yapf` in Bolts and to apply it to PL in the future, so we might not need to update the config now.

**Comment by akihironitta** [comment]
Once @arnaudgelas updates all the PRs, I'll start to check them and mark them as ready-to-go. https://github.com/PyTorchLightning/pytorch-lightning/pull/5420#issuecomment-757692544 https://github.com/PyTorchLightning/pytorch-lightning/pulls?q=is%3Apr+is%3Aopen+isort

**Comment by akihironitta** [comment]
> Once @arnaudgelas updates all the PRs, I'll start to check them and mark them as ready-to-go. [#5420 (comment)](https://github.com/PyTorchLightning/pytorch-lightning/pull/5420#issuecomment-757692544) https://github.com/PyTorchLightning/pytorch-lightning/pulls?q=is%3Apr+is%3Aopen+isort

@Borda I just realised that I'm not authorised to relabel issues/PRs in PL repo, so if you'd like me to do so, add me to the team on GitHub :]
