### ISSUE TITLE
Lightning Model module , get_model_size method

### ISSUE THREAD

**Issue by kartik4949** [PyTorchLightning/pytorch-lightning#4807]
## 🚀 Feature
A get_model_size method in model module which return model size in megabyte based on precision.

### Motivation
Just thinking out loud..

### Additional context
We can add this in mode summary too
```
# ------------
# model
# ------------
model = LitClassifier(args.hidden_dim, args.learning_rate)
>> print(model.size)
>> 104.14281 Mb with fp32.
```

**Comment by awaelchli** [comment]
That's a fun suggestion :) 
I suppose a method is not suitable since this is just a information query and does not muatate the state of the model.

**Comment by kartik4949** [comment]
Property i mean :)
