### ISSUE TITLE
Getting Started with Model Parallelism?

### ISSUE THREAD

**Issue by siddk** [PyTorchLightning/pytorch-lightning#4824]
I'm looking to combing PyTorch-Lightning with existing tools for Model Parallelism -- FairScale (https://github.com/facebookresearch/fairscale), TorchGPipe (https://github.com/kakaobrain/torchgpipe) and even some of the Model Parallelism present in MegatronLM (https://github.com/NVIDIA/Megatron-LM).

Is there a minimal example that exists about how to get Lightning Modules to play nicely with any of the above external libraries? Navigating through some of the WIP PRs I also see plans of including model parallelism into Lightning directly (which would be great!).

What's a good place to start here?

**Comment by ananyahjha93** [comment]
@SeanNaren

**Comment by JayThibs** [comment]
I'm wondering about this too. @siddk did you come across anything since your initial post?
