### ISSUE TITLE
How to use pytorch-lightning to train a detectron2 model?

### ISSUE THREAD

**Issue by hiyyg** [PyTorchLightning/pytorch-lightning#4830]
The trainers in pytorch-lightning are really cool, but how can I use them to train a detectron2 model? Is there any example that I can follow?

**Comment by tchaton** [comment]
Hey @hiyyg,

Not I am aware of. You could use the model implementation from https://github.com/facebookresearch/detectron2 and integrate it easily in Lightning.

Have a look at bolt from some inspiration: https://github.com/PyTorchLightning/pytorch-lightning-bolts

Best regards,
Thomas Chaton.

**Comment by hiyyg** [comment]
Thanks! It would be great if there is a minimal official example as this could attract more people in the detection field.

**Comment by Robotatron** [comment]
Can't one simply instantiate the model with Detectron2, which yields you a Pytorch Model and then train with Pytorch Lightning?
