### ISSUE TITLE
Questions about GPUStatsMonitor callback and GPU utilization

### ISSUE THREAD

**Issue by bartmch** [PyTorchLightning/pytorch-lightning#4833]
I'm logging the GPU activity using the default values. I'm getting the following plots on my tensorboard:
![image](https://user-images.githubusercontent.com/10415569/100073822-69621480-2e57-11eb-8c22-36098871e4f1.png)

A couple of questions:

1. Is the utilization really zero at specific time points (jigsaw) or is it just plotting zero's in-between epochs?
2. If my utilization is really zero at specific points, how can I make sure this doesn't happen? What about memory utlization?
3. As you can see in the first two graphs, the memory allocation is above 75%, but the memory utilization shows 16-18%. Why do these two numbers don't correspond?
4. Is there a similar callback for CPU? E.g.:If I want to check CPU utilization in-between training cycles (e.g.: to check data loader preparation) 
5. Any recommendations on how to set num_workers on an 8-GPU system?

Thanks!

**Comment by tchaton** [comment]
Hey @bartmch,

1. We use internally `torch.cuda.empty_cache()` to free memory, it could explain the 0

3. Not sure, it will need more investigations

4. I don't think we do, but it could easily be implemented. Feel free to submit a PR 👍 

5. Try out Lightning tuner. It might help. The best is to play with batch_size and num_workers, and find the best combinaison for your dataset / model.

Best,
T.C
