### ISSUE TITLE
Use custom batch dataloader with DDP

### ISSUE THREAD

**Issue by floboc** [PyTorchLightning/pytorch-lightning#4836]
Hello,
In our project, we use a custom data loader like so:
```
class BatchDataLoader(torch.utils.data.dataloader.DataLoader):
    def __init__(self, ds, batch_size, shuffle, num_workers=0):
        inner_sampler = RandomSampler(ds) if shuffle else SequentialSampler(ds)
        sampler = BatchSampler(inner_sampler, batch_size, False)
        super().__init__(ds, batch_size=None, sampler=sampler, num_workers=num_workers)
```

We use this custom dataloader so that the `__getitem__` method is directly called with the list of batch indices and returns a full batch instead of single items. We need this because for some technical reasons, the `__getitem__` method is way way faster when accessing a batch of data items rather than single ones. This has been working perfectly fine so far until we started looking into using ddp for training our model.

By default Lightning setup its own sampler for distributed training. We can override this behaviour with replace_sampler_ddp=False but then our custom sampler would be used, whereas it is not made for distributing.

If we wish to make our own custom distributed version of it, then how can we retrieve the distributed context from lightning? Is there a way to know if we are in a distributed context, and if so, how many nodes, etc? Can this be done from a Lightning data module, as this is where we instantiate the data loaders? I tried using `torch.distributed,is_available()` as a first step. While this passes on Windows, this call fails with `AssertionError: Default process group is not initialized` on Linux if we are not in a distrbuted context (for instance training on a single GPU). For info, I'm using Lightning 1.0.5 with PyTorch 1.5.1. We wish to setup our sampler automatically, without the user having to specify extra parameters.

Or do you see a way to achieve the same behaviour (getting batches of indices in the `__getitem__` method of the dataset) while still benefitting from the default DistributedSampler that Lightning setup? I thought of wrapping my original dataset in another one that would create "buckets" of data, but then how can I make sure the dataset is reshuffled each epoch so that the buckets don't always have the same content?

Thanks for your help :)

**Comment by floboc** [comment]
To give more information, here is what I thought of when mentioning to wrap the dataset:

```
class BatchedDataset(Dataset):
    def __init__(self, source: Dataset, batch_size: int = 1024, drop_last: bool = True):
        super().__init__()

        self.source = source
        self.batch_size = 1024
        self.drop_last = drop_last
        self.batch_indices = None
        self.shuffle()

    def shuffle(self):
        self.batch_indices = torch.randperm(len(self.source)).tolist()

    def __getitem__(self, index):
        start_idx = index * self.batch_size
        end_idx = min(len(self.source), start_idx + self.batch_size)
        batch_indices = self.batch_indices[start_idx:end_idx]
        batch = self.source.__getitem__(batch_indices)
        return batch

    def __len__(self):
        if self.drop_last:
            return len(self.source) // self.batch_size
        else:
            return (len(self.source) + self.batch_size - 1) // self.batch_size
```

This could work, however, several questions remain:
- How to make sure shuffle() is called at the end or beginning of each epoch, without having to setup very specific training hooks. Our code is quite general and might handle other dataset that don't require this. I would like to fullu setup the Dataset and DataLoader in my data module class
- How to make sure this is working as expected across multiple nodes / process, ie making sure that it is synchronized (shuffle either called on main process and then synced, or ensuring determinism) ?

Thanks :)

**Comment by floboc** [comment]
Me again :)
I found the current workaround to make sure my dataset is shuffled at each epoch by adding this to my module class:

```
    def on_train_epoch_start(self) -> None:
        try:
            dataset = self.trainer.train_dataloader.dataset
            dataset.set_epoch(self.current_epoch)
        except Exception:
            pass
        return super().on_train_epoch_start()
```

I'm still looking for the correct way to achieve this however, all this feels very hacky, and I had to make my module aware of this specific case which doesn't seem to be a good idea

**Comment by s-rog** [comment]
I've looked into custom distributed samplers in pytorch before and all solutions I found are pretty hacky.

Lightning actually calls `set_epoch` as well for distributed samplers, it's just done automatically from the backend.

**Comment by tchaton** [comment]
Hey @floboc,

To make slightly cleaner, you could check the instance of your dataset instead of using a try / empty except. You might miss some errors there.

I guess the only solution would be to create a LigthiningDistributedSampler you inherit from, and we would call `.set_epoch(self.current_epoch)` for you. 

But I am not really sure it would be worth it.

Best,
T.C
