### ISSUE TITLE
Get AWS open-source for GPU testing

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#486]
To have full GPU testing we shall integrate some solution like Korina... 
https://twitter.com/kornia_foss/status/1193093489371865089

https://aws.amazon.com/opensource
Amazon is part of the open source community: we've been contributing to hundreds of projects for over a decade. We continue to widen our open source collaboration, increasing code contributions and helping to sustain the overall health of open source. We are committed to working with, supporting, and contributing to new and existing open source projects that provide value to our customers and partners.

https://aws.amazon.com/blogs/opensource/aws-promotional-credits-open-source-projects
- To be eligible, you will need an active AWS Account. 
- Your software project must also be licensed under an OSI-approved license, but please still apply if the commonly-used licenses in your project’s space (e.g., open data) are not OSI-approved!
- Use the application form to provide complete details including your account number, the amount of credits being requested, and a brief description of how the credits will be used. 
- The credits will expire after one year. 
- Applications will be reviewed within 10-15 business days. 
- Assuming that they meet the basic eligibility requirements above, we will be examining applications on the basis of their relevance to AWS and its customers.

**Comment by Borda** [comment]
@williamFalcon ^^

**Comment by williamFalcon** [comment]
@Borda working with circleCI for now

**Comment by Borda** [comment]
@williamFalcon We already have CircleCI config... or what do you mean?

**Comment by williamFalcon** [comment]
circleci for gpu support

**Comment by Borda** [comment]
We are going to use `g3.8xlarge` instance an instal own Drone.io instance

**Comment by Borda** [comment]
take inspiration from
https://github.com/facebookresearch/pytorch3d/blob/master/.circleci/config.yml

**Comment by luiscape** [comment]
@Borda let me know if you need any support here. :)

**Comment by Borda** [comment]
@williamFalcon do we have an update, did we get it, meaning the free credit and instance with two GPUs? So far I remember the instance was pending...
