### ISSUE TITLE
DDP Logdir Multiple Runs Bug

### ISSUE THREAD

**Issue by lukasfolle** [PyTorchLightning/pytorch-lightning#4866]
## 🐛 Bug

Using `accelerator="ddp"` and running a pl Experiment mulitple times each time creating a new Trainer, the log version number is handled in a wrong way.
Instead of creating folder "version_2" after running "version_1" a folder with name "2" is created.
To fix this, after the training, `os.environ.pop("PL_EXP_VERSION")` has to be executed.

## Please reproduce using [the BoringModel and post here](https://colab.research.google.com/drive/1GFQ6doCWl_aTdBaBVOgTf1dTs_qZV0sg?usp=sharing)

https://colab.research.google.com/drive/1GFQ6doCWl_aTdBaBVOgTf1dTs_qZV0sg?usp=sharing

### Expected behavior

Increase "version_1" to "version_2".

**Comment by lukasfolle** [comment]
@Borda Any updates on this?

**Comment by awaelchli** [comment]
@lukasfolle is this still a problem? You provided a colab example but ddp is not supported in notebooks. 
Note that the behavior is different when you run your script multiple times vs. when you call Trainer.fit multiple times in the same script.

**Comment by lukasfolle** [comment]
Please have a look at the code in the Colab. The issues arises when looping over trainer.fit().

**Comment by awaelchli** [comment]
Looking into fixing this now.

```python
import os
import torch
from torch.utils.data import Dataset
from pytorch_lightning import LightningModule, Trainer


class RandomDataset(Dataset):

    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):

    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def loss(self, batch, prediction):
        # An arbitrary loss to have a loss that updates the model weights during `Trainer.fit` calls
        return torch.nn.functional.mse_loss(prediction, torch.ones_like(prediction))

    def training_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"loss": loss}

    def training_step_end(self, training_step_outputs):
        return training_step_outputs

    def training_epoch_end(self, outputs) -> None:
        torch.stack([x["loss"] for x in outputs]).mean()

    def validation_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"x": loss}

    def validation_epoch_end(self, outputs) -> None:
        torch.stack([x['x'] for x in outputs]).mean()

    def test_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        self.log('fake_test_acc', loss)
        return {"y": loss}

    def test_epoch_end(self, outputs) -> None:
        torch.stack([x["y"] for x in outputs]).mean()

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1)
        return [optimizer], [lr_scheduler]


def run():
    train_data = torch.utils.data.DataLoader(RandomDataset(32, 64), batch_size=2, num_workers=0)
    val_data = torch.utils.data.DataLoader(RandomDataset(32, 64), batch_size=2, num_workers=0)
    test_data = torch.utils.data.DataLoader(RandomDataset(32, 64), batch_size=2, num_workers=0)

    for _ in range(2):
        model = BoringModel()
        trainer = Trainer(
            max_epochs=1,
            progress_bar_refresh_rate=20,
            accelerator="ddp",
            gpus=2
        )
        trainer.fit(model, train_data, val_data)
        trainer.test(test_dataloaders=test_data)
        print(os.environ.get("PL_EXP_VERSION"))
        del trainer, model


if __name__ == '__main__':
    run()

```

**Comment by shijianjian** [comment]
This bug has not been fixed yet. I wanted to save some additional CSVs (e.g. prediction outcomes), I encountered an error about the folder path of ```lightning_logs/0```

```python
def validation_epoch_end(self, outputs) -> None:
        print(self.logger.log_dir)
```

**Comment by Borda** [comment]
@awaelchli shall we reopen it?

**Comment by awaelchli** [comment]
Yes. I just realized I fixed the reported issue with the log dir folder created but there is still an issue with accessing `trainer.log_dir` by the user as pointed out by @shijianjian

**Comment by edenlightning** [comment]
@awaelchli status?

**Comment by awaelchli** [comment]
It is very tricky for DDP here. The initial "fix" I had in mind won't work with the examples provided here.
The problem is that there we have several trainers run sequentially, but Lightning can't know if the current trainer is the very first one in the script or if we had already run one. 

The following two situations:
A)

```py
trainer = Trainer()
trainer.fit() # PL_EXP_VERSION = 0
trainer.test() # PL_EXP_VERSION = 0 (should not reset)
```

B)
```py
trainer = Trainer() 
trainer.fit() # PL_EXP_VERSION = 0

trainer = Trainer() 
trainer.test() # PL_EXP_VERSION = 0 or 1?
```


From the perspective of Lighting on a per process scoope, A) and B) are indistinguishable. So I'm a bit stuck here.

**Comment by edenlightning** [comment]
@SeanNaren mind taking a look? @awaelchli would like a second opinion

**Comment by SeanNaren** [comment]
@awaelchli I agree that this is something lightning should not do by default. If the user specifies the version we need to be careful not to make any changes to the set version (i.e do not increment).

Just throwing ideas out there, how about some form of auto-increment function that can be called `on_fit_end`?

**Comment by awaelchli** [comment]
@shijianjian The PR #7403 is going to fix this issue. 
Two small notes about your use case:

```python
 def validation_epoch_end(self, outputs) -> None:
        print(self.logger.log_dir)
```

1) Here it would be better to access `self.trainer.log_dir` because that is universal for all loggers. 
2) If you are accessing and writing to the log_dir, it would be best to do that with a guard

```python
if trainer.global_rank == 0:
    # access logdir on rank 0 only
```

to avoid race conditions.
