### ISSUE TITLE
How to handle multiple batches？

### ISSUE THREAD

**Issue by Defiler24** [PyTorchLightning/pytorch-lightning#4867]
## Code
train_loaders = [
DataLoader(env,  batch_size=32, num_workers=8) 
for i, env in enumerate(train_datasets)
]

train_batch_iter = zip(*train_loaders)

## About 
DataLoader is a function: 
iter(torch.utils.data.DataLoader(...))

## Question
What should I do to use “train_batch_iter” in training step or how should I adjust?

**Comment by awaelchli** [comment]
multiple train datasets are not supported atm, a feature is in development here: #1959 
For now, you can wrap your datasets into a custom dataset that concatenates the data.

**Comment by awaelchli** [comment]
https://pytorch-lightning.readthedocs.io/en/stable/multiple_loaders.html
