### ISSUE TITLE
How to write log info to txt file

### ISSUE THREAD

**Issue by xiadingZ** [PyTorchLightning/pytorch-lightning#4876]
How to save each epoch's `self.log` info to txt file, in the meantime keeping the tensorboard logs.
I want to log some metric value of each epoch, and my debug text info. such as `self.log('This is a text info')`

**Comment by awaelchli** [comment]
Something like [this](https://pytorch-lightning.readthedocs.io/en/stable/generated/pytorch_lightning.loggers.CSVLogger.html#pytorch_lightning.loggers.CSVLogger)?

**Comment by xiadingZ** [comment]
Yes, I want to have multi loggers,   one graph-based, such tensorboard, one text-bast, such as csv or txt.  Maybe text is more suitable, such that I can log string info and time info ...

**Comment by carmocca** [comment]
Well, you have a few options:

1. Implement a custom Logger to write text to your liking.
2. Use Python's `logging` with a [FileHandler](https://docs.python.org/3/library/logging.handlers.html#filehandler)
3. Just printing to the stdout or stderr stream and redirecting it to a file when you run your code.

Depends on what you actually want to log.

**Comment by zhutmost** [comment]
@xiadingZ Hi maybe you can have an eye on [here](https://github.com/zhutmost/neuralzip/blob/master/apputil/progressbar.py). I re-implement a ProgressBar, and it can be used with a FileHandler & Stream logger.

**Comment by xiadingZ** [comment]
Thanks.  I wish pytorch-lightning can support text logger such as `logging`, and handle `ddp` things by default. User only need to call `self.trainer.text_logger.log(...)`.  Everyone can use `logging` by default, no need to install `tensorboard`  and so on ... to visualize their result.

**Comment by zhutmost** [comment]
@xiadingZ My logging implementation with ddp:
1. the process with `LOCAL_RANK == 0`, the logger('lightning') logs to Stream (i.e. std_out) and FileHandler ('rank0.log').
2. the processes with `LOCAL_RANK != 0`, the logger('lightning') only logs to FileHandler ('rankN.log', N=1,2,3,...).

To achieve this, you'd better to re-implement a Progressbar to replace the build-in tqdm one.

**Comment by justusschock** [comment]
@xiadingZ we already have this with the csv logger (as @awaelchli mentioned). If you want another format we would welcome a PR for that (you should be able to reuse a lot from the csv logger code).

**Comment by addisonklinke** [comment]
@awaelchli I get how the CSV logger sounds similar to the text logging that @xiadingZ requested, but I cannot tell how it would be used to log simple text strings (either to console or a file). 

Looking at the source code, it seems like all the Lightning loggers only support `log_metrics()` and `log_hparams()` methods which both accept a `dict` parameter. How then can a user accomplish `self.log('This is a text info')` where a `str` parameter is passed instead?

**Comment by awaelchli** [comment]
maybe you are simply looking for the `self.print` in the LightningModule? This will print directly to the console. But you need to turn off the progress bar otherwise things get mixed up.

The underlying loggers methods can be accessed by `self.logger.experiment.whatever_this_logger_supports("your text")`.

**Comment by addisonklinke** [comment]
Thanks for the suggestion - `self.print` would definitely get the job done. Using a specific logger method will not work if you have more than one logger configured though (unless all of them support the same `.whatever_this_logger_supports()` method).

For reference of future readers, I made a [discussion post](https://github.com/PyTorchLightning/pytorch-lightning/discussions/6182) that goes into additional detail. Overall, I think custom callbacks are a nice way to consume the `trainer.callback_metrics` produced by `self.log()` and format them for console printing. This lets the user have console logs + whatever ML experiment framework they want (i.e. Tensorboard, Comet, Weights and Biases, etc). My current solution doesn't generalize well across metric names, but it works fine in my situation. If I can make it more general eventually, I will plan to submit a PR with the callback implementation

**Comment by carmocca** [comment]
@FrancescoSaverioZuppichini you can totally use Python's stdlib `logging` and add a `FileHandler` to write to a file.
