### ISSUE TITLE
Tensorboard log_graph does not seem to do anything

### ISSUE THREAD

**Issue by pierresegonne** [PyTorchLightning/pytorch-lightning#4885]
## 🐛 Bug

While exploring Tensorboard's logging features I experimented with the `log_graph` function, that was added after #2915 (issue) and #3003 (PR). 

According to the docs the function has the following signature `log_graph(model, input_array=None)`

So I tried to call it doing, inside my PL module:

```python
...

def __init__(self, ..):
    ...
    self.example_input_array = torch.rand((10, self.input_dim))
    ...

def test_step(self, batch, batch_idx):
    ...
    self.logger.log_graph(self)
    ...
```

without any success. No error message is displayed and Tensorboard does not recognise any logged graph.

Nevertheless if I change my code to:

```python
...

def __init__(self, ..):
    ...
    self.example_input_array = torch.rand((10, self.input_dim))
    ...

def test_step(self, batch, batch_idx):
    ...
    self.logger.experiment.add_graph(self, self.example_input_array)
    ...
```

Which is what the `log_graph` function is supposed to call, then I do see my graph appearing in Tensorboard.

### To Reproduce

Execute the following gist

https://gist.github.com/pierresegonne/091a1d0e163f01a6f1c944c1bc4e9cf6

And change lines 123/124 to see the graph being logged or not

### Environment

```txt
* CUDA:
        - GPU:
        - available:         False
        - version:           None
* Packages:
        - numpy:             1.19.2
        - pyTorch_debug:     True
        - pyTorch_version:   1.7.0
        - pytorch-lightning: 1.0.2
        - tqdm:              4.50.2
* System:
        - OS:                Darwin
        - architecture:
                - 64bit
                - 
        - processor:         i386
        - python:            3.8.6
        - version:           Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64
```

**Comment by rohitgr7** [comment]
you need to set `log_graph=True` in `TensorboardLogger` instance. It's `False` by default.
https://github.com/PyTorchLightning/pytorch-lightning/blob/f677efe61ecf28af1e5216a5baf502be6f394564/pytorch_lightning/loggers/tensorboard.py#L79
https://github.com/PyTorchLightning/pytorch-lightning/blob/f677efe61ecf28af1e5216a5baf502be6f394564/pytorch_lightning/loggers/tensorboard.py#L195-L207

**Comment by pierresegonne** [comment]
Oh right, I don't know how I missed that! Thanks a lot!

**Comment by getgaurav2** [comment]
@rohitgr7  - I am facing similar issue while training a model using Sagemaker .  I tried both the 

> you need to set `log_graph=True` in `TensorboardLogger` instance. It's `False` by default. https://github.com/PyTorchLightning/pytorch-lightning/blob/f677efe61ecf28af1e5216a5baf502be6f394564/pytorch_lightning/loggers/tensorboard.py#L79 https://github.com/PyTorchLightning/pytorch-lightning/blob/f677efe61ecf28af1e5216a5baf502be6f394564/pytorch_lightning/loggers/tensorboard.py#L195-L207

@rohitgr7  - I am facing similar issue while training a model using AWS Sagemaker .  I added both of these things in my code. Could there be anything different in training  the model in Sagemaker ?

**Comment by amitbcp** [comment]
@pierresegonne have set log_graph=True but still go does not come up.
On using `self.logger.experiment.add_graph(self, self.example_input_array) `
 the following error comes
```

`LightningModule.use_amp` was deprecated in v1.6 and is no longer accessible as of v1.8. Please use `Trainer.amp_backend`.
Error occurs, No graph saved
*** RuntimeError: `LightningModule.use_amp` was deprecated in v1.6 and is no longer accessible as of v1.8. Please use `Trainer.amp_backend`.
```

**Comment by fingoldo** [comment]
To be honest I still don't see anything related in tensorboard, despite initiating TensorboardLogger with log_graph=True.
