### ISSUE TITLE
metrics.classification.ConfusionMatrix() not available

### ISSUE THREAD

**Issue by qwertimer** [PyTorchLightning/pytorch-lightning#4889]
## 🐛 Bug

The ConfusionMatrix class called from metrics.classification.ConfusionMatrix is not working. When trying to import class it fails.

To fix issue the __init__.py file of the metrics module needs to include a comma following the ConfusionMatrix line like so

```
  from pytorch_lightning.metrics.classification import (                               
      Accuracy,                                                                        
      Precision,                                                                       
      Recall,                                                                          
      FBeta,                                                                           
      F1,                                                                              
     ConfusionMatrix,                                                                 
  )             
```

This issue occurs on the latest versions of pytorch_lightning.

**Comment by ydcjeff** [comment]
In the latest stable versions of pytorch lightning (1.0.8), there is no class interface of `ConfusionMatrix` yet.
It will be landed on 1.1 release. If you want to use it now, please install from master.
`pip install git+https://github.com/PyTorchLightning/pytorch-lightning.git@master -U`
