### ISSUE TITLE
[LoggerCollection.log_hyperparams] [no optional argument metrics]

### ISSUE THREAD

**Issue by emilemathieu** [PyTorchLightning/pytorch-lightning#4899]
## 🐛 Bug

Hello ! :)

The following method [TensorBoardLogger.log_hyperparams](https://github.com/PyTorchLightning/pytorch-lightning/blob/1.0.8/pytorch_lightning/loggers/tensorboard.py#L149) has an optional argument `metrics ` yet [LoggerCollection.log_hyperparams](https://github.com/PyTorchLightning/pytorch-lightning/blob/1.0.8/pytorch_lightning/loggers/base.py#L353) doesn't, yielding an error when relying on several loggers including `TensorBoardLogger` and using this optional argument.

Is that behaviour expected? Shouldn't all loggers have this optional argument?

### To Reproduce
```python
logger1 = pl.loggers.TensorBoardLogger(save_dir="logs")
logger2 = pl.loggers.CSVLogger(save_dir="logs")
pl.Trainer(logger=[logger1, logger2], etc)
```
Yields `TypeError: log_hyperparams() got an unexpected keyword argument 'metrics'`.

### Environment

* CUDA:
	- GPU:
	- available:         False
	- version:           10.2
* Packages:
	- numpy:             1.19.4
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0
	- pytorch-lightning: 1.0.6
	- tqdm:              4.53.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.8.6
	- version:           #1 SMP Tue Aug 11 16:36:14 UTC 2020

**Comment by SkafteNicki** [comment]
@emilemathieu I definitly see the problem, but does it happen while calling `trainer.fit` or do you call `logger.log_hyperparams` yourself?

**Comment by emilemathieu** [comment]
@SkafteNicki I have
```python
def test_epoch_end(self, outputs):
    self.logger.log_hyperparams(self.hparams, metrics={'hp_metric': self.hp_metric})
```
to get the hyperparameters in tensorboard, which get called with `result = trainer.test(datamodule=data_module)`.

**Comment by SkafteNicki** [comment]
@emilemathieu so tensorboard is the odd one here as it is the only logger that has the extra `metrics` argument. Therefore, instead of changing the remaining loggers to comply with tensorboard, I would advice that you just call that logger directly:
`self.logger[0]...`
Assuming here that tensorboard is the first logger you initialize with.

**Comment by emilemathieu** [comment]
Thanks @SkafteNicki! You're right it makes more sense to do so :)
I'm closing the issue.
