### ISSUE TITLE
Formatting issues in metric docs

### ISSUE THREAD

**Issue by s-rog** [PyTorchLightning/pytorch-lightning#4908]
There are some formatting issues with the arguments (the incorrect blocks and apostrophes). I've yet to go through the whole metrics docs, noting them here as I find them for when I get a chance to fix them or if anyone wants to help!

Incorrect:
https://pytorch-lightning.readthedocs.io/en/latest/metrics.html#f1-func
https://pytorch-lightning.readthedocs.io/en/latest/metrics.html#fbeta-func

Correct examples:
https://pytorch-lightning.readthedocs.io/en/latest/metrics.html#iou-func
(among others)

Related: #4837

Edit:
Also noticed that F1 has an unused beta arg that shouldn't be there (we have fbeta), though that's probably a separate issue.

**Comment by tadejsv** [comment]
When the FBeta "split-off" from #4385 will be merged, this will be fixed

**Comment by s-rog** [comment]
The doc issue and beta in f1 issues are still present in 1.1
