### ISSUE TITLE
ModelCheckpoint Callback save and restore extension

### ISSUE THREAD

**Issue by daandres** [PyTorchLightning/pytorch-lightning#4911]
## 🚀 Feature

callbacks.ModelCheckpoint implements on_save_checkpoint and on_load_checkpoint to save and load it's state to/from a checkpoint. Save/Load all internal members to recover complete state from checkpoint. 

### Motivation

I use a ModelCheckpoint callback to save my Top-K (3) models during training. Sometimes I resume training at a certain point and want to train further epochs. But the loaded Callback has an empty best_k_models list, so this list is build up again. Older models are not tracked and I get three new models in same folder, and I do not know, which are the Top-3 ones. 
Therefore a full state of ModelCheckpoint would resolve this. 

### Pitch

Extend the ModelCheckpoint methods to export and load all internal states. I'm not sure if there is missing something, but here is a try:

    def on_save_checkpoint(self, trainer, pl_module) -> Dict[str, Any]:
        return {
            "best_model_score": self.best_model_score,
            "best_model_path": self.best_model_path,
            "best_k_models" : self.best_k_models,
        }

    def on_load_checkpoint(self, checkpointed_state: Dict[str, Any]):
        self.best_model_score = checkpointed_state["best_model_score"]
        self.best_model_path = checkpointed_state["best_model_path"]
        self.best_k_models = checkpointed_state["best_k_models"]

### Alternatives

Subclass the ModelCheckpoint to implement this, but I think this would complicate things.  

### Additional context

-/-

**Comment by carmocca** [comment]
I think this would be nice addition, but its not as easy as you said. For example:

- What if the checkpoints were moved to a different path?
- What if the user set a different monitor/mode?

Feel free to open a draft PR and we can help you with it :smile:

**Comment by daandres** [comment]
I think #4712 #4383 partially covers a similar problem. 

Yes, both points are important thoughts. I'll think about a general way to capture this. 

* If user changes monitor mode, move old checkpoints to subdirectory or rename files?
* If checkpoints were moved out of scope, than a user can't load it. and if it reads the yaml with the best checkpoints containing wrong paths, it should be possible to specify new path. But I think, this is should not be part of this issue here.

**Comment by carmocca** [comment]
> I think #4712 #4383 partially covers a similar problem.

They do but the difference is that they don't attempt to restore the saved state. Then it becomes a simpler issue.

> * If user changes monitor mode, move old checkpoints to subdirectory or rename files?

I wouldn't move them at all. If the monitor has changed I would warn the user about it and reset the state as if it was a new `ModelCheckpoint` instance.

> * If checkpoints were moved out of scope, than a user can't load it. and if it reads the yaml with the best checkpoints containing wrong paths, it should be possible to specify new path. But I think, this is should not be part of this issue here.

If the paths don't exist the code will fail (as it currently is) when trying to delete them.

In any case, I was just giving an example of an edge case which makes implementing your suggestion not as easy as just updating `on_{save,load}_checkpoint`.

**Comment by rohitgr7** [comment]
https://github.com/PyTorchLightning/pytorch-lightning/issues/5173#issuecomment-748571874
https://github.com/PyTorchLightning/pytorch-lightning/issues/5173#issuecomment-748618082
few more comments on the same issue.

**Comment by PeterMitrano** [comment]
I would also like a solution for this case, where "best" model info is wiped when resuming training. I didn't realize this, and was using broken results for a while.

I'd say if the monitor is changed than it should print a warning and restart.

**Comment by PeterMitrano** [comment]
FWIW, simply adding `self.best_k_models` was sufficient in my use case, so I'm using this:

```
class MyModelCheckpoint(pl.callbacks.ModelCheckpoint):

    def on_save_checkpoint(self, trainer, pl_module, checkpoint):
        return {
            "monitor":          self.monitor,
            "best_model_score": self.best_model_score,
            "best_model_path":  self.best_model_path,
            "current_score":    self.current_score,
            "dirpath":          self.dirpath,
            "best_k_models":    self.best_k_models,
        }

    def on_load_checkpoint(self, trainer, pl_module, callback_state):
        self.best_model_score = callback_state["best_model_score"]
        self.best_model_path = callback_state["best_model_path"]
        self.best_model_score = callback_state["best_model_score"]
        self.best_k_models = callback_state["best_k_models"]
```
