### ISSUE TITLE
 How to resume training

### ISSUE THREAD

**Issue by davidenitti** [PyTorchLightning/pytorch-lightning#4914]
#### What is your question?
How to resume training

#### What have you tried?
The following:
`trainer = pl.Trainer(gpus=1, default_root_dir=save_dir)`
saves the checkpoints but does not resume from the last checkpoint (it starts a new version)
The following code starts the training from scratch (but I read that it should resume):
```
logger = TestTubeLogger(save_dir=save_dir, name="default", version=0)
trainer = pl.Trainer(gpus=1, default_root_dir=save_dir, logger = logger)

```
it always starts over and it also save always in a different checkpoint if the checkpoint exists e.g. epoch=0.ckpt, and after epoch=0-v0.ckpt (instead of overwriting)

#### What's your environment?

 - OS: Linux
 - Packaging pip
 - Version: pytorch_lightning-1.0.8

**Comment by Borda** [comment]
mind check this cool PL feature https://pytorch-lightning.readthedocs.io/en/latest/trainer.html#resume-from-checkpoint
feel free to reopen if needed :]

**Comment by davidenitti** [comment]
@Borda I knew that feature, I would like instead an automatic resume from the last checkpoint.
I read that it should be possible but it isn't. otherwise, I have to find the list of all checkpoints, extract the number and then get the last one, which is as complicated as in pytorch. actually it's even more complicated because it never overwrite a checkpoint, so I might have weird naming as epoch=0-v0.ckpt
