### ISSUE TITLE
default_root_path vs default_root_dir

### ISSUE THREAD

**Issue by jethrokuan** [PyTorchLightning/pytorch-lightning#4926]
I noticed that the argument to Trainer is `default_root_dir`, but the docs sometimes show `default_root_path`. I did a grep on the codebase for `default_root_path`, and here are the results:

```
./notebooks/05-trainer-flags-overview.ipynb:2155:    "trainer = pl.Trainer(default_root_path=os.getcwd())\n",
./pytorch_lightning/trainer/properties.py:51:    default_root_path: str
./docs/source/trainer.rst:618:    trainer = Trainer(default_root_path=os.getcwd())
```

I'm fairly convinced it's simply a documentation issue, but it requires some code changes (the 2nd line), and I'm not sure whether that will affect anything.

**Comment by carmocca** [comment]
It should be fine. Can you open a PR?
