### ISSUE TITLE
update min dependencies

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#4928]
## 🐛 Bug

after pip install strategy changes we have several packages which are not feasible to install together

### To Reproduce

see all min CI config https://github.com/PyTorchLightning/pytorch-lightning/runs/1478280229

### Expected behavior

update some libs to be installable, probably go one by one or list dependencies of our dependencies and find a minimal intersection

**Comment by ydcjeff** [comment]
Let me take this
