### ISSUE TITLE
The correct way to resume experiment with logger

### ISSUE THREAD

**Issue by hobogalaxy** [PyTorchLightning/pytorch-lightning#4935]
From what I understand checkpoints don't save id of the logger run right?
Then what is the correct way to resume training from checkpoint and resume the correct logger run at the same time?

For example, I'm using Wights&Biases logger where you can pass id argument which resumes run experiment:
```
WandbLogger(id=run_id)
```
How can I know what is the correct run id without checking it manually?
Is it possible to somehow store it in the checkpoint?
Also, why is checkpoint not storing things like that automatically? Seems like a useful feature.

**Comment by kilianovski** [comment]
Maybe, `ModelCheckpoint` should also have an option to save wandb state as well?

**Comment by jonashaag** [comment]
Same question here.

**Comment by jonashaag** [comment]
Still an issue, stalebot.
