### ISSUE TITLE
How to log more than one metrics in logger?

### ISSUE THREAD

**Issue by 7zhanghao** [PyTorchLightning/pytorch-lightning#4947]
I want to log two metircs.What should i do?
self.log('my_loss', loss, on_step=True, on_epoch=True, prog_bar=True, logger=True) 
This can only log one metrics.

**Comment by ydcjeff** [comment]
@7zhanghao  You can just write another log.
```py
 self.log('another_loss', loss, on_step=True, on_epoch=True, prog_bar=True, logger=True)
```

**Comment by zhutmost** [comment]
@7zhanghao You can use `self.log_dict`

**Comment by 7zhanghao** [comment]
> @7zhanghao You can just write another log.
> 
> ```python
>  self.log('another_loss', loss, on_step=True, on_epoch=True, prog_bar=True, logger=True)
> ```

Thanks a lot.

**Comment by 7zhanghao** [comment]
> @7zhanghao You can use `self.log_dict`

Thanks a lot.
