### ISSUE TITLE
resolve py3.8 testing

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#4950]
## 🚀 Feature

cases:
- py3.8 Ubuntu minimal is falling for segmentation error when collecting tests -> find packages
- py3.8 Ubuntu latest has a hanging test -> find tests and skip it

### Motivation

restore testing for 3.8 skipped in #4943

**Comment by cuent** [comment]
@Borda can you assign this one to me?

**Comment by cuent** [comment]
Update: still trying to find the packages for CI.

Thought it would be easier 😄 

If somebody can help me spot a problem. It seems to be a test related when calling early stopping this [line](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/callbacks/early_stopping.py#L31).

I also attach the log of gdb. I cannot trace back the test yet though. 

[trace.txt](https://github.com/PyTorchLightning/pytorch-lightning/files/5640724/trace.txt)

**Comment by Borda** [comment]
@cuent any update here? do you have an open draft for it...

**Comment by kaushikb11** [comment]
Is it resolved?

**Comment by cuent** [comment]
@kaushikb11 I made some experiments but I wasn't able to find the root. Please refer the output and conf [here](https://github.com/cuent/pytorch-lightning/blob/master/.github/workflows/ci_test-full.yml)

**Comment by edenlightning** [comment]
@Borda status?

**Comment by Borda** [comment]
was done :]
