### ISSUE TITLE
[isort] Improve import formatting configuration

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning#4960]
## 🚀 Feature
Although #4242 have recently introduced isort to check and apply import formatting, I find the import order somewhat confusing, so I'd like to suggest to add the following two options to isort config `pyproject.toml`.

### `force_sort_within_sections = 'True'`
```python
# before
import torch
from pytorch_lightning import Callback
from torch.nn import functional as F

# after
from pytorch_lightning import Callback
import torch
from torch.nn import functional as F
```

### `order_by_type = 'False'`
```python
# before
from torch import Tensor, nn

# after
from torch import nn, Tensor
```

Since we have applied isort to only a few files as listed in #4805, I believe we can still modify the config. Let me know your thoughts on this. (This is the same issue as https://github.com/PyTorchLightning/pytorch-lightning-bolts/issues/422.)

**Comment by justusschock** [comment]
cc @Borda

**Comment by Borda** [comment]
> **`force_sort_within_sections = 'True'`**

not strong preference, but personally `False` as it is native in Pycharm

> **`order_by_type = 'False'`**

agree :]

**Comment by akihironitta** [comment]
> > **`force_sort_within_sections = 'True'`**
> 
> not strong preference, but personally `False` as it is native in Pycharm

@Borda Thank you for your response :] Shall I wait for other core contributors' comments, or should I give it a go with `False` as you prefer? (Not a strong opinion, but personally `True` is easier to read as `torch` imports, for example, are put together.)

**Comment by Borda** [comment]
@PyTorchLightning/core-contributors what do you think? @awaelchli 🐰

**Comment by awaelchli** [comment]
I don't know, I never look at import statements since it's all automated so I have no preference.

**Comment by rohitgr7** [comment]
personally I'd prefer.
```python
force_sort_within_sections=True
order_by_type=False
```

**Comment by akihironitta** [comment]
@PyTorchLightning/core-contributors Any other thoughts?

**Comment by Borda** [comment]
> Not a strong opinion, but personally `True` is easier to read as `torch` imports, for example, are put together.)

yes, but as from/import has different lengths it is not so easy to read... :/
