### ISSUE TITLE
conda python 3.8 support

### ISSUE THREAD

**Issue by pseudotensor** [PyTorchLightning/pytorch-lightning#4962]
We'd like to switch to python 3.8 for various reasons, and we've been using conda for better support of rapids from NVIDIA.  The install matrix suggests there is no python 3.8 builds for lightning yet.  Is there a plan do build those too?  It seems python 3.8 already works for other platforms for a while now.

**Comment by Borda** [comment]
@pseudotensor can you pls list you reasons why we should switch testing to 3.8?
we already have all [docker images also for python 3.8](https://hub.docker.com/repository/docker/pytorchlightning/pytorch_lightning/tags?page=1&ordering=last_updated&name=py3.8)

**Comment by pseudotensor** [comment]
Hi, I'm just not confident what works from looking at the matrix.  I assume it works, but maybe at least 1 python 3.8 target for testing for conda would be good, e.g. latest stable torch perhaps.

**Comment by Borda** [comment]
> I'm just not confident what works from looking at the matrix

may you please clarify what you mean?

We are testing py 3.6 3.7 3.8 with pip packages, so there is no special reason that conda won't work with 3.8 unless some of the 3rd party packages have an issue with py 3.8 on conda...

**Comment by pseudotensor** [comment]
Yes, there is no reason unless incompatible or no compatible packages etc.  Packages chosen may not be quite restricted properly, which I've found common.  i.e. alot of packages use >= constraint but in reality more != 's should have been chosen and only foresight would make it clear when to use <=.

**Comment by Borda** [comment]
yes, but that would yield thousands of builds for any combination or Python version / OS / dependency version...
let's reopen if there'll be a specific reason for this switch, I do not think we would add 3.8 rather switch from 3.7 to 3.8
