### ISSUE TITLE
Custom Checkpoint file extension

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#4963]
## 🚀 Feature

Atm, we have hardcoded `.ckpt` as a file extension for any checkpoint.

https://github.com/PyTorchLightning/pytorch-lightning/blob/db69d169e868451c16a4ee418f2de835ccce146c/pytorch_lightning/callbacks/model_checkpoint.py#L429

Proposed solution 1:
```
class ModelCheckpoint(Callback):
    FILE_EXTENSION = ".ckpt"
```
Proposed solution 2:
```
ModelCheckpoint(ext=''pt')
```

**Comment by awaelchli** [comment]
Should it be part of the filename?
Adding a new argument would require some justification I think.

**Comment by carmocca** [comment]
Some previous discussion about this: https://github.com/PyTorchLightning/pytorch-lightning/pull/3163#discussion_r476644340

**Comment by edenlightning** [comment]
I agree with @awaelchli, but just need to handle some edge cases (don;t think we should support "." in filenames anway, no?)

**Comment by Borda** [comment]
> I agree with @awaelchli, but just need to handle some edge cases (don;t think we should support "." in filenames anway, no?)

If we define it as propose in the description, all behaviors stay the same for now... And if use overwrite it is, it is his decision and responsibility

**Comment by rohitgr7** [comment]
> Should it be part of the filename?
Adding a new argument would require some justification I think.

I thought so too, but what if user wants the default filename created by PL but with a different extension? In that case it should be  `filename=None`.

**Comment by Borda** [comment]
well in such case you need to pass the instance of checkpoint call back anyway, so I would fo keeping untouched API inherit it...
```
class ModelCheckpoint(Callback):
    FILE_EXTENSION = ".ckpt"
    ...

class MyModelCheckpoint(ModelCheckpoint):
    FILE_EXTENSION = ".abc"
    ...
```
so you can later pass `[ModelCheckpoint(), MyModelCheckpoint()]`

**Comment by Borda** [comment]
> I agree with @awaelchli, but just need to handle some edge cases (don;t think we should support "." in filenames anway, no?)

as you agree with it I have reverted the description to the original one :]

**Comment by rohitgr7** [comment]
> Proposed solution 1:
class ModelCheckpoint(Callback):
    FILE_EXTENSION = ".ckpt"


I'd suggest this one

**Comment by janhenriklambrechts** [comment]
Ill happily work on this :)
