### ISSUE TITLE
Fix pipy badges and images not rendering

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#4978]
it seems that it did not work for [PyPI page](https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi/)
see our RC - https://pypi.org/project/pytorch-lightning/1.1.0rc1
when I open the PKG-INFO I still see the original paths...

Downloaded implemented in #4250

**Comment by Borda** [comment]
ref: https://github.com/PyTorchLightning/pytorch-lightning/pull/4250#issuecomment-737552478

**Comment by janhenriklambrechts** [comment]
If you still  need some help, I can look into it.

**Comment by Borda** [comment]
> If you still need some help, I can look into it.

it would be nice, I am about to take it today too, do you have any similar experience?

**Comment by janhenriklambrechts** [comment]
> it would be nice, I am about to take it today too, do you have any similar experience?
No similar experience but happy to dive in and learn. I might take some time getting up to speed (just like the checkpoint issue) so if it is very urgent, feel free to skip over me :]

**Comment by Borda** [comment]
seems we would need to upload the images somewhere on a cloud... https://stackoverflow.com/a/46875147/4521646

**Comment by janhenriklambrechts** [comment]
> seems we would need to upload the images somewhere on a cloud... https://stackoverflow.com/a/46875147/4521646

Or as an asset of this repo and just use the raw github link

**Comment by Borda** [comment]
yes, but as we download them during package build time there are not in any git version (just on the fly) so we would need to upload them to some free public domain and refer them there...
