### ISSUE TITLE
Where is stored logs of the NeptuneLogger when I use offline mode for a logger?

### ISSUE THREAD

**Issue by bes-dev** [PyTorchLightning/pytorch-lightning#4986]
I use Neptune Logger with the offline mode in my pipeline, but I can't find where log files are located, and I can't find parameters of NeptuneLogger to set store dir and so on from offline mode. Can someone help with it? Thanks in advance!

**Comment by rohitgr7** [comment]
check this path `trainer.log_dir`.

**Comment by stonelazy** [comment]
Still couldn't get any info on this.
