### ISSUE TITLE
Add multi-task support to EarlyStopping 

### ISSUE THREAD

**Issue by hbredin** [PyTorchLightning/pytorch-lightning#4994]
## 🚀 Feature

Make `EarlyStopping` watch multiple values and only stop when all of them no longer improve.

### Motivation

I have been training a multi-task model with multiple outputs. Each output is validated and logged by the model. 
As of today, early stopping can only watch one of them. Hence, the user has to choose which task is the main one.

### Pitch

Make `EarlyStopping` watch multiple values and only stop when all of them no longer improve.

### Alternatives

One could add multiple `EarlyStopping` callbacks (one for each task) but this would stop as soon as one of the task no longer improves (even though another one might still be improving).

### Additional context

Note that `ModelCheckpoint` does not have this problem: one can add multiple instances of `ModelCheckpoint` (one for each task) and you get what you expect: checkpointing based on each task's validation metric.

**Comment by carmocca** [comment]
I love the idea! It might be easier to create a `MultiTaskEarlyStopping` than updating the current `EarlyStopping` class.

Would you be willing to work on it?

> Note that `ModelCheckpoint` does not have this problem: one can add multiple instances of `ModelCheckpoint` (one for each task) and you get what you expect: checkpointing based on each task's validation metric.

This is not perfectly supported and only one ModelCheckpoint state will be saved.

**Comment by hbredin** [comment]
I need this feature at some point so am happy to contribute in the future but cannot provide an ETA (definitely not before 2021).

**Comment by ncuxomun** [comment]
Anyone implemented MultiTaskEarlyStopping manually?
