### ISSUE TITLE
Use lightning with dgl

### ISSUE THREAD

**Issue by Maybewuss** [PyTorchLightning/pytorch-lightning#4996]
```
def train_dataloader(self):
        return DataLoader(self.train_dataset,
                          batch_size=self.hparams.batch_size,
                          shuffle=True,
                          num_workers=4,
                          collate_fn=self.batcher)
```
I use collate_fn to batch dgl graphs, but when I training model, trigger this warning:
`
DGLWarning: DGLGraph.__len__ is deprecated.Please directly call DGLGraph.number_of_nodes.
`
How tor fix it ?

**Comment by awaelchli** [comment]
Could you provide a bit more information? It looks like this warning is coming from the DGL library. It would be nice to have a minimal example to run. Make sure your train_dataset is a `torch.nn.Dataset` that has the `__len__` method defined.

**Comment by Maybewuss** [comment]
```
import pytorch_lightning as pl
import dgl
from torch.utils.data import DataLoader, Dataset
import torch.nn as nn
from torch.optim import AdamW
import torch

class Dataset(object):
    def __init__(self, instances):
        self.instances = instances

    def __getitem__(self, idx):
        """Get the instance with index idx.
        """
        return self.instances[idx]

    def __len__(self):
        return len(self.instances)

class Model(pl.LightningModule):
    def __init__(self, *args, **kwargs):
        super().__init__()
        self.net = nn.Linear(1, 1)
        
    def forward(self, *args, **kwargs):
        x = torch.randn(2, 1)
        return self.net(x)
    
    def training_step(self, batch, batch_idx):
        loss = self().sum()
        return loss
    
    def configure_optimizers(self):
        opt = AdamW(self.net.parameters(), lr=100)
        return opt

graph = dgl.heterograph(
    {
        ('drug', 'interacts', 'drug'): [(0,1), (1, 2)],
        ('drug', 'treats', 'disease'): [(2, 3), (0, 3)],
        
    }
)

data = [graph, graph, graph]
dataset = Dataset(data)
data_loader = DataLoader(dataset, batch_size=1, collate_fn=dgl.batch)

model = Model()
trainer = pl.Trainer()
trainer.fit(model, train_dataloader=data_loader)

```

`
/Applications/anaconda3/envs/py36/lib/python3.6/site-packages/dgl/base.py:45: DGLWarning: DGLGraph.__len__ is deprecated.Please directly call DGLGraph.number_of_nodes.
`

Does lightning use len function when load data from dataloader ?

**Comment by awaelchli** [comment]
Your code looks fine. I still don't think Lightning is causing the warning. Can you just run only this code:

```python 
data = [graph, graph, graph]
dataset = Dataset(data)
data_loader = DataLoader(dataset, batch_size=1, collate_fn=dgl.batch)
next(iter(dataloader))
```

**Comment by Maybewuss** [comment]
> Your code looks fine. I still don't think Lightning is causing the warning. Can you just run only this code:
> 
> 
> 
> ```python 
> 
> data = [graph, graph, graph]
> 
> dataset = Dataset(data)
> 
> data_loader = DataLoader(dataset, batch_size=1, collate_fn=dgl.batch)
> 
> next(iter(dataloader))
> 
> ```
> 
> Does it throw the warning?
> 
> 

I tried, no warning throw.
