### ISSUE TITLE
Dead Links in "Implementing your own DDP" documentation

### ISSUE THREAD

**Issue by alanhdu** [PyTorchLightning/pytorch-lightning#5031]
## 📚 Documentation

In the "Implementing your own DDP section" (https://pytorch-lightning.readthedocs.io/en/stable/multi_gpu.html#implement-your-own-distributed-ddp-training), the text says:

> If you need your own way to init PyTorch DDP you can override pytorch_lightning.core.LightningModule.().
>
> If you also need to use your own DDP implementation, override: pytorch_lightning.core.LightningModule.configure_ddp().

Unfortunately, both of those seem to be dead links. I'm not sure what would replace them -- the custom DDP implementation should presumably point to https://pytorch-lightning.readthedocs.io/en/stable/accelerators.html#implement-a-custom-accelerator, but I'm not sure where the "overriding the init Pytorch DDP" should live (from the Git blame, it looks like used to call to a `init_ddp_connection` function that doesn't seem to exist anymore).

**Comment by Borda** [comment]
@alanhdu mind send a PR?

**Comment by alanhdu** [comment]
@Borda -- what should the updated links point to? Presumably the `configure_ddp` should point to the custom accelerator docs, but I don't know where the first link ("init Pytorch ddp") should go.

**Comment by awaelchli** [comment]
Maybe here: 
https://github.com/PyTorchLightning/pytorch-lightning/blob/2c11d96012f629264e57601d68074ef73bb17659/pytorch_lightning/plugins/ddp_plugin.py#L73
