### ISSUE TITLE
metrics from "sanity check" do not appear on wandb / epoch 1 becomes 0

### ISSUE THREAD

**Issue by undertherain** [PyTorchLightning/pytorch-lightning#5033]
#### What is your question?
I'm using so called "sanity check" to run actual full validation before I do any training, using `num_sanity_val_steps=-1`
however I could not see any metrics displayed on wandb. 
Eventually I had to implement custom `validation_epoch_end`
where instead of `log_dict` I'm using 
`self.logger.agg_and_log_metrics(metrics, step=self.current_epoch + 1)`

the question is if there is more normal / straight-forward way to do this?
I still have to implement custom `training_epoch_end`, because currently validation epoch 1 corresponds to training epoch 0. Essentially how I see it is validation curve on wandb starting from epoch 0, training epoch starting from 1, and this being achieved by some sort of "don't decrement epoch number" kind of parameter...
Thanks!

#### What's your environment?
currently using PL  1.0.8 and wandb 0.10.12

**Comment by undertherain** [comment]
looks like part of the problem is here
```
        if step == self._prev_step:
            self._metrics_to_agg.append(metrics)
            return step, None
```
the _prev_step is initially set to 0, so it does not do logging while still in epoch 0
I don't mind it it's epoch -1 on wandb, though still would be niceer to start eval from 0 and training from 1

**Comment by undertherain** [comment]
okey, so it looks like the case it that it is not that it's not logging per se
it is that the wandb logger waits to collect all metrics for a given step, and only updates when the step changes to the next one. 
so 
1. does PL ever log results of the call to log_something 
2. using  agg_and_log_metrics directly is a bit tricky, because if I use epoch as step, I should not be using batch as step in trainer. Which is okeish if I only log per epoch manually in both train and val. 
3 . Would still prefer to do it through log_dict but there's too much levels of abstraction there to figure out what's going on in that code

**Comment by undertherain** [comment]
I though to find an answer in samples - and noticed that they are not logging, but returning a dict. So I rewrote my code like in samples - just to get a warning that 
```
UserWarning: The {log:dict keyword} was deprecated in 0.9.1 and will be removed in 1.0.0
[0]<stderr>:Please use self.log(...) inside the lightningModule instead.
```
cmon guys....

**Comment by undertherain** [comment]
okey. short but hacky solution is
```
    def validation_epoch_end(self, outputs):
        if self.trainer.running_sanity_check:
            self.trainer.running_sanity_check = False  # so that loggers don't skip logging
            self.trainer.current_epoch = -1 
```

**Comment by borisdayma** [comment]
If you want to commit all the metrics and increment the step after your sanity check, you could also use `wandb.log({})`.
However you need to be sure that the step is actually going to increase as you cannot log at previous steps.
