### ISSUE TITLE
validating bar keep showing 0 when check_val_every_n_epoch is bigger than 1

### ISSUE THREAD

**Issue by ZhichaoDuan** [PyTorchLightning/pytorch-lightning#5039]
## 🐛 Bug

Normally, the validating bar should update according to the procedure of validation_step, but when I set check_val_every_n_epoch bigger than 1, 2 for example, it keeps showing 0it.

I encountered this issue under a terminal environment.

 - PyTorch 1.6.0:
 - Linux

**Comment by ananyahjha93** [comment]
@ZhichaoDuan can you reproduce this using the BoringModel?

**Comment by lstefanou** [comment]
Same issue here. Setting check_val_every_n_epoch to 2 gives me a validation progress bar stuck at `Validating: 0it [00:00, ?it/s]`.

Perhaps related; the first epoch (either correctly or not depending on whether the Trainer should validate on epoch 0) shows the sum of train and validation batches, but never loops through the validation batches. E.g. I have 100/50 train/val batches, first epoch will show n/150 but will stop at 100. Second epoch will show the correct number (100).

- PyTorch 1.7.0
- PyTorch Lightning 1.0.8
- Linux

**Comment by ZhichaoDuan** [comment]
> @ZhichaoDuan can you reproduce this using the BoringModel?

Istefanou below have located the issue, could you take a look at it?

**Comment by edenlightning** [comment]
Anyone wants to try and submit a fix?

**Comment by sailordiary** [comment]
Why was this closed?
