### ISSUE TITLE
ddp opens processes on GPUs (and consumes memory) not assigned to the Trainer

### ISSUE THREAD

**Issue by mpaepper** [PyTorchLightning/pytorch-lightning#5041]
## 🐛 Bug

When training on multiple GPUs with ddp, it is still starting processes on the unused GPUs (with a lot less memory, but still). It's not running any work there (GPU-Util is 0% in nvidia-smi).

How to fix this manually: I can run `CUDA_VISIBLE_DEVICES="2,3" python train.py --gpus 0,1` and then it works, it only runs processes on GPUs 2,3 and nothing on 0,1.

It also crashes when you use GPU 0 or GPU 1 and then some others (for example 0, 2, 3 crashes).

To me it looks like the ddp rank is used to index into the list of visible GPUs and there is some error in how that is handled.

### To Reproduce

Run training on GPU index 2,3 and it will also create a process on 0 and 1 (can be verified in nvidia-smi):

```
trainer = pl.Trainer(gpus=[2,3], accelerator='ddp')
trainer.fit(lightning_model)
```

### Expected behavior

I should be able to run any GPU combination and the other GPUs should not be touched.

### Environment

* CUDA:
	- GPU:
		- GeForce RTX 2080 Ti
		- GeForce RTX 2080 Ti
		- GeForce RTX 2080 Ti
		- GeForce RTX 2080 Ti
	- available:         True
	- version:           10.2
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0
	- pytorch-lightning: 1.0.8
	- tqdm:              4.54.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.8.5
	- version:           #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020

**Comment by mpaepper** [comment]
I think it's related to this: https://github.com/PyTorchLightning/pytorch-lightning/issues/4705

**Comment by mpaepper** [comment]
Some further illustrations:

With GPU 0,1 all looks good, 2 processes one on GPU 0, one on GPU 1
![Auswahl_504](https://user-images.githubusercontent.com/4135790/101659852-c7414f80-3a46-11eb-8bbe-132d5bb78398.png)

However with GPU 2,3, suddenly there are two ghost processes on GPU 0 and 1
![Auswahl_505](https://user-images.githubusercontent.com/4135790/101659925-dfb16a00-3a46-11eb-968b-b1cb62f904c7.png)

This can be fixed when using CUDA_VISIBLE_DEVICES="2,3" and then GPU 0,1 -> 2 processes one on GPU 2, one on GPU3
![Auswahl_506](https://user-images.githubusercontent.com/4135790/101659987-f1930d00-3a46-11eb-9d8e-e950354444d9.png)

**Comment by mpaepper** [comment]
Some further illustrations:

With GPU 0,1 all looks good, 2 processes one on GPU 0, one on GPU 1
![Auswahl_504](https://user-images.githubusercontent.com/4135790/101660248-3fa81080-3a47-11eb-98f9-c8c6c01ef87b.png)

However with GPU 2,3, suddenly there are two ghost processes on GPU 0 and 1
![Auswahl_505](https://user-images.githubusercontent.com/4135790/101660259-433b9780-3a47-11eb-9a3a-dd317fa582ed.png)

This can be fixed when using CUDA_VISIBLE_DEVICES="2,3" and then GPU 0,1 -> 2 processes one on GPU 2, one on GPU3
![Auswahl_506](https://user-images.githubusercontent.com/4135790/101660268-46368800-3a47-11eb-99a5-cb39fda5cd77.png)

**Comment by awaelchli** [comment]
same as here? #4705

**Comment by edenlightning** [comment]
would you be able to share a reproducible script?

**Comment by mpaepper** [comment]
@edenlightning Here is a reproducable script:

https://github.com/mpaepper/pytorch_lightning_issue_5041/tree/master

Running on GPUs 0 and 1 works: python index.py '0,1'

Running on GPUs 0, 2 and 3 doesn't work / hangs: python index.py '0,2,3'

**Comment by mpaepper** [comment]
Oh, and importantly what I forgot to mention:

While this fails: `python index.py '0,2,3'`
This works: `CUDA_VISIBLE_DEVICES="0,2,3" python index.py "0,1,2"`
