### ISSUE TITLE
train_epoch_end called before epoch_end

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#5042]
### To Reproduce

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/training_loop.py#L858

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

* `IDE`: Please, use our python [bug_report_model.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
) template.

* `Colab Notebook`: Please copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py) (or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by kaushikb11** [comment]
Hi @tchaton, what's the expected behavior here? As in the [code](https://github.com/PyTorchLightning/pytorch-lightning/blob/eee3b1a284470b3eca6ebd1815c0ddd7f550c667/pytorch_lightning/trainer/training_loop.py#L832), `run_on_epoch_end_hook` is called in `run_training_epoch`.

```python
    def run_on_epoch_end_hook(self, epoch_output):
        # inform logger the batch loop has finished
        self.trainer.logger_connector.on_train_epoch_end()

        self.trainer.call_hook('on_epoch_end')
        self.trainer.call_hook('on_train_epoch_end', epoch_output)
```

Just want to be clear if the sequence needs to be changed. Thanks!
