### ISSUE TITLE
`Missing logger folder Warning` due to `isdir` of  `fsspec`

### ISSUE THREAD

**Issue by gqk** [PyTorchLightning/pytorch-lightning#5052]
## 🐛 Bug

I linked a folder to `PROJECT_ROOT/lightning_logs`, but `pytorch-lightning` showed the warning `Missing logger folder: PROJECT_ROOT/lightning_logs`, and then wrote the `tensorboard` event log file to `PROJECT_ROOT/lightning_logs/version_0`, instead of creating a new `version_xxx`.

I think this is because in this case, `fsspec`'s `isdir` returns `False`, while python `os.path.isdir` returns `True` . Please refer to [https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/loggers/tensorboard.py#L241](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/loggers/tensorboard.py#L241) for details.

**Comment by edenlightning** [comment]
Thanks for the issue! @f4hy any idea?

**Comment by ethanwharris** [comment]
@gqk Closing as this should now be fixed by #6730
