### ISSUE TITLE
Exceptions in a Transform are silently ignored during training; fails next epoch with no error msg

### ISSUE THREAD

**Issue by NumesSanguis** [PyTorchLightning/pytorch-lightning#5055]
## 🐛 Bug

An Exception, such as StopIteration, is silently ignored by the Trainer and the error message is not printed out. Also, training continues, even when data points are missing.

## Please reproduce using [the BoringModel and post here](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing)

https://colab.research.google.com/drive/1gAssRJ4fIC0SObNBoS1IzGFN545TVQ9x?usp=sharing

### To Reproduce

A Transform that throws a StopIteration exception somewhere during training:
```
class SimulateTransformError(object):
    def __init__(self, generator_len):
        self.generator = self.num_gen(generator_len)

    def num_gen(self, generator_len):
        for i in range(generator_len):
            yield i

    def __call__(self, sample):
        try:
            # does nothing except exhausting the generator
            next(self.generator)
            return sample
        except StopIteration as e:
            raise StopIteration(f"Generator ran out of samples:\n{e}")
```

Apply transform while retrieving an item:

```
def __getitem__(self, index):
    return self.transform(self.data[index])
```

### Expected behavior

Show the error message: f"Generator ran out of samples:\n{e}"

### Actual behavior

- If you run 1 epoch, you notice that epoch 0 stops at 48%, but no error
- If you run 2+ epochs, training continues after epoch 0, and throws an error during epoch 1: `RuntimeError: stack expects a non-empty TensorList`
- The real error is never shown

### Environment

Colab:
```
* CUDA:
	- GPU:
		- Tesla P100-PCIE-16GB
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0+cu101
	- pytorch-lightning: 1.1.0
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020
```

### Additional context

If you wrap the transform in a try statement, an error message is printed, but the actual error message `e` is empty:
```
try:
    data = self.transform(data)
except Exception as e:
    print(f"Data transform failed with error:\n{e}")
# empty e
```

**Comment by tchaton** [comment]
Hey @NumesSanguis,

I seems StopIteration is quietly skipped by Dataloarder, not Pytorch Lightning.
Works fine with other exceptions. https://github.com/PyTorchLightning/pytorch-lightning/pull/5222/files

Best regards,
T.C

**Comment by awaelchli** [comment]
Hey @NumesSanguis ! 
If I understand correctly, you would like to show the error message "Generator ran out of samples", correct?
For this please use a different event, for example
```
RuntimeError("Generator ran out of samples")
 ```
StopIteration is meant for iterators and it is normal that it is "silent" because it is meant to stop an iteration. 
Hope this helps.
