### ISSUE TITLE
Fix metrics backwards compatibility 

### ISSUE THREAD

**Issue by teddykoker** [PyTorchLightning/pytorch-lightning#5061]
Moved to pl.metrics.utils (some users have complained about this)

TODO: add function back to functional (with deprecation warning) that simply calls new one

**Comment by Borda** [comment]
it just about importing, so the fix is add in functional `__init__` corrected in #5062

**Comment by edenlightning** [comment]
@teddykoker @Borda can we close this?

**Comment by Borda** [comment]
> @teddykoker @Borda can we close this?

it is in #5067
