### ISSUE TITLE
{progress_bar:dict keyword} and {log:dict keyword} continue to work in pytorch lightning > 1.0

### ISSUE THREAD

**Issue by ORippler** [PyTorchLightning/pytorch-lightning#5081]
## 🐛 Bug

{progress_bar:dict keyword} and {log:dict keyword} continue to work in pytorch lightning > 1.0.

The functionality is maintained and the deprecation warning still raised (you can see the tensor "bug" appearing in the progress_bar). Logging was confirmed by visual inspection of tensorboard logs.

```
The {progress_bar:dict keyword} was deprecated in 0.9.1 and will be removed in 1.0.0.
The {log:dict keyword} was deprecated in 0.9.1 and will be removed in 1.0.0
```

## Please reproduce using [the BoringModel and post here](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing)

https://colab.research.google.com/drive/14hc8XhVY2Gc7H-oQKaqdtpZFYJE39eXm?usp=sharing

### Expected behavior

I would expect the progress bar not to be updated nor the scalars to be logged in lightning > 1.0.
Alternatively, if the team decided to no longer deprecate/remove logging/progress bars (or decides to remove in a later version) via the above method I would expect the DeprecationWarning to be changed accordingly.

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

* `IDE`: Please, use our python [bug_report_model.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
) template.

* `Colab Notebook`: Please copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py) (or fill out the checklist below manually).

* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0+cu101
	- pytorch-lightning: 0.10.0
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

**Comment by edenlightning** [comment]
Thanks! Want to submit a fix?

**Comment by ORippler** [comment]
If the developers could chime in with an update on the deprecation of `{progress_bar:dict keyword}` and `{log:dict keyword}` sure.
It's still open whether one should:

* Remove the Deprecation Warning, as the functionality will be maintained until further notice.
* Remove the Deprecation Warning and the logging functionality via above methods, raising an Error with hint to the Deprecation of the functionality instead.
* Increment the supported Version listed in the Deprecation Warning (i.e. until what version the functionality will be maintained/suppoted).

**Comment by edenlightning** [comment]
@Borda
