### ISSUE TITLE
Logging Error in Pycharm with Python3 code

### ISSUE THREAD

**Issue by Enderikus** [PyTorchLightning/pytorch-lightning#5088]
![screenshot logging error in pycharm ide 1](https://user-images.githubusercontent.com/75743042/101900171-523d5980-3baf-11eb-8a3c-c6db1df478fd.jpg)

![screenshot logging error in pycharm ide 2](https://user-images.githubusercontent.com/75743042/101900276-81ec6180-3baf-11eb-9297-bff86232b6af.jpg)

### Before asking: 
1. Try to find answers to your questions in [the Lightning Forum!](https://forums.pytorchlightning.ai/)
2. Search for similar [issues](https://github.com/PyTorchLightning/pytorch-lightning/issues).   
3. Search the [docs](https://pytorch-lightning.readthedocs.io/en/latest/).    

#### What is your question?
Hello, i'm sorry to bother anyone, i'm learning to program python via video tutorials on youtube, i'm an absolute beginner, i use pycharm IDE. I would like to know if this (see screenshots) is a IDE-bug, or it's something that i'm doing wrong. I have already written and saved dozens of .py files, learning from examples, mostly they work the way they should. But as  of jet i do not write complete programs only code snipets... be gentle because i'm a total noob, thank you.
#### What have you tried?
Done excactly as example, but it doesn't seem to work
#### What's your environment?
Windows 10 machine
 - OS: [e.g. iOS, Linux, Win]
 - Packaging [e.g. pip, conda]
 - Version [e.g. 0.5.2.1]

**Comment by Borda** [comment]
it is unrelated to. PL, but I see a problem that your moduled/files are named `logging.py` and `logging2.py` which makes the native `logging` overloaded and your `logging.py` does not have any attributes...

**Comment by Enderikus** [comment]
Both files were identical, Both gave same error, thanks anyway... I'm going back to HTML CSS

**Comment by Enderikus** [comment]
I had the impression i submitted this in the wrong thread, got hundreds of mails the last two days, none had anything to do with my question, this all is new for me. That's what it means being a noob...
