### ISSUE TITLE
pip install pytorch-lightning["extra"] doesn't install FairScale

### ISSUE THREAD

**Issue by mees** [PyTorchLightning/pytorch-lightning#5093]
## 🐛 Bug

The documentation [0] states that to enable sharded training one needs to install the extras packages with `pip install pytorch-lightning["extra"]`, in my case only following the second option `pip install https://github.com/PyTorchLightning/fairscale/archive/pl_1.1.0.zip` actually installed fairscale.

[0] https://pytorch-lightning.readthedocs.io/en/stable/multi_gpu.html#model-parallelism-beta

### To Reproduce
`pip install pytorch-lightning["extra"]`

### Expected behavior

Fairscale gets installed.

### Environment

 - PyTorch Version 1.7.0
 - OS: Linux
 - How you installed PyTorch: pip
 - Python version: 3.6.9
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: 4x TITAN X

**Comment by hassiahk** [comment]
I just checked this, FairScale is not getting installed through `pip install pytorch-lightning["extra"]`.

### My Environment
- PyTorch Version: 1.7.0
- OS: Linux
- How you installed PyTorch: pip
- Python version: 3.8.5

**Comment by Borda** [comment]
true, we skip all HTTP paths from packages...
https://github.com/PyTorchLightning/pytorch-lightning/blob/ddc3757309e367ee8d67e2aabde2e6e46045572d/pytorch_lightning/setup_tools.py#L51
there is some problem on pypi side if they are passed to these dependences...
