### ISSUE TITLE
pass a variable instead of string to self.save_hyperparameters()

### ISSUE THREAD

**Issue by aiyolo** [PyTorchLightning/pytorch-lightning#5103]
## 🚀 Feature

pass a `variable` instead of `string` to function `self.save_hyperparameters()`
### Motivation

```
>>>  class ManuallyArgsModel(LightningModule):
...     def __init__(self, arg1, arg2, arg3):
...         super().__init__()
...         # manually assign arguments
...         self.save_hyperparameters('arg1', 'arg3')
```
I think it is too weird to pass strings as arguments to `self.save_hyperparamets()`, using variables instead,such as `self.save_hyperparametes(arg1, arg3)`,  is much more elegant.

**Comment by awaelchli** [comment]
the reason why it is a string is because in order to save the parameters one also has to know the name of the variable.

**Comment by aiyolo** [comment]
we know `print('val')` and `print(var)` are very different things, similarly, `save_hyperparemetes('var')` may mislead users that they are saving a string rather than a variable, this is what I'm concerned. So is it possible to improve it?

**Comment by ZJX-CV** [comment]
If we use this function，will params be saved in ckpt file automatically？
