### ISSUE TITLE
Question about gif in readme.

### ISSUE THREAD

**Issue by nngogol** [PyTorchLightning/pytorch-lightning#5105]
Hi, @williamFalcon! Thank you for your work! You are the **_real wizard_**.

Official [docs](https://pytorch-lightning.readthedocs.io/en/stable/new-project.html) have absolutely great animation, which is located
below `Here’s a 3 minute conversion guide for PyTorch projects:` part.
It's a video, that has playback knob. As for me, this is great for understanding pytorch and software (in general way).
Question: can you tell me **what** did you used for making this animation?
Is it a **text effects in video-editor**
or special presentation software with code highlight
or custom written software?
or is it manim repo?

**Comment by DuinoDu** [comment]
Great animation, also want to know.
