### ISSUE TITLE
Pretty print tensors in `trainer.test()`

### ISSUE THREAD

**Issue by bryant1410** [PyTorchLightning/pytorch-lightning#5107]
## 🐛 Bug

When printing the results of `trainer.test()` (saying "DATALOADER:0 TEST RESULTS"), it shows "tensor(...)", sometimes also including the device, when just a number should be shown.

## Please reproduce using [the BoringModel and post here](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing)

I copied the template and didn't modify it, as it already shows the issue: https://colab.research.google.com/drive/1_lBgEkebPAdoZ-045qGpjUG_E4IUL60w?usp=sharing

It shows this:

```
DATALOADER:0 TEST RESULTS
{'fake_test_acc': tensor(4.7004e-14)}
```

### Expected behavior

```
DATALOADER:0 TEST RESULTS
{'fake_test_acc': 4.7004e-14}
```

**Comment by tchaton** [comment]
Hey @bryant1410,

Would you want to open a PR and add this functionality ?

It is happening in this function: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py#L245

Best,
T.C

**Comment by shimengfeng** [comment]
Any update on this? I am encountering the same output and would like to have it update. Thank you!
