### ISSUE TITLE
Wrong name in APEX optimization levels

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#5137]
- APEX optimization levels are “O1, O2, O3” and not “01, 02, 03”. We should fix this in code + docs.

Make sure it is clear from the docs that the use of Apex anymore and recommend that users use upstream native AMP available since PyTorch 1.6

**Comment by ayushm-agrawal** [comment]
Hello,
Could you please link this issue in code and docs?

**Comment by shaz13** [comment]
I searched the code and docs. I have found all "O1, O2, O3" not "01,02,03" 

I believe the font at makes it looks more narrow and hence the confusion

1. https://pytorch-lightning.readthedocs.io/en/stable/trainer.html?highlight=amp%20optimization#amp-level
2. https://nvidia.github.io/apex/amp.html#opt-levels

Please link the code/doc if I have missed it @edenlightning

**Comment by ayushm-agrawal** [comment]
@Borda this seems to be fixed?

**Comment by Borda** [comment]
it seems so, @edenlightning ^^
