### ISSUE TITLE
[CI] Fix GitHub Action Release Deprecation

### ISSUE THREAD

**Issue by SeanNaren** [PyTorchLightning/pytorch-lightning#5153]
## 🐛 Bug

GitHub Actions deprecated something within our current CI for docker releases: https://github.com/PyTorchLightning/pytorch-lightning/actions/runs/424422351

@Borda already found what needs to change:

https://https://github.com/PyTorchLightning/pytorch-lightning/blob/597dfa174c9488771044ae5b3496f9ed94f9354a/.github/workflows/release-docker.yml#L29

https://github.com/PyTorchLightning/pytorch-lightning/blob/597dfa174c9488771044ae5b3496f9ed94f9354a/.github/workflows/ci_dockers.yml#L85

**Comment by Borda** [comment]
this is the deprecated call
https://https://github.com/PyTorchLightning/pytorch-lightning/blob/597dfa174c9488771044ae5b3496f9ed94f9354a/.github/workflows/release-docker.yml#L29

this is the new call like
https://github.com/PyTorchLightning/pytorch-lightning/blob/597dfa174c9488771044ae5b3496f9ed94f9354a/.github/workflows/ci_dockers.yml#L85

**Comment by Borda** [comment]
@InCogNiTo124 is interested in...

**Comment by InCogNiTo124** [comment]
@Borda yeah, I'll try to get it done this week :))

**Comment by Borda** [comment]
@InCogNiTo124 how is it going, do you need some help?

**Comment by InCogNiTo124** [comment]
@Borda I will hopefully get it done tmrw
