### ISSUE TITLE
How to compute metric in each step without reseting the metric

### ISSUE THREAD

**Issue by Adoni** [PyTorchLightning/pytorch-lightning#5166]
I want to know a metric during the process of an epoch. That is, I want to know the metric value until now. However, if I call `metric.compute()` in each step, it will reset my metric, which is not expected. I read the source code and didn't find a clever way to do that. So could you tell me how to do that?

**Comment by SkafteNicki** [comment]
Fixed by #5409. Closing this now.

**Comment by Adoni** [comment]
Thanks!

**Comment by Adoni** [comment]
> Fixed by #5409. Closing this now.

Thanks
