### ISSUE TITLE
Improve the default ProgressBar

### ISSUE THREAD

**Issue by aiyolo** [PyTorchLightning/pytorch-lightning#5167]
## 🚀 Feature

It would be great to have different bars to individually indicate different training stage, such as
- train_progress_bar: display the train_loop
- val_progress_bar: display the val_loop
- main_progress_bar: display max_epochs*(train_loop + val_loop)
- test_progress_bar: display the test loop
### Motivation

The current default ProgressBar has some flaws:
- using train_progress_bar to display the train_loop+val_loop, which may get user confused, people are unaware of when the train_loop is finished
- it can't display the ETA of total training process
### Pitch

just like this pic demostrates:
![image](https://user-images.githubusercontent.com/12464091/102469235-799f9500-408d-11eb-8da4-f9b6d71d16d2.png)

**Comment by aiyolo** [comment]
@Borda @awaelchli 
I've implemented this feature in the [colab](https://colab.research.google.com/drive/1YdThfcGap5IIxty05pTo4kqfh5hLwjDw?usp=sharing), is it okay to make a PR?

**Comment by Borda** [comment]
> I've implemented this feature in the [colab](https://colab.research.google.com/drive/1YdThfcGap5IIxty05pTo4kqfh5hLwjDw?usp=sharing), is it okay to make a PR?

sure, send it as Draft for 1.2

**Comment by carmocca** [comment]
IMO we should not make this change to the default progress bar, given how long has it been the way it is.

However, it would be interesting to have more progress bar implementations (such as this one) which subclass the default one and can be used via the `callbacks` Trainer parameter.

**Comment by Borda** [comment]
Yes, changing for default would take some time to prove that the new progress bar is better but we can add a new one and user can decide which he prefers
