### ISSUE TITLE
Failing computer_vision_fine_tuning example

### ISSUE THREAD

**Issue by jspaezp** [PyTorchLightning/pytorch-lightning#5174]
Hello,

I noticed in the current master branch, the computer_vision_fine_tuning example fails to run with the following error.

```
TypeError: __init__() got an unexpected keyword argument 'root_data_path'
```

The error lies in the fact that `root_data_path` is being passed to `pl.LightningModule.__init__` from `main` .

https://github.com/PyTorchLightning/pytorch-lightning/blob/e721b1f51f50d61b6ed77d628e8e08fbae18f2eb/pl_examples/domain_templates/computer_vision_fine_tuning.py#L452

This can be fixed by removing the `**kwargs` in `super().__init__(**kwargs)`. I don't see any arguments in the parser that actually need to be passed to the parent class so It would not lead to bugs due to ignoring the leftover passed arguments.

https://github.com/PyTorchLightning/pytorch-lightning/blob/e721b1f51f50d61b6ed77d628e8e08fbae18f2eb/pl_examples/domain_templates/computer_vision_fine_tuning.py#L185

In addition, it seems like the logging is done in the "outdated" method with the `return {'log': {logging_dict}}` instead of the `self.log_dict(logging_dict)` / `self.log(val)`, would it be in the interest of the project to update it?

https://github.com/PyTorchLightning/pytorch-lightning/blob/e721b1f51f50d61b6ed77d628e8e08fbae18f2eb/pl_examples/domain_templates/computer_vision_fine_tuning.py#L275-L280

https://github.com/PyTorchLightning/pytorch-lightning/blob/e721b1f51f50d61b6ed77d628e8e08fbae18f2eb/pl_examples/domain_templates/computer_vision_fine_tuning.py#L290-L292

would you be interested in me submitting a PR fixing these issues?

Kindest wishes,
Sebastian
related to #4694

**Comment by awaelchli** [comment]
> would you be interested in me submitting a PR fixing these issues?

that would be absolutely amazing! please do!

**Comment by jspaezp** [comment]
Hello @awaelchli I created the PR in: https://github.com/PyTorchLightning/pytorch-lightning/pull/5229

let me know what you think. 
Kindest wishes!

**Comment by jspaezp** [comment]
Closing since it was fixed and merged in https://github.com/PyTorchLightning/pytorch-lightning/commit/17a0784c5e9789ec06e720f5f4a06a80756e73fa
