### ISSUE TITLE
How to inference on GPU?

### ISSUE THREAD

**Issue by Pengyang233** [PyTorchLightning/pytorch-lightning#5177]
## ❓ Questions and Help
Hi.

I have trained a Model with `Trainer.fit()`. Now I want to load the checkpoint at another place and preform inference. But I have no idea how to inference on GPU.  Where could I assign a GPU for my inference just like assigning a GPU before training:
```
trainer = pl.Trainer(max_epochs = cfg['n_epochs'],
                            callbacks=[checkpoint_monitor, lr_monitor],
                            gpus=1)
```
My inference code is (simplified version):
```
model = plModel.load_from_checkpoint('lightning_logs/version_0/checkpoints/model_epoch=17_val_loss=95.99.ckpt')
model.eval()
test_loader =test_dataloader()
        
correct_count = 0
nsample = len(test_loader)
for i, data in enumerate(test_loader):
    output = model(data['x'])
    label = data['label'].data.cpu().numpy()
    pred = nn.functional.softmax(output, dim=1)
    pred = np.argmax(pred.data.cpu().numpy(), axis = 1)
    correct_count += np.sum(pred == label)
accuracy = correct_count / nsample
```
#### What's your environment?
 - OS: [ Linux,]
 - Packaging [pip]
 - Version [1.1.0]

**Comment by awaelchli** [comment]
Hey, in case you didn't know, we have a forum here: https://forums.pytorchlightning.ai/ :) 
You can perform the inference like this (using your code sample):


```python 
trainer = Trainer(gpus=1, ...) 
model = plModel.load_from_checkpoint('lightning_logs/version_0/checkpoints/model_epoch=17_val_loss=95.99.ckpt')
# not needed
# model.eval()

trainer.test(model, test_dataloaders)

# move the rest to the LightningModule:

class PLModel: 

def __init__(self, ...)
   self.accuracy = pl.metrics.Accuracy()        

def test_step(self, batch, batch_idx)
    data = batch
    correct_count = 0
    nsample = len(test_loader)
    output = self(data['x'])
    label = data['label'].data.cpu().numpy()  # optimize this and use torch operations on the gpu instead of numpy
    # use the Metrics package, you can directly feed it logits
    # pred = nn.functional.softmax(output, dim=1)
    # pred = np.argmax(pred.data.cpu().numpy(), axis = 1) 
    self.accuracy(output, label)

def test_epoch_end(self, outputs):
    # log or print
    self.log('test_accuracy', self.accuracy.compute())
```

caution: brain-compiled code

References:
- https://pytorch-lightning.readthedocs.io/en/stable/metrics.html

**Comment by Pengyang233** [comment]
> Hey, in case you didn't know, we have a forum here: https://forums.pytorchlightning.ai/ :)
> You can perform the inference like this (using your code sample):
> 
> ```python
> trainer = Trainer(gpus=1, ...) 
> model = plModel.load_from_checkpoint('lightning_logs/version_0/checkpoints/model_epoch=17_val_loss=95.99.ckpt')
> # not needed
> # model.eval()
> 
> trainer.test(model, test_dataloaders)
> 
> # move the rest to the LightningModule:
> 
> class PLModel: 
> 
> def __init__(self, ...)
>    self.accuracy = pl.metrics.Accuracy()        
> 
> def test_step(self, batch, batch_idx)
>     data = batch
>     correct_count = 0
>     nsample = len(test_loader)
>     output = self(data['x'])
>     label = data['label'].data.cpu().numpy()  # optimize this and use torch operations on the gpu instead of numpy
>     
>     # pred = nn.functional.softmax(output, dim=1)
>     # pred = np.argmax(pred.data.cpu().numpy(), axis = 1) 
> 
>     # use the Metrics [1] package instead, you can directly feed it logits
>     # and it correctly works across multiple gpus should you need that.
>     self.accuracy(output, label)
> 
> def test_epoch_end(self, outputs):
>     # log or print
>     self.log('test_accuracy', self.accuracy.compute())
> ```
> 
> **caution: brain-compiled code**
> 
> References:
> 
> * [1] https://pytorch-lightning.readthedocs.io/en/stable/metrics.html

Thx so much. First time know the forum.

**Comment by msminhas93** [comment]
If you want direct access, it can be done directly using the forward pass as follows. (The way it is done in PyTorch.) This gives you direct access to the variables. 

```
model  = YourLightningModule.load_from_checkpoint(r"path/to/checkout.ckpt")
model.to(device)
data.to(device)
with torch.no_grad():
    out = model(data)
```
You can loop over a dataloader if you want.
