### ISSUE TITLE
group tests into class

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#5178]
## 🚀 Feature

Now, we have quite extensive skip conditions for many tests which are mostly very similar to all test in a single file, so with grouping, we shall clearly mark some features/expectations 

### Motivation

reduce conditions so it easier to navigate 

### Pitch

https://github.com/PyTorchLightning/pytorch-lightning/blob/69123af3ea651a5e1cc25014da6f1c0dee433916/tests/metrics/regression/test_ssim.py#L49-L53

**Comment by carmocca** [comment]
So are you talking about having ready-to-go wrappers? Like they do in PyTorch?

https://github.com/pytorch/pytorch/blob/1aaddd83a501743aad18f2f36da2ba9a2c3eb317/torch/testing/_internal/common_device_type.py#L25

**Comment by Borda** [comment]
well I was thinking about something simples, but that would be nice too

**Comment by kaushikb11** [comment]
@Borda I could pick this up.

**Comment by kaushikb11** [comment]
@Borda This is done, right?

**Comment by Borda** [comment]
no, but it just nice to have... and maybe after our `RunIf` not needed
