### ISSUE TITLE
PyTorch Geometric example removed.

### ISSUE THREAD

**Issue by LindaSt** [PyTorchLightning/pytorch-lightning#5179]
I've save this link https://github.com/PyTorchLightning/pytorch-lightning/tree/master/pl_examples/pytorch_ecosystem/pytorch_geometric a few days ago, but now I get a 404. Did it get moved somewhere else? I tried to google for it, but I can't find it anywhere.

Thanks.

**Comment by rohitgr7** [comment]
moved to geometric repo.
WIP PR: https://github.com/rusty1s/pytorch_geometric/pull/1916

**Comment by awaelchli** [comment]
It was removed in this PR:
https://github.com/PyTorchLightning/pytorch-lightning/pull/5085/files
If you want you can still copy the files there (click on view file, then copy paste)
or you can `git checkout 405a8402b8a82b2bf4a0ebf982939c548e07a27f`
