### ISSUE TITLE
all_gather raises NotImplementedError when no Accelerator defined in Trainer

### ISSUE THREAD

**Issue by 8greg8** [PyTorchLightning/pytorch-lightning#5181]
## 🐛 Bug

When no Accelerator is defined in Trainer, all_gather function in LightningModule raises NotImplementedError.

## Please reproduce using [the BoringModel and post here](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing)

https://colab.research.google.com/drive/1VPEIaQ-aN5KVA70VtvGk24AVkTYPvMoY?usp=sharing

### Expected behavior

* All gather should return a value instead.

### Environment

 * CUDA:
	- GPU:
		- Tesla P100-PCIE-16GB
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.19.4
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0+cu101
	- pytorch-lightning: 1.1.2rc1
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

**Comment by awaelchli** [comment]
Fyi your colab notebook is not public, it can't be accessed :)

**Comment by 8greg8** [comment]
@awaelchli sorry my bad. Corrected and changed the link in bug description. You should be able to access now.

**Comment by awaelchli** [comment]
@tchaton we should provide implementations for all_gather on cpu and single gpu to make code device agnostic.

**Comment by tchaton** [comment]
Hey @awaelchli,

Yes, we should.

Best,
T.C

**Comment by tchaton** [comment]
Dear @8greg8,

I checked the notebook and couldn't reproduce the bug.

@awaelchli I have checked the code and it seems we are already supporting `all_gather on cpu and single gpu`.
However, we don't support gradients for TPU.

Best,
T.C

**Comment by tchaton** [comment]
Dear @8greg8,

I checked the notebook and couldn't reproduce the bug.

@awaelchli I have checked the code and it seems we are already supporting `all_gather on cpu and single gpu`.
However, we don't support gradients for TPU. I opened an issue for it.

Best,
T.C

**Comment by awaelchli** [comment]
Yes because that came automatically with the accelerator refactor and the discussion here is before that was introduced.
Today, Trainer always has an accelerator defined. This issue can be closed if you agree.
