### ISSUE TITLE
fix cache for building docker image with Conda

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#5187]
## 🐛 Bug

actually, three are some problems on master right now
https://github.com/PyTorchLightning/pytorch-lightning/pull/5170/checks?check_run_id=1571579933

```
#6 78.20 Package requests conflicts for:
#6 78.20 torchtext[version='>=0.3.1'] -> requestsThe following specifications were found to be incompatible with your CUDA driver:
#6 78.20 
#6 78.20   - cudatoolkit=10.2.89 -> __cuda[version='>=10.2']
#6 78.20 
#6 78.20 Your installed CUDA driver is: not available
#6 78.20 
#6 78.20 
#6 ERROR: executor failed running [/bin/bash -c conda create -y --name $CONDA_ENV cudatoolkit=${CUDA_VERSION} &&     conda init bash &&     python -c "fname = 'environment.yml' ; req = open(fname).read().replace('pytorch', '${PYTORCH_CHANNEL}', 1) ; open(fname, 'w').write(req)" &&     python -c "import re ; fname = 'environment.yml' ; req = re.sub(r'python[>=]+[\d\.]+', 'python=${PYTHON_VERSION}', open(fname).read()) ; open(fname, 'w').write(req)" &&     python -c "import re ; fname = 'environment.yml' ; req = re.sub(r'torch[>=]+[\d\.]+', 'torch=${PYTORCH_VERSION}', open(fname).read()) ; open(fname, 'w').write(req)" &&     python -c "fname = 'environment.yml' ; req = open(fname).readlines() ; open(fname, 'w').writelines([ln for ln in req if 'horovod' not in ln])" &&     cat environment.yml &&     conda env update --file environment.yml &&     conda clean -ya &&     rm environment.yml]: exit code: 1
```

### Additional context

We need to keep this image updated because it used for our testing...

**Comment by Borda** [comment]
@ydcjeff mind be interested in this one... 🐰

**Comment by ydcjeff** [comment]
I will take a look tmr.

**Comment by Borda** [comment]
just see it also on other images, it is possible that it is random
https://github.com/PyTorchLightning/pytorch-lightning/pull/5172/checks?check_run_id=1581802294
on the other hand is rather strange that it building even without change, so it seems that the cache does not work...

**Comment by ydcjeff** [comment]
@Borda Instead of using cache, how about we schedule the docker build once a week?
Also shall we use github action `paths` to run only `CI build docker` when docker related files are changed?
WDYT?

**Comment by Borda** [comment]
> @Borda Instead of using cache, how about we schedule the docker build once a week?
> Also shall we use github action `paths` to run only `CI build docker` when docker related files are changed?
> WDYT?

we still need to run docker as CI as some PR may edit dockerfiles
but this looks good https://github.com/docker/build-push-action#leverage-github-cache
