### ISSUE TITLE
The behavior of model_checkpoint callback with `save_last=True`

### ISSUE THREAD

**Issue by keunwoochoi** [PyTorchLightning/pytorch-lightning#5188]
I have three questions about this. The doc says..

> save_last (Optional[bool]) – When True, always saves the model at the end of the epoch to a file last.ckpt. Default: None.

I assumed that if I pass, say, `filename='last_model.ckpt'` with `save_last=True`, [1] it would override the default filename for the latest checkpoint with what I pass.

Instead, it behaves differently. After epoch 1, [2] it saves two files.

```
last_model.ckpt
last.ckpt
```

[3] After epoch 2+, the callback overwrite `last.ckpt` and i think it makes sense. it updates `last_model.ckpt` with the latest model and that makes sense. BUT - then, `last_model.ckpt` is renamed to `last_model-v0.ckpt`. So at the end of training, I have two files.

```
last_model-v0.ckpt
last.ckpt
```

So I have multiple questions on this behavior.
On [1], wouldn't it make sense to use the passed `filename` instead of the default `last.ckpt`?
On [2], or if it ignores the passed `filename`, probably shouldn't it only saves `last.ckpt`?
On [3], the renaming behavior is unexpected to me and it seems a little strange. Is it intended?

**Comment by keunwoochoi** [comment]
On [1], additionally, I believe it actually has to use the passed filename because one could want to use two callbacks, one for the model and the other for the weights only, of course with different names.

**Comment by keunwoochoi** [comment]
Ok, I observed another default behavior that if I don't specify `filename`, it automatically saves another file (that probably has the latest model) with a name like `epoch=2-step=5624.ckpt`. And this is somehow explained by the doc saying

> By default, filename is None and will be set to '{epoch}-{step}'.

. But I still don't get why it saves two different files for the same, latest model. Is it an intended behavior?

**Comment by rohitgr7** [comment]
> the renaming behavior is unexpected to me and it seems a little strange. Is it intended?

the renaming is done to ensure that files are not replaced in case same filename is already present in the directory if save_top_k > 1 or -1.. if it's 1, then it will overwrite the `last_model.ckpt` and won't add a version to it. This is fixed on master.

> wouldn't it make sense to use the passed filename instead of the default `last.ckpt`

`last.ckpt` will be saved only when you specify `save_last=True`, mainly it's used to save the checkpoint for last epoch in case the training crash, to ensure the progress isn't lost. Additionally, if you specify `save_last=True`, it will ensure to save the last checkpoint for you along with other regular checkpoints.

**Comment by keunwoochoi** [comment]
Thanks for the answer. I'll take it as "`save_last` means whether the last model is going to be saved *additionally*". Maybe I can make a small PR about the documentation.
