### ISSUE TITLE
RuntimeError: Tensor for 'out' is on CPU, Tensor for argument #1 'self' is on CPU, but expected them to be on GPU (while checking arguments for addmm)

### ISSUE THREAD

**Issue by chunyuma** [PyTorchLightning/pytorch-lightning#5196]
### Before asking: 
1. Try to find answers to your questions in [the Lightning Forum!](https://forums.pytorchlightning.ai/)
2. Search for similar [issues](https://github.com/PyTorchLightning/pytorch-lightning/issues).   
3. Search the [docs](https://pytorch-lightning.readthedocs.io/en/latest/).    

#### What is your question?
Hi,

I'm using pytorch lightning 1.1.0 to train my model. However, I got the following error:

```
  File "./scripts/run_model.py", line 137, in <module>
    trainer.fit(model, train_dataloader=train_loader, val_dataloaders=val_loader)
  File "/home/cma/work/miniconda3/envs/mypersonal_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 470, in fit
    results = self.accelerator_backend.train()
  File "/home/cma/work/miniconda3/envs/mypersonal_env/lib/python3.8/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 66, in train
    results = self.train_or_test()
  File "/home/cma/work/miniconda3/envs/mypersonal_env/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 65, in train_or_test
    results = self.trainer.train()
  File "/home/cma/work/miniconda3/envs/mypersonal_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 492, in train
    self.run_sanity_check(self.get_model())
  File "/home/cma/work/miniconda3/envs/mypersonal_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 690, in run_sanity_check
    _, eval_results = self.run_evaluation(test_mode=False, max_batches=self.num_sanity_val_batches)
  File "/home/cma/work/miniconda3/envs/mypersonal_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 606, in run_evaluation
    output = self.evaluation_loop.evaluation_step(test_mode, batch, batch_idx, dataloader_idx)
  File "/home/cma/work/miniconda3/envs/mypersonal_env/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 178, in evaluation_step
    output = self.trainer.accelerator_backend.validation_step(args)
  File "/home/cma/work/miniconda3/envs/mypersonal_env/lib/python3.8/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 84, in validation_step
    return self._step(self.trainer.model.validation_step, args)
  File "/home/cma/work/miniconda3/envs/mypersonal_env/lib/python3.8/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 74, in _step
    output = model_step(*args)
  File "/export/home/cma/explainable_DTD_model/KG1/GATConv_model_pytorchlightning/scripts/model.py", line 275, in validation_step
    pred_y = self.forward(x_n_id, adjs, link, n_id, return_attention=False)
  File "/export/home/cma/explainable_DTD_model/KG1/GATConv_model_pytorchlightning/scripts/model.py", line 189, in forward
    x = self.convs[i]((x, x_target), edge_index)
  File "/home/cma/work/miniconda3/envs/mypersonal_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/export/home/cma/explainable_DTD_model/KG1/GATConv_model_pytorchlightning/scripts/model.py", line 91, in forward
    x_l = self.lin_l(x_l).view(-1, H, C)
  File "/home/cma/work/miniconda3/envs/mypersonal_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cma/work/miniconda3/envs/mypersonal_env/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/cma/work/miniconda3/envs/mypersonal_env/lib/python3.8/site-packages/torch/nn/functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: Tensor for 'out' is on CPU, Tensor for argument #1 'self' is on CPU, but expected them to be on GPU (while checking arguments for addmm)
```
I understand this error is because the tensors or layers might not in the same device. But I have no idea how to fix it. Since the tutorial of pytorch lightning[ multi-gpu](https://pytorch-lightning.readthedocs.io/en/stable/multi_gpu.html) page suggests to delete all `.cuda()` or `.to()` calls. So I think all layers and tensors should be automatically moved to the appropriate device. 
I didn't get this error when I use `pytorch` where I used some `.to()` functions.

Could you please give me some suggestions about how to fix this error. My `__init__` part and `__forward__` part code is below

#### Code

```python

class GAT(pl.LightningModule):
    def __init__(self, in_channels, hidden_channels, out_channels, num_layers, dropout_p, batch_set, idx_map, feat, num_head = 8, lr=0.005):
        super(GAT, self).__init__()

        self.num_layers = num_layers
        self.dropout_p = dropout_p
        self.lr = lr
        self.save_hyperparameters('in_channels','hidden_channels','out_channels','num_layers','dropout_p','num_head','lr')

        self.convs = torch.nn.ModuleList()
        self.convs.append(GATConv(in_channels, hidden_channels, heads=num_head, dropout=0, concat=False))
        for _ in range(num_layers - 1):
            self.convs.append(GATConv(hidden_channels, hidden_channels, heads=num_head, dropout=0, concat=False))
        self.lin = torch.nn.Linear(hidden_channels*2,out_channels)

    def forward(self, x, adjs, link, n_id, return_attention=False):

        for i, (edge_index, size) in enumerate(adjs):
            x_target = x[:size[1]]
            x = self.convs[i]((x, x_target), edge_index)
            x = F.elu(x)
            x = F.dropout(x, p=self.dropout_p, training=self.training)

        if link.shape[0]==1:
            x = torch.cat([x[[torch.where(n_id==i)[0][0] for i in link[:,0]]].view(1,-1),x[[torch.where(n_id==i)[0][0] for i in link[:,1]]].view(1,-1)], dim=1)
        else:
            x = torch.cat([x[[torch.where(n_id==i)[0][0] for i in link[:,0]],:],x[[torch.where(n_id==i)[0][0] for i in link[:,1]],:]], dim=1)

        x = self.lin(x).squeeze(1)   

        return x

``` 

#### What have you tried?

I tried to add some `.to()` in __init__ to move the layers to `cuda` device but it doesn't work.

#### What's your environment?

 - OS: Linux
 - Packaging: conda
 - Version: pytorch_lightning 1.1.0

**Comment by awaelchli** [comment]
Hi, could you please share the full code (GATConv is undefined) with an example input to forward through the model? It would help us debug.

Please also try to replace `pl.LightningModule` with `torch.nn.Module`, move the module to the gpu and then try to forward an example input.

**Comment by chunyuma** [comment]
Hi @awaelchli, thanks for your reply. GATConv is a convolutional layer from pytorch geometric so you can find its full code [here](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/conv/gat_conv.html#GATConv).

For your suggestion to replace `pl.LightningModule` with `torch.nn.Module`, actually I did use `torch.nn.Module` and it works fine. But since I want to use [shard training](https://pytorch-lightning.readthedocs.io/en/stable/multi_gpu.html) provided by your framework, I need to modify my code written by pytorch to pytorch lightning.  Thank you!

**Comment by balrovi** [comment]
Hello, I had the same error today. I didn't know what was the problem. I accidentally realized I used a seed (here 0) with torch.manual_seed(0) for a random data tain-val split (using torch.utils.data.random_split() ) but I haven't set back the seed by adding torch.manual seed(torch.initial seed()) after the split. Doing this somehow solved the problem for me.

**Comment by LIngerwsk** [comment]
Hello, I met the same bug today. Could you help me?
/content/Transformer_forecasting/Module/model.py:113: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(p)
Traceback (most recent call last):
  File "main.py", line 77, in <module>
    Train()
  File "main.py", line 51, in Train
    myloss = run_module.run_epoch(epoch, DataSet.construct_batch(dataloader_train, vector_in_dim, vector_out_dim), model, loss, model_name)
  File "/content/Transformer_forecasting/train_module/run_module.py", line 60, in run_epoch
    out = model.forward(batch.src, batch.src_mask)
  File "/content/Transformer_forecasting/Module/model.py", line 64, in forward
    out = self.encoder(self.src_embed(src), src_mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/Transformer_forecasting/Module/Embedding.py", line 17, in forward
    return self.lut(x)*math.sqrt(self.d_model)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: Tensor for 'out' is on CPU, Tensor for argument #1 'self' is on CPU, but expected them to be on GPU (while checking arguments for addmm)

`class Encoder_model(nn.Module):
    def __init__(self, encoder, src_embed, generator):
        super(Encoder_model, self).__init__()
        self.encoder = encoder
        self.src_embed = src_embed
        self.generator = generator
        
    def forward(self, src, src_mask):
        out = self.encoder(self.src_embed(src), src_mask)
        out = self.generator(out)
        return out`
`class Encoder(nn.Module):
    "Core encoder is a stack of N layers"
    def __init__(self, layer, N):
        # layer = one EncoderLayer object, N=6
        super(Encoder, self).__init__()
        self.layers = clones(layer, N)
        # 深copy，N=6，
        self.norm = LayerNorm(layer.size)
        # 定义一个LayerNorm，layer.size=d_model=512
        # 其中有两个可训练参数a_2和b_2

    def forward(self, x, mask):
        "Pass the input (and mask) through each layer in turn."
        # x is alike (30, 10, 512)
        # (batch.size, sequence.len, d_model)
        # mask是类似于(batch.size, 10, 10)的矩阵
        for layer in self.layers:
            x = layer(x, mask)
            # 进行六次EncoderLayer操作
        return self.norm(x)

class EncoderLayer(nn.Module):
    "Encoder is made up of self-attn and "
    "feed forward (defined below)"
    def __init__(self, size, self_attn, feed_forward, dropout):
        # size=d_model=512
        # self_attn = MultiHeadAttention对象, first sublayer
        # feed_forward = PositionwiseFeedForward对象，second sublayer
        # dropout = 0.1 (e.g.)
        super(EncoderLayer, self).__init__()
        self.self_attn = self_attn
        self.feed_forward = feed_forward
        self.sublayer = clones(SublayerConnection(size, dropout), 2)
        # 使用深度克隆方法，完整地复制出来两个SublayerConnection
        self.size = size # 512

    def forward(self, x, mask):
        "Follow Figure 1 (left) for connections."
        # x shape = (batch_size, sequence_length, d_model)
        # mask 是(batch.size, sequence_length, sequence_length)的矩阵，类似于当前一个词w，有哪些词是w可见的
        x = self.sublayer[0](x,
          lambda x: self.self_attn(x, x, x, mask))
        # x (batch_size, sequence_length, d_model) -> self_attn (MultiHeadAttention)
        # shape is same (batch_size, sequence_length, d_model) -> SublayerConnection
        # -> (batch_size, sequence_length, d_model)
        return self.sublayer[1](x, self.feed_forward)
        # x 和feed_forward对象一起，给第二个SublayerConnection`

**Comment by awaelchli** [comment]
@chunyuma did @balrovi's answers solve it for you too?
I can't help debug because I don't have the full code.
It looks like the inputs do not get moved to the device, wha does your training_step look like and what is the device of x in the forward of GAT?

**Comment by chunyuma** [comment]
Hi @balrovi and @awaelchli, thanks for your suggestions. However, I think this (set back the seed) should not be the reason for my case because I didn't use `torch.utils.data.random_split()` to do train-val split. Perhaps it might be due to incompatibility in somewhere between pytorch geometric and pytorch lightning.

**Comment by awaelchli** [comment]
sorry, now that you mention it (again)... I overlooked the fact that this is related to pytorch geometric. @tchaton has already brought this up and in the PR here he is trying to fix it for DDP: #5195
Are you using ddp?

**Comment by chunyuma** [comment]
Hi @awaelchli, I plan to use ddp but for the code that arises this error, I haven't used ddp yet.

**Comment by rayhou0710** [comment]
I had the same issue with my experiments and I am using the "dp" backend to train on 8 gpus on a single node.

**Comment by awaelchli** [comment]
@rayhou0710 for DP we can't support custom batch objects currently. see #2350

**Comment by rayhou0710** [comment]
> @rayhou0710 for DP we can't support custom batch objects currently. see #2350

Thanks Adrian! When I debug the issue, I see that its the model that is not moved to the GPU instead of data.

**Comment by guhur** [comment]
For me the problem was due to an issue on my model definition. I forget to use `nn.ModuleList` to initialize a list of modules. So the dependency graph was broken.
