### ISSUE TITLE
Typing: LightningModule casted to double turns into nn.Module

### ISSUE THREAD

**Issue by pisarik** [PyTorchLightning/pytorch-lightning#5219]
## 🐛 Bug

```python
import pytorch_lightning as pl


class PLModule(pl.LightningModule):
    pass


module = PLModule().double()
trainer = pl.Trainer()
trainer.fit(module)

```

You will get a typing warning on the last line in PyCharm:
`Expected type 'LightningModule', got 'Module' instead `

### Expected behavior

No typing warnings

### Environment

PyCharm 2020.3
pytorch-lightning 1.1.1

**Comment by tchaton** [comment]
Hey @pisarik,

I tried with BoringModel and everything seems fine. 

```
def test_lightning_module_conversion(tmpdir):

    class Model(BoringModel):
        def step(self, x):
            x = self(x.double())
            out = torch.nn.functional.mse_loss(x, torch.ones_like(x))
            return out

        def training_step(self, batch, batch_idx):
            output = self.layer(batch.double())
            loss = self.loss(batch, output)
            return {"loss": loss}

        def validation_step(self, batch, batch_idx):
            output = self.layer(batch.double())
            loss = self.loss(batch, output)
            return {"x": loss}

    model = Model()
    model = model.double()
    assert isinstance(model, LightningModule)
    model.training_epoch_end = None

    trainer = Trainer(
        max_epochs=1,
        default_root_dir=tmpdir,
        limit_train_batches=8,
        accumulate_grad_batches=1,
    )

    trainer.fit(model)
```

**Comment by pisarik** [comment]
@tchaton The reason why it works for you is because you added the line `assert isinstance(model, LightningModule)`.
Pycharm recognizes such lines and assumes that after assert the `model` is of type `LightningModule`, otherwise it would raise an error.

If you will remove the line with assert, then you will get exactly the same typing warning as I described.
However, if you will further remove `.double()`, then the typing warning disappear. I.e. casting model to double somehow breaks typings (perhaps because it returns `Module` instead of `LightningModule`).
