### ISSUE TITLE
How to disable automatic SLURM detection / signal handling?

### ISSUE THREAD

**Issue by jbohnslav** [PyTorchLightning/pytorch-lightning#5225]
#### What is your question?

I'm running single-GPU jobs on a SLURM cluster. PyTorch Lightning uses environment variables to detect that I'm on SLURM, and automatically [interrupts SIGTERM signals](https://github.com/PyTorchLightning/pytorch-lightning/blob/d5fa02e7985c3920e72e268ece1366a1de96281b/pytorch_lightning/trainer/connectors/slurm_connector.py#L108). However, when I'm debugging, I don't want the SIGTERM to be bypassed-- I need to know where the signal is originating.

I can't seem to tell PytorchLightning to not use the Slurm handler, because it's automatically detected using environment variables. Is there any way to not use PL's default SLURM connector / SIGTERM bypass function?

 - OS: Linux
 - Packaging pip
 - Version 1.1.1

**Comment by tchaton** [comment]
Hey @williamFalcon. Any idea on this one ?

**Comment by awaelchli** [comment]
@jbohnslav a quick hack could be to delete the slurm env variables like so:

```python
import os
del os.environ[SLURM_NTASKS]
del os.environ[SLURM_JOB_NAME]
```

at the beginning of the script, then lightning will not detect it as slurm. 

Another way could be to grab the original signal handler before trainer init, 
and then restore it on fit start (overwriting the one trainer has set):

```python
import signal
original_sigint_handler = signal.getsignal(signal.SIGTERM)
signal.signal(signal.SIGTERM, original_sigint_handler)
```

(A while back I had a feature PR #3632 that added a configureable way to register signals)

**Comment by YannDubs** [comment]
I just had a similar issue of wanting to deactivate SLURM detection (I use another library to deal with that and pytorch lightning is only one small component of my code). 

Given that wanting to deactivate SLURM detection seems a recurrent usecase (see also #6204 #6389 ) I think there ahoulr really just be a flag to the trainer (e.g. `disable_hpc_detection` as suggested by https://github.com/PyTorchLightning/pytorch-lightning/issues/6389#issuecomment-804344863 )
