### ISSUE TITLE
How to split my model to different gpu?

### ISSUE THREAD

**Issue by Hannibal046** [PyTorchLightning/pytorch-lightning#5227]
[pytorch-lightning forum](https://forums.pytorchlightning.ai/t/how-to-split-my-pytorch-model-to-different-gpu/507)

The problem is above.  Want some help ,thx!

**Comment by awaelchli** [comment]
perhaps you could try sharding
https://pytorch-lightning.readthedocs.io/en/stable/multi_gpu.html#sharded-training

**Comment by tchaton** [comment]
Dear @Hannibal046,

Let me answer on the forum directly !

Best,
T.C
