### ISSUE TITLE
TPU training freeze when define custom backward operation

### ISSUE THREAD

**Issue by rwbfd** [PyTorchLightning/pytorch-lightning#5230]
As is mentioned. A minimal example is here on the colab. 

Here is the address for an example. I have noted where it doesn't work. https://colab.research.google.com/gist/rwbfd/57dde430bc168505cfe7d5c42a31924e/tpu_freeze.ipynb

**Comment by edenlightning** [comment]
@lezwon any chance you can take a look?

**Comment by lezwon** [comment]
@edenlightning will check it out 👍

**Comment by lezwon** [comment]
@rwbfd I ran your notebook with a few minor changes:

- Corrected `pytorch-lightning` version
- Reduced number of dataloader workers from 40 to 4
- used `self.save_hyperparameters()` which helps reloading the model with valid arguments.

Seems to run fine after that.
Link: https://colab.research.google.com/drive/1gZwfOzfTdHLIayw6-ZYYqv-0QZRIMQ9l?usp=sharing
