### ISSUE TITLE
Typo correction in Transfer Learning sample code

### ISSUE THREAD

**Issue by LaserBit** [PyTorchLightning/pytorch-lightning#5231]
I tried to write the code by referring to the [Transfer Learning page](https://pytorch-lightning.readthedocs.io/en/stable/transfer_learning.html#example-imagenet-computer-vision) on readthedocs, but I got `RuntimeError: mat1 dim 1 must match mat2 dim 0`.

Since the FC layer of RenNet50 is a classification of 1000 classes, I tried setting the input of `self.classifier` to 1000, and it worked.

I am new to machine learning, so I am not sure if this is really the right fix. Thanks!

**Comment by Borda** [comment]
Good catch and thx for the PR :]
