### ISSUE TITLE
LightningModule .load_from_checkpoint  requires specific model signature

### ISSUE THREAD

**Issue by vitusbenson** [PyTorchLightning/pytorch-lightning#5266]
I have a LightningModule similar to this:

```python
class MyLightningModule(pl.LightningModule):
    def __init__(self, model: nn.Module, hparams: argparse.Namespace):
          init code here
    @staticmethod
    def add_task_specific_args(parent_parser: Optional[Union[argparse.ArgumentParser,list]] = None):
          arguments added here
```

Unfortunately this type of signature does not seem to be supported by 

```python
.load_from_checkpoint(checkpoint_path=my/ckpt/path)
```
see here:
https://github.com/PyTorchLightning/pytorch-lightning/blob/cdbddbe99f5b77e253eb627edf98c3159add9583/pytorch_lightning/core/saving.py#L192

at least I get the following Error:
```bash
File "/opt/conda/envs/MyEnv/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 192, in _load_model_state
    model = cls(**_cls_kwargs)
TypeError: __init__() missing 2 required positional arguments: 'model' and 'hparams'
```

So basically what I am wondering, I would like to keep the "model" separate from the "training/experiment" and also use Lightning for saving/loading weights. How do I achieve this?

**Comment by aiyolo** [comment]
Hello.
from my practice, if you add a line `self.save_hyperparameters()` in the `__init__()` method of your self defined model, e.g. `SelfDefinedModel()` , you only need to use `SelfDefinedModel.load_from_checkpoint('checkpoint.ckpt')` to load the checkpoint, otherwise, you will need to use  `SelfDefinedModel.load_from_checkpoint('checkpoint.ckpt', **params)` ,where `params` is what you pass to the `__init__()` method.

**Comment by vitusbenson** [comment]
> Hello.
> from my practice, if you add a line `self.save_hyperparameters()` in the `__init__()` method of your self defined model, e.g. `SelfDefinedModel()` , you only need to use `SelfDefinedModel.load_from_checkpoint('checkpoint.ckpt')` to load the checkpoint, otherwise, you will need to use `SelfDefinedModel.load_from_checkpoint('checkpoint.ckpt', **params)` ,where `params` is what you pass to the `__init__()` method.

Wow thank you that was rather simple. Exactly what I needed!
