### ISSUE TITLE
Replace custom samplers with distributed versions when replace_sampler_ddp=True

### ISSUE THREAD

**Issue by i-pan** [PyTorchLightning/pytorch-lightning#5271]
## 🚀 Feature
Replace custom samplers with distributed versions when `replace_sampler_ddp=True`.

### Motivation

One of the issues I've been having is using custom samplers with distributed training. Prior to Lightning, I was using the `DistributedSamplerWrapper` class from Catalyst (https://catalyst-team.github.io/catalyst/_modules/catalyst/data/sampler.html) as part of my own pipeline to use custom samplers during distributed training. 

When I try to define my own custom `DistributedSampler` when using Lightning, I always get the following error:
`AssertionError: Default process group is not initialized`

It makes sense because the data loader gets called before distributed is initialized. (See: https://github.com/PyTorchLightning/pytorch-lightning/issues/3238#issuecomment-695421373) 

However unlike in the comment, I'm unable to create the `DistributedSampler` by just leaving the arguments as their default since I always get the above `AssertionError`. It looks like the original poster was using TPUs, and it seems that on TPUs you can pass `rank` and `num_replicas` to the sampler without having to run `torch.distributed.init_process_group()`.  

### Pitch

Basically, what I do now is I manually edit the `TrainerDataLoadingMixin` class in `trainer/data_loading.py`.

I change the `auto_add_sampler()` method:
```
if self.replace_sampler_ddp and need_dist_sampler:
    if not isinstance(dataloader.sampler, (SequentialSampler, RandomSampler)):
        rank_zero_warn('Replacing custom sampler with distributed version ...')
        sampler = self._wrap_distributed_sampler(dataloader, shuffle)
    else:
        sampler = self._get_distributed_sampler(dataloader, shuffle)
dataloader = self.replace_sampler(dataloader, sampler)
```

New `_wrap_distributed_sampler()` method:
```
def _wrap_distributed_sampler(self, dataloader, shuffle):
    kwargs = self.distributed_sampler_kwargs
    kwargs['shuffle'] = shuffle and not self.overfit_batches
    sampler = DistributedSamplerWrapper(dataloader.sampler, **kwargs)
    return sampler
```

### Alternatives

There may be a simple workaround that I'm missing for why I'm not able to pass in my own custom distributed samplers, in which case this wouldn't be needed.

**Comment by awaelchli** [comment]
> When I try to define my own custom DistributedSampler when using Lightning, I always get the following error:
> AssertionError: Default process group is not initialized

You are probably trying to instantiate the DistributedSampler somewhere in the main process where the process group is not initialized yet. Move the relevant code to the `train_dataloader` or `setup` hook in your `LightningModule`, then it will work, because these hooks get called at the right time after distributed is initialized. Let me know if that works for you. We could consider adding a hint in the docs.

**Comment by ctlaltdefeat** [comment]
> > When I try to define my own custom DistributedSampler when using Lightning, I always get the following error:
> > AssertionError: Default process group is not initialized
> 
> You are probably trying to instantiate the DistributedSampler somewhere in the main process where the process group is not initialized yet. Move the relevant code to the `train_dataloader` or `setup` hook in your `LightningModule`, then it will work, because these hooks get called at the right time after distributed is initialized. Let me know if that works for you. We could consider adding a hint in the docs.

I am using a distributed wrapper around a custom sampler as well, and moving the code to the `train_dataloader` and `val_dataloader` hooks still give the same error:
```AssertionError: Default process group is not initialized```
What could be going wrong?

**Comment by swethmandava** [comment]
```
Traceback (most recent call last):
  File "finetune.py", line 495, in <module>
    main(args)
  File "finetune.py", line 462, in main
    logger=logger,
  File "/workspace/bart/lightning_base.py", line 428, in generic_train
    trainer.fit(model)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 471, in fit
    self.call_setup_hook(model)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1072, in call_setup_hook
    model.setup(stage_name)
  File "/workspace/bart/lightning_base.py", line 172, in setup
    self.train_loader = self.get_dataloader("train", self.hparams.train_batch_size, shuffle=True)
  File "finetune.py", line 271, in get_dataloader
    sampler = dataset.make_sortish_sampler(batch_size, distributed=self.hparams.gpus > 1)
  File "/workspace/bart/utils/utils.py", line 162, in make_sortish_sampler
    return DistributedSortishSampler(self, batch_size, shuffle=shuffle, **kwargs)
  File "/workspace/bart/utils/utils.py", line 381, in __init__
    num_replicas = dist.get_world_size()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 650, in get_world_size
    return _get_group_size(group)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 228, in _get_group_size
    _check_default_pg()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 220, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized
```

I have the same issue - my instantiation is in setup

**Comment by swethmandava** [comment]
Moving instantiation to train_dataloader instead of setup works for me.
