### ISSUE TITLE
the speed of each iteration halves with two GPUs

### ISSUE THREAD

**Issue by hanikh** [PyTorchLightning/pytorch-lightning#5276]
## 🐛 Bug

I am running this github repository https://github.com/mindslab-ai/faceshifter. In the first experiment, I used one GPU and the speed was about 1.34it/s (there was 994470 iterations, using DDP).  In the next experiment, I used two GPUs and this time the speed almost halved to 1.38s/it (this time there was 497235 iterations). Consequently, the speed of the whole algorithm does not change considerably.

### Expected behavior

I expect that the speed of each iteration does not change with 2 GPUs, as I am working with DDP and the whole batch is given to one GPU and since I have not changed batch size in both experiments (with one and two GPUs).

### Environment

 - PyTorch Version: 1.8
 - OS: ubuntu 18
 - Python version: Python 3.6.10
 - CUDA/cuDNN version: V11.1.74
 - GPUs: GeForce RTX 3090, GeForce RTX 3090

**Comment by rohitgr7** [comment]
If you set batch_size=32 then in your case with 2 GPUs with DDP the effective batch_size will be 64. So in both cases, the time per training step is almost the same but the iterations reduce hence eventually the total time per epoch reduced to half.

**Comment by hanikh** [comment]
the batch_size with one GPU is 8 and I can not change it with two GPUs (as far as I know the whole batch is not divided between GPUs. in my case, doubling the batch_size leads to cuda out of memory). so with two GPUs the effective batch_size is 16 (as you also said) but the reduction in the number of iterations is exactly the result of this increase in batch_size. 
to sum up, now the number iterations halves (as a result of batch_size getting doubled) and the time needed for each iteration doubles. so the total speed does not change

**Comment by hanikh** [comment]
the time per iteration are not the same. one of them is 1.34 **iteration per second** and the other one is 1.38 s**econd per iteration**

**Comment by hanikh** [comment]
the time per iteration is not the same. one of them is 1.34 **iteration per second** and the other one is 1.38 **second per iteration**

**Comment by hanikh** [comment]
actually my question is why the speed of per training step has halved with two GPUs. 
with one GPU about: 0.7s/it
with 2 GPUs about: 1.4 s/it

**Comment by hanikh** [comment]
actually my question is why the speed of training step has halved with two GPUs.
with one GPU about: 0.7s/it
with 2 GPUs about: 1.4 s/it

**Comment by rohitgr7** [comment]
ah... my bad I misread the units up there. Mind reproduce it with https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing? cc @williamFalcon

**Comment by edenlightning** [comment]
@hanikh mind reproducing?

**Comment by edenlightning** [comment]
Feel free to reopen with our boring example!
