### ISSUE TITLE
TestTubeLogger fails to log tensorboard hparams

### ISSUE THREAD

**Issue by thavlik** [PyTorchLightning/pytorch-lightning#5304]
## 🐛 Bug

I recall TestTubeLogger used to give me an HParams tab in tensorboard. Possibly since the changes described #2974 #3610 this is no longer the case, and the "fix" seems to entail discarding TestTubeLogger and using TensorboardLogger instead, but I am unable to do such a thing due to heavy code dependence on TestTubeLogger. There is never an HParams tab in TB regardless of calls to `tt_logger.log_hyperparams(config)` and `self.save_hyperparameters(config)` in my LightningModule constructor.

Switching to TensorboardLogger **does** cause the HParams tab to appear as expected, as suggested in the aforementioned issues. This issue is limited to PL's TestTubeLogger.

Does TestTubeLogger have the capability of writing HParams data for TB? Perhaps I am mistaken, and this was never possible. 

Thanks!

### Environment
pytorch-lightning==1.1.2

**Comment by s-rog** [comment]
I'm pretty sure test tube logger only logs hparams to the text tab of tensorboard (unless there was a PR I missed). If you need the hparams view, you'd have to use tb logger... there shouldn't be too much code you need to change?

Also the linked tb logger changes should not affect test tube.

**Comment by thavlik** [comment]
I was indeed mistaken, and the HParams tab appears during my hparam search as a result of calls to `tune.report()` (I use PL for the main implementation and wrap it with ray/tune for hparam searches).

Thank you for the clarification!
