### ISSUE TITLE
non-str key in hparam dict causes exception in logging

### ISSUE THREAD

**Issue by indigoviolet** [PyTorchLightning/pytorch-lightning#5311]
## 🐛 Bug

The `_flatten_dict` function in `LightningLoggerBase` assumes that dicts will only have string keys. Passing a hparam like `{2:3}` will break it.

## Please reproduce using the BoringModel

https://colab.research.google.com/drive/1qN5oIzPcH18QSZhAMy9N-YDkeDkc4-fy

### To Reproduce

Use following [**BoringModel**](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing) and post here

### Expected behavior

It should cast to str before logging

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

* `IDE`: Please, use our python [bug_report_model.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
) template.

* `Colab Notebook`: Please copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py) (or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0+cu101
	- pytorch-lightning: 0.10.0
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020
### Additional context

<!-- Add any other context about the problem here. -->

**Comment by Borda** [comment]
@indigoviolet good catch, mind sending a PR with the fix? 🐰

**Comment by marload** [comment]
Can i take this issue?
