### ISSUE TITLE
Keep the data structure of tensor-like objects after moving them to devices

### ISSUE THREAD

**Issue by MultiLi** [PyTorchLightning/pytorch-lightning#5313]
## 🚀 Feature
For now, PL handles the device conversion of data pretty good and make it almost transparent to users. But there are still restrictions like 1. data must be instances of torch.Tensor (or its subclasses) to be convertible, 2. after conversion, the data lose the original structures (and become torch.Tensor even if they are actually instances of its subclasses).

So I wonder if we can relax the limitation of the data, for example, to those data structures that have ".to()" method, and thus can preserve the original data structures after device conversion.

### Motivation
Make it easier to utilize structured data, like those [defined in detectron2](https://github.com/facebookresearch/detectron2/tree/master/detectron2/structures).

### Pitch

Keep the original class information after the data conversion

### Alternatives

If the relaxation is too loose, it's okay to keep the type check of torch.Tensor

**Comment by rohitgr7** [comment]
it does preserve the data structure if it has a `to` method.
tried this:
```python
from pytorch_lightning.utilities import move_data_to_device  # by default lightning uses this method to move data to the device

dev = torch.device('cuda')
a = Boxes(torch.randn(4, 4))
a = move_data_to_device(a, dev)
print(type(a), a.device, a.tensor.device)
```
Output:
```
<class '__main__.Boxes'> cuda:0 cuda:0
```

mind share a code sample where it doesn't work as expected??

**Comment by MultiLi** [comment]
> it does preserve the data structure if it has a `to` method.
> tried this:
> 
> ```python
> from pytorch_lightning.utilities import move_data_to_device  # by default lightning uses this method to move data to the device
> 
> dev = torch.device('cuda')
> a = Boxes(torch.randn(4, 4))
> a = move_data_to_device(a, dev)
> print(type(a), a.device, a.tensor.device)
> ```
> 
> Output:
> 
> ```
> <class '__main__.Boxes'> cuda:0 cuda:0
> ```
> 
> mind share a code sample where it doesn't work as expected??

Hi, thanks for the reply.

I can't provide a code sample since I don't move data to device manually.

Instead, I tried to put some data of custom structures in the output of data loader, and used them in modules. 

In that situation, if the custom structure is a subclass of torch.Tensor, the data becomes a torch.Tensor after the conversion. Or if not, then it won't be moved to device. It looks to me that the automatic conversion only works well on torch.Tensor.

**Comment by rohitgr7** [comment]
> Or if not, then it won't be moved to device (even if there is a .to method).

In the above code, `Boxes` has a `to` method defined and after moving the batch to the correct device it preserved the data structure.

For the other case, I need something (a simple code sample) to see where it's going wrong.

**Comment by awaelchli** [comment]
@MultiLi Is there a specific reason why you need to subclass Tensor? And in which cases does this break in Lighting? Afaik we only call .to() on tensors and we do instance checks against torch.Tensor which should work fine with your classes.
