### ISSUE TITLE
Tests refactoring - deprecating EvaluationModel

### ISSUE THREAD

**Issue by gianscarpe** [PyTorchLightning/pytorch-lightning#5328]
## 🚀 Feature

Deprecation of old trainer APIs (e.g., checkpoint_callback) and of EvaluationModel in favor of new APIs (e.g., callbacks) and BoringModel. Take PR  #4820 as an example. 
This issue should be tackled one file at the time to allow better review process (as discussed with @Borda).
NOTE (1): Every test should use default BoringModel class or inherit BoringModel to add specific features (e.g., different optimizer) as discussed with @williamFalcon.

### Motivation

Code refactoring, tests code-base will be cleaner and easier to extend/improve. New users can refer to tests as a documentation for pytorch-lightning usage and common practices.

### Pitch
In the end, we will base tests only on BoringModel.

**Comment by Borda** [comment]
Replacing old mixin-based `EvaluationModel` is essential and very needed, also as mentioned making it per file/case
On the other hand, I would make test API cleaning as a separate issue (if we re-write some test with `BoringModel` it shall always follow the latest API, but updating just test which already uses `BoringModel` shall be separate, btw, I think that this is almost fixed) 🐰 
Also, it would be nice to do some test pruning - for some simple cases, fuser tested values together, which shall make testing faster as many tests need to instantiate Trainer and Model and run a few steps and SIMPLIFY navigation in tests as now it is a bit jungle... 🌴

**Comment by Borda** [comment]
> I also suggest to add static types to move forward full-coverage of type checking. E.g.,
> 
> ```
> def foo(bar: str) -> int:
>    return len(bar)
> ```
> 
> It's a function that receives a string and return an int. Mypy will check if this function is used improperly.

FYI, we already have an issue for it #5023 so maybe we can skip it from this issue description...

**Comment by edenlightning** [comment]
@Borda what is left TODO here?

**Comment by Borda** [comment]
done :rabbit:
