### ISSUE TITLE
Logging momentum in LearningRateMonitor

### ISSUE THREAD

**Issue by sourabh-nutonomy** [PyTorchLightning/pytorch-lightning#5330]
## 🐛 Bug

Trying to log momentum in [LearningRateMonitor](https://pytorch-lightning.readthedocs.io/en/stable/generated/pytorch_lightning.callbacks.LearningRateMonitor.html?highlight=LearningRateMonitor) crashes training. When `log_momentum = False`, everything runs smoothly.

## Please reproduce using the BoringModel

https://colab.research.google.com/drive/1JiSrB4JYexxMAjPPdnbv4Q0ShqRH2YJQ?usp=sharing

### Environment

* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.19.4
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0+cu101
	- pytorch-lightning: 1.1.2
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

**Comment by rohitgr7** [comment]
nice catch! should log betas[0] when using Adam.
