### ISSUE TITLE
Dictionary accumulate_grad_batches doesn't work with model checkpoint loading

### ISSUE THREAD

**Issue by jonashaag** [PyTorchLightning/pytorch-lightning#5334]
## 🐛 Bug

If you pass `Trainer(accumulate_grad_batches={5: 2})` and reload a model checkpoint using `resume_from_checkpoint`, checkpoint loading will crash with

```
Traceback (most recent call last):
  ...
    trainer.fit(system)
  File "/home/jo/.venvs/au/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 470, in fit
    results = self.accelerator_backend.train()
  File "/home/jo/.venvs/au/lib/python3.8/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 63, in train
    self.trainer.train_loop.setup_training(model)
  File "/home/jo/.venvs/au/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 175, in setup_training
    self.trainer.checkpoint_connector.restore_weights(model)
  File "/home/jo/.venvs/au/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 64, in restore_weights
    self.restore(self.trainer.resume_from_checkpoint, on_gpu=self.trainer.on_gpu)
  File "/home/jo/.venvs/au/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 102, in restore
    self.restore_training_state(checkpoint)
  File "/home/jo/.venvs/au/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 164, in restore_training_state
    expected_steps = self.trainer.num_training_batches / n_accum
TypeError: unsupported operand type(s) for /: 'int' and 'dict'
```

Relevant code assumes `accumulate_grad_batches` is an integer:

https://github.com/PyTorchLightning/pytorch-lightning/blob/d20fd8e5ab1a52747fee2cd53290a679d8b726d0/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L156-L157

### Environment

```
* Packages:
	- numpy:             1.19.4
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0+cu110
	- pytorch-lightning: 1.1.0
	- tqdm:              4.51.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:
	- python:            3.8.5
	- version:           #1 SMP PREEMPT Tue Dec 22 08:14:42 UTC 2020
```

**Comment by marload** [comment]
Can i fix this issue?

**Comment by tchaton** [comment]
Hey @marload,

Yes, definitely. Feel free to take this one. Let me assign it to you.

Best regards,
T.C

**Comment by edenlightning** [comment]
hey @marload! Any update/ways we can help?

**Comment by carlomarxdk** [comment]
Any there any temporary workarounds for this issue?

**Comment by tchaton** [comment]
Dear @jonashaag, @carlomarxdk,

Would you mind to try master ? If the bug still persists, could you provide a reproducible script using the BoringModel ?

Best,
T.C

**Comment by ebartrum** [comment]
Hey, here is code to reproduce. First run `python train.py`, wait a few epochs (takes a few seconds) and cancel. Then run `python train.py --resume_from_ckpt=lightning_logs/<PATH TO CHECKPOINT YOU JUST CREATED>`
This gives me the error with pytorch lightning version 1.1.6

Save this file as train.py:

import os
import torch
from torch.utils.data import Dataset
from pytorch_lightning import LightningModule, Trainer
import argparse

class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len

class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def loss(self, batch, prediction):
        # An arbitrary loss to have a loss that updates the model weights during `Trainer.fit` calls
        return torch.nn.functional.mse_loss(prediction, torch.ones_like(prediction))

    def step(self, x):
        x = self.layer(x)
        out = torch.nn.functional.mse_loss(x, torch.ones_like(x))
        return out

    def training_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"loss": loss}

    def training_step_end(self, training_step_outputs):
        return training_step_outputs

    def training_epoch_end(self, outputs) -> None:
        torch.stack([x["loss"] for x in outputs]).mean()

    def validation_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"x": loss}

    def validation_epoch_end(self, outputs) -> None:
        torch.stack([x['x'] for x in outputs]).mean()

    def test_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"y": loss}

    def test_epoch_end(self, outputs) -> None:
        torch.stack([x["y"] for x in outputs]).mean()

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1)
        return [optimizer], [lr_scheduler]

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--resume_from_ckpt")
    args = parser.parse_args()

    train_data = torch.utils.data.DataLoader(RandomDataset(32, 64), num_workers=8)
    val_data = torch.utils.data.DataLoader(RandomDataset(32, 64), num_workers=8)
    model = BoringModel()
    trainer = Trainer(
        max_epochs=99999,
        gpus=-1,
        accumulate_grad_batches={2:2},
        distributed_backend="ddp",
        resume_from_checkpoint=args.resume_from_ckpt
    )
    trainer.fit(model, train_data, val_data)

**Comment by ebartrum** [comment]
I think this might solve it? Try to deal with the dictionary case by looking up the current n_accum. Perhaps theres a neater way though. Should I make a PR? Changes to 156 in checkpoint connector:
       
```
 # Division deals with global step stepping once per accumulated batch
        # Inequality deals with different global step for odd vs even num_training_batches
        if self.trainer.accumulate_grad_batches is None:
            n_accum = 1
        elif type(self.trainer.accumulate_grad_batches) == int:
            n_accum = self.trainer.accumulate_grad_batches
        if type(self.trainer.accumulate_grad_batches) == dict:
            grad_batch_key = max([k for k in\
                    self.trainer.accumulate_grad_batches.keys()\
                    if k < self.trainer.current_epoch])
            n_accum = self.trainer.accumulate_grad_batches[grad_batch_key]
```


> ## bug Bug
> 
> If you pass `Trainer(accumulate_grad_batches={5: 2})` and reload a model checkpoint using `resume_from_checkpoint`, checkpoint loading will crash with
> 
> ```
> Traceback (most recent call last):
>   ...
>     trainer.fit(system)
>   File "/home/jo/.venvs/au/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 470, in fit
>     results = self.accelerator_backend.train()
>   File "/home/jo/.venvs/au/lib/python3.8/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 63, in train
>     self.trainer.train_loop.setup_training(model)
>   File "/home/jo/.venvs/au/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 175, in setup_training
>     self.trainer.checkpoint_connector.restore_weights(model)
>   File "/home/jo/.venvs/au/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 64, in restore_weights
>     self.restore(self.trainer.resume_from_checkpoint, on_gpu=self.trainer.on_gpu)
>   File "/home/jo/.venvs/au/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 102, in restore
>     self.restore_training_state(checkpoint)
>   File "/home/jo/.venvs/au/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 164, in restore_training_state
>     expected_steps = self.trainer.num_training_batches / n_accum
> TypeError: unsupported operand type(s) for /: 'int' and 'dict'
> ```
> 
> Relevant code assumes `accumulate_grad_batches` is an integer:
> 
> https://github.com/PyTorchLightning/pytorch-lightning/blob/d20fd8e5ab1a52747fee2cd53290a679d8b726d0/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L156-L157
> 
> ### Environment
> 
> ```
> * Packages:
> 	- numpy:             1.19.4
> 	- pyTorch_debug:     True
> 	- pyTorch_version:   1.7.0+cu110
> 	- pytorch-lightning: 1.1.0
> 	- tqdm:              4.51.0
> * System:
> 	- OS:                Linux
> 	- architecture:
> 		- 64bit
> 		- ELF
> 	- processor:
> 	- python:            3.8.5
> 	- version:           #1 SMP PREEMPT Tue Dec 22 08:14:42 UTC 2020
> ```
