### ISSUE TITLE
Loading PL model from checkpoint with only weights

### ISSUE THREAD

**Issue by celsofranssa** [PyTorchLightning/pytorch-lightning#5337]
Hello,

How to properly load the PL model when [ModelCheckpoint](https://pytorch-lightning.readthedocs.io/en/stable/generated/pytorch_lightning.callbacks.ModelCheckpoint.html#modelcheckpoint) has `save_weights_only=True` ?

**Comment by rohitgr7** [comment]
it just save the weights, so all you need to do is:
```python
model = LitModule.load_from_checkpoint(ckpt_path_with_only_saved_weights)
```

**Comment by celsofranssa** [comment]
My Lit module looks like:
```python
class LitModule(LightningModule):

    def __init__(self, hparams):
        super(LitModule, self).__init__()
        self.hparams = hparams
        # loading huggingface pretrained transformer
        self.x1_encoder = BertModel.from_pretrained(hparams.architecture, hparams.output_attentions)
        self.x2_encoder = BertModel.from_pretrained(hparams.architecture, hparams.output_attentions)
```
where `hparams` is a dictionary containing the hyperparameters of the model loaded via [Hydra config](https://hydra.cc/docs/intro/).

This model does not need to export attentions (`hparams.output_attentions` is `False`) during training step but this is necessary during inference (`hparams.output_attentions` is `True`) after having the checkpoint loaded.

Then, would it be possible to pass a different `hparams` when loading the checkpoint?

**Comment by rohitgr7** [comment]
not familier with Hydra, but maybe try:
```python
model = LitModule.load_from_checkpoint(ckpt_path, output_attentions=True)
```

**Comment by celsofranssa** [comment]
It works, however `hparams` is a dictionary that defines a series of hyperparameters and is loaded from yaml file using hydra (has been [hydra](https://hydra.cc/docs/intro) removed from the PL?). So, I found the following solution:

```python
def inference_step(hparams):
  model = LitModule.load_from_checkpoint(
          checkpoint_path=hparams.model.checkpoint_path,
          **hparams.model # nested dict with model hyperparameters
  )
...
```

**Comment by tchaton** [comment]
Hey @celsofranssa,

```
  model = LitModule.load_from_checkpoint(
          checkpoint_path=hparams.model.checkpoint_path,
          **hparams.model # nested dict with model hyperparameters
  )
```

seems good to me !

Closing this issue for now.

Best,
T.C

**Comment by ofsoundof** [comment]
> It works, however `hparams` is a dictionary that defines a series of hyperparameters and is loaded from yaml file using hydra (has been [hydra](https://hydra.cc/docs/intro) removed from the PL?). So, I found the following solution:
> 
> ```python
> def inference_step(hparams):
>   model = LitModule.load_from_checkpoint(
>           checkpoint_path=hparams.model.checkpoint_path,
>           **hparams.model # nested dict with model hyperparameters
>   )
> ...
> ```

This is a very good solution!
