### ISSUE TITLE
Add LambdaCallback

### ISSUE THREAD

**Issue by marload** [PyTorchLightning/pytorch-lightning#5343]
## 🚀 Feature

Add `LambdaCallback` for quick and easy callback creation. 

### Motivation

Previously, we had to make a callback class in order to make a callback. However, Lambda Callback makes it easy to create a simple Callback without declaring a Class. TensorFlow officially provides this callback, which can be used very efficiently.

https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/LambdaCallback

### Pitch

Add a new callback, `LambdaCallback`

**Comment by marload** [comment]
If this feature is considered useful, I'm going to contribute.

**Comment by tchaton** [comment]
Hey @marload,

Yes, it would definitely be a great addition. Let's follow Keras API as it is pretty intuitive !
Feel free to submit a PR and ping me as reviewer.

Best,
T.C
