### ISSUE TITLE
What is _input_format

### ISSUE THREAD

**Issue by sachinruk** [PyTorchLightning/pytorch-lightning#5344]
Hi,

I've seen `_input_format` in the example for metrics, but I can't see where it mentions what it is: https://pytorch-lightning.readthedocs.io/en/latest/metrics.html#implementing-a-metric. Any help would be appreciated :)

**Comment by tchaton** [comment]
Hey @sachinruk,

The `_input_format ` was added there as a best practice example. This function should be implemented to validate the correct format of provided data.

Best regards,
T.C
