### ISSUE TITLE
Error with `load_from_checkpoint` 

### ISSUE THREAD

**Issue by bnaman50** [PyTorchLightning/pytorch-lightning#5345]
I am trying to fine-tune a language model and facing some issues with loading the model from the saved checkpoint. 

I have defined my own model which takes in `argparse.NameSpace` as the input as is suggested in the documentation [here](https://pytorch-lightning.readthedocs.io/en/latest/hyperparameters.html). 

```
class FineTuner(pl.LightningModule):
    def __init__(self, hparams):  # pass all the arguments
        super(FineTuner, self).__init__()
        self.hparams = hparams
```

After I am done with the fine-tuning, I try to load the model from saved checkpoint **in a separate file** as follows - 
```
from model_file import FineTuner
model = FineTuner.load_from_checkpoint(ckpt_path)
```

but it gives me the following error - 
`AttributeError: 'dict' object has no attribute 'tokenizer_name'`

I tried to look into the source code and found that the error is happening at this [line](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/core/saving.py#L192). 
I believe the error is occurring because the aforementioned line in `saving.py` file expects a `**dict` which is different from my model definition. 

**It would be great if you could solve this issue as I have seen many others are also having similar issues with model loading.** 

### For others who might still be looking for the answer, here is the workaround that I am using right now 
(but would still like to use the cleaner official version) - 
```
ckpt_path = abs_path('./path/to/ckpt/file')
checkpoint = torch.load(ckpt_path, map_location=lambda storage, loc: storage)
model = my_model(checkpoint['hyper_parameters']) #(better solution than explicitly providing all the hyperparameters)
model.load_state_dict(checkpoint['state_dict'])
```
If one were to look at the source code, you would notice that they are kind of doing the same steps but with some extra stuff ;) 
But hey, who does not like one-liners. 

I am using version version `1.0.4`.

**Comment by tchaton** [comment]
Hey @bnaman50,

Thanks for reporting this behaviour.
For now, you could change your `FineTuner` class as follow:

```
class FineTuner(...):
    def __init__(self, *args, arg_1, ...,arg_n, kwarg_1=..., ..., kwarg_n=...,  **kwargs):
```

So extra parameters doesn't break the loading.

Best,
T.X

**Comment by awaelchli** [comment]
You are seeing this error because you use the old way of setting hyperparameters. The docs warn about deprecation. Generally speaking, you want to replace the line `self.hparams = hparams` with the new `self.save_hyperparameters()` and use the constructor format suggested by @tchaton.

**Comment by edenlightning** [comment]
closing this. feel free to reopen of needed.
