### ISSUE TITLE
Lightning does not support DDP with Sparse Gradients

### ISSUE THREAD

**Issue by LithiumH** [PyTorchLightning/pytorch-lightning#5355]
## 🐛 Bug

Since all_reduce is currently only implemented for Gloo backend, there needs to be a way to choose gloo as the backend when initializing the ddp process group.

Relevant Pytorch issue: https://github.com/pytorch/pytorch/issues/22400
Relevant Lightning file: https://github.com/PyTorchLightning/pytorch-lightning/blob/ee9b3fe5744ff7b908b02483fea17f68c6e228fd/pytorch_lightning/plugins/ddp_plugin.py

Otherwise, any sparse gradient optimizer will cause RuntimeError: Tensors must be CUDA and dense 

## Please reproduce using the BoringModel
```
import torch
import torch.nn as nn
import torch.nn.functional as F
import pytorch_lightning as pl

from torch.optim import SparseAdam
from torch.utils.data.dataloader import DataLoader
from torch.utils.data import Dataset

class DummyDataset(Dataset):
    def __getitem__(self, i):
        return torch.zeros(5, dtype=torch.long)
    
    def __len__(self):
        return 10

class SparseModel(pl.LightningModule):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.embeddings = nn.Embedding(10, 10, sparse=True)

    def forward(self, batch):
        return self.embeddings(batch)

    def training_step(self, batch, batch_idx):
        embs = self.embeddings(batch)
        return F.mse_loss(embs, torch.ones(embs.size(), device=self.device))

    def train_dataloader(self) -> DataLoader:
        return DataLoader(DummyDataset(), num_workers=0)

    def configure_optimizers(self):
        return SparseAdam(self.embeddings.parameters(), 1e-2)

if __name__ == "__main__":
    model = SparseModel()
    trainer = pl.Trainer(gpus=2, accelerator='ddp')
    trainer.fit(model)
```
### To Reproduce

Run the code above

### Expected behavior

Model successfully trains

### Actual behavior
Got error `RuntimeError: Tensors must be CUDA and dense`

### Environment
`pytorch==1.7.1`
`pytorch-lightning==1.1.0`
`python==3.6.8`

### Additional context

The model successfully trains on 1 GPU without the DDP accelerator

**Comment by LithiumH** [comment]
Thanks GitHub bot

**Comment by LithiumH** [comment]
I just tested that changing line 84 of file `ddp_plugin.py` from
```
torch_backend = "nccl" if trainer.on_gpu else "gloo"
```
to 
```
torch_backend = 'gloo'
```
will solve this problem. However I'm unsure how best to implement this and other potential issues such as potential speed/multi-processing/GPU issues

**Comment by tchaton** [comment]
Hey @LithiumH ,

Great catch. We should expose a way to override backend for ddp.
Let me take this one next week.

Best,
T.C

**Comment by jwohlwend** [comment]
+1 on this. There are other issues with NCCL on A100 GPU's and pytorch 1.7. It runs fine with gloo, but NCCL hangs at initialization (could be nvlink related, unsure). Would be great to be able to override with gloo until this is officially resolved on the pytorch side.

**Comment by jwohlwend** [comment]
@tchaton Any updates on this?

**Comment by tchaton** [comment]
Hey @jwohlwend,

Made a PR to expose the torch distributed backend.

Best,
T.C

**Comment by jwohlwend** [comment]
Fantastic! Thank you
