### ISSUE TITLE
weights_save_path get overridden by modelcheckpoint but nothing indicate that.

### ISSUE THREAD

**Issue by kessido** [PyTorchLightning/pytorch-lightning#5361]
More like a "bug prone" feature IMHO.
Searching for "weights_save_path" in the source yield no other use except for modelcheckpoint, so I think that in case where the model checkpoint ignores the weights_save_path variable, it's better let the user know that he is incorrectly using the API rather then letting him explore why the model does not appear where it wished it to be (or why I'm getting "out of space" error even though the external device I'm saving to is empty Haha).

I don't mind PR-ing this, but let me know if this is acceptable by you.

**Comment by tchaton** [comment]
Hey @kessido,

I am not sure to fully understand your issue.
Would you mind providing an example with [bug_report_model](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py) 

Best,
T.C

**Comment by kessido** [comment]
```
 trainer = Trainer(
        weights_save_path='some/path/',
        checkpoint=[ModelCheckpoint('some/other/path'),]
    )
```

This just ignore the weights_save_path without saying anything to the user. He will only find out why iff he read the doc, or after first going through a "where is my weights??".

Instead imo I thing we should notify the user about missuse of API.
