### ISSUE TITLE
Adding run name to MLFlowLogger

### ISSUE THREAD

**Issue by sjdh** [PyTorchLightning/pytorch-lightning#5367]
## 🚀 Feature
Let MLFlowLogger accept a run name

```python
mlf_logger = MLFlowLogger(
    experiment_name="default",
    run_name="initial run",
)
```

### Motivation
Run names are useful to distinguish runs within an experiment:

![mlflow lightning log](https://user-images.githubusercontent.com/3899251/103701178-d82da400-4fa5-11eb-8b8a-9841e8c2ea1d.png)

MLFlowLogger has no run_name argument, making it harder to distinguish runs within an experiment:
![mlflow log lightning](https://user-images.githubusercontent.com/3899251/103703521-f6949f00-4fa7-11eb-9ab0-65ad9e3b5304.png)

The proposed form is consistent with the mlflow fluent tracking api:
```python
mlflow.start_run(run_name="parameter sweep 1")
```

### Pitch
Add a optional keyword argument to MLFlowLogger to increase clarity of logging. 

### Alternatives
Work with tags instead of run_name arguments; MLFlowLogger accepts tags.

**Comment by C-nit** [comment]
I was wondering why the mlflow self populated tags (user, source, version, ...) are not logged.  
`mlflow.start_run` adds some tags, including `run_name` before creating the run: https://github.com/mlflow/mlflow/blob/436f7e53cbbcc6152cd873f1924d17e8e9be5022/mlflow/tracking/fluent.py#L237
However the pytorch lightning logger is calling `self._mlflow_client.create_run(experiment_id=self._experiment_id, tags=self.tags)` directly, passing the tags on as given. Meaning we can add the tags ourselves.

The run name specifically you can set via the MLFLOW_RUN_NAME key.
Including the other tags:
```
from mlflow.tracking.context import registry as context_registry
from mlflow.utils.mlflow_tags import MLFLOW_RUN_NAME

user_specified_tags = {}  # your own tags here
user_specified_tags[MLFLOW_RUN_NAME] = run_name
tags = context_registry.resolve_tags(user_specified_tags)

mlflow_logger = MLFlowLogger(tags=tags)
```

**Comment by sjdh** [comment]
Yes, that works. 

I believe it is good practice to specify run names whenever logs are going to be shared with others or saved for longer time.  

To encourage this practice, it would help if mlflow.start_run supports an optional run_name keyword argument. 

I'd be happy to create a PR. How should I proceed? Can I just submit a PR? Or should the issue first have a certain status before a PR can be considered?

**Comment by kaushikb11** [comment]
@sjdh This makes sense! You could start with a PR. We will be happy to help
