### ISSUE TITLE
Refactor: hpc_load and entangled logics in CheckpointConnector

### ISSUE THREAD

**Issue by tarepan** [PyTorchLightning/pytorch-lightning#5370]
## 🚀 Feature
Refactor [`CheckpointConnector`][CheckpointConnector] by reducing duplicated parts and separating different functionality.  

[CheckpointConnector]:https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/connectors/checkpoint_connector.py

### Motivation
CheckpointConnector can be refactored.  

#### hpc_load
Almost all [`hpc_load`](https://github.com/PyTorchLightning/pytorch-lightning/blob/4d9db866a11f3b4b9b923bca811911ac79dad914/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L323) code is duplicated with `restore` (normal restore).  

#### Entangled logics
top-level method [`restore_weights`](https://github.com/PyTorchLightning/pytorch-lightning/blob/4d9db866a11f3b4b9b923bca811911ac79dad914/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L47) have several functionality/responsibility.  

- prevent OOM (CUDA cache clear)
- apply checkpoint to state
- control parallel environment (barrier)

Different responsibility should be in different function.  

### Pitch

- `hpc_load`: delete by using `restore`
-  `restore_weights`
    - the name do not reflect responsibility -> change to `attempt_to_restore`
    - multiple responsibility -> separate "applying checkpoint" parts as `attempt_to_apply_checkpoint`

**Comment by carmocca** [comment]
This is already done. Thanks!
