### ISSUE TITLE
pre-commit isort hook failure.

### ISSUE THREAD

**Issue by arnaudgelas** [PyTorchLightning/pytorch-lightning#5395]
When running `pre-commit run isort --all-files`, I get the following:

> isort....................................................................Failed
> - files were modified by this hook
> 
> Fixing /home/arnaud/dev/pytorch-lightning/tests/base/models.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/callbacks/model_checkpoint.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/utilities/test_all_gather_grad.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/loggers/test_tensorboard.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/loggers/test_wandb.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/classification/test_precision_recall.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/data_flow/test_eval_loop_flow_1_0.py
> Fixing /home/arnaud/dev/pytorch-lightning/pl_examples/basic_examples/simple_image_classifier.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/plugins/test_sharded_plugin.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/checkpointing/test_checkpoint_callback_frequency.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/base/model_train_dataloaders.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/profiler/__init__.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/regression/mean_squared_error.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/plugins/precision_plugin.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/plugins/test_rpc_plugin.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/functional/precision_recall_curve.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/functional/test_reduction.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/trainer/training_loop.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/utils.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/callbacks/test_early_stopping.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/tuner/lr_finder.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/test_dataloaders.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/utilities/argparse_utils.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/callbacks/test_callback_hook_outputs.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/trainer/connectors/checkpoint_connector.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/backends/test_tpu_backend.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/loggers/__init__.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/utilities/device_parser.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/utilities/test_apply_func.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/test_metric.py
> Fixing /home/arnaud/dev/pytorch-lightning/setup.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/base/model_utilities.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/test_config_validator.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/accelerators/cpu_accelerator.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/regression/test_ssim.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/core/optimizer.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/test_trainer_tricks.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/loggers/test_neptune.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/functional/ssim.py
> Fixing /home/arnaud/dev/pytorch-lightning/pl_examples/domain_templates/semantic_segmentation.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/loggers/test_csv.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/logging/test_logger_connector.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/classification/confusion_matrix.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/loggers/test_base.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/classification/roc.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/base/__init__.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/dynamic_args/test_multiple_eval_dataloaders.py
> Fixing /home/arnaud/dev/pytorch-lightning/pl_examples/basic_examples/autoencoder.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/__init__.py
> Fixing /home/arnaud/dev/pytorch-lightning/pl_examples/basic_examples/mnist_datamodule.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/profiler/profilers.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/regression/test_mean_error.py
> Fixing /home/arnaud/dev/pytorch-lightning/benchmarks/test_basic_parity.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/regression/mean_absolute_error.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/optimization/test_multiple_optimizers.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/trainer/connectors/training_trick_connector.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/cluster_environments/slurm_environment.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/utilities/test_apply_func_torchtext.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/utilities/model_utils.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/classification/precision_recall.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/base/simple_model.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/regression/explained_variance.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/test_metric_lightning.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/backends/test_dp.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/trainer/connectors/env_vars_connector.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/base/model_template.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/trainer/data_loading.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/tuner/batch_size_scaling.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/properties/log_dir.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/plugins/ddp_plugin.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/logging_tests/test_eval_loop_logging_1_0.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/deprecated_api/test_remove_1-3.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/trainer/optimizers.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/overrides/data_parallel.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/deprecated_api/test_remove_1-2.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/accelerators/ddp_spawn_accelerator.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/loggers/test_comet.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/regression/__init__.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/callbacks/test_lr_monitor.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/functional/test_nlp.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/test_trainer_cli.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/functional/confusion_matrix.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/core/test_memory.py
> Fixing /home/arnaud/dev/pytorch-lightning/pl_examples/test_examples.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/functional/__init__.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/classification/accuracy.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/base/model_test_dataloaders.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/utilities/upgrade_checkpoint.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/functional/mean_squared_error.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/models/test_horovod.py
> Fixing /home/arnaud/dev/pytorch-lightning/pl_examples/domain_templates/computer_vision_fine_tuning.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/trainer/trainer.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/classification/test_precision_recall_curve.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/classification/test_accuracy.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/models/test_tpu.py
> Fixing /home/arnaud/dev/pytorch-lightning/benchmarks/generate_comparison.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/test_states.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/accelerators/ddp_cpu_spawn_accelerator.py
> Fixing /home/arnaud/dev/pytorch-lightning/pl_examples/basic_examples/dali_image_classifier.py
> Fixing /home/arnaud/dev/pytorch-lightning/pl_examples/domain_templates/generative_adversarial_net.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/plugins/ddp_sequential_plugin.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/trainer/training_tricks.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/callbacks/test_progress_bar.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/model_hooks/test_model_hooks.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/core/step_result.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/callbacks/progress.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/checkpointing/test_trainer_checkpoint.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/callbacks/early_stopping.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/base/model_valid_steps.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/classification/test_inputs.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/models/test_torchscript.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/utilities/__init__.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/core/lightning.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/accelerators/accelerator_connector.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/loggers/neptune.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/functional/classification.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/trainer/connectors/data_connector.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/classification/average_precision.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/flags/test_fast_dev_run.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/functional/average_precision.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/backends/ddp_model.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/base/model_test_steps.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/functional/explained_variance.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/dynamic_args/test_multiple_optimizers.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/utilities/test_xla_device_utils.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/base/datasets.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/functional/mean_squared_log_error.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/models/test_restore.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/core/test_lightning_module.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/models/test_cpu.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/logging_tests/test_train_loop_logging_1_0.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/loggers/base.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/classification/helpers.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/functional/test_classification.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/plugins/rpc_plugin.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/core/test_lightning_optimizer.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/callbacks/test_callbacks.py
> Fixing /home/arnaud/dev/pytorch-lightning/benchmarks/test_sharded_parity.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/utilities/parsing.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/base/develop_utils.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/trainer/logging.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/__init__.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/models/test_gpu.py
> Fixing /home/arnaud/dev/pytorch-lightning/docs/source/conf.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/flags/test_val_check_interval.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/trainer/deprecated_api.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/base/deterministic_model.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/callbacks/test_gpu_stats_monitor.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/accelerators/__init__.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/core/test_decorators.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/models/test_sync_batchnorm.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/trainer/connectors/precision_connector.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/utilities/test_dtype_device_mixin.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/plugins/test_amp_plugin.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/test_optimizers.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/tuner/auto_gpu_select.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/models/test_amp.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/functional/reduction.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/classification/test_confusion_matrix.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/models/test_hooks.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/loggers/test_all.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/utilities/debugging.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/classification/f_beta.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/trainer/evaluation_loop.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/utilities/test_upgrade_checkpoint.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/metric.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/test_trainer.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/conftest.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/checkpointing/test_model_checkpoint.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/test_ddp.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/accelerators/ddp2_accelerator.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/trainer/connectors/profiler_connector.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/utils.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/base/develop_pipelines.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/core/saving.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/properties/test_get_model.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/loggers/test_mlflow.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/distributed/dist.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/accelerators/tpu_accelerator.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/optimization/test_parity_manual_optimization.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/classification/__init__.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/core/test_results.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/loggers/comet.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/loggers/csv_logs.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/callbacks/__init__.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/core/test_metric_result_integration.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/regression/test_psnr.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/functional/mean_absolute_error.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/cluster_environments/torchelastic_environment.py
> Fixing /home/arnaud/dev/pytorch-lightning/pl_examples/basic_examples/conv_sequential_example.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/classification/inputs.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/trainer/connectors/logger_connector/epoch_result_store.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/checkpointing/test_torch_saving.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/optimization/test_manual_optimization.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/loggers/mlflow.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/data_flow/test_train_loop_flow_dict_1_0.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/loggers/wandb.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/functional/test_self_supervised.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/functional/psnr.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/plugins/sharded_native_amp_plugin.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/models/data/horovod/train_default_model.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/utilities/data.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/test_supporters.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/accelerators/gpu_accelerator.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/core/memory.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/test_lr_finder.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/tuner/test_auto_gpu_select.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/core/test_datamodules.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/classification/precision_recall_curve.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/legacy_deprecate_flow_log_tests/test_trainer_steps_scalar_return.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/plugins/native_amp.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/functional/roc.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/legacy_deprecate_flow_log_tests/test_eval_loop_dict_return.py
> Fixing /home/arnaud/dev/pytorch-lightning/pl_examples/domain_templates/imagenet.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/base/model_valid_dataloaders.py
> Fixing /home/arnaud/dev/pytorch-lightning/pl_examples/bug_report_model.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/flags/test_overfit_batches.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/data_flow/test_train_loop_flow_scalar_1_0.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/models/test_hparams.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/plugins/test_apex_plugin.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/accelerators/ddp_hpc_accelerator.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/backends/test_ddp_spawn.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/accelerators/horovod_accelerator.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/functional/f_beta.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/classification/test_roc.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/regression/mean_squared_log_error.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/regression/test_explained_variance.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/plugins/apex.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/accelerators/ddp_accelerator.py
> Fixing /home/arnaud/dev/pytorch-lightning/pl_examples/basic_examples/backbone_image_classifier.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/plugins/test_ddp_sequential_plugin.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/trainer/connectors/slurm_connector.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/accelerators/accelerator.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/backends/test_accelerator_connector.py
> Fixing /home/arnaud/dev/pytorch-lightning/pl_examples/domain_templates/reinforce_learn_Qnet.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/backends/test_ddp.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/classification/test_f_beta.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/base/model_train_steps.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/utilities/device_dtype_mixin.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/warnings_tests/test_flow_warnings.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/base/boring_model.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/accelerators/dp_accelerator.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/utilities/seed.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/regression/psnr.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/collect_env_details.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/base/test_datasets.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/optimization/test_parity_automatic_optimization.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/loggers/tensorboard.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/models/test_onnx.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/plugins/sharded_plugin.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/metrics/classification/test_average_precision.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/test_trainer_test_loop.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/utilities/distributed.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/tuner/tuning.py
> Fixing /home/arnaud/dev/pytorch-lightning/pytorch_lightning/metrics/regression/ssim.py
> Fixing /home/arnaud/dev/pytorch-lightning/tests/trainer/logging_tests/test_distributed_logging.py

**Comment by Borda** [comment]
@arnaudgelas thx for reporting, you are welcome to send some smaller PRs according to #4805
