### ISSUE TITLE
TypeError caused due to arguments not found at the end of TPU training

### ISSUE THREAD

**Issue by Vijayabhaskar96** [PyTorchLightning/pytorch-lightning#5401]
## 🐛 Bug

When using TPU for training if you pass arguments when initializing the model, the training runs fine and completes all the epochs but at the end lightning for some reason tries to load the checkpoint back, here when loading the arguments are not found for some reason causing the error.

## Please reproduce using the BoringModel
Reproduced in the BoringModel, with `lr` passed during model initialization.

https://colab.research.google.com/drive/1CJ1WFQBvfe0-1oFV6BYl-8cAmvzjQQl_?usp=sharing

### To Reproduce

Just change the runtime to TPU and run the notebook.

### Expected behavior
Load the arguments passed before properly.

### Environment

Tested on both Colab and Kaggle.

**Comment by SeanNaren** [comment]
In:

```python
class BoringModel(LightningModule):

    def __init__(self,lr):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)
        self.lr = lr
```

Could you add `save_hyperparameters()`? This will cache your parameters for saving/loading the checkpoints:

```python
class BoringModel(LightningModule):

    def __init__(self,lr):
        super().__init__()
        self.save_hyperparameters()
        self.layer = torch.nn.Linear(32, 2)
        self.lr = lr
```

**Comment by Vijayabhaskar96** [comment]
It worked!
