### ISSUE TITLE
Restore training states without create new version in lightning_logs?

### ISSUE THREAD

**Issue by vietnamican** [PyTorchLightning/pytorch-lightning#5403]
I want to restore my training state, I read the docs and successful. But it create a new version in ```lightning_logs/``` directory and when I use Tensorboard, they're like 2 separated processes rather than one is followed by the other.
How can I continue training without create a new version in logs?

**Comment by tchaton** [comment]
Hey @vietnamican,

```
When you restore the Trainer, are you using Trainer(resume_from_checkpoint=...)
```

Would you mind trying this ?

```
Trainer(resume_from_checkpoint=..., callbacks=[ModelCheckpoint(dirpath=previous_path)]
```

Best,
T.C

**Comment by tchaton** [comment]
@rohitgr7 Any idea ?

**Comment by tchaton** [comment]
@rohitgr7 And do you think saving / restoring `self.dirpath` in the checkpoint could solve this use-case

**Comment by vietnamican** [comment]
@tchaton I try you suggestion and I checkpoints are restored the same directory every epoch. But I want to mention logs: PL is keeping create new version inside ```lightning_logs/``` and when draw in Tensorboard, two versions are different colors, which makes me feel like they are two separate training processes rather than continuous one. 
Copying the Tensorboard ```events.*``` files and put them under the same directory is simply way to solve this problem, sometimes it can be hard to handle though. If Trainer has a flag allow us to continue writing Tensorboard ```events.*``` files into the directory where the previous is, I think it sounds cool, right?

**Comment by rohitgr7** [comment]
@tchaton yes, saving/restoring `dirpath` will solve the issue. We need to have some conditions here. If a new `dirpath` is given in `ModelCheckpoint` while resuming, it shouldn't be restored. And not just `dirpath`, more things need to be saved and restored here. Discussion: https://github.com/PyTorchLightning/pytorch-lightning/issues/4911

**Comment by tchaton** [comment]
Hey @vietnamican,

Would you be interested to contribute a fix ?

Best,
T.C

**Comment by vietnamican** [comment]
@tchaton I'm happy to contribute! I'll create a PR when I added this feature.

**Comment by vietnamican** [comment]
I found TensorboardLogger solves the problem.
Here the notebook example: https://colab.research.google.com/drive/1yKJpWQ2q2idsXbSd9rTkWNeiV0JpVzP9?usp=sharing

**Comment by edenlightning** [comment]
Thanks!!

**Comment by mfoglio** [comment]
I also noticed that the code in the notebook what modified and now it contains a syntax error:
```
from pytorch_lightning.loggers import TensorBoardLogger
logger = TensorBoardLogger('lightning_logs', name=''=0)
```
