### ISSUE TITLE
allow val_check_interval to be larger than training dataset size 

### ISSUE THREAD

**Issue by cccntu** [PyTorchLightning/pytorch-lightning#5413]
## 🚀 Feature

allow `val_check_interval ` to be larger than the number of the training batches in one epoch

### Motivation

I am using a small datasets, so instead of specifying `max_epochs` in Trainer, I want to use `max_steps` and evaluate every `val_check_interval `, but when `val_check_interval` is larger than number of batches in training set, there is an error, like this:
```
`val_check_interval` (100) must be less than or equal to the number of the training batches (24). If you want to disable validation set `limit_val_batches` to 0.0 instead.
```

### Pitch

`val_check_interval ` should't be limited by the number of the training batches in one epoch, it should be a warning, not an error

### Alternatives

I am currently using a wrapper to make it an iterable dataset, so it allows me to do that

**Comment by rohitgr7** [comment]
https://github.com/PyTorchLightning/pytorch-lightning/issues/4409 similar

**Comment by gan3sh500** [comment]
@rohitgr7 @tchaton Could I work on this?

**Comment by rohitgr7** [comment]
@gan3sh500 yeah go ahead.

**Comment by gan3sh500** [comment]
@cccntu Did you try `check_val_every_n_epoch` for this purpose. 

@rohitgr7 This issue can be fixed by removing exceptions to warning and checking `trainer.total_batch_idx` when `val_check_batch` greater than `trainer.num_training_batches`.  Shall I open a PR? 

It seems a bit redundant with `check_val_every_n_epoch`. Or shall we add float support for `check_val_every_n_epoch`?

**Comment by rohitgr7** [comment]
yeah I guess just deprecate `check_val_every_n_epoch` and let `val_check_interval` handle it using float values (1.0, 2.0, 3.0...).

**Comment by gan3sh500** [comment]
@rohitgr7 Sounds good. It'll be a bit cleaner this way. I'll make the changes for this and PR.

**Comment by edenlightning** [comment]
@gan3sh500 any update on this?

**Comment by turian** [comment]
Related to this discussion: https://github.com/PyTorchLightning/pytorch-lightning/discussions/6253

**Comment by cccntu** [comment]
> @cccntu Did you try `check_val_every_n_epoch` for this purpose.
> It seems a bit redundant with `check_val_every_n_epoch`. Or shall we add float support for `check_val_every_n_epoch`?

Sorry for the late reply. I use `val_check_interval=n` to evaluate every `n` steps, using `check_val_every_n_epoch=n` would be evaluating every `n` epochs. 

Using together with `max_steps=m`, I can make sure the number of training steps don't change if the dataset size changes.

**Comment by kaushikb11** [comment]
Not exactly Priority P0. Moving it to P1

**Comment by Rizhiy** [comment]
Any updates on this?

**Comment by edenlightning** [comment]
@kaushikb11 what is left TODO here?

**Comment by shivammehta007** [comment]
Is this change merged? if yes then in which version? It is really useful, I am not sure why it is marked P2.
