### ISSUE TITLE
WANDB logger not logging per step, only per epoch

### ISSUE THREAD

**Issue by AmitMY** [PyTorchLightning/pytorch-lightning#5439]
#### What is your question?

When using WANDB logger, I don't see logs after every step, only after every epoch.

I have a toy dataset of 9 examples, and if I train for 5 epochs with batch size 1, I expect seeing 5*9=45 log entries for `training_loss`. However, I only see 5, on steps 8, 17, 26, etc...

Additionally, I see a warning:
> UserWarning: Trying to log at a previous step. Use `commit=False` when logging metrics manually.

And in validation I see:
> wandb: WARNING Step must only increase in log calls.  Step 0 < 8; dropping

As if I set the `step` manually (which I don't), or wandb doesn't manage to get the current step.

#### Code
```python
def trainingstep(self, batch, batch_idx):
    x, y = batch
    y_hat = self(x)
    return { "loss": F.cross_entropy(y_hat, y) }

def training_step_end(self, outputs):
    self.log('training_loss', outputs["loss"])
```

#### What I tried
I tried adding `on_step=True`, without success.

#### What's your environment?

 - OS: [e.g. iOS, Linux, Win] Linux
 - Packaging [e.g. pip, conda] pip
 - Version [e.g. 0.5.2.1] `1.1.3`

**Comment by rohitgr7** [comment]
you need to set `Trainer(log_every_n_steps=1, ...)` to see it at every step.
https://pytorch-lightning.readthedocs.io/en/latest/trainer.html#log-every-n-steps

**Comment by AmitMY** [comment]
Cool, thanks!
However, setting the trainer like that, I still only see a log every epoch. I will likely keep it on the default, 50, but for now I just want to see it working per step.

**Comment by tchaton** [comment]
Hey @AmitMY,

Would you mind trying out master ?

Best,
T.C

**Comment by edenlightning** [comment]
Feel free to reopen if issue persists!
