### ISSUE TITLE
`on_test_end` is not called in test

### ISSUE THREAD

**Issue by kengz** [PyTorchLightning/pytorch-lightning#5442]
## 🐛 Bug

I'm running a model with `fit` and `test` called. However I noticed that `on_test_end` is not called at the end of `test`.

## Please reproduce using the BoringModel

https://colab.research.google.com/drive/1j5J8TXAIqoFCqc-3WnAPMox8amNsRDjE?usp=sharing

### To Reproduce

Use following [**BoringModel**](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing) and post here

See the code addition at the bottom of [this cell](https://colab.research.google.com/drive/1j5J8TXAIqoFCqc-3WnAPMox8amNsRDjE?usp=sharing#scrollTo=V7ELesz1kVQo), which prints when the method is hit.

Then check the [output here](https://colab.research.google.com/drive/1j5J8TXAIqoFCqc-3WnAPMox8amNsRDjE?usp=sharing#scrollTo=AAtq1hwSmjKe). Notice how `##### hit on_test_end #####` is missing, whereas `##### hit on_train_end #####` is present and just fine.

### Expected behavior

When running the `trainer.test` step, `on_test_end` should be called at the end of test.

### Environment

See the shared Colab notebook. Below are pasted form the notebook:

```
* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.19.4
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0+cu101
	- pytorch-lightning: 1.1.3
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020
```

**Comment by rohitgr7** [comment]
can you update the notebook permissions?

**Comment by kengz** [comment]
done

**Comment by rohitgr7** [comment]
I just released there is no on_validation_end/on_test_end hook in LightningModule. It's only present in callbacks.

**Comment by kengz** [comment]
What does that mean? How can we get it called at the end of test?

**Comment by rohitgr7** [comment]
is there any reason to not include `on_validation_end` and `on_test_end` hooks in `LightningModule`? cc @PyTorchLightning/core-contributors

**Comment by Borda** [comment]
I do not think there is a reason, just missed it...

**Comment by awaelchli** [comment]
We should also consider a test for a full hooks life-cycle as done with the callbacks:
https://github.com/PyTorchLightning/pytorch-lightning/blob/87482935a3d03cab3ffff336c88e0ae977a2beee/tests/callbacks/test_callbacks.py#L22

**Comment by rohitgr7** [comment]
it's there @awaelchli https://github.com/PyTorchLightning/pytorch-lightning/blob/master/tests/models/test_hooks.py
just need to be updated the way it's done in callbacks.

**Comment by rohitgr7** [comment]
fixed in https://github.com/PyTorchLightning/pytorch-lightning/pull/5467
