### ISSUE TITLE
How to gather results during inference in ddp

### ISSUE THREAD

**Issue by tomdzh** [PyTorchLightning/pytorch-lightning#5472]
## ❓ Questions and Help
Hi, I am using multiple gpus and ddp mode for model inference. I am wondering how to gather the results from all distributed processes and save them into one file in the test_epoch_end. My code looks like this:

#### Code
```python
class PLModel(pl.LightningModule):
    def on_test_epoch_start(self):
        self.text_predictions = []
    
    def test_step(self, batch, batch_idx):
         pred_ids = model(batch)
         pred_texts = ids_to_texts(pred_ids) # some function that converts predicted ids to texts
         self.text_predictions.extend(pred_texts)

    def test_epoch_end(self, outputs):
        # here I want to know how to gather the text_predictions from all processes

        # after gathering
        df_text_predictions = pandas.DataFrame{'predictions': self.text_predictions}
        df_text_predictions.to_csv('predictions.csv', index=False)
```
#### What have you tried?
I am able to save the results into separate files in each distributed process. But I have to do post-processing to put all the files together. I want to know how to gather the results automatically so that I don't need to run another script for post-processing.

**Comment by tomdzh** [comment]
Accidentally submitted two same issues. Closed the other one....

**Comment by tchaton** [comment]
Hey @tomdzh,

Would you mind trying out the PR #5468 ?

Best,
T.C

**Comment by Arij-Aladel** [comment]
I have the same problem during validation step using 2 gpus I nedd to do some calculations on validation end I get have of results

**Comment by tomdzh** [comment]
I found a solution in this [PR](https://github.com/PyTorchLightning/pytorch-lightning/issues/2424), using the detectron2.utils.comm.all_gather
