### ISSUE TITLE
Add plugin trainer flag- Trainer(plugin="ddp_sharded")

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#5484]
@edenlightning commented on [Wed Nov 18 2020](https://github.com/PyTorchLightning/internal-dev/issues/52)

As a user, I would like to set the plugin using a string flag.

Currently, you need to pass in the plugin explicitly. It would be nicer if we can make plugin the configurable, so that the user has to only pass a string to enable a plugin.

---

@edenlightning commented on [Thu Nov 19 2020](https://github.com/PyTorchLightning/internal-dev/issues/52#issuecomment-730528206)

Trainer(plugin='sharded')

**Comment by SeanNaren** [comment]
This is done already! You can do `plugins=ddp_sharded` unless I'm missing something.
