### ISSUE TITLE
 Improve legacy checkpoint testing

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#5491]
## 🚀 Feature

Improve legacy checkpoint testing

### Motivation

Currently, we only test whether a legacy checkpoint can be loaded and run, but no internal state is checked.

### Pitch

Check the epoch number is correct, if the state is the expected, if we achieve a particular loss after 1 step...

We already have similar tests, we just have to do them for legacy checkpoints. see

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/tests/models/test_restore.py

### Additional context

https://github.com/PyTorchLightning/pytorch-lightning/blob/1f6236accce78303249c55de656b71501e607d1a/tests/checkpointing/test_legacy_checkpoints.py#L49-L72

cc: @Borda

**Comment by Borda** [comment]
@carmocca can you point me out to the test we could mirror here?
also in such case, we would probably need to use realistic dataset not random... :rabbit:

**Comment by carmocca** [comment]
I don't have something specific, we could use one in `tests/models/test_restore.py` as a template.

IMO the test for legacy testing should have a few common use cases like

- saving hparams
- logging something
- checkpointing
- early-stopping
- resuming from checkpoint

to try to cover as much as we can

But I don't think it should use MNIST, we can use random data and not test the loss

**Comment by Borda** [comment]
> IMO the test for legacy testing should have a few common use cases like

yes, your selection seems reasonable, we just need to keep in mind to use items that have been here since the "beginning" or at least we set the testing starts from...

> But I don't think it should use MNIST, we can use random data and not test the loss

but for random data it may not converge and so early stop or checkpoint wont be valid...

**Comment by carmocca** [comment]
> yes, your selection seems reasonable, we just need to keep in mind to use items that have been here since the "beginning" or at least we set the testing starts from...

Yes, I believe my list are all included since the beginning. We could also have different tests per versions

> but for random data it may not converge and so early stop or checkpoint wont be valid...

We can log a fake value to early stop

**Comment by Borda** [comment]
see follow-up work suggestions in https://github.com/PyTorchLightning/pytorch-lightning/pull/8535#discussion_r678947328
