### ISSUE TITLE
LightningModule docs is wrong when defining "Training with DataParallel"

### ISSUE THREAD

**Issue by Android121381** [PyTorchLightning/pytorch-lightning#5497]
The docs says when training with DataParallel the training_step_end function should be like this:
```
def training_step_end(self, batch_parts):
    gpu_0_prediction = batch_parts[0]['pred']
    gpu_1_prediction = batch_parts[1]['pred']
    # do something with both outputs
    return (batch_parts[0]['loss'] + batch_parts[1]['loss']) / 2
```
but acually, when i try it for myself, it should be like this:
```
def training_step_end(self, batch_parts):
    gpu_0_prediction = batch_parts['pred'][0]
    gpu_1_prediction = batch_parts['pred'][1]
    # do something with both outputs
    return (batch_parts['loss'][0] + batch_parts['loss'][1]) / 2
```
yes, the order of the axes are opposite.

**Comment by Borda** [comment]
@Android121381 mind send a PR with correction? :]

**Comment by Android121381** [comment]
> @Android121381 mind send a PR with correction? :]

Sure, whem I'm implementing examples, It says that the training_step_end should like this
```
**def training_step(self, batch, batch_idx):
    x, y = batch
    y_hat = self.model(x)
    loss = F.cross_entropy(y_hat, y)
    return {'loss': loss}

def training_step_end(self, batch_parts):
    # do something with both outputs
    return (batch_parts[0]['loss'] + batch_parts[1]['loss']) / 2
```
traing_step function returns the loss, then training_step_end function process it. But when i try it for myself, it gives me this error:
`KeyError: 0`
so i print the key of the input(batch_parts) of the training_step_end function, it says the key is
`dict_keys(['loss'])`
therefore, i change my code as below:
```
**def training_step(self, batch, batch_idx):
    x, y = batch
    y_hat = self.model(x)
    loss = F.cross_entropy(y_hat, y)
    return {'loss': loss}

def training_step_end(self, batch_parts):
    # do something with both outputs
    return (batch_parts['loss'][0] + batch_parts['loss'][1]) / 2
```
the validation_step_end function have the same problem.
