### ISSUE TITLE
Support saving checkpoint at the first epoch when setting a checkpoint save_interval

### ISSUE THREAD

**Issue by aiyolo** [PyTorchLightning/pytorch-lightning#5498]
## 🚀 Feature

saving checkpoint at the first epoch when setting a checkpoint save interval

### Motivation
The current implementation will skip to save the model checkpoint of the first epoch, this is a bad behavior, because we are not sure whether the checkpoint_callback works okay until the first checkpoint is saved.

**Comment by Borda** [comment]
hi, so would you suggest having checkpointing as part of `fast_dev_run`?

**Comment by rohitgr7** [comment]
I believe the request here is to allow checkpointing at `epoch=0` irrespective of the value of `period`. Nothing to do with `fast_dev_run`.
https://github.com/PyTorchLightning/pytorch-lightning/blob/83b1ff421dbc1a1c07786e322489086b055ffb01/pytorch_lightning/callbacks/model_checkpoint.py#L231

**Comment by aiyolo** [comment]
yes, this is exactly what I want to say. I believe most of people have the habit of checkpointing at the first epoch when they want to save their model at a interval.😊
