### ISSUE TITLE
FR: New Metric: Average Precision for Object Detection (e.g. Faster- or Mask-RCNN)

### ISSUE THREAD

**Issue by maxfrei750** [PyTorchLightning/pytorch-lightning#5501]
## 🚀 Feature
In object detection, the Average Precision Metric is very common. It would be nice to have it included in PyTorchLightning.

### Motivation

Object Detection is a major field of artificial intelligence, yet there exist no metrics for it in PyTorchLightning.

### Pitch
I just implemented the Average Precision Metric for Object Detection in one of my PytorchLightningProjects. If there is an interest to include it, I would be glad to contribute my code and prepare a PR.

### Alternatives
Somebody else implements it.

### Additional context
https://cocodataset.org/#detection-eval
https://jonathan-hui.medium.com/map-mean-average-precision-for-object-detection-45c121a31173

**Comment by SkafteNicki** [comment]
@maxfrei750 is this PR #4564 implementing the metric you are proposing or is it a different one?

**Comment by maxfrei750** [comment]
Shoot! My Googling skills failed me. :facepalm: Yeah, that's exactly the one. Thanks for pointing me in the right direction.
