### ISSUE TITLE
Trainer property `log_dir` cannot be accessed before model is bound to trainer

### ISSUE THREAD

**Issue by nathanpainchaud** [PyTorchLightning/pytorch-lightning#5524]
## 🐛 Bug
Tentatives to access a `Trainer` instance's `log_dir` property prior to calling `fit` results in an error:
```shell script
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
Accessing `log_dir` only works after calling `fit` (or from within the training loop itself, once the setup required by `fit` has been executed).

### To Reproduce
See bug reproduced with the `BoringModel` [here](https://colab.research.google.com/drive/1anCdwAV-PltCX1DrQc1TtLv_rfc6g9Qk?usp=sharing).

### Expected behavior
The Trainer's `log_dir` property should be accessible as soon as the Trainer is instantiated.

If this isn't possible because of some implementation detail, the documentation should at least be updated to clearly state this limitation.

**Comment by SkafteNicki** [comment]
It happens if the `ModelCheckpoint` dirpath have not been specified (which is the default behavior), because then it cannot be split in this part of the code:
https://github.com/PyTorchLightning/pytorch-lightning/blob/f2e99d617f05ec65fded81ccc6d0d59807c47573/pytorch_lightning/trainer/properties.py#L66-L68
A simple change to the condition should be sufficient:
``` python
if self.checkpoint_callback is not None and self.checkpoint_callback.dirpath is not None
```

**Comment by nathanpainchaud** [comment]
@SkafteNicki Thanks for the suggestion! I saw that was the problem, but I was hesitant whether such a simple fix would really be enough :sweat_smile: It at least solves the crash, but it doesn't really solve the real problem which is to access the trainer's expected logging directory _before_ binding the model.

I tried to apply your fix, but then `log_dir` just returns `None`, since it takes the following path, where the `self.logger` is then just a `DummyLogger` and thus `self.logger.save_dir` is None.
https://github.com/PyTorchLightning/pytorch-lightning/blob/f2e99d617f05ec65fded81ccc6d0d59807c47573/pytorch_lightning/trainer/properties.py#L69-L73

Why hasn't the correct logger already been created at this point? In my case I don't provide a logger but I do set the `default_root_dir`, and I would expect that Lightning would already have created the default `TensorBoardLogger` with an appropriate path.

**Comment by rohitgr7** [comment]
if logger is None, shouldn't `trainer.log_dir` be None too?

**Comment by nathanpainchaud** [comment]
@rohitgr7 In this case `logger` is **not** `None`. I think not specifying a logger shouldn't be assumed as not wanting a logger or to possibly log results, since Lightning defaults to providing a `TensorboardLogger`. I would understand if you set `logger` to `False` in the `Trainer`'s init, since then you explicitly specify you don't want a logger. But I think there is a difference between no custom logger and no logger at all.

**Comment by rohitgr7** [comment]
I meant if the user explicitly set `logger=False` in that case should it be `default_root_dir` or `None`? Also, I see some bugs already there, not 100% sure.

**Comment by nathanpainchaud** [comment]
I agree with you, that defaulting to `default_root_dir` would be best, even when `logger=False`. My reply was more to the point that the behavior I'm experiencing really doesn't make sense with my setup, and could only be argued as sensible with a different logger setup.

I'd be happy to help with sorting out this issue, but what the presence of the `DummyLogger` tells me it that this issue might have repercussions at large in how Lightning initializes the trainer, model and loggers under the hood, so I feel a bit out of my depth to tackle this issue by myself.

**Comment by rohitgr7** [comment]
will check :)

**Comment by rohitgr7** [comment]
@nathanpainchaud mind check if https://github.com/PyTorchLightning/pytorch-lightning/pull/5537 solves your issue?

**Comment by nathanpainchaud** [comment]
@rohitgr7 Well, it solves the crash like SkafteNicki's suggestion, but otherwise it has the same problem where the only logger the trainer sees is the `DummyLogger` that has `None` for a `save_dir`. So, in the end, I still get `None` when calling `trainer.log_dir`.

**Comment by rohitgr7** [comment]
well `DummyLogger` doesn't actually do anything. Any reason why are you using it?

**Comment by SkafteNicki** [comment]
I don't understand why you end up with a `DummyLogger`? `logger=True` give a tensorboard logger, `logger=False` give no logger.

**Comment by nathanpainchaud** [comment]
I'm not using it, I set `logger=True` when initializing the trainer. I assumed it's a placeholder created internally by Lightning until the default `TensorboardLogger` is created and substituted?

**Comment by rohitgr7** [comment]
are you using fast_dev_run?

**Comment by nathanpainchaud** [comment]
> are you using fast_dev_run?

Ahhh! Yes.

**Comment by awaelchli** [comment]
with multi-gpu training, we replace the logger on rank > 0 with a dummy logger.

**Comment by rohitgr7** [comment]
well when using fast_dev_run.. logging is disabled and with logger=True, the logger will be initialized with `DummyLogger`(basically means no logging). with `fast_dev_run=0/False`, it will be initialized with `TensorBoardLogger`.

**Comment by nathanpainchaud** [comment]
I can confirm that it's working when disabling `fast_dev_run`.

However, do you have any tips to give on how to workaround this in `fast_dev_run`. I personally find it useful to be able to test my exact pipeline in `fast_dev_run` (logs included). If `fast_dev_run` requires me to patch/disable parts of pipeline, then it looses part of its usefulness.

**Comment by rohitgr7** [comment]
it's the design choice to disable logging & checkpointing with `fast_dev_run` since it's meant to check that everything is working fine including logging (without actually logging anything).

**Comment by awaelchli** [comment]
If you still wish to see all files be written to logger and checkpoint dirs, you can consider limit_train_batches=1 for the Trainer argument (to replace fast dev run).  
Regarding the log_dir property, I wasn't aware this exists but looking at the implementation it is rather confusing how it is defined.  I recommend not to use this property and directly access `self.logger.log_dir` or `self.logger.save_dir`.

**Comment by rohitgr7** [comment]
@awaelchli actually the checkpoint callback is not required since it uses logger to decide the dirpath if it's not set else it does nothing. Either way, it's not required at all. Created a PR (WIP) linked to the issue for a fix. Let's see how it goes.

**Comment by nathanpainchaud** [comment]
@awaelchli Thanks for your recommendation! I discovered the `limit_{train|val|test}_batches` yesterday. Setting all of them to 1, along with `max_epochs=1` seems to achieve the in-depth test of my whole pipeline I wanted, although with a slightly less convenient config. I can understand the design decision for `fast_dev_run`, although I don't think I would be the only user confused by the different logging behavior between `fast_dev_run` vs. "normal mode".

Anyways, thanks to @rohitgr7 for his rapid intervention, and to both of you for your help and feedback :)

**Comment by awaelchli** [comment]
@rohitgr7 nice PR, makes much more sense this way :) 
@nathanpainchaud  max_steps = 1 is another option :)
