### ISSUE TITLE
training_forward assumes input has .copy() method for single GPU

### ISSUE THREAD

**Issue by MikeScarp** [PyTorchLightning/pytorch-lightning#553]
### Common bugs:
1. Tensorboard not showing in Jupyter-notebook see [issue 79](https://github.com/williamFalcon/pytorch-lightning/issues/79).    
2. PyTorch 1.1.0 vs 1.2.0 support [see FAQ](https://github.com/williamFalcon/pytorch-lightning#faq)    

**Describe the bug**
After #532 , training with a DataLoader where batch does not have a .copy() method (such as tuple) will cause an exception. It doesn't seem to be the assumption that batch should always be a tensor, because we are passing it to transfer_batch_to_gpu, which does a lot of checking to handle different types differently.
Exception happens at https://github.com/williamFalcon/pytorch-lightning/blob/f2191b0cdf4305ae3a5ad2b1e404f99764a1a7c6/pytorch_lightning/trainer/train_loop_mixin.py#L293

**To Reproduce**
1. Install bleeding edge build
2. Train with an DataLoader where a batch is of type tuple with one GPU

**Expected behavior**
I would expect the copy to only happen when batch is of type tensor, or possibly apply the copy to elements inside the tuple if it is a tuple.

**Comment by williamFalcon** [comment]
@MikeScarp good catch, silly oversight on our part. Mind submitting a PR?

**Comment by giovannipcarvalho** [comment]
It might not be a tuple either. I'm experiencing the same with torchtext's Batch class. In my case, data is already on the GPU.

**Comment by awaelchli** [comment]
Looks to me like the problem described by @MikeScarp was solved. Master branch does not contain the copy anymore. 

What @giovannipcarvalho mentions is also discussed here: #1245
So this may be closed? @MikeScarp
