### ISSUE TITLE
Failing to load the GPU-trained model onto CPU-machine

### ISSUE THREAD

**Issue by ncuxomun** [PyTorchLightning/pytorch-lightning#5543]
#### What is your question?
Hi, I cannot load neither model nor checkpoint from GPU onto CPU machine.
I followed the docs but the problem still remains. How can I resolve this issue?
Please follow the code sections below and its corresponding error messages.

#### Code
m_ae_model = LitAE.load_from_checkpoint(r'Path\version_1\_load.ckpt', in_out_size, z_size)
**TypeError: 'tuple' object is not callable**
(in_out_size is a tuple, image dimensions for convolutional operations, whereas z_size is the latent variable dimension)
I also tried loading ".pt" model by placing it onto the CPU using map_location. 

#### Code
location = torch.device('cpu')
m_ae_model = torch.load("m_ae_model.pt", map_location=location)

AttributeError: 'Trainer' object has no attribute '_enable_pl_optimizer'

#### What have you tried?
Saving GPU-trained model onto CPU (by model.to('CPU')), loading checkpoints.
#### What's your environment?

 - OS: Win (both machines)
 - Packaging pip
 - Version 1.1.3

**Comment by awaelchli** [comment]
Hi, please share the signature of your constructor or if possible the full code so that we can see if it is expecting positional args or keywoard args. Also please share the full error message so we can see where it originates from.
If your code has changed since you saved the checkpoint, it can result in errors like this.

**Comment by ncuxomun** [comment]
Hi, thanks for getting back to me. Here is the code:

class LitAE(pl.LightningModule):
    def __init__(self, in_out_size, latent_dim, lr=2e-4):
        super().__init__()
        self.in_out_size = in_out_size
        self.latent_dim = latent_dim
        self.lr = lr

        # encoder
        self.encoder = Encoder(self.in_out_size, self.latent_dim)
        # decoder model
        self.decoder = Decoder(self.in_out_size, self.latent_dim)

        self.encoder.apply(self.weights_init)
        self.decoder.apply(self.weights_init)

    def forward(self, data_in):
        embedding = self.encoder(data_in)
        data_out = self.decoder(embedding)
        return data_out

    def training_step(self, batch, batch_idx):
        x, y = batch
        # z = self.encoder(y)
        # pred_y = self.decoder(z)
        pred_x = self(x)
        train_loss = F.smooth_l1_loss(pred_x, x)
        # train_loss.retain_grad()

        self.log('train_loss', train_loss, prog_bar=True)
        return train_loss

    def validation_step(self, batch, batch_idx):
        self._shared_eval(batch, batch_idx, 'val')

    def test_step(self, batch, batch_idx):
        self._shared_eval(batch, batch_idx, 'test')

    def _shared_eval(self, batch, batch_idx, prefix):
        x, y = batch
        # z = self.encoder(y)
        # pred_y = self.decoder(z)
        pred_x = self(x)
        loss = F.smooth_l1_loss(pred_x, x)
        self.log(f'{prefix}_loss', loss, prog_bar=True)
        return loss

    def configure_optimizers(self):
        # optimizer = torch.optim.Adam(self.parameters(), self.lr)
        optimizer = AdaBelief(self.parameters(), lr=self.lr, eps=1e-16, betas=(0.9, 0.999), weight_decouple=True, rectify=True)
        return optimizer

    def weights_init(self, m):
        if isinstance(m, nn.Conv2d) or isinstance(m, nn.ConvTranspose2d):
            torch.nn.init.normal_(m.weight, 0.0, 0.02)
        if isinstance(m, nn.BatchNorm2d) or isinstance(m, nn.BatchNorm1d):
            torch.nn.init.normal_(m.weight, 0.0, 0.02)
            torch.nn.init.constant_(m.bias, 0)
        if isinstance(m, nn.Linear):
            torch.nn.init.normal_(m.weight, 0.0, 0.02)
            torch.nn.init.constant_(m.bias, 0)

# Load
location = torch.device('cpu')
m_ae_model = torch.load("m_ae_model.pt", map_location=location)
m_ae_model.eval()

with torch.no_grad():
    x_hat = m_ae_model(x)

x, x_hat, y = x.numpy(), x_hat.numpy(), y.numpy()

Error screenshot:
![image](https://user-images.githubusercontent.com/54369128/104946514-03819d00-596f-11eb-8259-6e9e9a7e7d82.png)

**Comment by awaelchli** [comment]
How did you create the checkpoint "m_ae_model.pt"? Did you just use the automatic model checkpointing from pytorch? or did you  create it in a different way? It is a bit suspicious that torch.load would try to unpickle a trainer.

**Comment by ncuxomun** [comment]
Hi! I did save the checkpoint "m_ae_model.pt" with  torch.save(...). Once when trained on GPU and once when trained over CPU.
Another time I attempted to load a checkpoint (trained on GPU) from lightning logging folder via:
model = MyLightingModule.load_from_checkpoint(PATH)
But again, the issue remained the same.

On another note, how would you advise to save (whole/partial) models?

**Comment by awaelchli** [comment]
See here https://pytorch.org/tutorials/beginner/saving_loading_models.html#save-load-entire-model
there are many disadvantages saving the whole model by pickling it. One example you see here, it will not work with a new version of PL for example. 
You should save the state_dict instead. See https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-loading-model-for-inference

**Comment by awaelchli** [comment]
You can use `Trainer.save_checkpoint` if you wish to be able to load your model with `LightningModule.load_from_checkpoint`
