### ISSUE TITLE
GAN Manual optimization not working after 1.0.7

### ISSUE THREAD

**Issue by import-antigravity** [PyTorchLightning/pytorch-lightning#5545]
## 🐛 Bug

I have a GAN model and as of 1.0.7 it no longer trains correctly. I've tried to troubleshoot the issue to the best of my ability but I have no idea what's causing the problem.

## Please reproduce using the BoringModel

https://colab.research.google.com/gist/import-antigravity/0730243bb11b56031110fd6aa7d58971/the-boringmodel.ipynb

### To Reproduce

See boringmodel above^^^

### Expected behavior

Using the colab notebook switch between version 1.0.6 and 1.0.7 to see the bug. For 1.0.6 after training a few epochs it's clear the GAN is beginning to converge, for 1.0.7 it just makes noise.

### Environment

 - PyTorch Version (e.g., 1.0): 1.0.7
 - OS (e.g., Linux): macOS, Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): n/a
 - Python version: 3.8
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: N/A

**Comment by tchaton** [comment]
Hey there,

Would you mind to try out master ?

Best,
T.C

**Comment by import-antigravity** [comment]
The error happens on every version up to and including the current stable release.

**Comment by Borda** [comment]
Hello, I have run the attached example but I have not seen any error, mind pls clarify what is the expected behavior?

**Comment by import-antigravity** [comment]
Running with version 1.0.7 produces basically noise, as shown in the ‘imshow’ cell
![D1C6B1A5-DA18-4B9C-8F8E-1EE08C82267B](https://user-images.githubusercontent.com/24441495/104857903-97a92100-58e9-11eb-9003-39b93b508a49.jpeg)

**Comment by import-antigravity** [comment]
It’s not an error, the code runs but does not function correcty

**Comment by import-antigravity** [comment]
> Hello, I have run the attached example but I have not seen any error, mind pls clarify what is the expected behavior?

Here is the notebook run with 1.0.6, you can see that after a couple of epochs it's clearly converging to a digit:
<img width="264" alt="Screen Shot 2021-01-19 at 2 33 26 PM" src="https://user-images.githubusercontent.com/24441495/105083917-9ac81c80-5a63-11eb-9870-43762943d013.png">

Here is the same notebook run with 1.0.7, there's no such convergence and it just produces noise:
<img width="278" alt="Screen Shot 2021-01-19 at 2 35 06 PM" src="https://user-images.githubusercontent.com/24441495/105083994-b9c6ae80-5a63-11eb-9e46-38d1163e075b.png">

**Comment by import-antigravity** [comment]
@Borda are you able to reproduce the above images in the notebook?

**Comment by Borda** [comment]
> @Borda are you able to reproduce the above images in the notebook?

yes, I can reproduce and see the same diff you illustrated in https://github.com/PyTorchLightning/pytorch-lightning/issues/5545#issuecomment-763080383

**Comment by tchaton** [comment]
Hey @import-antigravity,

I have bumped this to P0 Priority. We will look into it asap.

Best,
T.C

**Comment by carmocca** [comment]
Hi @import-antigravity! Thanks for the code snippet, it really helped!

This works in current master, as long as you run `optimizer.zero_grad()` before backward.

```python
g_opt.zero_grad()
self.manual_backward(g_loss, g_opt)
g_opt.step()
```

Same for `d_opt`.

Note that `manual_optimizer_step` has been removed.

Sorry for the API changes. Also, we plan to roll out a better fix ASAP but this should work in the meantime

**Comment by import-antigravity** [comment]
Okay, 

> Hi @import-antigravity! Thanks for the code snippet, it really helped!
> 
> This works in current master, as long as you run `optimizer.zero_grad()` before backward.
> 
> ```python
> g_opt.zero_grad()
> self.manual_backward(g_loss, g_opt)
> g_opt.step()
> ```
> 
> Same for `d_opt`.
> 
> Note that `manual_optimizer_step` has been removed.
> 
> Sorry for the API changes. Also, we plan to roll out a better fix ASAP but this should work in the meantime

Hmmm... I'm running that code in master (or whatever the version is when I install with pip and don't specify a version) and it's still not working.

Here's the link to the notebook again: https://colab.research.google.com/gist/import-antigravity/0730243bb11b56031110fd6aa7d58971/the-boringmodel.ipynb

**Comment by carmocca** [comment]
> Hmmm... I'm running that code in master (or whatever the version is when I install with pip and don't specify a version) and it's still not working.

That's the issue, your are using the last version in PyPI, not master.

To user master (we will release 1.2 very soon so don't worry about it), run:

`! pip install git+https://github.com/PyTorchLightning/pytorch-lightning`

**Comment by import-antigravity** [comment]
Yep, it looks like it works now! Thanks!

**Comment by import-antigravity** [comment]
Hi all,

I re-ran the notebook in master and it appears to be working neither in master, nor the most recent release (1.2.1)

**Comment by ethanwharris** [comment]
@import-antigravity this seems to be fixed if you movethe `zero_grad` calls to __before__ the forward passes for the generator and discriminator. Not sure why the behaviour changed...

**Comment by import-antigravity** [comment]
> @import-antigravity this seems to be fixed if you move the `zero_grad` calls to **before** the forward passes for the generator and discriminator. Not sure why the behaviour changed...

Oops, didn't see this until now. Let me try

**Comment by import-antigravity** [comment]
Works now! That's odd that this is the case. I'm closing this issue again but keeping #6282 open because I think we should get to the bottom of why that's going on, and also the docs do not reflect that this is required for proper functionality
