### ISSUE TITLE
on_train_epoch_end vs training_epoch_end

### ISSUE THREAD

**Issue by Bajo1994** [PyTorchLightning/pytorch-lightning#5550]
## ❓ Questions and Help

What is the difference between on_train_epoch_end and training_epoch_end? For what applications should we use each?

**Comment by tchaton** [comment]
Hey @Bajo1994,

* `training_epoch_end` will be used for the user to aggregate the outputs from training_step at the end of an epoch.

Example.
```
    def training_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"loss": loss}

    def training_step_end(self, training_step_outputs):
        return training_step_outputs

    def training_epoch_end(self, outputs) -> None:
        torch.stack([x["loss"] for x in outputs]).mean()
```

* on_train_epoch_end is a hook. It would be used to add extra logic to control the behaviour of the model.
But it is left to the user to choice how he wants to use it :)

I hope it helps !

Best,
T.C

**Comment by Bajo1994** [comment]
Many thanks for a thorough response.
