### ISSUE TITLE
hparams.yaml saved twice when using TensorBoardLogger

### ISSUE THREAD

**Issue by Andry-Bal** [PyTorchLightning/pytorch-lightning#5562]
## 🐛 Bug

When using `TensorBoardLogger(...default_hp_metric=False...)` and calling `self.save_hyperparameters()` from `LightningModule `instance, two _hparams.yaml_ files are created (unexpected one in the logger's `save_dir` and second under proper experiment version dir).

## Please reproduce using the BoringModel
See [**BoringModel**](https://colab.research.google.com/drive/1OpUpfU9awCEjPCR_XYo8z5TmF0MxBTJA?usp=sharing).

### To Reproduce

1. Create `LightningModule` with `self.save_hyperparameters()` call in `__init__`
2. Create `TensorBoardLogger` with `default_hp_metric=False`
3. Start training

### Expected behavior

Only one _hparams.yaml_ in `save_dir/name/version` should be created (like it happens when using tb logger with `default_hp_metric=True`).

### Environment
From Collab Notebook:

* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0+cu101
	- pytorch-lightning: 1.1.4
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           1 SMP Thu Jul 23 08:00:38 PDT 2020

**Comment by Andry-Bal** [comment]
### Update
The issue is **not related** to `self.save_hyperparameters()` in `LightningModule's` `__init__` as described above. It is `default_hp_metric=False` in a logger that causes unwanted _hparams.yaml_ to be created in loger's `save_dir`.

**Comment by ByronCHAO** [comment]
You can write this as a temporary workaround
```
logger = TensorBoardLogger(...default_hp_metric=False...)
_ = logger.experiment # add this
```

the second line will create the proper experiment version dir.
