### ISSUE TITLE
Best model checkpoints only save rank zero part of the pipe paralleled model.

### ISSUE THREAD

**Issue by haven-jeon** [PyTorchLightning/pytorch-lightning#5567]
## 🐛 Best model checkpoints only save rank zero part of the pipe paralleled model.

When saving the best checkpoint of the piped parallel model in the relevant module, only a part of the model is saved. The method of storing rank zero is suitable for the method of DP, but there is an issue in the MP.

I confirmed that the code below works well.
https://github.com/haven-jeon/pytorch-lightning/commit/9ebe8c031ded47cb31aee92fe3b64c797d11dfa4#diff-05daced8d811d9d4566136e3db8c0c35dac3312e6ca6ee6ba0ef7678fa16d051

### To Reproduce

Use following [**BoringModel**](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing) and post here

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

* `IDE`: Please, use our python [bug_report_model.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
) template.

* `Colab Notebook`: Please copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py) (or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): Centos 7
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: P40
 - Any other relevant information:

**Comment by edenlightning** [comment]
@tchaton

**Comment by SeanNaren** [comment]
Hey thanks @haven-jeon, I have a branch here which adds the missing function call:

https://github.com/PyTorchLightning/pytorch-lightning/tree/bug/5567-fix-pipe-checkpoint

You also add a warning in your branch, what's the reason for the warning?

**Comment by haven-jeon** [comment]
@SeanNaren Thanks.

There are issues in the `load_from_checkpoints()` as well as the model saving, warning parts is temporary code. The loading problem will be created as a separate issue.

**Comment by edenlightning** [comment]
@SeanNaren anything left TODO here?
