### ISSUE TITLE
When overwriting the setup() function in the LightningDataModule, it is forced to add an unnecessary parameter.

### ISSUE THREAD

**Issue by Toyhom** [PyTorchLightning/pytorch-lightning#5572]
### Environment

 - PyTorch Version (e.g., 1.0):1.7
 - OS (e.g., Linux):Windows
 - How you installed PyTorch (`conda`, `pip`, source):pip
 - Python version:3.6.12
 - CUDA/cuDNN version:11.0
 - GPU models and configuration: 
 - Any other relevant information: def setup(self)

### Additional context

I have to add another argument to setup(self) for it to work, such as setup(self,a), which I won't actually use at all.

**Comment by rohitgr7** [comment]
the other parameter refers to `stage` which can be 'fit'(called with `trainer.fit`) or 'test'(called with `trainer.test`). Using this you can avoid loading both train & val and test data all at once.
something like:
```python
def setup(self, stage):
    if stage == 'fit':  # will be 'fit' when calling trainer.fit()
        # load train & val data only
    elif stage == 'test':  # will be 'test' when calling trainer.test()
        # load test data only
```

**Comment by Toyhom** [comment]
Thank you for your answer.
