### ISSUE TITLE
"has conflicts" label removal

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#5573]
The "has conflicts" label is not removed automatically once conflicts are fixed

cc: @Borda

**Comment by Borda** [comment]
yes, non of mergify actions is running, it seems that we have not enabled it correctly...
I was checking the config in mergify dashboard and they are correct, co the bottleneck is on PL setting side 🐰

**Comment by Borda** [comment]
implemented in #5499 #5608 #5612 #5639
