### ISSUE TITLE
Accelerator examples cannot run

### ISSUE THREAD

**Issue by alanhdu** [PyTorchLightning/pytorch-lightning#5575]
## 📚 Documentation

In the [accelerator documentation](https://pytorch-lightning.readthedocs.io/en/stable/accelerators.html), the documentation tells you to use a custom accelerator like:

```python
trainer = Trainer(accelerator=DDPAccelerator())
```

Unfortunately, this is not actually possible -- all of the accelerators (AFAICT) require a `trainer` argument, and actually trying to execute this code raises:

```python
TypeError: __init__() missing 1 required positional argument: 'trainer'
```

Because of this, I'm not actually sure how to use a custom accelerator because there seems to be a circular dependency: the accelerators require the `trainer` as input, the trainer itself needs an accelerator.

**Comment by carmocca** [comment]
Hi @alanhdu!

Actually, it's not a bug in the documentation but in the signature! It should be `Optional`. You can just pass in None and it will be set later.

The parent class is correct:

https://github.com/PyTorchLightning/pytorch-lightning/blob/24462dc5fdc079e909f214bb6f938bfe42dbcf43/pytorch_lightning/accelerators/accelerator.py#L37

Do you want to open a PR with the fix?

**Comment by alanhdu** [comment]
I might send a PR in the future, but definitely not for a couple of days (in case anyone else wants to send it first).

**Comment by Rajathbharadwaj** [comment]
Hey, I'd like to contribute, any pointers on getting started?

**Comment by carmocca** [comment]
You'd have to:

- 1. Create a branch off the release/1.2-dev branch
- 2. Check every accelerator and make sure its signature includes `trainer: Optional[Trainer] = None`
- 3. Add tests to make sure your changes are working! You can use the example from the docs.
- 4. Open a PR!

**Comment by Rajathbharadwaj** [comment]
Got it. To check  all the accelerator, I just need to  check all the accelerator folder?

**Comment by Rajathbharadwaj** [comment]
> Got it. To check all the accelerator, I just need to check all the accelerator folder?

Also just changing the signature enough? , because if there is no conditional case checking if `trainer is not None`, then it might cause an error.

**Comment by carmocca** [comment]
> I just need to check all the accelerator folder?

Yes!

> Also just changing the signature enough? , because if there is no conditional case checking if trainer is not None, then it might cause an error.

You can make sure no errors are caused with tests :)

**Comment by Rajathbharadwaj** [comment]
Gotcha!

**Comment by awaelchli** [comment]
After the major accelerator refactor, this should now be possible. But some of the old accelerator logic is now placed in plugins. There are not many docs yet because the API is in beta. But as you have discussed here, most arguments in the plugins are optional and will be set internally according to the trainer settings.
