### ISSUE TITLE
ModelCheckpoint best_model_score not set with DDP

### ISSUE THREAD

**Issue by alanhdu** [PyTorchLightning/pytorch-lightning#5582]
## 🐛 Bug

When using the DDP accelerator, it looks like the `ModelCheckpoint.best_model_score` is not set anymore -- that means you cannot easily reconstruct the "best" performing model.

### To Reproduce

<details>

<summary> Reproducing Code </summary>

```python
import pytorch_lightning as pl
import torch.nn as nn
import torch

class RandomDataset(torch.utils.data.Dataset):
    def __init__(self, length: int):
        self.length = length
    def __len__(self):
        return self.length
    def __getitem__(self, idx: int):
        return torch.rand(100), torch.rand(5)

class TestModule(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.network = nn.Linear(100, 5)
        self.loss = nn.MSELoss()
        self.counter = 0
    def configure_optimizers(self):
        return torch.optim.Adam(self.network.parameters(), 1e-3)
    def training_step(self, batch, batch_idx: int) -> float:
        X, y = batch
        y_hat = self.network.forward(X)
        return self.loss(y, y_hat)
    def validation_step(self, batch, batch_idx: int) -> None:
        pass
    def validation_epoch_end(self, outputs):
        self.counter += 1
        self.log("val_score", self.counter)

if __name__ == "__main__":
    train_loader = torch.utils.data.DataLoader(RandomDataset(10), batch_size=4)
    val_loader = torch.utils.data.DataLoader(RandomDataset(2), batch_size=1)

    mod = TestModule()

    model_checkpoint = pl.callbacks.ModelCheckpoint(monitor="val_score", mode="max")
    trainer = pl.Trainer(
        callbacks=[pl.callbacks.ProgressBar(), model_checkpoint],
        accelerator="ddp_cpu",
        num_processes=2,
        max_epochs=10,
    )
    trainer.fit(mod, train_loader, val_loader)
    assert model_checkpoint.best_model_score is not None
```

</details>

fails with

```python
Traceback (most recent call last):
  File "scratch.py", line 45, in <module>
    assert model_checkpoint.best_model_score is not None
AssertionError
```

### Expected behavior

In this case, `model_checkpoint.best_model_score` should be 11 (and it is, if you not use `ddp_cpu`).

### Environment

 - PyTorch Version (e.g., 1.0): pytorch=1.7.1=py3.6_cpu_0
 - PyTorch Lightning Version: 1.1.4
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda (cpuonly)
 - Python version: 3.6.10
 - Any other relevant information:

**Comment by carmocca** [comment]
Hi!

If i'm not mistaken, this is due to a limitation of `ddp_cpu`, not an actual bug. It should work as expected with `accelerator=ddp`.

`ddp_cpu` uses `multiprocessing.spawn` behind the scenes and spawned children do not inherit all parent resources by design.

In any case, the `ddp_cpu` is just used for debugging purposes and is not any faster than `cpu`

cc: @awaelchli ?

**Comment by alanhdu** [comment]
FWIw, we're currently stuck using `ddp_spawn` (for "reasons"), which also exhibits this issue.

**Comment by awaelchli** [comment]
Hi, yes Carlos is right this is a limitation of how processes are spawned (multiprocessing.spawn). The trainer spawns n additional worker processes (so total n+1) and the process 0 does nothing except waiting until the spawned ones have returned from fit. At the end of fit, we transfer the model weights back to process 0 (in a multiprocessing.queue), the worker processes die. In addition, we also transfer back the best model path, which is needed in case user calls trainer.test(). You can find this code in the DDPSpawnAccelerator and DDPCPUSpawnAccelerator. 
https://github.com/PyTorchLightning/pytorch-lightning/blob/f477c2fd2980ad128bfe79a3b859e0b81b435507/pytorch_lightning/accelerators/ddp_spawn_accelerator.py#L249

We could in theory also add the model score there. I think that could be reasonable (if you think that's ok, I can work on this). However, note there are many more attributes we could put on the queue, but it is not really how it is meant to work. 

The above statements concern both ddp_spawn (which is gpu) and ddp_cpu (which could also be called ddp_cpu_spawn), some details may differ.

**Comment by awaelchli** [comment]
As a workaround for you right now until discussion is fully resolved, you should have access to the best model path. Therefore, you can manually load the checkpoint with torch.load and get the "best_model_score" directly from the dict that torch.load returns.
