### ISSUE TITLE
Refactor RunningStage routing mechanism

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#5593]
### Motivation

Currently, tes / predict function is relying on an ENV variable to set testing to True.

The logic should be simplified and cleaned up.

### Additional context

> No we can't in the current state of the codebase. Trainer.predict relies on self.trainertesting to be True for routing the code in the test part of the evaluation loop, and if we set self._running_stage = RuningStage.PREDICTING, it would route to validation and we won't gather the prediction.
> I plan to properly refactor routing in a follow up PR as it is currently a big mess.

_Originally posted by @tchaton in https://github.com/PyTorchLightning/pytorch-lightning/pull/5579#r561226879_

**Comment by rohitgr7** [comment]
which env variable?

**Comment by awaelchli** [comment]
@carmocca I believe this can be closed because you have worked on this just recently in #4945, right?

**Comment by carmocca** [comment]
Yes!
