### ISSUE TITLE
configure_callbacks hook for LightningModule

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#5615]
### Motivation

Provide model-specific callbacks in a LightningModule

### Pitch

Add a configure_callbacks method to LightningModule
Append the returned callbacks to the trainer callbacks. 

### Additional context

cc @edenlightning

**Comment by edenlightning** [comment]
Improvements:
* Supporting priorities for callbacks

CallbackA(priority=1)
CallbackB(priority=1)
CallbackC(priority=2)
In this case, A, B are called sequentially (order does not matter between A, B because both are priority 1.

And C is called after

A, B
C
or

B, A
C

**Comment by edenlightning** [comment]
Another improvments: Support child callbacks, to customize callback order

As a user, I want callbacks to be called in a specific order.

a = CallbackA()
b = CallbackB()
c = CallbackC()
d = CallbackD()

a.child_callback(b)
a.child_callback(c)
c.chold_callback(d)
The dag looks like:

a -> B
-> C -> D
