### ISSUE TITLE
speed up CI testing by running tests in parallel

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#5624]
### Motivation

Testing time in CI is high (> 10 min per commit), but we are not using all available resources. 
Tests that run on CPU can be executed in parallel. 

### Pitch

Use something like [pytest-xdist](https://github.com/pytest-dev/pytest-xdist) on a subset of the tests. 
I did some quick testing with pytest-xdist on the core tests:

```bash
pip install pytest-xdist 

py.test -v tests/core
# time: ~216s

py.test -v -n 2 tests/core
# time: ~149s
# speedup: 1.4x

py.test -v -n 10 tests/core
# time: ~42s
# speedup: 5.1x

```
Some tests still need to run sequentially, for example the GPU and multi-processing tests. 
For example, if we try to run xdist on tests/metrics we see there is a ddp communication issue.

### Alternatives

Feed cat while waiting for tests to finish. Cat will get very fat.

cc @Borda

**Comment by Borda** [comment]
yes, we have been playing with it past too, see #3606 #4854 but none of them was a simple win as you say that GPU need to run in a single process (no concurrent usage of GPU) which was pretty much our issue with setting any constancy on Drone

so yes we can separate folder in tests which can parallel and which need single stream aka
- tests/integration
- tests/unit_cpu
- tests/unit_gpu

or we could try is there is some pytest marker to mark which test cannot be run in parallel mode (I would say the mest) :]

**Comment by tchaton** [comment]
Hey @Borda @awaelchli,

Yes, let's try to re-explore this. If we could divide by 2 the running time of Drone, it would already be great !
I added this one as priority for 1.3.

Best,
T.C

**Comment by Borda** [comment]
> Yes, let's try to re-explore this. If we could divide by 2 the running time of Drone, it would already be great !

so far I have check we can speed up any CPU based test, but no test using GPU, and some far 70% of the 20min with Drone are GPU tests... so lest try but do not have too high expectations 🐰

**Comment by Borda** [comment]
FYI, I have run the full test in auto-parallel and seems that there is some other overhead since there is now gain overall
see: https://github.com/PyTorchLightning/pytorch-lightning/actions/runs/514805076

**Comment by edenlightning** [comment]
@Borda is this worth looking into for 1.3?

**Comment by Borda** [comment]
we are heer somehow block with refactoring tests, as just using parallel testing does not speed-up anything

**Comment by akihironitta** [comment]
Does anyone know why this issue was closed? Any link to the discussion? :eyes:

**Comment by Borda** [comment]
> Does anyone know why this issue was closed? Any link to the discussion?

pls see my comment above https://github.com/PyTorchLightning/pytorch-lightning/issues/5624#issuecomment-765902886

**Comment by akihironitta** [comment]
Thank you for pointing to the comment, and I'm sorry I somehow missed your comments above... :sweat_drops:
