### ISSUE TITLE
Failing to log to Neptune.ai when resuming from checkpoint

### ISSUE THREAD

**Issue by briankosw** [PyTorchLightning/pytorch-lightning#5626]
## 🐛 Bug

I'm trying to resume training from a checkpoint, and I'm trying to resume logging using the Neptune.ai logger, but it throws this particular error:

```
neptune.api_exceptions.ChannelsValuesSendBatchError: Received batch errors sending channels' values to experiment CAS-68. 
Cause: Error(code=400, message='X-coordinates must be strictly increasing for channel: b7ab6110-7a1b-4093-a35f-dc0904ff943f. Invalid point: InputChannelValue(timestamp=2021-01-23T11:02:05.882Z, x=98.0, numericValue=0.30072227120399475, text', type=None) (metricId: 'b7ab6110-7a1b-4093-a35f-dc0904ff943f', x: 98.0) Skipping 3 values.
```
At the point that I'm resuming, I've already trained for 7000 steps, yet the logger tries to log at step `x=98.0` as seen in the error message. 

## Please reproduce using the BoringModel

I'm not sure how I should reproduce this bug since it's more related to how Neptune.ai's logger specifically works, but I can try to come up with a repro soon.

## Environment

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8.5
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: Tesla V100
 - Any other relevant information:

**Comment by awaelchli** [comment]
Duplicate? #5130 
A PR for a fix is in development.
