### ISSUE TITLE
Cross-validation

### ISSUE THREAD

**Issue by gianscarpe** [PyTorchLightning/pytorch-lightning#5628]
### Motivation
I believe `cross-validation` directly implemented as part of pytorch-lightning could help a lot of users! 

### Pitch
Trainer.train could have a method `cross-validation` with parameters similar to `train` and a parameter for `cross-validation-split`. This is a nice feature to have, especially when we have small model/dataset! 

### Additional context
We can keep `sklearn` as a reference for this https://scikit-learn.org/stable/modules/cross_validation.html

**Comment by awaelchli** [comment]
See  #839

**Comment by gianscarpe** [comment]
Hi @awaelchli, sorry didn't find it with search tool!
