### ISSUE TITLE
charts in docs as plotly plots

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#5630]
## 🚀 Feature

replace all static plots in docs to Plotly
see: https://github.com/PyTorchLightning/pytorch-lightning-bolts/issues/537

### Motivation

- save space (no need for png images),
- better control over the content
- native resolution even for details/zoom-in

### Pitch

full transparency

### Alternative

http://nipy.org/nipy/devel/guidelines/sphinx_helpers.html#inserting-matplotlib-plots

**Comment by akihironitta** [comment]
btw do we have charts in lightning docs? I could find some (~ugly~ screenshots of TensorBoard) in Bolts, but I couldn't here.

**Comment by carmocca** [comment]
Is this worth doing? What plots would we update exactly?

**Comment by akihironitta** [comment]
I believe we can close this because AFAIK we don't have plots in the docs.

**Comment by Borda** [comment]
It could be used for benchmark results, cc: @kaushikb11
