### ISSUE TITLE
build-conda CI failed

### ISSUE THREAD

**Issue by tarepan** [PyTorchLightning/pytorch-lightning#5635]
## 🐛 Bug
`build-conda` CI failed almost every time.  

## To Reproduce
Run CI.  

- Example1: [current master HEAD](https://github.com/PyTorchLightning/pytorch-lightning/runs/1754427567)
- Example2: [current release/1.2-dev HEAD](https://github.com/PyTorchLightning/pytorch-lightning/runs/1746234872)

### Expected behavior
Build successfully.  

### Environment
Both

- `master`
- `release/1.2-dev`

### Additional context
It is long-lasting error which prevent efficient CI usage (now we routinely **ignore** CI result).  
At least, we can collect information about this error here for all (future) contributors.

**Comment by tarepan** [comment]
## Error code
[build-conda (3.8, 1.6)](https://github.com/PyTorchLightning/pytorch-lightning/runs/1746234872)

```bash
2148 #9 91.82     CMake Error at horovod/torch/CMakeLists.txt:21 (message):
2149 #9 91.82       Horovod build with GPU support was requested but this PyTorch installation
2150 #9 91.82       does not support CUDA.
```

**Comment by Borda** [comment]
yes, have implemented skip for unrelated RP in #5203
moreover, I was also trying to resolve this issue in #5611 but the failure seems kind of random...
@tarepan do you have any suggestions on how to fix it what shall we try?

**Comment by ydcjeff** [comment]
@tadejsv yes, we skip `CI build docker` for the PR if docker related files are not in the changes (only in master for now, haven't applied to `release/1.2-dev`). also, we have set timeout limits to 50 minutes, if the CI freeze, the job will fail.

**Comment by tarepan** [comment]
## Error origin analysis
- [`ci_dockers.yml`]'s `Build CUDA Docker` step
  - [`base-conda/Dockerfile`]'s 3rd RUN command (pip things)
    - pip wheel build error ?
      - `Horovod`
        - `CMake Error at horovod/torch/CMakeLists.txt`

[`ci_dockers.yml`]:https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/workflows/ci_dockers.yml
[`base-conda/Dockerfile`]:https://github.com/PyTorchLightning/pytorch-lightning/blob/master/dockers/base-conda/Dockerfile

[Above Error](https://github.com/PyTorchLightning/pytorch-lightning/issues/5635#issuecomment-766304178) is from `Horovod` 's [`CMakeLists.txt`](https://github.com/horovod/horovod/blob/599137d8129df6c18d82e2dfb29f14a083a341aa/horovod/torch/CMakeLists.txt#L20-L21)).  

```
if (HAVE_CUDA AND NOT Pytorch_CUDA)
    message(FATAL_ERROR "Horovod build with GPU support was requested but this PyTorch installation does not support CUDA.")
```

HAVE_CUDA  seems to be set base on [`ADD_CUDA` macro](https://github.com/horovod/horovod/blob/994913a2abc5812042a5c3540ced5b3316d23b72/CMakeLists.txt#L150)


PyTorch_CUDA seems to be set based on [this code](https://github.com/horovod/horovod/blob/ee64d414287feb8ba2d97bdeb23fe33e9f5c6c89/cmake/Modules/FindPytorch.cmake#L25-L26).  
The core is `(torch.version.cuda is not None) and (CUDA_HOME is not None)` (CUDA_HOME is `from torch.utils.cpp_extension import CUDA_HOME`)

**Comment by tarepan** [comment]
@Borda could I ask you the purpose of `build-conda`?  
Is it for **build test** on Anaconda?  

In that case, `base-conda/Dockerfile` install some dependencies through **`pip`** (and this part cause the build error).  
Is it intended test process?

**Comment by Borda** [comment]
> @Borda could I ask you the purpose of `build-conda`? Is it for **build test** on Anaconda?

yes, we are building conda image just for testing PL on Conda and we do not want to install all Conda dependencies for the Conda test run...

> In that case, `base-conda/Dockerfile` install some dependencies through **`pip`** (and this part cause the build error). Is it intended test process?

yes some packages ate installed with pip as they do not exist in conda-forge repository or they just need to be build from a source such as horovod
