### ISSUE TITLE
Add a bot for changelog

### ISSUE THREAD

**Issue by rohitgr7** [PyTorchLightning/pytorch-lightning#5637]
## 🚀 Feature
Add a bot to check whether CHANGELOG.md is updated or not in a PR

### Motivation
We can add a bot to check if CHANGELOG.md is updated or now wherever it's required. We can mark this as required.

**release branch**
If possible to do with milestones then milestones set to `release/xxx` must have a CHANGELOG since all the changes made considering base as the release branch are features/enhancement. Other changes made there are like adding a new changelog section or syncing master to release branch, CHANGELOG is anyways updated.

**master**
For the master branch, if a PR has labels `documentation`, `tests/ci`, `tutorial/examples` then we can ignore this requirement. For rest it should be marked as required.

### Alternatives
Manually check if it's updated or not.

Of course open to suggestions here. Please feel free to edit/update as per requirement.

cc @Borda

**Comment by edenlightning** [comment]
Great idea!

**Comment by Borda** [comment]
@rohitgr7 sorry for the long delay, yes according to labels or milestones it sounds good
talking about branch name - that would be suboptimal as you cannot change branch name once PR is created...

**Comment by rohitgr7** [comment]
@Borda I meant the base branch up there. But I guess that won't be a problem since we have only the master branch now.
