### ISSUE TITLE
add check for dead code

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#5649]
## 🚀 Feature

check if PR contains unused code or if the particular change dead code in not introduced somewhere else in the codebase

### Motivation

remove all unused code, keep the codebase healthy

### Alternatives

one toll I found - https://github.com/jendrikseipp/vulture
but let's check some alternatives

**Comment by aniketmaurya** [comment]
Do we have to write workflow for this? In case if we want to use the mentioned Library `Vulture` then we will write a workflow CI that will test reach PR?

**Comment by Borda** [comment]
@aniketmaurya yes we would add it here https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/workflows/code-formatting.yml

**Comment by aniketmaurya** [comment]
> @aniketmaurya yes we would add it here https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/workflows/code-formatting.yml

Thank you for the clarification @Borda . I've raised a PR with Vulture integrated to workflows. Please let me know if I need to correct something.

**Comment by Borda** [comment]
cool, to be clear my main concern when I tried the tool yesterday was how to. deal with methods arguments which are tthere because of inheritance but in cold they are not used anymore...
