### ISSUE TITLE
Kaggle and TPUs - Errors popping randomly in and out of existence

### ISSUE THREAD

**Issue by alexander-soare** [PyTorchLightning/pytorch-lightning#5665]
This is a general report about what it's like to work with PyTorch Lightining and TPUs on Kaggle. The reason I post it here instead of the XLA repo is that the PyTorch Lightning marketing openly invites us to use Kaggle. The reason I did not follow the bug template, is because I'm reporting something more general than one specific bug.

Over the past few days of trying to use the TPUs I've run into various errors that randomly pop into and out of existence like quantum particles. I can't paste the errors here because of their elusive nature, and I didn't have the hindsight of knowing it would come to this. Here are their descriptions:

- [OSError: Undefined Symbol](https://www.kaggle.com/discussion/214240)
- [Cannot replicate if number of devices (1) is different from 8](https://www.kaggle.com/discussion/214240)
- Some "failed to meet rendezvous point" error.
- Execution hangs indefinitely after `INIT TPU local core: 0, global rank: 0 with XLA_USE_BF16=None`. Also for 8 cores
- For 8 cores only, execution hangs indefinitely when progress bar appears (PyTorch Lightning)

Note that for ALL of these examples I've sometimes been able to do some combination of the following to fix it (without changing my code at all)

- Restart runtime
- Change to standard runtime then change back to TPU
- Refresh the page
- Run the same cell again

Unfortunately, I spend 80% of my time restarting my runtime and reinstalling XLA, and only 20% of my time feeling hopeful that "maybe I've fixed it for good"

By the way, this is how I set up XLA:

```
!curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
!python pytorch-xla-env-setup.py --version nightly --apt-packages libomp5 libopenblas-dev
```

**Comment by Borda** [comment]
@zcain117 this seems to be directly torch XLA, right?

**Comment by alexander-soare** [comment]
Perhaps. I may try there too. Never sure who's going to want to call "mine"
on this one. May also belong to Kaggle. The logic of choosing Lighting was
that they seem to have a vested interest (amongst others) in making sure
Kagglers can use it.

**Comment by tchaton** [comment]
Dear @alexander-soare,

Mind trying this PR: https://github.com/PyTorchLightning/pytorch-lightning/pull/6272/

Best,
T.C

**Comment by alexander-soare** [comment]
@tchaton just gave it a shot here https://www.kaggle.com/alexandersoare/pytorch-lightning-tpu-error?scriptVersionId=55790594
The undefined symbol error is one of those ones that I've seen happening sometimes (and sometimes not).

**Comment by tchaton** [comment]
Dear  @alexander-soare,

I have run the script several times and it seems to be working fine inside a TPU VM.

![Screenshot 2021-03-09 at 14.44.08.png](https://images.zenhubusercontent.com/5fa02d9c703c16598a8d683b/3b11425a-bd5f-40f0-98e2-dc90e8a82005)

Best,
T.C

**Comment by edenlightning** [comment]
@tchaton any update?

**Comment by alexander-soare** [comment]
@tchaton it is tough to debug. I didn't even know how to write the report. It's just a bunch of different things, perhaps further complicated by the fact that it's running through Kaggle. Thanks for looking into it.

**Comment by kaushikb11** [comment]
Hi @alexander-soare,
Could you pinpoint what exact issue you are facing right now? Maybe I could help you resolve it.

**Comment by alexander-soare** [comment]
@kaushikb11 thanks for jumping in but I dropped this shortly after I wrote this issue and don't have the time to get back into it. I plan to periodically check PyTorch TPU libraries every 6~12 months till the wrinkles have been ironed out :)

**Comment by kaushikb11** [comment]
@alexander-soare Ahh, okay! Feel free to tag me if you face this issue again or post a question on Lightning Slack. Cheers!
