### ISSUE TITLE
failing tests for Windows (Appveyor)

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#568]
### Common bugs
There are several issues related to the Windows path structure

**To Reproduce**
- see our CI results - https://ci.appveyor.com/project/Borda/pytorch-lightning/builds/29252138/job/ip4j5poawhphfd7g

**Expected behavior**
Fix bugs and enable Appveyor CI for PR check

**Comment by Borda** [comment]
- https://ci.appveyor.com/project/Borda/pytorch-lightning/builds/29252138/job/ip4j5poawhphfd7g#L708
- https://ci.appveyor.com/project/Borda/pytorch-lightning/builds/29252138/job/ip4j5poawhphfd7g#L760
- https://ci.appveyor.com/project/Borda/pytorch-lightning/builds/29252138/job/ip4j5poawhphfd7g#L782
- https://ci.appveyor.com/project/Borda/pytorch-lightning/builds/29252138/job/ip4j5poawhphfd7g#L834

**Comment by williamFalcon** [comment]
@Borda let's merge this on the circle CI issue? #626
