### ISSUE TITLE
Better logging with Loguru

### ISSUE THREAD

**Issue by TezRomacH** [PyTorchLightning/pytorch-lightning#5699]
## 🚀 Feature

In Pytorch-lightning you can notice logging information (set seed, write models summary, etc.) that is used, via `logging.getLogger(__name__)`.

I suggest an alternative as [Loguru](https://github.com/Delgan/loguru). The main advantages of Loguru are the colored messages and the acceleration of some functions (they plan to rewrite a lot of things in pure C).

### Motivation

To increase user engagement :)

### Pitch

I suggest use `_LOGURU_AVAILABLE` as usual and create a file with logger

```python
# in pytorch_lightning.utilities.loggers

from pytorch_lightning.utilities import _LOGURU_AVAILABLE

if _LOGURU_AVAILABLE:
    from loguru import logger as loguru_logger
    logger = loguru_logger
else:
    logger = logging.getLogger(__name__)

__all__ = ["logger"]
```

Wherever `log = logging.getLogger(__name__)` is used, change the import to

```python
from pytorch_lightning.utilities.loggers import logger
...

logger.info(...)
```

### Alternatives

Leave everything as it is ¯\_(ツ)_/¯

### Additional context
It could look like

```python
logger.info(f"Training with the following config:\n{OmegaConf.to_yaml(hparams)}")
```

<img width="659" alt="Screenshot 2021-01-29 at 00 16 26" src="https://user-images.githubusercontent.com/7549587/106199952-3d507000-61c7-11eb-8d10-a2c87afb075c.png">

**Comment by TezRomacH** [comment]
I can make a PR if the idea is okay :)

**Comment by jizongFox** [comment]
I definitively agree with @TezRomacH  and enjoy this PR.

**Comment by eusip** [comment]
I also agree with @jizongFox that @TezRomacH has proposed a PR that is worth further exploration.
