### ISSUE TITLE
Wrong `requires_grad` state after `return None` with multiple optimizers

### ISSUE THREAD

**Issue by deng-cy** [PyTorchLightning/pytorch-lightning#5723]
## 🐛 Bug

When I use multiple optimizers, I cannot use `return None` to skip one step, since it would cause error. I found that it was because `requires_grad` property of the corresponding network is not set to `True`. 

For instance, with two optimizers:

```
  def configure_optimizers(self):
      optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
      optimizer2 = torch.optim.SGD(self.layer2.parameters(), lr=0.1)
      return [optimizer, optimizer2], []
```

In the training step, 
```
def training_step(self, batch, batch_idx, optimizer_idx):
    print('optimizer_idx',optimizer_idx)
    print('layer:',next(self.layer.parameters()).requires_grad)
    print('layer2:',next(self.layer2.parameters()).requires_grad)
    ...
    return loss # loss is not None
```
we should get
```
optimizer_idx 0
layer: True
layer2: False

optimizer_idx 1
layer: False
layer2: True
...
```

However, if we return `None`, i.e.
```
def training_step(self, batch, batch_idx, optimizer_idx):
    ...
    return None
```
we would get
```
optimizer_idx 0
layer: True
layer2: False

optimizer_idx 1
layer: False
layer2: False
```
since returning `None` causes failure to change `requires_grad` state of layer2. 

### To Reproduce

https://colab.research.google.com/drive/1kRTKix1bxCOBJY0eR0h8jOVaRxt7L_6g?usp=sharing

### Expected behavior

`RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn`

### Environment

* CUDA:
	- GPU:
		- GeForce RTX 2080 SUPER
	- available:         True
	- version:           11.0
* Packages:
	- numpy:             1.19.2
	- pyTorch_debug:     False
	- pyTorch_version:   1.7.1
	- pytorch-lightning: 1.1.6
	- tqdm:              4.50.2
* System:
	- OS:                Windows
	- architecture:
		- 64bit
		- WindowsPE
	- processor:         Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
	- python:            3.8.5
	- version:           10.0.18362

**Comment by edenlightning** [comment]
Mind submitting a fix for this?

**Comment by deng-cy** [comment]
I drafted a PR

**Comment by edenlightning** [comment]
Thanks!!
