### ISSUE TITLE
Metrics `compute` result is being cached after `reset`

### ISSUE THREAD

**Issue by alanhdu** [PyTorchLightning/pytorch-lightning#5737]
## 🐛 Bug

It looks like after calling `pl.metrics.Metric.reset_state()`, the *previous* value of `pl.metrics.Metric.compute()` is somehow cached afterwards:

### To Reproduce

```python
import torch
import numpy as np
import pytorch_lightning as pl

class AverageMeter(pl.metrics.Metric):
    def __init__(self):
        super().__init__()
        self.add_state("value", torch.zeros(1), dist_reduce_fx="sum")
        self.add_state("count", torch.zeros(1), dist_reduce_fx="sum")

    def update(self, value):
        if isinstance(value, torch.Tensor):
            self.value += value.sum()
            self.count += value.numel()
        else:
            self.value += value
            self.count += 1

    def compute(self):
        return (self.value / self.count).item()

m = AverageMeter()
m.update(1)
m.compute()   # This passes if I don't call this line

m.reset()
print(m.value, m.count)
assert np.isnan(m.compute())
```

This crashes with:
```
tensor([0.]) tensor([0.])
1.0
Traceback (most recent call last):
  File "scratch.py", line 29, in <module>
    assert np.isnan(m.compute())
AssertionError
```

This is very strange -- the values of `value` and `count` are reset appropriately to be `(0, 0)`, but for some reason the compute value is 1.0.

If I comment out the `m.compute()` line, then this gives the expected behavior (of being `nan`).

### Expected behavior

This script should run without problems

### Environment

```
* CUDA:
	- GPU:
	- available:         False
	- version:           None
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.7.1
	- pytorch-lightning: 1.1.6
	- tqdm:              4.56.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
	- processor:         x86_64
	- python:            3.6.10
	- version:           #1 SMP Sun Jan 17 19:52:43 UTC 2021
```

**Comment by SkafteNicki** [comment]
This is the intended behavior, that no matter how many times `compute` is called in sequence you will still get the last computed result. The cashe is reset whenever `update` or `forward` is called.

**Comment by alanhdu** [comment]
Hm... would it be possible to update the documentation at https://pytorch-lightning.readthedocs.io/en/latest/metrics.html? There's no mention of this caching behavior, and I think it's not really obvious.

I would *love* a section on the "lifetime" of a metric -- when are things cached, when are things updated, and when are things reset (I assume they're reset by the Trainer on each epoch, but I don't think that's actually stated anywhere?).

**Comment by SkafteNicki** [comment]
@alanhdu we can definitly agree that it is not well documented. Thanks for pointing out :]
Metrics are still relatively new, and we are open for changes. For example from v1.2 `compute` will no longer call `reset` automatically anymore (many users was confused about this). However, this cashing behaviour is nessesary for us to proper log metrics in lightning.
I will try to come up with something that betters describes the lifetime of an metric.

If you dont mind, could you tell me what the usecase was that you wanted to call compute twice in a row?

**Comment by alanhdu** [comment]
>  For example from v1.2 compute will no longer call reset automatically anymore (many users was confused about this). 
That'd be great!

> could you tell me what the usecase was that you wanted to call compute twice in a row?

In this particular case, I was writing tests for some custom metrics and was confused about the right hooks for them. In general though, we implement a `__str__` to log the metrics to a custom logger which calls `compute` to get the current value of the metric. B/c of "reasons", in a complicated code-base we sometimes call `__str__` *and* `compute` to log to Lightning's logger.
