### ISSUE TITLE
is the LightningModule init args must be dict?

### ISSUE THREAD

**Issue by mlinxiang** [PyTorchLightning/pytorch-lightning#5741]
## 🐛 Bug

my LightningModule init args is <namespace> object which parse from cmd line, when i use load_from_checkpoint() the args change to dict, is these right? which cause my orignal code access such as opt.batch_size can't use anymore, pytorch_lightning is 1.1.6

![image](https://user-images.githubusercontent.com/6283983/106575338-ee179000-6576-11eb-834e-2d7350d63544.png)
![image](https://user-images.githubusercontent.com/6283983/106575353-f079ea00-6576-11eb-830b-991fb2a5a62f.png)

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux): mac
 - How you installed PyTorch (`conda`, `pip`, source): pip 
 - Build command you used (if compiling from source):
 - Python version: 3.6 
 - CUDA/cuDNN version: no
 - GPU models and configuration: no 
 - Any other relevant information: no

**Comment by carmocca** [comment]
You are correct. It is converted to `dict`. This is mentioned in the docs [here](https://pytorch-lightning.readthedocs.io/en/stable/weights_loading.html?highlight=load_from_checkpoint#pytorch_lightning.core.lightning.LightningModule.load_from_checkpoint.params.hparams_file).

Feel free to re-open if you have any further questions!
