### ISSUE TITLE
Is there a guide for code and test structure for new contributors? 

### ISSUE THREAD

**Issue by noamzilo** [PyTorchLightning/pytorch-lightning#5764]
## ❓ Questions and Help

Is there a guide for code and test structure for new contributors? 
Something like an architecture document, to be able to get into the code without reading most of it, and probably making mistakes.

I want to be able to contribute when I have time, but just getting into the code will take a while, and I was hoping this learning curve could be cut by some factor.

For example,

```
class EvalModelTemplate(
    ModelTemplateData,
    ModelTemplateUtils,
    TrainingStepVariations,
    ValidationStepVariations,
    ValidationEpochEndVariations,
    TestStepVariations,
    TestEpochEndVariations,
    TrainDataloaderVariations,
    ValDataloaderVariations,
    TestDataloaderVariations,
    ConfigureOptimizersPool,
    LightningModule,
):

has quite a few interfaces, which do things, and I doubt one has to know everything before being able to contribute.
```

___

Other basic issues I am facing-

1. How to enable GPUs for tests? It seems they are disabled by design.
2. How to see test (using pytest) prints as they go, without waiting for them to finish?
3. Which basic models, dataloaders, ect. to choose for basic tests? What are the options?
4. architecture overview of PL, top down

**Comment by justusschock** [comment]
Hey @noamzilo ,

I am afraid that we don't have anything like that. The closest to what you'd wish for is the [Contribution Guide](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md)

**Comment by carmocca** [comment]
Closing in favor of #6622
