### ISSUE TITLE
Strange behavior of loss logger, different from actual loss, and with delay. Probably I am misreading something

### ISSUE THREAD

**Issue by noamzilo** [PyTorchLightning/pytorch-lightning#5767]
## 🐛 Bug

This is a follow up on [this](https://github.com/PyTorchLightning/pytorch-lightning/issues/5681)

Please notice `overfit_batches=1`.
This should mean validation loss should always equal train loss, and I would expect val loss to follow the train loss.
We observe a lag of train loss behind val loss, which would mean validation batches are checked before train epochs.
This could make sense, but should be documented, or maybe it is a bug, I don't know.

I am seeing strange behavior in a much more complex model and dumbing it down led me to this.

Please advise :)

## Please reproduce using the BoringModel

```

def test_train_val_logging_at_same_epoch(tmpdir):
    class TestModel(BoringModel):
        def training_step(self, batch, batch_idx):
            output = self.layer(batch)
            loss = self.loss(batch, output)
            self.log("train_loss", loss, prog_bar=True, on_step=False, on_epoch=True)
            return {"loss": loss}

        def validation_step(self, batch, batch_idx):
            output = self.layer(batch)
            loss = self.loss(batch, output)
            self.log("val_loss", loss, prog_bar=True, on_step=False, on_epoch=True)
            return {"x": loss}


    # fake data
    train_data = torch.utils.data.DataLoader(RandomDataset(32, 64))
    val_data = torch.utils.data.DataLoader(RandomDataset(32, 64))

    # model
    model = TestModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        max_epochs=5,
        overfit_batches=1,
        weights_summary=None,
    )
    trainer.fit(model, train_data, val_data)
```

Output in command line:

Epoch 0:  50%|█████     | 1/2 [00:06<00:06,  6.40s/it, loss=1.81, v_num=9, val_loss=1.81]
Validating: 0it [00:00, ?it/s]
Epoch 0: 100%|██████████| 2/2 [00:06<00:00,  3.21s/it, loss=1.81, v_num=9, val_loss=6.35]
Epoch 1:  50%|█████     | 1/2 [00:00<00:00, 283.67it/s, loss=4.08, v_num=9, val_loss=6.35, train_loss=1.81]
Validating: 0it [00:00, ?it/s]
Epoch 1: 100%|██████████| 2/2 [00:00<00:00, 220.58it/s, loss=4.08, v_num=9, val_loss=3.23, train_loss=1.81]
Epoch 2:  50%|█████     | 1/2 [00:00<00:00, 397.23it/s, loss=3.8, v_num=9, val_loss=3.23, train_loss=6.35]
Validating: 0it [00:00, ?it/s]
Epoch 2: 100%|██████████| 2/2 [00:00<00:00, 248.24it/s, loss=3.8, v_num=9, val_loss=3.04, train_loss=6.35]
Epoch 3:  50%|█████     | 1/2 [00:00<00:00, 397.15it/s, loss=3.61, v_num=9, val_loss=3.04, train_loss=3.23]
Validating: 0it [00:00, ?it/s]
Epoch 3: 100%|██████████| 2/2 [00:00<00:00, 264.78it/s, loss=3.61, v_num=9, val_loss=3.03, train_loss=3.23]
Epoch 4:  50%|█████     | 1/2 [00:00<00:00, 397.19it/s, loss=3.49, v_num=9, val_loss=3.03, train_loss=3.04]
Validating: 0it [00:00, ?it/s]
Epoch 4: 100%|██████████| 2/2 [00:00<00:00, 248.24it/s, loss=3.49, v_num=9, val_loss=3.03, train_loss=3.04]
Epoch 4: 100%|██████████| 2/2 [00:00<00:00, 172.69it/s, loss=3.49, v_num=9, val_loss=3.03, train_loss=3.04]

### Actual behavior

Notice train loss in epoch k is always the same as val loss on epoch k-2

### Expected behavior

I expect val loss to follow train loss by at most 1 epochs, not lag by 2

### Environment

 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Win
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): -
 - Python version: 3.7.5
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: irrelevant
 - Any other relevant information: notice overfit batches=1!

**Comment by noamzilo** [comment]
Please notice that plotting the same values of  `val_loss` and of `train_loss` is also  shifted by one (validation loss comes too soon). Thus, I doubt this is a strictly logger issue.

**Comment by awaelchli** [comment]
> This should mean validation loss should always equal train loss, and I would expect val loss to follow the train loss.

This is not true. During the training step, the weights are updated. Since the loss is a function of the weights and you are logging the average over all training steps, this will always be different than the validation loss.

Your special case is overfit_batches=1. Since you only run one batch in a training step, and the logging adds the value to the progress bar **before the model weights get updated**, you see the loss value as the same as the previous validation. But the next validation will compute the validation loss with the **updated** model weights, therefore a different value.

**Comment by noamzilo** [comment]
Hi, thanks for your answer.
Please explain, as I still don't understand - why is `train_loss` logged before the weights update? shouldn't the point of train loss be to show what happened in the current epoch, not before that epoch?

[from the doc](https://pytorch-lightning.readthedocs.io/en/1.0.8/logging.html): 

> Automatically accumulates and logs at the end of the epoch.

but from your answer

> the logging adds the value to the progress bar before the model weights get updated,

So (unlike the doc) train loss gets updated BEFORE the epoch (with the value from the last epoch), and val loss gets updated AFTER the epoch (with the value from the current epoch)?

Sorry for being slow, I am not following the current logging logic and would love a through explanation once again if that is ok.

Thanks :)

**Comment by awaelchli** [comment]
training epoch begins

training_step begins
you compute loss with parameters **W0 on batch B0** -> train_loss = 1.0
`self.log("train_loss", loss, prog_bar=True, on_step=False, on_epoch=True)` -> logs 1.0, but doesn't show it on step
training_step ends
return loss -> Lightning computes backward and updates parameters **W0 -> W1**

training_step begins
you compute loss with parameters **W1 on batch B1** -> train_loss = 2.0
`self.log("train_loss", loss, prog_bar=True, on_step=False, on_epoch=True)` -> logs 2.0, but doesn't show it on step
training_step ends
return loss -> Lightning computes backward and updates parameters `W1 -> W2`

training epoch ends 
train_loss = (1.0 + 2.0) / 2 = 1.5 shows in progress bar

validation epoch begins (will use parameters **W2**)
validation step begins
you compute loss with parameters **W2 on batch B0** -> val_loss = 1.1
`self.log("val_loss", loss, prog_bar=True, on_step=False, on_epoch=True)` -> logs 1.1, but doesn't show it on step
validation step ends

validation step begins
you compute loss with parameters **W2 on batch B1** -> val_loss = 2.2
`self.log("val_loss", loss, prog_bar=True, on_step=False, on_epoch=True)` -> logs 2.2, but doesn't show it on step
validation step ends

validation epoch ends
val_loss = (1.1 + 2.2) / 2 = 1.65 shows in progress bar

this example shows how it is for `overfit_batches=2`, but now you can easily apply the same logic for `overfit_batches=1`
As you can see, **val_loss != train_loss**
Why? because the model gets updated!

**Comment by noamzilo** [comment]
Thanks! Before diving into this and applying myself for overfit_batches=1, please state also when the print to progress bar does happen (it should happen at least 2 times if I understand, once at the end of each {}_epoch_end), [once prededed by `Validating: 0it [00:00, ?it/s`]

**Comment by awaelchli** [comment]
```python
import os

import torch
from torch.utils.data import Dataset

from pytorch_lightning import LightningModule, Trainer, seed_everything


class RandomDataset(Dataset):

    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):

    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def loss(self, batch, prediction):
        # An arbitrary loss to have a loss that updates the model weights during `Trainer.fit` calls
        return torch.nn.functional.mse_loss(prediction, torch.ones_like(prediction))

    def step(self, x):
        x = self.layer(x)
        out = torch.nn.functional.mse_loss(x, torch.ones_like(x))
        return out

    def training_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"loss": loss}

    def training_step_end(self, training_step_outputs):
        return training_step_outputs

    def training_epoch_end(self, outputs) -> None:
        torch.stack([x["loss"] for x in outputs]).mean()

    def validation_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"x": loss}

    def validation_epoch_end(self, outputs) -> None:
        torch.stack([x['x'] for x in outputs]).mean()

    def test_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"y": loss}

    def test_epoch_end(self, outputs) -> None:
        torch.stack([x["y"] for x in outputs]).mean()

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1)
        return [optimizer], [lr_scheduler]


def test_train_val_logging_at_same_epoch():
    class TestModel(BoringModel):
        def training_step(self, batch, batch_idx):
            output = self.layer(batch)
            loss = self.loss(batch, output)
            self.log("train_loss", loss, prog_bar=True, on_step=False, on_epoch=True)
            return {"loss": loss, "train_loss_manual": loss}

        def validation_step(self, batch, batch_idx):
            output = self.layer(batch)
            loss = self.loss(batch, output)
            self.log("val_loss", loss, prog_bar=True, on_step=False, on_epoch=True)
            return {"x": loss, "val_loss_manual": loss}

        def training_epoch_end(self, outputs):
            print("\n\ntrain_loss_manual", torch.stack([output["train_loss_manual"] for output in outputs]).mean().item())

        def validation_epoch_end(self, outputs):
            print("\n\nval_loss_manual", torch.stack([output["val_loss_manual"] for output in outputs]).mean().item())


    train_data = torch.utils.data.DataLoader(RandomDataset(32, 64))
    val_data = torch.utils.data.DataLoader(RandomDataset(32, 64))

    model = TestModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        max_epochs=5,
        overfit_batches=1,
        weights_summary=None,
        num_sanity_val_steps=0,
    )
    trainer.fit(model, train_data, val_data)


if __name__ == '__main__':
    seed_everything(100)
    test_train_val_logging_at_same_epoch()

```


```
Epoch 0:  50%|█████     | 1/2 [00:00<00:00, 333.28it/s, loss=0.12, v_num=5]

train_loss_manual 0.1203126609325409

Validating: 0it [00:00, ?it/s]
Validating:   0%|          | 0/1 [00:00<?, ?it/s]

val_loss_manual 1.1519145965576172
Epoch 0: 100%|██████████| 2/2 [00:00<00:00, 333.29it/s, loss=0.12, v_num=5, train_loss=0.120, val_loss=1.150]
Epoch 1:  50%|█████     | 1/2 [00:00<00:00, 499.92it/s, loss=0.636, v_num=5, train_loss=0.120, val_loss=1.150]

train_loss_manual 1.1519145965576172

Validating: 0it [00:00, ?it/s]
Validating:   0%|          | 0/1 [00:00<?, ?it/s]

val_loss_manual 0.40176457166671753
Epoch 1: 100%|██████████| 2/2 [00:00<00:00, 499.98it/s, loss=0.636, v_num=5, train_loss=1.150, val_loss=0.402]
Epoch 2:  50%|█████     | 1/2 [00:00<00:00, 499.62it/s, loss=0.558, v_num=5, train_loss=1.150, val_loss=0.402]

train_loss_manual 0.40176457166671753

Validating: 0it [00:00, ?it/s]
Validating:   0%|          | 0/1 [00:00<?, ?it/s]

val_loss_manual 0.3695394992828369
Epoch 2: 100%|██████████| 2/2 [00:00<00:00, 499.89it/s, loss=0.558, v_num=5, train_loss=0.402, val_loss=0.370]
Epoch 3:  50%|█████     | 1/2 [00:00<00:00, 499.56it/s, loss=0.511, v_num=5, train_loss=0.402, val_loss=0.370]

train_loss_manual 0.3695394992828369

Validating: 0it [00:00, ?it/s]
Validating:   0%|          | 0/1 [00:00<?, ?it/s]

val_loss_manual 0.36651962995529175
Epoch 3: 100%|██████████| 2/2 [00:00<00:00, 500.33it/s, loss=0.511, v_num=5, train_loss=0.370, val_loss=0.367]
Epoch 4:  50%|█████     | 1/2 [00:00<00:00, 500.16it/s, loss=0.482, v_num=5, train_loss=0.370, val_loss=0.367]

train_loss_manual 0.36651962995529175

Validating: 0it [00:00, ?it/s]
Validating:   0%|          | 0/1 [00:00<?, ?it/s]

val_loss_manual 0.36621975898742676
Epoch 4: 100%|██████████| 2/2 [00:00<00:00, 499.98it/s, loss=0.482, v_num=5, train_loss=0.367, val_loss=0.366]
Epoch 4: 100%|██████████| 2/2 [00:00<00:00, 333.38it/s, loss=0.482, v_num=5, train_loss=0.367, val_loss=0.366]
```

**Comment by winshot-thu** [comment]
Hi @noamzilo 
It's nice to meet someone who has the same problem.
![image](https://user-images.githubusercontent.com/100033782/187037788-3b9d3678-7bf6-415c-a02d-3c4b3665681c.png)
Only the first batch loss before function *def training_step_end* returned is equal loss in log.
Do you know the reason now?

**Comment by evileleven** [comment]
I have the similar issue. And I could not plot 'val_loss' on prog_bar, whether the parameter in self.log I set.

Sanity Checking DataLoader 0: 100%|██████████| 2/2 [00:00<00:00, 26.29it/s]
valid_loss_manual tensor(0.7617, device='cuda:0')
Epoch 0:   0%|          | 0/10 [00:00<?, ?it/s] in train loop
Epoch 0:  10%|█         | 1/10 [00:00<00:00, 16.29it/s, v_num=216, train_loss_step=0.990]in train loop
Epoch 0:  20%|██        | 2/10 [00:00<00:00, 28.01it/s, v_num=216, train_loss_step=1.030]in train loop
Epoch 0:  30%|███       | 3/10 [00:00<00:00, 35.40it/s, v_num=216, train_loss_step=1.350]in train loop
Epoch 0:  40%|████      | 4/10 [00:00<00:00, 42.62it/s, v_num=216, train_loss_step=1.240]in train loop
Epoch 0:  50%|█████     | 5/10 [00:00<00:00, 48.63it/s, v_num=216, train_loss_step=1.010]in train loop
Epoch 0:  60%|██████    | 6/10 [00:00<00:00, 53.57it/s, v_num=216, train_loss_step=1.170]in train loop
Epoch 0:  70%|███████   | 7/10 [00:00<00:00, 57.92it/s, v_num=216, train_loss_step=1.030]in train loop
Epoch 0:  80%|████████  | 8/10 [00:00<00:00, 61.66it/s, v_num=216, train_loss_step=0.816]in train loop
Epoch 0:  90%|█████████ | 9/10 [00:00<00:00, 64.93it/s, v_num=216, train_loss_step=0.860]in train loop
Epoch 0: 100%|██████████| 10/10 [00:00<00:00, 68.76it/s, v_num=216, train_loss_step=0.364]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation:   0%|          | 0/3 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/3 [00:00<?, ?it/s]
Validation DataLoader 0:  33%|███▎      | 1/3 [00:00<00:00, 361.67it/s]
Validation DataLoader 0:  67%|██████▋   | 2/3 [00:00<00:00, 229.90it/s]
Validation DataLoader 0: 100%|██████████| 3/3 [00:00<00:00, 238.05it/s]
valid_loss_manual tensor(0.9070, device='cuda:0')
Epoch 0: 100%|██████████| 10/10 [00:00<00:00, 57.81it/s, v_num=216, train_loss_step=0.364, val_loss=0.807, train_loss_epoch=1.050]Backend TkAgg is interactive backend. Turning interactive mode on.
train_loss_manual tensor(0.9872, device='cuda:0', grad_fn=<MeanBackward0>)
Epoch 1:   0%|          | 0/10 [00:00<?, ?it/s, v_num=216, train_loss_step=0.364, val_loss=0.807, train_loss_epoch=1.050]in train loop
Epoch 1:  10%|█         | 1/10 [00:00<00:00, 92.63it/s, v_num=216, train_loss_step=0.981, val_loss=0.807, train_loss_epoch=1.050]in train loop
Epoch 1:  20%|██        | 2/10 [00:00<00:00, 99.80it/s, v_num=216, train_loss_step=1.020, val_loss=0.807, train_loss_epoch=1.050] in train loop
Epoch 1:  30%|███       | 3/10 [00:00<00:00, 102.73it/s, v_num=216, train_loss_step=1.360, val_loss=0.807, train_loss_epoch=1.050]in train loop
Epoch 1:  40%|████      | 4/10 [00:00<00:00, 104.27it/s, v_num=216, train_loss_step=1.220, val_loss=0.807, train_loss_epoch=1.050]in train loop
Epoch 1:  50%|█████     | 5/10 [00:00<00:00, 105.19it/s, v_num=216, train_loss_step=1.010, val_loss=0.807, train_loss_epoch=1.050]in train loop
Epoch 1:  60%|██████    | 6/10 [00:00<00:00, 105.83it/s, v_num=216, train_loss_step=1.170, val_loss=0.807, train_loss_epoch=1.050]in train loop
Epoch 1:  70%|███████   | 7/10 [00:00<00:00, 106.32it/s, v_num=216, train_loss_step=1.030, val_loss=0.807, train_loss_epoch=1.050]in train loop
Epoch 1:  80%|████████  | 8/10 [00:00<00:00, 106.65it/s, v_num=216, train_loss_step=0.816, val_loss=0.807, train_loss_epoch=1.050]in train loop
Epoch 1:  90%|█████████ | 9/10 [00:00<00:00, 106.98it/s, v_num=216, train_loss_step=0.863, val_loss=0.807, train_loss_epoch=1.050]in train loop
Epoch 1: 100%|██████████| 10/10 [00:00<00:00, 110.17it/s, v_num=216, train_loss_step=0.355, val_loss=0.807, train_loss_epoch=1.050]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation:   0%|          | 0/3 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/3 [00:00<?, ?it/s]
Validation DataLoader 0:  33%|███▎      | 1/3 [00:00<00:00, 367.15it/s]
Validation DataLoader 0:  67%|██████▋   | 2/3 [00:00<00:00, 233.48it/s]
Validation DataLoader 0: 100%|██████████| 3/3 [00:00<00:00, 239.71it/s]
valid_loss_manual tensor(0.9029, device='cuda:0')
Epoch 1: 100%|██████████| 10/10 [00:00<00:00, 85.93it/s, v_num=216, train_loss_step=0.355, val_loss=0.806, train_loss_epoch=1.050]
