### ISSUE TITLE
Completely overwrite validation/test block (including the batch-level loop)

### ISSUE THREAD

**Issue by Cuberick-Orion** [PyTorchLightning/pytorch-lightning#5827]
### Motivation

In certain cases, for example, **an image+text multimodal retrieval model**, the training and validation/testing logic can be very different. Specifically:
* In training, for each input query, we construct the corresponding batches by sampling randomly from the dataset;
* In validation/testing, for each input query, we need to loop through *all* candidates within the dataset

I'll be happy to go into the details, but in short, for these use cases, we often need a COMPLETELY different pipeline for validation/testing, which doesn't necessarily fit into the 'loop' as we would use in typical training scenarios.

### Pitch

I would propose to have a higher-level function that could:
* Overwrite the entire validation/testing logic, *including* the batch-level loop - basically, redefines the validation/testing behaviors
* Have full control over what elements go to what device (i.e., manually define `.cuda()` or `.cpu()` - this is because, for retrieval-type tasks, it is highly impractical to stuff everything in VRAM at the same time, chances are we need to take things in and out of GPUs.

**Comment by carmocca** [comment]
> In validation/testing, for each input query, we need to loop through all candidates within the dataset

Are you talking about looping in your validation_step (for each batch) over a whole dataset? You should be able to do this today.

> Overwrite the entire validation/testing logic, including the batch-level loop - basically, redefines the validation/testing behaviors

I agree this would be a cool thing to allow. But that requires a large refactor on the internals as of today. Hopefully we can allow it soon.

> Have full control over what elements go to what device 

You can manually set your devices already where appropriate.

**Comment by Cuberick-Orion** [comment]
Thanks for the reply.

To go into details on the validation process, I will be taking the retrieval task as an example:
* Task definition: 
  * `input_query` (image and/or text) is to be matched with a `candidate` (image) within a large corpus
* The data flow in validation:
  * `input_query -> feature extraction (module_0) -> feature vectors (size: N x num_hid)` Do this for N input samples;
  * `candidate -> feature extraction (module_1) -> feature (size: M x num_hid)` Do this for M candidate images;
  * Then, compute similarity of features through e.g., l2-norm. Generate a similarity matrix of size `N x M`
  * Identify the most similar candidate for each input (operate on each row)

Imagine that the size of the inputs and candidates (N and M) are quite large- which is usually the case, we can't really fit this pipeline into the de-facto "loop" of validations. Chances are, we need to take over the loop and redesign something else, for example:
* process `input_query` in batches and save all features to `cpu()`
* process `candidate` in batches and save them to `cpu()`
* perform the necessary comparison on `cpu()`

I understand we can manually designate the device now (just again to point out that these things can be quite large), but for the former two steps, it could be tricky to realize as of this moment.

My workaround currently is to create two dataloaders in validation (corresponding to the two steps) and collect all processed features in `val_epoch_end`, but it is a bit complicated. The more straightforward way is to just bypass the pre-defined validation loop and create my own validation function, which receives the `val_dataloader` and `model` and do the things I want.

All in all, what I am trying to say is - the case where users need to (prefer to) define their own validation functions is not unreasonable or unheard of, and perhaps it would be better if lightning allows us to do so. Thanks.

**Comment by carmocca** [comment]
> All in all, what I am trying to say is - the case where users need to (prefer to) define their own validation functions is not unreasonable or unheard of, and perhaps it would be better if lightning allows us to do so.

I hear you. We'd like to eventually refactor the loops so users can do this sort of modification more easily.

Closing this for the moment. Thanks for your proposal ❤️
