### ISSUE TITLE
Must manually import `comet_ml` before `CometLogger` to avoid import error

### ISSUE THREAD

**Issue by nathanpainchaud** [PyTorchLightning/pytorch-lightning#5829]
## 🐛 Bug
A few weeks ago, a [refactoring of logger imports](https://github.com/PyTorchLightning/pytorch-lightning/commit/ec0fb7a3ec709699243c76dae04ee1e4ce2406a0#diff-7a041199139ffcca72689f9a15f47657330ff9d3206a46103e7a061a5fe2bc09) changed the ordering of imports for the `CometLogger`. However, comet requires for `comet_ml` to be imported before some other dependencies, i.e. torch and tensorboard, to work properly. If not, you get the following error:
```
ImportError: You must import Comet before these modules: torch, tensorboard
```

Before the imports reordering, comet's import requirements could be met by importing `CometLogger` before torch and tensorboard. However, since the refactoring, torch is now imported before comet in `loggers/comet.py` itself. This forces users to manually add an unused import for `comet_ml` before importing `CometLogger` to avoid the above `ImportError`.

### To Reproduce
This [**BoringModel**](https://colab.research.google.com/drive/1u7vE02v40RCebEXg1515KMuCxvelAcNF?usp=sharing) example reproduces the `ImportError`.

### Expected behavior
Users should not have to manually import `comet_ml` before `CometLogger` to avoid triggering the `ImportError`. The `comet_ml` import inside `loggers/comet.py` should exceptionally come before the `torch` import, even if it violates usual import ordering.

**Comment by edenlightning** [comment]
Thanks for the report! Mind sending a PR to fix this?

**Comment by edenlightning** [comment]
cc @Borda

**Comment by nathanpainchaud** [comment]
Sorry for the long delay in getting back to you on this issue. I tried to fix it by manually rearranging the imports, with the relevant annotations so that this manual placement would be ignored by `isort`. However, I can't seem to be able to make it work like it used to.

In the end, I think it might be better to solve this issue elsewhere for me, either in my own code or upstream with Comet to see if they can improve on their requirement of being imported first.

**Comment by awaelchli** [comment]
Seems like a pain to solve this.
@nathanpainchaud You can set a env variable `COMET_DISABLE_AUTO_LOGGING=1`, not sure how much it helps or what side effects it has. 
Just saw it in the docs [here](https://www.comet.ml/docs/python-sdk/warnings-errors/).

**Comment by nathanpainchaud** [comment]
@awaelchli Thanks for the link! I've not yet tried to disable Comet auto-logging, since I'm a bit fearful about the logging capabilities I might lose.

I first created the issue here because I thought it might be solved easily by simply reordering the imports in Lightning, but I'm fully aware that would only cover up the symptoms, and not treat the underlying issue. I think the best solution, even if it's ugly IMO, is to manually import Comet at the very beginning of my main script.

A more permanent resolution to the issue, if possible, should come from upstream. Therefore, I'm closing the issue here, but if anyone as a better idea on how to resolve this issue, they're welcome to re-open it :slightly_smiling_face:

**Comment by Queuecumber** [comment]
So I have something to add to this which is very strange. I usually run my experiments on a slurm cluster, I just found that when I launch through sbatch I don't get this error, but when I use srun to get a terminal on a node to do some debugging I do get the error. I have no idea why they would be different.
