### ISSUE TITLE
move_metrics_to_cpu works non-recursively

### ISSUE THREAD

**Issue by roytseng-tw** [PyTorchLightning/pytorch-lightning#5831]
## 🐛 Bug

https://github.com/PyTorchLightning/pytorch-lightning/blob/0b7f5a88a0f4691ec228c4708295a10d403fd592/pytorch_lightning/utilities/memory.py#L20-L46

`to_cpu` value should be passed to recursive calls.
```python
if isinstance(v, dict): 
    out_dict.update({k: recursive_detach(v, to_cpu=to_cpu)}) 
```

### Expected behavior

Should recursively detach (yes) and move tensors to cpu (bugged QQ).

### Environment

You can get the script and run it with:

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by carmocca** [comment]
Good catch! Do you want to open a PR with the fix?
