### ISSUE TITLE
Multigpu with different RAM capabilities

### ISSUE THREAD

**Issue by lbugnon** [PyTorchLightning/pytorch-lightning#5847]
I couldn't find a way to use more than one gpu that have different RAM capabilities (it fails when the smallest GPU reach it's capacity). Is there a way to solve this?
Thanks!

**Comment by carmocca** [comment]
This is a limitation of PyTorch. The only solution would be to manually map parts of your model to devices so the number of parameters fits your particular GPU setup.

See this issue for automatically doing this: https://github.com/PyTorchLightning/pytorch-lightning/issues/50

Closing. Feel free to re-open if you need anything else!
