### ISSUE TITLE
Improve interface between Trainer and argparse

### ISSUE THREAD

**Issue by dreavjr** [PyTorchLightning/pytorch-lightning#5875]
## 🚀 Feature

Current Trainer.add_argparse_args(parser_param) creates a new ArgumentParser object, passing the parser_param object as a parent to the newly created parser. Trainer.add_argparse_args() returns the new ArgumentParser object to its caller.

An improved interface would simply add all arguments to parser_param without creating a new object. To maintain backwards compatibility with almost all existing code, Trainer.add_argparse_args() may simply return the parser_param object.

### Motivation

The current interface makes impossible using advanced argparse features like grouping and subparsing. Due to the huge number of parameters in Trainer, isolating them in a group (instead of leaving them intermixed with everything else) is a common use case.

### Pitch

A small change in `pytorch_lightning.utilities.argparse_utils.add_argparse_args`, essentially removing the one line that creates a new ArgparseParser object:
```
parser = ArgumentParser(parents=[parent_parser], add_help=False,)
```

### Alternatives

The only alternatives I could think of are horrible: 

1. Clients subclassing Trainer and overriding add_argparse_args (breaking abstraction);
2. Clients calling Trainer.add_argparse_args with a clean parser and using protected members of ArgparseParser to copy the arguments onto a group or subparser of the actual parser (breaking abstraction in an even worse way).

**Comment by carmocca** [comment]
Duplicate of https://github.com/PyTorchLightning/pytorch-lightning/issues/3076 (requires the same fix)

Note that we plan to migrate our argparse functionalities to use https://github.com/PyTorchLightning/pytorch-lightning/pull/4492. Please have a look to see if it fits your use case!

**Comment by dreavjr** [comment]
Sorry about the duplication — somehow I missed that issue in my searches.

Yep, the #4492 PR would make those questions moot.  It looks amazing! :-)
