### ISSUE TITLE
MlflowLogger fail when logging long parameters

### ISSUE THREAD

**Issue by ducthienbui97** [PyTorchLightning/pytorch-lightning#5892]
### To Reproduce

Log anything  parameters longer than 250 characters

### Expected behavior

MlflowLogger not sending parameters longer than 250 characters to mlflow and log warning to user

### Environment

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux): 
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

### Additional context

Mlflow only allow paramters to be at most 500 bytes (250 unicode characters), their limit in database is 250 characters:
https://www.mlflow.org/docs/latest/rest-api.html#log-param
https://github.com/mlflow/mlflow/issues/1976
https://github.com/mlflow/mlflow/issues/3931

**Comment by tchaton** [comment]
Dear @ducthienbui97,

Thanks for opening a PR.

Best,
T.C
