### ISSUE TITLE
Access dataset directly in validation_epoch_end

### ISSUE THREAD

**Issue by Cuberick-Orion** [PyTorchLightning/pytorch-lightning#5896]
### Motivation / Pitch

Not sure if duplicated but:

I would propose to allow users to add additional arguments to be passed into functions such as `validation_epoch_end()`. 

One of the examples being: during validation, we might need to fetch some additional information from the dataset (e.g., `len(dataset)`), and currently it is a bit hard to achieve without passing the dataset into the model during `init`.

**Comment by awaelchli** [comment]
the datasets/dataloaders are available already, because they are attached to the trainer. 
Example:
```python
val_dataloader = self.trainer.val_dataloaders[0]  # one or multiple
val_dataset = val_dataloader.dataset
print(len(val_dataset))
```

**Comment by Cuberick-Orion** [comment]
Thanks for the tip! I am closing this issue.
