### ISSUE TITLE
Auto_scale_batch_size fails for to bigger batch sizes, cuDNN failure

### ISSUE THREAD

**Issue by FlorianMF** [PyTorchLightning/pytorch-lightning#5897]
## 🐛 Bug

I'm using a pre-trained ResNet50 on 224x224 images with 16-bit precision, I wanted to test the auto_scale_batch_size functionality.

The output in the terminal is the following:
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Using native 16bit precision.
Batch size 2 succeeded, trying batch size 4
Batch size 4 succeeded, trying batch size 8
Batch size 8 succeeded, trying batch size 16
Batch size 16 succeeded, trying batch size 32
Batch size 32 succeeded, trying batch size 64
Batch size 64 succeeded, trying batch size 128
Batch size 128 succeeded, trying batch size 256

All good till then. On batch size 256 the GPU's memory certainly is not sufficient and it fails on a 2d convolution.
The auto_scaling should be aborted at this point and the batch_size fixed to 128.
Instead the script fails with the message "RuntimeError: Unable to find a valid cuDNN algorithm to run convolution".

### To Reproduce
I'm not doing anything exceptional:
1. Parsing arguments with "--auto_scale_batch_size", "true"
2. Initiating model, datamodule and trainer using the parsed arguments
3. trainer.tune(model, dm)

### Question
Is this a problem on the Pytorch Lightning side not capturing the exception or is this anyhow linked to Cuda and installing a different version could be enough?

### Environment
1x GeForce RTX 2080Ti
Ubuntu 20.10
Python 3.8.5
Pytorch Lightning 1.1.8
Pytorch 1.7.1
Cuda 11.2
Env created with miniconda, packages installed with pip

**Comment by justusschock** [comment]
Hi @FlorianMF,

Have you tried to run that network with batchsize 256 without the auto_scaling? Because we don't do anything special on the convolutional side and this seems to be a bug in PyTorch.

**Comment by FlorianMF** [comment]
Hi @justusschock, 
I get the same error without auto_scaling for a batch_size=256, as well when adding 'torch.backends.cudnn.benchmark = True' at the top of the script.
When adding "torch.backends.cudnn.enabled = False" the error message "RuntimeError: CUDA out of memory" confirms my assumption.

So, am I 'forced' to use 'auto_scale_batch_size' once to get the maximum batch size and then rerun the script without the flag? I think your goal proposing this functionality is that this is not needed though.

**Comment by FlorianMF** [comment]
You're right. The error is captured when 'torch.backends.cudnn.benchmark = True' is added at the top and the script continues.

**Comment by FlorianMF** [comment]
Nonetheless, if the returned error's message is 'CUDA error: out of memory' its not captured because the function 'is_cuda_out_of_memory' in pytorch_lightning/utilities/memory.py checks for the message 'CUDA out of memory'

**Comment by tchaton** [comment]
Hey @FlorianMF,

Closing this issue as it seems resolved.

Best,
T.C
