### ISSUE TITLE
Calling fit mutiple times fails to call teardown

### ISSUE THREAD

**Issue by JonasFrey96** [PyTorchLightning/pytorch-lightning#5903]
## Please reproduce using the BoringModel

If your create a new teacher instance everything works great but if you dont it fails. 
Here is the colab to reproduce the error:
https://colab.research.google.com/drive/1G6korxcAO12wXLwhCMxTHkG3-bjMnfsc?usp=sharing

 - PyTorch Version (e.g., 1.0): 1.7
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): 
 - Python version: 3.7.6
 - CUDA/cuDNN version: CUDA 10.2 Driver Version: 440.100  
 - GPU models and configuration: 2080Ti and 1080Ti also 4x2080Ti DDP

**Comment by tchaton** [comment]
Dear @JonasFrey96,

After checking your notebook, it seems to me to be an expected behaviour.

Every time you call `trainer.fit(...)`, it should call `on_train_epch` and `teardown`.

@Borda Do you confirm ?

Best,
T.C

**Comment by awaelchli** [comment]
@JonasFrey96 I believe your observations are incorrect. 
This notebook incorrectly counts the times on_train_end is called. 
First of all, you increment the counter after you print the message how many times it was called so far.
Second, you never reset the counter, so naturally calling fit multiple times will just keep increasing the counter.

After I fix these two problem, your code prints `ON Trained end is called 1` which is the expected count.
