### ISSUE TITLE
BaseFinetuning Callback freeze_before_training is never called

### ISSUE THREAD

**Issue by agamemnonc** [PyTorchLightning/pytorch-lightning#5906]
## 🐛 Bug

I think there might be a bug in the implementation of the `BaseFinetuning` callback, and in particular in the following lines:
https://github.com/PyTorchLightning/pytorch-lightning/blob/a028171f26d781491fa87fd27adf0e6dc1d7c3ae/pytorch_lightning/callbacks/finetuning.py#L236-L237

`freeze_before_training` is meant to be over-riden by child classes so that the freezing logic is implemented before the start of training. However, the call to this method happens using the `on_before_accelerator_backend_setup` hook. I am not sure where this hook has come from as I was unable to find it in the `latest` version of the [documentation](https://pytorch-lightning.readthedocs.io/en/latest/callbacks.html#available-callback-hooks):

Testing the callback using the `MilestonesFinetuningCallback` from the related [example](https://github.com/PyTorchLightning/pytorch-lightning/blob/a028171f26d781491fa87fd27adf0e6dc1d7c3ae/pl_examples/domain_templates/computer_vision_fine_tuning.py#L65) resulted in the layers not being freezed before training. 

To make this work, I had to change the callback hook that `freeze_before_training` is called to `on_pretrain_routine_start`.

Apologies I wasn't able to provide a piece of code to reproduce this issue.

**On a separate note**, the `MilestonesFinetuningCallback` in the example uses wrong signatures:
https://github.com/PyTorchLightning/pytorch-lightning/blob/a028171f26d781491fa87fd27adf0e6dc1d7c3ae/pl_examples/domain_templates/computer_vision_fine_tuning.py#L72
here `module` should be `modules` to match the signature of the `freeze` method of the parent class:
https://github.com/PyTorchLightning/pytorch-lightning/blob/a028171f26d781491fa87fd27adf0e6dc1d7c3ae/pytorch_lightning/callbacks/finetuning.py#L147

Same applies to `unfreeze_and_add_param_group`:
https://github.com/PyTorchLightning/pytorch-lightning/blob/a028171f26d781491fa87fd27adf0e6dc1d7c3ae/pl_examples/domain_templates/computer_vision_fine_tuning.py#L77-L79
and
https://github.com/PyTorchLightning/pytorch-lightning/blob/a028171f26d781491fa87fd27adf0e6dc1d7c3ae/pl_examples/domain_templates/computer_vision_fine_tuning.py#L83-L84
Compare to:
https://github.com/PyTorchLightning/pytorch-lightning/blob/a028171f26d781491fa87fd27adf0e6dc1d7c3ae/pytorch_lightning/callbacks/finetuning.py#L197-L198

## Please reproduce using the BoringModel

Bug is in branch `release/1.2-dev` so I wouldn't be able to reproduce using  `pip` installation.

## Environment

 - PyTorch Version (e.g., 1.0): 1.6.0+cu101
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration:  4 X GeForce GTX 1080 Ti
 - Any other relevant information:

### Additional context

Happy to submit a PR to fix these issues.

**Comment by tchaton** [comment]
Dear @agamemnonc,

Thanks from finding the typos :)

I just tried the script again and it seems to have the correct behaviour.
When setting `train_bn` to `False` in MilestonesFinetuningCallback, I get only 6 params corresponding to the weight/ bias on the 3 Linear in `_fc_layers`.

Best,
T.C
