### ISSUE TITLE
Use Semantic Versioning

### ISSUE THREAD

**Issue by ajtritt** [PyTorchLightning/pytorch-lightning#5928]
## 🚀 Feature
Use [Semantic Versioning](https://semver.org/) when cutting releases.

### Motivation

Provide meaning to version strings that users can rely on when doing things like updating and managing pytorch_lightning as a dependency

### Pitch

Semantic Versioning provides a formal definition to the components of version strings. Changes to major, minor, and patch all have well-defined meanings. I've noticed a change that break backward compatibility with the release of version . This break was not indicated with a major version bump. 

### Alternatives

Keep using the current logic for determining version bumps and provide documentation on that logic. 

### Additional context

The one example I can come up with is the movement of `pytorch_lightning.cluster_environments` to `pytorch_lightning.plugins.environments`. I haven't followed development enough to know if there are other things that break backward compatibility, but here are some more details on this particular issue:

- 1.0.0 was cut from cdbddbe99f5b77e253eb627edf98c3159add9583. You can see `pytorch_lightning.cluster_environments` exists [here](https://github.com/PyTorchLightning/pytorch-lightning/tree/cdbddbe99f5b77e253eb627edf98c3159add9583/pytorch_lightning/cluster_environments) 
- Commit b3ebc18bcb0b4034fdfbc90fc3d79c9786cb59c1 moves the subpackage to `pytorch_lightning.plugins.environments`
- Following this, 1.1.7 was cut from 90a813fe96c5fdbf7c515cb7f356bedfe0bd5098. At this point, backward compatibility is broken w.r.t. the package containing ClusterEnvironments

**Comment by Borda** [comment]
@ajtritt so far I know we are following semantic versioning and keeping back-compatibility for 0.2 (2 feature releases)
the case you are mentioning is about internal features which we have not expected anyone would be using (we have been refactoring all accelerator and plugin system) and the cut comes with the transition from 1.1.x to 1.2
cc: @tchaton @edenlightning

**Comment by ajtritt** [comment]
@Borda perhaps it was an issue with documentation then. I had followed an examples on how to extend PL for running in different environments where it referenced `pytorch_lightning.cluster_environments`. 

https://pytorch-lightning.readthedocs.io/en/1.0.0/trainer.html#plugins
https://pytorch-lightning.readthedocs.io/en/stable/accelerators.html#example-1-arbitrary-hpc-cluster

**Comment by Borda** [comment]
yes, but pls note that the last 1.1.8 was the last in 0.1 series and the next will be 1.2, for that reason we have made a branch switch and the actual master contains 1.2 features...

**Comment by tchaton** [comment]
Dear @ajtritt @Borda,

Any update on this issue ?

Best,
T.C

**Comment by carmocca** [comment]
> * Commit [b3ebc18](https://github.com/PyTorchLightning/pytorch-lightning/commit/b3ebc18bcb0b4034fdfbc90fc3d79c9786cb59c1) moves the subpackage to `pytorch_lightning.plugins.environments`
> * Following this, 1.1.7 was cut from [90a813f](https://github.com/PyTorchLightning/pytorch-lightning/commit/90a813fe96c5fdbf7c515cb7f356bedfe0bd5098). At this point, backward compatibility is broken w.r.t. the package containing ClusterEnvironments

This is not correct, cluster_environments has not been moved in 1.1.8 (or lower), see:

https://github.com/PyTorchLightning/pytorch-lightning/tree/1.1.8/pytorch_lightning/cluster_environments

However, it has in 1.2.0rc1. see:

https://github.com/PyTorchLightning/pytorch-lightning/tree/1.2.0rc1/pytorch_lightning/plugins/environments

Keep in mind we don't follow strict SemVer as we (can) break compatibility after a MINOR version increase.
