### ISSUE TITLE
ModelCheckpoint doesn't delete checkpoints from s3 storage using Tensorboard Logger

### ISSUE THREAD

**Issue by umbertopietroni** [PyTorchLightning/pytorch-lightning#5935]
## 🐛 Bug

When using ModelCheckpoint with TensorboardLogger with a S3 bucket url path the models checkpoints are correclty uploaded into the cloud directory set by the logger but but past epochs versions are not deleted. If, instead, I use directly the ModelCheckpoint with `dirpath=<s3-url>` while saving tensorboard logs locally, then the checkpoints are both uploaded and deleted correctly on my s3 bucket.

### Expected behavior

ModelCheckpoint should delete past checkpoints on cloud storage also when using the TensorboardLogger

### Environment

 - PyTorch Version: 1.7.1
 - OS: Ubuntu 20.04
 - Python version: 3.8

**Comment by umbertopietroni** [comment]
At the moment I'm using this workaround and the ModelCheckpoint correctly deletes old checkpoints from the s3 bucket

```
        # tb_logs =  os.path.join("s3://", <s3_bucket>, <model_dir>) 
        logger = TensorBoardLogger(tb_logs, name=tb_name)


        # workaround to delete old checkpoints
        version = (
            logger.version
            if isinstance(logger.version, str)
            else f"version_{logger.version}"
        )
        dir_path = os.path.join(
            str(logger.save_dir), str(logger.name), version, "checkpoints"
        )

        self.checkpoint_callback = ModelCheckpoint(
            dirpath=dir_path,
            monitor=monitor,
            mode=mode,
            save_last=save_last,
            save_top_k=save_top_k,
            verbose=verbose,
        )

```

Otherwise, If I leave dir_path = None then I have the issue

**Comment by tchaton** [comment]
Dear @umbertopietroni,

Would you like make a fix PR ?

Best,
T.C

**Comment by kpoeppel** [comment]
I would also be interested in a solution to this, as I cannot use the workaround right away with multiple loggers.
