### ISSUE TITLE
The header link is broken

### ISSUE THREAD

**Issue by MasaYan24** [PyTorchLightning/pytorch-lightning#5955]
The link below is broken:
[pytorch-lightning page] -> header menu (・・・) → Get Started

Currently:
https://pytorch-lightning.readthedocs.io/en/latest/introduction_guide.html

Fix:
https://pytorch-lightning.readthedocs.io/en/latest/starter/introduction_guide.html

**Comment by SkafteNicki** [comment]
Closed by #5960.
