### ISSUE TITLE
Training loop get filled with unwanted logs.

### ISSUE THREAD

**Issue by shamanez** [PyTorchLightning/pytorch-lightning#5962]
## 🐛 Bug
During the training process, there are lots of unwanted logs printing about different function runtimes. I am using the latest pytorch_lightning version.

![image](https://user-images.githubusercontent.com/16892570/107860581-d0b2c200-6ea4-11eb-9cdf-f547b17bfba8.png)

**Comment by awaelchli** [comment]
Looks like the profiler is turned on. 
Can you post the code that reproduces this?
The instructions are in the report template.

**Comment by shamanez** [comment]
Is there way to turn off the profile?

**Comment by shamanez** [comment]
Is there a way to turn off the profile?

I am using this  [huggiface code](https://github.com/huggingface/transformers/blob/master/examples/research_projects/rag/lightning_base.py#L339)

**Comment by awaelchli** [comment]
It should be turned off by default
https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html#profiler

**Comment by awaelchli** [comment]
what are the inputs to generic_train? make sure the profiler is not passed in.

**Comment by shamanez** [comment]
works! Thanks!
