### ISSUE TITLE
Add ipython kernel detection and give warning when accelerator = "ddp"

### ISSUE THREAD

**Issue by ifsheldon** [PyTorchLightning/pytorch-lightning#5966]
## 🚀 Feature

Add ipython kernel detection and give warning when accelerator = "ddp"
### Motivation
When users try to use `ddp` as accelerator in Jupyter Notebook or Jupyter Lab, the trainer will be stuck forever and no hints about the cause. So, to better inform developers, it will be great to detect whether the code is run in a ipython kernel.

### Pitch

When users initialize a trainer by `Trainer(accelerator = 'ddp')` in a ipython kernel, give a warning or exception. Something like "ddp will not work in ipython kernel" should suffice.

### Additional context
Please see [this](https://github.com/ipython/ipython/issues/11694#issuecomment-485802013) to implement it. I can do a PR, but I am not sure if it is appropriate to place code for detection in `Trainer.__init__()`

**Comment by awaelchli** [comment]
The best place would be the accelerator connector where the ddp plugin gets selected. Happy to review the PR :)
