### ISSUE TITLE
Lightning throws "bypassing sigterm" on Slurm Cluster for unknown reason

### ISSUE THREAD

**Issue by vitusbenson** [PyTorchLightning/pytorch-lightning#5969]
## 🐛 Bug

I have a Python Script for training a model with DDP and multiple V100 GPUs. This works fine on development machines (DGX Station). When switching to SLURM cluster, Lightning detects Slurm and throws "bypassing sigterm" during the validation check iteration. As suggested in #5225 when deleting all variables from `os.environ` that belong to SLURM, the script works.

I am unsure if this is a Bug in my code, in Lightning or of the Slurm cluster I am running on. Any insight into possible reasons why Slurm is throwing the sigterms is greatly appreciated!

### Environment

 - PyTorch Version: 1.5
 - Lightning Version: 1.1.0
 - OS (e.g., Linux): Red Hat 7
 - How you installed PyTorch: conda
 - Python version: 3.7.7
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: 6x V100 32GB on IBM AC922

### Additional context

I know this is hard to reproduce.. But maybe somebody has an idea?

**Comment by tchaton** [comment]
Dear @vitusbenson,

Did you made any progress on this issue ?

Best,
T.C

**Comment by vitusbenson** [comment]
Dear @tchaton,

thanks for asking, so far I have not.

Cheers,
Vitus

**Comment by chengjiali** [comment]
I have the same error. Is it solved?

**Comment by koulakis** [comment]
I had the same issue, I was running on 4 gpus in a slurm cluster and got the error. In my case, the underlying issue was that I was using a wrong path for the training output. So somehow the original exception was never propagated and got the "bypassing sigterm" error instead.

**Comment by nicolebussola** [comment]
same here

**Comment by bhaktatejas922** [comment]
Same issue here

**Comment by YannDubs** [comment]
@nicolebussola @bhaktatejas922  @chengjiali  did you ever figure it out?

**Comment by hesic73** [comment]
Same issue.

**Comment by digantamisra98** [comment]
Same issue

**Comment by bhaktatejas922** [comment]
We still have the issue. I think it might have something to do with the dataloader? We avoid the issue now mostly by increasing the default time out on slurm to be 5 minutes. We start seeing weird behavior with training times in epox after the first one going up and up and up though. Really tough issue to pin down. Really have no idea what's happening

**Comment by bhaktatejas922** [comment]
I was thinking that using an in-memory data set like Nvidia dali would help. If anyone tries this please let me know

**Comment by yumengzhang1998** [comment]
Same issue here, has anyone figured out?

**Comment by navidivan** [comment]
same issue. If I forcefully stop the process, it corrupts my conda environment and it becomes unusable. does anyone experience the same thing?
