### ISSUE TITLE
module 'pytorch_lightning.metrics.classification' has no attribute 'AUROC'

### ISSUE THREAD

**Issue by Devesh2707** [PyTorchLightning/pytorch-lightning#6010]
## 🐛 Bug

module 'pytorch_lightning.metrics.classification' has no attribute 'AUROC' when I try to use pytorch_lightning.metrics.classification.AUROC

### To Reproduce

import pytorch_lightning as pl
auroc = pl.metrics.classification.AUROC()

-pytorch_lightning version == 1.1.8
![Screenshot_2021-02-16_19-56-41](https://user-images.githubusercontent.com/45910501/108076452-7165d500-7091-11eb-8b7d-4ccab9d00281.png)

### Additional context

Similarly AUC metric is also missing

**Comment by SkafteNicki** [comment]
Those two metrics will first be added in version 1.2 (released later today).
They can correctly be imported using master branch:
![path](https://user-images.githubusercontent.com/24896311/108084322-589af680-7074-11eb-94a6-8dfb4a3c99ee.PNG)

**Comment by Devesh2707** [comment]
Oh okay ! Thank You !
