### ISSUE TITLE
failing Docs build

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#604]
### Description
Not sure what is happening but it seems that the documentation fails... [![ReadTheDocs](https://readthedocs.org/projects/pytorch-lightning/badge/?version=latest)](https://pytorch-lightning.readthedocs.io/en/latest)
@williamFalcon could you pass details about documentation build?

**Comment by williamFalcon** [comment]
we no longer have the old docs... so the deployed version is out of sync and the build fails.

The solution is to get the new docs in place

**Comment by Borda** [comment]
What will be the new mapping of the top link/shortcuts in new docs?
```
  'github': 'https://github.com/williamFalcon/pytorch-lightning',
  'github_issues': 'https://github.com/williamFalcon/pytorch-lightning/issues',
  'contributing': 'https://github.com/williamFalcon/pytorch-lightning/blob/master/CONTRIBUTING.md',
  'docs': 'https://williamfalcon.github.io/pytorch-lightning/documentation.html',
  'twitter': 'https://twitter.com/PyTorchLightnin',
  'discuss': 'https://join.slack.com/t/pytorch-lightning/',
  'tutorials': 'https://williamfalcon.github.io/pytorch-lightning/examples.html',
  'previous_pytorch_versions': 'https://github.com/williamFalcon/pytorch-lightning/releases',
  'home': 'https://williamfalcon.github.io/pytorch-lightning/',
  'get_started': 'https://williamfalcon.github.io/pytorch-lightning/new-project.html',
  'features': 'https://williamfalcon.github.io/pytorch-lightning/',
  'blog': 'https://medium.com/@_willfalcon',
  'resources': 'https://williamfalcon.github.io/pytorch-lightning/',
  'support': 'https://williamfalcon.github.io/pytorch-lightning/',
```

**Comment by sneiman** [comment]
I assume you know that the docs cannot be fully used from the web site

**Comment by Borda** [comment]
@sneiman what do you mean?

**Comment by sneiman** [comment]
I cannot get to the documents online. If I go to:

https://github.com/PyTorchLightning/pytorch-lightning

and press the read the docs button, it attempts to go to

https://williamfalcon.github.io/pytorch-lightning/

and displays a 404 error. I can get to some of the examples and things through other paths, but nothing seems to get me to main docs.

**Comment by Borda** [comment]
@williamFalcon ^^
