### ISSUE TITLE
on_*_batch_transfer hooks should include a dataloader_index parameter

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#6058]
## 🚀 Feature

See title

### Motivation

Users might want to do different logic based on which dataloader produced the batch in particular, as different dataloaders might contain different batch structures

### Pitch

`def on_*_batch_transfer(batch, dataloader_idx)`

### Additional context

docs: https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_module.html#on-after-batch-transfer

cc: @SeanNaren @rohitgr7 @williamFalcon

**Comment by rohitgr7** [comment]
nice!
then we should add it to transfer_batch_to_device too since batch structure might be different in different data loaders?

**Comment by rohitgr7** [comment]
just a suggestion:
will it be good to make it a state? one can access it using `self.dataloader_idx`

pros:
- will make the training/val/test_step arguments/api consistent that will work in case of both with single dataloader or multiple with no code change required.

cons:
- might reduce the visibility to the user regarding the dataloader_idx argument.

**Comment by carmocca** [comment]
> will it be good to make it a state? one can access it using `self.dataloader_idx`

I personally prefer to have it as an argument, which is more functional. No strong feelings though

> * will make the training/val/test_step arguments/api consistent that will work in case of both with single dataloader or multiple with no code change required.

All these *_idx arguments across methods should be keyword arguments instead of positional. It's another refactor we should eventually do.

**Comment by rohitgr7** [comment]
I am thinking of having a `stage` parameter too here.. similar to one we have in `setup` since these hooks are common for train/val/test. But yeah, one can just use self.training/testing for that I guess.

**Comment by rohitgr7** [comment]
cc @PyTorchLightning/core-contributors
