### ISSUE TITLE
DeepSpeed hangs with iGPT

### ISSUE THREAD

**Issue by SeanNaren** [PyTorchLightning/pytorch-lightning#6064]
## 🐛 Bug

iGPT has caused issues with FairScale Sharded DDP before, so it's not a surprise DeepSpeed has some issues with running this model.

When training with ZeRO Optimization, DeepSpeed crashes:

```
RuntimeError: expected scalar type Float but found Half
    result = self.forward(*input, **kwargs)
  File "/home/sean/miniconda3/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 170, in forward
    return F.layer_norm(
  File "/home/sean/miniconda3/lib/python3.8/site-packages/torch/nn/functional.py", line 2202, in layer_norm
    result = self.forward(*input, **kwargs)
  File "/home/sean/miniconda3/lib/python3.8/site-packages/pl_bolts/models/vision/image_gpt/gpt2.py", line 23, in forward
    x = self.ln_1(x)
  File "/home/sean/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sean/miniconda3/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 170, in forward
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: expected scalar type Float but found Half
    return F.layer_norm(
  File "/home/sean/miniconda3/lib/python3.8/site-packages/torch/nn/functional.py", line 2202, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: expected scalar type Float but found Half
```

This is due to this line here:

https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/pl_bolts/models/vision/image_gpt/gpt2.py#L97

That doesn't take in the dtype or do a `type_as` conversion. We've managed to deal with this for now since when `precision=16` we use PyTorch Native AMP which converts arguments automatically, but in DeepSpeed they use a custom FP16_Optimizer for ZeRO which does not handle these conversions automatically. 

One fix for this would be for DeepSpeed to bring Native AMP support, and I'll make a ticket for this, but short term we can add a `type_as` conversion for lightning-bolts:

```
        sos = torch.ones(1, batch, self.hparams.embed_dim).type_as(x) * self.sos
```

However after remedying the above issue, the code hangs after a few iterations (I'm going to assume that this iteration may be where an optimizer step happens/takes place).

```
...
Epoch 0:   0%|▏                                                        | 14/3750 [00:03<15:59,  3.89it/s, loss=3.11, v_num=54]
[2021-02-18 13:31:07,760] [INFO] [stage2.py:1357:step] [deepscale] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 262144.0, reducing to 131072.0
[2021-02-18 13:31:07,760] [INFO] [stage2.py:1357:step] [deepscale] OVERFLOW! Rank 1 Skipping step. Attempted loss scale: 262144.0, reducing to 131072.0
[2021-02-18 13:31:07,760] [INFO] [stage2.py:1357:step] [deepscale] OVERFLOW! Rank 2 Skipping step. Attempted loss scale: 262144.0, reducing to 131072.0
[2021-02-18 13:31:07,760] [INFO] [stage2.py:1357:step] [deepscale] OVERFLOW! Rank 3 Skipping step. Attempted loss scale: 262144.0, reducing to 131072.0
Epoch 0:   0%|▏                                                        | 15/3750 [00:03<15:22,  4.05it/s, loss=3.11, v_num=54]
[2021-02-18 13:31:07,868] [INFO] [stage2.py:1357:step] [deepscale] OVERFLOW! Rank 1 Skipping step. Attempted loss scale: 131072.0, reducing to 65536.0
[2021-02-18 13:31:07,868] [INFO] [stage2.py:1357:step] [deepscale] OVERFLOW! Rank 2 Skipping step. Attempted loss scale: 131072.0, reducing to 65536.0
[2021-02-18 13:31:07,868] [INFO] [stage2.py:1357:step] [deepscale] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 131072.0, reducing to 65536.0
[2021-02-18 13:31:07,868] [INFO] [stage2.py:1357:step] [deepscale] OVERFLOW! Rank 3 Skipping step. Attempted loss scale: 131072.0, reducing to 65536.0
Epoch 0:   0%|▏                                                        | 16/3750 [00:03<14:50,  4.19it/s, loss=3.11, v_num=54]
[2021-02-18 13:31:07,976] [INFO] [stage2.py:1357:step] [deepscale] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 65536.0, reducing to 32768.0
[2021-02-18 13:31:07,976] [INFO] [stage2.py:1357:step] [deepscale] OVERFLOW! Rank 1 Skipping step. Attempted loss scale: 65536.0, reducing to 32768.0
[2021-02-18 13:31:07,977] [INFO] [stage2.py:1357:step] [deepscale] OVERFLOW! Rank 3 Skipping step. Attempted loss scale: 65536.0, reducing to 32768.0
[2021-02-18 13:31:07,977] [INFO] [stage2.py:1357:step] [deepscale] OVERFLOW! Rank 2 Skipping step. Attempted loss scale: 65536.0, reducing to 32768.0
Epoch 0:   0%|▎                                                        | 17/3750 [00:03<14:21,  4.33it/s, loss=3.11, v_num=54]
[2021-02-18 13:31:08,088] [INFO] [stage2.py:1357:step] [deepscale] OVERFLOW! Rank 1 Skipping step. Attempted loss scale: 32768.0, reducing to 16384.0
[2021-02-18 13:31:08,088] [INFO] [stage2.py:1357:step] [deepscale] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 32768.0, reducing to 16384.0
[2021-02-18 13:31:08,088] [INFO] [stage2.py:1357:step] [deepscale] OVERFLOW! Rank 3 Skipping step. Attempted loss scale: 32768.0, reducing to 16384.0
[2021-02-18 13:31:08,088] [INFO] [stage2.py:1357:step] [deepscale] OVERFLOW! Rank 2 Skipping step. Attempted loss scale: 32768.0, reducing to 16384.0
Epoch 0:   0%|▎                                                        | 18/3750 [00:04<13:56,  4.46it/s, loss=3.11, v_num=54] # stalls here
```

This could also be due to waiting for buckets that do not have gradients. For DDP, we have to set `find_unused_parameters=True` in order to run, so this might highlight an issue in the DeepSpeed distributed code.

Install PyTorch Lightning from master.
```bash
pip install lightning-bolts deepspeed
```

```python
import logging

from pl_bolts.datamodules import MNISTDataModule
from pl_bolts.models import ImageGPT

import pytorch_lightning as pl
from pytorch_lightning.plugins import DeepSpeedPlugin, DDPPlugin

dm = MNISTDataModule('.', batch_size=4)

model = ImageGPT(embed_dim=2048, layers=4, heads=4, vocab_size=32, num_pixels=28)

deepspeed_plugin = DeepSpeedPlugin(logging_level=logging.INFO)
ddp_plugin = DDPPlugin(find_unused_parameters=True)
trainer = pl.Trainer(
    max_epochs=1,
    gpus=4,
    precision=16,
    plugins=deepspeed_plugin,
)
trainer.fit(model, dm)
```

### Environment

* CUDA:
        - GPU:
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
        - available:         True
        - version:           11.2
* Packages:
        - numpy:             1.20.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.8.0+cu112
        - pytorch-lightning: 1.2.0rc1
        - tqdm:              4.56.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.5

**Comment by SeanNaren** [comment]
I'm wrong about the optimizer step, the DeepSpeed guys handle the optimizer overflow nicely here:

https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/zero/stage2.py#L1533-L1540

**Comment by griff4692** [comment]
Hi - what's a solution here? I'm encountering the same issue in lightning

**Comment by griff4692** [comment]
> Traceback (most recent call last):
>   File "finetune.py", line 27, in <module>
>     run(args, PureSAUCE)
>   File "/home/griffin/kabupra/graph/main.py", line 118, in run
>     trainer.fit(model)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 460, in fit
>     self._run(model)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 758, in _run
>     self.dispatch()
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 799, in dispatch
>     self.accelerator.start_training(self)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
>     self.training_type_plugin.start_training(trainer)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
>     self._results = trainer.run_stage()
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in run_stage
>     return self.run_train()
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 871, in run_train
>     self.train_loop.run_training_epoch()
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 499, in run_training_epoch
>     batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 738, in run_training_batch
>     self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 434, in optimizer_step
>     model_ref.optimizer_step(
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1403, in optimizer_step
>     optimizer.step(closure=optimizer_closure)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 214, in step
>     self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 134, in __optimizer_step
>     trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 325, in optimizer_step
>     make_optimizer_step = self.precision_plugin.pre_optimizer_step(
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/deepspeed_precision.py", line 46, in pre_optimizer_step
>     lambda_closure()
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 732, in train_step_and_backward_closure
>     result = self.training_step_and_backward(
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 823, in training_step_and_backward
>     result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 290, in training_step
>     training_step_output = self.trainer.accelerator.training_step(args)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 204, in training_step
>     return self.training_type_plugin.training_step(*args)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 337, in training_step
>     return self.model(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1105, in forward
>     loss = self.module(*inputs, **kwargs)
>   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1071, in _call_impl
>     result = forward_call(*input, **kwargs)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/deepspeed.py", line 62, in forward
>     return super().forward(*inputs, **kwargs)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 46, in forward
>     output = self.module.training_step(*inputs, **kwargs)
>   File "/home/griffin/kabupra/graph/models/pure_sauce.py", line 137, in training_step
>     return self.shared_step(batch, is_train=True)
>   File "/home/griffin/kabupra/graph/models/pure_sauce.py", line 128, in shared_step
>     sent_loss, cui_loss, sec_loss = self(**batch)
>   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1071, in _call_impl
>     result = forward_call(*input, **kwargs)
>   File "/home/griffin/kabupra/graph/models/pure_sauce.py", line 77, in forward
>     source_node_graph_states = self.dropout(self.graph.entity_graph_encoder(
>   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1071, in _call_impl
>     result = forward_call(*input, **kwargs)
>   File "/home/griffin/kabupra/graph/models/model_utils.py", line 132, in forward
>     x = self.elu(self.conv1(x, edge_index))
>   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1071, in _call_impl
>     result = forward_call(*input, **kwargs)
>   File "/home/griffin/.local/lib/python3.8/site-packages/torch_geometric/nn/conv/gat_conv.py", line 124, in forward
>     x_l = x_r = self.lin_l(x).view(-1, H, C)
>   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1071, in _call_impl
>     result = forward_call(*input, **kwargs)
>   File "/usr/lib/python3/dist-packages/torch/nn/modules/linear.py", line 96, in forward
>     return F.linear(input, self.weight, self.bias)
>   File "/usr/lib/python3/dist-packages/torch/cuda/amp/autocast_mode.py", line 211, in decorate_fwd
>     return fwd(*args, **kwargs)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/deepspeed/runtime/zero/linear.py", line 60, in forward
>     output = input.matmul(weight.t())
> RuntimeError: expected scalar type Float but found Half

For my context, I'm posting my full stack trace.  Thanks

**Comment by SeanNaren** [comment]
Are you using a similar model? It seems there is a chance this is fixed using the latest DeepSpeed but I haven't checked in a while @griff4692

**Comment by gautamsreekumar** [comment]
Hi, I am facing similar issues while using DeepSpeed plugin in PyTorch Lightning. My model is a custom CNN. I am using the latest DeepSpeed (0.4.3) and PyTorch Lightning 1.3.3, PyTorch 1.8.1. I am adding my error traceback below. @SeanNaren can you share any fix that worked in your case?

> Traceback (most recent call last):
>   File "main.py", line 150, in <module>
>     trainer.fit(model, datamodule=kitti15_datamodule)
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
>     self._run(model)
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 756, in _run
>     self.dispatch()
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 797, in dispatch
>     self.accelerator.start_training(self)
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
>     self.training_type_plugin.start_training(trainer)
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
>     self._results = trainer.run_stage()
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 807, in run_stage
>     return self.run_train()
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 869, in run_train
>     self.train_loop.run_training_epoch()
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 489, in run_training_epoch
>     batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 728, in run_training_batch
>     self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 432, in optimizer_step
>     using_lbfgs=is_lbfgs,
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1403, in optimizer_step
>     optimizer.step(closure=optimizer_closure)
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/pytorch_lightning/core/optimizer.py", line 214, in step
>     self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/pytorch_lightning/core/optimizer.py", line 134, in __optimizer_step
>     trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 326, in optimizer_step
>     self.lightning_module, optimizer, opt_idx, lambda_closure, **kwargs
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/pytorch_lightning/plugins/precision/deepspeed_precision.py", line 46, in pre_optimizer_step
>     lambda_closure()
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 723, in train_step_and_backward_closure
>     split_batch, batch_idx, opt_idx, optimizer, self.trainer.hiddens
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 826, in training_step_and_backward
>     self.backward(result, optimizer, opt_idx)
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 860, in backward
>     result.closure_loss, optimizer, opt_idx, should_accumulate, *args, **kwargs
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 309, in backward
>     self.lightning_module, closure_loss, optimizer, optimizer_idx, should_accumulate, *args, **kwargs
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/pytorch_lightning/plugins/precision/deepspeed_precision.py", line 72, in backward
>     deepspeed_engine.backward(closure_loss, *args, **kwargs)
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1191, in backward
>     self.optimizer.backward(loss)
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/deepspeed/runtime/zero/stage2.py", line 1742, in backward
>     self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 53, in backward
>     scaled_loss.backward(retain_graph=retain_graph)
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
>   File "/home/gautamsree/miniconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
>     allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
> RuntimeError: Found dtype Half but expected Float

**Comment by SeanNaren** [comment]
Thanks @gautamsreekumar! @griff4692 seemed to be running into an issue where the input tensors were not being converted by the DeepSpeed plugin to half. Could you try manually converting your tensors in your step function to see if that works? i.e

```python
def training_step(batch, batch_idx):
    batch = batch.half()
    ....
```

**Comment by gautamsreekumar** [comment]
@SeanNaren  Oh I think my issue is the other way round. My batch and the model are of type Half, but the autograd expected Float type. It is similar to your error, I think.

**Comment by SeanNaren** [comment]
@gautamsreekumar have you set `precision=16`?

**Comment by gautamsreekumar** [comment]
Yes. This is how my Trainer looks like.

```
if opt.deepspeed:
	plugins_list = [DeepSpeedPlugin(cpu_offload=True),
				DeepSpeedPrecisionPlugin(precision=16)]
	precision = 16

trainer = pl.Trainer(gpus=opt.ngpus,
				 accelerator='ddp',
				 plugins=plugins_list,
				 num_nodes=opt.num_nodes,
				 amp_backend='native',
				 amp_level='O2',
				 auto_lr_find=False,
				 benchmark=True, # only if the input sizes don't change rapidly
				 callbacks=callback_list,
				 gradient_clip_val=opt.grad_clip, # 0 gradient clip means no clipping
				 max_epochs=opt.nEpochs,
				 precision=precision, # decides the use of AMP
				 profiler='simple', # identify potential bottlenecks
				 resume_from_checkpoint=opt.resume,
				 sync_batchnorm=True,
				 stochastic_weight_avg=opt.swa, # set to True later
				 )
```

**Comment by gautamsreekumar** [comment]
Hi @SeanNaren, I tried to reproduce the error using minimal tools, but the error does not come then. I am not sure which component in my code reproduces this error, and I am not sure if I can share the code as it is part of an on-going research.

**Comment by SeanNaren** [comment]
iGPT is fixed in https://github.com/PyTorchLightning/lightning-bolts/pull/694 and this issue has been resolved in the latest DeepSpeed. @gautamsreekumar if you're able to reproduce the issue you're running into, please make another issue to track!
