### ISSUE TITLE
1.2.x cherries 🍒 

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#6083]
@PyTorchLightning/core-contributors Please update this issue with any commits/PRs that should make it into 1.2.x.
Each cherry is to be `git cherry-pick`-ed into the appropriate release

<details>
<summary>1.2.1 (#6154)</summary>

4b7c0fa (#6080)
97a81c3 (#6089)
ae6ce17 (#6107)

</details>

<details>
<summary>1.2.2 (#6304)</summary>

40d5a9d6df4c5102f79ec67ccc7daae21654dc96 (#5931)
3df02b8 (#6072): feature, required for #6073
1b498d1f143820a3acb7154ec24bf9d33a5a60ef (#6075)
925f082 (#6147)
dd2f5a0 (#6197)
651c25feb66ba0a4c715ca671744a20f0a1355b0 (#6216)
efda48f (#6262)
412a7d812e7f144420be6959bfb5f489fd8db7cb (#6267)
8001987 (#6297)

</details>

<details>
<summary>1.2.3 (#6431)</summary>

4a8422c (#6073)
4f904556e44d36807ba5f1a6269c821768c12675 (#6076)
~~826375effe30e9d9be0c59a40be3453c12f00977 (#6136)~~: blocked by (#4945)
~~facfda85f1e72f15a66e9999b88fadb6c273601a (#6139)~~: blocked by (#4945)
5d7388d43bb59b005e9e6fbdbceb9ee691d54484 (#6177)
a6c98c4e4944cfc4977d27a4ea1e0c7c621dfb4d (#6221)
2ec67a48b3ed9e79a29d1c0b7f868e542cb7628c (#6260)
1aac481957dda7b9873a4204b5c96cb4e2c205c6 (#6272)
484dce11ecb92aab13c29d26b57cbf8c7522ceeb (#6296)
80019874e57267e44d0eee9e898f51e45703e502 (#6302)
7acbd65bcb76b39a0f8d7a6f6985168d767ab23a (#6305)
e038e747a0d09171f21f42ae31f5e7dcd390ea77 (#6323)
46540ee260af5137ac38ff0ce1022290cbc120b9 (#6326)
39231aee1ae2883428d62714c40c6a3d835e8fe8 (#6330)
e84854264f248a6fb9a1435c4edca001cf7e1dae (#6357)
85c8074beefd81cce12823c5bca7e5f6e93f237d (#6363)
2a3ab6794606c7ac646dce608d559662cf04118d (#6365)
718074b99afc17204a1973f1bc94befa611ac094 (#6372)
0ec7a23a1e2988694279d36eca5301164d1a2661 (#6399)

</details>

<details>
<summary>1.2.4 (#6545)</summary>

248a8e8b321317ac2e466ba8b96d0b2f60fe134e (https://github.com/PyTorchLightning/pytorch-lightning/pull/6324)
523c59bfddca48d003ce20168e727e6683f3efd4 (https://github.com/PyTorchLightning/pytorch-lightning/pull/4688)
b2bcad11327ef947d622306f68f8a84000ee377c (https://github.com/PyTorchLightning/pytorch-lightning/pull/5968)
c53edce1a1bada7be97c40c8c6d6ae3caca56f4a (https://github.com/PyTorchLightning/pytorch-lightning/pull/6098)
fc6d4027334b8869f02a3bdca0a0846f1cf79928 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6380)
0544efd4535cb8965902fc3c938263b3deafc7b7 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6410)
9eded7fd7323ef474923f14b9a016f4a0f0d8ca3 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6419)
c81b2a8 (#6438)
1c013b43e049d423184323313014774738827c90 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6460)
079fe9bc0908fffdd55a08f7321a199bceaef6f8 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6476)
02fa32b (#6511)
156847bea7c8818e479f9eceac37e8236303f5dc (https://github.com/PyTorchLightning/pytorch-lightning/pull/6516)
ea36ee30b0a2eec1da693b42739aafed0389fbb9 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6513)
6a1414681107cf77d1ebeba86359df7b6668bf49 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6537)
0f07eaf51a206396f004a8d45729060b8ac80738 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6510)

last sha scrutinized: 0f07eaf51a206396f004a8d45729060b8ac80738

</details>

<details>
<summary>1.2.5 (#6646)</summary>

bc577ca7923387384c015d7e04d5b0c4e5f1afd9 (#6275)
8cd75a4dd51939881da265752c2d81307cbe4d9e (https://github.com/PyTorchLightning/pytorch-lightning/pull/6434)
6453091 (#6530)
555a6fea212e340f0b3a9684829e6027e4ba27c0 (#6540)
634d83134fea4bb701c24abd5a4a38adb0eddbcd (#6565)
87c03b10389bb88d1b1a4e5fbc40e8e02091fd04 (#6576)
8853a36d457bf2b226f6dd28a816712f02c0069f (#6579)
983a888f498131911a1296400448b004a53c1717 (#6587)
1fae10a2dc8224379eac84d6242e0847c2685565 (#6590)
cb590392880aefcb0830bf00ec08e4beef6d4f7e (#6600)

last sha scrutinized: 1fae10a2dc8224379eac84d6242e0847c2685565

</details>

<details>
<summary>1.2.6 (#6729)</summary>

615b2f736303ad3cd56b33111f69952255f01c0f (https://github.com/PyTorchLightning/pytorch-lightning/pull/6398)
9be092dbdb37db353002365e6d5219fae116cc42 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6498)
64d0fa44720da0d5e77f751faa5569950a25619e (https://github.com/PyTorchLightning/pytorch-lightning/pull/6524)
3b72bccdf2999a46a34fcc9c98b9bed879ad32d4 (#6536)
b8ef52baa111a0e43feb253b82c5ad14e5a04c57 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6625)
e62c7c7839beea9be336fe9f30873d005f9cdc5e (https://github.com/PyTorchLightning/pytorch-lightning/pull/6632)
2cbdc0125683131fe46c0e6ea700a50ad9d91ff6 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6654)
741c452551780e110938c8635db496682784be07 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6657)
bc613611e2709dd35bc3cef6bd71f6e9661ca6b2 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6682)
dcf6e4e3105199f2137224435f803357de3c511e (#6686)
3a4c4246eeb9afe19d5325a054cf38f8c3fbe0a9 (#6719)

last sha scrutinized: f79a13e

</details>

<details>
<summary>1.2.7 (#6850)</summary>

1bd5f36a5bf02ba853c04de77647456c64784399 (https://github.com/PyTorchLightning/pytorch-lightning/pull/5952) 
6dc1078822c33fa4710618dc2f03945123edecec (https://github.com/PyTorchLightning/pytorch-lightning/pull/6588)
3c86193de0e264004b40ec19c41b01360c90f1d2 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6728)
89b5326ca5a7bf422282f103ba04df61533bde03 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6730)
bb92754119934c79f97de38ce59470f0059f3a0d (https://github.com/PyTorchLightning/pytorch-lightning/pull/6741)
9876df16a2fd3f747c945c050698f25118ceaa6d (https://github.com/PyTorchLightning/pytorch-lightning/pull/6743)
13f67ad3132b67d4a6fce429731f4a4cd7eb00cc (https://github.com/PyTorchLightning/pytorch-lightning/pull/6767)
3e3175d0748ef461bf13b2258c8acdbe3a7bc8a5 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6781)
f58141121006e8b00a285eb58a98266e861b0e61 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6784)
22a266d8b8cf57455cc863e20491e416ec635ba7 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6794)
f8a379830d1cb92060264684dbaaa17b7a87036a (https://github.com/PyTorchLightning/pytorch-lightning/pull/6801)
cf8e828559450095cfdead77b074d05b131f34b6 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6816)
7f91c5ebbc60b5ebed61072846da606f5d3957e6 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6822)
264aa689de5998ed85bbf9c8e4517f9a406a34e5 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6828)
c3da7f50bb6accf023ccf360de8b519f8cc41ea9 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6836)
eafec7d425bf691ab5bfaf2794c3e581487ecfa8 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6838)

last sha scrutinized: f58141121006e8b00a285eb58a98266e861b0e61

</details>

<details>
<summary>1.2.8 (#6983)</summary>

23e8dff6b98f3429b31aa019bf126ad55d0f3ceb [CI] Drop brew update (https://github.com/PyTorchLightning/pytorch-lightning/pull/6985)
b37b58a73e74e173f4efc674a9ac2d4bb978e422 Fix Checkpoint issue when using Horovod distributed backend (https://github.com/PyTorchLightning/pytorch-lightning/pull/6958)
da1ac3a5309678716f49ca8add82bd870b3d0f25 update docker base on PT 1.7 (https://github.com/PyTorchLightning/pytorch-lightning/pull/6931)
1b3e4f9fb9a7a6e9fb516eee162b68763cb48ac3 Fix sync_dist for tpus (https://github.com/PyTorchLightning/pytorch-lightning/pull/6950)
80c529351439a0f8d3d6e9449cd47d16ba3abbec fix self.device access in DataParallel (https://github.com/PyTorchLightning/pytorch-lightning/pull/6414)
fe0d08899eba94d275ff42253f495d9e70d86f89 Fix ShardedDataParallel has no attribute require_backward_grad_sync (https://github.com/PyTorchLightning/pytorch-lightning/pull/6915)
55525031c65756c2e8574cfee5d386e584aecdca Fix TPU Spawn gather (https://github.com/PyTorchLightning/pytorch-lightning/pull/6896)
9c9e2a0325a6a5d25f0f82859965ffd330ea1acd fix gpus default for Trainer.add_argparse_args (https://github.com/PyTorchLightning/pytorch-lightning/pull/6898)
90e37ba458be13be02051c489e90b84b1efae2ae fix exception raising (https://github.com/PyTorchLightning/pytorch-lightning/pull/6901)
742c48e99462659c424fdb99c46b7f1b1e4a26bd [Fix] Ensure we set the eval/train flag correctly on accelerator model  (https://github.com/PyTorchLightning/pytorch-lightning/pull/6877)
1c2ecbf70c38912124a384f273090145c1328353 TPUSpawn + IterableDataset error message (https://github.com/PyTorchLightning/pytorch-lightning/pull/6875)
87f0aeac25c342a8342631518c871a42da842bc1 Fix DDP_SPAWN compatibility with bug_report_model.py (https://github.com/PyTorchLightning/pytorch-lightning/pull/6892)
eb15abcd821004fe88e5786a8ebd423a39b001dc Fix finetuning complex models correctly unfreezes. (https://github.com/PyTorchLightning/pytorch-lightning/pull/6880)
968ac091c0c2fc628baed22215f5d295772341c5 Remove hardcoding of rank_zero_only.rank in accelerator connector (https://github.com/PyTorchLightning/pytorch-lightning/pull/6878)
01b9cf8fdc117675029f5096470e14445276e607 Fix csv extension check (https://github.com/PyTorchLightning/pytorch-lightning/pull/6436)
86e1d9f75991cb7b1254ec282c474eacb8babb20 [fix] Better support for rank_zero_only setting for SLURM and torchelastic (https://github.com/PyTorchLightning/pytorch-lightning/pull/6802)
b7a22ba046ba57072a71b12d16caff000e66f798 CI: fixture for global rank variable reset (https://github.com/PyTorchLightning/pytorch-lightning/pull/6839)
127c52af747066b184faed215ab009ea6d77ad21 Fix EarlyStopping logic when min_epochs not met (https://github.com/PyTorchLightning/pytorch-lightning/pull/6705)

last sha scrutinized: e891ceb83651160ee1497455ffd63a75621bd013

Including non-bugfix commits is allowed if they are necessary to support a bugfix commit and it does not break compatibility. In that case, please add a comment for why the commit was included.

### Utils

To generate a list of commits after a SHA up to current master (with their corresponding links):

`git log --pretty=oneline master...<last_sha_scrutinized> | sed 's/#/https:\/\/github.com\/PyTorchLightning\/pytorch-lightning\/pull\//g'`

where `<last_sha_scrutinized>` is the SHA of the last commit that was considered to be included in the previous release.

**Comment by Borda** [comment]
still think that using GH releases would be more flexible and a bit easier
![Screenshot 2021-02-19 at 17 04 50](https://user-images.githubusercontent.com/6035284/108534801-d95b2c00-72da-11eb-9bf6-0b11a5e3468c.png)
 as you would also instantly see the commit name in the release report 
https://github.com/PyTorchLightning/pytorch-lightning/pull/5876/checks?check_run_id=1929613442#workspaces/lightning-5f9840e8ac6aae0010d13f8f/reports/release?release=602fe15165f367773aab8445

**Comment by carmocca** [comment]
> still think that using GH releases would be more flexible and a bit easier

The downside is it doesn't automatically provide a list of the master commits, right?

**Comment by awaelchli** [comment]
can we add again the list of potential candidates? because sometimes it is uncertain how quickly the PR will be merged

**Comment by carmocca** [comment]
@awaelchli we have a weekly meeting to decide the list from all merged PRs since the previous week, so shouldn't need it. Just make sure the milestone is correct.

**Comment by kaushikb11** [comment]
@awaelchli I have added you to the Monday commit release review meeting.

**Comment by carmocca** [comment]
Closing as there is no plan for any more bug-fix releases until 1.3 is out
