### ISSUE TITLE
DDP does not work well with `torch.no_grad()` in 1.2

### ISSUE THREAD

**Issue by Ingwar** [PyTorchLightning/pytorch-lightning#6087]
## 🐛 Bug

My code that uses `torch.no_grad` stopped working after updating to 1.2 (I'm doing knowledge distillation and using it to protect the teacher model computation). Now it throws
```
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one
```

## To Reproduce

[Here is](https://colab.research.google.com/drive/1nB30ra8i-JS7MZE0GVQ7solJ4CaV7HyB?usp=sharing) my modification of Boring Model. Basically, I've changed model definition and `train_step` to provide guard part of the computational graph with `torch.no_grad`. Also, I've change the final loss, it's now a sum of the original one and one computed as a similarity between mutable and guarded layers. As you can see, it throws RuntimeError at the first training iteration.

### Expected behavior

Training runs without any RuntimeException

### Environment

* CUDA:
	- GPU:
		- Tesla K80
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0+cu101
	- pytorch-lightning: 1.2.0
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

**Comment by Ingwar** [comment]
BTW, I've also seen it with different GPU and different versions of python, torch and CUDA.

**Comment by awaelchli** [comment]
I think you need to set `find_unused_parameters=True`:
`Trainer(...,  plugins=DDPPlugin(find_unused_parameters=True))`

**Comment by Ingwar** [comment]
I'll check it, thanks) But  why the same code worked in Lightning 1.1.* just fine?

**Comment by awaelchli** [comment]
I suspect it because we recently changed the default from `find_unused_parameters=True` to `False`. And the error message you reported also appears when find_unused_parameters is not set.

**Comment by Ingwar** [comment]
@awaelchli , explicitly instantiating the DDPPlugin with `find_unused_parameters=True` allows me to run my code, thank you! Howewer, I'd like to avoid that instantiation if possible to keep my code simpler) Is there a way to do so? Maybe, it's possible to pass the plugin parameters via CLI?

**Comment by awaelchli** [comment]
PL does not offer that option at the moment. If you need the `find_unused_parameters` in your CLI, you have to add it to the parser manually. We have started discussing how to expose plugin parameters but have not yet reached a conclusion. The accelerator + plugin API is still experimental and we will iterate on it.

**Comment by Ingwar** [comment]
@awaelchli , sure, feel free to close it and thank you for the help) BTW, is there any issue about the exposure of plugin parameters? If so, could you, please, share a link to it?

**Comment by awaelchli** [comment]
so far only internally, but have opened the discussion here just now: #6219
I will keep it updated

**Comment by Ingwar** [comment]
Thanks!
