### ISSUE TITLE
Define null values for enums

### ISSUE THREAD

**Issue by ifsheldon** [PyTorchLightning/pytorch-lightning#6095]
## 🚀 Feature

Create null values for enums instead of using `None`. For example, `utilities.enums.DistributedType` should have a `DistributedTypes.None` enum value in addition to existing enum values.
### Motivation
Python builtin `None` is hard to track, and I think it is always a good practice to have default null values for enums in compensation for the lack of null safety of Python. It is especially beneficial when a variable holding a type of enum will be `None`, which is the case for `DistributedType` in `trainer.connectors.accelerator_connector`.

### Pitch

Define null values for enums, we can:
* keep track of when a variable of a enum type will be `None`, facilitating code analysis
* remind code collaborators of the possibility of being None when using an enum type
* (If we practice this broadly, we can at least) ensure code collaborators that a variable holding a value of a enum type will always valid(i.e. not literally `None`)
* "prevent" `Null pointer exception`/ `None does not have method/attribute` error.

### Additional context

When fixing #5966 in #5970, I have to take special care of `None` of `self._distrib_type`, which is a bit annoying.

**Comment by carmocca** [comment]
I personally don't think this is worth it. It's just moving the problem from one place to another. Also makes the `Optional` type unintuitive.

Can you showcase some pieces of code who would greatly benefit from this?

**Comment by ifsheldon** [comment]
It is not just about `Optional`. You can see some code like(e.g. in `accelerator_connector.py`)
```
def __init__(self):
    self.attribute = None #initialize
    if condition:
        self.attribute = Enum.A
    else:
        self.attribute = Enum.B
    # many code 
    if condition:
        self.attribute = None
```
In this situation, `Optional` will not help at all. The points really matter are those I mentioned in the pitch, especially the first and the second points.
For the first point, if you have defined `SomeEnum.None`, you can, through static code analysis, find out where it is used while you cannot just find `None` since any variable can be `None` without any context. `SomeEnum.None` can give more context when code contributors implement the enum and use the enum.
And it's cheap if you are not intended to fully review the legacy code. You just add another value to an enum. That's it.
