### ISSUE TITLE
Not saving checkpoint when monitor is None and save_top_k is -1

### ISSUE THREAD

**Issue by ruotianluo** [PyTorchLightning/pytorch-lightning#6096]
## 🐛 Bug

When monitor is None, current will be None here
https://github.com/PyTorchLightning/pytorch-lightning/blob/6bc4490d01aed21c2d52f884d4afbeaa24a47ca0/pytorch_lightning/callbacks/model_checkpoint.py#L553

And check_monitor_top_k will return False because of that:
https://github.com/PyTorchLightning/pytorch-lightning/blob/6bc4490d01aed21c2d52f884d4afbeaa24a47ca0/pytorch_lightning/callbacks/model_checkpoint.py#L340

_update_best_and_save also doesn't take None current. raise error here: https://github.com/PyTorchLightning/pytorch-lightning/blob/6bc4490d01aed21c2d52f884d4afbeaa24a47ca0/pytorch_lightning/callbacks/model_checkpoint.py#L605

Currently, checkpointing is associated with validation, which is not necessarily always the case. I just want to save the checkpoint every k iterations.

## Please reproduce using the BoringModel

Sorry, no time to reproduce for now.

### To Reproduce

Use following [**BoringModel**](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing) and post here

### Expected behavior

Should save the checkpoint always if save_top_k == -1.

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

* `IDE`: Please, use our python [bug_report_model.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
) template.

* `Colab Notebook`: Please copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py) (or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by carmocca** [comment]
When `monitor is None`, the `_save_last_checkpoint` function is the one to save the model (even if `save_last is True`), not `_update_best_and_save`.

I just manually checked and it seems to work properly

```python
def test_bug(tmpdir):
    model_ckpt = ModelCheckpoint(dirpath=tmpdir, monitor=None, save_top_k=-1, save_last=False)
    model = BoringModel()
    trainer = Trainer(
        default_root_dir=tmpdir,
        logger=False,
        max_epochs=3,
        callbacks=[model_ckpt],
    )
    trainer.fit(model)

    print(os.listdir(tmpdir))
    # ['epoch=0-step=63.ckpt', 'epoch=2-step=191.ckpt', 'epoch=1-step=127.ckpt']
```

Can you elaborate on what is the problem?

**Comment by ruotianluo** [comment]
I see the code doing that. Interesting, let me check with my code.

**Comment by ruotianluo** [comment]
I c. this is because you set save_last to False. If you set save_last to True, the checkpoints will always be last.ckpt.
