### ISSUE TITLE
Early stopping on custom metric without validation_step

### ISSUE THREAD

**Issue by Inspirateur** [PyTorchLightning/pytorch-lightning#6104]
#### What is your question?

I have a metric that I can only define using every predictions on the validation split, so I cannot use `validation_step` since it only operates on batches of data.
I have a callback that computes and log this metric in `on_train_epoch_end`. 
I am not executing the validation loop because it's useless in my case.
My question is: How can I properly use the EarlyStopping callback ? (Same question for ModelCheckpoint)

#### What have you tried?
I have tried manually calling `pl_module.on_validation_epoch_end()` in my callback but it doesn't seem to work because EarlyStopping never stops the model even though the patience should have dropped to 0.

#### What's your environment?

 - OS: Kubuntu 20.04
 - Packaging: pip
 - Version: 1.1.4

**Comment by carmocca** [comment]
If I understood you correctly, you just need to make sure to create your instance as:

`EarlyStopping(monitor="your_metric")`

And then, in your LightningModule's `on_validation_epoch_end` do `self.log("your_metric", value)`

**Comment by Inspirateur** [comment]
Seems like that works, thank you.
I just had to define an empty `validation_step` method in my lightning module so the fake validation would be quick.
