### ISSUE TITLE
on_{validation,test}_epoch_end functions should have an outputs parameter

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#6105]
## 🚀 Feature

https://github.com/PyTorchLightning/pytorch-lightning/blob/3b0e4e0b2bc5b62bba09df5976e1460774ae7337/pytorch_lightning/core/hooks.py#L255

https://github.com/PyTorchLightning/pytorch-lightning/blob/3b0e4e0b2bc5b62bba09df5976e1460774ae7337/pytorch_lightning/core/hooks.py#L267

Should have an `outputs` parameter as

https://github.com/PyTorchLightning/pytorch-lightning/blob/3b0e4e0b2bc5b62bba09df5976e1460774ae7337/pytorch_lightning/core/hooks.py#L243

**Comment by awaelchli** [comment]
Duplicate? #5508
AFAIK @kaushikb11 is working on this

**Comment by kaushikb11** [comment]
Yup.

**Comment by kaushikb11** [comment]
Got involved in other fixes, will look into it again tomorrow.

**Comment by carmocca** [comment]
Didn't know! Closing this one
