### ISSUE TITLE
Access Optimizer and Optimizer Index in on_after_backward() hook

### ISSUE THREAD

**Issue by cemanil** [PyTorchLightning/pytorch-lightning#6116]
## 🚀 Feature
Let the on_after_backward() hook have access to the optimizer that will use the recently computed gradients to perform a parameter update. 

### Motivation
The documentation suggests that on_after_backward() is the ideal place to inspect gradient information. When using multiple optimizers, it helps to know which optimizer will use the recently computed gradients to perform a parameter update. 

### Pitch
If I'm not mistaken, this can be done by adding two arguments (optimizer and optimizer_idx) to the hook. TrainingLoop calls on_after_backward within the TrainingLoop.training_step_and_backward(...) method, which has access to the optimizer and optimizer index, so no extra "plumbing" would be needed I think. 

### Alternatives
One might alternatively use the LightningModule.optimizer_step() method to inspect gradient information. However, on_after_backward() seems like a better place to do this. 

### Additional context
This is related to issue #1527.

**Comment by carmocca** [comment]
Sounds good to me. Would you like to work on this?

**Comment by carmocca** [comment]
The `on_before_optimizer_step` has been added for this in 1.4
