### ISSUE TITLE
New pip install doesn't align with documentation when importing modules  

### ISSUE THREAD

**Issue by shamanez** [PyTorchLightning/pytorch-lightning#6141]
## 🐛 Bug

I tried to import the following modules. 
```
from pytorch_lightning.accelerators.ddp_accelerator import DDPAccelerator
from pytorch_lightning.cluster_environments import TorchElasticEnvironment
```

Gives the error : **ModuleNotFoundError: No module named 'pytorch_lightning.accelerators.ddp_accelerator'**

works well with version 1.1.8

**current version = 1.2.0**

**Comment by carmocca** [comment]
Hi!

The DDPAccelerator was removed in 1.2.0, you are probably interested in using the DDPPlugin now

These are the correct imports now:

```python
from pytorch_lightning.plugins.training_type import DDPPlugin
from pytorch_lightning.plugins.environments import TorchElasticEnvironment
```

cc: @awaelchli

**Comment by shamanez** [comment]
Are these things updated in the doc ?

Thanks a lot.

**Comment by carmocca** [comment]
Looks like we missed a reference

```console
$ grep -irn "DDPAccelerator" docs
docs/source/common/trainer.rst:257:    class MyOwnDDP(DDPAccelerator):
```

**Comment by awaelchli** [comment]
@shamanez  Not yet fully, because the accelerator and plugin API are still considered experimental and API is subject to change in the near future.

**Comment by shamanez** [comment]
@awaelchli 
So how can I create a custom accelerator now? 

As mentioned in this [code](https://github.com/huggingface/transformers/blob/master/examples/research_projects/rag/finetune_rag.py#L84), I want to access the init_ddp_conntection function. Could you please let me know how to do I it ?

**Comment by awaelchli** [comment]
Like so, more or less:
```python
from pytorch_lightning.plugins import DDPPlugin

class MyDDP(DDPPlugin):

    def init_ddp_connection(self, global_rank: int, world_size: int) -> None:
        # override this


trainer = Trainer(..., plugins=[MyDDP()])
```

**Comment by shamanez** [comment]
Ah thanks a lot. So basically I do not use any accelerators but put the
same stuff inside the ddppluggin.
