### ISSUE TITLE
@auto_move_data unexpectedly uses transfer_batch_to_device from DataModule

### ISSUE THREAD

**Issue by indigoviolet** [PyTorchLightning/pytorch-lightning#6143]
## 🐛 Bug

I have a LightningDataModule that produces a custom batch object, and I have implemented `transfer_batch_to_device` to move this data to the GPU. This works.

I have a separate `infer` method (on my LightningModule) which is invoked with a Tensor, and I wanted to use `@auto_move_data` to move this Tensor to 
the GPU. However, this unexpectedly uses my data module's `transfer_batch_to_device` method, and assumed that the input to `infer` will be of my custom batch type.

### To Reproduce

https://colab.research.google.com/drive/18f8886hG9AVSkYdVi96CIcZjrl9zX6Np#scrollTo=AAtq1hwSmjKe

### Expected behavior

1) I think this API is a bit confusing/surprising. I was expecting `@auto_move_data` to behave in the "default" mode since I passed in a Tensor, and I was not expecting it to use my  data module's `transfer_batch_to_device` method - especially since the `infer` method and the `@auto_move_data` decorator were on the LightningModule, not the data module. 

IMHO, a less confusing API would be to expect a `to()` method on the custom batch object, and make `transfer_batch_to_device` just call that `to()` method. Then it would work uniformly for tensors and custom batch objects.

2) Another thing that makes this problematic: the signature of `transfer_batch_to_device` is supposed to be `def transfer_batch_to_device(self, batch, device)`: https://pytorch-lightning.readthedocs.io/en/stable/extensions/datamodules.html?highlight=transfer_batch_to_device#transfer-batch-to-device

But in `@auto_move_data`, it is [getting called](https://github.com/PyTorchLightning/pytorch-lightning/blob/bcc00049550d920ddf4e66809c2f2c1aac7c31cb/pytorch_lightning/core/decorators.py#L61) with a tuple of `(args, kwargs)`, and no device AFAICT.

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0+cu101
	- pytorch-lightning: 1.2.0
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

**Comment by indigoviolet** [comment]
cc @rohitgr7 , since you have been working on this code recently.

**Comment by rohitgr7** [comment]
@indigoviolet 
`auto_move_data` was already using `transfer_batch_to_device` before I made the changes. in your case, you can add some conditionals for your use-case, since there is a possibility that during inference someone might still be using a custom batch, so changing it to default mode might be a problem. There are few ways you can do that:

```python
def transfer_batch_to_device(...):
    if isinstance(batch, torch.Tensor):
        return super().transfer_batch_to_device(batch)
    else:
        # your custom implementation
```
or
```python
def transfer_batch_to_device(...):
    if self.predicting:  # or self.testing/self.evaluating
        return super().transfer_batch_to_device(batch)
    else:
        # your custom implementation
```

regarding the `device` argument it get's that from `self.device` here incase it's not passed. ref: https://github.com/PyTorchLightning/pytorch-lightning/blob/bcc00049550d920ddf4e66809c2f2c1aac7c31cb/pytorch_lightning/core/hooks.py#L616-L617

I think we should either add the device argument back in the api call or just remove(after deprecation) it completely since it's accessible using `self.device` already.

**Comment by indigoviolet** [comment]
Thanks for the quick response, @rohitgr7 . 

My 2 cents is that this makes for a fairly confusing API: in one path we receive a custom object, in another we receive a tuple of `(args, kwargs)`,  which contains at some index perhaps the custom object or perhaps a real tensor. If I'm going to jump through these hoops and handle all the cases, how is `@auto_move_data` helping me? The documentation for `transfer_batch_to_device` doesn't mention anything like this either.

What did you think of my suggestion to instead expect `.to()` on a custom object? The API seems dramatically simpler,  and `transfer_batch_to_device` can also be replaced with a much simpler invocation of `.to(device)`.

**Comment by rohitgr7** [comment]
the only use-case for `auto_move_data` I can see is with the forward method.

will it make sense to update it to
```python
args = transfer_batch_to_device(args)
kwargs = transfer_batch_to_device(args)
```
? or do you have any other suggestions??

> The API seems dramatically simpler, and transfer_batch_to_device can also be replaced with a much simpler invocation of .to(device).

if you have `.to` method in your custom-batch then you don't need to override `transfer_batch_to_device`. It will handle it automatically.

**Comment by indigoviolet** [comment]
if `.to` is already supported, I think this is more of a documentation issue. 

Instead of highlighting/recommending a custom implementation of `transfer_batch_to_device`, we should document the support for `.to()` and its expected signature - I think that simplifies things quite a bit. 

Another thing that would help is unifying the documentation for `transfer_batch_to_device` in [LightningModule](https://pytorch-lightning.readthedocs.io/en/stable/common/lightning_module.html#transfer-batch-to-device) and [LightningDataModule](https://pytorch-lightning.readthedocs.io/en/stable/extensions/datamodules.html?highlight=transfer_batch_to_device#transfer-batch-to-device). The former recommends calling `super().transfer_batch_to_device()` which I think would have also solved my problem, the latter makes no mention of it.

**Comment by rohitgr7** [comment]
mind send a PR to update the docs? @indigoviolet

**Comment by indigoviolet** [comment]
Sure.

**Comment by awaelchli** [comment]
note, auto_move_data will be deprecated #6993
