### ISSUE TITLE
[Hydra] Add `_target_` key to hparams.yaml when the model is instantiated by hydra.utils.instantiate().

### ISSUE THREAD

**Issue by S-aiueo32** [PyTorchLightning/pytorch-lightning#6150]
## 🚀 Feature

This is the feature request to add more compatibility with `hydra.utils.instantiate()`.

### Motivation

Hydra has the feature to instantiate arbitrary classes through `hydra.utils.instantiate()`. This feature makes it possible to instantiate only from the configuration files without code changes. For example, the training with PL is simply done as follow:

```yaml:config.yaml
model:
    _target_: AwesomeLightningModule
    hidden_channels: 512
    ...
data:
    _target_: AwesomeDataModule
    batch_size: 128
    ...
trainer:
    _target_: pytorch_lightning.Trainer
    gpus: 1
    ...
```
```python:main.py
import hydra
from omegaconf import DictConfig


@hydra.main(config_path='', config_name='config')
def app(config: DictConfig) -> None:

    model: AwesomeLightningModule = hydra.utils.instantiate(config.model)
    data: AwesomeDataModule = hydra.utils.instantiate(config.data)
    trainer: pytorch_lightning.Trainer = hydra.utils.instantiate(config.trainer)

    data.setup('fit')
    trainer(model, datamodule=data)


if __name__ == '__main__':
    app()
```

If `save_hyperparameters()` is called in the constructor of `AwesomeLightningModule`, the configuration without `_target_` will be logged in `hparams.yaml` like:
```yaml
hidden_channels: 512
...
```
It is expected behavior but it seems to be unuseful in the test phase. More concretely, we can't use `hydra.utils.instantiate()` to instantiate the model same as the trained one because `_target_` is missed. Even if it were possible to know the `_target_`, we must write additional codes to import the models.

### Pitch

I want `save_hyperparameters()` to save `_target_` key into `hparams.yaml` only when the model is instantiated by `hydra.utils.instantiate()`:
```yaml
_target_: AwesomeLightningModule
hidden_channels: 512
...
```

### Alternatives

1. The `_target_` can be dynamically obtained so add this property to the LightningModule class:
```python
@property
def _target_(self) -> str:
    """Get the shortest module name that is importable from the current directory.
    """
    _target_ = self.__class__.__module__ + '.' + self.__class__.__name__
    for i in range(len(self.__class__.__module__.split('.'))):
        try:
            module_name = '.'.join(cls.__module__.split('.')[:-(i + 1)])
            _ = getattr(importlib.import_module(module_name), cls.__name__)
            _target_ = module_name + '.' + cls.__name__
        except (AttributeError, ValueError):
            pass
    return _target_
```

2. Inspect the call stack in `save_hyperparameters()` and update `hp` with `_target_` if the model instantiated by `hydra.utils.instantiate()`:
```python
def save_hyperparameters(self, *args, frame=None) -> None:
    if not frame:
        frame = inspect.currentframe().f_back
    init_args = get_init_args(frame)
    assert init_args, "failed to inspect the self init"
    if not args:
        # take all arguments
        hp = init_args
        self._hparams_name = "kwargs" if hp else None
    else:
        # take only listed arguments in `save_hparams`
        isx_non_str = [i for i, arg in enumerate(args) if not isinstance(arg, str)]
        if len(isx_non_str) == 1:
            hp = args[isx_non_str[0]]
            cand_names = [k for k, v in init_args.items() if v == hp]
            self._hparams_name = cand_names[0] if cand_names else None
        else:
            hp = {arg: init_args[arg] for arg in args if isinstance(arg, str)}
            self._hparams_name = "kwargs"

    # `hparams` are expected here
    if hp:
        self._set_hparams(hp)

    # additional part
    if 'hydra/utils.py' in inspect.stack()[-2].filaname:  # this condition should be improved.
        self._hparams.update({'_target': self._target_})

    # make deep copy so  there is not other runtime changes reflected
    self._hparams_initial = copy.deepcopy(self._hparams)
```

**Comment by omry** [comment]
cc @romesco.

**Comment by romesco** [comment]
This is an interesting idea! I wish I could help you prototype it, but I don't have the cycles at the moment! If you start a PR I'm happy to review it if you CC me, @S-aiueo32 =]

**Comment by omry** [comment]
I think it would be better if we had proper dataclasses defined to instantiate PTL objects.
those can be used as schema for your config and will add the target automatically.

See this Hydra 1.1 example:
https://github.com/facebookresearch/hydra/tree/master/examples/instantiate/object_recursive

**Comment by romesco** [comment]
As in https://github.com/romesco/hydra-lightning/blob/main/hydra-configs-pytorch-lightning/hydra_configs/pytorch_lightning/trainer.py
?

**Comment by omry** [comment]
Yes.
