### ISSUE TITLE
PyTorchProfiler crashes when emit_nvtx=True

### ISSUE THREAD

**Issue by NathanGrimaud** [PyTorchLightning/pytorch-lightning#6153]
## 🐛 Bug

When training with PyTorchProfiler(emit_nvtx=True), the training stops with the following error : 
`AttributeError: 'emit_nvtx' object has no attribute 'function_events'`

## Please reproduce using the BoringModel

-> https://colab.research.google.com/drive/1cqMxMgDVgltluaYZAkn9d2srSDmOu-1p?usp=sharing

### To Reproduce

Use following [**BoringModel**](**https://colab.research.google.com/drive/1cqMxMgDVgltluaYZAkn9d2srSDmOu-1p?usp=sharing**) and post here

### Additional context

Additional docs issue : 
It says here (https://pytorch-lightning.readthedocs.io/en/1.2.0/advanced/profiler.html) that you have to use `nvprof` to collect the profiler traces, but it is no longer supported for devices with compute capability 8.0 and higher.
I think that an exemple using nsight-compute would be great ( I can't test it right now because of the nvtx issue )

**Comment by tchaton** [comment]
Dear @NathanGrimaud,

I opened a PR with a fix. Would you mind giving it a try ?

Best regards,
T.C

**Comment by NathanGrimaud** [comment]
Well it works now thanks !
But I cannot get the whole report working 
```
nvprof --profile-from-start off -o trace_name.prof -- pytest tests/trainer/test_trainer.py::test_pytorch_profiler_nested_emit_nvtx

python -c "import torch;print(torch.autograd.profiler.load_nvprof('/home/ubuntu/pytorch-lightning/trace_name.prof'))"
```
nvprof isn't supported on nvidia's gpus since the Turing architecture (https://docs.nvidia.com/cuda/profiler-users-guide/index.html#profiling-overview). 
But this might belong to a new issue ( or even a PR if I can get it to work ^^)
