### ISSUE TITLE
Newer torchtext (>= nightly 2021-02-19) breaks PyTorch Lightning

### ISSUE THREAD

**Issue by thiagocrepaldi** [PyTorchLightning/pytorch-lightning#6165]
## 🐛 Bug

```python3
import pytorch_lightning as pl
  File "/../python3.7/site-packages/pytorch_lightning/utilities/apply_func.py", line 28, in <module>
    from torchtext.data import Batch
ImportError: cannot import name 'Batch' from 'torchtext.data' (/.../python3.7/site-packages/torchtext/data/__init__.py)
```

### To Reproduce

Install nightly torchtext after 02/19/2021 and install pytorch Lightning and try to import lightning on python interpreter

### Expected behavior

Latest pytorch lightning should be compatible with nightly torchtext or at lest a nightly ightning should be made available with such fix

**Comment by soyoung97** [comment]
For my case, torchtext version of 0.9.0 got this issue, so downgrading to `pip install torchtext==0.8.1` solved the version conflict.
