### ISSUE TITLE
Update instructions for questions in notebooks

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#6184]
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/notebooks/04-transformers-text-classification.ipynb
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/notebooks/06-mnist-tpu-training.ipynb
notebooks too pls.

_Originally posted by @rohitgr7 in https://github.com/PyTorchLightning/pytorch-lightning/issues/6155#issuecomment-784426082_

**Comment by rohitgr7** [comment]
I should have pushed a commit there itself.

**Comment by carmocca** [comment]
It's fine 👍 . Great that you noticed!
