### ISSUE TITLE
Customize multiple dataloaders behaviour in train vs val/test

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#6233]
User should be able to determine if multiple dataloaders will run simultaneously (passed as a list/dict), or get called sequentially.
This can be done with a trainer flag with multiple options.

Background:
Currently, in training step you get the different batches at the same time as list or dict, but for validation step it gets called multiple times with a dataloader_idx. Just thought it would be nicer if how multiple dataloaders are handled is consistent across training, val and test.

**Comment by mees** [comment]
@williamFalcon's suggestion was to have something like Trainer(multi_dataset_style=“sequential | simultaneous”) to enable consistent multiple dataloader behaviors.

**Comment by tchaton** [comment]
Hey @mees @edenlightning,

Any consensus on the feature to be implemented ? 

Note: `Sequential` training would be quick a large refactor internally to enable this feature.

Best,
T.C
