### ISSUE TITLE
has no attribute 'automatic_optimization'

### ISSUE THREAD

**Issue by duvenikitin** [PyTorchLightning/pytorch-lightning#6242]
## 🐛 Bug
I have some problems with using Trainer. Tried to launch it on GPU/TPU on google colab, played with parameters, nothing helps. Link to [google colab notebook](https://colab.research.google.com/drive/1gyRnS_jJOWGWk7Xh1D9bJtqH1Rkjd6gN?usp=sharing) is provided. Please help me with the issue.

## Training code
    model = Model(
        df = df,
        n_users=num_users + 1,
        n_items=num_movies + 1,
        embedding_sizes=emb_sizes,
        )
    
    trainer = Trainer(
                      # auto_select_gpus=True,
                      # gpus=1,
                      # tpu_cores=8,
                      distributed_backend='ddp_cpu',
                      max_epochs=num_epochs)
    trainer.fit(model)

### Error Message
ModuleAttributeError                      Traceback (most recent call last)
<ipython-input-25-98574efd1be9> in <module>()
     13                       distributed_backend='ddp_cpu',
     14                       max_epochs=num_epochs)
---> 15     trainer.fit(model)

2 frames
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
    777                 return modules[name]
    778         raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
--> 779             type(self).__name__, name))
    780 
    781     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

ModuleAttributeError: 'Model' object has no attribute 'automatic_optimization'

**Comment by akihironitta** [comment]
@duvenikitin Hi, could you update the notebook share setting so that anyone with the link can view it?

**Comment by duvenikitin** [comment]
@akihironitta thank you, haven't noticed that I attached a view-link.

**Comment by akihironitta** [comment]
@duvenikitin Thank you for the update! `Model` needs to be a subclass of `pl.LightningModule`.
```diff
- class Model(torch.nn.Module):
+ class Model(pl.LightningModule):
```

**Comment by duvenikitin** [comment]
Thank you a lot. That was a stupid mistake.
