### ISSUE TITLE
Improve verbosity and progress bar display for early stopping

### ISSUE THREAD

**Issue by turian** [PyTorchLightning/pytorch-lightning#6252]
## 🚀 Feature

When using EarlyStopping, it would be be great if the progress bar added two values, like "espatience" (the number of epochs of patience left before it might stop early) and "estarget" (which is the objective including min_delta, that must be achieved to avoid early stopping).

### Motivation

EarlyStopping verbose=True has almost no effect.

### Pitch

When doing a run, it would be great to have progress indication of the status of early stopping. i.e. how long until the next early stopping check will be done, and what objective value must be achieved for early stopping not to trigger.

### Alternatives

Watching the progress bar blindly and feeding pigeons bread crumbs when they fly onto my balcony.

Occasionally hitting carriage return at the end of an epoch so I can see what the early stopping objective was at that epoch.

### Additional context

n/a

**Comment by tchaton** [comment]
Dear @turian,

That's a great idea. Would you like to give it a try and make a PR ?

Best,
T.C

**Comment by turian** [comment]
@tchaton do you have any pointers for me?
