### ISSUE TITLE
Improve documentation for EarlyStopping patience parameter

### ISSUE THREAD

**Issue by turian** [PyTorchLightning/pytorch-lightning#6254]
## 📚 Documentation

[EarlyStopping API docs](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.callbacks.early_stopping.html#pytorch_lightning.callbacks.early_stopping.EarlyStopping) currently reads:

```
patience (int) – number of validation epochs with no improvement after which training will be stopped. Default: 3.
```

However, this is quite confusing because 'validation epochs' is not really a term used much in the documentation, and this leads the user to believe this is based upon training epochs. 

I would propose something like the following:

```
patience (int) – number of validation checks with no improvement after which training will be stopped. Default: 3. For example, if `check_val_every_n_epoch=4`, early stopping will take at least 12 training epochs to occur.
```

Related: https://github.com/PyTorchLightning/pytorch-lightning/discussions/6253

**Comment by tchaton** [comment]
Dear @turian,

Great improvement ! Mind making a PR ?

Best,
T.C

**Comment by turian** [comment]
Thank you @tchaton, I have.
