### ISSUE TITLE
all_gather for TPU doesn't support backward gradients.

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#6295]
Currently, we rely on `AllGatherGrad` to compute gather for GPUs.

TODO:
- [] Extend this class to support TPU
- [] Add tests

**Comment by ethanwharris** [comment]
Although all_gather will now work, it still doesn't support grad. so re-opening :)

**Comment by vatch123** [comment]
Is anyone looking into this? I would like to take it up but I would need some help fixing this.

**Comment by edenlightning** [comment]
sorry for the late reply, @vatch123 would be great if you can tackle this! @kaushikb11 can prob help.

**Comment by vatch123** [comment]
Ya sorry for the delayed response. Would love to start on this if someone can describe the issue a little more. Like what is the current state and what do we want to achieve? Thanks
