### ISSUE TITLE
Semantic Segmentation example 

### ISSUE THREAD

**Issue by akshaykvnit** [PyTorchLightning/pytorch-lightning#635]
## 🚀 Feature

Semantic Segmentation example code with dataloading and training implemented.
### Motivation

There are not many examples available for PyTorch Lightning (PL) as of now. A reproducible example illustrating semantic segmentation will be helpful for users to understand how everything works. I had to look around a lot while using PL, i.e. the documentation is not sufficient yet. So, this will improve the situation.
### Pitch

I have already implemented semantic segmentation using PL in my repository [here](https://github.com/akshaykvnit/pl-sem-seg) using the KITTI dataset and a few models (like ResNet50 and 101 FCN, DeepLabv3 - these are available directly in `torchvision`). So, the example will be similar i.e. it will illustrate the dataloading, training step and optimizer configuration steps clearly.

I can open a pull request implementing this if the idea is acceptable.

### Alternatives

The existing examples are too complicated (even the basic ones have way too much functionality mentioned for someone starting out with PL). The basic one is based on MNIST classification while the domain one is on GAN, so this can be an addition to the domain-specific examples.

### Additional context

Check [my repo](https://github.com/akshaykvnit/pl-sem-seg). It took me a lot of time to implement this simple thing :grimacing: and wouldn't have been possible using only the pl-examples in the repo (I had to look around a lot).

**Comment by williamFalcon** [comment]
@akshaykvnit would love this example! want to submit a PR with either the example or a link to an example? a blog post would also  be great, happy to promote it

**Comment by akshaykvnit** [comment]
@williamFalcon I had given a link to an example. [I'll link it here again](https://github.com/akshaykvnit/pl-sem-seg). Please do check it out, and then based on your suggestions, I'll submit a PR.
