### ISSUE TITLE
simple text classification example with ptl

### ISSUE THREAD

**Issue by vr25** [PyTorchLightning/pytorch-lightning#636]
Hi,

Thanks a lot for writing this useful wrapper and the documentation.

I am currently working with text and the examples given in the documentation are related to images. I was wondering if some basic text-related PyTorch to PyTorch lightning framework could be provided in the doc too.

Thanks!

**Comment by isspek** [comment]
I am interested in the example too. I couldn't figure out how to use dataloader with torchtext. It would be nice if there is a simple example for this purpose.

**Comment by williamFalcon** [comment]
The colab in the readme has a BERT example at the end.
