### ISSUE TITLE
ImportError: cannot import name 'Batch' from 'torchtext.data' - pytorch 1.8 and torchtext 0.9

### ISSUE THREAD

**Issue by shrinath-suresh** [PyTorchLightning/pytorch-lightning#6362]
## 🐛 Bug

Unable to import pytorch lightning - 1.2.2 with pytorch 1.8 and torchtext 0.9.

### To Reproduce

Install Pytorch 1.8 - `conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch`
Install torchtext 0.9 - `pip install torchtext`
Install pytorch lightning 1.2.2 - `pip install pytorch_lightning`

Open python prompt and import pytorch lightning

Error log - pytorch_lightning_import_error.log attached
 
[pytorch_lightning_import_error.log](https://github.com/PyTorchLightning/pytorch-lightning/files/6092573/pytorch_lightning_import_error.log)

### Expected behavior

Pytorchlightning package should be imported successfully

### Environment

`* CUDA:
	- GPU:
	- available:         False
	- version:           10.2
* Packages:
	- numpy:             1.19.2
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.0
	- tqdm:              4.50.2
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.8.5
	- version:           #40-Ubuntu SMP Fri Feb 5 23:50:40 UTC 2021`

```
$ pip freeze | grep light
pytorch-lightning==1.2.2
```

**Comment by shrinath-suresh** [comment]
@Borda Thanks for the fix. When can we expect the next release (i see the PR is merged to master) ?

**Comment by ranch-hands** [comment]
hi
will you please tell me how it fixed?
