### ISSUE TITLE
tensorflow version

### ISSUE THREAD

**Issue by vr25** [PyTorchLightning/pytorch-lightning#637]
Hi,

I am getting the following error and I was wondering what tensorflow version is currently supported since I am using 1.11.0.

`module 'tensorflow.io' has no attribute 'gfile'`

Thanks!

**Comment by neggert** [comment]
Tensorflow is no longer required. If you want to use the Tensorboard logger, you need `tensorboard>=1.14`, as specified in the requirements.txt file.

**Comment by Borda** [comment]
FTR, changed in #687
