### ISSUE TITLE
Pytorch lightning spawns processes after each epoch of training, causing training script to crash unexpectedly

### ISSUE THREAD

**Issue by kwanUm** [PyTorchLightning/pytorch-lightning#638]
## 🐛 Bug

When running my training script with PTL, I noticed that after the script is running process spawning is happening at the end of every epoch, which reloads the script. This unintended behavior often causes the training to crash if I'm in the middle of changing the code, and essentially locks the script running from any edits to it.

A possible fix for this is to create the Data Loader object only once [here](https://fburl.com/1x51d9ul).

### To Reproduce

Train with PTL using DDP and num_workers > 1, and place a breakpoint at the top of the main file of your project.

**Comment by neggert** [comment]
That link seems to be FB-internal, so I can't see what you're linking to, but you may be able to solve your problem by defining the dataloader as an attribute, then simply returning the existing dataloader in the `val_dataloader` method.

Early versions of Lightning actually cached the dataloader so that it didn't get re-created every epoch, but there are some use cases that need to create a new DL every time. This way, you have the flexibility to cache it yourself.

**Comment by kwanUm** [comment]
Thanks for your reply Nic, I'll go ahead and try that!

**Comment by williamFalcon** [comment]
@tullie want to look at this?

**Comment by tullie** [comment]
Yep. Will take a look this week

**Comment by tullie** [comment]
@kwanUm i've been unable to reproduce the problem. 

I'm wondering if you're not tagging your test_dataloader with @data_loader. This will ensure that the dataloader is only constructed once like you suggested. See https://github.com/PyTorchLightning/pytorch-lightning/blob/06242c200a318a37d1f882c786e60354ec04533f/pytorch_lightning/core/decorators.py#L5

If that doesn't help, can you please send me some more code of your setup so I can try and reproduce?

**Comment by kwanUm** [comment]
Thanks for trying to check this @tullie.

I haven't defined a test_dataloader method in my PTL Trainer - only overriden train_dataloader().

I'm sorry for not being able to share the code for you to reproduce it yourself, but here's my train_dataloader code (it's annotated correctly):

    @pl.data_loader
    def train_dataloader(self):
        train_dataset = GANTrainingDataset(...)
        if self.distributed_backend == "ddp":
            data_sampler = torch.utils.data.distributed.DistributedSampler(train_dataset,
                                                                           num_replicas=self.num_of_gpus_running,
                                                                           rank=self.logger.rank)
        else:
            data_sampler = torch.utils.data.RandomSampler(train_dataset)
        return DataLoader(
            train_dataset,
            batch_size=self.batch_size,
            sampler=data_sampler,
            num_workers=self.num_workers,
            drop_last=True,
            pin_memory=True,
        )

**Comment by tullie** [comment]
@kwanUm thanks - I was able to reproduce the problem.

My understanding is that you want DataLoader worker processes to be reused after each epoch. There's an issue and suggested work around for that in the pytorch repo here: https://github.com/pytorch/pytorch/issues/15849#issuecomment-573921048

Another suggestion, and what I do, is copy the code base to a separate folder before running distributed training. This ensures any local changes you make won't affect the run. 

Let me know if this helps!

**Comment by kwanUm** [comment]
Copying the code to another location for each run did the trick for me. Thanks!

**Comment by williamFalcon** [comment]
awesome!
