### ISSUE TITLE
Replace `val_check_interval` and `check_val_every_n_epoch` with `val_steps`  and `val_epochs`

### ISSUE THREAD

**Issue by cccntu** [PyTorchLightning/pytorch-lightning#6385]
## 🚀 Feature

Replace `val_check_interval` and `check_val_every_n_epoch` with `val_steps`  and `val_epochs`.
The logic also needs to be modified:
Currently:
* `val_check_interval=n`: n epochs if float;  n steps if int
* `check_val_every_n_epoch=n` n epochs, cannot be used with `float`

Proposed:
* `val_steps=n`: n steps, cannot be used with `float`
* `val_epochs=n` n epochs if float/int

### Motivation

The argument names are confusing.

### Additional context

See:
https://github.com/PyTorchLightning/pytorch-lightning/discussions/6253#discussioncomment-436962
#5413

**Comment by awaelchli** [comment]
Hi @cccntu 

> The argument names are confusing.

Could you add more details why the current names are confusing and why your proposed names would be less confusing?

**Comment by ananthsub** [comment]
@awaelchli @carmocca @tchaton It's slightly tangential to this issue, but for progress tracking we should clarify epochs/steps/batches across train/val/test/predict. e.g. is `step` the number of times `training_step` is called, or the number of times the optimizer is stepped?

**Comment by SkafteNicki** [comment]
Also related issue: https://github.com/PyTorchLightning/pytorch-lightning/issues/4409
That issue proposes that `check_val_every_n_epoch` should be completly removed, and instead `val_check_interval=2.0` should instead mean "do validation every second epoch" (integers will refer to steps and floats will refer to epochs). IMO that is a better solution.

**Comment by cccntu** [comment]
Hi @awaelchli I found it confusing because to specify `n` epoch, I would need to use `val_check_interval` if `n` is float and `check_val_every_n_epoch` if `n` is integer.

But I just realized you could specify `val_check_interval=1.0`.
Though I still think it would be more intuitive to use if we have alias like `val_steps` and `val_epochs`.

**Comment by carmocca** [comment]
> val_check_interval=n: n epochs if float

That's not correct, docs state: "use (float) to check within a training epoch"

> val_steps=n: n steps, cannot be used with float
> val_epochs=n n epochs if float/int

If we were to do this, I'd keep float for fractional usage:

- `val_steps=float`: every `int(val_steps * max_batches_in_epoch)` batches
- `val_epochs=float`: every `int(val_epochs * max_epochs)` epochs
- `val_steps=int`: every `val_steps` batches
- `val_epochs=int`: every `val_epochs` epochs

> is `step` the number of times `training_step` is called, or the number of times the optimizer is stepped?

Currently, the second:

https://github.com/PyTorchLightning/pytorch-lightning/blob/615b2f736303ad3cd56b33111f69952255f01c0f/pytorch_lightning/trainer/training_loop.py#L803-L809

I'd have epochs as full dataloader passes, steps as optimizer steps and batches as training/val/test steps performed

Note that this would make the name `val_steps` confusing, making `val_batches` more appropriate with this convention

> (integers will refer to steps and floats will refer to epochs)

I personally don't like this approach of relying on the type to change the logic.
