### ISSUE TITLE
Make verbose=False prevent showing "Saving latest checkpoint..."

### ISSUE THREAD

**Issue by hobogalaxy** [PyTorchLightning/pytorch-lightning#6408]
## 🚀 Feature
Currently Lightning prints:
```
[lightning][INFO] - Saving latest checkpoint...
```
when running training with `ModelCheckpoint(verbose=False)`.

Not sure if it's a bug or intended...

Can we make it to not log that when passing `verbose=False`?

**Comment by carmocca** [comment]
Sure, just need to check the verbose attribute of the checkpoints here:

https://github.com/PyTorchLightning/pytorch-lightning/blob/38a5fe7af1ba300aa95d7716b5bdee35d52d032b/pytorch_lightning/trainer/training_loop.py#L157-L158

Do you want to open a PR with the fix?

**Comment by hobogalaxy** [comment]
@carmocca I made a PR https://github.com/PyTorchLightning/pytorch-lightning/pull/6419.
