### ISSUE TITLE
Fails to install on google colab

### ISSUE THREAD

**Issue by simonm3** [PyTorchLightning/pytorch-lightning#6415]
Fails to install on colab.

```
!pip install pytorch-lightning
import pytorch_lightning  as pl
```

ImportError: cannot import name 'Batch' from 'torchtext.data' (/usr/local/lib/python3.7/dist-packages/torchtext/data/__init__.py)

**Comment by simonm3** [comment]
I think they just updated the python version to 3.7 because it worked previously

**Comment by simonm3** [comment]
works fine if I uninstall torchtext

**Comment by awaelchli** [comment]
can you install from master and check again please?
`!pip install git+https://github.com/PyTorchLightning/pytorch-lightning`
PR: #6365

**Comment by ricglz** [comment]
It seems like from master works fine

**Comment by simonm3** [comment]
That works.

Though also tried downgrading to previous versions and none of those worked.

**Comment by awaelchli** [comment]
previous version of what?
It's torchtext who removed the legacy Batch class, so you need to downgrade that too

**Comment by ranch-hands** [comment]
> can you install from master and check again please? `!pip install git+https://github.com/PyTorchLightning/pytorch-lightning` PR: #6365

HI, Didnt work on colab

**Comment by simonm3** [comment]
That works
