### ISSUE TITLE
Cannot Import LearningRateLogger

### ISSUE THREAD

**Issue by psbreuning** [PyTorchLightning/pytorch-lightning#6418]
## 🐛 Bug

I have been working with the same code in Colab for some time with no issues. Since today, PL could not be imported (https://github.com/PyTorchLightning/pytorch-lightning/issues/6415). As per linked thread, this is resolved with installing from master, however the following problem still persists:

import pytorch_lightning as pl
from pytorch_lightning.callbacks import LearningRateLogger

ImportError: cannot import name 'LearningRateLogger' from 'pytorch_lightning.callbacks' (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/callbacks/__init__.py)

**Comment by awaelchli** [comment]
This got renamed

`from pytorch_lightning.callbacks import LearningRateMonitor`

**Comment by psbreuning** [comment]
Many thanks :)

**Comment by iamstarlee** [comment]
> This got renamed
> 
> `from pytorch_lightning.callbacks import LearningRateMonitor`

many thanks!
