### ISSUE TITLE
Add neptune.ml logger

### ISSUE THREAD

**Issue by jakubczakon** [PyTorchLightning/pytorch-lightning#642]
## 🚀 Feature
Create NeptuneLogger (similar to CometLogger) to integrate with neptune.ml.

### Motivation

Jakub from neptune.ml here. 
People use our tool to keep track of their deep learning experiments (similar to comet, wandb, mlflow).
As we support ML reasearch (our tool is completely free for individuals and research teams) I figured it would be good for both parties to integrate neptune with pl.
I also saw other tools like Comet, MLFlow, and Wandb with similar integrations here.

### Solution/Pitch

I will prepare a PR with said integration and I only want folks to review/merge it.

**Comment by jakubczakon** [comment]
Truth be told I've already prepared a PR (didn't submit it yet).

I just have one question. How do I update the docs?
Which files do I need to update?

Jakub

**Comment by awaelchli** [comment]
The docs are contained in the source files. See for example [here](https://github.com/williamFalcon/pytorch-lightning/blob/master/pytorch_lightning/logging/__init__.py) for logging. The HTML can be generated with sphinx. See the Makefile in the docs subfolder.

**Comment by jakubczakon** [comment]
Thanks @awaelchli!
Now I understand.
I will update those docs and submit my PR tomorrow/Monday.
