### ISSUE TITLE
powersgd

### ISSUE THREAD

**Issue by titusnicolae** [PyTorchLightning/pytorch-lightning#643]
Powersgd paper shows promising scaling for distributed training.
https://arxiv.org/abs/1905.13727
I'm interested in porting this to pytorch-lightning, do you think it's a good idea?
Thanks

**Comment by jeffling** [comment]
@titusnicolae I'm a big fan of this. I'm not sure if it needs to be a framework level feature, or if we should find a way to make it easy to plug in. But I would _love_ to see a lightning-compatible implementation of this, whether in a PR or as a separate plugin.

**Comment by williamFalcon** [comment]
@titusnicolae @soumith this might be better in PyTorch?

**Comment by Borda** [comment]
@titusnicolae @jeffling any update here?

**Comment by jeffling** [comment]
@titusnicolae  any luck on porting this over? 

If it could be done in a callback, it should be. otherwise, I think if there is enough proof / demand behind this it would make sense to be in the framework.

**Comment by Borda** [comment]
@edenlightning is this in timeline?

**Comment by tchaton** [comment]
Hey @jeffling,

Any updates ? You could make a PR to add it to Lightning directly.

Best,
T.C

**Comment by tchaton** [comment]
Dear @titusnicolae,

PyTorch currently support PowerSGD and it can easily be added by registering builtin DDP Communitation hooks.

Do you want to give it a try ?

Best,
T.C

**Comment by titusnicolae** [comment]
thanks Thomas!
I'll give it a try someday, I'll be busy the following month

**Comment by shuyingsunshine21** [comment]
looks like https://github.com/PyTorchLightning/pytorch-lightning/issues/6727 could cover this scenario :)

**Comment by shuyingsunshine21** [comment]
@titusnicolae , with https://github.com/PyTorchLightning/pytorch-lightning/pull/6736, this should be supported
