### ISSUE TITLE
ImportError when importing pytorch-lightning on Colab

### ISSUE THREAD

**Issue by jordigc2** [PyTorchLightning/pytorch-lightning#6437]
## 🐛 Bug

I am trying to import pytorch-lightning on Colab and I am getting an ImportError on the package torchtext.

I have seen that there is a pull request ready to be approved here #6365 where they check the version of torch and it searches for the Batch package in a different path. I was wondering when will this be available on Colab to use.

Thank you,

**Comment by ayulockin** [comment]
I faced the same issue and was about to raise an issue. Here's a colab [gist](https://colab.research.google.com/gist/ayulockin/1f2cdab08dc186b063bf023ca45a5ca5/pl-error.ipynb).

**Comment by Llcht** [comment]
Same as #6426 #6415

Try using `!pip install git+https://github.com/PyTorchLightning/pytorch-lightning`
Don't forget to **reset the execution environment** before doing it.

**Comment by tchaton** [comment]
Dear @ayulockin,

The bug was resolved on master.

![Screenshot 2021-03-09 at 14.59.17.png](https://images.zenhubusercontent.com/5fa02d9c703c16598a8d683b/53e7ac50-c7e2-47ed-a3d7-6caf9c812661)

Closing this issue.

Best,
T.C
