### ISSUE TITLE
Can't load_from_checkpoint with QuantizationAwareTraining callback during training

### ISSUE THREAD

**Issue by Vozf** [PyTorchLightning/pytorch-lightning#6457]
for PL v1.2.0

```py
LightningModel.load_from_checkpoint(str(ckpt_path))
```
gives
```
  File "//checkpoint/utils.py", line 11, in load_pl_model
    pl_model: LightningModel = LightningModel.load_from_checkpoint(str(ckpt_path))
  File "/.venv/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 156, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "//.venv/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 204, in _load_model_state
    model.load_state_dict(checkpoint['state_dict'], strict=strict)
  File "//.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LightningModel:
Unexpected key(s) in state_dict: "quant.activation_post_process.fake_quant_enabled", "quant.activation_post_process.observer_enabled", "quant.activation_post_process.scale", "quant.activation_post_process.zero_point", "quant.activation_post_process.activation_post_process.eps", "quant.activation_post_process.activation_post_process.min_val", "quant.activation_post_process.activation_post_process.max_val", "model.encoder._bn0.activation_post_process.fake_quant_enabled", "model.encoder._bn0.activation_post_process.observer_enabled", "model.encoder._bn0.activation_post_process.scale", "model.encoder._bn0.activation_post_process.zero_point", .............
```

**Comment by tchaton** [comment]
@Borda

**Comment by Vozf** [comment]
Is there any temporary fix to apply? QAT is basically unusable without checkpoint loading

**Comment by kazhang** [comment]
The error in `load_from_checkpoint` is caused be model quantization preparation is done by checkpoint hook, which is not  triggered by PL module's load_from_checkpoint API. At the checkpoint loading time, Lightning module is not prepared for quantization but the checkpoint has quantization states.

Have we considered to delegate quantization preparation and conversion to PL module itself? In this way, we could call preparation and conversion in module's `on_load_checkpoint` hook. This is the design in my mind:
```
class QuantizationMixin(ABC):
    def prepare_for_quant(self):
        # insert quant and dequant
        # prepare_qat

    def convert_for_quant(self):
        # convert

    def setup_for_quant_checkpoint(self):
        # if model in checkpoint has been prepared
        # self.prepare_for_quant()
        # if model in checkpoint has been convert
        # self.convert_for_quant()

class MyModule(pl.LightningModule, QuantizationMixin):
    def on_load_checkpoint(self, checkpoint):
        self.setup_for_quant_checkpoint()

class QuantizationAwareTraining(Callback):
    def on_fit_start(self, trainer, pl_module):
        pl_module.prepare_for_quant()

    def on_fit_end(self, trainer, pl_module):
        pl_module.convert_for_quant()
```
This design gives several benefits:
1. The checkpoint could be loaded outside of training;
2. Module writer can override `prepare_for_quant` and `convert_for_quant` to define their own customization;
3. Simplifies quantization callback initiation. The same callback could be used across different modules.

**Comment by Borda** [comment]
@kazhang do you prefer to add another mixin (we try to reduce them) or just integrate it with the main LightningMdule?

**Comment by kazhang** [comment]
@Borda  by "integrate it with the main LightningMdule", do you mean adding model preparation and conversion function to the core PyTorch LightningModule? Well it does simplify the requirements for user to use the quant callback, but I'm not sure if it's the right thing to do - adding a function to core LightningModule just for a specific callback.

**Comment by Borda** [comment]
> Is there any temporary fix to apply? QAT is basically unusable without checkpoint loading

well you can load it without strict - `.load_from_checkpoint(str(trainer.checkpoint_callback.best_model_path), strict=False)`

**Comment by Borda** [comment]
> 1. The checkpoint could be loaded outside of training;

on the other hand, this design requires preparing a model which inherits from the `QuantizationMixin` so as a user you can't simply append/deploy quantization for any model you want... right?

**Comment by kazhang** [comment]
> well you can load it without strict, see
In that case, we're just loading an un-quantized model, right? What if users do want to load the in8 weights?

For example, there are post training steps (e.g. adding a wrapper to output tuple instead of dict) that happen on another machine. Trained checkpoint has to be able to load elsewhere.

> this design requires preparing a model which inherits from the QuantizationMixin so as a user you can't simply append/deploy quantization for any model you want... right?

Yup, I don't want to impose this extra constraint, but I couldn't figure out a better way...

**Comment by Borda** [comment]
> > well you can load it without strict, see
> 
> In that case, we're just loading an un-quantized model, right? What if users do want to load the in8 weights?
> 
> For example, there are post training steps (e.g. adding a wrapper to output tuple instead of dict) that happen on another machine. Trained checkpoint has to be able to load elsewhere.

well, no checkpoint contains quantized weights, as you can see in the callback, the quantization is done to the trained model when training ends compare to checkpoints which are saved from during training before the quantization conversion is called...
so if you want to work with the quantized model, you need to save it extra after training but that seems to be not working as the wrapped forward method is not pickable...
```
>       pickler.dump(obj)
E       _pickle.PicklingError: Can't pickle <function RegressionModel.forward at 0x7f7202cb48b0>: it's not the same object as tests.helpers.simple_models.RegressionModel.forward
```
so you need to use  `QuantizationAwareTraining(input_compatible=False)`

> > this design requires preparing a model which inherits from the QuantizationMixin so as a user you can't simply append/deploy quantization for any model you want... right?
> 
> Yup, I don't want to impose this extra constraint, but I couldn't figure out a better way...

I see, but as I just mentioned the checkpoint does not include any quantized weights, just collected statistics to run the conversion "again"

**Comment by yangyyt** [comment]
> I see, but as I just mentioned the checkpoint does not include any quantized weights, just collected statistics to run the conversion "again"

hi, So how should we use quantitative weights?  Calculate quantization weights based on weights and statistical parameters?

**Comment by Borda** [comment]
> hi, So how should we use quantitative weights? Calculate quantization weights based on weights and statistical parameters?

I see two options:
- you would need to save the model after training :100: 
- adding extra arguments which would save as checkpoint already quantized model :+1:

**Comment by yangyyt** [comment]
> * adding extra arguments which would save as checkpoint already quantized model 👍

Thanks for your answer. Firstly, quantized model is already trained. By printing the state_dict of checkpoint,I can see more parameters. but I don't know how to use these.   how should I use these parameters? can you give me a reference? or tell me some ways?
egs:
conv.weight
conv.bias
conv.weight_fake_quant.fake_quant_enabled
conv.weight_fake_quant.observer_enabled
conv.weight_fake_quant.scale 
conv.weight_fake_quant.zero_point 
conv.weight_fake_quant.activation_post_process.eps
conv.weight_fake_quant.activation_post_process.min_val 
conv.weight_fake_quant.activation_post_process.max_val 
conv.activation_post_process.fake_quant_enabled
conv.activation_post_process.observer_enabled 
conv.activation_post_process.scale 
conv.activation_post_process.zero_point
conv.activation_post_process.activation_post_process.eps 
conv.activation_post_process.activation_post_process.min_val 
conv.activation_post_process.activation_post_process.max_val 

how  to get quantitative weights based on the parameters of this layer?

**Comment by kazhang** [comment]
> I see, but as I just mentioned the checkpoint does not include any quantized weights, just collected statistics to run the conversion "again"

Yes, they are statistics. I assume user only need to call `torch.quantization.convert(pl_module, inplace=True)` on a module with those statistics to get the final quantized weights, right?

On a different note, in some use cases, users might want to customize how to quantize the model, for example, only quantize the trunk and keep the head in fp32 so that model is fast enough without losing too much accuracy.

Delegating model preparation to Lightning module itself allows users to 
1. perform such customization. 
2. manually prepare the module and then load the statistics from checkpoint post training.

**Comment by yangyyt** [comment]
Thank you very much.  I have search and read some introductions, so I sort of get an idea of what to do. After the model training is completed, the weight of floating point should be converted to fixed-point weight according to scale and zero point. However, calling torch.quantization.convert(pl_module, inplace=True) on a module can only generate these statistics, not the final quantized weight.

**Comment by Borda** [comment]
> On a different note, in some use cases, users might want to customize how to quantize the model, for example, only quantize the trunk and keep the head in fp32 so that model is fast enough without losing too much accuracy.

I guess you are talking about #8069

> I assume user only need to call `torch.quantization.convert(pl_module, inplace=True)` on a module with those statistics to get the final quantized weights, right?

the tricky part is that you need to do exactly the same conversion as you did before, so now implementing with resume from a checkpoint, see #8485

**Comment by yangyyt** [comment]
> so now implementing with resume from a checkpoint

emmm,  trainer = pl.Trainer(resume_from_checkpoint=model_path, callbacks=[QuantizationAwareTraining()]) can resume from a checkpoint to train continuedly. but I only want to load the quant model that someone else has trained,  and test the model. QuantizayionAwarwTraining  of pytorch is okay to load the quant model,  but pytorch-lightning is not okay.  That's true, right？

**Comment by yangyyt** [comment]
> so now implementing with resume from a checkpoint

emmm,  trainer = pl.Trainer(resume_from_checkpoint=model_path, callbacks=[QuantizationAwareTraining()]) can resume from a checkpoint to train continuedly. but I only want to load the quant model that someone else has trained,  and test the model. QuantizayionAwarwTraining  of pytorch is okay to load the quant model,  but pytorch-lightning is not okay.  That's true, right？
