### ISSUE TITLE
Missing documentation for limit_predict_batches

### ISSUE THREAD

**Issue by kkirtac** [PyTorchLightning/pytorch-lightning#6490]
Hi. Documentation is missing for `limit_predict_batches` in [Trainer](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/trainer.py#L115).

**Comment by rohitgr7** [comment]
@kkirtac mind send a PR with updated docs?

**Comment by kkirtac** [comment]
Thanks but I don't think I can. I am particularly interested to know what is this feature for but I can't find any documentation.

**Comment by rohitgr7** [comment]
@kkirtac it's similar to limit_train/val/test_batches. just limit the number of batches from the dataloader while calling `trainer.predict`.

**Comment by carmocca** [comment]
> I am particularly interested to know what is this feature for but I can't find any documentation.

Hi! There is no public documentation for this yet as it is an experimental feature and subject to change. Use at your own discretion.
