### ISSUE TITLE
trainer.predict method should return iterator instead of list

### ISSUE THREAD

**Issue by csarron** [PyTorchLightning/pytorch-lightning#6508]
## 🚀 Feature

trainer.predict method should return iterator instead of a list of predictions to avoid out of memory error

### Motivation
returning list of predictions can easily cause out of memory on GPUs

### Pitch

wrap the trainer.predict method to an iterator, so getting predictions can be something like:

```
for pred in trainer.predict(model, datamodule=dm):
    # do something with pred
```

**Comment by thomasahle** [comment]
This would be very useful for those of us that can't fit the entire predicted dataset in memory.
