### ISSUE TITLE
How do you use the hidden state from the previous training step in the next step?

### ISSUE THREAD

**Issue by n2cholas** [PyTorchLightning/pytorch-lightning#655]
I want to train an LSTM Language Model using Lightning, but I need to pass the previous step's hidden state to the next training step. The raw training loop looks something like this:

```Python
model.train()
hidden = model.init_hidden(batch_size)
for data in train_iter:
  text, target = data.text, data.target
  model.zero_grad()
  output, hidden = model(text, hidden)
  hidden = detach_tensors(hidden)  # for truncated bptt
  loss = criterion(output.view(-1, vocab_size), target.view(-1))
  loss.backward()

  optimizer.step()
```

How can I achieve this with Lightning? Thanks!

**Comment by BaohaoLiao** [comment]
I think you can define a variable in the model initialization for saving the hidden state of the previous step. For example:
class model(LightningModule):
    def __init__(self, args):
        super().__init__()
        self.previous_hidden = None  # cache
    def training_step():
        output, hidden = model(text, self.previous_hidden)
        self.previous_hidden = detach_tensors(hidden)

**Comment by williamFalcon** [comment]
Correct!

**Comment by shivdhar** [comment]
Would it be fair to say that this advice has been superseded by the `bptt` argument in `Trainer`?

**Comment by williamFalcon** [comment]
yes! 0.9.0 makes this very clear. check out the latest master docs

**Comment by shivdhar** [comment]
Thanks for the clarity!
