### ISSUE TITLE
Resume training fails with BackboneFinetuning callback.

### ISSUE THREAD

**Issue by its-dron** [PyTorchLightning/pytorch-lightning#6551]
## 🐛 Bug

Unable to resuming training when using BackboneFinetuning callback. 

`AttributeError: 'BackboneFinetuning' object has no attribute 'previous_backbone_lr'`

### To Reproduce

https://colab.research.google.com/drive/1RLKD3ISkGmAcy308GWUF57UTAoavdVcr?usp=sharing

### Expected behavior

BackboneFinetuning state should be saved in checkpoint, and be resumed. 

### Environment

* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.0+cu101
	- pytorch-lightning: 1.2.3
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.10
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

**Comment by its-dron** [comment]
Another use case that would break this is attempting to add BackboneFinetuning when resuming a checkpoint to further finetune on e.g. another dataset. However, I see this as an abuse of `resume_from_checkpoint`, and instead one should be directed to start a new training job using the checkpoint as a model initialization, rather than resuming mid training job.

**Comment by tchaton** [comment]
Dear @its-dron,

Thanks for reporting this bug.

Best,
T.C

**Comment by ethanwharris** [comment]
Hi @its-dron, this seems to be working for me on the master branch :) Can you confirm that this is the case by switching the first line (install pytorch-lightning) to
`! pip install git+https://github.com/PytorchLightning/pytorch-lightning.git --upgrade`?

**Comment by its-dron** [comment]
No go, I get the exact same error.

**Comment by ethanwharris** [comment]
Hi @its-dron, could you check that `pytorch-lightning.__version__` is 1.3.0.dev? Your notebook is definitely working for me when the first cell has:
`# ! pip install pytorch-lightning --upgrade`
`! pip install git+https://github.com/PytorchLightning/pytorch-lightning.git --upgrade`
Note that you have to uncomment the `pip install git+...` line and comment out the regular `pip install ...`. You may also need to reset the runtime for the change to work. 
Hope that helps :smiley:

**Comment by its-dron** [comment]
Ah, it worked this time. Thanks!

**Comment by ethanwharris** [comment]
@its-dron Cool :smiley: I'll close this issue
