### ISSUE TITLE
pytorch lightning: optimizer got an empty parameter list

### ISSUE THREAD

**Issue by moloxl** [PyTorchLightning/pytorch-lightning#6554]
## 🐛 Bug

Hi, I was trying a simple VAE model using Pytorch lightning. 
I defined the optimizers the same as the lightning website:

    def configure_optimizers(self):
        optimizer = optim.Adam(self.parameters(), lr=1e-3)
        return optimizer

### Got error about the **optimizer**:

  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\optim\optimizer.py", line 46, in __init__
    raise ValueError("optimizer got an empty parameter list")

ValueError: optimizer got an empty parameter list

### Data:

data = np.random.rand(20,2,8)
h_dim = 10;
z_dim = 2;

### Model:

class Model(pl.LightningModule):

    def __init__(self, data):
        super(Model, self).__init__()
        
        self.data = data
        self.train_data, self.test_data = train_test_split(data, 
                                           train_size=0.8, 
                                           random_state=42)
        
    def sampling(self, z_mean, z_log_sigma):
        std = z_log_sigma.mul(0.5).exp_()
        esp = torch.randn(*z_mean.size())
        z = z_mean + std * esp
        return z
    
    def encoder(self, inp):
        z = nn.Linear(8, 32)(inp)
        z_mean = nn.Linear(32, h_dim)(z)
        z_log_sigma = nn.Linear(32, h_dim)(z)
        return z_mean, z_log_sigma 
    
    def decoder(self, inp_z):
        out = nn.Linear(h_dim,8)(inp_z)
        return out
        
    def vae_loss(self, inp, out, z_mean, z_log_sigma):
        kl = -0.5 * torch.mean( 1 + z_log_sigma - z_mean**2 - z_log_sigma.exp() )
        return kl
    
    def forward(self, inp):
        z_mean, z_log_sigma = self.encoder(inp)
        inp_z = self.sampling(z_mean, z_log_sigma)
        out =  self.decoder(inp_z)
        return z_mean, z_log_sigma, out
    
    def configure_optimizers(self):
        optimizer = optim.Adam(self.parameters(), lr=1e-3)
        return optimizer
    
    def training_step(self, inp):
        z_mean, z_log_sigma, out = self.forward(inp)
        loss = self.vae_loss(inp, out, z_log_sigma, z_mean)
        return loss
    
    def train_dataloader(self): 
        return DataLoader(self.train_data, batch_size = 10)

**Comment by i-aki-y** [comment]
Your model looks purely functional. This means that the model has no properties that store learned weights.
I guess this is why the `self.parameters()` can not return anything.
What happen if you declare your layers in `__init__()` as properties and apply them in the `encode()` or `decode()` functions?

ex.

```
class Model(pl.LightningModule):

    def __init__(self, data):
        ...
        self.enc_lin = nn.Linear(8, 32)
        ...

    def encode(self, inp):
        z = self.enc_lin(inp)
        ...

```

**Comment by justusschock** [comment]
@i-aki-y is right. Also note, that if you recreate instances of the layer each time, you cannot optimize them, since there are always new parameters.

**Comment by awaelchli** [comment]
Here in bolts is an example VAE, this should help you get started.
https://github.com/PyTorchLightning/lightning-bolts/blob/master/pl_bolts/models/autoencoders/basic_vae/basic_vae_module.py

**Comment by moloxl** [comment]
> Your model looks purely functional. This means that the model has no properties that store learned weights.
> I guess this is why the `self.parameters()` can not return anything.
> What happen if you declare your layers in `__init__()` as properties and apply them in the `encode()` or `decode()` functions?
> 
> ex.
> 
> ```
> class Model(pl.LightningModule):
> 
>     def __init__(self, data):
>         ...
>         self.enc_lin = nn.Linear(8, 32)
>         ...
> 
>     def encode(self, inp):
>         z = self.enc_lin(inp)
>         ...
> ```

@i-aki-y @justusschock Thank you so much!! It works!! I have to first define everything in __init__()!
