### ISSUE TITLE
[BUG] got an unexpected keyword argument 'train_percent_check' when using trainer

### ISSUE THREAD

**Issue by aoussou** [PyTorchLightning/pytorch-lightning#6557]
## 🐛 Bug

train_percent_check option does not work:

```
Traceback (most recent call last):
  File "train_lightning.py", line 364, in <module>
    trainer = pl.Trainer(train_percent_check=0.1,gpus=2)
  File "/home/anaconda3/envs/nvidia-seg-pt15/lib/python3.6/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 42, in overwrite_by_env_vars
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'train_percent_check'
```

Runs fine if I don't use the keyword.

Code:
```
if __name__ == '__main__':
    trainer_sys = TrainSystem()    
    trainer = pl.Trainer(train_percent_check=0.1,gpus=1)    
    trainer.fit(trainer_sys)
```

### Environment

cudatoolkit               10.2.89              hfd86e86_1  
python                    3.6.13               hdb3f193_0  
pytorch                   1.5.1           py3.6_cuda10.2.89_cudnn7.6.5_0    pytorch
pytorch-lightning         1.2.3              pyhd8ed1ab_0    conda-forge
torchvision               0.6.1                py36_cu102    pytorch

GPU: 2080 Ti

**Comment by awaelchli** [comment]
Hi, this trainer argument got renamed a long time ago. You were probably looking at an old documentation. 
The new argument name is `limit_train_batches`, can be float for a fraction or int for a number of batches.

**Comment by awaelchli** [comment]
https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html#limit-train-batches

**Comment by aoussou** [comment]
@awaelchli 

Thank you very much. You might want to update this video because that's what I was taking as a reference:

https://www.youtube.com/watch?v=QHww1JH7IDU

**Comment by awaelchli** [comment]
The video is a bit old already, the API has changed a lot since then.
@edenlightning Can we add a note to the description of the video that this is for an outdated version of Lightning?
