### ISSUE TITLE
remove `tests` folder from packaging

### ISSUE THREAD

**Issue by orctom** [PyTorchLightning/pytorch-lightning#6558]
As you can see,`tests` is not under the `pytorch_lightning` namespace.
Not an issue, but it's not correct.

> site-packages/pl_examples/*
site-packages/pytorch_lightning-1.0.8.dist-info/*
site-packages/pytorch_lightning/*
site-packages/tests/backends/*
site-packages/tests/base/*
site-packages/tests/callbacks/*
site-packages/tests/checkpointing/*
site-packages/tests/core/*
site-packages/tests/loggers/*
site-packages/tests/metrics/*
site-packages/tests/models/*
site-packages/tests/plugins/*
site-packages/tests/trainer/*
site-packages/tests/tuner/*
site-packages/tests/utilities/*

It was first added in [0.5.3.2](https://github.com/PyTorchLightning/pytorch-lightning/blob/0.5.3.2/setup.py#L49)

**Comment by kaushikb11** [comment]
@Borda What's your opinion? Something we should look into.

**Comment by Borda** [comment]
yes, it shall not be there...

**Comment by Borda** [comment]
@orctom just tested and lited package of actual master and there are no more tests [SOURCES.txt](https://github.com/PyTorchLightning/pytorch-lightning/files/6174115/SOURCES.txt)
These tests shall be ancient so feel free to remove them and no worries that with installation you would get any new 🐰
