### ISSUE TITLE
Training stalls with DDP multi-GPU setup

### ISSUE THREAD

**Issue by sivakhno** [PyTorchLightning/pytorch-lightning#6569]
## 🐛 Bug

My training / validation step gets hung when using ddp on 4-GPU AWS instance.
Usually it happens at the end of the first epoch, but sometimes in the middle of it.
Code runs fine on 1 GPU. 
My model checkpoint is a very basic set up 
```
checkpoint_callback = pl.callbacks.ModelCheckpoint(
        args.checkpointdir,
        save_last=True)
```
as is the trainer 
```
        trainer = pl.Trainer(
            progress_bar_refresh_rate=1000,
            log_every_n_steps=1000,
            max_epochs=model_config['epochs'],
            gradient_clip_val=0.5,
            gpus=-1,
            accelerator='ddp',
            plugins=[pl.plugins.DDPPlugin(find_unused_parameters=True)],
            callbacks=[checkpoint_callback])
```

I know there is a related issue https://github.com/PyTorchLightning/pytorch-lightning/issues/4612, but in my case the hanging happens non-deterministically.

Funnily if I use subset of data using `--limit_train_batches ` the trains runs fine. However, I monitor GPU mem usage and it never goes above 91/92%.

Any suggestions would be most appreciated. 

Is there a way to at least induce an error message and failure. For example, on AWS SageMaker, stalled model does not fail the job and it continues accumulating costs.
I do not want to use other parallel backends as they are much slower making 4-GPU parallelism cost-ineffective. 

### Expected behavior

Model runs in multi-gpu DDP model without stalling. 

### Environment

Using AWS p3* instances

* CUDA:
	- GPU:
		- Tesla V100-SXM2-16GB
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.20.1
	- pyTorch_debug:     False
	- pyTorch_version:   1.4.0 (also tried 1.6.0)
	- pytorch-lightning: 1.2.3
	- tqdm:              4.57.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.8.5
	- version:           #40-Ubuntu SMP Fri Feb 5 23:50:40 UTC 2021

**Comment by tchaton** [comment]
Dear @sivakhno,

Could you update to master ? We resolve some bugs with DDP hanging.

If the problem persists, could you create a reproducible script using the BoringModel ? 

Best,
T.C

**Comment by NielsRogge** [comment]
Same issue, it doesn't even start for me. 

This is my hardware (2 GPU's on one machine):
```
!nvidia-smi
Thu Mar 18 13:43:52 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  On   | 00000000:01:00.0 Off |                  N/A |
|  0%   59C    P8    27W / 260W |   2370MiB / 11018MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  On   | 00000000:02:00.0 Off |                  N/A |
|  0%   58C    P8    23W / 260W |      4MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      9630      C   ...env_datascouts/bin/python     2281MiB |
|    0   N/A  N/A     28915      G   /usr/lib/xorg/Xorg                 27MiB |
|    0   N/A  N/A     28947      G   /usr/bin/gnome-shell               56MiB |
+-----------------------------------------------------------------------------+
```

My code (the dummy example from [this tutorial](https://pytorch.org/tutorials/beginner/blitz/data_parallel_tutorial.html)):

```
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import pytorch_lightning as pl

# Parameters and DataLoaders
input_size = 5
output_size = 2

batch_size = 30
data_size = 100

class RandomDataset(Dataset):

    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len

train_loader = DataLoader(dataset=RandomDataset(input_size, data_size),
                         batch_size=batch_size, shuffle=True)

class Model(pl.LightningModule):

    def __init__(self, input_size, output_size):
        super(Model, self).__init__()
        self.fc = nn.Linear(input_size, output_size)

    def forward(self, input):
        output = self.fc(input)
        return output

    def training_step(self, batch, batch_nb):
        x, y = batch
        loss = F.cross_entropy(self(x), y)
        return loss

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=0.02)

# Init our model
model = Model(input_size, output_size)

# Initialize a trainer
trainer = pl.Trainer(gpus=2, accelerator='ddp', max_epochs=3, progress_bar_refresh_rate=20)

# Train the model ⚡
trainer.fit(model, train_loader)
```

However, when running this, all I get is:

```
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
Missing logger folder: /home/(...)/lightning_logs
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
```

**Comment by Akanni96** [comment]
I've also faced a problem with code stuck on "initializing ddp". After much work, I solved my problem by simply adding `num_sanity_val_steps=0` as an argument to `Trainer(...)`

**Comment by awaelchli** [comment]
Hi I tried your script and it works on 1.2.3 and master.
Could you run with `NCCL_DEBUG=INFO python train.py` and paste the output?

**Comment by edenlightning** [comment]
@sivakhno friendly ping :)

**Comment by edenlightning** [comment]
feel free to reopen

**Comment by aminsaied** [comment]
I'm having the same issue. I've repro'd with the boring model. This is what I see:

- Passing `accelerator="ddp"` the job hangs at this stage:

    ```
    GPU available: True, used: True
    TPU available: None, using: 0 TPU cores
    initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
    ```
- Not passing `accelerator` argument the job completes

    ```
    UserWarning: You requested multiple GPUs but did not specify a backend, e.g. `Trainer(accelerator="dp"|"ddp"|"ddp2")`. Setting `accelerator="ddp_spawn"` for you.
  warnings.warn(*args, **kwargs)
    GPU available: True, used: True
    TPU available: None, using: 0 TPU cores
    2021-05-28 16:14:45.121192: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: 
    /opt/miniconda/lib/python3.7/site-packages/dotnetcore2/bin/deps
    2021-05-28 16:14:45.121308: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
    initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
    initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
    ...
    --------------------------------------------------------------------------------
    DATALOADER:0 TEST RESULTS
    {'test_loss': -0.284157931804657}
    --------------------------------------------------------------------------------
    ```
- Passing `plugins=[DDPPlugin(find_unused_parameters=False)]` has same behavior as passing `accelerator='ddp'`

Observations/comments:
- I am running with environment variable NCCL_DEBUG=INFO, but for `accelerator='ddp'` it doesn't get far enough to print anything. I can share the debug info from the ddp_spawn run if you think that helps.
- How significant do you think this warning is: tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/miniconda/lib/python3.7/site-packages/dotnetcore2/bin/deps
  - I was turning a blind eye because I have used this image to run ddp training previously
  - I can provide the dockerfile if that helps

Here's my environment:

Using Azure ML Standard_NC12s_v3 (2 x NVIDIA Tesla V100)

* CUDA:
	- GPU:
		- Tesla V100-PCIE-16GB
		- Tesla V100-PCIE-16GB
	- available:         True
	- version:           11.0
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0+cu110
	- pytorch-lightning: 1.2.4
	- tqdm:              4.49.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.7
	- version:           #38-Ubuntu SMP Sun Mar 22 21:27:21 UTC 2020

**Comment by aminsaied** [comment]
Update: I was able to resolve the issue by updating my image. Unfortunately I updated multiple things at once, so I can't say for sure what the root cause was, but the issue was at least resolved for me with the following set up:

* CUDA:
	- GPU:
		- Tesla V100-PCIE-16GB
		- Tesla V100-PCIE-16GB
	- available:         True
	- version:           11.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.1+cu111
	- pytorch-lightning: 1.3.3
	- tqdm:              4.51.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.10
	- version:           #38-Ubuntu SMP Sun Mar 22 21:27:21 UTC 2020

In addition the image update also addressed the libcudart issue mentioned:

Successfully opened dynamic library libcudart.so.11.0

Hope that helps.

**Comment by zhengyaogu** [comment]
I have a similar problem as @sivakhno . Here's the NCCL INFO I was able to capture. The terminal refreshed really fast, so the transcript below is only partial.

```
ip-172-31-91-31:17102:17338 [1] NCCL INFO Channel 00 : 1[1c0] -> 0[1b0] via direct shared memory
ip-172-31-91-31:17152:17336 [2] NCCL INFO Channel 00 : 2[1d0] -> 1[1c0] via direct shared memory
ip-172-31-91-31:17019:17335 [0] NCCL INFO Could not enable P2P between dev 0(=1b0) and dev 3(=1e0)
ip-172-31-91-31:17225:17337 [3] NCCL INFO Could not enable P2P between dev 3(=1e0) and dev 2(=1d0)
ip-172-31-91-31:17102:17338 [1] NCCL INFO Could not enable P2P between dev 1(=1c0) and dev 0(=1b0)
ip-172-31-91-31:17152:17336 [2] NCCL INFO Could not enable P2P between dev 2(=1d0) and dev 1(=1c0)
ip-172-31-91-31:17019:17335 [0] NCCL INFO Could not enable P2P between dev 0(=1b0) and dev 1(=1c0)
ip-172-31-91-31:17019:17335 [0] NCCL INFO Channel 01 : 0[1b0] -> 1[1c0] via direct shared memory
ip-172-31-91-31:17225:17337 [3] NCCL INFO Could not enable P2P between dev 3(=1e0) and dev 0(=1b0)
ip-172-31-91-31:17225:17337 [3] NCCL INFO Channel 01 : 3[1e0] -> 0[1b0] via direct shared memory
ip-172-31-91-31:17102:17338 [1] NCCL INFO Could not enable P2P between dev 1(=1c0) and dev 2(=1d0)
ip-172-31-91-31:17152:17336 [2] NCCL INFO Could not enable P2P between dev 2(=1d0) and dev 3(=1e0)
ip-172-31-91-31:17102:17338 [1] NCCL INFO Channel 01 : 1[1c0] -> 2[1d0] via direct shared memory
ip-172-31-91-31:17152:17336 [2] NCCL INFO Channel 01 : 2[1d0] -> 3[1e0] via direct shared memory
ip-172-31-91-31:17225:17337 [3] NCCL INFO Could not enable P2P between dev 3(=1e0) and dev 2(=1d0)
ip-172-31-91-31:17225:17337 [3] NCCL INFO Channel 01 : 3[1e0] -> 2[1d0] via direct shared memory
ip-172-31-91-31:17019:17335 [0] NCCL INFO Could not enable P2P between dev 0(=1b0) and dev 1(=1c0)
ip-172-31-91-31:17102:17338 [1] NCCL INFO Could not enable P2P between dev 1(=1c0) and dev 2(=1d0)
ip-172-31-91-31:17152:17336 [2] NCCL INFO Could not enable P2P between dev 2(=1d0) and dev 3(=1e0)
ip-172-31-91-31:17102:17338 [1] NCCL INFO Could not enable P2P between dev 1(=1c0) and dev 0(=1b0)
ip-172-31-91-31:17152:17336 [2] NCCL INFO Could not enable P2P between dev 2(=1d0) and dev 1(=1c0)
ip-172-31-91-31:17102:17338 [1] NCCL INFO Channel 01 : 1[1c0] -> 0[1b0] via direct shared memory
ip-172-31-91-31:17152:17336 [2] NCCL INFO Channel 01 : 2[1d0] -> 1[1c0] via direct shared memory
ip-172-31-91-31:17019:17335 [0] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
ip-172-31-91-31:17019:17335 [0] NCCL INFO comm 0x7f6808001060 rank 0 nranks 4 cudaDev 0 busId 1b0 - Init COMPLETE
ip-172-31-91-31:17019:17019 [0] NCCL INFO Launch mode Parallel
ip-172-31-91-31:17225:17337 [3] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
ip-172-31-91-31:17225:17337 [3] NCCL INFO comm 0x7fdea0001060 rank 3 nranks 4 cudaDev 3 busId 1e0 - Init COMPLETE
ip-172-31-91-31:17102:17338 [1] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
ip-172-31-91-31:17152:17336 [2] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
ip-172-31-91-31:17102:17338 [1] NCCL INFO comm 0x7f6c90001060 rank 1 nranks 4 cudaDev 1 busId 1c0 - Init COMPLETE
ip-172-31-91-31:17152:17336 [2] NCCL INFO comm 0x7fe4d4001060 rank 2 nranks 4 cudaDev 2 busId 1d0 - Init COMPLETE
```

**Comment by import-antigravity** [comment]
Can we re-open this? I'm having the same problem on PTL 1.5.10

**Comment by akihironitta** [comment]
@import-antigravity Could you create another issue if you don't mind since this issue is outdated and some written here may not apply to your issue just in case?

**Comment by import-antigravity** [comment]
Actually, the problem was that I'm using SLURM and I need to set the node to `--exclusive` mode
