### ISSUE TITLE
Trainer.predict(), LightningModule.predict(), and LightningDataModule.predict_dataloader() are not in documentation

### ISSUE THREAD

**Issue by norabelrose** [PyTorchLightning/pytorch-lightning#6574]
## 📚 Documentation

Currently the `Trainer.predict()` method, along with the `LightningModule.predict()` and `LightningDataModule.predict_dataloader()` hooks, are not mentioned anywhere in the documentation so users don't know about their existence unless they've read through the source files. This led to confusion on my part since I saw the `write_prediction` and `write_prediction_dict` methods get added to `LightningModule`, as well as the `limit_predict_batches` Trainer flag, but it wasn't clear how you were supposed to actually use them.

PS: While we're at it, the `training`, `testing`, `predicting`, `tuning`, and `evaluating` properties on `Trainer` aren't in the documentation either. I'm not sure if that is intentional or not— I can understand not wanting to expose the setters as public APIs— but the getters are definitely useful if the core `training_step`, `validation_step`, etc. methods on your `LightningModule` call helper methods that in turn need to know what stage they're in.

**Comment by tchaton** [comment]
Dear @norabelrose,

It is currently done in purpose. 
The API is still in beta and likely to slightly change.
We didn't change to share too much about it.

If you are interested to see where it is going:
In Flash: 
We are introducing a new object called DataPipeline: https://github.com/PyTorchLightning/lightning-flash/pull/141
It aims at simplifying your processing code and makes deployment easier. 

In Lightning
https://github.com/PyTorchLightning/pytorch-lightning/pull/6577

Best regards,
T.C
