### ISSUE TITLE
during training, model not able to save checkpoint at the end of every epoch

### ISSUE THREAD

**Issue by shahbaznazami** [PyTorchLightning/pytorch-lightning#6597]
## 🐛 Bug

when I try to train the model, the model not saving checkpoint at the end of every epoch

 - PyTorch Version : 1.1.4
 - OS:  Linux 18.04 
 - How you installed PyTorch (`conda`, `pip`, source): conda 
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: cuda 10.0 
 - GPU models and configuration: cuda 10.0

**Comment by kaushikb11** [comment]
Hi @shahbaznazami! That shouldn't be the case. Would you mind sharing a snippet of your code to look at? Also, would recommend going through these [docs](https://pytorch-lightning.readthedocs.io/en/latest/common/weights_loading.html).

**Comment by awaelchli** [comment]
closing for now, because some information is missing. 

pay close attention to warning messages printed in the terminal, or maybe you are using a metric monitor for a training metric. This is currently not supported but will be soon #7033
