### ISSUE TITLE
[RFC] Let Logger base class inherit from Callback

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#6606]
## 🚀 Feature

We could consider having loggers inherit the Callback base class.

### Motivation

This would enable third party loggers to perform additional features during the progression of training.
One example is uploading checkpoint files in WandB: #6231
It would make it significantly easier to add these features without tightly coupling them to the rest of the Trainer logic.

Also recently there was a feature request to add state persistence to loggers #6361. We would face similar challenges as we have with callbacks. But if we allow loggers to implement the callback methods, and when we solve #6467, then this would also enable #6361 to move forward without problem.

### Pitch

```python
# now
class LightningLoggerBase(ABC):

# pitch
class LightningLoggerBase(Callback, ABC):
```

### Alternatives

Keep Loggers as they are. For new features, we would have to introduce special new hook just for the logger.

cc @borda @awaelchli @edward-io @ananthsub @rohitgr7 @kamil-kaczmarek @Raalsky @Blaizzy @daniellepintz

**Comment by tchaton** [comment]
Sound like a good idea ! Do you see any cons ?

**Comment by ananthsub** [comment]
by implementing it as a callback, some question emerge like:
- do we need to re-order callback execution to handle loggers now? what if other callbacks want to log through the module? 
- would this make loggers harder to use outside of lightning?

**Comment by borisdayma** [comment]
I think it's possible loggers would have to occur last.

Also it would be good to take advantage to add a `after_save_checkpoint` method that happens **after** saving the model to upload it (`on_save` happens before).
