### ISSUE TITLE
Extract dataset definition out of the LightningModule

### ISSUE THREAD

**Issue by cgarciae** [PyTorchLightning/pytorch-lightning#662]
## 🚀 Feature
Extract dataset definition out of the `LightningModule`

### Motivation
Separation of data from the model. 

### Pitch
The datasets loaders could easily be passed to the `fit` method directly instead of having to define them inside the `LightningModule`, this avoids having a single class that possibly contains: data, data pipeline params, model, model hyperparams.

The basic example cloud look like this:

```python
from pytorch_lightning import Trainer

train_dataloader = DataLoader(...)
val_dataloader = DataLoader(...)

model = CoolSystem()

# most basic trainer, uses good defaults
trainer = Trainer()    
trainer.fit(model, train_dataloader=train_dataloader, val_dataloader=val_dataloader)
```

Its much more natural to how you usually structure your code in `scikit-learn` or `keras`.

### Alternatives
They could also be based to the `Trainer`s constructor.

**Comment by williamFalcon** [comment]
Why not allow for both? add 3 args to trainer or do it in .fit().  

if any of these datasets are passed in the corresponding lightningModule class isn’t called. 

thoughts?

**Comment by williamFalcon** [comment]
@cgarciae want to submit this PR? i agree that we should allow both ways of doing it

**Comment by awaelchli** [comment]
@cgarciae can the issue be closed or is there something left to do?

**Comment by cgarciae** [comment]
Looks awesome!

**Comment by williamFalcon** [comment]
@lorenzoFabbri @tullie @myleott @ashwinb @shootingsoul @vreis @darktex
