### ISSUE TITLE
`max_nb_epochs` not effective in master branch

### ISSUE THREAD

**Issue by esvhd** [PyTorchLightning/pytorch-lightning#663]
Hi,

I think this might be an easy one to fix. I'm using the bleeding edge version from master with `pytorch 1.3`. 

`Trainer(max_nb_epochs=...)` does not limit the max epochs in training at the moment. See [doc](https://williamfalcon.github.io/pytorch-lightning/Trainer/Training%20Loop/#force-training-for-min-or-max-epochs)

I think this is due to the following code and default setting:

https://github.com/williamFalcon/pytorch-lightning/blob/c32f2b91164abe309dd8456a16c01e9c35748bff/pytorch_lightning/trainer/trainer.py#L160-L164

But `max_epochs` has default set to 1000:

https://github.com/williamFalcon/pytorch-lightning/blob/c32f2b91164abe309dd8456a16c01e9c35748bff/pytorch_lightning/trainer/trainer.py#L75

Therefore by default if you only set `max_nb_epochs=`, the following is never called. Hence `max_epochs` will continue to be 1000.

https://github.com/williamFalcon/pytorch-lightning/blob/c32f2b91164abe309dd8456a16c01e9c35748bff/pytorch_lightning/trainer/trainer.py#L163-L164

This logic probably needs some enhancement, or let just one of these max epoch parameters drive training. Open to suggestions and happy to get a PR going based on what's decided. 

Thanks.

**Comment by Borda** [comment]
yes, it is a deprecated option

**Comment by esvhd** [comment]
Right, which one would be deprecated, `max_epochs` or `max_nb_epochs`? Thx

**Comment by Borda** [comment]
the `max_epochs` remains =]

**Comment by esvhd** [comment]
Make sense. Deprecating `max_nb_epochs` would involve quite a bit of changes and doc updates. How should we handle that? Warn in next version and officially deprecate in a future version? 

Would need a temporary fix anyway if it'd only be deprecated in a future version. Happy to help here. If there is an issue on deprecation that I can look at I'm happy to follow the process etc.

**Comment by williamFalcon** [comment]
@esvhd new  docs have this change
