### ISSUE TITLE
Detect if running in a real terminal and adapt prog_bar logic accordingly

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#6647]
## Please reproduce using the BoringModel

Currently, the progress bar doesn't make distinction between running in a real terminal or being piped to logs.

When Lightning run in logs, it produces a prog_bar line for each change.

<img width="1659" alt="Screenshot 2021-03-23 at 09 10 40" src="https://user-images.githubusercontent.com/12861981/112121895-a648d880-8bb7-11eb-8f7a-15f02eaeb013.png">

Todos:
* Detect if Lightning is running within a real terminal
* Adapt logging logic if not

 https://stackoverflow.com/questions/1077113/how-do-i-detect-whether-sys-stdout-is-attached-to-terminal-or-not

### To Reproduce

Use following [**BoringModel**](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing) and post here

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

* `IDE`: Please, use our python [bug_report_model.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
) template.

* `Colab Notebook`: Please copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py) (or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by pbsds** [comment]
I'm training in a SLURM cluster, and to be able to review the written logs i hav eto replace `\r` with `\n` with `sed`.
It would be nice if the progress bar is printed on new lines when no tty is detected. I would also appreciate if a timedelta since the start of training could be printed along with the progress bar updates when no tty is detected.

**Comment by tchaton** [comment]
Dear @pbsds, do you want to make a PR ?

**Comment by arvindmuralie77** [comment]
As mentioned in this [link](https://github.com/tqdm/tqdm/issues/750#issuecomment-537558122)  if we override tqdm.tqdm.status_printer() and replace `\n` with `\r`, then the progress bar is being printed on a new line. 
![git](https://user-images.githubusercontent.com/44038824/112735318-187f3b80-8f71-11eb-9f0a-283547de2d50.png)

However I don't know why ^[[A appears in the output file. ( I am running this on ubuntu )

**Comment by pbsds** [comment]
It seems to also move the cursor up and down during validation. Replacing characters isn't really a sustainable solution. Preferably tqdm should support a no-tty mode. I'll maybe look into it over easter


---- arvindmuralie77 wrote ----


As mentioned in this link<https://github.com/tqdm/tqdm/issues/750#issuecomment-537558122> if we override tqdm.tqdm.status_printer() and replace \n with \r, then the progress bar is being printed on a new line.
[git]<https://user-images.githubusercontent.com/44038824/112735318-187f3b80-8f71-11eb-9f0a-283547de2d50.png>

However I don't know why ^[[A appears in the output file. ( I am running this on ubuntu )

**Comment by kaushikb11** [comment]
@pbsds Friendly ping! :))
