### ISSUE TITLE
How to log train and validation loss in the same figure ?

### ISSUE THREAD

**Issue by WiraDKP** [PyTorchLightning/pytorch-lightning#665]
#### What is your question?
How can we log train and validation loss in the same plot and preview them in tensorboard?
Having both in the same plot is useful to identify overfitting visually.

#### Code
```
    def training_step(self, batch, batch_idx):
        images, labels = batch
        output = self.forward(images)
        loss = F.nll_loss(output, labels)
        return {"loss": loss, 'log': {'train_loss': loss}}
    
    def validation_step(self, batch, batch_idx):
        images, labels = batch
        output = self.forward(images)
        loss = F.nll_loss(output, labels)
        return {"loss": loss}

    def validation_end(self, outputs):
        avg_loss = torch.stack([x['loss'] for x in outputs]).mean()
        return {'val_loss': avg_loss, 'log': {'val_loss': avg_loss}}
```

#### What have you tried?
Using `Loss/train` and `Loss/valid` contains them in the same section, but still in separate plot.
```
    def training_step(self, batch, batch_idx):
        images, labels = batch
        output = self.forward(images)
        loss = F.nll_loss(output, labels)
        return {"loss": loss, 'log': {'Loss/train': loss}}
    
    def validation_step(self, batch, batch_idx):
        images, labels = batch
        output = self.forward(images)
        loss = F.nll_loss(output, labels)
        return {"loss": loss}

    def validation_end(self, outputs):
        avg_loss = torch.stack([x['loss'] for x in outputs]).mean()
        return {'val_loss': avg_loss, 'log': {'Loss/valid': avg_loss}}
```

I tried to use `self.logger.experiment.add_scalars()`, but confused on how to access train loss in validation loop.

#### What's your environment?
 - OS: MAC OSX
 - Packaging: conda
 - Version: 0.5.3.2

**Comment by 44REAM** [comment]
You can use
```
def training_step(self, batch, batch_idx):
     tensorboard_logs = {'acc': {'train': some_value }, 'loss':{'train': some_value } }
     return {"loss": loss, 'log': tensorboard_logs }

def validation_step(self, batch, batch_idx):
     tensorboard_logs = {'acc': {'val': some_value }, 'loss':{'val': some_value } }
     return {"loss": loss, 'log': tensorboard_logs }
```

**Comment by WiraDKP** [comment]
nested dictionary works!
Thank you @44REAM

**Comment by isolet** [comment]
Got `NotImplementedError: Got <class 'dict'>, but numpy array, torch tensor, or caffe2 blob name are expected.` when trying to use nested dict...

```py

def training_step(self, batch, batch_index):
   loss = self.model.loss(batch)
   # tensorboard_logs = {'train_loss': loss}
   tensorboard_logs = {'loss': {'train': loss}}

   return {'loss': loss, 'log': tensorboard_logs}
```


```
raceback (most recent call last):
  File "bert_ner.py", line 252, in <module>
    trainer.fit(system)
  File "/Users/user/.pyenv/versions/env-mkwPXnF--py3.7/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 630, in fit
    self.run_pretrain_routine(model)
  File "/Users/user/.pyenv/versions/env-mkwPXnF--py3.7/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 830, in run_pretrain_routine
    self.train()
  File "/Users/user/.pyenv/versions/env-mkwPXnF--py3.7/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 343, in train
    self.run_training_epoch()
  File "/Users/user/.pyenv/versions/env-mkwPXnF--py3.7/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 444, in run_training_epoch
    self.log_metrics(batch_step_metrics, grad_norm_dic)
  File "/Users/user/.pyenv/versions/env-mkwPXnF--py3.7/lib/python3.7/site-packages/pytorch_lightning/trainer/logging.py", line 74, in log_metrics
    self.logger.log_metrics(scalar_metrics, step=step)
  File "/Users/user/.pyenv/versions/env-mkwPXnF--py3.7/lib/python3.7/site-packages/pytorch_lightning/loggers/base.py", line 122, in log_metrics
    [logger.log_metrics(metrics, step) for logger in self._logger_iterable]
  File "/Users/user/.pyenv/versions/env-mkwPXnF--py3.7/lib/python3.7/site-packages/pytorch_lightning/loggers/base.py", line 122, in <listcomp>
    [logger.log_metrics(metrics, step) for logger in self._logger_iterable]
  File "/Users/user/.pyenv/versions/env-mkwPXnF--py3.7/lib/python3.7/site-packages/pytorch_lightning/loggers/base.py", line 18, in wrapped_fn
    fn(self, *args, **kwargs)
  File "/Users/user/.pyenv/versions/env-mkwPXnF--py3.7/lib/python3.7/site-packages/pytorch_lightning/loggers/tensorboard.py", line 126, in log_metrics
    self.experiment.add_scalar(k, v, step)
  File "/Users/user/.pyenv/versions/env-mkwPXnF--py3.7/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 342, in add_scalar
    scalar(tag, scalar_value), global_step, walltime)
  File "/Users/user/.pyenv/versions/env-mkwPXnF--py3.7/lib/python3.7/site-packages/torch/utils/tensorboard/summary.py", line 196, in scalar
    scalar = make_np(scalar)
  File "/Users/user/.pyenv/versions/env-mkwPXnF--py3.7/lib/python3.7/site-packages/torch/utils/tensorboard/_convert_np.py", line 30, in make_np
    'Got {}, but numpy array, torch tensor, or caffe2 blob name are expected.'.format(type(x)))
NotImplementedError: Got <class 'dict'>, but numpy array, torch tensor, or caffe2 blob name are expected.
```

**Comment by Borda** [comment]
@isolet mind open a new issue?

**Comment by christabella** [comment]
@isolet I have the same issue

**Comment by huyvnphan** [comment]
I have the same issue. How to fix this?

**Comment by thomasjo** [comment]
@huyvnphan Until this gets resolved properly, here's a _really terrible_ workaround...

``` python
def log_metrics(self, metrics, step=None):
    for k, v in metrics.items():
        if isinstance(v, dict):
            self.experiment.add_scalars(k, v, step)
        else:
            if isinstance(v, torch.Tensor):
                v = v.item()
            self.experiment.add_scalar(k, v, step)

def monkeypatch_tensorboardlogger(logger):
    import types
    logger.log_metrics = types.MethodType(log_metrics, logger)

# ...

monkeypatch_tensorboardlogger(trainer.logger)
```

Again, this is a terrible idea, but it works. Note that the example above assumes you only have the default `TensorboardLogger` wired up. Adjust accordingly if you have multiple loggers.

I began working on a PR to fix this properly but given the current situation with the pandemic, I simply have not found the time to put in the required effort to finish it. My hope is that the snippet above might inspire someone to continue where I stopped...

---
Ref: https://github.com/PyTorchLightning/pytorch-lightning/blob/af621f8590b2f2ba046b508da2619cfd4995d876/pytorch_lightning/loggers/tensorboard.py#L121-L126

**Comment by Borda** [comment]
@chiragraman @huyvnphan @thomasjo mind open a new issue?

**Comment by DanielOrtega94** [comment]
I have the same issue with 
pytorch                   1.5.0           
pytorch-lightning         0.7.6

 Anyone solve this?

**Comment by vibhavagarwal5** [comment]
@Borda Can we open this issue back? There's no solution to it as of now and the same error.

**Comment by import-antigravity** [comment]
I'm getting this error too

**Comment by awaelchli** [comment]
See my comment [here](https://github.com/PyTorchLightning/pytorch-lightning/issues/2563#issuecomment-656506419). 
You can do this right now in your validation_epoch_end and get the plots in one figure. 
I think in the future we could support that also as part of the output of the validation_epoch_end, but I would wait for the structured results to be finished first. Let me know if that helps.

**Comment by import-antigravity** [comment]
@awaelchli very cool, thanks for sharing!!!

**Comment by matthaeusheer** [comment]
@awaelchli This way I have to keep track of the global_step associated with the training steps, validation steps, validation_epoch_end steps etc. Is there a way to access those counters in a lightning module?

To make this point somewhat more clear:  

For example, in validation_epoch_end I want to plot parameter histograms
```python
for name, param in self.named_parameters():
    self.logger.experiment.add_histogram(name, param.data, global_step=self.val_epoch_end_counter)
self.val_epoch_end_counter += 1
```
so here I have to keep track of `val_epoch_end_counter` variable. Same would be with train_step and validation_step counters if we cannot use the nested
```python
return {'log': losses}
```
method which apparently takes care of all of that.
I wonder whether there is a method s.t. I don't have to keep track of all those global_step counters.

**Comment by noamzilo** [comment]
is there a solution yet? I think a loss should be a Metric  just like accuracy. If I am correct, I'd like to do this as a 1st issue.

**Comment by awaelchli** [comment]
@noamzilo a solution for what exactly? most information on this page is outdated. 

> should be a Metric just like accuracy

I'm not sure what you mean by that. If you have an idea for a feature, please post a new issue with your idea and use case :) 

@matthaeusheer Apologies, it seems I have not answered you. The counter you are looking for is called global_step, it can be accessed by `self.global_step` in LightningModule or via `trainer.global_step`. There is however no counter for validation, as it does not need one.

**Comment by Youyoun** [comment]
For those looking for a solution to this problem, here's the one I came up with (a bit more work):

Basically, create two tensor board loggers, which look to the same root directory, but the version is either train or val.
That way, you get two event files for the same version (one for train and one for val), which have the exact same metrics name.

```
version = get_next_version(LOG_DIR)
train_logger = pl_loggers.TensorBoardLogger(".", f"{LOG_DIR}/version_{version}", version="train")
val_logger = pl_loggers.TensorBoardLogger(".", f"{LOG_DIR}/version_{version}", version="val")
model_ckpt_callback = pl_callback.ModelCheckpoint(train_logger.root_dir) # This is to make the ModelCheckpoint call back write to the same directory as the logging, which is done by default if no logger is specifyed.
```

You can now access your loggers from your pl_module using indexing (you can define some constant that holds this index to make it more clean): 
- for train logger call: pl_module.logger[0]
- for val: pl_module.logger[1]

With this, you can call .log method and keep track of step metrics as well as averaged over epoch metrics. Just make sure that what you are logging has exactly the same name for train and val.

You end up with something like this:
![image](https://user-images.githubusercontent.com/15620802/127633754-ca89ebfd-096e-4c9a-843c-960148def644.png)

This alternative is slightly better than using .add_scalars, since it doesn't create multiple event files for each metric, and it makes pytorch_lightning keep track of the metrics evolution for you.

Hope this will save some time for some of you.

**Comment by ce52supi** [comment]
import pytorch_lightning as pl
from torch.utils.tensorboard import SummaryWriter


class LoggingCallback(pl.Callback):
    def __init__(self):
        self.train_losses = []
        self.valid_losses = []

    def on_train_batch_end(self, trainer, pl_module, outputs, batch, batch_idx):
        loss = outputs['loss'].detach().item()
        self.train_losses.append(loss)

    def on_validation_batch_end(self, trainer, pl_module, outputs, batch, batch_idx, dataloader_idx):
        loss = outputs['val_loss'].detach().item()
        self.valid_losses.append(loss)

    def on_epoch_end(self, trainer, pl_module):
        if len(self.train_losses) > 0:
            avg_train_loss = sum(self.train_losses) / len(self.train_losses)
            avg_val_loss = sum(self.valid_losses) / len(self.valid_losses)
            writer = SummaryWriter(log_dir=trainer.logger.log_dir)
            writer.add_scalars('losses', {'train': avg_train_loss, 'valid': avg_val_loss},
                               global_step=trainer.current_epoch)
            writer.close()
