### ISSUE TITLE
`Trainer.predict` stops gradients globally until `torch.set_grad_enabled(True)` is called

### ISSUE THREAD

**Issue by ethanwharris** [PyTorchLightning/pytorch-lightning#6650]
## 🐛 Bug

After `Trainer.predict` is called, gradients are never turned back on. This can cryptically impact tests (see #6595).

See error in notebook: https://colab.research.google.com/drive/1vbKcVwApZEcWX_ryyx-2BJXdLD_nkFBG?usp=sharing

**Comment by Borda** [comment]
@ethanwharris does the #6595 fixes also this issue?

**Comment by ethanwharris** [comment]
@Borda #6595 has a work arround (explicitly call `torch.set_grad_enabled(True)` after `predict`) but not an actual fix. I'll self assign this and work on a proper fix :smiley:
