### ISSUE TITLE
Multiple Optimizers For One Model

### ISSUE THREAD

**Issue by huyvnphan** [PyTorchLightning/pytorch-lightning#6660]
## 🚀 Feature

[Following Issue #375 ](https://github.com/PyTorchLightning/pytorch-lightning/issues/375)
I want to have two optimizers (for example Adam and SGD) for different **layers of the same model.** 
The two optimizers should all be stepped at the same iteration. 

Right now PyTorch Lightning doesn't support this feature.

**Comment by rohitgr7** [comment]
you can try manual_optimization. ref: https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_module.html#automatic-optimization

**Comment by carlosgmartin** [comment]
@huyvnphan Did you find a solution?

**Comment by huyvnphan** [comment]
> @huyvnphan Did you find a solution?

I just use manual optimization
