### ISSUE TITLE
Support for inference only models

### ISSUE THREAD

**Issue by turian** [PyTorchLightning/pytorch-lightning#6676]
## 🚀 Feature

ptl.LightningModule that don't require training and are inference only, should get the nice bits of ptl without having to create a mock Trainer class.

### Motivation

Some ptl models need the features of ptl (easy DDP, fp16) but don't require training. Instantiating a dummy Trainer class is gross.

### Pitch

I love ptl. But...

In a week, we are releasing torchsynth. It requires no training and is the fastest audio synthesizer in the world, yielding a corpus of training + test audio 100x larger than used in the literature. We use ptl because we want simple multi-GPU inference and fp16. However, we have to [kludge it](https://github.com/turian/torchsynth/blob/main/examples/lightningsynth.py) so that a mock Trainer with 0 epochs is created, before we can run multi-GPU inference.

It would be much cleaner if there were a Runner (?) alternative to Trainer that could be used for ptl LightningModules that don't require training.

### Alternatives

Zero epoch training, see our [kludge](https://github.com/turian/torchsynth/blob/main/examples/lightningsynth.py) 

### Additional context

Pretrained models and torch.hub models might use ptl but require no training, but still want the nice features of ptl

**Comment by carmocca** [comment]
> Some ptl models need the features of ptl (easy DDP, fp16) but don't require training. Instantiating a dummy Trainer class is gross.

The trainer is not a dummy, as it is the one to handle `accelerator=ddp` and `precision=16`.

> a mock Trainer with 0 epochs is created, before we can run multi-GPU inference.

You don't need to set `epochs=0` if you are just testing

> It would be much cleaner if there were a Runner (?) alternative to Trainer that could be used for ptl LightningModules that don't require training.

Your confusion comes from the fact that the `Trainer` name is a legacy name. If you think of it as `Runner` or `Engine`, then it makes sense. This is because it is used for more things than training, but renaming the class is not an option due to backwards compatibility.

Feel free to import as `from pytorch_lightning import Trainer as Runner` if it fits your idea better

**Comment by turian** [comment]
@carmocca That makes a lot of sense. I would agree that for 2.x, `Trainer` should be renamed to `Runner`.

**Comment by awaelchli** [comment]
Does the new predict API help you here @turian ? 
https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html#predict

**Comment by turian** [comment]
@awaelchli Interesting, I was not aware of it. I will see

**Comment by edenlightning** [comment]
Feel free to reopen if needed.
