### ISSUE TITLE
ImportError: cannot import name 'PY3' from 'torch._six'

### ISSUE THREAD

**Issue by IsaacRodgz** [PyTorchLightning/pytorch-lightning#6683]
I tried running the [example](https://colab.research.google.com/drive/1rHBxrtopwtF8iLpmC_e7yl3TeDGrseJL?usp=sharing%3E#scrollTo=w4_TYnt_keJi) from the section 'RAPID PROTOTYPING TEMPLATES' from the pytorch lightning documentation (https://pytorch-lightning.readthedocs.io/en/latest/starter/rapid_prototyping_templates.html) but gives the following error: "ImportError: cannot import name 'PY3' from 'torch._six' (/usr/local/lib/python3.7/dist-packages/torch/_six.py)
" when trying to make this import `from pl_bolts.datasets import DummyDataset`. Is it a probem of versions?

**Comment by kaushikb11** [comment]
Hi @IsaacRodgz,

It's an issue with Bolts, could you run `pip install lightning-bolts -U` and try it out?

**Comment by tchaton** [comment]
Dear @IsaacRodgz,

The issue has been resolved on Bolts. Please use the latest version.
Closing this issue.

Best,
T.C
