### ISSUE TITLE
Use a pickle-alternative for serialization

### ISSUE THREAD

**Issue by alanhdu** [PyTorchLightning/pytorch-lightning#6694]
## 🚀 Feature

Right now, if you use `ddp_spawn` or `ddp-cpu`, you are forced to make everything in your script pickleable. This is unfortunate, because there are many things that pickle cannot serialize correctly (e.g. `lambda` functions). One particular point of conflict is developing in a notebook -- if you write your `pl.LightningModule` in the notebook itself, it is attached to `__main__` and cannot be pickled (and thus you cannot use `ddp_spawn`).

There are alternative serialization libraries, most notably [cloudpickle](https://github.com/cloudpipe/cloudpickle) and [dill](https://github.com/uqfoundation/dill). I'm most familiar with cloudpickle, which is what [Dask](https://distributed.dask.org/en/latest/serialization.html#defaults), a super popular parallel computing library, uses.

I'm not super familiar with how communication is handled, but would it be possible to use one of these libraries instead of pickle for serialization? I think that would make DDP much easier to use (especially for the interactive Jupyter notebook development usecase).

**Comment by awaelchli** [comment]
PyTorch uses pickle by default. Even if Lightning did store with `torch.save(pickle_module=cloudpickle)` it would break if the user tries to load the checkpoints.

**Comment by alanhdu** [comment]
Sorry, to clarify are you saying that this is an issue I should raise with upstream PyTorch instead?

> Even if Lightning did store with torch.save(pickle_module=cloudpickle) it would break if the user tries to load the checkpoints.

I'm not sure I follow -- the pickling I'm talking happens when you spawn subprocesses, which I think is unrelated to the `torch.load` and `torch.save` for checkpoints. (I'm also not sure why things would break if the uesr tries to load checkpoints. Wouldn't they "just" have to specify `pickle_module` for `torch.load` as well?).

**Comment by awaelchli** [comment]
> the pickling I'm talking happens when you spawn subprocesses

How do we specify the pickle method for spawn, I don't see an argumetn to change that here: 
https://pytorch.org/docs/stable/multiprocessing.html#torch.multiprocessing.spawn

Found this: https://github.com/pytorch/pytorch/issues/13300
