### ISSUE TITLE
In multi-gpus, trainer.test Error when ModelCheckpoint specifies the filename.

### ISSUE THREAD

**Issue by ShomyLiu** [PyTorchLightning/pytorch-lightning#6716]
## 🐛 Bug

In ddp mode (`trainer(accelerator='ddp'`) with multi-gpus, the trainer could not find the saved **custom-named** checkpoints when `.test()`, which would lead to the following error:

![image](https://user-images.githubusercontent.com/10215945/112814361-cb56b300-90b1-11eb-822f-2a36e4a3b8d9.png)

In addition, the program could hang, not be closed (even with CTRL-C)   and the main GPU's Volatile is always 100%:

![image](https://user-images.githubusercontent.com/10215945/112814403-d7db0b80-90b1-11eb-97aa-5d84c90f7aa8.png)

The following modelcheckpoint would lead to the problem:
```
ckpt = ModelCheckpoint(dirpath='./checkpoints/', monitor='valid_loss', mode='min', filename="{epoch}-{valid_loss:.4f}")
```
If **removing the filename**, the program can work well:
```
ckpt = ModelCheckpoint(dirpath='./checkpoints/', monitor='valid_loss', mode='min')
```

## Please reproduce using the BoringModel

The code is based on the pl_example  in `https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/basic_examples/autoencoder.py`.

The whole code could be found in https://paste.ubuntu.com/p/2Qp4GRns7f/

### Environment

* CUDA:
        - GPU:
                - GeForce RTX 3090
                - GeForce RTX 3090
        - available:         True
        - version:           11.1
* Packages:
        - numpy:             1.19.4
        - pyTorch_debug:     False
        - pyTorch_version:   1.8.0+cu111
        - pytorch-lightning: 1.2.5
        - tqdm:              4.53.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.6.9
        - version:           #140-Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021

**Comment by kaushikb11** [comment]
Hi @ShomyLiu,
This could be resolved in your code by adding `sync_dist=True` parameter to reduce the metric across GPUs.
```python
self.log('valid_loss', loss, on_step=True, sync_dist=True)
```
But yes, better Error Handling could be added. We will look into it.

**Comment by ShomyLiu** [comment]
@kaushikb11  Thanks for your solution. It did work after adding `sync_dist=True`. 
Another small question, when using multi gpus   the output of test phase will be multiple, so which one should be used? 
Just using the above code, the output is:
```
DATALOADER:0 TEST RESULTS
{'test_loss': 0.04038815572857857, 'test_loss_epoch': 0.045426301658153534}
--------------------------------------------------------------------------------
[{'test_loss_epoch': 0.045426301658153534, 'test_loss': 0.04038815572857857}]
[{'test_loss_epoch': 0.046016596257686615, 'test_loss': 0.05867530405521393}]
```
Would you mind explaining these three outputs more clearer?  
I guess that the first one is the final result and the last two are the outputs of different processes.  In addition, what's the difference between `test_loss_epoch` and `test_loss`?

Thanks

**Comment by kaushikb11** [comment]
@ShomyLiu: `test_loss_epoch` is aggregated `test_loss` over one epoch.
