### ISSUE TITLE
Standardize API for logging images, histograms, etc.

### ISSUE THREAD

**Issue by sharuevds** [PyTorchLightning/pytorch-lightning#6720]
## 🚀 Feature
Standardized way to log non-scalar data

### Motivation

Different logging backends supported by PL use different ways to log such data, so it would be very convenient to have standardized way to do it. I mentioned it in Slack and got approval to make a PR, so I want to discuss details here.

### Pitch

Add methods that allow to log images, histograms or other data (audio, video, ...) to PL logger class.

### Additional context

What is better?

If the function is called, but current logger backend doesn't support this type of content:
- silently ignore: we misleading the user allowing him to use method that does nothing without any notification
- throw an error: it can be undesired behavior if LoggerCollection is used 
- show a warning: IMO best solution

What signature should methods have?
- `log_images(images: Dict[str, image_types])`: consistent with existing `log_metrics`, but new method should be added for each type of data (`log_images`, `log_histograms`, ...); IMO best solution
- `log_image(tag, image)`: consistent with Tensorboard, but can be inconvenient when logging multiple images
- `log_metrics` where image wrapper is passed as value: consistent with WandB (uses its own wandb.Image wrapper), but requires user to create wrappers and increases complexity

I am ready to make PR when details are discussed and approved.

**Comment by tchaton** [comment]
Dear @sharuevds,

Sounds like a great idea !
Would you mind making a PR for it ?

Best,
T.C

**Comment by borisdayma** [comment]
The difficulty here will be that integrations may allow different options.

For example with `wandb`:
* segmentation masks accept labels
* bounding boxes can be specified with different options
* audio can accept caption and sample rate
* video accepts fps and format
* very specific formats are also accepted: html, molecules…

I really love the idea though! We should just try to provide as many options as possible to take best advantage of loggers capabilities.

**Comment by Queuecumber** [comment]
Would love to see this as well, there should be a way to abstract the API enough to cover all use cases. Worst case scenario these functions can accept kwargs or something if you know what logger you're interacting with. I can try to mock something up if my currently pending PR ever gets merged

**Comment by ibro45** [comment]
I would suggest to make these a part of `LightningModule`, just like `log()` or `log_dict()`, once they are implemented. It would be a pity to have to call them from `self.logger.experiment` when they are already standardized. Example:
```python
self.log("loss", loss, on_step=True, on_epoch=True)
self.log_dict("metrics", metrics, on_step=True, on_epoch=True)

self.logger.experiment.log_images("input", input)  # pls no
# vs
self.log_images("input", input)
```

Making them part of the `LightningModule` would also be great because we could have `on_step` and `on_epoch` for them!
```python
self.log_images("input", input, on_step=True, on_epoch=True)
```

User could still access the logger-specific methods from `self.logger.experiments` but that would be just for advanced use-cases.

What do you think?

**Comment by ibro45** [comment]
Actually, it is not implemented, I just tried with master branch:

- LightningModule doesn't have `log_image` nor `log_text`, so calling `self.log_image()` raises `AttributeError`
- Calling self.logger.log_images() raises `NotImplementedError` from https://github.com/PyTorchLightning/pytorch-lightning/blob/7b4df7bf919acfd7f7b39d780faeadb54aec9ade/pytorch_lightning/loggers/base.py#L313

**Comment by twsl** [comment]
I think the first simple step is to replace the exceptions in the `LightningLoggerBase` with `pass`. I'll try to see if I can find some time.

**Comment by carmocca** [comment]
As described in https://github.com/PyTorchLightning/pytorch-lightning/issues/12183#issuecomment-1057828965 and the rest of the comments, closing.
