### ISSUE TITLE
Requires_grad automatically set to false during training

### ISSUE THREAD

**Issue by tklinterg** [PyTorchLightning/pytorch-lightning#674]
Hi,

First of all I'd like to thank you for the find package, it removes a lot of overhead.

I'm currently working on a project using the pytorch lightning module. However during the training procedure, the flag 'self.requires_grad' is set to false even though the 'self.unfreeze()' method has been used before in the forward pass.

I've been trying to find the location in the source code where this behavior is dictated, but cannot locate this.

Greatly appreciative in any hint or potential work around.

BR

**Comment by williamFalcon** [comment]
https://github.com/PyTorchLightning/pytorch-lightning/search?q=self.requires_grad&unscoped_q=self.requires_grad
