### ISSUE TITLE
Returning None in training_step generates an error

### ISSUE THREAD

**Issue by dumitrescustefan** [PyTorchLightning/pytorch-lightning#6753]
## 🐛 Bug

When returning None in training_step I get an error.  I need to skip some batches, as I do some processing in the collate function, and sometimes I need to ignore the entire batch. Thus, from the collator I return None, and in my training_step i have : 

```
    def training_step(self, batch, batch_idx):
        if batch is None:
            return None
```

however, as soon as this fires, I get `` KeyError: 'training_step_output_for_epoch_end' ``: 

```
Epoch 0:  45%|█████████████████████████████████████████████████████████████████████▌                                                                                      | 1084/2431 [05:59<07:26,  3.02it/s, loss=0.0128, v_num=77]
Traceback (most recent call last):
  File "/home/echo/p3.8-test/lib/python3.8/site-packages/pytorch_lightning/utilities/parsing.py", line 182, in __getattr__
    return self[key]
KeyError: 'training_step_output_for_epoch_end'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mpj/trainer.py", line 279, in <module>
    trainer_object.fit()
  File "mpj/trainer.py", line 237, in fit
    trainer.fit(model, train_loader, val_loader)
  File "/home/echo/p3.8-test/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/home/echo/p3.8-test/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/home/echo/p3.8-test/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/echo/p3.8-test/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/home/echo/p3.8-test/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 637, in run_train
    self.train_loop.run_training_epoch()
  File "/home/echo/p3.8-test/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 499, in run_training_epoch
    batch_output.training_step_output_for_epoch_end,
  File "/home/echo/p3.8-test/lib/python3.8/site-packages/pytorch_lightning/utilities/parsing.py", line 184, in __getattr__
    raise AttributeError(f'Missing attribute "{key}"') from exp
AttributeError: Missing attribute "training_step_output_for_epoch_end"
```

I looked at issue 3323 and others, and I am returning None, and accelerator is None (so, not dp or ddp). In case it matters, I do not have an ``training_epoch_end``, and it fails consistently whenever I return None.

Thanks for the help!

### Expected behavior

Skip the batch/step when returning None.

### Environment

* CUDA:
	- GPU:
		- GeForce RTX 2080 Ti
	- available:         True
	- version:           11.1
* Packages:
	- numpy:             1.18.3
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.0+cu111
	- pytorch-lightning: 1.2.6
	- tqdm:              4.56.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.8.2
	- version:           #140-Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021

**Comment by ethanwharris** [comment]
Hi @dumitrescustefan, thanks for the issue :smiley:

This seems to be working on master for me (no errors, training proceeds as expected). Could you install from master (`pip install git+https://github.com/PytorchLightning/pytorch-lightning`) and check that the bug persists? If so, could you provide an example showing the bug in action?

**Comment by edenlightning** [comment]
@dumitrescustefan friendly ping :)

**Comment by dumitrescustefan** [comment]
Hi, I tried to reproduce this bug some days ago using a simple MNIST colab example and it indeed seems to work (I inserted a simple return None in the training step and it does not crash). The problem is reproducing the quite complex project I'm working on, on colab; I'll give it a shot later this week as I'm a bit overwhelmed with work. Thanks for keeping this open!

**Comment by dumitrescustefan** [comment]
@edenlightning Thanks for waiting. I think I figured out what's been happening. It's not a problem when you simply return None in the training step, but it is a problem when you pass batch = None to the training step and then you return None. 

My guess is that pytorch lightning **expects that all batches contain some content** and ignores the training steps where None is returned. If, from the collate function as was my case, you **return a batch that is None** (that's how I marked the invalid batch) and then, in the training_step, you check if batch is None then return None, then it immediately fails. 

What I did was to add a flag in the collate_fn to mark if it's a valid batch or not, and in the training step I first check that flag (that's in the batch, amongst normal data). If it's not a valid batch, I just return None, and it seems to work. 

So this works ok: 

```
def collate_fn ():
   ... 
   valid = True # or false if the data is valid or not
   ... 
   return {"data": data,  ..... , "valid": valid}

def training_step(self, batch, batch_idx):
   if batch["valid"] is False:
      return None 
    ... normal processing resumes here
```

but this fails:
```
def collate_fn ():
   ... 
   valid = True # or false if the data is valid or not
   ... 
   if valid:
      return {"data": data,  ..... }
   else:
      return None

def training_step(self, batch, batch_idx):
   if batch is None:
      return None <- here it fails with AttributeError: Missing attribute "training_step_output_for_epoch_end" 
    ... normal processing resumes here
```

At this point I am unsure if this is a bug or that's how it is supposed to work. Please close the issue if this is not a bug or a Won't fix type of situation. Thanks!

**Comment by ethanwharris** [comment]
Hi @dumitrescustefan, Thanks for taking the time to reproduce this! This definitely seems like a use case that we should support. Just having a look at a fix now :smiley:
