### ISSUE TITLE
Model is not being saved after first epoch

### ISSUE THREAD

**Issue by CracKCatZ** [PyTorchLightning/pytorch-lightning#6763]
Hey guy's,
this is more like a question because I don't know if it is normal that my model is not being saved after running the first epoch.
So is it a normal behavior or not and should I then run it a second epoch?

Thank's in advance:)

**Comment by kaushikb11** [comment]
Hi @CracKCatZ, by default, Lightning automatically saves a checkpoint for you in your current working directory, with the state of your last training epoch.
Couple of references you could look into: [Ref 1](https://pytorch-lightning.readthedocs.io/en/stable/extensions/generated/pytorch_lightning.callbacks.ModelCheckpoint.html#pytorch_lightning.callbacks.ModelCheckpoint), [Ref 2](https://pytorch-lightning.readthedocs.io/en/stable/common/weights_loading.html).

**Comment by CracKCatZ** [comment]
Hey kaushikb11,
I've fixed it. I forgot to call the callback function.
But thank you anyway:)

**Comment by kaushikb11** [comment]
Awesome, Glad to know! Closing the issue, cheers!
