### ISSUE TITLE
NeptuneLogger ignores NEPTUNE_PROJECT environment variable

### ISSUE THREAD

**Issue by cifkao** [PyTorchLightning/pytorch-lightning#6766]
## 🐛 Bug

If `project_name` is not given, `NeptuneLogger` does not fetch the project name from the `NEPTUNE_PROJECT` environment variable and instead raises a `neptune.api_exceptions.ProjectNotFound` with the message "Project None not found".

### To Reproduce

https://colab.research.google.com/gist/cifkao/70eb23d9021d8470b3208c7eb3607abd/the-boringmodel-neptune.ipynb

### Expected behavior

The project name should be fetched from the `NEPTUNE_PROJECT` environment variable.

### Environment

* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.1+cu101
	- pytorch-lightning: 1.2.6
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.10
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

**Comment by jakubczakon** [comment]
@pitercl could you take a look?

**Comment by shnela** [comment]
There was a problem with `neptune-client` library.
The fix has been already published, so updating `neptune-client` to `0.9.3` will make your code work.

You can upgrade library, by running
```
pip install --upgrade neptune-client
```

If there are any other issues, do not hesitate to let us know ;)
