### ISSUE TITLE
How to use pytorch-lightning for meta learning

### ISSUE THREAD

**Issue by wheatdog** [PyTorchLightning/pytorch-lightning#678]
Thanks for making this great library! Appreciate your work very much!

I wonder if anyone has the experience to use pytorch-lightning for meta-learning, maybe combined with library like [Torchmeta](https://github.com/tristandeleu/pytorch-meta) or [learn2learn](https://github.com/learnables/learn2learn).

I would like to hear from others before getting my hands dirty. Thanks!

**Comment by williamFalcon** [comment]
could you post a toy example?

**Comment by williamFalcon** [comment]
@wheatdog will reopen if we need to add to examples

**Comment by pietrolesci** [comment]
Hi @wheatdog, 

I am working on meta-learning. I personally prefer the `higher` library as it gives more flexibility and is "nearer to the metal". I tried to reimplement [this](https://github.com/tristandeleu/pytorch-meta/blob/master/examples/maml-higher/train.py) example using pytorch-lightning. It still need some nurturing but the high-level (design) idea is there. You can find my implementation [here](https://gist.github.com/pietrolesci/503c271b8464ce1c579b1856fe58d87c).

In brief, I matched the meta-training steps to the PL hooks in the following way

- **Data loading**: delegate all the meta-training batch loading to a custom `DataLoader`. I highly recommend using [TorchMeta](https://github.com/tristandeleu/pytorch-meta) for this. You can then return it in the `training_dataloader` of a `DataModule`. Note: each batch will be a _set of tasks_

- **Meta-training** Implement all the meta-training logic in the `training_step`: each batch is a "batch of tasks". Loop on it and compute the inner gradients in the `higher` context

- **Optimizers**: let the `configure_optimizer` returns the `meta_optimizer` and the `inner_optimizer`. You can access them in the `training_step` via `self.optimizers()`

- **Meta-testing**: same as meta-training, your dataloader should return a batch of tasks.

**Comment by wakaizen** [comment]
Hi @pietrolesci ,

I checked your code, and found that higher does not support pytorch-lightning optimizers. How do you deal with this issue?

**Comment by pietrolesci** [comment]
Hi @wakaizen,

Thanks for your reply. Maybe I don't get your question. Aren't you able to run the code?

Also, can you please clarify what do you mean by "pytorch-lightning optimizers"? The _configure_optimizer_ returns a pytorch optimizer

**Comment by wakaizen** [comment]
@pietrolesci I run your code, and got such errors:
``` python
File "/home/hanw/miniconda3/envs/meta_learning/lib/python3.7/site-packages/higher/optim.py", line 786, in get_diff_optim
    "Optimizer type {} not supported by higher yet.".format(type(opt))
ValueError: Optimizer type <class 'pytorch_lightning.core.optimizer.LightningSGD'> not supported by higher yet.
```
It seems that during training, the PyTorch SGD optimizer is converted to the Lightning optimizer, and higher does not support such optimizer since it's not differentiable. 
By the way, I am using PyTorch 1.4, the latest lightning and the latest higher.

**Comment by wakaizen** [comment]
Anyway, it seems to be a long way to go before combining the two. Since now higher can only support 1 GPU. It can not handle DP or DDP...
