### ISSUE TITLE
BoringModel uses deprecated code

### ISSUE THREAD

**Issue by tmcclintock** [PyTorchLightning/pytorch-lightning#6792]
## 🐛 Bug

The [**BoringModel**](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing) is out of date. This model is used to help generate bug reports, but it uses syntax that was [deprecated](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md#removed-1) as of 1.2.6. This should be a simple fix to update, but I also propose making legacy `BoringModel`s for pre-1.2.6 versions, in case a user has an issue with old code.

**Comment by tchaton** [comment]
Dear @tmcclintock,

Could you share which part of the BoringModel is depreceated ?

NB: The BoringModel doesn't perform any logic by default.

Best,
T.C

**Comment by tmcclintock** [comment]
@tchaton the train/val/test_step functions all return a dictionary, even though they are supposed to use `LightningModule.log_dict` instead as of 1.2.6 (see the changelog bullet I linked to).

**Comment by ananthsub** [comment]
@tmcclintock - these step functions can still return a dict for further processing in the `training/validation/test_epoch_end` hooks

**Comment by awaelchli** [comment]
I see no reason to remove it from the BoringModel. It's perfectly fine to pass outputs from step to epoch_end hooks and it seems a good default implementation for a debugging model.

**Comment by tmcclintock** [comment]
Sure thing. My mistake, I must have misread the functions and misunderstood. Sorry for the noise.
