### ISSUE TITLE
doc about restoring training session

### ISSUE THREAD

**Issue by ycliu613** [PyTorchLightning/pytorch-lightning#682]
## Something confusing with the [doc](https://pytorch-lightning.readthedocs.io/en/latest/Trainer/Checkpointing/#restoring-training-session) about 'restoring training session'

I want to restart training from a checkpoint, but when I followed the doc and specified the variable `logger` to `Trainer`, it did not work.

Then I found the code [here](https://github.com/williamFalcon/pytorch-lightning/blob/12edc3099cd0d529b4ff0553f5c7cbe9f47dfdfb/pytorch_lightning/trainer/trainer_io.py#L187), and knew that I should specify  `checkpoint_callback`'s `filepath`, so that `Trainer` can restore the model and training state.

So whether the doc has not been updated or another mistake i've made? My environment version is listed below:
- torch: 1.3.1
- pytorch_lightning: 0.5.3.2

Thanks for your reply!

**Comment by williamFalcon** [comment]
can u post example code? you don’t need to pass in a path unless u want to. it defaults to current working dir.

**Comment by williamFalcon** [comment]
@ycliu613 new docs cover this
