### ISSUE TITLE
Extract wight and model for external use

### ISSUE THREAD

**Issue by learnermaxRL** [PyTorchLightning/pytorch-lightning#684]
## ❓ Questions and Help

Where to find the saved wieghts of the model alongwith the model architecture so that we can use them directly in external applications,by using simple torch loading model apis

**Comment by williamFalcon** [comment]
the weights are saved to the experiment folder. 

lightninglogs/model_name/version_1/weights/my_weights.ckpt

**Comment by learnermaxRL** [comment]
![Screenshot from 2020-01-15 12-50-25](https://user-images.githubusercontent.com/40789484/72413406-bdab5b00-3795-11ea-98f1-beacc79ac0c0.png)
Its not available

**Comment by learnermaxRL** [comment]
Their is no folder created under model name,I directly have lightning_logs - > version_nb and within each i am getting above data

**Comment by chris-clem** [comment]
Is there an update to this? I am using the TestTubeLogger and would like to access the weights. Or do I need to save them with `torch.save()` after the training?

**Comment by Borda** [comment]
@learnermaxRL @chris-clem may you share your logger configuration?

**Comment by chris-clem** [comment]
@Borda this is my logger and callback config:

```python
    logger = TestTubeLogger(save_dir=str(Path(log_dir)), name=model_name)

    checkpoint_dir = (
        Path(logger.save_dir)
        / logger.experiment.name
        / f"version_{logger.experiment.version}"
        / CHECKPOINTS
    )

    checkpoint_callback = ModelCheckpoint(filepath=str(checkpoint_dir), monitor=VAL_ACC)

    early_stop_callback = EarlyStopping(monitor=VAL_ACC, verbose=True)
```
