### ISSUE TITLE
Tune crashes with DataModule

### ISSUE THREAD

**Issue by lukasfolle** [PyTorchLightning/pytorch-lightning#6845]
## 🐛 Bug

Connected to #1495.
When using trainer.tune() only the `model` is forwarded, but no the datamodule cp.: https://github.com/PyTorchLightning/pytorch-lightning/blob/eafec7d425bf691ab5bfaf2794c3e581487ecfa8/pytorch_lightning/tuner/tuning.py#L64

### Expected behavior

Just like for `self.trainer.auto_scale_batch_size`  the datamodule or train/val dataloaders should be forwarded as well.
I.e.:
```
self.lr_find(
  model,
  train_dataloader=train_dataloader,
  val_dataloaders=val_dataloaders,
  datamodule=datamodule, ...)
```

**Comment by SkafteNicki** [comment]
Fixed by https://github.com/PyTorchLightning/pytorch-lightning/pull/6784
