### ISSUE TITLE
What is the "version" argument in the logger to resume checkoint ?

### ISSUE THREAD

**Issue by cdancette** [PyTorchLightning/pytorch-lightning#686]
## ❓ Questions and Help
In the documentation, in checkpointing : 
https://pytorch-lightning.readthedocs.io/en/latest/Trainer/Checkpointing/ , in "Restoring training session", it mentions the `version=1` argument from the logger. What is this argument, how do we use it ?

What i'd like to do is automate the resume of my training at the last checkpoint if it was killed.

**Comment by williamFalcon** [comment]
each experiment has a version (ie: each run of the model). to resume that run, pass in the matching version. 

ie: if i run this script
python train.py. 

it creates v1

if i rerun the same script it creates v2 and so on
