### ISSUE TITLE
multiple dataset doesn't work when passing `dict` to trainer.fit(model, train_loaders, valid_loaders)

### ISSUE THREAD

**Issue by keunwoochoi** [PyTorchLightning/pytorch-lightning#6881]
- pip installed pytorch lightning
- torch 1.7.1
- PL 1.2.7
- linux

the same code works when i passed multiple datasets as a list. but it didn't work when it was like this.
```python
trainer.fit(model, {1.0: dataloader, 0.0: dataloader}, {1.0: dataloader, 0.0: dataloader})
```

according to the error message, in `train_step(self, batch, batch_idx)` and `valid_step()`, batch is simply `0.0` -- probably coming from the key of the dict. my expected behavior was, as in the API doc, `{0.0: batch, 1.0: batch}`.

**Comment by SkafteNicki** [comment]
Currently only the `train_dataloader` can be passed in as an dict and `val/test_dataloader` need to be passed in as lists. 
It is mentioned at the bottom of this page: https://pytorch-lightning.readthedocs.io/en/latest/advanced/multiple_loaders.html#multiple-training-dataloaders
where `CombinedLoader` need to be used if you want `val/test_dataloader` as dict.
