### ISSUE TITLE
How to make test_end() return metrics 

### ISSUE THREAD

**Issue by Laksh1997** [PyTorchLightning/pytorch-lightning#690]
I have searched through the docs / Google as well as looked through the source code.

It seems like test_end() returns nothing (it has no `return` in the function). I was wondering if I was missing something really obvious. 

I would simply like to return the metrics of the test end.

**Comment by matthew-z** [comment]
You may try this:

```py
class MyModel(pl.LightningModule):
  def __init__(self, ...):
    self.test_result = None
  def test_end(self, outputs):
    self.test_result = get_eval_metrics(outputs)

model = MyModel()
trainer.test(model)
print(model.test_result)
```

**Comment by Laksh1997** [comment]
Thanks @matthew-z !
