### ISSUE TITLE
Missing LightningModule datamodule reference

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#6929]
## 🐛 Bug

This docs snippet does not work:

https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_module.html#datamodule

### To Reproduce

```python
def test_bug(tmpdir):
    class TestModel(BoringModel):
        def configure_optimizers(self):
            # works
            len(self.trainer.datamodule.train_dataloader())
            # does not
            len(self.datamodule.train_dataloader())
            
            return super().configure_optimizers()

    dm = BoringDataModule()
    trainer = Trainer(default_root_dir=tmpdir, fast_dev_run=True)
    trainer.fit(TestModel(), datamodule=dm)
```

```console
line 128, in configure_optimizers
    num_training_samples = len(self.datamodule.train_dataloader())
AttributeError: 'NoneType' object has no attribute 'train_dataloader'
```

### Expected behavior

`self.datamodule` works

## Alternatives

Update docs

### Environment

master

### Additional context

Reported by Brian Staber in Slack

**Comment by mesejo** [comment]
Can I work on this?

**Comment by ananthsub** [comment]
@carmocca is the model expected to have a reference to the data module during training?

**Comment by carmocca** [comment]
> Can I work on this?

Sure!

> @carmocca is the model expected to have a reference to the data module during training?

I guess given the docs link above and the fact that it has a property for it

https://github.com/PyTorchLightning/pytorch-lightning/blob/f29ecbfd909ff431ef837fcc8ebff451e897cb0b/pytorch_lightning/core/lightning.py#L164-L170

Although I wouldn't personally mind removing this and forcing access through the trainer.

**Comment by tchaton** [comment]
Dear @mesejo,

Could you make a PR for this ? 

Best,
T.C

**Comment by mesejo** [comment]
Hi @carmocca, when you said:

> I personally wouldn't mind removing this and forcing access through the trainer. 

Were you referring to the entire **datamodule** property?

**Comment by carmocca** [comment]
> Were you referring to the **datamodule** property?

I was referring to deprecating `model.datamodule` in favor of `model.trainer.datamodule`

cc: @PyTorchLightning/core-contributors Any opinions about this? Should we keep both ways?

**Comment by awaelchli** [comment]
I would prefer if we don't attach the datamodule to the LightningModule and instead reference it through trainer.

**Comment by carmocca** [comment]
Okay, let's deprecate it then and update the docs/ocurrences
