### ISSUE TITLE
Resolve several Horovod test failures

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#6935]
## 🐛 Bug

We are currently skipping several Horovod tests. We should eventually address each one.

- [ ] Coverage issue: https://github.com/PyTorchLightning/pytorch-lightning/blob/b9475c1ae913b647c18cbf5f445c53c2f793a7f5/tests/models/test_horovod.py#L52
- [ ] Unclear feature: https://github.com/PyTorchLightning/pytorch-lightning/blob/b9475c1ae913b647c18cbf5f445c53c2f793a7f5/tests/models/test_horovod.py#L154-L156
- [x] Flaky test on ubuntu 1. Produces a [segfault](https://github.com/PyTorchLightning/pytorch-lightning/runs/2305849946#step:15:772): https://github.com/PyTorchLightning/pytorch-lightning/blob/b9475c1ae913b647c18cbf5f445c53c2f793a7f5/tests/models/test_horovod.py#L243
- [x] Flaky test on ubuntu 2. Produces a segfault: https://github.com/PyTorchLightning/pytorch-lightning/blob/9402c052ed5a8acddce1b3afaafa5c881ed0c207/tests/models/test_horovod.py#L380
- [ ] Permissions issue 1: https://github.com/PyTorchLightning/pytorch-lightning/blob/b9475c1ae913b647c18cbf5f445c53c2f793a7f5/tests/models/test_horovod.py#L276
- [ ] Permissions issue 2: https://github.com/PyTorchLightning/pytorch-lightning/blob/b9475c1ae913b647c18cbf5f445c53c2f793a7f5/tests/models/test_horovod.py#L326

cc: @Borda @tgaddair

**Comment by Borda** [comment]
@tgaddair could you pls check these issues? 🐰

**Comment by edenlightning** [comment]
@tgaddair friendly ping :)

**Comment by edenlightning** [comment]
@Borda still relevant?

**Comment by carmocca** [comment]
The Python errors might be resolved with https://github.com/PyTorchLightning/pytorch-lightning/pull/8116

**Comment by edenlightning** [comment]
@carmocca is this fixed?

**Comment by carmocca** [comment]
#8116 might have fixed the ones marked as "flaky test". Need to check if that's the case but I'm sure the rest are still failing
