### ISSUE TITLE
Fairscale integration not working for me

### ISSUE THREAD

**Issue by aced125** [PyTorchLightning/pytorch-lightning#6943]
## 🐛 Bug

When I try to train a model with Fairscale (ddp_sharded), I get this error always:

```python
  File "/home/ubuntu/anaconda3/envs/torch/lib/python3.7/site-packages/fairscale/nn/data_parallel/sharded_ddp.py", line 500, in _setup_backward_hooks
    assert p_tmp.grad_fn is not None
AssertionError
```

Could anyone please point me at an example I could run?

 - PyTorch Version (e.g., 1.0): 1.8
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): conda install -c pytorch pytorch 
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: 8xV100
 - Any other relevant information:

**Comment by tchaton** [comment]
Hey @aced125, could you share a reproducible script ?

**Comment by SeanNaren** [comment]
Hi @aced125 this may be the same as https://github.com/PyTorchLightning/pytorch-lightning/issues/6876! Could you try using pytorch-lightning master and fairscale master?

```
pip install git+https://github.com/facebookresearch/fairscale.git
pip install git+git@github.com:PyTorchLightning/pytorch-lightning.git
```

**Comment by edenlightning** [comment]
@aced125 friendly ping :)
