### ISSUE TITLE
load_from_checkpoint function returning error - AttributeError: Can't get attribute '_gpus_arg_default'

### ISSUE THREAD

**Issue by psbreuning** [PyTorchLightning/pytorch-lightning#6964]
I am getting this error when trying to load model from checkpoint:

model = MyModel.load_from_checkpoint(path/to/model/Google Drive)

AttributeError: Can't get attribute '_gpus_arg_default' on <module 'pytorch_lightning.utilities.argparse' from '/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/argparse.py'>

This is happening on Google Colab. This was working for me before, but suddenly I get this error with the same models that I have loaded previously without issue.

**Comment by awaelchli** [comment]
Hi, we fixed this recently in master #6898 
This won't happen in the future, but unfortunately your checkpoint contains that serialised function and the only way to undo it is to 
1. downgrade lightning to the version that produced the checkpoint (in your case, was it 2.1,2.3?)
2. load the checkpoint with `torch.load()`, manually remove the `gpu_arg_default` from the hparams inside the dict
3. save the checkpoint again with `torch.save`.

Sorry for the inconvenience, I know this is very annoying!
