### ISSUE TITLE
epoch option to log_model using WandbLogger

### ISSUE THREAD

**Issue by turian** [PyTorchLightning/pytorch-lightning#6965]
## 🚀 Feature

WandbLogger should have an optional parameter, `log_model_every_k_epochs`, in which case the model is logged periodically.

### Motivation

WandbLogger appears only to log the model on finalize. This is different than the default ptl behavior, and also means that model logging happens unpredictably.

### Pitch

If Google Colab terminates your training, WandbLogger doesn't save your model.

If you cancel training and start editing your Jupyter notebook, WandbLogger doesn't save your model.

There is a high potential for human error in forgetting to manually call WandbLogger.finalize()

### Alternatives

I believe one can manually call WandbLogger.finalize() if they are monitoring the job. I don't know if this means that the logger cannot be reused or the training job continued.

Also, this workaround doesn't help in the setting where Colab shuts down an instance without warning.

**Comment by ananthsub** [comment]
n00b question: Would it be easier to extend the ModelCheckpoint callback for specific WandB functionality?
