### ISSUE TITLE
Multi-processing with IterableDataset Warning 

### ISSUE THREAD

**Issue by ozen** [PyTorchLightning/pytorch-lightning#6966]
Hi there. This is a report for a potential typo, and a related question.

The warning message given when using an IterableDataset is as follows: 

https://github.com/PyTorchLightning/pytorch-lightning/blob/049006a59cf62d3539aaf19037aca1caac98abfd/pytorch_lightning/utilities/data.py#L40-L45

Is the part `e.g. batch size > 1` should be `e.g. num_workers > 1`?

Is this warning about what [IterableDataset doc](https://pytorch.org/docs/stable/data.html#torch.utils.data.IterableDataset) explains about configuring the workers? If I write my IterableDataset similarly to the example provided in the doc and also define a `__len__` function, will there be any problems due to using PL?

Thanks.

**Comment by awaelchli** [comment]
See here: https://github.com/pytorch/pytorch/blob/399b66c8137db9ef86e45707ec30a44e40495f62/torch/utils/data/dataloader.py#L374

This has todo with the sampler in the dataloader that creates batches. While yes, it is related to num_workers, it's not just about that. I agree though the message I added should probably also mention num_workers in addition to batch size. If you want, send a PR with a doc update. Cheers <3

**Comment by ozen** [comment]
Thanks for the link, I hadn't read that part.

I still don't see it though. DataLoader's len uses the sampler length for map-style dataset, but cannot do so for iterable-style dataset since there is no sampler; so it returns len(dataset) / batch_size. The note comment is about the inaccuracy of len of iterable dataset in multi-processing setting (i.e. related to num_workers).

**Comment by awaelchli** [comment]
yes, we can replace batch size with num_workers as you suggest. Want to send a PR?

> Besides the helpful warning and the progress bar, does the implementation of len of an iterable dataset effect how PL runs the epoch?

not that I know, it's just iterating through the dataloader.
