### ISSUE TITLE
PyTorch Lightning ignores traditional WORLD_SIZE/RANK specifications in environment and doesn't document replacement

### ISSUE THREAD

**Issue by tmbdev** [PyTorchLightning/pytorch-lightning#7003]
## 🐛 Bug

Standard torch.distributed environment variables seem to be handled differently.

### To Reproduce

```
$ MASTER_ADDR=192.168.1.3 MASTER_PORT=1234 WORLD_SIZE=2 RANK=0 python3 boring_model.py
```

### Expected behavior

Should wait for second job to connect to the MASTER_PORT. Instead, just starts training. No combination of arguments and environment variables seems to change this behavior.

It appears that PL handles startup for distributed processing differently somehow and internally overrides environment variables. This works pretty well for ddp on single nodes and (presumably) automates deployment under Slurm.

But I can't figure out from the documentation or from the samples how to arrange for the traditional PyTorch behavior in which all jobs are started up manually. 

For comparison, this code behaves as expected:

```
$ cat > simple.py
import torch

print("init")
torch.distributed.init_process_group("gloo")
print("done", torch.distributed.get_rank(), torch.distributed.get_world_size())
$ MASTER_ADDR=192.168.1.3 MASTER_PORT=1234 WORLD_SIZE=2 RANK=0 python3 simple.py & sleep 3; MASTER_ADDR=192.168.1.3 MASTER_PORT=1234 WORLD_SIZE=2 RANK=1 python3 simple.py
```

That is, the two jobs rendezvous as expected and then exit.

### Suggested Behavior

- document how the traditional PyTorch behavior can be reproduced (i.e., no calculations of nodes/size/... in DDP)
- perhaps provide some kind of command line flag that restores the traditional behavior (e.g., "--accelerator ddp_plain")
- maybe something else

### Environment

 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, source): pip3
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: 1080
 - Any other relevant information:

**Comment by awaelchli** [comment]
Hi, did you follow these steps here?
https://pytorch-lightning.readthedocs.io/en/latest/advanced/cluster.html

I think you can also force the behavior you want like so:

from pytorch_lightning.plugins.environments import LightningEnvironment

```python
class MyCluster(LightningEnvironment):

    def creates_children(self):
        return True

trainer = Trainer(plugins=[MyCluster()])
```

**Comment by tmbdev** [comment]
Thanks. That page says to pass num_nodes explicitly to Trainer, which I can do. But that still doesn't work. I.e., if I say --num_nodes=2 on both nodes, each node believes its GLOBAL_RANK=0, even if I pass GLOBAL_RANK=1, RANK=1, etc. in the environment. So, I simply don't know how to get two nodes to rendezvous or even change the GLOBAL_RANK of any node.

As for your sugggested solution,  LightningEnvironment doesn't exist in 1.2.7, but apparently has been added in 1.2.8. It sounds like LightningEnvironment in 1.2.8. But in 1.2.7, I can write my own implementation:

```Python
def I(value, name):
    print(name, value)
    return value


class MyCluster(environments.ClusterEnvironment):
    def __init__(self):
        super().__init__()
        self._master_addr = I(os.environ["MASTER_ADDR"], "MASTER_ADDR")
        self._master_port = I(int(os.environ["MASTER_PORT"]), "MASTER_PORT")
        self._world_size = I(int(os.environ["WORLD_SIZE"]), "WORLD_SIZE")
        self._global_rank = I(int(os.environ["RANK"]), "RANK")

    def creates_childern(self):
        return False

    def master_address(self):
        return self._master_addr

    def master_port(self):
        return self._master_port

    def world_size(self):
        return I(self._world_size, "world_size")

    def global_rank(self):
        return self._global_rank

    def set_world_size(self, *args):
        raise Exception()

    def set_global_rank(self, *args):
        raise Exception()

    def local_rank(self):
        return I(0, "LOCAL_RANK")

    def node_rank(self):
        return self._global_rank
```

Unfortunately, this doesn't quite work either. It appears that I also need to set `num_nodes` to `world_size` as well, but it seems inconsistent to me that Lightning ignores the world_size returned by the ClusterEnvironment. In any case, I don't quite understand the logic, and I can't find anything in the documentation or the ClusterEnvironment documentation that explains what the rest of Lightning expects from these values.

I'm porting existing code that just uses WORLD_SIZE and RANK to configure itself in K8s and NGC environments; I suspect others have similar needs. So some simple support for plain PyTorch distributed logic would be nice, where Lightning just uses DDP but otherwise does not interfere in the setup of torch.distributed.

Secondly, the built-in Lightning logic may be smart and useful, but it's not clear to me how the different functions are intended to map processes onto the compute cluster; maybe a little more documentation would be nice. Everything seems to work great for single node DDP and Slurm, but a simple example of manually starting up 2 (or 4) jobs and having the rendezvous would be nice, similar to the very simple PyTorch example I gave above.

**Comment by awaelchli** [comment]
I believe you need to return True from creates_children, because otherwise Lightning will spawn the processes. But as you say, you want to start them manually on both nodes.

**Comment by awaelchli** [comment]
Sorry that there is not much documentation. These environments are new, we are working on better documentation.

**Comment by ananthsub** [comment]
@awaelchli the `creates_children` naming is confusing. many readers would assume its the environment within lightning that creates children processes vs processes being created before trainer.fit()

**Comment by tmbdev** [comment]
Thanks; I have tried returning both values, and neither works. Even if I stop ddp.py from creating subprocesses, I still don't know how to match the actual configuration of nodes and GPUs that I have. And even if I could somehow communicate what I want to it, it wouldn't be using the standard PyTorch distributed environment variables, which Lightning seems to use differently. 

It looks to me that in order to fit Lightning into an existing distributed training environment, I actually need both a new Environment class and a new `training_type`. The `training_type` should just wrap the model into DDP, but otherwise leave things alone: no subprocesses, no modification of the environment, etc.

I suspect I'm not the only user who has existing non-Lightning distributed code for which I need a solution that doesn't break/override the existing distributed startup code.

I'll investigate a bit further.

**Comment by ananthsub** [comment]
@tmbdev the torchelastic environment does not create subprocesses nor modifies the environment; ddp+torchelastic does just wrap the model in DDP

**Comment by awaelchli** [comment]
@tmbdev In Lightning you don't need to set the global, local and world size. It gets computed automatically. You only have to launch the script on every node and set the Node rank like so:

`NODE_RANK=1 MASTER_ADDR=192.168.1.3 MASTER_PORT=1234  python your_script.py`

> @awaelchli the creates_children naming is confusing. many readers would assume its the environment within lightning that creates children processes vs processes being created before trainer.fit()

We can change the name when we do the property/settter refactor. #6303

**Comment by tmbdev** [comment]
Thanks. I got something to work like this, but only on a local machine

```
# first job
$ CUDA_VISIBLE_DEVICES=0 MASTER_ADDR=127.0.0.1 MASTER_PORT=9888 NODE_RANK=0 python3 train.py --num_nodes=2 --gpus 1 --accelerator=ddp -b 32
# different window same host
$ CUDA_VISIBLE_DEVICES=1 MASTER_ADDR=127.0.0.1 MASTER_PORT=9888 NODE_RANK=1 python3 train.py --num_nodes=2 --gpus 1 --accelerator=ddp -b 32
```

When I use it on different hosts, things still fail:

```
192.168.1.3$ PL_TORCH_DISTRIBUTED_BACKEND=gloo MASTER_ADDR=192.168.1.3 MASTER_PORT=9888 NODE_RANK=0 python3 train.py --num_nodes=2 --gpus 1 --accelerator=ddp -b 32
training_urls =  ./shards/imagenet-train-{000000..000146}.tar
val_urls =  ./shards/imagenet-val-{000000..000006}.tar
batch_size 32 num_workers 6 world_size 0
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
Traceback (most recent call last):
  File "train.py", line 245, in <module>
    main(args)
  File "train.py", line 234, in main
    trainer.fit(model, data)
  File "/home/tmb/proj/webdataset-lightning/venv/src/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self.accelerator.setup_environment()
  File "/home/tmb/proj/webdataset-lightning/venv/src/pytorch-lightning/pytorch_lightning/accelerators/accelerator.py", line 80, in setup_environment
    self.training_type_plugin.setup_environment()
  File "/home/tmb/proj/webdataset-lightning/venv/src/pytorch-lightning/pytorch_lightning/plugins/training_type/ddp.py", line 108, in setup_environment
    self.setup_distributed()
  File "/home/tmb/proj/webdataset-lightning/venv/src/pytorch-lightning/pytorch_lightning/plugins/training_type/ddp.py", line 196, in setup_distributed
    self.init_ddp_connection()
  File "/home/tmb/proj/webdataset-lightning/venv/src/pytorch-lightning/pytorch_lightning/plugins/training_type/ddp.py", line 270, in init_ddp_connection
    torch_distrib.init_process_group(self.torch_distributed_backend, rank=global_rank, world_size=world_size)
  File "/home/tmb/proj/webdataset-lightning/venv/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 503, in init_process_group
    _update_default_pg(_new_process_group_helper(
  File "/home/tmb/proj/webdataset-lightning/venv/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 588, in _new_process_group_helper
    pg = ProcessGroupGloo(
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:769] connect [127.0.1.1]:6042: Connection refused
192.168.1.3$ 
```

```
192.168.1.9$ PL_TORCH_DISTRIBUTED_BACKEND=gloo MASTER_ADDR=192.168.1.3 MASTER_PORT=9888 NODE_RANK=1 python3 train.py --num_nodes=2 --gpus 1 --accelerator=ddp -b 32
training_urls =  ./shards/imagenet-train-{000000..000146}.tar
val_urls =  ./shards/imagenet-val-{000000..000006}.tar
batch_size 32 num_workers 6 world_size 0
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
... hangs ...
```

It looks like the jobs ignore the MASTER_ADDR and just pick their own on localhost anyway.

Source is here: https://github.com/tmbdev/webdataset-lightning/blob/f4d837dda1216ca0be8049c1a4297c49486b8ba2/train.py#L221

**Comment by awaelchli** [comment]
You need to select more than one GPU, otherwise it it will not run with the DDP plugin. This is why it ignores env variables that you supply

**Comment by tmbdev** [comment]
Just to summarize again: as a minimal test, I'm trying to start up distributed training between two nodes (192.168.1.3 and 192.168.1.9), each running one job, with each job getting one GPU.

It sounds like you are saying that `--gpus` specifies the total number of GPUs for the entire distributed job. However, that's not what the `--gpus` option seems to mean; not only does it alternatively allow the user to specify a list of local device numbers, specifying more gpus than _locally_ available fails:

```
$ PL_TORCH_DISTRIBUTED_BACKEND=gloo MASTER_ADDR=192.168.1.3 MASTER_PORT=9888 NODE_RANK=0 python3 train.py --num_nodes=2 --gpus 2 --accelerator=ddp -b 32
training_urls =  ./shards/imagenet-train-{000000..000146}.tar
val_urls =  ./shards/imagenet-val-{000000..000006}.tar
batch_size 16 num_workers 3 world_size 0
Traceback (most recent call last):
  File "train.py", line 243, in <module>
    main(args)
  File "train.py", line 228, in main
    trainer = pl.Trainer.from_argparse_args(args, plugins=plugs)
  File "/home/tmb/proj/webdataset-lightning/venv/src/pytorch-lightning/pytorch_lightning/trainer/properties.py", line 215, in from_argparse_args
    return from_argparse_args(cls, args, **kwargs)
  File "/home/tmb/proj/webdataset-lightning/venv/src/pytorch-lightning/pytorch_lightning/utilities/argparse.py", line 52, in from_argparse_args
    return cls(**trainer_kwargs)
  File "/home/tmb/proj/webdataset-lightning/venv/src/pytorch-lightning/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 40, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/tmb/proj/webdataset-lightning/venv/src/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 314, in __init__
    self.accelerator_connector = AcceleratorConnector(
  File "/home/tmb/proj/webdataset-lightning/venv/src/pytorch-lightning/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 119, in __init__
    self.parallel_device_ids = device_parser.parse_gpu_ids(self.gpus)
  File "/home/tmb/proj/webdataset-lightning/venv/src/pytorch-lightning/pytorch_lightning/utilities/device_parser.py", line 76, in parse_gpu_ids
    gpus = _sanitize_gpu_ids(gpus)
  File "/home/tmb/proj/webdataset-lightning/venv/src/pytorch-lightning/pytorch_lightning/utilities/device_parser.py", line 133, in _sanitize_gpu_ids
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: You requested GPUs: [0, 1]
 But your machine only has: [0]
```

If you look back to the beginning of this thread, this setup works fine with standard `torch.distributed`.

**Comment by tchaton** [comment]
Hey @tmbdev,

I actually get DDPPlugin. Mind checking on your side ?

```
def test_custom_cluster_env(tmpdir):

    class MyCluster(ClusterEnvironment):
        def __init__(self):
            super().__init__()

        def creates_children(self) -> bool:
            return True

        def master_address(self) -> str:
            return "192.168.1.3"

        def master_port(self) -> int:
            return 1234

        def world_size(self) -> int:
            return 2

        def set_world_size(self, size: int) -> None:
            pass

        def global_rank(self) -> int:
            return 0

        def set_global_rank(self, rank: int) -> None:
            pass

        def local_rank(self) -> int:
            return 0

        def node_rank(self) -> int:
            return 0

    trainer = Trainer(
        accelerator="ddp",
        default_root_dir=tmpdir,
        num_nodes=2,
        gpus=1,
        plugins=[MyCluster()]
    )

    assert isinstance(trainer.training_type_plugin, DDPPlugin)
```

**Comment by tchaton** [comment]
> Hey @tmbdev,
> 
> I actually get DDPPlugin. Mind checking on your side ?
> 
> ```
> def test_custom_cluster_env(tmpdir):
> 
>     class MyCluster(ClusterEnvironment):
>         def __init__(self):
>             super().__init__()
> 
>         def creates_children(self) -> bool:
>             return True
> 
>         def master_address(self) -> str:
>             return "192.168.1.3"
> 
>         def master_port(self) -> int:
>             return 1234
> 
>         def world_size(self) -> int:
>             return 2
> 
>         def set_world_size(self, size: int) -> None:
>             pass
> 
>         def global_rank(self) -> int:
>             return 0
> 
>         def set_global_rank(self, rank: int) -> None:
>             pass
> 
>         def local_rank(self) -> int:
>             return 0
> 
>         def node_rank(self) -> int:
>             return 0
> 
>     trainer = Trainer(
>         accelerator="ddp",
>         default_root_dir=tmpdir,
>         num_nodes=2,
>         gpus=1,
>         plugins=[MyCluster()]
>     )
> 
>     assert isinstance(trainer.training_type_plugin, DDPPlugin)
> ```

**Comment by tmbdev** [comment]
I have [modified the code](https://github.com/tmbdev/webdataset-lightning/blob/c6f3a6456fd956d89f9abe4d533d25803291b1b9/train.py) and it fails in the same way. 

In any case, this has nothing to do with my code (I only changed the data loader in the PL example). I get literally the same behavior with the [completely unmodified example from the PL distribution](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/domain_templates/imagenet.py)

So, the question is: how can I get DDP to work with `pl_examples/domain_templates/imagenet.py` when manually/ssh starting up two jobs on two different nodes? What are the right options to pass? Or does the code need to be modified in some way?

Starting a DDP training job by running multiple instances via ssh seems to me like something that ought to work somehow.

`MASTER_ADDR=192.168.1.3 MASTER_PORT=9988 python3 imagenet.py --accelerator ddp --num_nodes 2 --gpus 1 --data-path=...`

Hangs.

`MASTER_ADDR=192.168.1.3 MASTER_PORT=9988 NODE_RANK=0 python3 imagenet.py --accelerator ddp --num_nodes 2 --gpus 1 --data-path=...`

Fails with NCCL error on remote machine.

`PL_TORCH_DISTRIBUTED_BACKEND=gloo MASTER_ADDR=192.168.1.3 MASTER_PORT=9988 NODE_RANK=0 python3 imagenet.py --accelerator ddp --num_nodes 2 --gpus 1 --data-path=...`

Attempts to connect to `[127.0.1.1]:54709` on the master and fails, or hangs

**Comment by tmbdev** [comment]
[Here](https://github.com/tmbdev/webdataset-imagenet) is another repo that successfully does multinode training with plain PyTorch; the command to run it is `./run twonode master rank` in that repo. So I know the hardware works, DDP works, NCCL is properly configured, etc.

**Comment by rivi** [comment]
I was trying to run a very similar setup using AWS SageMaker (two instances executing `mpirun -np 1 ...`). The only difference seems to be that in my case each node has not one, but four GPUs. The same problems that @tmbdev mentioned happened to me as well.

**Comment by tchaton** [comment]
Hey @tmbdev,

Looking into this asap !
Thanks for sharing a reproducible script :)

Best,
T.C

**Comment by tchaton** [comment]
Hey @rivi, @tmbdev,

Would it be possible to have a reproducible script with a small public dataset already setup in a bucket ?

Best,
T.C

**Comment by tmbdev** [comment]
@tchaton Thanks. You don't need to use WebDataset at all; the I/O pipeline is unrelated. I couldn't get the example for the PL distribution to work:

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/domain_templates/imagenet.py

If you could show an example of pl_examples/domain_templates/imagenet.py where you ssh into host1 and host2, start up a training job manually with MASTER_ADDR and other options on both hosts, and then have it successfully start training, that would be great.

I can do this manually using standard PyTorch and no PL using a command like:

```
$ python -m torch.distributed.launch --use_env --nproc_per_node=1 --nnodes=2 --node_rank=$rank --master_addr=$master --master_port=9966 some_other_training_job.py --backend nccl
```

But I simply can't figure out the equivalent for PL.

**Comment by awaelchli** [comment]
As discussed offline, I believe you can force the behaviour you want with the workaround of setting this environment variable to True/1 in your command:

`PL_IN_DDP_SUBPROCESS=1`

I hope this works and at the very least it should get us closer to the solution.

**Comment by tchaton** [comment]
Dear @tmbdev,

Any updates ?

Best,
T.C

**Comment by tmbdev** [comment]
Thanks. I've only been able to test it on my desktop so far. I'll run it on the cluster again as soon as I have resources. (It's tricky to test because it's so hardware dependent.)

**Comment by edenlightning** [comment]
hey @tmbdev friendly ping :)

**Comment by iqbal786786** [comment]
> [Here](https://github.com/tmbdev/webdataset-imagenet) is another repo that successfully does multinode training with plain PyTorch; the command to run it is `./run twonode master rank` in that repo. So I know the hardware works, DDP works, NCCL is properly configured, etc.

The link is not working.

**Comment by iqbal786786** [comment]
Hi @awaelchli and @tchaton, I am a beginner in Pytorch and Pytorch Lightning. I am working in a company and I have access to two different machines having 4,8 GPUs respectively. I am just trying to learn how to train a model on two different nodes/machines. I tried it a lot over Google/Youtube but couldn't find a blog and documentation(in pytorch_lightning) that how to do it.

I am using VSCode to access remote machines. Please add end-to-end documentation for this. I am not having SLURM managed clusters, right.

For my understanding, the doc should look like(for general-purpose cluster), because I am a beginner:
1. Create Virtual env on both machines having the same distributions of libraries.
2. How to check whether two nodes have a connection on MASTER_PORT?
3. How to define environment variables on each node and what it is actually?
4. and How to query both machines with a toy example like MNIST
5. and How to write a simple train.py for MNIST?

Thanks a lot!

**Comment by iqbal786786** [comment]
> 
I have raised the below issue, please have a look, @awaelchli.
https://github.com/PyTorchLightning/pytorch-lightning/issues/12257
