### ISSUE TITLE
Name dataloader when returned in test_dataloader of LightningDataModule

### ISSUE THREAD

**Issue by LuoXin-s** [PyTorchLightning/pytorch-lightning#7010]
## 🚀 Feature
The ability that one can name `dataloader `when returned in `test_dataloader()` of `LightningDataModule`.

### Motivation

I may want to access the name of current dataloader's name when I have multiple `dataloader `returned from `test_dataloader()`, so that I can save my test results according to this speccific name.

**Comment by ananthsub** [comment]
Does the dataloader index work for you? You can maintain a map of index to name inside your module for convenience for naming
