### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch_lightning.logging'

### ISSUE THREAD

**Issue by v-sawant** [PyTorchLightning/pytorch-lightning#7044]
## Code
>> from pytorch_lightning.logging import NeptuneLogger
      ModuleNotFoundError: No module named 'pytorch_lightning.logging'

### Environment
python = 3.9.1
pytorch-lightning = '1.2.4'

**Comment by ananthsub** [comment]
Did you mean pytorch_lightning.loggers?

**Comment by v-sawant** [comment]
I was referring to older version of documentation. It was little hard to find the documentation of specific code version. 
@ananthsub Thanks you!

**Comment by xinzi2018** [comment]
i have the same question!

**Comment by Alongi666** [comment]
i have the same question!
