### ISSUE TITLE
DDPPlugin fails for multiple nodes in PL 1.2.8 

### ISSUE THREAD

**Issue by melanibe** [PyTorchLightning/pytorch-lightning#7060]
## 🐛 Bug
Using PL 1.2.8, multi-node training fails with `accelerator=ddp`. Precisely, the second node complains at initialization of processes with an AssertionError at `assert self.global_rank == 0` ([here](https://github.com/PyTorchLightning/pytorch-lightning/blob/832a03af7cae21bd4e6b7f752689a7ac6c2d4ce3/pytorch_lightning/plugins/training_type/ddp.py#L113)) in `_call_children_scripts` from `DDPPlugin` . 

### To Reproduce

No cluster available in the BoringModel

### Expected behavior
The `_call_children_scripts` has to be called for each node (not only on the master node), as this function starts the child processes for each individual gpu _per node_. Hence expected assert should be  `assert self.local_rank == 0` instead of `assert self.global_rank == 0`. After making this change, multi-node training works fine again 😃 

### Environment
 - PyTorch: 1.8.0
 - PL-lightning: 1.2.8
 - Python version:  3.7.3
 - GPU models and configuration: model trained on a cluster with multiple nodes with multiple gpus each.

**Comment by ananthsub** [comment]
@melanibe thanks for reporting! I sent #7061 to fix this

**Comment by awaelchli** [comment]
oh great fix!

**Comment by melanibe** [comment]
Sure, you're welcome :)

**Comment by shubhamwagh** [comment]
Hi, how can I use this fix in 1.2.8 PL version?
