### ISSUE TITLE
Investigate using Github CI

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#707]
## 🚀 Feature
Experiment with novel Github CI - action

### Motivation
having builds for all main os in single CI, so we can drop Travis and Appveyo 
We would keep CircleCI for future GPU testing...

**Comment by williamFalcon** [comment]
i heard bad things about github CI ...

**Comment by Borda** [comment]
Anything special? It was beta version till last month...

**Comment by Borda** [comment]
lets keep it open for now...
