### ISSUE TITLE
resume_from_checkpoint should not start from scratch if ckpt is not found

### ISSUE THREAD

**Issue by dsquareindia** [PyTorchLightning/pytorch-lightning#7072]
## 🐛 Bug

If the checkpoint file is not found at the location provided in `resume_from_checkpoint` argument in `pl.Trainer`, the training starts from scratch after displaying a `UserWarning` that is easy to miss.

### To Reproduce

Use the following [**BoringModel**](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing).

### Expected behavior

Should raise a `FileNotFoundError` and not start training from scratch.

**Comment by awaelchli** [comment]
Not sure if there is a real reason why we have warning instead of error. Want to give this a try? Contributions are welcome.

**Comment by ia-davidpichler** [comment]
I actually preferred the old semantics of this parameter as it makes my logic for an interruptible training job easier. Also the docs weren't updated to reflect this change: https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html#init

**Comment by carmocca** [comment]
> Also the docs weren't updated to reflect this change: https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html#init

@ia-davidpichler Would you be interested in opening a PR with the doc fix? 😄
