### ISSUE TITLE
DDP for multi-node jobs in non-slurm environments

### ISSUE THREAD

**Issue by sordonia** [PyTorchLightning/pytorch-lightning#7073]
## 🐛 Bug

When running DDP with num_nodes > 1 without a SLURM environment, the global rank is not computed correctly: global rank ends up being always equal to local rank, disregarding number of nodes. My hunch for why this is happening is that num_processes is not computed correctly.

My current solution is to create a custom plugin and explicitly pass num_nodes, please see below. I would need a bit of guidance to see how we can fix the current pytorch-lightning code in a less hacky way.

The following code works using the latest dev version (1.3.0rc1)

```
...

trainer = pl.Trainer(
  gpus=hparams.gpus,
  max_epochs=hparams.max_epochs,
  num_nodes=hparams.num_nodes,
  distributed_backend='ddp' if hparams.gpus > 1 else None,
  sync_batchnorm=hparams.gpus > 1,
  precision=hparams.precision,
  fast_dev_run=hparams.fast_dev_run,
  plugins=CustomPlugin(num_nodes=hparams.num_nodes),
  logger=logger)

...
```

```
class CustomEnvironment(LightningEnvironment):
    def __init__(self, num_nodes):
        super().__init__()
        self._creates_children = num_nodes > 1

    def creates_children(self):
        return self._creates_children

    def global_rank(self):
        rank = None
        if 'RANK' in os.environ:
            rank = int(os.environ.get("RANK"))
        return rank

    def master_address(self):
        return os.environ.get("MASTER_ADDR", "127.0.0.1")

    def master_port(self):
        return int(os.environ.get("MASTER_PORT", super().master_port()))

    def world_size(self):
        world_size = None
        if 'WORLD_SIZE' in os.environ:
           world_size = int(os.environ.get('WORLD_SIZE'))
        return world_size

    def node_rank(self):
        return int(os.environ.get("NODE_RANK", super().node_rank()))

    def local_rank(self) -> int:
        return int(os.environ.get("LOCAL_RANK", super().local_rank()))


class CustomPlugin(DDPPlugin):
    def __init__(self, num_nodes, **kwargs: Union[Any, Dict[str, Any]]) -> None:
        self.num_nodes = num_nodes
        super().__init__(
            cluster_environment=CustomEnvironment(num_nodes),
            find_unused_parameters=False,
            **kwargs,
        )

    @property
    def distributed_sampler_kwargs(self):
        distributed_sampler_kwargs = dict(num_replicas=self.world_size, rank=self.global_rank)
        return distributed_sampler_kwargs

    def set_world_ranks(self):
        self.local_rank = self.cluster_environment.local_rank()
        self.node_rank = self.cluster_environment.node_rank()
        self.global_rank = self.cluster_environment.global_rank()
        self.world_size = self.cluster_environment.world_size()
        
        # local run, this falls back to the current logic which is broken for
        # ddp and num_nodes > 1, I suspect the problem is in self.num_processes
        if self.global_rank is None:
            if self.num_nodes > 1:
                raise ValueError("Expected num_nodes > 1.")
            self.global_rank = self.num_processes * self.node_rank + self.local_rank
        if self.world_size is None:
            if self.num_nodes > 1:
                raise ValueError("Expected num_nodes > 1.")
            self.world_size = self.num_nodes * self.num_processes
```

**Comment by awaelchli** [comment]
How did you set the `NODE_RANK` environment variable when launching the processes? 
With the following debug script:

```python
import os
import torch
from torch.utils.data import Dataset
from pytorch_lightning import LightningModule, Trainer


class RandomDataset(Dataset):

    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):

    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        print("step", self.trainer.global_rank, self.trainer.local_rank, self.trainer.node_rank, self.trainer.world_size)
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)
        return {"x": loss}

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)
        return {"y": loss}

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    train_data = torch.utils.data.DataLoader(RandomDataset(32, 64), batch_size=2, num_workers=0)
    val_data = torch.utils.data.DataLoader(RandomDataset(32, 64), batch_size=2, num_workers=0)

    model = BoringModel()
    trainer = Trainer(
        gpus=2,
        num_nodes=2,
        accelerator="ddp",
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        num_sanity_val_steps=0,
        max_epochs=1,
        weights_summary=None,
    )
    print("init", trainer.global_rank, trainer.local_rank, trainer.node_rank, trainer.world_size)
    trainer.fit(model, train_dataloader=train_data, val_dataloaders=val_data)


if __name__ == '__main__':
    run()
```

If we run with e.g.` NODE_RANK=1 python debug.py`
The stdout prints (global_rank, local_rank, node_rank, world_size):

```
init 2 0 1 4
init 3 1 1 4
```

for the two processes on that node, which looks correct to me.

**Comment by awaelchli** [comment]
Apologies, I just noticed you said **1.3.0.rc1** and I thought you are running the latest.  But actually, the latest release is rc2 which has some cluster related things fixed. Mind try the update?

**Comment by sordonia** [comment]
It's a bit weird, I get:

2021-04-17 18:01:18 [1,3]<stderr>:  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 113, in _call_children_scripts
2021-04-17 18:01:18 [1,3]<stderr>:    assert self.local_rank == 0

Exactly 6 times (out of 8 opus, which makes sense). Is this how it is supposed to work?

**Comment by awaelchli** [comment]
With my example code above or with yours? Try mine first so we can be sure everything is setup correctly.
The local_rank 0 should launch all other processes on that machine and then continue training, but not until the all processes have initialized. 

On node 0 you need to call
`NODE_RANK=0 MASTER_ADDR=... MASTER_PORT=... python debug.py`
On node 1 you need to call
`NODE_RANK=1 MASTER_ADDR=... MASTER_PORT=... python debug.py`

**Comment by sordonia** [comment]
With my setup.

I see the problem: currently the platform I am currently using launches 8 processes automatically (creates_children must be set to return True), that's why 6 of them fail on the assert.

Can we customize the creates_children return value without a custom plugin?

**Comment by sordonia** [comment]
Update. If I set 1 process per node in the platform, it works great, thanks for the support and for the great tool.

If there's any interest in making customizing `creates_children` I can make a PR.

**Comment by awaelchli** [comment]
You are welcome. But what is this mysterious platform you are talking about? Does it have a name?

What did you have in mind? A setter? 
When we created the cluster environments, the intention was that they are a sort of look up table, a source of information about the type of environment. The idea is that this information is mostly static, because the cluster environment is not really expected to change dynamically. But I'm open to suggestion in #6303

**Comment by sordonia** [comment]
Yes :) AzureML.

I thought an option to Trainer: Trainer(..., environment_creates_children=True, ...), which would entail PL must assume the environment creates world_size processes.

Let me take a look

**Comment by awaelchli** [comment]
That would interfere with all cluster environments (currently we have slurm, torchelastic, and lightning). 
The best way currently would be to implement a `AzureMLEnvironment` inheriting from `ClusterEnvironment`.
That's the intended way to enable new clusters in Lightning.

**Comment by sordonia** [comment]
Is there a straightforward way for the user to specify to use the `AzureMLEnvironment` ?

**Comment by awaelchli** [comment]
I suggest this:

```python
class AzureEnvironment(ClusterEnvironment):
    ... # here override all abstract methods

trainer = Trainer(plugins=[AzureEnvironment()])
```

Need to document this
