### ISSUE TITLE
LR Schedulers shouldn't get `epoch` argument in `step` function

### ISSUE THREAD

**Issue by felixkreuk** [PyTorchLightning/pytorch-lightning#708]
## 🐛 Bug

PyTorch LR schedulers now shouldn't get any arguments in `step` function, see [here](https://github.com/pytorch/pytorch/blob/9e9bfbfd8d893cdf8205db67f220551214787d7f/torch/optim/lr_scheduler.py#L13-L20) and [here](https://github.com/pytorch/pytorch/issues/31828).

Looks like the calls in PytorchLightning are not in line with the new interface, see [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/dac59bb8d354f28b919d08aa369a7db6ab31bfa6/pytorch_lightning/trainer/training_loop.py#L334-L337).

This results in unexpected LR changes. Removing the `epoch` argument from `step` call solves the issue for me.

## Environment
PyTorch 1.4
PyTorchLightning 0.5.3.2

**Comment by williamFalcon** [comment]
good catch. we need to keep it backward compatible though

**Comment by Borda** [comment]
We shall catch it with a test...

**Comment by williamFalcon** [comment]
@Borda want to submit PR for this?

**Comment by williamFalcon** [comment]
@felixkreuk want  to submit a PR?
