### ISSUE TITLE
PyTorch Geometric Link Broken In Docs

### ISSUE THREAD

**Issue by aribornstein** [PyTorchLightning/pytorch-lightning#7083]
## 🐛 Bug

The link on this page doesn't resolve 

https://pytorch-lightning.readthedocs.io/en/latest/ecosystem/pytorch_ecoystem.html

We should consider highlighting other community ecosystem projects such as 
- https://github.com/manujosephv/pytorch_tabular
- https://github.com/asteroid-team/asteroid

**Comment by awaelchli** [comment]
Not sure why there is only one item in PyTorch Ecosystem examples. Should we simply combine this with the section "Community Examples"?

**Comment by tchaton** [comment]
Hey @awaelchli, I think the goal was to separate random projects using Lightning from PyTorch Ecosystem ones.
But it looks weird to have only 1.

**Comment by awaelchli** [comment]
One option is to have a single page with two sections until the list fills up with more examples.
