### ISSUE TITLE
core dump used with timm 0.3.2

### ISSUE THREAD

**Issue by linhx13** [PyTorchLightning/pytorch-lightning#7085]
## 🐛 Bug

core dump used with timm 0.3.2 and pytorch 1.8.1

## Please reproduce using the BoringModel

```python
import torch
import timm
import pytorch_lightning as pl
```
Run above code, it will core dump.

```python
import torch
import pytorch_lightning as pl
import timm
```
However, run this code, it's ok.

### To Reproduce

Use following [**BoringModel**](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing) and post here

### Expected behavior

Both codes should be ok.

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

* `IDE`: Please, use our python [bug_report_model.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
) template.

* `Colab Notebook`: Please copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py) (or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

* CUDA:
        - GPU:
                - GeForce RTX 2080 Ti
        - available:         True
        - version:           10.2
* Packages:
        - numpy:             1.18.5
        - pyTorch_debug:     False
        - pyTorch_version:   1.8.1+cu102
        - pytorch-lightning: 1.2.8
        - tqdm:              4.55.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.5
        - version:           #75~18.04.1-Ubuntu SMP Tue Feb 23 19:17:50 UTC 2021

**Comment by linhx13** [comment]
```python
import torch
import albumentations
from albumentations.pytorch.transforms import ToTensorV2
import pytorch_lightning as pl
import timm
```
And this will core dump too

albumentations              0.5.2

**Comment by awaelchli** [comment]
```
import torch
import timm
import pytorch_lightning as pl
```

no issue for me :( 

Both with timm==0.3.2 (as reported) and latest 0.4.
Try to install a fresh environment with only torch, timm, and lightning?



* CUDA:
        - GPU:
                - GeForce RTX 3090
                - GeForce RTX 3090
                - GeForce RTX 3090
                - GeForce RTX 3090
                - GeForce RTX 3090
                - GeForce RTX 3090
                - GeForce RTX 3090
                - GeForce RTX 3090
        - available:         True
        - version:           11.1
* Packages:
        - numpy:             1.20.2
        - pyTorch_debug:     False
        - pyTorch_version:   1.8.1+cu111
        - pytorch-lightning: 1.3.0rc2
        - tqdm:              4.60.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.8
        - version:           #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020

**Comment by linhx13** [comment]
yes, it's fine, thanks
