### ISSUE TITLE
Using SWA callback triggers useless deepcopy of data loaders

### ISSUE THREAD

**Issue by alexandrebone** [PyTorchLightning/pytorch-lightning#7089]
## 🐛 Bug

Using SWA callback triggers a deepcopy of the whole PyTorch Lightning module ("pl_module") at the on_before_accelerator_backend_setup hook (lines 140-142 of pytorch_lightning/callbacks/swa.py file). The PyTorch Lightning has the dataloaders as attributes, hence using deepcopy leads to the (useless) duplication of training and validation data loaders. 

### Expected behavior

No copy of the data loaders when initializing the _average_model attribute of the StochasticWeightAveraging callback. 

### Additional context

If data loaders occupy more than half of RAM, this deepcopy will lead to memory overflow.

**Comment by tchaton** [comment]
Dear @alexandrebone,

The `dataloaders` are wrapped into functions and it shouldn't cause an increase of memory during the deepcopy.

However, I am not sure about dataset. I will check.

Best,
T.c

**Comment by edenlightning** [comment]
@tchaton ping :)

**Comment by chrisby** [comment]
I also ran in OOM with SWA which does not run OOM when SWA is turned off.

**Comment by chrisby** [comment]
> I also ran in OOM with SWA which does not run OOM when SWA is turned off.

I guess in my case it was the deepcopy of the whole model, though.
