### ISSUE TITLE
imagenet_example cannot run

### ISSUE THREAD

**Issue by borisdayma** [PyTorchLightning/pytorch-lightning#709]
🐛 Bug

`imagenet_example` cannot be executed

### To Reproduce

1. Download imagenet
2. `cd pl_examples/full_examples/imagenet`
3. `python imagenet_example.py --data-path imagenet_path`

Error:

```
Traceback (most recent call last):
  File "imagenet_example.py", line 248, in <module>
    main(get_args())
  File "imagenet_example.py", line 229, in main
    model = ImageNetLightningModel(hparams)
TypeError: Can't instantiate abstract class ImageNetLightningModel with abstract methods forward
```

### Expected behavior

The example should run.

### Environment

PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 440.44
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] pytorch-lightning==0.6.0
[pip3] torch==1.3.1
[pip3] torchvision==0.4.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0

### Additional context

I suspect that there was breaking changes in the API and that the example is obsolete as the method `forward` is now expected.

**Comment by williamFalcon** [comment]
@neggert @Borda let's remove forward from being abstract?

**Comment by HarshSharma12** [comment]
I did a local fix for now by updating line 39 from **output = self.model(images)** to **output = self.forward(images)** and my forward function is just calling self.model

```
def forward(self, x):
        return self.model(x)
```

Also following issues also exist

1) Argument 'seed' must not be None as it breaks tensorboard writer. 
2) Argument 'data' might have been updated to 'data_path' recently but there are references to hparams.data in the dataloaders.

After fixing all three, I was able to run the example. 

I can create a PR if required.

**Comment by williamFalcon** [comment]
PR please!

**Comment by Rishabh-Choudhry** [comment]
I still get this issue when using conda installation of pytorch-lightning

**Comment by akihironitta** [comment]
@Rishabh-Choudhry Your issue could be a different issue since this issue is quite outdated. Could you create a new issue with your detail?

**Comment by gbeltramo** [comment]
I get the same error if I try to run the "Train a model (basic)" https://pytorch-lightning.readthedocs.io/en/latest/model/train_model_basic.html code after installing pytorch-lightning with `conda install pytorch-lightning -c conda-forge`

To fix the problem I had to run

```
conda remove pytorch-lightning
pip install pytorch-lightning
```

**Comment by UserA12345** [comment]
@gbeltramo thank you solved my issue as well
