### ISSUE TITLE
W&B: Allow for passing experiment into the WandbLogger (and logging semantics)

### ISSUE THREAD

**Issue by colehurwitz** [PyTorchLightning/pytorch-lightning#711]
Currently, the WandbLogger will automatically create a new internal experiment (run) whenever you create a new WandbLogger.

# Issue 

If I instantiate a wandb experiment outside of the logger, then I will have two experiments when I train my model since there is no way to set the internal experiment of the WandbLogger to my current external experiment.

# Potential Solution
Allow for passing an experiment into the WandbLogger:

```
class WandbLogger(LightningLoggerBase):
    def __init__(self, name=None, save_dir=None, offline=False, id=None, anonymous=False,
                 version=None, project=None, tags=None, experiment=None):
              .
              .
              .
              self._experiment = experiment
```
Then I can do this:

```
experiment = wandb.init(.......)
wandb_logger = WandbLogger(experiment=experiment)
```
I made this change locally, however, I wasn't sure if this was something you also wanted to implement as well. It works for me.

# Another small note

In the `WandbLogger.log_metrics` function, I would change:

`self.experiment.history.add(metrics)` --> `self.experiment.log(metrics)`

**Comment by williamFalcon** [comment]
@colehurwitz sounds good. feel free  to submit PR!

**Comment by colehurwitz** [comment]
Will do!

**Comment by neergaard** [comment]
@colehurwitz Which version of wandb are you using? When I try logging metrics with `self.logger.experiment.log(metric)`, I keep getting errors because the wandb `Run` object doesn't have a `log` method.

**Comment by colehurwitz** [comment]
Hi @neergaard, I am currently using `wandb 0.8.21`
