### ISSUE TITLE
error when importing the pytorch-lightning

### ISSUE THREAD

**Issue by karliesama** [PyTorchLightning/pytorch-lightning#7110]
I'm using python3.6-dev. I met this error when importing the pytorch-lightning

```
import pytorch_lightning as pl
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/__init__.py", line 63, in <module>
    from pytorch_lightning.callbacks import Callback
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.base import Callback
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/callbacks/base.py", line 22, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/lightning.py", line 39, in <module>
    from pytorch_lightning.core.saving import ALLOWED_CONFIG_TYPES, ModelIO, PRIMITIVE_TYPES
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/saving.py", line 41, in <module>
    from omegaconf.errors import UnsupportedValueType, ValidationError
ImportError: cannot import name 'UnsupportedValueType'
```

Please help me with this! Thanks a lot!!!

**Comment by akihironitta** [comment]
@karliesama Hi, thank you for reporting the issue. I couldn't reproduce the error in my local env below. Could you provide us with the information of your environment? (e.g. versions of `pytorch-lightning` and `omegaconf`)

<details><summary>my env</summary>

```console
$ wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
$ python collect_env_details.py
* CUDA:
	- GPU:
	- available:         False
	- version:           None
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.1
	- pytorch-lightning: 1.3.0rc2
	- tqdm:              4.60.0
* System:
	- OS:                Darwin
	- architecture:
		- 64bit
		-
	- processor:         i386
	- python:            3.6.13
	- version:           Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
$ python -c "import omegaconf; print(omegaconf.__version__)"                                                                                                                 
2.0.6
```

</details>

**Comment by tchaton** [comment]
Dear @karliesama,

Do you mind running those commands ?

```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
python collect_env_details.py
```

Best,
T.C

**Comment by karliesama** [comment]
> Dear @karliesama,
> 
> Do you mind running those commands ?
> 
> ```
> wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
> python collect_env_details.py
> ```
> 
> Best,
> T.C
```
Traceback (most recent call last):
  File "collect_env_details.py", line 30, in <module>
    import pytorch_lightning  # noqa: E402
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/__init__.py", line 63, in <module>
    from pytorch_lightning.callbacks import Callback
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.base import Callback
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/callbacks/base.py", line 22, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/lightning.py", line 39, in <module>
    from pytorch_lightning.core.saving import ALLOWED_CONFIG_TYPES, ModelIO, PRIMITIVE_TYPES
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/saving.py", line 41, in <module>
    from omegaconf.errors import UnsupportedValueType, ValidationError
ImportError: cannot import name 'UnsupportedValueType'
```

**Comment by kaushikb11** [comment]
@karkiesama Could you update lightning to the latest?

**Comment by akihironitta** [comment]
@karliesama Thank you for sharing the information. Lightning uses `omegaconf>=2.0.1`, so I believe running `pip install omegaconf -U` should fix the error. Please feel free to reopen this issue if the problem still persists.

**Comment by karliesama** [comment]
> pip install omegaconf -U

after running this line, I got this error when import pytorch-lightning in python.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/__init__.py", line 62, in <module>
    from pytorch_lightning import metrics
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/metrics/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/metrics/classification/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.functional.accuracy import _accuracy_compute, _accuracy_update
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/metrics/functional/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.functional.accuracy import accuracy  # noqa: F401
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/metrics/functional/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.classification.helpers import _input_format_classification, DataType
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/metrics/classification/helpers.py", line 19, in <module>
    from pytorch_lightning.metrics.utils import select_topk, to_onehot
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/metrics/utils.py", line 18, in <module>
    from pytorch_lightning.utilities import rank_zero_warn
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/apply_func.py", line 25, in <module>
    from pytorch_lightning.utilities.imports import _compare_version, _TORCHTEXT_AVAILABLE
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/imports.py", line 64, in <module>
    _HYDRA_EXPERIMENTAL_AVAILABLE = _module_available("hydra.experimental")
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/imports.py", line 34, in _module_available
    return find_spec(module_path) is not None
  File "/usr/lib/python3.6/importlib/util.py", line 88, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
  File "/usr/local/lib/python3.6/dist-packages/hydra/__init__.py", line 2, in <module>
    from . import utils
  File "/usr/local/lib/python3.6/dist-packages/hydra/utils.py", line 7, in <module>
    from hydra.plugins.common.utils import HydraConfig
  File "/usr/local/lib/python3.6/dist-packages/hydra/plugins/__init__.py", line 11, in <module>
    from .completion_plugin import CompletionPlugin
  File "/usr/local/lib/python3.6/dist-packages/hydra/plugins/completion_plugin.py", line 7, in <module>
    from omegaconf import DictConfig, ListConfig, Config, MissingMandatoryValue
ImportError: cannot import name 'Config'
```

**Comment by karliesama** [comment]
> @karkiesama Could you update lightning to the latest?

1.2.10 got the same error. Also, I have some other tools which are built upon 1.2.4. So I can only change the version to 0.9.0 to avoid the issue.

**Comment by dhananjaisharma10** [comment]
Hi! I'm facing the same issue.
I tried updating my PL version using
```
pip install pytorch-lightning==1.4.4
```
and did the following also:
```
pip install omegaconf -U
```
which gives me `omegaconf` version `2.1.1`.

Please help. Thanks! :)

**Comment by dhananjaisharma10** [comment]
Apparently, the error was not in either PL or Omegaconf. Doing the following solved my problem:
```bash
pip install hydra-core --upgrade
```
This issue might be helpful: https://github.com/PyTorchLightning/pytorch-lightning/issues/2197

Hope it helps!

**Comment by franchesoni** [comment]
I get another import error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs/users/marchesonif/.conda/envs/exp/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 54, in <module>
    from pytorch_lightning.callbacks import Callback
  File "/gpfs/users/marchesonif/.conda/envs/exp/lib/python3.9/site-packages/pytorch_lightning/callbacks/__init__.py", line 6, in <module>
    from pytorch_lightning.callbacks.progress import ProgressBarBase, ProgressBar
  File "/gpfs/users/marchesonif/.conda/envs/exp/lib/python3.9/site-packages/pytorch_lightning/callbacks/progress/__init__.py", line 22, in <module>
    from pytorch_lightning.callbacks.progress.progress import ProgressBar  # noqa: F401
  File "/gpfs/users/marchesonif/.conda/envs/exp/lib/python3.9/site-packages/pytorch_lightning/callbacks/progress/progress.py", line 17, in <module>
    from pytorch_lightning.utilities import rank_zero_deprecation
ImportError: cannot import name 'rank_zero_deprecation' from 'pytorch_lightning.utilities' (/gpfs/users/marchesonif/.conda/envs/exp/lib/python3.9/site-packages/pytorch_lightning/utilities/__init__.py)

Environment 1 where it happens:
# packages in environment at ...
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
absl-py                   1.1.0              pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.1            py39hb9d737c_1    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl  
blinker                   1.4                        py_1    conda-forge
blosc                     1.21.0               h8c45485_0  
brotli                    1.0.9                he6710b0_2  
brotlipy                  0.7.0           py39hb9d737c_1004    conda-forge
brunsli                   0.1                  h2531618_0  
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
cachetools                5.2.0                    pypi_0    pypi
certifi                   2022.6.15        py39hf3d152e_0    conda-forge
cffi                      1.15.1           py39he91dace_0    conda-forge
cfitsio                   3.470                hf0d0db6_6  
charls                    2.2.0                h2531618_0  
charset-normalizer        2.1.0              pyhd8ed1ab_0    conda-forge
click                     8.1.3            py39hf3d152e_0    conda-forge
cloudpickle               2.0.0              pyhd3eb1b0_0  
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
cramjam                   2.5.0                    pypi_0    pypi
cryptography              37.0.4           py39hd97740a_0    conda-forge
cudatoolkit               11.6.0              hecad31d_10    conda-forge
cytoolz                   0.11.0           py39h27cfd23_0  
dask-core                 2022.5.0         py39h06a4308_0  
fastparquet               0.8.1                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
freetype                  2.10.4               h0708190_1    conda-forge
frozenlist                1.3.0            py39hb9d737c_1    conda-forge
fsspec                    2022.5.0                 pypi_0    pypi
future                    0.18.2           py39hf3d152e_5    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
google-auth               2.9.1                    pypi_0    pypi
google-auth-oauthlib      0.4.6              pyhd8ed1ab_0    conda-forge
grpcio                    1.47.0                   pypi_0    pypi
idna                      3.3                pyhd8ed1ab_0    conda-forge
imagecodecs               2021.8.26        py39h4cda21f_0  
imageio                   2.9.0              pyhd3eb1b0_0  
importlib-metadata        4.12.0                   pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9e                   h166bdaf_2    conda-forge
jxrlib                    1.1                  h7b6447c_2  
krb5                      1.19.2               hac12032_0  
lame                      3.100             h7f98852_1001    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libaec                    1.0.4                he6710b0_1  
libcurl                   7.82.0               h0b77cf5_0  
libdeflate                1.8                  h7f8727e_5  
libedit                   3.1.20210910         h7f8727e_0  
libev                     4.33                 h7f8727e_1  
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libiconv                  1.17                 h166bdaf_0    conda-forge
libnghttp2                1.46.0               hce63b2e_0  
libnsl                    2.0.0                h7f98852_0    conda-forge
libpng                    1.6.37               h753d276_3    conda-forge
libprotobuf               3.15.8               h780b84a_1    conda-forge
libssh2                   1.10.0               h8f2d780_0  
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtiff                   4.2.0                h85742a9_0  
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   1.2.2                h55f646e_0  
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libzlib                   1.2.12               h166bdaf_1    conda-forge
libzopfli                 1.0.3                he6710b0_0  
llvm-openmp               14.0.4               he0ac6c6_0    conda-forge
locket                    1.0.0            py39h06a4308_0  
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markdown                  3.4.1                    pypi_0    pypi
mkl                       2021.4.0           h8d4b97c_729    conda-forge
mkl-service               2.4.0            py39h7e14d7c_0    conda-forge
mkl_fft                   1.3.1            py39h0c7bc48_1    conda-forge
mkl_random                1.2.2            py39hde0f152_0    conda-forge
multidict                 6.0.2            py39hb9d737c_1    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
networkx                  2.7.1              pyhd3eb1b0_0  
numerapi                  2.12.3                   pypi_0    pypi
numpy                     1.23.1                   pypi_0    pypi
oauthlib                  3.2.0              pyhd8ed1ab_0    conda-forge
openh264                  2.1.1                h780b84a_0    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1q               h166bdaf_0    conda-forge
packaging                 21.3               pyhd3eb1b0_0  
pandas                    1.4.3                    pypi_0    pypi
partd                     1.2.0              pyhd3eb1b0_1  
pillow                    9.0.1            py39h22f2fdc_0  
pip                       22.1.2             pyhd8ed1ab_0    conda-forge
protobuf                  3.19.4                   pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyarrow                   8.0.0                    pypi_0    pypi
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydeprecate               0.3.2                    pypi_0    pypi
pyjwt                     2.4.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1            py39hf3d152e_5    conda-forge
python                    3.9.13          h9a8a25e_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.12.0          py3.9_cuda11.6_cudnn8.3.2_0    pytorch
pytorch-lightning         1.6.5                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2022.1                   pypi_0    pypi
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pywavelets                1.3.0            py39h7f8727e_0  
pyyaml                    6.0              py39hb9d737c_4    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
rsa                       4.8                pyhd8ed1ab_0    conda-forge
scikit-image              0.19.2           py39h51133e4_0  
scikit-learn              1.1.1                    pypi_0    pypi
scipy                     1.7.3            py39hc147768_0  
setuptools                63.2.0                   pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                h295c915_0  
sqlite                    3.39.0               h4ff8645_0    conda-forge
submitit                  1.2.1              pyh44b312d_0    conda-forge
tbb                       2021.5.0             h924138e_1    conda-forge
tensorboard               2.9.1              pyhd8ed1ab_0    conda-forge
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2021.7.2           pyhd3eb1b0_2  
tk                        8.6.12               h27826a3_0    conda-forge
toolz                     0.11.2             pyhd3eb1b0_0  
torchmetrics              0.9.2                    pypi_0    pypi
torchvision               0.13.0               py39_cu116    pytorch
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
urllib3                   1.26.10            pyhd8ed1ab_0    conda-forge
werkzeug                  2.1.2              pyhd8ed1ab_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yarl                      1.7.2            py39hb9d737c_2    conda-forge
zfp                       0.5.5                h295c915_6  
zipp                      3.8.1                    pypi_0    pypi
zlib                      1.2.12               h166bdaf_1    conda-forge
zstd                      1.4.9                haebb681_0  

Environment 2 where it happens:
# packages in environment at ...
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
absl-py                   1.1.0              pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.1            py39hb9d737c_1    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl  
blinker                   1.4                        py_1    conda-forge
blosc                     1.21.0               h8c45485_0  
brotli                    1.0.9                he6710b0_2  
brotlipy                  0.7.0           py39hb9d737c_1004    conda-forge
brunsli                   0.1                  h2531618_0  
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
cachetools                5.2.0                    pypi_0    pypi
certifi                   2022.6.15        py39hf3d152e_0    conda-forge
cffi                      1.15.1           py39he91dace_0    conda-forge
cfitsio                   3.470                hf0d0db6_6  
charls                    2.2.0                h2531618_0  
charset-normalizer        2.1.0              pyhd8ed1ab_0    conda-forge
click                     8.1.3            py39hf3d152e_0    conda-forge
cloudpickle               2.0.0              pyhd3eb1b0_0  
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
cramjam                   2.5.0                    pypi_0    pypi
cryptography              37.0.4           py39hd97740a_0    conda-forge
cudatoolkit               11.6.0              hecad31d_10    conda-forge
cytoolz                   0.11.0           py39h27cfd23_0  
dask-core                 2022.5.0         py39h06a4308_0  
fastparquet               0.8.1                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
freetype                  2.10.4               h0708190_1    conda-forge
frozenlist                1.3.0            py39hb9d737c_1    conda-forge
fsspec                    2022.5.0           pyhd8ed1ab_0    conda-forge
future                    0.18.2           py39hf3d152e_5    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
google-auth               2.9.1              pyh6c4a22f_0    conda-forge
google-auth-oauthlib      0.4.6              pyhd8ed1ab_0    conda-forge
grpcio                    1.47.0                   pypi_0    pypi
idna                      3.3                pyhd8ed1ab_0    conda-forge
imagecodecs               2021.8.26        py39h4cda21f_0  
imageio                   2.9.0              pyhd3eb1b0_0  
importlib-metadata        4.12.0                   pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9e                   h166bdaf_2    conda-forge
jxrlib                    1.1                  h7b6447c_2  
krb5                      1.19.2               hac12032_0  
lame                      3.100             h7f98852_1001    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libaec                    1.0.4                he6710b0_1  
libcurl                   7.82.0               h0b77cf5_0  
libdeflate                1.8                  h7f8727e_5  
libedit                   3.1.20210910         h7f8727e_0  
libev                     4.33                 h7f8727e_1  
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libiconv                  1.17                 h166bdaf_0    conda-forge
libnghttp2                1.46.0               hce63b2e_0  
libnsl                    2.0.0                h7f98852_0    conda-forge
libpng                    1.6.37               h753d276_3    conda-forge
libprotobuf               3.15.8               h780b84a_1    conda-forge
libssh2                   1.10.0               h8f2d780_0  
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtiff                   4.2.0                h85742a9_0  
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   1.2.2                h55f646e_0  
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libzlib                   1.2.12               h166bdaf_1    conda-forge
libzopfli                 1.0.3                he6710b0_0  
llvm-openmp               14.0.4               he0ac6c6_0    conda-forge
locket                    1.0.0            py39h06a4308_0  
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markdown                  3.4.1              pyhd8ed1ab_0    conda-forge
mkl                       2021.4.0           h8d4b97c_729    conda-forge
mkl-service               2.4.0            py39h7e14d7c_0    conda-forge
mkl_fft                   1.3.1            py39h0c7bc48_1    conda-forge
mkl_random                1.2.2            py39hde0f152_0    conda-forge
multidict                 6.0.2            py39hb9d737c_1    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
networkx                  2.7.1              pyhd3eb1b0_0  
numerapi                  2.12.3                   pypi_0    pypi
numpy                     1.23.1                   pypi_0    pypi
numpy-base                1.22.3           py39hf524024_0  
oauthlib                  3.2.0              pyhd8ed1ab_0    conda-forge
openh264                  2.1.1                h780b84a_0    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1q               h166bdaf_0    conda-forge
packaging                 21.3               pyhd3eb1b0_0  
pandas                    1.4.3                    pypi_0    pypi
partd                     1.2.0              pyhd3eb1b0_1  
pillow                    9.0.1            py39h22f2fdc_0  
pip                       22.1.2             pyhd8ed1ab_0    conda-forge
protobuf                  3.19.4                   pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyarrow                   8.0.0                    pypi_0    pypi
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydeprecate               0.3.2                    pypi_0    pypi
pyjwt                     2.4.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39hf3d152e_5    conda-forge
python                    3.9.13          h9a8a25e_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.12.0          py3.9_cuda11.6_cudnn8.3.2_0    pytorch
pytorch-lightning         1.6.5                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2022.1                   pypi_0    pypi
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pywavelets                1.3.0            py39h7f8727e_0  
pyyaml                    6.0              py39hb9d737c_4    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
rsa                       4.8                pyhd8ed1ab_0    conda-forge
scikit-image              0.19.2           py39h51133e4_0  
scikit-learn              1.1.1                    pypi_0    pypi
scipy                     1.7.3            py39hc147768_0  
setuptools                63.2.0                   pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                h295c915_0  
sqlite                    3.39.0               h4ff8645_0    conda-forge
submitit                  1.2.1              pyh44b312d_0    conda-forge
tbb                       2021.5.0             h924138e_1    conda-forge
tensorboard               2.9.1              pyhd8ed1ab_0    conda-forge
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2021.7.2           pyhd3eb1b0_2  
tk                        8.6.12               h27826a3_0    conda-forge
toolz                     0.11.2             pyhd3eb1b0_0  
torchmetrics              0.9.2                    pypi_0    pypi
torchvision               0.13.0               py39_cu116    pytorch
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
urllib3                   1.26.10            pyhd8ed1ab_0    conda-forge
werkzeug                  2.1.2              pyhd8ed1ab_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yarl                      1.7.2            py39hb9d737c_2    conda-forge
zfp                       0.5.5                h295c915_6  
zipp                      3.8.1                    pypi_0    pypi
zlib                      1.2.12               h166bdaf_1    conda-forge
zstd                      1.4.9                haebb681_0  


Environment 3 (works OK)

Package                 Version
----------------------- ---------
absl-py                 1.1.0
aiohttp                 3.8.1
aiosignal               1.2.0
async-timeout           4.0.2
attrs                   21.4.0
cachetools              5.2.0
certifi                 2022.6.15
charset-normalizer      2.1.0
click                   8.1.3
cramjam                 2.5.0
fastparquet             0.8.1
frozenlist              1.3.0
fsspec                  2022.5.0
google-auth             2.9.1
google-auth-oauthlib    0.4.6
grpcio                  1.47.0
idna                    3.3
joblib                  1.1.0
Markdown                3.4.1
multidict               6.0.2
numerapi                2.12.3
numpy                   1.23.1
oauthlib                3.2.0
packaging               21.3
pandas                  1.4.3
pip                     22.1.2
protobuf                3.19.4
pyarrow                 8.0.0
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pyDeprecate             0.3.2
pyparsing               3.0.9
python-dateutil         2.8.2
pytorch-lightning       1.6.5
pytz                    2022.1
PyYAML                  6.0
requests                2.28.1
requests-oauthlib       1.3.1
rsa                     4.8
scikit-learn            1.1.1
scipy                   1.8.1
setuptools              58.1.0
six                     1.16.0
tensorboard             2.9.1
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
threadpoolctl           3.1.0
torch                   1.12.0
torchmetrics            0.9.2
tqdm                    4.64.0
typing_extensions       4.3.0
urllib3                 1.26.10
Werkzeug                2.1.2
wheel                   0.37.1
yarl                    1.7.2

**Comment by Weihua-Wang** [comment]
Maybe you installed hydra-core
`pip uninstall hydra-core`
