### ISSUE TITLE
What I use ddp, in validation_step that loged metric seems curious.

### ISSUE THREAD

**Issue by LuoXin-s** [PyTorchLightning/pytorch-lightning#7112]
## 🐛 Bug

I log the metric in validation_step, but I found the reported metric in tensorboard is uncorrect. I loged metric in every step toobserve, but have not found the reason. I mean I manual sum that together and divide `len(dataset)`, compare with tensorboard's value my value lower that it about **2**

### To Reproduce

Use following [**BoringModel**](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing) and post here

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

* `IDE`: Please, use our python [bug_report_model.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
) template.

* `Colab Notebook`: Please copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py) (or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by tchaton** [comment]
Dear @LuoXin-s ,

Would you mind to share a reproducible script for us to work on ?

Best,
T.C

**Comment by awaelchli** [comment]
Logging only happens on the first process/GPU in DDP. In general, you want to use torchmetrics which implement reduction correctly for you in DDP. 
If you want to just average (which is not always correct), you can consider `self.log(..., sync_dist=True)`. More explanation can be found in the docs.

**Comment by LuoXin-s** [comment]
@awaelchli 
Thank you for reminding me, but why this `sync_dist` feature set to false as default. When I work on single GPU `sync_dist=True` have any problem?

**Comment by awaelchli** [comment]
Because it has a minor performance hit due to additional communication. And you would notice this when syncing per step logging. But also, it's not truly syncing the metric in the sense that reduction is always mean and this is not correct for most metrics. See torchmetrics, it is explained there: https://torchmetrics.readthedocs.io/en/latest/pages/overview.html#overview
Let me know if this is unclear

**Comment by awaelchli** [comment]
Btw which version of Lightning are you using? We have fixed a related bug  #6138, make sure you use the latest version of Lightning to avoid it :)

**Comment by awaelchli** [comment]
Hello, @LuoXin-s  any updates here?

**Comment by LuoXin-s** [comment]
@awaelchli  Sorry for the untimely response, I'm busy on my graduation thesis. Btw when I use `sync_dist` it seems correct and I use  lightning 1.2.5

**Comment by awaelchli** [comment]
Okay, sounds good. Feel free to reopen the issue if you find inaccuracies. 
Good luck with your thesis.
