### ISSUE TITLE
convert examples to doctests

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#714]
## 🚀 Feature

Converting examples to doctests...

### Motivation

The examples now are static so there is no guarantee that they are still valid... 
**Advantages** of converting to doctest would:
- increase reproducibility
- each example can run as a stand-alone
- make testing on smaller units
- smaller test units simplify debugging

### Additional context

* https://docs.python.org/3/library/doctest.html
* https://thomas-cokelaer.info/tutorials/sphinx/doctest.html
* https://stackoverflow.com/questions/361675/python-doctest-vs-unittest

**Comment by Borda** [comment]
I would say to use doctest for small functionalities where we want to use it also as examples in docs and unittest for extension testing, for example, catching fail cases or running multiple edge test-cases

**Comment by awaelchli** [comment]
I can keep working on this if you like.

**Comment by Borda** [comment]
just pls do it by small pieces as you started so it is easier to merge / less potential conflicts to resolve lol

**Comment by awaelchli** [comment]
Many of the examples in LightningModule are just a method, something like this:

```
def training_epoch_end(self, outputs):
    train_acc_mean = 0
    for output in outputs:
        train_acc_mean += output['train_acc']

    train_acc_mean /= len(outputs)

    # log training accuracy at the end of an epoch
    results = {
        'log': {'train_acc': train_acc_mean.item()}
    }
    return results
```
Should we doctest this or not? Basically it would only do syntax check in this case, nothing else. What do you think?

**Comment by awaelchli** [comment]
just adding a reminder here that we may want to enable doctest for .rst files. ([comment](https://github.com/PyTorchLightning/pytorch-lightning/pull/1484#pullrequestreview-392655204)) 

`make doctest` currently raises many import errors
