### ISSUE TITLE
Problem with using multiple TPU cores and the WandbLogger

### ISSUE THREAD

**Issue by kaushikb11** [PyTorchLightning/pytorch-lightning#7142]
#### Query from User on Lightning Slack

There seems to be a problem with using multiple TPU cores and the WandbLogger. When I run with a single TPU core everything works fine & the results from my experiment get logged. However, if I then switch to 8 cores everything seems to run ok but nothing gets logged to WandB.

**Comment by tgisaturday** [comment]
@kaushikb11 I'll give a try and fix it.
