### ISSUE TITLE
 RuntimeError: CUDA error: device-side assert triggered #11366 

### ISSUE THREAD

**Issue by abb4s** [PyTorchLightning/pytorch-lightning#7145]
## 🐛 Bug
i tried to finetune bertForClassification and it raised  RuntimeError: CUDA error: device-side assert triggered #11366 
after that I can't move anything to  gpu even simple tensor:
![image](https://user-images.githubusercontent.com/7654832/115618986-9e8c6900-a308-11eb-8f10-23f592cde04b.png)

### To Reproduce

[colab notebook](https://colab.research.google.com/drive/1rnvMfNim187TlCDb1ureW3zmXq-LUW7W?usp=sharing)

### Environment

google colab

**Comment by tchaton** [comment]
Dear @abb4s,

I checked your code. 
I have seen several mis-uses in your code.
* Encoding should be done in dataset
* You are trying to decode, when you should be encoding
* You should have to move any tensors to device. Lightning does this for you.

You could have a look at this example: https://github.com/PyTorchLightning/lightning-flash/blob/master/flash_examples/finetuning/text_classification.py#L22 or https://github.com/PyTorchLightning/lightning-transformers.

Best,
T.C

**Comment by edenlightning** [comment]
feel free to reopen if needed.
