### ISSUE TITLE
Integration of Deep Graph Library (DGL) into Lightning

### ISSUE THREAD

**Issue by sophiakrix** [PyTorchLightning/pytorch-lightning#7164]
## 🚀 Feature
Integrating DGL into PyTorch Lightning 

### Motivation

DGL uses graphs as a basic data structure. That means their [dataloaders](https://docs.dgl.ai/en/latest/_modules/dgl/dataloading/pytorch.html#EdgeDataLoader) use graphs such as the [dgl.DGLHeteroGraph](https://docs.dgl.ai/en/latest/generated/dgl.heterograph.html) as input for their dataloader and process them. The output returned in every iteration by the `dgl.EdgeDataLoader` for example is a tuple of positive and negative samples and the data structures necessary to compute the forward pass. 
Right now, if the dgl.EdgeDataLoader is used in Lightning, it throws an error:
```
    input_nodes, positive_graph, negative_graph, blocks = train_batch
TypeError: cannot unpack non-iterable _EdgeDataLoaderIter object
```

It would be great to be able to use their dataloader with lightning to also work on graphs.

### Pitch

Integration of the dgl.EdgeDataLoader as a possible dataloader for Pytorch Lightning.

### Alternatives
Implementing the dataloader usage itself as suggested by BarclayII here: https://github.com/snap-stanford/ogb/blob/master/examples/lsc/mag240m/rgnn.py 

### Additional context

Here is a minimal working example to reproduce the error:
```
import dgl
import pytorch_lightning as pl
import torch
import torch.nn.functional as F

data_dict = {

    ('user', 'follows', 'user'): (torch.tensor([0, 1]), torch.tensor([1, 2])),

    ('user', 'follows', 'topic'): (torch.tensor([1, 1]), torch.tensor([1, 2])),

    ('user', 'plays', 'game'): (torch.tensor([0, 3]), torch.tensor([3, 4]))

}


class DataModule(pl.LightningDataModule):
    def __init__(self):
        super().__init__()
        self.sampler = dgl.dataloading.MultiLayerFullNeighborSampler(2)
        self.g = g
        self.train_eid_dict = {
            ('user', 'follows', 'user'): (torch.tensor([0]), torch.tensor([1]))
        }
        self.val_eid_dict = {
            ('user', 'follows', 'topic'): (torch.tensor([1]), torch.tensor([1]))
        }

    def train_dataloader(self) -> dgl.dataloading.EdgeDataLoader:
        dataloader = dgl.dataloading.EdgeDataLoader(
            g=self.g,
            eids=self.train_eid_dict,
            block_sampler=self.sampler,
            batch_size=1,
            shuffle=True,
            drop_last=False,
        )
        return dataloader

    def val_dataloader(self) -> dgl.dataloading.EdgeDataLoader:
        dataloader = dgl.dataloading.EdgeDataLoader(
            g=self.g,
            eids=self.train_eid_dict,
            block_sampler=self.sampler,
            batch_size=1,
            shuffle=True,
            drop_last=False,
        )
        return dataloader

class LitModel(pl.LightningModule):

     def __init__(self):
         super().__init__()
         self.layer_1 = torch.nn.Linear(28 * 28, 128)

     def forward(self, x):
         return torch.relu(self.l1(x.view(x.size(0), -1)))

     def training_step(self, batch, batch_idx):
         x, y = batch
         y_hat = self(x)
         loss = F.cross_entropy(y_hat, y)
         return loss

     def configure_optimizers(self):
         return torch.optim.Adam(self.parameters(), lr=0.02)



if __name__ == '__main__':

    g = dgl.heterograph(data_dict)

    model = LitModel()

    datamodule = DataModule()

    trainer = pl.Trainer()
    trainer.fit(model=model, datamodule=DataModule())

```

**Comment by sophiakrix** [comment]
Hi @justusschock , is there any news about the integration?

Best, Sophia

**Comment by justusschock** [comment]
Hi @sophiakrix 

Sorry for not getting back to you sooner.

The reason, why the code doesn't work (especially the line `x, y = batch` ) is because batch here is an object of `dgl.dataloading.pytorch._EdgeDataLoaderIter`. I don't know much about dgl internals, so I am not yet sure why this happens (probably some issue with custom loader class), but I'll report back :)

Do you have an idea on why this could return the item object on `next` instead of the actual batch?

**Comment by justusschock** [comment]
One workaround that works, is to manually call `batch = next(batch)`. But that really isn’t supposed to happen.

**Comment by justusschock** [comment]
@sophiakrix I think I found the issue: the DGL Dataloaders user custom iterators that aren't recognized as subclasses since it does not provide a `__iter__` function. So when we call `next` on each `Iterator`, the `isinstance(dataloader_iter, Iterator)` fails which is why we return the iter as is. This should be fixed in https://github.com/dmlc/dgl/pull/2886

**Comment by sophiakrix** [comment]
@justusschock this sounds logic! Thanks for having such a deep look into it. Does it mean that your fix in [dmlc/dgl#2886](https://github.com/dmlc/dgl/pull/2886) makes the DGL dataloader now compatible with PyTorch Lightning?

**Comment by justusschock** [comment]
@sophiakrix yes, that should fix it and provide compatibility.

**Comment by edenlightning** [comment]
Feel free to reopen if needed.
