### ISSUE TITLE
Add Optuna integrated badge to README.md

### ISSUE THREAD

**Issue by Crissman** [PyTorchLightning/pytorch-lightning#718]
Hi!

Optuna (optuna.org) is a new hyperparameter optimization library, and we’ve written an Optuna integration module for PyTorch Lightning to make it easy to search for good hyperparameter settings and prune unpromising trials. We’re looking for ways to let PyTorch Lightning users know this is available and thought a badge, like this

[![Optuna](https://img.shields.io/badge/Optuna-integrated-blue)](https://optuna.org)

to show Optuna integration is available would be helpful.

Here’s our example of using the pruning integration with PyTorch Lightning: https://github.com/optuna/optuna/blob/master/examples/pytorch_lightning_simple.py

If there are other ways you would recommend reaching out to PyTorch Lightning users to let them know about Optuna, please let us know.

If you're ok with adding this badge to the README, let me know and I'll create a PR.

Thanks!

**Comment by Borda** [comment]
I think that it would be better to add the example, @williamFalcon?

**Comment by williamFalcon** [comment]
@Crissman this is really cool! why don't we  instead  put together  a blogpost with  the example and  link this  example  to our docs?

**Comment by williamFalcon** [comment]
@Crissman added you to our docs (look in hyperparameters with 0.7.0 release)

**Comment by Crissman** [comment]
Thanks!
