### ISSUE TITLE
Model checkpoint cannot find monitored metric when using torchmetric collection with prefix

### ISSUE THREAD

**Issue by itsikad** [PyTorchLightning/pytorch-lightning#7235]
## 🐛 Bug
Hi,

`Modelcheckpoint` callback fails to find the monitored metric (e.g, 'val_mse') when using `torchmetrics.MetricCollection` clone method with prefix='val_'.

[Boring model](https://colab.research.google.com/drive/1sM7UQc0EnRyqswjAX_pP8KI0bOMcSgAW?usp=sharing)

Versions:
lightning=1.2.10
torchmetrics=0.3.1

**Comment by Borda** [comment]
@itsikad mind share example to reproduce, ideally with the boring model?

**Comment by itsikad** [comment]
@Borda the link doesn't work for you?

**Comment by tchaton** [comment]
Hey @itsikad,

I confirm the link works ! Looking into it !

Best,
T.C

**Comment by awaelchli** [comment]
The linked PR marks this as fixed. Closing.
