### ISSUE TITLE
TensorMetric cannot be imported

### ISSUE THREAD

**Issue by Wufang1997** [PyTorchLightning/pytorch-lightning#7248]
Hi, I cannot import TensorMetric in my 1.2.10 version of pytorch lightning. I found that others used it successfully in 0.9.0. Does this function deprecate in a higher version?

**Comment by Borda** [comment]
@Wufang1997 can you share some more details and what libs do you have installed?
```
pip list | grep lightning
pip list | grep torch
```

**Comment by SkafteNicki** [comment]
`TensorMetric` was removed in v1.0 of lightning when metrics was completely revamped in this PR https://github.com/PyTorchLightning/pytorch-lightning/pull/3868.
All metric development has been moved to [torchmetrics](https://torchmetrics.readthedocs.io/en/latest/) and I recommend that you checkout the base metric class `torchmetrics.Metric` that hopefully should fill out your needs.
