### ISSUE TITLE
automatic metric selection filename ModelCheckpoint

### ISSUE THREAD

**Issue by cemde** [PyTorchLightning/pytorch-lightning#7260]
## 🚀 Feature

when configuring the `filename` for the `ModelCheckpoint`, it might be nice to have an option to automatically paste the metric used for monitoring.

### Motivation

This would simplify setting up the ModelCheckpoint saving by dynamically creating the filename template.

### Pitch

Reserve "{\_\_monitor\_\_}" to be automatically set to the variable used for monitoring by `monitor=`. For example:

```
    cp = ModelCheckpoint(
        dirpath=dirpath,
        filename='{epoch}-{step}-{__monitor__:.2f}',
        save_top_k=3,
        mode='max',
        monitor='val_accuracy',
        )
```

could save the checkpoint to `epoch=1-step=2-val_accuracy=0.99.ckpt`.

**Comment by awaelchli** [comment]
Could we just treat the monitor internally in the callback the same as the callback metrics? Then we wouldn't need a special syntax and can just do: `filename='{epoch}-{step}-{monitor:.2f}',` for the same result?

**Comment by tchaton** [comment]
Yes, I think it would be pretty neat.

**Comment by tchaton** [comment]
@cemde, 

would you like to give it a try and make a PR ?

**Comment by carmocca** [comment]
I don't see what's the benefit of adding support for this considering how easy it is for the users to do it themselves with plain python f-strings

```python
monitor='val_accuracy'
mc = ModelCheckpoint(
    dirpath=dirpath,
    filename='{epoch}-{step}-' + f'{{{monitor}:.2f}}',
    save_top_k=3,
    mode='max',
    monitor=monitor,
)
```

where the filename will resolve to `'{epoch}-{step}-{val_accuracy:.2f}'`
