### ISSUE TITLE
KeyError: 0 when using multiple optimizer 

### ISSUE THREAD

**Issue by choieq** [PyTorchLightning/pytorch-lightning#7263]
## 🐛 Bug

I use 3 optimizer for training my model. 
It trains well, but got error when end of epoch 1. 

When self.current_epoch%2 ==0 Model is trained  by using one optimizer and 
self.current_epoch%==1 model is trained by using two optimizer.

 
### To Reproduce
https://colab.research.google.com/drive/1s8sIN02Uhiox9In0kHMpqxgYxK3o6zKx?usp=sharing

### Expected behavior
Multiple optimizer idx ?? 

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

* `IDE`: Please, use our python [bug_report_model.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
) template.

* `Colab Notebook`: Please copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py) (or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

 - PyTorch Version (e.g., 1.0):  1.6.0
 - PyTorch-lightning Version: 1.1.0
 - OS (e.g., Linux): ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): conda 
 - Build command you used (if compiling from source): 
 - Python version: 3.8.5
 - CUDA/cuDNN version: 
 - GPU models and configuration: 2080ti
 - Any other relevant information:

**Comment by tchaton** [comment]
Dear @choieq,

Thanks for reporting this bug.
I will look into it.

Best,
T.C

**Comment by choieq** [comment]
> Dear @choieq,
> 
> Thanks for reporting this bug.
> I will look into it.
> 
> By the way, you are using pretty old API for logging.
> 
> Use `self.log` and `self.log_dict` instead of providing back a dictionary.
> 
> ```
> def training_step(...):
> 
>     loss = ...
>     self.log("loss", loss, on_step=True, on_epoch=True, ...)
> ```
> 
> Here is the doc: https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.core.lightning.html#pytorch_lightning.core.lightning.LightningModule.log
> 
> Best,
> T.C

it works well, after i update pytorch-lightning! 

Thank you for your quick reply. 

Best,
choieq

**Comment by tchaton** [comment]
Hey @choieq,

```
def test_multiple_optimizers(tmpdir):

    class CustomModel(BoringModel):

        def __init__(self):
            super().__init__()

            self.layer = nn.Sequential(
                nn.Linear(32, 32),
                nn.Linear(32, 32),
                nn.Linear(32, 2)
            )

        def configure_optimizers(self):
            opt_1 = torch.optim.SGD(self.layer[0].parameters(), lr=0.1)
            opt_2 = torch.optim.SGD(self.layer[1].parameters(), lr=0.1)
            opt_3 = torch.optim.SGD(self.layer[2].parameters(), lr=0.1)
            return [opt_1, opt_2, opt_3]

        def training_step(self, batch, batch_idx, optimizer_idx):

            # train generator (pair)
            if ((self.current_epoch % 2)) == 0 and (optimizer_idx==0):
                loss =  super().training_step( batch, batch_idx)
                self.log("loss_1", loss["loss"])
                return loss

            # train generator (unpair)
            elif (self.current_epoch % 2) == 1 and (optimizer_idx==1):
                loss =  super().training_step( batch, batch_idx)
                self.log("loss_2", loss["loss"])
                return loss

            # train discriminator
            elif (self.current_epoch % 2) == 1 and (optimizer_idx == 2):
                loss =  super().training_step( batch, batch_idx)
                self.log("loss_3", loss["loss"])
                return loss

    model = CustomModel()
    model.training_epoch_end = None
    trainer = pl.Trainer(max_epochs=3)
    trainer.fit(model)
    assert list(trainer.callback_metrics.keys()) == ['loss_1', 'loss_2', 'loss_3']
```

**Comment by tchaton** [comment]
Hey @choieq,

Thanks for letting me know :) 
Quick note for the next issue. Would you mind to provide a reproducible script using the BoringModel as I couldn't run your notebook :)

Best,
T.C

**Comment by choieq** [comment]
**Can i share my gitlab code ??**
It's complicate to write reproducible script code by using colab.
Actually, i don't familiar with colab .. 

After updating pytorch-lightning version the "KeyError" is gone, but the GPU error such as "Caught RuntimeError in replica 0 on device 4" in the middle of training. 
And i tried use **acclerate=ddp**, but it causes Out of Memory(OOM), so i use DP Mode..

Thanks,
choieq
