### ISSUE TITLE
trainer.plugins has incorrect type declaration and plugins/environments do not inherit from Plugin

### ISSUE THREAD

**Issue by leezu** [PyTorchLightning/pytorch-lightning#7287]
Per https://pytorch-lightning.readthedocs.io/en/latest/clouds/cluster.html users can declare custom clusterenvironment and pass it as trainer plugin

```
import os
from pytorch_lightning.plugins.environments import ClusterEnvironment

class MyClusterEnvironment(ClusterEnvironment):

    def creates_children(self) -> bool:
        # return True if the cluster is managed (you don't launch processes yourself)
        return True

    def world_size(self) -> int:
        return int(os.environ["WORLD_SIZE"])

    def global_rank(self) -> int:
        return int(os.environ["RANK"])

    def local_rank(self) -> int:
        return int(os.environ["LOCAL_RANK"])

    def node_rank(self) -> int:
        return int(os.environ["NODE_RANK"])

    def master_address(self) -> str:
        return os.environ["MASTER_ADDRESS"]

    def master_port(self) -> int:
        return int(os.environ["MASTER_PORT"])


trainer = Trainer(plugins=[MyClusterEnvironment()])
```

However, ClusterEnvironment fails to inherit from Plugin and is thus not a valid argument to Trainer(plugins):

https://github.com/PyTorchLightning/pytorch-lightning/blob/338f5a331155d61a9d94168480ca45c264821019/pytorch_lightning/plugins/environments/cluster_environment.py#L17-L18

Further the type specification of trainer is incorrect (`list`):  

https://github.com/PyTorchLightning/pytorch-lightning/blob/338f5a331155d61a9d94168480ca45c264821019/pytorch_lightning/trainer/trainer.py#L139

**Comment by amogkam** [comment]
The docs are actually incorrect here I believe. The cluster environment should be passed into a plugin, it is not a plugin itself.

**Comment by leezu** [comment]
@amogkam Passing cluster environment to a plugin is valid, but appears not to be required. If cluster environment is passed as a plugin itself, the accelerator connector appears to take care of passing it to the respective other plugins:

https://github.com/PyTorchLightning/pytorch-lightning/blob/338f5a331155d61a9d94168480ca45c264821019/pytorch_lightning/trainer/connectors/accelerator_connector.py#L200-L214

and then

https://github.com/PyTorchLightning/pytorch-lightning/blob/338f5a331155d61a9d94168480ca45c264821019/pytorch_lightning/trainer/connectors/accelerator_connector.py#L439-L457
