### ISSUE TITLE
Modify hook on_batch_start() API to support other iterable dataloaders

### ISSUE THREAD

**Issue by chutaklee** [PyTorchLightning/pytorch-lightning#729]
### Motivation
By default ` LightningModule.train_dataloader()` and etc return a PyTorch DataLoader, but it can be easily extended to other iterable objects by converting to vanilla batch in `on_batch_start()`

### Pitch
```python3
def on_batch_start(self, batch):
    # do something
    # before
    return response
    # after
    return batch, response # batch is (Tensor, Tensor)
```

```python3
# example of using torchtext for NMT
@pl.data_loader
def train_dataloader(self):
    return torchtext.data.BucketIterator(dataset, batch_size)

def on_batch_start(self, batch):
    x, y = batch.src, batch.trg
    return (x, y), None
```

### Alternatives
Normally I can do this in `forward()`, but when using multiple gpus, it's better to let Lightning handle batch transfer.

### Additional context

Implementation in my fork https://github.com/chutaklee/pytorch-lightning/commit/b81c0ba1fcc01530f8e66a66f8e522c10826f797

Since it is not backward compatible(for those who've used `on_batch_start()` in their models), and I haven't make it to tests yet, so I'm not so sure, though it seems like a nice feature.

**Comment by colllin** [comment]
Have you tried using a DataLoader with an [IterableDataset](https://pytorch.org/docs/stable/data.html#iterable-style-datasets)?  Or is that not what you're asking?

**Comment by chutaklee** [comment]
> Have you tried using a DataLoader with an [IterableDataset](https://pytorch.org/docs/stable/data.html#iterable-style-datasets)? Or is that not what you're asking?

Accoring to my limited understanding, IterableDataset mainly solves expensive reads of data.
What I want is accept batches of other datatypes returned by non standrad dataloaders.

**Comment by Borda** [comment]
@chutaklee may you consider creating a PR?

**Comment by chutaklee** [comment]
> @chutaklee may you consider creating a PR?

Sure, as long as we agree this is what we want.

**Comment by chutaklee** [comment]
Maybe we can pass batches as mutable obejcts and modify in-place inside `on_batch_start`, then we don't need to break the consistency of hooks normally don't return at all.

**Comment by Borda** [comment]
@neggert @jeffling ^^

**Comment by Borda** [comment]
in the actual version, you can use a model hook which has the batch or [Callback](https://pytorch-lightning.readthedocs.io/en/latest/callbacks.html#callbacks) where you have access to both `trainer` and `model`
Thx you for your interest and interesting point, feel free to reopen if needed :robot:
