### ISSUE TITLE
Remove DataLoader warning for num_workers when using GPU

### ISSUE THREAD

**Issue by fonnesbeck** [PyTorchLightning/pytorch-lightning#7290]
## 🐛 Bug

When `num_workers` is specified as zero on a multicore machine in a DataLoader, you get the following warning:

    UserWarning: The dataloader, train dataloader, does not have many workers which may be a bottleneck. 
    Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.

This is fine when the model is being fit using CPUs, but is not sound advice when using GPUs and data are being loaded to the GPU with `.to(device)`. Can this message be turned off when cuda is specified as the device?

## Environment

* OS: Ubuntu
* Python version: 3.7.10
* PyTorch version: 1.8
* Lightning version: 1.0.8
* CUDA/cuDNN version: 11

**Comment by awaelchli** [comment]
Hi @fonnesbeck 
Where did you get that from? Can you name some references? I don't understand how one would reason against using multiple workers per GPU. 

Without a doubt, giving a good rule of thumb is difficult as there are many factors that play into the efficiency of loading data with multiprocessing.

**Comment by fonnesbeck** [comment]
OK, I think I have misunderstood what I have read in various places (the pytorch forum appears to be down right now, so I can't reference some of them). I'm getting RunTime errors with this on AWS, but this appears to be related to the multiprocessing settings. 

I will close this.
