### ISSUE TITLE
Unable to set optimizer state

### ISSUE THREAD

**Issue by cutecows** [PyTorchLightning/pytorch-lightning#7320]
## 🐛 Bug

I'm trying to restore the model using the resume_from_checkpoint. However, I am experiencing instability after the load, similar to #2613. I suspect this is because trainer.fit() calls configure_optimizers after restoring the optimizer, thus overwriting the previously restored value. Thus, I am additionally trying to set the optimizer in configure_optimizers, however, this leads to the process being killed. 
### To Reproduce
I do not have this issue in the BoringModel.

def configure_optimizers(self):
        betas = (0.9, 0.999)
        eps = 1e-6
        optim = torch.optim.Adam(self.parameters(),lr=self.lr,betas=betas,eps=eps)
        checkpoint = torch.load('......ckpt')
        optimizer_state = checkpoint['optimizer_states'][0]
        optim.load_state_dict(optimizer_state)
        #self.trainer.checkpoint_connector.restore_training_state(checkpoint)
        return {'optimizer': optim, 'monitor': 'val_loss'}

### Expected behavior

I would not expect restoring the state of the optimizer to kill the process.

### Environment

Pytorch Lightning 1.2.3
Pytorch 1.7.1
Installed torch with conda
Python version 3.7.1
Cuda version 10.2
Tesla V100

**Comment by Akanni96** [comment]
Prior to the most recent couple releases, I was able to use the following code  to ensure that the all optimizer settings were reloaded.  I think for versions 1.4.4>  attributes can not be set so the global_step and current_epoch lines fail, but for your environment set-up this method should work.


```
    trainer = pl.Trainer.from_argparse_args(**hparams ) 

    trainer.global_step = checkpoint['global_step']
    trainer.current_epoch = checkpoint['epoch']

   # restore the optimizers

    optimizer_states = checkpoint['optimizer_states']
    for optimizer, opt_state in zip(trainer.optimizers, optimizer_states):
      optimizer.load_state_dict(opt_state)

      # move optimizer to GPU 1 weight at a time
      # avoids OOM
      if trainer.root_gpu is not None:
          for state in optimizer.state.values():
              for k, v in state.items():
                  if isinstance(v, torch.Tensor):
                      state[k] = v.cuda(trainer.root_gpu)
    
    # restore the lr schedulers
    lr_schedulers = checkpoint['lr_schedulers']
    for scheduler, lrs_state in zip(trainer.lr_schedulers, lr_schedulers):
      scheduler['scheduler'].load_state_dict(lrs_state)

    del checkpoint
    torch.cuda.empty_cache()
```

**Comment by Akanni96** [comment]
The above does  not work. I have found that to restore you have to place the optimizer restoration code in configure_optimizers() function
