### ISSUE TITLE
Update "register_backward_hook" to "register_full_backward_hook" to stop warnings on Pytorch 1.8

### ISSUE THREAD

**Issue by vturrisi** [PyTorchLightning/pytorch-lightning#7334]
In Pytorch 1.8, register_backward_hook was replaced by register_full_backward_hook ([https://github.com/pytorch/pytorch/pull/46163](https://github.com/pytorch/pytorch/pull/46163)).

When a model returns more than one tensor that requires gradients, the following warning is raised:
```
full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input.
Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "
```

**Comment by awaelchli** [comment]
Hi

Where in Lightning did you see us use `register_backward_hook`?

**Comment by vturrisi** [comment]
I think this is actually related to pytorch and not pytorch lightning. [#pytorch/issues/57157](https://github.com/pytorch/pytorch/issues/57157).
