### ISSUE TITLE
Batch Size Tuner is unable to free memory after OOM

### ISSUE THREAD

**Issue by half-potato** [PyTorchLightning/pytorch-lightning#7335]
## 🐛 Bug

When using the batch size tuner, torch.cuda.empty_cache() does not free the memory that pytorch tried to allocated before going OOM. This results in the batch size tuner leaving the device memory full.

Unfortunately, I have limited time and the Boring model would require too much work to replicate the bug with.

### Environment

* CUDA:
	- GPU:
		- GeForce GTX 1060 6GB
	- available:         True
	- version:           10.2
* Packages:
	- numpy:             1.19.2
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.1
	- pytorch-lightning: 1.2.8
	- tqdm:              4.55.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         
	- python:            3.8.6
	- version:           #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020

 - PyTorch Version (e.g., 1.0): Also does not work with 1.7.1

**Comment by Borda** [comment]
@half-potato mind check our RC from yesterday? `pip install pytorch-lightning==1.3.0rc0`

**Comment by half-potato** [comment]
Version: pytorch-lightning==1.3.2
Sure, it doesn't fail to allocate memory anymore, but it also doesn't actually tune the batch size. It doesn't ever run 
```
trainer.reset_train_dataloader(model)
```
As a result, it never runs OOM. Putting this line back into ```_adjust_batch_size``` results in the same problem, where the memory isn't freed.

I found this issue on pytorch: https://github.com/pytorch/pytorch/issues/18853

It appears that it could be a driver issue.
