### ISSUE TITLE
Trainer.predict seems to ignore model.predict_step

### ISSUE THREAD

**Issue by Emrys-Merlin** [PyTorchLightning/pytorch-lightning#7347]
## 🐛 Bug

`trainer.predict` invokes `model.forward` even though `model.predict_step` is defined.

I am not sure if this might be related to https://github.com/PyTorchLightning/pytorch-lightning/issues/6129.

## Please reproduce using the BoringModel

https://colab.research.google.com/drive/1gH19OYVAdaH96_BPy4nVhB6AhfctqMG1?usp=sharing

### To Reproduce

I have implemented the behavior in the [**BoringModel**](https://colab.research.google.com/drive/1gH19OYVAdaH96_BPy4nVhB6AhfctqMG1?usp=sharing). The central methods are the following:
```
class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def predict_step(self, batch, batch_idx):
        return torch.zeros_like(self.layer(batch))
```
I used the following test:

```
def test_x(tmpdir):
    # init model
    model = BoringModel()

    # Initialize a trainer
    trainer = pl.Trainer(
        max_epochs=1, 
        progress_bar_refresh_rate=20
    )

    result = trainer.predict(model, test)
    result = result[0]
    np.testing.assert_almost_equal(np.abs(result).mean(), 0.0)
```

which produces:
 ```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-26-1f9f6fbe4f6c> in <module>()
----> 1 test_x(tmpdir)

1 frames
/usr/local/lib/python3.7/dist-packages/numpy/testing/_private/utils.py in assert_almost_equal(actual, desired, decimal, err_msg, verbose)
    593         pass
    594     if abs(desired - actual) >= 1.5 * 10.0**(-decimal):
--> 595         raise AssertionError(_build_err_msg())
    596 
    597 

AssertionError: 
Arrays are not almost equal to 7 decimals
 ACTUAL: 0.41472945
 DESIRED: 0.0
```

### Expected behavior

The assertion should pass. I expected `trainer.predict` to invoke `model.predict_step` and hence (in this minimal example) return only 0s.

### Environment

* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.1+cu101
	- pytorch-lightning: 1.2.10
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.10
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020
	- 
### Additional context

None

**Comment by justusschock** [comment]
Hi @Emrys-Merlin ,

I tried to reproduce it with the following script (pretty similar to what you posted):

```python
import os
import torch
from torch.utils.data import Dataset, DataLoader
from pytorch_lightning import LightningModule, Trainer
from torch.nn import functional as F
from torchmetrics.classification import Accuracy
import pytorch_lightning as pl
import numpy as np


class RandomDataset(Dataset):

    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index], 1

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def predict_step(self, batch, batch_idx, dataloader_idx):
        return torch.zeros_like(self.layer(batch[0]))


def run():
    # init model
    model = BoringModel()

    # Initialize a trainer
    trainer = pl.Trainer(
        max_epochs=1, 
        progress_bar_refresh_rate=20
    )

    test = DataLoader(RandomDataset(32, 100))

    result = trainer.predict(model, test)
    result = result[0]
    np.testing.assert_almost_equal(np.abs(result).mean(), 0.0)


if __name__ == '__main__':
    run()

```

But with lightning 1.3.0rc2 I could not reproduce this. Can you try to upgrade to master and see if the issue persists?

**Comment by Emrys-Merlin** [comment]
Thank you for the super fast reply :slightly_smiling_face: 

I have adapted the colab notebook and installed the master branch of pytorch-lightning: https://colab.research.google.com/drive/1gH19OYVAdaH96_BPy4nVhB6AhfctqMG1?usp=sharing

Sadly, the problem persists for me:
```bash
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-39-1f9f6fbe4f6c> in <module>()
----> 1 test_x(tmpdir)

1 frames
/usr/local/lib/python3.7/dist-packages/numpy/testing/_private/utils.py in assert_almost_equal(actual, desired, decimal, err_msg, verbose)
    593         pass
    594     if abs(desired - actual) >= 1.5 * 10.0**(-decimal):
--> 595         raise AssertionError(_build_err_msg())
    596 
    597 

AssertionError: 
Arrays are not almost equal to 7 decimals
 ACTUAL: 0.5589807
 DESIRED: 0.0
```

The environment now reads:
```bash


* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.1+cu101
	- pytorch-lightning: 1.3.0rc2
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.10
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020
```

**Comment by justusschock** [comment]
Hi again @Emrys-Merlin 

Thanks for the follow up, however this time I exactly ran your notebook (a copy of it in my own drive) and for me everything worked just fine. Have you tried to restart your colab runtime/purge it completely?

**Comment by Emrys-Merlin** [comment]
Hi @justusschock,

It seems that I have not. Sorry for that! I have restarted the kernel and reran everything. Now the test runs through.

Thank you for your help and your patience :slightly_smiling_face:  I will upgrade my local installation.

Best wishes
