### ISSUE TITLE
LightningCLI: Support config files on object stores

### ISSUE THREAD

**Issue by leezu** [PyTorchLightning/pytorch-lightning#7360]
## 🚀 Feature

In addition to `python trainer.py --config config.yaml`, LightningCLI should enable `python trainer.py --config s3://bucket/config.yaml` 

### Motivation

pytorch-lightning has good support for remote filesystems thanks to #2164 #3320 (and possibly others). Thanks to that, it's straightforward to deploy lightning-based scripts to compute cluster environments without having to write extra code preparing / post-processing the local file-systems https://pytorch-lightning.readthedocs.io/en/latest/clouds/cluster.html It would be nice to extend this to LightningCLI.

When using LightningCLI however, it's currently necessary to deploy the config.yaml file to each node, instead of referencing a copy in an object store such as S3.

cc @mauvilsa?

**Comment by mauvilsa** [comment]
@leezu I think this is a good idea, will look into it.

**Comment by edgarriba** [comment]
@leezu @mauvilsa thanks for bringing this up. Please, let us know if you need any support with the CLI integration /cc @carmocca

**Comment by mauvilsa** [comment]
Had a quick look at this and I have the following thoughts/doubts:

- The idea would be to use fsspec, which means this should be implemented in such a way that any protocol registered in fsspec in principle could work.
- The fsspec filesystems might require additional settings, e.g.  `key`, `secret`, `token`, etc. for [s3fs](https://s3fs.readthedocs.io/en/latest/api.html#s3fs.core.S3FileSystem). Having just `s3://bucket/config.yaml` is not enough in common use cases. How would these additional settings be specified?
- I see that fsspec is a requirement of lightning. But in the tests I only see simple http loading, e.g. [load_from_checkpoint](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/tests/trainer/test_trainer.py#L82-L89), nothing more complex like s3 or non-url based additional options.

**Comment by carmocca** [comment]
> The idea would be to use fsspec

Do you think this should be done here or in upstream jsonargparse?

> How would these additional settings be specified?

I guess environment variables are the best option here

> nothing more complex like s3 or non-url based additional options.

Not sure if it's worth us to have those tests instead of just trusting upstream fsspec

**Comment by leezu** [comment]
> > The fsspec filesystems might require additional settings, e.g. key, secret, token, etc. for s3fs. Having just s3://bucket/config.yaml is not enough in common use cases. How would these additional settings be specified?

> I guess environment variables are the best option here

There are a number of options, including environment variables. If you're for example on an AWS EC2 instance, these credentials would be automatically retrieved by fsspec (assuming your instance is configured to have access to the bucket in question). So if the EC2 instance is configured correctly, fsspec will "just work". See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials

**Comment by mauvilsa** [comment]
> > The idea would be to use fsspec
> 
> Do you think this should be done here or in upstream jsonargparse?

jsonargparse already supports http/https for the config, though requires optional packages and be explicitly enabled. The fsspec support should be added extending that. Here what we can do is enable fsspec by default, since it can be assumed that fsspec is installed.

> > nothing more complex like s3 or non-url based additional options.
> 
> Not sure if it's worth for us to have those tests instead of just trusting upstream fsspec

I am interested in looking at code and tests using fsspec. What I was able to find in lightning is not enough to know how to best do this. I have not used fsspec. It looks very powerful but the documentation seems to lack a bit.

> > > The fsspec filesystems might require additional settings, e.g. key, secret, token, etc. for s3fs. Having just s3://bucket/config.yaml is not enough in common use cases. How would these additional settings be specified?
> 
> > I guess environment variables are the best option here
> 
> Manually setting environment variables is possible, but may not be the so convenient :) If your code is running within an AWS network (eg. EC2), the credentials can be automatically retrieved (assuming your instance is configured to have access to the bucket in question) and fsspec will "just work". See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials

That is nice. Though I think the scope of this shouldn't be to make it work only for s3 on aws. If someone wants to use this in some private cluster which uses a minio server as storage, would fsspec "just work"? Or what if someone wants to use some other file system supported by fsspec? How would users know how to do this or that this is possible? The documentation in lightning and in fsspec is not enough. Or maybe I missed where these things are explained better.

@leezu when you say "environment variables is possible" do you mean that we could implement it like this, or fsspec already supports environment variables? Even if we initially implement it so that it works only for s3 on aws it would be good to have an idea how it can be extended without needing completely change the original implementation.

**Comment by leezu** [comment]
> when you say "environment variables is possible" do you mean that we could implement it like this, or fsspec already supports environment variables? Even if we initially implement it so that it works only for s3 on aws it would be good to have an idea how it can be extended without needing completely change the original implementation.

fsspec just calls the AWS SDK for Python. Above example just serves as documentation to understand what the SDK would do in the background. Sorry if it was confusing. The takeaway is that you don't need to worry about authentication in jsonargparse/pytorch-lightning and that each of the fsspec backends has their own ways (via environment variables or other features) to ensure authentication is taken care of.

**Comment by leezu** [comment]
Thank you @mauvilsa. It works great!

**Comment by edenlightning** [comment]
Closing this issue, feel free to reopen if there's anything to be done on the lightning front.

**Comment by leezu** [comment]
@edenlightning it'd be helpful for lightning to call

```
from jsonargparse import set_config_read_mode
set_config_read_mode(fsspec_enabled=True)
```

as lightning already depends on fsspec

**Comment by carmocca** [comment]
@leezu Want to open a PR with it?

**Comment by mauvilsa** [comment]
There isn't yet a jsonargparse release with the fsspec support. When this gets released I can create the PR.
