### ISSUE TITLE
Join Our Slack link doesn't work

### ISSUE THREAD

**Issue by NakedKoala** [PyTorchLightning/pytorch-lightning#7366]
## 📚 Documentation

Trying to join the slack group but the link (on repo README ) doesn't work

**Comment by tchaton** [comment]
@edenlightning

**Comment by kaushikb11** [comment]
@NakedKoala What's the Error for you?
Does this link https://join.slack.com/t/pytorch-lightning/shared_invite/zt-pw5v393p-qRaDgEk24~EjiZNBpSQFgQ work for you?
