### ISSUE TITLE
Doc broken / Link broken

### ISSUE THREAD

**Issue by jeremycochoy** [PyTorchLightning/pytorch-lightning#738]
* The readme link "Lightning module" is broken: https://pytorch-lightning.readthedocs.io/en/latest/LightningModule/RequiredTrainerInterface/
  * The source link in documentation goes nowhere: https://pytorch-lightning.readthedocs.io/en/latest/logging.html click on source goes to https://github.com/PyTorchLightning/PyTorch-Lightning/blob/pytorch_lightning/logging.py

It is really confusing and worrying for news comer like me who expect a simple and easy to plug api well documented and maintained.

**Comment by Borda** [comment]
Have you noticed some other broken links?

**Comment by neggert** [comment]
We just migrated to a new documentation stack, so there are some kinks to work out. Please continue to let us know if you find broken links.

**Comment by jeremycochoy** [comment]
Thanks for your quick answer.

I am rewriting part of existing code with lightning because I ended up with a similar API (obviously with a restricted set of lightning features) and I think that overall some standardisation of this code everybody always rewrite can be great. So I am mostly going back and forth through the documentation to find the equivalent features.

I find out that "Define a lightning module" and "Fit with a trainer" also seems to be pointing to the previous documentation.

**Comment by Borda** [comment]
just for the record, I think that the links got broken due to major docs update in #725

**Comment by sudarshan85** [comment]
Here are few more broken links that I found:

Tutorials:

- [START A RESEARCH PROJECT](https://pytorch-lightning.readthedocs.io/en/latest/tutorials.html#start-a-research-project)
- [9 KEY LIGHTNING TRICKS](https://pytorch-lightning.readthedocs.io/en/latest/tutorials.html#key-lightning-tricks)

None of the examples have any details in them.

**Comment by Borda** [comment]
@sudarshan85 do they have text the source code?

**Comment by ChristofHenkel** [comment]
broken links are also referenced in https://pypi.org/project/pytorch-lightning/0.2.5/

**Comment by Borda** [comment]
@ChristofHenkel it is a really old version and me what I say it was not even to possible to build the particular docs anymore... the only thing we can do now is kind of forwarding from https://williamfalcon.github.io/pytorch-lightning/ to the new (organisation) location...
any other idea @PyTorchLightning/core-contributors ?

**Comment by jeremycochoy** [comment]
I will also add that one link from the Medium article on "refactoring pytorch code with lightning" is broken:
> Lightning __tests__ it and [...]

I understand you just moved a lot of content from one domain to an other, so it makes take some times before we catch all the inconsistencies.

Hope it can helps you, and keep the good work. :)

**Comment by Borda** [comment]
talking about the medium links, @williamFalcon could you pls check it?

**Comment by jeremycochoy** [comment]
Also the blue/red gif picture which describe which part lightning handle is broken (alongside the logo at the top) on the pipy repository: https://pypi.org/project/pytorch-lightning/0.6.0/

Don't know if it is something expected or not. 🙃

**Comment by sh0416** [comment]
Is there anyone find the replacement for walliamfalcon.github.io? I think most of the use case for pytorch-lightning is inside that page, and the absence of that page makes me struggle implementing my project. Please help me. Also, pytorchlightning.github.io doesn't work neither.

**Comment by williamFalcon** [comment]
read the 0.5.3 docs on the readme. 
Which pages did we not bring over?

**Comment by sh0416** [comment]
@williamFalcon Oh.. my mistake. `pytorchlightning.github.io` gives 404, not the full link. Thanks for reply.

**Comment by jeremycochoy** [comment]
Actually, maybe http://pytorchlightning.github.io should have an index page? 🤣

**Comment by sh0416** [comment]
@jeremycochoy https://pytorchlightning.github.io/pytorch-lightning/ is the index page, not https://pytorchlightning.github.io/

**Comment by Borda** [comment]
I ll have look at it...

**Comment by Ir1d** [comment]
@Borda You can consider creating a new repo named `pytorchlightning.github.io`, and pushing the built docs into their with the help of CI

**Comment by jeremycochoy** [comment]
@Ir1d Oh, I didn't noticed you do not have a pytorchlightning.github.io repository. Actually I do not understand how you managed to host the actual documentation. 😅 

Also, maybe want to update the top right icon in the doc to display the PyTorchLightning team repo:
![image](https://user-images.githubusercontent.com/4193259/74017986-cca0ba00-499d-11ea-9a48-bc666b8570b5.png)

Although I do recognize that williamFalcon's work is amazing. 😄

**Comment by Borda** [comment]
the structure is different <user>.github.io/<repo> so @williamFalcon is admin to do so...

**Comment by Borda** [comment]
> @Ir1d Oh, I didn't noticed you do not have a pytorchlightning.github.io repository. Actually I do not understand how you managed to host the actual documentation. 

we are using ReadTheDocs or RTFD (~read the fucking docs) as before...

> Also, maybe want to update the top right icon in the doc to display the PyTorchLightning team repo:

where do you find this page?

**Comment by jeremycochoy** [comment]
@Borda I meant for hosting the documentation at https://pytorchlightning.github.io/pytorch-lightning/ without having a `pytorchlightning.github.io`.

I fond this github link (https://github.com/PyTorchLightning/pytorch-lightning/issues/738#issuecomment-583309344) at the url: https://pytorchlightning.github.io/pytorch-lightning/

Now I realise maybe this is an outdated doc and shouldn't be here, since as you mentionned the readme link to *read the docs*.

**Comment by Ir1d** [comment]
I think @jeremycochoy  is mislead by the unused gh-pages branch. Perhaps we should add a link to the new doc from there. (Since it is still crawled by the search engines, many others might still be misled too.

**Comment by jeremycochoy** [comment]
I think a redirect from `https://pytorchlightning.github.io/pytorch-lightning/` and an other one from `https://pytorchlightning.github.io/` to your RTFD would fix issues of peoples like me and @sh0416 being lost. It would also tell the search engines (like google) to update their links.

Ideally you would like to do a HTTP 301. Although it is the best, I don't think you can archives this with gh-pages but some HTML can do the job. This is [how Jekyll do HTML redirects](https://github.com/jekyll/jekyll-redirect-from/blob/master/lib/jekyll-redirect-from/redirect.html) if it can helps you.

**Comment by Borda** [comment]
> @Borda I meant for hosting the documentation at https://pytorchlightning.github.io/pytorch-lightning/ without having a `pytorchlightning.github.io`.

I agree that we shall drop the old MKdoc documentation, @williamFalcon 

> I think a redirect from https://pytorchlightning.github.io/pytorch-lightning/ and an other one from https://pytorchlightning.github.io/ to your RTFD would fix issues of peoples like me and @sh0416 being lost. It would also tell the search engines (like google) to update their links.

I totally agree, we have talked about it earlier, but it is about Will to do as he is the only admin
