### ISSUE TITLE
Incompatible torch and torchvision version numbers in requirements file

### ISSUE THREAD

**Issue by HarshSharma12** [PyTorchLightning/pytorch-lightning#739]
## 🐛 Bug

requirements.txt lists torch and torchvision requirements as follows 
```
torch>=1.1
torchvision>=0.4.0
```
which leads to pip installing torchvision 0.4.2 and torch 1.4.0. These are incompatible with each other. Running pip -r requirements.txt throws the following error 

> ERROR: torchvision 0.4.2 has requirement torch==1.3.1, but you'll have torch 1.4.0 which is incompatible.

### To Reproduce

1. Go to lightning root directory
2. Run 'pip -r requirements.txt'

### Expected behavior
Pip should be able to install all requirements successfully.

### Environment
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce RTX 2080 SUPER
Nvidia driver version: 430.64
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] pytorch-lightning==0.6.0
[pip] torch==1.3.1
[pip] torchfile==0.1.0
[pip] torchvision==0.4.2
[conda] pytorch-lightning         0.6.0                     dev_0    <develop>
[conda] torch                     1.3.1                    pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchvision               0.4.2                    pypi_0    pypi

**Comment by Borda** [comment]
I am not sure if we are able to set specific combinations of `toch` and `torchvision`, do you have any suggestion? @williamFalcon @neggert we still need to dig to `torchvision==0.5` #694

**Comment by jerpint** [comment]
I'm having a similar error show up from pip when upgrading torchvision==0.5.0 and pytorch==1.4.0:

```
ERROR: pytorch-lightning 0.6.0 has requirement torchvision<0.5,>=0.4.0, but you'll have torchvision 0.5.0 which is incompatible.
```
I feel like I can probably safely ignore this?

**Comment by popcornell** [comment]
Reproduced this error too on my side.

**Comment by Borda** [comment]
We are dropping `torchvision` from dependences... #797
