### ISSUE TITLE
MilestonesFinetuning in examples is missing super().__init()

### ISSUE THREAD

**Issue by FlorianMF** [PyTorchLightning/pytorch-lightning#7397]
## 🐛 Bug

The `MilestonesFinetune`callback in the pl_examples/domain_templates/computer_vision_fine_tuning.py is missing a init call of `BaseFinetune` via super().__init() [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/c3fc0313efe748533baaac1d1240dec9ef88fb1e/pl_examples/domain_templates/computer_vision_fine_tuning.py#L72).

The script will then fail, because when the _store() method of `BaseFinetune` is called the object does not have the `_internal_state` attribute

### Environment
I installed lightning just before directly from the repo (version  1.3.0rc2)

**Comment by Borda** [comment]
@FlorianMF nice, thx! are you interested in sending quick fix?

**Comment by FlorianMF** [comment]
Et voilà
