### ISSUE TITLE
Confusion between steps and batches

### ISSUE THREAD

**Issue by jeanm** [PyTorchLightning/pytorch-lightning#7407]
Looking at `TrainLoop`,  it would appear that the global step takes into account `accumulate_grad_batches`:
https://github.com/PyTorchLightning/pytorch-lightning/blob/6104a6316afb8cdd9825d77844db456ffa766ca1/pytorch_lightning/trainer/training_loop.py#L884-L892

However, the documentation for the trainer makes it sound like steps and batches are equivalent:
https://github.com/PyTorchLightning/pytorch-lightning/blob/6104a6316afb8cdd9825d77844db456ffa766ca1/pytorch_lightning/trainer/trainer.py#L286-L287

1. Should the difference between steps and batches be clarified somewhere? Perhaps calling steps "optimizer steps" or "param updates" would help avoid any misunderstandings.
2. Additionally, when reporting metrics via e.g. tensorboard, would it not be better to have the _x_ axis show batches rather than steps? This would allow easy comparison between runs with different world sizes and different values of `accumulate_grad_batches`.

**Comment by ananthsub** [comment]
@carmocca @awaelchli this is tightly related to #7406 i think
