### ISSUE TITLE
Callback causing deadlock in multiple GPU case with horovod accelerator

### ISSUE THREAD

**Issue by irasit** [PyTorchLightning/pytorch-lightning#7410]
## 🐛 Bug

Testing the multi gpu training with horovod. The training works perfectly in normal case. But if a callback is added, the training job will go into a dead lock,
```
Thu May  6 00:46:46 2021[1,0]<stderr>:[2021-05-06 00:46:46.239927: W /Users/pengz/github/horovod/horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
Thu May  6 00:46:46 2021[1,0]<stderr>:Missing ranks:
Thu May  6 00:46:46 2021[1,0]<stderr>:0: [broadcast.bool.sz]
```
This error seems similar to what @awaelchli found when testing an old issue [here](https://github.com/PyTorchLightning/pytorch-lightning/pull/5155#discussion_r549761269), but I can not find where this bool is coming from. 

Is there any flag that I can enable to get more logs for it?

## Please reproduce using the BoringModel

Not able to reproduce it with colab, it works fine for cpu or single gpu cases with horovod.
It can be reproduced by adding callback in this test example in horovod. https://github.com/horovod/horovod/blob/master/examples/spark/pytorch/pytorch_lightning_spark_mnist.py

### To Reproduce

Use following [**BoringModel**](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing) and post here

### Expected behavior

Not have deadlock.

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

* `IDE`: Please, use our python [bug_report_model.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
) template.

* `Colab Notebook`: Please copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py) (or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

 - PyTorch Version (e.g., 1.0): 1.2.9
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by irasit** [comment]
Found a work around to make lightning trainer compatible with petastorm data loader. This issue can be closed.

**Comment by awaelchli** [comment]
Hey! Great to hear that. Anything that we can do to improve compatibility with Lightning?

**Comment by discort** [comment]
@irasit 
I am getting exactly the same issue. Could you please share the cause of the deadlock and your workaround?

**Comment by Data-drone** [comment]
@discort did you manage to find a fix?
