### ISSUE TITLE
Pure pytorch train faster than pytorch-lightning ?

### ISSUE THREAD

**Issue by suyanzhou626** [PyTorchLightning/pytorch-lightning#7417]
## 🐛 Bug

I warped my pure pytorch training code to pytorch-lightning in semantic segmentation tasks.
I found the training speed is slower than pure pytorch.
I have two dataset, one has 705 images, training one epoch needs about 125s, however it needs about 170s in pl setting,
another dataset has 7776 images, all setting is the same as to above, training one epoch is about 21min in pure pytorch, and it's
about 32 min in pytorch-lightning.
Is that normal?

I saw another issue [a toy example ](https://github.com/PyTorchLightning/pytorch-lightning/issues/6196)
I also reproduce the same problem.

### Environment
pytorch version: 1.7
os: ubuntu 16.04
cuda: 11.0
cudnn: 8.05
pytorch-lightning: 1.3.0

**Comment by ananthsub** [comment]
Could you share your training code in pure pytorch alongside your Lightning code for us to debug?
