### ISSUE TITLE
implement freeze/unfreeze scheme for multi-optimizer case

### ISSUE THREAD

**Issue by CarloLucibello** [PyTorchLightning/pytorch-lightning#742]
This is issue is just to make sure that we remember to implement the suggestion https://github.com/PyTorchLightning/pytorch-lightning/pull/603#discussion_r358482942 at some point

**Comment by williamFalcon** [comment]
@CarloLucibello good catch. I thought we fixed it? @jeffling

**Comment by jeffling** [comment]
https://github.com/PyTorchLightning/pytorch-lightning/pull/603#issuecomment-575025755

Was the last movement on this front. Someone else may have to take it on

**Comment by CarloLucibello** [comment]
I'm sorry I won't have time in the near future to tackle this

**Comment by Borda** [comment]
anyone one interested @awaelchli @jeremyjordan
cc: @PyTorchLightning/core-contributors

**Comment by Borda** [comment]
@CarloLucibello any update here? 🐰

**Comment by CarloLucibello** [comment]
sorry, I have no buffer right now

**Comment by awaelchli** [comment]
This issue can maybe even be closed. With the new manual optimization, we should be able to deal with multiple optimizers in whatever crazy way we want.
https://pytorch-lightning.readthedocs.io/en/stable/optimizers.html#manual-optimization
