### ISSUE TITLE
Allow calling fit multiple times with Quantization (QAT)

### ISSUE THREAD

**Issue by t-vi** [PyTorchLightning/pytorch-lightning#7427]
## 🐛 Bug

When using the QuantizationAwareTraining() callback, one cannot call Trainer.fit twice.

### To Reproduce

Call Trainer.fit twice on any model gives an exception (which is pretty qpaque, I might add)

### Expected behavior

Resumes training

### Additional context

I imagine here is a tradeoff between two goals:
1. Have fit return a model that's ready for inference,
2. don't catapult yourself irreversibly out of the option to continue training.

With Quantization Aware Training's conversion step at the end (moving from fake quantization for QAT to quantized layers), we have to choose one. Currently, the QAT hook converts, so it has 1 but not 2.

To my mind, the conversion step is "preparing for export / inference" rather than part of training, so I would suggest to drop it from the fitting part.

**Comment by t-vi** [comment]
To avoid the confusion, calling fit twice means something like
```python
dm = BoringDataModule()
model = BoringModel()
t = pl.Trainer()
trainer = pl.Trainer(gpus=1, max_epochs=1, check_val_every_n_epoch=1, callbacks=[QuantizationAwareTraining()])
trainer.fit(model, datamodule=dm)
trainer.fit(model, datamodule=dm)
```

**Comment by edenlightning** [comment]
@Borda mind taking a look?

**Comment by Borda** [comment]
@t-vi how about adding an extra argument to the callback which would skip this quantization in `on_fit_end` and in such case user needs to call it separately and anytime he/she wants...

**Comment by t-vi** [comment]
So there are two practically irreversible transitions: Model -> QAT-Model -> Quantized model.
Yes, it would make sense to have something to skip the second one and offer it as an extra step. It's really a bit sad that you cannot unquantize a model, but it seems that the PyTorch quantization didn't really appreciate the philosophy of PyTorch as much as I would have wished.

**Comment by Borda** [comment]
> it seems that the PyTorch quantization didn't really appreciate the philosophy of PyTorch as much as I would have wished.

kind of way around could be replacing the quantized modules with the initial ones and will value from the quantized ones...
what do you think, does it worse to make this kind of reverse engineering?

**Comment by t-vi** [comment]
I think this reversal could be made (you'd have the rounding errors, but hey), but the problem of doing it outside PyTorch that I see is operator coverage.

**Comment by Borda** [comment]
> the problem of doing it outside PyTorch that I see is operator coverage

what do you mean by operator coverage?

**Comment by t-vi** [comment]
I mean that if there are quantized operators we don't handle (correctly) then we can't unquantize the model. I'd have to think a bit about how much of a problem I'd expect it to be, it might be not as bad as I thought it was. (Maybe I just wrote too much about operator coverage in those quantization tutorials... :slightly_smiling_face:  ).
