### ISSUE TITLE
Error complaining optimizer_idx is not there when it is

### ISSUE THREAD

**Issue by surya-narayanan** [PyTorchLightning/pytorch-lightning#7442]
### To Reproduce

 [**BoringModel**](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing) and post [here](https://colab.research.google.com/drive/1n4nzaLu4z08V9lMyYttBKqHZhrL82ntZ?usp=sharing)

### Expected behavior

Should just recognize optimizer index and also not throw an error if a condition forces different numbers of optimizers

### Environment

* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.1+cu101
	- pytorch-lightning: 1.3.0
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.10
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

**Comment by vballoli** [comment]
If the default argument `optimizer_idx` is set to `None`, you can re-write the training step either expecting an idx or None and accordingly use the optimizers. ```python
import torch
from pytorch_lightning import LightningModule
from torch.utils.data import Dataset

class BoringModel(LightningModule):
    @property
    def automatic_optimization(self) -> bool:
        return False

    def __init__(self):
        super().__init__()
        self.layer1 = torch.nn.Linear(32, 32)
        self.layer2 = torch.nn.Linear(32, 32)
        self.layer3 = torch.nn.Linear(32, 2)
        self.train_l1 = True

    def forward(self, x):
      out = self.layer1(x)
      out = self.layer2(out)

      return self.layer3(out)

    def loss(self, batch, prediction):
        # An arbitrary loss to have a loss that updates the model weights during `Trainer.fit` calls
        return torch.nn.functional.mse_loss(prediction, torch.ones_like(prediction))

    def training_step(self, batch, batch_idx, optimizer_idx=None):
                
        output = self(batch)        
        loss = self.loss(batch, output)
        if optimizer_idx is None:
          opt1 = self.optimizers()
          self.manual_backward(loss, opt1)
          opt1.step()
        else:
          opt2, opt3 = self.optimizers()
          self.manual_backward(loss, opt2, retain_graph=True)
          opt2.step()
          self.manual_backward(loss, opt3)
          opt3.step()
        
        return {"loss": loss}

    def training_step_end(self, training_step_outputs):
        return training_step_outputs

    def training_epoch_end(self, outputs) -> None:
        torch.stack([x["loss"] for x in outputs]).mean()

    def validation_step(self, batch, batch_idx):
        output = self(batch)
        loss = self.loss(batch, output)
        return {"x": loss}

    def validation_epoch_end(self, outputs) -> None:
        torch.stack([x['x'] for x in outputs]).mean()

    def test_step(self, batch, batch_idx):
        output = self(batch)
        loss = self.loss(batch, output)
        self.log('fake_test_acc', loss)
        return {"y": loss}

    def test_epoch_end(self, outputs) -> None:
        torch.stack([x["y"] for x in outputs]).mean()

    def configure_optimizers(self):
      if self.train_l1:
        opt1 = torch.optim.SGD(self.layer1.parameters(), lr=0.1)
        opt2 = torch.optim.SGD(self.layer1.parameters(), lr=0.1)
        return opt1
      else:
        opt2 = torch.optim.SGD(self.layer1.parameters(), lr=0.1)
        opt3 = torch.optim.SGD(self.layer1.parameters(), lr=0.1)
        return [opt2, opt3]

        
```

**Comment by surya-narayanan** [comment]
This works. I'm not sure why, or what the optimizer_idx does, since I don't use it anywhere and from what I [read](https://github.com/PyTorchLightning/pytorch-lightning/discussions/5780), it's largely useless for manual optimization (See OPs comment Dec 17 2020)

**Comment by vballoli** [comment]
`optimizer_idx` is only passed if there are multiple optimizers, so I think by assigning it a default `None`, it'll either remain `None` or will be the actual indices.

**Comment by thak123** [comment]
So optimizer_idx alternates between 0 and 1 for a training step?  What is the use case of alternating the optimizers?
