### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by hao-nan-liu** [PyTorchLightning/pytorch-lightning#7443]
## 🐛 Bug

Attribute Error Cannot set attribute

## Please reproduce using the BoringModel

https://colab.research.google.com/drive/1SuA3Qt-ZNPPU9EuztSTgNrGUPtdkSTpv#scrollTo=29jTHbeMiGL3

### To Reproduce

Use following [**BoringModel**](https://colab.research.google.com/drive/1SuA3Qt-ZNPPU9EuztSTgNrGUPtdkSTpv#scrollTo=29jTHbeMiGL3)

### Expected behavior

Expected to set hparam at least in version 1.2.3

### Environment

 - PyTorch Version (e.g., 1.3.0):

**Comment by vballoli** [comment]
I believe this is arising because the `hparams` property doesn't have a [setter](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/core/lightning.py#L1884-L1887).  A temporary solution would be 
```
self._hparams = {}
```
Imo the only solution is to add `@hparams.setter` like below?
```python
@hparams.setter
def hparams(self, hparams: Union[AttributeDict, dict]) -> None:
    self._hparams = AttributeDict(hparams)
```
I can send a PR if this is the solution.

**Comment by edgarriba** [comment]
@vballoli we already have a private `_set_params`. A solution could be to make that public as you mentions as a setter /cc @Borda @williamFalcon

**Comment by juliette-sch** [comment]
Hello, I'm compiling a code based on RoBERTa for the detection of emotions. The code had no errors last week but since this morning I have the error: "can't set attribute" that I can not solve.

`
class TrainingModule(pl.LightningModule):
    def __init__(self, hparams):
        super().__init__()
        self.model = EmoModel(AutoModelWithLMHead.from_pretrained("distilroberta-base").base_model, len(emotions))
        self.loss = nn.CrossEntropyLoss() ## combines LogSoftmax() and NLLLoss()
        self.hparams = hparams

        @hparams.setter
        def hparams(self, hparams: Union[AttributeDict, dict]) -> None:
          self._hparams = AttributeDict(hparams)  

    def step(self, batch, step_name="train"):
        X, y = batch
        loss = self.loss(self.forward(X), y)
        loss_key = f"{step_name}_loss"
        tensorboard_logs = {loss_key: loss}

        return { ("loss" if step_name == "train" else loss_key): loss, 'log': tensorboard_logs,
               "progress_bar": {loss_key: loss}}

    def forward(self, X, *args):
        return self.model(X, *args)

    def training_step(self, batch, batch_idx):
        return self.step(batch, "train")
    
    def validation_step(self, batch, batch_idx):
        return self.step(batch, "val")

    def validation_end(self, outputs: List[dict]):
        loss = torch.stack([x["val_loss"] for x in outputs]).mean()
        return {"val_loss": loss}
        
    def test_step(self, batch, batch_idx):
        return self.step(batch, "test")
    
    def train_dataloader(self):
        return self.create_data_loader(self.hparams.train_path, shuffle=True)

    def val_dataloader(self):
        return self.create_data_loader(self.hparams.val_path)

    def test_dataloader(self):
        return self.create_data_loader(self.hparams.test_path)
                
    def create_data_loader(self, ds_path: str, shuffle=False):
        return DataLoader(
                    EmoDataset(ds_path),
                    batch_size=self.hparams.batch_size,
                    shuffle=shuffle,
                    collate_fn=TokenizersCollateFn()
        )
  

    @lru_cache()
    def total_steps(self):
        return len(self.train_dataloader()) // self.hparams.accumulate_grad_batches * self.hparams.epochs

    def configure_optimizers(self):
        ## use AdamW optimizer -- faster approach to training NNs
        ## read: https://www.fast.ai/2018/07/02/adam-weight-decay/
        optimizer = AdamW(self.model.parameters(), lr=self.hparams.lr)
        lr_scheduler = get_linear_schedule_with_warmup(
                    optimizer,
                    num_warmup_steps=self.hparams.warmup_steps,
                    num_training_steps=self.total_steps(),
        )
        return [optimizer], [{"scheduler": lr_scheduler, "interval": "step"}]`

And when I use this class, I have the error 'can't set attribute': 

`lr=0.1 ## uper bound LR
from torch_lr_finder import LRFinder
hparams_tmp = Namespace(
    train_path=train_path,
    val_path=val_path,
    test_path=test_path,
    batch_size=16,
    warmup_steps=100,
    epochs=1,
    lr=lr,
    accumulate_grad_batches=1,
)
module = TrainingModule(hparams_tmp)`

thank you for your help.

**Comment by juliette-sch** [comment]
Hello, I'm compiling a code based on RoBERTa for the detection of emotions. The code had no errors last week but since this morning I have the error: "can't set attribute" that I can not solve.

`## Methods required by PyTorchLightning

class TrainingModule(pl.LightningModule):
    def __init__(self, hparams):
        super().__init__()
        self.model = EmoModel(AutoModelWithLMHead.from_pretrained("distilroberta-base").base_model, len(emotions))
        self.loss = nn.CrossEntropyLoss() ## combines LogSoftmax() and NLLLoss()
        self.hparams = hparams

        @hparams.setter
        def hparams(self, hparams: Union[AttributeDict, dict]) -> None:
          self._hparams = AttributeDict(hparams)  

    def step(self, batch, step_name="train"):
        X, y = batch
        loss = self.loss(self.forward(X), y)
        loss_key = f"{step_name}_loss"
        tensorboard_logs = {loss_key: loss}

        return { ("loss" if step_name == "train" else loss_key): loss, 'log': tensorboard_logs,
               "progress_bar": {loss_key: loss}}

    def forward(self, X, *args):
        return self.model(X, *args)

    def training_step(self, batch, batch_idx):
        return self.step(batch, "train")
    
    def validation_step(self, batch, batch_idx):
        return self.step(batch, "val")

    def validation_end(self, outputs: List[dict]):
        loss = torch.stack([x["val_loss"] for x in outputs]).mean()
        return {"val_loss": loss}
        
    def test_step(self, batch, batch_idx):
        return self.step(batch, "test")
    
    def train_dataloader(self):
        return self.create_data_loader(self.hparams.train_path, shuffle=True)

    def val_dataloader(self):
        return self.create_data_loader(self.hparams.val_path)

    def test_dataloader(self):
        return self.create_data_loader(self.hparams.test_path)
                
    def create_data_loader(self, ds_path: str, shuffle=False):
        return DataLoader(
                    EmoDataset(ds_path),
                    batch_size=self.hparams.batch_size,
                    shuffle=shuffle,
                    collate_fn=TokenizersCollateFn()
        )
  

    @lru_cache()
    def total_steps(self):
        return len(self.train_dataloader()) // self.hparams.accumulate_grad_batches * self.hparams.epochs

    def configure_optimizers(self):
        ## use AdamW optimizer -- faster approach to training NNs
        ## read: https://www.fast.ai/2018/07/02/adam-weight-decay/
        optimizer = AdamW(self.model.parameters(), lr=self.hparams.lr)
        lr_scheduler = get_linear_schedule_with_warmup(
                    optimizer,
                    num_warmup_steps=self.hparams.warmup_steps,
                    num_training_steps=self.total_steps(),
        )
        return [optimizer], [{"scheduler": lr_scheduler, "interval": "step"}]`

And it's when I used this function that I have the error : "can't set attribute" : 

`lr=0.1 ## uper bound LR
from torch_lr_finder import LRFinder
hparams_tmp = Namespace(
    train_path=train_path,
    val_path=val_path,
    test_path=test_path,
    batch_size=16,
    warmup_steps=100,
    epochs=1,
    lr=lr,
    accumulate_grad_batches=1,
)`

`module = TrainingModule(hparams_tmp)`

Thank you for your help.

**Comment by juliette-sch** [comment]
Hello, I'm compiling a code based on RoBERTa for the detection of emotions. The code had no errors last week but since this morning I have the error: "can't set attribute" that I can not solve.

`class TrainingModule(pl.LightningModule):
    def __init__(self, hparams):
        super().__init__()
        self.model = EmoModel(AutoModelWithLMHead.from_pretrained("distilroberta-base").base_model, len(emotions))
        self.loss = nn.CrossEntropyLoss() ## combines LogSoftmax() and NLLLoss()
        self.hparams = hparams

    def step(self, batch, step_name="train"):
        X, y = batch
        loss = self.loss(self.forward(X), y)
        loss_key = f"{step_name}_loss"
        tensorboard_logs = {loss_key: loss}

        return { ("loss" if step_name == "train" else loss_key): loss, 'log': tensorboard_logs,
               "progress_bar": {loss_key: loss}}

    def forward(self, X, *args):
        return self.model(X, *args)

    def training_step(self, batch, batch_idx):
        return self.step(batch, "train")
    
    def validation_step(self, batch, batch_idx):
        return self.step(batch, "val")

    def validation_end(self, outputs: List[dict]):
        loss = torch.stack([x["val_loss"] for x in outputs]).mean()
        return {"val_loss": loss}
        
    def test_step(self, batch, batch_idx):
        return self.step(batch, "test")
    
    def train_dataloader(self):
        return self.create_data_loader(self.hparams.train_path, shuffle=True)

    def val_dataloader(self):
        return self.create_data_loader(self.hparams.val_path)

    def test_dataloader(self):
        return self.create_data_loader(self.hparams.test_path)
                
    def create_data_loader(self, ds_path: str, shuffle=False):
        return DataLoader(
                    EmoDataset(ds_path),
                    batch_size=self.hparams.batch_size,
                    shuffle=shuffle,
                    collate_fn=TokenizersCollateFn()
        )
  

    @lru_cache()
    def total_steps(self):
        return len(self.train_dataloader()) // self.hparams.accumulate_grad_batches * self.hparams.epochs

    def configure_optimizers(self):
        ## use AdamW optimizer -- faster approach to training NNs
        ## read: https://www.fast.ai/2018/07/02/adam-weight-decay/
        optimizer = AdamW(self.model.parameters(), lr=self.hparams.lr)
        lr_scheduler = get_linear_schedule_with_warmup(
                    optimizer,
                    num_warmup_steps=self.hparams.warmup_steps,
                    num_training_steps=self.total_steps(),
        )
        return [optimizer], [{"scheduler": lr_scheduler, "interval": "step"}]`
And it's when I used this function that I have the error : "can't set attribute" :

lr=0.1 ## uper bound LR from torch_lr_finder import LRFinder hparams_tmp = Namespace( train_path=train_path, val_path=val_path, test_path=test_path, batch_size=16, warmup_steps=100, epochs=1, lr=lr, accumulate_grad_batches=1, )

module = TrainingModule(hparams_tmp)

Thank you for your help.

**Comment by ananthsub** [comment]
The setter for `hparams` was removed in v1.3. For saving hyperparameters, use `save_hyperparameters` https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_module.html#save-hyperparameters

**Comment by juliette-sch** [comment]
> The setter for `hparams` was removed in v1.3. For saving hyperparameters, use `save_hyperparameters` https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_module.html#save-hyperparameters

It works, thank you very much !

**Comment by celsofranssa** [comment]
> The setter for `hparams` was removed in v1.3. For saving hyperparameters, use `save_hyperparameters` https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_module.html#save-hyperparameters

However `self.hparams=hparams` doesn't make things easier?
