### ISSUE TITLE
Docs build error in Sphinx 4.0.0

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning#7455]
## 🐛 Bug
I locally confirmed that building docs (`cd docs; make html`) fails due to:
```
Extension error (sphinx_paramlinks.sphinx_paramlinks):
Handler <function build_index at 0x7f20c201c820> for event 'doctree-read' threw an exception (exception: __new__() missing 1 required positional argument: 'aliased')
make: *** [Makefile:19: html] Error 2
Traceback (most recent call last):
  File "/entrypoint.py", line 22, in <module>
    action.build_all_docs(github_env, [os.environ.get("INPUT_DOCS-FOLDER")])
  File "/sphinx_action/action.py", line 167, in build_all_docs
    raise RuntimeError("Build failed")
RuntimeError: Build failed
```
and also confirmed that `pip install Sphinx<4.0.0` fixes the error.

### To Reproduce
https://github.com/PyTorchLightning/pytorch-lightning/pull/7452/checks?check_run_id=2538915517

### Expected behavior
`make html` should successfully build the docs.

**Comment by astrojuanlu** [comment]
I didn't see a corresponding issue upstream, so I opened one https://github.com/sqlalchemyorg/sphinx-paramlinks/issues/9
