### ISSUE TITLE
Error: torch_xla/csrc/convert_ops.cpp:83 : Unsupported XLA type 10 when running TPU training

### ISSUE THREAD

**Issue by NakedKoala** [PyTorchLightning/pytorch-lightning#7471]
## 🐛 Bug

```
File "/root/anaconda3/envs/my-rdkit-env/lib/python3.7/site-packages/torch_xla/distributed/parallel_loader.py", line 46, in next
    xm.mark_step()
  File "/root/anaconda3/envs/my-rdkit-env/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 718, in mark_step
    wait=xu.getenv_as('XLA_SYNC_WAIT', bool, False))
RuntimeError: Error while lowering: f32[24,3,7,7]{0,1,3,2} xla::cast, type=f32, dtype=Float, stype=Half
Error: torch_xla/csrc/convert_ops.cpp:83 : Unsupported XLA type 10
Python Frames:

```
When running TPU training, encountered above error message , same code works for GPU training. 

### To Reproduce

Please run this colab notebook, 

https://colab.research.google.com/drive/1IlhXRWP84c3mXgjJMsypmhIC-4sSsDQf?usp=sharing

### Expected behavior

Should be able to run TPU training

**Comment by kaushikb11** [comment]
@NakedKoala Could you share more of the stack trace?

**Comment by shz1236** [comment]
@kaushikb11 I have the same error and the stack traces are list below:
`Exception in device=TPU:7: Error while lowering: f32[24,20,14]{2,1,0} aten::adaptive_max_pool3d_backward, location=forward@transformer.py:295
Error: torch_xla/csrc/convert_ops.cpp:83 : Unsupported XLA type 10
Python Frames:
  forward (/usr/local/lib/python3.7/dist-packages/torch/nn/modules/transformer.py:295)
  _call_impl (/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py:889)
  forward (/usr/local/lib/python3.7/dist-packages/torch/nn/modules/transformer.py:181)
  _call_impl (/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py:889)
  forward (<ipython-input-16-3d7ca3cd975e>:29)
  _call_impl (/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py:889)
  forward (<ipython-input-17-57cc895de685>:8)
  _call_impl (/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py:889)
  validation_step (<ipython-input-17-57cc895de685>:21)
  forward (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/overrides/base.py:57)
  _call_impl (/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py:889)
  validation_step (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/plugins/training_type/tpu_spawn.py:272)
  validation_step (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/accelerators/accelerator.py:226)
  evaluation_step (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/evaluation_loop.py:174)
  run_evaluation (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:962)
  run_sanity_check (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:1107)
  run_train (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:842)
  run_stage (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:807)
  new_process (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/plugins/training_type/tpu_spawn.py:163)
  _start_fn (/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py:323)
  _mp_start_fn (/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py:329)
  _wrap (/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py:59)
  run (/usr/lib/python3.7/multiprocessing/process.py:99)
  _bootstrap (/usr/lib/python3.7/multiprocessing/process.py:297)
  _launch (/usr/lib/python3.7/multiprocessing/popen_fork.py:74)
  __init__ (/usr/lib/python3.7/multiprocessing/popen_fork.py:20)
  _Popen (/usr/lib/python3.7/multiprocessing/context.py:277)
  start (/usr/lib/python3.7/multiprocessing/process.py:112)
  start_processes (/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py:179)
  spawn (/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py:394)
  start_training (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/plugins/training_type/tpu_spawn.py:259)
  start_training (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/accelerators/accelerator.py:96)
  dispatch (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:797)
  _run (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:756)
  fit (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:458)
  <module> (<ipython-input-19-a1b6cc2ee375>:1)
  run_code (/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882)
  run_ast_nodes (/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2828)
  run_cell (/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718)
  run_cell (/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py:537)
  do_execute (/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py:208)
  execute_request (/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py:399)
  dispatch_shell (/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py:233)
  dispatcher (/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py:283)
  null_wrapper (/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py:300)
  _run_callback (/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py:434)
  _handle_recv (/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py:480)
  _handle_events (/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py:451)
  <lambda> (/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py:535)
  null_wrapper (/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py:300)
  _run_callback (/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py:758)
  _run (/usr/lib/python3.7/asyncio/events.py:88)
  _run_once (/usr/lib/python3.7/asyncio/base_events.py:1786)
  run_forever (/usr/lib/python3.7/asyncio/base_events.py:541)
  start (/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py:132)
  start (/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py:499)
  launch_instance (/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py:845)
  <module> (/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16)
  _run_code (/usr/lib/python3.7/runpy.py:85)
  _run_module_as_main (/usr/lib/python3.7/runpy.py:193)`

**Comment by shz1236** [comment]
`Exception in device=TPU:7: Error while lowering: f32[24,20,14]{2,1,0} aten::adaptive_max_pool3d_backward, location=forward@transformer.py:295
Error: torch_xla/csrc/convert_ops.cpp:83 : Unsupported XLA type 10
Python Frames:
  forward (/usr/local/lib/python3.7/dist-packages/torch/nn/modules/transformer.py:295)
  _call_impl (/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py:889)
  forward (/usr/local/lib/python3.7/dist-packages/torch/nn/modules/transformer.py:181)
  _call_impl (/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py:889)
  forward (<ipython-input-16-3d7ca3cd975e>:29)
  _call_impl (/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py:889)
  forward (<ipython-input-17-57cc895de685>:8)
  _call_impl (/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py:889)
  validation_step (<ipython-input-17-57cc895de685>:21)
  forward (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/overrides/base.py:57)
  _call_impl (/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py:889)
  validation_step (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/plugins/training_type/tpu_spawn.py:272)
  validation_step (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/accelerators/accelerator.py:226)
  evaluation_step (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/evaluation_loop.py:174)
  run_evaluation (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:962)
  run_sanity_check (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:1107)
  run_train (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:842)
  run_stage (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:807)
  new_process (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/plugins/training_type/tpu_spawn.py:163)
  _start_fn (/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py:323)
  _mp_start_fn (/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py:329)
  _wrap (/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py:59)
  run (/usr/lib/python3.7/multiprocessing/process.py:99)
  _bootstrap (/usr/lib/python3.7/multiprocessing/process.py:297)
  _launch (/usr/lib/python3.7/multiprocessing/popen_fork.py:74)
  __init__ (/usr/lib/python3.7/multiprocessing/popen_fork.py:20)
  _Popen (/usr/lib/python3.7/multiprocessing/context.py:277)
  start (/usr/lib/python3.7/multiprocessing/process.py:112)
  start_processes (/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py:179)
  spawn (/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py:394)
  start_training (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/plugins/training_type/tpu_spawn.py:259)
  start_training (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/accelerators/accelerator.py:96)
  dispatch (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:797)
  _run (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:756)
  fit (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:458)
  <module> (<ipython-input-19-a1b6cc2ee375>:1)
  run_code (/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882)
  run_ast_nodes (/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2828)
  run_cell (/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718)
  run_cell (/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py:537)
  do_execute (/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py:208)
  execute_request (/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py:399)
  dispatch_shell (/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py:233)
  dispatcher (/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py:283)
  null_wrapper (/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py:300)
  _run_callback (/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py:434)
  _handle_recv (/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py:480)
  _handle_events (/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py:451)
  <lambda> (/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py:535)
  null_wrapper (/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py:300)
  _run_callback (/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py:758)
  _run (/usr/lib/python3.7/asyncio/events.py:88)
  _run_once (/usr/lib/python3.7/asyncio/base_events.py:1786)
  run_forever (/usr/lib/python3.7/asyncio/base_events.py:541)
  start (/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py:132)
  start (/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py:499)
  launch_instance (/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py:845)
  <module> (/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16)
  _run_code (/usr/lib/python3.7/runpy.py:85)
  _run_module_as_main (/usr/lib/python3.7/runpy.py:193)`

**Comment by shz1236** [comment]
@kaushikb11 I have the same error. It works for GPU training and the stack traces are list below:
```
Exception in device=TPU:7: Error while lowering: f32[24,20,14]{2,1,0} aten::adaptive_max_pool3d_backward, location=forward@transformer.py:295
Error: torch_xla/csrc/convert_ops.cpp:83 : Unsupported XLA type 10
Python Frames:
  forward (/usr/local/lib/python3.7/dist-packages/torch/nn/modules/transformer.py:295)
  _call_impl (/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py:889)
  forward (/usr/local/lib/python3.7/dist-packages/torch/nn/modules/transformer.py:181)
  _call_impl (/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py:889)
  forward (<ipython-input-16-3d7ca3cd975e>:29)
  _call_impl (/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py:889)
  forward (<ipython-input-17-57cc895de685>:8)
  _call_impl (/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py:889)
  validation_step (<ipython-input-17-57cc895de685>:21)
  forward (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/overrides/base.py:57)
  _call_impl (/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py:889)
  validation_step (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/plugins/training_type/tpu_spawn.py:272)
  validation_step (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/accelerators/accelerator.py:226)
  evaluation_step (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/evaluation_loop.py:174)
  run_evaluation (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:962)
  run_sanity_check (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:1107)
  run_train (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:842)
  run_stage (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:807)
  new_process (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/plugins/training_type/tpu_spawn.py:163)
  _start_fn (/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py:323)
  _mp_start_fn (/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py:329)
  _wrap (/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py:59)
  run (/usr/lib/python3.7/multiprocessing/process.py:99)
  _bootstrap (/usr/lib/python3.7/multiprocessing/process.py:297)
  _launch (/usr/lib/python3.7/multiprocessing/popen_fork.py:74)
  __init__ (/usr/lib/python3.7/multiprocessing/popen_fork.py:20)
  _Popen (/usr/lib/python3.7/multiprocessing/context.py:277)
  start (/usr/lib/python3.7/multiprocessing/process.py:112)
  start_processes (/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py:179)
  spawn (/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py:394)
  start_training (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/plugins/training_type/tpu_spawn.py:259)
  start_training (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/accelerators/accelerator.py:96)
  dispatch (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:797)
  _run (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:756)
  fit (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:458)
  <module> (<ipython-input-19-a1b6cc2ee375>:1)
  run_code (/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882)
  run_ast_nodes (/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2828)
  run_cell (/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718)
  run_cell (/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py:537)
  do_execute (/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py:208)
  execute_request (/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py:399)
  dispatch_shell (/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py:233)
  dispatcher (/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py:283)
  null_wrapper (/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py:300)
  _run_callback (/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py:434)
  _handle_recv (/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py:480)
  _handle_events (/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py:451)
  <lambda> (/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py:535)
  null_wrapper (/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py:300)
  _run_callback (/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py:758)
  _run (/usr/lib/python3.7/asyncio/events.py:88)
  _run_once (/usr/lib/python3.7/asyncio/base_events.py:1786)
  run_forever (/usr/lib/python3.7/asyncio/base_events.py:541)
  start (/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py:132)
  start (/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py:499)
  launch_instance (/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py:845)
  <module> (/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16)
  _run_code (/usr/lib/python3.7/runpy.py:85)
  _run_module_as_main (/usr/lib/python3.7/runpy.py:193)
```

**Comment by kaushikb11** [comment]
I would suggest opening this issue on the PyTorch XLA repo. As it is an OPs Lowering issue, a discussion could be opened on supporting this particular operation.
