### ISSUE TITLE
[Bug] Trainer.validate() incorrect return-type (same for test()) 

### ISSUE THREAD

**Issue by breznak** [PyTorchLightning/pytorch-lightning#7486]
## 🐛 Bug

- [ ] FIXME 1: with `model.validation_epoch_end = None` the `validate()` does not return `[validation_step()s]`
- [ ] FIXME 2: with `assert model.validation_epoch_end is not None` validate() does not return `{}`, but `[{}]`, where `len([]) == 1` (depends on num dataloaders??)
  - [ ] mention in doc that the len of returned `[{}]` depends on number of dataloaders?
- [x] TODO shouldn't doc on return-type for `test()` and `validate()` be similar/same? https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html#test 

## Please reproduce using the BoringModel

```python
import os
import torch
from torch.utils.data import DataLoader, Dataset
from pytorch_lightning import LightningModule, Trainer

class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)
    def __getitem__(self, index):
        return self.data[index]
    def __len__(self):
        return self.len

class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)
    def forward(self, x):
        return self.layer(x)
    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}
    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)
        return {'valid_loss': loss, 'other': 42}
    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)
    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)

def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    test_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=5,
        limit_val_batches=3,
        num_sanity_val_steps=0,
        max_epochs=1,
        weights_summary=None,
    )
    # pl.Trainer.validate() -> return-type?
    # > Returns
    #     The dictionary with final validation results returned by validation_epoch_end. If validation_epoch_end is not defined, the output is a list of the dictionaries returned by validation_step.
    # from: https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html?highlight=validate#validate
    #       ... and https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_module.html?highlight=validation_epoch_end#validation-epoch-end 
    
    #FIXME 1: with `model.validation_epoch_end = None` validate() does not return [validation_step()s]
    #FIXME 2: with `assert model.validation_epoch_end is not None` validate() does not return {}, but [{}], where len([]) == 1 (depends on num dataloaders??)
    #TODO shouldn't doc on return-type for test() and validate() be similar/same? https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html#test 
    
    
    # case 1
    # un/comment as needed - disable hooks mentioned in validate() & test() doc to change behavior of return-type
    # model.on_validation_epoch_end = None
    # model.validation_epoch_end = None
    # model.on_train_epoch_end = None
    # model.training_epoch_end = None
    # model.on_test_epoch_end = None
    # model.test_epoch_end = None
    
    # case 2
    trainer.fit(model, train_dataloader=train_data, val_dataloaders=val_data)
    val = trainer.validate(model, val_dataloaders=val_data)
    tst = trainer.test(model, test_dataloaders=test_data)

if __name__ == '__main__':
    run()
```

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !
PL1.3 from PyPI

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

### Additional context

Discussed on slack: https://pytorch-lightning.slack.com/archives/CRBLFHY79/p1620748519201000

**Comment by breznak** [comment]
> mention in doc that the len of returned [{}] depends on number of dataloaders? 

also, while this would be true for a single-input single-output model, it wouldn't have to be the case in general, right? 
I would say it should depend on the number of "heads" of the model? (not sure how to express that in PL code). Say we can have 
- a model with multiple-inputs (dataloaders/datasets?) with a "merge" layer and a single output head (`len(validation_result)==1`)
- a (single input) model with multiple output heads , `len(validation_result) == N`

**Comment by Borda** [comment]
@breznak are you interested in sending PR with a fix?

**Comment by breznak** [comment]
> interested in sending PR with a fix? 

@Borda sure, I'll try! 

I'll need some advice on the FIXMEs 1,2 - whether we update the doc to match the current code (easy way), or the API/doc is correct but the code does not do as intended?

**Comment by Borda** [comment]
@breznak sorry for the late reply, yes I think it depends on the dataloader, so you can simply type as Union of these cases
