### ISSUE TITLE
[DeepSpeedPlugin] Trainer.track_grad_norm support

### ISSUE THREAD

**Issue by leezu** [PyTorchLightning/pytorch-lightning#7490]
## 🚀 Feature
Trainer.track_grad_norm is currently silently ignored when using DeepSpeedPlugin stage 2.

### Motivation

Trainer.track_grad_norm works well with ddp_sharded. It would be nice to support in DeepSpeedPlugin too, given DeepSpeedPlugin's empirical better scaling efficiency.

### Alternatives

Use ddp_sharded to when track_grad_norm is needed. Add an error message when using track_grad_norm with DeepSpeedPlugin.

**Comment by edgarriba** [comment]
@kaushikb11 @SeanNaren any insights on this ?

**Comment by tchaton** [comment]
Hey @leezu,

That's a good question. As DeepSpeed is sharding the gradients, I think there won't be a simple solution unless they expose a way to do so.
Mind opening a feature request on DeepSpeed repo ?

Best,
T.C
