### ISSUE TITLE
`ddp_cpu` cannot run in interactive mode

### ISSUE THREAD

**Issue by alanhdu** [PyTorchLightning/pytorch-lightning#7491]
## 🐛 Bug

In the new 1.3 release, I get an error when trying to use `ddp_cpu`:
```python
In [1]: import pytorch_lightning as pl
In [2]: pl.Trainer(num_processes=2, accelerator="ddp_cpu")
...
~/workspace/pytorch-lightning/pytorch_lightning/trainer/connectors/accelerator_connector.py in check_interactive_compatibility(self)
    570         if _IS_INTERACTIVE and self._distrib_type is not None and not self._distrib_type.is_interactive_compatible():
    571             raise MisconfigurationException(
--> 572                 f"Selected distributed backend {self._distrib_type} is not compatible with an interactive"
    573                 " environment. Run your code as a script, or choose one of the compatible backends:"
    574                 f" {', '.join(DistributedType.interactive_compatible_types())}"

MisconfigurationException: Selected distributed backend ddp is not compatible with an interactive environment. Run your code as a script, or choose one of the compatible backends: dp, ddp_spawn, ddp_sharded_spawn
```

This used to work fine on Lightning 1.2.9

I *believe* the problem is at:

https://github.com/PyTorchLightning/pytorch-lightning/blob/b9a52fa2ef31f12f6992ece18a033318ec551907/pytorch_lightning/trainer/connectors/accelerator_connector.py#L521-L522

this says that the accelerator is DDP (which is rightly incompatible with interactive use), but I *think* that `ddp_cpu` is actually using `ddp_spawn`? At least, it was in Lightning 1.2.

Either this is erroneous and `ddp_cpu` is still using `ddp_spawn`, or IMO we should update the changelog to point out the breaking change (and hopefully have docs on how to use `cpu + ddp_spawn` for testing purposes).

**Comment by alanhdu** [comment]
I bisected this back to ebabe56f4ebde2813e1d77039ec7cb64bba63ee2 -- I guess that the `_distrib_type` was erroneously set to `DDP` this entire time but it never surfaced until we added this check?

**Comment by carmocca** [comment]
cc @justusschock @awaelchli

**Comment by awaelchli** [comment]
Hi
"ddp_cpu" was always using spawn, even if the name does not contain the word "spawn" like the gpu version does. 
Can you explain what you mean by "interactive mode"?

**Comment by alanhdu** [comment]
In that case, I think https://github.com/PyTorchLightning/pytorch-lightning/pull/7492 should be the right fix here.
