### ISSUE TITLE
Too slow TPU Training

### ISSUE THREAD

**Issue by sooftware** [PyTorchLightning/pytorch-lightning#7497]
## 🐛 Bug

Hi! Thank you for great project. I love pytorch-lightning.  
I tried to train with TPU using pytorch-lightning. I success training with TPU but, TPU training is too slow.  
I think there is something wrong. Here is the code that I set trainer.

```python
trainer = pl.Trainer(tpu_cores=8,
                     accelerator="dp",
                     precision=16,
                     accumulate_grad_batches=4,
                     check_val_every_n_epoch=1,
                     gradient_clip_val=5.0,
                     logger=logger,
                     auto_scale_batch_size=True,
                     plugins=TPUSpawnPlugin(),
                     max_epochs=20)
```
  
Please let me know if I set anything wrong.  
Overall code is [here](https://github.com/sooftware/lightning-asr/blob/main/bin/main.py)
  
 - PyTorch Version (e.g., 1.7.1):
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): I use google cloud platform's `pytorch-1-7-xla` image.
 - Build command you used (if compiling from source): Check [here1](https://github.com/sooftware/lightning-asr/blob/main/setup.py), [here2](https://github.com/sooftware/lightning-asr/blob/main/setup.sh)
 - Python version: 3.7.10
 - CUDA/cuDNN version: None
 - GPU models and configuration: None (GCP TPU)
 - Any other relevant information: Google Cloud Platform

**Comment by machineko** [comment]
Pytorch is known to have a lot worst XLA compilation then TF/Jax and i think they are still working on it.
You probably should post it in XLA/Pytorch repo https://github.com/pytorch/xla

**Comment by kaushikb11** [comment]
@sooftware Could you pass `TPUSpawnPlugin(debug=True)` to the plugins flag in Trainer? It will log if your code has any operations causing bottlenecks during the XLA compilation.

**Comment by sooftware** [comment]
Thank you. I will try.
