### ISSUE TITLE
Control Saving/Restoring Checkpoint From Training Type Plugin 

### ISSUE THREAD

**Issue by shuyingsunshine21** [PyTorchLightning/pytorch-lightning#7523]
### Motivation

Currently, we have `CheckpointConnector` to deal with logics of restoring/saving checkpoint, but it is highly dependent on training type plugin, especially when we will save/restore sharded states. It might be clearer for training type plugin/accelerator to directly handle these.

Another thing which might worth consolidating is one unified interface for restore. For saving checkpoint, we have clear one `save_checkpoint(self, filepath, weights_only: bool = False) `, however for restoring, we have 

* `checkpoint_connector.restore_weights()` (https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L82) when training providing `resume_from_checkpoint`
*  `training_type_plugin.restore_model_state_from_ckpt_path` (https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/trainer.py#L1152) when test/validation provide `ckpt_path`)

(The former depends on the latter, and for the latter, feel bit counter-intuitive for `restore_model_state_from_ckpt_path` to return checkpoint state though model has already been loaded and whether to load optimizer states)

the main difference is just whether we just restore model states. We could do similarly as 
```
def save_checkpoint(self, filepath, weights_only: bool = False)
```
for restoring
```
def restore_checkpoint(self, filepath, weights_only: bool = False)
```

### Pitch

Transfer ownership of load/restore to purely training type plugin (or accelerator), and unify `restore_checkpoint` interface.

### Alternatives

Remain current implementation.

**Comment by edgarriba** [comment]
@shuyingsunshine21 would you be open to send a PR with yoour proposal ?

**Comment by shuyingsunshine21** [comment]
sure, bring this up for brainstorming and need to think a bit more on this!
