### ISSUE TITLE
Docker: manifest for pytorchlightning/pytorch_lightning:latest not found

### ISSUE THREAD

**Issue by robert-s-lee** [PyTorchLightning/pytorch-lightning#7531]
## 🐛 Bug

Following [Docker hub instruction](https://hub.docker.com/r/pytorchlightning/pytorch_lightning)  below using the `latest` results in `Docker: manifest for pytorchlightning/pytorch_lightning:latest not found`

```
docker pull pytorchlightning/pytorch_lightning
```

Specifying [`tag`](https://hub.docker.com/r/pytorchlightning/pytorch_lightning/tags?page=1&ordering=last_updated) does work.
  
```
% docker pull pytorchlightning/pytorch_lightning:base-conda-py3.8-torch1.8
base-conda-py3.8-torch1.8: Pulling from pytorchlightning/pytorch_lightning
```

## Please reproduce using the BoringModel

N/A

### To Reproduce

```
 % docker pull pytorchlightning/pytorch_lightning
Using default tag: latest
Error response from daemon: manifest for pytorchlightning/pytorch_lightning:latest not found: manifest unknown: manifest unknown
```
### Expected behavior

Pull the `latest`

### Environment

 - OS - MacBook Pro on OSX 10.15.7

**Comment by Borda** [comment]
it is interesting, we do not have such a tag in docker hub and Docker does not alow another tag as default
https://hub.docker.com/repository/docker/pytorchlightning/pytorch_lightning/tags?page=1&ordering=last_updated&name=latest
