### ISSUE TITLE
UninitializedParameter

### ISSUE THREAD

**Issue by kingjr** [PyTorchLightning/pytorch-lightning#7546]
## 🚀 Feature
Detect UninitializedParameter and run one batch/sample before fitting.

### Motivation
Pytorch now accepts 'lazy' layers with `UninitializedParameter`. 

However, this seems to cause a memory error in PL at when we start the trainer because it attempt to estimate the memory usage:
```
RuntimeError: Can't access the shape of an uninitialized parameter. This error usually happens in `load_state_dict` when trying to load an uninitialized parameter into an initialized one. Call `forward` to initialize the parameters before accessing their attributes.
```

### Pitch
Currently I am solving this issue by manually calling the data / system before fitting the trainer:

```python
data.setup()
batch = next(iter(data.train_dataloader()))
system.train()
system.forward(batch)
trainer.fit(system, data)
```

I think this may be also fixable with a Hook, but I think there must be a cleaner solution.

**Comment by awaelchli** [comment]
I believe this is because we have this strange way of computing the "model size": 
https://github.com/PyTorchLightning/pytorch-lightning/blob/233f252bb427c930be8e7ca56fe115b637278b8d/pytorch_lightning/core/memory.py#L235

We probably have to filter the parameters there based on the type.

**Comment by kingjr** [comment]
> Are you interested in sending a PR?

I'm new to PL, so that would probably be unreasonable, sorry :/

**Comment by awaelchli** [comment]
no pressure! totally fine

**Comment by vatch123** [comment]
> I believe this is because we have this strange way of computing the "model size":
> https://github.com/PyTorchLightning/pytorch-lightning/blob/233f252bb427c930be8e7ca56fe115b637278b8d/pytorch_lightning/core/memory.py#L235
> 
> We probably have to filter the parameters there based on the type.
> Are you interested in sending a PR?

Hi @awaelchli I am also new to PL but I am hoping to contribute. Can I pick this up?

**Comment by awaelchli** [comment]
Would be great! The help is very much appreciated!

**Comment by vatch123** [comment]
Thanks. How are we planning to approach this? I mean should we just set the lazy layer parameters to zero or something? I have also written a very basic test that captures this should I begin a pull request?

**Comment by edgarriba** [comment]
@vatch123 yes, please send that PR :)

**Comment by tchaton** [comment]
Hey @kingjr,

Would you mind providing the full trace and a reproducible example with the BoringModel ?


I am getting a slightly different error, so I think there might be 2 issues with this new UninitializedParameter.

```
import torch
from torch.nn.parameter import UninitializedParameter

class Model(torch.nn.Module):

    def __init__(self):
        super().__init__()
        self.model = UninitializedParameter()

model = Model()
print([p.numel() for p in model.parameters()])
*** ValueError: Attempted to use an uninitialized parameter in <method 'numel' of 'torch._C._TensorBase' objects>. This error happens when you are using a `LazyModule` or explicitly manipulating `torch.nn.parameter.UninitializedParameter` objects. When using LazyModules Call `forward` with a dummy batch to initialize the parameters before calling torch functions
```

Best,
T.C

**Comment by tchaton** [comment]
Hey @vatch123,


By using `print([0 if isinstance(p, UninitializedParameter) else p.numel()  for p in model.parameters()])` there: https://github.com/PyTorchLightning/pytorch-lightning/blob/233f252bb427c930be8e7ca56fe115b637278b8d/pytorch_lightning/core/memory.py#L226, we should have a hacky fix for now.

@awaelchli Should we move summary after the first batch call, as parameters are actually generated properly ?

Best,
T.C

**Comment by vatch123** [comment]
Hey @tchaton,
Thanks for the help. But I guess the `trainable_parameters` property will also break this. I guess we need to look for a different solution or there would be multiple positions where we would need to apply this hack.
https://github.com/PyTorchLightning/pytorch-lightning/blob/233f252bb427c930be8e7ca56fe115b637278b8d/pytorch_lightning/core/memory.py#L226-L232

**Comment by vatch123** [comment]
The uninitalized parameter is a new feature in torch. The older version of torch running in CI fails to recognize uninitialized variables. How to get around that if anyone has any ideas?

**Comment by ananthsub** [comment]
@awaelchli @tchaton instead of running it after the first batch, what if we:
- Removed model summary from the core trainer and made it a callback
- Ran the callback on train end of the beginning to ensure all the initialization is correct

IMO we should strive to make the model summarization an independent component which we can re-integrate with the training framework. It's not far from that, except this could take an `nn.Module` instead of a `LightningModule`: https://github.com/PyTorchLightning/pytorch-lightning/blob/04dcb1786d0ea41dfdb1e73493b214169e365c6c/pytorch_lightning/core/memory.py#L185-L192
