### ISSUE TITLE
trainer.test() doesn't work with GPU + SWA options

### ISSUE THREAD

**Issue by priancho** [PyTorchLightning/pytorch-lightning#7555]
## 🐛 Bug

I tried to use SWA when training my model and faced the following error (reproduced with the Boring model).
It seems like `trainer.test()` doesn't work with the SWAed model on GPU.

In addition, it works if you train it with CPU and SWA.

```bash
...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-43-6b9ff008e36d> in <module>()
     27 trainer.fit(model, train, val)
     28 
---> 29 trainer.test(test_dataloaders=test)
...
...
...
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in <lambda>(module)
   1283         
   1284         gen = self._named_members(
-> 1285             lambda module: module._parameters.items(),
   1286             prefix=prefix, recurse=recurse)
   1287         for elem in gen:

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
    946                 return modules[name]
    947         raise AttributeError("'{}' object has no attribute '{}'".format(
--> 948             type(self).__name__, name))
    949 
    950     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

AttributeError: 'BoringModel' object has no attribute '_parameters'
```

### To Reproduce

Use following [**BoringModel**](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing) and post here

I have reproduced the reported bug with the Boring model below:
- https://colab.research.google.com/drive/1e4oytv98kyhex7pRs1TkPKSZkcvrKvlW?usp=sharing

### Expected behavior

It must runs test without any problem

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

* `IDE`: Please, use our python [bug_report_model.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
) template.

* `Colab Notebook`: Please copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py) (or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.1+cu101
	- pytorch-lightning: 1.3.1
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.10
	- version:           #1 SMP Tue Apr 20 19:55:43 PDT 2021

**Comment by ananthsub** [comment]
This looks similar to https://github.com/PyTorchLightning/pytorch-lightning/issues/7505 . I'm closing this issue out in order to consolidate the discussion in one place. Let's follow up on #7505
