### ISSUE TITLE
transfer_distrib_spawn_state_on_fit_end in tpu_spawn.py regex path wildcard use can cause opaque error.

### ISSUE THREAD

**Issue by Natithan** [PyTorchLightning/pytorch-lightning#7559]
## 🐛 Bug

This function: [https://github.com/PyTorchLightning/pytorch-lightning/blob/e126649d19e85c449b007008361f10374878f2f4/pytorch_lightning/plugins/training_type/tpu_spawn.py#L183](url)
is intended to create a file based on another file ending with .ckpt.
However, the "." in re.sub matches any character (not just a dot).
Concretely, in my case, my checkpoint save path was called ".../model_ckpts". This led to this re.sub creating the string ".../model.tmp_end.ckpt", which is a directory that is not found, and leads to the error Exception in device=TPU:0: [Errno 2] No such file or directory: '.../model.tmp_end.ckpts/epoch=11-step=23-v1.tmp_end.ckpt'

### Expected behavior

It should not matter how I name my checkpoint directory (more specifically: I should be able to use 'ckpt' as part of the folder name.
That or there should be a warning raised against doing so.

The cause of the issue seems pretty clear, so not making a collab reproduction.

**Comment by Borda** [comment]
@kaushikb11 mind have look? :]
