### ISSUE TITLE
trainer.fit doesn't work in 1.3.1 version!

### ISSUE THREAD

**Issue by shamanez** [PyTorchLightning/pytorch-lightning#7561]
## 🐛 Bug

The trainer.fit(model) gives the following error. 

![image](https://user-images.githubusercontent.com/16892570/118369662-548d5f00-b5f8-11eb-92c6-456f05958d72.png)

The error further says:

**Comment by ananthsub** [comment]
Could you share the full stack trace along with the code used that led to the exception?

**Comment by shamanez** [comment]
sure. I tried to train the Huggingface model using the following lightning base script.

https://github.com/huggingface/transformers/blob/master/examples/research_projects/seq2seq-distillation/lightning_base.py#L379

**Comment by shamanez** [comment]
Here is my exact code, 

This work perfectly with 1.2.10!

https://github.com/shamanez/transformers/blob/rag-retriever-end2end/examples/research_projects/rag-end2end-retriever/lightning_base.py

**Comment by ananthsub** [comment]
Could you share the full exception info too?

**Comment by ananthsub** [comment]
@shamanez in your lightning module, you're overriding `setup` incorrectly. Use `stage` as the argument name instead of `mode`

**Comment by shamanez** [comment]
Thanks a lot. That means in this line I need to use "mode". 

One little thing, could you please let me know what other stuff needs to be changed in the trainer. 

Is [this line](https://github.com/shamanez/transformers/blob/rag-retriever-end2end/examples/research_projects/rag-end2end-retriever/lightning_base.py#L392) a must for a trainer? 

Then what about the "distributed_backend" parameters? Should I change it to an accelerator?

**Comment by Borda** [comment]
What was last PL version you were using, most of these things was deprecated a while ago and all was covered by warnings...

**Comment by shamanez** [comment]
1.2.10.

**Comment by carmocca** [comment]
> Is [this line](https://github.com/shamanez/transformers/blob/rag-retriever-end2end/examples/research_projects/rag-end2end-retriever/lightning_base.py#L392) a must for a trainer?

Shouldn't in 1.3 as the default is True
 
> Then what about the "distributed_backend" parameters? Should I change it to an accelerator?

Yes. the `distributed_backend` flag is deprecated.

Closing as the original post is resolved.
