### ISSUE TITLE
`model` becames unpickable after calling `trainer.predict(model, dataloader)`

### ISSUE THREAD

**Issue by randommm** [PyTorchLightning/pytorch-lightning#7567]
## 🐛 Bug

`model` becames unpickable after calling `trainer.predict(model, dataloader)`, raises:
`TypeError: can't pickle _thread.lock objects`.

See attached example.

[example_pickle_pl.zip](https://github.com/PyTorchLightning/pytorch-lightning/files/6489192/example_pickle_pl.zip)

![Screenshot at 2021-05-16 09-26-39](https://user-images.githubusercontent.com/4267674/118397125-e745f200-b628-11eb-8eea-0fea4e7e5399.png)

**Comment by justusschock** [comment]
Hi @randommm ,

Can you give us a minimal example to reproduce? Without that, I'm afraid we cannot do much.

**Comment by carmocca** [comment]
@justusschock he did provide code.

> See attached example.
> 
> [example_pickle_pl.zip](https://github.com/PyTorchLightning/pytorch-lightning/files/6489192/example_pickle_pl.zip)

**Comment by yifuwang** [comment]
Hi @justusschock, in case you haven't had a chance to look at this yet: #7608.

**Comment by justusschock** [comment]
Hi @yifuwang I just prepared #7609 :D

**Comment by yifuwang** [comment]
@justusschock oops apologize for the trouble. Should've asked first. Will be more mindful next time :)
