### ISSUE TITLE
MLFlowLogger can‘t set Run Name

### ISSUE THREAD

**Issue by RegiusQuant** [PyTorchLightning/pytorch-lightning#7571]
When using MLFlowLogger for lightning model training, we can not set `Run Name` parameters

**Comment by justusschock** [comment]
I'm not familiar with mlflow. What's the difference between the `Run Name` and the `Experiment Name`? Generally, we rely on the logging providers to implement the backends.

If you can tell me, how you would specify the run-name when logging to mlflow manually I can see whether I can integrate it.

**Comment by RegiusQuant** [comment]
@justusschock In Mlflow, single experiment may contains multiple runs.

We can use `mlflow.start_run(run_name="aaa")` to set `Run Name`

<img width="516" alt="197F2D0A-3DE3-4A76-954C-722EB0951004" src="https://user-images.githubusercontent.com/36260888/118643040-a3144680-b80e-11eb-8792-08d83566b07a.png">
<img width="468" alt="1293EE4D-6267-4647-AEDF-48D6DBBFC5F1" src="https://user-images.githubusercontent.com/36260888/118643074-ad364500-b80e-11eb-8dea-341e97b85cd6.png">

**Comment by i-aki-y** [comment]
In the mlflow, the `run_name` is stored as a tag with key "mlflow.runName"
So you can set run_name by passing the tags as a workaround.

```
 MLFlowLogger(
    experiment_name="my_experiment",
    tracking_uri=MLFLOW_TRACKING_URI,
    tags={"mlflow.runName": "your-run-name"},
)
```

**Comment by RegiusQuant** [comment]
> In the mlflow, the `run_name` is stored as a tag with key "mlflow.runName"
> 
> https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.start_run
> 
> So you can set a run_name by passing tags as a workaround.
> 
> ```
>  MLFlowLogger(
>     experiment_name="my_experiment",
>     tracking_uri=MLFLOW_TRACKING_URI,
>     tags={"mlflow.runName": "your-run-name"},
> )
> ```

@i-aki-y thx, it works!

**Comment by justusschock** [comment]
@i-aki-y or @RegiusQuant want to submit a PR to include this to the logger?

**Comment by i-aki-y** [comment]
OK, I will make a PR.

**Comment by edenlightning** [comment]
Thanks @i-aki-y !
