### ISSUE TITLE
Why isn't EarlyStopping called after every validation_end unlike ModelCheckpoint?

### ISSUE THREAD

**Issue by chris-clem** [PyTorchLightning/pytorch-lightning#758]
## ❓ Questions and Help

Hi,

I was wondering why the EarlyStopping Callback is not called after every validation_end unlike the ModelCheckpoint Callback? I use val_check_interval < 1 and my model overfits quite fast on the train data, so it would be handy to stop even during an epoch.

#### What have you tried?

I tried to replace on_epoch_end with on_batch_end of the EarlyStopping Callback, but that did not work. My next step would be to integrate the functionality of EarlyStopping into ModelCheckpoint, but maybe there is an easier solution.

#### What's your environment?

 - OS: Linux 16.04 LTS
 - Packaging: pip
 - Version: 0.6.0

**Comment by williamFalcon** [comment]
AFAIK it is  being called after every checkpoint callback?

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/training_loop.py#L352

**Comment by chris-clem** [comment]
Is this already available in Version 0.6.0? It was changed 7 days ago: https://github.com/PyTorchLightning/pytorch-lightning/commit/b35c472bb17d170102fd0b987655462b7e3304d3

**Comment by Borda** [comment]
> Is this already available in Version 0.6.0? It was changed 7 days ago: [b35c472](https://github.com/PyTorchLightning/pytorch-lightning/commit/b35c472bb17d170102fd0b987655462b7e3304d3)

Yes
