### ISSUE TITLE
[MNIST-TPU-Colab] RuntimeError: Cannot replicate if number of devices (1) is different from 8 

### ISSUE THREAD

**Issue by renat-abbyazov** [PyTorchLightning/pytorch-lightning#7591]
## 🐛 Bug

Hi folks,

I have a problem when running Lightning MNIST TPU example notebook on all 8 TPU cores, please also see https://github.com/PyTorchLightning/pytorch-lightning/issues/1703#issuecomment-821804582

### To Reproduce

https://colab.research.google.com/github/PytorchLightning/pytorch-lightning/blob/master/notebooks/06-mnist-tpu-training.ipynb

### Environment

 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS: Ubuntu 18.04.5 LTS (Bionic Beaver)
 - How you installed PyTorch: pip
 - Python version: 3.7.10
 - Any other relevant information: pytorch-lightning-environment
 ```
pytorch-lightning             1.3.1         
torch                         1.8.1+cu101   
torch-xla                     1.8           
torchmetrics                  0.3.2         
torchsummary                  1.5.1         
torchtext                     0.9.1         
torchvision                   0.9.1+cu101 
```

**Comment by kaushikb11** [comment]
@renat-abbyazov Could you run only the 8 TPU Cores example after restarting the notebook? Lmk if that works.

**Comment by renat-abbyazov** [comment]
yes, it works if I am using all 8 TPU Cores from the start

**Comment by adnan33** [comment]
I am facing the same issue even after starting with 8 tpu cores (on both torch xla 1.8 and 1.9) . Is there any workaround that enables using all 8 cores?
