### ISSUE TITLE
Add TorchIO tutorial to PyTorch Ecosystem examples

### ISSUE THREAD

**Issue by fepegar** [PyTorchLightning/pytorch-lightning#7595]
## 📚 Documentation

Hi! I have seen that there is a section in the docs for [PyTorch Ecosystem examples](https://pytorch-lightning.readthedocs.io/en/latest/ecosystem/community_examples.html#pytorch-ecosystem-examples). I recently added [TorchIO + MONAI + PyTorch Lightning](https://github.com/fepegar/torchio/tree/master/notebooks#torchio--monai--pytorch-lightning) to [TorchIO](http://torchio.rtfd.io/). Would you like to add it to the list? I can open a PR if you like.

**Comment by edenlightning** [comment]
Looks cool! Go for it!
