### ISSUE TITLE
Early Stop being triggered causing epochs to increase spuriously

### ISSUE THREAD

**Issue by surya-narayanan** [PyTorchLightning/pytorch-lightning#7634]
## 🐛 Bug

Early stopping triggered with min_epochs causes epochs to increase by 1 for no reason

## Please reproduce using the BoringModel

https://colab.research.google.com/drive/1tEuLz3Bhc8ktwlDWb00eZCDwpklAEktg?usp=sharing

### Expected behavior

Epochs should stay the same even if Early Stopping is triggered

### Environment

* CUDA:
	- GPU:
	- available:         False
	- version:           10.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.1+cu101
	- pytorch-lightning: 1.3.2
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.10
	- version:           #1 SMP Tue Apr 20 19:55:43 PDT 2021### Additional context

Other info: 

In this plot here each epoch should last 32 steps. However, it the bug I am describing is causing the number of epochs counted to escalate.

![image](https://user-images.githubusercontent.com/17240858/119045654-97d92c00-b970-11eb-9c85-242c94945b4a.png)

**Comment by biswaroop1547** [comment]
The notebook which you've linked above, has both `min` and `max` epochs set to ```10``` but you mentioned in the issue 32 epochs, just a beginner here trying to understand the issue :sweat_smile:
can anyone please explain on that?

**Comment by surya-narayanan** [comment]
Sorry to confuse - the screenshot was from my work, not the notebook :D

**Comment by biswaroop1547** [comment]
Ah got it! Thanks! :)
