### ISSUE TITLE
wandb logging does not work - log method called on the wrong object (?)

### ISSUE THREAD

**Issue by Aljo-Rovco** [PyTorchLightning/pytorch-lightning#764]
## 🐛 Bug

When using the WandbLogger and not providing an experiment, I get an `AttributeError: 'Run' object has no attribute 'log'` in line [84 of WandbLogger](https://github.com/PyTorchLightning/pytorch-lightning/blob/deffbaba7ffb16ff57b56fe65f62df761f25fbd6/pytorch_lightning/logging/wandb.py#L84). Instead on `experiment`, I think `log` should be called on `wandb`

#### Code sample
    wandb_logger = WandbLogger(name="name", save_dir="/path/to/folder", offline=False,  project="project")
    trainer = Trainer(logger=wandb_logger)
    trainer.fit(model)

### Environment

 - PyTorch Version (e.g., 1.0): 1.2
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version:9.0
 - GPU models and configuration:
 - Any other relevant information:

**Comment by Aljo-Rovco** [comment]
upgrading to wandb `0.8.21` resolved this issue. was on `0.8.14` before

**Comment by Borda** [comment]
then we shall put the min version to requirements, pls, a PR is welcome...

**Comment by Aljo-Rovco** [comment]
Just as a means to show the users the required versions and do checks for it in the respective methods (check in `wandb.py` if the correct version is installed)? Guess people wouldn't want to do a `pip install -r requirements-extra.txt`

**Comment by Borda** [comment]
@Aljo-Rovco is there a PR?

**Comment by Aljo-Rovco** [comment]
@Borda yes. Created the suggested 'requierments-extra.txt' with the current versions of the logger packages
