### ISSUE TITLE
Full precision (fp32) support for ZeRO Stage2 and Stage3

### ISSUE THREAD

**Issue by qiyifei1** [PyTorchLightning/pytorch-lightning#7663]
## 🚀 Feature
Deepspeed v0.3.16 supports fp32 for ZeRO Stage2 and Stage3.
Is it possible to have it in pytorch-lightning?

### Motivation
To train fp32 models with higher speed

**Comment by edenlightning** [comment]
@SeanNaren

**Comment by abhinavrai44** [comment]
I am also facing issues when I try to use mix precision. Please share a solution if it is possible

**Comment by SeanNaren** [comment]
This is possible now in Lightning 1.4, just install the latest DeepSpeed and do not pass the precision=16 flag!
