### ISSUE TITLE
Restructure Lightning Docs

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#7666]
## 🚀 Feature
Restructure Lightning documentation to make it easier to read, find, and use.

### Motivation
Lightning has grown a lot, and so did the docs. We should do a massive clean up.

**Comment by oplatek** [comment]
Can you please links to github source code?

For example in here: https://pytorch-lightning.readthedocs.io/en/latest/extensions/generated/pytorch_lightning.callbacks.Callback.html#pytorch_lightning.callbacks.Callback

I cannot jump to Github page exploring the source code. I just jump to another docs page.
<img width="855" alt="Screenshot 2021-05-31 at 16 43 56" src="https://user-images.githubusercontent.com/229266/120209952-883eca80-c22f-11eb-9a2c-d88cd0c547c7.png">

**Comment by akihironitta** [comment]
@oplatek Jumping to the source code in the docs (which is the same as the PyTorch docs) isn't enough for you? e.g. https://pytorch-lightning.readthedocs.io/en/latest/_modules/pytorch_lightning/callbacks/base.html#Callback

**Comment by oplatek** [comment]
@akihironitta do not take it as a criticism ... it is a nice feature for sure! Just want more always :) 

However, linking directly to GitHub would be really awesome for several use-cases I use very frequently:
1. exploring history on GitHub and comparing it with my version to debug the differences
2. GitHub supports jumps to references / jump to definitions - one can use a web browser almost like an IDE.

When I am thinking about it would be enough to put a single link to a python module/file on GitHub from the top of each page in the docs:

e.g. for https://pytorch-lightning.readthedocs.io/en/latest/_modules/pytorch_lightning/callbacks/base.html
put a link to https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/callbacks/base.py

I always search for the Github code anyway based on the docs.
