### ISSUE TITLE
pytorch lightning v1.3.x ModelCheckpoint does not save the model checkpoint

### ISSUE THREAD

**Issue by VardaanBajaj** [PyTorchLightning/pytorch-lightning#7667]
I was using the following code to call the fit function of the trainer class.
```
checkpoint_callback = ModelCheckpoint(
    dirpath = os.getcwd(),
    filename = '{epoch:02d}-{val_loss:.5f}-best-model.ckpt',
    save_top_k = 1,
    # save_weights_only=True,
    verbose = True,
    monitor = 'val_loss',
    mode = 'min'
)

early_stopping_callback = EarlyStopping(monitor='val_loss', patience=5)

trainer = pl.Trainer(
    checkpoint_callback=checkpoint_callback,
    callbacks=[early_stopping_callback],
    max_epochs=N_EPOCHS,
    progress_bar_refresh_rate=30,
    log_every_n_steps = 10
)
```

The expectation is that after calling the fit() function on the trainer object, the best model should be saved (save_top_k=1) since the val_loss is decreasing almost every epoch. In pytorch lightning version I was initially using version 1.3.2 where the desired output is not obtained. I tried everything related to ModelCheckpoint in the pytorchlightning forums but there was hardly any deviation from the above code. Finally on switching the version to 1.2.5, things worked as expected. 

Is there any gap in my understanding of things?

**Comment by ananthsub** [comment]
You need to pass checkpoint_callback via the callbacks argument of the Trainer

**Comment by VardaanBajaj** [comment]
Thanks a lot. This helps.
