### ISSUE TITLE
Add warning for "ddp" in validation_epoch_end

### ISSUE THREAD

**Issue by Rizhiy** [PyTorchLightning/pytorch-lightning#7691]
## 📚 Documentation

As I currently understand, in `ddp` `validation_epoch_end` only sees part of the data which is located on selected device. This needs to be made more apparent in the documentation, since currently it only talks about `dp` and `ddp2` which made me think that for everything else it is done automatically.

Thanks!

**Comment by XiaomoWu** [comment]
Agree. This also applies to `test_epoch_end`, where it only gathers data on one GPU.

**Comment by edenlightning** [comment]
interested in contributing a PR?
