### ISSUE TITLE
If ModelCheckpoint and Validation occur on the same step, validation should run first.

### ISSUE THREAD

**Issue by Rizhiy** [PyTorchLightning/pytorch-lightning#7694]
## 🚀 Feature
When using iteration based training, if validation and check pointing occur on the same step, validation should run first.

i.e.
```python
        checkpoint_callback = ModelCheckpoint(
            every_n_train_steps=100
            save_top_k=1,
            save_last=True,
			...
        )
        trainer = self._create_trainer(
            max_steps=1_000
            callbacks=[checkpoint_callback],
            val_check_interval=50,
			...
        )
```
In this arrangement, currently, checkpointing is (sometimes?) called first and will see stats from 50th iteration. This leads to incorrect version of the model being saved.

### Motivation

Currently, order is either random or check pointing is run first, which causes incorrect.
### Pitch

Ensure that if `ModelCheckpoint` callback exists and validation is used, `ModelCheckpoint` is always called after validation is done.

### Alternatives

Considering how many callbacks exists, perhaps validation should be changed to run as a callback as well. That way, ensuring correct order might be as easy as sorting callbacks.

**Comment by ananthsub** [comment]
Could you provide an example with the BoringModel from the bug report that demonstrates the inconsistency?

**Comment by Rizhiy** [comment]
> Could you provide an example with the BoringModel from the bug report that demonstrates the inconsistency?

https://colab.research.google.com/drive/117WHyWm6vYd7hUVNde-ve2nWVt74c7BS?usp=sharing

**Comment by dmitrypenzar1996** [comment]
Still observing this issue. Is there any workaround?
