### ISSUE TITLE
all_gather should raise an error if it didn't gather anything.

### ISSUE THREAD

**Issue by Rizhiy** [PyTorchLightning/pytorch-lightning#7695]
## 🚀 Feature
Currently, `all_gather` passes silently when non-compatible type is passed into it.

### Motivation

This can lead to bugs, when the wrong variable is passed in and nothing is gathered.

### Pitch

Keep track if anything was actually gathered in `all_gather` and raise an error if not.

### Alternatives

Check type during `all_gather` and if non-gatherable stuff is passed in, raise an Error.

**Comment by edenlightning** [comment]
Thanks for the issue! Want to try sending a PR with the fix?

**Comment by Rizhiy** [comment]
@edenlightning will take a look on weekend.
