### ISSUE TITLE
Allow using all_gather on custom classes

### ISSUE THREAD

**Issue by Rizhiy** [PyTorchLightning/pytorch-lightning#7696]
## 🚀 Feature
Make `all_gather` work with custom classes which contain gatherable variables.

### Motivation

Currently, `all_gather` works on raw tensors and some default collections. I like to wrap my tensors into custom classes, so they are easier to work with. It is not always possible to inherit `Tensor`, so not all of them are detected properly.

### Pitch

Have a class which can be inherited which defines functions to provide gatherable variables, e.g.:
```python
class Gatherable:
	def vars_to_gather(self) -> Sequence:
		raise NotImplementedError
	
	def update_from_gathered(self, gathered: Sequence) -> None:
		raise NotImplementedError
```
This can then be used to gather custom classes.

### Alternatives

Perhaps `pl.utilities.apply_func.TransferableDataType` can be reused, since it has nearly the same functionality, the question is how to automatically process gathered input.
Perhaps just concatenating in batch dimension will work fine as a default.

**Comment by yifuwang** [comment]
FWIW there's already an `all_gather_object` in `torch.distributed`:
https://pytorch.org/docs/stable/distributed.html#torch.distributed.all_gather_object

**Comment by Rizhiy** [comment]
@yifuwang Thanks for the tip, but it would still be nice to have it inside `all_gather` since it already calls `convert_to_tensors`.

**Comment by saltoricristiano** [comment]
Hi!
Any news on all_gather_object? I'm in the same situation!
