### ISSUE TITLE
Allow validation_epoch_end to trully work on all outputs

### ISSUE THREAD

**Issue by Rizhiy** [PyTorchLightning/pytorch-lightning#7697]
## 🚀 Feature
Currently, when using `ddp` `validation_epoch_end` only sees part of the data, which is not ideal for some metrics. It would be nice if optionally all outputs were gathered together at this stage.

### Motivation

Some metrics work differently if data is split beforehand and the results are averaged, in such cases a view of complete data provides more accurate results.

### Pitch

Have a flag in `Trainer`/`LighningModule` which will gather all outputs before passing them to `validation_epoch_end`.

**Comment by ananthsub** [comment]
It might not always be tractable to have `validation_epoch_end` gather all outputs onto one rank. For instance, this could easily OOM if used with a large validation dataset, or if the validation outputs themselves are large. 

What's the main issue you see with calling `all_gather` inside of the LightningModule to collect results?

**Comment by Rizhiy** [comment]
> It might not always be tractable to have validation_epoch_end gather all outputs onto one rank. For instance, this could easily OOM if used with a large validation dataset, or if the validation outputs themselves are large.

That's why I said optional) With regards to OOM errors, I think it is better to allow user to decide, RAM is not that expensive TBH.

> What's the main issue you see with calling all_gather inside of the LightningModule to collect results?

It is extra logic which can easily be automated. Since this project aims to remove boilerplate, I believe this is a valid request.

**Comment by XiaomoWu** [comment]
@Rizhiy Have you taken a look at `torchmetrics`? According to the [doc](https://torchmetrics.readthedocs.io/en/latest/pages/lightning.html#torchmetrics-in-pytorch-lightning), the line `self.log('train_acc_epoch', self.accuracy.compute())` computes the metric based on all outputs:

```python
class MyModel(LightningModule):

    def __init__(self):
        ...
        self.accuracy = torchmetrics.Accuracy()

    def training_step(self, batch, batch_idx):
        x, y = batch
        preds = self(x)
        ...
        # log step metric
        # this only computes metric on a single batch and on a single device
        self.log('train_acc_step', self.accuracy(preds, y))
        ...

    def training_epoch_end(self, outs):
        # log epoch metric
        # this computes metric based on *all* outputs
        self.log('train_acc_epoch', self.accuracy.compute())
```

**Comment by Rizhiy** [comment]
@XiaomoWu I saw that, but I don't trust the docs as much since `validation_epoch_end` also mentions *all*)
Can someone from the team confirm that torchmetrics `.compute` works with outputs across all nodes and all gpus?

**Comment by Rizhiy** [comment]
Another problem with having to gather manually: if tensor sizes don't match between nodes, process freezes with 100% GPU utilisation.
