### ISSUE TITLE
Does Pytorch-Lightning support the task of federated learning?

### ISSUE THREAD

**Issue by marsggbo** [PyTorchLightning/pytorch-lightning#7715]
Does Pytorch-Lightning support the task of federated learning? If so, any example provided? Thanks!

**Comment by kaushikb11** [comment]
@tchaton

**Comment by tchaton** [comment]
Hey @marsggbo,

We worked on a first integration with PySyft. Here is the notebook: https://github.com/OpenMined/PySyft/blob/dev/packages/syft/examples/duet/mnist_lightning/MNIST_Lightning_Syft_Data_Scientist.ipynb

Only works for CPU right now.

Best,
T.C
