### ISSUE TITLE
Model Parallel

### ISSUE THREAD

**Issue by nik-sm** [PyTorchLightning/pytorch-lightning#774]
Hi - I'm interested to start using your project, and I'm wondering if you support [Model Parallel](https://pytorch.org/tutorials/intermediate/model_parallel_tutorial.html), so that I can train models that do not fit on a single card?

If this is already supported, could you please point me to an example?
Or do you have any ideas on how to set this up manually, if it is not explicitly supported as part of the framework yet?

Thanks very much!

**Comment by awaelchli** [comment]
This was proposed in #50, but it's not yet implemented I think.

**Comment by williamFalcon** [comment]
@awaelchli correct. Let's keep the conversation in #50
