### ISSUE TITLE
Using DDPPlugin changes accelerator to ddp

### ISSUE THREAD

**Issue by Rizhiy** [PyTorchLightning/pytorch-lightning#7744]
## 🐛 Bug

If `DDPPlugin` is passed to `pl.Trainer` 

## Please reproduce using the BoringModel

https://colab.research.google.com/drive/1XsSQoQghHhIxA-9al9dnsjbBJOxzo1Ml?usp=sharing

### To Reproduce

As can be seen in output of "Run Test", `ddp` is initialized even though `dp` is chosen as accelerator.

### Expected behavior

Either ignore the plugin or raise an error about incompatability.

### Environment

* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.1+cu101
	- pytorch-lightning: 1.3.3
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.10
	- version:           #1 SMP Tue Apr 20 19:55:43 PDT 2021

**Comment by Rizhiy** [comment]
As a consequence, `DDPPlugin(find_unused_parameters=False)` cannot be used with `ddp_spawn`.

**Comment by awaelchli** [comment]
Directly related to #6090, we want to simplify how the accelerator and plugins are selected. This will also enable better checking of mismatching combinations.

**Comment by kaushikb11** [comment]
@Rizhiy @awaelchli Picking up #6090 next week, it would simplify things.

**Comment by awaelchli** [comment]
Sounds great!

**Comment by Rizhiy** [comment]
Decided to revisit this issue and found out that to use `find_unused_parameters` with `ddp_spawn` I have to use `DDPSpawnPlugin` instead of `DDPPlugin`.
Probably would be a good idea to add it to documentation.
