### ISSUE TITLE
Allow using pickle for checkpoints

### ISSUE THREAD

**Issue by Rizhiy** [PyTorchLightning/pytorch-lightning#7749]
## 🚀 Feature
Allow specifying pickle for checkpoint saving.

### Motivation

PyTorch has a bug with saving/loading classes with custom `__reduce__`: https://github.com/pytorch/pytorch/issues/32706

Since PL uses `torch.load` for loading checkpoints that means that models with custom `__reduce__` also don't work.
This also applies to any variable of the model, not just weights.

### Pitch

Allow us to save and load checkpoints using pickle.

### Alternatives

Respect `__reduce__` of the model, which is better I guess, but will probably require a bigger refactor.

**Comment by Rizhiy** [comment]
I guess this technically can be done by pickling in `on_save_checkpoint` and unpicking in `on_load_checkpoint`, but looks kind of ugly.

**Comment by justusschock** [comment]
Hi @Rizhiy ,

From the issue it seems that the pickle module is not the issue here but rather how torch uses that module. That being said, I don't think changing that module would help here.

**Comment by Rizhiy** [comment]
What I'm asking for is for ability to use `pickle.dump` and `pickle.load` instead of `torch.save` and `torch.load`.
