### ISSUE TITLE
Progress bar inaccurate during multi-node training [Fairscale/Deepspeed]

### ISSUE THREAD

**Issue by aplesnia** [PyTorchLightning/pytorch-lightning#7751]
## 🐛 Bug

When using either Fairscale or Deepspeed on multiple gpus across multiple nodes, the progress bar seems to be inaccurate. The total iterations seems to be calculated using the per gpu batch size. At first I thought, the current iteration count may be not matching up if it was based on the effective batch size (per_gpu_batch_size * num_gpus * num_nodes * accumulation_steps), however that doesn't perfectly match up either. I've looked through the documentation, but it doesn't really seem to specify weather the intent with the progress bar was to use the per gpu batch size or the effective bath size across all gpus. I have tried explicitly setting  `logging_batch_size_per_gpu` in the Deepspeed plugin as well to no avail, and same thing happens with Fairscale based training as well.

### To Reproduce

```python
trainer_args = dict()
trainer_args["plugins"] = []
trainer_args["num_nodes"] = 4
trainer_args["gpus"] = 4
trainer_args["accelerator"] = "ddp"
trainer_args["logger"] = mlf_logger
trainer_args["default_root_dir"] = PATH_LOG
trainer_args["callbacks"] = [model_checkpoint]

trainer_args["max_epochs"] = 1 
trainer_args["val_check_interval"] = 0.05  
trainer_args["accumulate_grad_batches"] = 1

train_mode = DeepSpeedPlugin(
    logging_batch_size_per_gpu = 128,
    cpu_offload = True,
    allgather_bucket_size=3e8,
    reduce_bucket_size=3e8,
)
trainer_args["plugins"].append(train_mode)
trainer_args["precision"] = 16

data_module = experiment_data.DataDefinitionA(
    batch_size=128,
    num_workers=6,
    prefetch_factor=10,
)

optimizer_config = {
    "optimizer_class": DeepSpeedCPUAdam, #FusedAdam, 
    "optimizer_kwargs": {"lr" : 5e-5},
}

model = experiment_models.bert_config_A(
    tokens_to_indices=data_module.vocab_and_mappings["tokens_to_indices"],
    config_positional=data_module.vocab_and_mappings["config_positional"],
    max_len=data_module.max_len,
    optimizer_config=optimizer_config,
    use_sent_idx=True,
    which='SMALL'
)

trainer = Trainer(**trainer_args)

trainer.fit(model, data_module)
```

Log at the end of training:
Note above it is set to train for 1 epoch, yet at the end of training the progress bar is only 3%.
15974338 total iterations seems correct assuming its based on the per gpu batch size like `total iterations = (num_training_samples + num_val_samples/val_check_interval) / batch_size_per_gpu` However, 528947 * 16 gpus != 15974338 so I am really quite unsure of how the current iteration is being set.
```
> Epoch 0:   3%|▎         | 528946/15974338 [145:20:08<4243:51:07,  1.01it/s, loss=1.96, v_num=61fd]
> Epoch 0:   3%|▎         | 528946/15974338 [145:20:08<4243:51:07,  1.01it/s, loss=1.97, v_num=61fd]
> Epoch 0:   3%|▎         | 528947/15974338 [145:20:09<4243:50:51,  1.01it/s, loss=1.97, v_num=61fd]
> Epoch 0:   3%|▎         | 528947/15974338 [145:20:09<4243:50:51,  1.01it/s, loss=1.97, v_num=61fd]
> Epoch 0:   3%|▎         | 528947/15974338 [145:22:22<4244:55:27,  1.01it/s, loss=1.97, v_num=61fd]
> 
> 
> [2021-05-23T10:36:42.272833] The experiment completed successfully. Finalizing run...
> 2021-05-23 10:36:42,278 - __main__ - 124 - INFO - Exiting context: TrackUserError
> 2021-05-23 10:36:42,278 - __main__ - 124 - INFO - Exiting context: RunHistory
> Cleaning up all outstanding Run operations, waiting 900.0 seconds
> 2 items cleaning up...
> Cleanup took 0.14957070350646973 seconds
> 2021-05-23 10:36:42,582 - __main__ - 124 - INFO - Exiting context: Dataset
> 2021-05-23 10:36:42,582 - __main__ - 124 - INFO - Exiting context: ProjectPythonPath
> [2021-05-23T10:36:42.583066] Finished context manager injector.
```

### Expected behavior
Progress bar reaches 100% at the end of the epoch and correctly updates iterations through training so the training time estimate is also accurate. 

### Environment

 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): N/A
 - Python version: 3.8
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: 16 v100s across 4 nodes
 - Any other relevant information:

**Comment by tchaton** [comment]
Dear @aplesnia,

Thanks for reporting this bug. Do you get the same issue when using DDP ?

Best,
T.C

**Comment by tchaton** [comment]
Dear @aplesnia,

As a workout until we get a fix, please just use `val_check_interval` as an integer.

Will keep you updated.

Best,
T.C

**Comment by aplesnia** [comment]
@tchaton Thank you for looking into this. I am wondering though if there is more to my issue than just the part you discovered. I will try and play around with the BoringModel when I get a chance to see if I can replicate it, but for now, in my original post the setup was:

Compute: 4 nodes with 4 gpus each = 16 total gpus
Training dataset size: 510933628 samples
Validation dataset size: 2557061 samples
Batch size: 64 per gpu
val_check_interval:  0.005 # set it like this because it wasn't working as expected as above

The progress bar above showed 15974338 total iterations which can approximately be reached by:
(Full Training dataset size  + Full Validation dataset size/val_check_interval ) / batch_size_per_gpu = (510933628  + 2557061/0.005 ) / 64 = 15974153.5625

Thus it seems like the full length of BOTH the training and validation datasets are being used in my case to come up the the total iterations number. It seems to be running correctly on all of the gpus though, so although I dont have a way to tell it seems like the current iteration is updating correctly. Its almost like the current iteration is correctly working in multi node mode, but the total iteration is treating it as its running on a single gpu. Which is why I am guessing that after a full epoch runs, the progress bar only shows ~3%

**Comment by aplesnia** [comment]
Update: I believe I have figured out the other issue and it's not a Pytorch Lightning bug. 

I have a CustomDistributedSampler and I had len(CustomDistributedSampler) returning the length of the full dataset instead of the per replica length like the default DistributedSampler does. So `val_check_interval` is still an issue, but the other part about it only reaching 3% completion was an error on my end.

**Comment by tchaton** [comment]
Dear @aplesnia,

Thanks for sharing your updates. Let me investigate the `val_check_interval` bug. 
Sorry for the inconvenience.

Best,
T.C

**Comment by tchaton** [comment]
Hey @aplesnia,

After further exploration, it seems to me the behaviour is correct.



```
@RunIf(min_gpus=2, special=True)
@pytest.mark.parametrize(["total_train_samples", "train_batch_size", "total_val_samples", "val_batch_size", "val_check_interval"], [
    pytest.param(8, 4, 2, 1, 0.2),
    pytest.param(8, 4, 2, 1, 0.5),
])
def test_progress_bar_max_val_check_interval(total_train_samples, train_batch_size, total_val_samples, val_batch_size, val_check_interval, tmpdir):

    world_size = 2

    train_data = DataLoader(RandomDataset(32, total_train_samples), batch_size=train_batch_size)
    val_data = DataLoader(RandomDataset(32, total_val_samples), batch_size=val_batch_size)

    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        num_sanity_val_steps=0,
        max_epochs=1,
        weights_summary=None,
        val_check_interval=val_check_interval,
        gpus=world_size,
        accelerator="ddp",
    )
    trainer.fit(model, train_dataloader=train_data, val_dataloaders=val_data)

    total_train_batches = total_train_samples // (train_batch_size * world_size)
    val_check_batch = max(1, int(total_train_batches * val_check_interval))
    assert trainer.val_check_batch == val_check_batch
    val_checks_per_epoch = total_train_batches / val_check_batch
    total_val_batches = total_val_samples // (val_batch_size * world_size)
    assert trainer.callbacks[0].total_train_batches == total_train_batches
    assert trainer.callbacks[0].total_val_batches == total_val_batches
    total_val_batches = total_val_batches * val_checks_per_epoch
    if trainer.is_global_zero:
        assert trainer.callbacks[0].main_progress_bar.total == total_train_batches + total_val_batches
```

**Comment by piseabhijeet** [comment]
Hi @tchaton 

Sorry for opening the discussion here, however, i am also facing a similar issue.

I am training my model without validation data and on 2 GPUs but i am still seeing the total iterations in accordance with local GPU batch_size. Here is a snippet of my code:

`trainer=pl.Trainer(max_epochs=2, callbacks=callbacks, logger=logs, gpus=2, accelerator='ddp', num_sanity_val_steps=0, terminate_on_nan=False, val_check_interval=0`
`trainer.fit(model, train_dataloader=train_data)`

Below are the logs:
![image](https://user-images.githubusercontent.com/57705684/143232312-17c1bed9-4f77-4f1b-881a-9e3deac49897.png)

Here i have 3500 samples for training and the local batch size is 32.

What could be the issue?

My environment:
PT - 1.8.2+cu111
PL - 1.3.8

**Comment by tchaton** [comment]
Hey @piseabhijeet,

From your logs, I can see there is 54 iteration.

Here is how it is calculated with only training data: dataset_length / (local_batch_size * num_gpus). 

3500 / (32 * 2) ~= 54.68 -> 54 as the last batch is drop or re-sampled.

When using DDP, your effective `batch size = num_gpus * local_bach_size`.

**Comment by piseabhijeet** [comment]
> Hey @piseabhijeet,
> 
> From your logs, I can see there is 54 iteration.
> 
> Here is how it is calculated with only training data: dataset_length / (local_batch_size * num_gpus).
> 
> 3500 / (32 * 2) ~= 54.68 -> 54 as the last batch is drop or re-sampled. This is the total number of batches to be seen by each GPU.
> 
> When using DDP, your effective `batch size = num_gpus * local_bach_size`.
> 
> It looks good to me.

Hi @tchaton 

Thank you for your prompt response.

batch_size is fine, i was referring to iterations: in the screenshot if you see, it shows 106 iterations - where the iterations should have been equal to 54. 
Also, `batch_idx` is the same for both GPUs - is this the expected behavior?

**Comment by tchaton** [comment]
Can you try with `Trainer(limit_val_batches=0)`. It seems validation might be included.

**Comment by piseabhijeet** [comment]
> Can you try with `Trainer(limit_val_batches=0)`. It seems validation might be included.

But i havent included val_dataloader

**Comment by piseabhijeet** [comment]
> limit_val_batches=0

Hi @tchaton 
even after specifying `limit_val_batches=0` ,the iterations are the same.

**Comment by piseabhijeet** [comment]
> Can you try with `Trainer(limit_val_batches=0)`. It seems validation might be included.

Hi @tchaton 

Apologies for the trouble, i had overridden the ProgressBar methods using tqdm operations. When i disable this callback, the behavior works as expected.

Sorry again for the inconvenience.

**Comment by tchaton** [comment]
Dear @piseabhijeet,

Happy you found the source of the problem !

Best,
T.C
