### ISSUE TITLE
Trainer.predict returns None when tpu_cores=8

### ISSUE THREAD

**Issue by KijitoraButi** [PyTorchLightning/pytorch-lightning#7755]
## 🐛 Bug

The Trainer.predict error was fixed in this [issue](https://github.com/PyTorchLightning/pytorch-lightning/issues/7664#issue-899023307), but there was another problem.
When tpuc_cores=8, Trainer.predict returns None.

## Please reproduce using the BoringModel

https://colab.research.google.com/drive/1evjVtSbQpVfiWpTsiZknT6PO6Fa7u7sY?usp=sharing

### To Reproduce

If you set tpu_cores=8 and run Trainer.predict, None will be returned.

### Expected behavior

Predicted values are returned from Trainer.predict.

### Environment

 - PyTorch Version (e.g., 1.0): 1.8.1+cu101
 - OS (e.g., Linux): Linux
 - Python version: 3.7.10
 - Any other relevant information: Colab notebook with TPU

**Comment by justusschock** [comment]
cc @kaushikb11 😎

**Comment by kaushikb11** [comment]
@KijitoraButi `return_predictions` is not supported by plugins that spawn processes. `TPUSpawn` Plugin is a subclass of `DDPSpawn` plugin and spawn processes, it is not supported.

**Comment by tchaton** [comment]
Dear @KijitoraButi,

Supporting trainer.predict for TPU could result into OOM and we decided it would be unwise.

However, we have a built-in Callback called BasePredictionWriter: https://pytorch-lightning.readthedocs.io/en/stable/extensions/generated/pytorch_lightning.callbacks.BasePredictionWriter.html#pytorch_lightning.callbacks.BasePredictionWriter.

```
import torch
from pytorch_lightning.callbacks import BasePredictionWriter

class CustomWriter(BasePredictionWriter):

    def __init__(self, output_dir: str, write_interval: str):
        super().__init__(write_interval)
        self.output_dir

    def write_on_batch_end(
        self, trainer, pl_module: 'LightningModule', prediction: Any, batch_indices: List[int], batch: Any,
        batch_idx: int, dataloader_idx: int
    ):
        torch.save(prediction, os.path.join(self.output_dir, dataloader_idx, f"{batch_idx}.pt"))

    def write_on_epoch_end(
        self, trainer, pl_module: 'LightningModule', predictions: List[Any], batch_indices: List[Any]
    ):
        torch.save(predictions, os.path.join(self.output_dir, "predictions.pt"))
```

Best,
T.C
