### ISSUE TITLE
How to alternatively load training and validation data?

### ISSUE THREAD

**Issue by marsggbo** [PyTorchLightning/pytorch-lightning#7757]
### Motivation

Now I have to optimize two models, one should be optimized by training data, and the other should be optimized by validation data. I wonder how to get a batch of both training and validation in the same step. 

### Pitch

The original Pytorch code is like this:
```python
...
        for step, ((trn_X, trn_y), (val_X, val_y)) in enumerate(zip(self.train_loader, self.valid_loader)):
            trn_X, trn_y = trn_X.to(self.device), trn_y.to(self.device)
            val_X, val_y = val_X.to(self.device), val_y.to(self.device)

            # phase 1. network 1 step
            self.ctrl_optim.zero_grad()
            logits, loss = self._logits_and_loss(val_X, val_y)
            loss.backward()
            self.ctrl_optim.step()

            # phase 2: network 2 step
            self.optimizer.zero_grad()
            logits, loss = self._logits_and_loss(trn_X, trn_y)
            loss.backward()
            self.optimizer.step()
```

**Comment by justusschock** [comment]
Hi @marsggbo 

I think this should be possible with manual optimisation (see [here](https://pytorch-lightning.readthedocs.io/en/latest/common/optimizers.html#manual-optimization) for the docs on this). However, we know that we currently have some limitations on that and we are currently working on allowing more customization on the training process. 

Any specific ideas/feature requests for that?

**Comment by marsggbo** [comment]
thanks! using multiple dataloaders and optimizers solved my problem.
