### ISSUE TITLE
NoneType object has no attribute on_predict_start when progress_bar_refresh_rate=0

### ISSUE THREAD

**Issue by max0x7ba** [PyTorchLightning/pytorch-lightning#7793]
## 🐛 Bug

When I pass `progress_bar_refresh_rate=0` constructor argument to `Trainer`, then `fit`, and then call `predict` it raises:

```
Traceback (most recent call last):
  File "bug_report_model.py", line 69, in <module>
    run()
  File "bug_report_model.py", line 65, in run
    trainer.predict(model, dataloaders=val_data)
  File "/home/max/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1025, in predict
    results = self.fit(model)
  File "/home/max/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/home/max/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 543, in dispatch
    self.accelerator.start_predicting(self)
  File "/home/max/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 79, in start_predicting
    self.training_type_plugin.start_predicting(trainer)
  File "/home/max/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 122, in start_predicting
    self._results = trainer.run_predict()
  File "/home/max/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 817, in run_predict
    self.predict_loop.setup(model, max_batches, dataloaders)
  File "/home/max/anaconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/trainer/predict_loop.py", line 58, in setup
    self.trainer._progress_bar_callback.on_predict_start(self.trainer, self.trainer.lightning_module)

```

## Please reproduce using the BoringModel

Start with https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py and insert the following 2 lines:

```
--- bug_report_model.py~	2021-06-01 21:13:13.040915960 +0100
+++ bug_report_model.py 	2021-06-01 21:14:35.767217478 +0100
@@ -58,9 +58,11 @@
         num_sanity_val_steps=0,
         max_epochs=1,
         weights_summary=None,
+        progress_bar_refresh_rate=0
     )
     trainer.fit(model, train_dataloader=train_data, val_dataloaders=val_data)
     trainer.test(model, test_dataloaders=test_data)
+    trainer.predict(model, dataloaders=val_data)
 
 
 if __name__ == '__main__':
```
### Expected behavior

`trainer.predict` completes successfully.

### Environment

 - PyTorch Version: 1.8.1
 - pytorch_lightning: 1.2.6
 - OS: Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.8.5
 - CUDA/cuDNN version: n/a
 - GPU models and configuration: n/a
 - Any other relevant information: tbd

### Additional context

One solution is to assign a dummy object which implements the required interface but does nothing to `trainer._progress_bar_callback` instead of `None` when `progress_bar_refresh_rate=0`. This would fix similar errors in the rest of the codebase, should it also assume that `trainer._progress_bar_callback` is always usable.

**Comment by kaushikb11** [comment]
@max0x7ba Could you share a reproducible notebook? Because it is not throwing errors for me.

**Comment by max0x7ba** [comment]
> @max0x7ba Could you share a reproducible notebook? Because it is not throwing errors for me.

I only used someone else's notebooks. 

How do I open https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py in some online notebook, please?

**Comment by max0x7ba** [comment]
> @max0x7ba Could you share a reproducible notebook? Because it is not throwing errors for me.

Start with https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py and the following 2 lines:

```
--- bug_report_model.py~	2021-06-01 21:13:13.040915960 +0100
+++ bug_report_model.py.py	2021-06-01 21:14:35.767217478 +0100
@@ -58,9 +58,11 @@
         num_sanity_val_steps=0,
         max_epochs=1,
         weights_summary=None,
+        progress_bar_refresh_rate=0
     )
     trainer.fit(model, train_dataloader=train_data, val_dataloaders=val_data)
     trainer.test(model, test_dataloaders=test_data)
+    trainer.predict(model, dataloaders=val_data)
 
 
 if __name__ == '__main__':
```

**Comment by max0x7ba** [comment]
> @max0x7ba Could you share a reproducible notebook? Because it is not throwing errors for me.

Added reproduction to the original report.

**Comment by kaushikb11** [comment]
What Lightning version are you using? Could you try the master?

**Comment by max0x7ba** [comment]
> What Lightning version are you using? 

pytorch_lightning-1.2.6

> Could you try the master?

Updating to pytorch_lightning-1.3.3 fixed it, thank you.
