### ISSUE TITLE
remove deprecated APIs [TBD for v0.8.0]

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#780]
## 🚀 Feature

In version 0.5.3 and 0.6 was some API changed but for compatibility reasons we still keep it... 
This deprecated API shall be cleaned in upcoming 0.8 release :rocket:

**Comment by Borda** [comment]
Still thinking about the package name (not repo/project) that it is too long... I like something like `torchlightning` or just `ptlightning` =)
Join it with cleaning could be a good opportunity... 8-)

**Comment by Borda** [comment]
let's get a wider opinion... :] https://www.surveymonkey.com/r/GMJG9TN

**Comment by williamFalcon** [comment]
Nope. For now let's keep as is

**Comment by djbyrne** [comment]
Hi guys, I'd be happy to take this on. Really like the framework and would like to start contributing :)

**Comment by Borda** [comment]
sure, at this moment this is just reminder so we do not forget it.. lol
but sure, @djbyrne would you mind having look at some other "first issues" in the backlog

**Comment by djbyrne** [comment]
Yeah @Borda I'd be happy to. Could look at #714, i think thats the only remaining "good first issue" that doesn't have someone working on it

**Comment by djbyrne** [comment]
Hey @Borda I have a PR ready, but when I try to push my branch it says I dont have access to the repo. Do I need to be added to the repo list ?

**Comment by Borda** [comment]
You need to do branch in your forked repo and then make PR, but this is for long future because 0.8.0 is planed after couple months... So there is high chance of conflicts with other PRs
I would recommend to let it be and take other first good issue ;)

**Comment by djbyrne** [comment]
Ah I see, will do. Yeah for sure, is there a workspace for Pytorch Lightning?

**Comment by Borda** [comment]
> Ah I see, will do. Yeah for sure, is there a workspace for Pytorch Lightning?

https://camo.githubusercontent.com/42eaba71efb1cd9904693fee132c8d11d70088d2/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f736c61636b2d636861742d677265656e2e7376673f6c6f676f3d736c61636b
