### ISSUE TITLE
Doesn't run on CPUs when `accelerator="ddp_cpu"` on TPUs

### ISSUE THREAD

**Issue by kaushikb11** [PyTorchLightning/pytorch-lightning#7810]
## 🐛 Bug

Doesn't run on CPUs when `accelerator="ddp_cpu"` is selected for Trainer on TPUs

### To Reproduce

```python
    model = BoringModel()
    trainer = Trainer(
        accelerator="ddp_cpu",
        tpu_cores=8,
        max_epochs=5,
    )
```

**Comment by kaushikb11** [comment]
@awaelchli An update on this issue, `ddp_cpu` works on TPUs when `num_processes` is default. But I pass values for it (2, 3, etc), it throws an Error.

```
https://symbolize.stripped_domain/r/?trace=7f8c85b0ff24,7f8c85a4520f,6c65636300316c64&map=
*** SIGTERM received by PID 120425 (TID 120425) on cpu 7 from PID 118970; stack trace: ***
PC: @     0x7f8c85b0ff24  (unknown)  open
    @     0x7f8a124b21e0        976  (unknown)
    @     0x7f8c85a45210  (unknown)  (unknown)
    @ 0x6c65636300316c65  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7f8c85b0ff24,7f8a124b21df,7f8c85a4520f,6c65636300316c64&map=ca1b7ab241ee28147b3d590cadb5dc1b:7f8a057b3000-7f8a127e5b20
E0707 12:33:03.001385  120425 coredump_hook.cc:250] RAW: Remote crash gathering disabled for SIGTERM.
E0707 12:33:03.015446  120425 process_state.cc:771] RAW: Raising signal 15 with default behavior
```

**Comment by awaelchli** [comment]
Is there any known difference of a CPU inside a TPU machine? make sure to omit `tpu_cores` when running this plugin. We should probably make this an error.

So you are saying 

```python
    model = BoringModel()
    trainer = Trainer(
        accelerator="ddp_cpu",
        num_processes=2
        max_epochs=5,
    )

```
does not work on a TPU machine, but on a regular CPU machine all is good right?

**Comment by kaushikb11** [comment]
It fails even after omitting the `tpu_cores` flag.

```python
    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=30,
        limit_val_batches=30,
        accelerator="ddp_cpu",
        # tpu_cores=8,
        num_processes=2,
        num_sanity_val_steps=0,
        max_epochs=3,
        weights_summary=None,
    )
```

Yes, it works as expected on my CPU machine. No worries, I will dig more into it.

**Comment by kaushikb11** [comment]
Update on this, I commented the XLA interactions in the Lightning code, but still, it was raising issues. Seems like this would be an issue on the tpuvm side if you are running `ddp_cpu` directly on TPU host machines.

**Comment by awaelchli** [comment]
@kaushikb11 I would recommend removing the P0 here, since ddp_cpu is really just meant for debugging. It's not recommended over just regular training with accelerator=cpu, as there are not performance benefits. 

What is your recommendation regarding the issue. Do we want to handle it in the accelerator connector with a error message, that this combination is not supported?

**Comment by kaushikb11** [comment]
Yup, let's add an error message in the Accelerator Connector that this combination as we are sure it is not supported, rather than the Users being bombarded with some alien error.

Will do a PR for this.
