### ISSUE TITLE
Unknown Warning on Pytorch Profiler

### ISSUE THREAD

**Issue by FrouxBY** [PyTorchLightning/pytorch-lightning#7816]
## 🐛 Bug

I get a warning when using the pytorch profiler on my machine, I cannot understand wether it's a real issue, and if it does affect the profiling.

```
[W record_function.cpp:322] Could not match some of the start callbacks with the corresponding end callbacks, callbacks changed during RecordFunction lifetime; you might be trying to profile the code after profiler is finished
```

## Please reproduce using the BoringModel

I am not able to reproduce it using Collab and the Boring Model, however, copying the BoringModel on my machine and run it (with the addition of profiler="pytorch" in Trainer param) does trigger the warning

### To Reproduce

Use following [**BoringModel**](https://colab.research.google.com/drive/1kGXKMdDenCdXeAFhlruwRXb-qlhzHtef?usp=sharing) 
however it does not trigger the warning on Collab, only on my working machine

### Expected behavior

No Warning, or at least an understanding why this is happening

### Environment

* CUDA:
        - GPU:
                - GeForce GTX 1080
                - GeForce GTX 1080
        - available:         True
        - version:           10.2
* Packages:
        - numpy:             1.20.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.8.1+cu102
        - pytorch-lightning: 1.3.3
        - tqdm:              4.48.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                -
        - processor:         x86_64
        - python:            3.7.5
        - version:           #145-Ubuntu SMP Wed Mar 24 18:08:07 UTC 2021

Thanks for helping me in understanding this warning

**Comment by tchaton** [comment]
Dear @FrouxBY,

I had the same warning while implementing the PyTorch Profiler. I think it is ok.
Did you visualise your traces ?

Best,
T.C

**Comment by FrouxBY** [comment]
Dear @tchaton,

Yes, i did visualize my traces, and they seem ok, so I believe it is ok as well, just thought someone as an idea about this warning
This will do for now, and if later on it become a problem, I will ask directly on the pytorch project, (or maybe they will be more documentation on it by this time),

Best

**Comment by austinmw** [comment]
I also get this warning. Any idea what it stems from?

**Comment by carmocca** [comment]
@austinmw We can re-open if you can provide a minimal reproducible script.
