### ISSUE TITLE
TPUs on Colab: training stuck at 0 in first epoch

### ISSUE THREAD

**Issue by ms337** [PyTorchLightning/pytorch-lightning#7856]
## 🐛 Bug

Custom LightningModule does not train on TPUs in Google Colab. Training gets stuck on Epoch 0, 0% for both 1 and 8 cores. Sometimes a runtime crash is observed. The same model trains successfully on 1 GPU in Colab and locally.

Using High-RAM environment and get "TPU has started up successfully with version pytorch-1.8" confirmation on initializing LightningModule in code cell.  

Failure first observed with custom dataset, and reproduced with DummyDataset. 

## Please reproduce using the BoringModel

N/A.

### To Reproduce

Please use this Colab shared below:

https://colab.research.google.com/drive/1IeJRghHFegfvBjeLAbW2sK0I-9yVZxPx?usp=sharing

Uses a DummyDatatset to reproduce. LightningModule implemented in a code cell with dependancies loaded through a repo cloned into runtime. All steps setup to reproduce easily.

Used High-RAM environment with Colab Pro. 

Multiple params used to reproduce error on TPUs: 

batch_size: 64, 128
tpu_cores: 1, 8
num_workers: 1, 8

With GPUs, works with:
batch_size = 2, 4
image_size = 256
num_workers = 1

### Expected behavior

Should successfully train on TPUs or give a clear error. 

### Environment

Installing TPU client with `!pip install cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.8-cp37-cp37m-linux_x86_64.whl`

Multiple custom Python modules imported by setting up code repo and imported as needed.

On running the collect_env_details.py script:

* CUDA:
	- GPU:
	- available:         False
	- version:           10.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.1+cu101
	- pytorch-lightning: 1.3.4
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.10
	- version:           #1 SMP Tue Apr 20 19:55:43 PDT 2021

### Additional context

The Lightning Module is fairly complex is multiple nn.Module submodules and external dependancies.

Model is not that big: 386.669 MM  is the Total estimated model params size.

No` .device(), .cuda()` calls, etc. in the minimal code being used while reproducing. 

When running with custom dataset wrapped in a LightningDataModule, gets stuck on Validation Sanity Check at the start. Colab shows the stack where I can see that it's stuck on a `_poll_process() `call. Note that using the DummyDataset does to initiate a Validation Sanity check (presumably intended behaviour). 

Running with the custom dataset with 1 TPU core has also given the following output while at 0 in validation sanity check, and then the runtime crashes:

```
tcmalloc: large alloc 2147483648 bytes == 0x55a7fdac8000 @  0x7fc39bb23b6b 0x7fc39bb43379 0x7fc38446025e 0x7fc3844619d2 0x7fc237248853 0x7fc236a4c9cf 0x7fc2371fa48a 0x7fc236b6b9e8 0x7fc236b6dd05 0x7fc236fd6471 0x7fc236f7bf50 0x7fc236ead314 0x7fc30d36154d 0x7fc30d47f01a 0x7fc236f7bf50 0x7fc236ead314 0x7fc2386db4a2 0x7fc2386db9f4 0x7fc236f7bf50 0x7fc236ead314 0x7fc3955e7c00 0x55a766e10cc0 0x55a766e10a50 0x55a766e87aba 0x55a766e7f7ad 0x55a766e123ea 0x55a766e847f0 0x55a766e12849 0x55a766e12ea1 0x55a766e81bb5 0x55a766e7f4ae
tcmalloc: large alloc 2147491840 bytes == 0x55a87dac8000 @  0x7fc39bb23b6b 0x7fc39bb43273 0x7fc1ecd5e19a 0x7fc1f6d4b5f2 0x7fc1ecd5d46c 0x7fc1ecd298ff 0x7fc1ecd2cdf8 0x7fc39a4236df 0x7fc39b8f66db 0x7fc39aa2b71f
tcmalloc: large alloc 2147491840 bytes == 0x55a9112e4000 @  0x7fc39bb43887 0x7fc39a439c29 0x7fc39a439ff2 0x7fc39a43a65e 0x7fc1f00e9047 0x7fc1f00e9a94 0x7fc1ecd9d486 0x7fc1ecd9d10c 0x7fc1ecd5f3e1 0x7fc1ecd298ff 0x7fc1ecd2cdf8 0x7fc39a4236df 0x7fc39b8f66db 0x7fc39aa2b71f
/usr/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 6 leaked semaphores to clean up at shutdown
```

On initializing the LightningModule, prints:
```
WARNING:root:TPU has started up successfully with version pytorch-1.8
/usr/local/lib/python3.7/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.24.3) or chardet (4.0.0) doesn't match a supported version!
  RequestsDependencyWarning)
```

**Comment by kaushikb11** [comment]
Hi Madhav, went through the code, manual optimization is not yet supported for TPUs in Lightning.
That's why the Error `AttributeError: 'LightningDistributedModule' object has no attribute 'require_backward_grad_sync'` for Single TPU core.

**Comment by ms337** [comment]
Hi @kaushikb11, thanks for looking into it. 

### Update

Switched to automatic optimization. The errors of training being stuck at 0 and runtime crashing without error still persist for some `batch_size` cases, albeit that now Resource Exhausted Errors occur for another set of them. The model trains for 1-Core `batch_size=4`.

Note that this is all with the DummyDataset.

### Automatic Optimization Implementation

Fairly confident that the automatic optimization for the GAN  is implemented correctly: its structurally based on the [documentation section on the same](https://pytorch-lightning.readthedocs.io/en/latest/common/optimizers.html#use-multiple-optimizers-like-gans) and the [Bolts DCGAN implementation ](https://github.com/PyTorchLightning/Lightning-Bolts/blob/master/pl_bolts/models/gans/basic/basic_gan_module.py#L67-L77). So I doubt that it is a source of error now.


### Debugging for Batch Size causing memory errors

Presuming memory issues might be a problem, I focused on testing out cases with varying` batch_size`. Kept the` num_workers` constant at `16` with ample Runtime RAM remaining.

I ran the following variations:

For 1 Core TPU run:

| Batch Size 	| Success/Failure                  	|
|------------	|--------------------------	|
| 128**        	| Runtime Crash            	|
| 64         	| Resource Exhausted Error 	|
| 32         	| Resource Exhausted Error 	|
| 16         	| Resource Exhausted Error 	|
| 8          	| Resource Exhausted Error 	|
| 4          	| Trains                   	|

For 8 Core TPU run, the errors are as follows:

| Batch Size 	| Failure       	|
|------------	|---------------	|
| 128**        | Runtime Crash 	|
| 64         	| Runtime Crash 	|
| 32         	| Stuck         	|
| 16         	| Stuck         	|
| 8          	| Stuck         	|
| 4          	| Stuck         	|

### Additional Context

Model is not that big:

```
  | Name                   | Type            | Params
-----------------------------------------------------------
0 | a_net                  | ANet            | 13.8 M
1 | p_net                  | PNet            | 4.9 M 
2 | g_net                  | GNet            | 70.4 M
3 | vgg16_perceptual_model | VGG16Perceptual | 7.6 M 
-----------------------------------------------------------
72.5 M    Trainable params
24.2 M    Non-trainable params
96.7 M    Total params
386.669   Total estimated model params size (MB)
```


### Questions

Are the errors of training being stuck at 0 and runtime crashing being caused by memory exhaustion issues too? 

Are these failure cases expected behaviour for training with TPUs using PL?  

Any ideas on why it trains for the 1-Core,` batch_size = 4`  case, and not for the 8-core `batch_size = 4` case?

Any suggestions from the community on maximizing TPU usage here would be welcome. Already looking at  https://pytorch-lightning.readthedocs.io/en/latest/advanced/tpu.html#performance-considerations.

Thanks.

**Comment by kaushikb11** [comment]
Hey @ms337, you seemed to have left Cato Slack.

Something to note here, while training on multiple tpu cores, the effective batch size is `batch_size & num_tpu_cores` which might be causing the memory issue.

**Comment by kaushikb11** [comment]
@ms337 Closing the issue.
