### ISSUE TITLE
Training metrics not reported in log file

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#7899]
## 🐛 Bug

Forwarding issue found in Kaggle participation
seems all training metrics are missing in CSVLogger

### To Reproduce

https://github.com/Borda/kaggle_plant-pathology/issues/9

### Expected behavior

have complete logging

### Environment

 - PyTorch Version (e.g., 1.0): 1.7
 - How you installed PyTorch (`conda`, `pip`, source): 1.3.4

**Comment by edgarriba** [comment]
@Borda I created a minimal example to reproduce the issue but cannot find the configuration where the metrics are not logged
```python
class CustomModel(BoringModel):
    def training_step_end(self, training_step_outputs):
        self.log("train_acc", 1., prog_bar=False)
        self.log("train_prec", 1., prog_bar=False)
        self.log("train_f1", 1., prog_bar=True)
        return super().training_step_end(training_step_outputs)

def test_integration(tmpdir):
    trainer = pl.Trainer(
        logger=CSVLogger(tmpdir),
        max_epochs=1,
    )
    model = CustomModel()
    trainer.fit(model)

    metrics = pd.read_csv(f'{trainer.logger.log_dir}/metrics.csv')
    print(metrics)
```
which produces the following output
```bash
metrics
   train_acc  train_prec  train_f1  epoch  step
0        1.0         1.0       1.0      0    49
```

**Comment by Borda** [comment]
I have another very simple model and still missing all train metrics
https://github.com/Borda/kaggle_brain-tumor-3D/blob/main/kaggle_brain3d/models.py
