### ISSUE TITLE
The main bolts website has a typo - "Rigurously" should be "Rigorously"

### ISSUE THREAD

**Issue by 00krishna** [PyTorchLightning/pytorch-lightning#7904]
## 🐛 Bug

There is typo on the main bolts website: https://www.pytorchlightning.ai/bolts
The section head says "Rigurously Tested", and it should be "Rigorously Tested"

## Please reproduce using the BoringModel

https://www.pytorchlightning.ai/bolts

https://www.pytorchlightning.ai/bolts

No Colab.

### To Reproduce

Go to website:
https://www.pytorchlightning.ai/bolts

**Comment by awaelchli** [comment]
Thanks!
Forwarded to website admin :)

**Comment by Borda** [comment]
shall be fixed now :rabbit:
