### ISSUE TITLE
nvidia dali support

### ISSUE THREAD

**Issue by smallzzy** [PyTorchLightning/pytorch-lightning#791]
## 🚀 Feature
Re-open the case for #513. i.e. Support nvidia dali iterator as a possible data loader.

### Pitch

I have submitted a wip pull request to the master. #789
I would like to know if it is ok for the test to be depending on nvidia-dali in addition to apex.

**Comment by smallzzy** [comment]
The dali iterator does not support resetting while epoch is not finished. I suppose I shall provide a warning for that.

**Comment by williamFalcon** [comment]
@smallzzy this is sick. super excited by this feature

**Comment by Borda** [comment]
@smallzzy we have cleared the API and now it should be stable... Mind resume your addition?

**Comment by brunoalano** [comment]
Some news about DALI support?

**Comment by Borda** [comment]
@brunoalano interested in implementing DALI?

**Comment by brunoalano** [comment]
@Borda Do you have a pipeline what should have be done to support it? But I'm available to do that with a minimal guidance (started using PyTorch Lightning and DALI these days)

**Comment by Borda** [comment]
we had almost done PR some time ago so I use you can resume from that point... #789

**Comment by irustandi** [comment]
Is anyone working on this currently?

**Comment by ydcjeff** [comment]
@irustandi I think no one

**Comment by irustandi** [comment]
I tried converting PyTorch Lightning's MNIST example to use DALI, it seems to work out of the box without requiring modification to the PyTorch Lightning's internals. See below.

[https://gist.github.com/irustandi/3d180ed3ec9d7ff4e73d3fdbd67df3ca](https://gist.github.com/irustandi/3d180ed3ec9d7ff4e73d3fdbd67df3ca)

**Comment by Borda** [comment]
@irustandi cool, mind add it as example, send a PR?

**Comment by irustandi** [comment]
@Borda sure, will create the PR.

**Comment by ImMrMa** [comment]
I want to know that if dali with ddp and amp and dali's pipeline in distributed situation can work well? And have a perfect performance?

**Comment by Borda** [comment]
Good question, I believe so... @awaelchli?
