### ISSUE TITLE
More flexible paths for saving tensorboard data

### ISSUE THREAD

**Issue by bobkemp** [PyTorchLightning/pytorch-lightning#793]
## 🚀 Feature

I'd like more flexibility in the directory hierarchy used for writing tensorboard data.
Specifically, I want to make the experiment-name directory optional, removing one level in the hierarchy.

Also I'd like to be able to specify the name of the version directory.  Currently it is "version_N" but if the constructor version parameter is a string, I think it could just directly use that.

### Motivation

You could specify the version on the command line or generate it from the current datetime, which I find more meaningful than "version_73".  Likewise if the tensorboard data is not going to be preserved, it's much more readable in the tensorboard gui to skip the experiment name.

### Pitch

I have a branch with working code + tests

https://github.com/bobkemp/pytorch-lightning/tree/tensorboard-path-generalisation

### Alternatives

None

**Comment by williamFalcon** [comment]
@bobkemp could you post examples and use cases of what you mean? also, you can submit a PR to make the changes easier to see.

**Comment by bobkemp** [comment]
Here's the directory layout you could have and how it appears in TensorBoard.
I think the change also cleans up the code a little, removing duplication.

![pr793-changes](https://user-images.githubusercontent.com/5106328/74086418-908f5700-4a7a-11ea-880d-67eb1cc5fb8d.png)

Without experiments directory:
`TensorBoardLogger(tensorboard_dir, name="")`

checkpoints/version_0
checkpoints/version_0/events.out.tfevents.1581113035.glia.8401.0
checkpoints/version_0/meta_tags.csv

Without experiments directory and with explicitly named version directory:
`TensorBoardLogger(tensorboard_dir, name="", version="2020-02-07-220525")
`
checkpoints/2020-02-07-220525
checkpoints/2020-02-07-220525/events.out.tfevents.1581113127.glia.8438.0
checkpoints/2020-02-07-220525/meta_tags.csv

Current code:
`TensorBoardLogger(tensorboard_dir)
`
checkpoints/default
checkpoints/default/version_0
checkpoints/default/version_0/events.out.tfevents.1581112657.glia.8299.0
checkpoints/default/version_0/meta_tags.csv
checkpoints/default/version_1
checkpoints/default/version_1/events.out.tfevents.1581112777.glia.8341.0
checkpoints/default/version_1/meta_tags.csv

**Comment by bobkemp** [comment]
PR 804
