### ISSUE TITLE
Release Pytorch Lightning as a conda package

### ISSUE THREAD

**Issue by dangpzanco** [PyTorchLightning/pytorch-lightning#794]
## 🚀 Feature

Please make the `pytorch-lightning` package available from the conda package manager. This would probably be done through conda-forge: `conda install pytorch-lightning -c conda-forge`

### Motivation

The default way of installing Pytorch is via their conda channel, so (probably) most users of Lightning already use the conda package manager.

Conda packages provide automatic updates (`conda update --all`) and better package dependencies management, which could make the user's life a lot easier.

### Pitch

I'd like to install `pytorch-lightning` and its dependencies via this command:
```
conda install pytorch-lightning -c conda-forge
``` 
Ideally, this wouldn't force reinstall the `pytorch` package from its channel to `conda-forge`.

### Alternatives

My personal way of installing `pytorch-lightning` is running:
`pip install --no-deps pytorch-lightning test-tube`
And then `conda install` the missing dependencies that show up on `pip check`.

On version 0.5.3.x this was mandatory, since the required `pytorch-lightning` packages would mess up `numpy` and other conda packages.

**Comment by williamFalcon** [comment]
@dangpzanco agreed. Is this something you can take care of? at least the config. then we can set up what needs to happen for conda release.

**Comment by dangpzanco** [comment]
@williamFalcon I'm not sure if I'll be able to take care of this (I don't have much spare time). But if nothing comes up in a couple of weeks, I'll probably look into it.

**Comment by williamFalcon** [comment]
@Borda want to look at this for this release?

**Comment by Borda** [comment]
Depends how much time will leave, I don't have any experience with conda packaging yet...

**Comment by awaelchli** [comment]
According to @hadim it is not possible to release as conda package:
https://github.com/PyTorchLightning/pytorch-lightning/issues/199#issuecomment-588269459

**Comment by hadim** [comment]
Apparently it's possible to add pytorch packages to conda-forge following this example: https://github.com/conda-forge/staged-recipes/pull/11762

The pytorch version available on conda-forge is 1.1 CPU so tests won't pass but tests are already performed on this repo anyway.

**Comment by hadim** [comment]
See https://github.com/conda-forge/staged-recipes/pull/11778

**Comment by awaelchli** [comment]
would be great to have it in conda! Thanks hadim

**Comment by hadim** [comment]
You can close here.

**Comment by awaelchli** [comment]
we should probably add instructions in the readme. 
And it does not seem to work on windows but that could be because... Windows.
