### ISSUE TITLE
Small Missing Documentation about `on_test_start()`

### ISSUE THREAD

**Issue by eugeneh101** [PyTorchLightning/pytorch-lightning#7947]
In the callbacks documentation (https://pytorch-lightning.readthedocs.io/en/latest/extensions/callbacks.html), it mentions `on_test_start()`. However, in the LightningModule documentation (https://pytorch-lightning.readthedocs.io/en/stable/common/lightning_module.html where presumably the source file is https://github.com/PyTorchLightning/pytorch-lightning/blob/master/docs/source/common/lightning_module.rst), `on_test_start()` does not show up. Is `on_test_start()` supposed to be mentioned in the LightningModule docs as well? If so, please let me know, and I will do steps 2 (fix the typo) and 3 (submit a PR). Cheers!

## 📚 Documentation

For typos and doc fixes, please go ahead and:

1. Create an issue.
2. Fix the typo.
3. Submit a PR.

Thanks!

**Comment by carmocca** [comment]
> Is on_test_start() supposed to be mentioned in the LightningModule docs as well?

It is!

The PR would be greatly appreciated. If you also notice any other hooks that aren't mentioned you can include those too.

Thanks!

**Comment by tchaton** [comment]
Dear @eugeneh101,

Awesome catch !

Best,
T.C

**Comment by eugeneh101** [comment]
No problem, glad to help!
