### ISSUE TITLE
new profiler has failing tests

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#796]
@jeremyjordan 
Tests fail on OSX

```
tests/test_profiler.py::test_advanced_profiler FAILED 
```

**Comment by williamFalcon** [comment]
@jeremyjordan https://travis-ci.org/PyTorchLightning/pytorch-lightning/jobs/647158609

**Comment by jeremyjordan** [comment]
*sigh* that environment has really inconsistent `time.sleep()`s (eg. see discussion [here](https://www.reddit.com/r/Python/comments/8eqwsr/unexpected_behavior_of_timesleep_seems_to_add/?utm_source=amp&utm_medium=&utm_content=post_body)). i could relax the precision requirement on the test even further.

perhaps i can also profile a no-op and require the recorded duration to be less than X to ensure our profilers don’t add much overhead.

**Comment by Borda** [comment]
maybe some larger tolerance on the value?
```
        a_duration = get_duration(p.profiled_actions["a"])
>       np.testing.assert_almost_equal(a_duration, [4], decimal=1)
E       AssertionError: 
E       Arrays are not almost equal to 1 decimals
E       
E       Mismatch: 100%
E       Max absolute difference: 0.150021
E       Max relative difference: 0.03750525
E        x: array(4.2)
E        y: array([4])
tests/test_profiler.py:46: AssertionError
```

**Comment by jeremyjordan** [comment]
yeah a larger tolerance will ensure it passes the tests, we should also include a new test which does something like 

```
with profiler.profile("no-op"):
    pass
```
and ensure the "no-op" duration is less than some desired overhead threshold. this ensures that we won't introduce performance regressions in future updates.
