### ISSUE TITLE
Support yield in training_step for automatic optimization

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#7968]
## 🚀 Feature

Enable user to yield loss and optimizer to perform optimization in the order they wish.

```py
    class TestModel(BoringModel):

        def __init__(self):
            super().__init__()
            self.automatic_optimization = True

        def training_step(self, batch, batch_idx):
            # Discriminator.
            optimizer_idx = 0
            loss_d = self.loss(batch, self.layer(batch))
            optimizer = self.optimizers()[optimizer_idx]
            yield {"loss_d": loss_d, "optimizer": optimizer}
            # automatic optimization and it applies gradients

            # Generator.
            optimizer_idx = 1
            loss_g = self.loss(batch, self.layer(batch))
            return {"loss_g": loss_g, "optimizer": self.optimizers()[1]}
            # automatic optimization and it applies gradients

        def configure_optimizers(self):
            optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
            optimizer_2 = torch.optim.SGD(self.layer.parameters(), lr=0.1)
            return optimizer, optimizer_2
```

### Pitch

Some models which can be implemented only using manual optimization could be implemented using this paradigm and would result in more readable code.

**Comment by carmocca** [comment]
A gist of how this works:

```python
def training_step(i):
    print(f'training_step({i}) before first yield')
    yield i
    print(f'training_step({i}) before second yield')
    yield i
    print(f'training_step({i}) after second yield')


# 2 optimizers - 2 yields
optimizers = ['opt1', 'opt2']
for step in range(3):
    for loss, opt in zip(training_step(step), optimizers):
        print(f'after training_step({step})', loss, opt)
        # opt.zero_grad()
        # loss.backward()
        # opt.step()
```

```python
training_step(0) before first yield
after training_step(0) 0 opt1
training_step(0) before second yield
after training_step(0) 0 opt2
training_step(0) after second yield
training_step(1) before first yield
after training_step(1) 1 opt1
training_step(1) before second yield
after training_step(1) 1 opt2
training_step(1) after second yield
training_step(2) before first yield
after training_step(2) 2 opt1
training_step(2) before second yield
after training_step(2) 2 opt2
training_step(2) after second yield
```
This means we could get rid of the `optimizer_idx` parameter

**Comment by justusschock** [comment]
I really like this.

This makes it a lot easier. 
But how would a potential deprecation of the current API work? 
Also for new users: They might not be familiar with how a generator works and that might be a bigger issue to start with.

Do we completely switch to yielding then? E.g. also when we have only one optimizer?

Just a side note: @tchaton once you start yielding something, you cannot have a return statement (afaik) since it actually returns the generator. So your second loss would have to be yielded as well (as @carmocca did).

**Comment by tchaton** [comment]
Hey @justusschock,

```py
def training_step(i):
    print(f'training_step({i}) before first yield')
    yield 1  # loss for first opt
    print(f'training_step({i}) before second yield')
    return 2  # loss for second opt


# 2 optimizers - 2 yields
optimizers = ['opt1', 'opt2']
for step in range(3):
    for loss, opt in zip(training_step(step), optimizers):
        print(f'{loss} = training_step({step}) for', opt)
        # opt.zero_grad()
        # loss.backward()
        # opt.step()
    print()
```

```
training_step(0) before first yield
1 = training_step(0) for opt1
training_step(0) before second yield

training_step(1) before first yield
1 = training_step(1) for opt1
training_step(1) before second yield

training_step(2) before first yield
1 = training_step(2) for opt1
training_step(2) before second yield
```

**Comment by yifuwang** [comment]
@justusschock you can have a return statement in a generator. The return value is accessible through StopIteration's value attribute. The generator would be typed as `Generator[YieldType, SendType, ReturnType]`.

**Comment by justusschock** [comment]
@yifuwang thanks for letting me know, wasn't aware of this :) I tired this some time ago and it complained about that :D But that means, that we also need to check that value attribute when switching to  yield, right?

@tchaton that would be a solution I could agree with. What do we recommend though? And with one loss value it wouldn't matter if you yield or return right?

**Comment by tchaton** [comment]
Hey @justusschock,

I think this version should be the default for automatic optimization. It is more general and remove the need for `optimizer_idx == 0`.

I wonder how it gets traced though. @SeanNaren Would this work with IPU ?

Best,
T.C

**Comment by justusschock** [comment]
@tchaton Tracing doesn't work there. 


```python
>>> import torch
>>> def dummy_func(x):
...     yield x * 2
>>> torch.jit.trace(dummy_func, torch.tensor([1]))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/torch/jit/_trace.py", line 778, in trace
    traced = torch._C._create_function_from_trace(
RuntimeError: Tracer cannot infer type of <generator object dummy_func at 0x128f45190>
:Only tensors and (possibly nested) tuples of tensors, lists, or dictsare supported as inputs or outputs of traced functions, but instead got value of type generator.
```

but if we wrap it with the `generator` snippet we could also include a flag that falls back to returning as well?

**Comment by yifuwang** [comment]
I think the generator could be made traceable with a generic wrapper which converts the generator semantic to "returning a list of losses".
```
from typing import List
import torch

def dummy_func(x):
    yield x * 2
    yield x * 3

def wrapper(x) -> List[torch.Tensor]:
    ret: List[torch.Tensor] = []
    gen = dummy_func(x)
    for loss in gen:
        ret.append(loss)
    return ret

torch.jit.trace(wrapper, torch.tensor([1]), strict=False)  # strict=False for returning a list
```

But I agree that if we were to support this semantic, it should be in addition to the function version of the training_step, since generators are not (yet) idiomatic in PyTorch and we may run into unexpected issues later.

**Comment by justusschock** [comment]
@yifuwang But if you do this, you have another control flow. 

WIth yielding it would be `forward1` -> `backward1` -> `optimstep1` -> `forward2` -> `backward2` -> `optimstep2`
and with your wrapper it would be `forward1` -> `forward2` -> `backward1` -> `optimstep1`-> `backward2` -> `optimstep2`

Which may not be the desired behaviour since usually the result of forward2 should already be run with the updates from optimstep1.

**Comment by tchaton** [comment]
Hey @justusschock @yifuwang,

I guess this is still a great way to organise the `training_step` code and I don't believe users should `jit` the training_step anyway as it can contain `self.log`.

@yifuwang Would you be interested to give it a go. I believe this would be a bit involved, but definitely a really interesting feature :) 

Best,
T.C

**Comment by justusschock** [comment]
@tchaton we need to have jit-support since this is the only way to support @SeanNaren 's effort with IPUs

**Comment by tchaton** [comment]
Hey @justusschock,

IPUs support only `1 optimizer` anyway.
I would prefer not block this feature developement due to IPUs which are still in a very early beta stage.
Outside of IPUs, this feature should work for all other TrainingTypePluging. 
@SeanNaren Do you confirm ?

Best,
T.c

**Comment by SeanNaren** [comment]
> Hey @justusschock,
> 
> IPUs support only `1 optimizer` anyway.
> I would prefer not block this feature developement due to IPUs which are still in a very early beta stage.
> Outside of IPUs, this feature should work for all other TrainingTypePluging.
> @SeanNaren Do you confirm ?
> 
> Best,
> T.c

Agreed, I'd build this API with pure PyTorch compliant training type plugins/accelerators and then extend if possible to ones that are limited, such as IPUs.

**Comment by awaelchli** [comment]
This is not the first time, I remember we discussed this exact idea around before 1.0 release, @ananthsub may remember. We came to the conclusion that it is not going to work (I forgot the exact reason, too long ago).

Anyway, my question would be: How will Lightning know which optimiser is currently active?

**Comment by ananthsub** [comment]
> This is not the first time, I remember we discussed this exact idea around before 1.0 release, @ananthsub may remember. 

Here was the prior issue: https://github.com/PyTorchLightning/pytorch-lightning/issues/3535

> Anyway, my question would be: How will Lightning know which optimiser is currently active?

@awaelchli In the case of multiple optimizers and automatic optimization, could we rely on the order of optimizers returned matching with the yielded losses as @carmocca shows above? It is less explicit though if the module yields differently than the number of optimizers configured, though maybe users ought to yield a dummy loss in this case?

**Comment by carmocca** [comment]
An example of a yielding loop is available here: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/loop_examples/yielding_training_step.py

Closing this as it's not in our interest to provide support out-of-the-box. "yielding" is an advanced mechanism in Python so for the best user experience, we wouldn't want to suggest it unless it's the best option to support an use-case.
