### ISSUE TITLE
Optional dependencies are required for deprecated logging module

### ISSUE THREAD

**Issue by tullie** [PyTorchLightning/pytorch-lightning#798]
🐛 Bug

There is a backwards compatibility issues coming from PR #767. Notably, if a user doesn't have any of the extra logging dependencies then they'll be an import error.

### To Reproduce

1. Remove all logging dependencies from your environment (E.g. comet)
2. Depend on the deprecated pytorch_lightning.logging package and run

### Expected behavior

We expect to maintain backwards compatibility here so optional dependencies shouldn't be required.

**Comment by Borda** [comment]
Not sure if I understand correctly so if you remove eg `mlflow` and import `pytorch_lightning.logging` it crash with an import error?

**Comment by tullie** [comment]
Sorry it isn't related to 155. Not sure how that slipped in there. 

Otherwise, your understanding is right.

**Comment by Borda** [comment]
> Sorry it isn't related to 155. Not sure how that slipped in there.

The tricky thing is when it creates issue/PR it enters the text field starting with # which is associated with an issue/PR number so it automatically opens suggestion pop-up and the oldest issue (on the top) is the 155 and without enough attention, it is placed there automatically... It happened me several times already :]
@williamFalcon could you grant to @PyTorchLightning/core-contributors right to edit issues/PR so we do not border users with simple-straight-forward issues... 8-]
