### ISSUE TITLE
Make more detailed and non confusing output for ModelCheckpoint callback

### ISSUE THREAD

**Issue by notonlyvandalzzz** [PyTorchLightning/pytorch-lightning#7996]
## 🚀 Feature
Show result of the best model selection algorithm inside ModelCheckpoint callback

### Motivation

Its unclear and sometimes confusing what has been 'checkpointed' and why, especially in combination with mlflow autolog: you have no idea what model has been sent into mlflow

### Pitch

Typical claaback creation looks like this: 
```python 
checkpoint_callback = ModelCheckpoint(monitor='precision_val')
```
And it gonna be very helpful to produce output like this:
```
Best result for precision_val is 0.894 at epoch no. 45, model saved in $path or $logger you're using
```

### Alternatives

My regular train/test cycle utilizes bestmodel selection algo and produces output like i've proposed

**Comment by tchaton** [comment]
Dear @notonlyvandalzzz,

Sounds definitely interesting. Would you like to open a PR with this addition ?

Best,
T.C
