### ISSUE TITLE
SaveConfigCallback: Race condition with ddp.

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#8003]
## Please reproduce using the BoringModel

While running: `pl_examples/basic_examples/autoencoder.py` with 

```bash
python pl_examples/basic_examples/autoencoder.py --trainer.accelerator="ddp" --trainer.gpus=2
```

It failed there as the config file didn't exist.
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/utilities/cli.py#L100

```
  File "/home/thomas/pytorch-lightning/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 165, in start_training
    self._results = trainer.run_stage()
  File "/home/thomas/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 898, in run_stage
    return self._run_train()
  File "/home/thomas/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 947, in _run_train
    self.fit_loop.run()
  File "/home/thomas/pytorch-lightning/pytorch_lightning/loops/base.py", line 82, in run
    self.on_run_start(*args, **kwargs)
  File "/home/thomas/pytorch-lightning/pytorch_lightning/loops/fit_loop.py", line 173, in on_run_start
    self.trainer.call_hook("on_train_start")
  File "/home/thomas/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 1246, in call_hook
    trainer_hook(*args, **kwargs)
  File "/home/thomas/pytorch-lightning/pytorch_lightning/trainer/callback_hook.py", line 152, in on_train_start
    callback.on_train_start(self, self.lightning_module)
  File "/home/thomas/pytorch-lightning/pytorch_lightning/utilities/cli.py", line 102, in on_train_start
    f'{self.__class__.__name__} expected {config_path} to not exist. '
```

### To Reproduce

Use following [**BoringModel**](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing) and post here

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

* `IDE`: Please, use our python [bug_report_model.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
) template.

* `Colab Notebook`: Please copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py) (or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by carmocca** [comment]
> It failed there as the config file didn't exist.

The error is saying "expected to **NOT** exist" so the file does exist.

This is most likely because a previous run created the config file and by default, the CLI raises this error to avoid overwriting it.

**Comment by tchaton** [comment]
Hey @carmocca,

Interesting, I believe this happen on my first run, but happen due 2 processes running there. Need to be replicated.
However, I believe the error message should be clearer there if the intention is to `avoid overwriting it`.

Best,
T.C

**Comment by carmocca** [comment]
> However, I believe the error message should be clearer there if the intention is to avoid overwriting it.

Done in #8059
