### ISSUE TITLE
LightningCli: Passing trainer_defaults

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#8008]
### To Reproduce

It seems that ``PyTorchProfiler`` can't be passed as profiler argument in: 

```py
                           [--data.test_transforms TEST_TRANSFORMS]
                           [--data.dims DIMS]
profiler_example.py: error: Configuration check failed :: Parser key "trainer.profiler": Value "<pytorch_lightning.profiler.pytorch.PyTorchProfiler object at 0x7faeafcc7910>" does not validate against any of the types in typing.Union[pytorch_lightning.profiler.base.BaseProfiler, str, NoneType]:
  - Expected an str or a Dict with a class_path entry but got "<pytorch_lightning.profiler.pytorch.PyTorchProfiler object at 0x7faeafcc7910>"
  - Expected a <class 'str'> but got "<pytorch_lightning.profiler.pytorch.PyTorchProfiler object at 0x7faeafcc7910>"
  - Expected a <class 'NoneType'> but got "<pytorch_lightning.profiler.pytorch.PyTorchProfiler object at 0x7faeafcc7910>"
```

```
from pytorch_lightning.profiler import PyTorchProfiler

LightningCLI(ModelClass, DataModuleClass, trainer_defaults={"profiler": PyTorchProfiler(profile_memory=True)})
```

Is it a mis-use of LightningCLI or a bug ? @carmocca 

Use following [**BoringModel**](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing) and post here

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

* `IDE`: Please, use our python [bug_report_model.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
) template.

* `Colab Notebook`: Please copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py) (or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by carmocca** [comment]
Seems to me like this is a bug upstream. This produces the same error:

```python
from typing import Optional

import jsonargparse

print(jsonargparse.__version__)

class A:
    ...

def fn(arg: Optional[A] = None):
    print(arg)

parser = jsonargparse.ArgumentParser()
parser.add_function_arguments(fn)
parser.set_defaults({'arg': A()})
parser.parse_args()
```

cc: @mauvilsa

**Comment by mauvilsa** [comment]
Yes, this is an issue that relates to jsonargparse. In general having a class instance as a default is not a good idea because it is mutable. Furthermore, this breaks print_config because there is no way to convert the class instance into a `class_path` and `init_args` dict. Most likely what is needed is a default factory class that would be used in these cases, and giving a clear error message if a class instance is used for a default.

**Comment by carmocca** [comment]
So a function like `parser.set_default_factory(profiler=callable)`?

or `parser.set_default_factory(profiler={'class': PyTorchProfiler, 'init_args': ...})`?

**Comment by mauvilsa** [comment]
Something more like

```python
my_default_factory = default_class_factory(MyClass, init_args={...})
```

which then could be used to override a default as

```python
parser.set_defaults({'my_module.my_class': my_default_factory})
```

or to use as default in a signature as

```python
class MyModule:
    def __init__(
        self,
        my_class: MyClass = my_default_factory,
    ):
        ...
```

Something analogous to the field in dataclasses.

**Comment by tchaton** [comment]
> Yes, this is an issue that relates to jsonargparse. In general having a class instance as a default is not a good idea because it is mutable. Furthermore, this breaks print_config because there is no way to convert the class instance into a `class_path` and `init_args` dict. Most likely what is needed is a default factory class that would be used in these cases, and giving a clear error message if a class instance is used for a default.

Hey @mauvilsa,
I would argue that even if `default_class_factory` is definitely the recommended approach, we should still support `trainer_defaults`  with arguments provided by users. 
Especially as the path can be inferred automatically as `trainer.profiler` and we can inspect the class to get the proper  `print_config`.
When a user provides directly arguments in this format, we should print a warning with the recommended approach.
Currently, I believe not supporting passing trainer_kwargs seems counter-intuitive and users would become frustrated. 

Best,
T.C

**Comment by mauvilsa** [comment]
> I would argue that even if `default_class_factory` is definitely the recommended approach, we should still support `trainer_defaults` with arguments provided by users.

I agree that if a class instance of the correct type is given then it shouldn't fail like it does now.

> Especially as the path can be inferred automatically as `trainer.profiler` and we can inspect the class to get the proper `print_config`.

The class path can be inferred, but the init args can't be inferred. The file that `SaveConfigCallback` saves has two main uses. One is knowing the exact settings that were used when it was run and the second is reproducibility. If only the class path is inferred and included in the saved config, then it is not reproducible since some custom init args could have been used for the default. On the other hand, if this config key is not included in the saved config then it will be reproducible because when excluded the correct default would be used. But then by looking at the saved config you don't know all the settings that were used. Probably the best would be some solution in the middle. When I have a better idea how to make everything fit together I will comment.

> When a user provides directly arguments in this format, we should print a warning with the recommended approach. Currently, I believe not supporting passing trainer_kwargs seems counter-intuitive and users would become frustrated.

I agree we should do this.

**Comment by carmocca** [comment]
@quancs Your issue is https://github.com/PyTorchLightning/pytorch-lightning/discussions/8561, not this one

You can work around it by passing `--trainer.plugins ddp_find_unused_parameters_false`

**Comment by quancs** [comment]
> 
> 
> @quancs Your issue is #8561, not this one
> 
> You can work around it by passing `--trainer.plugins ddp_find_unused_parameters_false`

Aha, sorry....

**Comment by mauvilsa** [comment]
The `lazy_instance` now works for `nn.Module` classes. This is part of jsonargparse v4.0.0.

**Comment by carmocca** [comment]
@mauvilsa can you open a PR with a test using it with some of our components?

we'd need to merge https://github.com/PyTorchLightning/pytorch-lightning/pull/10426 first
