### ISSUE TITLE
When trying to load a cached model, got error

### ISSUE THREAD

**Issue by Xiang-Pan** [PyTorchLightning/pytorch-lightning#8016]
```python
trainer = Trainer(resume_from_checkpoint=PATH) 
```
---
```
 File "/scratch/xp2030/envs/pytorch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 898, in test
    self._set_running_stage(RunningStage.TESTING, model or self.lightning_module)
  File "/scratch/xp2030/envs/pytorch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 565, in _set_running_stage
    model_ref.running_stage = stage
AttributeError: 'NoneType' object has no attribute 'running_stage'
```

**Comment by ethanwharris** [comment]
Hi @Xiang-Pan thanks for reporting this. Can I ask what version of pytorch-lightning you are using? Are you able to provide a notebook that reproduces the bug (ideally using our [**BoringModel**](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing))?

Thanks :smiley:

**Comment by awaelchli** [comment]
`self._set_running_stage` was removed and refactored a while ago. Chances are high this is resolved in the latest version :)

**Comment by Borda** [comment]
@awaelchli I think that this is a back-compatibility issue which we shall address...

**Comment by awaelchli** [comment]
@Borda the error shows an internal call and fails there. We don't know what the user is running as no information was provided, the full stack trace is also missing.

**Comment by tchaton** [comment]
Dear @Xiang-Pan,

Without more information on your side, we will have to close this issue.

Best,
T.c

**Comment by Xiang-Pan** [comment]
I will try to get more information, I just met the error and tried another save and load method

**Comment by awaelchli** [comment]
@Xiang-Pan closing this stale issue. 
I am certain that upgrading the Lightning version will solve your problem.
