### ISSUE TITLE
Customizable TensorBoard Graphics especially at Test Run

### ISSUE THREAD

**Issue by iamkucuk** [PyTorchLightning/pytorch-lightning#802]
## 🚀 Feature
Customizable TensorBoard graphics may be helpful especially at the test run.

### Motivation
One may need to add customized graphics like pictures or grads to tensorboard. Especially for the test run, adding one scalar is just not enough. Exposure of tensorboard writer may be helpful. (Or even better, use-ready functions to show images, plot graphs etc.)

**Comment by williamFalcon** [comment]
https://pytorch-lightning.readthedocs.io/en/latest/experiment_logging.html#tensorboard
