### ISSUE TITLE
A unified and convenient  `Config` class

### ISSUE THREAD

**Issue by dalek-who** [PyTorchLightning/pytorch-lightning#8033]
### Motivation
There are many different ways to config things in a deep learning project, including:
* json/yaml
* argparser
* dataclass
* user-defined config class
* global variables
* ...

However, none of them is perfect. In my practice, I summarize some principles that a perfect config should satisfy:
- 1. **Easy to record and trace.**
For example, a json file or a config class can be traced by `git commit`, it's easy to review the difference in the future, but `argparser` can't be traced.
- 2. **Friendly to IDE (in another words, friendly to programming).**
This princeple including:
  * Can be auto completed.
  * Can hint types
  * Can jump to definition by click
  * Easy to refactor, like rename a config variable
  * Easy to add new config
So, a config class is better than `argparser` or `json`

- 3. **Simple syntax**
The syntax to define `argparser` is long and boring:
```python
parser = ArgumentParser()
parser.add_argument('--name', type=str, required=True,
                    help='Your name')
parser.add_argument('--language', type=str, default='Python',
                    help='Programming language')
parser.add_argument('--package', type=str, default='Tap',
                    help='Package name')
```

My favorite alternate is [typed-argument-parser](https://github.com/swansonk14/typed-argument-parser), which syntax is simple:
```Python
from tap import Tap

class SimpleArgumentParser(Tap):
    name: str  # Your name
    language: str = 'Python'  # Programming language
    package: str = 'Tap'  # Package name

```

- 4. **Can be nested defined and init**
json and yaml are easy to be nested, but a config class is difficult. For example, I want to define such a model config, but haven't find a library to do this:
```python
class Config_Encoder_A(BaseConfig):
    num_layer: int = 5
    activate: str = "relu"

class Config_Encoder_B(BaseConfig):
    pretrain_model: str = 'bert-base-uncased'
    sentence_emb: str = 'cls'

class Config_Decoder_C(BaseConfig):
    ...

class Config_Decoder_D(BaseConfig):
    ...

class Config_Model(BaseConfig):
    encoder: Union[Config_Encoder_A, Config_Encoder_B] = Config_Encoder_A
    decoder: Union[Config_Decoder_C, Config_Decoder_D] = Config_Decoder_D

config_model = Config_Model()
```
python `dataclass` can define a single config class, but can't easily define and init a nested config class.

- 5. **Can be converted from/to widely used config file format, like json/yaml**
- 6. **Some config value can be dynamically generated**
For example: when I want to config experiment's output dir:
```python
@dataclass
class ConfigFile:
    debug: bool
    start_time: str
    comment: str

    def __post_init__(self):
        self.OUTPUT_DIR = Path("./output") / f"{self.start_time}_debug-{self.debug}_{self.comment}"
        self.TENSORBOARD_DIR = self.OUTPUT_DIR / "tb"
        self.CHECKPOINT_DIR = self.OUTPUT_DIR / "checkpoint"
        self.log_path = self.OUTPUT_DIR / "log.txt"
        ...
```
These`Path` value can't be static set, since `debug` and `comment` are determined by command line args，and `start_time` is determined only on runtime.
- 7. **Split by namespace**
Many global variables is a bad practice, split them into differ class: `Config_Model`, `Config_Data`, `Config_Trainer`, `Config_FilePath`, `ArgumentParser`...
- 8. **(optional) Can choose whether this class can be read from command line argument**.
That is, a config class can be `static defined`,  `dynamic generated`(see 6), or `parsed from command line`(see 3, `Tap`)
- 9. **(optional) Can be used through `config.xxx`, or `config['xxx']`**
Some coders like object-style, while others like dict-style.
- 10. **(optional) Keep it a recommend best practice, rather than a forced one.**

Currently, there's no perfect config class: 
* [Transformers](https://huggingface.co/transformers/) `XXXConfig` like `ConfigBert` is limited to config transformer-like models, not a general deep-learning framework like pytorch-lightning 
*  [typed-argument-parser](https://github.com/swansonk14/typed-argument-parser) can't be nested defined, and can't dynamically calculate some config
* a simple python `dataclass` don't have complex feature like convert from/to json
* [Marshmallow](https://github.com/marshmallow-code/marshmallow) is designed for ORM, not for config.
* It's difficult for researchers to define a config class with so much feature.

Also, a build-in config class for pl has other benifit :
* can be expanded to support auto hyper-parameter search (if you plan to do so)
* have a unified api to save/load hyper-parameter
* reduce the argument number passed to `pl.LightningModule`, several objects like 'config_model', 'config_path', 'config_data' will replace hundreds of independent arguments.

**Comment by dalek-who** [comment]
If you are interested, I can show more details about my practice.

**Comment by carmocca** [comment]
I'm not quite sure what's your pitch or issue but we already integrate a library that works similarly to `Tap` called [jsonargparse](https://github.com/omni-us/jsonargparse). It supports most if not all of the points you made.

You can find the docs about our integration with it (the `LightningCLI`) here:
https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_cli.html

Note that Lightning can be used with any other config/CLI library. Another example is [Hydra](https://github.com/facebookresearch/hydra) which we have integrated in https://github.com/PyTorchLightning/lightning-transformers. It allows us to define a complex config structure for dynamic instantiation.

**Comment by dalek-who** [comment]
@carmocca Ok, I will detailed read these two library. Maybe this feature is too greedy :)
