### ISSUE TITLE
TPU execution causes error, while the same code works fine for GPU 

### ISSUE THREAD

**Issue by StephennFernandes** [PyTorchLightning/pytorch-lightning#8055]
Trained a Transformer model from scratch in pytorch, but the same code works fine on GPU  but throws error on TPU. 
heres the link to the code:

https://github.com/StephennFernandes/Transformers_from_scratch_lightning

possibly error in prepare_data() and setup() methods. 
checked if its a memory issue in collab turns out its not 
@kaushikb11 follow up from out past slack conversations

**Comment by kaushikb11** [comment]
@StephennFernandes Does the training work for Single core?

**Comment by StephennFernandes** [comment]
Haven't tested it on TPU single core, but it does work fine on GPU

**Comment by kaushikb11** [comment]
@StephennFernandes It's very hard to debug the issue without access to the data. Kindly add steps to access the data or steps for mock data. Closing the issue, feel free to reopen it with an approach to reproduce the issue. Also, do run it on a single TPU core, and update the details.
