### ISSUE TITLE
kernel restarting in jupyternotebook for import pytorch_lightning as pl

### ISSUE THREAD

**Issue by wenouyang** [PyTorchLightning/pytorch-lightning#8064]
When using jupyter notebook to run  pytorh_lightning program, after typing

`import pytorch_lightning as pl`

It generates popup kernel restarting message

![image](https://user-images.githubusercontent.com/5430158/122796387-f2251f80-d283-11eb-83d6-fb96660f63c0.png)

**Comment by kaushikb11** [comment]
@wenouyang Could you share the notebook to reproduce the issue?

**Comment by wenouyang** [comment]
@kaushikb11 ,  I think it might be due to the virtual environment been crashed. I re-installed on in another virtual environment. It is working now.
