### ISSUE TITLE
`CSVLogger` leaves out first (batch_idx = 0) iteration?

### ISSUE THREAD

**Issue by skanti** [PyTorchLightning/pytorch-lightning#8098]
## 🐛 Bug

The `CSVLogger` does not seem to log the very first `num_sanity_val_steps` and `batch_idx = 0` or `gobal_step = 0`

### To Reproduce

Use
```py
self.trainer = pl.Trainer( num_sanity_val_steps=2, logger=some_csv_logger,  ...)

def training_step(..):
  self.log("x", x)
  
def val_step(..):
  self.log("y", y)
```

### Expected behavior

Should include the metrics at `step = 0`
![image](https://user-images.githubusercontent.com/11197940/123086466-5d552a00-d41b-11eb-86f9-33df9ef8e6dc.png)

 - PyTorch Version (e.g., 1.0): 1.8
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version: 11.0
 - GPU models and configuration: Tesla P100
 - Any other relevant information:

**Comment by justusschock** [comment]
Hi @skanti 

I checked that and verified that this works as intended.

The Issue with your example is, that you only log at the end of the epoch (and therefore no step values are being logged). 
Additionally note that we have two trainer arguments controlling the logging called 
`flush_logs_every_n_steps` and `log_every_n_steps`. To verify this you have to set them to one.

The following script produces correct results for me:

```python
import torch
import pytorch_lightning as pl


class Dataset(torch.utils.data.Dataset):
    def __len__(self):
        return 100

    def __getitem__(self, index):
        return torch.tensor(index).float()


class Model(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(1, 1)

    def training_step(self, batch, batch_idx):
        self.log('x', batch, on_step=True, on_epoch=True)

        return self.linear(batch).sum()

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters())


pl.Trainer(
    logger=pl.loggers.CSVLogger('./test.csv'),
    limit_train_batches=100,
    flush_logs_every_n_steps=1,
    log_every_n_steps=1,
).fit(Model(), torch.utils.data.DataLoader(Dataset()))
```

**Comment by skanti** [comment]
Is there no other way to have the first iteration logged without `log_every_n_steps=1`? It slows down training quite significantly. `flush_logs_every_n_steps` seems to be a tensorflow specific flag.

If it is not possible with the current version. It would be great to add it as feature request
