### ISSUE TITLE
Using other libraries with pytorch-lightning.

### ISSUE THREAD

**Issue by ankitvad** [PyTorchLightning/pytorch-lightning#811]
I'm just wondering, would it be possible to use the AllenNLP/Texar-PyTorch models and data processing submodule as part of PyTorch-Lightning Trainer? Do you think using the class structure setting and the GPU training setting of PyTorch Lightning would be adaptable to AllenNLP modules?
I saw that torchtext data handling approaches can be used with Lightning, if I was to call any Seq2Seq models and the data input created by using AllenNLP and then use all of pytorch lightning's approach for training on GPU and everything, would that port to AllenNLP?

**Comment by williamFalcon** [comment]
Lightning doesn't abstract  pytorch.  As long as AllenNLP is using pure  pytorch modules  it should be fine!

Try it out.

Check out the  colab on the readme  to see  how it works with transformers
