### ISSUE TITLE
create dm.EMNISTDataModule

### ISSUE THREAD

**Issue by murphyk** [PyTorchLightning/pytorch-lightning#8110]
It would be useful to have a DM for https://www.tensorflow.org/datasets/catalog/emnist.

### Motivation

EMNIST is a much better dataset than MNIST, since it has more classes (0-9, a-z, A-Z), more data (4x), and more inherent ambiguity, yet it still easy to deal with computationally.

![image](https://user-images.githubusercontent.com/4632336/123210742-4d6b3380-d477-11eb-80da-3e9a74a18a07.png)

**Comment by ananthsub** [comment]
@murphyk this could be a good request for Lightning bolts / @PyTorchLightning/core-bolts as core PyTorch Lightning offers the API/interface for these components, but not implementations

**Comment by murphyk** [comment]
I created https://github.com/PyTorchLightning/lightning-bolts/issues/672. Closing this.
