### ISSUE TITLE
LoggerCollection breaks PyTorch profiler

### ISSUE THREAD

**Issue by gahdritz** [PyTorchLightning/pytorch-lightning#8157]
## 🐛 Bug

If the Trainer's `profiler` parameter is set to `"pytorch"` and the `Trainer`'s logger is an instance of `LoggerCollection`, the profiler fails to write to a local file (with a warning).

The path for said file is derived from [this property](https://github.com/PyTorchLightning/pytorch-lightning/blob/28afc7a10d9f9c1160935fb5c81a1a8c0492b392/pytorch_lightning/trainer/properties.py#L223) of the Trainer, which in turn derives from the `save_dir` of the Trainer's logger whenever the logger isn't a stock TensorBoard logger. The `save_dir` property of a LoggerCollection, which is what you get when the trainer is provided with more than one logger, [is set to None by default](https://github.com/PyTorchLightning/pytorch-lightning/blob/28afc7a10d9f9c1160935fb5c81a1a8c0492b392/pytorch_lightning/loggers/base.py#L416), apparently deliberately. I'm not sure what the rationale behind that decision was, so I'm hesitant to make a PR myself, but it seems logical to me that `LoggerCollection` should have a `log_path` property defined analogously to [that of a `TensorBoardLogger`](https://github.com/PyTorchLightning/pytorch-lightning/blob/28afc7a10d9f9c1160935fb5c81a1a8c0492b392/pytorch_lightning/loggers/tensorboard.py#L119), and that the property of the `Trainer` shouldn't fall back to the `save_dir` property automatically when its logger isn't an instance of `TensorBoardLogger`.

## Reproduction

[Here's a BoringModel Colab link](https://colab.research.google.com/drive/1qt2wedM_CahAphWwJTjTk3W-3vlpLJjO?usp=sharing). The following warning is generated during training when the `Trainer`'s logger is wrapped in a list:

```
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/profiler/pytorch.py:441: UserWarning: The PyTorchProfiler failed to export trace as `dirpath` is None
  rank_zero_warn("The PyTorchProfiler failed to export trace as `dirpath` is None")
```

### Expected behavior

The PyTorch profiler should always have access to a default logging path, even when the `Trainer`'s logger is a `LoggerCollection`. Ideally, it would follow the same "version" convention obeyed when the logger is a `TensorBoardLogger`.

### Environment

```
* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.2
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.0+cu102
	- pytorch-lightning: 1.3.7post0
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
	- processor:         x86_64
	- python:            3.7.10
	- version:           #1 SMP Sat Jun 5 09:50:34 PDT 2021
```

**Comment by tchaton** [comment]
Dear @gahdritz,

Thanks for reporting this issue. Would you be interested in making a fix PR to Lightning ? 
I believe it shouldn't be too hard and a good way to learn more :) 

Best,
T.C

**Comment by gahdritz** [comment]
Yeah I can take a crack at it

**Comment by gahdritz** [comment]
@tchaton the PR is done. Let me know if you think it adequately addresses this issue.
