### ISSUE TITLE
Cannot log gpu memory without making on step = True while logging train loss

### ISSUE THREAD

**Issue by karthi0804** [PyTorchLightning/pytorch-lightning#8159]
### Discussed in https://github.com/PyTorchLightning/pytorch-lightning/discussions/7582

<div type='discussions-op-text'>

<sup>Originally posted by **karthi0804** May 18, 2021</sup>
I am using 1.3.0 version. I wanted to just log the gpu memory at all time steps. So I enabled ```log_gpu_memory='all'``` and ```log_every_n_steps=1```. I couldn't find the gpu logging for steps. But If I log the train loss on steps, I can see the gpu logging at each steps. Is this how it is intended to work? I expect that gpu logging should be independent of self.log(). </div>

**Comment by tchaton** [comment]
Dear @karthi0804,

Thanks for reporting this bug. Would you mind providing a reproducible script using the BoringModel ?

Best,
T.C

**Comment by karthi0804** [comment]
@tchaton thanks for fixing it! hopefully I will contribute next time.
