### ISSUE TITLE
Add deepspeed support

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#817]
Let's support this!

https://github.com/microsoft/DeepSpeed

**Comment by sudarshan85** [comment]
Forgive me if I'm wrong, but doesn't Lightning already provide many functions supported by DeepSpeed? Also, going by a cursory reading of DeepSpeed, isn't it just another wrapper for Pytorch? Or am I wrong?

**Comment by williamFalcon** [comment]
i haven’t had a chance to read in depth but this is likely a library that operates on top of models which means lightning can use it

**Comment by xingzhaolee** [comment]
I think it's something like Lightning with more features based on the CIFAR example. One way is to make Lightning dependent on DeepSpeed for training related stuffs while Lightning focuses on reproducibility.

**Comment by williamFalcon** [comment]
It's not like lightning at all lol. It's more like apex... or distributed.

To add support in lightning we need to create a flag and follow the readme instructions:

https://github.com/microsoft/DeepSpeed

Addition A:
```
model_engine, optimizer, _, _ = deepspeed.initialize(args=cmd_args,
                                                     model=model,
                                                     model_parameters=params)
```

Addition B:
```
for step, batch in enumerate(data_loader):
    #forward() method
    loss = model_engine(batch)

    #runs backpropagation
    model_engine.backward(loss)

    #weight update
    model_engine.step()
```

@neggert @jeffling anyone want to take this?

**Comment by williamFalcon** [comment]
@jeffra, @ShadenSmith, @samyam, anyone interested in adding this to lightning? :)

**Comment by xingzhaolee** [comment]
@williamFalcon okay my bad I didn't read through it properly. Btw, I think the Training Optimizers, Advanced Parameter Search and Simplified Data Loader seems like good features to be included into Lightning if DeepSpeed backend is used. Or is it better for user to manually call it using the DeepSpeed library?

**Comment by williamFalcon** [comment]
@xingzhaolee these are all features we should automatically allow when someone uses the deepspeed backend.

**Comment by jeffra** [comment]
@williamFalcon Thanks for reaching out to us, this could be great. We are having internal discussions about how to proceed and will get back to you soon. We're also in the process of learning more about Lightning, it looks like great work you all have done :)

**Comment by zbloss** [comment]
Hi team, this would be a huge addition to lightning!

The biggest barrier to entry for deepspeed is having to refactor all of my code, and the biggest attractor to lightning is the organization and simplicity it provides

**Comment by edenlightning** [comment]
https://github.com/pytorch/pytorch/issues/42849

**Comment by javismiles** [comment]
what´s the latest on this? will deepspeed be integrated in lightning at some point soon? thank you :)

**Comment by williamFalcon** [comment]
yup! we're actively working on this. Expect a v1 of it in the next few weeks via an rc. (cc @SeanNaren )

**Comment by SeanNaren** [comment]
DeepSpeed is made up of many components as @williamFalcon said above, but I think we're only after a few pieces here. ZERO optimization is the key piece here and the code can be seen here: https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/zero/stage2.py

Stage 1 and 2 have been released for ZERO optimization, and for reference (from paper [here](https://arxiv.org/pdf/1910.02054.pdf)):

```
1) Optimizer State Partitioning (Pos): 4x memory reduction, same communication volume
as DP;
2) Add Gradient Partitioning (Pos+g): 8x memory reduction, same communication volume
as DP;
3) Add Parameter Partitioning (Pos+g+p): Memory reduction is linear with DP degree Nd.
For example, splitting across 64 GPUs (Nd = 64) will yield a 64x memory reduction. There is
a modest 50% increase in communication volume
```

It's called an optimizer but it's a bit more involved. The goal API is to create an accelerator that encompasses this functionality, something like below:

```
model = MegatronLM() # too_big_for_single_gpu_training

Trainer(
	accelerator=‘ddp’,
	num_gpus=2
)
trainer.fit(model) # Crashes because of CUDA out of memory

Trainer(
	accelerator=‘deepspeed’,
	num_gpus=2
)

trainer.fit(model) # Actually trains!
```

I'm currently stepping through the optimizer and separating it from the fp16 components to play nice with native amp. If anyone is interested message me or comment! Happy to collab :)

**Comment by javismiles** [comment]
sounds great! looking forward to the v1 ;)

> yup! we're actively working on this. Expect a v1 of it in the next few weeks via an rc. (cc @SeanNaren )

**Comment by blefaudeux** [comment]
> DeepSpeed is made up of many components as @williamFalcon said above, but I think we're only after a few pieces here. ZERO optimization is the key piece here and the code can be seen here: https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/zero/stage2.py
> 
> Stage 1 and 2 have been released for ZERO optimization, and for reference (from paper [here](https://arxiv.org/pdf/1910.02054.pdf)):
> 
> ```
> 1) Optimizer State Partitioning (Pos): 4x memory reduction, same communication volume
> as DP;
> 2) Add Gradient Partitioning (Pos+g): 8x memory reduction, same communication volume
> as DP;
> 3) Add Parameter Partitioning (Pos+g+p): Memory reduction is linear with DP degree Nd.
> For example, splitting across 64 GPUs (Nd = 64) will yield a 64x memory reduction. There is
> a modest 50% increase in communication volume
> ```
> 
> It's called an optimizer but it's a bit more involved. The goal API is to create an accelerator that encompasses this functionality, something like below:
> 
> ```
> model = MegatronLM() # too_big_for_single_gpu_training
> 
> Trainer(
> 	accelerator=‘ddp’,
> 	num_gpus=2
> )
> trainer.fit(model) # Crashes because of CUDA out of memory
> 
> Trainer(
> 	accelerator=‘deepspeed’,
> 	num_gpus=2
> )
> 
> trainer.fit(model) # Actually trains!
> ```
> 
> I'm currently stepping through the optimizer and separating it from the fp16 components to play nice with native amp. If anyone is interested message me or comment! Happy to collab :)

FYI we have an implementation of the optimizer side in https://github.com/facebookresearch/fairscale/blob/master/fairscale/optim/oss.py, compatible with standard pytorch (ie. same param groups for instance, so that schedulers don't see a change). The issue with any implementation is that to get the full benefits you need to change the way the DP engine works though, that's true of 1) and 2) above. If you keep the normal pytorch DDP then the gradients are all-reduced and you waste some traffic. cc @ananthsub

**Comment by SeanNaren** [comment]
thanks @blefaudeux! That's a clean implementation :) have you seen a large performance degradation using the fairscale + ddp implementation?

**Comment by williamFalcon** [comment]
we could drop the v1 to use the non optimized version first? then quickly move to a v2 where we modify the ddp stuff as well?

we already have lightningddp which modifies the original ddp a bit.

**Comment by blefaudeux** [comment]
> thanks @blefaudeux! That's a clean implementation :) have you seen a large performance degradation using the fairscale + ddp implementation?

(with the standard DDP, using the linked optimizer as a drop-in "replacement" -more, wrap- to a normal optimizer) couple of percents if multi node, but that would depend on the interconnect. intra node it's actually faster on top of saving memory.

Now with more custom DDP like what deepspeed is doing there's a lot of potential in terms of speed and memory, but it's a little more compllicated to integrate, working on it. I can mention https://github.com/pytorch/pytorch/issues/42849 and https://github.com/pytorch/pytorch/issues/37002 here, ideally it would be nice to be able to customize the communication patterns without duplicating/forking

**Comment by SeanNaren** [comment]
I assume the memory saving is pretty much the same? I think that's definitely key, so as @williamFalcon said we could start from there!

**Comment by blefaudeux** [comment]
> I assume the memory saving is pretty much the same? I think that's definitely key, so as @williamFalcon said we could start from there!

You can save a bit more if you own the communications, because you can release the gradients as soon as they have been reduced to the appropriate rank, that's 2) basically. So 1) is drop-in, you can get a 1.5 of sorts by releasing all the now-useless gradients at the beginning of the sharded optimizer step (that's what the fairscale implementation above does), and 2) is when you drop the gradients as soon as possible. [example](https://app.circleci.com/pipelines/github/facebookresearch/fairscale/624/workflows/a237a38a-193c-4efb-b6f6-6be89d52bd98/jobs/2369/parallel-runs/0/steps/0-110), toy problem training a RN101 on 4 gpus, first is DDP, second is OSS+DDP, third is OSS+custom DDP

**Comment by SeanNaren** [comment]
Thanks @blefaudeux! We'll get the fairscale OSS integrated into a new accelerator, then look towards DDP changes to reduce the overhead further. Out of curiosity has there been any progress integrating gradient/parameter partitioning?

**Comment by blefaudeux** [comment]
> Thanks @blefaudeux! 
of course !

> We'll get the fairscale OSS integrated into a new accelerator, then look towards DDP changes to reduce the overhead further.

 You might need to sync with Ananth (@ananthsub), within FB there's already a lightning/fairscale integration running, could be worth it unifying the efforts ?

> Out of curiosity has there been any progress integrating gradient/parameter partitioning?


I've an experimental branch which gives [these results](https://app.circleci.com/pipelines/github/facebookresearch/fairscale/610/workflows/590b7b39-a97e-439f-8c72-aa4ffdd10ed9/jobs/2310/parallel-runs/0/steps/0-110) currently (last chunk. 'OSS experimental'), following the ideas presented in [this RFC](https://github.com/pytorch/pytorch/issues/42849) (split the model in chunks, use autograd hooks to load/drop the parameters on the fly while keeping reasonably close to pytorch, each rank owns the optimization for one chunk only), very much WIP though. The savings depend a lot on the model size and optimizer, and with this test problem the activations dominate actually so it's not the most impressive usecase (still useful).

**Comment by SeanNaren** [comment]
Just an update if anyone is tracking this, we technically haven't gotten 'DeepSpeed' support but that's primarily a design choice as the upstream API can be improved to not detriment user experience.

What this means is currently FairScale which has [been integrated into lightning some time](https://pytorch-lightning.readthedocs.io/en/latest/multi_gpu.html#sharded-training) provides most of the features whilst being accessible to all lightning modules in different domains, and I highly suggest looking at our sharded training as a replacement. There are some exciting improvements coming up as well to continue the memory/speed efficiency in FairScale and from other integrations :)

**Comment by Spenhouet** [comment]
Is there also going to be support for ZeRO-Offload?

https://www.deepspeed.ai/tutorials/zero-offload/

Or does this also depend on FairScale implementing it? In case, I created a feature request here: https://github.com/facebookresearch/fairscale/issues/337

**Comment by SeanNaren** [comment]
An update here! DeepSpeed finally has been integrated as a plugin into Lightning, see our docs [here](https://pytorch-lightning.readthedocs.io/en/latest/advanced/multi_gpu.html#deepspeed). We've worked hard to make the API flexible whilst reducing friction as much as possible. 

If you see run into any problems please leave an issue or message us on our PyTorch Lightning slack channel!

> Is there also going to be support for ZeRO-Offload?

There already is, and it's [the staple feature](https://pytorch-lightning.readthedocs.io/en/latest/advanced/multi_gpu.html#zero-offload) with presets out the box, so you don't need to modify your code to use it (for most cases), we also give instructions to tune to reasonable parameters.

Currently the plugin is available from PyTorch Lightning master, but we'll be releasing 1.2 soon with the feature with technical details and benchmarks soon to come.

I'd once again like to suggest that users first check out [Sharded Training](https://pytorch-lightning.readthedocs.io/en/latest/advanced/multi_gpu.html#sharded-training) as this works out the box for more use cases and has complete Lightning Support, where we are still ironing out kinks with DeepSpeed. FairScale will be introducing some exciting features like ZeRO-offload whilst being PyTorch-compliable so keep an eye :)

**Comment by williamFalcon** [comment]
![waaa](https://media.tenor.com/images/f4c8059e75d21aa301174d4374ec4680/tenor.gif)

**Comment by jeffra** [comment]
> An update here! DeepSpeed finally has been integrated as a plugin into Lightning, see our docs [here](https://pytorch-lightning.readthedocs.io/en/latest/advanced/multi_gpu.html#deepspeed). We've worked hard to make the API flexible whilst reducing friction as much as possible.
> 
> If you see run into any problems please leave an issue or message us on our PyTorch Lightning slack channel!
> 
> > Is there also going to be support for ZeRO-Offload?
> 
> There already is, and it's [the staple feature](https://pytorch-lightning.readthedocs.io/en/latest/advanced/multi_gpu.html#zero-offload) with presets out the box, so you don't need to modify your code to use it (for most cases), we also give instructions to tune to reasonable parameters.
> 
> Currently the plugin is available from PyTorch Lightning master, but we'll be releasing 1.2 soon with the feature with technical details and benchmarks soon to come.
> 
> I'd once again like to suggest that users first check out [Sharded Training](https://pytorch-lightning.readthedocs.io/en/latest/advanced/multi_gpu.html#sharded-training) as this works out the box for more use cases and has complete Lightning Support, where we are still ironing out kinks with DeepSpeed. FairScale will be introducing some exciting features like ZeRO-offload whilst being PyTorch-compliable so keep an eye :)

This is super exciting!! :) thanks for your contributions to DeepSpeed and all your work getting DeepSpeed integrated into lightning! I think we have a chat coming up soon, we would love to hear more about any kinks you discovered with DeepSpeed and how we can iron those out together. Also especially curious on details regarding PyTorch incompatibilities with DeepSpeed?

**Comment by SeanNaren** [comment]
So epic to see you here @jeffra you and your team has done amazing work, I can't wait to see what you guys come up with, and hope we can assist in your work! Thank you for your kind words but it's really your team that did all the work :)

I'll be hopefully pushing a few PRs to DeepSpeed/Lightning to ease integration (a lot of the issues are kinks we need to iron out on our end in PyTorch Lightning). These range from small issues like configuration of the throughput timer, to more involved changes like multi-optimizer/multi-scheduler support or allowing lightning to control Apex/AMP settings outside of DeepSpeed. 

I'll be tracking these via issues so we can iterate on them and make the integration even better. I've been using DeepSpeed for a while now across a multitude of models and it's been an incredible experience with the level of customisability. I'm glad we're moving towards the community being able to fine-tune/train larger models!

**Comment by jeffra** [comment]
Thanks for the kind words @SeanNaren! :) Very much looking forward to a great collaboration going forward.
