### ISSUE TITLE
We should be able to output the PyTorchProfiler results to any data sink handlers.

### ISSUE THREAD

**Issue by camruta** [PyTorchLightning/pytorch-lightning#8185]
PyTorchProfiler currently uses torch.profiler.tensorboard_trace_handler to generate result files for TensorBoard.

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/profiler/pytorch.py#L429

It is probably useful to add support for other custom handler(s) user may want to use to output the results to different data sink. For example, many users would benefit from being able to see the results in commonly used analytics or visualization tools such as Grafana. Such user defined handlers can also customize the output in a way that makes the troubleshooting specific cases easier.

**Comment by carmocca** [comment]
Sounds fair.

Do you think the handler list should be an optional init argument of the class? Where we add the tensorboard handler automatically if necessary?

**Comment by camruta** [comment]
Yes, that's what I had in my mind. I'll send a draft for review.

**Comment by kaushikb11** [comment]
@camruta Awesome! Assigning you to the issue

**Comment by tchaton** [comment]
Dear @camruta,

Any updates ?

**Comment by camruta** [comment]
I had some trouble with my local dev setup, and wasn't able to add a test for the code changes in order to publish a PR. I'll create a task for Ananth with all the details and code snippets, who can take it further. I think he is also thinking about other enhancement opportunities with the profiler, so probably makes sense to re-think this with the rest of the planned changes.
