### ISSUE TITLE
Enable anchor links in docs

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#819]
Our docs don't have these links. We need to enable them.

![image](https://user-images.githubusercontent.com/3640001/74248339-71303e00-4cb5-11ea-8657-eb8f847bf1ed.png)

**Comment by Borda** [comment]
@luiscape may you have look at the JS in our template?
https://github.com/readthedocs/readthedocs.org/issues/6661#issuecomment-587140328

**Comment by luiscape** [comment]
@Borda See my response on that issue here: https://github.com/readthedocs/readthedocs.org/issues/6661#issuecomment-588030590

The problem is with the extension `nbsphinx`. I'm making a PR with a fix.
