### ISSUE TITLE
Display actual examples instead of links to the files in the new docs

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#821]
When I  click on examples I see a list of examples. Ideally, I see the actual example for each one when I click into it. See [Example page](https://pytorch-lightning.readthedocs.io/en/latest/examples.html)

**Comment by Borda** [comment]
there is probably build error because now the examples are missing completly, see e.g [GAN](https://pytorch-lightning.readthedocs.io/en/latest/pl_examples.domain_templates.gan.html)

**Comment by Dev-Akash** [comment]
Hi there, i am new to this, and want to contribute by solving this issue, but was not able to figure out how can i validate the changes i have made as after forking i can't see docs page hosted in respect to my forked repo. Can anyone help me with this ?

**Comment by Borda** [comment]
Great, you can make docs locally
```bash
cd docs 
pip install requirements.txt 
make html
```
And then check `dics/build/html/index.html`

**Comment by Dev-Akash** [comment]
@Borda thanks for the help, i will soon be sending a PR after applying changes successfully.
