### ISSUE TITLE
Implement Rich ProgressBar 

### ISSUE THREAD

**Issue by kaushikb11** [PyTorchLightning/pytorch-lightning#8255]
## 🚀 Feature

Rich ProgressBar Integration

> Rich is a Python library for rich text and beautiful formatting in the terminal.

Github: https://github.com/willmcgugan/rich
Related PR: https://github.com/PyTorchLightning/pytorch-lightning/pull/5500

**Comment by Borda** [comment]
@tchaton has this one https://github.com/PyTorchLightning/pytorch-lightning/tree/rich_logging

**Comment by karthikrangasai** [comment]
Is someone working on this issue ?

**Comment by kaushikb11** [comment]
@karthikrangasai Yup, will get started with it.

**Comment by karthikrangasai** [comment]
Oh okay.
