### ISSUE TITLE
CLI: instantiate return objects

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#8261]
## 🚀 Feature

while working with Tuner I found it quite useful to great multiple copies of the same model or data, so for I would extend and feel it is quite natures of all methods `instantiate_`

### Motivation

get more freedom to customize user scripts

### Alternatives

```py
    def instantiate_trainer(self, inplace: bool: True) -> Optional[Trainer]:
        ...
        if inplace:
            self.trainer = trainer
        else:
            return trainer
```

**Comment by tchaton** [comment]
Hey @Borda,

Mind giving more context where you found this to be useful ?

Best,
T.C
