### ISSUE TITLE
LightningCLI does not accept DDPPlugin as trainer argument

### ISSUE THREAD

**Issue by tasptz** [PyTorchLightning/pytorch-lightning#8262]
## 🐛 Bug

LightningCLI does not accept DDPPlugin as trainer argument

Code:
```python
from pytorch_lightning.utilities.cli import LightningCLI
from pytorch_lightning import LightningModule, LightningDataModule
from pytorch_lightning.plugins import DDPPlugin
cli = LightningCLI(
    LightningModule,
    LightningDataModule,
    subclass_mode_model=True,
    subclass_mode_data=True,
    trainer_defaults={'plugins': [DDPPlugin(find_unused_parameters=False)]}
    #trainer_defaults={'plugins': DDPPlugin(find_unused_parameters=False)}
)
```

Error:
```
trainer.py: error: Configuration check failed :: Parser key "trainer.plugins": Value "[<pytorch_lightning.plugins.training_type.ddp.DDPPlugin object at 0x7fbf0fef3dc0>]" does not validate against any of the types in typing.Union[typing.List[typing.Union[pytorch_lightning.plugins.base_plugin.Plugin, pytorch_lightning.plugins.environments.cluster_environment.ClusterEnvironment, str]], pytorch_lightning.plugins.base_plugin.Plugin, pytorch_lightning.plugins.environments.cluster_environment.ClusterEnvironment, str, NoneType]:
  - Value "<pytorch_lightning.plugins.training_type.ddp.DDPPlugin object at 0x7fbf0fef3dc0>" does not validate against any of the types in typing.Union[pytorch_lightning.plugins.base_plugin.Plugin, pytorch_lightning.plugins.environments.cluster_environment.ClusterEnvironment, str]:
    - Expected an str or a Dict with a class_path entry but got "<pytorch_lightning.plugins.training_type.ddp.DDPPlugin object at 0x7fbf0fef3dc0>"
    - Expected an str or a Dict with a class_path entry but got "<pytorch_lightning.plugins.training_type.ddp.DDPPlugin object at 0x7fbf0fef3dc0>"
    - Expected a <class 'str'> but got "<pytorch_lightning.plugins.training_type.ddp.DDPPlugin object at 0x7fbf0fef3dc0>"
  - Expected an str or a Dict with a class_path entry but got "[<pytorch_lightning.plugins.training_type.ddp.DDPPlugin object at 0x7fbf0fef3dc0>]"
  - Expected an str or a Dict with a class_path entry but got "[<pytorch_lightning.plugins.training_type.ddp.DDPPlugin object at 0x7fbf0fef3dc0>]"
  - Expected a <class 'str'> but got "[<pytorch_lightning.plugins.training_type.ddp.DDPPlugin object at 0x7fbf0fef3dc0>]"
  - Expected a <class 'NoneType'> but got "[<pytorch_lightning.plugins.training_type.ddp.DDPPlugin object at 0x7fbf0fef3dc0>]"
```
## Expected

Accept the argument as described in
https://pytorch-lightning.readthedocs.io/en/stable/benchmarking/performance.html#when-using-ddp-set-find-unused-parameters-false

## Colab example

https://colab.research.google.com/drive/1MuOcvfWoujaU76jvtU85Y6jXSRnLLyHF?usp=sharing

### Environment

* CUDA:
	- GPU:
		- NVIDIA GeForce GTX 970
	- available:         True
	- version:           11.3
* Packages:
	- numpy:             1.20.2
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.1
	- pytorch-lightning: 1.3.8
	- tqdm:              4.61.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.8.10
	- version:           `#66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021`

**Comment by mauvilsa** [comment]
With the version of jsonargparse being released today I think this will not fail anymore. However, looking at this I am thinking that there is something that we might want to change related to plugins. Currently `callbacks` has the behavior that when added using `trainer_defaults` they will be persistent. This means if someone provides more plugins in a config file, these are concatenated to the ones defined in `trainer_defaults`. Also a callback can be added to be persistent but configurable. Should the behavior for plugins be the same?

**Comment by carmocca** [comment]
> Should the behavior for plugins be the same?

Yes, although multiple plugins is much more of a niche usecase

**Comment by tchaton** [comment]
Yes, only 1 plugin from each type is supported.

**Comment by tchaton** [comment]
Dear @tasptz,

From trying with the latest version from `jsonargparse` ?

Best,
T.C

**Comment by mauvilsa** [comment]
The code snippet in the description does work with the new version of jsonargparse. I only tested `--help` and `--print_config`.

> Yes, although multiple plugins is much more of a niche usecase

Even though it is a niche use case I think it might be good to be the same as the callbacks. Right now if you do `--print_config` the yaml includes:

```yaml
  plugins:
  - <pytorch_lightning.plugins.training_type.ddp.DDPPlugin object at 0x7fe185f6e630>
```

Which is not a valid value for the config. If it is like the callbacks then the object instance wouldn't appear.
