### ISSUE TITLE
Load model from previous git commit

### ISSUE THREAD

**Issue by nicolas-dufour** [PyTorchLightning/pytorch-lightning#8268]
## 🚀 Feature

Being able to load a model from a given git commit.

### Motivation

The idea is to been able to load a model even if the codebase of the model have evolved since we trained that model. This would allow for better retrocompatibility in a developement phase and allow to think of the model more freely without having in mind compatibility issues

### Pitch

The idea is that when calling MyLightingModule.load_from_checkpoint, on can give a specific git commit id so that the model is loaded according to the code base at the time when the model was trained.

**Comment by carmocca** [comment]
So you are proposing that the `checkpoint` saved includes the commit hash of your model code?

We cannot know this inside Lightning, however, you could add this information yourself to the checkpoint for future reproducibility.

Keep in mind that when you call `MyLightingModule.load_from_checkpoint(ckpt)`, you are doing it for a specific `MyLightingModule` code, so it would require to reload the entire source tree dynamically and reload/restart the python process so the expected code is used.

So yeah, not sure if this is even technically possible. Closing for now, but feel free to elaborate on the proposal

**Comment by nicolas-dufour** [comment]
My idea is not necessarily linked to git, mainly, for me the problem is the code dependence when loading models. Isn't it possible to load models in a code independent way (Some kind of pickling). I'm not at all sure it's doable, just wanted to share a feature that i think would make my workflow much easier.
