### ISSUE TITLE
TPU example from https://pytorch-lightning.readthedocs.io/en/stable/advanced/tpu.html not working

### ISSUE THREAD

**Issue by Abhishek-Prajapat** [PyTorchLightning/pytorch-lightning#8270]
## Please reproduce using this notebook

https://colab.research.google.com/drive/1JaRZK6PsqOtyMINeng_EwD7KlHxxL-Ft?usp=sharing

### Expected behavior

The Import of pl should have been successful.

### Environment

Cause of the above-mentioned error I can't execute the environment script.

**Comment by kaushikb11** [comment]
@Abhishek-Prajapat I ran the cells in your linked notebook. It worked! Give it a try again!

**Comment by Abhishek-Prajapat** [comment]
I think there was some issue with the PyTorch version. I upgraded the PyTorch version and now it's working.

**Comment by Abhishek-Prajapat** [comment]
The issue occurred again and after some digging, I found this thread - https://github.com/pytorch/xla/issues/2259. It looks like both the torch and torch_xla should be of same version.
