### ISSUE TITLE
false positives with `is_overridden` on DataModule hooks

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#8273]
### To Reproduce

```python
from pytorch_lightning import LightningDataModule
from pytorch_lightning.utilities.model_helpers import is_overridden


class BoringDataModule(LightningDataModule):

    def __init__(self):
        super().__init__()
        print("I'm not overriding setup, has_prepared_data!")

assert not is_overridden('setup', instance=BoringDataModule(), parent=LightningDataModule)
assert not is_overridden('prepare_data', instance=BoringDataModule(), parent=LightningDataModule)
```

The call to `is_overridden` for this hook is used in https://github.com/PyTorchLightning/pytorch-lightning/blob/8193bae6bde378e137ab07eb916a4cb515ecbace/pytorch_lightning/trainer/connectors/data_connector.py#L62

### Expected behavior

Assertion holds true.

### Additional context

It is also the case in 1.3.x.

**Comment by SkafteNicki** [comment]
Probably due to the wrapping going on here:
https://github.com/PyTorchLightning/pytorch-lightning/blob/dd340a659818def94468f11aa4fed492e27f3e92/pytorch_lightning/core/datamodule.py#L381-L387

**Comment by awaelchli** [comment]
@SkafteNicki thanks for investigating this. Carlos found the fix for it.

**Comment by tchaton** [comment]
Great catch !
