### ISSUE TITLE
Managing Checkpoints

### ISSUE THREAD

**Issue by srush** [PyTorchLightning/pytorch-lightning#828]
## 🚀 Feature

During training there is support for checkpointing multiple variants of the model. However to utilize these checkpoints you need to parse the file names to get out information. It would be nice if lightning either wrote out statistics to make it easy to find the right model, or even better allowed you to load based on validation statistics. 

```
load_from_checkpoint(ckpt, metric=‘f-score’, mode=‘max’)
```

**Comment by Borda** [comment]
sounds interesting, @srush would you be interested in submitting such PR?

**Comment by Borda** [comment]
Well, I would maybe rather add a method that would return a path to such checkpoint and then you can load it on your own...
```
find_checkpoint(folder, metric=‘f-score’, mode=‘max’)
```
cc: @PyTorchLightning/core-contributors thoughts?
