### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by phammanhhiep** [PyTorchLightning/pytorch-lightning#8281]
## 🐛 Bug

I got the error `RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn` when having 2 optimizers (to train a GAN model), and also set option `accumulate_grad_batches` with value greater than 1 in [trainer](https://github.com/PyTorchLightning/pytorch-lightning/blob/d856989120b078581f3f694fd7a1c036703f67a9/pytorch_lightning/trainer/trainer.py). The loss, returned from method LightningModule.traininng_step and corresponding to the second optimizer, has requires_grad as False, which results to the error. 

Similar fixed bug is [5574](https://github.com/PyTorchLightning/pytorch-lightning/pull/5574), though it does not handle the case when option `accumulate_grad_batches`  with value greater than 1 is used. 

### To Reproduce

Use following [**BoringModel**](https://colab.research.google.com/drive/1nag9KMawRfWaBAmqZ1TKiaRhxrYUUFNh#scrollTo=Flyi--SpvsJN) 

### Environment
PyTorch Lightning Version 1.3.7

**Comment by bmahlbrand** [comment]
I know this is closed, but I just pulled master, and tried testing w/3 optimizers instead of 2 (this problem is fixed when I only have 2) and the issue persists. How can I help?
