### ISSUE TITLE
`overfit_pct` vs `train_percent_check` etc

### ISSUE THREAD

**Issue by ghost** [PyTorchLightning/pytorch-lightning#830]
As far as I can make out, the (only?) purpose of  `overfit_pct` is to overwrite the values of `train_percent_check`, `val_percent_check`, and `test_percent_check`. If that is the case, then I think we should 
- make  the names more similar (e.g. `data_percent_check`)
- move the positions of the arguments closer together (so that it suggests a relation)
- update the docs to reflect that (I found the docs confusing)

Also, the default value should not be `0.0` but `None`.

Another option would be to drop it completely for the sake of simplification. Not sure.

**Comment by williamFalcon** [comment]
@ghost want to submit a PR?
