### ISSUE TITLE
Multi-Node DDP Freezing Before Training

### ISSUE THREAD

**Issue by Zasder3** [PyTorchLightning/pytorch-lightning#8301]
## 🐛 Bug

When attempting to train a model on multiple nodes, the script successfully initializes DDP however it fails to actually train the models.

## To Reproduce

File: https://gist.github.com/Zasder3/6b36a0529c5a20c50570006441082d19 The file contains the notebook compiled into a single python file with changes made to the trainer:
```python
trainer = pl.Trainer(
        max_epochs=1, 
        progress_bar_refresh_rate=20,
        accelerator='ddp',
        gpus=8,
        num_nodes=2
    )
```
To run simply prepare 2 nodes with the following commands:
```bash
$ export MASTER_PORT=8080
$ export MASTER_ADDR=INTERNAL IP
$ export WORLD_SIZE=2
$ export NODE_RANK=[0, 1] # pick based on node
$ export PL_TORCH_DISTRIBUTED_BACKEND=gloo # optional and has identical function with and without
```

### Expected behavior

One would expect training to occur, however it only initializes DDP and dies on the spot.

### Environment

* CUDA:
	- GPU:
		- GeForce RTX 2080 Ti
		- GeForce RTX 2080 Ti
		- GeForce RTX 2080 Ti
		- GeForce RTX 2080 Ti
		- GeForce RTX 2080 Ti
		- GeForce RTX 2080 Ti
		- GeForce RTX 2080 Ti
		- GeForce RTX 2080 Ti
	- available:         True
	- version:           10.2
* Packages:
	- numpy:             1.20.2
	- pyTorch_debug:     False
	- pyTorch_version:   1.7.1
	- pytorch-lightning: 1.3.8
	- tqdm:              4.60.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.8.5
	- version:           # 51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021

**Comment by tchaton** [comment]
Dear @Zasder3,

From first glance, it seems the environment variable are wrong.

```
$ export MASTER_PORT=8080
$ export MASTER_ADDR=INTERNAL IP
$ export WORLD_SIZE=16 # 2 nodes * 8 gpus each
$ export NODE_RANK=0 or 1 # based on which node you run it.
$ export PL_TORCH_DISTRIBUTED_BACKEND=gloo # optional and has identical function with and without
```

# on node 0
```
MASTER_PORT=... MASTER_ADDR=... WORLD_SIZE=16 NODE_RANK=0 PL_TORCH_DISTRIBUTED_BACKEND=gloo python script.py
```

# on node 1
```
MASTER_PORT=... MASTER_ADDR=... WORLD_SIZE=16 NODE_RANK=1 PL_TORCH_DISTRIBUTED_BACKEND=gloo python script.py
```

Mind trying this ?

**Comment by awaelchli** [comment]
yep, looks like the world size was incorrectly set :)

**Comment by Zasder3** [comment]
Updated the script to `export WORLD_SIZE=16` but I still find that the error persists.

**Comment by tchaton** [comment]
Hey @Zasder3,

Would you be open to a pair debugging session on your machine ? 

Best,
T.C

**Comment by Zasder3** [comment]
Sure thing! I'd be available tomorrow morning (CST) if that works for you too?

**Comment by Zasder3** [comment]
Updating to the master version (`https://github.com/PyTorchLightning/pytorch-lightning/archive/refs/heads/master.zip`) fixed the error! Everything now runs smoothly.
