### ISSUE TITLE
init logger with version/experiment_name based on hparams

### ISSUE THREAD

**Issue by tshu-w** [PyTorchLightning/pytorch-lightning#8309]
I'm using LightningCLI, however, I could not find a convinced way to init logger with version/experiment_name based on hparams, which make my log folder more readable:
<img width="1075" alt="Screen Shot 2021-07-06 at 20 53 27" src="https://user-images.githubusercontent.com/13161779/124603362-7094da80-de9c-11eb-9fd4-483013da2d3b.png">

**Comment by justusschock** [comment]
cc @carmocca @mauvilsa Is there an option for this?

**Comment by tshu-w** [comment]
I think I can customize CLI's fun
 before_instance_class to init my logger, sorry for bothering.
