### ISSUE TITLE
GPU Memory leak using BCELoss while logging the training loss

### ISSUE THREAD

**Issue by Nora-Go** [PyTorchLightning/pytorch-lightning#8325]
Hi :)
first of all thanks for your great work!

## 🐛 Bug

At the moment I'm facing a weird bug:
I have a binary segmentation task and want to use the BCELoss (https://pytorch.org/docs/stable/generated/torch.nn.BCELoss.html) (in my real code I do some computations before (not just a simple sigmoid/ clamp) such that the input is already in [0, 1]).
However, I run into a "RuntimeError: CUDA out of memory."
As I noticed that comes from a GPU memory leak.
When I use BCEWithLogitsLoss (https://pytorch.org/docs/stable/generated/torch.nn.BCEWithLogitsLoss.html) everything runs smoothly.
I wouldn't be asking here if it did not have to do something with Lightning. So the intriguing part is, when I comment out self.log('train_loss', loss) in the train_step also the model using BCELoss runs smoothly (however only in the minimal example... in my own code it does not seem to be that easy :/).
So I wonder what is going on and if you can help me (as I want to use the BCELoss and log the loss).

## Please reproduce using the BoringModel
You can find my minimal example attached together with some example images.
Please first run the make_dummy_dataset_binary_seg script and then the train script.
My model is very close to  your BoringModel, I just needed to adapt it a little (let me know if it is not good as is) and it needs to run a full epoch to reproduce the error (for me the error comes at the middle of the epoch).

### To Reproduce

[MinimalExample.zip](https://github.com/PyTorchLightning/pytorch-lightning/files/6777219/MinimalExample.zip)

### Expected behavior

You will hopefully be able to reproduce the "RuntimeError: CUDA out of memory." error during some part of the first epoch.
I would ideally like to run the first epoch without any errors :)

### Environment

* CUDA:
	- GPU:
		- GeForce RTX 2080 Ti
	- available:         True
	- version:           11.0
* Packages:
	- numpy:             1.20.2
	- pyTorch_debug:     False
	- pyTorch_version:   1.7.1+cu110
	- pytorch-lightning: 1.3.8
	- tqdm:              4.60.0
* System:
	- OS:                Windows
	- architecture:
		- 64bit
		- WindowsPE
	- processor:         Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
	- python:            3.8.0
	- version:           10.0.18362

Thank you very much!

Best,
Nora

**Comment by carmocca** [comment]
Hi! Can you try using master? Logging has been re-designed so it is possible that it's not an issue anymore if it's really due to the `self.log` call

**Comment by Nora-Go** [comment]
Hi :) so you mean updating to 1.3.8? This does unfortunately not help :/

**Comment by carmocca** [comment]
Hi @Nora-Go 

The fastest way for us to be able to help you is if you can adapt [this script](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py) to reproduce the behaviour you are seeing.

You don't need to provide the actual data you are using, you can simply create some tensors of the appropriate shapes filled with random data.

Also, you don't need to wait until a CUDA OOM. As long as you can reproduce that the memory grows without bounds, then that's good enough for us to take a look!

Thank you for your patience.

**Comment by Nora-Go** [comment]
Hi @carmocca

Thank you for your answer, and sorry my first try at a minimal example was not good.
So here the second try using your script and with a random dataset - I am still able to reproduce the error.
[bug_report_model.zip](https://github.com/PyTorchLightning/pytorch-lightning/files/6954895/bug_report_model.zip)

All the best,
Nora
