### ISSUE TITLE
Recommender system domain example

### ISSUE THREAD

**Issue by jiwidi** [PyTorchLightning/pytorch-lightning#8335]
## 🚀 Feature
Pytorch Lightning usage example with recommender systems

### Motivation

I've been using PL for a while now and I think is a great framework to speed up DS work. When I began using it I read through the domain [examples](https://github.com/PyTorchLightning/pytorch-lightning/tree/master/pl_examples/domain_templates) and got inspiration on how to structure my code. My work has been mostly around recommender systems and I haven't seen many examples of PL in this domain. If I were to code one, would this be of value for you? If so, what requirements should it have? 
### Pitch

I want to create domain examples for recommenders systems that use PL. I have the only (to my knowledge) public PyTorch implementation of the BST [model](https://arxiv.org/pdf/1905.06874.pdf) from Alibaba in GitHub, and it uses PL. I could prepare this in a higher code quality standard, or prepare some other model examples that use PL. 

I think a worthy domain example for PL should have a simple dataset and focus on the usage of PL on recommender systems, the BST models have quite some preprocess needed on movie lens dataset required.  The Netflix dataset is also worth checking out and some RNN architectures work good with it.

I want to start a discussion if this is something of interest for the PL team and if so I could bring more examples of models that could be use as domain example.

**Comment by tchaton** [comment]
Dear

**Comment by tchaton** [comment]
Hey @jiwidi,

Any updates on your side ?

Best,
T.C

**Comment by jiwidi** [comment]
Hi @tchaton,

I was actually waiting for some of those updates to see if I could include them in the tutorial and have a more updated version on how to use PL for recommender systems. Do you know the status of those?

**Comment by tchaton** [comment]
Hey @jiwidi,

Yes, all good ! You can definitely make a PR on Lightning Tutorials. 

Here is an example: https://github.com/PyTorchLightning/lightning-tutorials/tree/main/course_UvA-DL/deep-autoencoders
Here is a template: https://github.com/PyTorchLightning/lightning-tutorials/tree/main/sample-template

This is definitely something we really want within the tutorials :) 

Best,
T.C

**Comment by tchaton** [comment]
Dear @jiwidi,

Any updates on this ticket ?

Best,
T.C

**Comment by jiwidi** [comment]
Hi @tchaton sorry for the late answer.

I have an initial version of the tutorial at https://github.com/jiwidi/lightning-tutorials/blob/main/lightning_examples/movielens-behavior-sequence-transformer/bst.py

I based myself on the other examples. Care to give it a look and tell me what you think of it? Can open the PR if needed.
