### ISSUE TITLE
Demo Notebook Error:

### ISSUE THREAD

**Issue by ucalyptus** [PyTorchLightning/pytorch-lightning#834]
## 🐛 Bug
`trainer.fit(gan_model)
`
`ValueError: Your LightningModule defines 2 optimizers but training_step is missing the "optimizer_idx" argument.`

### To Reproduce

1. Go to [this link](https://colab.research.google.com/drive/1r884gr5Wn44kY9VTeo1DfPkaXXn7UXwk#scrollTo=h788dCGu7_Iu&line=3&uniqifier=1).
2. Run the cell
3. Scroll down .

 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

### Additional context
This is the exact demo notebook.

**Comment by Borda** [comment]
@ucalyptus could you pls make the notebook public? We do not have permission to see it...

**Comment by ucalyptus** [comment]
@Borda done

**Comment by Borda** [comment]
well it seems that the demo is using all API

**Comment by oggyfaker** [comment]
> @Borda done

hi can you share the public jupyter notebook . I cant see it
