### ISSUE TITLE
Load ckpt_path when given to test/validate/predict

### ISSUE THREAD

**Issue by SeanNaren** [PyTorchLightning/pytorch-lightning#8347]
## 🚀 Feature
When the `ckpt_path` is passed to the `test/validation/predict` functions of the Trainer, they load the weights even if a model is provided.

### Motivation

I noticed that one of our DeepSpeed test was incorrect (see [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/tests/plugins/test_deepspeed_plugin.py#L597-L607)). `resume_from_checkpoint` does not re-load the weights for test/validate/predict, which is probably the right thing to do, however when modified to pass `ckpt_path` to the `test` function I noticed the weights are not loaded, which is default behaviour.

As described by @carmocca I suggested we change the behaviour as such:

### BEFORE
```
trainer.test(model, ckpt_path=None) # use provided model
trainer.test(model, ckpt_path='best') # use provided model, ignore ckpt_path
trainer.test(model, ckpt_path='my_path') # use provided model, ignore ckpt_path

trainer.fit(model)
# then
trainer.test(ckpt_path=None) # use latest model
trainer.test(ckpt_path='my_path') # load path
```

### AFTER

```
trainer.test(model, ckpt_path=None) # use provided model
trainer.test(model, ckpt_path='best') # load best model
trainer.test(model, ckpt_path='my_path') # load path

trainer.fit(model)
# then
trainer.test(ckpt_path=None) # load best model
trainer.test(ckpt_path='my_path') # load path
```

This imo makes the behaviour in line with what's expected + allows deepspeed to be used as an engine in the cases where inference cannot happen without the Trainer (when there is sharding orchestration etc).

**Comment by tchaton** [comment]
Sounds good to me !

**Comment by SeanNaren** [comment]
I've realised that (1) and (5) should be different behaviour, i.e

```
test(ckpt_path=None) # uses latest model connected to the trainer
test(ckpt_path='best') # uses the best ckpt weight 
```

The issue comes from if the default is now `ckpt_path=None` which will load the best ckpt weights, how would we load the latest model? This would require a different behaviour, which I don't think is currently prefered.

To simplify this issue, I think we should just stick to be simple; if the ckpt_path is not 'best' or None, we load the ckpt
