### ISSUE TITLE
Tensorboard logging should use `num_grad_updates` not `batch_idx`

### ISSUE THREAD

**Issue by ibeltagy** [PyTorchLightning/pytorch-lightning#835]
When `accumulate_grad_batches > 1`, the x-axis in tensorboard should be number of gradient updates, not number of batches that have been processed.

**Comment by timofeev1995** [comment]
Have the authors changed the logic in master branch? Now 1 tensorboard step == 1 optimizer step?
Thanks!

**Comment by ibeltagy** [comment]
AFAICT, this was fixed here https://github.com/PyTorchLightning/pytorch-lightning/pull/832
