### ISSUE TITLE
_pickle.PicklingError: Can't pickle <class 'TypeError'>: it's not the same object as builtins.TypeError

### ISSUE THREAD

**Issue by rastegah** [PyTorchLightning/pytorch-lightning#8351]
## 🐛 Bug

Encountering the following issue:
```
Traceback (most recent call last):
  File "/import/linux/python/3.8.2/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/import/linux/python/3.8.2/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'TypeError'>: it's not the same object as builtins.TypeError
Traceback (most recent call last):
  File "/import/linux/python/3.8.2/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/import/linux/python/3.8.2/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'TypeError'>: it's not the same object as builtins.TypeError
```

* This happens when using just 1 GPU without multi-gpu
* I have manually pickled my model, data loader and all modules and have fixed any issues

 - PyTorch Lightning Version 1.3.8
 - PyTorch Version 1.9
 - Python version: 3.8.2
 - OS: Linux
 - CUDA/cuDNN version: cuda/10.2-cudnn7.5.1
 - GPU models and configuration:
 - How you installed PyTorch: pip

**Comment by awaelchli** [comment]
Add 

if __name__ == "__main__" 

where your entry point to the script is. 
Chances are high you get this because you have num_workers > 0 in your DataLoader.

**Comment by rastegah** [comment]
thanks, but no change

1. that was already in the script entry point
2. changing num_workers also makes no difference

after manual inspection, I noticed that injection of callables with `gin-config` caused some pickling issues, but the issue persists even after solving these

**Comment by awaelchli** [comment]
@rastegah sorry for the standard answer but this was my best guess. 
It looks like you are not posting the full error stack trace so we don't know where this is originating from. And without a code sample it will also be hard to know what's going on.

**Comment by rastegah** [comment]
Here is the entry point to the script: 
`import fire
import os
import gin

from dptm.model import lightning_run
from dptm.utils import gin_register_and_parse

@gin.configurable
def run_train(gin_file: str = "gin/dptm.gin"):
    gin_config_path = os.path.join(os.getcwd(), gin_file)
    gin_register_and_parse(gin_config_path)

    lightning_run(gin_config_path)

def main():
  fire.Fire(run_train)

if __name__ == "__main__":
    main()`

`@gin.configurable
def lightning_run(gin_config: str = None,
                  n_epochs: float = 50, 
                  batch_size: float = 1, 
                  patience: int = 5,
                  log: bool = False,
                  data_module: Callable = LitDataModule):
    dataset = LitDataModule()

    model = LitModule()

    # Initialize a trainer
    logger = init_logger(gin_config) if log else None
    trainer = pl.Trainer(gpus=1,
                                   max_epochs=n_epochs,
                                   progress_bar_refresh_rate=20, 
                                   logger=logger)

    # Train the model ⚡
    trainer.fit(model, dataset)
    trainer.test(model)`

And the stack trace occurs during validation sanity check:

`Validation sanity check: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "/import/linux/python/3.8.2/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/import/linux/python/3.8.2/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'TypeError'>: it's not the same object as builtins.TypeError
Traceback (most recent call last):
  File "/import/linux/python/3.8.2/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/import/linux/python/3.8.2/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'TypeError'>: it's not the same object as builtins.TypeError`

I've spent hours trying to locate the issue. Manually pickled all modules and data modules. I'm usually an analogous environment and setup to other projects that do not encounter this error.

**Comment by awaelchli** [comment]
Can you set `num_workers=0` just to make sure this is not due to the multiprocessing in dataloaders?
And are you 100% sure this is the full stack trace?
There is nothing more above ` Validation sanity check: 0it [00:00, ?it/s]Traceback (most recent call last): File`?

**Comment by rastegah** [comment]
Setting `num_workers=0` does work now! Any idea how to resolve this?

**Comment by awaelchli** [comment]
Yes, that means you have somewhere a non-picklable object that gets accessed or imported in the code that runs in the worker processes. That's usually everything inside your dataset code and everything that gets imported there. PyTorch / Python will pickle all these objects to recreate the state in spawned processes. You would run into this issue even without Lightning I'm pretty sure. 
To test it, simply do this: 

```python
def main():

    dataset = MyDaset(...)
    dataloader = DataLoader(..., num_workers=2)
    data = next(iter(dataloader))
    
    # comment out all Lightning code
    # trainer.fit()
```
    
and if you run into a pickle error we know for sure what's the problem.
