### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn where accumulate_grad_batches > 1

### ISSUE THREAD

**Issue by bmahlbrand** [PyTorchLightning/pytorch-lightning#8365]
## 🐛 Bug

https://github.com/PyTorchLightning/pytorch-lightning/issues/8281 but w/3 optimizers instead of 2

## Please reproduce using the BoringModel

https://colab.research.google.com/drive/1wmSXZjybxXnZ9jFK8L0lQ9NvXGrkpiRo?usp=sharing

### To Reproduce

https://colab.research.google.com/drive/1wmSXZjybxXnZ9jFK8L0lQ9NvXGrkpiRo?usp=sharing

### Expected behavior

Should accumulate gradients and toggle optimizers as needed

**Comment by tchaton** [comment]
Dear @bmahlbrand,

I run your notebook using ``pip install pytorch-lightning==1.4.0rc0 `` and it seems to work.

<img width="882" alt="Screenshot 2021-07-19 at 13 14 44" src="https://user-images.githubusercontent.com/12861981/126151850-af6f55f0-25e8-44b5-b9a2-cf53ba01aecc.png">


Mind giving it a try ? Feel free to close the issue if resolved.

Best,
T.C

**Comment by bmahlbrand** [comment]
looks good to me! notebook and the actual project I noticed the problem on seem to run. Thanks!
