### ISSUE TITLE
Multiprocessing bug after switch to latest Lightning version

### ISSUE THREAD

**Issue by griff4692** [PyTorchLightning/pytorch-lightning#8402]
> Epoch 0:   4%|████▏                                                                                                    | 4/100 [00:06<02:28,  1.55s/it, 

> loss=nan]Traceback (most recent call last):
> 
>   File "finetune.py", line 27, in <module>
>     run(args, Summarizer)
>   File "/home/griffin/kabupra/graph/main.py", line 117, in run
>     trainer.fit(model)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 460, in fit
>     self._run(model)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 758, in _run
>     self.dispatch()
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 799, in dispatch
>     self.accelerator.start_training(self)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
>     self.training_type_plugin.start_training(trainer)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
>     self._results = trainer.run_stage()
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in run_stage
>     return self.run_train()
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 871, in run_train
>     self.train_loop.run_training_epoch()
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 491, in run_training_epoch
>     for batch_idx, (batch, is_last_batch) in train_dataloader:
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/profiler/profilers.py", line 112, in profile_iterable
>     value = next(iterator)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 534, in prefetch_iterator
>     for val in it:
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 464, in __next__
>     return self.request_next_batch(self.loader_iters)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 478, in request_next_batch
>     return apply_to_collection(loader_iters, Iterator, next)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 85, in apply_to_collection
>     return function(data, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
>     data = self._next_data()
>   File "/usr/lib/python3/dist-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
>     idx, data = self._get_data()
>   File "/usr/lib/python3/dist-packages/torch/utils/data/dataloader.py", line 1152, in _get_data
>     success, data = self._try_get_data()
>   File "/usr/lib/python3/dist-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
>     data = self._data_queue.get(timeout=timeout)
>   File "/usr/lib/python3.8/multiprocessing/queues.py", line 116, in get
>     return _ForkingPickler.loads(res)
>   File "/usr/lib/python3/dist-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
>     fd = df.detach()
>   File "/usr/lib/python3.8/multiprocessing/resource_sharer.py", line 58, in detach
>     return reduction.recv_handle(conn)
>   File "/usr/lib/python3.8/multiprocessing/reduction.py", line 189, in recv_handle
>     return recvfds(s, 1)[0]
>   File "/usr/lib/python3.8/multiprocessing/reduction.py", line 164, in recvfds
>     raise RuntimeError('received %d items of ancdata' %
> RuntimeError: received 0 items of ancdata
> Traceback (most recent call last):
>   File "finetune.py", line 27, in <module>
>     run(args, Summarizer)
>   File "/home/griffin/kabupra/graph/main.py", line 117, in run
>     trainer.fit(model)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 460, in fit
>     self._run(model)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 758, in _run
>     self.dispatch()
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 799, in dispatch
>     self.accelerator.start_training(self)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
>     self.training_type_plugin.start_training(trainer)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
>     self._results = trainer.run_stage()
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in run_stage
>     return self.run_train()
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 871, in run_train
>     self.train_loop.run_training_epoch()
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 491, in run_training_epoch
>     for batch_idx, (batch, is_last_batch) in train_dataloader:
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/profiler/profilers.py", line 112, in profile_iterable
>     value = next(iterator)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 534, in prefetch_iterator
>     for val in it:
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 464, in __next__
>     return self.request_next_batch(self.loader_iters)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 478, in request_next_batch
>     return apply_to_collection(loader_iters, Iterator, next)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 85, in apply_to_collection
>     return function(data, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
>     data = self._next_data()
>   File "/usr/lib/python3/dist-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
>     idx, data = self._get_data()
>   File "/usr/lib/python3/dist-packages/torch/utils/data/dataloader.py", line 1152, in _get_data
>     success, data = self._try_get_data()
>   File "/usr/lib/python3/dist-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
>     data = self._data_queue.get(timeout=timeout)
>   File "/usr/lib/python3.8/multiprocessing/queues.py", line 116, in get
>     return _ForkingPickler.loads(res)
>   File "/usr/lib/python3/dist-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
>     fd = df.detach()
>   File "/usr/lib/python3.8/multiprocessing/resource_sharer.py", line 58, in detach
>     return reduction.recv_handle(conn)
>   File "/usr/lib/python3.8/multiprocessing/reduction.py", line 189, in recv_handle
>     return recvfds(s, 1)[0]
>   File "/usr/lib/python3.8/multiprocessing/reduction.py", line 164, in recvfds
>     raise RuntimeError('received %d items of ancdata' %
> RuntimeError: received 0 items of ancdata

Hi - I just switched over to the latest version of Lightning and for some reason I am getting this error.  Does anyone know why this might be the case?  I am loading each example to a file during training so maybe there are too many files open?  I've reduced the num_workers to a small int and it's still happening.

**Comment by griff4692** [comment]
For others, I resolved this by adding

`torch.multiprocessing.set_sharing_strategy('file_system')`

**Comment by griff4692** [comment]
For others, I resolved this by adding

`torch.multiprocessing.set_sharing_strategy('file_system')`

**Comment by huangjin520** [comment]
> For others, I resolved this by adding
> 
> `torch.multiprocessing.set_sharing_strategy('file_system')`

Hi , I meet the same question as you . So I think you solution will help me out the dillemma. In order to apply your approach ,i want to know  **where the code** `torch.multiprocessing.set_sharing_strategy('file_system')` **should be placed** , and **what's the meaning of 'file_system'.**
Thanks for your reply sincerely!
