### ISSUE TITLE
mlflow run_name unexpected argument error

### ISSUE THREAD

**Issue by sid-sundrani** [PyTorchLightning/pytorch-lightning#8431]
## 🐛 Bug
The [documentation](https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.loggers.mlflow.html?highlight=logger#mlflow-logger) mentions there is an argument called run_name for the mlflow logger, where the run_name of a given experiment can be provided. Although,run_name is an unknown argument to the mlflow logger

`TypeError: __init__() got an unexpected keyword argument 'run_name'`

## Please reproduce using the BoringModel
Colab link:  https://colab.research.google.com/drive/1thcmInx6tQDOnkxk2Ir8hoOUx1UrOpIx?usp=sharing

### To Reproduce

```
from pytorch_lightning.loggers import MLFlowLogger
import mlflow

mlf_logger = MLFlowLogger(
    experiment_name="test",
    run_name="testrun",
)
```
### Environment
Colab - https://colab.research.google.com/drive/1thcmInx6tQDOnkxk2Ir8hoOUx1UrOpIx?usp=sharing

**Comment by awaelchli** [comment]
That's because you are looking at the docs under "latest" which is the development version. On the master branch, there is a run_name argument but 1.3.x does not have that. You are probably using Lightning 1.3.x. 
If you want, you can install Lightning rc0 to test the features before the 1.4 release.

**Comment by awaelchli** [comment]
Here are the docs for the stable version (1.3.x) https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.loggers.mlflow.html

**Comment by sid-sundrani** [comment]
Okay got it. Thanks for clarifying
