### ISSUE TITLE
Very annoying LightningDeprecationWarning: Relying on `self.log('val_loss', ...)`

### ISSUE THREAD

**Issue by datacubeR** [PyTorchLightning/pytorch-lightning#8482]
## 🐛 Bug

Following all of the instructions provided in the Documentation I can't understand the warning:
```
LightningDeprecationWarning: Relying on `self.log('val_loss', ...)` to set the ModelCheckpoint monitor is deprecated in v1.2 and will be removed in v1.4. Please, create your own `mc = ModelCheckpoint(monitor='your_monitor')` and use it as `Trainer(callbacks=[mc])`.
  "Relying on `self.log('val_loss', ...)` to set the ModelCheckpoint monitor is deprecated in v1.2"
```
## Please reproduce using the BoringModel
https://colab.research.google.com/drive/15TS0iWvfo6tvRtze-9tHOaZi0uWsHtUe?usp=sharing

### To Reproduce

Just Run the Notebook...

### Expected behavior

IMHO the suggestion provided by the warning is not clear and I can't find a way to avoid it according to the docs.

### Environment

* `Colab Notebook`: Please copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/requirements/collect_env_details.py) (or fill out the checklist below manually).

 - PyTorch Lightning Version (e.g., 1.3.0): 1.3.8
 - PyTorch Version (e.g., 1.8): 1.9.0+cu102
 - Any other relevant information: Tested in the colab environment with BoringModel as is. Just modified some steps in BoringModel

### Additional context

This issue repeats on my Ubuntu Machine:
![image](https://user-images.githubusercontent.com/48638337/126261099-8c250ebd-4dae-4628-862e-1ae57114afa7.png)

Thanks in advance,

Alfonso

**Comment by tchaton** [comment]
Dear @datacubeR,

I entirely understand your frustration. Lightning tries to provide as much information as possible to avoid breaking changes with a 2 cycle depreciation. This is important for people using Lightning in production, better to annoy than break :) 

This particular warning indicates that the ModelCheckpoint used to rely `magically` on `val_loss` for checkpointing if no monitor was provided, but it isn't the case anymore, this would have to be explicitly provided to the ModelCheckpoint Callback.

Also, you can prevent warning to appear using the following.

# this should prevent the warning to appear
```py
callback = ModelCheckpoint(monitor="val_loss")
```

You can also filter out some warnings as follow 
```py
def ignore_pl_warnings():
    warnings.filterwarnings(
        "ignore", r".*GPU available but not used.*", UserWarning
    )
    warnings.filterwarnings(
        "ignore", r".*does not have many workers.*", UserWarning
    )


def disable_pl_info():
    pl._logger.setLevel(logging.CRITICAL)
```

Best,
T.C

**Comment by tchaton** [comment]
I am closing this issue, feel free to re-open it if you have more questions.
