### ISSUE TITLE
Resuming training from checkpoint doesn't work correctly with BaseFinetuning

### ISSUE THREAD

**Issue by eladsegal** [PyTorchLightning/pytorch-lightning#8502]
## 🐛 Bug

When the model is using a callback that inherits from BaseFinetuning and the training is resumed, the optimizer doesn't get the right param groups restored, resulting in an exception.

## Reproduction using the BoringModel
I've added a `backbone` module to the model and a `BackboneFinetuning` callback to the trainer which unfreezes backbone at epoch 2. 
In training, right after the beginning of epoch 3 I stop the training by using `trainer.should_stop=True`, making sure the last checkpoint saved is at the end of epoch 2 by changing `checkpoint_callback.save_last` to `False`.
Then, I resume the training from `last.ckpt` and `ValueError: loaded state dict has a different number of parameter groups` is thrown.

https://colab.research.google.com/drive/1xIE218xOvK9tSoWV_2z820Qog_NqrILs?usp=sharing

### Expected behavior

The problem is that `checkpoint_connector.restore_callbacks` is called before `accelerator.setup`, which means that `BaseFinetuning.on_load_checkpoint` is called before `trainer.optimizers` is set and therefore the right param groups are not updated for the optimizers:
https://github.com/PyTorchLightning/pytorch-lightning/blob/4c79b3a5b343866217784c66d122819c59a92c1d/pytorch_lightning/trainer/trainer.py#L860-L863

Seems like a solution would be to put `restore_callbacks` after `accelerator.setup`.

### Environment
```
* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.2
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.0+cu102
	- pytorch-lightning: 1.4.0rc0
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.11
	- version:           #1 SMP Sat Jun 5 09:50:34 PDT 2021
```

**Comment by tchaton** [comment]
Dear @eladsegal,

Mind trying master, I should be resolved.

If not, mind sharing a reproducible script ?

Best,
T.C
