### ISSUE TITLE
Origin Warning: [W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)

### ISSUE THREAD

**Issue by tobiascz** [PyTorchLightning/pytorch-lightning#8537]
## Warning

I am training a model with ddp an every time the dataloader gets called e.g. when starting training or starting evaluation I get the warning:

`[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
`

In the training function of my code I already disabled warnings:
`
logging.disable(logging.WARNING)
warnings.filterwarnings("ignore")`

which should mean that this is a pytorch problem and not pytorch lighting. Nevertheless I would like to understand why and where this warning is coming from and if I am doing something wrong in my code.

**Comment by awaelchli** [comment]
Hi, it is coming from pytorch 1.9: https://github.com/pytorch/pytorch/issues/57273
Some users report that the warning disappears with `pin_memory=False` in the dataloader.

**Comment by MaveriQ** [comment]
I get the same Warning at the start of every epoch. Is there any update on it?
