### ISSUE TITLE
[Pyright] Cannot instantiate abstract class

### ISSUE THREAD

**Issue by hadim** [PyTorchLightning/pytorch-lightning#854]
I use [Pyright](https://github.com/microsoft/pyright) for static type checking and it raises 66 errors on `master` due to `Cannot instantiate abstract class 'Trainer'`.

I have been able to reproduce the issue:

```python
import abc


class MixinA(abc.ABC):
    @abc.abstractmethod
    def a(self) -> None:
        print('MixinA.a')


class MixinB(abc.ABC):
    @abc.abstractmethod
    def b(self) -> None:
        print('MixinB.b')


class Trainer(MixinA, MixinB):
    pass


ab = Trainer()
```

Do you think this should be addressed or do you think it's an error from Pyright? In that case, I will open a ticket on the Pyright repo.

**Comment by Borda** [comment]
by my understanding the example above is correct, so I would open question on Pyright if they are aware of it... could you please link your issue there to this one so we neep track... Thx

**Comment by hadim** [comment]
See https://github.com/microsoft/pyright/issues/529#issuecomment-588255021

**Comment by Borda** [comment]
hi @hadim, can we connect on Slack?

**Comment by Borda** [comment]
Well, in our case the key is the order of parent classes, see:
```python
import abc

class MixinA(abc.ABC):
    pass

class MixinB(abc.ABC):
    def get_model(self):
        print('MixinB.get_model')

class MixinC(abc.ABC):
    @abc.abstractmethod
    def get_model(self):
        pass

    def use_model(self):
        m = self.get_model()
        print('MixinC.get_model')

# correct parent class order
class Trainer_1a(MixinA, MixinB, MixinC):
    pass

trainer = Trainer_1a()  # <- No error here

# wrong parent class order
class Trainer_1b(MixinA, MixinC, MixinB):
    pass

trainer = Trainer_1b()  # <- Can't instantiate abstract class Trainer_1b with abstract methods get_model
```

**Comment by hadim** [comment]
The error I got is actually on `Trainer_1a` and not `Trainer_1b`.

(I am on slack)

**Comment by hadim** [comment]
Ok so Pyright complains on `Trainer_1a` but Python raises an error on `Trainer_1b`.

**Comment by hadim** [comment]
It has been confirmed the bug is on the Pyright side so I close here.

**Comment by Borda** [comment]
@hadim thank you for your initiative!
