### ISSUE TITLE
improve Trainer.tune output display

### ISSUE THREAD

**Issue by talhaanwarch** [PyTorchLightning/pytorch-lightning#8544]
There is unnecarry logging, which does not convey any information. Can we remove it.
**During tuning**
![image](https://user-images.githubusercontent.com/37379131/126912551-83ddbc26-90ff-4603-bfc2-a826f356e158.png)
**During training**
![image](https://user-images.githubusercontent.com/37379131/126912637-517596d6-a900-4ce0-b6a2-890f11c3194f.png)

**Comment by awaelchli** [comment]
One way to avoid this could be to set `verbose_evaluate=False` during tuning
Are you interested in sending a PR?
