### ISSUE TITLE
[Pyright] Cannot access member 'X' for type 'None'

### ISSUE THREAD

**Issue by hadim** [PyTorchLightning/pytorch-lightning#855]
Pyright raises 89 errors on `master` about `Cannot access member 'X' for type 'None'`. Here is an example in `evaluation_loop.py`:

```python
                # track outputs for collation
                dl_outputs.append(output)

                # batch done
                if test:
                    self.test_progress_bar.update(1)  # PYRIGHT ERROR
                else:
                    self.val_progress_bar.update(1)  # PYRIGHT ERROR
                    self.main_progress_bar.update(1)  # PYRIGHT ERROR
            outputs.append(dl_outputs)

        eval_results = {}
```

One way to fix this is to indicate the type of those variables:

```python
self.test_progress_bar: Any = None
```

Unless you see a more elegant way?

**Comment by Borda** [comment]
This shall be fixed, may you consider sed a PR?

**Comment by hadim** [comment]
Not sure I would have time on the short term but I'll keep it on my TODO list.

**Comment by Dev-Akash** [comment]
Hi there, I am interested in solving this bug, can i work on this ?

**Comment by Borda** [comment]
Hi @Dev-Akash sure, that would be great!

**Comment by Borda** [comment]
Hi @Dev-Akash how is it going?

**Comment by Borda** [comment]
Hi @Dev-Akash how is it going? any progress here... :rabbit:

**Comment by Borda** [comment]
@hadim maybe we can also add this check to CI, does it run on Linux?

**Comment by hadim** [comment]
You can install it with npm (see website). Sorry I don't have time to do that at the moment.

**Comment by uditarora** [comment]
I'd be happy to take a look at this if no one else is working on it. Let me know.

CC: @Borda

**Comment by Borda** [comment]
@Dev-Akash still interested in finishing the type check after #2121?

**Comment by Dev-Akash** [comment]
> @Dev-Akash still interested in finishing the type check after #2121?

Hi @Borda, sorry for the delayed reply, I was unavailable these days..
And yes i am interested in contributing to it, so let me once again go with the code and surely i will add some pull requests to fix these issues. 
I also need help in knowing how can I reproduce the above error ?

**Comment by Dev-Akash** [comment]
> @Dev-Akash still interested in finishing the type check after #2121?

Currently not able to contribute in this issue, you can unassign me from this issue.
Thank you !

**Comment by Borda** [comment]
@uditarora still interested in taking this over? :]

**Comment by uditarora** [comment]
> @uditarora still interested in taking this over? :]

Sure, I have some free time over the next week. Let me try and fix more Pyright errors :)

Let me know if you have something specific in mind that I should look at. Else I can pick up some module randomly.

**Comment by Borda** [comment]
@uditarora how is it going here?

**Comment by 0560405608** [comment]
`****`

**Comment by uditarora** [comment]
> @uditarora how is it going here?

I made a little progress earlier but not enough to send a PR, before sadly getting caught up with school-related deadlines. I'm not sure how much I'll be able to contribute for the next month, so please feel free to assign it to someone else in the meanwhile if they're interested :)

**Comment by gianscarpe** [comment]
As discussed with @Borda, I would suggest improving the typing of all the code base to make static type checking more robust! :)

**Comment by akihironitta** [comment]
I think we can close this issue as we have a tracking issue for typing: #5023.
