### ISSUE TITLE
Enable auto parameters tying for TPU

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#8555]
### Motivation

Currently, TPU requires to tie the parameters after the weights are being moved to TPU and users need to override the `on_post_move_to_device` which isn't intuitive and requires some expert knowledge, especially if you are using model from a library and you are fully aware of its internal architecture yet.

Lightning could automate this process and depreciate `on_post_move_to_device` hook with an approach similar to the one below.

```
def find_shared_parameters(model: LightningModule, tied_parameters = None):
    if tied_parameters is None:
        tied_parameters = {}

    for module in model.modules(recurse=False)
        for prefix, p in module.named_parameters():
            if p not in tied_parameters:
                tied_parameters[p] = []
            tied_parameters[p].append(prefix)
        find_shared_parameters(module, tied_parameters)

    return [prefixes for prefixes in tied_parameters.values() if len(prefixes) > 2]

def on_before_move_to_device(self):
    if  on_tpu:
        self.prefixes = self.find_shared_parameters(self.lightning_module)

def on_post_move_to_device():
    self.apply_tying(self.prefixes)
```

#### If you enjoy PL, check out our other projects:

- [Metrics](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.
- [Flash](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning
- [Bolts](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch
- [Lightning Transformers](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

**Comment by tchaton** [comment]
Hey @kaushikb11, mind sharing your thoughts ?

**Comment by kaushikb11** [comment]
Hey @tchaton, this sounds good to me. Agreed, users would face this issue while using an external library without having control over the warning.

**Comment by ananthsub** [comment]
as @tchaton points out, this also would enable us to deprecate `on_post_move_to_device` and `parameter_validation `
 https://github.com/PyTorchLightning/pytorch-lightning/discussions/8736

**Comment by ananthsub** [comment]
@tchaton @kaushikb11 as a reference, here is how fairseq handles this:
https://github.com/pytorch/fairseq/blob/1f7ef9ed1e1061f8c7f88f8b94c7186834398690/fairseq/trainer.py#L110-L118

**Comment by kaushikb11** [comment]
Thanks @ananthsub for the reference. I will add it as a priority for next week!
