### ISSUE TITLE
Can we keep all GPUs use the same batch of data when we use distributed mode (like horovod or DDP) ?

### ISSUE THREAD

**Issue by marsggbo** [PyTorchLightning/pytorch-lightning#8562]
### Motivation

Currently, I want to train a Supernet, which contains many sub-networks, and I want to use multiple GPUs to accelerate training, and each GPU trains different models but uses the same batch of data.

So I wonder how to implement it?

**Comment by ijpq** [comment]
pl has only impl auto adding distributedsampler, is it proper that impl a specific Distributed sampler grab same batch?

**Comment by tchaton** [comment]
Dear @marsggbo, you can prevent Lightning to inject the DistributedSampler within your DataLoader by doing.

```py
Trainer(replace_ddp_sampler=False)
```

Feel free to close this issue if it resolves your problem.

**Comment by marsggbo** [comment]
thanks for your suggestion. `replace_sampler_ddp=False` will make all GPUs use the same data during the training and validation step, but I want to make GPUs use the same data during the training step, but different data during the validation step.  This is indeed a weird use case, 

![image](https://user-images.githubusercontent.com/13477956/127606433-338248af-8a6e-4e57-ac9d-f7ee0a487b0f.png) any suggestions would be greatly appreciated

**Comment by jiarenyf** [comment]
> thanks for your suggestion. `replace_sampler_ddp=False` will make all GPUs use the same data during the training and validation step, but I want to make GPUs use the same data during the training step, but different data during the validation step. This is indeed a weird use case,
> 
> ![image](https://user-images.githubusercontent.com/13477956/127606433-338248af-8a6e-4e57-ac9d-f7ee0a487b0f.png) any suggestions would be greatly appreciated

... You can just set ```torch.utils.data.distributed.DistributedSampler``` at train_loader, and set ```torch.utils.data.SequentialSampler``` or `None` at valid_loader ...
