### ISSUE TITLE
Main script runs multiple times - once per GPU

### ISSUE THREAD

**Issue by ViktorThink** [PyTorchLightning/pytorch-lightning#8563]
Encountered same problem as in this post: https://stackoverflow.com/questions/66261729/pytorch-lightning-duplicates-main-script-in-ddp-mode

When using four GPUs, the main script runs four times, meaning that the model is downloaded four times, which takes time, and causes out of memory error. 

I tried lots of configurations, but they all have the same problem, here is an example code I used:

```
trainer = pl.Trainer(
    gpus=4,
    plugins=DeepSpeedPlugin(
              stage=3,
              cpu_offload=True,
              partition_activations=True,),
    max_epochs=2,
    accumulate_grad_batches=8,
    precision=16,
    accelerator="ddp",

    )

trainer.fit(model, train_dataloader)
```

I don't understand why the main script should run multiple times, and does anyone know a way for the main script to run only once?

**Comment by ethanwharris** [comment]
Hi @ViktorThink to make sure that your code only runs once you can use something like this:
```
# imports

if __name__ == "__main__":
    # download data
    # train model etc.
```

Hope that helps :smiley:

**Comment by ViktorThink** [comment]
Thank you  for the quick reply.

Both I and the guy making the other post tried that with no success. It all runs as main surprisingly.

**Comment by ethanwharris** [comment]
@ViktorThink Actually, I think this is the expected behaviour from the docs here: https://pytorch-lightning.readthedocs.io/en/stable/advanced/multi_gpu.html#distributed-data-parallel

You would always need each process to create the model correctly. What you could do is make sure that once the model is downloaded it doesn't get downloaded again (the weights should just be saved and then re-loaded by the subsequent processes). Otherwise you could try alternative methods like ddp_spawn or regular data parrallel.

Hope that helps :smiley:

**Comment by ViktorThink** [comment]
Thanks a lot for the help.

I will try ddp_spawn tomorrow.

**Comment by ViktorThink** [comment]
It seems like using the DeepSpeedPlugin overrides the accelerator selected, because I tried with ddp_spawn and dp, but got the same problem. (I thought I tried with ddp_spawn yesterday, but double checked today, same result).

I managed to use dp without DeepSpeedPlugin, (but had some problem with ddp_spawn, not sure why). 

Thanks for the help @ethanwharris!

**Comment by tchaton** [comment]
> Encountered same problem as in this post: https://stackoverflow.com/questions/66261729/pytorch-lightning-duplicates-main-script-in-ddp-mode
> 
> When using four GPUs, the main script runs four times, meaning that the model is downloaded four times, which takes time, and causes out of memory error.
> 
> I tried lots of configurations, but they all have the same problem, here is an example code I used:
> 
> ```
> trainer = pl.Trainer(
>     gpus=4,
>     plugins=DeepSpeedPlugin(
>               stage=3,
>               cpu_offload=True,
>               partition_activations=True,),
>     max_epochs=2,
>     accumulate_grad_batches=8,
>     precision=16,
>     accelerator="ddp",
> 
>     )
> 
> trainer.fit(model, train_dataloader)
> ```
> 
> I don't understand why the main script should run multiple times, and does anyone know a way for the main script to run only once?

Dear @ViktorThink,

There is 2 ways to do Distributed Data Parallel Training.
The first one is `ddp`, it launches N processes running the same script by aware of their own ranks and word_size
The second one is `ddp_spawn`, it creates 1 processes which will spawn N others.

DeepSpeedPlugin has been built on top of DDPPlugin, so having your script runs 4 times is totally expected.

In order to avoid download the model on each processes, you could do

```py
import os
if os.getenv("LOCAL_RANK", '0') == '0':
      download_weights(...)
model = Model()
dm = DataModule()
Trainer(model, dm)
```

**Comment by timothylimyl** [comment]
@tchaton , in this case, how do we avoid DDP running the script 4 times?

For example, in some hyperparam search cases, we want will put the `trainer.fit` in a loop while changing the hyperparams. In this case, the DDP processess will end up running the main script (duplication) 4 times more than necessary.

**Comment by loretoparisi** [comment]
> > Encountered same problem as in this post: https://stackoverflow.com/questions/66261729/pytorch-lightning-duplicates-main-script-in-ddp-mode
> > When using four GPUs, the main script runs four times, meaning that the model is downloaded four times, which takes time, and causes out of memory error.
> > I tried lots of configurations, but they all have the same problem, here is an example code I used:
> > ```
> > trainer = pl.Trainer(
> >     gpus=4,
> >     plugins=DeepSpeedPlugin(
> >               stage=3,
> >               cpu_offload=True,
> >               partition_activations=True,),
> >     max_epochs=2,
> >     accumulate_grad_batches=8,
> >     precision=16,
> >     accelerator="ddp",
> > 
> >     )
> > 
> > trainer.fit(model, train_dataloader)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't understand why the main script should run multiple times, and does anyone know a way for the main script to run only once?
> 
> Dear @ViktorThink,
> 
> There is 2 ways to do Distributed Data Parallel Training. The first one is `ddp`, it launches N processes running the same script by aware of their own ranks and word_size The second one is `ddp_spawn`, it creates 1 processes which will spawn N others.
> 
> DeepSpeedPlugin has been built on top of DDPPlugin, so having your script runs 4 times is totally expected.
> 
> In order to avoid download the model on each processes, you could do
> 
> ```python
> import os
> if os.getenv("LOCAL_RANK", '0') == '0':
>       download_weights(...)
> model = Model()
> dm = DataModule()
> Trainer(model, dm)
> ```

What about model eval?
I did like
```python
is_main_process = True
    if train_strategy=='ddp':
        # LP: distributed data parallel
        is_main_process = False
        if os.getenv("LOCAL_RANK", '0') == '0':
            # ddp main process
            # @see https://github.com/Lightning-AI/lightning/issues/8563
            is_main_process = True

trainer = pl.Trainer(logger=logger,
                        callbacks=[checkpoint_callback],
                         max_epochs=hparams["epochs"],
                         devices=devices,
                         accelerator=accelerator,
                         strategy=train_strategy)
trainer.fit(model, trainloader)

if is_main_process:
        log_message('evaluation...')
        model.eval()
        logits = model(tensors.int()).cpu().detach().numpy()
        upload(logits)
```

in order to run evaluation on the main only.
