### ISSUE TITLE
How to reinit wanbd in a for loop with PL Trainer

### ISSUE THREAD

**Issue by Gladiator07** [PyTorchLightning/pytorch-lightning#8574]
### Discussed in https://github.com/PyTorchLightning/pytorch-lightning/discussions/8572

<div type='discussions-op-text'>

<sup>Originally posted by **Gladiator07** July 27, 2021</sup>
I am training 5-fold CV with PyTorch Lightning in a for loop. I am also logging all the results to wandb. I want wanbd to reinitalize the run after each fold, but it seems to continue with the same run and it logs all the results to the same run. I also tried passing kwargs in the WandbLogger as mentioned in the docs [here](https://pytorch-lightning.readthedocs.io/en/stable/extensions/generated/pytorch_lightning.loggers.WandbLogger.html#pytorch_lightning.loggers.WandbLogger.params.**kwargs), with no luck.
Here's a pseudo code of it:

```python
def run(fold):
    kwargs = {
        "reinit": True,
        "group": f"{CFG['exp_name']}"
    }
    wandb_logger = WandbLogger(project='<name>', 
                        entity='<entity>', 
                        config = CFG,
                        name=f"fold_{fold}",
                        **kwargs
            )
    trainer = Trainer(
        precision=16,
        gpus=1,
        fast_dev_run=False,
        callbacks = [checkpoint_callback],
        logger=wandb_logger,
        progress_bar_refresh_rate=1,
        max_epochs=2,
        log_every_n_steps=1

    )

    trainer.fit(
        lit_model,
        data_module
    )

if __name__ == "__main__":
    for fold in range(5):
        run(fold)
```</div>

**Comment by marcelschilling** [comment]
@Gladiator07 Did you try to use wandb.init(...) before and wandb.finish() after every step of your CV?

**Comment by Gladiator07** [comment]
Thanks, I had to mention run.finish() explicitly to stop my wandb run. I thought PL handled this internally, so I didn't tried this. Anyways, thanks for your help :)
