### ISSUE TITLE
Broken link in Set Grads to None section

### ISSUE THREAD

**Issue by ifsheldon** [PyTorchLightning/pytorch-lightning#8606]
## 📚 Documentation

In https://pytorch-lightning.readthedocs.io/en/latest/guides/speed.html#set-grads-to-none
> For a more detailed explanation of pros / cons of this technique, read [this](https://pytorch.org/docs/master/optim.html#torch.optim.Optimizer.zero_grad) documentation by the PyTorch team.

The link seems to be broken, and I think the latest valid link is https://pytorch.org/docs/master/generated/torch.optim.Optimizer.zero_grad.html#torch.optim.Optimizer.zero_grad

**Comment by awaelchli** [comment]
Hi @ifsheldon 

The link should probably not point to the master branch. And we can link through the API like this:
```py
:meth:`torch.optim.Optimizer.zero_grad`
```
and it will generate the link for us automatically. 
Are you interested in sending a PR with this fix?

**Comment by ifsheldon** [comment]
I mean, it's not the link in the below that is broken.
> In order to modestly improve performance, you can override [optimizer_zero_grad()](https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.core.lightning.html#pytorch_lightning.core.lightning.LightningModule.optimizer_zero_grad).

but the link of "this" in the below

> For a more detailed explanation of pros / cons of this technique, read [this](https://pytorch.org/docs/master/optim.html#torch.optim.Optimizer.zero_grad) documentation by the PyTorch team

I took a look at the source code, the link of "this" is hardcoded. 
```rst
For a more detailed explanation of pros / cons of this technique,
read `this <https://pytorch.org/docs/master/optim.html#torch.optim.Optimizer.zero_grad>`_ documentation by the PyTorch team.
```
And perhaps you should also make it autognerated?

**Comment by awaelchli** [comment]
Yes I agree. We are talking about the same thing :)

**Comment by ifsheldon** [comment]
OK, sorry. I don't really understand how the API works, but I see you have made a PR. Thanks a lot.

**Comment by awaelchli** [comment]
No problem at all. Thanks for finding this
