### ISSUE TITLE
LightningCLI shouldn't run fit by default

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#8615]
### To Reproduce

Currently, the LightingCLI runs fit by default which is an anti-pattern for the Lightning API and seems like magic.

Current implementation.
```py
    cli = LightningCLI(LiftModel, MnistDataModule)
    cli.trainer.test(datamodule=cli.datamodule)
    cli.trainer.save_checkpoint("mnist_cnn.pt")
```

Expected implementation.
```py
    cli = LightningCLI(LiftModel, MnistDataModule)
    cli.trainer.fit(cli.model, datamodule=cli.datamodule)
    cli.trainer.test(datamodule=cli.datamodule)
    cli.trainer.save_checkpoint("mnist_cnn.pt")
```

### Environment

 - PyTorch Lightning Version (e.g., 1.3.0):
 - PyTorch Version (e.g., 1.8)
 - Python version:
 - OS (e.g., Linux):
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - How you installed PyTorch (`conda`, `pip`, source):
 - If compiling from source, the output of `torch.__config__.show()`:
 - Any other relevant information:

**Comment by ethanwharris** [comment]
Seems related to #7226 (PR in #7508), #8251

**Comment by awaelchli** [comment]
@tchaton I think strictly this is not a bug as it is documented [here](https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_cli.html#lightningcli) right were LightningCLI is first introduced:

> The instantiation of the LightningCLI class takes care of parsing command line and config file options, instantiating the classes, setting up a callback to save the config in the log directory and finally running the trainer. 

I do however agree with you that this is an issue and it is also _my opinion_ that the instantiation of LightningCLI should not run a trainer.fit.

**Comment by Borda** [comment]
just for the record, @tchaton https://github.com/PyTorchLightning/pytorch-lightning/pull/8251#issuecomment-874558913
cc: @carmocca
