### ISSUE TITLE
Add test guidance to contributer guide

### ISSUE THREAD

**Issue by jeremyjordan** [PyTorchLightning/pytorch-lightning#862]
## 📚 Documentation

From discussion on PR #837 , we should include some guidelines for how code is tested, especially for new contributions. This would probably be included in `CONTRIBUTING.md` in the docs.

Things to discuss would be:
- usage of fixtures in tests
- parameterized tests
- expected level of documentation in tests

**Comment by jeremyjordan** [comment]
cc @Borda from our chats on the PR, made this issue

**Comment by awaelchli** [comment]
maybe this could also include guidelines about how code is formatted and documented, e.g. format for doc strings, typing, how exceptions are handled etc., so that the codebase has a uniform style.

**Comment by Borda** [comment]
partially done in #993
