### ISSUE TITLE
About fine-tuning and explaining the result

### ISSUE THREAD

**Issue by gofimofi** [PyTorchLightning/pytorch-lightning#863]
## ❓ Questions and Help

Hi,

Thank you for the contribution and framework. Would you mind if you lead me how to freeze all the layers except classification layer during the fine tuning? And also would you help me how to explain the result of the fine tuned model such as which words of the "sentence" made it labelled as positive? 

Thank you.

**Comment by polars05** [comment]
Check out the **Example: Imagenet (computer Vision)** section of https://pytorch-lightning.readthedocs.io/en/latest/introduction_guide.html. In the example, ResNet50 is frozen through `self.feature_extractor.eval()`. Upon calling `trainer.fit(model)`, only the classifier is trained. You could definitely apply the same concept to a NLP model. Hope this helps you!
