### ISSUE TITLE
Separating test phase in different file & accepting test specific hyperparameters

### ISSUE THREAD

**Issue by dasayan05** [PyTorchLightning/pytorch-lightning#8631]
## 🚀 Feature

Allow users to separate "Train + Validation" and "Test" phases into separate files and allow extra hyperparameters in Test phase.

### Motivation

Often, research codes and trained models shared by researchers are consumed by developers who only care about testing on the trained model and not retraining it. It makes sense if users can break their `PyTorchLightning` module into two different files with the test file accepting extra hyperparameters specific to testing, e.g. "How many samples to draw from a trained VAE".

### Pitch

One script `train.py` for training + validation:
```python
class TrainPLModule(pl.LightningModule):
    def __init__(self, all, my, hps):
        self.save_hyperparameters()
        # all my hyper params can be accessed from self.hparams
    def training_step(self, ...): ...
    def validation_step(self, ...): ...

system = TrainPLModule(all=ALL, my=MY, ...)
trainer.fit(system)
```
.. another `test.py` for testing
```python
class TestPLModule(TrainPLModule):
    def test_step(self):
        # self.hparams are all indeed accessible, BUT ..
        # I want new hparams specific to testing process
        self.hparams.test_specific_hp # NOT AVAILABLE

system = TestPLModule.load_from_checkpoint('/trained/model',
                                            all=NEW_ALL, # overwrites the original HP
                                            # but this WON'T show up in self.hp in test_step()
                                            test_specific_hp=12
trainer.test(system)
```

### Alternatives

We can define all Hyperparameters in `train.py` and [overwrite them in test file after loading the model](https://pytorch-lightning.readthedocs.io/en/stable/common/weights_loading.html#checkpoint-loading), but testing process maybe large and have lots of testing specific HPs which are totally unnecessary for training (e.g. VAE latent space sampling/walking, creating UMAP/TSNE embedding from latent codes etc).

### Additional context

Opening this feature request on @tchaton's suggestion on this discussion https://github.com/PyTorchLightning/pytorch-lightning/discussions/8581

**Comment by tchaton** [comment]
Dear @dasayan05,

Definitely an interesting idea ! Would you be interested to work on this ?

Best,
T.C

**Comment by dasayan05** [comment]
@tchaton I would love to give it a try.

So, the reason `.load_from_checkpoint(..)` rejects unknown `kwargs` is clearly this line here:
https://github.com/PyTorchLightning/pytorch-lightning/blob/963c26764682fa4cf64c93c5a7572ae0040e9c32/pytorch_lightning/core/saving.py#L193

We can simply tweak some code around this to inject the unknown parameters into `model.hparams`. Is this a reasonable thing to do ? @tchaton do you have any other suggestion ?
