### ISSUE TITLE
Bug: Trainer.predict() returns list of eval-batch-size, not List[predictions_per_dataloader] as in Doc

### ISSUE THREAD

**Issue by breznak** [PyTorchLightning/pytorch-lightning#8646]
## 🐛 Bug

`pl.Trainer.predict()` states to return list of predictions per each dataloader. Doc: https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#predict 

But it returns list of predictions per each eval batch. 

### To Reproduce

```py
import os

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    test_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    pred_data = DataLoader(RandomDataset(32, 64), batch_size=2)

    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        num_sanity_val_steps=0,
        max_epochs=1,
        weights_summary=None,
    )
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
    trainer.test(model, dataloaders=test_data)

    #FIXME test starts here - tested on PL 1.3.8, PL 1.4: same bug
    predictions = trainer.predict(model, dataloaders=pred_data, return_predictions=True)
    # see https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#predict
    assert len(predictions) == 1, 'Expected 1 dataloader, not N predictions by eval_batch_size!'


if __name__ == "__main__":
    run()
```

### Expected behavior

Either change doc, or aggregate the data predict() returns. 

### Environment

 - PyTorch Lightning Version (e.g., 1.3.0): 1.3.8, 1.4.0
 - PyTorch Version (e.g., 1.8): 1.8
 - Python version: 3.6
 - OS (e.g., Linux): Linux

**Comment by justusschock** [comment]
Hi @breznak 

Thanks for the issue. You are right, this is not formulated really clearly. So it is intended to work that way since we simply omit the wrapping structure of multiple dataloaders if we only see one element/loader :)

Would you like to contribute a PR to make this more clear in the docs? :)

**Comment by breznak** [comment]
> So it is intended to work that way since we simply omit the wrapping structure of multiple dataloaders if we only see one element/loader 

ok, (I'd rather be for consistency and return `List[ per_dataloader(s) ]`, but still... the predict() returns a list of dictionaries per batch-size (eval batch). Don't we want to aggregate the data over the batches into a single Tensor with all predictions?

**Comment by tchaton** [comment]
Dear @breznak,

Some users prefer to have per-batch level predictions as it is easier to store and prevent OOM while performing prediction.
It is why we introduce `BasePredictionWriter` Callback.

Best,
T.C
