### ISSUE TITLE
Add predict_epoch_end and predict_step_end methods to LightningModule

### ISSUE THREAD

**Issue by mehrshadhosseini28** [PyTorchLightning/pytorch-lightning#8657]
## 🚀 Feature

Add predict_epoch_end and predict_step_end methods to LightningModule

Why aren't there these two methods?

### Motivation

I think these methods are very useful. for example, putting the results of each batch together.

**Comment by ananthsub** [comment]
@mehrshadhosseini28 this is closely related to https://github.com/PyTorchLightning/pytorch-lightning/issues/8479 

though for predict_epoch_end, you could locally keep track of the predict_step return values in your LightningModule and then post-processing them in on_predict_epoch_end
