### ISSUE TITLE
un-packing bug : TypeError: wrapper() got an unexpected keyword argument 

### ISSUE THREAD

**Issue by felixdittrich92** [PyTorchLightning/pytorch-lightning#8677]
## 🐛 Bug
Hi, since the update (lightning 1.4 & pytorch 1.9) i get some curios error:
```
 File "/home/felix/anaconda3/envs/work/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 178, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/felix/Desktop/memoresa-work-ml/Task_NLP/NER_torch/torch_model.py", line 85, in validation_step
    loss, logits = self(ids=ids, mask=mask, labels=labels)
  File "/home/felix/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: wrapper() got an unexpected keyword argument 'ids'
```
(before update all was fine)
```py
def forward(self, ids, mask, labels=None):
        outputs = self.bert(input_ids=ids, attention_mask=mask, labels=labels)
        # outputs.loss   outputs.logits   outputs.attentions
        return outputs.loss, outputs.logits
```
```py
def validation_step(self, batch, batch_idx):
        ids = batch["ids"]
        mask = batch["mask"]
        labels = batch["tags"]
        loss, logits = self(ids=ids, mask=mask, labels=labels)
```
 I have checked the validation step input all is ok

### To Reproduce
pip3 install -r requiremetns.txt
(change paths in trainer.py and ner_dataset.py to your env paths)
python3 Task_NLP/NER_torch/trainer.py

You can use the following Github link (pls contact me to get access):
https://github.com/felixdittrich92/memoresa-work-ml
ID Slack: U01RBRR0EAG

### Environment

* CUDA:
        - GPU:
        - available:         False
        - version:           10.2
* Packages:
        - numpy:             1.21.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.9.0+cu102
        - pytorch-lightning: 1.4.0
        - tqdm:              4.61.2
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.10
        - version:           #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021

**EDIT:** the error occurs only if i try to set `QuantizationAwareTraining` as callback !!!

cc @awaelchli @ananthsub @borda

**Comment by carmocca** [comment]
cc @Borda as it seems to be caused by QAT

**Comment by tchaton** [comment]
Dear @felixdittrich92,

Would you mind trying to reproduce this behaviour using the BoringModel script: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py

This doesn't seem much, but it saves us countless hours :) 

Best,
T.C
