### ISSUE TITLE
Links to Colab in "Lightning in 2 steps" are dead

### ISSUE THREAD

**Issue by enolan** [PyTorchLightning/pytorch-lightning#8684]
## 📚 Documentation

Under "Examples of systems are:" all the Colab links are dead.

**Comment by tchaton** [comment]
Dear @enolan,

Thanks for reporting this issue. Would you be interested in making a contribution ?

Best,
T.C

**Comment by seanbenhur** [comment]
Hi, @tchaton shall I work on this!?

**Comment by tchaton** [comment]
Dear @seanbenhur,

Yes, please !

Best,
TC

**Comment by seanbenhur** [comment]
The notebooks are not available on the master branch, it is available here, https://github.com/PyTorchLightning/lightning-tutorials/tree/6100885854c803458886c731cddd6bd67498c0a1, is it okay to use this branch!?
