### ISSUE TITLE
[RFC][Docs] Expand Common Use Cases to improve discoverability

### ISSUE THREAD

**Issue by SeanNaren** [PyTorchLightning/pytorch-lightning#8693]
## 📚 Documentation

The goal is to improve discoverability when using the docs for new users, or users who just want to see what features we support. We've grouped quite a bit into the drop down which hides and obfuscates important information that the user may not know to click imo.

To improve this, I suggest we go from this:

<img width="1494" alt="Screenshot 2021-08-03 at 11 47 04" src="https://user-images.githubusercontent.com/6707363/128003236-194f5eb6-8a1e-4991-af6f-f5fab6dd64cb.png">

to this:

<img width="1511" alt="Screenshot 2021-08-03 at 11 45 10" src="https://user-images.githubusercontent.com/6707363/128003022-e39ae762-d416-4095-8ba3-70c20d72739a.png">

Negatives are that dropdown options below common use cases require scrolling now, however I think this is fine given the priority of showing features that we support out the box on the left.

**Comment by Borda** [comment]
I like it and also I would make the landing page look more like our actual readme, have just double content list is not very useful
