### ISSUE TITLE
pytorch_lightning.utilities.exceptions.MisconfigurationException: Error while merging hparams: the keys <keys> are present in both the LightningModule's and LightningDataModule's hparams.

### ISSUE THREAD

**Issue by shivammehta007** [PyTorchLightning/pytorch-lightning#8716]
## 🐛 Bug

Hello everyone

I was using a `Namespace` object to save my hparams and was passing the same object to LightningModule and LightningDataModule. But after updating to Lightning 1.4.0 from 1.3.8, first I can no longer use `self.hparams = hparams` in LightningModule. So I change it to `self.save_hyperparameters(hparams)` but since I had same keys (as it is the same object). It throws this error:
```
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: Error while merging hparams: the keys <keys> are present in both the LightningModule's and LightningDataModule's hparams.
```

**What are the best practices to fix this? Any source code example for this?** 

@kaushikb11  suggested me on slack to open an issue with this, I already had a discussion for it as well at https://github.com/PyTorchLightning/pytorch-lightning/discussions/8695 but no updates so I too posted it here.

Kind Regards

### To Reproduce
We need a Lightning data loader and Hparams in a namespace or any dictionary type object.

https://colab.research.google.com/drive/1CVCiB6i6keO9dPzDClLzW8JZ0fRkr2K-?usp=sharing

### Expected behavior

Before 1.4.0 at least in <= 1.3.8 I could save the hparams in LightningDataModule as self.hparams and everything ran with no issues, and ideally it should just take it too as I have to use self.hparams.batch_size or other hyperparameters later in LightningDataModule as well.

### Environment

```
* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.2
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.0+cu102
	- pytorch-lightning: 1.4.1
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.11
	- version:           #1 SMP Sat Jun 5 09:50:34 PDT 2021
```

### Additional context
If there is any other way which is a better way to do it please let me know regarding that as well.

**Comment by shivammehta007** [comment]
What are the best practices to do something like this, when you have hyperparameters for both LightningDataModule and LightningModule? I don't want to merge to one Lightning Module as I really like the abstraction of LightningDataModule.

**Comment by awaelchli** [comment]
@shivammehta007 If you are passing the same hparams container to both the datamodule and the lightning module there is no point in calling `save_hyperparameters()` in both because they are identical. So I suggest call hyperparameters only in the lightning module. Then you can see the logged hparams in the logger (if the logger you use supports that).

**Comment by shivammehta007** [comment]
Right I thought about it but also, I can no longer set self.hparams = hparams as well in the LightningDataModule

**Comment by shivammehta007** [comment]
For a Namespace object it throws `TypeError: 'Namespace' object is not iterable` but I guess then I can do `vars(hparams)` and it should solve the problem or is there any other better way for it? Thanks for the help :)

**Comment by awaelchli** [comment]
Yes I would recommend not passing directly a namespace into the model. Not saying it is bad but passing in a dict or a fixed number of arguments has the benefit that the module becomes independent of what argument parsing tool was used (namespace is from argparse library). So it can be more easily reused in places where there is maybe no argparser or a different configuration system.

**Comment by shivammehta007** [comment]
Thank you that solves my issues!
