### ISSUE TITLE
How to repeat the evaluation loop for multiple times 

### ISSUE THREAD

**Issue by marsggbo** [PyTorchLightning/pytorch-lightning#8718]
### Motivation

Suppose I've finished training the model, then I want to evaluate its performance in different situations, e.g., different input data sizes, different layers.

The pseudo code of original Pytorch looks like
```python
train_one_epoch(model , ...)
for setting in settings:
    r = validate_on_epoch(model, settings)
    ....
```

However, it seems that we cannot modify the loops.

### Alternatives

One possible solution I can think of so far is that I can implement the validation code in `training_epoch_end` function, for example

```python
class MyModel(pl.LightningModule)
    def training_epoch_end(self, outputs: List[Any]):
        acc = np.mean([output['acc'].item() for output in outputs])
        loss = np.mean([output['loss'].item() for output in outputs])
        self.log("train/loss", loss, on_step=False, on_epoch=True, sync_dist=False, prog_bar=False)
        self.log("train/acc", acc, on_step=False, on_epoch=True, sync_dist=False, prog_bar=False)

        for setting in settings:
            r = validate_on_epoch(model, settings)
```

Question 1: How can we adapt the above pseudo code to pytorch-light style?
Question 2: Can my alternative solution work when we use `ddp` or `horovod` mode?

Thanks!

**Comment by ananthsub** [comment]
@marsggbo you could call Trainer.validate to run one epoch of the validation data: https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html#validation
