### ISSUE TITLE
poetry + hydra

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#872]
## 🚀 Feature

It would be great to have hydra and poetry integrated within Pytorch Lightning.

**Comment by Borda** [comment]
@tchaton sounds good, could you pls add motivation or/and use-case how you would like to use it?

**Comment by tchaton** [comment]
Hey @Borda , I used pytorch-lightning for two on my previous projects and I chosed not to use it for my latest one.
I felt it was missing some flexibility, due to having one logic template for both model and dataset.

We are using hydra for the configuration and poetry for package management.

Here is the project: https://github.com/nicolas-chaulet/deeppointcloud-benchmarks.
I think we have an interesting architecture for managing ML research projects. Please, have a look :)

Best,
Thomas Chaton.

**Comment by Borda** [comment]
There is already similar suggestion, so please continue the discussion in #807
