### ISSUE TITLE
Deprecate LightningModule.get_progress_bar_dict

### ISSUE THREAD

**Issue by ananthsub** [PyTorchLightning/pytorch-lightning#8742]
## 🚀 Feature

Deprecate this method off the LightningModule and move this to the ProgressBar callback:
https://github.com/PyTorchLightning/pytorch-lightning/blob/efec3d461c38e00c4db36acecf946ac45e08b0e1/pytorch_lightning/core/lightning.py#L1772-L1818

### Motivation

We are auditing the Lightning components and APIs to assess opportunities for improvements:
- https://docs.google.com/document/d/1xHU7-iQSpp9KJTjI3As2EM0mfNHHr37WZYpDpwLkivA/edit#
- https://github.com/PyTorchLightning/pytorch-lightning/issues/7740

Moving this logic to the progress bar callback is far more natural:
- Customization for the progress bar display should sit inside the ProgressBar class, not inside the LightningModule
- The Callback API already has access to both the Trainer and LightningModule, so it can combine properties of both. The progress bar can access the available progress bar metrics from the Trainer, and filter down or supplement with additional keys to display
- This reduces the non-ML modeling surface area of the LightningModule cleaner, making it more focused
- This helps separate the LightningModule & Trainer APIs: https://github.com/PyTorchLightning/pytorch-lightning/issues/7315

### Pitch

- Offer corresponding utilities on the progress bar callback to filter/enrich the metrics used for the TQDM display
- Deprecate this method in v1.5
- Remove this method in v1.7

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by daniellepintz** [comment]
I am interested in working on this, could you please assign it to me?

**Comment by kaushikb11** [comment]
@ananthsub @daniellepintz I liked the idea to have `get_progress_bar_dict` accessible within the `LightningModule`.

For instance a few months back, I had created a `CustomLightningModule` subclassing the `LightningModule`. And I wished to customize the keys in the `progress_bar_dict` as well.

The method was pretty helpful in that case.

**Comment by ananthsub** [comment]
> @ananthsub @daniellepintz I like the idea to have `get_progress_bar_dict` accessible within the `LightningModule`.
> 
> 
> 
> For instance a few months back, I had created a `CustomLightningModule` subclassing the `LightningModule`. And I wished to customize the keys in the `progress_bar_dict` as well.
> 
> 
> 
> The method is pretty helpful in that case, rather than having it in the Callback.

@kaushikb11 imo that means we need to make it easier for people to customize the progress bar callback as part of the progress bar design & implementation. It shouldn't be part of the lightning module. 

The support here for the progress bar is an anomaly. For instance, we don't offer the same ability for the lightning module to customize what metrics the trainer's profiler records. That customization ought to be part of the profiler.

**Comment by daniellepintz** [comment]
@ananthsub I agree
