### ISSUE TITLE
Make default implementation for train_dataloader in DataHooks raise NotImplementedError

### ISSUE THREAD

**Issue by ananthsub** [PyTorchLightning/pytorch-lightning#8752]
### Discussed in https://github.com/PyTorchLightning/pytorch-lightning/discussions/8734

We are auditing the Lightning components and APIs to assess opportunities for improvements:
- https://docs.google.com/document/d/1xHU7-iQSpp9KJTjI3As2EM0mfNHHr37WZYpDpwLkivA/edit#
- https://github.com/PyTorchLightning/pytorch-lightning/issues/7740

The default implementation for these is logging a warning that nothing is implemented. https://github.com/PyTorchLightning/pytorch-lightning/blob/963c26764682fa4cf64c93c5a7572ae0040e9c32/pytorch_lightning/core/hooks.py#L529

The current default implementation logs a warning, which can be lost, and which forces the framework to perform is_overridden checks. Instead, having the default implementation raise a NotImplementedError will make errors clear to users in case users forget to implement these hooks.

This applies for all the dataloader hooks in DataHooks, not just train_dataloader

**Comment by Arnab1181412** [comment]
Sir can i work on this issue as I am a new contributor to open source.

**Comment by ananthsub** [comment]
> Sir can i work on this issue as I am a new contributor to open source.

Definitely! Go ahead 😄

**Comment by Arnab1181412** [comment]
Sir as I am new so can you give me a bit context about the problem what I understand from the issue is that instead of giving warning when users forget to use hooks I should raise a NotImplementedError

**Comment by Tshimanga** [comment]
@ananthsub this issue _looks_ orphaned, and I'm keen to pick it up; but I wanted to check in first since @Arnab1181412 had initially volunteered. I want to be cognizant of any potential etiquette and not step on any toes 🙏🏽

**Comment by ananthsub** [comment]
> @ananthsub this issue _looks_ orphaned, and I'm keen to pick it up; but I wanted to check in first since @Arnab1181412 had initially volunteered. I want to be cognizant of any potential etiquette and not step on any toes 🙏🏽

Please go ahead! Thank you for checking :)

**Comment by Tshimanga** [comment]
@ananthsub so the ticket states `This applies for all the dataloader hooks in DataHooks, not just train_dataloader`, but based on the docstrings on all the other dataloader hooks `{val, test, predict}_dataloader` are intentionally optional hooks whose presence is not necessary to run the `Trainer`. Is the assertion here that users will be required to override all of these dataloader hooks?
https://github.com/PyTorchLightning/pytorch-lightning/blob/de57feff445744f431eaef29182b1bcbf58a1924/pytorch_lightning/core/hooks.py#L649-L651
https://github.com/PyTorchLightning/pytorch-lightning/blob/de57feff445744f431eaef29182b1bcbf58a1924/pytorch_lightning/core/hooks.py#L597-L599

Surprisingly the docstring for the `predict_dataloader` doesn't explicitly say that it's optional but I've never overridden it in my projects 😅

**Comment by awaelchli** [comment]
There is a problem. The IDEs now show that the LightningModule is an abstract class and complains that we must implement all abstract methods (train_dataloader etc.). But these are obviously not mandatory. 

![image](https://user-images.githubusercontent.com/5495193/132434521-afd7b480-0c80-44fd-ae17-f1c4065029a8.png)

We should fix this

**Comment by ananthsub** [comment]
@awaelchli does removing ABC from the LightningModule's inheritance resolve this? https://github.com/PyTorchLightning/pytorch-lightning/blob/91ce0d0a99ec0a488e04e09997f6dd662ce217cd/pytorch_lightning/core/lightning.py#L56

**Comment by awaelchli** [comment]
no, since raising `NotImplementedError` will make the class abstract anyway. See also #9499 who is attempting to do that.

**Comment by awaelchli** [comment]
Given the documentation and recommended usage of [NotImplementedError here](https://docs.python.org/3/library/exceptions.html#NotImplementedError), we should consider raising a different error.

**Comment by ananthsub** [comment]
> no, since raising `NotImplementedError` will make the class abstract anyway. See also #9499 who is attempting to do that.

huh, I thought these would have to be marked with `@abstractmethod` decorators for the IDE to raise a warning

**Comment by justusschock** [comment]
@ananthsub you are correct afaik. 

@awaelchli the difference is that for classes that inherit `ABC` (or have `ABCMeta` as metaclass) cannot be instantiated as long as there is at least one method marked as `abstractmethod`

**Comment by carmocca** [comment]
This is caused by a bug in PyCharm: https://github.com/PyTorchLightning/pytorch-lightning/pull/9529#discussion_r709156055

**Comment by carmocca** [comment]
Here's another issue about an user complaining about this: https://github.com/PyTorchLightning/pytorch-lightning/issues/10667

@justusschock proposed the following alternative:

> An alternative could be to return None here and then raise a RuntimeError inside the trainer when data is None

**Comment by carmocca** [comment]
And one more: https://github.com/PyTorchLightning/pytorch-lightning/issues/12176

**Comment by awaelchli** [comment]
I wanted to fix this a while ago with #9529. We can reconsider?

**Comment by carmocca** [comment]
I'd say yes since it seems like it's important to users.
