### ISSUE TITLE
rename `master*` properties in cluster environments to `main*`

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#8774]
## 🚀 Feature

Refactor our internal language for [master port and master address]( https://github.com/PyTorchLightning/pytorch-lightning/blob/cc036155d482c9dbdc7a0d8a0be34696f314e192/pytorch_lightning/plugins/environments/cluster_environment.py#L29) in the cluster environments and accelerators.

### Motivation

Inclusive language

### Pitch

rename to `main_address` and `main_port`

### Alternatives

other name suggestions welcome

### Additional context

Lightning may also rename "master" branch to "main" soon.

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>
``

**Comment by awaelchli** [comment]
This may be combined with #6303 where we propose to make the methods properties.

**Comment by Arnab1181412** [comment]
Sir can I work on this issue I'm a new contributor

**Comment by awaelchli** [comment]
Yes, that would be great! 
Here is what I had in mind we need to do:

1. Deprecate `master_address()` and `master_port()` method
2. Add new properties main_address and main_port
3. Replace all occurrences in Lightning with new calls

Feel free to send a PR for these items and let me know if you have any questions :) 
You can find the contributing guide here: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md

**Comment by alli1999** [comment]
Hi could I contribute in this too? It would be my first contribution

**Comment by bamblebam** [comment]
The kubeflow and other environments also have master properties in them so maybe we should try and change them too

**Comment by awaelchli** [comment]
@alli1999 If @Arnab1181412 didn't start yet (it does not seems so) feel free to take it. 
Yes @bamblebam it needs to be renamed everywhere (simple find and replace) 

See my comment above for directions

**Comment by alli1999** [comment]
Sure I'll work on it. We just replace master_address() and master_port() with main_address() and main_port()

**Comment by alli1999** [comment]
I've done the changes to all the methods. Should I create a pr?

**Comment by awaelchli** [comment]
@alli1999 Yes. You can go to the tab on top here "Pull Requests" and you should see a button to open it. Then read the template and fill it out. Then me and the other members will review the changes and help you finish it.
Thanks for your help.
