### ISSUE TITLE
Fetch GPU stats using torch.cuda.memory_stats

### ISSUE THREAD

**Issue by edward-io** [PyTorchLightning/pytorch-lightning#8780]
## 🚀 Feature

(as discussed in https://github.com/PyTorchLightning/pytorch-lightning/discussions/7518)

Gather GPU stats using torch.cuda.memory_stats instead of nvidia-smi for GPUStatsMonitor.

### Motivation

Some machines do not have nvidia-smi installed, so they currently are unable to gather data using the GPUStatsMonitor callback, which is useful for detecting OOMs and debugging their models.

### Pitch

For users using PyTorch version >= 1.8.0, use [torch.cuda.memory_stats](https://pytorch.org/docs/stable/generated/torch.cuda.memory_stats.html) to gather memory data instead of invoking the nvidia-smi binary. 

Some fields (fan_speed, temperature) that are logged in GPUStatsMonitor are not available from torch.cuda.memory_stats. We can either 1) use nvidia-smi as a fallback if a user requests those fields or 2) Remove those fields if we see that they aren’t being used anywhere and don’t consider them useful anymore.

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by ananthsub** [comment]
this will be great to expand memory stats availability! 
@edward-io what do you propose for the utilities here, especially the `mode` argument? https://github.com/PyTorchLightning/pytorch-lightning/blob/e54180363663b690367f0051484650fcd12e5de2/pytorch_lightning/utilities/memory.py#L102-L157

I think checking the PyTorch version, preferring `torch.cuda.memory`, and falling back to nvidia-smi if available makes sense. 

Closely related is `log_gpu_memory` as an argument on the Trainer constructor. If set, the Trainer instantiates a GPUStatsMonitorCallback. IMO, we ought to deprecate this parameter from the Trainer constructor, as `min_max` is an implementation choice for nvidia-smi, but it bears no relation to `torch.cuda.memory_stats`. But we can discuss this in a separate issue. It's closely related to the discussion here: https://github.com/PyTorchLightning/pytorch-lightning/issues/8478#issuecomment-884577276

**Comment by edward-io** [comment]
Thanks for catching that - I'm thinking that we can keep `get_memory_profile` as is, with the `mode` argument, as long as we return the same output for `get_gpu_memory_map`.

**Comment by daniellepintz** [comment]
@edward-io have you already started working on this/do you plan to, or should I go ahead and include this in my PR for #9032?

**Comment by carmocca** [comment]
Done in #9586
