### ISSUE TITLE
fitting model after pl.to_torchscript fails

### ISSUE THREAD

**Issue by pedrozudo** [PyTorchLightning/pytorch-lightning#8784]
So I am working with pytorch-lightning and torchscript, where I have a set up similar to the following:

```python
class MyModel(pl.LightningModule):
    def __init__(self, *args):
        super(MyModel, self).__init__()
        ...

model = MyModel(some_arguments)
model.to("cuda") #not really important

dim_inputs = (1,10,10)
dummy_input = torch.rand(dim_inputs)

print(isinstance(model, pl.LightningModule)) #prints True
model = model.to_torchscript(method="trace", example_inputs=dummy_input)
print(isinstance(model, pl.LightningModule)) #print false


trainer = pl.Trainer(gpus=1)
trainer.fit(model)
```

This then gives the following error:

```bash
  File "/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in fit
    self._run(model)
  File "/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 850, in _run
    self.config_validator.verify_loop_configurations(model)
  File "/python3.9/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 34, in verify_loop$configurations
    self.__verify_train_loop_configuration(model)
  File "/lib/python3.9/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 49, in __verify_tr$in_loop_configuration
    has_training_step = is_overridden("training_step", model)
  File "/python3.9/site-packages/pytorch_lightning/utilities/model_helpers.py", line 45, in is_overridden
    raise ValueError("Expected a parent")

```

So the error happens while checking that the `LightningModule` is setup correctly when doing the `model.fit`. It basically checks that the module is indeed a `LightningModule`. This it where it fails. Somehow the `to_torchscript` makes the model lose the information that it was subclassed from pl.LightningModule.

**Comment by ananthsub** [comment]
`to_torchscript` returns a ScriptModule, which you're re-assigning to your LightningModule: https://github.com/PyTorchLightning/pytorch-lightning/blob/e54180363663b690367f0051484650fcd12e5de2/pytorch_lightning/core/lightning.py#L1902-L1908

therefore, `model` is no longer a `LightningModule` which is why trainer.fit() no longer works.

**Comment by pedrozudo** [comment]
Yeah, I figured that `to_torchscript` does not return a LightningModile. I was wondering whether this was the desired behavior? And if yes, is it then also desired not to be able to use `.fit` on it. I could image then `to_torchscript` return an object on which `.fit ` can be used. Maybe don't remove the bug tag just yet?


About what I want to do: I got a messy python script that gives me the computation graph. Now that graph is quite big, so re-constructing the whole thing for each forward pass means that the python part of the forward pass is just taking too long. I want to compile that graph and reuse, instead of reconstructing it for every forward pass during training.

**Comment by ananthsub** [comment]
> Yeah, I figured that to_torchscript does not return a LightningModile. I was wondering whether this was the desired behavior? And if yes, is it then also desired not to be able to use .fit on it. I could image then to_torchscript return an object on which .fit can be used. Maybe don't remove the bug tag just yet?

The desired behavior is to export the contents of the LightningModule to script modules. It's not intended for the Trainer to work with arbitrary ScriptModules for fitting, the same way the Trainer doesn't work with arbitrary nn.Modules for training. The input to the Trainer for fitting must be a LightningModule. 

> About what I want to do: I got a messy python script that gives me the computation graph. Now that graph is quite big, so re-constructing the whole thing for each forward pass means that the python part of the forward pass is just taking too long. I want to compile that graph and reuse, instead of reconstructing it for every forward pass during training.

Inside your LightningModule, you can script the relevant parts of your computation graph once before training starts. These scripted modules can be inside your LightningModule, so you can call Trainer.fit() as you would normally. 

```
class MyModel(pl.LightningModule):
    def __init__(self, *args):
        super(MyModel, self).__init__()
        # torchscript your nn.Modules here with the PyTorch torch.jit.script/trace choices
        
    def training_step(self, *args, **kwargs):
        # Use your scripted modules here
        ...

model = MyModel(some_arguments)
trainer = pl.Trainer(gpus=1)
trainer.fit(model)
```

**Comment by pedrozudo** [comment]
> The desired behavior is to export the contents of the LightningModule to script modules. It's not intended for the Trainer to work with arbitrary ScriptModules for fitting, the same way the Trainer doesn't work with arbitrary nn.Modules for training. The input to the Trainer for fitting must be a LightningModule.

I agree it should not work with arbitrary SciptModules but maybe introducing a new class, e.g. LightningScriptModules, would do the trick. 

> Inside your LightningModule, you can script the relevant parts of your computation graph once before training starts. These scripted modules can be inside your LightningModule, so you can call Trainer.fit() as you would normally.

Indeed, this would have been my first alternative now too.


Anyways, thanks for the quick reply!
