### ISSUE TITLE
Set GPU exclusive mode

### ISSUE THREAD

**Issue by ifsheldon** [PyTorchLightning/pytorch-lightning#8794]
## 🚀 Feature

Provide a function that enables GPU exclusive mode.

### Motivation

When I try to test different models with different hyperparameters, I want one `Trainer` to fully occupy some of my GPUs. Now I have two models to train, and I want them trained separately on two GPUs. So, I did something like
```python
trainer = pl.Trainer(
        gpus=1,
        auto_select_gpus=True,
    )  # 1
```
But when I run two instances of my training script, `pl` will always select the GPU-0 even if only one training instance can have one GPU run at 100%. Then I have to do something like this
```python
trainer = pl.Trainer(
        gpus="0", # or "1"
        auto_select_gpus=True,
    )
```
but `pl` gives me a deprecation warning. I can set a GPU availability scope of course, but it's basically the same as `gpus="0"`. My intention was to have `pl` to automatically select one **idle** GPU (instead of a GPU that has enough memory even if it's busy) to train my model. Then I think it's probably `pl` doesn't set the exclusive mode, so the `# 1` block doesn't behave as I expected.

### Pitch
I was thinking something like:

```python
trainer = pl.Trainer(
        gpus=1,
        auto_select_gpus=True,
        exclusive=True
    ) 
```
then if a training instance is running, another new training instance will be forced to find another GPU.

### Alternative
Something like this seems also great
```python
trainer = pl.Trainer(
        gpus=1,
        auto_select_gpus="idle", # or "memory-fit" or False
    ) 
```

### Additional context
My `pytorch-lightning` is `1.4.1`.

Can you please explain more on the `gpus` behaviour in `1.5` and later?  Can you also add more explanation or a link when showing the deprecation warning?

The deprecation warning is 
```shell
LightningDeprecationWarning: Parsing of the Trainer argument gpus='1' (string) will change in the future. In the current version of Lightning, this will select CUDA device with index 1, but from v1.5 it will select gpus [0] (same as gpus=1 (int)).
```

**Comment by awaelchli** [comment]
> Can you please explain more on the gpus behaviour in 1.5 and later? Can you also add more explanation or a link when showing the deprecation warning?

`Trainer(gpus=n)` where n is an integer is selecting the GPUs with indices [0, 1, ..., n-1] (the first n GPUs). 
However, in PL < 1.5 when n is a string it doesn't behave like that and instead it was choosing GPU index n. This is not consistent and is therefore changed to be equivalent with the int type. So in PL 1.5 and higher, `Trainer(gpus=3)` will be the same as `Trainer(gpus="3")` and will select three GPUs.

**Comment by awaelchli** [comment]
@ifsheldon don't you think it's better to let the user set the compute mode on the GPU themselves with nvidia-smi? Since this is affecting the system globally, I think it's safer to let the user or admin set this. It anyway requires root privileges afaik. What do you think?

To clarify, currently, `auto_select_gpus` will select a GPU if torch can move a tensor to the device.

**Comment by ifsheldon** [comment]
If setting exclusive mode in `pl` is too intrusive, then the alternative seems good enough. The current behaviour of `auto_select_gpus` is same as `memory-fit` I think, but the problem is even if a GPU is running at 100% but having enough memory, `pl` will select it despite that another one is totally idle.

**Comment by awaelchli** [comment]
> The current behaviour of auto_select_gpus is same as memory-fit I think

No, actually not. As I tried to explain above, it will select a GPU if PL can move a tensor to the GPU, i.e., this tests if the GPU is in exclusive mode and running a job.

> And this problem will be worst after 1.5 because people cannot select GPUs manually by doing like gpus="1" and then they have to do it via setting CUDA environment variable.

That's not true. Manually selecting GPUs is still possible by providing a list of indices. This has not changed.

**Comment by ifsheldon** [comment]
> this tests if the GPU is in exclusive mode and running a job.

I don't know what you meant by "and" in "i.e., this tests if the GPU is in exclusive mode and running a job". Is it literally a logical `and` here? I just tried running two instances of training scripts, it turns out that after the first instance is running and GPU 0 is at 100%, then I run the same training script again, `pl` will run it on GPU 0 again.

The training code is the same as above.
```python
trainer = pl.Trainer(
        gpus=1,
        auto_select_gpus=True,
    )
```
If the "and" here is logical `and`, then this bahaviour is expected, although it was not my intention. If you meant that PL checks these two criteria and if one of the two fails, it will not move a tensor to the GPU, then it's a bug now I suppose.

**Comment by awaelchli** [comment]
From your screenshot, we can see your GPU is in default mode (middle on the right). It means it allows to run multiple processes per GPU. You can set it to exclusive mode with `nvidia-smi -q 3 -i 0`  I believe.

[Here is the code](https://github.com/PyTorchLightning/pytorch-lightning/blob/a64cc373946a755ce6c3aef57c1be607dfe29a0c/pytorch_lightning/tuner/auto_gpu_select.py#L52) where PL checks if it can move a tensor: 

```python
for i in range(torch.cuda.device_count()):
        if i in exclude_gpus:
            continue
        # Try to allocate on device:
        device = torch.device(f"cuda:{i}")
        try:
            torch.ones(1).to(device)
        except RuntimeError:
            continue
        return i
```

**Comment by awaelchli** [comment]
> And it is not even "memory-fit" mode. I think a better solution will be as my proposed alternative. In "memory-fit" mode, PL checks if it can allocate a tensor of the same number of parameters of a model on a GPU. In "idle" mode, PL checks if a GPU is busy right now.

It's a good suggestion, but unfortunately it won't work. The model parameters alone on the device are not determining how much memory will be used during training, as it is the full forward and backward pass plus optimizer states that make the most of the memory consumption. Running two trainings on the same device with tight memory is dangerous. Either of the trainings could fail due to OOM. I do not recommend this approach unless user can reliably know their memory consumption.

**Comment by ifsheldon** [comment]
> Running two trainings on the same device with tight memory is dangerous

Yeah, I agree, but now PL doesn't check anything except the exclusive mode, which is worst. 

Alternatively, we can call the current mode as "fit-in" or something and give warning about the potential memory issues. Besides, we should have an "idle" mode, which checks if a GPU is busy, like running at >=80%.
