### ISSUE TITLE
Record iteration speed with `Trainer` and automatically pass to loggers

### ISSUE THREAD

**Issue by EricWiener** [PyTorchLightning/pytorch-lightning#8817]
## 🚀 Feature
Currently, users are required to track iteration speed themselves. It seems like a common use case to want to display iteration speed/sec in the logging UI of choice (ex. `tensorboard`), so it would be very nice if the `Trainer` could automatically record the iteration speed/sec and pass it to a logger.

### Motivation
I am currently implementing a callback to track iteration speed and it is quite a lot of code for such a small task.

### Pitch
Add a flag to the Trainer to automatically track iteration speed and pass this information to the specified logger.

Ex:
```
trainer = Trainer(..., log_iteration_speed = True, logger = tb_logger)
```

and then the Tensorboard would have plots for `iter:sec/train`, `iter:sec/validation`, `iter:sec/test`, etc. I recommend `iter:sec` vs. `iter/sec` because tensorboard groups plots into sections if there are `/`.

The user can then choose to add these metrics to the hparams section of the tensorboard. This would require that the keys used for logging be exported for public consumption.

### Alternatives
Instead of logging to a tensorboad, the `Trainer` could print out an average iter/sec per split at the end of training. However, this is an issue if the user manually kills the fitting process and then the average iter/sec won't be printed.

### Additional context
https://pytorch-lightning.slack.com/archives/CRBLFHY79/p162843593629850

**Comment by dongzhuoyao** [comment]
any update about this feature?
