### ISSUE TITLE
simplification over all kinds of "path" settings

### ISSUE THREAD

**Issue by marsggbo** [PyTorchLightning/pytorch-lightning#882]
I'm lost in all kinds of "path" settings, could it be more simpler?

Across the source code and examples, I find that there are many types of "path" config, such as the path in `ModelCheckpoint`, `logger`, and `default_save_path` in trainer.

Could you please explain these path configs in more detail? For example, if we set `default_save_path`, how does it influence other path configs?

**Comment by hadim** [comment]
I agree this kind be confusing. I am trying to unify the callback system and also try to merge this with the loggers.

In that spirit, I have added a property in `Callback` to retrieve what I would call the "training base directory": https://github.com/PyTorchLightning/pytorch-lightning/pull/889/files#diff-c2e9d63e89e5e7cc3384083af905407dR29

By default, all callbacks should use this path and only use the one provided in the init of the callback if it's different than `None`.

Callback that write on disk should also have a `prefix` arguments so all the files they write would go in `base_training_folder / prefix` (it can be a folder or a file).

Let me know what do you think.

**Comment by Borda** [comment]
@marsggbo good suggestion, we shall keep the API simple and easy to navigate...
Would you consider sending a PR with such simplification so we may have a concrete discussion over each case?

**Comment by marsggbo** [comment]
@Borda Hello, thank you for this great project!

Actually, I'm not familiar with the code details. However, I implement a framework, namely [**torchline**](https://github.com/marsggbo/torchline), based on pytorch-lightning.  In **torchline**, all configuration can be set in a single `yaml` file by using **[yacs](https://github.com/rbgirshick/yacs)** lib. I think that it may further simplify the code quantity and improve the code reusability.

To keep the path consistency, we do some preprocessing when initializing the config, refering to [torchline/config/config.py](https://github.com/marsggbo/torchline/blob/master/torchline/config/config.py).

hope it can help you.

**Comment by Borda** [comment]
Good suggestion, could you pls participate in #807 ?
