### ISSUE TITLE
Allow `--gpus=None` to be specified on the CLI.

### ISSUE THREAD

**Issue by Erotemic** [PyTorchLightning/pytorch-lightning#8823]
Currently specifying `--gpus=None` breaks the utils.argparse logic. I want to allow the string None to be a valid option. In other words, I want the user to be able to explicitly specify the default value for this argument, which is currently not possible.

Why? In my workflow I customized my argparser. This caused the `--gpus` argument to default to something non-None. Then, for whatever reason, my nvidia drivers stopped working (as they sometimes do), so I wanted to fallback on the CPU. When I tried to set `--gpus=None` argparse balked at me because it was not a valid gpu option. But removing the `--gpus` option no longer defaulted to None. Therefore, there was no way for the user to overwrite my short-sighted defaults and simply get the CPU.

If the only way to set the value of an argument is by removing the specification, then that can cause issues like the one I had. Regardless, I think it is good design such that you can always _change_ the value of an argument to achieve a particular funtionality. 

As an example say I have a script:

```bash
python fit.py \
    --gpus=1 \
    --num_workers=2 
```

the diff from the above to the CPU version where it removes the line:

```bash
python fit.py \
    --num_workers=2 
```

no longer gives a reader any indication that a --gpus option was ever there, or is something that could be specified and changed, whereas 

```bash
python fit.py \
    --gpus=None \
    --num_workers=2 
```

Preserves the original `--gpus` arg as something important that this script might vary. (It also makes it much eaiser to futher parametarize that argument in bash itself). I believe that having the option to simply change the value rather than being forced to remove the entire line is desirable.

**Comment by awaelchli** [comment]
@Erotemic in your use case what is the advantage of None over just setting gpus=0?

**Comment by Erotemic** [comment]
Well, now I feel silly.

I'm so used to setting the specific device I want to use, I didn't even consider that. It still feels a little weird that the user can't set the argument explicitly to the default, but as long as 0 is effectively the default, then I'm happy enough to close the issue and PR. No need to add complexity when its not needed.
