### ISSUE TITLE
SaveConfigCallback errors out when default_root_dir is an S3 path

### ISSUE THREAD

**Issue by thecooltechguy** [PyTorchLightning/pytorch-lightning#8843]
## 🐛 Bug

Hi, when running PL Lightning using an S3 `default_root_dir` in the Trainer (while using the `LightningCLI`), I’m getting the following error:
```
Traceback (most recent call last):
File "train.py", line 56, in <module>
trainer_defaults=trainer_defaults
File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/utilities/cli.py", line 289, in __init__
self.fit()
File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/utilities/cli.py", line 432, in fit
self.trainer.fit(**self.fit_kwargs)
File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in fit
self._run(model)
File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 865, in _run
self._call_setup_hook(model) # allow user to setup lightning_module in accelerator environment
File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1170, in _call_setup_hook
self.setup(model, stage=fn)
File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/callback_hook.py", line 52, in setup
callback.setup(self, model, stage=stage)
File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/utilities/cli.py", line 191, in setup
self.parser.save(self.config, config_path, skip_none=False, overwrite=self.overwrite)
File "/opt/conda/lib/python3.6/site-packages/jsonargparse/core.py", line 811, in save
path_fc = Path(path, mode='fc')
File "/opt/conda/lib/python3.6/site-packages/jsonargparse/util.py", line 446, in __init__
raise TypeError(ptype+' is not creatable since parent directory does not exist: '+abs_path)
TypeError: File is not creatable since parent directory does not exist: /app/s3://some_s3_path/lightning_logs/version_0/config.yaml
```
This error goes away if I add `save_config_callback=None` to the `LightningCLI` , so I think this may be a bug with the CLI saving the config callback, when the Trainer’s `default_root_dir`  points to an S3 path.

### To Reproduce
Any training script that uses `LightningCLI` and an S3 based `default_root_dir` will cause the `SaveConfigCallback` to fail.

### Expected behavior

The `SaveConfigCallback` object works with S3 based Trainer `default_root_dir` values.

**Comment by awaelchli** [comment]
strange, in theory this should work since we have a makedirs call here with fsspec: 
https://github.com/PyTorchLightning/pytorch-lightning/blob/b47e3ab7ce171ced7b9d807bbca6062cd6b5c97e/pytorch_lightning/utilities/cli.py#L187

I believe you need to install this extension: 

```
pip install pip install fsspec[s3]
```


Can you check what gets returned when you do

```python
from pytorch_lightning.utilities.cloud_io import get_filesystem
fs = get_filesystem("path/to/your/s3/folder")
```
?

**Comment by thecooltechguy** [comment]
Hi @awaelchli , thanks for your help and sorry for the delay in my response! The S3 integration in general works (e.g., model check-pointing to S3, S3 root dirs also work without the SaveConfig callback, etc.).

In the below code excerpt from Lightning, `config_path` and `log_path` are both valid and correct/expected S3 paths at runtime (which I confirmed with `print` statements):

```python
if trainer.is_global_zero:
    # save only on rank zero to avoid race conditions on DDP.
    # the `log_dir` needs to be created as we rely on the logger to do it usually
    # but it hasn't logged anything at this point
    get_filesystem(log_dir).makedirs(log_dir, exist_ok=True)
    self.parser.save(self.config, config_path, skip_none=False, overwrite=self.overwrite)
```
However, I think the issue arises because in the last line (`self.parser.save(...)`), `self.parser` is a `LightningArgumentParser` object that extends from `jsonargparse`'s `ArgumentParser`, but doesn't override its `save` method (see https://github.com/omni-us/jsonargparse/blob/45996d88e9026e345fd10d4f6bf46859cc243ca3/jsonargparse/core.py#L781). And since the `jsonargparse`'s `ArgumentParser`'s save method assumes a local filesystem, it is unable to write to S3.

**Comment by awaelchli** [comment]
@thecooltechguy I don't think we should override their save method. 

@carmocca @mauvilsa what do you say?

a) override their save function
b) open a feature request in jsonargparse
c) not support it

or something else.

**Comment by carmocca** [comment]
Since `jsonargparse` already supports reading config files off s3, I think it's fair for it to implement writing to s3 too.

https://github.com/omni-us/jsonargparse/blob/df466645f64a4fdd5983197ca6fe28ca38126d04/jsonargparse/optionals.py#L112-L117

Otherwise, it could refactor the `parser.save` function so we don't have to override it entirely, just the data writing parts. Then it would be easy for us to override those as we already subclass their `ArgumentParser`

https://github.com/PyTorchLightning/pytorch-lightning/blob/13e64e6a80bc19308e99ff6aedb95ad68968b5b8/pytorch_lightning/utilities/cli.py#L37

**Comment by mauvilsa** [comment]
I think best if it is added to jsonargparse.

**Comment by thecooltechguy** [comment]
Awesome, sounds good! Thanks!

**Comment by mauvilsa** [comment]
@thecooltechguy could you please try out #9073 with the current master version of jsonargparse.
