### ISSUE TITLE
Nightly XLA + Lightning Issue

### ISSUE THREAD

**Issue by david-littlefield** [PyTorchLightning/pytorch-lightning#8863]
## 🐛 Bug

`pt-xla-profiler: TransferFromServerTime too frequent: 314 counts during 80 steps
pt-xla-profiler: Op(s) not lowered: aten::sgn_out,  Please open a GitHub issue with the above op lowering requests.`

It takes longer to train an epoch with TPUs on Colab using 8 cores than my 1080 ti 11GB GPU. I've been stumbling my way through using the TPU in PyTorch Lightning. I was able to identify a bottleneck thanks to an answer that was posted by @kaushikb11. However, I don't know where to go from here.

### To Reproduce

Run the [notebook](https://colab.research.google.com/drive/1t0kgqnugEeMopBmQDZ7EzvnHjBPcjC1l?usp=sharing) in Coab.

### Expected behavior

Train the model faster than my 1080 ti 11GB GPU.

### Environment

* CUDA:
	- GPU:
	- available:         False
	- version:           10.2
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.0+cu102
	- pytorch-lightning: 1.4.2
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.11

**Comment by kaushikb11** [comment]
Hi @david-littlefield, as it is an issue of Operation(s) not being lowered for XLA, PyTorch XLA would be the right place to create an issue and discuss the support of those operations.

**Comment by david-littlefield** [comment]
Great, I'll do that. Thanks, @kaushikb11 !

**Comment by david-littlefield** [comment]
Ok, so PyTorch XLA added `sgn` to their implementation but the bottleneck still comes up in PyTorch Lightning. Is there a way to track down where and why the issue is occuring?

**Comment by david-littlefield** [comment]
@Borda @kaushikb11 I've been informed that the current issue seems to be coming from PyTorch Lightning and that I may need to install the nightly version of PyTorch Lightning. However, I searched through the readme, docs, and issues section but I didn't see anything mentioned about a nightly version of PyTorch Lightning. Any suggestions?

```
Traceback (most recent call last):
  File "/content/nuwave/trainer.py", line 1, in <module>
    from lightning_model import NuWave
  File "/content/nuwave/lightning_model.py", line 9, in <module>
    import pytorch_lightning as pl
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/classification/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics, void
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/utils.py", line 29, in <module>
    from pytorch_lightning.utilities import rank_zero_deprecation
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/apply_func.py", line 27, in <module>
    from pytorch_lightning.utilities.imports import _compare_version, _TORCHTEXT_AVAILABLE
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/imports.py", line 93, in <module>
    from pytorch_lightning.utilities.xla_device import XLADeviceUtils  # noqa: E402
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/xla_device.py", line 23, in <module>
    import torch_xla.core.xla_model as xm
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/__init__.py", line 101, in <module>
    import _XLAC
ImportError: /usr/local/lib/python3.7/dist-packages/_XLAC.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl20is_contiguous_customENS_12MemoryFormatE
```

**Comment by kaushikb11** [comment]
Hi @david-littlefield, I have commented on the XLA Github [issue](https://github.com/pytorch/xla/issues/3080#issuecomment-908885800). Could you try those steps out and give us an update?

**Comment by Borda** [comment]
@david-littlefield thank you for sharing this trace with us, however, the trace leads to the XLA package...

**Comment by david-littlefield** [comment]
Thanks, @Borda. I'm still pretty new to this kind of thing so please excuse my naivety on the subject 😅. PyTorch XLA has added `sgn` implementation to their nightly release. I'm trying to figure out how to make it work with PyTorch Lightning. I don't know where to go from here. @kaushikb11 is trying to help figure it out in the related PyTorch XLA issue.

**Comment by david-littlefield** [comment]
@Borda It doesn't seem like PyTorch Lightning is compatible with PyTorch XLA nightly. PyTorch XLA lowered the `sgn` operation in their nightly release about 3 weeks ago but we haven't been able to get it working in PyTorch Lightning. Thank you. for the time you have spent on this issue.
