### ISSUE TITLE
support for bf16 in lightning trainer

### ISSUE THREAD

**Issue by yuvalkirstain** [PyTorchLightning/pytorch-lightning#8874]
## 🚀 Feature

Many models (e.g. T5) were trained using `bf16`, and as such, using `fp16` results with `nans`. Now pytorch [ supports](https://github.com/pytorch/pytorch/issues/55374)  `bf16`. I think that supporting `bf16` is a must have feature (and due to my ongoing research that builds upon Pytorch Lightning it will be amazing if it will be integrated fast :) )

### Motivation

Many models (especially in NLP like T5) *cannot*  be trained with `fp16` when using pytorch-lightning. This makes some of them practically unusable (due to the memory consumption), and others just train slow. 

### Pitch

I want to pass an argument to the trainer that says `precision=bf16` and it will train it with `bf16`.

**Comment by leezu** [comment]
With https://github.com/pytorch/pytorch/pull/61002 and nccl https://github.com/pytorch/pytorch/pull/61799 the following patch can setup PL for bf16 training if the user calls `th.set_autocast_gpu_dtype(th.bfloat16)`. Adding a separate API that automatically calls `th.set_autocast_gpu_dtype(th.bfloat16)` based on a config option may be helpful.

```diff
modified   pytorch_lightning/plugins/precision/native_amp.py
@@ -42,6 +42,12 @@ class NativeMixedPrecisionPlugin(MixedPrecisionPlugin):
         model: 'pl.LightningModule',
         closure_loss: torch.Tensor,
     ) -> torch.Tensor:
+        if hasattr(torch, 'get_autocast_gpu_dtype') and torch.get_autocast_gpu_dtype() == torch.bfloat16:
+            from pytorch_lightning.core.lightning import warning_cache
+            warning_cache.warn(
+                "Skipping torch.cuda.amp.GradScaler() in NativeMixedPrecisionPlugin as torch.bfloat16 is used "
+            )
+            return super().pre_backward(model, closure_loss)
         closure_loss = self.scaler.scale(closure_loss)
         return super().pre_backward(model, closure_loss)
 
@@ -58,6 +64,8 @@ class NativeMixedPrecisionPlugin(MixedPrecisionPlugin):
                 f"native PyTorch amp and lbfgs are not compatible (optimizer {optimizer_idx})."
                 " To request, please file a Github issue in PyTorch and tag @mcarilli"
             )
+        if hasattr(torch, 'get_autocast_gpu_dtype') and torch.get_autocast_gpu_dtype() == torch.bfloat16:
+            return True  # make_optimizer_step outside of the precision plugin
         result = True
         if model.automatic_optimization:
             result = lambda_closure()
```

**Comment by leezu** [comment]
@yuvalkirstain apply above patch to pytorch-lightning AND in your training script, call `th.set_autocast_gpu_dtype(th.bfloat16)` before you begin training.

**Comment by leezu** [comment]
`th` refers to `torch`. You need pytorch version that includes https://github.com/pytorch/pytorch/commit/324673a537fc818527b8375700a9b95a83a00c92 If you do multi-gpu training, you need to compile pytorch from source should also apply the commits from https://github.com/pytorch/pytorch/pull/61799 before compiling

**Comment by carmocca** [comment]
Awesome @leezu !

Feel free to open a PR when that is available in a torch release.

**Comment by tchaton** [comment]
Hey @carmocca, what do you think about `Trainer(precision=torch.bfloat16)`.

**Comment by carmocca** [comment]
> what do you think about Trainer(precision=torch.bfloat16)

The problem with passing the torch dtype is that then users will expect to be able to pass any torch dtype, which is not supported right now
