### ISSUE TITLE
Best model path returns nothing and best model score is none

### ISSUE THREAD

**Issue by MeganClark-Robinson** [PyTorchLightning/pytorch-lightning#8900]
## 🐛 Bug

I am currently using lightning 1.5.0dev (Master) and configuring model checkpoint and doing the training as described in the docs. However, the checkpoint best_model_path returns nothing and the best_model_sccore is None.

### To Reproduce

 continues training
    # ------------------------
    checkpoint_callback = ModelCheckpoint(
        dirpath=f"{hparams.output_path}/checkpoints/",
        save_top_k=hparams.save_top_k,
        verbose=True,
        monitor=hparams.early_stopping_metric,
        mode='max',
        #prefix=hparams.name,
        filename=f'{{epoch}}-{{{hparams.early_stopping_metric}:.2f}}'
    )
    early_stop_callback = EarlyStopping(
        monitor=hparams.early_stopping_metric,
        min_delta=0.00,
        patience=3,
        mode='max')

    trainer = Trainer(
        #fast_dev_run=True,
        gpus=hparams.gpus,
        logger=logger,
        #fast_dev_run=hparams.fast_dev_run,
        min_epochs=hparams.min_epochs,
        max_epochs=hparams.max_epochs,
        #checkpoint_callback=checkpoint_callback,
        checkpoint_callback = True,
        resume_from_checkpoint=hparams.resume_from_checkpoint,
        callbacks=[early_stop_callback],
        weights_summary='full',
        num_sanity_val_steps=hparams.num_sanity_val_steps,
        log_every_n_steps=hparams.log_every_n_steps
    )
    # ------------------------
    # 4 START TRAINING
    # ------------------------

    trainer.fit(module)
    print(
        f"Best: {checkpoint_callback.best_model_score} | monitor: {checkpoint_callback.monitor} | path: {checkpoint_callback.best_model_path}"
        f"\nTesting..."
    )
    trainer.test(ckpt_path=checkpoint_callback.best_model_path)

**Comment by carmocca** [comment]
Hi @MeganClark-Robinson! 

The fastest way for us to be able to help you is if you can adapt [this script](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py) to reproduce the behaviour you are seeing.
Otherwise, it's really hard for us to help you by just looking at that snippet :)

It will also be helpful if you link to the docs you are following.

**Comment by ananthsub** [comment]
`checkpoint_callback` needs to be bassed to the `callbacks` argument in the trainer. from your script, it's not passed in anywhere, so its fields aren't populated

**Comment by MeganClark-Robinson** [comment]
> `checkpoint_callback` needs to be passed to the `callbacks` argument in the trainer. from your script, it's not passed in anywhere, so its fields aren't populated

Thank you so much for your help

**Comment by MeganClark-Robinson** [comment]
> Hi @MeganClark-Robinson!
> 
> The fastest way for us to be able to help you is if you can adapt [this script](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py) to reproduce the behaviour you are seeing.
> Otherwise, it's really hard for us to help you by just looking at that snippet :)
> 
> It will also be helpful if you link to the docs you are following.

Thank you so much. Actually I passed checkpoint_callback to callbacks argument and it works.
