### ISSUE TITLE
Specifying `--model.class_path` through CLI has unclear behaviour

### ISSUE THREAD

**Issue by dasayan05** [PyTorchLightning/pytorch-lightning#8916]
## 🐛 Bug / Unclear Behaviour

I have a doubt about order of arguments in command line when using `LightningCLI`. The following behaviour is quite strange/unclear to me. Even the docs do not talk much about this. It is mostly about the `model.class_path` attribute in `subclass_mode_* = True`.

### To Reproduce

Let's have this *super simplified* example `minimal.py`. Just notice the arguments of `BoringModel`'s constructor. Otherwise, the code doesn't do much.

```python
# minimal.py file
import pytorch_lightning as pl
from pytorch_lightning.utilities.cli import LightningCLI

class BoringModel(pl.LightningModule):

    def __init__(self, arg1: str = 'default', arg2: str = 'default') -> None:
        super().__init__()
        print(f'Instantiated with: arg1 = "{arg1}", arg2 = "{arg2}"')

    def training_step(self, batch, _):
        exit(0)

    def configure_optimizers(self):
        exit(0)

    def train_dataloader(self):
        exit(0)

if __name__ == '__main__':
    cli = LightningCLI(pl.LightningModule, subclass_mode_model=True, save_config_callback=None)
```

.. and a `config.yaml` file which we are gonna use with `--config`

```yaml
trainer:
  logger: false
  checkpoint_callback: false
model:
  class_path: minimal.BoringModel
  init_args:
    arg1: changed
    arg2: changed
```

1. This one is **as expected**

```bash
$ python minimal.py --config config.yaml --model.init_args.arg1 changed_again
Instantiated with: arg1 = "changed_again", arg2 = "changed"
...
```

2. But if I add `--model.class_path` with the exact same model specified in `config.yaml` (just overspecifying)

```bash
$ python minimal.py --config config.yaml --model.class_path minimal.BoringModel --model.init_args.arg1 changed_again
#                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Instantiated with: arg1 = "changed_again", arg2 = "default"
```
.. value of `arg2` fell **back to default** (??) Not even read from `config.yaml`.

3. If I **change the order** of the `model.class_path` argument in command line
```bash
python minimal.py --config config.yaml --model.init_args.arg1 changed_again --model.class_path minimal.BoringModel
#                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Instantiated with: arg1 = "default", arg2 = "default"
...
```
.. both **back to default** ?

At this point, my impression was that 
> whenever `--model.class_path ..` is specified in cmd line, it injects the default values in that exact position

For example, if we have this ..

`--config` -> `--model.class_path` -> `--individuals` order in command line, it translates to ..

`--config` -> `class defaults` -> `--individuals`

.. **BUT** then, how would you describe this ?

```bash
$ python minimal.py --model.class_path minimal.BoringModel --config config.yaml --model.init_args.arg1 changed_again
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Instantiated with: arg1 = "changed", arg2 = "changed"
...
```

by the *logic I assumed*, it should have been

```bash
Instantiated with: arg1 = "changed_again", arg2 = "changed"
```

**I really can't find a unifying rule about the ordering. Kindly explain.**

### Environment

- PyTorch Lightning Version: `master` branch
- PyTorch Version: 1.9.0
- Python version: 3.8
- OS: Linux

**Comment by carmocca** [comment]
This is an issue on `jsonargparse`, the parser behind the CLI. cc: @mauvilsa as the author.

**Comment by mauvilsa** [comment]
Configuring a subclass (in the example above `model`) requires setting a dictionary with both `class_path` and `init_args` entries. The    `--*.class_path` arguments is a recently added feature and currently it is implemented as setting `{"class_path": "..."}`, meaning that any previous `init_args` are discarded. It was implemented like this since the obvious use is to override the `class_path` which requires `init_args` to be discarded, otherwise args from a different class could be kept. For the next release of jsonargparse I will change it so that if the given `class_path` is the same as the previous one, then `init_args` are not discarded. Though note that this is an unusual use case since there is no reason for specifying again and again the same `class_path`.

**Comment by tchaton** [comment]
Dear @dasayan05,

This PR https://github.com/PyTorchLightning/pytorch-lightning/pull/8844 should this slightly simpler.

Best,
T.C

**Comment by dasayan05** [comment]
@mauvilsa Thank you for your reponse, it clears a bit of confusion but there is still a problem.

The problem is not only having same class in `--*.class_path` (the above behaviour appear in different subclasses too, see below example), but with the fact that the some `init_args` are getting discarded silently without the user realizing it. The following is quite a real example (with datamodule this time) of what users might want to do: I have two datamodules (two different datasets) with just their location being different (`dir` argument)

```python
# minimal.py
class DataModule_1(pl.LightningDataModule):
    def __init__(self, dir='.', augmentation=False):
        super().__init__()
        print(f'Dataset 1 in {dir} and augmentation {augmentation}')
        exit(0)

class DataModule_2(pl.LightningDataModule):
    def __init__(self, dir='.', augmentation=False):
        super().__init__()
        print(f'Dataset 2 in {dir} and augmentation {augmentation}')
        exit(0)

if __name__ == '__main__':
    cli = LightningCLI(..., datamodule_class=pl.LightningDataModule,
                       subclass_mode_data=True, save_config_callback=None)
```
```yaml
# config.yaml
data:
  class_path: minimal.DataModule_1
  init_args:
    dir: /path/to/dataset1
    augmentation: true
```

Now if user wants to quickly check on dataset 2, its quite reasonable (and tempting) for users to try the following:
```bash
$ python minimal.py --config config.yaml --data.class_path minimal.DataModule_2 --data.init_args.dir /path/to/dataset2
Dataset 2 in /path/to/dataset2 and augmentation False
```

.. but since it discards the `config.yaml` silently, the `augmentation` argument will fall back to default without user realizing it.

If `CLI` really wants this behaviour,
1. The docs must be more clear about the usage of `--*.data_class`
2. It can explicitly warn/error if user enters _incomplete specification_ of a new subclass

Secondly, I still don't understand the ordering of arguments. @mauvilsa said

> any "**previous**" `init_args` are discarded

.. how come the last example of my original post outputs the way it does ? is there a requirement `--*.class_path` argument to be in a specific position?

**Comment by mauvilsa** [comment]
> The problem is not only having same class in `--*.class_path` (the above behaviour appear in different subclasses too, see below example), but with the fact that the some `init_args` are getting discarded silently without the user realizing it.

For me it is much more comfortable to change this kind of things in the config where everything is clear instead of command line. But people were requesting being able to do with individual command line arguments and that is why it was added. The current behavior I think is the correct one because different classes don't necessarily have common args. I can add a warning so that this does not happen silently.

>     2. It can explicitly warn/error if user enters _incomplete specification_ of a new subclass

There is now way to know if a subclass specification is incomplete. Each argument is parsed one by one from left to right. This is just the way argparse works. The warning that can be added is when previous init_args are discarded by the parse of a `--*.class_path` argument.

> Secondly, I still don't understand the ordering of arguments.

The order is first `class_path` and then any `init_args`. Note the case that you don't give a config file and you start with an `--*.init_args` argument. The parser has no way of verifying if the value is valid if it is not known to which class it is supposed to be given to.

> .. how come the last example of my original post outputs the way it does ? is there a requirement `--*.class_path` argument to be in a specific position?

The last example I have not looked at. That one could be a bug.

**Comment by mauvilsa** [comment]
I have implemented that if class_path is given which is the same as the previous class_path, then init_args are not discarded. With this change all of the examples above give `Instantiated with: arg1 = "changed_again", arg2 = "changed"`. Also if a different class_path is given, the init_args are discarded and a warning shown.

**Comment by dasayan05** [comment]
@mauvilsa Ah, just saw [this ](https://github.com/omni-us/jsonargparse/commit/cdd0ea5bc28a261062c3e16ee49e68941afebc73)and [this](https://github.com/omni-us/jsonargparse/commit/bdc7635685220fa7b108c06626ae1902bad84fc2). Looks good 😃 Thanks.

I can reproduce the same `--*.class_name` change from Lightning code.
But I can't really see the warnings. Is Lightning's warning system suppressing them ? Do you need some change on PL side as well ? I haven't really look into it in detail.

**Comment by mauvilsa** [comment]
> But I can't really see the warnings. Is Lightning's warning system suppressing them ? Do you need some change on PL side as well ? I haven't really looked into it in detail.

What code are you using to see the warnings? Note that the warning is only when there are init_args and the class_path changes. There is a unit test that shows that it is working [signatures_tests.py#L329-L337](https://github.com/omni-us/jsonargparse/blob/95ad57db616bc7d1db9d319270655840e09360af/jsonargparse_tests/signatures_tests.py#L329-L337). I don't know if lightning suppresses warnings, but I would think it doesn't.

**Comment by carmocca** [comment]
Closing this. We can re-open if there's anything more to do.
