### ISSUE TITLE
Docker build error in docker/nvidia/Dockerfile

### ISSUE THREAD

**Issue by edwardpwtsoi** [PyTorchLightning/pytorch-lightning#8928]
## 🐛 Bug

```
Traceback (most recent call last):
782  File "<string>", line 1, in <module>
783FileNotFoundError: [Errno 2] No such file or directory: './pytorch-lightning/requirements/extra.txt'
784error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
```

The whole directory was moved under pytorch-lightning i.e.
pytorch-lightning
└── pytorch-lightning-*

### To Reproduce

```
wget https://github.com/PyTorchLightning/pytorch-lightning/archive/1.4.2.zip --progress=bar:force:noscroll
unzip 1.4.2.zip
mkdir pytorch-lightning
mv pytorch-lightning-*/ pytorch-lightning
tree pytorch-lightning -L 1
```

```
pytorch-lightning
└── pytorch-lightning-1.4.2
```

### Expected behavior

tree pytorch-lightning
pytorch-lightning
├── CHANGELOG.md
├── LICENSE
├── MANIFEST.in
├── Makefile
├── README.md
├── _notebooks
├── benchmarks
├── dockers
├── docs
├── environment.yml
├── legacy
├── pl_examples
├── pyproject.toml
├── pytorch_lightning
├── requirements
├── requirements.txt
├── setup.cfg
├── setup.py
└── tests

### Environment

- PyTorch Lightning Version (e.g., 1.3.0): N/A
- PyTorch Version (e.g., 1.8): N/A
- Python version: Python 3.8.11
- OS (e.g., Linux): Ubuntu 20.04.2 LTS
- CUDA/cuDNN version: N/A
- GPU models and configuration: N/A
- How you installed PyTorch (`conda`, `pip`, source): NGC Image pytorch 21.07

### Additional context

I changed to the following, it would build successfully. Let me know would you guys think could this could be a PR?
https://github.com/edwardpwtsoi/pytorch-lightning/blob/360143f49fabc8082a5a5a1b577b509d7758ec5b/dockers/nvidia/Dockerfile#L35

**Comment by tchaton** [comment]
Dear @edwardpwtsoi, I believe you can make a PR.

@Borda Any thoughts ?
