### ISSUE TITLE
Tensorboard logger logdir is not consistent in DDP mode

### ISSUE THREAD

**Issue by DavidMChan** [PyTorchLightning/pytorch-lightning#8945]
## 🐛 Bug

When the tensorboard logger is created, loggers on all ranks will have different (inconsistent) log directories, even though directories are only created on rank 0.

### To Reproduce

See: https://gist.github.com/DavidMChan/9c1fbc6e61031f2fe6014c01ddd5850b for reproducible code.
The above code produces:
```
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
.../data_loading.py:105: UserWarning: The dataloader, test dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 24 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Testing: 0it [00:00, ?it/s]
.../lightning_logs/version_24
.../lightning_logs/version_24
.../lightning_logs/version_24
.../lightning_logs/version_23
.../lightning_logs/version_24
.../lightning_logs/version_23
.../lightning_logs/version_24
.../lightning_logs/version_23
.../lightning_logs/version_24
.../lightning_logs/version_23
.../lightning_logs/version_24
.../lightning_logs/version_24
.../lightning_logs/version_23
.../lightning_logs/version_24
.../lightning_logs/version_23
.../lightning_logs/version_24
.../lightning_logs/version_23
.../lightning_logs/version_24
.../lightning_logs/version_23
.../lightning_logs/version_24
.../lightning_logs/version_23
.../lightning_logs/version_24
.../lightning_logs/version_23
.../lightning_logs/version_24
.../lightning_logs/version_23
.../lightning_logs/version_24
.../lightning_logs/version_23
.../lightning_logs/version_24
.../lightning_logs/version_23
.../lightning_logs/version_23
.../lightning_logs/version_23
.../lightning_logs/version_23
--------------------------------------------------------------------------------
DATALOADER:0 TEST RESULTS
{'test_loss': -0.23455876111984253}
--------------------------------------------------------------------------------
```

### Expected behavior

Logger variables should be consistent between ranks. Presumably, it's not only the log directory, but other variables as well.

### Environment

```bash
* CUDA:
        - GPU:
                - GeForce RTX 3090
                - GeForce RTX 3090
        - available:         True
        - version:           11.1
* Packages:
        - numpy:             1.21.2
        - pyTorch_debug:     False
        - pyTorch_version:   1.10.0.dev20210815+cu111
        - pytorch-lightning: 1.4.2
        - tqdm:              4.62.1
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.11
        - version:           #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021
```

### Additional context

At least having a globally consistent record of the log directory would be nice, since I am producing artifacts on the different ranks that I would like to save to disk. This gets a bit more confusing as you scale to multiple nodes, but right now, the folders returned on ranks that are not 0 *don't even exist*. An option when using DDP to sync the log directory, or a global option for writing pickleable objects to the rank-0 log directory would be great. Alternatively, making it so calling this property on a rank that is not 0 raises an error would be more user-friendly until there is a long-term solution is probably a good idea.

cc @borda @rohitgr7 @awaelchli @edward-io @ananthsub @kamil-kaczmarek @Raalsky @Blaizzy

**Comment by awaelchli** [comment]
@DavidMChan I think that's because of this line in your code:

`print(self.logger.log_dir)`

The better option is to access `self.trainer.log_dir` which is synchronized and will return a consistent result. 
We should communicate that better to users and not let them access `self.logger.log_dir`.

**Comment by DavidMChan** [comment]
Ah, thanks! This is good to know. I followed the issue here: https://github.com/PyTorchLightning/pytorch-lightning/issues/2370, which is now outdated, I suppose. 

Since this is already in the docs [here](https://pytorch-lightning.readthedocs.io/en/latest/common/loggers.html) (And I'm just blind), I don't know if this is really an issue.

**Comment by awaelchli** [comment]
Yes it's not a big issue, but we need to increase visibility in the docs in the logging section. Thanks

**Comment by bamblebam** [comment]
If we just need to update the docs to tell not to use `logger.log_dir` , I can do it.

**Comment by bamblebam** [comment]
What exactly should I add to the logger docs ?
Just a note saying, call the ```self.trainer.log_dir``` instead of ```self.logger.log_dir``` or something else ?
And are the logger docs a good page for this, Ig this would be better in the Trainer docs
