### ISSUE TITLE
TPU tests failing in CI

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#8961]
## 🐛 Bug
3 TPU test are failing on master in CI with this error:
`Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/_actions/GoogleCloudPlatform/github-actions/master/setup-gcloud'. Did you forget to run actions/checkout before running your local action?`

The test are:
* TPU cleaning (https://github.com/PyTorchLightning/pytorch-lightning/runs/3354656217)
* tpu-testing-job (3.7, 1.6) (https://github.com/PyTorchLightning/pytorch-lightning/runs/3354655659)
* tpu-testing-job (3.7, 1.8) (https://github.com/PyTorchLightning/pytorch-lightning/runs/3354655690)

### To Reproduce
Check CI

### Expected behavior
Green CI

### Environment
CI environment

### Additional context

Tagging @Borda who might have some insight here

**Comment by daniellepintz** [comment]
For reference here is the config for these tests: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/workflows/ci_test-tpu.yml

**Comment by daniellepintz** [comment]
Reopening this since TPU cleaning job is still failing. @kaushikb11 do you mind taking a look?

**Comment by daniellepintz** [comment]
it looks like I dont have access to reopen

**Comment by kaushikb11** [comment]
Hi @daniellepintz, I have reopened the issue and take a look into it! Thanks.

**Comment by daniellepintz** [comment]
thanks so much for the fix @kaushikb11!
