### ISSUE TITLE
`limit_val_batches=0.0` has no effect when `overfit_batches=1`

### ISSUE THREAD

**Issue by rbracco** [PyTorchLightning/pytorch-lightning#8962]
## 🐛 Bug

I want to overfit a batch using `overfit_batches`, `limit_val_batches` is set to `0.0` but there's still a validation batch every epoch making it take twice as long. Why is validation happening at all when using `overfit_batches` and why is `limit_val_batches` not working as expected?

This is my trainer, 
```
trainer = pl.Trainer(
    gpus=1,
    overfit_batches=1,
    limit_val_batches=0.0,
    log_every_n_steps=1,
    deterministic=True,
)
```

### To Reproduce

I tried to reproduce using the boring model, but the colab nb is broken 
![image](https://user-images.githubusercontent.com/47190785/129806057-a2a2df2c-f686-4fa9-963e-41be7cfd3786.png)

### Expected behavior

Validation shouldn't happen by default when using overfit_batches. If it is desirable to have a validation batch then `limit_val_batches=0.0` should override that behavior. 

### Environment

pytorch 1.9.0
lightning 1.4.1

**Comment by tchaton** [comment]
Dear @rbracco,

Would you like to give it a try ?

This is definitely a good first issue.

Best,
T.C

**Comment by rbracco** [comment]
Sure, I'm happy to PR, I would just like to clarify the desired behavior. Would it be...

A. No validation by default when using `overfit_batches`?
B. Validation by default, but `limit_val_batches=0.0` prevents validation?

Thank you.

**Comment by tchaton** [comment]
Dear @rbracco,

I would go for solution B.

overfit_batches=1 makes sure everything works properly for training, validation. 
If you had limit_val_batches=0.0, there shouldn t be validation.

Feel free to make a PR with this addition.

Best,
T.C

**Comment by popfido** [comment]
> 
> I would go for solution B.
> 
> overfit_batches=1 makes sure everything works properly for training, validation.
> If you had limit_val_batches=0.0, there shouldn t be validation.
> 
> Feel free to make a PR with this addition.
> 
> Best,
> T.C

@tchaton 

I meets this problem too and checkout the codes in ``Trainer`` of master.

It seems like that the ``DebuggingConnector`` will reset ``limit_val_batches``, ``limit_train_batches`` and ``limit_test_batche`` to ``overfit_batches`` when ``overfit_batches`` > 0 through function ``determine_data_use_amount`` via PR #3447. And this happends all the time since there is no switcher to control it.

**Comment by tchaton** [comment]
Hey @popfido,

The default value for `limit_val_batches=1.0`. If a user sets it explicitly to .0, I would expect overfit batches not to over-write it as it is a request from the user.

**Comment by popfido** [comment]
Hi @tchaton,

How about other param that also be reseted by ``determine_data_use_amount`` to ``overfit_batches`` like ``limit_test_batche`` or ``limit_train_batches``,. Although it's hard to image that there exists such kind of user who will set both  ``overfit_batches`` > 0, and ``limit_train_batches`` or ``limit_test_batche`` = 0.0

Bests, 
F.W

**Comment by popfido** [comment]
Hi @tchaton,

In my view the fast solution for this bug is to check whether the value of ``limit_val_batches``, ``limit_train_batches`` and ``limit_test_batche`` is the default value. If not, then keep them from resetting by ``overfit_batches``.

Bests,
F,W
