### ISSUE TITLE
Train fails on distributed learning

### ISSUE THREAD

**Issue by kangsan0420** [PyTorchLightning/pytorch-lightning#8964]
## 🐛 Bug

I'm testing pytorch_lightning with simple example (AutoEncoder using MNIST).
The autoencoder works fine with the code in the below snapshot.
However, when I set the gpus=[0,1] instead of [0] or uncomment line number 9 & 10 or both, train goes fail (the reconstructed images look like a noise, not like the input images from MNIST)
I think somthing wrong in distribution.

![image](https://user-images.githubusercontent.com/79678563/129826075-790ba631-32a9-42fd-ba07-5979d25c55a1.png)

### To Reproduce

In the above snapshot, net and dataset are from:
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/basic_examples/autoencoder.py

### Expected behavior

![image](https://user-images.githubusercontent.com/79678563/129828368-88de81ee-3d52-4302-84c7-89fafa1202d5.png)

### Environment

- PyTorch Lightning Version (e.g., 1.3.0): 1.4.2
- PyTorch Version (e.g., 1.8): 1.9.0
- Python version: 3.8.11 (default, Jul  3 2021, 17:53:42) [GCC 7.5.0]
- OS (e.g., Linux): Ubuntu 18.04.5 LTS
- CUDA/cuDNN version: 10.2
- GPU models and configuration: Tesla V100 × 2
- How you installed PyTorch (`conda`, `pip`, source): docker pull pytorchlightning/pytorch_lightning:base-cuda-py3.8-torch1.9
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information: I'm using jupyerlab. In the above container, pytorch_lightning was installed by `pip install pytorch_lightning`

**Comment by tchaton** [comment]
Hey @kangsan0420,

Would you mind sharing a reproducible script ? You said it is coming from 1 of the examples, but we would need the script to find the root if the probleme.

Best,
T.C

**Comment by kangsan0420** [comment]
Here`s the script: https://github.com/kangsan0420/temp/blob/master/main.ipynb

I found another problem in min_delta parameter in `pytorch_lightning.callbacks.early_stopping.EarlyStopping`.
When I set `min_delta=0` and `verbose=True`, it works fine but if it is not 0 (e.g. `min_delta=1e-4`), the output by `verbose` printed twice. As you can see below (it's in the above link), every second output always shows no improvement. Thus, the `patience` parameter is also not working with `min_delta!=0`.

![image](https://user-images.githubusercontent.com/79678563/129996434-5fed8ed1-e6e2-40e1-80ef-2604d02ea9b3.png)

**Comment by kangsan0420** [comment]
@tchaton 
Added) Earlystopping was my fault. Inherit was wrong. I'm sorry :(
However, the distributed learning keeps fail.
Here's the code (script version):
https://github.com/kangsan0420/temp2/blob/master/main.py

I conducted 6 experiments with below parameters.
a) script/None: `gpus=[0], accelerator=None`  (success)
b) script/ddp: `gpus=[0], accelerator='ddp', plugins=DDPPlugin(find_unused_parameters=False)` (fail) 
c) script/ddp_2gpus: `gpus=[0,1], accelerator='ddp', plugins=DDPPlugin(find_unused_parameters=False)` (fail)
d) script/ddp_wo_plugin : `gpus=[0], accelerator='ddp'`  (fail)
e) script/dp: `gpus=[0], accelerator='dp'`  (success)
f) script/dp_2gpus: `gpus=[0,1], accelerator='dp'`  (fail)

You may notice on the below result images that only single gpu and the accelerator= (None or 'dp') makes the train success (the digits 0,6,8 are reconstructed well).
What should I do to use ddp that is 3x faster than dp?​

![image](https://user-images.githubusercontent.com/79678563/130550030-90cf8911-af81-4dc5-a352-9561126d8f92.png)

Thank you
Kangsan Lee

**Comment by tchaton** [comment]
Dear @kangsan0420,

I have updated the auto encoder script: https://github.com/PyTorchLightning/pytorch-lightning/pull/9402.

It seems to be working for me.

Best,
T.C
