### ISSUE TITLE
Deprecate `stochastic_weight_avg` from Trainer constructor

### ISSUE THREAD

**Issue by ananthsub** [PyTorchLightning/pytorch-lightning#8971]
## 🚀 Feature

Remove this argument from the Trainer constructor:
https://github.com/PyTorchLightning/pytorch-lightning/blob/c6b68883879e38719688865aceac746477f0a9b9/pytorch_lightning/trainer/trainer.py#L161

### Motivation

We are auditing the Lightning components and APIs to assess opportunities for improvements:
- https://docs.google.com/document/d/1xHU7-iQSpp9KJTjI3As2EM0mfNHHr37WZYpDpwLkivA/edit#
- https://github.com/PyTorchLightning/pytorch-lightning/issues/7740

First, from the user POV: why should users have to learn about 2 different ways of enabling stochastic weight averaging?
- Either add a trainer flag `stochastic_weight_avg=True`
- Or add a `StochasticWeightAveraging` callback to the `Trainer`'s `callbacks` list

This goes against the values here: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md#main-core-value-one-less-thing-to-remember

Secondly, this will simplify the internal codebase: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md#simple-internal-code

The Trainer today has over 50 arguments to its constructor. This number is growing with each feature release, and makes the trainer cluttered. It also hurts the extensibility of the trainer: a number of arguments passed to the Trainer are to customize other utilities. Plumbing arguments through the trainer creates an undesirable coupling: when the underlying components change, the framework is forced to make breaking API changes in at least two places:
1. The underlying component
2. The trainer constructor

The trainer should have a high bar for what's included on the arguments list. `stochastic_weight_avg` configures a callback for users, which users could easily do in 1 line and pass into the `callbacks` argument.

By default, this is not enabled, so users have to opt into this anyways. 

### Pitch

1. Deprecate `stochastic_weight_avg ` off the Trainer constructor in v1.5
2. Update any tutorials/documentation to point to how users can easily construct a StochasticWeightAveraging callback on their own

https://github.com/PyTorchLightning/pytorch-lightning/blob/5329b0d11358b72a42d596d3b70b7010e35c45af/pytorch_lightning/trainer/connectors/callback_connector.py#L85-L93

3. Remove the flag in v1.7

This nets us 1 constructor argument saved, which is progress

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by ananthsub** [comment]
@edenafek - any suggestions on this based on the comments rom #8989 ?

**Comment by tchaton** [comment]
Hey @daniellepintz @ananthsub,

I apologise this is taking so long to get to final answer. Let me push for this.

Best,
T.C
