### ISSUE TITLE
lr_find crashes or hangs when using multiple GPUs

### ISSUE THREAD

**Issue by idfah** [PyTorchLightning/pytorch-lightning#8983]
## 🐛 Bug

When running `Trainer.tuner.lr_find` using multiple GPUs and `accelerator='ddp_spawn'`, the procedure fails with a pickling exception:
```
_pickle.PicklingError: Can't pickle <function BoringModel.configure_optimizers at 0x7f9d6f81f0d0>: it's not the same object as __main__.BoringModel.configure_optimizers
```

When using the ~~`dp`~~ and `ddp` accelerators, the procedure seems to hang indefinitely.

### To Reproduce

```
import os

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.lr = 0.1
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum().abs()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum().abs()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum().abs()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=self.lr)


def run():
    train_data = DataLoader(RandomDataset(32, 4), batch_size=8)
    val_data = DataLoader(RandomDataset(32, 4), batch_size=8)
    test_data = DataLoader(RandomDataset(32, 4), batch_size=8)

    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        gpus=[0, 1],
        accelerator='ddp_spawn',
    )

    lr_finder = trainer.tuner.lr_find(
        model, train_dataloaders=train_data, val_dataloaders=val_data)

    print(lr_finder.suggestion())


if __name__ == "__main__":
    run()
```

### Expected behavior

Learning rate finder should work across multiple GPUs with each accelerator or else raise an exception stating that some combinations are not supported.

### Environment

* CUDA:
        - GPU:
                - Tesla K40m
                - Tesla K40m
        - available:         True
        - version:           11.2
* Packages:
        - numpy:             1.21.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.8.1
        - pytorch-lightning: 1.4.2
        - tqdm:              4.62.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.3
        - version:           #1 SMP Thu Oct 22 00:20:22 UTC 2020

- PyTorch Lightning Version: 1.4.2
- PyTorch Version: 1.8.1
- Python version: 3.8.3
- OS (e.g., Linux): Linux
- CUDA/cuDNN version: 11.2
- GPU models and configuration: 2xk40 or 2x2080TI
- How you installed PyTorch: pip

### Additional Context

It is valuable to be able to run the `lr_finder` on multiple GPUs in order to replicate the configuration, e.g., batch and model sizes, that will be used during the actual training procedure.

**Comment by idfah** [comment]
I suspect that wrapping `.configure_optimizers` in this way is the source of the pickling exception for `ddp_spawn`:
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/tuner/lr_finder.py#L100

**Comment by awaelchli** [comment]
as @idfah pointed out, it will be a bit complex to sort this out for ddp_spawn. for dp, it should work without problem, we will investigate.

[all variants of ddp will not work with LR finder. ](https://pytorch-lightning.readthedocs.io/en/latest/advanced/lr_finder.html)

**Comment by idfah** [comment]
@awaelchli I think I may have had an unrelated issue that was causing the `dp` accelerator to hang... I found some hung python process and killed them and now it seems to work.  I'm not really sure why.

The `ddp` accelerator does still hang for me though and `ddp_spawn` has the pickling issue.

I'll try to dig a bit as time permits.  Having a working `dp` implementation gives me a workaround for now though.
