### ISSUE TITLE
Impossible to report bugs with Colab Template

### ISSUE THREAD

**Issue by michele-arrival** [PyTorchLightning/pytorch-lightning#9009]
## 🐛 Bug

The Colab link provided for bug reports raises an error :

```
TypeError: Expected 'Iterator' as the return annotation for `__iter__` of ExperienceSourceDataset, but found typing.Iterable
```

I believe it's related to this: https://github.com/PyTorchLightning/lightning-bolts/issues/707

### To Reproduce

https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing

### Expected behavior

lightning-bolts should be installed with:

`pip install lightning-bolts`

rather than 

`pip install pytorch-lightning-bolts`

**Comment by carmocca** [comment]
Fixed!
