### ISSUE TITLE
[dp/ddp mode]Enable checking which process I'm in

### ISSUE THREAD

**Issue by Ir1d** [PyTorchLightning/pytorch-lightning#901]
### Motivation

![image](https://user-images.githubusercontent.com/10709657/74890319-a710a900-53be-11ea-8f8a-b46ab96c924b.png)
The motivation is that in dp/ddp mode, one print statement in `training_step` ends up with multiple printed lines (4 lines because I'm using 4 GPUs)
### Pitch

I hope that there's a `self.rank` to let the user check which process they're in.

So they may choose to print for only rank 0, or print the rank to screen with the msg to avoid confusion.

### Alternatives

@williamFalcon suggests make it automatically handled with a self.print
### Additional context

I'd prefer a self.rank because horovod has this ranking. I'm not sure if there are similar things in pytorch.

**Comment by williamFalcon** [comment]
```self.print()``` is available in 0.7.1

you can also check:
```self.trainer.proc_rank```
