### ISSUE TITLE
add missing docstrings to public properties in loggers

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#9028]
## 📚 Documentation

There are a few undocumented public properties in the logger wrappers. 
Example: 
https://github.com/PyTorchLightning/pytorch-lightning/blob/92e49795e1e044ee7f1ca450babf0c50c1b5d81f/pytorch_lightning/loggers/mlflow.py#L174

Let's document these so they show up in our HTML docs and so users can discover them. 

**This is a good issue for new contributors!! If you are interested, please send a pull request right away (one per logger class).**

**Comment by bamblebam** [comment]
I can do this

**Comment by bamblebam** [comment]
I think this should still be open as the other logger classes are left.

**Comment by awaelchli** [comment]
@bamblebam it was auto-closed. It was because you had "Fixes xyz" in the description of the PR, GitHub was smart about it to close after merge :)
