### ISSUE TITLE
Implement available Horovod Runners directly

### ISSUE THREAD

**Issue by twsl** [PyTorchLightning/pytorch-lightning#9050]
### Motivation
The current implementation requires an external run of the python script with `horovodrun`.

### Pitch
 For convinience, available horovod runners for plattforms like [Spark](https://github.com/horovod/horovod/blob/master/docs/spark.rst#horovod-spark-run) or [Ray](https://github.com/horovod/horovod/blob/master/docs/ray.rst#horovod-ray-executor) could be directly called inside of PyTorch Lightning. This would allow to specify the number of gpus only once during the initialization of the trainer.

### Alternatives
Just keep it the way it is.

### Additional context

This could provide a nice way to enable multi node/gpu inside of Databricks notebooks. Detection of Databricks can easily be done via the env var `DATABRICKS_RUNTIME_VERSION`. Spark could be detected via [env vars](https://spark.apache.org/docs/latest/configuration.html#environment-variables) as well. For Ray there is alredy a [Horovod on Ray Plugin](https://github.com/ray-project/ray_lightning).

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by tchaton** [comment]
Dear @twsl ,

Thanks for opening this issue. We are currently in the process to move the Horovod Plugin to the Horovod library, so I believe this feature should be build there directly.

Best,
T.C

**Comment by twsl** [comment]
@tchaton is there any issue you can link for me to track progress? But that sounds good, I hope the ETA is not too far away

**Comment by tchaton** [comment]
Dear @twsl,

Mind sharing some background on why this feature is important for you ?

Best,
T.C

**Comment by twsl** [comment]
I prefer notebooks to python scripts for researching and would like to simply scale my code by updating the trainer parameter and selecting a different cluster.
Databricks is the easiest way for me to access a cluster and comes with horovod spark setup while `ddp` doesn't work in notebooks.
