### ISSUE TITLE
Improve wandb tests

### ISSUE THREAD

**Issue by ghost** [PyTorchLightning/pytorch-lightning#906]
The tests of the `wandb`-logger are not as comprehensive as for the rest of the loggers. Currently, they just test if constructing a logger works.

Testing `wandb` in the same way as the other loggers works:

    def test_wandb_logger(tmpdir):
        """Verify that basic functionality of wandb logger works."""
        tutils.reset_seed()

        wandb_dir = os.path.join(tmpdir, "wandb")
        logger = WandbLogger(save_dir=wandb_dir, anonymous=True, offline=True)

        hparams = tutils.get_hparams()
        model = LightningTestModel(hparams)

        trainer_options = dict(
            default_save_path=tmpdir,
            max_epochs=1,
            train_percent_check=0.05,
            logger=logger
        )

        trainer = Trainer(**trainer_options)
        result = trainer.fit(model)

        print('result finished')
        assert result == 1, "Training failed"

    def test_wandb_pickle(tmpdir):
        """Verify that pickling trainer with wandb logger works."""
        tutils.reset_seed()

        wandb_dir = str(tmpdir)
        logger = WandbLogger(save_dir=wandb_dir, anonymous=True)
        trainer_options = dict(
            default_save_path=tmpdir,
            max_epochs=1,
            logger=logger
        )

        trainer = Trainer(**trainer_options)
        pkl_bytes = pickle.dumps(trainer)
        trainer2 = pickle.loads(pkl_bytes)
        trainer2.logger.log_metrics({"acc": 1.0})

But the CI tests on github for windows fail. The tests for Ubuntu and Mac work. Seems to be some problem related to file-access that I cannot recreate locally

**Comment by Borda** [comment]
@ghost mind send a PR? :raccoon:

**Comment by borisdayma** [comment]
I think you guys fixed it here: https://github.com/PyTorchLightning/pytorch-lightning/commit/f862d9f6915881e3f4048586a16ef607e5640d26

**Comment by edenlightning** [comment]
@Borda can we close this?

**Comment by Borda** [comment]
> can we close this?

not yeat as wandb is not included in the stand test suite
https://github.com/PyTorchLightning/pytorch-lightning/blob/9e8716afe8bd535ecb468027a8a4c919a3ae16d1/tests/loggers/test_all.py#L29
https://github.com/PyTorchLightning/pytorch-lightning/blob/9e8716afe8bd535ecb468027a8a4c919a3ae16d1/tests/loggers/test_all.py#L76

**Comment by awaelchli** [comment]
The wandb logger is now included in the other tests as well and the todos that @Borda pointed out are gone. 
It is tested also for pickling and folder structure / paths for logged files. 
I would argue it is now at the similar level as other loggers. Shall we close?
