### ISSUE TITLE
NeptuneLogger missing 'save_dir' parameter

### ISSUE THREAD

**Issue by mkmenta** [PyTorchLightning/pytorch-lightning#9082]
## Proposed refactoring or deprecation

Add the parameter `save_dir` to [`NeptuneLogger`](https://pytorch-lightning.readthedocs.io/en/1.4.3/extensions/generated/pytorch_lightning.loggers.NeptuneLogger.html) with the same functionality as other loggers like [`TensorboardLogger`](https://pytorch-lightning.readthedocs.io/en/1.4.3/extensions/generated/pytorch_lightning.loggers.TensorBoardLogger.html#pytorch_lightning.loggers.TensorBoardLogger).

### Motivation

`NeptuneLogger` is the only logger missing the parameter `save_dir`.

### Pitch

I think it would be better if all loggers have the `save_dir` parameter and follow the same standard unless there is any other reason.

**Comment by rohitgr7** [comment]
I think it's not possible to specify the local dir path when training offline with Neptune.
https://docs.neptune.ai/you-should-know/connection-modes#uploading-offline-data

**Comment by kamil-kaczmarek** [comment]
Hi @mkmenta,

In some cases Neptune logs metadata to the `.neptune` directory in your cwd, which is not parametrizable at the moment. Therefore NeptuneLogger does not have such parameter.

You can read more about this here: https://docs.neptune.ai/you-should-know/connection-modes

**Comment by rohitgr7** [comment]
I'd suggest a PR in [neptune client](https://github.com/neptune-ai/neptune-client) if possible for this. Would be a great addition. Closing this for now. We can reopen this and add it once it's available in the native logger :)
