### ISSUE TITLE
Instead of overwriting `hparams` when resuming from a checkpoint, merge them

### ISSUE THREAD

**Issue by EricWiener** [PyTorchLightning/pytorch-lightning#9083]
## 🚀 Feature
Instead of doing:
```
# overwrite hparams by the given file
checkpoint[cls.CHECKPOINT_HYPER_PARAMS_KEY] = hparams
```
[Source](https://github.com/PyTorchLightning/pytorch-lightning/blob/e63968ab8867a5aae8ab9d883f186ce379199cff/pytorch_lightning/core/saving.py#L144)

It could be:
```
checkpoint[cls.CHECKPOINT_HYPER_PARAMS_KEY].update(hparams)
```

### Motivation
I had saved some hyperparameters for logging to tensorboard hparams. However, not all of the variables were saved (since I only wanted a few to show up in the hparams section). When I did:
```
MyLightningModule.load_from_checkpoint(checkpoint_path=pth, hparams_file=hp_file)
```
I then got an error because certain variables that aren't present in the hparams file I specified.

However, if I do:
```
MyLightningModule.load_from_checkpoint(checkpoint_path=pth)
```
then all the variables are loaded from the checkpoint and everything works as expected.

I can also do:
```
MyLightningModule.load_from_checkpoint(
    checkpoint_path=pth, 
    hparams_file=hp_file,
    # extra variables missing from hparams file here
)
```
but the cleanest approach would be to just use the hparams file to update the existing variables in the checkpoint (rather than overwriting everything from the checkpoint).

### Pitch
If you have some variables you want to override, but still want the majority of the variables saved in the checkpoint, it would be desirable to have the hyperparameters merged rather than only use the hyperparameters from the saved file.

### Alternatives
```
checkpoint[cls.CHECKPOINT_HYPER_PARAMS_KEY].update(hparams)
```

### Additional context
N/A

**Comment by awaelchli** [comment]
unless I misunderstand the issue/pitch, this seems dangerous to me. 

there may be many hyperparameters and it's difficult to know how and whats get merged from where. how will the user communicate their intentions, and how are we communicating back from where we take each param?

to me, it looks like it will be safer and sanest to either load from checkpoint or file, but never mix the hparams.

**Comment by EricWiener** [comment]
The behavior would be to load from checkpoint + overwrite everything from the checkpoint with hparams. The current behavior is to only use params from hparams if hparams is passed, but I don't see the downside to keeping values from the checkpoint as well if they aren't specified in hparams.

The order of precedence would be:
1. Individually passed args
2. hparams
3. checkpoint

**Comment by awaelchli** [comment]
the downside is that parameters get mixed. an example is when someone tries to load a checkpoint and an unrelated parameter file. when parameters are missing, we want an error.

side note: the hparam file approach is inherently limited. it's nice to have a file saved in human readable format listing the parameters but I do not recommend loading from it.

**Comment by EricWiener** [comment]
Got it. Should I close the issue + PR?

**Comment by rohitgr7** [comment]
> when parameters are missing, we want an error.

how about a warning in this case? if some of the existing hparams are missing or new hparams comes up in the new hparams_file, we can generate a warning?

**Comment by EricWiener** [comment]
I like the idea of a warning. It could be seen as more of a feature than an issue being able to easily specify additional parameters. If you make a change to the model but want to load from a new checkpoint, it could be a lot easier to modify the hparams file manually rather than having to pass additional arguments when loading the model (especially since those additional arguments aren't needed for future checkpoints with the updated model).

**Comment by rohitgr7** [comment]
@awaelchli thoughts??

**Comment by awaelchli** [comment]
sorry to give a negative answer once again, I will stay with my previous statement. Don't be discouraged, it's just one opinion out of many. I am not affected by the decision since I don't use this feature. If people think changing this is good then please go ahead.

and lastly I would like to mention the LightningCLI which I believe handles these use cases more elegantly with config files.

**Comment by EricWiener** [comment]
Closing because of https://github.com/PyTorchLightning/pytorch-lightning/pull/9146#discussion_r701089185

**Comment by rohitgr7** [comment]
shall we at least raise an error/warning then in case the new hparams files doesn't contain all the keys that were saved in some checkpoint?
