### ISSUE TITLE
[RFC] Depreceate `Trainer(benchmark)` and use deterministic

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#9128]
Out of scope for this PR but maybe we should remove `Trainer(benchmark)` and set

`torch.backends.cudnn.benchmark = not deterministic`

_Originally posted by @carmocca in https://github.com/PyTorchLightning/pytorch-lightning/pull/9121#discussion_r696202228_

cc @borda @justusschock @awaelchli @akihironitta @rohitgr7 @tchaton

**Comment by kaushikb11** [comment]
Hi @rishawsingh, any update on this? Let us know if we could help in any way.

**Comment by carmocca** [comment]
Squatting this issue for onboarding @krshrimali
