### ISSUE TITLE
`automatic_optimization = False` breaks pytorch profiler

### ISSUE THREAD

**Issue by jjyyxx** [PyTorchLightning/pytorch-lightning#9177]
### To Reproduce

Run basic_examples/profiler_example.py with `--trainer.profiler pytorch` work as expected, but adding `self.automatic_optimization = False` in `ModelToProfile` breaks it with an AssertionError (even if `manual_backward` is used properly).

### Expected behavior

Profiling in manual optimization mode shall work as expected.

### Environment

* CUDA:
        - GPU:
                - NVIDIA GeForce RTX 2060
        - available:         True        
        - version:           11.1        
* Packages:
        - numpy:             1.20.1      
        - pyTorch_debug:     False       
        - pyTorch_version:   1.9.0+cu111 
        - pytorch-lightning: 1.4.4       
        - tqdm:              4.59.0      
* System:
        - OS:                Windows     
        - architecture:
                - 64bit
                - WindowsPE
        - processor:         AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD
        - python:            3.8.8
        - version:           10.0.19041

**Comment by tchaton** [comment]
Dear @jjyyxx,

Would you mind sharing your code,

```py
class ModelToProfile(LightningModule):
    def __init__(self, name: str = "resnet50"):
        super().__init__()
        self.model = getattr(models, name)(pretrained=True)
        self.criterion = torch.nn.CrossEntropyLoss()
        self.automatic_optimization = False

    def training_step(self, batch, batch_idx):
        opt = self.optimizers()
        opt.zero_grad()
        inputs, labels = batch
        outputs = self.model(inputs)
        loss = self.criterion(outputs, labels)
        self.log("train_loss", loss)
        self.manual_backward(loss)
        opt.step()

    def validation_step(self, batch, batch_idx):
        inputs, labels = batch
        outputs = self.model(inputs)
        loss = self.criterion(outputs, labels)
        self.log("val_loss", loss)

    def predict_step(self, batch, batch_idx, dataloader_idx: int = None):
        inputs = batch[0]
        return self.model(inputs)

    def configure_optimizers(self):
        return torch.optim.SGD(self.parameters(), lr=0.001, momentum=0.9)
```

**Comment by tchaton** [comment]
Hey @jjyyxx,

Thanks for reporting this bug. I can confirm I was able to reproduce it.

I will investigate this deeper.

Best,
T.C
