### ISSUE TITLE
Example for Predict method to label new data #1853

### ISSUE THREAD

**Issue by paapu88** [PyTorchLightning/pytorch-lightning#9199]
## 📚 Documentation

It seems that predicting using bathes is possible now (issue #1853 is done).
I could not get it working in a 2 GPU machine. Latest error was 
>  File "/home/ubuntu/anaconda3/envs/myenv/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
>NotImplementedError: Caught NotImplementedError in replica 0 on device 0.

It would be nice to get a minimal working example for predicting using bathes.
terveisin Markus

**Comment by carmocca** [comment]
What's your Lightning verision?

Can you share your LightningModule and some reproducible code?

It's likely the error comes from not implementing `predict_step` and/or `predict_dataloader`

**Comment by paapu88** [comment]
Hei,
This not about the particular error, but I was hoping to get a minimal working example of 
https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html#predict
which uses bathed input data.
terveisin, Markus

**Comment by carmocca** [comment]
You also have these docs! Also, I suggest you browse the `stable` docs

https://pytorch-lightning.readthedocs.io/en/stable/starter/introduction_guide.html#predicting
