### ISSUE TITLE
best_model_epoch in model_checkpoint

### ISSUE THREAD

**Issue by turian** [PyTorchLightning/pytorch-lightning#9204]
## 🚀 Feature

model_checkpoint.best_model_epoch should return the epoch of the best model.

### Motivation

When tuning a grid and deciding upon a max_epochs for later training, one might run a particularly large grid with many epochs. It's useful to know, when retrieving the best model, what the training epoch it was trained until.

### Alternatives

Looking at the best_model_path and determining the epoch from there.

**Comment by carmocca** [comment]
You could get it today by doing `torch.load(model_checkpoint.best_model_path)["current_epoch"]`

**Comment by turian** [comment]
@carmocca I believe you mean `epoch`, not `current_epoch`. Thank you for the workaround!

**Comment by rohitgr7** [comment]
or you can create a simple callback to track both the best_model_path and its current_epoch. This way you don't have to load the checkpoint.
