### ISSUE TITLE
gradient value should be unscaled when precision=16

### ISSUE THREAD

**Issue by AndersJing** [PyTorchLightning/pytorch-lightning#9205]
## 🐛 Bug

On 1.4.x, when track_grad_norm=2 and precision=16, the logged gradient value is the scaled value.

### To Reproduce

https://colab.research.google.com/drive/1kV3wP8HmprPVflKXfY5eMdqIOar8reKk?usp=sharing

### Expected behavior

The gradient value should be unscaled when preciosn=16

### Environment

* CUDA:
	- GPU:
		- Tesla K80
	- available:         True
	- version:           10.2
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.0+cu102
	- pytorch-lightning: 1.4.4
	- tqdm:              4.62.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.11
	- version:            Sat Jun 5 09:50:34 PDT 2021

### Additional context

On v1.3.8, the behavior is normal, see https://colab.research.google.com/drive/1AXMhr1gPll5ZPDTphQqAOJlI_9iEMISU?usp=sharing

@carmocca

**Comment by cowwoc** [comment]
I believe this is fixed in release 1.4.9: https://github.com/PyTorchLightning/pytorch-lightning/releases/tag/1.4.9

Can this issue be closed?

**Comment by AndersJing** [comment]
I run the code again on 1.4.9, the issue is fixed.
