### ISSUE TITLE
Dataclass ClassVars are not correctly handled in apply_to_collection

### ISSUE THREAD

**Issue by a-gardner1** [PyTorchLightning/pytorch-lightning#9208]
## 🐛 Bug

When including a dataclass in part of a batch that contains a `ClassVar` field, the `ClassVar` field is passed as a keyword argument to the dataclass instance's `__init__` function, resulting in a `TypeError`.
This appears to be due to the use of `__dataclass_fields__` versus `dataclasses.fields` introduced in a [relatively recent PR that added support for dataclasses to `apply_to_collection`](https://github.com/PyTorchLightning/pytorch-lightning/pull/7935/files#diff-04e358a842de2e45c9ccde33d2feb59c37c023234906008e156ae7c741b671d4R121).
The `__dataclass_fields__` attribute does not distinguish between pseudo-fields `ClassVar`/`InitVar` and actual fields, whereas [`dataclasses.fields`](https://docs.python.org/3/library/dataclasses.html#dataclasses.fields) does.

### To Reproduce
https://colab.research.google.com/drive/1Ha5BsgV29buPZwn04mohfkOC4bycm7jN?usp=sharing

### Expected behavior

The model should load data and train without error.

### Environment

* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.2
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.0+cu102
	- pytorch-lightning: 1.4.4
	- tqdm:              4.62.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.11
	- version:           #1 SMP Sat Jun 5 09:50:34 PDT 2021

**Comment by carmocca** [comment]
Since you are already familiar with what's the problem, do you want to open a PR with the fix?

Remember to include a case for it in `tests/utilities/test_apply_func.py`

**Comment by a-gardner1** [comment]
Sure, I'll try to get to it in the next week or so.

**Comment by jinyoung-lim** [comment]
I could pick this up if @a-gardner1 does not.
