### ISSUE TITLE
Signature change in torch autocast from fast_dtype to dtype.

### ISSUE THREAD

**Issue by jstjohn** [PyTorchLightning/pytorch-lightning#9210]
## 🐛 Bug

The type signature [changed from `autocast(fast_dtype=)` to `autocast(dtype=)`](https://github.com/pytorch/pytorch/commit/6324d98e9e736214ee7a161482b02aaf8cebbc9d#diff-dac4bd53ced015c8810b3b02fc5c2ec6c2b0658c5090b4fbbd09c96bd45087d1R16-R17).

### To Reproduce

1. Install pytorch nightly >= August 30th.
2. Train a model with precision="bf16". 

### Expected behavior

Not the following error:

```
    return torch.cuda.amp.autocast(fast_dtype=self._fast_dtype)
TypeError: __init__() got an unexpected keyword argument 'fast_dtype'
```

With further details in the traceback:
```
  File "/home/jstjohn/miniconda3/envs/ravel/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/native_amp.py", line 126, in val_step_context
    with self.autocast_context_manager():
  File "/home/jstjohn/miniconda3/envs/ravel/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/native_amp.py", line 114, in autocast_context_manager
    return torch.cuda.amp.autocast(fast_dtype=self._fast_dtype)
TypeError: __init__() got an unexpected keyword argument 'fast_dtype'
```

### Environment

* CUDA:
	- GPU:
		- NVIDIA A10
		- NVIDIA A10
	- available:         True
	- version:           11.1
* Packages:
	- numpy:             1.21.1
	- pyTorch_debug:     False
	- pyTorch_version:   1.10.0.dev20210830
	- pytorch-lightning: 1.5.0dev
	- tqdm:              4.62.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.9.6
	- version:           #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021

**Comment by carmocca** [comment]
Assigning you as you already offered contributing the fix :)
