### ISSUE TITLE
Add "epoch" options to basic templates

### ISSUE THREAD

**Issue by baeseongsu** [PyTorchLightning/pytorch-lightning#925]
## 🚀 Feature

Add "epochs" option to parser of 'basic_examples/lightning_module_template.py'

### Motivation

Thanks to 'basic_examples/lightning_module_template.py', I could build my deep learning model. Some beginners like me might build their model from this basic template. However, there are no options to manipulate epochs. I just thought that what people use often should be included in the basic template, so I uploaded my issue.

### Pitch

I suggest that the basic template includes "epoch" option in the basic template.

### Alternatives

Add "epoch" options to parser of 'basic_examples/lightning_module_template.py'
```python
parser.add_argument('--epochs', default=10, type=int, metavar='N',
                            help='number of total epochs to run')

trainer = pl.Trainer(max_epochs=hparams.epochs)
```

### Additional context

I am really enjoying PytorchLightning framework. Thanks 😄

**Comment by Borda** [comment]
yeah, it can be solved a part of that one, could you check on the follow-up PR? :]
