### ISSUE TITLE
Run the test set every epoch on a single GPU

### ISSUE THREAD

**Issue by jipson7** [PyTorchLightning/pytorch-lightning#9254]
## 🚀 Feature

Hi there. I wasn't sure whether to comment on [this issue](https://github.com/PyTorchLightning/pytorch-lightning/issues/5245) or open a new one since it was closed. But Id like to be able to evaluate the test set at the end of every validation epoch. And ideally have the test set be evaluated on one of N GPUs when using DDP as a training accelerator.

### Motivation

Working on some retrieval models that have a fairly fast test evaluation cycle, and we'd like to see test results as its training. The evaluation has a synchronization point after embedding the data points thats run in `test_epoch_end`, and only works on a single GPU.

### Pitch

I had hoped I could solve the first issue with a simple hack like:
```
def on_train_epoch_start(self) -> None:
    super().on_train_epoch_start()
    if self.current_epoch > 0:
        self.trainer.test()
```
However it threw the error:
```
self.trainer._results.extract_batch_size(split_batch)
AttributeError: 'NoneType' object has no attribute 'extract_batch_size'
```
which presumably means that running the test has overwritten some necessary state?

Finally I considered spawning the test via a separate script and the python subprocess library. This would be sufficient since I only need the text output, however I think the GPU allocation would cause an OOM error for one of the 2 processes. If I can figure that part out, this approach might also solve the issue of running it on a single GPU?

Thanks for any thoughts or advice.

**Comment by turian** [comment]
This is also useful when debugging why test scores are very different than validation scores. In that case, it's useful to see validation vs test every epoch.

**Comment by carmocca** [comment]
Checking the test set performance during fitting can be considered "cheating", in any case, you could treat your test set dataloader as a "validation" dataloader and return it from `val_dataloaders` or pass it to `trainer.fit(val_dataloaders=...)`.

**Comment by ananthsub** [comment]
I believe @carmocca 's suggestion could work for your use case as Lightning will run sequentially process the validation dataloaders passed in.

However, you'd need to be very careful, especially when logging metrics, to take into account the `dataloader_idx` in the `validation_step` to avoid things like inadvertent hyperparameter optimization on the test set.

**Comment by turian** [comment]
@carmocca I'm aware of this build we're building an audio ML benchmark suite. The test set has special postprocessing and scoring logic we want to carefully scrutinize.

**Comment by jipson7** [comment]
> Checking the test set performance during fitting can be considered "cheating" and is generally not recommended.
> 
> In any case, you could treat your test set dataloader as a "validation" dataloader and return it from `def val_dataloaders()` or pass it to `trainer.fit(val_dataloaders=...)`.

Thanks for the suggestion, Ill give it a shot.

**Comment by tchaton** [comment]
Hey @turian,

I believe merging `val_dataloaders = val_dataloaders + test_dataloaders` is definitely the recommend approach.

I don't believe we would want to support this, especially on 1 GPU.

Closing this feature request.

Best,
T.C

**Comment by Erotemic** [comment]
> Checking the test set performance during fitting can be considered "cheating" and is generally not recommended.

I strongly disagree here. It is only cheating if you use that information to make decisions. It is absolutely valid to look at the evolution of the performance on the test set as training progresses, and in many cases it is critical to the research itself.

The current strategy of overloading the validation dataloader prevents you from using a validation dataset to make decisions while also studying the post-hoc performance on the test set.

Yes, people could use this to "cheat", but the same thing is true for looking at the results of the test set on the last epoch, and then making decisions about training a new model. I don't think this is lightning's problem to solve, but it could make reduce friction of research on techniques that use a validation set to make decisions (e.g. about learning rate).
