### ISSUE TITLE
Add option to not flatten config in `WandbLogger.log_hyperparams`

### ISSUE THREAD

**Issue by xvr-hlt** [PyTorchLightning/pytorch-lightning#9264]
## 🚀 Feature

Make the config flattening that happens in `WandbLogger.log_hyperparams` optional.

### Motivation

Wandb support nested config by default. Furthermore, by flattening the configuration it makes it more difficult to load an experiment from a wandb run – instead of taking the config directly from the run, you have to un-flatten it first (or really, not use log_hyperparams and instead do it manually).

### Pitch

Add `flatten: bool = True` as a kwarg in `log_hyperparams`.

Perhaps this should be a flag in the base class too? Unsure if other loggers require hyperparam flattening so outside my ken.

Happy to make a PR if we approve.

**Comment by rohitgr7** [comment]
or maybe you can override `WandbLogger.log_hyperparams` and remove that LOC from your custom logger. just a workaround though.

**Comment by borisdayma** [comment]
Actually should we flatten at all?
What was the reason for it?
