### ISSUE TITLE
Automate choosing sampler 

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#927]
## 🚀 Feature
Let's automate choosing the sampler.

### 
Case 1 (DDP, training):
Default to distributedSampler
```
sampler = DistributedSampler(dataset)
```

Case 2 (training):
```
sampler = RandomSampler(dataset)
```

Case 3 (val, test):
```
sampler = SequentialSampler(dataset)
```

Case 4 (tpu, train, val, test):
```
xm.DistributedSampler(dataset)
```
### Motivation

Samplers are hard and should be automated.

@srush

**Comment by srush** [comment]
I don't know if it is possible, but it would also be great is TPU Test at least could somehow be sequential. In NLP it is common just to print out the test results to a file and use an external script for final eval. Having them in order is nice (alternatively I guess id's could be threaded through and sorted.)
