### ISSUE TITLE
Support deadlock detection mechanism in FSDP, Horovod and deepspeed plugins

### ISSUE THREAD

**Issue by four4fish** [PyTorchLightning/pytorch-lightning#9291]
## 🚀 Feature

Discussed in https://github.com/PyTorchLightning/pytorch-lightning/pull/9267

Two issues :
1. FSDP, Horovod and deepspeed plugins extended DDP, and overrides pre_dispatch - where share_pid and _share_information_to_prevent_deadlock get called. As result, pid share and deadlock avoiding is not supported in these plugins. 

2. Because the _share_information_to_prevent_deadlock is not called in FSDP, Horovod and deepspeed, the sync_dir is not initialized. And reconciliate_processes need sync_dir to create recovery path. So reconciliate_processes is not supported because sync_dir is none in these plugins.

`def reconciliate_processes(self, trace: str):
        if self.world_size < 2:
            return

        sync_dir = self._sync_dir

        Path(sync_dir).mkdir(parents=True, exist_ok=True)`

### Pitch

Longterm: flatten the inheritance - FSDP, Horovod and deepspeed should extend parallel plugin instead of DDP. The characteristics are pretty different for these plugins. Flatten the inheritage could avoid fail silently and wrong assumptions. 

Now: add _share_information_to_prevent_deadlock to FSDP, Horovod and deepspeed plugins

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by ananthsub** [comment]
@four4fish @tchaton I wonder if this process cleanup / deadlock detection is another "trait" for the training type plugins, similar to the has block backward sync discussion

**Comment by tchaton** [comment]
Hey @ananthsub,

Definitely, I believe it would be its own mixin.

Best,
T.C
