### ISSUE TITLE
PyTorch Lightning Ecoystem Unittesting Library

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#9294]
## 🚀 Feature

Lightning is currently being used by multiple libraries out there and PyTorch Lightning sometimes introduce some breaking changes, which might have some severe impacts when use in production.

Furthermore, it is pretty un-likely a library using Lightning 1.0 would work out of the box with Lightning 1.5.0dev.

This feature is meant to make Lightning more reliable by extending its test stacks to lightning community libraries.

Here is the feature proposal.

* Create a Lightning Ecosystem framework as a submodule of Lightning
* Community Libraries will be able to add some optimised tests with their own components built on top of Lightning.
* Those tests would be run on Lightning nightlies to ensure Lightning doesn't introduce any breaking change over time.

Conditions:
* Each library test should be relying on a frozen version of the library. Multiple versions could be tested out, but Lightning master should always be used.

```
folder_1/
      test.py
      requirements.txt # frozen requirements.
folder_2/
      test.py
      requirements.txt # frozen requirements.
...
```

Open questions:

* Should we introduce a dev branch for merging all PRs, run the community tests and automatically merge dev into master if successful ?

### Alternatives

create template for integration repos #9315

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by tchaton** [comment]
@ananthsub @awaelchli @Borda

**Comment by awaelchli** [comment]
@tchaton I like it! 

> Should we introduce a dev branch for merging all PRs, run the community tests and automatically merge dev into master if successful ?

Who's responsibility will it be to fix the dev branch? Since versions are pinned as you explained, to resolve any issue that requires changes to the third party we would be blocked potentially quite a long time, even if we ourselves submit PRs.

**Comment by Borda** [comment]
In general, I like the motivation and benefits of integration testing, see also our partial integration test with TM
https://github.com/PyTorchLightning/metrics/tree/master/integrations

> * Community Libraries will be able to add some optimised tests with their own components built on top of Lightning.

I feel that could be blocking integrations at scale... Meaning if we have five 3rd party integration and one ill be failing we get a red flag for all so it won't be very simple to detect which integration is failing... so I may rather suggest #9315

**Comment by tchaton** [comment]
Thanks @awaelchli @Borda.

Let's close this one in favour of #9315.

I believe we can still run the other library within Lightning CI on post merge to master, but more as an indication.

Best,
T.C
