### ISSUE TITLE
element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by vivekruhela** [PyTorchLightning/pytorch-lightning#9299]
## Proposed refactoring or deprecation

I am trying to train a simple CNN using pytorch lightning  (I am doing this first  time). And I am getting an error as `element 0 of tensors does not require grad and does not have a grad_fn`.
**Data Description**: I am using imbalanced data with 95% one class and 5% second class with each sample has a feature matrix of 1316*162. There are in total 1200 samples. So U have written my own dataloader and tried to implement the pytorch lightening as shown below:

```py
      class custom_dataloader(torch.utils.data.Dataset):

          def __init__(self,sfile,lfile,root_dir):

            self.name_frame = sfile  # a list of samples like [sample1, sample12,....]
            self.label_frame = lfile  # a list of sample labels in the same order like [0,1,0,0,....]
            
        self.root_dir = root_dir  #parent directory where all the feature matrix are saved

    def __len__(self):
        return len(self.name_frame)

    def __getitem__(self, idx):
        
        sname = os.path.join(self.root_dir, self.name_frame[idx])
        feat = pd.read_csv(sname,index_col=0, header=0).to_numpy()
        scaler = StandardScaler()
        feat  =scaler.fit_transform(feat)
        feat = torch.tensor(feat).float()
        label = torch.tensor(int(self.label_frame[idx])).float()
        sample = (feat,label)
        return sample

        `

Now the remaining for lightning data module and dl module codes are as follows:

    class Data(pl.LightningDataModule):
    
        def __init__(self,train_sfile, val_sfile, train_lfile, val_lfile,root_dir):
        super(Data,self).__init__()
        
        self.train_sfile = train_sfile
        self.train_lfile = train_lfile
        self.val_sfile = val_sfile
        self.val_lfile = val_lfile
        self.root_dir = root_dir
    
    def train_dataloader(self):
        train_batch_loader = custom_dataloader(self.train_sfile, self.train_lfile, self.root_dir)
        return torch.utils.data.DataLoader(train_batch_loader,batch_size=16,shuffle=True, num_workers=20)
    
    def val_dataloader(self):
        test_batch_loader = custom_dataloader(self.val_sfile, self.val_lfile, self.root_dir)
        return torch.utils.data.DataLoader(test_batch_loader,batch_size=16,shuffle=True, num_workers=20)

    class model(pl.LightningModule):
        def __init__(self):
        super(model,self).__init__()
        
        self.conv1 = nn.Conv2d(1, 16, (3,3))
        self.conv2 = nn.Conv2d(16, 16, (3,3),padding=0)
        self.maxpool = nn.MaxPool2d((2,2),stride=(2,2))
        self.fc1 = nn.Linear(16, 2)
        self.dropout = nn.Dropout(0.5)
        self.leakyrelu = nn.LeakyReLU(0.3)
        self.loss = nn.CrossEntropyLoss(weight=torch.from_numpy(np.array([1.,20.])).float())
        
    def forward(self, x):
        
        x = x.reshape(1,1,1316,162)
        x = self.conv1(x)
        x = self.leakyrelu(x)
        x = self.maxpool(x)
        
        x = x.reshape(1,16,657,-1)
        x = self.conv2(x)
        x = self.leakyrelu(x)
        x = self.maxpool(x)
        
        x = x.reshape(1,16,327,-1)
        x = self.conv2(x)
        x = self.leakyrelu(x)
        x = self.maxpool(x)
        
        x = x.reshape(1,16,162,-1)
        x = self.conv2(x)
        x = self.leakyrelu(x)
        
        x = F.adaptive_avg_pool2d(x, (1, 1))
        x = x.reshape(-1,16)

        x = self.fc1(x)
        x = self.dropout(x)
        output = F.log_softmax(x, dim=1)
        
        return output
    
    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=0.001,weight_decay=1e-5)
    
    
    def training_step(self,train_batch, batch_idx):
        tr_loss = 0
        x, y = train_batch # for batch size of 16 and accelerator dp, I am getting here a batch of 8 for 1 gpu and 8 for another gpu, 
        y = y.long()
        for i in range(y.shape[0]):
            logits = self.forward(x[i])
            print(logits.requires_grad,y[i].requires_grad)
            loss = self.loss(logits, y[i].view(logits.shape[0]))
            tr_loss += loss.item()
        return tr_loss
    
    def validation_step(self,valid_batch, batch_idx):
        te_loss = 0
        x, y = valid_batch
        y = y.long()
        for i in range(y.shape[0]):
            logits = self.forward(x[i])
            loss = self.loss(logits,label.view(logits.shape[0]))
            te_loss += loss.item()
        
    clf = model()
    root_dir = './NN/all_feat_mat'
    sfile = './NN/samples.txt'
    lfile = './NN/labels.txt'
    X = open(sfile).read().split('\n')[:-1]
    Y = open(lfile).read().split('\n')[:-1]
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33)
    data_batch = Data(X_train, X_test, y_train, y_test,root_dir)
    trainer = pl.Trainer(gpus=2,
                     max_epochs=100,
                     accelerator='dp',
                     num_sanity_val_steps=0)
    trainer.fit(clf,data_batch)`
```

### Motivation

I am quite interested in using several feature of pytorch lightening such as automatic  tensor-board implementation, grid search in CNN and many others. I have learned basic examples of lightning using available documentations and trying to use the same way as described. But  unfortunately, it is not working as expected.

### Pitch

I expect it to work it smoothly. If we look into the error message and it's backtrace, it shows that loss function needs to have `reqd_grad=True`. I tried this too but didn't work. So  how to make optimizor automatically able to take the weighted cross-entropy loss function.

### Additional context

I am attaching the error message and its back trace here. The `True` and `False` printed below shows the output of `logits.requires_grad,y[i].requires_grad` i.e. the logits and targets grad states.:

`GPU available: True, used: True
TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

  | Name      | Type             | Params
-----------------------------------------------
0 | conv1     | Conv2d           | 160   
1 | conv2     | Conv2d           | 2.3 K 
2 | maxpool   | MaxPool2d        | 0     
3 | fc1       | Linear           | 34    
4 | dropout   | Dropout          | 0     
5 | leakyrelu | LeakyReLU        | 0     
6 | loss      | CrossEntropyLoss | 0     
-----------------------------------------------
2.5 K     Trainable params
0         Non-trainable params
2.5 K     Total params
0.010     Total estimated model params size (MB)

Epoch 0: 0%
0/77 [00:02<?, ?it/s]

True False
True False
TrueTrue False
 False
True False
True False
True False
True False
True False
True False
True False
True False
True False
True False
True False
True False

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-12-202a7f2e8d17> in <module>
      3                      accelerator='dp',
      4                      num_sanity_val_steps=0)
----> 5 trainer.fit(clf,data_batch)

~/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloader, val_dataloaders, datamodule)
    497 
    498         # dispath `start_training` or `start_testing` or `start_predicting`
--> 499         self.dispatch()
    500 
    501         # plugin will finalized fitting (e.g. ddp_spawn will load trained model)

~/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in dispatch(self)
    544 
    545         else:
--> 546             self.accelerator.start_training(self)
    547 
    548     def train_or_test_or_predict(self):

~/miniconda3/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py in start_training(self, trainer)
     71 
     72     def start_training(self, trainer):
---> 73         self.training_type_plugin.start_training(trainer)
     74 
     75     def start_testing(self, trainer):

~/miniconda3/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py in start_training(self, trainer)
    112     def start_training(self, trainer: 'Trainer') -> None:
    113         # double dispatch to initiate the training loop
--> 114         self._results = trainer.run_train()
    115 
    116     def start_testing(self, trainer: 'Trainer') -> None:

~/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in run_train(self)
    635                 with self.profiler.profile("run_training_epoch"):
    636                     # run train epoch
--> 637                     self.train_loop.run_training_epoch()
    638 
    639                 if self.max_steps and self.max_steps <= self.global_step:

~/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py in run_training_epoch(self)
    491             # ------------------------------------
    492             with self.trainer.profiler.profile("run_training_batch"):
--> 493                 batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
    494 
    495             # when returning -1 from train_step, we end epoch early

~/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py in run_training_batch(self, batch, batch_idx, dataloader_idx)
    653 
    654                         # optimizer step
--> 655                         self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)
    656 
    657                     else:

~/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py in optimizer_step(self, optimizer, opt_idx, batch_idx, train_step_and_backward_closure)
    432             on_tpu=self.trainer._device_type == DeviceType.TPU and _TPU_AVAILABLE,
    433             using_native_amp=using_native_amp,
--> 434             using_lbfgs=is_lbfgs,
    435         )
    436 

~/miniconda3/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py in optimizer_step(self, epoch, batch_idx, optimizer, optimizer_idx, optimizer_closure, on_tpu, using_native_amp, using_lbfgs)
   1385             # wraps into LightingOptimizer only for running step
   1386             optimizer = LightningOptimizer._to_lightning_optimizer(optimizer, self.trainer, optimizer_idx)
-> 1387         optimizer.step(closure=optimizer_closure)
   1388 
   1389     def optimizer_zero_grad(self, epoch: int, batch_idx: int, optimizer: Optimizer, optimizer_idx: int):

~/miniconda3/lib/python3.7/site-packages/pytorch_lightning/core/optimizer.py in step(self, closure, *args, **kwargs)
    212             profiler_name = f"optimizer_step_and_closure_{self._optimizer_idx}"
    213 
--> 214         self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)
    215         self._total_optimizer_step_calls += 1
    216 

~/miniconda3/lib/python3.7/site-packages/pytorch_lightning/core/optimizer.py in __optimizer_step(self, closure, profiler_name, **kwargs)
    132 
    133         with trainer.profiler.profile(profiler_name):
--> 134             trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)
    135 
    136     def step(self, *args, closure: Optional[Callable] = None, **kwargs):

~/miniconda3/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py in optimizer_step(self, optimizer, opt_idx, lambda_closure, **kwargs)
    275         )
    276         if make_optimizer_step:
--> 277             self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)
    278         self.precision_plugin.post_optimizer_step(optimizer, opt_idx)
    279         self.training_type_plugin.post_optimizer_step(optimizer, opt_idx, **kwargs)

~/miniconda3/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py in run_optimizer_step(self, optimizer, optimizer_idx, lambda_closure, **kwargs)
    280 
    281     def run_optimizer_step(self, optimizer: Optimizer, optimizer_idx: int, lambda_closure: Callable, **kwargs):
--> 282         self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)
    283 
    284     def optimizer_zero_grad(self, current_epoch: int, batch_idx: int, optimizer: Optimizer, opt_idx: int) -> None:

~/miniconda3/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py in optimizer_step(self, optimizer, lambda_closure, **kwargs)
    161 
    162     def optimizer_step(self, optimizer: torch.optim.Optimizer, lambda_closure: Callable, **kwargs):
--> 163         optimizer.step(closure=lambda_closure, **kwargs)

~/miniconda3/lib/python3.7/site-packages/torch/optim/optimizer.py in wrapper(*args, **kwargs)
     86                 profile_name = "Optimizer.step#{}.step".format(obj.__class__.__name__)
     87                 with torch.autograd.profiler.record_function(profile_name):
---> 88                     return func(*args, **kwargs)
     89             return wrapper
     90 

~/miniconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     26         def decorate_context(*args, **kwargs):
     27             with self.__class__():
---> 28                 return func(*args, **kwargs)
     29         return cast(F, decorate_context)
     30 

~/miniconda3/lib/python3.7/site-packages/torch/optim/adam.py in step(self, closure)
     64         if closure is not None:
     65             with torch.enable_grad():
---> 66                 loss = closure()
     67 
     68         for group in self.param_groups:

~/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py in train_step_and_backward_closure()
    648                         def train_step_and_backward_closure():
    649                             result = self.training_step_and_backward(
--> 650                                 split_batch, batch_idx, opt_idx, optimizer, self.trainer.hiddens
    651                             )
    652                             return None if result is None else result.loss

~/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py in training_step_and_backward(self, split_batch, batch_idx, opt_idx, optimizer, hiddens)
    754                 if result is not None:
    755                     with self.trainer.profiler.profile("model_backward"):
--> 756                         self.backward(result, optimizer, opt_idx)
    757 
    758                     # hook - call this hook only

~/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py in backward(self, result, optimizer, opt_idx, *args, **kwargs)
    784         else:
    785             result.closure_loss = self.trainer.accelerator.backward(
--> 786                 result.closure_loss, optimizer, opt_idx, should_accumulate, *args, **kwargs
    787             )
    788 

~/miniconda3/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py in backward(self, closure_loss, optimizer, optimizer_idx, should_accumulate, *args, **kwargs)
    255 
    256         output = self.precision_plugin.backward(
--> 257             self.lightning_module, closure_loss, optimizer, optimizer_idx, should_accumulate, *args, **kwargs
    258         )
    259 

~/miniconda3/lib/python3.7/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py in backward(self, model, closure_loss, optimizer, opt_idx, should_accumulate, *args, **kwargs)
     69         # do backward pass
     70         if automatic_optimization:
---> 71             model.backward(closure_loss, optimizer, opt_idx)
     72         else:
     73             closure_loss.backward(*args, **kwargs)

~/miniconda3/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py in backward(self, loss, optimizer, optimizer_idx, *args, **kwargs)
   1246         """
   1247         if self.trainer.train_loop.automatic_optimization or self._running_manual_backward:
-> 1248             loss.backward(*args, **kwargs)
   1249 
   1250     def toggle_optimizer(self, optimizer: Optimizer, optimizer_idx: int):

~/miniconda3/lib/python3.7/site-packages/torch/_tensor.py in backward(self, gradient, retain_graph, create_graph, inputs)
    253                 create_graph=create_graph,
    254                 inputs=inputs)
--> 255         torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
    256 
    257     def register_hook(self, hook):

~/miniconda3/lib/python3.7/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    147     Variable._execution_engine.run_backward(
    148         tensors, grad_tensors_, retain_graph, create_graph, inputs,
--> 149         allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
    150 
    151 

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn`

Kindly suggests.
______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by tchaton** [comment]
Hey @vivekruhela,

I can see from your code you are mis-using PyTorch. You should not use `tr_loss += loss.item()`. This convert the loss into a float which explains the error message.

Best,
T.C

**Comment by vivekruhela** [comment]
Thanks for pointing this out. Can you suggest for the following question:

I am using the batch size 16 so that there are 16 samples in 1 batch. I am also using `dp` accelerator. Now in `training_step` function, everytime I get a batch of 8 samples (I think 8 sample for 2 gpus each so it becomes 16 in total). I need to run model for each sample and train it. (same issue for valid_step also. So how I can improve my training_step such that I can handle a batch of 16 and get an average loss of entire batch.  Thanks

**Comment by tchaton** [comment]
When you use dp, a single batch is being loaded and splitted across GPUs. 
This isn't really efficient.
I would advice you to use `ddp` which is 3x time faster :) Each gpu will receive a batch with 16 samples.

I will be closing this issue. Feel free to re-open if you can't make it work.

**Comment by vivekruhela** [comment]
Problem is solved by changing `dp` by `ddp` and correcting `training_step` and `validation_step`. I am now looking forward with tensor-board logging and other features. Thanks a lot for your help.
