### ISSUE TITLE
Exceptions in a child process would lead to a zombie process

### ISSUE THREAD

**Issue by w2kun** [PyTorchLightning/pytorch-lightning#9303]
## 🐛 Bug

When I was training a model with DDP, I found that if a child process throws an exception, it will lead to a zombie process. In this case, the CTRL+C cannot terminate the main process.

![processes](https://user-images.githubusercontent.com/66891683/131962511-342c35bb-1d27-46ce-a4bf-90c8d7e09db8.png)

The blue and red boxes indicate the main and child processes, respectively.

### To Reproduce

The following code can reproduce the problem.

```python
import torch.nn
from pytorch_lightning import Trainer, LightningModule
from torch.utils.data import Dataset, DataLoader


class DemoModule(LightningModule):
    def __init__(self):
        super(DemoModule, self).__init__()

        self.linear = torch.nn.Linear(3, 3)

    def training_step(self, batch, batch_idx):
        return 0.0

    def configure_optimizers(self):
        adam = torch.optim.Adam(self.parameters(), 1.0e-3)
        return adam


class DemoData(Dataset):
    def __init__(self):
        self.data = list(range(10))

    def __len__(self):
        return len(self.data)

    def __getitem__(self, item):
        return self.data[item]


def main():

    # prepare data loader
    train_loader, val_loader = DataLoader(DemoData(), 1, True), DataLoader(DemoData(), 1, False)

    # define model
    model = DemoModule()

    # define trainer
    trainer = Trainer(accelerator='ddp',
                      gpus=2,
                      num_nodes=1,
                      max_epochs=100)

    if trainer.local_rank != 0:
        raise RuntimeError('An error occurred.')

    # training
    trainer.fit(model, train_loader, val_loader)


if __name__ == '__main__':
    main()

```

### Expected behavior

The main process exits after the child process exits.

### Environment

- PyTorch Lightning Version (e.g., 1.3.0): 1.4.4
- PyTorch Version (e.g., 1.8): 1.7.1
- Python version: 3.6.8
- OS (e.g., Linux): Linux
- CUDA/cuDNN version: 11.0
- How you installed PyTorch (`conda`, `pip`, source): pip
- Backend: NCCL
- Accelerator: DDP
- GPUS: 2 * TITAN RTX

**Comment by ananthsub** [comment]
@w2kun this is likely due to the keyboard handling exception logic. This is very similar to #9303 (@awaelchli )

@w2kun does using Ctrl+D / system exit instead work for you to kill these processes?

**Comment by w2kun** [comment]
Hi, 
I tried ctrl+d but it doesn't seem to work. My current solution is using "kill + PID of main process". It can terminate the whole process.
