### ISSUE TITLE
Remove the prefix 'version_' in tensorboard logging

### ISSUE THREAD

**Issue by Ir1d** [PyTorchLightning/pytorch-lightning#931]
## 🚀 Feature

![image](https://user-images.githubusercontent.com/10709657/75208038-64cbdb00-57b5-11ea-8784-29c3759e06b9.png)

### Motivation

In tensorboard there's an explicit '/', and I think there's no need for this 'version_'.
it makes the whole stuff too long.

### Pitch

I can bring a PR for this.

**Comment by williamFalcon** [comment]
@Ir1d people usually version with numbers though. You might be the edge case with names here. I would be ok with `v_` instead

**Comment by Ir1d** [comment]
I would be ok with `v_` also, but wouldn't it be better if we allow users to decide the whole thing by themselves? I mean that let them use whatever prefix they like

**Comment by williamFalcon** [comment]
done
