### ISSUE TITLE
Setting `max_time` in trainer triggers deprecation warning

### ISSUE THREAD

**Issue by manuel-munoz-aguirre** [PyTorchLightning/pytorch-lightning#9346]
## 🐛 Bug

Setting `max_time` in `Trainer` triggers a deprecation warning:
```
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/callback_hook.py:103: LightningDeprecationWarning: The signature of `Callback.on_train_epoch_end` has changed in v1.3. `outputs` parameter has been removed. Support for the old signature will be removed in v1.5
  "The signature of `Callback.on_train_epoch_end` has changed in v1.3."
```

### To Reproduce
Reproduced by adding the `max_time` flag in the BoringModel notebook.

### Expected behavior
No warning should appear.

### Environment

* CUDA:
        - GPU:
        - available:         False
        - version:           10.2
* Packages:
        - numpy:             1.19.0
        - pyTorch_debug:     False
        - pyTorch_version:   1.9.0+cu102
        - pytorch-lightning: 1.4.5
        - tqdm:              4.62.2

**Comment by kaushikb11** [comment]
Umm, Why didn't this issue close automatically after the PR getting merged lol? @awaelchli

**Comment by awaelchli** [comment]
It should have, no idea why. Thanks for taking care of it.
