### ISSUE TITLE
Error occurs when returning `loss=None` with precision=16

### ISSUE THREAD

**Issue by deng-cy** [PyTorchLightning/pytorch-lightning#9352]
### To Reproduce
The BoringModel colab:
`https://colab.research.google.com/drive/1BycY9Bbnqp5TiTp_8jjpyZn-TUmhIP1q?usp=sharing`

A simpler version of the colab: what I did was to change `training_step` to
```
    def training_step(self, batch, batch_idx):
      if batch_idx==1:
        return None
      else:
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"loss": loss}
```
to return `loss=None`, and use 
```
    trainer = pl.Trainer(
        gpus=1,
        max_epochs=1, 
        progress_bar_refresh_rate=20,
        precision=16
    )
```
to use 16-digit precision. 

### Expected behavior

`RuntimeError: unscale_() has already been called on this optimizer since the last update().`

### Environment

* CUDA:
	- GPU:
		- Tesla K80
	- available:         True
	- version:           10.2
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.0+cu102
	- pytorch-lightning: 1.4.5
	- tqdm:              4.62.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
	- processor:         x86_64
	- python:            3.7.11
	- version:           #1 SMP Sat Jun 5 09:50:34 PDT 2021

Similar issues also occur on my own computer (Windows 10, Pytorch 1.9.0, Lightning 1.4.2)

### Additional context

If it returns `loss=None` at the very beginning, i.e.,
```
    def training_step(self, batch, batch_idx):
      if batch_idx==0:
        return None
      else:
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"loss": loss}
```
It gives another error

`AssertionError: Attempted unscale_ but _scale is None.  This may indicate your script did not use scaler.scale(loss or outputs) earlier in the iteration.`

I think it might be related to a similar issue [#2343](https://github.com/PyTorchLightning/pytorch-lightning/issues/2343)

**Comment by justusschock** [comment]
Hi @deng-cy 

Thanks for the detailed reproduction. However, as stated by the [docs](https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_module.html#training-step) we don't (yet) support skipping batches with `precision=16`
