### ISSUE TITLE
Gradient clipping error: hookedclipgradnorm() missing 2 required positional arguments

### ISSUE THREAD

**Issue by Jovp** [PyTorchLightning/pytorch-lightning#9361]
## 🐛 Bug

When training my model with gradient clipping I get:

`TypeError: hookedclipgradnorm() missing 2 required positional arguments: 'norm_type' and 'error_if_nonfinite'`

The error is raised from :
File "pytorch_lightning/plugins/precision/precision_plugin.py", line 137, in clip_grad_by_norm.
The error is solved by replacing:

`torch.nn.utils.clip_grad_norm_(parameters, clip_val)`
by
`torch.nn.utils.clip_grad_norm_(parameters, clip_val, 2, False)`

### To Reproduce

Unfortunately, I am not able to reproduce this problem in a light environment and cannot share the code.

### Expected behavior

The norm should be computed with default parameters without errors.

### Environment

- PyTorch Lightning Version : 1.4.5
- PyTorch Version : 1.9
- Python version: 3.8.10
- OS (e.g., Linux): Linux
- CUDA/cuDNN version: 11.2
- GPU models and configuration: V100 32GB
- How you installed PyTorch (`conda`, `pip`, source): pip

### Additional context

I noticed that gradient clipping was rewritten recently to use PyTorch's version. If I remember correctly in 1.4.3 (when the code was not relying on Pytorch) I didn't have this issue.

**Comment by rohitgr7** [comment]
weird since `torch.nn.utils.clip_grad_norm_` already have defaults set https://pytorch.org/docs/stable/generated/torch.nn.utils.clip_grad_norm_.html

**Comment by Jovp** [comment]
Yes! I expect this one to be quite involved...

**Comment by Jovp** [comment]
Unfortunately not, this is not something that I defined myself, and can't seem to find this function anywhere.

**Comment by Jovp** [comment]
I could find the third party responsible for this one. Thanks a lot for helping!
