### ISSUE TITLE
Pytorch mlflow creating 2 runs when running through MLProject file

### ISSUE THREAD

**Issue by piseabhijeet** [PyTorchLightning/pytorch-lightning#9370]
## 🚀 Feature

PL's mlflow logger creates a new run for logging metrics when trying to run a project using MLProject file. Can you add active run or run_uuid to mlf_logger to combine the logging in one run?

### Motivation

 I'm always frustrated when PL logger creates 2 runs for tracking metrics and hyper parameters.

### Pitch

It would be great if the logger accepts current run_uuid as a parameter to log things.
### Alternatives

One workaround is dont use MLProject file but it wouldn't make the project integrable.

### Additional context

Code snippet:
mlf_logger = MLFlowLogger(experiment_name=params.Experiment, tracking_uri=params.tracking_uri)
#mlflow.pytorch.autolog() <- this is not used

trainer = pl.Trainer(....., logger=mlf_logger)

Command to run the code:
mlflow run . -e train_val --no-conda --experiment-name 'Test'

This gives two runs, one i guess corresponds to the mlflow run .... command and other corresponding to auto_log() function.. 
![image](https://user-images.githubusercontent.com/57705684/132498009-a159ab42-ed0c-48ba-8c10-1f988662e59f.png)

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by piseabhijeet** [comment]
Hi @carmocca 

Any plans to get this as a feature?

Thank you

**Comment by carmocca** [comment]
I am not familiar with the MLFlow logger implementation, perhaps it would be good for you to ping or ask somebody on their side.
