### ISSUE TITLE
logger is NoneType hence doesn't have any experiment or other functionality in a lightning module

### ISSUE THREAD

**Issue by helldragger** [PyTorchLightning/pytorch-lightning#939]
## 🐛 Bug
When trying to use the logging abilities of lightning, I hit a wall, the default and tensorboard loggers both seem to stay uninitialized when calling ```trainer.fit(model)```, resulting in crashes everytime I try to log something.

### To Reproduce

Create a lightning module as such 
```
class SimpleRegressor(pl.LightningModule):
    ...
```

Use the logger anywhere to get this kind of stacktrace:

```
d:\Documents\projects\MetaWatch\MetaWatch\notebooks\audio-video-interest\simple_regressor.py in configure_optimizers(self)
    105         #see https://pytorch-lightning.readthedocs.io/en/latest/pytorch_lightning.core.lightning.html#pytorch_lightning.core.lightning.LightningModule.configure_optimizers
    106         # REQUIRED
--> 107         self.logger.experiment.add_hparams({'hidden_layer_size':self.hidden_layer_size,
    108                                             'linear_layer_size':self.linear_layer_size,
    109                                             'lstm_layers':self.lstm_layers})

AttributeError: 'NoneType' object has no attribute 'experiment'
```

#### Code sample
```
import pytorch_lightning as pl

class SimpleRegressor(pl.LightningModule):
    def __init__(self, cuda=False):
        super(SimpleRegressor, self).__init__()
        self.logger.experiment.add_hparams({'hidden_layer_size':1})
```

### Expected behavior

To log as described in the documentation.

### Environment
```
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Microsoft Windows 10 Pro    
GCC version: Could not collect  
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 970
Nvidia driver version: 441.12
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] pytorch-lightning==0.6.0
[pip3] tinynumpy==1.2.1
[pip3] torch==1.4.0
[pip3] torchvision==0.4.1
[conda] Could not collect
```

**Comment by ethanwharris** [comment]
Thanks for the issue! The intended way to acheive this is through a hook. When `__init__` is called on the `LightningModule`, the loggers won't have been created yet. I don't think there's any way to change that so we should update the docs to use a hook instead of `__init__`.

@PyTorchLightning/core-contributors any other thoughts on this?

**Comment by helldragger** [comment]
it also doesn't work in other functions, I tried in the training step, in the configure_optimizers too

**Comment by ethanwharris** [comment]
Ok, most of these work on master (i.e. if you install from github) for me - except `configure_optimizers`.

I've opened a PR (#964) which fixes that and cleans up the docs a bit.

**Comment by Beep-Boop-Bopa** [comment]
@helldragger where do I call the self.logger.experiment.add_hparams then? Rn it is in the test_epoch_end method.
![image](https://user-images.githubusercontent.com/42900802/111724885-7195f380-883c-11eb-9e3a-2fd79b8a8efb.png)
