### ISSUE TITLE
Ability to release resources associated with a DataLoader

### ISSUE THREAD

**Issue by cowwoc** [PyTorchLightning/pytorch-lightning#9390]
https://github.com/pytorch/pytorch/pull/35795 adds `DataLoader.persistent_workers` which is great from a performance point of view. Unfortunately when running multiple trials using Optuna, DataLoader workers take a long time to shut down after a trial completes.

When running under Windows, I am seeing each worker process allocate a commit size of 5GB. When `num_workers = 4` each trial commits 20GB of memory and it takes idle workers a long time (>1 minute) to shut down. If trials are short, I can easily end up with over 100GB of memory committed by worker processes which results in an out of memory error.

Is it possible to proactively shut down DataLoader workers at the end of a trial?

Does `DataLoader` provide a mechanism to release its resources? Does `teardown()` or other hooks provide a mechanism to close data loaders?

**Comment by cowwoc** [comment]
Per source-code comments of `_MultiProcessingDataLoaderIter` in `dataloader.py` the workers shut down when the `DataLoader` iterator is deleted. So it sounds as if someone is creating an iterator and never deleting it.

**Comment by ananthsub** [comment]
I wonder if one of https://github.com/PyTorchLightning/pytorch-lightning/pull/9387 or https://github.com/PyTorchLightning/pytorch-lightning/pull/9387]6 would address this

**Comment by cowwoc** [comment]
@ananthsub Maybe. But I noticed that no one ever explicitly deletes the returned iterator (I placed a breakpoint in `__del__` and it was never triggered). Ideally we should be deleting the iterator explicitly as this would result in instantaneous cleanup without having to rely on the garbage collector.

**Comment by cowwoc** [comment]
Specifically, I am referring to https://github.com/pytorch/pytorch/blob/e5ab0d1013072c26586b369536bccac648843958/torch/utils/data/dataloader.py#L1328

**Comment by tchaton** [comment]
Yes, good call. There is a ticket to address this: https://github.com/PyTorchLightning/pytorch-lightning/issues/9385

**Comment by tchaton** [comment]
Dear @cowwoc,

Would you mind making a PR where iterator are explicitly deleted ?

Best,
T.C

**Comment by tchaton** [comment]
The data_fetcher should also keep a reference to the dataloader_iterator. Does this PR resolves your issues ?

**Comment by cowwoc** [comment]
> The data_fetcher should also keep a reference to the dataloader_iterator.

Sorry, I'm not sure what this means. Does it mean I should or should not `del` the data_fetcher reference?

> Does this PR resolves your issues ?

It seems to help. On the one hand, the worker processes are not killed immediately like I would like but on the other hand I didn't run out of memory when running Optuna tests over an hour. This might mean that GC is kicking in to clean up the worker processes right before the system runs out of memory. I'll try running Optuna over 8 hours. If it doesn't run out of memory then I think we can consider this issue to be fixed.

Thanks for your support!

**Comment by cowwoc** [comment]
@tchaton @carmocca @awaelchli So, some bad news regarding https://github.com/PyTorchLightning/pytorch-lightning/pull/9915...

Yes, worker processes are getting killed. But for some reason this is happening after every epoch instead of after a full training cycle. This means that even when I have `DataLoader(persistent_workers=True)` the workers are continually being killed and performance is terrible.

Is it possible to adjust the PR so workers are only killed at the end of the training cycle (not once per epoch)?

**Comment by tchaton** [comment]
Dear @cowwoc,

Would you be willing to make a PR with this change ?

Best,
T.C

**Comment by cowwoc** [comment]
@tchaton I just tested https://github.com/PyTorchLightning/pytorch-lightning/pull/10434 and it works great. Performance is way up and workers are shut down properly when training ends non-exceptionally.

The next problem I discovered is that when training is aborted by Optuna throwing `TrialPruned` exception then the workers are not shut down. I added a breakpoint in `AbstractDataFetcher.teardown()` and sure enough it is never invoked.

It sounds like we're missing exception catching somewhere. Here is Optuna's callback:

```
class PyTorchLightningPruningCallback(Callback):
    """PyTorch Lightning callback to prune unpromising trials.

    See `the example <https://github.com/optuna/optuna-examples/blob/
    main/pytorch/pytorch_lightning_simple.py>`__
    if you want to add a pruning callback which observes accuracy.

    Args:
        trial:
            A :class:`~optuna.trial.Trial` corresponding to the current evaluation of the
            objective function.
        monitor:
            An evaluation metric for pruning, e.g., ``val_loss`` or
            ``val_acc``. The metrics are obtained from the returned dictionaries from e.g.
            ``pytorch_lightning.LightningModule.training_step`` or
            ``pytorch_lightning.LightningModule.validation_epoch_end`` and the names thus depend on
            how this dictionary is formatted.
    """

    def __init__(self, trial: optuna.trial.Trial, monitor: str) -> None:
        _imports.check()
        super().__init__()

        self._trial = trial
        self.monitor = monitor

    def on_validation_end(self, trainer: Trainer, pl_module: LightningModule) -> None:
        epoch = pl_module.current_epoch

        current_score = trainer.callback_metrics.get(self.monitor)
        if current_score is None:
            message = (
                "The metric '{}' is not in the evaluation logs for pruning. "
                "Please make sure you set the correct metric name.".format(self.monitor)
            )
            warnings.warn(message)
            return

        self._trial.report(current_score, step=epoch)
        if self._trial.should_prune():
            message = "Trial was pruned at epoch {}.".format(epoch)
            raise optuna.TrialPruned(message)
```

Any ideas?

**Comment by cowwoc** [comment]
@carmocca Is it possible to reopen this issue until we fix exception-handling?

**Comment by tchaton** [comment]
Hey @cowwoc,

Yes, I was planning to do so. Thanks for pinging us.

Best,
T.C

**Comment by tchaton** [comment]
Hey @cowwoc,

Mind trying out this PR: https://github.com/PyTorchLightning/pytorch-lightning/pull/10463

Best,
T.C

**Comment by cowwoc** [comment]
@tchaton I can confirm https://github.com/PyTorchLightning/pytorch-lightning/pull/10463 shuts down workers on `optuna.TrialPruned` exception. Thank you.

**Comment by tchaton** [comment]
Hey @cowwoc, Thanks you for your implication on this :) Would you be willing to create a tutorial notebook for Lightning and Optuna in Lightning Tutorials ?

**Comment by cowwoc** [comment]
Unfortunately, I am a bit overwhelmed with family chores at the moment.

The TL;DR is "Include `PyTorchLightningPruningCallback(trial, monitor="val_loss")` in Trainer.callbacks".

* Detailed tutorial: https://medium.com/optuna/using-optuna-to-optimize-pytorch-lightning-hyperparameters-d9e04a481585 
* Example source code: https://github.com/optuna/optuna-examples/blob/main/pytorch/pytorch_lightning_simple.py
* API reference: https://optuna.readthedocs.io/en/latest/reference/generated/optuna.integration.PyTorchLightningPruningCallback.html#optuna.integration.PyTorchLightningPruningCallback

I hope this helps.
