### ISSUE TITLE
Check for deprecated keys sooner in checkpoint loading

### ISSUE THREAD

**Issue by ananthsub** [PyTorchLightning/pytorch-lightning#9403]
## Proposed refactoring or deprecation
Fail faster if the model checkpoint contains deprecated keys

### Motivation

We currently wait all the way until [`restore_callbacks`](https://github.com/PyTorchLightning/pytorch-lightning/blob/a079d7fccc0a9be25b40296f2a348c4b4f40c8cf/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L167-L179) to validate that a checkpoint dictionary doesn't contain deprecated keys. However, this happens after the initial checkpoint load, datamodule, and lightning module weights are resumed. 

It'd be better to fail faster immediately after the checkpoint load if the checkpoint contains deprecated keys.

### Pitch

Add a utility function in the checkpoint connector to handle loading & validation
```
def _load_and_validate(checkpoint_path: _PATH) -> Dict:
    checkpoint = self.trainer.training_type_plugin.load_checkpoint(checkpoint_path)
    if any(key in checkpoint for key in DEPRECATED_CHECKPOINT_KEYS):
            raise ValueError(
                "The checkpoint you're attempting to load follows an"
                " outdated schema. You can upgrade to the current schema by running"
                f" `python -m pytorch_lightning.utilities.upgrade_checkpoint --file {checkpoint_path}`"
            )
```    
and remove this check from `restore_callbacks`

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by awaelchli** [comment]
I would like to propose #9396. Users should not need to upgrade a checkpoint manually IMO.
