### ISSUE TITLE
Support for progress bar updates at infrequent epochs

### ISSUE THREAD

**Issue by jlperla** [PyTorchLightning/pytorch-lightning#9412]
## 🚀 Feature

Right now there is a way to only update the progress bar after every XXX steps but
1. It doesn't work with custom callbacks according to the docs
2. Doing it every XXX epochs is often much more natural.

### Motivation

For things that go through epochs and steps rapidly, the progress bar updates can cause an enormous amount of output.

This might slow things down with the flushing, but the bigger issue is on batch systems on the cloud where the logs are being captured to stdout.  those cannot do inplace changes to the text within a terminal, so the logs get enormous.

### Alternatives

There also doesn't seem to be a way to hack it with a custom ProgressBar class.

Soemthing like
```python
class InfrequentProgressBar(ProgressBar):

    def __init__(self,epoch_frequency):
        super().__init__()  # if you don't add refresh_rate = 0 then it still shows every time.
        self.epoch_frequency = epoch_frequency

    def on_train_epoch_start(self, trainer, *args):
        if trainer.current_epoch % self.epoch_frequency == 0:
            super().on_train_epoch_start(trainer, *args)

    def on_train_batch_end(self, trainer, *args):
        if trainer.current_epoch % self.epoch_frequency == 0:
            super().on_train_batch_end(trainer, *args)            

    def on_validation_batch_end(self, trainer, *args):
        if trainer.current_epoch % self.epoch_frequency == 0:
            super().on_validation_batch_end(trainer, *args)
```
As a callback seemed to only show the epoch updating infrently for the progress bar itself, but the underlying stuff added to `self.log` still updates rapidly.

cc: @tchaton

cc @borda @awaelchli @rohitgr7 @ananthsub @carmocca

**Comment by jlperla** [comment]
My current workaround is that I add the following to my config file:
```yaml
  callbacks:
    - class_path: pytorch_lightning.callbacks.progress.TQDMProgressBar
      init_args:
        refresh_rate: 1 # set to 0 for no bar, then change epoch_heartbeat
```
add a constructor argument called `epoch_heartbeat` to my model, and then add
```python
    def validation_epoch_end(self, outputs):
        # Only logs if the progress bar turned off
        if (
            (self.trainer.progress_bar_callback is None)
            and (self.hparams.epoch_heartbeat > 0)
            and (self.current_epoch % self.hparams.epoch_heartbeat == 0)
        ):
            print(f"Epoch {self.current_epoch}: {self.trainer.progress_bar_dict}")
```

If I don't do this, it wrecks the grid output.

**Comment by carmocca** [comment]
I think your workaround is perfectly fine.

> This might slow things down with the flushing, but the bigger issue is on batch systems on the cloud where the logs are being captured to stdout. those cannot do inplace changes to the text within a terminal, so the logs get enormous.

This is a big problem in the design of TQDM. https://github.com/PyTorchLightning/pytorch-lightning/pull/9000 attempted to fix it with no success.

@kaushikb11 is Rich better in this regard?

**Comment by jlperla** [comment]
Sounds good.  If you think this is part of bigger redesign then maybe the `stale-bot` was right and the issue should be closed.
