### ISSUE TITLE
Support stepping options for lr scheduler

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#945]
Currently schedulers get called every epoch. Sometimes though, we want them to be called every step.

Proposal 1: 
Allow configure_optimizers to return this:

```python
return Adam, {'scheduler': LRScheduler, 'interval': 'batch|epoch'}
```

@ethanwharris @Borda thoughts? any simpler more general way of doing this? i think this dict can eventually have more options if we need to.

@srush

**Comment by Borda** [comment]
@SkafteNicki is working on it... Thx!
