### ISSUE TITLE
PyTorch profiler not working with the new version 1.4.6

### ISSUE THREAD

**Issue by aprbw** [PyTorchLightning/pytorch-lightning#9450]
## 🐛 Bug

PyTorch profiler not working with the new version 1.4.6

### To Reproduce

https://colab.research.google.com/drive/1NH1lsglFW4RtQgWswsZPeiK8JsjAbtAz?usp=sharing

Just add `profiler = 'pytorch'` argument to the trainer of the boring model.

### Expected behavior

Not hitting assertion error, and profiler runs normally.

```
/usr/local/lib/python3.7/dist-packages/torch/profiler/profiler.py in events(self)
    363         to be used in the trace callback or after the profiling is finished
    364         """
--> 365         assert self.profiler
    366         return self.profiler.function_events
    367 

AssertionError: 
```

### Environment

* CUDA:
	- GPU:
	- available:         False
	- version:           10.2
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.0+cu102
	- pytorch-lightning: 1.4.6
	- tqdm:              4.62.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.11
	- version:           #1 SMP Sat Jun 5 09:50:34 PDT 2021

### Additional context

Changing to 1.4.5 fixes the issue.

**Comment by tchaton** [comment]
Hey @aprbw,

Mind using master ?

Best,
T.C

**Comment by aprbw** [comment]
Hi, I'm using:

`! pip install pytorch-lightning==1.4.6`

On google colab. I'm not sure how to use master on google colab.

**Comment by tchaton** [comment]
You can use master by doing: `pip install git+https://github.com/PyTorchLightning/pytorch-lightning.git`. 

Mind sharing your findings ?

Best,
T.C

**Comment by aprbw** [comment]
Thanks! It hits the exact same error even with the master branch.

I implemented them here: https://colab.research.google.com/drive/1NH1lsglFW4RtQgWswsZPeiK8JsjAbtAz?usp=sharing

**Comment by mikael10j** [comment]
Hi there,
I've the same issue. The problem is that the ending of the training phase seems to kill the pytorch profiler, that therefore doesn't exist anymore for the test phase. And looking into the code, indeed at the end of the `fit`, the function `describe()` is called, which in turn calls `summary()`. In the case of the lightning PytorchProfiler this function calls `self._delete_profilers()`.

**Comment by aprbw** [comment]
Still not working with PL 1.5.0

**Comment by tarrade** [comment]
Same issue with 1.5.2. The issue appear when calling trainer.test which is what  @mikael10j  described in details.

**Comment by aprbw** [comment]
I can confirm that this is fixed. Thank you.
