### ISSUE TITLE
Lightning CLI is incompatible with models defined by data

### ISSUE THREAD

**Issue by ml-mountainman** [PyTorchLightning/pytorch-lightning#9473]
### Discussed in https://github.com/PyTorchLightning/pytorch-lightning/discussions/9452

<div type='discussions-op-text'>

<sup>Originally posted by **ml-mountainman** September 11, 2021</sup>
Is there an easy way to make a [Lightning CLI](https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_cli.html) work with a [Lightning Module defined by data](https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_cli.html)? This seems like a very common design pattern.

For example (from the docs) it doesn't appear possible to easily convert the following to a Lightning CLI:
```
# init dm AND call the processing manually
dm = ImagenetDataModule()
dm.prepare_data()
dm.setup()

model = LitModel(out_features=dm.num_classes, img_width=dm.img_width, img_height=dm.img_height)
trainer.fit(model, dm)
```

The current CLI implementation works for model re-loading. However, it requires data-dependent attributes to be specified to the config files prior to fitting, which does not seem ideal.</div>

**Comment by tchaton** [comment]
I believe it could be possible by doing some linking on datamodule properties to the model.

@carmocca @mauvilsa Any ideas on how we could support this properly ?

**Comment by mauvilsa** [comment]
This does seem exactly the case for which links applied on instantiation were implemented, see [lightning_cli.html#argument-linking](https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_cli.html#argument-linking).

**Comment by ml-mountainman** [comment]
I definitely missed this. Thank you!
