### ISSUE TITLE
PermissionError: [WinError 32]

### ISSUE THREAD

**Issue by grudloff** [PyTorchLightning/pytorch-lightning#9474]
## 🐛 Bug

While training and saving checkpoints with tensorboard I get `PermissionError: [WinError 32] The process cannot access the file because it is being used by another process`. This happens after a long amount of epochs.

### To Reproduce

[The_BoringModel.ipynb](https://gist.github.com/grudloff/1f1973044bc48e00139723a179e1a891)

### Environment

* CUDA:

	- GPU:

		- NVIDIA GeForce RTX 3080

	- available:         True

	- version:           11.1

* Packages:

	- numpy:             1.20.3

	- pyTorch_debug:     False

	- pyTorch_version:   1.9.0

	- pytorch-lightning: 1.4.5

	- tqdm:              4.62.1

* System:

	- OS:                Windows

	- architecture:

		- 64bit

		- WindowsPE

	- processor:         AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD

	- python:            3.9.6

	- version:           10.0.19043

### Additional context

Using Visual Studio Code.

**Comment by tchaton** [comment]
Hey @grudloff,

It seems there is some weird interaction with Tensorboard and ModelCheckpoint. Tensorboard applies some lock on the folder and the ModelCheckpoint can't delete the previous wait.
Mind trying logger=False ?

Best,
T.C

**Comment by grudloff** [comment]
Hello @tadejsv, thanks for the help. It seems that this was the issue!

**Comment by grudloff** [comment]
Defining a ModelCheckpoint callback with a different dir also solves the problem.

**Comment by grudloff** [comment]
> Defining a ModelCheckpoint callback with a different dir also solves the problem.

Got the same Error, seems it didn't fix the issue. @tadejsv do you have any suggestions for making them both work together?

**Comment by grudloff** [comment]
Now trying with this:

```python
epochs = 20000
model = create_model(epochs=epochs)
dir = os.getcwd()
trainer = pl.Trainer(gpus=1, max_epochs=epochs, log_every_n_steps=10,
                     default_root_dir=dir+'\\tensorboard',
                     callbacks=[pl.callbacks.ModelCheckpoint(dirpath=dir+'\\checkpoint')])
trainer.fit(model)
```
And an OSError was raised, somehow the cell it is still running but seems to be doing nothing, the progress bar below doesn't update and no updates appear on tensorboard.

```
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name     | Type       | Params
----------------------------------------
0 | conv     | ModuleList | 17.3 K
1 | head     | ModuleList | 948   
2 | out_conv | Conv1d     | 10    
----------------------------------------
18.2 K    Trainable params
300       Non-trainable params
18.5 K    Total params
0.074     Total estimated model params size (MB)
Epoch 3:   9%|▉         | 1/11 [00:40<03:23, 20.34s/it, train_loss=0.0421, train_MAE=0.0918, val_loss=0.042, val_MAE=0.0909]
Epoch 1086:  91%|█████████ | 10/11 [00:02<00:00,  4.86it/s, train_loss=0.020, train_MAE=0.000597, val_loss=0.020, val_MAE=0.00058]Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\Usuario\.conda\envs\pytorch-gpu\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\Usuario\.conda\envs\pytorch-gpu\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 233, in run
    self._record_writer.write(data)
  File "C:\Users\Usuario\.conda\envs\pytorch-gpu\lib\site-packages\tensorboard\summary\writer\record_writer.py", line 40, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File "C:\Users\Usuario\.conda\envs\pytorch-gpu\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 519, in write
    self.fs.append(self.filename, file_content, self.binary_mode)
  File "C:\Users\Usuario\.conda\envs\pytorch-gpu\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 150, in append
    self._write(filename, file_content, "ab" if binary_mode else "a")
  File "C:\Users\Usuario\.conda\envs\pytorch-gpu\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 154, in _write
    with io.open(filename, mode, encoding=encoding) as f:
OSError: [Errno 22] Invalid argument: b'C:\\Users\\Usuario\\OneDrive - Universidad T\xc3\xa9cnica Federico Santa Mar\xc3\xada\\Escritorio\\Tesis\\Simulaciones\\tensorboard\\lightning_logs\\version_0\\events.out.tfevents.1631555589.DESKTOP-SM5NUIG.16340.1'
Epoch 1087:  91%|█████████ | 10/11 [00:02<00:00,  4.71it/s, train_loss=0.020, train_MAE=0.000601, val_loss=0.020, val_MAE=0.000576]
```
