### ISSUE TITLE
Tensorboard Profiler - Incorrect Number of worker(s) 

### ISSUE THREAD

**Issue by shrinath-suresh** [PyTorchLightning/pytorch-lightning#9476]
## 🐛 Bug

Number of workers(s) - shown in the profiler UI is not matching with the number of workers (num_workers attribute in ptl) used for dataloading.

![ptl-tensorboard](https://user-images.githubusercontent.com/63862647/133040006-35133f91-a13e-4c5b-bbfe-31e5caa5fdea.png)

### To Reproduce

Run the basic profiler example from pytorch lightning repository

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/basic_examples/profiler_example.py

Set the `num_workers` attribute to 8 (in my case ) in line [97](https://github.com/PyTorchLightning/pytorch-lightning/blob/81ac340248ef13d7d7cc93cb795ced589925bec4/pl_examples/basic_examples/profiler_example.py#L97) and [101](https://github.com/PyTorchLightning/pytorch-lightning/blob/81ac340248ef13d7d7cc93cb795ced589925bec4/pl_examples/basic_examples/profiler_example.py#L101)

```
torch.utils.data.DataLoader(trainset, batch_size=2, shuffle=True, num_workers=8)
and 
torch.utils.data.DataLoader(valset, batch_size=2, shuffle=True, num_workers=8)
```

### Expected behavior

In the profiler UI - the Number of workers is expected to show as 8 . Instead it is showing 2 (attached screenshot for reference).

### Environment

* CUDA:
	- GPU:
	- available:         False
	- version:           10.2
* Packages:
	- numpy:             1.19.2
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.0+cu102
	- pytorch-lightning: 1.4.0
	- tqdm:              4.50.2
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.8.2
	- version:           #146~16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 2021

**Comment by tchaton** [comment]
Hey @shrinath-suresh,

I am not sure how the profiler extracts this information 

From the trace, it seems the profiler is properly wrapping the DataLoader, but it doesn't seem to be able to extract it.

<img width="536" alt="Screenshot 2021-09-14 at 18 04 55" src="https://user-images.githubusercontent.com/12861981/133302175-ed022d37-5248-4a6d-b5e6-b67aa88ca35d.png">

**Comment by guotuofeng** [comment]
@shrinath-suresh , the num_workers in DataLoader means how many subprocess will be used to load the data. On the other hand, the workers in tb_plugin is means how many underlying chrome tracing files associated with current run "version_0". They are two different kinds of concepts. 

Maybe we can consider make the term more concise.

**Comment by tchaton** [comment]
Hey @guotuofeng, thanks for the answer.

I think there is no issue with the current value being presented within the Tensorboard Profiler Plugin then.

I would suggest `num_traces` instead of `num_workers` which is quite for PyTorch confusing.

Furthermore, actually gathering the number of subprocesses might be an interesting information for the users.

Closing this issue.
