### ISSUE TITLE
Inconsistency in MLFlowLogger.log_metrics within steps

### ISSUE THREAD

**Issue by mmazuecos** [PyTorchLightning/pytorch-lightning#9497]
## 🐛 Inconsistency in MLFlowLogger.log_metrics within steps

The [documentation](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.loggers.mlflow.html) for MLFlowLogger states that it has a method log_metrics which signature is as follows:

`log_metrics(metrics, step=None)`

where **metrics** (Dict[str, float]) – Dictionary with metric names as keys and measured quantities as values and 
**step** (Optional[int]) – Step number at which the metrics should be recorded.

When within a training/validation/test _step method of a LightningModule:
- Setting `self.logger.experiment.log_metrics({"train_loss": loss})` results in the fit method raising `AttributeError: 'MlflowClient' object has no attribute 'log_metrics'`
- Setting `self.logger.experiment.log_metric({"train_loss": loss})` results in the fit method raising `TypeError: log_metric() missing 2 required positional arguments: 'key' and 'value'`
- Setting `self.logger.experiment.log_metric("train_loss", loss)` results in the fit method raising `TypeError: log_metric() missing 1 required positional argument: 'value'`

Found the behavior from the last two options by luck because of a typo. The logger would expect `log_metric` despite the documentation saying the method is called `log_metrics`. Even if I use `log_metric` the method expects parameters other than the Dict[str, float] stated in the documentation.

### To Reproduce

This is the minimum code I found that reproduces the bug:

https://github.com/mmazuecos/pytorch_lightning_mlflow_bug/blob/main/pytorch_lightning_mlflow_bug.py

### Expected behavior

The code should work with the `log_metrics` signature from the documentation.

### Environment

* CUDA:
	- GPU:
	- available:         False
	- version:           None
* Packages:
	- numpy:             1.21.2
	- pyTorch_debug:     False
	- pyTorch_version:   1.7.1.post2
	- pytorch-lightning: 1.4.5
	- tqdm:              4.62.2
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.8.11
	- version:           #148-Ubuntu SMP Sat May 8 02:33:43 UTC 2021

**Comment by twsl** [comment]
`log_metrics` is part of the implementation of `LightningLoggerBase` yet using the experiment return the MlFlowClient which can be used to access methods specific to mlflow. So simply removing the experiment property from your calls should solve your problem.
