### ISSUE TITLE
PyTorch XLA 1.9 wheels is broken

### ISSUE THREAD

**Issue by kaushikb11** [PyTorchLightning/pytorch-lightning#9505]
## 🐛 Bug

PyTorch XLA 1.9 wheels seem to be broken. The XLA team is working on the fix. [Reference](https://github.com/pytorch/xla/issues/3123#issuecomment-918796921)

#### Temporary fix

To train on Lightning using TPUs, install the 1.8 wheels for now until the fix is merged.

```python
!pip install cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.8-cp37-cp37m-linux_x86_64.whl
```

**Comment by tchaton** [comment]
Hey @ kaushikb11,

noob question: Is this a Lightning bug ?

Best,
T.C

**Comment by kaushikb11** [comment]
Hey @tchaton, we are still debugging and trying out different versions. But it's highly likely there's an issue on the XLA's side as mentioned by Jack.

The reason I have created an issue here is to point the fix & the issue for the Lightning TPU users.

**Comment by JackCaoG** [comment]
1.9 wheel should be fixed now

**Comment by kaushikb11** [comment]
Thanks @JackCaoG! I will give it a try
