### ISSUE TITLE
Add `trainer.state.{fitting/validation/testing/predicting/tuning}`

### ISSUE THREAD

**Issue by rohitgr7** [PyTorchLightning/pytorch-lightning#9524]
## Proposed refactoring or deprecation

Right now to check the state of the Trainer instance we have to import `TrainerFn` everywhere and manually check for it. For eg.

```py
from somewhere.in.lightning import TrainerFn

if trainer.state.fn == TrainerFn.FITTING:
    pass
```

### Motivation

Looks a bit tedious and not user-friendly.

### Pitch

Add a property to be able to access them like:

```py
if trainer.state.fitting:
if trainer.state.validating:
if trainer.state.testing:
if trainer.state.predicting:
if trainer.state.tuning:
```

Also possibly a setter as well?

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by carmocca** [comment]
I am personally not a fan of the `trainer.{training,testing,validating,...}` getter/setters we already have, they were added mostly for compatibility.

So adding the same for the `trainer.state` just for the sake of less characters written doesn't seem worth it. It would create more confusion with the difference of `trainer.validating` and `trainer.state.validating`

**Comment by rohitgr7** [comment]
> I am personally not a fan of the trainer.{training,testing,validating,...} getter/setters we already have

I am a big fan haha... makes it easy to do TTA using this simple check.

>  It would create more confusion with the difference of trainer.validating and trainer.state.validating

yep, thought so too.

> just for the sake of less characters written doesn't seem worth it.

not just for the sake of fewer characters. My friend actually raised this issue. He was trying to find whether `.fit` is running or `.validate` is running in one of the validation hooks but couldn't find any property in Trainer instance to check for it unless he has to open the codebase and check for it.

**Comment by tchaton** [comment]
Personally, I think it would make code slightly cleaner, but not a strong opinion there.

**Comment by carmocca** [comment]
I think we could try and provide a better mechanism for the users to check these things, but it should be directly in the `trainer`, not under `trainer.state`.

And the main goal would be to remove the ambiguity.

Open to ideas
