### ISSUE TITLE
Error with metrics with `None` averaging

### ISSUE THREAD

**Issue by BardiaKh** [PyTorchLightning/pytorch-lightning#9528]
## 🐛 Bug

There is an issue when using torch metrics with an averaging method of None. It seems that when the trainer is checking if the metrics are ready, as they are tensors of multiple elements (one for each class) they cannot be interpreted as booleans, hence the process crashes. 

### To Reproduce

https://colab.research.google.com/drive/1Hil03eDMHynRDNa0dG9SAVuPqmc0w2vo?usp=sharing

### Expected behavior

Just continue to the second epoch.

### Environment

```
* CUDA:
	- GPU:
		- Tesla K80
	- available:         True
	- version:           10.2
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.0+cu102
	- pytorch-lightning: 1.4.6
	- tqdm:              4.62.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.11
	- version:           #1 SMP Sat Jun 5 09:50:34 PDT 2021
```

### Additional context

None.

**Comment by tchaton** [comment]
Hey @ BardiaKh,

Would you mind making your notebook public ?

Best,
T.C

**Comment by BardiaKh** [comment]
Sorry for the inconvenience. It should be ok now.

**Comment by carmocca** [comment]
@BardiaKh Thanks for reporting the error, i've opened a PR to fix it.

However, keep in mind that logging `torchmetrics.Metric`s whose `compute()` result is a multidimensional tensor is not supported with `self.log(logger=True)` as the logger requires that the resulting tensors have a single element.

So you'll get a different error later:

`pytorch_lightning.utilities.exceptions.MisconfigurationException: The metric `tensor([0.5000, 1.0000, 0.5000])` does not contain a single element, thus it cannot be converted to a scalar.`
