### ISSUE TITLE
Where to add LightningDataModule arguments?

### ISSUE THREAD

**Issue by aprbw** [PyTorchLightning/pytorch-lightning#9532]
Here is the docs in question https://pytorch-lightning.readthedocs.io/en/stable/common/hyperparameters.html#argparser-best-practices

```
It is best practice to layer your arguments in three sections.

1. Trainer args (gpus, num_nodes, etc…)

2. Model specific arguments (layer_dim, num_layers, learning_rate, etc…)

3. Program arguments (data_path, cluster_email, etc…)
```

Firstly, maybe reverse the order here, because the order in the code example is reversed:

```
# ----------------
# trainer_main.py
# ----------------
from argparse import ArgumentParser

parser = ArgumentParser()

# add PROGRAM level args
parser.add_argument("--conda_env", type=str, default="some_name")
parser.add_argument("--notification_email", type=str, default="will@email.com")

# add model specific args
parser = LitModel.add_model_specific_args(parser)

# add all the available trainer options to argparse
# ie: now --gpus --num_nodes ... --fast_dev_run all work in the cli
parser = Trainer.add_argparse_args(parser)

args = parser.parse_args()
```

Finally, where is the best place to add LightningDataModule arguments?

**Comment by tchaton** [comment]
Dear @aprbw,

I believe it depends of your model / data interaction. Which one decide how to configure the other.

Concerning the parser, all command line arguments get parsed at the same time, so the order won't have an impact.

Best,
T.C

**Comment by aprbw** [comment]
> Concerning the parser, all command line arguments get parsed at the same time, so the order won't have an impact.

Ah okay, that make sense. So the best practice is simply more for easy reading. Thanks!
