### ISSUE TITLE
How to implement pre-training?

### ISSUE THREAD

**Issue by chris-clem** [PyTorchLightning/pytorch-lightning#954]
#### What is your question?

What would be the best way to implement pre-training? With pre-training, I mean that I want to freeze some layers for a couple of epochs before training all of them. At the moment, I do it in two runs. In the first one, I freeze the layers, train the model, and save its weights. In the second one, I load these weights and train the model without freezing. Is it possible to do it in one run? If so, how?

**Comment by AljoSt** [comment]
You could freeze/unfreeze the layers in the `on_epoch_start`-hook (see [hooks](https://pytorch-lightning.readthedocs.io/en/latest/hooks.html)).

**Comment by Borda** [comment]
Thx @AljoSt! @chris-clem  if you need some more info, feel free to reopen... :robot:
