### ISSUE TITLE
GPU memory issue when resuming from a checkpoint (fault tolerant enabled only)

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#9541]
## 🐛 Bug

When resuming from a checkpoint created by fault-tolerant training, memory gets allocated on GPU 0 even though we specify to use GPU ids > 0. 

Reported by Gurvinder Singh on Slack.

### To Reproduce

(yet to confirm reproducible) 

```python

import os
import torch
from torch.utils.data import Dataset, DataLoader
from pytorch_lightning import LightningModule, Trainer
from pytorch_lightning.callbacks import ModelCheckpoint
from pytorch_lightning.plugins import DeepSpeedPlugin
from deepspeed.ops.adam import FusedAdam


class RandomDataset(Dataset):

    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):

    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return loss

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)
        return loss

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)
        return loss

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(320, 64), batch_size=2)
    test_data = DataLoader(RandomDataset(32, 64), batch_size=2)

    model = BoringModel()
    checkpoint_callback = ModelCheckpoint(
        dirpath='tests/',
        filename='{epoch:02d}',
    )
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        gpus=-1,
        limit_train_batches=1,
        limit_val_batches=1,
        num_sanity_val_steps=0,
        precision=16,
        accelerator='ddp',
        max_epochs=10,
        #max_epochs=100,
        plugins=[DeepSpeedPlugin(stage=2)],
        weights_summary=None,
        callbacks=[checkpoint_callback],
        #resume_from_checkpoint='tests/epoch=9.ckpt',
    )
    trainer.fit(model, train_dataloader=train_data, val_dataloaders=val_data)
    trainer.test(model, test_dataloaders=test_data)


if __name__ == '__main__':
    run()
```

From Gurvinder:

> I can confirm that this happen only when using fault tolerant training. you can easily reproduce this using our test script. create a normal checkpoint and then resume from it (just put sleep on training_step to be able to see the gpu memory usage, otherwise its too fast :stuck_out_tongue: ) then repeat the same process with fault tolerant enabled checkpoint. In FT, you will see extra memory being used on GPU0. you must run this test on server with GPU > 1. I just tested now with current master 637f59f1d2caaad57af3ddfa05b1089e6da6d3d0

### Expected behavior

memory allocation only on the GPU that we actually want to use for training.

### Environment

TBD

- PyTorch Lightning Version (e.g., 1.3.0):
- PyTorch Version (e.g., 1.8)
- Python version:
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

**Comment by awaelchli** [comment]
After closer investigation, it looks like this is specific to the usage of the deepspeed plugin here and a duplicate of the observations that #9521 made. The fault-tolerant settings here don't seem to matter and when switching to DDP I see no unusual memory allocations.

**Comment by SeanNaren** [comment]
Thanks! Should now be fixed on lightning master, and with the latest Deepspeed version (`pip install deepspeed -U`)
