### ISSUE TITLE
Trainer should invoke torch.use_deterministic_algorithms()

### ISSUE THREAD

**Issue by cowwoc** [PyTorchLightning/pytorch-lightning#9544]
When `Trainer(deterministic=True)` then the implementation should invoke `torch.use_deterministic_algorithms(True)` under the hood, otherwise there is a chance that the underlying code will be non-deteministic.

Source: https://pytorch.org/docs/stable/generated/torch.use_deterministic_algorithms.html

**Comment by ananthsub** [comment]
@cowwoc there is an open PR for this: https://github.com/PyTorchLightning/pytorch-lightning/pull/9121

The issue blocking that PR's merge is setting use_deterministic_algorithms can raise a runtime error, which is not backwards compatible behavior with the current setting
