### ISSUE TITLE
Improve the Rich Progress Bar

### ISSUE THREAD

**Issue by SeanNaren** [PyTorchLightning/pytorch-lightning#9547]
### Motivation

@kaushikb11 did a great job with introducing the Rich Progress Bar, however I think we're away from what's pleasing + interesting additions!

Regarding the colour choices, we should allow some form of modifications via config dict or the callback's `__init__`
 
At the very least, I say we go from this:
<img width="834" alt="Screenshot 2021-09-15 at 22 19 03" src="https://user-images.githubusercontent.com/6707363/133510972-55eb2b93-b8b4-42e1-8715-461b02803994.png">

to something more uniform like this:
<img width="698" alt="Screenshot 2021-09-15 at 22 16 43" src="https://user-images.githubusercontent.com/6707363/133510960-8267d5c5-afb3-4446-9aa8-872e2b27c65f.png">

In terms of additional benefits, I think we can explore how easy it would be to allow users to add their own rich components. For example, a `GPURichProgressBar` could add an element to log the GPU utilization into the progress bar.

**Comment by ananthsub** [comment]
> For example, a GPURichProgressBar could add an element to log the GPU utilization into the progress bar.

This could be a cool collaboration with https://github.com/PyTorchLightning/pytorch-lightning/issues/9032 - if the accelerator returns the device stats, the rich progress bar could visualize this w/o needing to configure a separate device stats monitor (unless users want to log these stats to some other destination too)

the progress bar being both a logger (logging + visualizing data) and a callback (updating state based on the loop) merits exploration as to whether there's some higher-level composition that should be offered here. this intersection seems to be heating up further with wandb and mlflow each becoming more featured in what were previously silo-ed interfaces.
