### ISSUE TITLE
Validation sanity check seems to cause issues with very deep spectral_norm nets

### ISSUE THREAD

**Issue by SCMusson** [PyTorchLightning/pytorch-lightning#9571]
## 🐛 Bug

I had a relatively complex GAN setup that was working fine. I attempted to use spectral norm changing every conv block from
`nn.Conv1d(in, out, 3, 1 1, bias=False)` 
to
`import torch.nn.utils.spectral_norm  as spectral_norm
spectral_norm(nn.Conv1d(in, out, 3, 1 1, bias=False))` 
This works outside of pytorch_lightning but when converted to pytorch_lightning code it would crash.
The crash was caused because the model was creating extremely large values that would eventually generate an inf in the loss function.  

I am not allowed to share my code but I will share a number of things that fixed the issue and my conclusions from them:

1. Without spectral norm everything worked fine. I therefore assume the issues is caused by or exacerbated by spectral_norm
2. With the alternative spectral_norm implementation (from torch.nn.utils.parametrizations import spectral_norm) I ran into a completely different set of errors and did not pursue this avenue any further: 
> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [1]] is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
3. Reducing the number of layers in the network fixed the issue (not a satisfactory fix though).
4. Doing a forward pass with the network (train mode) with a single example before calling trainer.fit(model, pldataloader) solved the issue.
5. setting num_sanity_val_steps=0 fixed the issue (not a satisfactory fix though as I would quite like a sanity check). 

The problem it seems then is the very first validation_step (sanity pass) generates extremely high values that crash the script before training can begin. After a single forward pass not in eval mode everything is fine and validation_step will never crash the script again. I don't know how these things are implemented under the hood so either this is a bug or perhaps the sanity check should include a single training_step or a single forward pass not in eval mode first to ensure spectral_norm is setup properly. Again I don't know how these things are implemented and am simply guessing at this stage. 

- PyTorch Lightning Version ( 1.4.5):
- PyTorch Version (1.9)
- Python version: (3.9.6)
- OS (e.g., Linux): Ubuntu 18 
- CUDA/cuDNN version: cudatoolkit 11.1.74
- GPU models and configuration: Quadro p620

**Comment by justusschock** [comment]
Hi @SCMusson ,

I am not sure how we can fix this. Because if we would replace all spectral norms with something else for sanity checking this wouldn't be a real check.

Re 1.) I think this should be raised to the pytorch people. Mind opening an issue there?
Re 2.) I can understand, seams unrelated to this exact issue.
Re 3.) Also totally understandable. Does not work in practice.
Re 4.) From looking at the implementation in PyTorch, I could not see a reason for that right away. Please also mention this as well in the issue @PyTorch.
Re 5.) I agree. Does that also work if you sanity check in your pure PyTorch implementation?

Best,
Justus
