### ISSUE TITLE
lr_find need unique temporary checkpoint filenames.

### ISSUE THREAD

**Issue by aprbw** [PyTorchLightning/pytorch-lightning#9574]
## 🚀 Feature

lr_find need unique temporary checkpoint filenames.

### Motivation

I'm running a number of experiment in parallel that are saving to the same folder. Thus, they have the same `trainer.default_root_dir`. However, since they all have the same directory and filename, they are overwriting each other.

### Pitch

lr_find temporary checkpoint should have unique filenames.

### Alternatives

This can be done by assigning a long random string.

### Additional context

My current solution is to assign a temporary unique `trainer.default_root_dir`. But the problem is that these folders are not deleted at the end.

**Comment by rohitgr7** [comment]
or we can check if it exists and add a version at the end like `existing_filename_{v1|v2|v3}`. WDYT?

**Comment by aprbw** [comment]
I think that's a great solution as well.

**Comment by rohitgr7** [comment]
> or we can check if it exists and add a version at the end like
 existing_filename_{v1|v2|v3}. WDYT?

I deleted this comment because in parallel environment there is a possibility of a conflict since all experiments will be independent of each other.

**Comment by aprbw** [comment]
Thank you!
