### ISSUE TITLE
Logging the current learning rate

### ISSUE THREAD

**Issue by sahnimanas** [PyTorchLightning/pytorch-lightning#960]
I'd like to write the current learning rate to a Logger. I imagine this would require a call to `scheduler.get_lr()` but I'm not sure how I can access the scheduler object and where to place the get_lr call
TIA!

**Comment by jeremyjordan** [comment]
You can access the scheduler object via the `lr_schedulers` attribute in the trainer. However, since we don't expose this as a property of the class there's a chance that relying on this attribute _could_ break in future releases. ([see code here](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/trainer.py#L986))

You can leverage a [model hook](https://pytorch-lightning.readthedocs.io/en/latest/hooks.html) to log the value.

```
class YourModel(pl.LightningModule):
    def __init__(self, hparams):
        ...
    def on_epoch_start(self):
        # log value here
```

**Comment by Borda** [comment]
Thx @jeremyjordan! @sahnimanas if you need some more info, feel free to reopen... :robot:

**Comment by XinDongol** [comment]
`lr_schedulers` is not accessible now. Is there any other solution?

**Comment by XinDongol** [comment]
@Borda

**Comment by jeremyjordan** [comment]
@XinDongol  there is now a callback for this :) 
https://pytorch-lightning.readthedocs.io/en/stable/callbacks.html#learning-rate-logger

**Comment by itay1itzhak** [comment]
> @XinDongol there is now a callback for this :)
> https://pytorch-lightning.readthedocs.io/en/stable/callbacks.html#learning-rate-logger

This link leads to a page tha doesn't exists. Importing LearningRateLogger as mentioned in https://pytorch-lightning.readthedocs.io/en/0.7.6/api/pytorch_lightning.callbacks.lr_logger.html leads to an error:

ImportError: cannot import name 'LearningRateLogger' from 'pytorch_lightning.callbacks'

**Comment by Sav-eng** [comment]
> It is now lr_monitor and can be found here: https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.callbacks.lr_monitor.html?highlight=lr_monitor

This page does not exist anymore. Could you provide another solution of how to log the current learning rate?

**Comment by timothygebhard** [comment]
@Sav-eng Here's a link to the latest "stable" version of the docs which should still work: https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.callbacks.lr_monitor.html#learning-rate-monitor

**Comment by dpaleka** [comment]
None of the links above work. @timothygebhard if you don't mind, how did you find the last link back when it worked?

**Comment by timothygebhard** [comment]
@dpaleka I just updated the link 🙂

**Comment by alvitawa** [comment]
Is there a way to get the learning rate directly? I already use the callback for logging it but I need i need the actual value for my model.

**Comment by timothygebhard** [comment]
@alvitawa This may not be the best or most elegant solution, but inside your `model` (which inherits from `pl.LightningModule` and which is what you pass to your `Trainer` instance), you can do something like this:

```python
lightning_optimizer = self.optimizers()  # self = your model
    for param_group in lightning_optimizer.optimizer.param_groups:
        print(param_group['lr'])
```

This assumes that you only have a single optimizer; in principle, `self.optimizers()` can also return a list. Note also that this only works once the model is connected to a Trainer (e.g., you might not be able to call it already inside your model's constructor).

Outside your `model`, you can do something like this:
```python
optimizers = trainer.optimizers
    for optimizer in optimizers:
        for param_group in optimizer.param_groups:
            print(param_group['lr'])
```
But again, this only works once the model and the Trainer have been connected — if you run this before calling `.fit()`, the list of optimizers is just going to be empty. Hope this helps!

**Comment by ManosMpampis** [comment]
If someone see what the lr_monitor.py in the LearningRateMonitor claabacks does, it can be seen that to extract the lr it goes: trainer.lr_scheduler_configs.scheduler.optimizer.param_groups[0]["lr"] so I think this is the best way to see the current lr and the only way to see it after initializing mid point into a training.

**Comment by gravitychen** [comment]
simply print it

print('>>> self.trainer.lr_schedulers[0]["scheduler"].get_lr()[0]  ',self.trainer.lr_schedulers[0]["scheduler"].get_lr()[0])
or
print('>>> self.trainer.lr_schedulers[0]["scheduler"].get_last_lr()[0]  ',self.trainer.lr_schedulers[0]["scheduler"].get_last_lr()[0])

depending on your type of scheduler
