### ISSUE TITLE
Use `MlflowAutologgingQueueingClient` within the Lightning `MLFlowLogger` 

### ISSUE THREAD

**Issue by dannyfriar** [PyTorchLightning/pytorch-lightning#9607]
## Proposed refactoring and motivation

[MLflow PyTorch autolog](https://github.com/mlflow/mlflow/blob/master/mlflow/pytorch/_pytorch_autolog.py) uses MLflow's `MlflowAutologgingQueueingClient`  which enables the features described [here ](https://github.com/mlflow/mlflow/blob/94891da1c272038ac506f5d091c8c6b19e009b2d/mlflow/utils/autologging_utils/client.py#L2) , as well as `ExceptionSafeAbstractClass`, which catches errors logging to MLflow.

Suggest using these within [MLFlowLogger](https://pytorch-lightning.readthedocs.io/en/latest/_modules/pytorch_lightning/loggers/mlflow.html#MLFlowLogger). Currently a failed `log_metric` call can kill the training run but this would instead raise a warning for the user.

**Comment by tchaton** [comment]
Dear @dannyfriar,

Thanks for opening this issue. We are trying to get the MLFlow Team to make sure the logger is up-to-date.

Best,
T.C

**Comment by dannyfriar** [comment]
Thanks @tchaton I'll subscribe to that issue
