### ISSUE TITLE
Example of gradient accumulation documentation is not correct

### ISSUE THREAD

**Issue by Colanim** [PyTorchLightning/pytorch-lightning#961]
## 📚 Documentation

Example of [gradient accumulation documentation](https://pytorch-lightning.readthedocs.io/en/latest/pytorch_lightning.callbacks.gradient_accumulation_scheduler.html) is not correct :

```python
from pytorch_lightning import Trainer
from pytorch_lightning.callbacks import GradientAccumulationScheduler

# at epoch 5 start accumulating every 2 batches
accumulator = GradientAccumulationScheduler(scheduling: {5: 2})
Trainer(accumulate_grad_batches=accumulator)
```

If running the code like this, I receive following error :

> TypeError: Gradient accumulation supports only int and dict types

---

After reading the source code :

https://github.com/PyTorchLightning/pytorch-lightning/blob/d856989120b078581f3f694fd7a1c036703f67a9/pytorch_lightning/trainer/training_tricks.py#L32-L41

It seems the option `accumulate_grad_batches` can be only `int` or `dict`.

**Comment by ethanwharris** [comment]
Thanks for the issue!

Can you confirm if this is true on master? (by installing from github - https://github.com/PyTorchLightning/pytorch-lightning#bleeding-edge)

That was a recent addition so won't be on pip yet

**Comment by Colanim** [comment]
Ha, you're right, on Master the documentation is updated. My bad
