### ISSUE TITLE
Sampler is being replaced even with trainer.replace_sampler_ddp=False

### ISSUE THREAD

**Issue by MaximumEntropy** [PyTorchLightning/pytorch-lightning#9655]
## 🐛 Bug

In the following line:

https://github.com/PyTorchLightning/pytorch-lightning/blob/4bebf82f271fb577ed41831403551f0bff97651b/pytorch_lightning/trainer/data_loading.py#L152

PTL tries to replace the sampler object even if `trainer.replace_sampler_ddp` is `False`:

https://github.com/PyTorchLightning/pytorch-lightning/blob/4bebf82f271fb577ed41831403551f0bff97651b/pytorch_lightning/trainer/data_loading.py#L135

### To Reproduce

Should be easy to reproduce with any custom Sampler class that has different init args from the PyTorch default.

### Expected behavior

Function in line 152 should not be called and moved just below 147. This is how it was in version v1.4.8:

https://github.com/PyTorchLightning/pytorch-lightning/blob/1.4.8/pytorch_lightning/trainer/data_loading.py#L143

### Environment

- PyTorch Lightning Version (main):
- PyTorch Version (e.g., 1.10)
- Python version: 3.8.10
- OS (e.g., Linux): Linux
- CUDA/cuDNN version: N/A
- GPU models and configuration: N/A
- How you installed PyTorch (`conda`, `pip`, source): source
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

**Comment by tchaton** [comment]
Hey @MaximumEntropy,

I have checked and it seems to be working as expected. However, the code is definitely mis-leading as replace_sampler would be called but it won't actually happen. This definitely need a refactor :) 

Here is the test used to make sure it works fine.

```py
@mock.patch.dict(os.environ, {"CUDA_VISIBLE_DEVICES": "0,1", "PL_TRAINER_GPUS": "2"})
@mock.patch("torch.cuda.device_count", return_value=2)
@mock.patch("torch.cuda.is_available", return_value=True)
@pytest.mark.parametrize("replace_sampler_ddp", [False, True])
def test_combined_data_loader_validation_test(cuda_available_mock, device_count_mock, replace_sampler_ddp, tmpdir):
    """This test makes sure distributed sampler has been properly injected in dataloaders when using
    CombinedLoader."""

    class CustomDataset(Dataset):
        def __init__(self, data):
            self.data = data

        def __len__(self):
            return len(self.data)

        def __getitem__(self, index):
            return self.data[index]

    class CustomSampler(RandomSampler):

        def __init__(self, data_source, name) -> None:
            super().__init__(data_source)
            self.name = name

    dataset = CustomDataset(range(10))
    dataloader = CombinedLoader(
        {
            "a": DataLoader(CustomDataset(range(10))),
            "a": DataLoader(dataset, sampler=CustomSampler(dataset, "custom_sampler")),
            "b": {"c": DataLoader(CustomDataset(range(10))), "d": DataLoader(CustomDataset(range(10)))},
            "e": [DataLoader(CustomDataset(range(10))), DataLoader(CustomDataset(range(10)))],
        }
    )

    trainer = Trainer(replace_sampler_ddp=replace_sampler_ddp, accelerator="ddp", gpus=2)
    dataloader = trainer.auto_add_sampler(dataloader, shuffle=True)
    _count = 0

    def _assert_distributed_sampler(v):
        nonlocal _count
        _count += 1
        if replace_sampler_ddp:
            assert isinstance(v, DistributedSampler)
        else:
            assert isinstance(v, (SequentialSampler, CustomSampler))

    apply_to_collection(dataloader.sampler, Sampler, _assert_distributed_sampler)
    assert _count == 5
```

**Comment by MaximumEntropy** [comment]
Hey! We had code in NeMo in 1.4.x that was working fine and we wanted to move to 1.5 for bfloat support. In the process, this was one of the places where our code broke. Following that line from https://github.com/PyTorchLightning/pytorch-lightning/blob/4bebf82f271fb577ed41831403551f0bff97651b/pytorch_lightning/trainer/data_loading.py#L152, the code eventually gets to this bit https://github.com/PyTorchLightning/pytorch-lightning/blob/4bebf82f271fb577ed41831403551f0bff97651b/pytorch_lightning/trainer/data_loading.py#L164 where it tries to instantiate a new sampler object with constructor args that are different from our sampler class.

**Comment by MaximumEntropy** [comment]
Unfortunately, its going to be hard for me to come up with a minimal working example to reproduce this, but if I move this line https://github.com/PyTorchLightning/pytorch-lightning/blob/4bebf82f271fb577ed41831403551f0bff97651b/pytorch_lightning/trainer/data_loading.py#L152 inside the above if condition block to do so only when replace_ddp_sampler=True, everything works fine.
