### ISSUE TITLE
Remove `InternalDebugger`

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#9661]
## Proposed refactoring or deprecation

See title

### Motivation

The `InternalDebugger` is legacy and lets us to write bad code. The code should be structured in a way that enables testing.

### Pitch

- [x] #9188 
- [x] #9326 
- [x] #9327 
- [x] #9653
- [x] #9654 
- [x] #9675
- [x] #9680

### Additional context

Discussed in https://github.com/PyTorchLightning/pytorch-lightning/issues/8895

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by awaelchli** [comment]
Thanks @carmocca 
I have a branch where I started the dataloader removal a while ago. 
Have you already started? This one is going to be a bit of effort.

**Comment by carmocca** [comment]
No, I haven't. Up for grabs.
