### ISSUE TITLE
Add a "Unit Testing" guide to the Common Use Cases

### ISSUE THREAD

**Issue by alanhdu** [PyTorchLightning/pytorch-lightning#9674]
## 🚀 Feature

It would be great if we could create a set of tools + documentation for unit-testing a LightningModule. Unit-testing is something that a lot of researchers don't really do, and so if we can make this easy for folks I think that'd be a big win for the community.

One example of how this is currently difficult -- I'd like to be able to do is to unit-test `LightningModule.training_step` with something like:

```python
loss = module.training_step(...)
assert loss_is_correct(...)
assert right_things_were_logged(...)
```

but right now it's unclear how to do this -- it's not clear how to implement `right_things_were_logged` without having to mock a bunch of Lightning internals that I'm not comfortable with, and even naively calling `module.training_step(...)` can fail because of https://github.com/PyTorchLightning/pytorch-lightning/issues/8509#issuecomment-926209172.

I assume this is already possible somehow in Lightning (since Lightning itself looks like it's extensively unit-tested), but I think having a dedicated user guide would be suer helpful.

**Comment by carmocca** [comment]
Regarding the "right_things_were_logged", I recommend you don't try to test the `self.log` implementation (that's on us!) and instead test the inputs given. An example:

```python
from unittest import mock

import torch

from pytorch_lightning import LightningModule


class MyModel(LightningModule):
    def training_step(self, batch, batch_idx):
        loss = sum(batch)
        self.log("loss", loss)
        return loss


model = MyModel()
x = torch.tensor([1,2,3])

with mock.patch.object(model, "log") as log_mock:
    loss = model.training_step(x, 0)

assert loss == 6
log_mock.assert_called_once_with("loss", 6)
```

**Comment by tchaton** [comment]
Dear @alanhdu,

Would you be willing to make a PR with those additions ?

Best,
T.C

**Comment by alanhdu** [comment]
@tchaton 

I'm not sure I'm qualified! I don't know too much about the Lightning's design and what the appropriate ways to unit-test the different hooks are.

@carmocca 
> Regarding the "right_things_were_logged", I recommend you don't try to test the self.log implementation (that's on us!) and instead test the inputs given. An example:

Yeah, this makes a lot of sense to me, and for `log` I agree that a simple mock patch should work well.
