### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: '/home/pc/SR/dC/1-Data_Preparation'

### ISSUE THREAD

**Issue by pratikchhapolika** [PyTorchLightning/pytorch-lightning#9697]
I am using **Jupyter Lab Server**. It has pre-installed tf2.3_py3.6 kernel installed in it. It has 2 GPUS in it.

PyTorch Lightning Version (e.g., 1.3.0): '1.4.6'
PyTorch Version (e.g., 1.8): '1.6.0+cu101'
Python version: 3.6
OS (e.g., Linux): system='Linux'
CUDA/cuDNN version: 11.2
GPU models and configuration: Mentioned below
How you installed PyTorch (conda, pip, source): pip

NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:62:00.0 Off |                    0 |
| N/A   36C    P0    57W / 300W |   2842MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:89:00.0 Off |                    0 |
| N/A   32C    P0    43W / 300W |      3MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                              
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

I have trained a model, and saved the best model.

```
class SRTagger(pl.LightningModule):

  def __init__(self, n_classes: int, n_training_steps=None, n_warmup_steps=None):
    super().__init__()
    self.bert = BertModel.from_pretrained(BERT_MODEL_NAME, return_dict=True)
    self.classifier = nn.Linear(self.bert.config.hidden_size, n_classes)
    self.n_training_steps = n_training_steps
    self.n_warmup_steps = n_warmup_steps
    self.criterion = nn.BCELoss()

  def forward(self, input_ids, attention_mask, labels=None):
    output = self.bert(input_ids, attention_mask=attention_mask)
    output = self.classifier(output.pooler_output)
    output = torch.sigmoid(output)    
    loss = 0
    if labels is not None:
        loss = self.criterion(output, labels)
    return loss, output

  def training_step(self, batch, batch_idx):
    input_ids = batch["input_ids"]
    attention_mask = batch["attention_mask"]
    labels = batch["labels"]
    loss, outputs = self(input_ids, attention_mask, labels)
    self.log("train_loss", loss, prog_bar=True, logger=True)
    return {"loss": loss, "predictions": outputs, "labels": labels}

  def validation_step(self, batch, batch_idx):
    input_ids = batch["input_ids"]
    attention_mask = batch["attention_mask"]
    labels = batch["labels"]
    loss, outputs = self(input_ids, attention_mask, labels)
    self.log("val_loss", loss, prog_bar=True, logger=True)
    return loss

  def test_step(self, batch, batch_idx):
    input_ids = batch["input_ids"]
    attention_mask = batch["attention_mask"]
    labels = batch["labels"]
    loss, outputs = self(input_ids, attention_mask, labels)
    self.log("test_loss", loss, prog_bar=True, logger=True)
    return loss

  def training_epoch_end(self, outputs):
    
    labels = []
    predictions = []
    for output in outputs:
      for out_labels in output["labels"].detach().cpu():
        labels.append(out_labels)
      for out_predictions in output["predictions"].detach().cpu():
        predictions.append(out_predictions)

    labels = torch.stack(labels).int()
    predictions = torch.stack(predictions)

    for i, name in enumerate(LABEL_COLUMNS):
      class_roc_auc = auroc(predictions[:, i], labels[:, i])
      self.logger.experiment.add_scalar(f"{name}_roc_auc/Train", class_roc_auc, self.current_epoch)


  def configure_optimizers(self):

    optimizer = optim.RAdam(self.parameters(), lr=2e-5)

    scheduler = get_linear_schedule_with_warmup(
      optimizer,
      num_warmup_steps=self.n_warmup_steps,
      num_training_steps=self.n_training_steps
    )

    return dict(
      optimizer=optimizer,
      lr_scheduler=dict(
        scheduler=scheduler,
        interval='step'
      )
    )

```
**After training, I want to load my best model without training it again**

```
checkpoint_callback = ModelCheckpoint(
  dirpath="checkpoints",
  filename="best-checkpoint",
  save_top_k=1,
  verbose=True,
  monitor="val_loss",
  mode="min"
)

logger = TensorBoardLogger("lightning_logs", name="SReply")

# And early stopping triggers when the loss hasn't improved for the last 
# 2 epochs (you might want to remove/reconsider this when training on real-world projects):


early_stopping_callback = EarlyStopping(monitor='val_loss', patience=2)
# We can start the training process:
# checkpoint_callback supports only a bool value. If set to True, it will create a model checkpoint
# instance internally, but if you want to assign your own custom instance then pass it within callbacks:

trainer = pl.Trainer(
  logger=logger,
  callbacks=[early_stopping_callback,checkpoint_callback],
  max_epochs=N_EPOCHS,
  gpus=1,
  progress_bar_refresh_rate=50,
  amp_level='O3'
  )

trained_model = SRTagger.load_from_checkpoint(trainer.checkpoint_callback.best_model_path,n_classes=len(LABEL_COLUMNS))
trained_model.eval()
trained_model.freeze()
```

**Error**

```
---------------------------------------------------------------------------
IsADirectoryError                         Traceback (most recent call last)
/usr/local/bin/kernel-launchers/python/scripts/launch_ipykernel.py in <module>
----> 1 trained_model = SRTagger.load_from_checkpoint(trainer.checkpoint_callback.best_model_path,n_classes=len(LABEL_COLUMNS))
      2 trained_model.eval()
      3 trained_model.freeze()

~/.local/lib/python3.6/site-packages/pytorch_lightning/core/saving.py in load_from_checkpoint(cls, checkpoint_path, map_location, hparams_file, strict, **kwargs)
    129             checkpoint = pl_load(checkpoint_path, map_location=map_location)
    130         else:
--> 131             checkpoint = pl_load(checkpoint_path, map_location=lambda storage, loc: storage)
    132 
    133         if hparams_file is not None:

~/.local/lib/python3.6/site-packages/pytorch_lightning/utilities/cloud_io.py in load(path_or_url, map_location)
     30         return torch.hub.load_state_dict_from_url(str(path_or_url), map_location=map_location)
     31     fs = get_filesystem(path_or_url)
---> 32     with fs.open(path_or_url, "rb") as f:
     33         return torch.load(f, map_location=map_location)
     34 

~/.local/lib/python3.6/site-packages/fsspec/spec.py in open(self, path, mode, block_size, cache_options, **kwargs)
    980                 autocommit=ac,
    981                 cache_options=cache_options,
--> 982                 **kwargs,
    983             )
    984             if not ac and "r" not in mode:

~/.local/lib/python3.6/site-packages/fsspec/implementations/local.py in _open(self, path, mode, block_size, **kwargs)
    143         if self.auto_mkdir and "w" in mode:
    144             self.makedirs(self._parent(path), exist_ok=True)
--> 145         return LocalFileOpener(path, mode, fs=self, **kwargs)
    146 
    147     def touch(self, path, **kwargs):

~/.local/lib/python3.6/site-packages/fsspec/implementations/local.py in __init__(self, path, mode, autocommit, fs, compression, **kwargs)
    234         self.compression = get_compression(path, compression)
    235         self.blocksize = io.DEFAULT_BUFFER_SIZE
--> 236         self._open()
    237 
    238     def _open(self):

~/.local/lib/python3.6/site-packages/fsspec/implementations/local.py in _open(self)
    239         if self.f is None or self.f.closed:
    240             if self.autocommit or "w" not in self.mode:
--> 241                 self.f = open(self.path, mode=self.mode)
    242                 if self.compression:
    243                     compress = compr[self.compression]

IsADirectoryError: [Errno 21] Is a directory: '/home/pc/SR/dC/1-Data_Preparation'
```

**This error. comes when I try to load my model second time after closing and reopening the jupyter notebook. I run the code except training it.**

**Comment by ananthsub** [comment]
> This error. comes when I try to load my model second time after closing and reopening the jupyter notebook. I run the code except training it.

Did you confirm that the directory `'/home/pc/SR/dC/1-Data_Preparation'` exists?

**Comment by pratikchhapolika** [comment]
> > This error. comes when I try to load my model second time after closing and reopening the jupyter notebook. I run the code except training it.
> 
> Did you confirm that the directory `'/home/pc/SR/dC/1-Data_Preparation'` exists?

Yes I am inside this directory : `'/home/pc/SR/dC/1-Data_Preparation'` and when I do"

`!ls '/home/pc/SR/dC/1-Data_Preparation/checkpoints`

I get :  **best-checkpoint.ckpt**

**Comment by pratikchhapolika** [comment]
@ananthsub any update on this?

**Comment by rohitgr7** [comment]
```py
trainer = pl.Trainer(
  logger=logger,
  callbacks=[early_stopping_callback,checkpoint_callback],
  max_epochs=N_EPOCHS,
  gpus=1,
  progress_bar_refresh_rate=50,
  amp_level='O3'
  )

trained_model = SRTagger.load_from_checkpoint(trainer.checkpoint_callback.best_model_path,n_classes=len(LABEL_COLUMNS))
trained_model.eval()
```
you have created a new trainer instance and using a new checkpoint instance.. so `best_model_path` doesn't exist at this point.

**Comment by pratikchhapolika** [comment]
> ```python
> trainer = pl.Trainer(
>   logger=logger,
>   callbacks=[early_stopping_callback,checkpoint_callback],
>   max_epochs=N_EPOCHS,
>   gpus=1,
>   progress_bar_refresh_rate=50,
>   amp_level='O3'
>   )
> 
> trained_model = SRTagger.load_from_checkpoint(trainer.checkpoint_callback.best_model_path,n_classes=len(LABEL_COLUMNS))
> trained_model.eval()
> ```
> 
> you have created a new trainer instance and using a new checkpoint instance.. so `best_model_path` doesn't exist at this point.

So what solution do you suggest?

**Comment by rohitgr7** [comment]
you can just pass the path of the best checkpoint as a string or maybe extract it from one of your saved checkpoints to reload it correctly.

**Comment by pratikchhapolika** [comment]
> you can just pass the path of the best checkpoint as a string or maybe extract it from one of your saved checkpoints to reload it correctly.

SRTagger.load_from_checkpoint("path",n_classes=len(LABEL_COLUMNS))
trained_model.eval()

Closing it.
