### ISSUE TITLE
`.save_hyperparameters()` from a parent model doesn't save arguments of the child model

### ISSUE THREAD

**Issue by eladsegal** [PyTorchLightning/pytorch-lightning#9701]
## 🐛 Bug
Calling `.save_hyperparameters()` from a parent model doesn't save arguments of the child model.

### To Reproduce
This is a very simple example that has two models, each inherits from a parent.
In the first one, the parent calls `.save_hyperparameters()` and in the second one the child does.
You can see that difference in `.hparams` in each of the models.
https://colab.research.google.com/drive/1J4Z8AFanZUIPMffj0ZO0yiKtlDto1OQw?usp=sharing

### Expected behavior
It shouldn't matter where `.save_hyperparameters()` is called in the inheritance chain, all the parameters passed to the instantiated model should be saved in `.hparams`.
I believe the solution is already given with [collect_init_args](https://github.com/PyTorchLightning/pytorch-lightning/blob/a3def9d228b4c849e8a6222cffd22e547a17df64/pytorch_lightning/utilities/parsing.py#L157):
```
        init_args = {}
        for local_args in collect_init_args(frame, []):
            init_args.update(local_args)
```
instead of 
https://github.com/PyTorchLightning/pytorch-lightning/blob/a3def9d228b4c849e8a6222cffd22e547a17df64/pytorch_lightning/utilities/parsing.py#L220

It worked for me, so let me know if you'd like me to submit a pull request.

**Comment by awaelchli** [comment]
Hi @eladsegal 
Apologies for the late response. Thanks for sending the PR and the test.
Note, calling `save_hyperparameters()` in a super class constructor is suboptimal. If the signature of the subclass and the super class differ, then the union of these set s of arguments will be collected. Instantiating an object either from the super class or from the subclass will be problematic (this limitation, afaik, applies regardless of your fix).  
So I recommend calling `save_hyperparameters()` only in the most specific subclass.

**Comment by eladsegal** [comment]
Thanks @awaelchli, I understand and agree. 
My use case is pretty standard where I only pass `**kwargs` to the parent class's `__init__`, so it should be safe.
