### ISSUE TITLE
Introduce a mechanism to allow for production environment specific default plugins

### ISSUE THREAD

**Issue by yifuwang** [PyTorchLightning/pytorch-lightning#9741]
### Motivation

Large organizations typically have a set of plugins that everyone uses. For example, custom Checkpoint/TensorBoardLogger plugin that's tightly integrated with the organization's infra, or observability plugins to facilitate the monitoring of Lightning's usage within the organization. The instantiation of these plugins are essentially boilerplate copied from one project to another.

The plugin mechanism provided by Lighting allowed us to elegantly organize these components. However, it'd be great if there's a mechanism that allows for production environment specific default plugins, such that users within the organization can also enjoy Lightining's "no boilerplate" philosophy.

### Pitch
Allow for registering a callbacks factory (see example below) through `dist-info`. The the callback instances created by the factory will be added to `pl.Trainer` transparently.
```
def default_callbacks_factory() -> List[Callback]:
    pass
```
For power users who need to customize the settings of the default callbacks, they can explicitly configure an instance and pass it to `pl.Trainer`, which will replace the instance of the same type create by the factory.

### Alternatives

A wrapper class around `pl.Trainer` or a subclass of `pl.Trainer` that instantiates these plugin by default. Obviously, these are not ideal because it deviates from the pure Lightning experience.

### Additional context

The mechanism also facilliates https://github.com/PyTorchLightning/pytorch-lightning/issues/8895

Some more reading:
- https://stackoverflow.com/a/9615473
- https://amir.rachum.com/blog/2017/07/28/python-entry-points/

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

cc @borda

**Comment by tchaton** [comment]
Dear @yifuwang,

I believe the LightningCLI could actually helped there as we recently introduced registries.

Best,
T.C

**Comment by yifuwang** [comment]
Hi @tchaton, we use a set of heavily customized solutions for scheduling, peer discovery and process hierarchy management so LightningCLI is not an option for us. Though I wonder if the registry itself can be reused for this purpose. Can you share a pointer?

**Comment by kaushikb11** [comment]
@yifuwang You could check out the [Plugins registry](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/plugins/plugins_registry.py) as well.

**Comment by RuRo** [comment]
I still think, that this proposal is at least worth discussing. IMO, pytorch-lightning currently lacks idiomatic ways to change the "default" Trainer configuration. So I am bumping this.

**Comment by tchaton** [comment]
Hey @yifuwang @ananthsub,

Any updates on this ?

**Comment by RuRo** [comment]
bump

**Comment by daniellepintz** [comment]
FYI @akashkw is planning to work on this!
