### ISSUE TITLE
How to show more log infos during training instead of using tqdm to show only once?

### ISSUE THREAD

**Issue by marsggbo** [PyTorchLightning/pytorch-lightning#975]
### Motivation

Sometimes we want to check whether our model can converge. The most intuitive is to print the training information at regular intervals. However, tqdm only shows once, from which we cannot clearly see the trend of convergence.

### Alternatives

In this context, I wonder is it possible to use the normal method (e.g. simply print or logging) to log the training and validation information? Or does tqdm support print the information on both screen and file?

**Comment by williamFalcon** [comment]
you can always call print whenever you want. but ideally we look at tensorboard or another logger to check for convergence. 

but you’re free to do print(loss) in your code haha

**Comment by marsggbo** [comment]
I got it. I can first set `show_progress_bar=False`, then print the info in `training_step`, but I wonder how can I print the average value of accuracy and loss?

**Comment by djbyrne** [comment]
Is there anyway to use something like logging.info() instead of print?

**Comment by williamFalcon** [comment]
you can use self.print() inside the lightningModule
