### ISSUE TITLE
SWA callback takes more memory at the last epoch -> crashing

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#9752]
## 🐛 Bug

 found quite annoying that the SWA at the last epoch needs more memory, which results in crashing all training at the very end... :confused:

### To Reproduce

https://www.kaggle.com/jirkaborovec/brain-tumor-classif-lightning-efficientnet3d/edit/run/73264784

### Expected behaviour

thinking about lowering batch size for the last epoch within the callback... other thoughts?

### additional context

#9480 and #9441

**Comment by carmocca** [comment]
Closing in favor of #9441. We need to explore what is really causing the increase.
