### ISSUE TITLE
Support storing hparams as a dict

### ISSUE THREAD

**Issue by neggert** [PyTorchLightning/pytorch-lightning#977]
## 🚀 Feature
Right now, we assume `model.hparams` is an `argparse.Namespace`. We've had a number of requests to support `hparams` as a simple `dict`. Let's do it.

**Comment by festeh** [comment]
It would also be great to support nested dictionaries. Especially for [hydra](https://github.com/facebookresearch/hydra) users, because this library favors modular configs.

**Comment by awaelchli** [comment]
#943 Started also here with suggestion, but not sure what is the right way to do it.

**Comment by tstumm** [comment]
What about having a `set_hparams(hparams: Union[Dict, argparse.Namespace])` function in `LightningModule` (or having it as an mandatory argument to the constructor), s.t. the user only needs to call either the function in the modules constructor OR calling it implicitly using a `super.__init__(hparams` call. It could handle arbitrary conversion logic, such that the internally used `hparams` object can be used the same way everywhere.

**Comment by awaelchli** [comment]
The set_hparams approach is not going to work because often we want to prepare some stuff in the constructor where we need the hparams. 

I like your idea of the mandatory hparams argument to the constructor. If the superclass takes care of storing the hparams, it even gives the user more flexibility, for example he/she can rename it to self.args or something. It would also simplify the logic in the load method (e.g. LightningModule.load_from_checkpoint).

**Comment by awaelchli** [comment]
There is still the question of how we support multiple types of hparam objects and instantiate the user's LightningModule in the load_from_checkpoint method.

**Comment by festeh** [comment]
On the other hand, adding a mandatory argument will break a lot of existing code. What if instead use a
private method `_set_hparams(self)` which is called after constructor has finished and looks for `self.hparams`? Yes, user will not able to change the `hparams` name to something else, but I consider it normal.

**Comment by tstumm** [comment]
@awaelchli You can just type-check them and then convert it to some common type, e.g., a dict.
Or we just constraint the type of hparams to dict and expect that every user handles conversion on their own.
@festeh That would bring in a lot of additional complexity, as one then needs to either 1) manually call that method (so you need to change your code anyway) or 2) the method is called by some instrinsic step in the Pytorch-Lightning training/loading procedure. Breaking backwards compatibility is not necessarily a bad thing.

**Comment by festeh** [comment]
@tstumm  I meant the second option, this method may be called after the model is passed to `Trainer` . Then it can perform the steps suggested by you (type-checking and converting), like this
```
def _set_hparams(self):
    hparams = getattr(self, "hparams", None)
    if hparams is not None:
        if isinstance(hparams, dict):
            ...
        elif isinstance(hparams, Namespace):
            ...
```
I should say we need a really good reason to introduce a change that will break a lot of code.

**Comment by Borda** [comment]
hmmm, so what about having `hparams` as property which will be `Namespace` and setter `set_hparams` which will accept both `Namespace` and `dict` and store it in `_hparams` in the original form...

**Comment by awaelchli** [comment]
What if the hparams changes after setter is called? It is mutable, the user can change the values anytime. It should probably only be converted when checkpoint is saved. 
And when restoring, we basically can't restore the users original type... basically we don't know what to pass in to constructor. that's the big problem I see.

**Comment by awaelchli** [comment]
actually, in the PR #1029 of @Borda  the conversion is done in the property, not the setter. This could work. I think it's a good idea.
