### ISSUE TITLE
Multi GPU training docs should show batch-size behaviour

### ISSUE THREAD

**Issue by tmachnitzki** [PyTorchLightning/pytorch-lightning#9784]
I am fairly new to multi-GPU training, and it took me quite a while to understand that when using DDP the effective batch size scales with `num_gpus * batch_size`.
In fact, I thought that the batch-size that I provide to the lightning data module would be divided by the number of GPUs so that I often ran into memory errors.

Maybe this could be more clarified in the docs. https://pytorch-lightning.readthedocs.io/en/stable/advanced/multi_gpu.html

**Comment by rohitgr7** [comment]
it's mentioned here: https://pytorch-lightning.readthedocs.io/en/stable/advanced/multi_gpu.html#batch-size

**Comment by tmachnitzki** [comment]
I did see that, but since I don't know what horovod is, I did not know if the same thing applies to DDP only.

**Comment by rohitgr7** [comment]
both are different actually. `accelerator="ddp|horovod"` there actually means either `ddp` training or `horovod` training.

**Comment by tmachnitzki** [comment]
Thanks a lot for clarifying that. I still think this could be made a bit easier to understand in the docs.

**Comment by rohitgr7** [comment]
yeah sure!! do send a PR to update those if it's confusing :)
