### ISSUE TITLE
`on_train_batch_*` doesn't need `dataloader_idx`

### ISSUE THREAD

**Issue by rohitgr7** [PyTorchLightning/pytorch-lightning#9787]
## Proposed refactoring or deprecation

https://github.com/PyTorchLightning/pytorch-lightning/blob/9d982080df5dbc347249eeeae3311b18b397ac54/pytorch_lightning/loops/batch/training_batch_loop.py#L79
https://github.com/PyTorchLightning/pytorch-lightning/blob/9d982080df5dbc347249eeeae3311b18b397ac54/pytorch_lightning/loops/epoch/training_epoch_loop.py#L163
right now these 2 hooks get 0 as the value for `dataloader_idx`. In case of train_dataloaders we use some sort of `CombinedDataloader` so this argument seems redundant.

### Motivation

Are there any plans that this will be dynamic sometime in future or should we deprecate this argument and remove it? `training_step` doesn't have any such argument as well.

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by awaelchli** [comment]
Yes! Thanks for making this issue. I noticed this also the other day. This is very strange indeed. It should actually be the optimizer_idx and not the dataloader idx.

**Comment by awaelchli** [comment]
I believe we should remove it

**Comment by carmocca** [comment]
Context: https://github.com/PyTorchLightning/pytorch-lightning/pull/8911
