### ISSUE TITLE
Expose strict argument to model loading in trainer.tune

### ISSUE THREAD

**Issue by ranran9991** [PyTorchLightning/pytorch-lightning#9798]
## 🚀 Feature

Recently, the strict argument was added to model checkpointing (in [here](https://github.com/PyTorchLightning/pytorch-lightning/issues/2629)).

Using a trainer with` auto_lr_find=True `and calling `trainer.tune` still loads a save of the model, without the option of a `strict ` argument.

My use case is pretty complicated and involves Hyper Networks,  but I'm running into an error which this feature will fix
"Unexpected key(s) in state_dict:" 

Ideally, It would look like this
`trainer.tune(model, train_loader, val_loader, strict_loading=False)`

**Comment by awaelchli** [comment]
Thanks for the feature request. Such an addition to the tune() method would also have to generalize to the other Trainer methods that load a checkpiont, i.e., `Trainer.test()` and `Trainer.validate()` and after #9693, #9405 also `Trainer.fit()`.
