### ISSUE TITLE
Warnings and import errors when generating docs

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#980]
## 🐛 Bug

There are many warnings when generating the docs, many are import failures.
Because of them, the Trainer docs disappeared, see here: https://pytorch-lightning.readthedocs.io/en/latest/trainer.html

### To Reproduce

1. cd docs
2. make clean
3. make html

```
WARNING: autodoc: failed to import module 'pl_examples'; the following exception was raised:
Traceback (most recent call last):
  File "d:\anaconda3\envs\lightning\lib\site-packages\sphinx\ext\autodoc\importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "d:\anaconda3\envs\lightning\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\aeduw\Documents\Repositories\pytorch-lightning\pl_examples\__init__.py", line 143, in <module>
    from .basic_examples.lightning_module_template import LightningTemplateModel
  File "C:\Users\aeduw\Documents\Repositories\pytorch-lightning\pl_examples\basic_examples\lightning_module_template.py", line 21, in <module>
    class LightningTemplateModel(pl.LightningModule):
AttributeError: module 'pytorch_lightning' has no attribute 'LightningModule'
```

### Expected behavior

no import errors.

### Environment

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 442.19
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] pytorch-lightning==0.6.1.dev0
[pip] torch==1.4.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py37hb782905_0  
[conda] mkl_fft                   1.0.15           py37h14836fe_0  
[conda] mkl_random                1.1.0            py37h675688f_0  
[conda] pytorch                   1.4.0           py3.7_cuda101_cudnn7_0    pytorch
[conda] pytorch-lightning         0.6.1.dev0                dev_0    <develop>

**Comment by awaelchli** [comment]
@Borda Thanks for the PR but the import errors are still there. For some reason the docs don't like the PL examples.
We have this import

```
import pytorch_lightning as pl
class LightningTemplateModel(pl.LightningModule):
...
```

in the examples. I tried converting the relative imports to regular ones, but couldn't fix the issue.

**Comment by awaelchli** [comment]
However, if I change
```
import pytorch_lightning as pl
class LightningTemplateModel(pl.LightningModule):
...
```
to this
```
import pytorch_lightning as pl
class LightningTemplateModel(pl.core.lightning.LightningModule):
...
```
the error disappears. (it is the same for the other examples)

**Comment by Borda** [comment]
Well, it looks strange, for me it passed, but I will check it again...
What you say is that the particular imports in `__init__` doesn't work properly...
Have you tried to install the package and then run `make html`?

**Comment by Borda** [comment]
Well, it looks strange, for me it passed, but I will check it again...
What you say is that the particular imports in `__init__` doesn't work properly...
Have you tried to install the package and then run `make html`?

**Comment by awaelchli** [comment]
You are right, I had to reinstall the package. 
Example code was running fine before so it never made me think to reinstall. Strange ...
