### ISSUE TITLE
Horovod MisconfigurationException

### ISSUE THREAD

**Issue by twsl** [PyTorchLightning/pytorch-lightning#9801]
## 🐛 Bug

It is possible to start training with PL on horovod without horovodrun.

E.g. Databricks has it's own proprietary [HorovodRunner](https://github.com/databricks/spark-deep-learning), which allows starting distributed training from interactive environments by wrapping a method.
If this method includes the initialization of the trainer, I can bypass the `MisconfigurationException`, but if I want to initialize to trainer upfront, I do get said exception [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/connectors/accelerator_connector.py#L844).

One solution to my problem could be to include the enum [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/utilities/enums.py#L87).
An other solution could be to check, if the interactive environment is a databricks notebook using the `DATABRICKS_RUNTIME_VERSION` env var.

### To Reproduce
Additions to BoringModel on Databricks:
```
def train_horovod():
  
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        num_sanity_val_steps=0,
        max_epochs=400,
        gpus=1,
        weights_summary=None,
        accelerator='horovod'
    )
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
```

Create the runner and run
```
from sparkdl import HorovodRunner
hr = HorovodRunner(np=8, driver_log_verbosity="all")
hr.run(train_horovod)
```

If you move the trainer initialization outside of the `train_horovod`, you get the exception

### Expected behavior

Trainer initialization without errors.

### Environment

- PyTorch Lightning Version (e.g., 1.3.0):
- PyTorch Version (e.g., 1.8)
- Python version:
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

Happy to provide the PR once we figured out how to solve this.

**Comment by awaelchli** [comment]
> If you move the trainer initialization outside of the train_horovod, you get the exception

But I would very much expect so. Doesn't this line of code spawn eight processes? 

> hr = HorovodRunner(np=8, driver_log_verbosity="all")
> hr.run(train_horovod)

Then certainly the Trainer instantiation needs to be done inside that function because that's a separate process then.
Is there something blocking you from initializing the trainer inside that function? The trainer needs to be aware of the environment and the commands above are providing that with different environment variables (I imagine so).

**Comment by twsl** [comment]
Yes, this spawns 8 processes.
I was just confused by the naming of the `is_interactive_compatible` method.
As far as I understand the different environment is not required for proper initialization.
Having the trainer object on the driver would allow e.g. proper plotting of the tune lr curve inside the interactive environment.
But it's probably the easiest way to just keep it the way it is to avoid confusion with the horovodrun commandline option.
