### ISSUE TITLE
Can we resume model training from the epoch it got interrupted?

### ISSUE THREAD

**Issue by pratikchhapolika** [PyTorchLightning/pytorch-lightning#9834]
I am using Jupyter Lab to run. It has pre-installed `tf2.3_py3.6` kernel installed in it. It has 2 GPUS in it.

PyTorch Lightning Version (e.g., 1.3.0): **'1.4.6'**
PyTorch Version (e.g., 1.8): **'1.6.0+cu101'**
Python version: **3.6**
OS (e.g., Linux): system=**'Linux'**
CUDA/cuDNN version: **11.2**
How you installed PyTorch (conda, pip, source): **pip**

Here is the screenshot of my model and it got interrupted  due to connection issue.  

`I am saving the best model in checkpoint.`

<img width="1024" alt="Screenshot 2021-10-06 at 9 40 21 AM" src="https://user-images.githubusercontent.com/11159549/136163032-235ae52d-48a3-48ae-99e1-14a9d239a23a.png">

**I couldn't find a way to resume training from the pint it stopped.**

Any help would be appreciated.

**Comment by tchaton** [comment]
Hey @pratikchhapolika,

You can use `Trainer(resume_from_checkpoint=X)` to keep training for the latest checkpoint.

PyTorch Lightning master also contains a mechanism for fault tolerance training which can be activated as follow `PL_FAULT_TOLERANT_TRAINING=1 python script.py`.

This is still experimental and should be used with care. Learn more about it there: https://pytorch-lightning.readthedocs.io/en/latest/advanced/fault_tolerant_training.html?highlight=fault%20tolerant%20training

Best,
T.C

**Comment by pratikchhapolika** [comment]
> resume_from_checkpoint=X

Thank you.

IN the  `resume_from_checkpoint=X` we have to pass the path?

**Comment by awaelchli** [comment]
If you want to resume from a particular checkpoint, you have to pass in the path. 
If there was a failure and Lightning auto-saved a checkpoint, there should be a file ".pl_auto_save.ckpt" in the current working directory. On current master, Lightning will detect this file and load it automatically when running the script again.
