### ISSUE TITLE
Does Pytorch lightning allows to share the best model .ckpt file without sharing any other details?

### ISSUE THREAD

**Issue by pratikchhapolika** [PyTorchLightning/pytorch-lightning#9838]
I am using Jupyter Lab to run. It has pre-installed tf2.3_py3.6 kernel installed in it. It has 2 GPUS in it.

PyTorch Lightning Version (e.g., 1.3.0): '1.4.6'
PyTorch Version (e.g., 1.8): '1.6.0+cu101'
Python version: 3.6
OS (e.g., Linux): system='Linux'
CUDA/cuDNN version: 11.2
How you installed PyTorch (conda, pip, source): pip

I am saving the best model in checkpoint.
Model trained: `Distilber-base-uncased`

`I want to use this model in different machine to do inferencing`

**How can I load this model using pytorch lightning?**

When I tried this?

```
load_model = torch.load('best-checkpoint.ckpt')
trained_model.eval()
trained_model.freeze()
```

**I get error.**

**I know in the document it says like this:**

```
trained_model = SRTagger.load_from_checkpoint('best-checkpoint.ckpt',n_classes=len(LABEL_COLUMNS))
trained_model.eval()
trained_model.freeze()
```

`But the problem here is I have to pass the entire **`SRTagger`** class also in inferencing machine. `

Is there better way to load model ?

**Comment by Programmer-RD-AI** [comment]
hi, you can get the `state_dict()` of the model and then `model.load_state_dict(torch.load('./state_dict.ckpt'))` you can try this can you give me a update thanks

**Comment by rohitgr7** [comment]
`.ckpt` just stores the weights and not the architecture. I'd suggest using torchscript/onnx runtime.
Ref doc: https://pytorch-lightning.readthedocs.io/en/latest/common/production_inference.html
