### ISSUE TITLE
dpp training stuck ( lightning=1.4.9 )

### ISSUE THREAD

**Issue by yinrong** [PyTorchLightning/pytorch-lightning#9851]
I'm stuck using lightning=1.4.9
the numbers "96% 4260/4435" keeps the same forever.  
![image](https://user-images.githubusercontent.com/4221569/136338235-06d0c777-868c-46a3-9212-acd4fcd3e275.png)

**Comment by tchaton** [comment]
Dear @yinrong,

Would it be possible for you to provide a reproducible script, possibly with the BoringModel ?

Best,
T.C

**Comment by yinrong** [comment]
@tchaton could you continue to work on this issue?

**Comment by tchaton** [comment]
Hey @yinrong,

Could you make sure you have the same number of batches for all ranks.

It will hang if there is an uneven number of batches

Best,
T.C

**Comment by awaelchli** [comment]
To expand on @tchaton answer: When you randomly select your dataset, make sure each process chooses the same one. You  can set the seed to make sure of this:

```py
from pytorch_lightning import seed_everything
seed_everything(1)
```
