### ISSUE TITLE
max_steps < train_batches doesn't run validaiton loop at the end of epoch

### ISSUE THREAD

**Issue by rohitgr7** [PyTorchLightning/pytorch-lightning#9855]
## 🐛 Bug

There is something possible wrong when setting max_steps. Not sure if it's the intended behavior.

### To Reproduce

<details><summary>CODE</summary>
<p>

```py
import os

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.batch_size = 32
        self.total_len = 2000
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss*12}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)
        
    def train_dataloader(self):
         return DataLoader(RandomDataset(32, self.total_len), batch_size=self.batch_size)
    
    def val_dataloader(self):
        return DataLoader(RandomDataset(32, self.total_len), batch_size=self.batch_size)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=1e-2)
```

</p>
</details>

Doesn't run the validation loop at the end of epoch. Should it run?
```py
model = BoringModel()
trainer = Trainer(max_epochs=10, logger=False, num_sanity_val_steps=0, max_steps=2)
trainer.fit(model)
```

runs total steps = max_epochs. is it the intended behavior??
```py
model = BoringModel()
trainer = Trainer(max_epochs=10, logger=False, num_sanity_val_steps=0, max_steps=-1)
trainer.fit(model)
```

### Environment

- PyTorch Lightning Version (e.g., 1.3.0): master
- PyTorch Version (e.g., 1.8): 1.9
- Python version: 3.9
- OS (e.g., Linux): macos
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source): conda
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

**Comment by awaelchli** [comment]
For the first question:

> Doesn't run the validation loop at the end of epoch. Should it run?

The end of epoch was not reached, so we don't run validation. It's expected.

2nd example with max_steps=-1:

> runs total steps = max_epochs. is it the intended behavior??

It's expected to stop at max_epochs=10. Setting a `max_*` argument to -1 simply turns that limit off. Other limits will apply.
Related PR: #9460

**Comment by rohitgr7** [comment]
Thanks @awaelchli 
> Setting a max_* argument to -1 simply turns that limit off.

that means should the following run for total 10 steps or 10*12 or 0??
```py
trainer = Trainer(max_epochs=10, logger=False, num_sanity_val_steps=0, max_steps=-1, limit_train_batches=12)
```
currently, it seems to run 0 steps on the master

**Comment by awaelchli** [comment]
After #9460, it should run for 10 epochs, since the `max_steps=-1` means the `max_steps` limit gets turned off. On master this runs 0 steps because -1 is not considered a special value yet.
