### ISSUE TITLE
PL_FAULT_TOLERANT_TRAINING=1 causes TypeError

### ISSUE THREAD

**Issue by p1x31** [PyTorchLightning/pytorch-lightning#9858]
## 🐛 Bug

After running training with PL_FAULT_TOLERANT_TRAINING=1 I've got this error, everything works as intended without it
```
    modality: self.encoders[modality](batch[modality])
TypeError: list indices must be integers or slices, not str
```
### To Reproduce
breaking code:
```python
class I2T(pl.LightningModule):
    def __init__(self, config: DictConfig):
        super().__init__()
        self.save_hyperparameters(config)
        self.modalities = ('text', 'image')
        self.encoders = nn.ModuleDict({
            modality: instantiate(self.hparams.model.get(modality))
            for modality in self.modalities
        })
        # hard-coded ntxent loss for simplicity
        self.loss = nn.CrossEntropyLoss()

    def forward(self, batch: Dict) -> Dict:
        return {
            modality: self.encoders[modality](batch[modality])
            for modality in self.modalities
        }
```
full file: https://github.com/yandex/mlcup/blob/main/cv/baseline/i2t/system.py#L35

### Expected behaviour

Starts to train
### Environment

* CUDA:
	- GPU:
		- GeForce RTX 2080 Ti
	- available:         True
	- version:           11.1
* Packages:
	- numpy:             1.19.1
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.1+cu111
	- pytorch-lightning: 1.4.9
	- tqdm:              4.48.2
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.8.5

**Comment by ikergarcia1996** [comment]
Same here @awaelchli 
`
    def training_step(self, batch, batch_idx):
        x, y = batch["images"], batch["y"]
`

Causes 
`
TypeError: list indices must be integers or slices, not str. 
`

It works without the fault-tolerant flag. 

RTX3090
PyTorch 1.10.0
PyTorch Lightning 1.4.9
