### ISSUE TITLE
Warning recommend `save_top_k=None` but it crash training

### ISSUE THREAD

**Issue by tarepan** [PyTorchLightning/pytorch-lightning#9868]
## 🐛 Bug
Warning on `ModelCheckpoint` recommend `save_top_k=None` arguments, but it crash training.  

### To Reproduce
[Colab Notebook](https://colab.research.google.com/drive/1M3TIL1GqgJtz_gkYgIf797M6dG23NHu-?usp=sharing)  

Core part is   

```python
ckpt_callback = pl.callbacks.ModelCheckpoint(save_last=True, save_top_k=0)
# Output warning during `Trainer.fit`:
#   > ModelCheckpoint(save_last=True, save_top_k=None, monitor=None) is a redundant configuration.
#   > You can save the last checkpoint with ModelCheckpoint(save_top_k=None, monitor=None).    

...

ckpt_callback = pl.callbacks.ModelCheckpoint(save_top_k=None, monitor=None)
# Output error during `Trainer.fit`:
#   > TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

### Expected behavior
`ModelCheckpoint(save_top_k=None, monitor=None)` is recommended by the warning.  
So this argument work properly, so training success and generate `last.ckpt` checkpoint file.  

### Environment

```
* CUDA:
	- GPU:
	- available:         False
	- version:           11.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.0+cu111
	- pytorch-lightning: 1.4.9
	- tqdm:              4.62.3
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.12
	- version:           #1 SMP Sat Jun 5 09:50:34 PDT 2021
```

**Comment by rohitgr7** [comment]
the warning itself seems redundant. save_top_k should be an int always and it will save last checkpoint in case of `monitor=None and save_top_k=-1|0|1` given that you set `save_last=True`. If monitor is None, for the save_top_k we already have checks, so I don't think we need this one. but need to confirm

cc @carmocca @awaelchli

**Comment by carmocca** [comment]
@Programmer-RD-AI The fix is not correct - we want to actually remove the warning, these lines:

https://github.com/PyTorchLightning/pytorch-lightning/blob/5206e52786917b3c87cb012933bd138615d8543d/pytorch_lightning/callbacks/model_checkpoint.py#L430-L434

Also, https://github.com/PyTorchLightning/pytorch-lightning/blob/5206e52786917b3c87cb012933bd138615d8543d/pytorch_lightning/callbacks/model_checkpoint.py#L150 should not mention the `None` option.

**Comment by Programmer-RD-AI** [comment]
ok

**Comment by Programmer-RD-AI** [comment]
hi I changed the code can you it please.
Thank you.

https://github.com/PyTorchLightning/pytorch-lightning/pull/9875

Regards
