### ISSUE TITLE
Allennlp Support

### ISSUE THREAD

**Issue by mikerossgithub** [PyTorchLightning/pytorch-lightning#987]
I'm looking at supporting AllenNlp/Lightning integration. Work has started over here:
https://github.com/allenai/allennlp/pull/3860

Also discussed in this repo here: #807 

This issue is to consolidate some lightning-related issues in this effort

**Comment by mikerossgithub** [comment]
I am trying to figure out which hooks to use in lightning for one-time serialization at the beginning of training. Specifically, my example is for a `Vocabulary` which is determined by both the model and the training data.

A `Vocabulary` maps words or tokens to indices. Sometimes it is initialized from the model, sometimes from the training data, and sometimes from a combination of both. In AllenNlp, for instance, a vocabulary may be loaded from a pre-trained model, then expanded by traversing the dataset (to find new words which haven't been seen before). The vocabulary is then saved into the serialization directory, once (before training begins). It is required to use the model on new data, so it needs to be saved alongside the checkpoints.

To implement this in PytorchLightning, we need serialization that:
* happens once (before training), only on the master node (e.g. in a distributed setting)
* happens after having already loaded the model and the training data set (and traversing the training dataset once).

What hooks would I use to do this?

**Comment by mikerossgithub** [comment]
A second question I have is where the best place is to add MomentumSchedulers. AllenNlp has support for both LearningRateSchedulers and MomentumSchedulers. In PytorchLightning, there is already support for LearningRateSchedulers in the return values for `LightningModule.configure_optimizers()` so conceptually it feels like MomentumSchedulers should be in the same place as LearningRateSchedulers, but I don't want to modify the underlying return type of configure_optimizers.

**Comment by williamFalcon** [comment]
hey! this  is aweome. Happy to support the  other schedulers.
I can take a look at this more carefully in a few days once we get this release out.

In the  meantime, check out or new docs!
https://pytorch-lightning.readthedocs.io/en/latest/

This might be  useful:
https://pytorch-lightning.readthedocs.io/en/latest/callbacks.html

Or prepare_data() here:
https://pytorch-lightning.readthedocs.io/en/latest/lightning-module.html

**Comment by mikerossgithub** [comment]
Thanks, `prepare_data()` is what I was missing, as was looking in `core.hooks` -- `lightning_module_template` is helpful!

**Comment by williamFalcon** [comment]
@mikerossgithub how's this going? any help you need from us?

**Comment by mikerossgithub** [comment]
@williamFalcon - I've submitted a working AllenNlp module here:
https://github.com/PyTorchLightning/pytorch-lightning/pull/1993
It needs some work, but should useable.

**Comment by Borda** [comment]
pls your thought @PyTorchLightning/core-contributors

**Comment by edenlightning** [comment]
Closing this issue, as this will be done in Bolts: https://github.com/PyTorchLightning/pytorch-lightning-bolts/issues/128.
