### ISSUE TITLE
WandBlogger doesn't log when working with TPU cores

### ISSUE THREAD

**Issue by rusty-electron** [PyTorchLightning/pytorch-lightning#9876]
## 🐛 Bug

I am trying to run a resnet200d model for document classification on Kaggle TPUs using python-lightning. I have set up WandB logger and connected it to my wandb account. The training starts well but at 50 steps the logger complains that It can't log as the process was called from a different pid. See error image below:

![wandb_issue](https://user-images.githubusercontent.com/22986666/136651234-fbcb7de9-feaa-4218-a036-1aa1a51f7c4a.png)

I have tried to use options like `sync_dist=True` or `rank_zero_only=True` (in the self.log calls) but it still doesn't work.

### To Reproduce

You can try running the mentioned kaggle notebook:
https://www.kaggle.com/rustyelectron/documentclassification-pytorch-tpu-wandb/

Wait till about 50 steps to get the error.

### Expected behavior

The wandblogger should work normally and log data.

### Environment

* CUDA:
	- GPU:
	- available:         False
	- version:           None
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0a0+7e71a98
	- pytorch-lightning: 1.2.10
	- tqdm:              4.62.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
	- processor:         x86_64
	- python:            3.7.10

### Additional context

None

cc @kaushikb11 @awaelchli @morganmcg1 @AyushExel @borisdayma @scottire

**Comment by Programmer-RD-AI** [comment]
hi,

Can you check these issues?

https://forums.pytorchlightning.ai/t/tpu-failures-in-colab/310
https://github.com/wandb/client/issues/1994
https://github.com/PyTorchLightning/pytorch-lightning/issues/1062
https://discuss.huggingface.co/t/logging-experiment-tracking-with-w-b/498
https://wandb.ai/site/articles/pytorch-lightning-with-weights-biases
https://wandb.ai/cayush/pytorchlightning/reports/Use-Pytorch-Lightning-with-Weights-Biases--Vmlldzo2NjQ1Mw

Regards,

**Comment by rusty-electron** [comment]
@Programmer-RD-AI sorry, 🤦 its public now. Ok, I will take a look at the links you provided.

**Comment by Programmer-RD-AI** [comment]
It ok check the links and see if they solve the issue

Regards

**Comment by borisdayma** [comment]
This should now be fixed.
Could you update Pytorch Lightning from master branch and install the most recent version of wandb?

```bash
pip install --upgrade wandb
pip install --upgrade git+https://github.com/PytorchLightning/pytorch-lightning.git
```
