### ISSUE TITLE
Single-process multi-node CPU training

### ISSUE THREAD

**Issue by borchero** [PyTorchLightning/pytorch-lightning#9877]
## 🚀 Feature

Allow setting `DistributedType.DDP` for `DistributedType.DDP_CPU` to run in the main process when running distributed CPU training.

### Motivation

Whenever a model is small, it is not necessarily useful to use a GPU. However, one might still benefit from distributing computations for model training across nodes -- especially when you consider that containers are also "nodes".

Currently, this has the drawback that even when one process per node is used, a process is spawned instead of using the main process, breaking plenty of functionality.

### Pitch

There is already an open PR (#9603), this was opened after the PR.

### Alternatives

---

### Additional context

---

**Comment by awaelchli** [comment]
Good observation. Let's special case this!
