### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'precision'

### ISSUE THREAD

**Issue by LuposX** [PyTorchLightning/pytorch-lightning#991]
## 🐛 Bug

I followed the guide to "use 16bit precision" from the [documentation](https://pytorch-lightning.readthedocs.io/en/latest/apex.html)

But when I do:
```
trainer = Trainer(amp_level='O1', precision=16, gpus=1)
trainer.fit(model)
```

I get the error message:
`TypeError: __init__() got an unexpected keyword argument 'precision'`

I am using lightning version: 0.6.0

**Comment by williamFalcon** [comment]
use master

**Comment by BradWyble** [comment]
Hi William, 

I am experiencing the same issue.  I upgraded to master and the issue was not resolved.

**Comment by Borda** [comment]
@BradWyble pls double check that you using master, e.g install from github 
```bash
pip install https://github.com/PyTorchLightning/pytorch-lightning/archive/master.zip
```
https://github.com/PyTorchLightning/pytorch-lightning/blob/bcb45d906d5f378a30461d513728cad34fc647ce/pytorch_lightning/trainer/trainer.py#L108
