### ISSUE TITLE
Simplification: Merge load_from_metrics and load_from_checkpoint 

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#994]
## 🚀 Feature

The two ways of loading a LightningModule from checkpoint only differ in one  argument, the tags_csv. 

### Motivation

The code is almost identical for both and the purpose is the same. If we merge these two into one function, it would simplify the API.

### Pitch

Combine
`load_from_metrics(cls, weights_path, tags_csv, map_location=None)` and 
`load_from_checkpoint(cls, checkpoint_path, map_location=None)` into a single signature:

```
load_from_checkpoint(cls, checkpoint_path, tags_csv=None, map_location=None)
```
and make load_from_metrics deprecated.

### Alternatives

keep as is, not a big deal :)

**Comment by williamFalcon** [comment]
let’s do it!

**Comment by Borda** [comment]
@awaelchli I agree, just which method shall be the remaining one?
 `load_from_metrics` or `load_from_checkpoint` :]

**Comment by awaelchli** [comment]
Probably load_from_checkpoint as it used more often :) I already made PR :)
