### ISSUE TITLE
AttributeError: 'int' object has no attribute 'log_hyperparams'

### ISSUE THREAD

**Issue by prdai** [PyTorchLightning/pytorch-lightning#9942]
## 🐛 Bug

GPU available: True, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_76476/2376091482.py in <module>
      2 model = Model()
      3 trainer = Trainer(125)
----> 4 trainer.fit(model)
      5 wandb.finish()

~/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloaders, val_dataloaders, datamodule, train_dataloader)
    550         self.checkpoint_connector.resume_start()
    551 
--> 552         self._run(model)
    553 
    554         assert self.state.stopped

~/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _run(self, model)
    914 
    915         # plugin will setup fitting (e.g. ddp will launch child processes)
--> 916         self._pre_dispatch()
    917 
    918         # restore optimizers, etc.

~/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _pre_dispatch(self)
    943     def _pre_dispatch(self):
    944         self.accelerator.pre_dispatch(self)
--> 945         self._log_hyperparams()
    946 
    947     def _log_hyperparams(self):

~/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _log_hyperparams(self)
    970 
    971             if hparams_initial is not None:
--> 972                 self.logger.log_hyperparams(hparams_initial)
    973             self.logger.log_graph(self.lightning_module)
    974             self.logger.save()

AttributeError: 'int' object has no attribute 'log_hyperparams'

### To Reproduce

https://github.com/Programmer-RD-AI/Intel-Image-Classification-Learning-PyTorch-Lightning/blob/main/00.ipynb

### Expected behavior

to fit the model

### Environment

* CUDA:
	- GPU:
		- GeForce RTX 3060
	- available:         True
	- version:           11.1
* Packages:
	- numpy:             1.20.3
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.1+cu111
	- pytorch-lightning: 1.4.9
	- tqdm:              4.62.2
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.11
	- version:           20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021

### Additional context

I am new to PyTorch lightning.

If this is a bug of PyTorch Lightning I would love to fix it.

With best regards,
Ranuga

**Comment by rohitgr7** [comment]
```py
2 model = Model()
3 trainer = Trainer(125)
```
here. the first argument of the trainer is logger which can't be an int.

**Comment by mjurej** [comment]
GPU available: True (cuda), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/home/aul/anaconda3/envs/pl/lib/python3.7/site-packages/pytorch_lightning/trainer/setup.py:178: PossibleUserWarning: GPU available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='gpu', devices=2)`.
  category=PossibleUserWarning,
Running in `fast_dev_run` mode: will run the requested loop using 1 batch(es). Logging and checkpointing is suppressed.

  | Name     | Type           | Params
--------------------------------------------
0 | resnet   | ResNet         | 21.3 M
1 | accuracy | BinaryAccuracy | 0     
--------------------------------------------
21.3 M    Trainable params
0         Non-trainable params
21.3 M    Total params
85.177    Total estimated model params size (MB)
Traceback (most recent call last):
  File "train.py", line 25, in <module>
    main()
  File "train.py", line 22, in main
    trainer.fit(resnet_choco, datamodule=dm)
  File "/home/aul/anaconda3/envs/pl/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 604, in fit
    self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/home/aul/anaconda3/envs/pl/lib/python3.7/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/aul/anaconda3/envs/pl/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 645, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/aul/anaconda3/envs/pl/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1086, in _run
    self._log_hyperparams()
  File "/home/aul/anaconda3/envs/pl/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1126, in _log_hyperparams
    datamodule_log_hyperparams = self.datamodule._log_hyperparams if self.datamodule is not None else False
AttributeError: 'ChocoDataModule' object has no attribute '_log_hyperparams'

**Comment by CheaSim** [comment]
> GPU available: True (cuda), used: False TPU available: False, using: 0 TPU cores IPU available: False, using: 0 IPUs HPU available: False, using: 0 HPUs /home/aul/anaconda3/envs/pl/lib/python3.7/site-packages/pytorch_lightning/trainer/setup.py:178: PossibleUserWarning: GPU available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='gpu', devices=2)`. category=PossibleUserWarning, Running in `fast_dev_run` mode: will run the requested loop using 1 batch(es). Logging and checkpointing is suppressed.
> 
> ## | Name | Type | Params
> ## 0 | resnet | ResNet | 21.3 M
> 1 | accuracy | BinaryAccuracy | 0
> 21.3 M Trainable params 0 Non-trainable params 21.3 M Total params 85.177 Total estimated model params size (MB) Traceback (most recent call last): File "train.py", line 25, in main() File "train.py", line 22, in main trainer.fit(resnet_choco, datamodule=dm) File "/home/aul/anaconda3/envs/pl/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 604, in fit self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path File "/home/aul/anaconda3/envs/pl/lib/python3.7/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt return trainer_fn(*args, **kwargs) File "/home/aul/anaconda3/envs/pl/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 645, in _fit_impl self._run(model, ckpt_path=self.ckpt_path) File "/home/aul/anaconda3/envs/pl/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1086, in _run self._log_hyperparams() File "/home/aul/anaconda3/envs/pl/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1126, in _log_hyperparams datamodule_log_hyperparams = self.datamodule._log_hyperparams if self.datamodule is not None else False AttributeError: 'ChocoDataModule' object has no attribute '_log_hyperparams'

You can add  `self.save_hyperparameters()` in the `ChocoDataModule` to solve this issue.
