### ISSUE TITLE
NLP Help Funcs

### ISSUE THREAD

**Issue by Programmer-RD-AI** [PyTorchLightning/pytorch-lightning#9946]
## 🚀 Feature

NLP Help Funcs,
for example
`Tokenizing`
`Bag of words`
and loading the data
and other techniques of NLP I think this would be useful.

### Motivation

I do NLP project a lot and I have found that I need to create custom functions for tokenizing and creating the data.
Example Notebook : https://github.com/Programmer-RD-AI/kickstarter-NLP-V4/blob/main/00.ipynb

### Pitch

to create a new section of pytorch lightning called NLP
which has everything needed for doing NLP projects in PyTorch Lightning

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

With best regards,
Ranuga

**Comment by carmocca** [comment]
Hi!

Unfortunately, we are not interested in these domain-specific contributions at this point. However, you might find other projects such as https://github.com/pytorch/text more interesting. There are also many OSS projects focusing on NLP helper functions.

Thank you for your suggestion.
