### ISSUE TITLE
reverse callback order in exiting event

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#9950]
## 🚀 Feature

At this moment  we are calling a callback in the same order everywhere, which may be a bit contra intuitive for users assuming a custom wrapper is doing some pseudo wrapper

### Motivation

For example `on_epoch_start` is the entering and `on_epoch_end` is paired exiting event...
- `on_epoch_start`: A -> B -> C
- `on_epoch_end`: C -> B -> A

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

cc @borda @tchaton @justusschock @awaelchli @ananthsub @daniellepintz

**Comment by awaelchli** [comment]
I think what @Borda is trying to say is that the order is currently

```
callback0.on_epoch_start
callback1.on_epoch_start
callback2.on_epoch_start

callback0.on_epoch_end
callback1.on_epoch_end
callback2.on_epoch_end
```

@Borda is suggesting to change to:

```
callback0.on_epoch_start
callback1.on_epoch_start
callback2.on_epoch_start

callback2.on_epoch_end  (reverse order)
callback1.on_epoch_end
callback0.on_epoch_end
```

What is the motivation behind this? Do you have a specific use case?

**Comment by Rajathbharadwaj** [comment]
Hey, I'm interested in working on this. Any pointers would be helpful.
