### ISSUE TITLE
remove configuring_optimizers function

### ISSUE THREAD

**Issue by Programmer-RD-AI** [PyTorchLightning/pytorch-lightning#9973]
## 🚀 Feature

remove configuring_optimizers function

### Motivation

I am was doing a lot of projects with PyTorch Lightning so I can understand what else to add.

### Pitch

I want to know why cant we remove `configuring_optimizers` in a `pl.LightningModule`
Becuase I think if the person using can just 
in
`def __init__()`
to just add
`self.optimizer = Adam(self.parameters(),lr=0.001)`
would it not be easier for a new person who is learning PyTorch Lightning? 

### Alternatives

None

### Additional context

None
______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

With best regards,
Ranuga

**Comment by rohitgr7** [comment]
2 use-cases:
1. some schedulers need total training steps and that might not be available during init.
2. we can initiate some modules in `setup`, so the optimizer can't be initialized during init.

That's why `configure_optimizers` seems reasonable.

**Comment by Programmer-RD-AI** [comment]
ok,

With best regards,
Ranuga
