### ISSUE TITLE
Drop Python 3.6 support

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning#9981]
### Motivation
- Python 3.6 EOL on `2021-12-23`: https://devguide.python.org/#branchstatus
- Some major ml libraries have already dropped Python 3.6 support.
  - numpy 1.20.0: https://numpy.org/devdocs/release/1.20.0-notes.html
  - scikit-learn 1.0: https://github.com/scikit-learn/scikit-learn/issues/20084
  - PyTorch 1.11: https://github.com/pytorch/pytorch/issues/66462
    > 1.10.X should be the last official PyTorch release to support Python 3.6

### Pitch
- [ ] Remove all CI using Python 3.6

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by Rajathbharadwaj** [comment]
Hey, I wish to contribute to this if this isn't assigned. Any steps on how I can get started?

**Comment by akihironitta** [comment]
@Rajathbharadwaj Hi, thanks for having an interest in contributing! This issue has already been addressed partially in #10269, and there is nothing to do at the moment until Python 3.6 EOL planned on `2021-12-23`.

**Comment by function2-llx** [comment]
Does the Python version badge need an update too?
![image](https://user-images.githubusercontent.com/38486514/156103692-9de60eb9-311d-408f-87b1-789e8fd2838a.png)

**Comment by carmocca** [comment]
Yes. Would you be interested in fixing the badge?

**Comment by function2-llx** [comment]
@carmocca After some investigation, I find it unnecessary to do some fix on this. The badge in the Readme refers to the one generated by PyPI based on contents written in `setup.py`. Currently, it generates the badge from tag 1.5.10, on which Python 3.6 is not dropped. It will update automatically in the next release.

`setup.py` on tag 1.5.10:
https://github.com/PyTorchLightning/pytorch-lightning/blob/9ebdc52ec631df92ca7cfc1ba852801dd36d3864/setup.py#L108-L112

`setup.py` on current master branch:
https://github.com/PyTorchLightning/pytorch-lightning/blob/f3c2a1338c08e0ab47cf9ca97de54e59e5f3a31c/setup.py#L105-L108

**Comment by carmocca** [comment]
Good to know! Thank you for your time!
