### ISSUE TITLE
Allow and expose resetting optimizers

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#9982]
## 🚀 Feature

was thinking if we have a simple way how to reset optimizers, while I have finetuning and need to add extra parameters for training/learning

### Motivation

yes... have trainer method `reset_optimizors`  which would ask the model for actual optimizers and schedulers

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

cc @borda

**Comment by tchaton** [comment]
Sounds like an interesting idea. Would you mind giving a bit more context, what would be the alternatives?

**Comment by carmocca** [comment]
Also the difference to `accelerator.setup_optimizers(trainer)`
