### ISSUE TITLE
Remove validation completely when overfit_batches > 0

### ISSUE THREAD

**Issue by rohitgr7** [PyTorchLightning/pytorch-lightning#9989]
## Proposed refactoring or deprecation

<details><summary>CODE</summary>
<p>

```py
import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch['a']).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        breakpoint()
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)

if __name__ == '__main__':
    train_data = {'a': DataLoader(RandomDataset(32, 64), batch_size=2), 'b': DataLoader(RandomDataset(32, 64), batch_size=2)}
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)


    model = BoringModel()
    trainer = Trainer(
        gpus=None,
        max_epochs=2,
        num_sanity_val_steps=0,
        overfit_batches=2
    )
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
```

</p>
</details>

I think we should just turn of validation when `overfit_batches > 0` instead of silently replacing the `val_dataloaders` with `train_dataloader` here:
https://github.com/PyTorchLightning/pytorch-lightning/blob/8c76cf5ae1db078dcd201b08de788ac6769c894d/pytorch_lightning/trainer/data_loading.py#L414-L416

### Motivation

There is a possibility that the structure of data returned by train dataloader might not be compatible with `validation_step` (check example above) and thus will lead to errors. To make it compatible, users might have to update their `validation_step` code just for `overfit_batches > 0`, which I guess isn't a good user-exp and also leads to errors. Overfit_batches is just used for quick debugging and checking model adaptability with the train dataset.

Also the above code leads to error even before `validation_step` is called since train_dataloaders are not handled the right way.

### Pitch

Turn off validation completely by setting `limit_val_batches=0` during init if `overfit_batches > 0`.

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

cc @justusschock @awaelchli @akihironitta

**Comment by popfido** [comment]
If this decision is about to do under the agreement of developing team, I'd like to directly fix my PR to your Suggestion LOL.

**Comment by tchaton** [comment]
Hey @rohitgr7 @kingyiusuen,

From what I heard, I believe there is 2 option right now.

1. 😋 Disable validation completely when overfit_batches > 0

2. 🚀 Don't replace the val_dataloaders and use only `overfit_batches` val batches to perform the evaluation.

**Comment by rohitgr7** [comment]
@popfido interested in updating your PR? we can go with disabling the validation completely in case of overfit_batches

**Comment by popfido** [comment]
> @popfido interested in updating your PR? we can go with disabling the validation completely in case of overfit_batches

Got it @rohitgr7
